### ISSUE TITLE
Derived title IDs visualization

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#100]
Derived title IDs do not get identified/visualized?

**Comment by eu-genia** [comment]
I guess I am being confused, I believed if in the work records there are text parts with a `@corresp`, when I list derived IDs in a MS description I should see the actual works, not the derived IDs, but here
https://betamasaheft.eu/manuscripts/ESum039/main
I am not seeing that.
Is there an error in my encoding of either ESum039 or LIT1047Aksumi? Thanks, @PietroLiuzzo

**Comment by eu-genia** [comment]
(before replacing all IDs in the MS record I thought I'd better ask)

**Comment by PietroLiuzzo** [comment]
I do not think reopening an issue without discussion from 2016 is a good practice. I am moving this to a new issue
