### ISSUE TITLE
syriaca comment in clavis

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1002]
in LIT3611Miracle, there is in the clavis bibliography:
```xml
  <bibl type="Poncelet"><!--<ptr target="bm:syriaca"/>-->
                  <citedRange unit="item">4</citedRange>
               </bibl>
```
The poncelet number refers, I suppose, to this item: http://csm.mml.ox.ac.uk/index.php?p=pon_view&rec=9, but I cannot find any related work on syriaca. Did I miss it or is there some copy paste error here? Do you maybe remember something about this, @MassimoVilla ? Thank you!

**Comment by MassimoVilla** [comment]
I am quite sure I have not added that information. The whole "Miracles of Mary" cycle was meant to receive a further and systematic full description/revision at a later stage, and I have not added any reference from other traditions.

**Comment by thea-m** [comment]
Ok, thanks a lot!

**Comment by thea-m** [comment]
@DenisNosnitsin1970 did you work on this record? I'm quite sure I didn't add this either...

**Comment by DenisNosnitsin1970** [comment]
No, I haven't add this.

**Comment by thea-m** [comment]
thank you! So no syriaca and KRZ were involved?

**Comment by PietroLiuzzo** [comment]
No, I tried to explain what happened in the comments to the commit with the changes.
