### ISSUE TITLE
Ascension of Isaiah text

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1006]
Is the text given in LIT1671Isaiah the same as https://m.tau.ac.il/~hacohen/AscJes/AscJesp%201.html? I am a little bit confused only because of the added chapter indications ("ክፍል ፡ ፩ ።"), which are not present in the edition. And I assume that they only had chapters 1-5 copied, not the entire text?

**Comment by PietroLiuzzo** [comment]
I do not know if the word file sent in 2017 is derived from the images you link to

**Comment by PietroLiuzzo** [comment]
Could @sologebre or @DariaElagina check this, please?

**Comment by sologebre** [comment]
I checked it out. Yes, LIT1671Isaiah refers to the linked text. As Dorothea said earlier, it is a little confusing in the numbering. In the edition, the section is presented with the Roman number, but in the uploaded text, referred as ክፍል ፡ ፩….., I do not really the sources for it. But as far as we depend on the edition, we keep what has been said in the edition. We have discussed it with Peitro and then deleted ክፍል ፡ ፩ ።, ክፍል ፡ ፪ ።, ክፍል ፡ ፫ ።, ክፍል ፡ ፬ ።, ክፍል ፡ ፭ ። that are not part of the edited text.
