### ISSUE TITLE
visualization of bibliography in physical description 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1011]
for example in http://betamasaheft.eu/manuscripts/BDLbruce93/main:
The rubric "Secondary Bibliography" in the visualization of the `<listBibl type="secondary">`s in `<physDesc>` (in this case, `<foliation>` and `<binding>`) is printed in a way which can mislead users to take it as the bibliography for the entire record, not this particular element. Would it be possible to print it in a smaller font or indented in a way that shows clearly to which item it belongs (only the title, not the references themselves)?

**Comment by PietroLiuzzo** [comment]
What about removing those headers there?
See screenshot, I have also removed the dots in favour of a cleaner indentation
![schermata 2018-12-05 alle 06 46 18](https://user-images.githubusercontent.com/508012/49492684-9297cd80-f859-11e8-8acc-fb1b5efc18f1.png)

**Comment by PietroLiuzzo** [comment]
btw: why three times the same book instead of several `<citedRange>` ?

**Comment by thea-m** [comment]
thank you, much better! and yes, you're right
