### ISSUE TITLE
spelling of Beta maṣāḥəft in <publisher> in new records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1013]
In records created through the app, Beta maṣāḥəft is spelled beta maṣāḥəft in the `<publisher>` element, in the other records it's correctly Beta maṣāḥəft (I don't remember, maybe it was already once corrected everywhere)

**Comment by PietroLiuzzo** [comment]
The commit fixes the small b in the script. I am now going to fix the data

**Comment by PietroLiuzzo** [comment]
This has been updated in all repositories, BUT, to avoid killing the application by sending for transformation to RDF with the hook more then 8000 files, I have turned off for persons and manuscript the hook when doing the commit. So, these files will be updated from the repository only with the new release, but do not worry, the big B is there in the data.

**Comment by thea-m** [comment]
It's still beta maṣāḥǝft in new work records...not sure whether it was meant to be already corrected or will be fixed in the new release

**Comment by PietroLiuzzo** [comment]
Please see above. I should have added release with code freeze. Sorry
