### ISSUE TITLE
catalogue view small error?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1016]
not very major, but in the catalogue view http://betamasaheft.eu/catalogues/list, it seems like before d'Abbadies catalogue, there is an empty line to which 3 manuscripts belong. Presumably we did something wrong in the data

**Comment by PietroLiuzzo** [comment]
these three record http://betamasaheft.eu/catalogues/EMML11/list
point to a phantom catalogue in the Ethio studies Group library which should have tag bm:EMML11

**Comment by thea-m** [comment]
As far as I know, this catalogue is not published, so I cannot create the corresponding zotero entry

**Comment by PietroLiuzzo** [comment]
I am going to comment out the information
