### ISSUE TITLE
typo guidelines

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1018]
In the very welcoming welcome message here:
http://betamasaheft.eu/Guidelines/
"Schema" is once written with a capital and a few words later not, and "practitiones" should be practitioners. 
Thank you!
(Sorry if I could have edited it, I didn't find this page)

**Comment by thea-m** [comment]
Thank you! I'm sorry, I just saw it now: mainteined should be maintained...

**Comment by PietroLiuzzo** [comment]
thank you, I fixed that as well, this is not a page in the data, is hard coded as back up if nothing else is selected
