### ISSUE TITLE
entry in institution equal to places

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1024]
@PietroLiuzzo , I believe the new entry INS0521BetaMadhaneAlem is a doublet for LOC1888BetaMa, INS0523BetaMarqoreos is the same as LOC1889BetaMa

**Comment by PietroLiuzzo** [comment]
feel free to correct the data making sure that links to ids are preserved in all cases. It was not possible to identify those with certainty when we created the entry.

**Comment by eu-genia** [comment]
also INS0520BetaEmmanuel already exists in places as LOC1877BetaAm
INS0519Beta_Libanos is LOC1876BetaAb
INS0518MotaGiorgis is LOC4876MotaGi
