### ISSUE TITLE
rendering of marked up place and person names 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1025]
It seems to me that there are some issues in the rendering of marked up place/person names on the app. Are place names supposed to link to Dillmann and not the respective place record?
 In any case, in some cases in the chronicle of Bakaffa, marked up place and person names don't link anywhere and also seem to hinder the linking of the words following them to Dillmann (In Paragraph 16 of LIT4633Chronicle, I cannot click on ጐንደር, which is marked up, nor on the icon next to it or the following words until ወአንገሥዎ; In paragraph 18 I cannot click on the words following ዳሞት until በቃለ, including the name of Bakaffa.)
(Maybe here the app also shows an older version of the text? It has ወበሳኒታ፡ ሳርባኵሳ። at the beginning of this paragraph while the XML record has `ወበሳኒታ፡ኀደረ፡ <placeName ref="LOC5576Sarbak">ሳርባኵሳ።</placeName>`)

**Comment by PietroLiuzzo** [comment]
#1042 should help in this, as it allows you to hide or show those arrows. I also fixed the issue which you pointed at, now the marked entities link to the place/person/work and also the link format is fixed.

**Comment by PietroLiuzzo** [comment]
the lack of functionality of the hands and arrows in the text view is recorded in another issue #988
