### ISSUE TITLE
transliteration bəʾsi

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1026]
We have mainly bəʾəsi/t until now (there are not many occurences), but it should probably be bəʾsi/t, following Bulakh's proposition?

**Comment by abausi** [comment]
In this case we have even more evidence: the Greek rendering of this epithet on coins is "BISI" and this points to a possible pronunciation "bəʾsi" rather than "bəʾəsi". So, I would be in favour of "bəʾsi"

**Comment by thea-m** [comment]
Perfect, I've added it to this list (commit still to be reviewed, so not yet updated online):
http://betamasaheft.eu/Guidelines/?id=dubious-spelling

**Comment by thea-m** [comment]
should "bǝʾǝsǝya" in the record RIE187 also be changed?

**Comment by thea-m** [comment]
thank you!
