### ISSUE TITLE
Markup places

### ISSUE THREAD

**Issue by sologebre** [BetaMasaheft/Documentation#1034]
In markup of the places in the Chronicle of Galāwdewos for the following paragraph 

```xml
ወእምዝ፡2 ዓደወ፡ 
<persName ref="PRS4428Galawdew"><roleName 
type="title">ማር፡</roleName> ገላውዴዎስ፡ </persName>ማዕዶተ፡ 
<placeName ref="LOC6850Takkaze" 
notBefore="1540" notAfter="1541"> </placeName> 
<placeName ref="LOC1022Abbay" notBefore="1540" notAfter="1541">ክልኤቱ፡ አፍላግ፡</placeName>መንገለ፡ ምድረ፡ <placeName ref="LOC5597Sawa" notBefore="1540" notAfter="1541">ሼዋ፡</placeName>a3 እመንገለ፡4 ምድረ፡5 <placeName ref="LOC6569Tegray" notBefore="1540" notAfter="1541">ትግራይ፡</placeName>
```
There are two problems that I have noticed here.
One, in the normal encoding system when I marked `<placeName ref="LOC6850Takkaze" notBefore="1540" notAfter="1541"/>`  the name Takazze  appears in visualization which  is actually not part of the text. But when I marked it `<placeName ref="LOC6850Takkaze" notBefore="1540" notAfter="1541"> </placeName>` it is corrected. So, how can we be consistent for these kinds of cases in the future?
Secondly, I want to mark up here in the text ክልኤቱ፡ አፍላግ፡ referring the two rivers (Takazze and Abay). So in this case, is there a possibility to use two ids for one element?

**Comment by PietroLiuzzo** [comment]
Thank you very much, I will fix this as soon as possible

**Comment by eu-genia** [comment]
The first case - actually this was the desired behaviour, we said originally we do not want to have to retype the word, so it is very often that we use a closed tag and the name is expected to be printed. Automatically removing the automatic printing is dangerous, as there are now hundreds of records using this feature. Maybe inserting the blank is the better workaround.

**Comment by PietroLiuzzo** [comment]
This is however wrong it the place is marked up in the text, be reassured that the feature will remain everywhere, but here in the text edition, we should really not print a name, neither force the encoder to add a white space.

**Comment by sologebre** [comment]
Thank you, now it is fixed!

**Comment by thea-m** [comment]
Was there an answer to the second question? It is not yet clear to me.

> Secondly, I want to mark up here in the text ክልኤቱ፡ አፍላግ፡ referring the two rivers (Takazze and Abay). So in this case, is there a possibility to use two ids for one element?

**Comment by PietroLiuzzo** [comment]
Sorry, I did not document the answer to this. No, there isn't now. You can encode with `<certainty/>` alternative values. http://betamasaheft.eu/Guidelines/?q=certainty&id=certainty 
an example of this for places can be seen here http://betamasaheft.eu/works/LIT5019MonumentumAdulitanum2.xml 
But this is not the case, here there are two places, i.e. two rivers, it is no alternative identification. we need thus two annotations, and the empty `<placeName>` serves well in that

**Comment by thea-m** [comment]
Thank you!
