### ISSUE TITLE
group the results by type

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1035]
@eu-genia asked to clearly distinguish results by type.
Here is my first go at it
![schermata 2019-01-15 alle 16 13 22](https://user-images.githubusercontent.com/508012/51189518-83884e80-18e0-11e9-9cae-7cbb52133855.png)

**Comment by PietroLiuzzo** [comment]
This is live now for you to test

**Comment by eu-genia** [comment]
the uppercase reload worked :)

**Comment by PietroLiuzzo** [comment]
prima, then it was just the cache. let me know about the colours then, if they are ok, simply close the issue.

**Comment by eu-genia** [comment]
sorry, one thing, is it possible for longer lists to keep them within one box, now that each box is scrollable? check out the mss box for e.g. http://betamasaheft.eu/search.html?query=dammo

**Comment by eu-genia** [comment]
i was wondering whether now that each box has its own scrolling one can remove the limit - i do find that pages 2 and 3 look funny, with empty and partial boxes.

**Comment by PietroLiuzzo** [comment]
what you propose would be fine for a limited number of results as in your examples. but you will want pagination if there are 600+ results for example. I can remove the boxes if they are empty in pagination, would that be fine?

**Comment by eu-genia** [comment]
i assume the pagination inside the boxes is not possible? i do find this situation http://betamasaheft.eu/search.html?query=john confusing...

**Comment by PietroLiuzzo** [comment]
it is possible, sure, I can think of as many disadvanteges as there are now however and no real improvement, but that is not that important. what would others like to have in this context? @thea-m @DariaElagina @sologebre @DenisNosnitsin1970 ?

**Comment by DenisNosnitsin1970** [comment]
I personally do not find it confusing, as long as there is numeration in each of the boxes.

**Comment by thea-m** [comment]
for me, it would feel more intuitive to scroll down as much as possible within the single boxes (why not to 600) than to use the pagination, but then again, I might be a bit pagination blind (it took me a few months to discover the one in the guidelines search...).
Whichever solution is adopted, this grouping makes the search much more user friendly already and will prove to be very helpful

**Comment by PietroLiuzzo** [comment]
you can have 600 for each of 6 boxes... if you want to wait 6 minutes... :) 
btw, you can set the pagination interval by adding a parameter per-page different from 20. for example http://betamasaheft.eu/search.html?query=john&per-page=5
perhaps it would be enough to make this visible as it is in the list views, so that you can change and set it to 600 if you are going to make coffee while you wait? 
I can still additionally remove the boxes when they are empty in the pagination.

**Comment by eu-genia** [comment]
what are the disadvantages of pagination within a box? it makes the loading quicker than scrolling and still you can move within one category until the end. now if there are many long lists, like in the example above, to go down in a specific category one has to move to the next page for all. like @thea-m says, i am not sure a new user will understand immediately how to get to numbers 21-40 in a box, especially if it is neither at top or bottom (like works here) - the list simply seems truncated

**Comment by PietroLiuzzo** [comment]
you have asked for a page with several boxes grouping the results, this meant already an increase in the loading time, which you might have noticed, as a first. The pagination in the boxes would mean up to twelve of this on the result page view.
<img width="554" alt="schermata 2019-01-17 alle 12 44 34" src="https://user-images.githubusercontent.com/508012/51316685-ae47e380-1a55-11e9-8085-dfe86e3e7bc5.png">
which might create confusion beside being even more 'art brut' than it already is now, especially in the advanced search, as compared to this larger view for the simple search. Since the same effect is produced by the single pagination bar, I really struggle to see the reason for multipling these bars and I do not see how a user would be helped by having to chose among 12 of such bars instead of having one simple one doing one simple thing for all. 
btw, in what way would that make the loading quicker I do not understand, the page will be reloading every time in any case, to move on to the second page for all or just for one group. And some users clicking on the bar in the box will have the expectation that it moves all and I will get exactly the opposite request from yours now. On the immediateness of the user understanding we could spend months... how to compute it? @DenisNosnitsin1970 above proves that this is not as general as you think. I would like to propose that
- [ ] removing the boxes if empty
- [ ] making the number of items per page option evident to allow the user to change the setting
- [ ] perhaps adding beside the total and the numbering of the item, the information about which ones are in the box
- [ ] perhaps increasing the pagination bar size in proportion to the results
- [ ] perhaps increasing the maximum size of the box to fit all the results (avoid scrolling in the box) 
would already be a satisfactory list of improvements. Please @DariaElagina and @sologebre, do have your say in this. if a majority of you does really want to have all these pagination bars, I will enter that business.

**Comment by DariaElagina** [comment]
The way it is now is a little bit confusing, but I managed to find everything I looked for :). If other options would take much more time to load the search results, I would rather avoid them. Actually, it is rather seldom that I search in more than two categories at the same time. So, it is fine with me the way it is.
