### ISSUE TITLE
Bibliography inside a personne file 

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/Documentation#1043]
It is possible and pertinent to add the bibliography of a scholar in his or her personal file ? 
For instance, i am encoding Deborah Lifchitz's file (PRS6310) and wondering if and how I could add her articles and books. 
Using a `<listBibl>` would be enough ?

**Comment by PietroLiuzzo** [comment]
If it is marked as scholar we already have in the scholars view a link to a search in the bibliography, like this: https://www.zotero.org/groups/358366/ethiostudies/items/q/Lifchitz
However, given that in the person record we would collect bibliographical references **about** the entry, or relevant to it, I think you could simply add a link, to this or a better list of her publications, using a simple `<ref>`.
