### ISSUE TITLE
Binding description: keywords for turn-ins and cover 

### ISSUE THREAD

**Issue by ElianaDalSasso** [BetaMasaheft/Documentation#1048]
As pointed out in a discussion with @DenisNosnitsin1970 it would be useful to add keywords to describe:

- a cover that covers only the spine and the back edge of the boards --> proposed keyword: quarter cover. As it is in  [http://www.ligatus.org.uk/lob/concept/1530](url).

- different types of turn-ins corner --> proposed keywords: mitred corner, open mitred corner, stitched corner, tongued corner, overlapping corner foredge over, overlapping corner head/tail over. Combining what is in Szirmay (Index p. 347),  in the descriptions of Ethio-Spare and in Ligatus>features>cover features>turn-ins.

I also suggest a keyword to encode the presence of a secondary cover, mainly a textile over-cover --> proposed keyword: chemise . As it is in http://www.ligatus.org.uk/lob/concept/1252.

And then update the related part in the guidelines.

What do you think?

**Comment by PietroLiuzzo** [comment]
sure, add those keywords following the existing guidelines as soon as a need for that arises in the encoding. once you have updated authority files, taxonomy and the schema ODD I will updated the RNG.

**Comment by ElianaDalSasso** [comment]
@PietroLiuzzo ok!
@DenisNosnitsin1970 you are right it is widely used to describe the secondary cover of romanesque binding. But it just came in my mind that there are cases in which the textile over cover protects the nude boards, so there is no primary cover. Similar cases are recorded by Pollard and Vezin and summarized in Szirmay  (p. 165 fig. 8.21a). Szirmay speaks indistinctly of chemises and over-cover. 
We can use over-cover but I would avoid to define it as a secondary cover. Another option could be dust wrapper but personally I don't like the term.

**Comment by DenisNosnitsin1970** [comment]
Eliana, I think over-cover is appropriate.

**Comment by DenisNosnitsin1970** [comment]
Eliana, 
do we stop at "over-cover" (and close the issue)?
Regards - DN

**Comment by ElianaDalSasso** [comment]
Sorry for the late answer. Yes, for me it's ok, I added the keyword for over-cover and for the turn-ins  but they don't appear in the list of the keywords for bindings. @PietroLiuzzo did I forget a step?
Thank you

**Comment by PietroLiuzzo** [comment]
added also to taxonomy and schema
