### ISSUE TITLE
image viewer BnF?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1052]
There seems to be a problem with the image viewer, for example http://betamasaheft.eu/manuscripts/BNFet102/viewer
If I click on "Objekt hinzufügen", I see the small images of the manuscript, but upon clicking on one of them, nothing opens

**Comment by PietroLiuzzo** [comment]
This is a known issue with the BnF images, it has been like that since there is the viewer and there is no fix for the moment.

**Comment by thea-m** [comment]
Would it then be possible to instead of linking to the viewer link to Gallica (as for the manuscripts without iiif)? Otherwise the user experience is a bit frustrating.

**Comment by PietroLiuzzo** [comment]
I will try to contact again the people there to see if there is a fix

**Comment by thea-m** [comment]
thank you!

**Comment by PietroLiuzzo** [comment]
this is now not visible at all any more, not even in openseadragon

**Comment by thea-m** [comment]
It is really a pity, especially as the BnF has recently added a very large number of "new" manuscripts (well, the microfilm scans, but still!) and now the majority manuscripts of Zotenberg's catalogue are online. If we encoded the link to the images additionally in `<facsimile>`, would this be visualised as "link to images" as in the British Library manuscripts? Retrieving the link now from the bottom of the not working viewer page is not very user friendly.
(What is good is that somehow the litttle preview image is still displayed in lists so that we can still quickly see which manuscripts have images!)

**Comment by PietroLiuzzo** [comment]
yes, you can add the link to their viewer in facsimile and eventually have both, the potentially working mirador and the link to their viewer

**Comment by PietroLiuzzo** [comment]
do not replace the idno in facs, and keep adding that, which is the how of somehow the tumbnail and openseadragon views work

**Comment by thea-m** [comment]
thank you!

**Comment by PietroLiuzzo** [comment]
the viewer is now working for all instances, also bnf.
turns out, I could have fixed this long ago, I took the wrong path of investigation...

**Comment by PietroLiuzzo** [comment]
downloaded and built with npm https://github.com/ProjectMirador/mirador/releases/tag/v2.7.0 and replaced the files in the app with those in the build directory

**Comment by thea-m** [comment]
Great!
