### ISSUE TITLE
unused person relations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1053]
Because the list of relations has grown quite long, I have commented out in the schema the relations for persons that until now were not used at all. Please revert this if you think it was a bad idea.
(and, out of curiosity: there are many relations listed two or three times in the list in the schema, such as snap:kinOf. Is there a reason for that or did it happen accidentally?)

**Comment by PietroLiuzzo** [comment]
as you might remember, in order to be able to transform the ODD to the correct RNG with links you need a modified version of the TEI XSLT doing the transform in oXygen for you. The many options available are there to cover for all those things people might want to put in, even if they were never used. So, I wonder if it is actually worth changing this, since it is a change in the Schema relevant to everyone I think it needs to be discussed (the previous changes I made to the schema were bug fixes or content unrelated changes)

**Comment by thea-m** [comment]
An in order to discuss it I opened this issue. The relations in question ("UncleOfSeriousIntimateRelationshipWith", "Hal") were in a large part clearly imported from elsewhere and not been created out of our project's needs, which is of course fine, and if anyone will need them in the future, they could very easily reinclude them. I find that the list has become very annoying when I scroll through it in the content completion in order to add a relation, but if everyone else is happy, let's keep it.

**Comment by thea-m** [comment]
the relations in question were:

bm:sisterInLawOf
bm:daugtherInLawOf
bm:hasBaptized
snap:SlaveOf
snap:SiblingOfParentOf
snap:UncleOfSeriousIntimateRelationshipWith
snap:SlaveOf
snap:SeriousIntimateRelationshipWith
snap:PaternalFamilyRelationship
snap:ParentOf
snap:MaternalFamilyRelationship
snap:HouseSlaveOf
snap:HereditaryFamilyOf
snap:HalfFamilyRelationship
snap:GreatGrandmotherOf
snap:GrandparentOf
snap:FreedmanOf
snap:FosterFamilyRelationship
snap:ExtendedHouseholdOf
snap:HouseSlaveOf
snap:HereditaryFamilyOf
snap:HalfFamilyRelationship
snap:GreatGrandparentOf
snap:FreedwomanOf
snap:FreedSlaveOf
snap:FreedmanOf
snap:ExtendedFamilyOf
snap:AuntOf
snap:ChildOfSiblingOf
snap:CasualIntimateRelationshipWith
snap:ChildOf
bm:brotherInLawOf

**Comment by thea-m** [comment]
Not sure on the new issue policy here @PietroLiuzzo . I have nothing to add, but woudn't decide this by myself.
@sologebre @DenisNosnitsin1970 @DariaElagina

**Comment by PietroLiuzzo** [comment]
nothing new about the issue policy, you only look after this problem and ping the interested people until you can reach an agreement for the solution or simply go ahead with what your judgement tells you is the best.

**Comment by thea-m** [comment]
I will leave them commented out, since no one seems to have needed any of them in the last year. They can always be reintroduced.
