### ISSUE TITLE
error in TEI with links XSLT transformation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1055]
there is a problem with this page, I cannot see the reason in the record:
http://betamasaheft.eu/tei/PRS8464samraKr.xml

**Comment by PietroLiuzzo** [comment]
thanks for point this out, the TEI with links is to be updated indeed . if you want to see the xml, please use .xml only, without /tei/

**Comment by PietroLiuzzo** [comment]
it looks like the main blocker here is a problem in the way the tei for the bibliography is obtained, i.e. with a call to the zotero api. 
https://api.zotero.org/groups/358366/items?tag=bm:1941GrondijsCrucifixion&format=tei

I have emailed zotero-dev google group about this to see if they know the reason.

**Comment by PietroLiuzzo** [comment]
#1033
