### ISSUE TITLE
<collation> in composite manuscripts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1056]
Sorry if this was discussed already, but I found nothing here or in the guidelines. Where should the quire structure of composite manuscripts be encoded? The relevant quires in their respective msParts (let's assume a new msPart coincides with a new quire :) ), or in one single `<collation>` in the first `<physDesc>` which relates to the entire manuscript (that's what I did)? Both have been used. What do you think?

**Comment by PietroLiuzzo** [comment]
My feeling is that it depends. In some cases the collation would be the one of the entire mss, in others the one of the parts. I would not want to have this regulated in the guidelines, the existing rules seem to be enough for our use cases until now .

**Comment by thea-m** [comment]
I agree it makes sense like this. Maybe i can state just this in the guidelines.

**Comment by PietroLiuzzo** [comment]
I would think is one of those cases where too much guidance does not help, but if you want to add a line and a link to some examples that clarify some possible cases when one might decide in one or the other way, we could then check how it goes.

**Comment by DariaElagina** [comment]
I think it would be better to add this information to the guidelines

**Comment by thea-m** [comment]
added to guidelines
