### ISSUE TITLE
encoding of more than one support material

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1057]
I would like to describe a manuscript made of several kinds of paper. Where can I encode this? I improvised this:
  ```xml
 <support>
                           <material key="paper" xml:id="m1">
                              <locus from="i" to="2"/>
                              <locus from="17" to="31"/>
                              <note>Thickish, whitish paper.</note>
                           </material>
                           <material key="paper" xml:id="m2">
                              <locus from="3" to="6"/>
                              <locus from="13" to="16"/>
                              <note>Creme coloured, thinner paper.</note>
                           </material>
 </support>
```

but am happy for another solution.

**Comment by PietroLiuzzo** [comment]
I do not think I have enough information to help you sorry. is this made of several types of paper in one go, lets generically say "mixed", or is it made of parts each of one material? the encoding you have come up with is reasonable, but let me think that perhaps those groups of folios might be parts?

**Comment by thea-m** [comment]
I think "mixed" fits here (I was also wondering whether they are parts, but the paper discontinuities are not concomitant with discontinuities of quires/hands/content, and it seems that the manuscript was produced in one act of production)

**Comment by PietroLiuzzo** [comment]
Then I believe it is fine like you have done.
