### ISSUE TITLE
Encoding of Mazmura Dǝngǝl

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1058]
Dear all,
it seems that the description of Mazmura Dǝngǝl (LIT3985Mazmura) should be adjusted. The Psalter should be included into the work description as a citation. Till now there are two main strategies of describing manuscripts containing Mazmura Dǝngǝl. One has either done it in a descriptive manner, or one has given the same locus for two different ms_items. In fact, the Psalter is a part of Mazmura Dǝngǝl. If you agree with this solution, I would adjust the description of Mazmura Dǝngǝl and correct the existing descriptions.

**Comment by thea-m** [comment]
Sure, go ahead!

**Comment by eu-genia** [comment]
thank you!

**Comment by eu-genia** [comment]
As I started in #1149: I believe we need a separate ID for Mazmura Dengel and one combined ID for the Psalter combination.

**Comment by DariaElagina** [comment]
I think we might have just one ID for  Mazmura Dengel, combined with Psalter with the whole structure, as they always occur together. Different variations might be encoded then as well.

**Comment by DariaElagina** [comment]
After returning to Hamburg, I will take care of that issue.

**Comment by eu-genia** [comment]
to complicate the issue
See e.g. 
- ESamm011 where psalms of the Virgin are added to Psalms **+ Canticles + Song**
- ESktm010 and ESky030 (description not yet adjusted) that have the following metadata provided "Ps. 1 is **preceded** by a few lines from the Mazmura dǝngǝl “Psalter of the Virgin”: ነዓ፡ ኀቤየ፡ ንጉሠ፡ እስራኤል። በዓለ፡ መዝሙር፡ ሠናይ፡ ወጥዑመ፡ ቃል።"

**Comment by thea-m** [comment]
@DariaElagina I believe that you continued your work on the encoding of Mazmura Dǝngǝl? It is not clear to me whether the current LIT3985Mazmura record reflects the most up to date decisions. (There is no change element by you, and I don't remember at all whether I did the textpart encoding - but I don't think so?) Could you maybe update this issue?

**Comment by thea-m** [comment]
@DariaElagina ?

**Comment by DariaElagina** [comment]
No, it is not up to date. The encoding of the textpart of it is still on my list.

**Comment by thea-m** [comment]
Perfect. I was just asking because I have some Mazmura Dengel manuscripts to encode. Then I will wait until there is an example to follow.

**Comment by thea-m** [comment]
@DariaElagina please close when you think the work on this is done
