### ISSUE TITLE
referring to team members/editors in other elements

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1061]
I have just come across a case I am not sure how to correct or where to look up (must be me being slow...): 
LIT1295Dersan
has this note attached to a relation:
`<desc>This homily is attributed in  <bibl>
                              <ptr target="bm:Lusini2005EAEDersanaM"/>
                           </bibl> 
                           to <persName ref="PRS10390Yohanne"/>, but according to <persName ref="DN"/>, the manuscripts' usual formulation
                           is <q xml:lang="gez">baʾǝnta Yoḥannǝs</q>, making thus authorship not entirely clear. The homily is about <persName ref="PRS5720JohnChr"/>.</desc>` 

naturally, the reference to Denis `<persName ref="DN"/>` goes against the schema as it is, as it is not a pers type record - do we need to create a pers type records for the persons quoted or is there another work around to fix the record? (of course if one refers to a written source it is easier, one can use a bibl element, but here it seems more generic)

**Comment by PietroLiuzzo** [comment]
no, this is just an error in the way I formulated the schematron rule when I updated it to check the refs in persName. the way that is encoded is fine.

**Comment by PietroLiuzzo** [comment]
btw : I have fixe the way in which `q` was rendered, so that it is not anymore a paragraph...
