### ISSUE TITLE
Laurenziana images

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1067]
The images from Laurenziana need 
 - [x] to be converted to pyramidal TIFF
 - [x] eventually to be renumbered (better not!)
 - [x] be moved to the TIFF collection on the images disk
 
The 
- [x] iiif.xql and 
- [x] viewer.xql
scripts might need adjustment and update especially for rights and attribution of the images.

**Comment by PietroLiuzzo** [comment]
@abausi @antobrita who and how should be credited for these images ?

**Comment by PietroLiuzzo** [comment]
an issue with iipimage server makes it crash on load of some of the images from this dataset. The issue has been reported and is beeing evaluated by Ruven Pillay

**Comment by abausi** [comment]
Dear Pietro,

many thanks: I hope this can be solved.

Il 25.02.2019 15:51, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
for sure, they have always been very responsive and I have no doubt that they will point me to a nice fix.

**Comment by PietroLiuzzo** [comment]
- [ ] rendering in the sequence as text for the decoration and additions of the content of desc using string:tei2string()
- [ ] Wrong sequence 005 in facs should bring to https://betamasaheft.eu/iiif/Laurenziana/BML_001/BML_001-005.tif/full/full/0/default.jpg correctly, not to 2. there must be some accounting in iiif.xql based on ES

**Comment by PietroLiuzzo** [comment]
- [ ] also the openseadragon viewer does not yet work for these manuscripts

**Comment by PietroLiuzzo** [comment]
Ruven Pillay solved the issue on iipimage server, which prompted also an update to the latest version of this on our server. now the images work all properly.
