### ISSUE TITLE
Christ and the 12 Apostles

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1071]
Dear Jacopo,

I have this drawing here
https://betamasaheft.eu/iiif/Laurenziana/BML_001/BML_001-087.tif/full/full/0/default.jpg
and Marrassini says Cristo e i 12 Apostoli
should I make an AT or use something like e.g.
`<persName ref="PRS5684JesusCh"></persName> <ref type="authFile" corresp="AT1047Apostles"/>` 
?

**Comment by Gnisci** [comment]
Dear Pietro,

Thank you for your query and for drawing my attention to this. Since the image is placed after the Crucifixion, I think it must be the  Teaching or "Synaxis of the Twelve Apostles". Christ does appear in some icons that feature this subject.

**Comment by PietroLiuzzo** [comment]
should I than make an AT Synaxis of the Twelve Apostles?

**Comment by Gnisci** [comment]
Most certainly! It's an unusual subject for Ethiopian art!

**Comment by PietroLiuzzo** [comment]
Thanks!
