### ISSUE TITLE
add secondary bibliographic reference that has not been used as a source for the record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1073]
Does it make sense to add a general secondary reference to a manuscript record, even if it has not been used as a source for the record? It could not be in `<source>`.
(I was reading something on BLorient481 and thought it would be useful for readers of the record to have the article listed in the bibliography, but I didn't work on this record and it wouldn't make sense for me now to incorporate the information.)
What do you think @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
Adding a bibliographical reference is always good IMHO. you should be able to use your listBibl elsewhere than in source. You can also point to another manuscript record or section of another manuscript record with a simple `ref`

**Comment by sologebre** [comment]
test for Dorothea!

**Comment by thea-m** [comment]
thank you @sologebre !

**Comment by thea-m** [comment]
and thank you @PietroLiuzzo ! In this case, I'm not really sure where to add the reference - it gives some background information on the manuscript's history, on some content items and physical characteristics but no particular place in the record comes to mind to me naturally. Do you have maybe a suggestion for a place for a general reference?

**Comment by PietroLiuzzo** [comment]
into additional, after the adminInfo, where there is currently the wrong listBibl type edition? that could/should become your secondary bibliography and you could add the reference there.

**Comment by thea-m** [comment]
Perfect! Should I add something to the guidelines or don't we want to discourage people from finding a more precise place for inserting their references?

**Comment by PietroLiuzzo** [comment]
I would be in favour of the second.

**Comment by thea-m** [comment]
Thank you!
