### ISSUE TITLE
repository records for private collections

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1077]
Just to make what has already been practiced explicit - we do create repository records for the private collections of individuals who own manuscripts? Can INS0368atohayle and AHB001gondar be followed as an example?
@PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
yes. although we have not used these in the corresponding manuscripts, we have quite a number of private collections in institutions, from the recent update to the institutions list from the list of EMIP/EMML
https://betamasaheft.eu/institutions/list?placetype=privateHouse

**Comment by thea-m** [comment]
thank you!
