### ISSUE TITLE
angel art theme

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1081]
Would a drawing of "An angel holding a sword and scabbard", which occurs sometimes in scrolls, be an art theme? Or would it be simply AT1082Angel specified by using keywords in the description?

**Comment by Gnisci** [comment]
Hello Thea, unless there are more elements in the image which allow it to be associated to a literary source/sources, such as a miracle, I would just label it as an angel. What do you think?

**Comment by Gnisci** [comment]
This was closed, but I think the issue has not been solved, as I was suggesting, for consistency, I would just use the art theme angel: https://betamasaheft.eu/authority-files/list?keyword=AT1082Angel.

**Comment by PietroLiuzzo** [comment]
since @thea-m asked and you answered I think it is closed... what else would need doing?

**Comment by Gnisci** [comment]
I don't know, Thea never got back to me, so I assume this issue is not closed for her

**Comment by thea-m** [comment]
Sorry for the delay! Some kind of acknowledgement from the one asking the question would always be appropriate, ahem. 
I was wondering how to make this decision visible in the guidelines, because for me the question of when to create an AT ID is not trivial (and not only for me, as we know from BM history). But probably opening (and closing...) a quick issue when it arrises is the best way forward. 
Thank you!
