### ISSUE TITLE
links from Geez words

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1087]
During the TraCEs meeting yesterday, it was suggested to give visibility in BM to the morphological annotations made by TraCES. I proposed that the current link from any single Geez word in BM to a fuzzy search in the online Dillmann is altered to provide this.
This means that instead of linking directly
- a _double click_ on the word will call the parser via alpheios (embedded) and thus return possible results, including TraCES annotations with the links to the Dillmann
- a _single click_ will open a popup or a modal with some options:
     - if the word is a person name, title, date, place name, it will give the link to the relavant record
     - if the word is a place name it will give the link to related places in palagios (which will load in there, instead of opening a new popup)
     - the link to the fuzzy search in Dillmann
     - the link to a simple search of that word
     - the link to the advanced search for that word
     - the link to a query in the morphoparser
     - the link to a corpus search in morphoparser (thus listing all annotations of that exact word)
     - if the word has any annotation from TraCEs, then it will display the annotations for that word
 
@abausi @eu-genia @DenisNosnitsin1970 @thea-m @sologebre @DariaElagina @SusanneHummel @vitagrazia81 @MagdaKrzyz  what do you think?

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @thea-m @sologebre @DariaElagina @SusanneHummel @vitagrazia81 @MagdaKrzyz could you please simply drop an ok or no here, or briefly comment on the proposal above? thanks

**Comment by MagdaKrzyz** [comment]
Dear Pietro,

I agree with your proposal.
One remark: the existing links for cross-references should remain untouched. 
Best
Magda

**Comment by DariaElagina** [comment]
Dear Pietro,
I agree as well. 

Best,
D

**Comment by thea-m** [comment]
I have no opinion at all :)

**Comment by vitagrazia81** [comment]
Dear Pietro,
sorry if we reply only now. In theory it seems a good idea. Only a question: what does a simple search or advanced search give? which is the difference? Thank you

**Comment by PietroLiuzzo** [comment]
not much, I can omit the simple search link indeed

**Comment by SusanneHummel** [comment]
Dear Pietro,

as I am still in the process of understanding the parser and all the search functions, I - unfortunately - cannot give you a constructive feedback. At the first sight, it seems to me that there are too many options offered, thosr might confuse the user (at least me :)
Best
Susanne

**Comment by DenisNosnitsin1970** [comment]
Dear Pietro, 
does it mean that if the user does not need all this information, he will not receive it unless he clicks on the word (I mean, if the user searches for a manuscript/works, usually he does not expect/does not wich to find more than that)?

**Comment by PietroLiuzzo** [comment]
I have clearly managed to be extremely unclear!

This will only affect words in a page, like a text or a manuscript description, and only geez text which is not otherwise marked. no searching or search results are involved, no worries! The box will contain links to searches, so that you can click and go to a page which contains the results of that action without having to copy the text and paste it over, for example

**Comment by PietroLiuzzo** [comment]
The new generic behaviour has hovering on words offer a popup with four links to the traces annotations, the morpho parser, dillmann and a search in BM. on double click alpheios fires only for words in elements which have @xml:lang="gez". place, person and titles have normal link on single click and a left pointing hand and a arrow eventually for further popups with information from the RDF relations and from Pelagios

**Comment by MagdaKrzyz** [comment]
Impressive!
Alles unklar!


pt., 22 mar 2019 o 10:03 Pietro Liuzzo <notifications@github.com>
napisał(a):
