### ISSUE TITLE
works creation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1089]
Again
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<exception>
<script/>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>
exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 583, column 19]
</message>
</exception>
```
I think because I was inactive too long and got logged out, but I did log in again before creating the record! It is a bit annoying, can anything be done to stay logged in for at least a day or so?

**Comment by PietroLiuzzo** [comment]
no, we depend on this on an external module whose availability turns out to be shaky.

**Comment by thea-m** [comment]
:(

**Comment by thea-m** [comment]
after 20 or so minutes!

**Comment by PietroLiuzzo** [comment]
I understand your frustration, I wish I could do more right now to resolve this!
