### ISSUE TITLE
floruit

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1090]
leftover feedback from Paris: Do you still want to change the visualization of `<floruit>` to "Period of Activity"?

**Comment by sologebre** [comment]
Yes, it would be nice to change it.  The meaning of <floruit> in some cases refers to a date or period during which a person was known to have been alive and which can easily be understood from the person's date of birth and death. Thus, I think that the "Period of Activity" is clearer and more specific, referring only to people's active years. So it would be okay if we change it.

**Comment by thea-m** [comment]
it's now floruit again?

**Comment by thea-m** [comment]
https://betamasaheft.eu/persons/PRS5720JohnChr/main

**Comment by PietroLiuzzo** [comment]
yep, it was a regression, sorry.
