### ISSUE TITLE
add geez titles to miracles of mary

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1091]
from bm:TasfaGiyorgis1956Taammera
maybe leo could do this?

**Comment by PietroLiuzzo** [comment]
@LeonardBahr would you like/have time to go through this pubblication and edit the XML data in BM adding the geez titles?

**Comment by thea-m** [comment]
@LeonardBahr : When you will have a contract again, just noted it here as not to forget it. I have not yet added all references and created all records.

**Comment by thea-m** [comment]
and incipits from macomber?

**Comment by thea-m** [comment]
will be carried out by @AngelaMueller
