### ISSUE TITLE
epithet encoding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1097]
I once wrote this in a record, which I noticed now is not conform with the guidelines:
`<persName xml:lang="en" xml:id="n3" type="main">Cornelius <addName type="epithet">the Centurion</addName></persName>`
I don't remember whether it was discussed before I wrote it - can it stay like this or should it be corrected?
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
PRS11980Cornelius is valid... could you please point out what exactly is the inconsistency with the guidelines?

**Comment by thea-m** [comment]
The missing xml:id and encoding within another persName, not as a separate one
 
> Epithet
> Epithets should be recorded as `<addName type='epithet'>`↗ and should have their @xml:id with a chosen value. Assuming the @xml:id is in this case "SaviourOfTheWorld" ID to be copied there will be the like 'PRS5684JesusCh#SaviourOfTheWorld'
> 
> 
> ```
> <persName xml:lang="gez" xml:id="n1">ኢየሱስ፡ ክርስቶስ፡</persName>
> <persName xml:lang="gez" type="normalized" corresp="#n1">ʾIyasus Krǝstos</persName>
> <persName xml:lang="gez" type="alt" xml:id="n2">ክርስቶስ፡</persName>
> <persName xml:lang="gez" corresp="#n2">Krǝstos</persName>
> <persName xml:lang="gez" xml:id="MadhaneAlam"><addName type="epithet">መድኃኔ፡ ዓለም</addName> </persName>
> <persName xml:lang="gez" corresp="#MadhaneAlam">Madḫāne ʿĀlam</persName>
> ```
