### ISSUE TITLE
suggested citation etc. box in repository records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1098]
Is there a reason why the  "Suggested citatation", "Revisions", "Attribution" box is absent of the view of repository records (for example https://betamasaheft.eu/manuscripts/INS0339BML/list)? I think it would make sense to have it there, as everywhere else.

**Comment by PietroLiuzzo** [comment]
will add them with the specification that they refer only to the institution record, not to the list of manuscripts.
