### ISSUE TITLE
assigning an id to a narrative unit

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/Documentation#1100]
I cannot find in the guidelines how to assign an id to a narrative unit, for, as far as I understand, there is no list keeping trace of the references already assigns. 
So when I want to create a new one, which number should I use for a ref="NAR00XX" in the <title> ?

**Comment by PietroLiuzzo** [comment]
please after login use the form on the application https://betamasaheft.eu/newentry.html?collection=narratives 
the form has a link to https://betamasaheft.eu/Guidelines/?id=entities-id-structure
but the numeric part will be automatically assigned. Actually this assignment is rather easy to reproduce, as it simply picks the next integer after the last used, so you could figure it out by looking at the most recent version of the narratives units repo.
