### ISSUE TITLE
creating more than one new record : app crashes ? 

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/Documentation#1101]
When trying to create a second record after creating a first one, I have the following error message : 
          This XML file does not appear to have any style information associated with it. The document tree is shown below.
        <exception><path>/db/apps/BetMas/edit/save-new-entity.xql</path><message>exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 583, column 19]</message></exception>

Then if I log out and log in again, it is OK. 

Is it normal ?

**Comment by PietroLiuzzo** [comment]
Dear Anais, yes, this is a known issue. it is no crashing, simply the login not being carried over. 
please try with another browser, refresh from server or simply wait a bit. there is nothing I can do at the moment as this depends on an external module and has been already notified, so we wait for an update or will look into changing system in the future
