### ISSUE TITLE
locus

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/Documentation#1102]

**Comment by anaiswion** [comment]
When encoding the folios, I have used the following, copying from another ms files and following the guidelines : <locus from="1" to="129"/>, or  <locus from="139v"></locus>. All of them are unvalid. 
In the file (EMML50) there were already some <locus> encoded with @target, which are valid. 
Is the error because one should not use @from and @to together with @target in the same file ?  
Or is there a pb with the schema ?

**Comment by PietroLiuzzo** [comment]
what is the error message you get from the schema?

**Comment by anaiswion** [comment]
"References to foliation and columns in @target, should use the #, e.g. #6r."

But I am not using @target :-) !

**Comment by PietroLiuzzo** [comment]
yes, there is a problem in the schema, in a rule I added while I could not update the rng.
give me a sec.
