### ISSUE TITLE
occupations ruler and political definition

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1103]
I rephrased the guidelines in https://github.com/BetaMasaheft/guidelines/pull/41 in what I believed was a faithful paraphrasis of the existing text, but now I see it clashing with the schema, so maybe I misunderstood.
The schema has for "ruler" "Ruler of a country, region or similar" and for political "Political occupation (other than ruler)".
Actually, do we have to keep them so strictly separated? I see no problem with using both, since presumably all rulers are occupied with politics. Then we could also use ruler for governors for instance, which according to my impression would be accurate.

**Comment by sologebre** [comment]
Actually, we have decided long ago that occupation as a ruler refers only to the king or queen. However, political occupation involves several positions - local governor, courtier, various medieval political positions. In fact, as you have suggested in some cases, we could also use local governors as ruler in the region where they govern. Therefore, if it does not affect the schema, we should not keep them so strictly separated.
