### ISSUE TITLE
List of easy/repetitive tasks for training, hiwis etc.

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1105]
We once had such a list, maybe we could keep one again?
- Add geez incipit from Macomber's list to the miracle of mary records (Geez needed)
- Add EMML manuscript attestations from Macomber's list to the miracle of mary records
- add geez title from bm:TasfaGiyorgis1956Taammera to the miracle of mary records (Geez needed)
- add wikidata to records of biblical persons

**Comment by PietroLiuzzo** [comment]
yes, I would feel like the wiki is a more appropriate place for this

**Comment by PietroLiuzzo** [comment]
moved to https://github.com/BetaMasaheft/Documentation/wiki/small-tasks-list
