### ISSUE TITLE
alpheios link

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1106]
The alpheios pop up window currently pops up when double clicking on all words inside records, regardless of language, and starts a Latin analysis.
![image](https://user-images.githubusercontent.com/19650382/54678201-dd85da00-4b04-11e9-9494-e55a42bb3e3b.png)
Sorry if this is only an issue in our versions and you already solved it.

**Comment by PietroLiuzzo** [comment]
should be now fixed also in the current version
