### ISSUE TITLE
Nicene creed / Ṣalota hāymānot

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1108]
Are not LIT3308Nicene and LIT4323SalotaHa the same thing by any chance? @DenisNosnitsin1970 @thea-m ?

**Comment by DenisNosnitsin1970** [comment]
There are indeed two creeds, one "Nicene" and one called "Amakneyo za-hawaryat" (Apostolic creed).

**Comment by eu-genia** [comment]
Have you checked LIT4323SalotaHa?

**Comment by DenisNosnitsin1970** [comment]
I think I did once, i can do it another time.

**Comment by DenisNosnitsin1970** [comment]
No, they are not. LIT4323SalotaHa seems to have been attested only in Vat et 47. LIT3308Nicene is one of the two standard creeds attested in the Missal.

**Comment by eu-genia** [comment]
also in Senodos? ESam002?

**Comment by DenisNosnitsin1970** [comment]
Yes, Senodos AM-002 contains LIT3308Nicene as well.

**Comment by eu-genia** [comment]
thank you
