### ISSUE TITLE
add magdala provenance to BL MSS

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1112]

**Comment by thea-m** [comment]
In fact, the provenance is already there. I wonder now about our use of   
```xml
<origPlace>
<placeName ref="INS0101MadhaneAlam"/>
</origPlace>
```
This was added maybe a bit uncritically - since the (majority of the?) manuscripts were brought from other churches to Maqdala by Tewodros. I don't think that it should be automatically added to all manuscripts of this collection, but, if no further information is available, no origin should be indicated and INS0101MadhaneAlam be indicated only in the provenance.
Do you agree?
@DenisNosnitsin1970 @sologebre @eu-genia

**Comment by eu-genia** [comment]
I would replace it if we know more and leave it if we do not, we go as far back as we can.
For the provenance I had                      ```
<provenance>Looted by the British <persName ref="PRS7484Napier">Napier</persName> 
                        expedition in <date>1868</date> from the church of <placeName ref="INS0101MadhaneAlam">Madḫāne ʿAlam</placeName>
                  </provenance>
```
- this I would always insert.

**Comment by thea-m** [comment]
I agree for the provenance (I think all who worked with Wright's catalogue copied this text), but not quite for the place of origin, which we have indeed never discussed as far as I know. 
I would interprete the TEI definition for origPlace ("contains any form of place name, used to identify the place of origin for a manuscript, manuscript part, or other object") to mean mostly the place of production of the manuscript and would read the records in this way. Especially if, as in this case, we give no paragraphic information but simply the link to repository. It is visualized as "Original Location" - does this mean "first attested location of this manuscript"? That could maybe make sense as well, but we would have to specify it.

**Comment by DenisNosnitsin1970** [comment]
Yes, origin indicates, stricktly speaking, the place of production, which is rarely known. Provenance encompasses the history of ownership, evtl. chain of owners. Madhane Alam is not the origin for nearly all these books (but then it appears that exactly origin is known only for very small part of the books), only the last storage place, so it belongs to provenance. Original location (in the sense - first owner) can be solicited in some cases, but the place of origin in the sense of place of production will be known in a few cases only.

**Comment by thea-m** [comment]
I will delete now the occurences of simple
```xml
   <origPlace>
                                <placeName ref="INS0101MadhaneAlam"/>
                            </origPlace>
```
without other references in the record that would point to it as the real place of origin, checking that the reference to INS0101MadhaneAlam is provided in `<provenance>` in all cases.
