### ISSUE TITLE
Objects of Veneration

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1113]
In commit https://github.com/BetaMasaheft/Authority-Files/commit/d5215c1b053d2bb27717a36aafe7e85435431ca2 
@eu-genia created a new taxonomy section (Objects of Veneration) and two values for it (True Cross and Covenant of Mercy) also, correctly, linking these to the art themes values which were already there.
I do not have of course anything against this, but as we would typically discuss here these sort of changes and I do not recall any discussion about this, before I add these values to the schema (unless somebody else wants to complete this taxonomy update) could you confirm that this is fine with all?
@thea-m @sologebre @DenisNosnitsin1970 @DariaElagina

**Comment by eu-genia** [comment]
This was the result of the discussion here
https://github.com/BetaMasaheft/Documentation/issues/836
Already discussed by everyone

**Comment by eu-genia** [comment]
xml edited
