### ISSUE TITLE
analytic view https://betamasaheft.eu/works/LIT2384Taamme/analytic doesnt't work

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1114]
504 Gateway Time-out

I suspect the high number of IDs in the relations of this record as the reason, or the other 400+ records which have a saws:formsPartOf relation with it. Is there anything we can do about it?

**Comment by PietroLiuzzo** [comment]
See comments to commit above, if you try, from my measures the improvement is dramatic.

**Comment by thea-m** [comment]
Thank you, yes, now it works and does not take long to load!
