### ISSUE TITLE
keywords filter in work list view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1115]
Could the keywords for which one can filter here https://betamasaheft.eu/works/list be limited to actual genre keywords? It makes no sense to filter works for "beardless"...
And, since there is the very nice period filter just beneath it, there is no need for the period keywords to be present twice.

**Comment by PietroLiuzzo** [comment]
I have made this change and killed the db, I am restarting it...

**Comment by PietroLiuzzo** [comment]
you will get all and any keywords for the relevant context now, so, unfortunately no beardless or bearded literary work!
scherzi a parte, another good general improvement I think, thanks for pointing it out!

**Comment by thea-m** [comment]
Great!
