### ISSUE TITLE
Clarification of Clavis, CAe, IDs on the app

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1117]
One of the issues raised in the feedback session at the Paris workshop was our use of the word "clavis", which is not widely known and was not understood by most. And now I was asked again what we mean by this. I think that this justifies some reflection on how we can present our work in this area to make it more accessible.
If this term is to be kept everywhere, maybe a first step could be to have "Clavis Aethiopica (CAe)" instead of just "Clavis" in the menu? However, for the other entities we also have there "Persons" and "Places", not "Gazzetteer" and "Prosopography", so maybe "Works" could be used as well?
Maybe there could also be further information in the work list view (https://betamasaheft.eu/works/list)? Would it be possible to have a kind of title there (above "Please, select a filter" for instance) that says "Clavis Aethiopica: Repertory of the Ethiopian Written Tradition" or something similar?
I assume that the long-term intention is for the CAe numbers to be used outside of the project as well, in which case we would need to make them more understandable to users. There is also often confusion about CAe numbers, IDs and titles. Probably there should be an explanation for "CAe" on the page of works, for example in a window on hovering above the CAe number?
I have no good idea how to resolve the confusion about what IDs are, maybe you do?

Thank you!

@abausi @PietroLiuzzo @eu-genia @DenisNosnitsin1970 @sologebre @DariaElagina

**Comment by PietroLiuzzo** [comment]
From the plan we made I should have has texts under the round discs for each entity type on the homepage. There was the idea to fetch that from the guidelines which is ok. Only we would need to identify the bits to provide there and if they are missing add them. 

Process would look like
1. Check that clear definitions / clarification of these points are present in the guidelines 
1. If not edit them
1. Decide which piece to link to or transclude or both and where. E.g. Page Works Div 2 in guidelines should be shown in work list view etc 
1. I will then add these.

I would avoid lengthy menu names as much as possible 1 word is already too long sometimes. The tour text can be also improved and picked from/linked to the guidelines. We also have the hints functionality which can be much extended to provide more and better hints for navigation

**Comment by PietroLiuzzo** [comment]
I have added one line texts in the updated index page.

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/Guidelines/?id=definitionWorks

**Comment by abausi** [comment]
This is very good! But I would suggest these corrections (file attached).

Il 08.11.2019 15:05, Pietro Liuzzo ha scritto:

**Comment by thea-m** [comment]
@abausi thank you! However, I see no attachment...

**Comment by abausi** [comment]
I do not know why: it did nto go through the email...

Il 08.11.2019 15:42, thea-m ha scritto:

**Comment by PietroLiuzzo** [comment]
please send attachment per email, not to the github issue tracker.

**Comment by thea-m** [comment]
this is now covered by #1247
