### ISSUE TITLE
menu explanation windows

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1118]
The explanations one gets when hovering on the menu of pages are very helpful! But for me, only the windows for "Hide/show pointers", "Hide/show related", "Geobrowser" and "Compare" (on work pages) stay stable when I move the cursor (in Chrome). It's not necessary for those that provide just one informative word, but the ones that have clickable links (like "Edit") or where one has to scroll to read the complete information are not fully usable like this. 
(Probably no one ever clicks on them anyway, but still..)

**Comment by PietroLiuzzo** [comment]
The buttons leading to alternative views of each item are explained in the tour as well. Their behavior is to show up on the right of the button and they have a fixed height not to exceed that row. I can try to make them adapt to size and display on top of the header.

**Comment by thea-m** [comment]
What I mean is that When I hover on the "Edit" button I see "Not sure...have a look at the Beta masaheft" and have no possibility of either clicking on "Beta masaheft" or scrolling down to see the rest of the text. I can of course click the edit button, which works fine.

**Comment by PietroLiuzzo** [comment]
I think then it was just too far on small buttons. better if it is closer and overlaps bigger buttons. Please try now, you should be able to move into the tooltip text and click on the guidelines link

**Comment by thea-m** [comment]
It's better now, thank you!
