### ISSUE TITLE
martyr person type

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1119]
I would suggest to add "martyr" to the person types, do you agree?
@DenisNosnitsin1970 @sologebre @DariaElagina @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Would be helpful. Do we need other categories of saintly persons?

**Comment by thea-m** [comment]
We have just started to use these types, so for now we only have angel, saint, biblical and prophet (several can of course be used in the same record). We can absolutely expand the list, do you already have suggestions?

**Comment by sologebre** [comment]
yes, definitely, it is very helpful.

**Comment by DariaElagina** [comment]
Excellent idea

**Comment by DenisNosnitsin1970** [comment]
Dorothea, 
do I understand right? The envisaged categories are
1) Angel
2) Saint, biblical
3) Prophet
4) Martyr

**Comment by thea-m** [comment]
Hi! Angel, saint, biblical and prophet are the categories that already exist and can be used (saint and biblical are two separate ones). I now want to add martyr, and of course, we can add more if we find them useful.

**Comment by thea-m** [comment]
see https://betamasaheft.eu/Guidelines/?id=persons

> Person types
> Generic information about types of persons which are not occupations, such as "saint" or "angel" are encoded with keywords. If you would like to add new person type keywords, or are unsure about whether to encode an information as a person type keyword or occupation, please open a new issue.
> 
> ```
> <textClass>
> <keywords>
> <term key="angel"></term>
> </keywords>
> </textClass>
> ```

**Comment by thea-m** [comment]
I created the authority file and added the value to the taxonomy and schema, could you update it @PietroLiuzzo ?
