### ISSUE TITLE
search/filter for person groups

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1121]
It would be nice to be able to search for person groups (and filter the person view list for groups as well).
(If it's not already possible and I missed how?)

**Comment by PietroLiuzzo** [comment]
so you would like a filter that allows you to see only person groups (like the results from here
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootPr%2F%2Ft%3ApersonGrp , but in the filter view.) you will see stephanites, house of Takla haimanot, etc.
and another one that would list these groups and let you see the members more or less as in this list for persons https://betamasaheft.eu/as.html?query=&homophones=true&AttestedInType=2&references=PRS11208HouseTakla&xmlid= 
but without having to know that you should search for the id of a group etc.
I think this would be a valuable addition and would surface a type of information which is currently well hidden.

**Comment by thea-m** [comment]
Thank you!
