### ISSUE TITLE
subtitle for extras

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1128]
In the web app, the subtitle "Finding aids" should be printed

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/1122#issuecomment-479455210_

**Comment by PietroLiuzzo** [comment]
I do not personally have nothing against this. Should this affect then all extras?

**Comment by eu-genia** [comment]
only if they have a defined desc type

**Comment by eu-genia** [comment]
(this case only refers to the newly imported data of the type Finding aids; this should be clearly visible)

**Comment by PietroLiuzzo** [comment]
@eu-genia I have made that change, I still remember. The following values are used in desc within an item that is a extra
* Unclear
* StampExlibris
* Gloss
* findingAid
* GuestText
* OwnershipNote
* Correction
* CommemorativeNote
* PoemArke
* Letter
* DonationNote

So the question is:
Do you want to instantiate an exception and have only findindAid printed when it is findingAid, or would it not be better to have this always printed out.

To this question follows a further one. You ask for a "subtitle" but to be consistent with the way in which this information is given for Additions, it would be printed in brackets like (Type: finding aid)

I would take this occasion to improve the consistency of the visualization, so if we decide to use a subtitle of some sort here, I would do the same for additions. otherways, I would use the same way we currently have to view the type.

Additionally I will add, whichever the choice here, also a link back to the additions, binding and decorations searches to go directly to a list which has all instances.

**Comment by PietroLiuzzo** [comment]
@thea-m @sologebre @DenisNosnitsin1970 @DariaElagina please have also a say, I am sure you have ideas and the current way this comes out is unsatisfactory (e.g. extras which only have a type result in an empty list item...)

**Comment by thea-m** [comment]
Sorry, I'm aware that doesn't answer your question: Could you link to the XPath for the search of extras that have a `<desc>` with a @type? I didn't manage it. I am a bit surprised that there are any that do have a desc with @type, since this is not mentioned in the guidelines and we usually use the types only for additions. I can see why one would use them for extras as well, and might have done it myself also. But then we could add an example and a clarifying sentence to the guidelines.
I am wondering particularly about those that have Unclear, GuestText, OwnershipNote, CommemorativeNote, PoemArke, Letter and DonationNote. Why wouldn't these be additions?

**Comment by thea-m** [comment]
(It might be useful to define the types that can be used for extra, since this would provide some structure to what is often a "Restekategorie" in the area of documenting scribal practices)

**Comment by thea-m** [comment]
As for the visualization, I would be in favour of consistency between additions and extras, the current visualization in brackets looks fine to me. I might actually prefer to have it printed at the top of the element's visualization instead of at the bottom, maybe next to the locus visualization? I would probably also prefer it not to be in camel case (is it called normal case then?....).
For a1 in https://betamasaheft.eu/manuscripts/ESakm008/main, for example:

> 1. f. 125v (Type: Ownership Note)

But obviously that's all a subjective preference.

**Comment by PietroLiuzzo** [comment]
[Xpath query for items which have xml:id starting with e and a child desc with a type attribute](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aitem%5Bstarts-with%28%40xml%3Aid%2C+%27e%27%29%5D%5Bt%3Adesc%5B%40type%5D%5D)

will give you all extras with a desc which has a type.

adding the value, will give you the breakdown.
[Xpath query for items which have xml:id starting with e and a child desc with a type attribute of a specific value](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aitem%5Bstarts-with%28%40xml%3Aid%2C+%27e%27%29%5D%5Bt%3Adesc%5B%40type+%3D+%27GuestText%27%5D%5D)

The majority of these (577) is the findingAids I just added from the domlib data.

To exclude all the findingAid, you can use this query

[Xpath for items which have xml:id starting with e and a child desc with a type attribute which doe not have the value findingAid](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aitem%5Bstarts-with%28%40xml%3Aid%2C+%27e%27%29%5D%5Bt%3Adesc%5B%40type+%21%3D+%27findingAid%27%5D%5D)

If I remember correctly, the distinction between extra and additions is an inheritance of Ethio-SPaRe which we maintained grouping the items in additions with different `xml:id`s whereas the only semantic distinction in the TEI is between `msItem`s and `additions//item` 

The section [Varia](https://betamasaheft.eu/Guidelines/?q=extra&id=additionsVaria)  of this page does need a lot of editing indeed, as there are a number of things in that list which we do differently

**Comment by PietroLiuzzo** [comment]
I forgot to add, that because of the above and the distinction made in the guidelines currrently I would not see too much of a problem in using the currently allowed types for any item in additions also for extras. It is instead questionable how to decide on the level of "triviality" which the guidelines now suggest so that perhaps this point needs to be specified and better described as well.

**Comment by PietroLiuzzo** [comment]
The camelCase is simply lack of printing of the proper name for the value, I will fix that in any case.

**Comment by PietroLiuzzo** [comment]
I have printed this out until further discussion as suggested by Dorothea, and added a link back to the additions list for additions.

**Comment by eu-genia** [comment]
for now I can only see Stamp Exlibris and Unclear used in Extras, that does make sense (as the others are true additions)

OK for treating them all equally (I was originally lead by the E-S database where Finding aids are a distinct category alongside Additions and Extras, so are treated with the same type of subtitle)

**Comment by eu-genia** [comment]
The items that @sologebre encoded in BLorient697 as extras of Type: Ownership Note and Type: Poem Arke should be additions AFAIC

**Comment by PietroLiuzzo** [comment]
@eu-genia I do not understand what you mean with "I can only see...". the link to the Xpath above is a Guest Text in ESam002 for example.

**Comment by thea-m** [comment]
(I have used unclear quite a lot, but it does actually not make any sense at all - why not give no type and just describe the item as best as possible?)

**Comment by PietroLiuzzo** [comment]
the type will help grouping

**Comment by thea-m** [comment]
Yes, if it were used consistently, which it is not. The majority of extras has no type at all.

**Comment by sologebre** [comment]
I've corrected it now.

**Comment by PietroLiuzzo** [comment]
Thanks @thea-m  for opening this issue https://github.com/BetaMasaheft/Documentation/issues/1130
I did remember well that there was a conversation started on something similar...
