### ISSUE TITLE
additions/additiones

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1129]
Both are used on the app, Additiones is printed in the respective section of manuscript pages (https://betamasaheft.eu/manuscripts/BDLaethg11/main), Additions for example in the index (https://betamasaheft.eu/additions). We should probably decide on one. I would be in favour of Additions.
@abausi ?

**Comment by PietroLiuzzo** [comment]
I have fixed this to be always additions for the moment.
