### ISSUE TITLE
Crucifixion as a subbject?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1132]
Among the subject keywords, there is "Crucifixion", is this actually a subject or has it entered the list by accident (it hasn't been used)?
@DenisNosnitsin1970 @DariaElagina @eu-genia @sologebre

**Comment by DenisNosnitsin1970** [comment]
"Crucifixion" is a subject, but in painting, I think

**Comment by thea-m** [comment]
yes, and there we have AT1005Crucifixion. It must have slipped into this list as well somehow, I'll delete it then
