### ISSUE TITLE
Punctuation

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1133]
1) For some reason Punctuation content is printed twice, differently, see e.g. ESdz004
2) Can we have a @subtype for "Dividers"?

**Comment by PietroLiuzzo** [comment]
after more than a year... I wonder...

**Comment by PietroLiuzzo** [comment]
we can have a subtype dividers, but I am not the one to decide on this and the reason to make this distinction.

**Comment by eu-genia** [comment]
with subtype dividers all works fine I believe, have just had the same case in another MS

**Comment by eu-genia** [comment]
No wait a sec I still have a prob, the punctuation block is printed under Layout and then again under Palaeography; with subtype Dividers the Dividers block is not repeated under Palaeography, see the two mss here
https://github.com/BetaMasaheft/Manuscripts/compare/ESap020
![image](https://user-images.githubusercontent.com/17987728/82951956-6b324480-9fa8-11ea-8535-80a029d2ed8a.png)

**Comment by eu-genia** [comment]
(We do need the subtype Dividers)

**Comment by eu-genia** [comment]
I see now the bit is not printed under Layout only under Palaeography, but the bit with subtype Dividers does not appear because it is not in the schema

**Comment by PietroLiuzzo** [comment]
it does not appear because it is not in the XSLT which does the view in that context, it actually is in the schema as it appears https://betamasaheft.eu/Guidelines/?id=ab

**Comment by PietroLiuzzo** [comment]
This is what I have now locally, please let me know if it is ok.
<img width="322" alt="Schermata 2020-05-27 alle 18 57 17" src="https://user-images.githubusercontent.com/508012/83049832-e993f280-a04b-11ea-8772-a57610b5d49f.png">

**Comment by PietroLiuzzo** [comment]
the script assumes that there is a list of items into this ab[@subtype="dividers"]

**Comment by eu-genia** [comment]
yes looks good
