### ISSUE TITLE
add rule to prevent ids starting with # in @active and @passive

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1135]
@DenisNosnitsin1970 just pointed out rightly that we are missing a rule to prevent the use of strings starting with # as values of @active and @passive.

this is a small change which needs to be made around line 4784 of our schema, anyone willing to give it a go @eu-genia @DariaElagina @thea-m ?

**Comment by eu-genia** [comment]
committed here https://github.com/BetaMasaheft/Schema/commit/b022e8484acbb5b32a39c6d0010fb8ee68230f92
