### ISSUE TITLE
how to type geez numerals with keyman

### ISSUE THREAD

**Issue by AngelaMueller** [BetaMasaheft/Documentation#1136]
how are geez-numbers written with keyman and inserted with atom?

**Comment by PietroLiuzzo** [comment]
I do not know. @abausi ?
or perhaps @sologebre, @thea-m, @eu-genia, @DenisNosnitsin1970 or @DariaElagina can help? perhaps we ought to have a support page in the GL about input methods as well.

The input method should not have any interference with the editor you are using, so, atom has nothing to do with keyman, and once you know how to type the numerals, you can type them in Atom as in any other software.

**Comment by thea-m** [comment]
I don't know what programm you're using - in SIL Ethiopic 1.3, you type the numeral followed by ( (German keyboard), for the decimals then followed by 0
https://www.tavultesoft.com/keyboarddownloads/%7B7FAC071E-6F5C-4E7B-ACD3-D79E55F09DA8%7D/readme.html

**Comment by eu-genia** [comment]
I use the normal windows keyboard most of the time, then you simply select Amharic keyboard layout and click the button where the German keyboard has "Ä" and then the number (or select from the menu)

**Comment by AngelaMueller** [comment]
Hab rausgefunden wie es funktioniert bei Keyman: 1 + 0, 2 + 0 etc.Korrigiere das bei meinen Eingaben noch.Danke!

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Apr. 8, 2019 at 14:40 schrieb thea-m<notifications@github.com>:   
I don't know what programm you're using - in SIL Ethiopic 1.3, you type the numeral followed by ( (German keyboard), for the decimals then followed by 0
https://www.tavultesoft.com/keyboarddownloads/%7B7FAC071E-6F5C-4E7B-ACD3-D79E55F09DA8%7D/readme.html

**Comment by AngelaMueller** [comment]
OK. I found out it's 0 + 1, 0 + 2 etc. for 1, 2 in geez numerals.I'll try Ä + as well.Thanks!

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Apr. 8, 2019 at 14:57 schrieb Eugenia<notifications@github.com>:   
I use the normal windows keyboard most of the time, then you simply select Amharic keyboard layout and click the button where the German keyboard has "Ä" and then the number (or select from the menu)

**Comment by abausi** [comment]
0 + 0 > 100

and for tens:

1 + 0 > 20 etc.

Il 08.04.2019 14:37, AngelaMueller ha scritto:

**Comment by PietroLiuzzo** [comment]
I will add this to the combos.html page.
