### ISSUE TITLE
EMML50 repository

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1137]
Dear Anaïs, 

could we update the repository of EMML50 to INS0599AKU, as suggested in this issue:
https://github.com/BetaMasaheft/Documentation/issues/1099 (assuming that the manuscript is still kept there... )
It would really make a nice example for the guidelines.

Thank you!

**Comment by anaiswion** [comment]
I've been reading the various issues linked with  #1099 ... and I am not sure if there is a decision about how to consider EMML at the end. 
Anyway my view on the topic is the following. 
Using the EMML reference as a shelf-mark, which is the shelf-mark given to the microfilm but also written inside each manuscript microfilmed, is very useful, and in most cases can not be replaced by another shelf-mark (EMML50 is an exception). 
Considering EMML as a repository makes sense as the physical repository... of the microfilms (and the digitised files, when they exist). 
But it is a fact that at the time when they have been microfilmed, those mss where kept in physical repositories in Ethiopia, and should still be kept there (as far as EMML50 is concerned it seems dubious). . 
Why not keeping the EMML structure (I mean : the manuscripts xml files organised according to their EMML numbers), for its clarity. And at the same time, it is possible to differentiate the repository of the microfilm/digitised copy from the repository of the physical manuscript.  
I'll give an example to make it clear.
