### ISSUE TITLE
(about: ) in bibliographies broken

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1138]
e.g. https://betamasaheft.eu/works/LIT2317Senodo/main
does not load the reference

**Comment by PietroLiuzzo** [comment]
the bibl here do not point to an xml:id within the file but to the names of the manuscripts, for the about to work, the witness needs to have an xml:id and the bibl a corresp with a pointer to that

**Comment by eu-genia** [comment]
sorry, hope now is all OK

**Comment by PietroLiuzzo** [comment]
as you can see, it is not yet. the reason is that you are assigning the ID of the manuscript again as xml:id for the witness element, which is resulting in the process identifying those ids to be faulty everywhere in the app, not only here. please make sure to use a string different from the ID, it is enough as in pre-existing entries and in the examples provided in the guidelines to change to lower case.
I will add a statement about this in the guidelines, as the examples are clearly not self explanatory enough.

**Comment by eu-genia** [comment]
done
