### ISSUE TITLE
E-S files missing data (Extras / Crux Ansata)

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1141]
1 Extras

E.g. ESam015
Varia : | - Corrections written over erasures, in the main hand: fols. 10v, 11r, 12v, 14v, 25v, 26v, 31r, 33v, 38v, 45r, 52r, 63r, 64r, 64v, 65v, 66v, 82v, 88r.
-- | --
XML
```
<extras class="MCRMetaLangText" heritable="false" notinherit="false">
<extra xml:lang="en" inherited="0" form="plain">
- Corrections written over erasures, in the main hand: fols. 10v, 11r, 12v, 14v, 25v, 26v, 31r, 33v, 38v, 45r, 52r, 63r, 64r, 64v, 65v, 66v, 82v, 88r.
</extra>
</extras>
```
For most manuscripts this element has been converted into Extras (e1) but obviously not for all!
Is there a way to find out where it has not been taken?
(It is very difficult to manually check each and every time)

****

2 Crux ansata / Coronis
In E-S descriptions the fields sometimes contains description in words
e.g. 

ESap009
Crux ansata : | Crux ansata is used as a text divider in fols. 41ra, 164ra (?).
-- | --

ESmakm053
-> Crux ansata : | Two crux ansatas with a coronis in between (fol. 73vb).
-- | --

In BM only the locus was picked
(e.g. ESap009:

```
<ab type="CruxAnsata">
                              <locus target="#41ra"/>
                           </ab>
```
)

the text is missing and should be inserted

**Comment by PietroLiuzzo** [comment]
I do not understand what do you mean by "obviously not for all". I would need at least one example where this does not happen, otherwise,  you can safely assume that every time there was <extras> in the mycore XML there is now an extra in our TEI, there is a pretty much straight forward rule for that.

**Comment by PietroLiuzzo** [comment]
I see, you ment the above as the example...

**Comment by PietroLiuzzo** [comment]
apparently the extras have been added only when additionals where also there, the 248 cases in which there are only extras and no additionals do not have this. e.g. ESagm002 has none of the information in 
domlib_document_00001233

**Comment by PietroLiuzzo** [comment]
There are more or less 20 instances of the issue with Crux Ansata / Chi Rho / Coronis

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Manuscripts/commit/45c10bc7cd30d6404bdd5e7e6022b67f68182533
I have hand fixed these cases
