### ISSUE TITLE
visualization of fragmented mss

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1143]
msFrag elements are not seen in the navigation bar - guess it could be helpful if they are? See e g ESam040 consisting of two fragments formerly registered as am-040 and am-047

**Comment by eu-genia** [comment]
also the contents of the msIdentifier for each fragment should be visualized

**Comment by PietroLiuzzo** [comment]
please check if it is fine now.

**Comment by eu-genia** [comment]
ESam040 looks good, but can you please check ESamm005006 - the navigation bar is there but for some reason it does not jump to f1?
