### ISSUE TITLE
encoding of rubrication

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1144]
General information on the use of rubrication is currently encoded (after many issues already...) in `<handNote>`
in `<seg type="rubrication">` (presumably because it is a scribal phenomenon). I was wondering now whether `<layout>` wouldn't be a more appropriate place? It seems a bit inconsistent to me that punctuation is encoded there, but rubrication, which is in fact often used as a means of layout, is not. But there were probably reasons for the original decision for handNote?
@DenisNosnitsin1970 @eu-genia @sologebre @DariaElagina

**Comment by thea-m** [comment]
I am also wondering whether it would be useful to formalize the encoding of rubrication more. Now, we mainly write lists in `<seg type="rubrication">`. Could it be helpful to formalize the most recurring phenomena of rubrication (nomina sacra, titles and incipits, punctuation, numerals...) and then specify the precise way in which this rubrication is carried out? For instance "Nomina sacra (ማርያም፡ consistently throughout the manuscript, እግዚአብሔር፡ on f.29ra)" (in whatever form of encoding would make most sense). 
Would this add something to the records (would someone be interested in filtering manuscripts precisely for specific kinds of rubrication?), other than more consistency?

**Comment by DenisNosnitsin1970** [comment]
Sorry, one correctly related to the thema indirectly. "Nomina sacra" is a wrong term, it does not exist in Ethiopia. As far as I understand, "nomina sacra" refers to abbreviations. Ethiopian never abbreviated the names, so wie IHC for Greek Iēsous, XC, XP XPC for Christ etc. What we mean are "holy names" or "divine names".

**Comment by thea-m** [comment]
Ah, thank you! Should we then be doing something about the 1065 occurrences in our records? Or can it be recoined for the Ethiopian tradition?

**Comment by DenisNosnitsin1970** [comment]
Actually, 1065 occurrences should be corrected at a certain point. These are mostly from Ethio-Spare records, but the term is already occupied for smth that the Ethiopian tradition does not have. We should understand which names exactly we mean, and if "holy names" or "divine names" really fit, or better we use references to separate name. The problem is that only some of what can be considered as "holy names" are usually rubricated. For instance, Mary is rubricated frequently, but Jesus not so much, "God" seldom. Do we consider the words for God and Trinity as "holy names"? (I assume the record in Ethio-Spare mss mostly refers to St. Mary, but this should be checked).

**Comment by DenisNosnitsin1970** [comment]
I would not describe "rubrication" as the mean of means of layout. "Rubrication" itself follows (or disregards occurs outside of) layout. Means of creating layout are pricking/ruling. Rather, "rubrication" is the means of further structuring the written area and developing hierarchy therein.

**Comment by thea-m** [comment]
I agree, I would understand rubrication in SdC terminology as pertaining to the "mise en texte" (and not "mise en page"). But it seems to me that `<layout>` might be a more approriate place for it in our records than hand description. (Until now, `<layout>` is not limited to the description of ruling and pricking and the text area created by them, punctuation is also encoded there, which, if we take a stricter definition, would seem inconsistent to me).

**Comment by DenisNosnitsin1970** [comment]
It depends on the ontological point of view, there can be several of them. Under "hands", it can be a logical extension of <seg type/>, one describes what is written in black ink (or, as default, it is everything), and what is written in red, for instance. Then one is in a good position to introduce "hand of the rubricator", which is an important category. "Punctuation in layout" sounds a bit odd for me, unless there is a logical explanation. We may have a look in the catalogues as to how the rubrication is dealt with by others.

**Comment by thea-m** [comment]
Thank you @DenisNosnitsin1970, I agree. We can check more modern catalogues (in the catalogues of Ethiopian manuscripts, there is often a "Varia" section which includes mentions of rubrication or similar practices which is not particularly helpful for this discussion; in the example entry in Syntaxe du Codex rubrication of incipits is described in "Organisation du contenu"). I would indeed encode in handDesc whether the rubrication was carried out by the main hand or not, and if not, have a separate handNote for the rubricator.
However it is decided in the end, I would like already now to encode rubrications in the usual place within a `<list>`. It is a list anyway in all records, now just encoded as one. I have done this in TF003 (description not finished yet) and it helps me organize my thoughts. Could it be visualized in a list form on the app, @PietroLiuzzo ?

```xml
     <seg type="rubrication">
                       <list>
                          <item>Titles and beginnings
                          <list>
                             <item>Two pairs of rubricated lines, separated by three black lines at the beginning of <locus target="#3r"/></item>
                             <item>Titles and numbers of psalms</item>
                    ...
                          </list>
                          </item>
                          
                          <item>Elements of punctuation</item>
                          
                          <item>Names
                          <list>
                             <item> እግዚአብሔር፡ on <locus from="110r" to="112r"/></item>
                          </list>
                          </item>
                          
                          <item>Other
                          <list>
                             <item>Names of the Hebrew letters and their interpretations in Ps. 118</item>
                          </list>
                          </item>
                       </list>
                    </seg>
```
