### ISSUE TITLE
encoding of crux ansata

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1146]
Where should the presence of a crux ansata as a recurrent marginal sign to mark the beginning of textual units be encoded? ES manuscripts have `<ab type="CruxAnsata"`> in layout, in BM manuscripts it is spread through extras or handNote (but not very frequent). 
What do you think? I'm not sure whether this belongs more to layout or to scribal practices?
@DenisNosnitsin1970 @DariaElagina @eu-genia @sologebre @PietroLiuzzo 

#1141

**Comment by DenisNosnitsin1970** [comment]
I would say, it is neither layout nore the scribal practice (perhaps the second but only very uproximately). Actually it is a kind of punctuation sign, of the same type as other text dividers, and the way and regularity of its use are meaningful. Perhaps here the need of "punctuation" becomes visible.

**Comment by thea-m** [comment]
Thank you! Then I'll close this, since we already have https://github.com/BetaMasaheft/guidelines/issues/48
