### ISSUE TITLE
Mazmura dawit + dǝngǝl

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1149]
I wonder whether a separate Work ID should be created for the Psalter (LIT2701Dawit) + Psalter of the Virgin (LIT3985Mazmura) combination? This is a fixed frequent collection and probably deserves its own Work status. This way one could also immediately distinguish the augmented version, which would also be seen immediately as first-level msItem title (now one has to click and open to see whether there is Mdǝngǝl inside or not). What do you think, @thea-m @DariaElagina @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
Agree. All modified Psalters need separate IDs.

**Comment by thea-m** [comment]
Sure, but isn't this already covered by https://github.com/BetaMasaheft/Documentation/issues/1058? Does LIT3985Mazmura also occur without the Psalter?

**Comment by eu-genia** [comment]
Yes you are right! sorry have forgotten... I even talked to @DariaElagina about this a while ago. 

Anyway, why I do not think LIT3985Mazmura occurs without the Psalter, it differs as to how much of it occurs (Psalms + Canticles + Song, just Psalms, Psalms+Canticles, or just single stanzas here and there), so we still might need two IDs, one general for any stanzas or combination, and one specific for the complete combination.

Anyway i leave it to Daria to check and correct.
