### ISSUE TITLE
encoding of ruling and pricking

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1150]
The presence and execution of ruling and pricking is mostly encoded in `<ab type="ruling">` and `<ab type="pricking">` in `<layout>`, for example in ESakm007: 
```xml
    <ab type="ruling">Deviates, cp. <locus target="#15v">15v</locus>,
                              16r.</ab>
                           <ab type="pricking">Pricking and ruling are partly visible. </ab>
                           <ab type="ruling" subtype="pattern"> Ruling pattern:
                              1A-1A/0-0/0-0/C.</ab>
                           <ab type="pricking"> Primary pricks are not visible. </ab>
                           <ab type="pricking"> Ruling pricks are partly visible. </ab>
                           <ab type="ruling"> The upper line is written above the ruling. </ab>
                           <ab type="ruling"> The bottom line is written above the ruling. </ab>
                           <ab type="ruling"> The scribe frequently disregarded the ruling (s.,
                              e.g., <locus target="#13v">13v</locus>, 18v-19r).</ab>

```

However, in some records, `<dimensions unit="mm" rend="pricked ruled">` (also in `<layout>`) is used instead (for example GAet10). Here, the information that ruling and pricking is present is currently not visualized on the app if the description does not contain the respective `<ab>`s as well.

Both uses are present in examples in the guidelines. Maybe it would make sense to use `rend="pricked ruled"` to encode the presence of ruling and/or pricking (which could be visualized as "Pricking and ruling are present") and the `<ab>`s for more information on their execution, if available (this is how @ElianaDalSasso has actually done it in SHOr413).

I could suggest this a bit more explicitly in the guidelines, and in any case, any of the existing encoding practice would still be valid.

What do you think? @PietroLiuzzo @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
I think we should stick with the typed ab, whose presence already says there is pricking/ruling, and correct records and guidelines to 
* remove `rend="pricked ruled"`
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Adimensions%5B%40rend%3D%27pricked+ruled%27%5D
* fix the first example in https://betamasaheft.eu/Guidelines/?q=ruling&id=layoutDesc of the GL accordingly (adding also the source of the example)

**Comment by thea-m** [comment]
Good, can I then remove the sentence "A @rend can be used to list separated by spaces other visible characteristics." from the layout guidelines? I don't find any uses of @rend in `<dimensions>` other than this.

**Comment by PietroLiuzzo** [comment]
There was probably some rationale behind this which I fail to recall and cannot find in the issues. @ElianaDalSasso might remember?

**Comment by PietroLiuzzo** [comment]
I think it is anyway safe to kill.

**Comment by ElianaDalSasso** [comment]
Dear Thea, dear Pietro,
it seems that I used 'pricked ruled' to encode a 'text area'. I will modify the files according to the Guidelines!

**Comment by thea-m** [comment]
thank you, @ElianaDalSasso ! Could you close this issue when you're done?
