### ISSUE TITLE
Highlighting works with text

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1154]
At the moment, the main work view does not give you any indication as to whether there is any encoded text. The "text" tab at top is nearly "invisible" (as it is in-between many others), and then in 99% of cases not helpful as there are few works with `<div type="edition">`. 
Would it be possible for those that have the `<div type="edition">` (and possibly, in case it comes later, `<div type="translation">`) have a button within the main view saying TEXT? Or that for those records the "Text" tab is more visible?

**Comment by PietroLiuzzo** [comment]
I can make the text button red, if you think that helps.

**Comment by eu-genia** [comment]
Would help, would probably help even more if there is something in the main body with a link

**Comment by PietroLiuzzo** [comment]
The Text button and the Transcription button for mss are now red. Eventually, this was already available in the left-side navigation bar, I have made that red as well and updated the text of the link to match the one in the options at the top.

**Comment by PietroLiuzzo** [comment]
in case there is a translation there will be also a translation button. However, this will link to the same text view, as the translation is always shown there.

**Comment by eu-genia** [comment]
A minor thing: the prompt when pointing at Text tab says "Full Text (as available)". Maybe delete the word "Full" as there can be also very partial text.
