### ISSUE TITLE
Link to DOMlib descriptions in ES manuscripts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1159]
I think that it would be useful to link to the original DOMlib descriptions in the records of ES manuscripts, particularly in the cases of manuscript descriptions that have been intensively reworked or elaborated. Or was there a specific reason behind the decision not to do this?
@PietroLiuzzo @eu-genia @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
IMHO, it would make much more sense for a user of DOMlib to be linked to BM, where the newer versions are, rather than for a BM user to be pointed to an older version of the same information.

**Comment by thea-m** [comment]
That would also be good, but will they (who are they?) do it? We do already link to DOMlib in the Catalogue bibliography, and it would be much more precise to link to the actual description, as we do for all catalogue digitalisations. We are now going through these records anyway and it would not take much time to add the right link to each one we happen to open.

**Comment by DenisNosnitsin1970** [comment]
It is difficult to say what is better. The existence of Ethio-Spare database is not secure at all on the long run, by the way. The images are a more significant reason to link the descriptions. To insert a reference from the later version to the original, not vice versa, seems to be a common practice to me.

**Comment by PietroLiuzzo** [comment]
ok, I can add a link back to domlib, explicitly saying this is an older version. The images there are not accessible as far as I know, only users with account can access them there, so I would think that if we want to provide more direct access to images we should make more free to access from Beta Masaheft. The images are being processed and adding the necessary markup to make them available is not difficult and I can do it myself

**Comment by PietroLiuzzo** [comment]
I forgot to mention, but I hope it was clear already, that this is of course a decision for @DenisNosnitsin1970 to take, and even if more become accessible, it does not mean all, by all means

**Comment by thea-m** [comment]
I completely agree with regard to the importance of making the images accessible on BM. I'm not sure why it is so necessary to treat these DOMlib descriptions in another way as all the other catalogue entries on which our records are based and which are given in secondary bibliography? I see the relationship as similar - some of the XML records just present the information given in the old records in a new way, and some constitute significant reworkings.
Anyway, thanks a lot!

**Comment by PietroLiuzzo** [comment]
- [ ] the bibliographic reference in Catalogue Bibliography to ES should lookup a list of domlib ids matching the actual ES identifiers, so that the actual bibliographical reference can be updated looking up the relevant record adding a link to the correct domlilb item and the name of the cataloguer (#1214)
