### ISSUE TITLE
using atom: any shortcuts ? 

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/Documentation#1160]
Just a simple daily question : how to enter a tag in a text with Atom ? with Oxygen I was using the "cmd+e" short cut to introduce a tag around selected words. 
I ask this here as I cannot find this kind of help in Atom.

**Comment by PietroLiuzzo** [comment]
I do not think there is this facility, you have to type your < and you will get a list of the elements allowed by the schema, which you can pick.

**Comment by anaiswion** [comment]
OK thanks ! what a pity ! I love so much the ctrl+E in Oxygen !
