### ISSUE TITLE
line indications in scroll description

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1162]
I would like to indicate the lines of items in a scroll description in `<locus>`. It is not possible to give only lines in locus, but it needs @target, @to or @from, I have now done it like this:
```
<locus from="1r" n="11"/>
<locus to="1r" n="18"/>
```
Is this fine from the encoding? @PietroLiuzzo 

I think that it would be more useful to readers to have a continuous line count from the beginning to the end of the entire scroll, and not to start counting anew with each new parchment strip, which is why I used "folio 1" through the entire description. What do you think? Would it be preferable for example to indicate the strip on which each msItem is located, or to visualize only the line numbers?  @DenisNosnitsin1970 ?

**Comment by thea-m** [comment]
Any opinions? @DenisNosnitsin1970 @PietroLiuzzo

**Comment by DenisNosnitsin1970** [comment]
I would say, to indicate the strip number is ok, while counting lines will be a nightmare for the catalogers. However, I wonder if the boundaries are always well visible, and if of the strips always with the boundaries between the texts. I assume, they do not. Alternatively, one can segment the scroll into written areas between images, and count after them.  But actually the simple sequence image I - text I - text II - image II - text III - image III is already quite helpful and is enough for finding the way. To my opinion, the best way would be to visualize the structure of written and painted areas of the scroll, smth like sample in the attachment (schemes are offered in some selected cases in catalogues, S. Strelcyn etc.). It would be helpful
![Cod Etiop 22 scroll](https://user-images.githubusercontent.com/18533839/58465653-730e9d00-8138-11e9-8e8a-73cac1018632.png)
 also for cases of scroll layouts that are more complex than one column. Is it technically possible?

**Comment by thea-m** [comment]
Thank you! Nice schema :) I was also wondering about whether we could achieve something similar to these layout schemes, which are very helpful in catalogues. Single texts can also continue in more than one column, and I believe also accross the borders delimitated by the images. 
In my case, we will have the images of the scrolls to be described. Could it maybe be possible to superimpose such a sketch above the real image and include this in the description? (Apart from the image viewer, in which the images will be accessible in the normal way)
Counting lines is not fun (and due to irregularities can be really difficult), but I think it's necessary, also to indicate the overall number of lines of the scroll.

**Comment by thea-m** [comment]
Everyone agreed in the meeting that these kinds of schemas are very helpful to have in descriptions. Is there a way of including them in BM? @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
no way to draw them in any sort of automated dream, no. If you make one, the image can be stored and linked / viewed, that is no problem, just like in the post above. 

If the images of a scroll will be stored by us we can also point to regions of an image and think about what to display from the images anywhere we want.

**Comment by thea-m** [comment]
To come back to the original issue about the encoding of lines in scroll descriptions - apart from the question of how practical this will be in new cataloguings, occasionally they are already provided in the description and should therefore be present in our records. I think it would be nice to do this then in a consistent way which we could include in the guidelines. There was my original  proposition here with something like
```
<locus from="1r" n="11"/>
<locus to="1r" n="18"/>
```
and @DariaElagina has used a note in the msItem:
` <note>Lines 1-24.</note>`

I have no opinion on what would be better - what would you suggest @PietroLiuzzo ?

**Comment by thea-m** [comment]
@PietroLiuzzo could you give us your recommendation for the encoding of lines in scroll?

**Comment by PietroLiuzzo** [comment]
Sorry for the delay in looking at this issue. I think the option provided by @thea-m are ok for us in principle, while I would resort to the note only if there is no other option.

It is however a tricky case and exploring the TEI  and EpiDoc guidelines did not help much for this sort of referencing. I already fired a request for help to the markup list and I will also enquire with the TEI list if I do not get replies. This case is indeed more similar to encoding of papyri and inscriptions than to our  more common encoding for manuscripts, where we benefit from a series of bespoke elements like 
`<locus>`, `<foliation>`, `<collation>` etc.

I already got a reply from Torsten Schaßan, pointing to the fact that from and to are text only, and we could have in there some more complex sequence, like `<locus from="sec3col1line40" to="sec3col1line65">sec. 3, col. 1, line 40-65</locus>`. However, implementing this would be a bit painful for me, as it would involve a lot of code rewriting, and I think it makes the incorrectness of the contents of @to and @from more likely. But if we all agree it is the right solution, let's go for it and do the necessary changes. the above example would result in an encoding like 

```xml
<locus from="1rline11" to="1rline18"/>
```
which would be supplemented in the full TEI as 

```xml
<locus from="1rline11" to="1rline18">f. 1r lines 11-18</locus>
```
and rendered as 

> f. 1r lines 11–18

I would perhaps suggest that we could use normal referencing systems which we have already in place, and which would help also in clarifying the structure of the contents on the scroll.

The `div[@type='edition']` will have the appropriate nesting of `div`s, and in this case they are definitely not "optional" or deferable as in the case of a manuscript which benefits from the description in extent and a certain level of computability of locations  based on the attributes of locus and the assumption it is made of folia. 

To represent the structure of the text with `div`s will have their own `@xml:id` and within `<msItem>` we will point to those with a `ref[@corresp]`. 

e.g., starting from the schema above, the encoding in div[type edition] of the scroll description would look like the following

````xml
<div type="edition">
    <div type="textpart" subtype="section" n="1" xml:id="sec1">
        <div type="textpart" subtype="picture" n="1" xml:id="pic1"/>
    </div>
    <div type="textpart" subtype="section" n="2" xml:id="sec2">
         <div type="textpart" subtype="column" n="1" xml:id="col1">
             <div type="textpart" subtype="text" n="1" xml:id="sec2col1text1"/>
         </div>
         <div type="textpart" subtype="column" n="2" xml:id="col2">
              <div type="textpart" subtype="text" n="1" xml:id="sec2col2text1"/>
              <div type="textpart" subtype="text" n="2" xml:id="sec2col2text2"/>
              <div type="textpart" subtype="text" n="3" xml:id="sec2col2text3"/>
          </div>
    </div>
    <div type="textpart" subtype="magicsquares" n="1" xml:id="magicsquares"/>
</div>
````

**Comment by PietroLiuzzo** [comment]
Another option of reference, given the structure, would be a canonical reference, in `@cRef`, as we already do, declared in refDecl, like @cRef="betmas:MSid123:1.2.3" or  @cRef="betmas:MSid123:sec1.col2.3" where each dot separated part of the reference after the second semicolumn is actually the n or the xml:id of the relevant section

````xml
<div type="textpart" subtype="text" n="1" xml:id="sec1">
...
<div type="textpart" subtype="text" n="2" xml:id="col2">
<lb n="1"/>
<lb n="2"/>
<lb n="3"/>
</div>
</div>
````

the syntax would be the same we already use, so we could have for @thea-m 's example a value for @cRef which is simply betmas:MSid123:11-18

**Comment by thea-m** [comment]
Thank you @PietroLiuzzo , amazing! I remember having once searched for other TEI descriptions of scrolls and not found anything...but they must exist?
I would like to check whether I undestood correctly some of the things that you mentioned (it is not always clear to me where an alternative proposition starts: how does the div structure in edition interact with the encoding of lines?)

> which would require those `<lb n="11"/>` and `<lb n="18"/>` to be there

This means that the lb elements would need to be in the record for all lines (or only for the referenced lines)?

I like the proposed structure of `<div>`s a lot, which would definitely improve the clarity of the records. Purely taken from your example, referencing this xml:ids would make the overall structure of the scroll more understandable. But how would the encoding of lines fit in this model? I understand it with the @cRef, but from you wrote it is "an alternative" and I'm sure I understand from what (the proposition by Torsten Schaßan or another one?)

I am sorry if my answer is a bit unclear, I am struggling to understand the beginning and end of different proposals in your two comments. I think that the div structuring is definitely the way to go and would follow your suggestion on the related encoding.

**Comment by PietroLiuzzo** [comment]
I am not trying to give a solution, only to provide a series of complete options, I will provide some complete proposals below, but mixtures of them are also likely, and as you will see, they still need some decision to be taken on the actual best option.

> how does the div structure in edition interact with the encoding of lines?

well, the lines are also part of the structure of the text. especially if you want or need to restart counting lines because of a new column or a new section or a new text. if you want to refer to something there must be something to refer to, however, the data type of the attributes of locus is not a pointer but text, so that we have more flexibility, i.e. it needs not to point to the exact same value of another attribute somewhere else.

> This means that the `lb` elements would need to be in the record for all lines (or only for the referenced lines)?

I would prefer all lines to be there, but I understand that this sounds pointless since there will be no text in most cases. as I tried to explain, I feel a bit different about a pointer to a folio than to a pointer to a set of lines, but I may be wrong.

> But how would the encoding of lines fit in this model? 

### proposal 1 counting `lb` and referring to `@n`
#### div edition
````xml
<div type="edition">
    <div type="textpart" subtype="section" n="1" xml:id="scroll1">
<ab>
<pb n="1r"/>
<lb n="1"/>
<lb n="2"/>
<lb n="3"/>
...
<lb n="11"/>
<lb n="12"/>
....
<lb n="18"/>
</ab>
    </div>
    </div>
````

#### possible references (EXAMPLES ONLY!)
* `<ref corresp="scroll1"/>`
* `<locus from="1r" n="11"/> <locus to="1r" n="18">` current usage, but it is a bit strange use of ours and we can do much better.... and we are in time to change, there are only 172 cases in the data at the moment.
* `<locus from="1rline11" to="1rline18">` this would add only parsing functionality to locus attributes and assume one only sequence of numbered lb elements in div type edition. this does not seam to be fitting the case exemplified by @DenisNosnitsin1970 above.


### proposal 2 parsing defined values for `@from` `@to` `@target` based on `@xml:id` and `@n`

instead of only using "1ra"-like things in the attributes of `<locus>` we will provide places to point to and thus make the content of the attribute structured and parsable. This requires the existence of the elements and attributes it refers to, more than the simple reference to a folio, recto verso and column does. 
It does not mean we have to use this everywhere, but that if a more complex value is used, than there should be the corresponding structure at least in the edition div.

#### div edition
````xml
<div type="edition">
    <div type="textpart" subtype="section" n="1" xml:id="sec1">
        <div type="textpart" subtype="picture" n="1" xml:id="pic1"/>
    </div>
    <div type="textpart" subtype="section" n="2" xml:id="sec2">
         <div type="textpart" subtype="column" n="1" xml:id="col1">
             <div type="textpart" subtype="text" n="1" xml:id="sec2col1text1">
                  <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
         </div>
         <div type="textpart" subtype="column" n="2" xml:id="col2">
              <div type="textpart" subtype="text" n="1" xml:id="sec2col2text1">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
              <div type="textpart" subtype="text" n="2" xml:id="sec2col2text2">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
              <div type="textpart" subtype="text" n="3" xml:id="sec2col2text3">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
          </div>
    </div>
    <div type="textpart" subtype="magicsquares" n="1" xml:id="magicsquares"/>
</div>
````

#### possible references (EXAMPLES ONLY!)
* `<ref corresp="#sec2col2text2"/>`
* `<ref corresp="#magicsquares"/>`
* `<ref corresp="#pic1"/>`
* `<locus from="sec2line1" to="sec2line3">`
* `<locus from="sec2col1text1line1" to="sec2col2text1line3">`

### proposal 3 the "canonicalized" references
Here we set on some standard xml:ids, not diffrently from what we do elsewhere and enforce that use: sec is always a section and contains always divs with xml:id starting with pic or col or text, etc. this may seam a small effort but it is not...

#### div edition
````xml
<div type="edition">
    <div type="textpart" subtype="section" n="1" xml:id="sec1">
        <div type="textpart" subtype="picture" n="1" xml:id="pic1"/>
    </div>
    <div type="textpart" subtype="section" n="2" xml:id="sec2">
         <div type="textpart" subtype="column" n="1" xml:id="col1">
             <div type="textpart" subtype="text" n="1" xml:id="text1">
                  <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
         </div>
         <div type="textpart" subtype="column" n="2" xml:id="col2">
              <div type="textpart" subtype="text" n="1" xml:id="text2">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
              <div type="textpart" subtype="text" n="2" xml:id="text3">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
              <div type="textpart" subtype="text" n="3" xml:id="text4">
                 <lb n="1"/>
                 <lb n="2"/>
                 <lb n="3"/>
             </div>
          </div>
    </div>
    <div type="textpart" subtype="magicsquares" n="1" xml:id="magicsquares"/>
</div>
````

#### possible references (EXAMPLES ONLY!)
* `<ref corresp="#col2"/>`
* `<ref corresp="#magicsquares"/>`
* `<ref corresp="#pic1"/>`
* `<locus from="sec2col1line1" to="sec2col2line3">`
* `<locus from="sec2col1text1line1" to="sec2col2text1line3">`
* `<ref cRef="betmas:MSid123:1.2.3">`
* `<ref cRef="betmas:MSid123:sec1.col2.3">`

I hope I managed to make my self a bit more clear, to my self as well!

**Comment by thea-m** [comment]
Thank you, it is much clearer! And you right, now is exactly the right moment to work on such changes. 
These are far too advanced discussions for me to be able to give any input on how to proceed. You seem to lean towards Proposal 2 or 3? Both seem to me equally understandable and appropriate for our needs.
(We would need to keep in mind that, as always, we would need some ways to also encode scrolls for which only minimal description is available/desired, but I'm sure that should be no problem.)

**Comment by DariaElagina** [comment]
Thank you, Pietro! These are wonderful suggestions! I can not thus undesrtand one thing: how can we refer to recto or verso in the second and third proposals?

**Comment by PietroLiuzzo** [comment]
> Thank you, Pietro! These are wonderful suggestions! I can not thus undesrtand one thing: how can we refer to recto or verso in the second and third proposals?

We keep using <pb/> as well for that, and the div structure would go on in the same way and have such a pb[n='1r'] at some point if one wants to have that.

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/issues/920

**Comment by PietroLiuzzo** [comment]
- [ ]  document in guidelines referencing structure for text and mapping of URIS to URLS with parameters which are then passed to the DTS API

**Comment by PietroLiuzzo** [comment]
- [ ] add parsing support for lines in iiif.xqm module where `@from, @to and @target `are parsed
- [ ] add parsing support for lines in locus.xslt where `@from, @to and @target `are parsed
- [ ] update in data `locus[@n]` and its double occurrences to use the expanded syntax for referencing
