### ISSUE TITLE
typos in the text of LIT2000Mazmur

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1165]
can we correct typos in the text of LIT2000Mazmur?
In tPs151, l. 6 it should be ለተኣኅዞቱ instead of ለተኣኅዞቲ
@PietroLiuzzo ?

**Comment by thea-m** [comment]
@PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
please go ahead. this correction is one of the cases in which a direct commit is in order IMHO.
