### ISSUE TITLE
markup of line take ups

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1166]
How can we mark up line take ups (and -downs) in text (for example in Psalter manuscripts)? 
`<add place="above">` does not to fit here, because it suggests a later addition above the line, while the line take up happened during the writing process when not enough space was left to finish the line. Neither `<add>` nor `<hi>` seem suitable elements to me. 
We might decide not to mark these up at all, but since their presence is also noted in Extras, it seems to be of enough interest to warrant a way of encoding it when occurring in text we are transcribing. Or is it not necessary at all? @DenisNosnitsin1970 ?
@PietroLiuzzo ?

**Comment by thea-m** [comment]
or maybe `<hi>` with specific values would be ok, since they are "graphically distinct" from the surrounding text?

**Comment by thea-m** [comment]
would it also be useful to mark up reduced script in text? As with the line take ups, I'm really not sure whether it adds something to the already existing mention of the phenomenon occurring in the manuscript with examples in Extras. But it might make sense to have the possibility?

**Comment by thea-m** [comment]
what do you think regarding the usefulness of marking up these phenomena in transcribed text? @DenisNosnitsin1970 @DariaElagina @sologebre ?

**Comment by PietroLiuzzo** [comment]
I have no idea what a line take up or down is. can you link to an image or explain me?

**Comment by thea-m** [comment]
Sorry!
![image](https://user-images.githubusercontent.com/19650382/59026865-badba580-8857-11e9-806c-61d9f0f990b3.png)
At the end of the third line of this image, no space was left for the last character and it was written above the line. It is not a later addition. This is common in psalters, and there can also be decorated signs highlighting the concerned characters.

**Comment by thea-m** [comment]
It was decided in the meeting that this is indeed a relevant feature to mark up in text. This brings us back to the encoding: Would `<hi>` with new values make sense here, or is there a better alternative? @PietroLiuzzo

**Comment by thea-m** [comment]
What do you think, @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
I do not know. I will ask on the TEI list.

**Comment by DenisNosnitsin1970** [comment]
<hi> would make sense, in my opinion.

**Comment by PietroLiuzzo** [comment]
I agree it is a feature, and I sent this message to the TEI list for advice. I think among the many things we already encode this would not add much in any case. How many would we be able to encode? and when we have encoded 10.000 what do we do of this? does it really tell something interesting? what sort of search or highlighting would you expect in the visualization (which will never attempt to reproduce this phenomenon as it is on the page)?

**Comment by PietroLiuzzo** [comment]
The TEI list has spoken. 

I am not sure how many of you have followed that, so, here my summary:

- recommendation one: really consider if it is worth (see my comment above)
- use <hi> element
- use <seg> element with `@type=“turnover|turnunder”`
- use <seg> with `@rend="above|below"`

I think, if after all we really want to embark into this further encoding specification (but then I would really want to see some hundreds to be marked up and somebody using this feature for her / his research), then <seg> has the best call, and I would prefer `@rend` over `@type`.
We can in any case add a recommendation in this sense in the GL, but since the way GL are taken is always prescriptive rather than descriptive, i.e. people feel they have to mark all what is accounted for in the guidelines, which is quite far from true, I would consider this. On the other side we do have already plenty of such cases and it is not this one which will make a real difference.

**Comment by thea-m** [comment]
Thank you!
It would be potentially marked up in many records, since since is a feature common to most Psalter manuscripts, whose incipits etc. we often transcribe. I don't know if anyone would use this right now for research (I wouldn't), but I see this feature on the same level as others broadly belonging to scribal practices which we do encode (rubrications, corrections etc.) and in which there is interest. What do you think, @DenisNosnitsin1970 ?
If the guidelines are taken as prescriptive, then we have simply to be clearer on this in workshops etc. Looking at the records encoded by any project member, I think it would be hard to find one that actually encoded everything mentioned as encodable in the guidelines.
I just suggested `<hi>` because this is what we have used for similar cases, if `<seg>` is seems better to you, let's use that.

**Comment by PietroLiuzzo** [comment]
all you have to do is go on and edit the GL, adding an example (e.g. the one above) possibly with an image linked to explain it as here. as said, I think the best choice, although my second preferred would be `hi[@rend]`.

**Comment by DenisNosnitsin1970** [comment]
In my opinion, there should be a possibility to refer to the general presence of the feature, and, for an advanced level and specialized research, the possibility to encode each specific case. It is a scribal practice (but more individual than rubrication); actually we do not know how to interpret this at the moment, but someone will certainly deal with it one day.

**Comment by thea-m** [comment]
I will add it to the guidelines
