### ISSUE TITLE
Description of a fragment

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1169]
Dear all,
I am a little bit puyzzled with a description of a manuscript of which only two leaves are preserved. What should be put in objectDesc? I could not find such a case in the guidelines.

**Comment by thea-m** [comment]
Can you use "leaf", and then give 2 in the dimensions?

**Comment by DariaElagina** [comment]
This is a possibility, and then I just describe the state in the condition?

**Comment by thea-m** [comment]
I would probably do it like that, because it really is not a codex anymore.maybe you could also work with SdC relations, if you can clearly see that it used to be part of a codex?

**Comment by DariaElagina** [comment]
Ok, thank you!
