### ISSUE TITLE
new calendar view

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1171]
we want to produce data relevant for readings organized along the ethiopian calendar.
- [x] the value 'commemoration' with a definition will be added by @thea-m to the open list for the values of subtype of `<div>`
- [x] a TEI file with a `<list>` of the month's names and the days in each month will be created and stored in the app with the following format inside `<body>` 
```xml
<list>
     <item xml:id="monthname">monthname
         <list>
            <item xml:id="monthname1">day of the month</item>
            <item xml:id="monthname2">day of the month</item>
           ...
         </list>
     </item>
<item xml:id="monthname2">monthname2
         <list>
            <item xml:id="monthname1">day of the month</item>
            <item xml:id="monthname2">day of the month</item>
           ...
         </list>
     </item>
....
</list>
```

this will be called ethiopian.xml and will be stored in the app as a static list

- [x] guidelines need to be updated to add the encoding of this recurring dates in the texts and manuscript transcriptions, as <date calendar="ethiopian" ref="cal:monthname1">nodes of the date in the text</date>
- [x] a `<prefixDef/>` needs to be added to point to the calendar file
- [ ] the RDF needs to be transformed correctly creating for each day an entity (as a static set o triples) and pointing each div to the corresponding URI in data2rdf.xsl
- [x] a view will be added to resources which
   - provides a view of this calendar file
   - clicking on each day a search for divs in works containing a `<date/>` with `@ref` equal to the value of the xml:id of the given day and the type of calendar (there might be others) will be run to return all works which refer to such date in this way (withough @when, @notBefore, @notAfter!)
    - for each work a list of manuscripts with the corresponding msItems and eventually divs which link to them will be given, each of which lists the commemorations for that day.
    - commemorations (`div[subtype='commemoration']`) might be linked to narrative units, in which case a link will be offered to the narr unit.

**Comment by thea-m** [comment]
I added the value commemoration to the schema, but could not transform it.

**Comment by PietroLiuzzo** [comment]
since my changes to the TEI stylesheets where accepted, you should actually be able now, simply updating the TEI stylesheets. I will do this now.

**Comment by PietroLiuzzo** [comment]
received the file from @thea-m  and stored in the application in a calendars collection

**Comment by PietroLiuzzo** [comment]
as it turns out from the TEI list, we have been using calendar in the wrong way. here what James Cummings wrote

> I notice where you have calendar="ethiopian", I'd point out that the calendar attribute uses the teidata.pointer datatype, which means it should be a URI (or fragment). Thus this is technically saying there is a file in the same directory called 'ethiopian'. (Which indeed there might be for all I know.) But presumably it might also be '#ethiopian' pointing to a <calendar> inside a <calendarDesc> in the header.  I'm only pointing it out because I've seen a lot of other projects' files specify calendar just as a string and not realise it should be a pointer. ;-) 

I will ahve to add calendar and calendarDesc to all files with XInclude #1069

**Comment by PietroLiuzzo** [comment]
I have started to set up things for calendarDesc to be used.
- [ ] all occurrences of calendar="\w will have to be replaced by calendar="#\w
- [ ] in `<profileDesc>` the new xi:include element should be added, like
```xml
<xi:include href="https://raw.githubusercontent.com/BetaMasaheft/Documentation/master/calendarDesc.xml">
            <xi:fallback>
               <p>Calendars definitions.</p>
            </xi:fallback>
         </xi:include>
```
as in #1069 
this requires the addition of the namespace for xinclude in the header.
all files need to be updated for this.

**Comment by PietroLiuzzo** [comment]
this issue is much larger. it affects most of the attributes which we use with simple strings from the schema and are in teidata.pointer datatype. https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.pointer.html
This is valid to our local schema where the attributes are replaced with local definitions which only take a value from a fixed list.
Some of these, like ref are fixed in the post.xsl so that the exported TEI is correcter (not in all cases, like this calendarDesc is not considered)
so, it might remain an option to leave with it, but make the export correct.

the xi:include solution is very painful, see comment above, plus needs a full review of the code which deals with dates.
examples with xi:include 
https://betamasaheft.eu/IHA0968 and https://betamasaheft.eu/RIE189

**Comment by PietroLiuzzo** [comment]
Also the values in `@who` need to be prefixed and point to the editors file using `prefixDef`.
James Cummings suggested to 

>  in the working version use prefixDef to define prefixes so you can have things like contrib:ES or cal:hijri and have those point to local shared files between all files. Then when generating the full TEI version you resolve all those pointers and include things like pointed to bibliographic items, contributor's respStmts, calendarDesc etc.

**Comment by PietroLiuzzo** [comment]
calendar and who are now fine in the postprocessed file, while they are documented in their use by our customization. The calendarDesc element is added only if there is any attribute calendar.
the list of editors is populated with additional respStmt with xml:id for each author of a change which is not mentioned there as editor. every resp and who point to the id of editor or respStmt, which both contain the expanded form of the name from editors.xml and a link to the team page.

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/calendar

**Comment by PietroLiuzzo** [comment]
@thea-m when you have sometime you could try to enter some of these 
````xml
<date ref="ethioCal:Maskaram1">
         1st Maskaram
  </date>
````

so that we see if the dates search behaves as expected and we can tailor it?
thanks

**Comment by thea-m** [comment]
I marked up 2nd Maggabit in LIT4033Senkessar, EMML6952 and ESqdq004, but the search shows no results:
https://betamasaheft.eu/calendar?day=Maggabit2
MAybe I encoded in the wrong name.
And the guidelines have "You can align a commemoration to a day in the calendar, without that being a specific day in history using @calendar and a @ref like in the following example.", but the @calendar isn't used in the example?

**Comment by PietroLiuzzo** [comment]
guidelines were wrong

**Comment by PietroLiuzzo** [comment]
also the script is correct now, please have a look @thea-m, since this is the totality of instances, you should not even need to add parameters

**Comment by thea-m** [comment]
thank you, it works now!
