### ISSUE TITLE
Corrections by Jeremy Brown

### ISSUE THREAD

**Issue by AngelaMueller** [BetaMasaheft/Documentation#1174]
How shall I mark the corrections made by Jeremy Brown?
I thought about this way:
```xml
ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ፊንቄ፡ ዘስሙ፡ ባሮክ፣ 
                     ጠዋይ፡ ዘአልቦቱ፡ ምግባረ፡ <choice resp="Jeremy Brown"><corr>ሠናይ፡</corr><sic>ሠነይ፡</sic></choice> ዘያሠምሮ፡ ለእግዚአብሔር፣
                     ከመ፡ ይስረይ፡ ኃጣውኢሁ።
````
```xml
ወሀሎ፡ አሐዱ፡ አብ፡ ቅዱስ፣ አባ፡ አብርሃንም፡ ሶርያዊ፣ ሊቀ፡ ጳጳሳት፡ ዘሀገረ፡ እለ፡ <supplied resp="JeremyBrown" reason="omitted">እ</supplied>ስክንድርያ፣
                        ወውእቱ፡ እምኍልቆሙ፡ ለአበው፡ ሊቃነ፡ ጳጳሳት፡ ፷ወ፪።
                        ዝንቱ፡ አብ፡ ኮነ፡ እምነ፡ ክርስቲያን፡ ዘብሔረ፡ ምሥራቅ፡ ወኮነ፡ ነጋዴ።
```

Then, however, it will not be marked, that these changes are made based on mistakes in the Macomber list.
And: Jeremy Brown is not an ID yet.

Any ideas? Suggestions?

Thanks in advance!
Angela

**Comment by PietroLiuzzo** [comment]
You cannot have anything in `@resp`, see examples in the pages linked here https://betamasaheft.eu/Guidelines/?id=@resp
You can avoid adding resp in each correction, if you can simply add a statement about this in your `<change>` element or in `<editionStmt>`

**Comment by AngelaMueller** [comment]
Found another solution.
Marked the changes as usual and added <change who="AM" when="2019-04-24">corrections by Jeremy Brown</change>
Alright?

**Comment by PietroLiuzzo** [comment]
could you please post a link to an example of your solution?

**Comment by AngelaMueller** [comment]
Yes, i tried already, but it was not posted...
<revisionDesc>
         <change who="PL" when="2016-11-17">Created XML record from Ethio authority google spreadsheet</change>
         <change who="MV" when="2017-03-31">Added keywords and relations</change>
         <change who="DR" when="2018-11-16">Added keyword, title and Macomber reference</change>
         <change who="AM" when="2019-04-30">added text</change>
         <change who="AM" when="2019-06-24">correction by Jeremy Brown</change>
      </revisionDesc>

<div type="edition">
             <div type="textpart" subtype="incipit" xml:lang="gez">
               <note>This incipit is taken from <ref type="mss" corresp="EMML3872"/>.</note>
                 <ab>
                     ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ፊንቄ፡ ዘስሙ፡ ባሮክ፣
                     ጠዋይ፡ ዘአልቦቱ፡ ምግባረ፡ <choice resp="PRS6437Macomber"><corr>ሠናይ፡</corr><sic>ሠነይ፡</sic></choice> ዘያሠምሮ፡ ለእግዚአብሔር፣
                     ከመ፡ ይስረይ፡ ኃጣውኢሁ።
                 </ab>

**Comment by AngelaMueller** [comment]
> <revisionDesc>
         <change who="PL" when="2016-11-17">Created XML record from Ethio authority google spreadsheet</change>
         <change who="MV" when="2017-03-31">Added keywords and relations</change>
         <change who="DR" when="2018-11-16">Added keyword, title and Macomber reference</change>
         <change who="AM" when="2019-04-30">added text</change>
         <change who="AM" when="2019-06-24">correction by Jeremy Brown</change>
      </revisionDesc>

**Comment by AngelaMueller** [comment]
> <div type="edition">
             <div type="textpart" subtype="incipit" xml:lang="gez">
               <note>This incipit is taken from <ref type="mss" corresp="EMML3872"/>.</note>
                 <ab>
                     ወሀሎ፡ አሐዱ፡ ብእሲ፡ በሀገረ፡ ፊንቄ፡ ዘስሙ፡ ባሮክ፣
                     ጠዋይ፡ ዘአልቦቱ፡ ምግባረ፡ <choice resp="PRS6437Macomber"><corr>ሠናይ፡</corr><sic>ሠነይ፡</sic></choice> ዘያሠምሮ፡ ለእግዚአብሔር፣
                     ከመ፡ ይስረይ፡ ኃጣውኢሁ።
                 </ab>

**Comment by PietroLiuzzo** [comment]
I do not understand your second example, resp is on the choice, should it not be on corr or sic? dependenig if macomber is responsible of the correct or wrong version?

**Comment by AngelaMueller** [comment]
Yes, I get your point. I'll check it again and let you know.

    Am Freitag, 28. Juni 2019, 10:40:31 MESZ hat Pietro Liuzzo <notifications@github.com> Folgendes geschrieben:  
 
 
I do not understand your second example, resp is on the choice, should it not be on corr or sic? dependenig if macomber is responsible of the correct or wrong version?
