### ISSUE TITLE
use of IDs in work editions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1175]
would it be possible to visualize the IDs to works given in corresp in the textparts of LIT5673AkkonuColl? It is encoded like this:
```
  <div type="textpart" xml:id="AkkMir2" corresp="LIT3588Miracle">
                        <label>Miracle</label>
                    </div>
                    
                    <div type="textpart" xml:id="AkkSta2" corresp="LIT4274AkkonuB#Stanza2">
                        <label>ʾAkko-nu bǝʾsi stanza</label>
                    </div>
                    
                    <div type="textpart" xml:id="AkkMin2" corresp="AT1109MMWorker">
                        <label>Miniature</label>
                    </div>
```
Currently, the IDs given in corresp are not rendered anywhere on the app. Could the text given in label become a link to these records? Or could they be printed next to it?
If it would be preferable I could of course also include a `<ref>` with @corresp to the respective ID in `<label>`, which would solve this. But I think that this kind of encoding (with @corresp in the `<div>` and no ID used in `<label>`) has been used quite often, if it is not desirable I might add an example to the guidelines.
@PietroLiuzzo ?

**Comment by thea-m** [comment]
I'm not sure if it's related, but it would also be nice if the use of AT1108MMDaqseyos in LIT5673AkkonuColl would be picked up on the page of AT1108MMDaqseyos  with "show attestations"

**Comment by PietroLiuzzo** [comment]
ok, now that is also done

**Comment by thea-m** [comment]
thank you, it's perfect!
