### ISSUE TITLE
parallel versions view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1176]
Does the view of parallel versions (encoded with narrative units) work?
The pelican in Physiologus was our example, right? When I click on "versions" in https://betamasaheft.eu/works/LIT4916PhysB/text, nothing happens

**Comment by PietroLiuzzo** [comment]
only chapter with the pelican has parallel version. did you check that?

**Comment by PietroLiuzzo** [comment]
versions are shown correctly clicking on version at the link you provide. they are output below the current text section.

**Comment by thea-m** [comment]
sorry, I didn't scroll down! Yes, I know it's the only one.
