### ISSUE TITLE
transliteration አርባዕቱ

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1177]
Leslau has ʾarbāʿəttu, Mittwoch ʾarbāʿtu, which is what I would tend towards. In our records, there is also often ʾArbāʿǝtu, inherited from the EAE. What do you suggest?

**Comment by abausi** [comment]
I agree with you and suggest: ʾarbāʿtu

**Comment by thea-m** [comment]
thank you, I updated https://betamasaheft.eu/Guidelines/?id=dubious-spelling
