### ISSUE TITLE
filter persons by keyword

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1178]
I would like to filter the persons view by keyword, but it seems not to be possible, there are 0 results here, for example https://betamasaheft.eu/persons/list?mainname=&date-range=0%2C2000&cp=&keyword=biblical

**Comment by PietroLiuzzo** [comment]
I will have a look at this. in the mean while, you get the very same from here 
https://betamasaheft.eu/authority-files/list?keyword=biblical

**Comment by thea-m** [comment]
thank you!

**Comment by PietroLiuzzo** [comment]
please try this again.
