### ISSUE TITLE
languages on the app 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1179]
I noticed in the languages offered when filtering by languages, for example in the advanced search, the random use of Italian (Inglese and Italiano) and the wrong "Deutsche", which are a bit strange. These were probably stated in some records by us, but I don't know where. Could all languages be given consistently in English or English/self designation?

**Comment by PietroLiuzzo** [comment]
it is easy to xpath for this. I have fixed the wrong Deutsche
there are many more italiano and inglese (e.g.)
https://betamasaheft.eu/xpath?xpath=$config:collection-root//t:language[.=%27Italiano%27]&start=101
which I can fix during data freeze

**Comment by thea-m** [comment]
that would be helpful, thank you!

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Works/commit/eed5e03b3ec15ceb77934696194fbd8619c8389e

**Comment by PietroLiuzzo** [comment]
@thea-m could you check if this is fine now and in case it is close the issue? I have checked and I think it is ok, but I want to be sure. thanks

**Comment by thea-m** [comment]
In the advanced search, there still is Inglese and Deutsche, and in the persons view filter, still Italiano and Inglese

**Comment by PietroLiuzzo** [comment]
sorry, I had forgotten to update the static list for the menus after updating the data
