### ISSUE TITLE
narrative units classified as manuscripts in search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1185]
search results in narrative units are classed as manuscripts, for example:
https://betamasaheft.eu/as.html?query=pelican&homophones=true&AttestedInType=1&xmlid=
The resulting link is of course not working
https://betamasaheft.eu/manuscripts/NAR0013pelican/main

**Comment by PietroLiuzzo** [comment]
well spotted! an extra r!
