### ISSUE TITLE
subtypes for colophon/titles

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1186]
I guess the subtypes should be, as in the issue above, and as discussed, 
inscriptio
subscriptio
(as correctly featured in the example in the guidelines,   `<div type="textpart" subtype="title inscriptio" xml:id="Title">`
)
(not inscription / subscription as in the text of the guidelines and now in the schema)

can this be harmonized? thank you

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/946#issuecomment-507221714_

**Comment by PietroLiuzzo** [comment]
the reason I have changed this is that these were already used in the english form in the data. I can change this overall in data and schema, but I would not see too much the point since it is consistently a list of values in english which we are using. could you please document here the reason why these should be inscriptio and subscriptio? I will for the moment update the example in the guidelines to have the correct value. (adding a link to the page of the guideines you are speaking about gives you 2 + points ! )

**Comment by eu-genia** [comment]
This was discussed last year with Antonella who pleaded for Latin terminology also used by Buzi. Also to avoid homonymy with inscription in the sense epigraph. There were other reasons but dont remember now, @abausi might remember better.
In the title view one can see inscriptio in bm data.

**Comment by PietroLiuzzo** [comment]
thanks for the clarification.
I will then update data and schema and remove those n

**Comment by abausi** [comment]
...cannot react, sorry..., but I think Zhenia is right

Il 01.07.2019 14:00, Pietro Liuzzo ha scritto:
