### ISSUE TITLE
invalid files in oxygen

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1187]
all (?) my records in oxygen are marked as invalid, the error message is "value of attribute "ident" is invalid; must be a string matching the regular expression "[a-z][a-z0-9\+\.\-]*"", when I click on it prefixDef.xml opens on  prefixDef ident="ethioCal" and with the error message "element "listPrefixDef" not allowed here; expected element "TEI" or "teiCorpus""
Did I miss something? as far as I know I synced everything

**Comment by PietroLiuzzo** [comment]
that was just me giving a wrong prefix. now the included file is updated with https://github.com/BetaMasaheft/Documentation/commit/2fdf54771713b7f15bf6ba7ca4a7487cbb81ab64#diff-0be04d1effd389c6b499020e5ccacade and also the code using that prefix. I suspect however that it will take a bit for this to be understood by oXygen which has imported the fragment already

**Comment by PietroLiuzzo** [comment]
yep, just quit oxygen and restart it, it will pick up the corrected file for validation

**Comment by thea-m** [comment]
now it's fine, thank you!
