### ISSUE TITLE
problem with new person record creation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1189]
I cannot create new person records anymore

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <exception>
> <script/>
> <path>/db/apps/BetMas/edit/save-new-entity.xql</path>
> <message>
> exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 583, column 19]
> </message>
> </exception>

I've cleared the cache and tried in chrome and firefox

**Comment by PietroLiuzzo** [comment]
please try again, I have refreshed the permissions and tested creating a record as you, and all went well

**Comment by thea-m** [comment]
works now, thank you!
