### ISSUE TITLE
"more than one..." keyword

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1191]
In the keyword filter in the advanced search, several keywords cannot be chosen because there are "more than one": Genealogy, Subscription, Doxology, Oromo, Translation, Prayers, Baptism, Daqseyos, MadhaneAlam, PalmSunday
I'm not sure about the reasons for this and don't want to start wildly editing the schema and taxonomy...

**Comment by PietroLiuzzo** [comment]
this values can indeed be chosen any way. It is only the label which cannot be produced and the reason for this is that the values have been added as xml:ids of divs or other elements in other files.
