### ISSUE TITLE
versions view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1193]
The parallel versions button is available on manuscript and work pages, but seems not to work for manuscripts (again, the pelican, here for example https://betamasaheft.eu/manuscripts/BNFabb247/text?per-page=107 ). If the versions view is supposed to be available only from work pages, could the button on manuscript pages be deleted? Though I think that nothing speaks against keeping it, if it would work.

**Comment by PietroLiuzzo** [comment]
it cannot work for two reasons:
- there are no versions of a manuscript
- there is no explicit link in this file between the msItem and the div
i have removed the button
