### ISSUE TITLE
gender visualization on persons pages

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1194]
Currently, gender is not in any way visualized on persons' pages, as far as I can see. While this is extremely useful in the many cases of our records which have the wrong gender assigned, it would be theoretically nice to keep this information visible for those not reading the XML records. Didn't we use to have an icon for that somewhere next to the namebox or the main name?

**Comment by PietroLiuzzo** [comment]
yes, the icon simply was not supported anymore, I have replaced it now with the font-awesome correspondent.
