### ISSUE TITLE
alignment to iconclass

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1198]
Art themes, objects and subjects should be aligned to iconclass, which is used by several other projects.
e.g. 
http://iconclass.org/rkd/11F4/
https://corpusvitrearum.de/id/11F4

**Comment by thea-m** [comment]
cool! i used to always walk past the church windows project in potsdam :)

**Comment by PietroLiuzzo** [comment]
in https://betamasaheft.eu/AT1026NativityMary I have added 
````xml
  <listRelation>
                <relation 
                       name="skos:exactMatch" 
                       active="AT1026NativityMary" 
                       passive="ic:73A31"/>
</listRelation>
````
and some modules updates to provide a link to a list of related items from Europeana.
adding other such alignment would automatically produce the link in the authority file view. 
it would have been nice to transclude them and a module is already available but the sparql resulst are over http and we cannot load them directly

**Comment by PietroLiuzzo** [comment]
@Gnisci I would add this to the guidelines, if that sounds fine to you as well. specifying in the guidelines that the it is not necessary to use skos:exactMatch, other relations which relate our Art Theme or object, or keyword to the Iconclass classes are also fine (broadMatch, closeMatch, relations of other kind...)

**Comment by Gnisci** [comment]
Dear Pietro, sounds like an excellent idea. I would specify to check if an AT is existent in Iconclass before creating it (though the Ethiopian tradition has a few ATs which will not be in ICONCLASS) it will prevent the situation that happened with Ralph Lee, where he was creating ATs that had no background in the existing literature.

**Comment by PietroLiuzzo** [comment]
I will draft the guidelines page and ping you as a reviewer. thanks!
