### ISSUE TITLE
Education encoding

### ISSUE THREAD

**Issue by antobrita** [BetaMasaheft/Documentation#1201]
I noticed that among the child elements of `<person>` in BM there is no field for encoding `<education>`. The element `<floruit>` is already overcrowded to additionally host also this information. It would be important to include this element, which is already present in the TEI guidelines (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-education.html). @PietroLiuzzo @thea-m @sologebre

**Comment by PietroLiuzzo** [comment]
the element education can now be used (it was excluded from the schema) and viewed in the person view. however, it is not indexed in any way and until there will be attested usage of it in the data I will avoid doing that.
