### ISSUE TITLE
Affiliation encoding

### ISSUE THREAD

**Issue by antobrita** [BetaMasaheft/Documentation#1202]
I would like to encode the following information from an EAE entry: 

> "When the Italian war 1935-36 started, Š.G. became organizer of the Ethiopian Women's Work Association [...] and Š.G. the vice-president".

I thought to proceed in the following way:

`<floruit>`    `<child element no. 1>` `<child element no. 2>` `<date from="1935" to="1936"></date>` and to encode the second part of the above information in the element `<affiliation>`. Am I allowed to do it? The element `<affiliation>`, although present in TEI guidelines and also in BM's drop down menu, has not been so far used in BM. @PietroLiuzzo @thea-m @abausi

**Comment by PietroLiuzzo** [comment]
as in the case of education in #1201 this is a matter of decision from you and the team about how to encode. for the use we currently make of this information, there is nothing preventing but also nothing requiring us to use this specific element for which we would have no specific use. the same information can be given as string encoding dates and names in floruit or in other parts of the person record, without using affiliation. You are free to use it if you want and we can see if other encoders will pick up on that, in which case we will see what to do with that information.
