### ISSUE TITLE
facs attribute for ES images

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1203]
It is not clear to me from the guidelines how to find the correct value to put in @facs when referring to images of Ethiospare manuscripts, for example ESmhg013. Where can it be found?
@simseybo

**Comment by thea-m** [comment]
it can only be found in the domlib database by people who have an account there
https://mycms-vs03.rrz.uni-hamburg.de/domlib/content/main/manuscript/manuscript.xml

**Comment by PietroLiuzzo** [comment]
the above is untrue for images already available in BM

**Comment by PietroLiuzzo** [comment]
the image number in the viewer on BM  should be fine.
