### ISSUE TITLE
encoding of "Dr"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1204]
how can we encode this correctly? Did someone need it before?

```xml
<persName xml:lang="de" xml:id="n1">
                        <roleName>Dr</roleName>
                        <surname>Omansen</surname>
                        <forename>Eva</forename>
                    </persName>
```
@sologebre @PietroLiuzzo

**Comment by thea-m** [comment]
as I could have known, and a kind e-mail usefully reminded me of, a @type is needed in roleName. Will the value be "title"?

**Comment by sologebre** [comment]
It's a good idea. So far, we only encoded the traditional civil and military titles that are actually attested in various Gǝʿǝz historical texts as well in manuscripts. We do not find any of modern academic or military titles prefixed to a person in Gǝʿǝz texts, but in the description of the names of persons in modern times we can encode these titles in person record description. But the relevance of ecoding these modern academic or military titles needs first further discussion.  
	TEI guidelines offer a possible way to mark these academic or military titles. The guidelines states that such academic title or military can be encoded with the element <roleName> with @type and a value “honorific” (academic or other honorific prefixed to a name e.g. Doctor, Professor, Mrs., etc.). So we will then add the value “honorific” in our schema and update the guidelines so that any interested encoder can mark such academic titles and military ranks.
