### ISSUE TITLE
visualization of collation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1207]
I was wondering whether the element `<collation>` would maybe be better visualized as "quire structure" on the app? In our context, "collation" is somewhat misleading. What do you think?
@DenisNosnitsin1970 @DariaElagina @sologebre

**Comment by DenisNosnitsin1970** [comment]
Why is it misleading?

**Comment by thea-m** [comment]
many people think of the textual collation that is part of an edition process

**Comment by sologebre** [comment]
Yes, you are right. Actually, TEI also uses the term collation (contains a description of how the leaves, bifolia, or similar objects are physically arranged). So, it is preferable to keep the terminology of the TEI. But to avoid any misunderstanding, I would suggest that we can add the point that collation  means "quire structure" as an additional clarification in our guidelines.

**Comment by DenisNosnitsin1970** [comment]
I see. I am also of the opinion that some ambiguity may emerge, but on the other hand "collation" is the standard professional term, https://schoenberginstitute.org/2014/10/01/visualizing-the-construction-of-manuscripts-through-collation-and-video-digipal-iv-symposium/.

**Comment by thea-m** [comment]
I was really talking purely about the visualization of the app, obviously we use this element because it is TEI, and there is nothing at all wrong with it. It is like the floruit-period of activity issue. I just noticed that this confused people at all workshops we gave.

**Comment by DenisNosnitsin1970** [comment]
Do you mean - looking at collation visualization they though it is the textual collation?

**Comment by thea-m** [comment]
Once they clicked on the diagrams or formulas, they understood immediately. But the term lead always to bis surprise.  How about we use "Collation (Quire Structure)"?

**Comment by sologebre** [comment]
That is perfect!

**Comment by DenisNosnitsin1970** [comment]
I would stay with one term. No further hierarchy and complications with ( ) or / on the surface (it is already complex enough containing scripts of different sizes etc).

**Comment by thea-m** [comment]
From the meeting: It should be changed to "Quire Structure" with "Collation" appearing on hovering. 
@PietroLiuzzo
