### ISSUE TITLE
visualization of physical description

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1209]
It was decided in the meeting that it would be desirable if the "Physical Description" section in manuscript pages on the app would be somewhat highlighted or easier to immediately see for users.
To begin with, it would already be helpful if Form of Support and Extent were visualized below "Physical Description". 
A suggestion was to highlight the entire physical description section by colour (which I think will again contribute to visual overload on the page), my suggestion was not to have the summary on top, so that the physical description would be immediately visible (but many people want and use the summary). Other good ideas are welcome :)

**Comment by PietroLiuzzo** [comment]
I will do this change once there is agreement on a model. thanks.

**Comment by thea-m** [comment]
Do you have a good idea for this? I really think that the "let's colour whatever we are thinking about right now" is what let to the visual overload of the last design. But if there are no other suggestions, we will have to do it like this.

**Comment by PietroLiuzzo** [comment]
With regard to this issue, I would like to suggest the above small changes to the manuscript view, beside the requested change to the position of the title Physical description (which I will capitalise, as above, same for watermark), I have
- moved the summary into the main block 
- added a border to the Physical description
- limited the height of the summary to 400px, after which overflow will be scrollable
- moved the attestations button with other buttons for that area

Please @abausi  @eu-genia @thea-m @DariaElagina @DenisNosnitsin1970 @Ralph-Lee-UK give your feedback.

**Comment by Ralph-Lee-UK** [comment]
This looks like a good development to me, clear presentation, without overloading the system.
