### ISSUE TITLE
rubrication formalization

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1211]
born in the discussion of #1144
It has been decided in the meeting that a more formalized (and eventually filterable and searchable) encoding of rubrication would be desirable. 
As a first step, categories of rubrication have to be identified. For now, the following were mentioned:
- beginnings and titles
- Divine names
- names of donors
- elements of punctuation
- (elements of) digits
- other nouns
Are there others? @DenisNosnitsin1970 @DariaElagina @sologebre @eu-genia 

Then, a good way of encoding these has to be developed. Maybe by the use of keywords? Could the description then be compared to that of bindings? @PietroLiuzzo 

Finally, it would be desirable to be able to refer to rubrication systems, particularly those of the passages at the beginning of works with a single string, comparable to Muzerelle's system for ruling. Such a system could be developed in the future.

**Comment by DenisNosnitsin1970** [comment]
Titles perhaps separate, in the very beginning.

**Comment by DenisNosnitsin1970** [comment]
There is some controversy as to what is to be considered as "title". Those specifically rubricated are like the titles appearing in MA-010, here as "running title", frequently only on the incipit page.

**Comment by DariaElagina** [comment]
I am not sure, but I think that abbreviations are sometimes rubricated as well.

**Comment by eu-genia** [comment]
Here is e.g. from ESamq017 (just by chance, the one I have last opened), 

> Nomina sacra; a few lines on the incipit page; two
>                            (occasionally three) initial lines of Texts I-1-12; **names of
>                            supplications, antiphons and chants, and their abbreviations** (e.g.,
>                            mastabqʷǝʿ, mǝqnāy, mǝlṭān, mazmur, salām, ʾaryām, qǝne); **initial words**
>                            of supplications, antiphons and other chants, and their sections (e.g.,
>                            ḥǝli, yǝtbārak, säbbǝḥǝwwo, gǝnäyu, täśahalänni, nǝsebbǝḥo, ʾantä,
>                            täkäśtä, sǝmʿanni); **names of feasts** and other occasions; **musical notation
>                            signs**: intratextual (e.g., yǝgäbru, qāla ʿawadi, ʾaklilä), interlinear
>                            (e.g., fols. 13va-16rb, 57va-67rb) and marginal (entire and elements);
>                            **names of the categories of melody** ʿǝzl, gǝʿǝz, ʾararay; directives for
>                            the ministers (e.g., ǝm-qǝdmä, wa-dǝḫrehu, wa-ʾǝmzǝ, ʾǝm-lǝdät,
>                            ba-zamana); tamallas signs on fols. 20va l.19 and 61vb l.16; Ethiopic
>                            numerals or their elements; elements of the punctuation signs.
> 
It also has an addition "Very often only initial letters of words are rubricated." - how do we formalize this?

**Comment by DenisNosnitsin1970** [comment]
It is probably still the "incipit rubrication". The first letter of the first ward in a subsection.

**Comment by eu-genia** [comment]
I understood it in the way that only g is red in gǝʿǝz

**Comment by DenisNosnitsin1970** [comment]
Do you have the folio number? It may be an abbreviation of the melodic category.

**Comment by DenisNosnitsin1970** [comment]
gǝʿǝz

**Comment by eu-genia** [comment]
I copied above the text as it is given in AMQ-017.

**Comment by eu-genia** [comment]
Another example from a liturgical AKM-007, just to fill the list of categories:

> Nomina sacra; **name of the king**; incipit of Texts
>                            I-II; **titles of the books to be read**; **directives for the ministers and
>                            their abbreviations**; elements of the punctuation signs; Ethiopic
>                            numerals.

**Comment by eu-genia** [comment]
maybe "other words" instead of "other nouns". e.g. esagged is often red, it is not a noun, but it would be probably too much to divide by all parts of speech.

**Comment by DenisNosnitsin1970** [comment]
It is better to try to collect the categories after the categories of the books. Psalters, Gospels, Synaxarions, Missals etc. Chant books may be the most difficult.

**Comment by PietroLiuzzo** [comment]
I took this on some times ago, and now see it is an old friend. well, it is never too late... I think using `<term>` as we do in the binding description or in decoNote would be a fine option.  
- [ ] the taxonomy needs to be updated with the list of desired values, if not already there
- [x] the XSLT transforming this will already print those as in binding
- [ ] the faceted search can be expanded with a filter for these keywords (and I will add a filter for those in binding as well) on the example of the filter for art keywords and art themes, which lists keywords (term) and themes (ref) used inside decoNote only.

**Comment by PietroLiuzzo** [comment]
I would also suggest to keep the above values for the taxonomy. I think those, combained with the classificiation (keywords/term) of the manuscripts and of the texts could give a nice pattern of representation (perhaps a good starting point for a quantitative analysis of this feature, leading to a "system")

**Comment by PietroLiuzzo** [comment]
who is up for updating the taxonomy? and perhaps the guidelines, adding an example? @thea-m @DariaElagina @DenisNosnitsin1970 @eu-genia @smaugustine

**Comment by DenisNosnitsin1970** [comment]
Sometimes the name of the saint in his Vita is written red, or the name of the angel in the respective homily. 
"Name of the protagonist"?
This would be interesting for me, but a bit later, after the summer school.

**Comment by thea-m** [comment]
Thank you, @DenisNosnitsin1970 !

**Comment by PietroLiuzzo** [comment]
I have added a facet allowing to filter down results based on the contents of term/@key into seg[@type='rubrication']

**Comment by DenisNosnitsin1970** [comment]
Dear Pietro, 
I know that the issue was assigned to me. The taxonomy is fine, more or less, and functions, but there are a couple of important points that should be better formalized, in my opinion. Then  a few changes will be needed, maybe with a short round of discussion. I am working on this issue, it will take a couple of days, but not more.
