### ISSUE TITLE
clarifications of Ethio-Spare terms

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1214]
Maybe we should clarify some Ethio-Spare terms used in the BM's "revisions of the data".

For Example: https://betamasaheft.eu/manuscripts/ESamm008/main#catalogue

We read:

    Eugenia Sokolinski adjusted to schema on 24.4.2019
    Pietro Maria Liuzzo transformed from mycore to TEI P5 on 10.5.2016
    Massimo Villa last edited on 28.1.2015
    Sophia Dege created on 30.5.2013
    Denis Nosnitsin registered on 20.5.2010

"registered" means the Ethio-Spare team! photographed the ms.
"created" means "catalogued"
"last edited" is the last change (any change: from just a dot to a proper revision)

I would suggest to take out "last editing". 
If the date of photographing is to be quoted, than I would suggest to quote the team.

@PietroLiuzzo @MassimoVilla @SophiaD-M @vitagrazia81 @thea-m @DariaElagina @MagdaKrzyz @DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Dear Susanne, if you want to be very correct - various members of the team were there when the items were photographed, so "Ethio-Spare team" would be a generalisation.

**Comment by thea-m** [comment]
From the point of view of someone who did not work in Ethio-Spare, it is indeed not evident which of these (registered, created, last edit) refers to the actual cataloguing.

**Comment by eu-genia** [comment]
We could specify the roles better of course; to me it seamed important to credit the main cataloguer duly. (During the batch conversion to BM, DN was entered everywhere as editor in the files, which I then replaced with the actual cataloguer's intials).
 I am quite against taking out the "last edited" out as indeed, as far as I know, in many cases the descriptions were significantly revised at later points (esp. those left unfinished by Iosif or Abraham but also others), so unless someone knows 100% that the last edit was just inserting a comma one cannot ignore the contribution. Besides, our rule is that every change is credited and attributed. It is a pity that there was no versioning in Ethio-SPaRe so the record history cannot be fully recovered, but we cannot simply cancel what is there.
