### ISSUE TITLE
watermarks

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1215]
Are the moving and popping up watermarks in images of manuscripts (ES and Laurenziana) on the app absolutely necessary? I find them quire irritating when working with the images.  Could static watermarks possibly be sufficient?

**Comment by PietroLiuzzo** [comment]
from my point of view, they are an important security measure to prevent inappropriate reuse (e.g. screenshots)

**Comment by thea-m** [comment]
But wouldn't they do the same without sparkling? It really hurts my eyes when I work with them.

**Comment by PietroLiuzzo** [comment]
there is no such setting, no. but I am not sure what you mean with this sparkling. they change position and size on zooming, but I cannot reproduce anything which I would call sparkling. I might have to look at it on your screen to understand what is the issue

**Comment by thea-m** [comment]
I meant the changing position and size on zooming, which you called sparkling in our last encoding meeting :)
