### ISSUE TITLE
Ethio-SpaRe descriptions in BM: mention of the Ethio-SpaRe as original Data in "revisions of the data" and distinction with the BM data

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Documentation#1216]
In addition and relating to the issue #1214 and the issues #1213 and #1159, I would like to add the following. Beside the clarification of some Ethio-Spare terms used in the BM's "revisions of the data", it would be nice and , on my opinion, more precise, if also in "Revisions of tha data", it will be specified  that the original data, i.d. the original description, is the Ethio-Spare description, catalogued by.... etc,..  There should be a clear distinction between the two data, the Ethio-Spare and  the data produced in the frame and by the team of BM. As it is now in "Revisions of the data" this is not understandable.

Then, under the name of the MS. at the top of the BM page, I noted that there is the name of the Ethio-SPaRe cataloguer. I know that this was done with a positive intention, and I am sure that the description which now appears in BM database might also contain  improvements of the original description, but still, to keep this name, the name of the author of original Ethio-Spare description, is not completely correct. They remain two different documents, produced in two different moments , projects, and people.

**Comment by PietroLiuzzo** [comment]
<img width="445" alt="Schermata 2020-06-07 alle 17 57 51" src="https://user-images.githubusercontent.com/508012/83973698-6fcff480-a8e8-11ea-93e3-1fe4e0dd867b.png">
I think that Revision of the data is quite precise about this process and @eu-genia is also working on each record to fix them, I am not sure what else can be done. Unless there is a concrete proposal in this regard perhaps this issue can be closed?

**Comment by eu-genia** [comment]
I think it is all very clear already, as the original cataloguer is given at the top of the record
Unless there are protests I would close the issue

I would like to use this occasion to call all those using Ethio-SPaRe records in their forthcoming publications to drop me a line so that I make sure that these records are available and updated on BM and can be quoted with the BM link (as domlib shall soon be obsolete and offline)

**Comment by vitagrazia81** [comment]
Yes, also I find this revision very clear and precise. Thank you. The issue can be closed for me as well.
