### ISSUE TITLE
manuscripts comparison codicological data

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1218]
In the visualization of codicological data in the manuscript comparison view, I don't understand to what "Unfortunately we cannot put on a chart this data, because it is provided using different units of measure (mm, in)" refers (it happens to appear on all the works I tested now, for example https://betamasaheft.eu/compare?workid=LIT4033Senkessar, https://betamasaheft.eu/compare?workid=LIT2509Weddas)
It can't refer to the sewing stations, which are visualized just below?

**Comment by PietroLiuzzo** [comment]
this had been fixed with a better description of the missing chart.
