### ISSUE TITLE
show all manuscripts of a given work in filter view?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1219]
@vitagrazia81 had wanted to link to a list on BM of all ES manuscripts containing a certain work (LIT1544Gebrah) - I had hoped that this would be possible through the manuscript filter view  https://betamasaheft.eu/manuscripts/list (where it is possible to filter by data provenance), but it was not. Would including there a field for work IDs be possible, or is it not practical?
(Maybe related, maybe not: what is supposed to be written in the "name" field in the filter view? It's not clear to me.)

**Comment by PietroLiuzzo** [comment]
<img width="405" alt="Bildschirmfoto 2019-08-14 um 09 40 36" src="https://user-images.githubusercontent.com/508012/63003033-9c0d1700-be77-11e9-96f8-5000c36b32b3.png">

**Comment by PietroLiuzzo** [comment]
the query can be also made as https://betamasaheft.eu/manuscripts/list?cp=ES&contents=LIT1544Gebrah

**Comment by PietroLiuzzo** [comment]
but, as always, BEWARE, because the ES mss are not encoded fully, so, the query will only match the ones which HAVE BEEN ENCODED.

**Comment by thea-m** [comment]
Thank you! Obviously only the encoded ones can be found. I am not sure how the first screenshot helps us here?

**Comment by PietroLiuzzo** [comment]
you can already do what you are asking, but you cannot see this in the filtered search, as explained in the red box in the screenshot

**Comment by thea-m** [comment]
OK, thank you, I had understood it to mean that it only shows result lists that are shorter than 1000 items or manuscripts that contain less than 1000 items.

**Comment by PietroLiuzzo** [comment]
better ways to phrase that are always welcome.

**Comment by vitagrazia81** [comment]
@thea-m,  @PietroLiuzzo, thank you.

**Comment by thea-m** [comment]
"It is only possible to filter by categories which give less than 1000 results. These are the only categories shown here." What do you think?
And: What are we supposed to write in the "name" field?

**Comment by PietroLiuzzo** [comment]
in the name field you can write what has been asked for that field, so the primary name of a resource, the id, the person name, the toponym, the title of a work respectively. if you now prefer another label, please tell me.
