### ISSUE TITLE
@when in floruit

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1220]
as pointed out by @SophiaD-M , it is unexpected to find a single date under the rubric of "Period of Activity". Of course this is only the visualization of `<floruit>` (which I still think is very good), but probably in most of the cases in our records that have @when in `<floruit>`, what is meant is in fact not only a single year (many of these records are from the beginning of the project, where for example the beginning of a ruler's reign was encoded in this way, see PRS10626ZaraY).  Maybe we could encourage the use of @from and @to in `<floruit>`, and restrict the use of @when to cases where indeed only one year is meant.
What do you think?
@sologebre @DenisNosnitsin1970

**Comment by sologebre** [comment]
Yes, as we have discussed so far <floruit> only refers a period of activity of an individual. In this case, for Ethiopian kings (for most of them) we have conventionally known years of reigns which is considered as a period of activity that we should indicate @from (indicates the starting point of the period) and @to (indicates the ending point). However, most of the time ,when we are not sure of the exact <floruit>, period of the person's activity, but we have supporting evidence to claim the approximate period of <floruit>, period of activity, we should use also @ notBefore (specifies the earliest possible date for the event) and @notAfter (specifies the latest possible date for the event). Yes, as is mentioned there are person records as usual we need to correct. On the other case, we use @when we do have a single period of the particular event happened to a person.  For example, if we know the exact date of birth and death.

**Comment by thea-m** [comment]
Yes, exactly. Could you maybe edit the guidelines to make this more obvious and update the old records?

**Comment by sologebre** [comment]
It has now been updated.
