### ISSUE TITLE
date of reign in the records of rulers

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1221]
@SophiaD-M has suggested that it would be very helpful for users to find the date of rulers' reigns on their page. This date is often encoded in `<floruit>` (as stated in the guidelines). However, people who have not read the guidelines (=everyone) of course cannot know this. In these cases, it would be useful to either mention the date of their reign explicitely in the paragraphical information, or to somehow specify the visualization of `<floruit>` (with an attribute? another element?). What do you think?
@sologebre @DenisNosnitsin1970

**Comment by sologebre** [comment]
I see no other possible solution than accurately describe the years of reign in para-graphic information as you have suggested. I will go through the record and update it accordingly.
