### ISSUE TITLE
wikidata box has disappeared from place records

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1227]

**Comment by thea-m** [comment]
I can currently see no wikidata links on place pages, for example https://betamasaheft.eu/places/LOC2482Dambi/main or https://betamasaheft.eu/places/LOC1216AddisA/main

**Comment by PietroLiuzzo** [comment]
sorry I have no memory of way that disappeared. it should be back.

**Comment by thea-m** [comment]
Thank you!
