### ISSUE TITLE
search for codicological features

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1230]
I don't understand how the search for number of leafs, number of quires and quire types in manuscripts work.
If it's only me, I'll be happy with an oral explanation, otherwise we might need to add some clarification in the search?
![image](https://user-images.githubusercontent.com/19650382/65709077-450e7a80-e090-11e9-8003-ba0d78178293.png)
I assumed that : used in the bars means "to", but I cannot find any results with any of these filters. For example, how could I search for manuscripts composed of 10 quires? of quinions? of 50-100 leafs?
Can anyone explain to me? @DenisNosnitsin1970 @DariaElagina @sologebre

**Comment by PietroLiuzzo** [comment]
number of folia will look in an index based on `t:extent/t:measure[@unit='leaf'][not(@type)]` 
number of quires will look in an index based on `t:extent/t:measure[@unit='quire'][not(@type)]` 
Quire composition will look in `t:dim[ancestor::t:collation][@unit='leaf']`

There is indeed an issue with the index usage which prevents these queries from working.

**Comment by PietroLiuzzo** [comment]
These feature of the filter search are currently being entirely rewritten to use the new facets indexes of exist 5. It will speed up the searches and also increase the number of searchable parameters (although always limited to the content of the collection)

**Comment by PietroLiuzzo** [comment]
removing the number() function from the xpath had a dramatic impact on the queries using these parameters, even without indexes, reducing the time of execution from 52seconds to 0.034...

**Comment by PietroLiuzzo** [comment]
dear @thea-m when you have a minute could you test on new server 
- [manuscripts composed of 10 quires](https://betamasaheft2.aai.uni-hamburg.de/manuscripts/list?mainname=&date-range=0%2C2000&cp=&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C1000&qn=10%2C10&qcn=1%2C40&wL=1%2C100&restorations=)
- [manuscripts with at least 1 quinion](https://betamasaheft2.aai.uni-hamburg.de/manuscripts/list?mainname=&date-range=0%2C2000&cp=&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C1000&qn=1%2C100&qcn=10%2C10&wL=1%2C100&restorations=)
- [manuscripts with 1-100 leaves](https://betamasaheft2.aai.uni-hamburg.de/manuscripts/list?mainname=&date-range=0%2C2000&cp=&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C100&qn=1%2C100&qcn=1%2C40&wL=1%2C100&restorations=)

all these will receive a facet. the facet for leaves will have to 
- compute values given as 1 + 80 (e.g.), eventually ignoring the added protective leaves count
- clean from white space
- format numbers given as 160.2 or similar

**Comment by thea-m** [comment]
thank you! Here some remarks:
- Manuscripts with 10 quires: among the results, ESagm006 has 9 quires, EMIP02035 has 11 (last one with n="a"), SHOr415 has 11
- manuscripts with at least 1 quinion: I checked a few random manuscripts from the results list, all seemed fine to me
- manuscripts with 1-100 leaves: I also checked some randomly, among these BLorient621 has 113 leaves, BLorient502 has 201

**Comment by PietroLiuzzo** [comment]
> * Manuscripts with 10 quires: among the results, ESagm006 has 9 quires, EMIP02035 has 11 (last one with n="a"), SHOr415 has 11

the search matches manuscripts which have a number of quires included in the range in  `<measure unit="quire">10</measure>` which is 10 in both examples. 

> * manuscripts with 1-100 leaves: I also checked some randomly, among these BLorient621 has 113 leaves, BLorient502 has 201

yes and no... this looks into `<measure unit="leaf">10</measure>` and BLorient621 has indeed one which is <`measure unit="leaf">1</measure>` in p1, and so does BLorient502 in p2... I am not sure how I could make this check better. also if I store this information in the index it will always come from these elements. what should I do, add up all of element occurrences for a filter value?

**Comment by thea-m** [comment]
Ah, I understand. Then I think it's not dramatic as it is now, anyone working with these kinds of queries would in any case have to check the results. Adding up the elements would probably work in these cases (it will not consider `<measure unit="leaf" type="blank">`).
(good that this was brought up, I was not aware that `<measure unit="quire">` was essential and never used it...I'll add it to my records)

**Comment by PietroLiuzzo** [comment]
I would not consider any element essential, in our current workflow. the fact that there is a search feature should not put any requirement on the data, otherwise we would not have anything online, there is no single dataset that has all things which are searchable for in different queries and contexts... and we have plenty of workarounds (like this one is going to become) to face these diversities.
