### ISSUE TITLE
OwernshipNote or ScribalNoteCommissioning

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1232]
In one of the EMIP records, one addition is a prayer that identifies the owner, and also identifies him as the commissioner of the manuscript. I have recorded this with 'type="OwnershipNote" but it could also be a "ScribalNoteCommissioning" - or indeed both. Any advice on what to do here?

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 , any suggestion?

**Comment by DenisNosnitsin1970** [comment]
In Ethio-Spare, "Note on commissioning of the writing" is the statement of commissioner (1 or 3 pers.):

for instance, with such a formula:
- I commissioned this book (literally: "I have had this book"), Walda Hagos.....
or
- He commissioned this book (literally: "He has had this book written"), Walda Hagos....
It is a kind of "colophon of commissioner"
If it is a prayer that mentions the person as commissioner, I would not call it "ScribalNoteCommissioning".
DN

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK is this answer satisfactory, can this issue be closed?

**Comment by Ralph-Lee-UK** [comment]
Very clear, thankyou!

**Comment by Ralph-Lee-UK** [comment]
Very clear, thankyou!
