### ISSUE TITLE
problem in idno in BNFabb57 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1235]
There is a problem with the second idno element in BNFabb57 (which seems to me to conform to the guidelines) that leads to an error on the app.
```
<idno facs="https://gallica.bnf.fr/ark:/12148/btv1b525076181">BnF Éthiopien d'Abbadie
              57</idno>
```
I commented it out for now, but maybe you understand what's going on?

**Comment by PietroLiuzzo** [comment]
you need `<altIdentifier>` https://betamasaheft.eu/Guidelines/?id=identifiersStructure

**Comment by thea-m** [comment]
@DenisNosnitsin1970

**Comment by thea-m** [comment]
thank you!
