### ISSUE TITLE
work records not synced

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1238]
LIT5781MashafaAnkero and LIT5782HymntoGeorge seem not to be synced on the app (I did not check all other new work records systematically to see whether this is the case elsewhere)

**Comment by PietroLiuzzo** [comment]
interesting, I think the hook is not working properly. I have reloaded to the app all works in /new done after 20.8.2019 (few)

**Comment by thea-m** [comment]
thank you!
