### ISSUE TITLE
image inside front cover

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1240]
@Ralph-Lee-UK  asked me

> if there is a mark, image, or whatever on the inside front cover, or other places, how might we refer to those correctly?

I have no idea, can anyone help? binding? decoDesc?

@Ralph-Lee-UK could you perhaps send as an image here or an example, so that we can better help? images in the mss go in decoNote, but on the cover I would say in binding

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @thea-m

**Comment by thea-m** [comment]
Yes, binding and decoDesc seem the two best options. I would tend towards binding in cases of marks, scribbles or similar, and decide case by case for glued images, miniatures or similar, for which decoDesc might be the better place (with a reference in binding). 
The case of glued images (in other places of the manuscript) was discussed in https://github.com/BetaMasaheft/Documentation/issues/843, where a type in decoDesc was decided. 
@DenisNosnitsin1970 ?

**Comment by DenisNosnitsin1970** [comment]
I would describe the image under decoDesc, but refer to it under binding as well; scribbles on the binding I would describe under "Additions/extras".

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK
