### ISSUE TITLE
something is wrong in LIT4840Tertag

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1244]
Please coordinate the entries for "Sarkis", "Tertag", "Zenā Sarkis za-ʾArmānyā..." (LIT5189Sergius; LIT4840Tertag)
thank you

**Comment by PietroLiuzzo** [comment]
I am sure this is entirely clear for @thea-m but for me, if you could expand a bit on "coordinate" it would be nicer! what needs to be done?

**Comment by thea-m** [comment]
It seems to me that LIT5189Sergius was created erroneously, and should be deleted and and replaced by LIT4840Tertag in BLorient827. @sologebre if you have no objections, I will do this.

**Comment by sologebre** [comment]
Ok, please do!
