### ISSUE TITLE
subject keywords for Rāʾǝya Sinodā

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1245]
I am unsure about the subject keywords best to be used for Rāʾǝya Sinodā. What would you suggest?
@abausi @DenisNosnitsin1970
(you can find the list here https://betamasaheft.eu/authority-files/list, scrolling down to subjects)

**Comment by abausi** [comment]
The appropriate keyword under subjects would be "Apocalyptic literature"; and we should probably introduce this; other, additional, keyowrds, could be: Christian Literature, Religion; but I am convinced that this keyword makes sense

**Comment by thea-m** [comment]
Thank you! I will create this keyword, I also believe it is needed.

**Comment by DenisNosnitsin1970** [comment]
I agree.
