### ISSUE TITLE
cannot create new authority file

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1246]
> 
> <exception>
> <path>/db/apps/BetMas/edit/save-new-entity.xql</path>
> <message>
> exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 583, column 19]
> </message>
> </exception>
> 
I logged out and in and tried in firefox as well

**Comment by thea-m** [comment]
(reminder to myself, to create ApocalypticLiterature)

**Comment by thea-m** [comment]
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
I have updated the chmod of the new folder which should prevent this error from reappearing and also created the file

**Comment by thea-m** [comment]
thank you! Now I can create but not download...

**Comment by PietroLiuzzo** [comment]
I have loaded the file, but the error you encounter here is quite new...

**Comment by thea-m** [comment]
Never gets boring
