### ISSUE TITLE
visualization of placeName in mss

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1250]
For some reason I do not see the name of the place printed, e.g. in ESgbi002
`The ms originates from <placeName ref="INS0101MadhaneAlam"></placeName>` - the name is not printed (unless I type it in inside the tag of course). 
Is this the desired behaviour or a bug?

**Comment by thea-m** [comment]
I see it...

**Comment by eu-genia** [comment]
must have been something with my PC last week!
I can now too...
