### ISSUE TITLE
info on chojnacki collection?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1254]
It might be nice there would be on the app some information on the Chojnacki collection and the reasons for its presence on BM, maybe comparable to https://betamasaheft.eu/tweed.html. I don't know whether this could be included directly in the viewer or would have to be on a separate page. What do you think?
@Gnisci @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
provide some text and I will make the page.

**Comment by Gnisci** [comment]
Something from what I wrote here perhaps: https://www.betamasaheft.uni-hamburg.de/manuscripts/newresearch/chojnacki.html ?

**Comment by thea-m** [comment]
Maybe you could add a link to this page or include the entire text on a new page? I think it's very informative.
