### ISSUE TITLE
scholars in ethiopian studies page

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1255]
I was wondering whether we still need to keep this page https://betamasaheft.eu/academics.html among the resources. It was compiled for a specific occasion and I am concerned that we have many many resources hidden over the app that many people have trouble finding, so maybe we don't need to keep the ones that serve no specific function. What do you think? @sologebre 
(If we do keep the page, the title should be changed to Scholars in Ethiopian and Eritrean Studies)

**Comment by sologebre** [comment]
Yes, I agree it's better to delete it.

**Comment by thea-m** [comment]
@PietroLiuzzo , could you delete it then?

**Comment by PietroLiuzzo** [comment]
removed from new app
