### ISSUE TITLE
attestations of LIT5809OntheBurial

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1256]
Why is ESaqg004 not listed when clicking the "show attestations" button in LIT5809OntheBurial?

**Comment by PietroLiuzzo** [comment]
is the first in the list of manuscripts. and the only result in the attestation box, as far as i can see. could you please try again?

**Comment by thea-m** [comment]
yes, now it's there. Nothing at all loaded in the attestations box before.
