### ISSUE TITLE
suggestions on dates in person records and requests for changed to record https://betamasaheft.eu/persons/PRS8386SalamaI/main

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1257]
First of all I think Frumentius and his brother were Syrians not Egyptians.

For the different names I think "Frumentius" should be written as one of the alternative names as well - not everybody is able to read the transcription properly. and its the commonly used form in non-scientific writings.

lastly, I have never seen the dates in a 4-digit writing. That is 0340 for the year 340. 

Thank you

**Comment by SophiaD-M** [comment]
Sorry, I have to add further critizism. in the box for the additional names it is twice stated "birth" followed by Ethiopian names - none of which were his birth names obviously. 

Secondly I do not understand what this is supposed to mean: Death: 0356- (high)

**Comment by SophiaD-M** [comment]
oh, and last (and hopefully least), "Ethiopian Orthodox Täwahedo Church" as his faith is more than strange! 

In the EAe it is at least written like this "Ethiopian Orthodox (Täwahedo) Church", which still is not ideal. However, I think too many people were killed, tortured or persecuted in Ethiopian past over the "Täwahedo" issue that it should not be written there as is.

**Comment by thea-m** [comment]
According to the guidelines https://betamasaheft.eu/Guidelines/?id=faith and the issue behind this guideline page https://github.com/BetaMasaheft/Documentation/issues/870 (admittedly not a very lively discussion - so, if you disagree, please open a new issue), he should simply be "Christian"

**Comment by SophiaD-M** [comment]
I like the issues #870  - but the results are not fully convincing. Just imagine there are these strange people in history who were not religious at all... 
If it needs to be there why not "associated with EOC" or similar? Why is "Faith" there by default?

**Comment by PietroLiuzzo** [comment]
well, well, here we have a nice mixture of many different issues all in one thread. Please consider opening different issues and describing for each the problem, your suggestions, providing also a link to at least one example. here I think we are speaking of https://betamasaheft.eu/persons/PRS8386SalamaI/main

I can change the format of the date (that is the ISO format for year): what would you like?

all the rest as far as I can see is for @sologebre as it pertains corrections to the data. 
I have added the brackets for (Tawāhedo): is the transliteration ok @thea-m ?

**Comment by thea-m** [comment]
Tawāhǝdo

**Comment by thea-m** [comment]
And Sophia has provided the ID in the title :)

**Comment by PietroLiuzzo** [comment]
which one, giving 4 options does not help

**Comment by PietroLiuzzo** [comment]
I will introduce a template for issues to try and make them a bit more reasonable

**Comment by thea-m** [comment]
I can see nothing unreasonable in this issue. It cannot be expected from persons who are not familiar with the project workflow to be aware of our current preferences regarding issues. Opening one issue for several points related to one record seems to me quite intuitive.

**Comment by PietroLiuzzo** [comment]
We have made the corrections to the single file, to the view and we know faith does not need to be there by default, and we should remove it where it is wrongly assigned or irrelevant. please consider closing this issue.

**Comment by PietroLiuzzo** [comment]
can this be closed? this is also assigned to two persons. if there are outstanding parts, could you please point them out? thanks
