### ISSUE TITLE
faith of persons

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1258]
I like the issues #870  - but the results are not fully convincing. Just imagine there are these strange people in history who were not religious at all... 
If it needs to be there why not "associated with EOC" or similar? Why is "Faith" there by default?

_Originally posted by @SophiaD-M in https://github.com/BetaMasaheft/Documentation/issues/1257#issuecomment-555031598_

**Comment by thea-m** [comment]
Any ideas or opinions regarding particularly the use and definition of "EOTC" (when assigned to persons)?
@DenisNosnitsin1970 @sologebre @DariaElagina @eu-genia

**Comment by DenisNosnitsin1970** [comment]
We can use "Ethiopian Orthodox Christian", but the same thing is meant. EOTC is the modern name for the same institution that existed starting from the 4th cent., no less no more. Eritrean Orthodox Church has been created only recently (whe Eritrea was a colony, I think the local church was part of the EOCT). Frankly speaking, I do not see big problems here, at least for Ethiopians/Eritreans. We have to be ready that we will very rarely find exact and assertive references to baptism, however we can safely assume that all persons bearing Ethiopian Christian Amharic/Geez/TGN names, historically, were baptized, and wwished to finish his/her life with the proper funeral service. If we have grounds to think that someone changed his/her faith - this also happened at times - it should be added (the reasons could be explained in the abstract). "Associated" does not mean anything, in my opinion. "Associated" is widely used in a different meaning, as a reference to institutional affiliation. Most of the scribes, for instance, were affiliated with the EOTC (we can assume that all were baptized, but one would have to think over the issue of Beta Israel scribes).

**Comment by thea-m** [comment]
We can summarise that there is a general practice of assigning EOTC in person records of those active in Ethiopian/ERitrean environments and involved in the production of manuscripts of this tradition.  For me, the problem of retroactively using the modern organisational name for those who lived before its institutionalisation in this form is already partly solved by the visualisaton on the app as "Ethiopian Orthodox (Tewahedo) Church", and regardless of that, there is still no necessity of including "EOTC" in all records by default.
