### ISSUE TITLE
relation overview for records without relations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1260]
The new relations overview (thank you!) begins with "See ." for records which have no relations, for example PRS1389Adam. Would it be possible to have this sentence only in records with relations?

**Comment by PietroLiuzzo** [comment]
This record actually HAS a relation, it is just that this is not encoded correctly
```
<relation name="sonOf">
<desc> son Mäḥammad Ali </desc>
</relation>
</listRelation>
```

**Comment by thea-m** [comment]
Ah, thank you!
