### ISSUE TITLE
letter and canon tables

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Documentation#1263]
Bonjour!
While encoding, I found three work files, the following:

LIT1349EpistlEusebius
LIT1224Canons
LIT4876LetterCanons: Letter to Carpianus and Eusebian Canons

I wonder what is the meaning and purpose of the third one. The description  provided as
2 pages of letter + 8 pages of canons
seems to be mysterious. I would commit violence and kill this third file , but I do not feel myself authorized. I assigned everyone who is mentioned in this files, who might know more.
if I am confusing something, please let me know!
thank you very much for either correcting me or commiting violence to this file.

**Comment by eu-genia** [comment]
This was following the indication of @abausi to disambiguate between the canon table types properly

**Comment by eu-genia** [comment]
see https://github.com/BetaMasaheft/Documentation/issues/336

**Comment by thea-m** [comment]
There is also LIT4877LetterCanons. Clearly, the titles are inconsistent and the disambiguation and correct encoding of versions should be improved. I have no time for this now, maybe someone else can do it? Or I in the future.
(How did I ever create LIT4877LetterCanons? There is not even a title)

**Comment by thea-m** [comment]
I think that we can close this issue, since the discussion is now taking place in #336 .
(See also #459 )
@nafisa-valieva : you can always do any edits that you think are necessary in a new branch and then make a pull request. But of course discussing in a prior issue is completely fine, and often, preferable.
