### ISSUE TITLE
list

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Documentation#1264]
Ciao Pietro,
now validating, I see that normal encoding of the text (`<lb/> <cb/> <pb/>` etc )is not allowed in the `<list>` element. Is there a way to allow it or what shall I do, encoding those documents or notes which are additions according to Andrist and us? I do not want to loose this data. I have started to delete it, but now on the half way through I regret to delete it, I'd better keep it! and I can have it from my file back, if the schema allows.

**Comment by PietroLiuzzo** [comment]
can this also be closed now?

**Comment by nafisa-valieva** [comment]
let it be your second Advent gift)))
