### ISSUE TITLE
visualizing translators

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1267]
I suggest to print the content of the relation "betmas:isAuthorOfEthiopicTranslation" in the main Work record under the Author element (as Translator?), what do you think @thea-m @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
we can do this easily, let me know

**Comment by PietroLiuzzo** [comment]
I have added this. let me know if it is ok. e.g. https://betamasaheft.eu/works/LIT1180Baenta/main

**Comment by DenisNosnitsin1970** [comment]
I agree.

**Comment by eu-genia** [comment]
very nice

**Comment by PietroLiuzzo** [comment]
ok, sorry for the long wait...
