### ISSUE TITLE
xml:lang of non Geez Ethiopic languages in places and persons names

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1268]
Dear all,
I have noticed that there is a tendency (probably also from me, but it's always easier to notice inconsistencies in other people's records...) to automatically mark up all Ethiopic person and place names as "Geez", even when they clearly are for example Amharic. In the case of names in a (for us) clearly identifiable language, this can easily be prevented if we keep this in mind.
However, there can be cases of names where we (I at least...) do not know the language immediately. What would you suggest for such cases? Still use Geez as a kind of default?

@DenisNosnitsin1970 @sologebre @DariaElagina @eu-genia

**Comment by PietroLiuzzo** [comment]
I do not recall enforcing the presence of xml:lang anywhere, if this is the case, then it needs to be fixed. if you do not know you should not feel compelled to add inexact or even wrong information in the data.

**Comment by thea-m** [comment]
It is not enforced. I was under the impression that any text not marked up otherwise would be taken as English, which then would be wrong in these cases.

**Comment by sologebre** [comment]
For persons and places names in ethiopic texts, etymology does not only refer necessarily Amharic or Geez in some cases may refer to Cushtic and other linguistic category. But sometimes, we may find the meaning of person or place names in Amharic or some in Oromifaa (we have actually several places in this language as well) - this happens very rarely. So, if we start to identify what the etymology of the language of the person or place name is, it is very difficult or, in some cases, confusing. So, as you suggested, I think it would be better still to use Geez as a kind of default.

**Comment by thea-m** [comment]
As @sologebre has rightly stated, there are often no easy answers to this. I think it would be preferable to not have Geez as a default but not to mark up the language, if that is possible.
@PietroLiuzzo , are languages not marked up seen as English? This was my impression. 
Examples would look like this:
```xml
 <place type="area">
                    <placeName  xml:id="n1">ቀዘባ፡</placeName>
                    <placeName corresp="#n1">Qazabā</placeName>
                </place>
```

**Comment by thea-m** [comment]
I think that this is an important issue, and it arrises often in the encoding of place and person names. For instance, there are also personal names of which one part is Geez and one Amharic. To encode this all seems to me now not really necessary, but to encode with the wrong language annoying for anyone who actually might research onomastics in the future.

**Comment by DariaElagina** [comment]
As we just had a discussion on it with Solomon, I would suggest that we rise this question on the next meeting, on the 18th of February. I think the crucial point is the meaning of xml:lang. Does it indicate the language in which the name had originated, or the form of a name in a given language? I think that by now we mix these both concepts. For example,
<persName xml:lang="gez" xml:id="n1">እስክንድሮስ፡</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">ʾƎskǝndǝros</persName>
<persName xml:lang="en" xml:id="n2">Alexander</persName>
In this case, xml:lang="gez"  and xml:lang="en" do not indicate the etymology, but the form of a personal name attested in Geez and English correspondingly.

**Comment by DariaElagina** [comment]
`<persName xml:lang="gez" xml:id="n1">እስክንድሮስ፡</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">ʾƎskǝndǝros</persName>
<persName xml:lang="en" xml:id="n2">Alexander</persName>`

**Comment by DenisNosnitsin1970** [comment]
I would agree; actually I never thought of etymology, just the form of the name as attested in the specific language.

**Comment by DariaElagina** [comment]
As it was agreed on our last meeting, we should use xml:lang for the language of attestation. So, any proper name attested in Geez text should receive the attribute xml:lang="gez", though it might be of Arabic, Amharic, Oromo, or whatever origin. There is an idea once to introduce another attribute to indicate etymology when known. Have I missed anything?

**Comment by PietroLiuzzo** [comment]
In taking a decision, as the documentation been consulted?
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html
http://www.rfc-editor.org/rfc/bcp/bcp47.txt
