### ISSUE TITLE
"Art keywords" and "Object and Animals" are not shown in index list

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1273]
https://betamasaheft.eu/authority-files/list
Art keywords and Objects and animals are not shown when clicking on these categories in the left menu.

![image](https://user-images.githubusercontent.com/19650382/69795671-e15a1800-11cc-11ea-9930-8fbc17908b1f.png)

I would expect them to be listed.

**Comment by PietroLiuzzo** [comment]
thanks for the notification! this was a permission issue on the folder where these files are contained which has been fixed in the db.

**Comment by thea-m** [comment]
Thank you!
