### ISSUE TITLE
Links to syriaca and pleiades taken from relations don't work 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1274]
Links in place records to syriaca and pleiades that are taken from relations don't work, for example in INS0478DS
https://betamasaheft.eu/http://syriaca.org/place/360
(or LOC5017Nubia)

The links taken out of a sameAs value, for example in LOC1236Agama do work. Is giving the reference in a relation old encoding and should be updated? I don't find anything on this in the guidelines.

**Comment by PietroLiuzzo** [comment]
If you are referring to the relations table, they do work correctly. in the paragraph recently added on top the link text and link content are mismatched and I will look at this. There is no encoding issue of any kind as far as I can see, it is only a problem in the visualization.

**Comment by PietroLiuzzo** [comment]
now also the link in the paragraph about relations added at the top are fixed. please let me know if I did not actually find the wrong instances of links you were referring to

**Comment by thea-m** [comment]
Thank you, perfect!
