### ISSUE TITLE
missing information in title (?) or summary (?)

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1275]
Concerning manuscripts/GAet3

I am not exactly sure what this part is called, maybe "title" or "summary", see attached images for clarification. 
In the rest of the Grottaferrata collection the here highlighted area contains information - the titles of the works included. Just for consistency it would be wonderful to have it also in this description for manuscript 3.
<img width="667" alt="Eliana" src="https://user-images.githubusercontent.com/29302681/69809133-66532a80-11e9-11ea-8ef9-5de45f43e18f.PNG">

**Comment by PietroLiuzzo** [comment]
Yes, the titleStmt/title element is empty. This is not a required information, but you are welcome to add it if you would like to have it in there. You can hit the EDIT button and propose a change. The missing informations are many more than the ones which are present, so, every little helps!
