### ISSUE TITLE
Gabra Māryām in DS records disambiguation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1276]
PRS11944GabraM and PRS11905GabraM are used for persons called Gabra Māryām in the DS records. 
We should check whether they are really two persons and the IDs are used correctly.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 , what do you think?
Currently, the IDs are used in this way:

PRS11944GabraM : DSEthiop 4, 8, 21, 22
- DSEthiop4: owner, donated in 1951, associated with ማኅበረ፡ ሥላሴ፡ (same manuscript names Hayla Gabreel and Gabra Sellase from Dabra Bizan/Baramus)
- DSEthiop8: patron, 1854-1861 (could be the same hand as the note in DSEthiop1? - but this would make the dating proposed according to the mentioned patriarch and metropolitan improbable)
- DSEthiop21 scribe, associated with ማኅበረ፡ ሥላሴ፡, 1951-1952 
- (DSEthiop22, same hand as DSEthiop21)

PRS11905GabraM : DSEthiop 1, 3, 12, 15
- DSEthiop1, owner in the 20th century, associated with Gondar (older manuscript) (ownership note maybe same hand as DSEthiop12?)
- DSEthiop3: name added later in the margins
- DSEthiop12: owner (before 1954) 
- DSEthiop15: patron, associated with scribe Walda Takla Hāymānot (beginning 20th century)

**Comment by DenisNosnitsin1970** [comment]
I would say of course there may be some confusion because both IDs differ only in two signs out of 14. But one also has to see the hierarchy of the notes. Besides, it is a normal problem of a collection that grew in the natural way, in a context, contrary to those picked or gatherd by a collector.

**Comment by thea-m** [comment]
Sure, what concerns me is only whether they are really two persons and whether our assignment of ID to the mentioned names in the manuscripts is correct.

**Comment by DenisNosnitsin1970** [comment]
Of course, this concerns me as well. In all these cases the person in quistion is called Gabra Maryam. The main question for me is, if GM of Gondar is the same as GM of Mahbara Sellase. For the moment, 
i tend to think that they are the same.  DSEthiop8's dating is made on the basis of the names mentioned in the text; the hand can be the same with a note in DSEthiop1, quite short, made by the hand of the owner (GM), but this is a bit uncertain. On the whole, I find the way I have to operate in the DB with the persons very unconvinient (all indications and arguments are dispersed and hidden).

**Comment by DenisNosnitsin1970** [comment]
No decision on GM yet; it can happen that in some cases it cannot be decided with certainty

**Comment by DenisNosnitsin1970** [comment]
Among the group below, actually, only Ethiop 8 seems to be singled out, the rest of the books hangs well together. Name + the name of a monastery (not smth very common like Dabra Maryam), hand in nos. 21+name+dating and 22 is very obvious (even though 22 is not signed). Ethiop4 could have other owners from a different Eth. monastery and get in the possession of GM at the end, this is normal; his connection to Mahbara Sellase is well attested in the ms.  

    DSEthiop4: owner, donated in 1951, associated with ማኅበረ፡ ሥላሴ፡ (same manuscript names Hayla Gabreel and Gabra Sellase from Dabra Bizan/Baramus)
    <DSEthiop8: patron, 1854-1861 (could be the same hand as the note in DSEthiop1? - but this would make the dating proposed according to the mentioned patriarch and metropolitan improbable)>
    DSEthiop21 scribe, associated with ማኅበረ፡ ሥላሴ፡, 1951-1952
    (DSEthiop22, same hand as DSEthiop21)

**Comment by DenisNosnitsin1970** [comment]
Now, we can try to see again if PRS11944GabraM, well identified on several parmeters, can be linked in a sufficiently secure way to PRS11905GabraM (if and in which books it will be possible).
