### ISSUE TITLE
Double Clavis numbers

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1278]
There are two records each with the Clavis numbers 5810 and 5811:  LIT5810HomilySatan and LIT5810ExplanationHebrewNames, LIT5811OntheC and LIT5811GHI (just created by me through the app and not yet committed). Is there any way of checking whether there is a problem with the numerical part of the ID assigned by the app or whether these records were created without using the app?
@PietroLiuzzo @eu-genia @DenisNosnitsin1970 
In case the latter case is true, please remember to always create new work records through the app, so that this does not happen. Thank you!
I will now create new records for the concerned files and substitute their ID for the old ones in records where they have been used.

**Comment by thea-m** [comment]
LIT5811OntheC and LIT5810HomilySatan are not shown on the app ("LIT5810HomilySatan is not an available item") - they were probably created manually?

**Comment by PietroLiuzzo** [comment]
Dear @thea-m thanks for spotting this! 
@eu-genia please fix these records creating them in the app and replacing the content.

**Comment by thea-m** [comment]
I have started fixing this, so I think it's best if I continue, not to create more chaos
