### ISSUE TITLE
Private Collections page on the website

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1279]
We had talked in a meeting about how adding pages for collections of manuscripts catalogued or described (broadly) within the project to the app would improve the visibility of these collections and the work done with them.
There are already pages for the Tweed and Dayr as-Suryan collections:
https://betamasaheft.eu/tweed.html
https://betamasaheft.eu/DSintro.html
I think that it would be useful to have similar pages for the smaller private collections described by us as well. Do you have ideas for a useful organisation of such a page?
I have the Fricke collection (5 MSS, four already partially described on BM), and one manuscript belonging to Mathias Müth (not yet described), which have all been digitized by Karsten and whose images we will have on the app (not yet there).  Now there will be at some point the Dauwe collection, and undoubtely more in the future.
I would suggest a page, listed among the resources, called "Private Collections" (possibly with a very brief and general introduction?) and links on this page to further pages for each of the collections.
What do you think?
@abausi @eu-genia @PietroLiuzzo @DenisNosnitsin1970 @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
It is useful, I have to contribute one.

**Comment by PietroLiuzzo** [comment]
There are many other private collections in EMIP for example. I wonder if we do not need a more systematic solution for this. The description of the collection is clearly different from a description of a repository, but I remember we agreed on not having a collection entity to overload the fragmentation of the system. 
I think the solution already put in place is ok, and I am fine adding a static page with links to others. but a static page is a static page, which is separated from the database information and I think until we have up to 5 is ok, but we ought to think bigger, because we do have many more private collections.
What makes the Tweed and DS collection worth a page of their own is the sort of cooperation activating the work at the end of the day, as for the Chonjacki collection of images.

**Comment by thea-m** [comment]
Thank you. I see this slightly differently. For me, the main aim  here was not mainly to have a page for all "private collections", but to highlight "Collections (first/primarily) described on BM", especially those for which currently no other catalogues are published. Since the EMIP and EMML private collections are primarily described within these projects, I see no need for an extra page for all their private collections, which have their repository records and can be filtered with the search in case of interest.
But if you have already have a systematic solution in mind, please let us know!

**Comment by PietroLiuzzo** [comment]
I do not have a solution in mind, no, and yes, I agree we are seeing different problems.

Calling this additional page "private collections" as you initially suggested would be deceiving, I like more this second proposal for "Collections primarily described in BM".

However, I still think listing these "collections" on a static page is not enough, we must be able to group these declaratively, at the moment these can only be done negatively (not EMIP, not EMML, not ES, not IIHA, etc.) 

what about a <collection> element which says beta masaheft or something similar?

**Comment by PietroLiuzzo** [comment]
we should also agree on what gets this special label, building on your suggestion above.

btw, unfortunately it is not yet so that all the private collections have their own repository... but we will get there at some point

**Comment by thea-m** [comment]
Yes, that is a good idea. 
Where would you suggest to include such an element in the records? 
I think it should be, for sure, given in records first described in BM, such as the Suryan collections and these private collections that I'm working on. @DenisNosnitsin1970 , how about the collection that you are describing? Is it already published elsewhere? 
Would you like the Veroli/Casamari collections to be included there? Here there are XML records in BM and a parallel inventory. @SusanneHummel @antobrita 
For now the number of concerned collections is small enough to decide this case by case. Do you think we need a general guideline for this now?

**Comment by DenisNosnitsin1970** [comment]
I think that what makes sense is to publicize the collections which are (or were, until recent time) in private hands. If a collection was built up by a private person entered an institution, in the sense of the modern librarian science, it is called "fond(s)" of someone. "Fond of Conti Rossini", "fond of Sapeto" etc.  I think it makes sense to make notices for those who bequeathed his/her collection to an institution. There is something that they all share - the bequeather collected the books on purpose and deliberate cooperation with modern science, and such a note can just be a commemorative note (and this is common). But I am less sure about EMML mss in possession of private persons in Ethiopia (I am not sure they would favor publicizing, for instance). After some consideration, also I am not sure that we have to publicize in such a way institutional collections (then we have to have notices on of them). Rather, the entries for repositories should be filled with reasonable texts and interlinked with persons, and/or somehow more visible in the web.

**Comment by PietroLiuzzo** [comment]
I now think that probably the easiest and most sensible thing to do is to simply use collection, which can be used multiple time in relation to each identifier. I will then add mechanically to Isl horn afr and EMIP  datasets a standard collection value (ES and EMML already have one). I will index this in the facet and range index as well.

**Comment by PietroLiuzzo** [comment]
items in collections primarily described in BM will have a `<collection>Beta Masaheft</collection>` and e.g. a `<collection>Mathias Müth</collection>` and it will be possible to filter by either.
We can keep having both single pages about this collections or a page with listed collection, as a static page, that is no problem and can be done easily with provided text.

**Comment by PietroLiuzzo** [comment]
- [ ] @thea-m @DenisNosnitsin1970 please send me information for a page about the collections you want to list
- [ ] add a standard `<collection>` value in IslHornAfr and EMIP datasets. similarly mark Veroli/Casemari data set (and others which may be notified here, please) as Beta Masaheft.

**Comment by thea-m** [comment]
Thank you! Could you use as a name "Beta maṣāḥǝft"? :)
The collections I know of described in BM are:
-  Fricke (INS0904TF, nothing to add to the text on https://betamasaheft.eu/Fricke.html) 
- Neukirchen (INS0915Neukirchen, @DariaElagina and  @DenisNosnitsin1970 worked with that one). 
- Dayr as-Suryān (INS0478DS)
I hope I missed nothing, but nothing else comes to mind now. 
(For Müth and Dauwe, no work has been done yet)
