### ISSUE TITLE
problem with attestations function

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1281]
Manuscripts containing references to particular title xml:ids of work IDs are not listed among the attestations of these work records, I think. (It sounds confusing because I'm confused.)
For example: 
I would expect ESap016 (containing `<title ref="LIT1461Gadlah#t1-4"/>` im ms_i1 ) among the attestations of LIT1461Gadlah, but it isn't. 
Other cases I found are: LIT2051Nagara and ESakm010; LIT1015Actsof and the same ESap016.
I think that the encoding itself is correct (though mostly used for different recensions of one work, in which case we now prefer to create new work IDs), but it would be important that the concerned records can be found through the attestations function.

**Comment by PietroLiuzzo** [comment]
LIT1461Gadlah#t1-4 looks like a very creative pointer in this context.
please remove update it with correct information, e.g. the Work id or the id of a `div` element.
The titles in LIT1461Gadlah look to me to be abusing unnecessarily the rules for titles assignment. if these are recensions, why are they not treated as such as suggested also above by @thea-m?
The attestations function has always looked only for the exact identifier. this is not a bug, thus I am changing it into a feature request.

**Comment by thea-m** [comment]
Thank you! I think that this was done in analogy with the encoding versions in other languages of a work. I will check whether there are other cases and correct them.

**Comment by PietroLiuzzo** [comment]
I have updated the attestations function to match things which start with a certain ID, instead of being the same and only the same.

**Comment by PietroLiuzzo** [comment]
please check if it does what you expect

**Comment by thea-m** [comment]
Thank you! (it has skipped my attention)
