### ISSUE TITLE
@facs with @target statement

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1282]
For clarification, when adding an @facs statement to a list of target folios, as in the following example, does the number of image numbers in the @facs statement need to match precisely the number of folio references? 

So, for instance, in the following statement, although the feature is noted as present on two folios, they are actually on the same image, which means that the same image number is referenced twice:

`<locus target="#86v #87r" facs="089 089"/>`

In the examples on https://betamasaheft.eu/Guidelines/?q=facs&id=images each examples where @facs is combined with @target this is the case, but it seems redundant, unless the code requires a precise match

**Comment by PietroLiuzzo** [comment]
Dear Ralph, the information on positioning and that on the images linked to that are separated exactely for this reason. You do not need to provide as many facs as there are targets if they are not needed. 
perhaps it is worth adding an example in the GL, like

`<locus target="#86v #87r" facs="089"/>`

ok?

**Comment by Ralph-Lee-UK** [comment]
Pietro

 

I thought that this was the case, but such an example in the guidelines would be helpful!

 

Regards

 

Ralph 

 

Ralph Lee

Cambridge, UK

* +44 7906149088 
*  <mailto:ralphlee1965@gmail.com> ralphlee1965@gmail.com

 

 <https://www.facebook.com/ralph.lee.7505>   <skype:ralph_and_sarah?add>
