### ISSUE TITLE
Add series (?) Abhandlungen der Philosophisch-Philologischen Classe der Königlich...

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1293]
Should "Abhandlungen der Philosophisch-Philologischen Classe der Königlich Bayerischen Akademie der Wissenschaften" be added as a series in Zotero? Such as Trumpp 1881 (Gädlä Adam)?
And then "I. Cl., XIV. Bd., III. Abth." as a series number?

**Comment by FrancescaPanini** [comment]
Yes,
see this example: https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/TF3WSMFA/q/kebra%20nagast
