### ISSUE TITLE
Stray Characters

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1294]
Ashlee Benson and I are both experiencing the appearance of stray characters in files. For instance the following code, that is found in EMIP02026.xml

                      (haräg); &gt;<locus target="#16r #55v" facs="016 056"/> (multiple full stops);
                      &gt;<locus target="#52v" facs="053"/> (line of black dots)

The characters "; &gt;" appear twice in this line, but I am sure (99% at least) that these characters were not present when I saved the file, and then committed the edits. There are a few other cases, where this has happened. In this particular case I am confident (although 100% of course is impossible) that Ashlee did not enter these characters, as in the only thing done was copy from a spreadsheet the 'facs=" statements that are present in the file. 

I am trying to get to the bottom of this, and will, of course, be double checking for local causes. As you know both Ashlee and I have had issues with the linter-autocomplete-jing - which has sometimes failed. We have both introduced the habit of entering an incomplete command at the start of editing, and waiting for the autocomplete to start, which can sometimes take a minute or two, before continuing to edit. 

I'm just trying to get to the bottom of any ways in which these characters might have been introduced later in the process. I accept that this is unlikely, but these are also unusual characters to have typed in twice in error!

**Comment by PietroLiuzzo** [comment]
My best guess is that the copy paste operation has produced these. 
It does not seem to have anything to do with either Atom, the linter package or anything else. 
perhaps that step can be avoided to test if removing the step removes the issue?

on the failures of the linter package I have no solution. You can try and report a detailed issue to the developer of that package. We have not experienced this issues. I would suggest trying to reinstall java and reinstall after that Atom and the package (with its dependences). 

Alternatives are to use another software if Atom is not fine for you. our preference here is for Oxygen XML, but you can use any XML editor which has a way to validate. I am not aware of other easily usable options.

I am afraid this does not help much
