### ISSUE TITLE
encoding of "edited" text in catalogues

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1296]
What do you think would be the best method for us to encode the text given by Wright for example in the incipit of BL Orient 678, where the text of this manuscript is given with the variants of BL Orient 683?
https://archive.org/details/catalogueofethio00brituoft/page/58
I would tend towards separating the text of the two manuscripts, and giving each in the respective records, instead of trying to reproduce a sort of apparatus in one of the records.

**Comment by PietroLiuzzo** [comment]
How difficult would it be to split this text in two? I am not sure how complex this would become, but it would be certainly interesting. 
if the text is know, could it go in the text record and be encoded with apparatus there (so the text is not to be split)

**Comment by thea-m** [comment]
In this case, it is not very complicated (as you can see in the link I gave), since they are only the variants of two manuscripts. I cannot estimate whether it would make more sense to give the text in the work record. It is already edited (precisely with these two manuscripts) by Budge, but we don't have the text of the edition in our record.

**Comment by abausi** [comment]
Actually, I have an (unpublished) edition of mine of this text ("Introduction" and "Preaching of Peter") prepared on the bases of MSS EMML 1482 (ff. 2ra-11va), 1767 (ff. 3ra-21rb), 1825 (ff. 1ra-15vb 126ra), 6839 (ff. 1ra-8vb), 7604 (ff. 5ra-16va), and Bibliothèque nationale de France (Paris), Zotenberg 52 [Éthiopien 33bis] (ff. 1ra-15vb), d’Abbadie 58 (ff. 2ra-14va), and d’Abbadie 64 (ff. 2ra-13rb) = 
Budge 1899, 4-36. Shall I send this to you? I have also an (unpublished) transcription of the corresponding Arabic text, from a manuscript in Florence.

**Comment by PietroLiuzzo** [comment]
ok, so we will add the text from Alessandro and the witness list but not the apparatus, so @abausi can still publish that as well or someone else can enter the apparatus at a later stage. thanks!

**Comment by PietroLiuzzo** [comment]
@thea-m point me here to the correct branch where to commit the text, thanks!

**Comment by thea-m** [comment]
branch GH. I was unsure how to deal with the printed edition witness. thank you!

**Comment by PietroLiuzzo** [comment]
I have made two commits with the text and some statements about authority.
for the witnesses list, I have nested a listWit linked to the budge bibl and given to that the xml:id="Z", I think it is quite accurate.

**Comment by thea-m** [comment]
It looks good to me!

**Comment by PietroLiuzzo** [comment]
then we can PR it! but I am not sure what sort of other changes does this GH branch include....

**Comment by PietroLiuzzo** [comment]
(I should have closed it with the Merge... sorry)
