### ISSUE TITLE
spaces before word separator in old BL records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1299]
In many old BL records, there are spaces before the word separator in Geez text. Theoretically it would be nice if it would be corrected, I have no time for this now. It could possibly be a future training exercise.

**Comment by eu-genia** [comment]
You are right. I could easily do it but since there are quite a few records involved maybe it is better if @PietroLiuzzo could batch replace " ፡" through "፡" and " ።" through "።"?
It could become quite a big merge
