### ISSUE TITLE
encoding of a commisioner note (?)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1300]
I am unsure how to encode the note given in BLorient678 on f. 137v. Here is the catalogue description:
https://archive.org/details/catalogueofethio00brituoft/page/60 (p. 61b)
The text is: 

> ወዘአጽሐፍዋ፡ ለዛቲ፡ ገድለ፡ ሐዋርያት። ሳፎንያስ፡ ወደራቴዎስ፡
>                                     ወምክሕነ፡ ክርስቶስ፡ አርድእት። ወዘጸሐፋ፡ ፊቅጦር፡ በእንተ፡ ፍቅሮሙ፡ ለ፲ወ፪ሐዋርያት፡ ተአሚኖሙ፡
>                                     በጸሎቶሙ፡ ለ፲ወ፪ሐዋርያት፡ ወለ፸ወ፪አርድእት፡ ይጽሐፍ፡ ስሞሙ፡ ኀበ፡ ዐምደ፡ ብርሃን፡ በቀለመ፡
>                                     ወርቅ፡ ኀበ፡ ይሴባሕ፡ ኢየሱስ፡ ሊቅ፡ በዜማ፡ ዕሙቅ፡ ወበስብሐት፡ ድሙቅ፡ ለዓለመ፡ ዓለም፡ አሜን፡
>                                     አሜን፡ ወአሜን። ለይኩን። ለይኩን።

It seems to me neither a colophon nor an addition (for now, I encoded it as explicit without type), rather a scribal note on the commissioners and scribe. Can you help me?
@DenisNosnitsin1970 @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
I think it is a supplication for the commissioners and scribes. ወዘአጽሐፍዋ፡ ... ወዘጸሐፋ፡... ይጽሐፍ፡ ስሞሙ፡ ኀበ፡ ዐምደ፡ ብርሃን፡

**Comment by thea-m** [comment]
Yes, of course, you are right! I will encode then as explicit type supplication. Thank you
