### ISSUE TITLE
retrieve or recreate persons for BLorient678

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1301]
PRS12796Sofonyas, PRS12854Daratewos, PRS12855Fiqtor (who created 50 records in the ten seconds between me creating Sofonyas and Daratewos??) could not be downloaded, either retrieve or recreate them when I can again

**Comment by thea-m** [comment]
When trying to re-create IDs for these persons for whom I could not create IDs, I get 

> Dear Dorothea, unfortunately PRS12796Sofonyas already exists! Please, hit the button below and try a different id.

(even though theoretically it would be possible that I would want to create a different ID for a different person with the same name...though here I don't)
Can you help? @PietroLiuzzo

**Comment by thea-m** [comment]
PRS12856Sofon created on 20.12. did make it to my new folder! I am confused. Now I tried to re-create Daratewos and could create but not download:
![image](https://user-images.githubusercontent.com/19650382/71882115-147cb900-3134-11ea-951e-095666ee68b8.png)
(The numeric part of the ID assigned continues from the last ID in the numbered folder, not the new 
 folder. It's not a problem because it's still an unused number - the new folder somehow continues 
 12809, but still strange )

**Comment by thea-m** [comment]
I created and downloaded PRS12861Daratewos normally on my laptop. The numerical ID assigned is one that already exists in PRS12861Gasaggasa @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
there was never any check for the numeric part of the ID for persons, places, manuscripts, etc., only a check for unicity. the only place where this check of the numeric part happens is Works. If this is now disturbing I can introduce a counter, but the ones which have been already assigned a valid and correct unique identifier will remain so as there is no need to change them IMHO. let me know

**Comment by thea-m** [comment]
Yes, I know, otherwise I would have changed them already. I'll close this since this issue seems only to occur on my desktop.
