### ISSUE TITLE
standardise list of digitised manuscripts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1302]
https://betamasaheft.eu/availableImages.html 
standardise spelling, presentation

**Comment by thea-m** [comment]
@PietroLiuzzo If I do this, can I send you a word document with my modifications, or can you send me an XML record of the current list that I can edit?

**Comment by PietroLiuzzo** [comment]
This fragment of HTML is as every html page of the application also stored here in github, although not synced directly.
https://github.com/BetaMasaheft/BetMas/blob/master/BetMas/availableImages.html
if you edit it and make a PR to that repo I will then merge it and also upload the new file.
thanks!
