### ISSUE TITLE
"More than 1 ApocalypticLiterature"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1303]
When creating a new work, among the genre keywords there is "More than 1 ApocalypticLiterature". To me, it seems that the keyword has the correct amount of records in authority files, the taxonomy and schema
![image](https://user-images.githubusercontent.com/19650382/71815109-b0e48400-307e-11ea-9f70-96b3e6612731.png)

**Comment by PietroLiuzzo** [comment]
please refresh

**Comment by thea-m** [comment]
thank you!
