### ISSUE TITLE
Institutions in new folder not available on the app

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1304]
All institutions in the new folder are not available on the app, see for example 
https://betamasaheft.eu/manuscripts/INS0904TF/list

> INS0904TF is not the id af any available repository.

**Comment by PietroLiuzzo** [comment]
Thanks for pointing this out. This was an obscure permissions issue. Please check now, it should be ok.
please note the settlement ref, where wd: is missing. Thanks

**Comment by thea-m** [comment]
Perfect, thank you!
