### ISSUE TITLE
abstract in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1305]
There are several person records where information on the person is encoded in `<abstract>`, for example PRS12697Tewoflos. I think that we have never discussed this use, it is not mentioned in the guidelines and not visualized. Maybe it would be better just to move this information to `<person>`?

**Comment by DenisNosnitsin1970** [comment]
Possible. My consideration was only to add a couple of narrative lines concerning the persons.

**Comment by thea-m** [comment]
Yes, I see. Will you edit the records?

**Comment by DenisNosnitsin1970** [comment]
If you mean the structure like below,  
<person sex="2">
                    <persName xml:lang="gez" xml:id="n1"> ወለተ፡ ገብርኤል፡</persName>
                    <persName xml:lang="gez" type="normalized" corresp="#n1">Walatta Gabrǝʾel</persName>
                    <faith type="EOTC"/>
                    <occupation type="other"/>
                    <birth/>
                    <death/>
                    <floruit/>
                </person>

sometimes it does not allow to include specific types of nformation. Here, a very precise information is necessary, in fact, we have it in not many cases.

**Comment by thea-m** [comment]
I see, I also have occasional troubles with person records (but never worked intensively at them).  As I understand it, most of what would be relevant bibliographical information would go to "floruit", see the guidelines https://betamasaheft.eu/Guidelines/?id=persons. In any case, if there are types of information that you would like to include but find no place for, could you open an issue to discuss it? It is in these cases probably a larger problem that doesn't only affect you, but everyone else as well and we would benefit from the discussion.

**Comment by PietroLiuzzo** [comment]
The example in PRS12697Tewoflos seems to me more a case where a state-like element, e.g. occupation would be needed. abstract is certainly not correct.

**Comment by PietroLiuzzo** [comment]
https://tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSEpc

**Comment by PietroLiuzzo** [comment]
note is also fine, as we are not focusing on persons right now...

**Comment by thea-m** [comment]
Thank you!
