### ISSUE TITLE
collation help

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1308]
I have a manuscript (without leather cover), where a parchment "bifolium" (or rectangular strip of parchment) has been used to include the entire textblock, i.e. it constitutes the first and the last folio, and all quires are contained within it (probably to stabilise the book). I am unsure how to describe and encode this. It seems rather as pertaining to the binding than the collation? Should there then be a note in collation with reference to the binding explaining why the collation begins with f.2? Or would you rather suggest to encode this as part of the collation?

**Comment by DariaElagina** [comment]
I have seen something like that, I would suggest that this "bifolium" rather should be encoding in binding, a note in collation would be sufficient.

**Comment by thea-m** [comment]
I agree, it makes more sense. Thank you!
