### ISSUE TITLE
support IIIF images from bodlein in viewer

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1310]
@SophiaD-M discovered that the Bodleian has actually already digitised some Geez manuscripts. 
@PietroLiuzzo , could you add to our https://betamasaheft.eu/availableImages.html
Bodleian Library  (https://digital.bodleian.ox.ac.uk/inquire/Discover/Search/#/?p=c+2,t+ethiopian,rsrs+0,rsps+10,fa+ox%3Acollection%5EEthiopian%20and%20Eritrean%20Manuscripts,so+ox%3Asort%5Easc,scids+,pid+,vi+) (Search for "ethiopian", filter by "Ethiopian and Eritrean Manuscripts", click on the leaves icon at the upper right corner of each search result to view the images)
And what are the possibilities of linking to these images in our records? 
Thank you!

**Comment by PietroLiuzzo** [comment]
These have a IIIF Manifest. We should link that to the catalogue entries as well.

**Comment by thea-m** [comment]
Yes, my question was how to do that :) where should which link be added?
the permalink for 1r? https://digital.bodleian.ox.ac.uk/inquire/p/7d89c73d-96b5-4d53-a739-01073305cf57?

**Comment by PietroLiuzzo** [comment]
is the  @facs of <idno> not fine ?
https://betamasaheft.eu/Guidelines/?id=images
the link you want to add is 
the one under the iiif logo, https://iiif.bodleian.ox.ac.uk/iiif/manifest/637a8b9e-6ac5-4942-aa13-52a5266b65c7.json

**Comment by PietroLiuzzo** [comment]
I will see when this is added and provide support for rendering it.
