### ISSUE TITLE
encoding weight of manuscripts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1311]
I would like to encode the weight of manuscripts, which we have not done until now (as far as I am aware of). 
Intuitively, I would add this information in  `<extent>` as `<measure type="weight" unit="g"></measure>`. What do you think? (About the encoding, not the point of the undertaking, please :) )

**Comment by PietroLiuzzo** [comment]
Well, I am indeed curious about the point of the undertaking! your proposition for the encoding is attested in the TEI guidelines, so I think it is a safe way to go.

**Comment by thea-m** [comment]
thank you, I'll add it to the guidelines later

**Comment by PietroLiuzzo** [comment]
Thanks, there you really want to provide some evidence of why this is useful.
