### ISSUE TITLE
"personal page" on BM not availabe

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1313]
My personal page https://betamasaheft.eu/user/Dorothea is not available
Either you are not requesting your personal account or the account guest/Dorothea is not an enabled account or you are not authenticated.

**Comment by PietroLiuzzo** [comment]
thanks for opening the issue this does not work because of the login not passing on the data.

**Comment by PietroLiuzzo** [comment]
I have restored at least the visibility of the non sensible informations, those which do not require login for the moment
