### ISSUE TITLE
encoding unfoliated guard leaves

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1314]
What would be the best way to encode the presence of unfoliated guard leaves? There are several ways this has been done in records, due to the varied origin of the records.
For example, the Bruce manuscripts have several guard leaves at the beginning and end, which are not foliated and not taken into account by Dillmann's catalogue in the amount of folios given and othe description. According to what we already have in the records, these would be some possibilities for describing the case of three guard leaves at the beginning and one at the end (the total fol. number of the manuscript would be 73):
```
<measure unit="leaf">3+69+1</measure>
<measure unit="leaf">iii+69+iv</measure>
<measure unit="leaf">69+I-III+IV</measure>
```
Are any of these better from the point of view of the encoding, or is it a question of personal preference?
Occasionally, these leaves actually are part of a quire which also contains the first foliated leaves and beginning of the text. Would this change the description in `<measure>` (it is described in the collation)?

@DenisNosnitsin1970 @PietroLiuzzo

**Comment by DenisNosnitsin1970** [comment]
I personally find the way <measure unit="leaf">iii+69+iv</measure> the most optimal and transparent. Yes, classically, the guard leaves at the beginning and at the end are frequently not considered as part of the textblock, but rather the part of the binding. Many manuscripts in the libraries have been modified by the conservators/librarians, and the guard leaves were added in the libraries (when the volumes were rebound) and later tacitly disregarded in the descriptions.  I think we have to consider them and take them back into the description, according to opportunities of physical checking. A remark (like, "the guard leaves were added in the BL") can be also added under the collation.

**Comment by PietroLiuzzo** [comment]
Formally this is important for many computational tasks, and variation here is the rule apparently. If I want to parse  iii+69+iv, how would I have to understand each part of the notation? That there are 3 guard leaves at the beginning, 69 with an arabic numeral for the total, and a fourth at the end? then the first position in the notation is a total in roman numerals (why?), but the last position in this small formula is an ordinal number. what if there are two guard leaves at the end? V?. I do not find it very transparent, honestly, each position in the notation has a different format and needs interpretation. 3+69+1 is much more coherent, with only totals, all in arabic numerals. This said, the one can, with effort, be transformed into the other and backwards. this is not true for 69+I-III+IV which also break an ideal sequence.

Creativity in this element includes a minority of interesting things like
164 (I + 163) 
1-71 + 1(after 91) 
1-91 
101.0 
101a-116b 
122 (III + 118 + 42a)
128+4
134 (1 + 133) 
138 + 5 
152 (V + 147)
153ff 
1a-100b and 117ab 
21-188

not only these are not computable, they are not reliably parsable to get out of them some information.

We could over fix here and do something like the following
```xml
<measure unit="guardleaf" type="front">3</measure>
<measure unit="leaf">69</measure>
<measure unit="guardleaf" type="back">3</measure>
```

But I understand that this is a though argument.

```xml
<measure unit="leaf">3+69+1</measure>
```

would be ok, and I can then print it as III+69+IV in the website, if this is deemed better. If we decide for 
```xml
<measure unit="leaf">iii+69+iv</measure>
```
I will do nothing in terms of filtering the view and have to parse every time in the scripts.
please let me know, if no comment rises, I will go with the second as it is supported by the comment above.

**Comment by thea-m** [comment]
Thank you, @PietroLiuzzo for rescuing this neglected issue!

>  If I want to parse iii+69+iv, how would I have to understand each part of the notation? That there are 3 guard leaves at the beginning, 69 with an arabic numeral for the total, and a fourth at the end? 

Yes, that's it.

You are completely right that the existing notations are intransparent and confusing. If it is any consolation, they do reflect existing past and present practices, and especially in the historical catalogues, the notations are hardly understandable.

This proposal

```
<measure unit="guardleaf" type="front">3</measure>
<measure unit="leaf">69</measure>
<measure unit="guardleaf" type="back">3</measure>
```

seems ideal and clear to me, at least for new cataloguings where we see the manuscripts and can actually form an idea of the existence of guard leaves. I expect that it would still run into trouble for some historical catalogues, but this is an issue of intransparence of the catalogues, not our notation.. This could then be visualised on the app how ever more qualified people would desire.
@DenisNosnitsin1970 what do you think?

**Comment by PietroLiuzzo** [comment]
just to point out, I think it would be much more encodable to stick to `<measure unit="leaf">3+69+1</measure>` and visualize this as iii+69+iv if so desired. Simple encoding with 
parsable pattern, visualisation as in the tradition. I have already some code to take into account some deviations among those listed above.

**Comment by DenisNosnitsin1970** [comment]
To visualize, then, as i-iii+69+iv.

**Comment by PietroLiuzzo** [comment]
that can be done, sure! so I will 
- [ ] use this assumption in the script (but also hide some of the existing alternatives with some computation)
- [ ] make an update to the guidelines page with this suggestion for measure. if references for this kind of notation are available, it would be great to point to some literature in support of the encoded pattern and the visualised one, if none, I will simply point out that this is our way, and take some bits from this conversation
thanks a lot

**Comment by thea-m** [comment]
Thank you!
