### ISSUE TITLE
listBibl without div in work records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1319]
There are many work records in which a listBibl element is given in body without being inside a div element (my presumably imperfect xpath found 82). These bibliographical references are not visualized on the app. (I think that this is how bibliography used to be encoded a long time ago?)
Is there a way of either visualizing these references or batch correcting the concerned records?
I would say that it is quite an important issue, since currently it appears to users that a considerable amount of our records is without bibliography.
For example LIT2281Trinity or LIT2388Taamme
Thank you!

**Comment by PietroLiuzzo** [comment]
I cannot see any `listBibl` in LIT2388Taamme
