### ISSUE TITLE
Correction marks in manuscripts

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1320]
There are various marks used to show corrections or missing text, most of them encode ok, but I am struggling to find the symbol in this clip from a catalogue, that looks a little like a capital I in a serif font. Any ideas what symbol to use for this? It seems to come out blank in the Atom editor
![image](https://user-images.githubusercontent.com/39619238/74261877-cf7c1180-4cf3-11ea-8bcc-ff66c6ad9949.png)

**Comment by PietroLiuzzo** [comment]
I think that I would personally avoid trying to reproduce the glyph in the text, if not strictly necessary (i.e. phrase "a symbol is used" instead of "the symbol (...) is used"), and if this is not one that has made it into a Unicode chart. we can instead 
- include an image of a specimen (support for visualization to be added)
- add locations of specimena that will link to the viewer where the symbol can be seen as is without attempt at reproduction in unicode.
What do you think?

**Comment by Ralph-Lee-UK** [comment]
An image of a specimen when possible would be good, partly because sometimes there are several marks on a page, so let us know when this functionality might be available. 
The second is also good and can be implemented immediately, and could be included with a comment as to the column and line of text to look at, which would get over the problem mentioned above. There are some cases also where the image set already includes close ups of these symbols, in which case they could also be added. 
I will follow this up with the EMIP team in a meeting that we will have tomorrow afternoon. 
Many thanks

**Comment by PietroLiuzzo** [comment]
This has several implications which at the moment make me think it is better to postpone and better investigate how to do this. pointing to the location in the image and displaying that instead of somehow uploading an image would be preferable

**Comment by PietroLiuzzo** [comment]
the same code can be used for surfaces and facsimile from transkribus #1472

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK this is an example from my development db, not yet available
<img width="640" alt="Schermata 2020-09-15 alle 21 39 37" src="https://user-images.githubusercontent.com/508012/93256694-fe7fc780-f79b-11ea-98d6-2ef3536e3b61.png">
It should show you where I am now with this. You may obtain, once this is completed, this image by adding something like
```xml
<rs><graphic  xml:id="g1" 
     url="https://betamasaheft.eu/iiif/EMIP/Codices/1928/015.tif/1780,500,40,35/full/0/default.jpg"/>
 </figure></rs>
```
which I am documenting in the GL as well. 
The tricky part here will be to get those x,y,w,z, which form the region, but for images you have access to, this may not be that complicated.
eventually, I am also working on extracting this information for files where we have an aligned transcription. every <locus> will show also the linebox aligned to it and the transcription, so, if transcription and zones are available, with a correct locus, e.g.
`locus target="14ra4"` you will get the line in which this symbol occurs as you reference it, and thus eventually have no need to add further images.

**Comment by Ralph-Lee-UK** [comment]
This is great, and looks like a comprehensive solution to the problem. I look forward to trying it out on some of our records.

**Comment by PietroLiuzzo** [comment]
the first part of this is operational, you can try. gl are updated in the images branch, locus support will come as part of issue on transkribus
