### ISSUE TITLE
Locus target statements and additional clarifying text

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1321]
In encoding locations using @locus, it is sometimes necessary to add text following links. So, for instance, the catalogued might read "f. 6r and passim" or it might read "f.121v line 12".

In the guidlines, the following example of code is given:
<locus from="1v" to="2ra">the text begins on 1v in line 1 and ends on 2ra in line 6 </locus>
Found at 
https://betamasaheft.eu/Guidelines/?q=locus&id=referencing-the-manuscript&start=6

Which I had interpreted as a way to deal with this, so for instance I have code in 
https://betamasaheft.eu/manuscripts/EMIP01951/main#9r
<locus target="#9r" facs="011"> and passim</locus>

On the webpage this is seen as 
![image](https://user-images.githubusercontent.com/39619238/74342594-a3b76500-4da1-11ea-977a-fcb126b724e7.png)

Although when the link is clicked on, folio 9r does open.

There are various other examples, so in EMIP01990

                        <item xml:id="e15">
                          <locus target="#78v" facs="081"> line 16</locus>
                          <desc>lines of text written in the upper margin with a symbol (┴) marking the location where the text is to be inserted</desc>
                          </item>

And here it looks like
![image](https://user-images.githubusercontent.com/39619238/74343130-71f2ce00-4da2-11ea-921d-2c4eb2d0ac90.png)

Have I misunderstood the correct way to encode this? If I have the wrong understanding of what this should be used for, is there any other way of adding some clarifying text following an image link. This could be accomplished in both these cases by including the text of the folio reference with the added comment, for instance.

**Comment by PietroLiuzzo** [comment]
Dear Ralph, if you chose to use text within `<locus>` you will have to provide the entire string. 
`<locus target="#6r">f. 6r and passim</locus>`

**Comment by PietroLiuzzo** [comment]
we use at the moment `@n` for the line number, but this has many limitations and a discussion about this was started in #1162

**Comment by Ralph-Lee-UK** [comment]
All clear, many thanks
