### ISSUE TITLE
Links to attestations in the calendar view don|t work

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1322]
In the calendar list https://betamasaheft.eu/calendar.html, the links to the manuscript records attested under each date don't work (I assume that they are meant to be links since the cursor transforms into a hand...).
For example, under 20 Maggābit, two manuscripts are listed, it would be nice to click on them and be led to their respective pages. The link to a work record under 2 Yakkātit for example, works as expected.
Not urgent :)

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/75024996-aa796280-549a-11ea-8cb0-9203dd50b5fb.png)

**Comment by PietroLiuzzo** [comment]
thanks, this was a silly mistake by my...
