### ISSUE TITLE
Image links, and folio numbers

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1323]
As you know we are working at getting the Tweed collection files finished. As part of this process we are producing a new set of images, at least for some cases, where the image set is not correct. 

The new image sets will not automatically have the folio number stamped on the image, which raises a question as to whether there is another way of marking the folio number in the viewer?

For instance, if you look at https://betamasaheft.eu/manuscripts/EMIP01997 
Scroll down to the 'frame notes' and click on the first long set of links under 'decorative designs.' The image viewer will open, and the current image set has the folio stamped in the corner of the image. As you can see the image viewer opens and obscures the list that was clicked. Without the folio number stamp, it would be difficult to know which image one was looking at, especially in a long list like this. 

Would it be better to be sure to continue having folio numbers stamped, or can we code this so that the folio number in the xml file also appears in the viewer window.

Attached is a screen shot of what I am talking about. 

![image](https://user-images.githubusercontent.com/39619238/74958650-2f17a280-5401-11ea-9e14-184ecdc15642.png)

**Comment by PietroLiuzzo** [comment]
I will change the behaviour of this box to show the information on which one has clicked as well, so on top, under Images from EMIP/Codices/1997/ it will say : decoration 1 .... f. 8 and whatever follows. no changes needed in your encoding

**Comment by PietroLiuzzo** [comment]
If you check now you will find that I have added some explicit information on the sequence of images displayed.

**Comment by Ralph-Lee-UK** [comment]
Just checked, and this is a very good solution to this problem. Many thanks
