### ISSUE TITLE
Text of search results

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1324]
In the search result list view of work records, there appears, in cases where the works have short titles, often the beginning of "Akademie der Wissenschaften" directly after the title. I think that the list would look cleaner if there were only the title among the results.

**Comment by PietroLiuzzo** [comment]
Dear Dorothea, could I ask you to help me to understand with a screenshoot? 
thanks

**Comment by thea-m** [comment]
I could not download the snipping tool to the new computer, but I'll try something

**Comment by PietroLiuzzo** [comment]
Mit diese [Anleitung](https://support.microsoft.com/de-de/help/13776/windows-10-use-snipping-tool-to-capture-screenshots) gehet es nicht?

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/75024567-e95ae880-5499-11ea-9087-75d9108efe2f.png)
Thank you! :)

**Comment by PietroLiuzzo** [comment]
ignore <publicationStmt/> in index

**Comment by PietroLiuzzo** [comment]
this was actually the kwic:get-summary function. I changed the first parameter to use as context for the KWIC only the parent element, instead of the entire file.
