### ISSUE TITLE
Possible source of unusual validation errors

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1329]
We have for some time been experiencing stray characters appearing in edits using Atom. 

Today, I spotted the following error in file EMIP02015.xml

![image](https://user-images.githubusercontent.com/39619238/75367166-c5dbd780-58b7-11ea-903d-c06caf8dfba3.png)

You will see that the error message finds errors in a line of code which, as far as I can see is fine! I have even rewritten the line to check for stray characters. There is no red dot indicating an error. 

Any thoughts on what might be going on?

**Comment by PietroLiuzzo** [comment]
I am afraid I am not able to help. I will post the same here

https://github.com/aerhard/linter-autocomplete-jing/issues

to the developer of the extension

**Comment by Ralph-Lee-UK** [comment]
Thanks.

**Comment by PietroLiuzzo** [comment]
I am testing this and the error is ok, I mean that is what it is supposed to tell you as you key in the element. however, this does not seem the case in your screenshot. my best guess is that you are not having connection anymore with the schema, so it cannot validate again to tell you that it is ok... may this be part of the issue?

**Comment by Ralph-Lee-UK** [comment]
Interesting. My internet connection is fine today, and as soon as I type a deliberate error then the error shows. Puzzling
