### ISSUE TITLE
visualization of titles crossreferenced

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1333]
There are instances where titles loop endlessly because no decision can be made, causing not little trouble. I  am happy I found out this issue, but I am not sure how to solve it. I would be glad for quick feedback, please @thea-m @eu-genia @DenisNosnitsin1970 @DariaElagina 

here an example
I am trying to get the title of LIT1960Mashaf#SupplicationApostles and I end up here

```xml
<div type="textpart" xml:id="SupplicationApostles" corresp="LIT4711Mastabqwe#SupplicationApostles">
<label>
ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles”
</label>
...
</div>
```

the code is told to look for @corresp if it is there, so I do and find in LIT4711Mastabqwe#SupplicationApostles

```xml
<div type="textpart" xml:id="SupplicationApostles" corresp="LIT1960Mashaf#SupplicationApostles">
<label>
ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles”
</label>
...
</div>
```
because there is again a @corresp, it goes back and so on... forever... 

Now, I understand that this is to say that they are the same, I want to be sure what I am doing:
is it fine if I ignore @corresp if a `<label/>` is present?

**Comment by PietroLiuzzo** [comment]
in the first case for  LIT1960Mashaf#SupplicationApostles this would say 

> "Maṣḥafa qǝddāse, ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles” same as LIT4711Mastabqwe#SupplicationApostles"

in the second case for LIT4711Mastabqwe#SupplicationApostles  it would say 

> "Mastabqʷǝʿ, ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles” (same as LIT1960Mashaf#SupplicationApostles)"

but I could also have it print the following, e.g. for the first, and the other way around for the second

> Maṣḥafa qǝddāse, ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles” same as Mastabqʷǝʿ, ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles

**Comment by DenisNosnitsin1970** [comment]
The both seems to be the same in any case (probably it was not possible to ascertain as the text of one is missing/ not accessible).

**Comment by PietroLiuzzo** [comment]
Thanks @DenisNosnitsin1970. I am currently concerned only about the title display formatting and to avoid this error

**Comment by PietroLiuzzo** [comment]
sorry, the third is not an option, it would loop again.
I could do this 

> Maṣḥafa qǝddāse, ጸዋትው፡ ዘአበዊነ፡ ሐዋርያት፡ ṣawātǝw zaʾabawina ḥawāryāt “Series (of Supplications) of our Fathers the Apostles” (same as #SupplicationApostles in  Mastabqʷǝʿ)

**Comment by eu-genia** [comment]
looks good!
