### ISSUE TITLE
Missing commits 

### ISSUE THREAD

**Issue by Ashlee-Benson** [BetaMasaheft/Documentation#1334]
So there is an issue! Ok, let's try and make clear what the problem is
There are some mss that I worked on and committed that are not showing up as changed in Atom, despite the fact that it's been a couple of weeks since the pull request for them went through.

I just did some research on GitHub to see if I could locate the commits.  I could not find them when I looked at the main "History" tab on the desktop version of GitHub.  But, when looked at the specific branch they would have been on by using the "Select branch to compare..." feature, then I was able to locate them.  I then went to the GitHub website and found the pull requests they should have been in and looked under both the "commits" tab and the "files changed" tab for the respective pull requests and they're not there either.  There are commits on there from either you or Jonah on those days as well, so it's like only mine went missing.  I'm not sure what's happening.  

I have backup files of these mss, so while I can copy and paste the changes from the backups, I wanted to touch base with you to discern if I would be messing anything up by doing this, since they can be found in the commit history, but have not been updated in Atom for some reason.

which records or views are affected?
If you want some details to look into this further, one commit was made on 2/4/2020, it was for EMIP 690-708, and 1952.  These can be found in the branch from 30-Jan-2020.  There is another set of mss that have changes missing as well that were committed on 2/7/2020 (in branch 02-Feb-2020) EMIP 709-741 and 1921-1922.
if it an issue about the data, on which branch are you?

what is that you are trying to do?

what have you tried ?

If there is a guidelines page please add link.

if you get an error, which error do you get, just copy it here

Is it something about visualisation?

What do you see?

What is wrong with it?

What would you like to see?

**Comment by PietroLiuzzo** [comment]
Dear @Ashlee-Benson, I am growingly concerned about this. The problem described above seams to me very likely an issue related to missed pushes and changes of branches which I am not in a position to investigate. I am also a bit worried about these backup copies.
once you are sure that your master branch is up to date and the current EMIP working branch is up to date, please consult with your co-editors for the branch and very carefully make the changes, commit them and push them to the new branch. @Ralph-Lee-UK @jonahsandford could you please assist? please report back via email

**Comment by Ralph-Lee-UK** [comment]
We'll work on this, definitely. From what you say this appears to be an issue with the changeover between branches, and what happens if an editor continues work on an old branch before a new branch is cloned? What we have been doing is continuing work, and then once a pull request is approved, cloning a new branch, and when this is switched to GitHub gives the option of moving the edits to the new branch. That potentially could produce problems if these edits are on files that are also included in the pull request - but I think GitHub deals with this? Perhaps we could have a quick chat about what might be going on?

**Comment by Ashlee-Benson** [comment]
Ralph,

Can you and I meet for a bit after our meeting with Steve today?

I’m not sure if Pietro’s assessment of the situation is entirely correct.
1.) these were files that were not worked on by anyone else besides me 2.)
at least one set of the missing commits was committed before a pull request
on that branch was even made. I’m looking into the other one.

Ashlee
