### ISSUE TITLE
provenance of Madhane Alam manuscripts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1338]
From @DenisNosnitsin1970 

> provenance" I would always start in such cases with saying that the book was looted (taken, according to your point of view) by Tewordos II from an unidentified church in or around Gondar (sometimes identification is still possible) and brought to his church of `<placeName ref="INS0101MadhaneAlam"/>`.

to be improved in the records

**Comment by DenisNosnitsin1970** [comment]
It can be done at least in those mss where we have the "new" ownership note. There are many mss where we do not have it now (lost with the leaf) or only traces of it (erased), we can only assume (still, the assumption can be expressed in the description).
