### ISSUE TITLE
Pull/push error

### ISSUE THREAD

**Issue by Ashlee-Benson** [BetaMasaheft/Documentation#1340]
So there is an issue! Ok, let's try and make clear what the problem is
Unable to pull/push on GitHub, keep receiving the following error: 

error: cannot lock ref' refs/remotes/origin/EMML4398':unable to resolve reference 'refs/remotes/origin/EMML4398': reference broken
From https://github.com/BetaMasaheft/Manuscripts
! [new branch]          EMML 4398         -> origin/EMML4398  (unable to update locate local ref)
error: cannot lock ref 'refs/remotes/origin/NeuekirchenMss': unable to resolve reference
'refs/remotes/origin/NeuekirchenMss':reference broken
! [new branch]           NeuekirchenMss => origin/NeuekirchenMss  (unable to update local ref)
which records or views are affected?

if it an issue about the data, on which branch are you?

what is that you are trying to do?
pull and push commits
what have you tried ?
restarting GitHub
If there is a guidelines page please add link.

if you get an error, which error do you get, just copy it here
error: cannot lock ref' refs/remotes/origin/EMML4398':unable to resolve reference 'refs/remotes/origin/EMML4398': reference broken
From https://github.com/BetaMasaheft/Manuscripts
! [new branch]          EMML 4398         -> origin/EMML4398  (unable to update locate local ref)
error: cannot lock ref 'refs/remotes/origin/NeuekirchenMss': unable to resolve reference
'refs/remotes/origin/NeuekirchenMss':reference broken
! [new branch]           NeuekirchenMss => origin/NeuekirchenMss  (unable to update local ref)
Is it something about visualisation?

What do you see?

What is wrong with it?

What would you like to see?

**Comment by thea-m** [comment]
Could you try it again to see whether the EMML4398 branch still comes up in the error message? I now commited a record whose ID I had used before, maybe that posed a problem? (but probably not)
Thank you, Dorothea

**Comment by Ashlee-Benson** [comment]
Hi Dorothea, I've tried multiple times and it's still giving me the same error.

**Comment by PietroLiuzzo** [comment]
Please @Ashlee-Benson, hold on and avoid any further attempts. I may need to call you and see your screen, and guide you step by step. By all means please read carefully and do not say ok to any action suggested without fully understanding what is happening.

**Comment by Ashlee-Benson** [comment]
We can send you a link to a meeting we have now. Please stand by for an email

**Comment by PietroLiuzzo** [comment]
I will then make time now. In general, please do not post in the issue tracker of the project issues related to your workflow, just contact me directly.
