### ISSUE TITLE
saws:formsPartOf to be corrected

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1341]
@eu-genia in the following24 record https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootPl%2F%2Ft%3Arelation%5B%40name%3D%27saws%3AformsPartOf%27%5D saws:formsPartOf is used to relate two places. This is incorrect, because saws is an ontology for text, not for places. depending what is meant, and I do not recall having discussed this before, sorry, could you use one of the gn: properties instead or dcterms:isPartOf?

the same as above is true for 
saws:isDifferentTo, saws:hasPart

_Originally posted by @PietroLiuzzo in https://github.com/BetaMasaheft/Documentation/issues/1307#issuecomment-578388297_

**Comment by thea-m** [comment]
Splitting #1307 into single issues in the hope that this will help us resolve this topic easier

**Comment by thea-m** [comment]
> @eu-genia in PRS11583Gozam and PRS11584Damot you used saws:isRelatedTo where I think the appropriate relation would have been syriaca:has-relation-to-place.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Places/pull/21
https://github.com/BetaMasaheft/Persons/pull/72
