### ISSUE TITLE
syriaca:has-relation-to-place to be corrected

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1342]
It looks like [we have also diffusedly abused syriaca:has-relation-to-place](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3Arelation%5Bstarts-with%28%40active%2C%27LOC%27%29%5D%5Bstarts-with%28%40passive%2C%27LOC%27%29%5D%5B%40name%3D%22syriaca%3Ahas-relation-to-place%22%5D), which is meant to be used for relations **persons/place , not place/place**, and this was indeed already in the guidelines and has been used correctly [elsewhere, e.g. for Fasilidas and Gorgora](https://betamasaheft.eu/persons/PRS4015Fasilada/analytic). We could use (and document + add to the GL) for those cases of unspecified relation between two places another property, e.g. simply dc:relation.

_Originally posted by @PietroLiuzzo in https://github.com/BetaMasaheft/Documentation/issues/1307#issuecomment-578390706_

**Comment by eu-genia** [comment]
i have started on this one too but dc:relation does not seem to be a valid value

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Places/pull/21
