### ISSUE TITLE
saws:isMemberOf in person records to be corrected

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1346]
saws:isMemberOf is used to relate persons to one another, I guess members of groups real or ideal.
We need to find an alternative, because saws: is only to relate texts, then I can replace all instances.
see for example
````xml
<relation name="saws:isMemberOf">
    <count>26</count>
    <relation xmlns="http://www.tei-c.org/ns/1.0" name="saws:isMemberOf" active="PRS7720Pantalew" passive="PRS12196NineSaints"/>
    <relation xmlns="http://www.tei-c.org/ns/1.0" name="saws:isMemberOf" active="PRS1653Alef" passive="PRS12196NineSaints"/>
....
</relation>    

````

_Originally posted by @PietroLiuzzo in https://github.com/BetaMasaheft/Documentation/issues/1307#issuecomment-578403561_

**Comment by PietroLiuzzo** [comment]
foaf:member would be fine here http://xmlns.com/foaf/spec/#term_member, I have already added it to prefixDef and we use it already in our RDF

**Comment by thea-m** [comment]
Thank you! Could you add this to the schema and then replace this in all the concerned records? (Can I add relations to the schema like I would normally edit it, or is there anything else that needs to be done in regard to this?) 
This will also need to be corrected in the guidelines: https://betamasaheft.eu/Guidelines/?id=groups I'll do it, once the schema and records are updated

**Comment by PietroLiuzzo** [comment]
ok, I will proceed with all changes. I was mildly hoping in some involvement of the users of this property in this discussion, but fair enough!

**Comment by PietroLiuzzo** [comment]
ok, the other changed needed in the transformation are taken care of. yes, you can add these values in the schema as any other edit.

**Comment by PietroLiuzzo** [comment]
once the two pr on the data and gl are merged, this issue can be closed.

**Comment by thea-m** [comment]
Thank you!
