### ISSUE TITLE
Adding locus statements with image links in additions

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1347]
The current rules for writing additions and extras require that a @locus statement that includes a @facs command come before the @desc (or at least that is what it seems to be). This makes sense in ordering things in a sensible way in the statements. The flexibility of the system, however, also invites the writing of further links within @desc statements, pointing to connections between items. The following command, for instance, was what I would have like to write in e1 of EMIP 2086:

`<desc>Writing exercise, attempt to copy first folio of <locus target="#62r" facs="063"/>‎</desc>`

There may be a workaround to this of which I am not aware, but if not, perhaps it could be taken up as a suggestion?

**Comment by PietroLiuzzo** [comment]
Yes, I will to make this change in the new application.

**Comment by Ralph-Lee-UK** [comment]
Perfect

**Comment by PietroLiuzzo** [comment]
not yet done :)

**Comment by PietroLiuzzo** [comment]
where do you get this constraint? from the guidelines?

**Comment by PietroLiuzzo** [comment]
Actually, I am not sure if I do need to do anything, as I am not finding in schema or guidelines this constraint. sorry!
I think I would go for something like
`<desc>Writing exercise attempt to copy <locus target="#62r" facs="063"/>‎ of <ref target="#ms_i4" type="item"/>.</desc>`
which seems to validate and work fine in the app. it may be still contradicting some advise in the guidelines which I could not find. please let me know.

**Comment by Ralph-Lee-UK** [comment]
This now looks fine, Pietro. Previously I could only get it to validate with the locus statement set before the desc statement. I have edited EMIP 2086 in this way, so I'll check all is ok when the pull request has been made, and approved. Many thanks

**Comment by Ralph-Lee-UK** [comment]
Pietro, on making this one change to EMIP 2086, https://betamasaheft.eu/manuscripts/EMIP02086/main#p1, the page now crashes. Can you check for me what the cause of the crash is?

**Comment by PietroLiuzzo** [comment]
please check the other issue  #1332, linked also above, it crashes because the changes in the collation were not reproduced, the line in question here is not the cause of this.
