### ISSUE TITLE
Citing images

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1349]
**Is your feature request related to a problem? Please describe.**
We can let the user cite each version of a XML record, but if an author wants to cite an image related to a manuscript he/she will have to cite the catalogue and point to the image as an item associated to it, which is not correct.

**Describe the solution you'd like**
in the viewer, provide a citation box for image with a suggested citation for the image, which should go to the single image, not to the folio and use the canvas URI from the iiif manifest representation

> To provide a reference to an image use the following
Image {{Image number or images range}} of {{manuscript title}} photographed by {{author(s) of the photo set}} for {{Institution or project holding the photos}}, stored and served by Die Schriftkultur des christlichen Äthiopiens und Eritreas: Eine multimediale Forschungsumgebung / Beta maṣāḥǝft hosted at Universität Hamburg. Image link {{dereferencable, optionally SHAed, canvas id to default render}}, {{permanent manifest URI}} {{availability statement}} accessed {{date accessed}}

so for a concrete example with some complexity to provide a reference to image 8 of the set for BMLacq306 I would provide something like

> Image BML_009-008.tif of Florence, Biblioteca Medicea Laurenziana, BML Acq. e doni 306, photographed by Antonella Brita, Karsten Helmholz and Susanne Hummel for Biblioteca Medicea Laurenziana, https://betamasaheft.eu/api/iiif/BMLacq306/canvas/p8, IIIIF manifest URI: https://betamasaheft.eu/api/iiif/BMLacq306/manifest, published in conjunction with this descriptive data about the manuscript with the permission of the Biblioteca Medicea Laurenziana, prot. 190/28.13.10.01/2.23 of the 24 January 2019 and are available for research purposes. Stored and served by Die Schriftkultur des christlichen Äthiopiens und Eritreas: Eine multimediale Forschungsumgebung / Beta maṣāḥǝft hosted at Universität Hamburg.  [Accessed: 2020-03-07+01:00]

if a range, this would start as

> Images BML_009-008.tif, BML_009-009.tif, BML_009-010.tif of....

alternatively or additionally in other contexts it could be a more content oriented citation format, and say

> Range of Images containing Florence, Biblioteca Medicea Laurenziana, BML Acq. e doni 306, Quire 2, ff. 8-15, photographed by ...

or more generically

> Range of Images containing Florence, Biblioteca Medicea Laurenziana, BML Acq. e doni 306, ff. 8-15, photographed by ....

@thea-m @DenisNosnitsin1970 @eu-genia @DariaElagina I would love to have your thoughts on this

**Comment by eu-genia** [comment]
This is very good but ideally the full citation should (also) include the date of the photographing, not (only) of record creation. There should be a place to provide this info. E-S mss have it among the changes, with the date. I believe this is essential, as manuscripts mutate, and are often photographed several times, even by the same people.

**Comment by thea-m** [comment]
I think that the last, more generic beginning, is very clear and quick and easy to read. 
I have trouble fully understanding the complete sentence (what is the subject of "are available for research purposes"?), but this is probably due to my linguistic, legal and generic ignorance.
Regarding the date of the photographing, I agree, but wonder whether this needs necessarily to be included in the XML description of the manuscript in a change element as has been done for the Ethiospare manuscripts. I would view the act of photographing and describing the manuscript as two different activities, and the photographing is not a change affecting the XML record...

**Comment by eu-genia** [comment]
I agree the Quire does not have to be mentioned.

I did not mean the date has to be a change element, simply gave an example where it is hidden in E-S case for the moment. I agree it might be better to find another place (then the E-S descriptions have to be additionally updated)

Should we now do the nitpicking in English or are we talking in general terms for the moment? If nitpicking then of course no "the" before "24 January", "and available" (without are)

**Comment by PietroLiuzzo** [comment]
any comment is welcome, I am not about to implement it immediately, please reformulate the entire phrasing as you would like it. thanks!

**Comment by thea-m** [comment]
Thank you! @PietroLiuzzo where would be a good place to add the date of photographing? Does it have to be in the manuscript records?
I am afraid I am certainly not able to formulate English sentences of legal consequence.

**Comment by PietroLiuzzo** [comment]
I am not sure and cannot check right now. perhaps @eu-genia can have a go looking into the TEI Guidelines to start with.

**Comment by eu-genia** [comment]
I guess the place to use would be the `<surrogates>` element
as in
```
<surrogates>
 <bibl>
  <title type="gmd">digital image / microfilm /etc.</title>
  <idno>*****.</idno>
  <date when="1984">May 1984</date>
 </bibl>
 </surrogates>
```
we would need the type gmd (general material designation)
this could eventually also be used to resolve the problem of multiple IDs for mss/microfilms/photosets

**Comment by PietroLiuzzo** [comment]
can you provide a link to the page of the TEI guidelines ? thanks

**Comment by eu-genia** [comment]
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-surrogates.html

**Comment by PietroLiuzzo** [comment]
if no objects arise to this, I am fine with using it without further specification on our side. However, we may give some consideration to whether it is for us relevant to add these `bibl`, title, etc. or a `p` may be fine for our needs. we will then have to document in the GL, and make for this purpose at least 1 example.

**Comment by PietroLiuzzo** [comment]
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msadsu

**Comment by eu-genia** [comment]
I think that title of gmd type is helpful to distinguish digital images / microfilms / other surrogates (like Combonian photographs); there may be several types of surrogates of different date for the same manuscript

**Comment by PietroLiuzzo** [comment]
#1472 the source TEI export also has surrogate, so all good. I will dismiss the citation format proposal and instead
- [ ] add support for visualization of surrogates
- [ ] document surrogates in the Guidelines
using examples from the transkribus transformation
