### ISSUE TITLE
we have also examples of dcterms:creator and saws:hasWritten used to connect a person and manuscript.

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1350]
we have also examples of dcterms:creator and saws:hasWritten used to connect a person and manuscript. Could we go for the second and leave dcterms:creator for authorship of textual units?

_Originally posted by @PietroLiuzzo in https://github.com/BetaMasaheft/Documentation/issues/1307#issuecomment-578401548_

**Comment by PietroLiuzzo** [comment]
I will remove these instances so that dcterms:creator is limited as it should for authorship of textual units. the following are the affected records

dcterms:creator  | person | manuscript
-- | -- | --
1 | bm:PRS9744Victor | bm:IVkoriander4
2 | bm:PRS12730Absallus | bm:IVorlov40
3 | bm:PRS12734BaedaMaryam | bm:IVkoriander5


saws:hasWritten |x | y
-- |-- | --
1 | bm:PRS11810HaylaMa | bm:BAVet110
2 | bm:PRS12079TaklaMa | bm:MNC013
3 | bm:PRS11482Yohannes | bm:RNBefns5

**Comment by PietroLiuzzo** [comment]
now we have substituted dcterms:creator with saws:hasWritten in all instances of this type (6 total) and we have 6 statements which in same case are accompanied by a persName[@role='scribe'] in the manuscript record. 
with saws:hasWritten an authorship of some content is also implied (which may be what led to the use of dcterms:creator for some?), in the ontology it is used for "Marginalia".
would some of these actually be saws:isCopierOf ? 
@DenisNosnitsin1970 @DariaElagina @thea-m

**Comment by thea-m** [comment]
PRS9744Victor is the protagonist of texts attested in IVkoriander4. Both dcterms:creator and saws:hasWritten seem not appropriate here, note also the relation dcterms:creator used to connect the same person record with LIT4845Martyr, which also seems not ideal to me. I would use lawd:hasAttestations for the PRS-MS relation and ecrm:P129i_is_subject_of or ecrm:P129_is_about for the PRS-LIT relation. Can you confirm this, @DenisNosnitsin1970 ?

From what I can tell from the records, in all other cases mentioned, saws:isCopierOf would be the best relation between the PRS-MS relation (though in RNBefns5, `role="scribe"` has a `cert="low"`, but this was not reflected in the previously used relation either)

**Comment by PietroLiuzzo** [comment]
This only needs a small feedback from @DenisNosnitsin1970, or am I wrong?

**Comment by DenisNosnitsin1970** [comment]
I confirm.

**Comment by PietroLiuzzo** [comment]
thanks!
