### ISSUE TITLE
"A Work part of Ethiopian Literature"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1354]
All work records have "A Work part of Ethiopian Literature" in  `<sourceDesc>` - I think this should be "Ethiopian and Eritrean", to be consistent? 
@DenisNosnitsin1970 @eu-genia @DariaElagina

**Comment by thea-m** [comment]
(and maybe work not with a capital?)

**Comment by DenisNosnitsin1970** [comment]
Rather "Ethiopic literature", not "Ethiopian and Eritrean" (now generalizing, considering "Amharic" an extension of "Ethiopic"). All in all, the string "A Work part of ... Literature" appears to me not very lucky definition. At least one of two "A part of ... literature" or "A work of .... literature".

**Comment by thea-m** [comment]
From discussion with @DenisNosnitsin1970 , we are both wondering about the need for the presence of this statement in the files. Similarily "Prosopography of Ethiopian Written tradition" (also linguistically problematic?) in person records. Are these statements needed, @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
imagine a user of the TEI file in 10 years. they land on one of these files somewhere and have no clue what it is, this statement should briefly say what this is. It is not needed, but useful. we can change the wording, we can avoid displaying it if unwanted, etc. let me know.

**Comment by thea-m** [comment]
@abausi , since you seem to have a GitHub morning - any suggestions to the improvement of the phrases "A Work part of Ethiopian Literature" and "Prosopography of Ethiopian Written tradition" present as a general (and as I was convinced by Pietro's last comment, useful) statement in all work/persons records?

**Comment by abausi** [comment]
I would be for "A Work part of the Ethiopian and Eritrean written literature", since we definitely also include Amharic, but also Tǝgrǝññā and other languages, if attested in manuscripts, and do not let's forget all that has been inherited from IslHornAfr. For the prosopography, this is even easier, and I would be for the "Prosopography of Ethiopian and Eritrean written tradition".

**Comment by thea-m** [comment]
Thank you! I still suffer from article confusion - "A Work part of the Ethiopian and Eritrean written literature" and "Prosopography of Ethiopian and Eritrean written tradition" - "the" in front of "Ethiopian" or not? I have lost all Sprachgefühl in these cases.

**Comment by abausi** [comment]
Probably, better without "the", in both.

**Comment by DenisNosnitsin1970** [comment]
If we speak about Geez, Amharic, Tigrigna, it will be "literatures", won't it? And what is about Somali? I am not really convinced by the string "A Work part of". What is meant?  A work which is a part of ... literature?

**Comment by abausi** [comment]
We should consult a native speaker; I think that "literature" can have a broad meaning, and we should not even exclude Somali literature, as long as this appears, in written form, in manuscripts: manuscripts remain our minimal requirement. There are different solutions to the problem: Ricci titled his 1969 contribution "Letterature (plural) dell'Etiopia", but we might also use it in a comprehensive sense, e.g. one can talk of "Romance literatures" but also of "Romance literature".

**Comment by abausi** [comment]
I have some doubts on the whole string, "Work part of", that makes sense only if it belongs to a series, in opposition and relation to other items.

**Comment by DenisNosnitsin1970** [comment]
I would somehow start thinking from the end, "... the literature of Ethiopia and Eritrea". I think that it is what we want to say: literature circulating in both regions/both countries, but not necessarily belonging exclusively to one of them.

**Comment by abausi** [comment]
Yes, but then we should in any case limit the filed and introduce "written", or we shall encompass everything, and in particular ORAL literatures, for which really we cannot claim any special competence. This is out of the scope of BM.

**Comment by DenisNosnitsin1970** [comment]
Of course; do you think that the content may be understood to such a degree that someone would think in this direction?

**Comment by abausi** [comment]
I am sure that if we do not delimit it, someone would certainly assume that we also include oral literature, that is in fact a very important component of the literatures of Ethiopian and Eritrea; unless we assume (I am thinking) that this does not automatically imply to consider also the oral literatures. In itself, waht is defined belogns to the the literatures of Ethiopia and Eritrea. But why do we need "Work part of"? why not simply "A work of"?

**Comment by DenisNosnitsin1970** [comment]
I do not know why it is "Work part of". I would say just "Work of".

**Comment by abausi** [comment]
Just to sum up: we stay with "Work of the literatures of Ethiopia and Eritrea". This is quite neutral and minimal, but correct, also politically correct. The article is required here, I think.

**Comment by thea-m** [comment]
Jacopo has confirmed the article for both cases. @PietroLiuzzo, could you (I presume with the next release?) change these sentences in work and person records to "Work of the literatures of Ethiopia and Eritrea" and "Prosopography of the Ethiopian and Eritrean written tradition", respectively? Thank you!

**Comment by PietroLiuzzo** [comment]
sorry, this had not been assigned to a milestone and I missed it last week... will do it next time!
