### ISSUE TITLE
labiovelars to be corrected

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1355]
Despite many past actions of this kind, there are still/again many records, presumably in all entities, in which the correct ʷ is not used. It would be good if someone would search for this and correct it in the concerned records. It would also be good if we would remember to use it.
Any volunteers? @DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
you mean, they are not in superscript? I could volonteer, I would like to do such a task for some time.

**Comment by thea-m** [comment]
Good, then just do it, no need to wait :)
