### ISSUE TITLE
Two Seal of Solomon Authority Files

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1360]
As noted by @Gnisci , we have two Seal of Solomon authority files: The art keyword SealofSolomon and the Art Theme AT1140SealSol. Both have apparently never been used, which is surprising, since much discussion preceded their creation: https://github.com/BetaMasaheft/Documentation/issues/794. Since my last contribution to this discussion was the creation of AT1140SealSol, I would be in favour of keeping (and using!) this and deleting the art keyword. 
@eu-genia @Gnisci @DariaElagina

**Comment by Gnisci** [comment]
I think keeping it as AT makes more sense.

**Comment by PietroLiuzzo** [comment]
I have not followed the discussion or do not remember it, but you can also state an equivalence if the two are really the same concept, and thus avoid deleting or updating as necessary.

**Comment by thea-m** [comment]
Ah, thank you for the reminder @PietroLiuzzo ! In this case, I think that would not be the best solution, but good to keep in mind
