### ISSUE TITLE
error for external link

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1364]
I wanted to add an external link in a `<note>` in a record, for which, I believe I followed the guidelines writing `<ref target="http://www.bl.uk/manuscripts/FullDisplay.aspx?index=3&ref=Add_MS_19342"/>`. This is marked as invalid, the error message is "The reference to entity "ref" must end with the ';' delimiter.", which I don't undestand...

**Comment by PietroLiuzzo** [comment]
@eu-genia is also having issues with the validation. there might be something in the latest changes that did not go well. if you click on the error it will open the file at the line of the error, could you be so kind to copy that line here?

**Comment by PietroLiuzzo** [comment]
please also not that you have an unescaped "&" in the url

**Comment by thea-m** [comment]
Ah, thank you! It was only the &. I had no other validation issues whatsoever.
