### ISSUE TITLE
Narrative units not displayed on the app anymore

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1365]
For all narrative units, there is the error message:

> Something has gone wrong and there are more than one item with id NAR0001gwelt.
> 
> /db/apps/BetMasData/authority-files/Narratives/NAR0001gwelt.xml
> /db/apps/BetMasData/Narratives/NAR0001gwelt.xml

**Comment by PietroLiuzzo** [comment]
well that is funny, but at least the error is usefully telling us where the issue lies to solve it quickly. Thanks for reporting! I have now removed the erroneously double narrative folder into authority files in the db!
