### ISSUE TITLE
list view with dates fails by looking for ranges of years

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1366]
@SophiaD-M wanted to filter the BNF manuscripts to find those dated to the 15th century, which we thought would be easiest with the date filter in the repository view:
https://betamasaheft.eu/manuscripts/INS0303BNF/list?mainname=&date-range=1390%2C1500&cp=&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C1000&qn=1%2C100&qcn=1%2C40&wL=1%2C100&restorations=
However, this results in a 504 Gateway Time-out.

**Comment by PietroLiuzzo** [comment]
Thanks for reporting, I have isolated the query needing optimization and will look into it asap

**Comment by PietroLiuzzo** [comment]
I have limited the date search to origDate and improved the index lookup for the query, it should be working now, although not yet optimal
