### ISSUE TITLE
text not limited by restrictions of movement

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1367]
I noticed here https://betamasaheft.eu/manuscripts/INS0478DS/list that some text parts are not staying within their intended limits:
![image](https://user-images.githubusercontent.com/19650382/77302919-5e684a80-6cf2-11ea-8aff-598cd56f6492.png)
![image](https://user-images.githubusercontent.com/19650382/77302952-69bb7600-6cf2-11ea-827e-a150abee2205.png)

**Comment by thea-m** [comment]
And the word to the right of TEI cannot be read:
![image](https://user-images.githubusercontent.com/19650382/77303155-bc952d80-6cf2-11ea-82c5-a7ceb4273406.png)

**Comment by PietroLiuzzo** [comment]
Thanks for point this out. It would be useful  additionally to know what device you are using. This are however for the list view expected behaviours with the current style, which is designed for desktop primarily, not for tablets or smartphones, where it can be used suboptimally.

**Comment by thea-m** [comment]
Thank you! It is a hp laptop (Pavilion - do you need more details?)

**Comment by PietroLiuzzo** [comment]
do you magnify your view?

**Comment by thea-m** [comment]
No

**Comment by thea-m** [comment]
The same is true for some search results, for example https://betamasaheft.eu/as.html?query=%E1%88%98%E1%8B%9D%E1%8C%88%E1%89%A0&homophones=true&AttestedInType=1&xmlid=
![image](https://user-images.githubusercontent.com/19650382/77645710-78f52a80-6f63-11ea-9874-1d93c03e4e5c.png)

**Comment by PietroLiuzzo** [comment]
thanks for posting. this is really dependent on each specific device, I cannot reproduce most of this on my computer. This is one of those aspects of interface design which would require a specialist. I have not the competences to make the style fully responsive to every size and screen. I will not take any action, but will keep the issue in case we will have support for such aspects in the future. thanks!

**Comment by thea-m** [comment]
perfect, thank you!
