### ISSUE TITLE
Key word for student scrolls?

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1369]
Dear all,
as some of you know I have in Platonov's catalogue three scrolls containing excerpts from the First Epistle of John, and one scroll containing syllabary which, according to the cataloguer, were used for learning reading or writing. Here is the link to the discussion of one of such scrolls: https://github.com/BetaMasaheft/Manuscripts/pull/264
The use of such scrolls in the education process has been confirmed by my brief consultation of some contributions as well as by Mersha. Would it probably be a good solution to think of a new key word for such "student scrolls", for we already had a discussion on where to put this information in the description?

**Comment by DenisNosnitsin1970** [comment]
It would be useful to know how Ethiopian themselves call it. Is it also "ketab" or not?

**Comment by DariaElagina** [comment]
I will check

**Comment by Mersha-Alehegne** [comment]
Hi Daria: I can repeat what I said. During former days, a father used to give his son a _fidal gabatā_ scribed on a folio of parchment when he sends his son to school. This was the case until Tasfā Gabra Śǝllāse started to print the _fidal_ in the 1920s. To Denis' question, Kǝtab in the Christian tradition is related to those "magical" pieces. The one used by pupils in the reading schools is called _fidal gabatā_.

**Comment by thea-m** [comment]
A keyword might be a good idea (why not DidacticUse or something equally broad, so as not to get into terminological problems - and there might be other mansucripts at some point where a similar purpose can be detected?), and I also think that it might make sense to create a new LIT ID for the beginning of the beginning of the first Epistle of John, in possible combination with a syllabary, since these are used here in a very clear context and sequence (and are not, in fact, "incomplete"). 

In any case, any place for this information out of `<summary>` would be good in my opinion, as I said already in the PR :)

(De-assigning myself due to the one person per issue rule )

**Comment by DariaElagina** [comment]
Maybe, DidacticMaterial? I agree that a creation of a LIT ID would make sence.

**Comment by DenisNosnitsin1970** [comment]
Ok; Ya-fidal gabata as the name of the text, but actually ist't "abugida"/"hahu", i.e. a syllobary? You can think if you want to unite or sort out, in one way or another, syllobaries that sometimes appear as marginal notes.

**Comment by DariaElagina** [comment]
I thinl Dorothea and me were speaking about the Epistle of John, not of abugida

**Comment by DenisNosnitsin1970** [comment]
ok

**Comment by thea-m** [comment]
DidacticMaterial sounds good!
I do not know these scrolls at all, so I am merely suggesting things out of thin air - they are usually composed of the beginning of the first Epistle of John, including, occasionally, the syllabary? There might be also scrolls containing only the syllabary? 
Depending on their occurrence together, single IDs for both texts and a common ID for both together might be useful.

**Comment by thea-m** [comment]
@DariaElagina I see that you are in the process of creating LIT5905FidalaHawarya. I was planning to create IDs for the Hahu and Abugida syllabaries, or did you also already create those? Thank you!

**Comment by DariaElagina** [comment]
@thea-m  no, I did not, I have used LIT4001Syllab so far. In the catalogue description I have no mention on the arrangement of the syllabary

**Comment by thea-m** [comment]
Thank you! No, just one (hahu, as Denis pointed out ;) ) syllabary in a recent manuscript of various liturgical and didactic material.

**Comment by DariaElagina** [comment]
The key word is introduced.
