### ISSUE TITLE
XML view on the app

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1370]
**Describe the bug**
Error when trying to view TEI/XML on the app

**To Reproduce**
Open whichever page (eg LIT2145OntheT) click TEI/XML you are brought to
https://betamasaheft.eu/tei/LIT2145OntheT.xml

**Expected behavior**
I would expect to see the processed TEI/XML file but I get the message

This page contains the following errors:
error on line 4 at column 89: xml namespace URI mapped to wrong prefix
Below is a rendering of the page up to the first error.

**Comment by PietroLiuzzo** [comment]
The post processing XSLT has some issue. 
You can see YOUR XML by adding .xml at the end of the file without /tei/

**Comment by PietroLiuzzo** [comment]
the transformation is actually fine, as tested independently from controller.xql
