### ISSUE TITLE
count() function for position of msItem leading to timeout 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1371]
I wanted to access https://betamasaheft.eu/works/LIT4033Senkessar/main, but always get 504 Gateway Time-out

**Comment by PietroLiuzzo** [comment]
thanks, I have isolated one of the causes and removed it for the time being, but this is not closing this issue, as I am thus removing a feature, which I hope to be able to retrieve with the faceted indexes

**Comment by thea-m** [comment]
Thank you!
