### ISSUE TITLE
Unidentified hymns and the Saʿātāt

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1372]
As suggested by @DenisNosnitsin1970 it might be worthwile to check whether unidentified hymns for which we have text available might be related to the Saʿātāt. If so, adding this reference to the concerned records, would of course greatly add to our project.
Maybe someone feels called to this at some point...
The text can be searched here, https://www.ethiopianorthodox.org/amharic/yezemametsheft/yaredawi%20metsaheft/seatat%20for%20church%20service_august2016.pdf, and we have a searchable copy of bm:Tasfa1955Saatat

**Comment by thea-m** [comment]
Check:
LIT4632Hymn
LIT4313Prayer
LIT4306Salam
LIT4272Salam

**Comment by DenisNosnitsin1970** [comment]
LIT4632Hymn seems to be Kidan za-nagh

**Comment by DenisNosnitsin1970** [comment]
Or the beginning of the Kidan, the beginnig (but the end, in BAVet91, i cannot find)

**Comment by thea-m** [comment]
No, not yet, sorry
