### ISSUE TITLE
find by CAe number in work view?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1373]
I think it's one of our aims that the CAe references become more broadly used, also by those not working in BM. I imagine that people would then like to have a place on the website where they can type the CAe number and find the record in question. (I know - it can be done with the search, looking up by ID and choosing "works" - but I don't think that this is obvious to outsiders and it also would still get the IHA results together with "our" records).
I was wondering whether this would be possible in the work view, somewhat in analogy to the "other Clavis ID" filter, i.e. to have a "search by CAe number" field, where typing the number, e.g. 2000, would then get the result LIT2000Mazmur (and not LIT2000IHA). (I guess that this would not be technically a filter as the other functions on this page and don't know if it is possible at all)
What do you think?

**Comment by PietroLiuzzo** [comment]
Yes, I definitely agree and will add it in the new faceted search

**Comment by thea-m** [comment]
Thank you!

**Comment by PietroLiuzzo** [comment]
this will also be in the faceted search as said above (so, this issue should stay open) but I have added a temporary feature (the look will probably remain the same also when facets are in) o search by CAe, just above the Other Clavis ID. this takes just a number and matches is as string in the ID of a record.

**Comment by thea-m** [comment]
Thank, that will be very helpful! @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
After investigating and implementing locally the faceted search functionality, it looks like this is better of where it is now.
