### ISSUE TITLE
Use of 'type' designation for additions

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1375]
This issue is about the use of the 'type' designation of additions. 

For a 'Calendar of the Apostles and Evangelists' would 'CalendaricNote' be appropriate as a 'type'?

**Comment by DenisNosnitsin1970** [comment]
Yes, it will. Please do. Just describe in a note what it is, with a couple of words (I assume that this is not "calendar", but a "list of feasts of the apostles and evangelists", quite typical type of the calendaric note).
