### ISSUE TITLE
verso of scrolls

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1378]
From https://github.com/BetaMasaheft/guidelines/issues/87

@DariaElagina has written:

> Do we want to use 1r/ 1v to distinguishe between the face side and the reverse side? I have some more scrolls wich have texts/additions on their reverse side. I was not using this terminology just because it was too much stuck to codices in my head.

I would say yes, to me it seems intuitive. But I checked some catalogues now and couldn't find anywhere a reference to the reverse side of scrolls (though I have already seen scrolls where the reverse merits to be mentioned...strange). What do you say @DenisNosnitsin1970 ?

(I'm not sure who to assign)

**Comment by abausi** [comment]
Scrolls/rolls which are written on the verso, particularly, in papyrology, are called "opistograph scrolls", and "anopistograph" those which are not written on the verso side. Could one use this terminology and define accordingly "opistograph" or "anopistograph" scrolls? this corresponds to general codicological terminology. Do we need "1" or "r" and "v" are enough?

**Comment by thea-m** [comment]
Thank you! Learned something new :) I think that once the referencing issue is solved (probably to be dealt with together with the entire scroll complex  https://github.com/BetaMasaheft/Documentation/issues/1162), a way can be found to introduce this terminology and the possibility to filter according to it.
My impression of the Ethiopic tradition is that the v will be needed mostly in the cases of secondary notes on the verso, since most scrolls are anopistograph. A scroll with a main text on the r and later notes on the v would probably not be described es opistograph?

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1162

**Comment by PietroLiuzzo** [comment]
This can be now achieved in a number of ways, naming divs, giving number, with pb and combinations of these, according to each case. while opistograph/anopistograph describe the entire object and can be used to describe the object, for referencing of the text we would use recto and verso or named sides I guess, especially thinking of fragmentary scrolls or objects with more than one face, like inscriptions.
 I will specify this in the GL, suggesting without mandating the use in a `div[@type='textpart']` of `@subtype` with value 'recto' or 'verso'.
