### ISSUE TITLE
Encoding of scroll strips

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1379]
From https://github.com/BetaMasaheft/guidelines/issues/87
@DariaElagina has written:

> The scrolls are sewn mostly of several parchment strips, do we want to number them 1,2,3 accordingly?

I think it makes sense. It would also be good to encode their size consistently (to have the possibility of encoding their size consistently, you know what I mean....) and to be able to refer to each strip within the description. 

I have done this in the following way, without prior discussion if I remember correctly:

```xml
     <dimensions type="outer" unit="mm">
                              <height>1590</height>
                           </dimensions>
 <dimensions type="outer" unit="mm" xml:id="strip1">
                              <height>486</height>
                              <width>100</width>
                           </dimensions>
                           <dimensions type="outer" unit="mm" xml:id="strip2">
                              <height>588</height>
                              <width>120</width>
                           </dimensions>
                           <dimensions type="outer" unit="mm" xml:id="strip3">
                              <height>540</height>
                              <width>97</width>
                           </dimensions>
```
I think now that it would maybe be better to create a value "strip" for @type in measurements. 

@PietroLiuzzo What do you think? Once we have decided on a way of encoding, this could probably be relatively easily rendered on the app with "strip dimension" or something similar? 

@DariaElagina is this what you meant originally?

**Comment by PietroLiuzzo** [comment]
I think this is already fine, and the way you have encoded it [here](https://betamasaheft.eu/manuscripts/TF002/main ) works well. I also agree that referencing to the `@xml:id` e.g. `<layout columns="2" writtenLines="68" corresp="#strip1">` as in the same example is ok.

**Comment by thea-m** [comment]
Thank you! I think it would be useful to create a new guidelines page on the encoding of scrolls (where this would be included), once the related issues are solved.

**Comment by DariaElagina** [comment]
I have created a PR for the GL
