### ISSUE TITLE
Invisible doublet LIT5778MirTaklaHaymanotSabal

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1382]
So there is an issue! Ok, let's try and make clear what the problem is

which records or views are affected?
https://betamasaheft.eu/works/LIT5778MirTaklaHaymanotSabal

what have you tried ?
according to the app, there are two records with the ID, obviously copied to different folders
***
Something has gone wrong and there are more than one item with id LIT5778MirTaklaHaymanotSabal.

/db/apps/BetMasData/works/5001-6000/LIT5778MirTaklaHaymanotSabal.xml
/db/apps/BetMasData/works/4001-5000/LIT5778MirTaklaHaymanotSabal.xml

***
I don't see anything in the 4001-5000 folder. Before I create a new doublet and delete it to trick the system maybe there is a faster way for you to resolve?

**Comment by PietroLiuzzo** [comment]
Thanks for documenting this issue, it should be ok now.
This was already the correct thing to do and requires no further action in any case. Please, it does no good to try and "trick the system", really, it wastes yours and my time in equal measure.
