### ISSUE TITLE
translations of legend

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1383]
I would like to provide the translation of legends in the decoration description of manuscripts, which is not yet specified in the guidelines. In analogy to the translation of additions, I would propose simply to add under the `<q>` element giving the legend another `<q>` with the translation:
```xml
<decoNote type="drawing" xml:id="d20">
<locus target="#118v"/>
<desc>Monochrome drawing depicting <persName ref="PRS6819Mary"/>, to the left, 
and <persName ref="PRS3827Ephrem"/>, to the right. 
<persName ref="PRS6819Mary"/> performs a  <term key="gestureblessing">gesture of blessing</term> with her right hand.</desc>
<q xml:lang="gez">ዘከመ፡ ባረከቶ፡ እግዝእትነ፡ ለ<persName ref="PRS3827Ephrem">ኤፍሬም፡</persName></q>
<q xml:lang="en">How our Lady blessed Ephrem.</q>

```

What do you think?
@PietroLiuzzo @Gnisci

**Comment by Gnisci** [comment]
Sounds like an excellent idea, but should the translation not get an id to clarify its relation to the previous <q> element?

**Comment by PietroLiuzzo** [comment]
I do not think that in analogy to other places we should give an id and corresp here, but we can if we decide to do so, perhaps reflecting the change to entire dataset and all places where this would be the situation.

**Comment by thea-m** [comment]
I understand the improved clarity and consistency such a change (xml:id with corresp) would give to our data, and would follow @PietroLiuzzo 's decision on whether it should be implemented. 
Which other places of encoding in our records would be affected, apart from the `<q>` elements in `<additions>` giving the text of additions? There is <foreign> used for translations of `<incipit>` and `<explicit>`. `<foreign>` is also used for the captions of miniatures, for which we did not yet have the need to include a translation. 
Nothing else comes to my mind now, but that doesn't mean much.

**Comment by PietroLiuzzo** [comment]
I think we can safely continue to work with xml:lang only, if anyone wants to additionally add xml:id and corresp, that is fine and can be done as well and does not harm.

**Comment by thea-m** [comment]
Thank you!
