### ISSUE TITLE
ተረፈ፡ ኤርምያስ፡Letter of Jeremiah

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1384]
there doesn't appear to be a 'works' record for this book. Can we create one?

**Comment by PietroLiuzzo** [comment]
@thea-m please, could you double check this and in case help @Ralph-Lee-UK with this ? thanks a lot

**Comment by thea-m** [comment]
Hi! The record for the letter of Jeremiah is here: https://betamasaheft.eu/works/LIT1686Epistl/main
I do not know this work well, but have never come accross the Geez title you gave: Might there be a confusion with the Paralipomena of Jeremiah, https://betamasaheft.eu/works/LIT2167Parali/main?

**Comment by Ralph-Lee-UK** [comment]
Many thanks, this is exactly what I wanted! The title that I gave is used in Ethiopia in contemporary printed bibles certainly, but I am not aware of when its use started.

**Comment by thea-m** [comment]
Thank you!
https://github.com/BetaMasaheft/Works/pull/90
