### ISSUE TITLE
translation of shelfmarks

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1385]
I would like to provide a translation for some Arabic shelfmarks in the DS records. It should be clear that the translation is mine, not part of the holding repository's official system. How could this best be done?
There is this in the record:
```xml
<altIdentifier>
 <idno> مسلسل 10884</idno>
</altIdentifier>
```
and I want to give the translation "Serial number 10884". In analogy to our encoding of work titles, I could give an xml:id to the idno and then add a second idno referring to it?

```xml
<idno xml:id="Shelfmark1" xml:lang="ar"> مسلسل 10884</idno>
<idno corresp="#Shelfmark1" xml:lang="en">Serial number 10884</idno>
```

(Now I notice that we never added xml:lang to non-English identifiers. Is this relevant or can we ignore it?)

**Comment by PietroLiuzzo** [comment]
I do not see any issue with this.

**Comment by thea-m** [comment]
Ah, oXygen sees an issue: only one idno per altIdentifier (I could have checked before). So, two altIdentifier elements?

```xml
    <altIdentifier>
                     <idno xml:lang="ar" xml:id="idno1">كتب مقدسة ١٩١٥</idno>
                  </altIdentifier>
                  <altIdentifier>
                     <idno xml:lang="en" corresp="#idno1">Sacred Books 1915</idno>
                  </altIdentifier>
```

**Comment by PietroLiuzzo** [comment]
yep

**Comment by thea-m** [comment]
thank you
