### ISSUE TITLE
Items not displaying or error messages

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1386]
Following recent edits, the following files are not displaying any information, just a blank page. The code validated ok, clearly, and I have looked for obvious errors but haven't found any. Can you advise?

https://betamasaheft.eu/manuscripts/EMIP00002/main
https://betamasaheft.eu/manuscripts/EMIP00005/main
https://betamasaheft.eu/manuscripts/EMIP00006/main
https://betamasaheft.eu/manuscripts/EMIP00007main
https://betamasaheft.eu/manuscripts/EMIP00013/main
https://betamasaheft.eu/manuscripts/EMIP00017/main
https://betamasaheft.eu/manuscripts/EMIP00021/main
https://betamasaheft.eu/manuscripts/EMIP00025/main
https://betamasaheft.eu/manuscripts/EMIP00026/main

**Comment by PietroLiuzzo** [comment]
This is already an improvement in comparison to the previous java error, at least you can click through to other views. I was not able to catch the error from the XSLT to print it. I am having a look at this and will make a branch with the corrections

**Comment by PietroLiuzzo** [comment]
sorry, this has likely affected many more record and was a silliness in a new piece of XSLT I added recently. thanks for spotting this!
