### ISSUE TITLE
Wikidata ID for works?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1387]
I was just wondering whether there would be a benefit for us to add wikidata IDs also to work records? In general, it seems to me it would contribute to increase the overall connectiveness. But there is probably a reason why we don't do this?

**Comment by thea-m** [comment]
Hmm, now I see that the BM ID is already there, at least for one work (https://www.wikidata.org/wiki/Q1123371)....very mysterious and amazing.

**Comment by PietroLiuzzo** [comment]
if you check the reference in wikidata it is no mystery any more... you can add wikidata IDs in the records, but for works it would be much easier to add the BM id in wikidata, simply using the proporty we asked to be set up.

**Comment by thea-m** [comment]
Ok, it was just the example used when you created the property?
Thank you
