### ISSUE TITLE
Incorrect Data Entered for EMIP 602

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1388]
The entry at:
https://betamasaheft.eu/manuscripts/EMIP00602/main#p1
Contains information about another manuscript! The edits were done by "MV", whom I guess is Massimo Villa, on 16/02/2018. 
We would like to enter the correct data, but first this information needs to go to its correct location. Can you advise?

**Comment by MassimoVilla** [comment]
Dear Ralph Lee, thank you. I will take care of this right now.

**Comment by MassimoVilla** [comment]
I've gone through the EMIP mss and I've identified two overlapping problems:
1. First, data do not refer to EMIP 602, as Ralph Lee rightly points out, but to EMIP-MM 620. I blatantly mistook the numerical part, for which I'm sorry.
2. The manuscript I've encoded is _not_ EMIP 620 (which has been properly described). It rather belongs to a further series of EMIP materials, namely EMIP-MM (Microfilmed Manuscript). It is a series of MSS microfilmed by the UNESCO microfilming project in 1969-70 (in the case at issue in the monastery of Dima Giyorgis) and recently digitized by the EMIP project. I currently see no folder for these materials in the master branch. @PietroLiuzzo am I entitled to create a new folder under EMIP for the EMIP-MM mss records?

**Comment by PietroLiuzzo** [comment]
I am not able to help in identifying which ms you described @MassimoVilla , all there is in BM is what you can see, but perhaps @Ralph-Lee-UK does know where are these microfilmed mss. 
Please do not change ids, simply remove the wrong content and add it in the correct file. Thanks!

**Comment by Ralph-Lee-UK** [comment]
Thanks Pietro, and will do this. I will check with Steve Delamarter to see if he can identify the correct file location.

**Comment by Ralph-Lee-UK** [comment]
Just discussed this with Steve Delamarter, and EMIP-MM 602 is in fact Unesco 1052, which was given the number EMIP 3081 when the microfilm was photographed for the EMIP project. I have copied the entries from EMIP 602 to EMIP 3081, and removed them from EMIP 602. I think this resolves this fully. The details are also in the change log for both entries

**Comment by PietroLiuzzo** [comment]
Thanks a lot!
