### ISSUE TITLE
encoding of Ethiopian/non-Ethiopian binding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1389]
There has been the desire to encode in schematic form whether the binding of manuscripts is of Ethiopian or non-Ethiopian origin. I think that it would make sense to indicate this in the records (there might be some semantic overlapping with the existing encoding of whether the binding is contemporary to the production of the manuscript, but not always - it can be contemporary and not Ethiopian). Do you have suggestions on where in the records to state this?
I could imagine a `@type` in `<binding>` with several values (maybe "Ethiopian", "European", "Other"?).
@MassimoVilla @ElianaDalSasso @PietroLiuzzo

**Comment by MassimoVilla** [comment]
I agree with @thea-m 's proposal to add values in `<binding>`.
One concern about terminology: we agree that Ethiopian here loosely includes also Eritrean, of course, as well as "European" basically means "Western" (let me use this term) or non-Ethiopian. 
Wouldn't it be better to have different terms (e.g., local), or even a true/false statemente like `local="true/false"`? Further details (e.g., binding of Italian provenance) might be provided in a sentence.

**Comment by thea-m** [comment]
The terminology is of course problematic. But local can also be relative, there are Geez manuscripts produced outside of Ethiopia and Eritrea...

**Comment by MassimoVilla** [comment]
True, and indeed one more reason to avoid Ethiopian/European as the only options. So better to avoid a true/false statement, which neglects many cases. 
Does "Western" instead of European look too 'culturally biased' according to you? 
I also ask @DenisNosnitsin1970  for a comment on this terminological issue.

**Comment by DenisNosnitsin1970** [comment]
I used to say "non-Ethiopian".  "Western" is better than "European" but it does not really fit as well, in my opinion, because we may have other bindings that look like European, but they are not, e.g., Ethiopic manuscripts produced in Egypt, or in Jerusalem, or rebound there or elsewhere outside Ethiopia/Europe according to the local techniques. "Western" is also very general, as there are traditions and many types inside Europe. The parchment textblock may assume binding of any origin. Is it a must that the type of the binding should be stated? I think what we can do for sure is to distinguish between "Ethiopian" and "non-Ethiopian" (or do indicate that the binding was disturbed/rearranged outside Ethiopia).

**Comment by ElianaDalSasso** [comment]
I agree with @thea-m as well, encoding in schematic form the origin of the binding is definitely useful and also the suggested location (@type in <binding>) seems to me appropriate. As regards the terminology, I think that the more straightforward solution is the one indicated by @DenisNosnitsin1970  "Ethiopian" and "non-Ethiopian". Defining the origin of a binding is not an easy task, a dedicated study is required for each item and free-text descriptions may lead to ambiguity.

**Comment by PietroLiuzzo** [comment]
I would suggest to add the "non-Ethiopian" only where this is sure and avoid declaring everywhere else "Ethiopian" or anything else, if the opposition is true/false it will be enough.

**Comment by ElianaDalSasso** [comment]
I think it works. If further information is available it could be added in a note, right?

**Comment by thea-m** [comment]
Thank you! So there is a consensus to add to `<binding>` a @type with the value nonEthiopian? I would be in favour of having the value Ethiopian as well, so that there would be the possibility of making no statement on this without it being interpreted as Ethiopian binding.

**Comment by PietroLiuzzo** [comment]
@thea-m I am not sure I follow the last comment. Are you saying that the majority of mss are neither Ethiopian or non Ethiopian? I thought we can safely say that we interpret silence as Ethiopian and specify in other cases, generically with non Ethiopian, more precisely if necessary. if we have to go through all and ad type='ethopian' isn't it the same as saying nothing?

**Comment by thea-m** [comment]
No, but maybe I did not understand your comment from 4 days ago correctly...
I said that I think it would be good to have the possibility to mark up the binding explicitly as Ethiopian or non-Ethiopian, while keeping the possibility not to make a statement on this (without the absence of a statement being interpreted as "Ethiopian binding" - though this will be of course the case, in the overwhelming case of the currently existing records which obviously do not have this statement,).

**Comment by DenisNosnitsin1970** [comment]
Pietro, it is about the binding. The textblock of an Ethiopian manuscript can lose its original binding and receive, in the course of history, a non-original binding. E.g., many manuscripts in the European libraries. They all were rebound and got non-Ethiopian bindings.

**Comment by DenisNosnitsin1970** [comment]
Yes, exactly. If i understood well, the consensus was to mark the binding "non-Ethiopian" - in case it is - without entering further details (that may be complicated).

**Comment by abausi** [comment]
I am in favour of an explicit "Ethiopian" statement.

**Comment by PietroLiuzzo** [comment]
Sorry, on a second though, I think [`@contemporary` is just for this](https://betamasaheft.eu/Guidelines/?id=bindingDescription) and although its connotation is only temporal apparently ([TEI binding element](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-binding.html) ) I would recommend not overcomplicating this and keep using only this attribute which is already used in more than 2000 records. We can eventually add more values to it, add more optional values, add a filter for this feature. for a binding which is contemporary but non-Ethiopian you may have `<binding contemporary="true non-Ethiopian"/>`. Alternatively, if this is too much of a stretch for you, I would suggest the simple use of a dedicated keyword in the first decoNote inside binding.

**Comment by thea-m** [comment]
Without revisiting the entire discussion the last proposal by @PietroLiuzzo seems fine to me. Can we add the non-Ethiopian value?

**Comment by DenisNosnitsin1970** [comment]
Yes, Ethiopian - non-Ethiopian would be fine option.

**Comment by ElianaDalSasso** [comment]
I agree.
