### ISSUE TITLE
seg without @type

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1390]
when writing `<seg rend="above">` (as specified in the guidelines for line take-ups, https://betamasaheft.eu/Guidelines/?id=text-encoding), I get the error report "element "seg" missing required attribute "type""

**Comment by PietroLiuzzo** [comment]
this change to the GL should do this, I have also added above and below as values of rend. please give it a try

**Comment by thea-m** [comment]
perfect, thank you!
