### ISSUE TITLE
Zotero polishing

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#1391]
Going more or less systematically through Zotero, EthioStudies (deleting all "journal abbreviations", starting to standardizing some journal titles, inserting several hundreds of "years" where missing etc. I have carried out already quite a few thousands of corrections) I have also gone through BM tags in the "EAe".

Aside from innumerable other corrections (from the name of the "EAe" itself, to the volume, year, etc. whereas the abbreviation, "Short title" is still missing also everywhere, but there must be, it is essential for the correct display of the entry in BM, and the editor should also be there), there are still corrections to be done, to correct the most apparent mismatch of tag and year.

I have grouped a few I noticed through cross searchs in a dedicated folder in "EthioStudies": "EAe problematic entries". For these entries, the wrong tag should be replaced with a right one: example: "bm:Burtea2005Susenyos" refers to the article "Susǝnyos", in "EAe" IV (2010): the tag, for clarity and consistency, should be replaced with "bm:Burtea2010Susenyos" (checking that this does not already exist!). I understand that the tag has a linking function and does not change much in the display: but these references risk to be misleading, due to frequent process of "copy paste", that has been obvioulsy and understandably applied to create new entries. In the end, they are a source of further potential errors.

Can anyone take care of this?

Many thanks!

**Comment by abausi** [comment]
Note in a few entries, the tag has systematically (wrongly) "Nosnistin"; the error was also in the entries, but these I have corrected.

**Comment by abausi** [comment]
I have corrected all EAe entries in EthioStudies, only the editors could not be inserted (yet) for all entries. For the future, please, take as example existing entries and follow them as consistently as possible. Only add the editor.

**Comment by abausi** [comment]
Concerning the Lincei publications: use the following conventions (please, to integrate in the Guidelines; I cannot get into the details why, and the situation is complicated, since different forms are used, in single parts of the volumes, for the yearly frontispiece, frontispiece of the fascicles etc.):

in the Field publication:

RENDICONTI:
up to 1921:
Atti della Reale Accademia dei Lincei, Rendiconti, Classe di scienze morali, storiche e filologiche
1922-1945:
Atti della Reale Accademia nazionale dei Lincei, Rendiconti, Classe di scienze morali, storiche e filologiche
1946-:
Atti della Accademia nazionale dei Lincei, Rendiconti, Classe di scienze morali, storiche e filologiche

MEMORIE:
the same, but write: "Memorie" instead of "Rendiconti":
Atti della Accademia nazionale dei Lincei, Memorie, Classe di scienze morali, storiche, filologiche
etc.

SERIES:
indicate in the field "Volume" (not "Series"!) the Series and the volume, separated by comma, in this fom (series "in extenso"):
Serie quinta, 2
etc.

Note that there are "Memorie" that are monographs; in this case, use the item type "book". In this case, provide the series ("Memorie" etc.) in the dedicated field, and in the field "Series number" indicate the number and if necessari the fascicle, e.g.:
Series: Atti della Accademia Nazionale dei Lincei, Memorie, Classe di scienze morali, storiche e filologiche
Serie Number: Serie nona, 25/1

**Comment by PietroLiuzzo** [comment]
please somebody taking this issue clean the list of assignees and self assign.

Please, avoid changing tags if this is not really necessary, and avoid doing so before being in control of the occurrences in the data, as discussed over skype. what really matters is that they are unique. If we want to change them, ok, but it should be done more or less at the same time of updating the data, to avoid long lasting inconsistencies building up on confusion.

**Comment by abausi** [comment]
I agree, Pietro; this is just what remains of a large polishing; I am still working; there are a few cases, where this should be done, it is not urgent, and I understand context and concern

**Comment by abausi** [comment]
We should probably also define WHEN a tag must be corrected: I think that wherever name (bibliographical author or editor) and year are wrong the tag (and the data!) should be corrected (and updated); otherwise we will have a completely arbitrary creation of tags; and it will be impossible to verify if a tag already exists, for the same entry I want to enter: this latter is not a fictitious example, this problem has already happened

**Comment by thea-m** [comment]
Should someone start correcting tags and carry out the necessary change and replace actions in the records, please keep in mind that there is a considerable amount of work carried out in branches other than the master branch, which would also need to be considered to avoid complete chaos. Thank you.

**Comment by eu-genia** [comment]
I have already stated on another occasion that I do not believe correcting tags is something sensible or necessary - arbitrary tags are not a problem at all, we have arbitrary IDs, many with "wrong" spelling inherited from EAe or other inconsistencies, tags are just IDs, and we are supposed to make sure they have not been used whenever we create new ones. 
Correcting data is another matter, but tags are not printed, they are just custom IDs, like the IDs we use for the XML files.
We should try to follow the guidelines when creating entries and tags but correcting existing ones, already used in data, would create more errors than solve (inexistent) problems.

**Comment by abausi** [comment]
I also said, this is not a major problem in itself: but it causes in the run, cascade problems, as long as data are more and more "dirty", due to teh process of copying dn doubling. It is not a urgent priority, but it is something that must be carefully monitored, much more than we did so far.

**Comment by abausi** [comment]
There are also very practical consequences: it is not pssible to check the existence or not of BM tags, if the name does not correspond to that of the bibliographical record: I gave the example of a few entries, collected in a special folder (after carrying out much more corrections of every kind: this is just what concerns the tags).

In details, to give one example: in the "EAe" entry Nosnitsin, Denis 2003. ‘Bur’, in Siegbert Uhlig, ed., Encyclopaedia Aethiopica, I (Wiesbaden: Harrassowitz Verlag, 2003), 639b–640a, the author was wrongly spelt: "Nosnistin" instead of "Nosnitsin"; accordingly, a tag was created (by someone who presumably copied the wrong name and did not realize it) in the form: bm:Nosnistin2003Bur (with wrong name in the tag). I went through Zotero and corrected "Nosnistin" to "Nosnitsin". If we now do not correct the tag in the data, if I check whether the expected tag: bm:Nosnitsin2003Bur exists or not, I will not find it. One can assume that one will also have a look in the data, but still, this is not exactly cosmetics, it is a bit more. I would then not talk of "inexistent" problems. These are problems, among other problems.

There are also INNUMERABLE cases when references to CSCO or other old publications were given, not to the year of the original edition, but to the year of a reprint. The guidelines are clear, but they were not followed. This, again, has the same kind of consequences.

Not a priority, but somethin that must be dealt with.

**Comment by eu-genia** [comment]
even if the tag is bm:Nosnustin2003 or whichever, it is correct, as long it is unique. before assigning a tag one should simply check that exactly this tag you want to assign is not taken.
a bm: reference to a reprint is also correct, reprint and original are two different things that can have two distinct tags. the citations should go to the original, so this should be eventually cleaned, but that the reprint has a tag with the year of the reprint is fully correct.

**Comment by abausi** [comment]
Dear Zhenia, you go around problems: wrong names are wrong names, and 
wrong thing only produce wrrong results. Double tags for the same item 
shold be avoided, unless there are special reasons.

As to reprints (particularly, anastatic reprints, that occurred many 
times in different years, like for CSCO volumes), we should simply avoid 
referring to them. They add "noise" and we are not librarians. Wew have 
the duty to provide the information for what it is relevant. As a user 
and a scholar, I need to know when a text was published first (many 
books are now reprinted on demand all over the world and nobody think of 
using these as references). This is a question of real substance.

Il 14.04.2020 15:23, Eugenia ha scritto:

**Comment by eu-genia** [comment]
The first point I don't understand - double tags are not acceptable. Tag must be one and unique. It is of course nice if it is also typo-free, but since the tag is just an alphanumeric sequence that could very well be arbitrary (it was our decision to make it "readable" but for the system it doesnt have to be) the typo correction is an extra wish that can be done when there are no real errors left.
The second point - maybe I was not clear. The edition quoted must be the original one, correct. So where in the data (work file, manuscript file) someone quoted a reprint it is there that the correction is needed. Not in the Zotero library where both, the original and the reprint, can well coexist, these are two distinct objects. It is not a problem if each has its own unique tag. This is not an error and does not harm.

**Comment by abausi** [comment]
For the points of double tags (they were alreday "de facto" created, wittingly or not: there are for sure bibliographical entries with double tags) they can make sense: for example, the edition Conti Rossini 1904 of Gadla Yared and Gadla Pantalewon, could be double tagged bm:ContiRossini1904:Yared and bm:ContiRossini1904Pantalewon Or should one use the first among them that was created? This is a matter of discussion but this praixs does not harm as well. Errors (wrong spelling or wrong year etc.) prevent checking, because you get completely unpredictable results and you would not expect Nosnitsin to be written Nosnutsin or Nosnatsin.

Again, it was never my intention to say that this is THE MOST URGENT ISSUE, but it is something that must be considered. If you remember, justifying errors on the base of precedents, was at several times, praxis and matter of discussion in the "EAe": let's try not to repeat the same errors.

**Comment by eu-genia** [comment]
no. one book must have one tag. no double tags can be assigned. the first tag created must be used everywhere as it was already used in the data and cannot be changed.

**Comment by eu-genia** [comment]
as for typos - they must be corrected in the bibliographic entry.
the way we work is: i need to quote something. i look for the entry. if i find it i copy the tag and insert it. i don't care what the tag is as long as this is the entry i need. if i don't find it i must create it and assign the tag. before i assign the tag and close the issue i do the search for the exact tag i am assigning now to make sure noone has assigned it before. there is no circumstance in which i would start looking for "nosnatsin".

**Comment by abausi** [comment]
This is fact, not an opinion.

Aside from this fact, this is in a way understandable: the user can see the tag as not appropriate and needs to use a new one (or the book can be quoted in completely different conetxts).

I do not say that this is correct: but this means that more control is needed and that the creation of the tag should try (arbitrary as it is) to cover the possible use of that tag. This, again, brings us to some further reflection.

**Comment by eu-genia** [comment]
the BM user may not use a new tag if there is one in the BM environment. one can create as many non-BM custom tags as one wants. the context for possible use is not relevant. it is just an ID, for me it could also be bm:ABC123DEF etc.

**Comment by abausi** [comment]
You are right, the problems arise exactly because the tags are half-predictable. And when they contain wrong matter, they are quite disturbing and can induce errors. But in the end, I was only asking to revise a couple of dozens of apparently very wrong tags. The very large majority are clean and "talking", and this has also its great advantages.

**Comment by PietroLiuzzo** [comment]
We are speaking here of a total 27 records in the bibliography, I think this can be simply carried out going through the records and checking the data correcting it accordingly. If you trust me to do this, I can proceed my self with the changes in library and data. We will certainly have this issue again, we can add to the PR review guidelines also to watch out for this.

**Comment by PietroLiuzzo** [comment]
bm:Zawde2003Assallafac --> bm:Zawde2010Assallafac, no record uses this
bm:Chernetsov2014GabraSellase --> removed, no record uses this
bm:KaplanNosnitsin2003BeeseSalam ? 
bm:Pankhurst2010Debarwa --> bm:Pankhurst2005Debarwa, changed in LOC2614Debarw
bm:Dege2010EAESeddat --> bm:Dege2014EAESeddat, changed in LIT1965Mashaf
bm:Marrassini2005Strelcyn --> bm:Marrassini2010Strelcyn, changed in PRS8999Strelcyn
bm:Crummey2010TadlaGwalu --> merged two versions, removed one extra tag bm:Crummey2010Tadla, unused
bm:Lusini2003EAEDersanaS --> bm:Lusini2005EAEDersanaS, changed in LIT2296Sayfas und LIT1300Dersan
bm:Bairu2003BashahAboye --> unused, removed
bm:Habtemichael2005EAEAkkonu --> bm:Habtemichael2003EAEAkkonu, changed in LIT5673AkkonuColl and LIT4274AkkonuB
bm:Raineri2003Lebdeyos --> bm:Raineri2007Lebdeyos, changed in PRS6225Lebdeyos
bm:Burtea2005Susenyos --> bm:Burtea2010Susenyos, changed in PRS8886Sisinios
bm:ChernetsovBustorf2005Sisgayo --> bm:ChernetsovBustorf2010Sisgayo, changed in PRS8885Sisgayo
bm:Lourie2003Eutychius --> bm:Lourie2005Eutychius, changed in PRS3919Eutychiu
bm:Munro-Hay2003Abrha --> unused, removed
bm:Ege2010HaylaMalakot --> bm:Ege2005HaylaMalakot, changed in PRS5205haylaMa
bm:NosnitsinTsegay2003BesuaAmlak ? 
bm:Nosnistin2003Bur -->  bm:Nosnitsin2003Bur, changed in LOC2019Bur
bm:Nosnistin2003Arius --> bm:Nosnitsin2003Arius, changed in PRS2033AriusA
bm:Nosnistin2007Keflo --> bm:Nosnitsin2007Keflo, changed in PRS5929Keflo
bm:Nosnistin2007KeflaMaryam --> bm:Nosnitsin2007KeflaMaryam, changed in PRS5912KeflaMa
bm:WolkNosnistin2007KeflaGiyorgis --> bm:WolkNosnitsin2007KeflaGiyorgis, changed in PRS5907KeflaGi
bm:NosnistinAhmed2007Ifat --> bm:NosnitsinAhmed2007Ifat, changed in LOC3921Ifat
bm:Nosnistin2010RosNabiyat --> bm:Nosnitsin2010RosNabiyat, changed in PRS8212RosNabi
bm:NosnistinDirkAliev2014Zeqwala --> bm:NosnitsinDirkAliev2014Zeqwala, not used
bm:Nosnitsin2007Asir --> bm:Nosnitsin2014Asir, changed in INS0007AM
