### ISSUE TITLE
Encoding of objects placed in MSS

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1395]
What would be a good place to state the presence of objects present in a manuscript which we do not consider to be parts of the manuscript? I have two categories in mind:
- objects such as dried flowers or dead insects
- usually modern notes,  which might contain descriptions of the manuscript by previous librarians or cataloguers, or other documents relating to the history of the manuscript, such as its acquisition (all placed loosely in the manuscript or its case, not glued to it or written on its pages).

These might all contain interesting information on the manuscript's use and history. This information would usually be elaborated in `<history>` - do you think that it would be enough to mention the presence of these objects and documents there, or would a more formalised encoding be useful?

@DariaElagina @eu-genia

**Comment by DariaElagina** [comment]
I have no opinion on insects or flowers, though they might provide a lot of information. But concerning notes or documents which are not attached to the manuscript I would even prefer to consider them on their own and creat minimal records for them.

**Comment by thea-m** [comment]
It is an interesting idea, but maybe too meta for me to imagine in practice - and these are not really objects of the Geez written tradition, but rather scholarly or bureaucratic artefacts (those that I have in mind - there might of course be many different cases).

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 what was your way to treat the louse?

**Comment by thea-m** [comment]
I think that's the one
```
  <condition key="deficient">The volume is worn.
                          Stains of water and dirt,
                          the boards and the leather cover and some leaves are damaged by insects.
                          Dry soil, sand, dry insects are between the leaves.
                          The text block is loose, resewn.
                        Recent parchment repairs on ff. <locus target="#42"/>, <locus target="#114"/>
                        (with the lost text portions written anew). Margins of
                      some folios are cut, <locus target="#5"/>, <locus target="#59"/>,
                      <locus target="#151"/>, <locus target="#161"/>, <locus from="151" to="167"/>.
                    </condition>
```

**Comment by thea-m** [comment]
Regarding the modern documents - what about `<adminInfo>`?
Something like?
```xml
   <additional>
                  <adminInfo>
                     <note>A paper sheet containing a modern description of the manuscript in Arabic is placed inside it.
                        It is stated in the description that <persName ref="PRS12557Barha"/> copied this manuscript as a
                        personal copy. On the verso, there is a description of <ref type="mss" corresp="DSEthiop8"/>.</note>
                  </adminInfo>
               </additional>
```

**Comment by DenisNosnitsin1970** [comment]
Yes, smth like this.

**Comment by thea-m** [comment]
@PietroLiuzzo regarding the modern documents, I think that this information is better encoded in `<adminInfo>`, which we haven't used yet. Anything relevant to the history of the manuscript that might be included in this can be highlighted in history as well. If you have no objections, could you render  the content of `<adminInfo>` under "Administrative information" (maybe under history?) on the app?

**Comment by PietroLiuzzo** [comment]
we use `adminInfo` quite a lot AFAIK, considering it is where the `listBibl[@type='catalogue']` is placed most of the times. the note should follow `recordHist`. I will add this visualization, which will be available with the next release

**Comment by thea-m** [comment]
Ah, yes, you are right. Thank you!

**Comment by PietroLiuzzo** [comment]
<img width="631" alt="Schermata 2020-06-19 alle 10 52 40" src="https://user-images.githubusercontent.com/508012/85114853-04a4ed00-b21b-11ea-8c4c-a6d5783a8a9a.png">
I have left it where it was already, after decoration instead of mixing with history, and added the title only if there is a note to print
