### ISSUE TITLE
cannot create new authority files

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1396]
I cannot create new authority files anymore.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<exception>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>
exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 577, column 19]
</message>
</exception>
```

**Comment by PietroLiuzzo** [comment]
Could you please try again?

**Comment by thea-m** [comment]
Perfect, thank you!

**Comment by thea-m** [comment]
Ah, too optimistic. I could create but not download. 
![image](https://user-images.githubusercontent.com/19650382/79573302-b9594b80-80be-11ea-8278-ee1dcd8e15e3.png)

Didn't we have such a thing once already?

**Comment by PietroLiuzzo** [comment]
yes, but fixing it once does not mean it will not break again.

**Comment by thea-m** [comment]
(I didn't mean that, I just got nostalgic)

**Comment by PietroLiuzzo** [comment]
I see four more *Inlay*.xml files. did you manage to download those?

**Comment by thea-m** [comment]
No, the same error for all

**Comment by thea-m** [comment]
They were supposed to be different files, only all ending with Inlay

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/79573944-b14ddb80-80bf-11ea-830a-17dd5d417c45.png)

**Comment by PietroLiuzzo** [comment]
they are. I cannot reproduce the error. I will download and commit the new files myself. refreshing cache and browser may help.

**Comment by thea-m** [comment]
Thank you!
