### ISSUE TITLE
Dual Language Texts

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1397]
We have several texts in the EMIP collection that are in both Gə'əz and Amharic. Is there any recommendation for how these should be encoded? In particular the @textLang statement.

**Comment by PietroLiuzzo** [comment]
is the first example in this page of the guidelines helpful?
https://betamasaheft.eu/Guidelines/?id=manuscriptContents

**Comment by Ralph-Lee-UK** [comment]
Pietro

 

This is very helpful, and I’ll make sure that things are corrected

 

Regards

 

Ralph 

 

Ralph Lee
Cambridge
UK 

+44 7906169088

**Comment by Ralph-Lee-UK** [comment]
A supplement to this question relates to incipits, where the language is identified with a xml:lang="gez" or similar statement. I have a set of incipits which are quite common where Ge'ez text is quoted, and then interpreted and explained in Amharic, so the sentences are a mixture of the two languages. 

For example, currently in EMIP 625, there is an incipit statement:

<incipit xml:lang="gez">ወእምከመ ፡ ፈጸምከ ፡ አሥራተ ፡ ኵሉ ፡ አሥተ ፡ አሥራቱን ፡ ሁሉ ፡ አውጥተህ ፡ ከፈጸምክ ፡ በኋላ ፡ ና ፡ ተላላፊ ፡ ነው ፡ አመ ፡ ዳግመ ፡ ትኤሥር ፡ ከአሥሩ ፡ አንድ ፡ ከአወጣህ ፡ በኋላ ፡ ዳግመኛ ፡ <gap reason="omitted"/></incipit>

But actually, the first five words and Ge'ez, followed by eight words of Amharic, then another three in Ge'ez and then five more in Amharic. 

In this particular case the words are translations, but that will not always be the case, the translation may develop into extended commentary and interpretation. 

We may need to discuss this with others too, so please let me know who else we should invite to discuss this!

**Comment by PietroLiuzzo** [comment]
This happens rather frequently and should be dealt with using `<foreign>`. The main language of the text should be recorded in `@xml:lang` in `<incipit>`, while parts of the text in other languages including translations will be in a foreign which has the correct `@xml:lang`.
