### ISSUE TITLE
EMIP mss not properly visualized on the app

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1400]
I am not sure whether it might be perhaps intentional, but the content of at least two EMIP manuscripts is not visualized on the app, for example
https://betamasaheft.eu/manuscripts/EMIP00334/main or https://betamasaheft.eu/manuscripts/EMIP00368/main. Only the shelfmarks are printed, not the rest of the record. The records seem relatively normal to me.
(I only saw these two by chance, I did not check other records)

**Comment by PietroLiuzzo** [comment]
In the past, before the latest release you would have got an error page, and no possibility to further navigate, if the XSLT transformation was failing. since 5.0 release this blank page is what you get instead, which allows to further navigate at least.

**Comment by thea-m** [comment]
Wonderful!
