### ISSUE TITLE
paragraphic information on a person's name

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1404]
I would like in a record paragraphic information on a person's name (something like it is this name in that language, which might point originally to that name in this language, which is all quite speculative and encoded purely as persName with various degrees of certainty would be understandable only with difficulty) and am not sure where the best place for this information would be. A `<note>` in `<person>`?
(I think this might be somehow related to the problem outlined in https://github.com/BetaMasaheft/Documentation/issues/1305, but here, floruit really does not seem the right place to me.)
Could you help me?

**Comment by PietroLiuzzo** [comment]
yes, a note in person would be the right place for this.

**Comment by thea-m** [comment]
Perfect, thank you!
