### ISSUE TITLE
empty watermark element

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1405]
Many manuscript records of parchment codices have an empty `<watermark/>` element, and I'm very sure that these are inherited from example ms files and constitute no statement on the presence of watermarks in these manuscripts. 
Could `<watermark/>` be only visualized on the app if it is not empty? The current visualization might be misleading.
(I would also say that these should be in fact deleted from the records, since they are superfluous or wrong.)
For example EMIP02039, and many more, especially EMIP and Vatican records

**Comment by thea-m** [comment]
(In case we opt for a deletion in the records, we should only delete those in records that occur in a `<support>` element which also has  `<material key="parchment"/>`)

**Comment by PietroLiuzzo** [comment]
if we get to the business of deleting superfluous empty elements, we get into a very deep hole. we can easily fix the visualization, but removing an empty statement does not help a lot. it does IMHO no harm and says just nothing, because it is just an empty tag. of course if more care would be used not to leave these empty elements that would be nice!

**Comment by thea-m** [comment]
Thank you! 
The visualisation now is "watermark No", which is much better. I would still be in favour of not visualizing it at all, since it really is meaningless (and now adds to the visual clutter on the app), and I also think that the empty element in the records could be misinterpreted. But it looks to me just like a copy paste issue from some example file in the Vatican and EMIP records, so not very dramatic.

**Comment by PietroLiuzzo** [comment]
mmm, it should not appear at all. can you tell me the example you are looking at? thanks a lot!

**Comment by thea-m** [comment]
EMIP02039, in which I now see there is no `<material>` (not our problem....). In manuscripts with `<material key="parchment"/>` it is not visualized, so all is fine.

**Comment by thea-m** [comment]
Coming accross this again when I searched for watermarks in the files, I still think that it would be better to delete the watermark element in parchment codices. Maybe one day there will be other changes carried out everywhere, or someone will practice scripts or something similar, and that could be included. 
@eu-genia

**Comment by eu-genia** [comment]
the watermarks are not visualized if support is parchment
