### ISSUE TITLE
Description of commentary on a known work

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1407]
In one of the collections imaged by EMIP, there is a set of commentary material on the Five Pillars of Mystery. One work contains several works like the example given here, which although the initial description suggests the work Amǝstu A‘ǝmadä Mǝsṭir, አምስቱ፡ አዕማደ፡ ምሥጢር፡. actually the work is an Amharic commentary on this work. 

Ff. 1r–36v: Five Pillars of Mystery, Amǝstu A‘ǝmadä Mǝsṭir, አምስቱ፡ አዕማደ፡ ምሥጢር፡. The basic work is an Amharic explanation of the teachings of the Church, widely copied, e. g. EMML 1648, f. 16a; EMML 1815; see also ፭ቱ አዕማደ፡ ምሥጢር፡፡ (Addis Ababa: Täsfa Press, 1952 EC). In what follows, the commentaries are not a usual part of the Five Pillars.
በስመ ፡ አብ ፡ ወወልድ ፡ . . . ሦስቱን ፡ ስም ፡ ሦስቱን አካል ፡ አንድ ፡ አምላክ ፡ ብለን ፡ አምነን ፡ በሦስትነቱ ፡ በአንድነቱ ፡ ተማፅነን ፡ ሰይጣንን ፡ ክደን ፡ ዓዕማደ ፡ ምስጢርን ፡ እንናገራለን፡

Any advice on how to go about entering the description of these works would be most appreciated.

**Comment by DenisNosnitsin1970** [comment]
You can consider various options: if the AAM and its commentary are bound together (copied as one text), you can count this as one work and encode accordingly (but this will be not the classical AAM, but a special version of it: AMM+commentary). If the commentary is set apart (copied as the following work, has a properly shaped incipit and explicit), then it is a separate work. It is also possible. THese are the main variants (sometimes, one has to see if the commented text builds up a special version that drifted away from the main branch).   this is how i understand it.

**Comment by Ralph-Lee-UK** [comment]
Thank you for clarifying this. The ones in this manuscript are pretty much all in Amharic with a few Gǝʿǝz words so I am clear that it is some form of commentary.

**Comment by thea-m** [comment]
If it is a commentary interwoven with the main work, it would seem reasonable to create a new work ID  (AMM+commentary) for this, as Denis wrote. Let us know if you want us to create it for you. I do not know this work well, so cannot say anything specific to this situation. However, it is an Amharic work, so I am not sure that the language in itself is an indication here?

**Comment by Ralph-Lee-UK** [comment]
Will do! There are several of these, on a selection of works. When I have the full list I'll let you know.

**Comment by Ralph-Lee-UK** [comment]
One further question, as I build up the list. Particularly with Amharic commentary books tend to be collected together, so, for instance, the Andǝmta on the Pauline Epistles is common as a single work. At the other end, works are often broken down into an 'introduction' and then 'text and commentary'. My sense is that it would be good to create works for the commentary on a specific book, even if it is commonly found with others - would you agree? I think too that at this stage it, following on from answers to some other questions that I have had, we should at this point gather all commentary on a particular book together, with a view to refining definitions at some point in the future, as identifying the particular content of a set of commentaries would be a major work in itself. This would mean, perhaps, putting the Lay Bet and Tach Bet commentaries together, again for the time being. Would you agree?

**Comment by thea-m** [comment]
Hi! Our general criterion for the creation of work IDs is the independence of circulation. If all commentaries on the Pauline Epistle usually circulate together, they will receive a common ID. And if some of these also circulate independently from this collection, they will receive an independent ID (or, conversely, if the collection can also circulate WITHOUT this particular work).
If versions of a commentary are not yet well studied and are difficult to distinguish then we do indeed create a "general ID" for this work which refers to all of its possible versions. Separate IDs for the single versions, if already known, can then be created simultanously or in the future.
I hope that this somehow helps with your questions? Please let us know!

**Comment by Ralph-Lee-UK** [comment]
So the list of commentaries, and other similar works that we have are as follows, all Amharic Commentary on Gǝʿǝz text unless otherwise stated:
Commentary on the Introductory Rite to the Miracles of Mary
Commentary on the Our Father
Commentary on Hail Mary
Commentary on the Praises of Mary
Commentary on the The Commandments
Commentary on the Pillars of Mystery
Commentary on the Nicene Creed
Commentary on the Farewell Speech of Moses
Commentary on Prayer of the Covenant
Commentary on Supplications
Commentary on Litanical Prayer
Commentary on Mystagogia
Commentary on the Ordinary of the Mass
Commentary on the Anaphora of the Apostles
Commentary on the Anaphora of Our Lord
Commentary on Anaphora of John, Son of Thunder
Commentary on Anaphora of Mary
Commentary on Anaphora of the 318 Orthodox Fathers
Commentary on Anaphora of Athanasius
Commentary on Anaphora of Basil
Commentary on Anaphora of Gregory, brother of Basil
Commentary on Anaphora of Epiphanius
Commentary on Anaphora of John Chrysostom
Commentary on Anaphora of Cyril
Commentary on Anaphora of Jacob of Serugh
Commentary on Anaphora of Dioscorus
Commentary on Anaphora of Gregor the Wonder Worker
Commentary on the Five Pillars of Myster
Commentary on the Mystery of the Trinity
Commentary on the Myster of the Incarnation
Commentary on the Mystery of Baptism (two versions)
Commentary on the Mystery of Holy Communion
Commentary on the Mystery of the Resurrection of the Dea
Commentary on the Epistles of Paul (sub items on all letters, including Hebrews)
Commentary by John Chrysostom on Matthew's note about Mary
Comentary on the Didascalia
Commentary on Homilies of the Fathers
Commentary on the Testimony of the Fathers
Commentary on the Testimony of the Fathers on the Incarnation
Commentary on Code of the Kings (መጽሐፈ፡ ፍትሐ፡ ነገሥት፡ ከነትርጓሜው፡)
Commentary on Ezekiel
Commentary on Instructions and Explanations to the Chanters
Commentary on the Computus
Commentary on Qerǝlos
Commentary on the Words of Aragawi
Commentary on the Story of David
Commentary on the  Four Gospels 
Commentary on Orit/Octateuch
Commentary on Enoch
Commentary on Daniel
Commentary on Psalms
Commentary on the Psalter
Commentary on Book of Revelation
Commentary on Isaiah
Commentary on the Daily Prayer
A final work is 'A Theological Critique of Certain Practices of the Orthodox Church, ስለ፡ ኦርቶዶክስ፡ ቤተ፡ ክርስቲያን፡ አንዳንድ፡ ሥርዓቶች፡ የቀረበ፡ ነገረ፡ መለኮታዊ፡ ትችት፡ which only occurs once. There are lots of sub sections in this, but as there is only one copy, it should probably just be categorised as a single work

I think there may be more of these, but this is the major part

**Comment by thea-m** [comment]
Thank you! We will look into this in the next days.

**Comment by DenisNosnitsin1970** [comment]
I think Commentary on the Pillars of Mystery and Commentary on the Five Pillars of Mystery may be the same.

**Comment by PietroLiuzzo** [comment]
Once the list will be stable and consolidated I can batch create these record starting from a small table (as we did for EMIP records).

**Comment by thea-m** [comment]
I am already creating them in the Commentaries branch.

**Comment by Ralph-Lee-UK** [comment]
@thea-m sorry for the delay in responding to this one too! 
the commentary on the Anaphora is, I believe, commentary onhttps://betamasaheft.eu/works/LIT1569habeka/main

The commentary on the Creed is probably connected to https://betamasaheft.eu/works/LIT5629AndemtaCreed/main, yes. With the current understanding, it would seem appropriate to group them together, until we are clearer about different versions. 

Regarding your other questions, at the moment I think that the commentary on the mysteries are separate from those on the Five Pillars. Perhaps the works records could cross reference each other to point to researchers the need to look into this?

From the catalogue entries that I have, the two commentaries on the mystery of Baptism are not the same. The catalogue entry for one says 'second version'. Would you like me to look into this further?

I also understand that yes there are commentaries on the Psalter and commentaries on the Psalms. The part of the former that is on the Psalms will probably relate to the second!

**Comment by thea-m** [comment]
Thank you! I think I addressed everything for now in https://github.com/BetaMasaheft/Works/pull/167, exept the second version of the Commentary on the Mystery of Baptism. Could you give me anything allowing to distinguish both versions (even only manuscripts they are attested in, if the catalogue already mentions the two versions)?
