### ISSUE TITLE
Noting Ownership

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1409]
I have a set of mss which are known to have been owned by the Nəburä ‘Ǝd Dəmeṭəros Gäbrä Maryam. There is no 'ownership note' in the mss, but they have what is described in the catalogue as 'An extensive colophon with a presentation poem composed by the copyist to the owner'. This poem clearly indicates the owner. Wondering if you could offer some guidance as to how to code this 'addition'. It could have type as 'poem' but that doesn't necessarily describe the substantive content that the poem indicates the copyist and the owner. Any help most welcome

**Comment by PietroLiuzzo** [comment]
could this not just be in the [colophon](https://betamasaheft.eu/Guidelines/?id=colophon) as described in the catalogue?
[in these examples](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3Acolophon%5Bdescendant%3A%3At%3ApersName%5B%40role%5D%5D) you will find a person with a role marked up inside a colophon.
among them, this example from [https://betamasaheft.eu/RNBEfns23](https://betamasaheft.eu/RNBEfns23)
`````xml
<colophon xml:id="coloph1" xml:lang="gez">
<locus target="#291v"/>
ዝንቱ፡ መጽሐፍ፡
<persName ref="PRS12511DaligawY" role="owner">ዘደሊገው፡ ዮሐንስ።</persName>
ዘአጽሐፎ፡
<persName ref="PRS12512HaylaI" role="donor">ኃይለ፡ ኢየሱስ፤</persName>
ጸሐፊ፡ ኃጥእ፡ ወምኑን፡
<persName ref="PRS12513WaldaM" role="author">ወልደ፡ ማርያም፡</persName>
ወቢጹ፡ ናርዶስ፤ ዘሠረቆ፡ ወዘፈሐቆ፡ በሥልጣነ፡ ጴጥሮስ፡ ወጳውሎስ፡ ውጉዘ፡ ለይኩን። አሜን፡
</colophon>
`````
if you do not have the text of the colophon, the following is also ok.
`````xml
<colophon xml:id="coloph1">
<persName ref="PRS1234yourowner" role="owner"/>
</colophon>
`````
or you can simply note the owner in [`<particDesc>`](https://betamasaheft.eu/Guidelines/?q=owner&id=particDescPersons)

this gives you several ways to give the information that this person is owner, the other a copist, etc., but it does not help with the poem.

**Comment by DenisNosnitsin1970** [comment]
I bit diffiult to understand what it is about having no text. The colophon must focus on the production aspect (at least in my understanding), it can be also poetic. On the other hand, there are some poetic compositions of different kinds, that mention all agents involved, but they are smth different (poems in honour, on the presentation, for the church, for saints, etc.).

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo This is exactly what I wanted, but thanks @DenisNosnitsin1970 for the extra information too!
