### ISSUE TITLE
title not printed correctly

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1410]
The title of LIT5886MonthsLength is printed on the app as "MonthsLength", not as "On the length of the day during the months of the year." as given as t1 in the record

**Comment by thea-m** [comment]
same for LIT5185PrayerHemamBuda
This also affects the rendering of the titles in the article, which is what interests me right now...

**Comment by PietroLiuzzo** [comment]
of course, titles are done the same everywhere. This is however quite weird. it looks like a title MonthsLength was actually there at some point.

**Comment by thea-m** [comment]
I think it might have been created like this, but was later corrected. Thank you!

**Comment by thea-m** [comment]
It seems like this is not fixed yet? There is the same here: https://betamasaheft.eu/works/LIT5912MMThecla/main
I remember that I typed only "Miracle of Mary:" in the form and then added the rest of the title in the record (I just pressed on create too quickly, it can happen...).

**Comment by PietroLiuzzo** [comment]
the record predates the fix, I have corrected it in the titles list

**Comment by PietroLiuzzo** [comment]
if you find other cases, updating the record should also update the title and thus fix it if it was created before the fix and registered with a wrong title

**Comment by thea-m** [comment]
Thank you!
