### ISSUE TITLE
zotero doublet

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1411]
There seem to be two identical Zotero entries for the EAe entry on Abugida and Hahu by Chernetsov. Can one be deleted or is there a deeper reason for this?

**Comment by abausi** [comment]
Provided that the BM tags are preserved, one can be deleted; at best, 
they should be merged, which automatically preserves all tags, all 
merged in the only remaining entry. I can do this.

Il 08.05.2020 08:40, thea-m ha scritto:

**Comment by thea-m** [comment]
Thank you!
