### ISSUE TITLE
summary in layout?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1412]
In a manuscript that has multiple layouts (encoded in different `<layout>`s in `<layoutDesc>`), I would like to provide some general statements applying to the entire manuscript. In analogy to the description of decorations, could I use `<summary>` in `<layoutDesc>` (and if so, could this be visualised in the app before the single layouts?)?

**Comment by PietroLiuzzo** [comment]
yes https://betamasaheft.eu/Guidelines/?id=layoutDesc :)
