### ISSUE TITLE
A manuscript containing many framgments

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1414]
One EMIP manuscript contains many fragments of books, partly listed below. 

Would it be correct in this case to code all the fragments of Jubilees, for instance, together, under one major item, just giving all the details in the locus and other statements? The hand is consistent, and it looks like the folios have been stitched together out of order, and some lost. 

Ff. 1rv: Jubilees 15:3–19
Ff. 2rv: Hosea 14:4–9; Amos 1:1–9
Ff. 3rv: Amos 1:9–2:10
Ff. 4rv: Jubilees 49:1–11
Ff. 5rv: Hosea 11:8b-13:2a
Ff. 6rv: Hosea 9:5–10:5a
Ff. 7rv: Jubilees 43:21–44:12
Ff. 8rv: Amos 2:10–3:12a
Ff. 9rv: Amos 3:12b-4:10a
Ff. 10rv: Jubilees 31:3–16a
Ff. 11rv: Jubilees 31:16b-28a
Ff. 12rv: Jubilees 26:27–27:6  
Ff. 13rv: Jubilees 27:6–21
Ff. 14rv: Jubilees 27:21–28:6
Ff. 15rv: Jubilees 28:6–19 (through, “. . .and Jacob went in again. . .”)
Ff. 16rv: Jubilees 30:17–31:2
Ff. 17rv: Jubilees 28:19–29:2
Ff. 18rv: Amos 8:7–9:6 (through, “. . .the one who builds his upper chamber in the heavens”)
Ff. 19rv: Amos 9:6–15; Micah 1:1–5 (through, “what is the. . .”)
Ff. 20rv: Micah 6:11–7:12a
Ff. 21rv: Jubilees 43:7–21
Ff. 22rv: Jubilees 23:11–20
Ff. 23rv: Jubilees 21:4b-13a
Ff. 24rv: Jubilees 42:4–20a
Ff. 25rv: Jubilees 37:19b-38:8
Ff. 26:vr: (folio is reversed) Micah 1:5–2:3
Ff. 27rv: Hosea 13:2–14:3
Ff. 28rv: Jubilees 34:7b-20a
Ff. 29rv: Jubilees 34:20b-35:10a
Ff. 30rv: Jubilees 35:10b-20b
Ff. 31rv: Jubilees 35:20b-36:4b
Ff. 32rv: Jubilees 32:9a-21b (through, “. . .do not dwell here”)
Ff. 33rv: Jubilees 38:8b-39:5b
Ff. 34rv: Jubilees 39:5b-39:18b

**Comment by PietroLiuzzo** [comment]
sounds ok to me, with the locus elements.

**Comment by thea-m** [comment]
Yes, that is what we would do in these cases, when the manuscript has been misbound

**Comment by PietroLiuzzo** [comment]
although this can be done and is ok, you do have the option of a better and more detailed description, using `<msFrag>` if you have the necessary information about each material fragment, or even just some on some fragments physically distinct.https://betamasaheft.eu/Guidelines/?id=manuscripts
please, if the answers are ok, close this issue.

**Comment by thea-m** [comment]
@PietroLiuzzo the guidelines paragraph on msFrag and the issue it arose from deal with cases in which fragments of a former circulation unit are now spread in different manuscripts. That is different from the case of missbound leaves all kept in one manuscript. If you think msPart and msFrag would be more appropriate there, it would maybe be good to discuss this in a separate issue, because this would concern many other records.

**Comment by PietroLiuzzo** [comment]
I do not understand your concern. The guidelines give one specific more complex case which requires guidance but the normal use of msFrag and msPart remains normal usage, which we could perhaps document with some examples in the GL. I do not think we do not need to extend one specific case to all cases. In this manuscript, if knowledge is available and time to enter the data and will to so, it is an available option to use msFrag/msPart, and even if this is the option chosen in this case, I do not actually see the need for it to affect any other record where a different possible decision has been taken already which follows the guidelines and is valid. I just wanted to inform about other options, as good as the one already proposed.

**Comment by thea-m** [comment]
But they seem to me two different cases, which points to differences in understanding that might affect other records. Without having seen the manuscript in question, I understood that what happened was that there is one unit of production, which in the production process has been bound not in the intended and textually warranted order. This is to me very different from having one manuscript constituted of several units of production, in which case we would use msPart.

**Comment by Ralph-Lee-UK** [comment]
@thea-m the manuscript is at this link https://betamasaheft.eu/manuscripts/EMIP00654/main, as I have coded it. The images are not available yet, but should be shortly. Here are the first 6 images, of the first 6 folios listed above, to give you an idea of what we are talking about.  

![EMIP00654_MYS54_001](https://user-images.githubusercontent.com/39619238/83158619-e73da100-a0fc-11ea-8730-6f6b3c71b2e0.jpg)
![EMIP00654_MYS54_002](https://user-images.githubusercontent.com/39619238/83158636-ed338200-a0fc-11ea-8790-bd210a6348ad.jpg)
![EMIP00654_MYS54_003](https://user-images.githubusercontent.com/39619238/83158655-f290cc80-a0fc-11ea-93bc-c56ea4d72a6f.jpg)
![EMIP00654_MYS54_004](https://user-images.githubusercontent.com/39619238/83158676-f91f4400-a0fc-11ea-8049-becf73c14ea0.jpg)
![EMIP00654_MYS54_005](https://user-images.githubusercontent.com/39619238/83158705-03d9d900-a0fd-11ea-8357-d775a662cbc5.jpg)
![EMIP00654_MYS54_006](https://user-images.githubusercontent.com/39619238/83158733-0d634100-a0fd-11ea-9eb5-b885796f1c9f.jpg)

**Comment by thea-m** [comment]
Oh, nice old manuscript! :)
To me, it does look like misbinding/later partial destruction of the codex and not like several units of production. I would encode it with several locus elements. But it seems possible that @PietroLiuzzo and I have a different understanding of the use of msPart.

**Comment by DenisNosnitsin1970** [comment]
If it is the same hand, may be this is just one manuscript with destroyed binding and leaves in disorder?

**Comment by PietroLiuzzo** [comment]
I only wanted to offer an alternative option.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 yes you are right. I think Steve Delamarter first received these in a plastic bag!
Thanks for the advice. Are you all happy with the way it is currently coded?

**Comment by PietroLiuzzo** [comment]
I think it is ok, thanks.
