### ISSUE TITLE
work title printed

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1415]
It might be an indexing problem (?) but I do not understand where the printed title of a work is taken from.

Can you please give a link to an example?
https://betamasaheft.eu/works/LIT1198Baqada

What is wrong with it?
The title above is printed as
"Bäqädami gäbrä Ǝgziʾabǝḥer"

What would you like to see?
"Ba-qadāmi gabra ʾƎgziʾabǝḥer" (as in title)

**Comment by PietroLiuzzo** [comment]
there was another issue about this few days ago and an issue was identified and fixed which prevented the update of the titles in the reference list of titles in the application on modifications. for a good two months records have been committed and updated without this fix and there are a lot which present this issue. I will rebuild the list entirely with the next release, but for now we will fix on a request basis. you need not to try and reverse engeneer, the rules used to decide the title remain the same, and are documented in the relevant Guidelines pages.

**Comment by thea-m** [comment]
Re-commiting the record with a pseudochange as suggested to me previously by @PietroLiuzzo fixes the title, I just did it with this and another record

**Comment by PietroLiuzzo** [comment]
> Re-commiting the record with a pseudochange as suggested to me previously by @PietroLiuzzo fixes the title, I just did it with this and another record

This is just if you really cannot wait until the next release, e.g. if you are working on an upcoming deadline. please avoid workarounds and unnecessary commits, if possible. for example you can do a real improvement instead of a pseudochange... but since it is a known issue with an already working solution, the best think to do would be to simply wait.

**Comment by thea-m** [comment]
I really could not wait. It was also exactly what you suggested me to do. And it is very rare to find a record in which there is not one useful thing that can be improved.

**Comment by eu-genia** [comment]
Is it the same or a different issue that I see now e.g. in the new records such as 
LIT5924CanticleBE
(the title is printed twice?)

**Comment by PietroLiuzzo** [comment]
it is a different issue, but it is now already here, no need to move it around.

**Comment by PietroLiuzzo** [comment]
@eu-genia and @thea-m  do you remember by any chance if you loaded these pages or compiled pdfs immediately after merging? this information would help me roll out some options among the ones possible (I have any way removed the doubles from [the affected commit](https://github.com/BetaMasaheft/Works/pull/143))

**Comment by thea-m** [comment]
I think that for both cases (asynchronised titles and double titles) I saw examples for records not immediately edited before loading/editing (for the double titles for sure). But I cannot be completely certain now...

**Comment by eu-genia** [comment]
the double titles were newly created records, they were first uploaded more or less as they are now (only minor typos edited after the very first commit), and I only tried to load pages today

**Comment by eu-genia** [comment]
(may I further edit the affected work files? I have a branch with minor edits (https://github.com/BetaMasaheft/Works/compare/minor-edits) waiting for a pull request)

**Comment by PietroLiuzzo** [comment]
yes, you can do whatever you want, this is still a bit mysterious, I have done an error somewhere which I am clearly not finding. 
Where these for example committed as references in a mss and then committed as new works?

**Comment by thea-m** [comment]
do you mean the ones that are not synchronised or the ones with the double title?
(I don't know about either, but maybe something will come to mind later...)

**Comment by eu-genia** [comment]
"Where these for example committed as references in a mss and then committed as new works?"

Well committed no, but I am not so sure about the merge (they were both yesterday but cannot remember the order, could be that the MS branch was merged first)
Is there a time stamp? https://github.com/BetaMasaheft/Manuscripts/commit/d52425d4f434091fdbfc4423c18961f187bf5253

**Comment by PietroLiuzzo** [comment]
thanks, this is already helpful, the timestamp of the commits or merge would not help a lot unfortunately because the title is added to the list only when it is first requested. I will now test this sort of flow

**Comment by eu-genia** [comment]
I see the same prob with a very old and never corrected work entry LIT1301Dersan

**Comment by PietroLiuzzo** [comment]
Just as an update 
- I have removed manually the 120+ remaining doublets 
- limited the matched title from the list to the first, although there should not be two at all.
this should hide the issue at least.
my testing however has not revealed any issue in the code, but looking at each case has pointed me in the direction of an old issue with the xquery update module, which sometimes doubles the insert. I am investigating this further to see if this is really the issue and how to sort it.

**Comment by PietroLiuzzo** [comment]
I have also added a timestamp to the title as they get added, so that, after the release, we will be able to track this down if it reappears. thanks for your patience and cooperation
