### ISSUE TITLE
ʾAdām or ʾAddām?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1416]
Both are used in BM and it is not yet on the list https://betamasaheft.eu/Guidelines/?id=dubious-spelling. 
If I searched the TraCES corpus correctly, the decision seemed to lean towards ʾAddām?
Thank you!

**Comment by abausi** [comment]
One more case that is very doubt and can be solved only by an arbitrary 
decision. I think we had discussed also in TraCES and we opted, if I 
remember well, for ʾAddām, but for sure no consistency was achieved. 
Yet, still, probably better: ʾAddām. Who knows if we have to do with a 
reversed case of Tigrinya-Amharic speakers' habits length opposition?

Il 20.05.2020 14:11, thea-m ha scritto:

**Comment by thea-m** [comment]
Who knows indeed...
Thank you!
