### ISSUE TITLE
information on text block

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1418]
I would like to encode consistently information on the text block (in our case, until now only the information that it is industrially produced or a notebook, but there might be other cases with other information on it). This is currently done either in binding or collation. Where do you think this information would best belong? Now I think that support would maybe be an appropriate place? (We could go then for a simple `<p> `with paragraphic information, or something else)
@DenisNosnitsin1970 @DariaElagina

**Comment by thea-m** [comment]
@DenisNosnitsin1970 if we find a solution for this, it will make the PDF process easier

**Comment by DenisNosnitsin1970** [comment]
I see, it is a bit difficult. Most of the catalogues do not have this feature, which is however necessary esp. when everyone includes the collation formula. Let me think a short while.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 decided that this would best be included in `<collation>`.
@PietroLiuzzo would it be fine for instance to have a simple `<p>`  in which information on the text block will be included paragraphically in `<collation>` before the list and signatures?

**Comment by PietroLiuzzo** [comment]
I appreciate @DenisNosnitsin1970 suggestion, but I have to say that I have not understood what the features to be encoded are, and this conversations sounds a bit elliptic (which PDF process? which feature? what is a "text block"?). I will try my best to provide some feedback. 

If the schema allows you a paragraph, you can add a paragraph, as usual, but collation is [collation](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-collation.html), and

>  contains a description of how the leaves, bifolia, or similar objects are physically arranged.

and  "text block" "information" is a bit vague for me to make a suggestion on this topic. If this "text block" is a "similar object" and the physical arrangement is what you want to describe that is entirely ok. 

However, there is currently no similar case of use of `<p>` inside `<collation>` in our data, but we use `<note>` for [general or fragmentary information on the quire structure](https://betamasaheft.eu/Guidelines/?q=collation&id=collationDesc) which does not fit in `<signatures>` or in the quires (item[@xml:id="q{\d+}"]) `<list>` in [more than 600 cases](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Acollation%2Ft%3Anote). If you are trying to make a case for `<p>` as opposed to `<note>` for a different type of information, I would argue that the current use of `<note>` is no way semantically different from your intended use of `<p>` and using `<p>` beside `<note>` as a way to distinguish these would be wrong, compared to simply continue to use `<note>`. 

If it really is only "notebook" or "industrially produced" which you want to add, we have a value "Notebook [An object consisting of an industrially produced paperblock in the form of a notebook.]" for `@objectDesc`, which you already know about (e.g. DSEthiop7) to which a value "IndustriallyProduced" could be added or any other you will feel the need to add, which[ fits the attribute description](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-objectDesc.html#tei_att.form). This would allow filtering with this value as well. A paper notebook, could be further described in `<support>` with a `<p>` as you rightly posed, and I do not understand why and when this valuable option got discarded in the conversation in favour of collation.

If in your catalogue's PDF you would like to have this information printed with the collation or under a "collation" heading which does not need to have the meaning of the TEI collation element, this is of course entirely ok, but does not needs to interfere, let alone determine the encoding, in the collation section of your PDF we can print also the`<p>` present in `<support>` when the value of `objectDesc/@form` is one of a sublist you decide, e.g. Notebook, IndustriallyProduced.

I hope this helps.

**Comment by DenisNosnitsin1970** [comment]
Dear Pietro,  I am sorry, actually I did not make any clear suggestion, I do not understand what is the subject of the discussion. For the Dayr as-Suryan catalogue, bits of information on the textblock (which is neither collation nor binding) will be placed in "Other details". That is all. As to the rest, I did not think of that properly.

**Comment by PietroLiuzzo** [comment]
I think we are all happy with `<p>` in `<support>` and this issue can be closed

**Comment by thea-m** [comment]
Good, I think this would already be covered somehow by the example of using p in support for further material description that is already present in the guidelines, so I will not edit them further, please do if you feel it would be better.
