### ISSUE TITLE
error keyword index view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1419]
The index view for some categories of keywords seems to have a problem (subjects, occupations, periods, person types):

> HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/authority-files/list: exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: titles:decideTUSource($resource as item()*, $pRef as xs:string) item()*. Expected cardinality: exactly one, got 0. [at line 183, column 67, source: /db/apps/BetMas/modules/titles.xqm] In function: titles:decideTUSource(item()*, xs:string) [183:33:/db/apps/BetMas/modules/titles.xqm] titles:switcher(item()*, item()*) [23:4:/db/apps/BetMas/modules/titles.xqm] titles:printTitle(element()) [463:228:/db/apps/BetMas/modules/titles.xqm] list:getlist(xs:string*, xs:integer*, xs:integer*, xs:integer*, xs:integer*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMas/modules/list.xqm]

**Comment by thea-m** [comment]
https://betamasaheft.eu/authority-files/list?keyword=ecclesiastic these pages I mean, sorry

**Comment by PietroLiuzzo** [comment]
sorry, it should be fine now

**Comment by thea-m** [comment]
Thank you!
