### ISSUE TITLE
persons - reference to existing repositories?

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1421]
Is it possible to apply the rule for place names, namely to use external links (e.g to Wikidata IDs) instead of creating a new record for widely known places, also to persons. 
For example:  
`<persName ref="wd:Q16859468">Parsley Peel</persName>`

**Comment by PietroLiuzzo** [comment]
As far as I remember using `<persName ref="wd:Q16859468"/>` (so, also omitting the actual name, if you are in an english context and are fine with the standard english name in wikidata) should be already possible without any problem, please let me know if this is not the case and in which situation it does not behave as expected (validation? visualization?). there is no explicit paragraph about this in the guidelines, but the usage is exactely the same as for placeName.

**Comment by SusanneHummel** [comment]
The enocing is valid, so it should work. We, @thea-m and me, just wanted to be sure, since there is no explicit mention in the guidlines for persons.

**Comment by PietroLiuzzo** [comment]
eventually I think what the GL say after example 2 in the [named entities page](https://betamasaheft.eu/Guidelines/?q=named%20entities&id=named-entities-and-authority-lists) "same for placeName and region" should be "same for persName and region", I can fix it
