### ISSUE TITLE
Assigning CPG IDs to the second-level BM IDs: Case of Qerǝllos 

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1422]
Dear all,

I have encoded the text structure of Qerǝllos LIT3309Qerellos assigning second-level IDs to all identifiable textparts within this collection. Many of them (with the exception of only third section) have corresponding CPG IDs, which need to be documented. However, there is by now no "proper" way to assign CPG IDs to single textparts. 
I have no information and no evidence on independent circulation of all these textual units (which might be a case, please share if you know about it), thus creation of first-level IDs for them would contradict to our GL, which stays that the first-level IDs are reserved for the works with an independent circulation. I would find it problematic to create first-level IDs basing not on the evidence from Ethiopic tradition, but on external documentation. 

The pull request in which the topic has arised: https://github.com/BetaMasaheft/Works/pull/156

What would be the most sensible and economic solution?

**Comment by thea-m** [comment]
Is the way it has been done (and not documented) in LIT1586Hayman fine?
```
     <div type="textpart" xml:id="Theophilos2">
                  <label>Extract from the 21st Festal letter (Graf 1937, 383)</label>
                  <listBibl type="clavis">
                     <bibl type="CPG">
                        <ptr target="bm:CPG2"/>
                        <citedRange unit="item">2589</citedRange>
                     </bibl>
                  </listBibl>
               </div>
```

**Comment by DariaElagina** [comment]
I had this idea, but if I could undertsand the Pietro's reply in the PR, this would not surface either in data or on the App. But it is good to know that there are further cases :)

**Comment by eu-genia** [comment]
As I mentioned under the pull request, note that the homilies already have work records, which were already used in MSS descriptions
![image](https://user-images.githubusercontent.com/17987728/83014641-5e9d0300-a01f-11ea-8f1d-eb3c93d53d32.png)

Cp. 
BLadd16200
IVkoriander3

So I would simply follow the way the Qerellos manuscripts have already been treated in the BM, which seems the most reasonable to me

**Comment by DariaElagina** [comment]
But these mss attest the circulation within the collection, not an independent circulation of the textual units. I can just encode the corresp relation, which would spare my time. But a reconsideration of GL on the textual units it required then.

**Comment by PietroLiuzzo** [comment]
> LIT1586Hayman

@thea-m you are right, it does surface in the header, it could be better though... and could really do with some documentation in the GL, so next time we do not need to wonder. I can improve that labelling to report the title of the part of the record

**Comment by PietroLiuzzo** [comment]
<img width="615" alt="Schermata 2020-05-27 alle 16 46 59" src="https://user-images.githubusercontent.com/508012/83035459-c6f8de00-a039-11ea-9dcc-0db323798e69.png">

**Comment by PietroLiuzzo** [comment]
@DariaElagina could you draft a change for the GL and make a PR there linked to this issue? I would actually take the example here. As it turns out [there are more](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-root%2F%2Ft%3AlistBibl%5B%40type%3D%27clavis%27%5D%5Bancestor%3A%3At%3Adiv%5B%40type%5D%5D). I had completely forgotten.
