### ISSUE TITLE
E-S MSS images

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1423]
At least in some cases the image folders (also loaded to the BM server) contain many copies of the same page (minor changes), e.g. notably
ESqs007: there are 61 images on the server now, but actually the (beautifully illuminated composite) MS only has 8 folia and no binding, actually the whole is covered by images 001-009, the rest is repetition.
Would it be better to "clean" such cases, or we leave it at that? (@PietroLiuzzo your opinion is also important)

**Comment by DenisNosnitsin1970** [comment]
I do not know why it has so many images, maybe there was a mistake somewhere (smth copied twice, perhaps). We uploaded only the normal regular images + binding, there was not special images.

**Comment by eu-genia** [comment]
look for yourself in 
VSHLZ5\HLZ5\QS-Qälaqel Seyon  User\QS-007 User\QS-007 User\QS-007 User\QS-007 User Resized

**Comment by eu-genia** [comment]
or on the BM server (i have now added facs but not yet uploaded so only one by one)
from
https://betamasaheft.eu/iiif/QS/007/QS-007_001.tif/full/full/0/default.jpg
to
https://betamasaheft.eu/iiif/QS/007/QS-007_061.tif/full/full/0/default.jpg

**Comment by eu-genia** [comment]
I suggest that at least on the BM server for the app, all images from 010 to 061 are removed

**Comment by PietroLiuzzo** [comment]
actually, extra images if ordered do not harm. when you want to publish these images, which are not currently available via BM, it would be enough to provide in `@n` the last useful image. I have moved the extra images away in the server.
