### ISSUE TITLE
explanatory text in <colophon>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1424]
I'm a bit surprised that this hasn't come up yet, so I might have missed it...
What would be the best place to add explanatory text in a colophon? Not the translation, but sometimes we add paraphrastic summaries or similar remarks.
This is in the data both in `<note>` in `<colophon>` and directly in `<colophon>`.  Both are fine with the schema and I don't think the variation is dramatic, but it could be good to add something to the guidelines. The encoding in note is, in my impression, more often, and would make sense because then the direct text in `<colophon>` would be that of the colophon itself. Could we add this to the guidelines? (A minor issue might be that we usually have `<colophon xml:id="coloph1" xml:lang="gez">` whereas the text in note would not be in Geez.)
@DariaElagina @eu-genia @PietroLiuzzo

**Comment by DariaElagina** [comment]
I would prefer to use the note to put such kind of information.

**Comment by eu-genia** [comment]
I confirm, I have used a note element within the colophon element in such cases.

**Comment by PietroLiuzzo** [comment]
note is fine and can be documented in GL, thanks

**Comment by thea-m** [comment]
thank you!
