### ISSUE TITLE
encoding partial rubrication

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1425]
We would like to differentiate between "complete" rubrication, where the entire word or element is written in red, and partial rubrication, where only parts of an element (typically numerals and punctuation marks) are rubricated. 
As always, of course the existing hi rend="rubric" (which has been used widely for both cases) should remain valid.
I think it would be logical to introduce a new value for `@rend` in `<hi>` (partialRubric or something like that). The schema also offers `@rendition` in `<hi>`, which we haven't used and I didn't find explained anywhere, could this be used here?
@SusanneHummel @MassimoVilla

**Comment by PietroLiuzzo** [comment]
I do not understand this question. With `<hi rend="rubric"/>` you mark up what is rubricated. if only the dot is rubricated then, only put the element around the dot. 
```xml
<hi rend="rubric">ላሊበላ፡</hi>
<hi rend="rubric">ላሊ</hi>በላ፡
ላሊበላ<hi rend="rubric">፡</hi>
```
This is already marking up that part of a word is rubricated and is already and very precisely computable. we could also tell what the average percentage of a word is rubricated, including or excluding or isolating punctuation. e.g. in the example above the entire three line of text are 6 letters out of 12 which are rubricated in total, but the average percent (partial) if we omit punctuation, based on a word is still 50%, punctuation is on the total rubricated 66% of the times within words with separators which have some rubrication at all, etc... different counts could also be made of course based on codepoints.
or am I missing what you mean by "partial"? do you mean part of a letter?

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/84065099-0cb39000-a9c4-11ea-8638-969446edad55.png)
Sorry!
Here you can see that some punctuation signs (፨, ፤) and numerals are only partially rubricated, it is not possible (for me) to mark up only a part of these elements...

**Comment by PietroLiuzzo** [comment]
ok, elements for me means elements in XML. 
I would use [`@rendition`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.rendition.html#tei_att.rendition) which 

> "points to a description of the rendering or presentation used for this element in the source text."

```xml
<hi rend="rubric" rendition="#partialRubric">፨</hi>
```
this requires inside `encodingDesc/tagsDecl` the following

```xml
<rendition xml:id="partialRubric">Red ink is used only partially (e.g.!!!)</rendition>
```
This becomes IMHO interesting if related also to a `handNote`

```xml
<hi rend="rubric" rendition="#partialRubric" hand="#h1">፨</hi>
```

**Comment by PietroLiuzzo** [comment]
please, let me warn you once more and encourage you to consider if this is really necessary... what will you actually do with this?

**Comment by thea-m** [comment]
Thank you!
What would you like in the (e.g.!!!)? An example from the file? It is a very common phenomenon.

First, it is simply more precise (both complete and partial rubrication exist for these elements), and does would not cost in any way more time. Second, it will be interesting to study the use of rubrication (why are we marking up rubrication at all?) over different periods and places. We are really in Grundlagenforschung here and precisely encoding easily identifiable features as these without large time investments will prove an imprortant basis for further research.

**Comment by PietroLiuzzo** [comment]
you can put what you prefer to properly describe this rendition, I just added some example text, so that you were not left only with the css like example in the TEI guidelines. My concern about the excess of encoding is that there will always be some other basic feature which perhaps one day would be nice to work on, but if we set out to do each of these and keep adding there will never be any consistent set of data to do anything and the future will become so remote we will not even remember what we set out to do and why. Indeed our curiosity and interest always surpass our possibility, but a pinch or realism sometimes cannot harm. My tuppence only! I think my job is only to warn you and encourage a selective decision process. You are of course free to markup whatever element, feature, letter, or particle you wish!

**Comment by PietroLiuzzo** [comment]
@thea-m should I just document this suggestion in the GL? are you happy with it?

**Comment by thea-m** [comment]
Thank you and sorry, yes. I have actually already used this in BDL records, fir example BDLaethb5.
