### ISSUE TITLE
Advanced Search Quire Number Search fails / xs:integer / count issue 

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1426]
Ich habe eine Frage zur Suche.

Ich wollte gern alle Geez-Manuskripte angezeigt bekommen, die mehr als 31 Lagen (ich hatte den Rahmen auf 31-59 gesetzt) haben. Also habe ich die entsprechenden Filter in der Suche verwendet (siehe Bild 1 
[screenshot 1.pdf](https://github.com/BetaMasaheft/Documentation/files/4748245/screenshot.1.pdf)). 

Als Ergebnis erhalte ich 61 Mss, vgl. Bild 2 (
[screenshot2.pdf](https://github.com/BetaMasaheft/Documentation/files/4748244/screenshot2.pdf)) und https://betamasaheft.eu/as.html?query=&homophones=true&AttestedInType=1&xmlid=&work-types=mss&qn=31%2C59&language=gez#

Klicke ich nun auf das erste Ms in der Ergebnisliste, hat dieses aber nur 5 Lagen. https://betamasaheft.eu/manuscripts/SHOr400/main

Mach ich etwas falsch?

**Comment by PietroLiuzzo** [comment]
nein, du machst nicht falsch. hier sucht die app in measure[@unit='quire'] und erwartet einen numerische Werte. der ist aber meistens nicht...
e.g.
```xml
<measure xmlns="http://www.tei-c.org/ns/1.0" unit="quire">6</measure>
<measure xmlns="http://www.tei-c.org/ns/1.0" unit="quire">Protection quire + 19</measure>
<measure xmlns="http://www.tei-c.org/ns/1.0" unit="quire">A+11</measure>
```
alternative suche: 
https://betamasaheft.eu/facet.html?query=mansucript&type-facet=manuscript&QuireCount-facet=34&QuireCount-facet=37&QuireCount-facet=38&QuireCount-facet=40


ich hab auch die xs:integer weg genommen wegen performance

**Comment by PietroLiuzzo** [comment]
RDF data does not contain total quires. update
search instead counting items in collation

**Comment by PietroLiuzzo** [comment]
noch alternative such, die sucht direkt in collation
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Acollation%2Ft%3Alist%5Bcount%28t%3Aitem%29+ge+31%5D

**Comment by PietroLiuzzo** [comment]
in die letzte gibt es mehrere ergebnisse, weil das index in facet rechnet nur `//t:collation//t:item[@n]`, und die suche oben alle auch die die kein `@n` haben

**Comment by PietroLiuzzo** [comment]
in app.xqm `t:TEI[descendant::t:collation/t:list/count(t:item)[. ge 31][. le 59]]` cannot work (reusing app:paramrange()) another query constructor is needed which will make a count()

**Comment by SusanneHummel** [comment]
Danke. Die erste Suche hilft mir sehr!

**Comment by PietroLiuzzo** [comment]
to fix the search results I have limited in the xpath the considered mss to those where measure is given as an integer only, this reduces the results, but is at least true. a more precise result can be achieved with the filtering of actual values in the facet search.

**Comment by SusanneHummel** [comment]
Perfect. Thank you!
