### ISSUE TITLE
text language visualization

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1428]
When we have `<q xml:lang="gez"/>`
This is correctly visualized as "Text in Gǝʿǝz"
What about other language codes?
(cp. https://betamasaheft.eu/manuscripts/ESam007/main additio 1)

**Comment by PietroLiuzzo** [comment]
you have to declare the [language](https://betamasaheft.eu/Guidelines/?id=language)s in `langUsage`. in this file you only have
```xml
<langUsage>
<language ident="en">English</language>
<language ident="gez">Gǝʿǝz</language>
</langUsage>
```

**Comment by eu-genia** [comment]
thank you
