### ISSUE TITLE
Prayer of St Peter

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1430]
I have a work in on EMIP record called Prayer of Saint Peter, ጸሎተ፡ ጴጥሮስ፡.

I don't seem to be able to find a work file for this. Am I missing something, or should a new file be created? I can prov

**Comment by thea-m** [comment]
Hi! Judging from incipits of the textparts, it seems to be this work: LIT4668Prayer, attested in BAVet92 and RNBspbdaBIII16. A cursory look at it makes gives to me the impression that the title "Prayer of St Peter" only refers to the first textpart.

**Comment by Ralph-Lee-UK** [comment]
Thanks for this, I have corrected several other references that share the same incipit, and indeed they are usually accompanied by a collection of disciples' prayers, as in BAVet92
