### ISSUE TITLE
ID error

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1431]
https://betamasaheft.eu/manuscripts/EMIP00412/main

The same ID (412) has been used in EMIP00412 and EMIP00413, also throughout the shelfmarks and facs links, which makes me know unsure whether substituting the 2 by 3 in EMIP00413 can be done by me without knowing the records well. Could you correct it? Thank you!

**Comment by Ralph-Lee-UK** [comment]
This is a coding error. 412 is correct. I will edit 413 just now - it is also a psalter, but it is not the same manuscript at all! Apologies for this, and thanks for spotting it.

**Comment by Ralph-Lee-UK** [comment]
This is complete now, and the new file will appear when I make our weekly pull request next Wenesday

**Comment by thea-m** [comment]
Thank you!
