### ISSUE TITLE
complete text instead of incipit/explicit

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1432]
We are looking for way to encode (for our catalogue) the complete text of a short work instead of its incipit and explicit for msItems. This is in cases where the text is so short that giving its incipit and explicit would cover it entirely. (encoding with `<incipit>` and `<explicit>` would give the erroneous impression that there is more text)
It would be logical to transcribe the text in a `<div>` in the body. Our issue is that we would like this transcription to appear in the catalogue (and the app later) in the same place as incipits and explicits of longer texts, which is where readers will expect it (so a differentiation from other texts potentially given in divs would be needed). 
What would you suggest, @PietroLiuzzo ?
@SusanneHummel @MassimoVilla @Gnisci

**Comment by PietroLiuzzo** [comment]
this simply goes in the text, in a div which you may connect directly to your msItem. If it simple transcription, not an edited or drafted text then please do this in the manuscript record and add appropriate structure to the div[@type='edition']
The position in which it should be displayed can be managed, that is no problem, especially now that a lot of the text display issues are restructured and made much more flexible. #1309   
I will transform this issue in one of simple visualization as it is. On the users expectations I would not bet without a proper survey, but it is enough that it is your requirement.

**Comment by PietroLiuzzo** [comment]
BTW, I would also give some consideration to long incipits and explicit, even when they are not the entirety of the text, but are simply lengthy.

**Comment by thea-m** [comment]
Good, should we mark this up in any particular way to differentiate from other divs?

**Comment by PietroLiuzzo** [comment]
no, place the text in the correct folio div, with pb, cb, eventually lb and use locus to refer to them.
you will now be able to use notations like 1ra1 or 1.1 to point to a specific line on a folio, and use this notation in target, from and to inside locus

**Comment by PietroLiuzzo** [comment]
of course you can have a div with subtype incipit, but I would not consider it really necessary.

**Comment by PietroLiuzzo** [comment]
#1309

**Comment by thea-m** [comment]
Thank you!
