### ISSUE TITLE
Song of Songs works record

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1433]
I have been discussing with Steve Delamarter about the nature of the text of Song of Songs. From quite extensive research that he has done, there are clearly three versions of this text, which partly reflect the three different works that this text is found in - biblical manuscripts, Psalters, and the Gabra Hemamat. Some versions, for instance, follow more the Hebrew version of the text, and other the Greek. As it stands this data is unpublished, although we are currently working on a volume that will publish this data. It strikes me that this sort of information could be included as 'forthcoming information' within the works record for this text. Steve would be happy to provide a summary of the findings that will be published. What do you think?

**Comment by thea-m** [comment]
Hi! Thank you for thinking about this. Yes, it would of course be absolutely valuable information that would also affect the encoding choices for this work (putting in question the use of one work record for these different recensions). We would be happy to make this information available, and a summary of any detail as you deem useful would be very welcome!
