### ISSUE TITLE
Line breaks for notes

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1434]
`<note>` elements like `<ab>` and `<p>` etc. should better be a separate paragraph (new line)
otherwise we have cases like e.g. 
https://betamasaheft.eu/works/LIT2050Nagara/text
with no line break between a note and the div label
![image](https://user-images.githubusercontent.com/17987728/84995162-f6d46680-b14b-11ea-830e-e5d82be5c530.png)

**Comment by PietroLiuzzo** [comment]
this is context dependent. I have changed `note` to be a paragraph when output as HTML in the same context of encoding and presentation in which it appears in the provided example.

**Comment by eu-genia** [comment]
at least for me there is still no line break between the note and the label

**Comment by PietroLiuzzo** [comment]
no, it will not be live until the rest of the release is done.
