### ISSUE TITLE
Encoding an unstable collection

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1437]
As this is my first post I want to welcome everybody and thankthe project coordinators for including me. My issue concerns a proper way to encode BL Orient. 786=Wright 343.

This is a Retu'a Haymanot homiliary for varous occasions mostly connected with Christ's passion. I have analyzed all the mss. of this collection and it seems that while most texts appear in more than one manuscript only two of them appear in ALL mss. 

There is a stub Lit2222RetuaH which I was hoping to expand but the question is, which homilies should be inluded as forming part of this collection.

Thank you very much in advance for sharing your opinions! @DenisNosnitsin1970 @Ralph-Lee-UK

**Comment by DenisNosnitsin1970** [comment]
I think you should encode each homily as a separate work, and create ID for a collection only if you have found that it is a kind of stable composition, attested in more than one manuscript. It does not matter that the homilies are ascribed to the same author. You can see how the homiliaries are treated in the DB, or also look how the authors are treated known for their homilies (e.g. John Chrysostom).

**Comment by Ralph-Lee-UK** [comment]
This seems an appropriate cautious approach. I wonder whether we could, however, add something along the same lines that we did for the commentary on various texts? Here we have created a broad category of 'commentary on the Gospels' and suchlike, with a view to clarifying what this means following future research. Could we create an RH 'work' which at first points only to the possible connections between these homilies?

**Comment by DenisNosnitsin1970** [comment]
If the homilies are encoded as works in the correct way they are interlinked with RH, and the relationship can be visualised accordingly; key word "homily" exists and is actively in use. What kind of category are you thinking of?
