### ISSUE TITLE
date of the "Era of the Martyrs" in FSUor13

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1439]
Note: the date of the "Era of the Martyrs" in FSUor13 is obviously wrong: it cannot be "በ፲፻ወ፪፻፺ወ፷ እምዓመተ፡ ሰማዕታት፡" and the "፷" (60) must be probably emended to "፰" (8): please, check if this is an error of the catalogue, in the MS, or by BM.

_Originally posted by @abausi in https://github.com/BetaMasaheft/Documentation/issues/1438#issuecomment-647407209_

**Comment by DenisNosnitsin1970** [comment]
Indeed! This is a typographic imperfection in the catalogue, I will correct it.

**Comment by thea-m** [comment]
thank you!
