### ISSUE TITLE
Wrong person IDs for Takla Haymanot in EMIP MSS

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1442]
Dear @Ralph-Lee-UK , @jonahsandford , @Ashlee-Benson 

I see that the ID PRS11112TaklaH was used in many EMIP descriptions to mark up Saint Takla Haymanot  (e g EMIP00162, EMIP00412, EMIP00370, EMIP00415, EMIP00454, EMIP00487, EMIP02046, EMIP03274 etc.) The ID belongs however to the owner of MS BLadd11622

ID PRS11084TaklaHa was used in EMIP00073, but this ID belongs to the owner of MS BLadd16217

ID PRS9150TaklaHa was used in EMIP00028, EMIP00006, EMIP00009, EMIP00063 - but this ID belongs to the Abbot of May Anbasa

**Saint Takla Haymanot has ID PRS9162TaklaHa** 

Please correct all these and possible other references to Saint Takla Haymanot in EMIP to PRS9162TaklaHa.

____

Tasfa Giyorgis Abbot of DL is PRS11205TasfaG (not PRS9272TasfaGi as in EMIP00006)

Saint Ewostatewos is PRS3934Ewostate (not PRS10959Ewostatewos as in EMIP00073 EMIP02046 or PRS3915Eustathi as in EMIP00036 etc.)

Thank you!

**Comment by eu-genia** [comment]
UPDATE: I have now corrected what I found 
https://github.com/BetaMasaheft/Manuscripts/pull/634

Would be great if you could keep the correct IDs for your records

**Comment by Ralph-Lee-UK** [comment]
I'll get on with these as soon as possible. @Ashlee-Benson, I will code these and also update the spreadsheet with the correct information.

**Comment by eu-genia** [comment]
Dear Ralph, for now the records have been fixed, just keep this in mind for the future, also that we do not have `<name>` tag, only `<persName>` `<placeName>` etc. Thank you so much!

**Comment by Ralph-Lee-UK** [comment]
Will do!
