### ISSUE TITLE
Coding 20th Century Pamphlets

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1446]
From the EMIP project we have a set of images of pamphlets printed on paper that were produced in Haile Sellassie's reign. They are very wide in their content, but many are written by important scholars from that period. 

Titles include 

እነሆ አጫጭር ልቦለዶች
ምን ይሉኝ
ኅብረ አምሳል (አማርኛ ቅኔ)
እኔስ ስው አልሆንም
ሰጲራ
የይስማኤል ቍጥቋጦ
እሱንተይው!!

Just wondering what to do with this set of images, and encoding them. Should we create work files for each of them? Or is there a more suitable way to encode each of these? Any advice most welcome! A sample of title pages is attached
![EMIP02446_KaleabAddisDealers158_001](https://user-images.githubusercontent.com/39619238/86579085-bad73900-bf74-11ea-8ff8-a8e796aa3174.jpg)
![EMIP02445_KaleabAddisDealers157_001](https://user-images.githubusercontent.com/39619238/86579101-bf9bed00-bf74-11ea-8beb-4b840fd318c1.jpg)
![EMIP02444_KaleabAddisDealers156_001](https://user-images.githubusercontent.com/39619238/86579119-c460a100-bf74-11ea-89d1-3ab8ea0e248e.jpg)
![EMIP02450_KaleabAddisDealers162_001](https://user-images.githubusercontent.com/39619238/86579125-c7f42800-bf74-11ea-9af8-273fcf90330c.jpg)
![EMIP02449_KaleabAddisDealers161_001](https://user-images.githubusercontent.com/39619238/86579136-ccb8dc00-bf74-11ea-90cf-90e99c9e605f.jpg)

![EMIP02447_KaleabAddisDealers159_001](https://user-images.githubusercontent.com/39619238/86579060-b4e15800-bf74-11ea-8dd6-956cde26ba9f.jpg)

![EMIP02448_KaleabAddisDealers160_001](https://user-images.githubusercontent.com/39619238/86579050-af840d80-bf74-11ea-9820-e7b066c65968.jpg)

**Comment by thea-m** [comment]
@PietroLiuzzo what do you think?

**Comment by eu-genia** [comment]
Well this is outside of BM scope but in principle I would have nothing against encoding books parallel to MSS if that is an individual project's need (among the records inherited from IHA there are also a lot of books, though unfortunately they forgot to mark it in the data ;))

**Comment by Ralph-Lee-UK** [comment]
I did wonder about this. I think that the books are valuable, they are written in many cases by leading scholars of their era, and so having them widely accessible through BM would be valuable. Perhaps @PietroLiuzzo can guide us here?

**Comment by DenisNosnitsin1970** [comment]
I think it is fine if it is an individual case, but if there is more of this stuff (very interesting and valuable), a special scheme for description of old prints/incunabulas would probably be necessary.

**Comment by thea-m** [comment]
For sure they are interesting, and since available to a project using the digital research environment, I see no reason why they should not be incorporated. But since our guidelines were developed mainly for manuscript descriptions, here it would be useful for Pietro to advise you.

**Comment by PietroLiuzzo** [comment]
A set of images will need in bm a manuscript record, where you will use [`<objectDesc form='Book'/>`](https://betamasaheft.eu/Guidelines/?id=objectDesc). Please also note the supported use of [`<measure unit="page">`](https://betamasaheft.eu/Guidelines/?q=paginated&id=referencing-the-manuscript).
I do not know what the content looks like, but I would assume that _one_ work record for each textual unit would suffice, without need to split down to the parts at all and without writing down any incipit etc.. the text would belong to the work record. I am quite sure there are many ways in which these materials will relate to the data in BM, thanks!

**Comment by Ralph-Lee-UK** [comment]
That makes sense to me, @PietroLiuzzo. I will create the work record for each textual unit, as you suggest, with the information at the start of the pamphlet. This will probably be very brief, but as the records will be attached to images, this will probably be sufficient. When I have created a few work records, I'll make a pull request, and ask you to check them. Many thanks again!
