### ISSUE TITLE
new record creation BLorient539

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1447]
I would like to create new records for these two prayers:
![image](https://user-images.githubusercontent.com/19650382/86782228-239ae000-c05f-11ea-911c-f2eb8a8d79c1.png)

https://archive.org/details/catalogueofethio00brituoft/page/78/mode/2up

Any objections?
@DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I have nothing against :)
