### ISSUE TITLE
potential improvements to Collatex

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1449]
In case you might work on Collatex again (maybe when more than one person uses it?), there would be a few points that would make it even more useful (for me):
- if homophones (the usual ones, I think you must have the list?) and different punctuation signs would not be treated as significant variants
- if some mark up in the records would be visualised. I realise that this might be a very individual preference. I have for example a lot of `<gap>`s in my records, it would be practical to see them somehow in the table. Any visualisation would be fine for me ([...] or HERE IS A GAP, the ones the app uses or whatever) . Similarily, a visualisation of  `<supplied>` could be useful for me (how is not important to me, <> or however).

(And only due to the laziness of me working mainly with narrative units in this feature: It could be nice to chose the manuscripts from the automatic table of all manuscripts to be collated. I completely realise that I can type in the individual manuscripts that I want with their pbs etc. and will get the desired result).

It is already very useful how it is!

**Comment by PietroLiuzzo** [comment]
the homophones here have to be handled by collatex, which we use "out of the box", I have no understanding of how to play with it to do that. I will try and look into it.
for the mark up: I pass to collatex a string which takes text nodes (`yourselection//text()`), I could pass to it instead the result of the transformation text nodes,  `yourselection//text()` --> transform to HTML --> take //text(). this will collate all your brackets as well. I am not sure how this would be useful. you could have a go copypasing the text from the /text view into the demo collatex and seeing if the results given there are any better. I could match the results back to the text and try to transform that, but it sounds rather unreliable, i.e. how do I go back from the token of result by collatex to  relevant portion of the encoded text?
on "chose the manuscripts from the automatic table"... which one? where? we can certainly add more collation links, but I am not sure which table of manuscripts you mean and what behaviour you would expect

**Comment by thea-m** [comment]
Thank you!
On the last point, sorry for being unclear. I just meant this table:

![image](https://user-images.githubusercontent.com/19650382/86896471-4cc27b80-c106-11ea-860f-fed8c1033406.png)

Now, for me the number of manuscripts is still limited, and can be well handled, but I imagine that it could be useful to be able to "ignore" any of them to only collate two or three. But again, I get that I can just add the individual IDs and passages.

**Comment by thea-m** [comment]
I had tried the collatex demo previously, and tried again now. The collation itself seems fine, but if is very difficult to copy the result and bring them in a form that I can work with, if I have to go on to manually delete each bracket.
![image](https://user-images.githubusercontent.com/19650382/86896977-1b967b00-c107-11ea-92ae-83f3ad2de60d.png)

I am not interested in all the markup (rubrication, personal names, dates...), only the gaps are really significant for the collation.
I anyway copy the table and edit it manually. It would just be practical to see immediately the places where there are gaps instead of comparing with the records, but it's also fine like this, if this is a complicated thing, don't waste too much time.

**Comment by thea-m** [comment]
It would also be helpful for me if the `<lb>`s from Transkribus transcriptions would not be taken into consideration by Collatex. For example
![image](https://user-images.githubusercontent.com/19650382/102779288-419d9800-4394-11eb-8ba6-940ea2afbc4f.png)
is from
```
<lb facs="#facs_1_r2l11" n="10"/>ስ፡ ወሰአለ፡ ኀበ፡ እግዚአብሔር፡ ይሕድጎ፡ እም
<lb facs="#facs_1_r2l12" n="11"/>ኔሁ፡ ወእምነ፡ ውሉዱ፡ ወተጸመሞ፡ በእንተ፡ 
```
(EMML4398)
The actual hindrance of this for me is not very big (homophones and punctuation are maybe more important), and probably does not outweight the great help of both transkribus and collatex, but it is still an extra step to be carried out. As the information on line breaks is not really important for my work now, I am somewhat tempted to delete them to avoid this, and this of course would be a pity. Any thoughts?

**Comment by thea-m** [comment]
(Ah, I don't know whether the issue here is actually the `<lb>`s or the space in the file?)

**Comment by PietroLiuzzo** [comment]
could you please give me the exact reference of the passages you are trying to collate?

**Comment by thea-m** [comment]
NAR0133SenJob

**Comment by PietroLiuzzo** [comment]
so, is the problem here that the collation is "interrupted" more than necessary? there are no lb in the text passed to collatex

**Comment by PietroLiuzzo** [comment]
also the space is normalized before sending to collatex.

**Comment by thea-m** [comment]
The problem for me is 1) that collatex doesn't recognise እምኔሁ and እም ኔሁ as identical and 2) that I have to delete all these spaces when I copy the text, but that's my problem as no one forces me to copy this text :)
So, exactly the same issue as with homophones and punctuation: it would save time if they were recognized by collatex. Is the solution to delete the space preceding `<lb>`s in the files then?

**Comment by thea-m** [comment]
(If the space is normalised, I don't understand why it's still there?) Thank you!

**Comment by PietroLiuzzo** [comment]
I now understood. the issue is that the lb is not classified as beeing part or not of a word. 
it should be actually
`እም<lb break="no" facs="#facs_1_r2l12" n="11"/>ኔሁ፡` 
I am thinking how this can be fixed for collatex, I think it is not a great issue, but one that should have come up earlier, sorry about that

**Comment by thea-m** [comment]
should I add now `break="no"` to the concerned files that I'm working with?

**Comment by PietroLiuzzo** [comment]
I will 
- add a transformation step in the collatex script to remove them all mechanically
- update the transformation from transkribus to add the attribute break=no when there is no word separator before lb.
so you do not have to do anything of this sort manually.

**Comment by thea-m** [comment]
Thank you!

**Comment by PietroLiuzzo** [comment]
as I am at it now, I will do also the above. I will add string visualization of 
- gap as []
- lb as above, so nothing or a space if a separator is present
- supplied as <>
- subst as ''
- del as #
- choice will print corr only
please add to this list if anything else should be considered

**Comment by thea-m** [comment]
Thank you, that's great! Nothing else. For choice, could you instead print sic only?

**Comment by PietroLiuzzo** [comment]
ok

**Comment by PietroLiuzzo** [comment]
The collatex behaviour when calling Narrative units is now the following.
the text is retrieved, e.g,

```xml
<div xmlns="http://www.tei-c.org/ns/1.0" type="textpart" subtype="commemoration" corresp="NAR0133SenJob" xml:lang="gez" n="1"> <ab> <hi rend="rubric">አመ፡ </hi> <date ref="ethiocal:Genbot2"> <hi rend="rubric">፪እ</hi> <lb facs="#facs_1_r2l5" n="4"/>ምነ፡ ወርኀ፡ ግንቦት፡</date> በከመ፡ ኮነት፡ ይእቲ፡ ዕለት፡ <lb facs="#facs_1_r2l6" n="5"/> <hi rend="rubric">አዕረፈ፡ ኢዮብ፡ ጻድቁ፡ ዝንቱሰ፡ ኮነ፡ ንጹሐ፡ ው</hi> <lb facs="#facs_1_r2l7" n="6"/>ስተ፡ ትውከልቱ፡ ወጻድቅ፡ ውስተ፡ ማዓልቱ፡ <lb facs="#facs_1_r2l8" n="7"/>በከመ፡ <sic resp="DR">ሰ</sic>ምዐ፡ ኮነ፡ አብ፡ በእንቲአሁ፡ ውስተ፡ <lb facs="#facs_1_r2l9" n="8"/>መጻሕፍቲሁ፡ ከመ፡ ውእቱ፡ ኢይከውን፡ <hi rend="rubric">፩</hi>አመ <lb facs="#facs_1_r2l10" n="9"/>ማዕልቱ፡ ንጹሕ፡ ከማሁ፡ ወአመከሮ፡ ዲያብሎ <lb facs="#facs_1_r2l11" n="10"/>ስ፡ ወሰአለ፡ ኀበ፡ እግዚአብሔር፡ ይሕድጎ፡ እም <lb facs="#facs_1_r2l12" n="11"/>ኔሁ፡ ወእምነ፡ ውሉዱ፡ ወተጸመሞ፡ በእንተ፡ <lb facs="#facs_1_r2l13" n="12"/>አእምሮተ፡ ትእግሥቱ፡ ጻድቅ፡ ወውእቱ፡ ይከ <lb facs="#facs_1_r2l14" n="13"/>ውን፡ ምስሌነ፡ ወፍካሬ፡ ለኵሉ፡ ዘ<gap reason="illegible"/>ጽሐ፡ <lb facs="#facs_1_r2l15" n="14"/>እምኔሁ፡ በከመ፡ ይቤ፡ መጽሐፍ፡ ናሁ፡ ሰማዕ <lb facs="#facs_1_r2l16" n="15"/>ክሙ፡ ትእግስቶ፡ ለኢዮብ፡ ወርኢክሙ፡ ደሐ <lb facs="#facs_1_r2l17" n="16"/>ሪ፡ በዘገብረ፡ እግዚአብሔር፡ ምስሌሁ፡ በእንተ፡ <lb facs="#facs_1_r2l18" n="17"/>አመ፡ ዕለተ፡ አሐዱ፡ ሐጕለ፡ ውሉዶ፡ ወወለቶ <lb facs="#facs_1_r2l19" n="18"/>ወጥሪቶ፡ ወኵሎን፡ ንዋዮ፡ ሃሎ፡ ከመዝ፡ ግሙራ፡ <lb facs="#facs_1_r2l20" n="19"/>ዳእሙ፡ ወእስከ፡ ፀላኢ፡ እስመ፡ ሥጋሁ፡ እስመ፡ <lb facs="#facs_1_r2l21" n="20"/>ጸላኢ፡ ዘበጦ፡ ሎቱ፡ ዝብጠተ፡ <gap reason="illegible"/>ልጋሴ፡ እም <lb facs="#facs_1_r2l22" n="21"/>ነ፡ ርእሱ፡ እስከ፡ መከይዱ፡ ወኮነ፡ በውስተ፡ ዝ <lb facs="#facs_1_r2l23" n="22"/>ንቱ፡ ኵሎ፡ ያአኵቶ፡ ለእግዚአብሔር፡ ወኢ፡ <lb facs="#facs_1_r2l24" n="23"/>ስሕተ፡ ዕለተ፡ ግሙራ፡ ወኢ፡ አበሰ፡ ላዕለ፡ ፈጣ <lb facs="#facs_1_r2l25" n="24"/>ሪሁ<hi rend="rubric">፨</hi> ዳእሙ፡ ዘንተ፡ ሐደገ፡ ዘይቤ፡ ዳእሙ፡ ሐ <lb facs="#facs_1_r2l26" n="25"/>ደጋ፡ ለዕለት፡ ዘተወል<sic resp="DR">፡ </sic>ደ፡ ባቲ፡ ወኮነ፡ ይብ<gap reason="illegible"/> <lb facs="#facs_1_r2l27" n="26"/>አመ፡ ኃጥእ፡ ንዋዮ፡ እግዚአብሔር፡ ወ<gap reason="illegible"/>፡ ወ <lb facs="#facs_1_r2l28" n="27"/>እግዚአብሔር፡ ነሥኦ፡ ግዱፈ፡ ላዕለ፡ አ<gap reason="illegible"/> <lb facs="#facs_1_r2l29" n="28"/>ወተወሰከ፡ በዘኮነ፡ ላዕሌሁ፡ ገስጾተ፡ ፍ<gap reason="illegible"/> <pb facs="#facs_2" n="67v"/> <cb facs="#facs_2_r3" n="a"/> <lb facs="#facs_2_r3l1" n="1"/>ኒሁ፡ ዘ<hi rend="rubric">፫</hi>ወብእሲቱ<sic resp="DR">፡ </sic>ኒ፡ ከማሁ፡ ለሊሃ፡ አበከረቶ፡ <lb facs="#facs_2_r3l2" n="2"/>ሎቱ፡ በአብሰ፡ ወኢ<sic resp="DR">፡ </sic>ቲሰጥዋ፡ ወመማከረ፡ በከ <lb facs="#facs_2_r3l3" n="3"/>መ፡ ያሜከርዎ፡ ለውርቅ፡ ውስቱ፡ ምንሃብ<hi rend="rubric">፨</hi> <lb facs="#facs_2_r3l4" n="4"/>ወናገሮ፡ እምነ፡ ዳመናት፡ እግዚእ፡ ወፈወሶ፡ <lb facs="#facs_2_r3l5" n="5"/>እምደዌሁ፡ ወአካዕበተ፡ ኵሎ፡ ዘኮነ፡ ሎቱ፡ <lb facs="#facs_2_r3l6" n="6"/>ወወለደ፡ ካዕበ፡ ውሉደ፡ ወሐይወ፡ በርስእና፡ <lb facs="#facs_2_r3l7" n="7"/>ሠናይ፡ ካዕበ፡ አዕረፈ፡ በሰላም፡ <seg type="supplication">ጸሎቱ፡ የሃ <lb facs="#facs_2_r3l8" n="8"/> <add place="overstrike">ሎ፡ ምስለ፡ ፍቁሩ፡ ክርስቶስ፡ አሜን።</add> </seg> </ab> </div>

```

than it is transformed to with a new xslt into 

```xml
<div xmlns="http://www.tei-c.org/ns/1.0" type="textpart" subtype="commemoration" corresp="NAR0133SenJob" xml:lang="gez" n="1"> <ab> አመ፡ ፪እምነ፡ ወርኀ፡ ግንቦት፡ በከመ፡ ኮነት፡ ይእቲ፡ ዕለት፡ አዕረፈ፡ ኢዮብ፡ ጻድቁ፡ ዝንቱሰ፡ ኮነ፡ ንጹሐ፡ ውስተ፡ ትውከልቱ፡ ወጻድቅ፡ ውስተ፡ ማዓልቱ፡ በከመ፡ ሰምዐ፡ ኮነ፡ አብ፡ በእንቲአሁ፡ ውስተ፡ መጻሕፍቲሁ፡ ከመ፡ ውእቱ፡ ኢይከውን፡ ፩አመማዕልቱ፡ ንጹሕ፡ ከማሁ፡ ወአመከሮ፡ ዲያብሎስ፡ ወሰአለ፡ ኀበ፡ እግዚአብሔር፡ ይሕድጎ፡ እምኔሁ፡ ወእምነ፡ ውሉዱ፡ ወተጸመሞ፡ በእንተ፡ አእምሮተ፡ ትእግሥቱ፡ ጻድቅ፡ ወውእቱ፡ ይከውን፡ ምስሌነ፡ ወፍካሬ፡ ለኵሉ፡ ዘ[illegible]ጽሐ፡ እምኔሁ፡ በከመ፡ ይቤ፡ መጽሐፍ፡ ናሁ፡ ሰማዕክሙ፡ ትእግስቶ፡ ለኢዮብ፡ ወርኢክሙ፡ ደሐሪ፡ በዘገብረ፡ እግዚአብሔር፡ ምስሌሁ፡ በእንተ፡ አመ፡ ዕለተ፡ አሐዱ፡ ሐጕለ፡ ውሉዶ፡ ወወለቶወጥሪቶ፡ ወኵሎን፡ ንዋዮ፡ ሃሎ፡ ከመዝ፡ ግሙራ፡ ዳእሙ፡ ወእስከ፡ ፀላኢ፡ እስመ፡ ሥጋሁ፡ እስመ፡ ጸላኢ፡ ዘበጦ፡ ሎቱ፡ ዝብጠተ፡ [illegible]ልጋሴ፡ እምነ፡ ርእሱ፡ እስከ፡ መከይዱ፡ ወኮነ፡ በውስተ፡ ዝንቱ፡ ኵሎ፡ ያአኵቶ፡ ለእግዚአብሔር፡ ወኢ፡ ስሕተ፡ ዕለተ፡ ግሙራ፡ ወኢ፡ አበሰ፡ ላዕለ፡ ፈጣሪሁ፨ ዳእሙ፡ ዘንተ፡ ሐደገ፡ ዘይቤ፡ ዳእሙ፡ ሐደጋ፡ ለዕለት፡ ዘተወል፡ ደ፡ ባቲ፡ ወኮነ፡ ይብ[illegible]አመ፡ ኃጥእ፡ ንዋዮ፡ እግዚአብሔር፡ ወ[illegible]፡ ወእግዚአብሔር፡ ነሥኦ፡ ግዱፈ፡ ላዕለ፡ አ[illegible]ወተወሰከ፡ በዘኮነ፡ ላዕሌሁ፡ ገስጾተ፡ ፍ[illegible] ኒሁ፡ ዘ፫ወብእሲቱ፡ ኒ፡ ከማሁ፡ ለሊሃ፡ አበከረቶ፡ ሎቱ፡ በአብሰ፡ ወኢ፡ ቲሰጥዋ፡ ወመማከረ፡ በከመ፡ ያሜከርዎ፡ ለውርቅ፡ ውስቱ፡ ምንሃብ፨ወናገሮ፡ እምነ፡ ዳመናት፡ እግዚእ፡ ወፈወሶ፡ እምደዌሁ፡ ወአካዕበተ፡ ኵሎ፡ ዘኮነ፡ ሎቱ፡ ወወለደ፡ ካዕበ፡ ውሉደ፡ ወሐይወ፡ በርስእና፡ ሠናይ፡ ካዕበ፡ አዕረፈ፡ በሰላም፡ ጸሎቱ፡ የሃ{ሎ፡ ምስለ፡ ፍቁሩ፡ ክርስቶስ፡ አሜን።} </ab> </div>
```
then normalized for 

> አመ፡ ፪እምነ፡ ወርኀ፡ ግንቦት፡ በከመ፡ ኮነት፡ ይእቲ፡ ዕለት፡ አዕረፈ፡ ኢዮብ፡ ጻድቁ፡ ዝንቱሰ፡ ኮነ፡ ንጹሐ፡ ውስተ፡ ትውከልቱ፡ ወጻድቅ፡ ውስተ፡ ማዓልቱ፡ በከመ፡ ሰምዐ፡ ኮነ፡ አብ፡ በእንቲአሁ፡ ውስተ፡ መጻሕፍቲሁ፡ ከመ፡ ውእቱ፡ ኢይከውን፡ ፩አመማዕልቱ፡ ንጹሕ፡ ከማሁ፡ ወአመከሮ፡ ዲያብሎስ፡ ወሰአለ፡ ኀበ፡ እግዚአብሔር፡ ይሕድጎ፡ እምኔሁ፡ ወእምነ፡ ውሉዱ፡ ወተጸመሞ፡ በእንተ፡ አእምሮተ፡ ትእግሥቱ፡ ጻድቅ፡ ወውእቱ፡ ይከውን፡ ምስሌነ፡ ወፍካሬ፡ ለኵሉ፡ ዘ[illegible]ጽሐ፡ እምኔሁ፡ በከመ፡ ይቤ፡ መጽሐፍ፡ ናሁ፡ ሰማዕክሙ፡ ትእግስቶ፡ ለኢዮብ፡ ወርኢክሙ፡ ደሐሪ፡ በዘገብረ፡ እግዚአብሔር፡ ምስሌሁ፡ በእንተ፡ አመ፡ ዕለተ፡ አሐዱ፡ ሐጕለ፡ ውሉዶ፡ ወወለቶወጥሪቶ፡ ወኵሎን፡ ንዋዮ፡ ሃሎ፡ ከመዝ፡ ግሙራ፡ ዳእሙ፡ ወእስከ፡ ፀላኢ፡ እስመ፡ ሥጋሁ፡ እስመ፡ ጸላኢ፡ ዘበጦ፡ ሎቱ፡ ዝብጠተ፡ [illegible]ልጋሴ፡ እምነ፡ ርእሱ፡ እስከ፡ መከይዱ፡ ወኮነ፡ በውስተ፡ ዝንቱ፡ ኵሎ፡ ያአኵቶ፡ ለእግዚአብሔር፡ ወኢ፡ ስሕተ፡ ዕለተ፡ ግሙራ፡ ወኢ፡ አበሰ፡ ላዕለ፡ ፈጣሪሁ፨ ዳእሙ፡ ዘንተ፡ ሐደገ፡ ዘይቤ፡ ዳእሙ፡ ሐደጋ፡ ለዕለት፡ ዘተወል፡ ደ፡ ባቲ፡ ወኮነ፡ ይብ[illegible]አመ፡ ኃጥእ፡ ንዋዮ፡ እግዚአብሔር፡ ወ[illegible]፡ ወእግዚአብሔር፡ ነሥኦ፡ ግዱፈ፡ ላዕለ፡ አ[illegible]ወተወሰከ፡ በዘኮነ፡ ላዕሌሁ፡ ገስጾተ፡ ፍ[illegible] ኒሁ፡ ዘ፫ወብእሲቱ፡ ኒ፡ ከማሁ፡ ለሊሃ፡ አበከረቶ፡ ሎቱ፡ በአብሰ፡ ወኢ፡ ቲሰጥዋ፡ ወመማከረ፡ በከመ፡ ያሜከርዎ፡ ለውርቅ፡ ውስቱ፡ ምንሃብ፨ወናገሮ፡ እምነ፡ ዳመናት፡ እግዚእ፡ ወፈወሶ፡ እምደዌሁ፡ ወአካዕበተ፡ ኵሎ፡ ዘኮነ፡ ሎቱ፡ ወወለደ፡ ካዕበ፡ ውሉደ፡ ወሐይወ፡ በርስእና፡ ሠናይ፡ ካዕበ፡ አዕረፈ፡ በሰላም፡ ጸሎቱ፡ የሃ{ሎ፡ ምስለ፡ ፍቁሩ፡ ክርስቶስ፡ አሜን።}

and this is the text which is passed to collatex.
now, it looks to me like this is now actually correct, but I hope it is better for this purpose given the current markup, and avoids you some manual work at least

**Comment by PietroLiuzzo** [comment]
Please, if you try it let me know what needs changes

**Comment by thea-m** [comment]
Thank you! It looks to me now as described by you here. It will save me a lot of time!
The homophones and punctuation issue seem to be not solvable, should this point maybe be moved to discussions for a potential future miracle, so that this issue can be closed?

**Comment by PietroLiuzzo** [comment]
if you could expand on the miracles I would appreciate. the fact that I have done this does not mean that other things cannot be done, only that I got this far.

**Comment by PietroLiuzzo** [comment]
homophones can be normalized, you need to tell me by which rules.
punctuation can be entirely removed.

**Comment by thea-m** [comment]
This is what I wrote in the first comment of this issue:

> if homophones (the usual ones, I think you must have the list?) and different punctuation signs would not be treated as significant variants

I was not aware that it was unclear.  

For me, the most useful would be if homophones and punctuation signs would be displayed without normalisation as they are in the manuscripts, but not treated as variants, i.e. ኃይለ፡ and ሀይለ፨ would be marked as identical. If this is not possible without normalisation, I'll prefer for them to be displayed in the way they are now, even if they will be treated as significant variants. 
As you know, these are only my personal preferences, in case other people are also using this resource, they might have a different opinion.

**Comment by PietroLiuzzo** [comment]
there are no other users at the moment. the unclear part is what this normalisation should look like. We can replace ኃ with ሀ in the text which is passed to collatex for example and remove both ፡ and ፨ so the strings will be identical and treated as such. However to do this you have to decide on a list of replacements and I can add them to the script.

**Comment by thea-m** [comment]
Thank you! As I wrote, I would prefer no such normalisation to take place and will continue to live then with the homophones and punctuation signs to be treated as variants.

**Comment by PietroLiuzzo** [comment]
text of this ms includes output with break='no' from new transkribus2BM.xsl script https://github.com/BetaMasaheft/Manuscripts/pull/978
