### ISSUE TITLE
Search for female scribes, patrons and owners

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1450]
Dear Pietro,

would it be possible to check whether there is a femal scribe among the 1262 scribes contained in the BM database?
https://betamasaheft.eu/facet.html?query=scribe#

In the authority files, the sex could be assigned, so I thought it should be possible to filter the female scribes (if there are at all). 
I would like to do the same search for persones with the role "patron" or "owner".

Thank you!

Best,
Sanne

**Comment by thea-m** [comment]
(On the gender assignment issue: In the records transformed from the EAE, gender was apparently (?) assigned manually, and there were quite a few mistakes. Those we noticed we corrected, but there probably are still several. But this should not dramatically affect these queries, which usually give results of persons created by BM, where there is hopefully not the same problem, because there is no need to assign a gender if it is not known.)

**Comment by PietroLiuzzo** [comment]
please let me know if I should expand this to be a view or part of functionality of some sort in the app.

**Comment by SusanneHummel** [comment]
I found the search example for femal donors in the help menue under SPARQL Endpoint. However, I have to admit that wouldn't have been able to adjust this one to a search for femal scribes. Ther
Also, I was not able to reproduce the wonderful list you presented above (with all females in different roles mentioned in mss). 
Therefore for me it would be extremely helpful to have some sort of functionality related to search for females in the app.
Thank you!

**Comment by PietroLiuzzo** [comment]
Super, how would envisage it? a simple dedicated page, like "gender and manuscripts" with static queries as above and graphic representations of the results? would that be a good starting point? thanks!

**Comment by thea-m** [comment]
I think that would be good!

**Comment by SusanneHummel** [comment]
Sonds wonderful to me, too. Thank you!

**Comment by PietroLiuzzo** [comment]
you can now see this page here
https://betamasaheft.eu/gender

**Comment by PietroLiuzzo** [comment]
related pages include the table, with some changes to content and formatting, which is linked in the page above as charts and graph. It is just a starting point, open a new issue please for more requirement on this new resource.

**Comment by PietroLiuzzo** [comment]
<img width="1675" alt="Schermata 2020-08-12 alle 11 30 27" src="https://user-images.githubusercontent.com/508012/89999575-40928680-dc8f-11ea-97e1-c31f4756d072.png">
this is a quick graph in palladio, obtained by loading the same data grom SPARQL where I am filtering a graph of relations between perons and manuscripts by gender for a given timespan. have fun!

**Comment by thea-m** [comment]
thank you!

**Comment by SusanneHummel** [comment]
Dear Pietro,
thank you! 
Unfortunately, I was again not able to reproduce the search for female scribes. 
- first it is such a tiny script that it is really difficult for me to read (https://betamasaheft.eu/gender)
- than I simply don't know what to copy and to edit and to paste into https://betamasaheft.eu/sparql

I am really sorry to be such a hopeless case...

I woudld like to quote your search in my article that I am about to finalize. Is there a permanent link to a sucessful query on female scibes?

Best
Susanne

**Comment by PietroLiuzzo** [comment]
you only have to click the link in the text. the table is comprehensive, not only for female. https://betamasaheft.eu/gender/table

**Comment by PietroLiuzzo** [comment]
I have added https://betamasaheft.eu/gender/table/female and https://betamasaheft.eu/gender/table/male linked from the landing page which contain tables which are restricted by gender.
If you are using this in a paper, my suggestion would be, depending on what you are quoting it for, to either 
- simply point to the general page (https://betamasaheft.eu/gender) or to one of the views (/gender/table, /gender/graph, /gender/page) or to the data at /gender/data. All these are stable links, they will not change. Their content will, these are not resources subject to versioning, like manuscripts, e.g., which can be cited using [PIDs](https://betamasaheft.eu/pid.html), but only visualisations of aggregates and queries. 
- to cite a stable version of the specific _dataset_ (/gender/data) which you used via its HTML view, so not the latest version and not that specific view, but indeed what you used in whatever way, you could save a copy of the data, in a format of your choice to Zenodo or to Uni Hamburg ZFDM repo, and point to that dataset and its DOI, both Zenodo and ZFDM run the same software which allows very easy versioning of the imported resources. The metadata would have to contain reference to BM as required by the CCBYSANC of the data, allowing non commercial derivates with attribution. 
- If you want to cite the page as it looks when you are looking at it and with the data as it looks, although this is less likely citation form IMHO, I would suggest to save it to the Way Back Machine with any of the available plugins and cite the web resource pointing to the version stored there.   e.g. https://web.archive.org/web/20200812190615/https://betamasaheft.eu/gender/table/female

I this summary on citation of web resources is useful anywhere else, I can paste it where appropriate.

**Comment by SusanneHummel** [comment]
> you only have to click the link in the text. the table is comprehensive, not only for female. https://betamasaheft.eu/gender/table

I find a very useful table with all information including the fields "male/female" "owner/scribe/donor". Bit I would need to count the occurances: scribe+femal by myself? Now its zero, so in this case its easy.

**Comment by PietroLiuzzo** [comment]
female+scribe or any other role attested by gender you find already counted and contextualized in /gender/page hoovering the columns will tell you the count, which is also already grouped, since the rows in the table cannot be counted one by one, because for example two roles or two occupation will have each one row.
let me know what further views or breakdown you need, these can all be added, as said this can only be a starting point.

**Comment by SusanneHummel** [comment]
> I this summary on citation of web resources is useful anywhere else, I can paste it where appropriate.

I would now cite the link with the date of access
https://betamasaheft.eu/gender/table/female 

I would find your summary very helpful. I had a quick look into the help menue, and could not find "citation" ( I know that BM always suggest a citation of authority files and catalogue entries at the bottom og the page)

**Comment by PietroLiuzzo** [comment]
If I may, the date of access is not sufficient, because is not reproducible. you are only saying that you saw it at a given date. the webarchive link is a better option if you want to cite the page as such, as it also allows the future reader to go back to that date and time and see what you saw in the best possible way at that time.
help page is now updated

**Comment by SusanneHummel** [comment]
You're absolutely right! Thank you!!
