### ISSUE TITLE
new record for BLorient534

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1452]
I would like to create a new record for a collection of salām-hymns in BLorient534. It is different from LIT2001Mazmur (which can be read here for example https://gallica.bnf.fr/ark:/12148/btv1b100934307/f2.image), even salams to the same person on the same day diverge (according to the catalogue incipit). 

![image](https://user-images.githubusercontent.com/19650382/86914360-843e2180-c120-11ea-99ad-2aa53008775a.png)

![image](https://user-images.githubusercontent.com/19650382/86914386-8e602000-c120-11ea-940d-66d2f7e79a2e.png)

https://archive.org/details/catalogueofethio00brituoft/page/84/mode/2up

Of course, I would be even happier if you know this collection and I would not have to create a record.

**Comment by thea-m** [comment]
@DariaElagina  @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I do not know this collection, I think nothing prevents from creating a new ID

**Comment by DenisNosnitsin1970** [comment]
Difficult to say. There are several similar collections of the type "Egziabeher nagsa..." ("Medraweyan and samayaweyan" is one of them), no one studied them.  Would be nice if you could spot more that one witness, you can try to fine a kind of guidance in the book of Getatchew Haile

**Comment by thea-m** [comment]
Good, thank you. I will check the book as soon as I can, and in the meanwhile, make a PR for the manuscript without ID for this text, and leave this issue open so that it will not be forgotten.

**Comment by thea-m** [comment]
Indeed, as suggested by @DenisNosnitsin1970, Getatchew mentioned this work, and it is LIT2236Salama. No need for a new ID, and I think that this is a nice confirmation of the new workflow's usefulness, @PietroLiuzzo
