### ISSUE TITLE
double idno

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1454]
there are [5 cases](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3AmsIdentifier%2Ft%3Aidno%5B2%5D) in which `<msIdentifier>` contains 2 `<idno>` and need to be corrected. please note that alternative identifiers need `<altIdentifier>`.

**Comment by eu-genia** [comment]
I can see in the list https://betamasaheft.eu/xpath?xpath=$config:collection-rootMS//t:msIdentifier/t:idno[2] quite many DS manuscripts, probably not for me to fix? @thea-m

**Comment by thea-m** [comment]
They are all DS manuscripts, because all have an additional `<idno xml:lang="ar">`. Should this be changed? @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
thanks @eu-genia and @thea-m I think this is fine as is now.
