### ISSUE TITLE
unfoliated leaves

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1455]
Grouping several dispersed comments in different PRs for a better coherence of discussion: 
https://github.com/BetaMasaheft/Manuscripts/pull/648
@DenisNosnitsin1970 wrote:

> I think that i + 164 + ii works out better than 1 + 164 + 2. This second indication fails to show that 1 and 2 refer to the units of another level (to such an extend that they were not foliated). The only problem of i + 164 + ii is that it does not let the reader understand that numbers i and ii are unwritten. If we assign these numbers in our descriptions only, but they do not exist in physical manuscript, this should be somehow indicated.

@thea-m wrote:

> I am indicating it in the note (especially as this is a record created purely from the catalogue description).
> I am a bit confused now, so let me try to paraphrase: You would suggest to use Arabic numerals only for guard leaves that have been foliated, while in the case of unfoliated guard leaves, to use Latin numerals?
> In a previous discussion that let to the current guidelines, it was agreed to only use Arabic numerals (which are visualised on the app as Latin numerals).

@DenisNosnitsin1970 wrote:

> I have just dealt with a related problem you commented upon in Abb 202. The main thing is as follows. If Arabic numbres are used for the foliation of the textblock only, I think we should preferably use a different system to foliate fly leaves. I think it is the common practice.
> In addition, if these are numbers added by us (they are not in the catalogue and not in the physical object), it should also be made visible.
> 

https://github.com/BetaMasaheft/Manuscripts/pull/652/files

@thea-m wrote:

> is it 2+92+1, or are they already included in the 92?

@DenisNosnitsin1970 wrote:

> I implicate that they are not foliated and therefore not included into the number 92. I see that these additional leaves amount to a kind of small problem of cataloguing. I would tend to take over the number provided in the catalogue, and only add details in the "note". I would not add numbers of folios that are not in the catalogue and not in the images (in this specific case, I do not really understand well the status of those added paper leaves). Or we need to indicate clearly that those numbers are unwritten and exist in the imagination of the cataloguer only, smth like (ii) - 92 - (i)

**Comment by PietroLiuzzo** [comment]
please see #1314 and related work documented in that issue. You encode  1+164+1 (!!PLEASE BE CAREFUL, not 1 + 164 + 2!! and the app should show the desired i + 164 + ii if it does not let me know, the change was introduced, it may simply be that a file was not uploaded to the live app.

**Comment by thea-m** [comment]
@PietroLiuzzo , I know, I opened this because there is apparently more need for discussion, see the PRs, that has for the moment more to do with the content than the encoding, of which I am aware (which is why I commented on this in the PRs)

**Comment by thea-m** [comment]
I think that one part of the problem is that we are discussing two different things at once. 
The first problem is how to deal with the presence of unnumbered leaves in the catalogue. Where and how should they be noted?
The second is the nature of these leaves - are they really "guard leaves"?
Consequently, should there be a difference in dealing with leaves added for example by the European library during rebinding, and original guard leaves of the manuscript?

**Comment by DenisNosnitsin1970** [comment]
I think that we should not make it too complicated, and say that we discuss the unfoliated leaves in the beginning and the end (there are a number of facets in this matter, but we can start from the bigger framework). What Pietro mentioned is already very good and actually what nearly what is needed, in my opinion, there is one small detail: the number of leaves is the administrative information. If the catalogue says: 92 leaves, and we estimate: i + 164 + ii, shouldn't it be made clear that this is not what the catalogue that we use the authoritative source says, but what we say? (e.g., Abb 202 has unfoliated leaves in the beginning and the end, not accounted for in the catalogue). Yes, the guard leaves may be very complex: we cannot see them physically, sometimes they were are original, sometimes added in the library, etc.

**Comment by PietroLiuzzo** [comment]
I think, without need for further markup precision you can use multiple measure elements as detailed in the GL and describe faithfully in words what happens.

**Comment by DenisNosnitsin1970** [comment]
I see, this is a good solution.

**Comment by thea-m** [comment]
So you agree that we stick to what we have and add discoursive explanations whenever necessary?

**Comment by DenisNosnitsin1970** [comment]
I never refuse to stick to what we have, it is probably the question of configuring the available means. You will see in Abb 202.
