### ISSUE TITLE
New work record for BDL Aeth. g 13

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1457]
I would like to create a record for this litany, attested in the Oxford manuscript and some EMIP manuscripts, and edited by Hammerschmidt in bm:Hammerschmidt1960Texte, 29-35. 

In which manuscript is the work you would like to create attested?  BDL Aeth. g 13, EMIP00616, EMIP00130, EMIP02049, EMIP02042

![image](https://user-images.githubusercontent.com/19650382/88809366-5777aa00-d1b4-11ea-91bf-8d1df634a3fe.png)

@DariaElagina

**Comment by DariaElagina** [comment]
I could not find this work in the database either, so I think that a work record should be created.

**Comment by thea-m** [comment]
Thank you!
