### ISSUE TITLE
Image of Saint Bǝsoy

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1458]
EMIP 499 contains the 'Image of Saint Bǝsoy', መልክአ፡ ብሶይ፡ with the incipit:
 
ሰላም፡ ለዝክረ፡ ስምከ፡ ዘተሰብሐ፡ ወተወደሰ፡

I can only identify two miracles related to Bǝsoy in the clavis̮ so wish to query whether a new work record should be created. 

Image of the first part of this work is attached. 

![image](https://user-images.githubusercontent.com/39619238/88943944-059e5500-d284-11ea-8cc6-aa4e295f52aa.png)

**Comment by thea-m** [comment]
I don't find any other reference to this work outside of EMIP records either, and would be in favour of creating a new ID.

**Comment by Ralph-Lee-UK** [comment]
I will create the work file.

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Works/pull/259
thank you!

**Comment by smaugustine** [comment]
It seems to me that this text is likely not for any of the Egyptian figures named Pishoi/Bishoy. In 7.3 he is called "ወልደ፡ ዘርአ፡ ቡሩክ፡", which establishes an Ethiopian connection, and then in 22.3 he is called "ፍሬ፡ ከርሠ፡ ሰማዕት፡ ዮሐንስ፡ ከማ፨", which seems to connect him to the Yoḥannǝs Kamā who was martyred alongside Gerǝllos as reported in ገድለ፡ አፍቀረነ፡ እግዚእ፡ (as far as I am aware, there is not another Yoḥannǝs Kamā who was martyred). While anachronistic, ገድለ፡ ዘርአ፡ ቡሩክ፡ reports that Zarʾa Buruk was a spiritual son of the same Gerǝllos, which might explain how this Bǝsoy could be connected to both Zarʾa Buruk and Yoḥannǝs Kamā (cf. https://github.com/BetaMasaheft/Documentation/issues/3295 and https://github.com/BetaMasaheft/Documentation/issues/3192#issuecomment-3493933939).

We are also told that he died in Tāḫśāś (25.3: እምአመ፡ አዕረፍከ፡ ብሶይ፡ በወርኀ፡ ማእረር፡ ታኅሣሥ፨), which does not seem to correspond to any of the Egyptians of this name.

Unfortunately, the other specific details of his life, that he had a disciple named Tomās (15.5: ዘምስለ፡ ረድእከ፡ ቶማስ፡), that a certain Muslim saw his face shining (20.3–5: ሶበ፡ ኪያከ፡ ሐወጸ፨ እስማዔላዊ፡ ... መልክአ፡ ገጹ፡ አስተርአየ፡ ለምጸ፨), and that he was buried in a church dedicated to Mary (26:1–2: ወለመቃብሪከ፡ ሕንጽት፨ በስመ፡ ማርያም፡), offer little in attempting a precise identification.
