### ISSUE TITLE
person record not created

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1461]
I'm sorry,  my latest person creation failed
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<exception>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 575, column 19]</message>
</exception>**
**
```
probably because I failed to log out and in, my fault. I'm just writing this issue in case that this is also something interfering with the app syncing and it would be better if you retrieved the record. Otherwise I'd just create a new one.

**Comment by thea-m** [comment]
@PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
what is the record you tried to create?

**Comment by PietroLiuzzo** [comment]
the last recorded by the app is PRS13124GabraKrestos

**Comment by thea-m** [comment]
The name was Walda Krəstos. If he has not been recorded, I can recreate without trouble?

**Comment by PietroLiuzzo** [comment]
yes
