### ISSUE TITLE
Gǝ‘ǝz grammar, Säwasǝw, ሰዋስወ፡ ግእዝ፡

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1462]
A good number of the EMIP mss have a short grammar of Gǝʾǝz included. Images below are from EMIP 2108 which are a typical example. The text may vary somewhat. I can't identify a work file that would fit this. Any recommendations for how to code this? 
![EMIP02108_CUA-ICOR-Lehnus10_003](https://user-images.githubusercontent.com/39619238/89514552-ec3e6100-d7cd-11ea-95ee-0c91124c2bd0.jpg)
![EMIP02108_CUA-ICOR-Lehnus10_004](https://user-images.githubusercontent.com/39619238/89514580-f3656f00-d7cd-11ea-8ea1-49a6b13fd7ad.jpg)
![EMIP02108_CUA-ICOR-Lehnus10_002](https://user-images.githubusercontent.com/39619238/89514597-f8c2b980-d7cd-11ea-9b7e-34422e15d0ae.jpg)

**Comment by thea-m** [comment]
I think the most immediate solution would be to used the general work record LIT2293Sawase. If more work on these is done in the process of encoding, and specific versions can be identified, new records for those could be created.

**Comment by DenisNosnitsin1970** [comment]
The beginning is not on the verso side, but on the recto that i do not see, right? (it would be nice to have a look at it). I think for the moment it is enough if yo encode this with the id of the general work record, and quote a little bit from it (

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970  and @thea-m thanks for this. I think the beginning is missing, as the recto side is covered with scrawls, sadly

**Comment by thea-m** [comment]
Can this be closed?

**Comment by DenisNosnitsin1970** [comment]
Yes.
