### ISSUE TITLE
New work record for BLorient545

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1463]
I would like to create a record for the second hymn to Libānos as described here by Wright:

![image](https://user-images.githubusercontent.com/19650382/89526411-fe2cfd80-d7e7-11ea-92c4-33b835991daa.png)

https://archive.org/details/catalogueofethio00brituoft/page/90/mode/2up

@DariaElagina @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
You have the full right to do this! There is always a chance that a salam is taken out from a collection like Egziabeher Nägsä. If you want to get more solid ground, you can check EAE Libanos and the edition, small compositions must be recorded in one or another way.

**Comment by thea-m** [comment]
Thank you! It is edited in the edition as a salam following the malkʾ. So will create a record for it.
