### ISSUE TITLE
EMA mss visualization and the schema 

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1466]
It seems that a lot in BNFabb152 large parts of the description are not visible on the app (maybe because the schema has been changed since) 

E.g. the long text in the `<additions>` before the `<list>` starts is not visualized, 
The `<title>` elements within the `<item>` in the additions is not visualized - I guess it should be placed within the `<desc type="GuestText">` or similar.

I guess either the description(s) using this device or the schema must be adjusted to be able to view the content.

**Comment by eu-genia** [comment]
Forget it, sorry, these are EMA mss no idea what to do with them

**Comment by PietroLiuzzo** [comment]
you are right, this manuscript has been imported from EMA and needs quite some work on it to be made valid. neither the schema nor the visualisation need any changing, only the data needs to be reworked, as a lot of other data in the project for different reasons, so, it makes no exception or issue imho, just a normal work in progress.

**Comment by eu-genia** [comment]
OK, I was not sure who was in charge of making them properly viewable.
Since they were already imported with some adjustments to our schema I was thinking that maybe some general ones could be still implemented. E.g. is it possible to do some batch changes (e.g. introduce in EMA imports a `<desc>` element around the content of each `<item>` in `<additions>`)?

**Comment by PietroLiuzzo** [comment]
there is only that one.

**Comment by eu-genia** [comment]
There are some attributes that the schema does not have (some were introduced, 
e.g. note type="résumé" is accepted but note type="traduction" is red, but this is a footnote to translation, we would lose their information if I take the type out
they have different keywords for the types of land ownership (gwelt, rest - these categories are central for their type of research) which we also do not have

**Comment by PietroLiuzzo** [comment]
Since this is being worked on by others, and has its own story, I think it would be better to let it be. There is already a complete and detailed report on the divergences of this special file from the others and the necessary changes to the schema have been done already, between 2017 and 2018. I wonder what is that puts pressure on this particular item right now among all the rest. If it is so urgent that it becomes fully compatible with the rest of the data now, please let me know and I will do this my self on the basis of the previous report.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/719

**Comment by eu-genia** [comment]
If there is someone who will fix it at some point it is OK, for me it was important to be able to view it on the app

**Comment by PietroLiuzzo** [comment]
So there was no urgency, because it is visible in the app, beside known limitation. Please leave the branch and PR #719 untouched so that I can carry on with the review.
