### ISSUE TITLE
EMIP 1923 and identification of specific works

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1467]
EMIP 1923 is contains an extensive list of homilies, most of which come under the general heading of LIT3309Qerellos. I have been able to identity a good number. There are several works that I am struggling with. If anyone can help me identify them and then think about whether there are any new work files to be identified I would appreciate it! For instance, there are several that are just identified as 'Homily by Cyril of Alexandria' and there are several work records with this title, but no details in them to help further identification. 
The works are the following as listed in the EMIP catalogue, and images follow for each of them, with the number in brackets referring to the white folio stamp in the top right hand corner of the images)
That Christ is One, Kama aḥadu Krestos, <foreign xml:lang="gez">ከመ፡ ፩፡ ክርስቶስ፡</foreign> by Cyril of Alexandria (79)

Homily by Cyril of Alexandria, <foreign xml:lang="gez">(ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡</foreign> (125)

Homily by Cyril of Alexandria, <foreign xml:lang="gez">(ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት ዘለእስክንድርያ፡</foreign> (129)

Homily by Cyril of Alexandria, <foreign xml:lang="gez">(ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡</foreign> (132)

Homily by Cyril of Alexandria, <foreign xml:lang="gez">(ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡</foreign> (137)

Homily by Epiphanius of Cyprus On the Orthodox Faith, <foreign xml:lang="gez">ድርሳን፡ ዘኤጲፋኒስ፡ ጳጳስ፡ ዘሀገረ፡ ቆጵሮስ፡ በእንተ፡ ሃይማኖት፡ ርትዕት፡</foreign> (141)

Homily by Epiphanius of Cyprus on an Explanation of the Trinity, <foreign xml:lang="gez">ድርሳን፡ ዘኤጲፋንዮስ፡ ጳጳስ፡ ዘቆጵሮስ፡ በእንተ፡ ሥላሴ፡ ፍካሬ፡</foreign> (144)

The Faith of Gregory [Thaumaturgus] of Neo-Caesarea, <foreign xml:lang="gez">በእንተ፡ ሃይማኖት፡ ለቅዱስ፡ ጎርጎርዮስ፡ ጳጳስ፡ ዘኔዎቂ[ሳ]ርያ፡</foreign> (154)

On the Nativity and Life of Our Lord, <foreign xml:lang="gez">እንተ፡ በኵሉ፡ ክብርት፡ ጌና፡ ዘይእቲ፡ ልደቱ፡ በሥጋ፡</foreign> (161)

Confession of faith, <foreign xml:lang="gez">አንቀጽ፡ ቀዳማዊ፡</foreign> (162)

![EMIP01923_CFRRC90_166](https://user-images.githubusercontent.com/39619238/90143019-ff74a200-dd74-11ea-9586-5df6d9eae62a.jpg)
![EMIP01923_CFRRC90_083](https://user-images.githubusercontent.com/39619238/90142033-cb4cb180-dd73-11ea-92b3-934b49632968.jpg)
![EMIP01923_CFRRC90_129](https://user-images.githubusercontent.com/39619238/90142136-ef0ff780-dd73-11ea-9ad5-15afa4110a30.jpg)
![EMIP01923_CFRRC90_133](https://user-images.githubusercontent.com/39619238/90142201-00590400-dd74-11ea-8072-62669a788704.jpg)
![EMIP01923_CFRRC90_136](https://user-images.githubusercontent.com/39619238/90142260-1070e380-dd74-11ea-9010-564177b7dbaf.jpg)
![EMIP01923_CFRRC90_141](https://user-images.githubusercontent.com/39619238/90142359-2c748500-dd74-11ea-8487-9ae8add0ce01.jpg)
![EMIP01923_CFRRC90_145](https://user-images.githubusercontent.com/39619238/90142464-4e6e0780-dd74-11ea-9cc7-9e5bf854d060.jpg)
![EMIP01923_CFRRC90_148](https://user-images.githubusercontent.com/39619238/90142555-6ba2d600-dd74-11ea-980e-eedc101047ee.jpg)
![EMIP01923_CFRRC90_158](https://user-images.githubusercontent.com/39619238/90142648-87a67780-dd74-11ea-8bb9-3d3b67063924.jpg)
![EMIP01923_CFRRC90_165](https://user-images.githubusercontent.com/39619238/90142693-9725c080-dd74-11ea-8b62-98c7d242fb8d.jpg)
![EMIP01923_CFRRC90_166](https://user-images.githubusercontent.com/39619238/90143062-0e5b5480-dd75-11ea-879a-3076b5ef592d.jpg)

**Comment by thea-m** [comment]
Hi! Here are most of them. They are all textparts of LIT3309Qerellos, so I listed them here with their dependent ID first, and the individual ID second. The last two I could not verify now, maybe @DenisNosnitsin1970 or @DariaElagina can help.

That Christ is One, Kama aḥadu Krestos, ከመ፡ ፩፡ ክርስቶስ፡ by Cyril of Alexandria (79)
 = LIT3309Qerellos#Dialogue = LIT3312Unity

Homily by Cyril of Alexandria, (ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡ (125)
= LIT3309Qerellos#HomilyByCyril1 = LIT3328Cyril

Homily by Cyril of Alexandria, (ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት ዘለእስክንድርያ፡ (129)
= LIT3309Qerellos#HomilyByCyril2 = LIT3329Cyril

Homily by Cyril of Alexandria, (ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡ (132)
= LIT3309Qerellos#HomilyByCyril3 =  LIT3330Cyril

Homily by Cyril of Alexandria, (ድርሳን፡) ዘቄርሎስ፡ ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡ (137)
= LIT3309Qerellos#HomilyOfCyril4 = LIT5622HomilyCyrilJohnMiyazya

Homily by Epiphanius of Cyprus On the Orthodox Faith, ድርሳን፡ ዘኤጲፋኒስ፡ ጳጳስ፡ ዘሀገረ፡ ቆጵሮስ፡ በእንተ፡ ሃይማኖት፡ ርትዕት፡ (141)
= LIT3309Qerellos#HomilyByEpiphanius = LIT1267Dersan

Homily by Epiphanius of Cyprus on an Explanation of the Trinity, ድርሳን፡ ዘኤጲፋንዮስ፡ ጳጳስ፡ ዘቆጵሮስ፡ በእንተ፡ ሥላሴ፡ ፍካሬ፡ (144)
= LIT3309Qerellos#SymbolByEpiphanius = LIT1266Dersan

The Faith of Gregory [Thaumaturgus] of Neo-Caesarea, በእንተ፡ ሃይማኖት፡ ለቅዱስ፡ ጎርጎርዮስ፡ ጳጳስ፡ ዘኔዎቂ[ሳ]ርያ፡ (154)
= LIT3309Qerellos#SymbolByGregory = LIT3325Gregory

Not checked: 
On the Nativity and Life of Our Lord, እንተ፡ በኵሉ፡ ክብርት፡ ጌና፡ ዘይእቲ፡ ልደቱ፡ በሥጋ፡ (161)
= LIT3309Qerellos#OnBirthAndLife = LIT3334Ontheb (possibly, but I could not check this)

The last one might possibly be LIT3309Qerellos#AntihereticalTreatise = LIT3335Antihe, but I could not check this either

**Comment by Ralph-Lee-UK** [comment]
This is wonderful, thankyou!

**Comment by Ralph-Lee-UK** [comment]
@thea-m - one further question - where could I have found this information? Some of the xml works files have little information in them.

**Comment by thea-m** [comment]
In this case, the individual IDs were all listed in LIT3309Qerellos. I often find it easier to directly look at the XML, either in my editor or in the app with the URL http://betamasaheft.eu/LIT3309Qerellos.xml. I could check the editions by Weischer to verify that the texts correspond to these IDs (except for the last two, to whose presumed editions I currently don't have access).
You are of course right that most work files are very basic. Here as well, it would be great to have the incipits and explicits at least. But it is all work in progress, one day we might be there (and let me repeat that particularly the EMIP encoding with the huge quantity of typed excerpts and matching images available is an invaluable resource).

**Comment by Ralph-Lee-UK** [comment]
Thanks very much for this. I will type up the incipits for these entries at least, so they will be in the EMIP 1923 file.

**Comment by thea-m** [comment]
Thank you! That would be quite helpful. But please do it only if it is in your workflow anyway - there will always be more work than what can be accomplished...

**Comment by Ralph-Lee-UK** [comment]
And a final question - is there a preference over whether the dependent ID or the individual ID? I couldn't find any information in the guidelines on this.

**Comment by thea-m** [comment]
Both are fine. Since the manuscript is one of the Qerellos, I would suggest to use there the dependant IDs, and to encode all homilies as textparts of LIT3309Qerellos.
