### ISSUE TITLE
Title within the Additions

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1468]
The element `<title>` has often been used in the `<additions>` outside of the `<desc>` element; in this case it is not visible on the app. The element `<title>` should be within the `<desc type=GuestText>` as described in the guidelines https://betamasaheft.eu/Guidelines/?q=additions&start=6&id=additionsVaria

E.g. in IVsuhtelen256 

```
<item xml:id="a2">
<desc type="GuestText"/>
<title type="incomplete" ref="LIT2444Temher"/>
<locus target="#2v"/>
...
</item>
```
Should become

```
<item xml:id="a2">
<locus target="#2v"/>
<desc type="GuestText"><title type="incomplete" ref="LIT2444Temher"/>
</desc>
...
</item>
```

The list is here
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aadditions%2Ft%3Alist%2Ft%3Aitem%2Ft%3Atitle

I have 96 hits - I think we have all committed the error @DenisNosnitsin1970 @thea-m 
(I will be fixing mine now)

Alternatively of course @PietroLiuzzo can be asked to modify the schema but I would suggest that we stick to the guidelines...

(@DenisNosnitsin1970 there is sometimes also something wrong with the repository link for IV, maybe can be fixed too)

**Comment by thea-m** [comment]
Thank you, I have corrected those in my records. I will not fix the Vatican records now, which have many peculiarties anyway.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/720
https://github.com/BetaMasaheft/Manuscripts/pull/721

**Comment by DenisNosnitsin1970** [comment]
OK, I'll correct main.

**Comment by eu-genia** [comment]
@DariaElagina also has something to fix (in InEtn4055) sorry forgot to tag

**Comment by eu-genia** [comment]
I still see some manuscripts in the list
1[Portland, Ethiopic Manuscript Imaging Project, Alwan Codex 3](https://betamasaheft.eu/EMIP00108) (EMIP00108)a1title
2[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 223](https://betamasaheft.eu/BAVcerulli223) (BAVcerulli223)a24title
3[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 223](https://betamasaheft.eu/BAVcerulli223) (BAVcerulli223)a32title
4[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 223](https://betamasaheft.eu/BAVcerulli223) (BAVcerulli223)e4title
5[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 37](https://betamasaheft.eu/BAVcerulli37) (BAVcerulli37)e14title
6[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 37](https://betamasaheft.eu/BAVcerulli37) (BAVcerulli37)e15title
7[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 37](https://betamasaheft.eu/BAVcerulli37) (BAVcerulli37)e16title
8[Vatican City, Biblioteca Apostolica Vaticana, Biblioteca Apostolica Vaticana Cerulli 37](https://betamasaheft.eu/BAVcerulli37)[](https://betamasaheft.eu/BNFabb96) (BAVcerulli37)e17title
9(BNFabb96)

**Comment by thea-m** [comment]
I can fix them

**Comment by eu-genia** [comment]
Thank you!
