### ISSUE TITLE
New work record for the Encyclical Letter in BL Add 19,339

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1469]
I could not find a record for this work in a database, which is a letter of Mark, the 108th patriarch of Alexandria to the Church of Ethiopia. Here is the link to Wright, pp 264-265: https://archive.org/details/catalogueofethio00brituoft/page/264/mode/2up
Would you mind if I creat a work record for it? Or should I rather just assign a keyword letter? @DenisNosnitsin1970  @thea-m

**Comment by DenisNosnitsin1970** [comment]
I would assign a record to it. In terms of genre, it is possibly similar to "paschal letters" that are parts, for instance, of Hamanota abaw, 
but this one is circulated separately (it is a long one!), and the ms is probably not the only witness.

**Comment by DariaElagina** [comment]
Thank you!
