### ISSUE TITLE
Further Commentaries that may need work files creating

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1471]
A while ago we agreed to create work files for Amharic commentaries on works. EMIP00634 contains the following, and I don't seem to be able to find the work file for this. Can you help?

  <title>Commentary on Mystagogia, Tǝrgwame Tǝmhǝrtä Ḫǝbu‘at, <foreign xml:lang="gez">ትርጓሜ፡ ትምሕርተ፡ ኅቡዓት፡</foreign></title>
                  <textLang mainLang="am" otherLangs="gez">Gə‘əz and Amharic</textLang>
                  <incipit>
                    <foreign xml:lang="gez">በእንተ ፡ ትምህርተ ፡ ኅቡዓት ፡ ቅድመ ፡ ዘትትነገር ፡ እምጵርስ ፎራ ፡</foreign>
                    <foreign xml:lang="am">
                      ታሪከ ፡ ጌታ ፡ በሕይወተ ፡ ሥጋ ፡ ሳለ ፡ ያስተማረው ፡ ወንጌል ፡ ይባላል።
                      ከሞት ፡ ተነሥቶ ፡ ያስተማረው ፡ ኪዳን ፡ ይባላል።
                      በሕይወተ ፡ ሥጋ ፡ ሳለ ፡ ያስተማረው ፡ ወንጌል ፡ መባሉ ፡ ስለምን ፡ ነው ፡ ቢሉ ፡ ወንጌል ፡ ማለት ፡ ብሥራት ፡ ማለት ፡ ነው።
                      ወንጌል ፡ ብሥራት ፡ ስብከት ፡ ቢል ፡ አንድ ፡ ወገን ፡ ነው።
                      ወንጌል ፡ ቢሂል ፡ በልሳነ ፡ ጽርዕ ፡ ዘበትርጓሜሁ ፡ ስብከት ፡ እንዲል ፡ <gap reason="omitted"/></foreign></incipit>

**Comment by thea-m** [comment]
I also don't find an existing ID for this, so it would make sense to me to create one. 
@DenisNosnitsin1970 @DariaElagina what do you think?

**Comment by DenisNosnitsin1970** [comment]
It seems that it exists already, LIT5944CommMystatgogia.

**Comment by Ralph-Lee-UK** [comment]
Perfect, many thanks!
