### ISSUE TITLE
Coding EMIP 690

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1475]
EMIP 690 is a Deggwa and I am seeking some advice in coding. The Deggwa is divided into 8 long sections. The first part, for instance, starts with the Hymn for the Feast of John the Baptist (LIT4350JohnTheBaptist) and ends with the Hymn to the Martyrs (LIT4364Martyrs). There are several sets of vigil hymns, not all of which correspond to the textparts in LIT3178Deggwa.xml

Each of the 8 sections is similar, the second form ዋዜማ፡ ዘአስተምሕሮ፡ (LIT4365Supplication1) through to the Hymn for Epiphany (LIT4380Epiphany) and I think the Hymn to Simeon (LIT4381Simeon2) is missing (it certainly does not have its title rubricated). 

I don't have the time to go through every folio, but would it be acceptable to give the starting hymn and finishing hymn of each section? If that is so, how would one encode a section 'starting with X and finishing with Y' in a meaningful way?

Given that there is some good information in the catalogue, it seems a shame to lose it. 

Let me know what you think.

**Comment by PietroLiuzzo** [comment]
@karljonaskarlsson perhaps you may also have something to say on this?

**Comment by DariaElagina** [comment]
Probably, you could just use the subordinate ms_items?

**Comment by thea-m** [comment]
Thank you! The Deggwa encoding is currently indeed not much developed, but this might be reasonable while awaiting the results of Jonas' thesis.
Yes, I also think that using subordinate ms_items here would be fine. You could add a clarifying statement in a `<note>` explaining that these are only the first and last textparts and that the catalogue does not reproduce the complete structure of the manuscript.

**Comment by Ralph-Lee-UK** [comment]
That is very helpful. Indeed we all await Jonas' thesis with bated breath!
