### ISSUE TITLE
Commentary on Ezekiel

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1476]
There are two works files:

LIT5799TergwHezq and LIT5975CommEzekiel 

I think the latter was created in the list of Amharic commentaries that we created a short time ago. I think that they are essentially the same thing. 

LIT5799TergwHezq is referenced once in the coded mss in BLorient506 and LIT5975CommEzekiel is not yet used. 

Should one be deleted?

**Comment by DenisNosnitsin1970** [comment]
I think, yes, esp. if one has not been used and has no relations.

**Comment by thea-m** [comment]
LIT5799TergwHezq is in Geez. I do not know these works well enough to tell whether the Amharic is a strict translation from the Geez. But if not, then both records should be kept.

**Comment by Ralph-Lee-UK** [comment]
@thea-m this is an important point. Many of the Amharic commentaries also go by the title ትርጓሜ፡ መጽሐፍ፡ ዘሕዝቅኤል፡ or in this case ትርጓሜ፡ ሕዝቅኤል፡ but having looked at the incipit for BLorient506 the commentary is in Gǝʾǝz whereas in EMIP00691 the text of Ezekiel is in Gǝʾǝz but the commentary is in Amharic, so both records should definitely be kept. In Cowley's work he distinguished between the ትርጓሜ tradition in Gǝʾǝz and the Amharic commentary which has become known as Andǝmta, so it makes full sense to maintain this distinction as further work files are created.

**Comment by PietroLiuzzo** [comment]
perhaps use isVersionInAnotherLanguageOf?

**Comment by thea-m** [comment]
If @Ralph-Lee-UK decides that they are versions of each other, that would be useful. Please close this issue when you consider it solved.

**Comment by DenisNosnitsin1970** [comment]
Just a remark: i think "Andemta" is a word that is never used in written commentaries. Instead, if at all, Tergwame is used. But "Tergwame ... " is in the title of some translated Geez commentaries to biblical patristic works (these texts are fluent, well-shaped, not fragmentary and mosaic as Andemta records), if I am not mistaken.

**Comment by thea-m** [comment]
Thank you, @DenisNosnitsin1970 !

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 is correct - I believe that Roger Cowley did produce a couple of mss that use the term Andemta - but quite often it is not used. It is a useful general term to refer to a category of commentary, however. Tergwame is used, as you say, of some commentary material that is earlier, and of quite a different style. Roger Cowley was also clear that these earlier Tergwame are a separate set of literature from the later Amharic commentary - although there is some continuity between the traditions. When we created the recent set of work files, with the abbreviation 'Comm' in the file name, the title was clearly recorded as 'Amharic Commentary on...'. It might be appropriate, therefore, to edit LIT5799TergwHezq to have an English title 'Gǝʾǝz Commentary on...' rather than just 'commentary on...' Furthermore, given that Amharic commentary does sometimes use the title Tergwame, it might be appropriate to change the title of the file too - to LIT5799GeezCommHezq or something like this. That would also suggest that the other commentary files are renamed 'LIT####AmCommHezq' or something like that. Or is this going too far? @thea-m do you have any thoughts?

**Comment by thea-m** [comment]
We will not change the IDs, as these are in themselves meaningless and should only be changed when absolutely necessary. I've  Gǝʾǝz Commentary on.. as a title to LIT5799TergwHezq, I think that's a good solution

**Comment by Ralph-Lee-UK** [comment]
Perfect, this is a good workable solution.
