### ISSUE TITLE
search results

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1480]
**Is your feature request related to a problem? Please describe.**
searching for መርምህናም for example, the results of as.html give KWIC and element name, but because the result is found in the transcription, clicking the link does not bring to the occurrence and neither the text parameter is used to provide the highlighting of the match in the view. using facet.html the element name is given, there is hightlighting but the link goes to the main view. 

**Describe the solution you'd like**
- [x] as.html results should include the name of the closest element with an xml:id
- [x] if the result is matched in the text the link provided should be one of the possible dts uris shortened form for the document api, e.g. https://betamasaheft.eu/BNFet677.5.20.3 or directly https://betamasaheft.eu/manuscripts/BNFet677/text?ref=5.20.3 to avoid controller.xql overhead

**Additional context**
Also the landing view of nested units has no useful navigation hints. when landing at BNFet677.5.20.3 
- [ ] I should have prev, next, and upper level in the navigation options, which however are not in the response from the dTS navigation API request https://betamasaheft.eu/api/dts/navigation?id=https://betamasaheft.eu/BNFet677&ref=5.20.3 
the document API request parallel to this will instead have links in the header, which can be used for prev and next at least. dts:citationDepth and dts:level should be used to compute the upper level (but, hey, should that not be already there?)

**Comment by PietroLiuzzo** [comment]
Thanks @SusanneHummel for providing example and discussing the issue

**Comment by PietroLiuzzo** [comment]
while I am at it, @eu-genia @thea-m @DenisNosnitsin1970 @DariaElagina do you have any additional feature request for the text view and the search results in advanced search and faceted search? 
thanks

**Comment by thea-m** [comment]
Nothing from me, thank you

**Comment by PietroLiuzzo** [comment]
<img width="838" alt="Schermata 2020-09-12 alle 11 46 04" src="https://user-images.githubusercontent.com/508012/92992756-9441fb00-f4ed-11ea-8e0c-02cc84b786cb.png">
I have opted for leaving the link to the main entry related too the title and provide additional links for the KWIC passages provided (always limited to the 3).
