### ISSUE TITLE
Lǝssāna sabʾ duplicates

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1482]
LIT1770Lessan and LIT3034RepCh314 seem to refer to the same work. As LIT1770Lessan has not been used yet, I suggest transfering the additional title it provides to LIT3034RepCh314 and deleting it.
Any objections? @DariaElagina @DenisNosnitsin1970 @eu-genia  @smaugustine

**Comment by smaugustine** [comment]
Good catch! The addition of "Malkǝʾa lǝssān" definitely indicates that it is the same (and not Lǝssāna Yāʿǝqob).

**Comment by smaugustine** [comment]
See [this comment](https://github.com/BetaMasaheft/Documentation/issues/1477#issuecomment-690187990) regarding distinguishing ልሳነ፡ ሰብእ፡ and ልሳነ፡ ያዕቆብ፡.

**Comment by eu-genia** [comment]
Sure
Lǝssāna sabʾ is I think holding a current record in duplicates. 
(LIT1770Lessan was actually the original ID, inherited with most others from the EAe index, and was supposed to be edited, but then it was continuously overlooked when creating LIT3034RepCh314, LIT4696MagicPr and probably LIT5679MagicPrayer...)

**Comment by thea-m** [comment]
Let's see it as proof that a lot of people are doing a lot of work. And it confirms the usefulness of opening issues before new ID creations etc. Thank you!

**Comment by eu-genia** [comment]
Just for @smaugustine : the record history is such: first stubs were created in all categories on the basis of the final Indices in the Encyclopaedia Aethiopica. So all works, persons, places etc. ever mentioned in the EAe automatically got IDs in BM. Only those which were never mentioned need new records. The problem with the EAe stubs is of course that they all need to be edited, none has Fidal, and they all use EAe transcription.
