### ISSUE TITLE
from relation to standOff and annotation

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1484]
We extensively use `<relation>` which was an acceptable but critisized practice, now TEI has [standOff and annotation](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SASOstdf), following Web Annotation Data Model, and I feel we should move to that. This can be transformed from the current data, and will allow revision of the annotations and eventually the inclusion in the data of annotations available from other sources, and which can be mapped from other WADM implementations. We implement WADM at the moment only for our non-standard prototype for a DTS Indexes API, which is what offers you the indexes in the text view. 
This change, if implemented at schema and guidelines level will mean a bit more encoding, as this model uses few more elements than our current practice with attributes in the `<relation>` element. It offers a lot more possibilities, but it is an entire structure of elements, not a single thing. 
We can also still decide to only add this to the canonicalized TEI which we offer for download, that is, keep to our practice in the data, but expose data which has limited `standOff` and `annotation`s instead of the `relation` element. This has no impact for editors and cataloguers, but limits us to what we are currently doing, which is in any case already enough IMHO. My proposal is to implement the latter unless someone feels we ought to move to that practice also for our daily encoding. Please let me know @DariaElagina @DenisNosnitsin1970 @thea-m @eu-genia @smaugustine

**Comment by thea-m** [comment]
That sounds the easiest and I trust your judgement on such issues. I would however not want our laziness to prevent better encoding and am willing to adapt, in case you would think that best :)

**Comment by eu-genia** [comment]
Looking at the examples (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-standOff.html)

I do see some advantages in the linguistic mark up 

As for the other examples it seems to me rather as a means to add extensive annotation to an entity mentioned in other parts of the TEI document (e.g. in the second example, on the place names mentioned) without the need to create additional TEI documents (here for Atlanta and Birmingham), so it does not seem really relevant  - or comparable to the `<relation>` as we use it) but maybe I am seeing it all wrong

**Comment by PietroLiuzzo** [comment]
Well, the examples in the Guidelines are really limited and I think in this case even less telling than in other cases. The change in principle is much deeper than what these exemplify, and actually covers something for which most of us had to revert to other practices, e.g. our `<relation>`. Key to understand this is WADM as generic, good for everything, standard model for annotations, this is afaik the successor of OA. So, we know have a way to do this properly. It is a way which costs us a good amount of encoding more.
from 
```xml
<relation active="LIT1233example" name="iam:RelationName" passive="LIT4545example"/>
```
to
```xml
    <annotation xml:id="ann01"
        target="LIT1233example">
     <ptr target="LIT4545example"/>
    </annotation>  
```
Where I am definitely not sure where the relation qualifier would go. after all, annotation still does not actually seem to cover our usage for typed relations. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-annotation.html
I think this needs to be asked to the TEI list, which I will do presently.

**Comment by eu-genia** [comment]
this is exactly what i meant. stand off annotation is not the same as relation (at least as we were understanding it)
or one needs an additional taxonomy for annotation types which would derive from relation qualifiers but I don't see this for now

**Comment by PietroLiuzzo** [comment]
Yes, apparently is much easier. While our use of relation is indeed fine, we can in the export move all those into standOff, inside a single listRelation.

**Comment by PietroLiuzzo** [comment]
we could consider using annotation for what annotations are for, eventually.

**Comment by eu-genia** [comment]
the EMA project annotations are good candidates for standOff annotations
