### ISSUE TITLE
Italian Letter of Ṭobiyā Giyorgis Gabra ʾƎgziʾabǝḥer

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1485]
MS Vat. Borg. lat. 285 ff. 352r-353r ([digitized here](https://digi.vatlib.it/view/MSS_Borg.lat.285/0359)) contains a letter written in Italian by Ṭobiyā Giyorgis Gabra ʾƎgziʾabǝḥer (PRS9535tobiyaG), an Ethiopian who worked under the patronage of Cardinal Stefano Borgia. The letter describes the provenance of MS Vat. Borg. et. 24 ([digitized here](https://digi.vatlib.it/view/MSS_Borg.et.24)).

This isn't exactly an Ethiopian manuscript, but it is a literary work by an Ethiopian. I was going to simply link to the Vatican's website from the record for BAVborget24, but is there a better way to incorporate it? Ṭobiyā Giyorgis was the first Ethiopian Catholic bishop and the letter is of some historical value in addition to its connection with BAVborget24.

**Comment by thea-m** [comment]
@DariaElagina has done a lot of work on the encoding of letters, maybe she has good ideas. In principle, a record for such a letter could also be created, even though it is no Ethiopic manuscript, it is clearly of importance to the manuscript tradition.

**Comment by DariaElagina** [comment]
Nice. Actually when I was describing letters, I did not create any work records for them, just added a key word Letter (one could think of creating a correspondig Narrative Unit). So, there are only manuscript records for the letters. A creating of a manuscript record in this case does not make sence I think. Maybe, we could record this letter in Zotero as a manuscript, and add it to BAVborget24 (bibliography) and PRS9535tobiyaG (authorship).

**Comment by eu-genia** [comment]
I think Daria's cases were somewhat different as these were letters in Ethiopian MSS, assigned msItem IDs, so no need to create anything extra. Yet, a Zotero record for an autograph in a manuscript does not sound right either.
To me, a stub record for BAVborglat285, with an msItem (or rather an additio a1, seems like the main collection ends on 350, as the description here http://www.mss.vatlib.it/gui/console?service=present&term=@5Borg.lat.285_ms&item=1&add=0&search=1&filter=&relation=3&operator=&attribute=3040 also suggests, and a facs pointing to the MS, sounds like a cleaner solution if we want to be consequent
