### ISSUE TITLE
Work records for BLorient 604

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1488]
BLorient 604 (Wright p.143-145 https://archive.org/details/catalogueofethio00brituoft/page/142/mode/2up) is a collection of Marian homilies. I was not able to find work records for some of them so I am putting forward a suggestion to create them. They are:
#3 on her birth, presentation in the Temple and marriage to Joseph
#4 on the dormition
#7 on the covenant of mercy
#8 on the annunciation
#9 on the conception
@DenisNosnitsin1970 @thea-m

**Comment by thea-m** [comment]
Thank you! It might take me a few days to look into this, so please be patient, but maybe the others are faster.

**Comment by thea-m** [comment]
I did not find IDs for 3, 4, 8 and 9 either (4 is edited in bm:Arras1973TransituText, 85-100). 7 is, I believe LIT3987Prayer. Maybe @DenisNosnitsin1970 knows more?

**Comment by DenisNosnitsin1970** [comment]
If you search for "Dormition", you will find a number (three) of IDs for a homily on dormition of mary, all without manuscripts. I assume these records were taken from the register of EAE. I think you can use one of them. For ኪዳነ፡ ምሕረት: , please check LIT1290Dersan and the linked ms ESakm011.

**Comment by thea-m** [comment]
Which new IDs are you creating, which ones of the existing are you using? There seems to be confusion with LIT3987Prayer and LIT1290Dersan , but I'll address this in a separate issue. Thank you!
