### ISSUE TITLE
New work record for Bodleian Aeth. b. 4

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1491]
In which manuscript is the work you would like to create attested? 
Bodleian Aeth. b. 4
Or for which other reason would you like to create this new record?
The manuscript contains 42 miracles of St George. No work records exist for those miracles, and therefore need to be created.

@thea-m @MassimoVilla

**Comment by thea-m** [comment]
Yes, I don't think there are any, so they should be created

**Comment by SusanneHummel** [comment]
I also close this one.
