### ISSUE TITLE
Question about digitized Ethio-SPaRe manuscripts

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1492]
Hello,
I am looking for the digitized Ethio-SPaRe manuscripts. On this page https://betamasaheft.eu/availableImages.html, I select Ethio-SPaRe and get the list of 1028 manuscripts https://betamasaheft.eu/manuscripts/list?cp=ES. However, not all of them are available in Beta maṣāḥǝft viewer. Does it mean all 1028 are digitized, but available somewhere else, or only some are digitized and they are in Beta maṣāḥǝft viewer? In the latter case, how can I sort the list of 1028 mss by available images?

**Comment by PietroLiuzzo** [comment]
the facet search has this option, [here](https://betamasaheft.eu/facet.html?query=Ethio-SPaRe&images-facet=yes) I have simply searched for "Ethio-Spare" and filtered by Images Availability.

**Comment by elambrinaki** [comment]
Thank you very much @PietroLiuzzo!

**Comment by PietroLiuzzo** [comment]
you are very welcome!
