### ISSUE TITLE
Duplicate Entries for ጠቢበ፡ ጠቢባን፡

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1493]
The work record which references Dillmann's _Chrestomathia_ no. 9a (incipit: ኦእግዚአብሔር፡ ጠቢበ፡ ጠቢባን፡ ከሃሊ፡), LIT2393tabiba, is a duplicate of LIT3092RepCh372.

It also appears that LIT3092RepCh372 is a duplicate of LIT3084RepCh364 (incipit: እግዚአብሔር፡ ጠቢበ፡ ጠቢባን፡ ከሃሊ፡).

(@thea-m, @eu-genia)

**Comment by eu-genia** [comment]
I think you are right; we used LIT2393tabiba, EMIP people mostly used LIT3084RepCh364, noone used LIT3092RepCh372. (@DenisNosnitsin1970 your take?)
We should decide which is the ID to remain.

**Comment by DenisNosnitsin1970** [comment]
I can check, sure.

**Comment by DenisNosnitsin1970** [comment]
I would use only LIT2393tabiba, the other two can be illiminated. I can do this, and correct the manuscripts (mostly EMIP)

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 have you managed to fix this? Thank you! I just am trying to see if there are issues that can be closed.

**Comment by DenisNosnitsin1970** [comment]
It was fixed.
