### ISSUE TITLE
ርቱዕ፡ ሃይማኖት፡

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1494]
I am seeking on advice on cataloguing mss of the work ርቱዕ፡ ሃይማኖት፡. Lacking images just now for the one that I am looking at, but I believe it is one of the set Rǝtuʿa Haymanot, EA IV p.382. I don't think that there is a work file for this set of homilies, and if that is so should we create one?

**Comment by DariaElagina** [comment]
I think that @MarcinKrawczuk has catalogue a manuscript, maybe he could share his experience.

**Comment by MarcinKrawczuk** [comment]
@Ralph-Lee-UK Please have a look at https://betamasaheft.eu/manuscripts/BLorient786/main, maybe it will be helpful. 

The record I used for the general collection is LIT2222RetuaH, but I guess one would have to at some point distinguish between various "Retua Haymanot"s , at least between the ca. 14th-Century one and the "Aksumite" one.

**Comment by Ralph-Lee-UK** [comment]
This is very helpful. I agree that at some point the distinction needs to be made, but for now this is enough for an interested researcher to find all the material that they need!
