### ISSUE TITLE
Claves in work records

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1495]
Apologies if I'm asking about something obvious but it bothers me. In the case of work records, should I assign a clavis only when the given sources mentions the Ethiopic version or is it allowed also when the Ethiopic version is not recorded but I have good grounds to believe that it's the same text? For example, LIT3169Cosmas may very well be BHO 210, but the Ethiopic version is not mentioned in the BHO.

**Comment by PietroLiuzzo** [comment]
if with assigning a clavis you mean adding a listBibl[@type='clavis'] and you are sure, I see no issue in adding that information, you may leave a note with your argument as well, if you want. https://betamasaheft.eu/Guidelines/?q=clavis&id=work-teiHeader
