### ISSUE TITLE
The Book of the Order of the Disciples

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1497]
I have two mss in the EMIP collection with a book with this title, the first page of one of them is attached. There does not appear to be a work record for this. Can anyone help?

![image](https://user-images.githubusercontent.com/39619238/94258714-2a7e1400-ff25-11ea-90da-885e225812b7.png)

**Comment by DenisNosnitsin1970** [comment]
this is one of the versions of the apocryphal acts of the apostles, with an introduction. i see this version, e.g., in ms esmgm007. please have a look into the recent articles of vitagrazia pisani on the mss of the Acts of the apostles from Ethio-spare, for sure she elaborated on this point.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 many thanks for this. There are four work files with the title 'Book of the Disciples', LIT3945ArdeetBE, LIT3942ArdeetCh, LIT1915Mashaf, LIT1828Mahale - is one of these the correct work file to use?

**Comment by DenisNosnitsin1970** [comment]
LIT3945ArdeetBE is  obviously the Beta Israel version. I see now that it is attested in only one Ethio-Spare Ms that is considered a Beta Israel manuscript (there is no word on the content as to if it is different from the Christian Mashafa Ardeet - Dorothea, this is an issue, someone should do this).   LIT1828Mahale - it is something completely different; LIT1915Mashaf is the right one, but I do not see why you need it. The introduction mentioned above is unlikely "Mashafa ardeet",, it only mentions "disciples", doesn't it?

**Comment by thea-m** [comment]
@DenisNosnitsin1970 regarding LIT3945ArdeetBE, someone who has worked with it should elaborate the records.
I wonder however how the Ardeet discussion came about - isn't the image above related to LIT1461Gadlah?

**Comment by DenisNosnitsin1970** [comment]
"Ardeet" is mentioned in the text above. I meant only specific marking features of the BE versus Christian versions. Christian versions are also not homogeneous, most probably, as "Ardeet" appears both as part of some other works and as isolated work of itself.

**Comment by thea-m** [comment]
I was just surprised, as you wrote earlier that this version resembles esmgm007, which contains Acts of the Apostles, no Ardeet.

**Comment by DenisNosnitsin1970** [comment]
But the manuscript in question contains apocryphal Acts, not Ardeet. However, the Book of the Disciples is not related to the issue, as far as I understand.

**Comment by DenisNosnitsin1970** [comment]
Dear Ralph, you need only "apocryphal Acts of Apostles" for that item, please use the general ID if you do not find the one fitting this version.

**Comment by Ralph-Lee-UK** [comment]
All clear now, many thanks!
