### ISSUE TITLE
Homiliary of the Savior of the World, Dǝrsanä Mädḫane Aläm, ድርሳነ፡ መድኃኔ፡ ዓለም፡?

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1500]
In EMIP 812 I have the work with the attached images. It is recorded in a datasheet as ድርሳነ፡ መድኃኔ፡ ዓለም፡ for which I cannot locate a work file. Can anyone identify the work, and its work file?
![image](https://user-images.githubusercontent.com/39619238/94672236-e2883400-030c-11eb-8245-8df53adc4b0f.png)
![image](https://user-images.githubusercontent.com/39619238/94672254-e6b45180-030c-11eb-95d7-e147e6e6a822.png)
![image](https://user-images.githubusercontent.com/39619238/94672291-f6cc3100-030c-11eb-8bab-99f07756f7bf.png)

**Comment by DenisNosnitsin1970** [comment]
it is still the ornate inroduction, exeptionally long. does the work proper sensu starts somewhere?

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 apologies - I thought I had got to the start, but you are quite right! Here are some further images:

![image](https://user-images.githubusercontent.com/39619238/94675244-54fb1300-0311-11eb-8f50-09cf425dce49.png)
![image](https://user-images.githubusercontent.com/39619238/94675295-69d7a680-0311-11eb-975e-1538372655f3.png)
![image](https://user-images.githubusercontent.com/39619238/94675307-6d6b2d80-0311-11eb-9646-723d890e8808.png)
![image](https://user-images.githubusercontent.com/39619238/94675254-5a585d80-0311-11eb-93c2-9959d8681dbf.png)

**Comment by DenisNosnitsin1970** [comment]
This seems to be one of the versions of Zena hemamatihu la-Krestos, a work from the "cycle of Medhane Alam" (though the long introduction looks strange). It appears mostly in modern manuscripts, it is possible that we have no IDs. 
Have a look in the article of P. Piovanelli in "Linguistic, Oriental and Ethiopian Studies in Memory of Paolo Marrassini", you will find useful information.

**Comment by Ralph-Lee-UK** [comment]
Very helpful. Should we create a work file?

**Comment by DenisNosnitsin1970** [comment]
We will need if we do not have one, at least one general record for all versions. In recent manuscripts they are numerous, and they are frequent in "accordion books".

**Comment by Ralph-Lee-UK** [comment]
Good. Would you do that, or should I?

**Comment by DenisNosnitsin1970** [comment]
Ok, I will do it.

**Comment by PietroLiuzzo** [comment]
really, issue 1500!!

**Comment by thea-m** [comment]
@DenisNosnitsin1970 , have also a look at https://github.com/BetaMasaheft/Documentation/issues/1501.

**Comment by DenisNosnitsin1970** [comment]
Two issues opened at the same time, dedicated to the same topic, not interlinked?

**Comment by thea-m** [comment]
People think independently from each other :) As soon as I noticed, I interlinked.

**Comment by DenisNosnitsin1970** [comment]
Hmm, what a coincidence...

**Comment by DenisNosnitsin1970** [comment]
Fine. But there is still smth that I do not understand about this EMIP text. It is different from those listed in Povanelli, isn't it? The texts in Piovanelli are very short, they only list the sufferings, one ms page.

**Comment by DenisNosnitsin1970** [comment]
Ralph, from which collectio does this ms come from, or does it have another shelf-mark? What I have as EMIP 811 is different.

**Comment by Ralph-Lee-UK** [comment]
Sorry, I wasn't able to attend to this for a couple of days. Is there now a work file?

**Comment by DenisNosnitsin1970** [comment]
Dear Ralph, I would like to consult the entire manuscript, it is a bit difficult case. It is not what I originally thought it is. Can you make the ms accessible to me, or just say what is another shelf-mark? I have many EMIP mss, but my EMIP 811 is different.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 Apologies, another of my comments didn't save! this is EMIP 812, not 811 (I have corrected this in the initial entry of this issue now). There is a PDF of the whole manuscript that you can obtain from this link https://1drv.ms/b/s!AsYm6VrVJ3xVlad3hENFyAESLoylDw?e=PYjCKr

**Comment by DenisNosnitsin1970** [comment]
Ralph, i found these texts, with some difficulty though. This is a complex case. Unless i overlooked smth, a manuscript of the same content is BNF Ethiopien 116, ff. 6r-36v, accessible on-line (in the beginning the witnesses do not coincide, possibly before ናንቅህ ርእሰ f. 4v, but further they do). This ms is catalogued in BM, but very  summarily, following the catalogue of Zotenberg. There are some IDs in it, but they should be checked and the definition "Dersan mahyawi" as well because there is another work called like this, recent, but quite frequent in the manuscripts.  Another witness is Abbadie 29 (the ms is not catalogued in BM). Both manuscripts were used in an edition which I append here
[Une_christologie_veterotestamentaire_Edi.pdf](https://github.com/BetaMasaheft/Documentation/files/5318890/Une_christologie_veterotestamentaire_Edi.pdf). Now, EMIP 812 is the third witness.
 So the task seems to be complex now. It looks like you need to dissimilate this work(s)/record(s) from the current Dersana Mahyawi LIT1291Dersan, look how this text in EMIP 812 etc. organized and new ID(s) will be needed. Do you want to undertake this?

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970  this is very helpful indeed! At the moment I don't have the time to do this properly! I can set it aside to do later, unless someone in Hamburg could do it. Let me know what is best.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970  this is very helpful indeed! At the moment I don't have the time to do this properly! I can set it aside to do later, unless someone in Hamburg could do it. Let me know what is best.

**Comment by DenisNosnitsin1970** [comment]
OK, i can finish this.

**Comment by Ralph-Lee-UK** [comment]
Very grateful for this.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 I have another one to add to this. EMIP 149 is catalogued as 'Homiliary of the Saviour of the World' and the first folio reads thus:

![EMIP00149_Weiner44_004](https://user-images.githubusercontent.com/39619238/100375368-99e7b100-3005-11eb-8b00-f9ac8aebb66c.JPG)

There doesn't appear to be a work file for this one, which I acknowledge seems to be quite different from the one above

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 can you check if a new work ID should be created? Thank you

**Comment by DenisNosnitsin1970** [comment]
Sure, I will do this.

**Comment by DenisNosnitsin1970** [comment]
Dear Ralph, it looks like the beginning of the homily from the "cycle of Mabˁa Ṣəyon", which normally includes: 1) Homily on the Saviour of the World (not homiliary), 2) Book for the Commemoration of the Saviour of the World, 3) Image of the Saviour of the World. 
 It is a recent collection with sophisticated structure; in the second work, "Book of the Commemoration", the Life of St Mabˁa Ṣəyon + Miracles is included. Other types of structure partition might also be possible, of course. BM has no properly described manuscripts of with this work yet, but there is a number in EthioSpare/DomLib, with detailed content description (as above). Can you consult them?

**Comment by Ralph-Lee-UK** [comment]
This is very helpful, and yes on more detailed inspection the Life of Mabˁa Ṣəyon and the other content that you mention are there, and some miracles of Jesus, among other things. I would be happy to consult the EthioSpare material - can you point me to the right link to start with?

**Comment by DenisNosnitsin1970** [comment]
Try this, https://mycms-vs03.rrz.uni-hamburg.de/domlib/content/main/manuscript/manuscript.xml , go for "manuscripts" "search" "in the metadata", Mabˁa Ṣəyon

**Comment by DenisNosnitsin1970** [comment]
Try Mabˁa Ṣəyon in the search of BM

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/facet.html?query=%22Mab%CB%81a+%E1%B9%A2%C9%99yon%22

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 has this been solved? 
I believe this issue (?) has once again been reopened as https://github.com/BetaMasaheft/Documentation/issues/2077 and both appear open

**Comment by eu-genia** [comment]
can you list here the relevant CAe IDs? thank you

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 in this issue the records were requested for
- Zena hemamatihu la-Krestos (also here https://github.com/BetaMasaheft/Documentation/issues/1501)
- Homily on the Saviour of the World (also here https://github.com/BetaMasaheft/Documentation/issues/2077)

can you please put here the CAe IDs of the records created? Many thanks!
