### ISSUE TITLE
Homily of Hǝrǝyaqos on the Honour and Purity of Mary....

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1502]
The work below does not appear to have a work file. Can anyone help me identify it, and its work file?
![image](https://user-images.githubusercontent.com/39619238/94674101-9985af00-030f-11eb-9a4f-23f1cc4a4ec3.png)

**Comment by thea-m** [comment]
I think it's LIT1750LahaMa

**Comment by MarcinKrawczuk** [comment]
@Ralph-Lee-UK My guess would probably be LIT3998Dersan (see the linked record BLorient 775, it has incipit)

**Comment by thea-m** [comment]
Yes, both records seem to have been used to refer to the same work. Please use LIT1750LahaMa (the older one), I will open a separate issue to deal with the doublet.

**Comment by Ralph-Lee-UK** [comment]
Thank you! This is helpful.
