### ISSUE TITLE
New work records for መልክአ፡ እድና፡ and መልክአ፡ ኪዳነ፡ ምሕረት፡ (alternate)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1503]
In which manuscript is the work you would like to create attested? 

- Vat. Borg. et. 22 (= Borg. L. V. 13)

If possible, give a link to or quote from the catalogue description:

1. መልክአ፡ እድና፡ (mother of Zamikāʾel ʾAragāwi)
     - Incipit: ለወሀቤ፡ ሀብታት፡ እግዚአብሔር፡ ዘሠናይ፡ ሀብቱ፡ ወላዲቱ፡ ድንግል፡ ወሀቢተ፡ ጸጋ፡ በከንቱ፨ አስተብቍዒዮሙ፡ እድና፡ ወአልዕሊዮሙ፡ በእንተ፡ ዝንቱ፨ የሀቡኒ፡ ሀብተ፡ ክሂል፡ ዘግብረ፡ ተሥእኖ፡ አልቦቱ፨
     - Explicit: ሰ(ላም፡ ለኪ)፨ ምስለ፡ ወንጌላዊ፡ ዮሐንስ፡ ሐዋርያ፡ ዕልት፡ ዘለኪ፡ ወዘሚካኤል፡ ፍሬ፡ ከርሥኪ፨ እምሄውትየ፡ እድና፡ ለወልደ፡ ወልድኪ፡ ማኅሌትየ፡ ባርኪ፡ ባርኪ፨

2. መልክአ፡ ኪዳነ፡ ምሕረት፡ (alternate)
     - Incipit: ሰላም፡ ሰላም፡ ለዝክረ፡ ስምኪ፡ ጥዑም፡ ለሥዕርትኪ፡ ድሉል፡ ወለገጽኪ፡ ግሩም፡ ኪዳነ፡ ምሕረት፡ ማርያም፡ ወትምክሕተ፡ ኵሉ፡ ዓለም፡
     - Explicit: ስብሐት፡ ለኪ፡ ማርያም፡ በኍልውዐ፡ ዓመታት፡ ወአዝማን፡ ሰብሐት፡ ለኪ፡ ማርያም፡ እምንባበ፡ ኵሉ፡ ልሳን፡ ምሉእ፡ ስብሐትኪ፡ በኵሉ፡ መካን።

Further information or questions on this work:

I haven't found any other manuscripts containing መልክአ፡ እድና፡ (at all), despite looking quite a bit. Also, having looked through many መልክእ፡ incipits, I still have not seen this one for ኪዳነ፡ ምሕረት፡. The manuscript also contains መልክአ፡ ዘሚካኤል፡ አረጋዊ፡ (Chaîne no. 278).

**Comment by thea-m** [comment]
I also don't find these, so would agree with creating new IDs.

**Comment by eu-genia** [comment]
Sorry I did not see this issue (was not tagged?)
have you checked 
LIT1854Malkea
LIT1855Malkea

**Comment by smaugustine** [comment]
LIT1854Malkea is actually a duplicate of LIT3082RepCh362, which is the standard መልክአ፡ ኪዳነ፡ ምሕረት፡ (እግዚአብሔር፡ ወሃቤ፡ ብርሃን፡).

LIT1855Malkea has no text and no manuscripts contain it, but I would imagine it's also a duplicate of the latter.

From my own survey of መልክአ፡ ጉባኤ፡ manuscripts and my own list of incipits for መልክእ፡, the one here (ሰላም፡ ሰላም፡ ለዝክረ፡ ስምኪ፡ ጥዑም፡) seems to be a separate composition.

**Comment by eu-genia** [comment]
This means we also have to
(1) delete LIT1854Malkea merging it to LIT3082RepCh362
(2) I guess delete LIT3080RepCh360 which also points to LIT3082RepCh362 but still exists in the app
(3) delete LIT1855Malkea merging it to LIT3082RepCh362
correct?

**Comment by smaugustine** [comment]
Yes, indeed.

There seems to be a pattern of duplicate records for works in Chaîne's _Répertoire_, which itself already has duplicate entries.

**Comment by smaugustine** [comment]
I can take care of this, there aren't so many to go through in this case.

**Comment by eu-genia** [comment]
Thank you

**Comment by eu-genia** [comment]
NB: I believe the hymn in [EMIP00480 ](https://betamasaheft.eu/manuscripts/EMIP00480/main) currently identified as LIT1854Malkea is not LIT3082RepCh362 but the new one you created, LIT6191Malkea, as the incipit quoted is ሰላም፡  ሰላም፡  ለዝክረ፡  ስምኪ፡  ጥዑም፡
