### ISSUE TITLE
Three Marian homilies

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1507]
I would appreciate every help in identifying these three homilies on Mary from EMML 8897.

1) 
![89r](https://user-images.githubusercontent.com/62760230/94844940-3e42e200-041f-11eb-8f7b-46a9cc2d6f43.png)

This one appears sometimes in Retua Haymanot homiliaries e. g. Tanasee 142 = Daga Estifanos 29 f. 104r-119r or EMML 2375, f. 109r-122r

2) 
![115v](https://user-images.githubusercontent.com/62760230/94845051-692d3600-041f-11eb-8a97-4b6f031bd4b3.png)
Here I don't have a clue.

3) 
![160v](https://user-images.githubusercontent.com/62760230/94845155-94b02080-041f-11eb-96ed-6f812cf203f5.png)

This one is quite popular e. g. BL Orient. 692, Vat et 268, BnF d'Aabb 158, EMML 1763 and many more. @DariaElagina @DenisNosnitsin1970 @thea-m

**Comment by thea-m** [comment]
Hi! The beginning of the second text seems to be identical to LIT2252salota, see for example https://betamasaheft.eu/manuscripts/BNFet67/main or https://betamasaheft.eu/manuscripts/ESmr004.xml. Maybe you could compare the rest of the text in these and your manuscripts.

**Comment by thea-m** [comment]
The other ones I don't find now either. If no one else has an idea, new IDs could be created.
