### ISSUE TITLE
መልክአ፡ ሕማም፡ Duplicates

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1508]
Another set of duplicates from Chaîne, nos. 25 and 26 (= LIT2741RepCh25 and LIT2742RepCh26). In this case, the first two stanzas may be copied out of order, leading to two entries in his Répertoire.

መልክአ፡ ሕማም፡ was edited by Getatchew Haile (_Tradition on the Holy Cross_, 1.5), and in this edition he gives the stanzas in this order:

1. ሰላም፡ ለሕማምከ፡ ቤተ፡ አይሁድ፡ ዘአንደደ። ...
2. ሰላም፡ ለሕማምከ፡ ቤተ፡ አይሁድ፡ ዘአመዝበረ። ...

(@eu-genia)

**Comment by eu-genia** [comment]
Thank you, these of course should be merged to LIT2741RepCh25; shall you take care of it?

**Comment by smaugustine** [comment]
My pleasure.
