### ISSUE TITLE
New work record for Malkǝʾa Śǝllāse

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1510]
In which manuscript is the work you would like to create attested? 
- BGV-003 (Veroli collection)

Or for which other reason would you like to create this new record?
- unrecorded version of the Malkǝʾa Śǝllāse (incomplete in the Ms, but comprises at least 50 strophes prasing the Trinity)

If possible, give a link to or quote from the Ms:
```
<incipit xml:lang="gez">
                           <locus target="#1ra"/>
                           <pb n="1r"/>
                           <cb n="a"/>
                           <hi rend="rubric">ሰላም፡ ለሕላዌክሙ፡ ዘኢይት፡</hi> ዓወቅ፡ ጥንቱ፡ ወኢይትዓመር፡ ተፍጻሜቱ፡
                           አጋእዝትየ፡ <hi rend="rubric">ሥላሴ፡</hi> ዘኢትመውቱ፡ እንዘ፡ ፫፩ወእንዘ፡ ፩፫ቱ፡ ዕበይክሙ፡
                           ተፍጻሜ፡ አልቦቱ። <hi rend="rubric">ሰላ፡</hi> ለዝክረ፡ ስምክሙ፡ ዘይጥዕም፡ እምሀሊብ። ወእምነ፡
                           መዓር፡ ፃማ፡ እደ፡ ገብሩ፡ ለንህብ። </incipit>
                        <explicit xml:lang="gez">
                           <locus target="#3vb"/><hi rend="rubric">ሰ፡</hi> ለቆምክሙ፡ አጋእዝትየ፡ <hi
                              rend="rubric">ሥላሴ፡</hi> ዳ<gap reason="illegible" unit="chars"
                              extent="2"/> ነቢይ፡ እንዘ፡ ይብል፡ ሃሌ፡ ይቤሎ፡ እግዚ<gap reason="illegible"
                              unit="chars" extent="1"/>፡ ለእግዚእየ፡ ንበር፡ በየማንየ፡ ወልድ፡ <gap
                              reason="illegible" unit="chars" extent="1"/>ሂል፡ እግዚአብሔር፡ ካዕበ፡ አርአየ።
                              <gap reason="illegible" unit="chars" extent="2"/>ዕክሙ፡ አጋእዝትየ፡ <hi
                              rend="rubric">ሥ፡</hi> በከመ፡ ሙሴ፡ በውስተ፡ ኦሪት፡ እንዘ፡ ይብል፡ ተርጐ<gap
                              reason="illegible" unit="chars" extent="2"/> ብሔር፡ እግዚእ፡ እምቅድመ፡ <gap
                              reason="lost" extent="unknown"/></explicit>
```

**Comment by DenisNosnitsin1970** [comment]
It seems to be not malk', is a work which called ውዳሴ፡ ዘማልክአ፡ ሥላሴ attested, according to Zarzeczny, "Inventarion dei manoscritti...", 2014, no. 29; he indicates one of the printed editions of Malke'a guba'e in which it has been published.

**Comment by SusanneHummel** [comment]
Thank you I will check it!

**Comment by SusanneHummel** [comment]
The manuscript MS 29, which Rafał described, has been digitized by Ethio-SPaRe (ACTC-015). So, I had a closer look. In fact, it contains a text very similar to the one in BGV-003. There are more strophes in Ms 29/ACTC-015, which also contain a different number of verses (2 to 5). To me it still looks very much like a Malkǝʾa-hymn in style and content, but we can take the title as given in Ms 29/ACTC-015 ‘Wǝddāse zaMalkǝʾa Śǝllāse’. I have no preferences. 

For the work file I would specify Incipit and Explict as they are in Ms Ms 29/ACTC-015. I have transcribed again, because there are some typos in the catalogue. Would it be better to normalize and correct the punctuation for the work file or shall I leave the text as written in the Ms (as below)?


Incipit
ውዳሴ፡ ዘመልክዐ፡ ሥላሴ፡ ሰላም፡ ለህላዌክሙ፡ ዘኢይትዓወቅ፡ ጥንቱ፡ ወኢይትአመር፡ ተፍጻሜት። አጋእዝትየ፡ ሥላሴ፡ እለ፡ ኢትመውቱ፡ እንዘ፡ ፫፩ወእንዘ፡ ፩፫ለዕበይክሙ፡ ፍጻሜ፡ አልቦቱ ። ሰላም፡ ለሥላሴክሙ፡ ለድማሬክሙ። ወዕሪናክሙ፡ ለህላዌክሙ፡ ወመለኮትክሙ። ለስብሐቲክሙ። ወመንግሥትክሙ።

Explicit
ሰላም፡ ለተከስቶትክሙ፡ በቤተ፡ አብርሃም፡ ወደብረ፡ ሲና። በውስተ፡ ዮርዳኖስ፡ ወታቦር፡ በቅድመ፡ ሕዝባ፡ ለዲና። አጋእዝትየ፡ ስላሤ፡ ምሉአነ፡ ጥበብ፡ ወልቡና፡ እምብዙኅ፡ ስብሐቲክሙ፡ ዘያስተፌሥሕ፡ ሕሊና። ውሑደ፡ ነገርኩ፡ ይኩነኒ፡ ምዝጋና።

**Comment by DenisNosnitsin1970** [comment]
You do not need to normalize the orthography in the work file, you just specify that you follow one specific manuscript. 
Alternatively you can quote also an Ethiopian edition of the work, 
if you find it the book indicated by Rafal or any other  church edition of Malke'a guba'e. The title is strange, indeed.

**Comment by MassimoVilla** [comment]
One small remark: we decided in a previous meeting (regarding the Bodleian mss though) that "a space is added between numeral and words (to facilitate filtered search); no space within composed numerals". So, `፫፩ ወእንዘ፡ ፩፫ ለዕበይክሙ፡`, right?

**Comment by SusanneHummel** [comment]
Thank you! 
I checked the available church edtions in our library and could not find it.
The reference in the catalogue 'ed. AA, 317-37', however, is not clear to me as no title and no year is given.

**Comment by DenisNosnitsin1970** [comment]
Indeed, it is only unspecified AA (no year?), at least in the version of the article that is on-line (right?). It looks like he wants to ay that the work is edited.  May be you can just ask Rafal directly, it is an interesting question.

**Comment by SusanneHummel** [comment]
I think this can be closed.
