### ISSUE TITLE
Visualizing formerlyListedAs

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1511]
What do you see?
The General Description lists all relations - but it should skip the formerlyListedAs relation which results in noItem display

Can you please give a link to an example?
See LIT2741RepCh25
![image](https://user-images.githubusercontent.com/17987728/95326922-9bb5b380-08a3-11eb-997c-c341acb6a2eb.png)

What is wrong with it?
It correctly say above "This record was formerly also listed as LIT2742RepCh26" (and redirects from there) but it also under General Description has "See No item: LIT2742RepCh26 = CAe . "

What would you like to see?
the relation of formerlyListedAs should not reappear under General Description or in the analytical view

**Comment by eu-genia** [comment]
I now see that the whole part of "See" with the list of relations disappeared - this is a pity, I actually found it very helpful, since the analytical view takes ages to load, I only wanted the relation of "formerlyListedAs" become invisible...

**Comment by PietroLiuzzo** [comment]
in this record there is only the formerlyListedAs relation. that excluded there is nothing to show for See... i.e. relations encoded within that record. the analytic view loads any relations, including those pointing to the present element. The See section disqualifies the named relations, while both the side bar with the relation lists and the analytic view preserve the link qualification.
