### ISSUE TITLE
New work records for Prayers against the Serpent

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1513]
In BGV-003 (Veroli collection) there are two different prayers, a longer and a shorter one; see the transcription below and the references.
There seems to exist a great variety of „Prayers of the Serpent“. 

The clavis has so far only one entry; LIT4328SalotaArwe (LIT5131MagicPrayer  “Magic Prayer Against Snakes” is of different kind). This entry, however, does not provide any text which makes it impossible to disambiguate the different Prayers of the Serpent; it might have been created for all occurrences where no text is available (?).

Another version (other than those included in BGV-003) of the “Prayer of the Serpent” is attested in EMIP00227 (the incipit is given here) and linked to CAe 5888 (ʾAsmāt-prayer (general record)).
Furthermore, we find different mention of this prayers in additions (without clavis reference and without text):
EMIP00499: Asmat Prayer against snake, ጸሎተ፡  ዓርዌ፡  ምድር፡
EMIP02081: Asmat prayer against snakebite, ጸሎተ፡  ዓርዌ፡  ምድር፡
EMIP02103: Asmat prayer against snake, ጸሎተ: ዓርዌ: ምድር፡,

I suggest to create two more work files for the two different versions attested in BGV-003:

1. longer version, see bm:Six1994VOHD6, p. 73 (Hs. 7, X 1)

```
 <seg part="I">ጸሎት፡ በእንተ፡ አርዌ፡ ምድር፡ ሶበ፡ <add place="above"
                                       >መጽአ፡</add> መልእክት፡ እኂዘከ፡ ዘፈረ፡ ልብሱ፡ ለእመ፡ ሀሎ፡ ርኁቀ፡ አስትዮ፡ ለላዕኩ፡
                                    ወየሀዩ፡ እግዚኡ፡ በስመ፡ እግዚእ፡ በስመ፡ ቀዳማዊ፡ በቃለ፡ እግዚእ፡ ጸንዓ፡ ሰማይ፡ ወምድር፡ </seg>

                                 <seg part="F">
                                    <pb n="168vb"/> ኢየሐምም፡ ለጸላኢ፡ አልቦ፡ ኃይል፡ ወአ<pb n="169ra"/>ልቦ፡ ጽንዕ፡
                                    እንበለ፡ እግዚአብሔር፡ ክቡር፡ ወልዑል፡ ለዓለመ፡ ዓለም፡ አሜን። ፯በማይ፡ ድግም። </seg>
```

2. short version; simliar to the one preserved in Ms. DDm-018, fols. 3v-4v (Ethio-SPaRe)

```

 <q xml:lang="gez"> ጸሎተ፡ አርዌ፡ ምድር፡ በስምከ፡ ኪንድ፡ <gap reason="illegible"
                                    unit="chars" extent="1"/>ድር፡ ንቋዕ፡ ላላደ፡ ይቤፌ<gap
                                    reason="illegible" unit="chars" extent="1"/>፡ ጡጡራን፡ ቀረዓዱን፡ ደመ፡
                                    <gap reason="illegible" unit="chars" extent="1"/>ራን፡ በከመ፡ ስምከ፡
                                 ይኩን፡ ይጻእ፡ ወይልሳሕ፡ ሕምዘ፡ ተመን፡ ሕምዘ፡ ከይሲ፡ ሕምዘ፡ አፍዖት፡ አንተ፡ ከይሲ፡ አይቴ፡
                                 ነበርከ፡ ዘነሰከ፡ ወዘአንሰከ፡ ኅድግ፡ ይቤሉከ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ለገብርከ፡ እገሌ።
                                 ዕፀ፡ ሰመግ፡ ዘዌ፡ የጸጅማጸባ፡ አ<add place="above">ም</add>ፋር፡ ቕፍርግ፡ <gap
                                    reason="illegible" unit="chars" extent="1"/><pb n="169rb"/>
                                 እምስረዊሙ፡ ለእሉ፡ ዕፀዋት፡ አጥዕሞ፡ ለዘ<add place="above">ተ</add>ነስከ ። ጸሐፊሁ፡
                                 ገብረ፡ ሥላሴ፡ በመንግሥተ፡ ኢዮአስ፡ ንጉሥ፡ </q>
```

**Comment by DenisNosnitsin1970** [comment]
If there is no text quotation in the manuscript in question there is no way to record the text except creating a new ID for it, in the hope that  it can be checked in the future. Arwe prayer may be many and all different, not necessarily versions of each other (the title rather denotes the function, it is not really the proper title).

**Comment by thea-m** [comment]
Yes, these are always confusing...I agree with Susanne's proposal for two new records, since she will include the incipits and explicits. I would also suggest to explicitly make LIT4328SalotaArwe a general ID for cases in which only "ጸሎተ፡ ዓርዌ፡ ምድር፡" or similar is given in the catalogues without further possibility of identification.

**Comment by DenisNosnitsin1970** [comment]
Yes, why not. Should a deneral ID have no text then?

**Comment by thea-m** [comment]
Not as a rule, but in principle, general IDs are mostly used when there are several recensions for cases in which the recension is not known. Hopefully, if one had a text, the recension would be identifiable or a specific ID could be created.

**Comment by SusanneHummel** [comment]
I close it
