### ISSUE TITLE
EMIP 764 Collection of Hymns

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1515]
I have worked through a large Malk;a Guaba'e and have identified most of the works. The following have stumped me (and I may have just missed something simple!). @smaugustine this is the PDF that you downloaded the other day. Any assistance gratefully received!

The following is a Hymn to the Trinity, and does not seem to correspond to any of Chaine's records
![image](https://user-images.githubusercontent.com/39619238/95611433-baf64180-0a59-11eb-8196-996367906f73.png)

The following is a Hymn to Mary, for which I can't find the Chaine number:
![image](https://user-images.githubusercontent.com/39619238/95611572-e8db8600-0a59-11eb-8358-c9a48f5bd76d.png)
 
And a Hymn to Stephen:
![image](https://user-images.githubusercontent.com/39619238/95611614-f55fde80-0a59-11eb-8cc6-ec7ed4e92364.png)

And another to Tewodros:
![image](https://user-images.githubusercontent.com/39619238/95611643-03156400-0a5a-11eb-8eef-15d7a31e54db.png)
![image](https://user-images.githubusercontent.com/39619238/95611654-07418180-0a5a-11eb-8789-04885b425204.png)

And a Hymn to St Victor
![image](https://user-images.githubusercontent.com/39619238/95611684-11638000-0a5a-11eb-8aee-3b8dbc1fe12e.png)

And one to Gabra Masqal
![image](https://user-images.githubusercontent.com/39619238/95611707-1d4f4200-0a5a-11eb-99c3-89192b440a46.png)

And then the final work:
![image](https://user-images.githubusercontent.com/39619238/95611736-28a26d80-0a5a-11eb-8c8d-893ca6389f33.png)

**Comment by smaugustine** [comment]
Most of these መልክኣት፡ seem to differ from the more typical versions found in MSS. I will keep checking to see if they occur elsewhere, but I don't immediately recognize them.

The second one is actually for Hanna, the mother of Mary, and there are numerous ones for one or both of Joachim and Hanna (as is the case with this MS). The last was very new to me, a መልክእ፡ for the "Holy Innocents".

As a whole it is an interesting MS, clearly put together for the celebration of ማኅሌት፡ (as it is in current practice), beginning with ነግሥ፡ ዘማኅሌት፡, the festal ነግሥ፡ stanzas, then መልክኣት፡ arranged by their corresponding feast..

**Comment by Ralph-Lee-UK** [comment]
So to start with we should probably think of creating a new work file for the Malk'ǝ for the Holy Innocents. @DenisNosnitsin1970, @thea-m would you agree with this idea?

**Comment by thea-m** [comment]
I also couldn't find existing IDs for these hymns. I would be in favour of creating new IDs for all of them. Let me know if you'd like me to do this.

**Comment by DenisNosnitsin1970** [comment]
Indeed, there is no other way but creating new IDs.

**Comment by Ralph-Lee-UK** [comment]
I'll do this as soon as possible
