### ISSUE TITLE
EMIP 775 Prayer appended to Wǝddāse ʾAmlāk 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1517]
The prayer on the right hand page is appended to Wǝddāse ʾAmlāk in this mss - any ideas on what it may be? 
![image](https://user-images.githubusercontent.com/39619238/95731258-31bc5600-0c77-11eb-87b2-bed986de876b.png)

**Comment by DenisNosnitsin1970** [comment]
You have ወአንቲሂ....በዕብራይስጢ Mአሪሃም in Arganona Weddase (ed. Leander).

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 many thanks - it's in the section for Monday!
