### ISSUE TITLE
Create New Record for Hymn for the Miracles of ʾEwosṭātewos

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1518]
EMIP 764 (84r) and Vat Borg et 9 (53v) both contain a hymn with the following stanza:
> መንክራቲከ፡ ሰማዕነ፡ እንዘ፡ ትነብር፡ አርማንያ፡ መካነ።
> ኤዎስጣቴዎስ፡ ተአምር፡ በኢትዮጵያ፡ ዘኮነ።
> መርበብቶ፡ ኢይስፋሕ፡ ውስተ፡ ማኅበርነ።
> ትትበአስ፡ መስተቃርነ፡ ብጽሐነ፡ ፍጡነ።
> ዘተሠርኀከ፡ ስነ፡ ጳዝዮን፡ አቡነ።

This is followed by three more stanzas and then Chaîne 333 (one stanza) and 323 (around a dozen stanzas).

I would have considered having one work record for all of these, numbering the stanzas in the body for references (#stanza1 etc.), but now I'm not sure, since EMIP 480 does not include "መንክራቲከ፡ ..." or 323, beginning only with 333.

So, then, I suggest simply creating a new work for "መንክራቲከ፡ ..." (a poem of 4 stanzas). It would then work out that:

| MS                 | -<br>"መንክራቲከ፡" | Chaîne 323<br>"አናኅኩ፡" | Chaîne 333<br>"እምብዙኅ፡" | Chaîne 353<br>"እንዘ፡ ሀሎኩ፡" |
| ------------- |:-------------------:|:-------------------------:|:---------------------------:|:-------------------------------:|
| BL Or 641      |      |      |      | ✓ |
| BL Or 577      |  ?  |  ?  |  ?  | ✓ |
| BL Or 702      |      | ✓ | ✓ | ✓ |
| BL Or 829*    |      |  ?  | ✓ | ✓ |
| EMIP 480       |     |     | ✓ | ✓ |
| EMIP 764       | ✓ | ✓ | ✓ | ✓ |
| Vat Borg et 9 | ✓ | ✓ | ✓ | ✓ |
| ONB Aeth 22 |     |      |     | ✓ |

What do you think, @eu-genia and @Ralph-Lee-UK?

(Postscript, it's possible there's some variation in length for 353, similar to the variation with the other items, but this would require further, closer examination)

**Comment by eu-genia** [comment]
I would be for a new record for the previously unrecorded hymn (plus possibly additionally a new overarching record for the constellation of hymns, just as there are overarching records for "hagiographic collections" which may or may not include all elements)
