### ISSUE TITLE
Visualization of illegible character not correct in the App

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1519]
The text of 

https://betamasaheft.eu/works/LIT6196PrayerSerpent2/text

is displayed not in a correct way beacuse the 'illegible' characters do not appear. It should be displayed by a specifig sign that somehow replaces the missing/illegibel charcters of the text. Otherwise the App displays an incomplete text without marking it.

I encoded: 
 ```
<div type="edition">
                <note>The text is taken from <ref type="mss" corresp="BGV003#a2"/>.</note>
                <div type="textpart" xml:lang="gez">
                    <ab> ጸሎተ፡ አርዌ፡ ምድር፡ በስምከ፡ ኪንድ፡ <gap reason="illegible" unit="chars" extent="1"
                        />ድር፡ ንቋዕ፡ ላላደ፡ ይ ቤፌ<gap reason="illegible" unit="chars" extent="1"/>፡ ጡጡራን፡
                        ቀረዓዱን፡ ደመ፡ <gap reason="illegible" unit="chars" extent="1"/>ራን፡ በከመ፡ ስምከ፡
                        ይኩን፡ ይጻእ፡ ወይልሳሕ፡ ሕምዘ፡ ተመን፡ ሕምዘ፡ ከይሲ፡ ሕምዘ፡ አፍዖት፡ አንተ፡ ከይሲ፡ አይቴ፡ ነበርከ፡ ዘነሰከ፡
                        ወዘአንሰከ፡ ኅድግ፡ ይቤሉከ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ለገብርከ፡ እገሌ። ዕፀ፡ ሰመግ፡ ዘዌ፡ የጸጅማጸባ፡
                            አ<add place="above">ም</add>ፋር፡ ቕፍርግ፡ <gap reason="illegible"
                            unit="chars" extent="1"/> እምስረዊሙ፡ ለእሉ፡ ዕፀዋት፡ አጥዕሞ፡ ለዘ<add place="above"
                            >ተ</add>ነስከ ። ጸሐፊሁ፡ ገብረ፡ ሥላሴ፡ በመንግሥተ፡ ኢዮአስ፡ ንጉሥ፡ </ab>
                </div>
            </div>
```

**Comment by PietroLiuzzo** [comment]
please use `@quantity` instead of `@extent` as in the Guidelines https://betamasaheft.eu/Guidelines/?id=text-encoding and you will correctly get the expected "+" sign which is currently the one used to mark this (can of course be change with something else if needed)

**Comment by PietroLiuzzo** [comment]
I have added in any case support for this and rendered it with a ▧ for each unit from 1 to the value of `@extent` . this has not much sense, it is just a placeholder fix for similar instances of use of extent for quantity. `@quantity` is used to indicate the exact quantity as you are doing here (a numeric value), while `@extent` is for a less defined one, like "unknown" (and is a text value, which can of course include numbers). https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.dimensions.html

**Comment by SusanneHummel** [comment]
Thanky you for the explanaition,. I have corrected the file and will start the pull request.
