### ISSUE TITLE
Visualization of the bibliography

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1521]
The bibliography in 
https://betamasaheft.eu/works/LIT6195PrayerSerpent/main

is not correctly visualized. The "item" **Hs. 7, X 1** is not complete

I encoded:
```
<bibl>
                    <ptr target="bm:Six1994VOHD6"/>
                    <citedRange unit="page">73</citedRange>
                    <citedRange unit="item">Hs. 7, X 1</citedRange>
                </bibl> 
```

**Comment by PietroLiuzzo** [comment]
the spaces in the cited range are the issue here. the js is adding those as space separated values in a data attribute and the spaces which are already there get confused. I will see what I can do

**Comment by PietroLiuzzo** [comment]
ok, that is now viewable and this issue is sorted, however, it is still very rudimentally adding back what is missing in this case. i.e. if the `citedRange[@unit='item']` comes first, for example, this will not work.
