### ISSUE TITLE
Images not showing in EMIP records

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1525]
For most of the EMIP collection for which @facs statements have been added the images are currently not showing. When the links are clicked, the following error shows:

![image](https://user-images.githubusercontent.com/39619238/96439869-0994a000-11ff-11eb-8caf-46ea3e173a84.png)

The links for the Tweed collection are working, but none of the others.

**Comment by smaugustine** [comment]
Perhaps it's connected to [this issue](https://github.com/BetaMasaheft/Documentation/issues/1522)? It seems that BM's image server is having problems.

**Comment by PietroLiuzzo** [comment]
Restarted the server, looks to me like this closed at least this issue, please check and close or report back. thanks

**Comment by Ralph-Lee-UK** [comment]
All working now, thanks

**Comment by PietroLiuzzo** [comment]
there is already another issue open about this.

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo raising this issue again, the same error is now seen on EMIP 137, 138, 139. I have checked the code for anything obvious.

**Comment by PietroLiuzzo** [comment]
please see above, I am closing this because the same issue is already reported in another ticket and still needs a stable solution. https://github.com/BetaMasaheft/Documentation/issues/1591
