### ISSUE TITLE
Possibility of a double work record

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1526]
To be on the safe side,  I wanted to ask whether LIT1293Dersan and LIT2487Vision are perhaps not the same? @DenisNosnitsin1970 @DariaElagina @thea-m

**Comment by thea-m** [comment]
I think you accidentally copy pasted the same LIT1293Dersan twice :) Which is the other ID that you meant?

**Comment by MarcinKrawczuk** [comment]
@thea-m Of course I did, sorry. It's correct now.

**Comment by thea-m** [comment]
Yes, I think they are identical. I suggest to keep LIT2487Vision, I will update it now with the content of the other record and change the references. Thank you!
