### ISSUE TITLE
Licensing Inconsistency?

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1533]
The template-generated XML files indicate that the data is licensed CC BY-SA, but the bottom of the page in BM says that it is licensed CC BY-NC-SA. Is this a mistake? Is it a distinction between the data and the app? This could be expressed clearer.

**Comment by PietroLiuzzo** [comment]
Dear @smaugustine yes, the distinction was exactly between the app and its views and the data as such. Personally I do not recall the rationale behind this at the moment.
However, this is again a decision taken early on in the project life which I am not able to simply change or update or clarify. @abausi @eu-genia @DenisNosnitsin1970 @thea-m @DariaElagina please have your say. 
I am not sure what you mean with "template-generated".

**Comment by smaugustine** [comment]
I see. The distinction makes sense (though software is not typically licensed using CC licenses).

By "template-generated", I simply meant the XML files generated by the app itself.

Is there an info page anywhere explaining how the data/app are licensed? It might be worth putting something together that clearly lays out how everything related to the project is licensed.

**Comment by PietroLiuzzo** [comment]
The app generates a number of XML files. you mean the ones from the form for new entries?
We can certainly add a page as you suggest, ist is a good idea no doubt.

**Comment by abausi** [comment]
Sorry, I am in a (series of) meeting(s), cannot react.

Yours,

A.B.

Il 26.10.2020 12:29, Pietro Liuzzo ha scritto:

**Comment by abausi** [comment]
Please, if you agree on a decision, go on without me, I am fine with 
what you decide, and will have a look later.

Il 26.10.2020 12:30, Alessandro Bausi ha scritto:

**Comment by thea-m** [comment]
I was not involved in these decisions (as far as I remember) and have no expertise on the topic.
