### ISSUE TITLE
zotero entity for Denkschrift

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1534]
I'm not sure what the correct zotero entity for this "Denkschrift" http://menadoc.bibliothek.uni-halle.de/ssg/content/titleinfo/1433583 (bm:Brockelmann1935Transliteration) is, nothing seems really to fit. Can you help me? Is it a book?

**Comment by MarcinKrawczuk** [comment]
What's wrong with it being a book? Here for example https://stabikat.de/DB=1/XMLPRS=N/PPN?PPN=421037164 it is a book line any other.

**Comment by FrancescaPanini** [comment]
This is simply a book, the record was created correctly. I simply added the publisher when I checked it as that was missing.
