### ISSUE TITLE
Duplicates: LIT1869Malkea and LIT3118RepCh398 (and others)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1538]
LIT1869Malkea is the record for መልክአ፡ ውዳሴ፡ ማርያም፡, the versified form of ውዳሴ፡ ማርያም፡ commonly found as part of ሰዓታት፡ in the current usage (among many other places). Like ውዳሴ፡ ማርያም፡, of course, it is subdivided according to the days of the week.

Chaîne includes each of these in his _Répertoire_:

- LIT3118RepCh398 (ፈቀደ፡ እግዚእ፡)
- LIT3046RepCh326 (አክሊከ፡ ምክህነ፡)
- LIT3103RepCh383 (ኵሉ፡ ሠራዊተ፡ ሰማያት፡)
- LIT3105RepCh385 (ዕፀ፡ [sic] እንተ፡)
- LIT3010RepCh290 (ቡርክት፡ አንቲ፡)
- LIT3039RepCh319 (ንጽሕት፡ ወብርህት፡)
- LIT3019RepCh299 (ተሰመይኪ፡ ፍቅርተ፡)

These should be merged into LIT1869Malkea, with subdivisions added for each of the daily sections.

I can do this, if no one objects? (@eu-genia, @thea-m)

**Comment by eu-genia** [comment]
sounds good to me

**Comment by thea-m** [comment]
Sure, if the parts are not attested independently. Did you check this?

**Comment by smaugustine** [comment]
@thea-m I will do some digging and report back, but I strongly suspect not. Chaîne does not give any manuscripts for these entries (!), which would've helped identify if there are any such cases.

There aren't any manuscripts in BM, at least, that reference any of the Tuesday-Sunday records. The one for Monday is referenced twelve times, and I will check to make sure that these are መልክአ፡ ውዳሴ፡ and not the regular ውዳሴ፡ ማርያም፡.

**Comment by eu-genia** [comment]
just checking - when the merge was done and the records deleted - did you check that the deleted ones are not pointed to from anywhere else? if they are not and all is good the issue may be closed

**Comment by eu-genia** [comment]
Dear @smaugustine - I believe this has not been followed up on?

LIT3118RepCh398 is still there and points to LIT2509Weddas (part of) - it is also pointed to from 13 mss
![image](https://user-images.githubusercontent.com/17987728/171622193-78a6f61b-ee24-4257-9482-2c57215ec670.png)

LIT3046RepCh326 is still there and points to LIT2509Weddas (part of)
LIT3103RepCh383 is still there and points to LIT2509Weddas (part of)
LIT3105RepCh385 is still there and points to LIT2509Weddas (part of)
LIT3010RepCh290 is still there and points to LIT2509Weddas (part of)
LIT3039RepCh319 is still there and points to LIT2509Weddas (part of)
LIT3019RepCh299 is still there and points to LIT2509Weddas (part of)

LIT1869Malkea has not been updated to incorporate the hymns

Disambiguation is probably also needed between 
LIT1869Malkea 
and
LIT2509Weddas 

Can you check if something must be done here?

**Comment by eu-genia** [comment]
@smaugustine I guess never followed up on this, @thea-m can you please take it over together with the #2455? Thank you!
