### ISSUE TITLE
መልክአ፡ ሥዕል፡ Duplicates

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1539]
It seems that the original record for መልክአ፡ ሥዕል፡ is LIT1864Malkea and that LIT2748RepCh32 is simply a duplicate (and unused at that).

Related is LIT3088RepCh368 (ኦርኅርኅተ፡ ኅሊና፡ ...), which is very often (almost always) at the beginning of መልክአ፡ ሥዕል፡ (ሰላም፡ ለሥዕልኪ፡ ዘይዔድም፡ ...) — this is the case with the edition by Alcide Roman and made clear in EMML 1706 ("የርሕርሕተ፡ ኅሊና፡ መልክዓ፡ ስዕል፡ ደራሲ፡" ...) — though there are instances where it is omitted.

It seems that LIT2748RepCh32 should be merged into LIT1864Malkea and a `textpart` added with `corresp="LIT3088RepCh368"` (or would a `formsPartOf` relation be better?).

@eu-genia, @thea-m

**Comment by thea-m** [comment]
Yes, that seems good to me (both the textpart and the relation, maybe may_form_part_of, if it can be absent).
