### ISSUE TITLE
Two homilies of Cyriacus of Behnesa

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1540]
I would like to create work records for two homilies from BLorient 690 (no. 7 and 10) attributed to Cyriacus of Behnesa. Here's the catalogue: https://archive.org/details/catalogueofethio00brituoft/page/160/mode/2up . Any comments? @DenisNosnitsin1970 @thea-m @DariaElagina

**Comment by thea-m** [comment]
I also think there aren't ID yet for these.

**Comment by MarcinKrawczuk** [comment]
This thread is no longer needed.
