### ISSUE TITLE
visualizing size spans

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1541]
UM-039 has in the description that has to be transferred to XML dimensions as range (height 310-330 etc.)
I tried to encode it as `<height unit="mm" atLeast="310" atMost="330"></height>` but I believe this is not supported in the visualization, and I cannot enter a range inside the tag (`<height unit="mm">310-330</height>`) as it is not numerical. What would the solution be? Can visualization support for ranges be introduced?

**Comment by PietroLiuzzo** [comment]
I think 

````xml
<height unit="mm" atLeast="310" atMost="330">320</height>
````

would be a quite fair encoding, where the precise information is given without breaking all the rest.

**Comment by PietroLiuzzo** [comment]
I can add a visualization of those two attributes in the app, no problem, it will show the range instead of the value
