### ISSUE TITLE
Search in colophons for painters (role in any encoding location)

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1542]
How can I search for the follwoing information:

I would like to know in which mss a name of a painter is mentioned in the colophon. The search mask does not offer the possibility to limit any search to content in colophones, at least I was not able to do that. It might be useful also for other information provided in colophones (for example the name of a queen).

**Comment by PietroLiuzzo** [comment]
We will take into consideration this when restructuring the RDF model and the ontology with @Hizkie . 

If you search for[ painter in the facet search](https://betamasaheft.eu/facet.html?query=painter), you will get many painters.
each person record will list the occurrences of that person in our data, e.g. https://betamasaheft.eu/persons/PRS12451Hezqeel/main 

At the moment we have a dedicated search for colophons, titles, etc. https://betamasaheft.eu/titles here you find persons named in there, but you have to know if they are painters.

Person's names which are marked up (a large minority!) in colophons can be seen [here](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Acolophon%2F%2Ft%3ApersName). 
There are a few, one cannot know how many of these are painters. 

This list is restricted to [colophons, no matter how many person are named in there](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Acolophon%5Bt%3ApersName%5D).

You can get a list of [all persons marked up in colophons and their occupation with this query](https://betamasaheft.eu/sparql?query=SELECT+%3Fcolophon+%3Fname+%3Foccupation%0D%0AWHERE+%7B%0D%0A++%3Fcolophon+a+bm%3Acolophon+%3B%0D%0A++dc%3Arelation+%3Fperson+.%0D%0A++%3Fperson+a+bm%3Apers+%3B%0D%0A++++++++++foaf%3Aname+%3Fname+%3B%0D%0A++++++++++snap%3Aoccupation+%3Foccupation+.%0D%0A%7D)

This is the query, if you want to use it elsewhere, remember the prefixes, in BM they are added for you.
```sparql
SELECT ?colophon ?name ?occupation
WHERE {
  ?colophon a bm:colophon ;
  dc:relation ?person .
  ?person a bm:pers ;
          foaf:name ?name ;
          snap:occupation ?occupation .
}
```
But the RDF does not seem to know about any painter related to colophons

The following Xquery on the data
````xquery
for $p in $config:collection-rootMS//t:colophon//t:persName
let $persId := $p/@ref
let $persRecord := $config:collection-rootPr/id($persId)
let $occ := string-join($persRecord//t:occupation/text(), ' ' )
group by $O := $occ
let $occupers := for $occpers in $p    
                            let $root := string($occpers/ancestor::t:TEI/@xml:id)
                            return (string($occpers/@ref) || ' in ' || $root)
return
(normalize-space(replace($O, ',', '')) || ', ' || string-join(distinct-values($occupers), ' '))
````
returns these results, there are no "painters" but you have a scribe and artist

|owner                                                                         |PRS11217AdfaD in BNFet116 PRS10951Barakata in BNFet34|
|------------------------------------------------------------------------------|-----------------------------------------------------|
|attendant of the treasury (gǝmğā bet) of Dabra Libānos for Za-Walda Māryām in | PRS12716KeflaMaryam in ESamq006                     |
|Lasarist missionary associate of                                              | PRS8972Stella in BNFabb203                          |
|king                                                                          | PRS8346sahlase in BLorient786 PRS8346sahlase in BLadd16256 PRS5205haylaMa in BLadd24184|
|Queen                                                                         | PRS8278SablaWa in BLorient641 PRS8278SablaWa in BLorient510|
|governor or military commander                                                | PRS10233Yamana in BLorient644                       |
|priest                                                                        | PRS12120Mahsanta in ESsmm003                        |
|rayǝs                                                                         | PRS11090TaklaI in BNFet78                           |
|däǧǧ.                                                                         | PRS3856esateof in BNFet143                          |
|2nd Patriarch of Alexandria                                                   | PRS11174Anianus in BNFet113                         |
|pope                                                                          | PRS4820Gregory in IVEf27                            |
|rāyǝs                                                                         | PRS11115FereKr in BNFet80                           |
|emperor                                                                       | PRS4428Galawdew in BNFet78 PRS4428Galawdew in BLorient699|
|scholar and librarian                                                         | PRS10747Zotenbe in BNFet163 PRS10747Zotenbe in BNFet162|
|                                                                              | PRS10604Zannaba in BLorient786 PRS13030AsbaGiyorgis in BLorient786 PRS12511DaligawY in RNBEfns23 PRS12512HaylaI in RNBEfns23 PRS12513WaldaM in RNBEfns23 PRS12301Gabra in RNBspbdaBII39 PRS12294Gabra in RNBspbdaBII39 PRS12520TaklaH in IVEf27 PRS12521TaklaE in IVEf27 PRS11944GabraM in DSEthiop21 PRS12955Tawfilus in DSEthiop21 PRS12557Barha in DSEthiop7 PRS11959Pawlos in DSEthiop7 PRS10954Matewos in BNFet35 PRS9853Walatta in BNFet143 PRS7805Peter in BNFet113 PRS7743Paul in BNFet113 PRS11208HouseTakla in BNFet78 PRS11232HouseSam in BNFet42 PRS9197Taklase in BNFet42 PRS11232HouseSam in BNFet80 PRS11208HouseTakla in BNFet80 PRS10445Yonaso in BNFet80 PRS11332Houseof in BNFet80 PRS10811Takla in BNFet19 PRS11018TanseaK in BNFet53 PRS11515Antiochus in BNFet110 PRS4374Gabreel in BNFet110 PRS11234WalattaN in BNFet124 PRS11235WaldaG in BNFet124 PRS8744Semon in BNFet131 PRS11243ZaManfasQ in BNFet126 PRS4306GabraMa in BNFet126 PRS11223Susenyos in BNFet122 PRS11224SabanaG in BNFet122 PRS12809WaldaHanna in BNFabb137 PRS1822IHA in EMIP02006 PRS1822IHA in EMIP00692 PRS1822IHA in EMIP00690 PRS12937GabraWahedScribe in ESdz019 PRS12825Tensae in ESqsm002 PRS12826Kefla in ESqsm002 PRS12939TasfaSeyonScribe in ESap046 PRS12941TaklaGiyorgis in ESap046 PRS12723DastaGabraMaryam in ESum008 PRS13057WaldaSellaseScribe in ESbgy013 PRS3894estifano in EStrm017 PRS12041GabraGiyorgis in ESakm012 PRS12043EgziH in ESakm012 PRS12004WaldaTensae in ESky014 PRS12835Barhe in ESdmb003 PRS12834Zamaryam in ESdmb003 PRS11074Fesseha in ESaqg006 PRS12821Aytoh in ESgkm006 PRS12641Makonnan in ESdd004 PRS12008TaklaHaymanotAnbasat in ESakm010 PRS12004WaldaTensae in ESakm010 PRS12937GabraWahedScribe  in ESbqm006 PRS13124GabraKrestos in ESmy018 PRS13119FequraIyasus in ESmy018 PRS13123TaklaEwostatewos in ESmy018 PRS13125ZabanaKrestos in ESmy018 PRS12482Tewodros in BLorient699 PRS12418Amha in BLorient719 PRS6152Lalibala in BLorient719 PRS11874AkalaKr in BLorient532 PRS11357Zawalda in BLorient484 PRS12647WaldaAmlak in BLorient755 PRS12244Kola in BLorient644 PRS11361Kanafera in BLorient644 PRS6778Marqos in BLorient644 PRS12247YamanaAb in BLorient644 PRS4979HafaKre in BLorient644 PRS10033Wangela in BLorient644 PRS6576Malakota in BLorient644 PRS4441Galilawi in BLorient644 PRS12248Anestasya in BLorient644 PRS12249WalattaKr in BLorient644 PRS12250WalattaM in BLorient644 PRS12251EhwaKr in BLorient644 PRS12252EdaKr in BLorient644 PRS12253Zamaryam in BLorient644 PRS12254EmhabaKr in BLorient644 PRS12255LakaM in BLorient644 PRS12256QalaK in BLorient644 PRS12257MarataKr in BLorient644 PRS12258BazgenaD in BLorient644 PRS11860LesanaKrestos in BLorient644 PRS4306GabraMa in BLorient711 PRS1246AbibBu in BLorient711 PRS12580FessehaSeyon in BLorient713 PRS12581Anorewos in BLorient713 PRS12584Aqelesya in BLorient713 PRS11835NabiyaL in BLorient509 PRS10473Yostos#n2 in BLorient622 PRS10473Yostos#n1 in BLorient622 PRS12161Giyorgis in BLorient633 PRS12159MaswataKr in BLorient633 PRS12160AmmehaG in BLorient633 PRS12158Zaparaql in BLorient633 PRS13076GabraMaryam in BLorient775 PRS11367Ananya in BLadd24991 PRS11082ErgataQ in BLadd16217 PRS11083FaqadaE in BLadd16217 PRS11084TaklaHa in BLadd16217 PRS11081Warqena in BLadd16252 PRS2548Basilide in BAVet38 PRS11232HouseSam in BAVet38 PRS6554Makwanne in BAVet82 PRS11656GabraH in BAVet82 PRS11659WaldaA in BAVet82 PRS6554Makwanne in BAVet87 PRS11553WaldaK in BDLbruce77 PRS11554WalattaM in BDLbruce77 PRS11555WalattaI in BDLbruce77 PRS11556WaldaS in BDLbruce77 PRS11640BatraM in BDLbruce85 PRS11559Marqorewos in BDLbruce81 PRS11474GabraM in BDLaethe14 PRS11444GabraMi in BDLaethf15 PRS11445HaylaS in BDLaethf15 PRS11393KrestosAmlakena in BDLaethc2 PRS11394Ermeyas in BDLaethc2 PRS11621NagadaK in BDLpoc8 PRS12161Giyorgis in BLorient681 PRS12160AmmehaG in BLorient681 PRS12887TaklaS in BLorient679 PRS12888WaldaAb in BLorient679 PRS12881Tewodotos in BLorient677 PRS12882Awsegneyos in BLorient677 PRS12873MazmuraD in BLorient680 PRS12874Anorewos in BLorient680 PRS12879Bazzabbeh in InEtn56274 PRS8661scusev in InEtn56274 PRS12868WaldaA in InEtn30521218 PRS12907NahuS in BLadd24184 PRS13092WalattaG in BLorient785 PRS13093Zamikael in BLorient785 PRS13091WaradaQal in BLorient783 PRS13140Giyorgis in BLadd19339|
|abbot                                                                         | PRS11016Tomas in BNFet52 PRS11002GabraK in BNFet45 PRS11091ZawgaM in BNFet78 PRS3779enbaqom in BNFet66 PRS3779enbaqom in BLorient699 PRS3779enbaqom in FSUor10|
|emp.                                                                          | PRS7550Nero in BNFet113                             |
|queen                                                                         | PRS2682BerhanM in BNFet112 PRS6829Maryams in BNFet146 PRS2682BerhanM in BLorient533 PRS5045hamalmal in BLorient644 PRS2682BerhanM in BLorient776 PRS10671Zawditu in BAVet81 PRS8276SablaWa in BDLbruce86|
|miss.                                                                         | PRS3451DeJacob in IVEf27 PRS6064Krapf in BLadd16252 |
|maggābi                                                                       | PRS11116GabraN in BNFet80                           |
|ʿalaqā                                                                        | PRS11690Gambar in BAVet87                           |
|of Santo Stefano dei Mori of Santo Stefano dei Mori                           | PRS10372Yohanne in BAVet35                          |
|According to the embedded colophon in he was the one who has “translated” (za-ʾaʿlawkǝwwā) the work (Gadla and Taʾammǝra samāʿtāta Ṗarāqliṭos| PRS12940Danel in ESap046                            |
|96th Patriarch of Alexandria                                                  | PRS5709JohnXIV in BNFet110 PRS5709JohnXIV in BLorient778|
|scribe/owner/commisioner?                                                     | PRS11060EdaK in BNFet66                             |
|ṣaḥāfe tǝʾǝzāz                                                                | PRS9942WaldaMa in BAVet81                           |
|ʿaqqābe bet                                                                   | PRS12869Mamma in BLorient681                        |
|Evangelist                                                                    | PRS6751Mark in RNBspbdaBII39 PRS6751Mark in BNFet113|
|metropolitan                                                                  | PRS8033Qerellos in DSEthiop11 PRS6775Marqos in BNFet110 PRS6876Matewos in EMIP00284 PRS6072Krestodo in ESqsm017 PRS6774Marqos in ESap046 PRS7830Petros in ESagm005 PRS6774Marqos in ESap019 PRS11137QerellosII in ESagm001 PRS10393Yohanne in BLorient699 PRS6776Marqos in BLorient754 PRS6775Marqos in BLorient778|
|Missonary                                                                     | PRS9683Urbino in BNFabb203                          |
|Patriarch                                                                     | PRS6903Matthew in BNFet52                           |
|governor of (śǝyuma ʿagāme) in the first half of the 16th century             | PRS12942Natan  in ESap046 PRS12942Natan  in ESap019 |
|abunä                                                                         | PRS10953Tewodros in BNFet35                         |
|scribe                                                                        | PRS11202GermaS in BNFet112 PRS11015Estifanos in BNFet52 PRS11085AmdaH in BNFet78 PRS11037Wasef in BNFet27 PRS11037Wasef in BNFet24 PRS11118Tewogolos in BNFet80 PRS11309Alphonsus in BNFet152 PRS11236DamaW in BNFet124 PRS11010Samuel in BNFet50 PRS11011Natan in BNFet50 PRS11012Gad in BNFet50 PRS11037Wasef in BNFet29 PRS11010Samuel in BNFabb35 PRS11011Natan in BNFabb35 PRS11012Gad in BNFabb35 PRS11010Samuel in BNFabb137 PRS11011Natan in BNFabb137 PRS11012Gad in BNFabb137 PRS12076ZawaldaMaryam in ESum041 PRS12076ZawaldaMaryam in EStrm017 PRS12076ZawaldaMaryam in ESsmm003 PRS11077Zadengel in ESmr040 PRS11073Neway in ESaqg006 PRS12076ZawaldaMaryam in ESqsm007 PRS10788WaldaMuse in ESmr023 PRS11363Galawde in BAVet38 PRS11621WaldaRu in BAVet81|
|monk                                                                          | PRS6525Mahdanta in BNFet2 PRS8410Salikof in BNFet110 PRS8321saggaAm in ESsdm021|
|qes gabaz of                                                                  | PRS11963WaldaGiyorgisAgamyo in ESagm005             |
|scholar                                                                       | PRS10036Wansleb in BNFet76                          |
|governor                                                                      | PRS5222haylaMi in BNFet143 PRS8668SebhatA in ESagm005 PRS8265Sabagadi in ESagm001 PRS8265Sabagadi in ESamq005 PRS9978Waldase in BLadd19339|
|Patriarch monk                                                                | PRS3259CyrilV in DSEthiop11                         |
|94th Patriarch of Alexandria                                                  | PRS5708JohnXII in BNFet35 PRS5708JohnXII in ESap046 PRS5708JohnXII in ESap019|
|governor or military commander                                                | PRS8681SeelaK in BLorient644                        |
|ʾaṣe                                                                          | PRS5226haylase in BAVet81                           |
|abbot                                                                         | PRS10952Tatamqa in BNFet35                          |
|nǝburäʾǝd                                                                     | PRS3504Demetros in EMIP00680 PRS3504Demetros in EMIP00691 PRS3504Demetros in EMIP00692|
|scribe monk                                                                   | PRS10997Galawdeyos in BNFet42                       |
|supervisor of scribes                                                         | PRS11203AyentaK in BNFet112                         |
|ruler                                                                         | PRS10076WasanS in BLorient786 PRS2110AsfaWas in BNFet124 PRS1878AmmehaI in BNFet124|
|chronicler                                                                    | PRS8871Sinoda in BDLbruce91                         |
|Patriarch                                                                     | PRS4380Gabriel in BNFet78 PRS2533Baselyos in EMIP02033 PRS2533Baselyos in EMIP00690 PRS6905Matthew in BLorient754 PRS4380Gabriel in BAVet38|
|traveller translator                                                          | PRS7834PetrosA in BLorient799                       |
|governor of in the early 20th century                                         | PRS12642WaleWarrababbo in ESdd004                   |
|wr.                                                                           | PRS7077Mikael in BNFet66 PRS3947ezra in BNFet146    |
|qāyǝm                                                                         | PRS11117Samuel in BNFet80                           |
|bishop                                                                        | PRS3178Constant in BLorient700                      |
|traveller                                                                     | PRS2916Bruce in BDLbruce92                          |
|Scribe and artist                                                             | PRS11849Luqas in BLorient733                        |
|Emperor                                                                       | PRS6229LebnaDe in IVorlov4 PRS7006Menilek in RNBEfns22 PRS6229LebnaDe in BNFet115 PRS5616IyasuI in BNFet163 PRS5617IyasuII in BNFet112 PRS5616IyasuI in BNFet162 PRS3874eskender in BNFet35 PRS6229LebnaDe in BNFet143 PRS5616IyasuI in BNFet143 PRS8550sardaDe in BNFet143 PRS9153TaklaHa in BNFet143 PRS10342Yeshaq in BNFet113 PRS8550sardaDe in BNFet110 PRS3175Constant in BNFet110 PRS6229LebnaDe in BNFet138 PRS5617IyasuII in BNFet126 PRS5616IyasuI in BNFet122 PRS7006Menilek in EMIP02006 PRS7006Menilek in EMIP00284 PRS7006Menilek in EMIP00701 PRS2377Bakaffa in ESqsm017 PRS6229LebnaDe in ESap046 PRS10378Yohanne in ESagm005 PRS6229LebnaDe in ESap019 PRS5617IyasuII in BLorient699 PRS5617IyasuII in BLorient533 PRS9153TaklaHa in BLorient720 PRS9430Tewodros in BLorient733 PRS10375Yohanne in BLorient641 PRS3430DawitII in BLorient643 PRS10626ZaraY in BLorient650 PRS10375Yohanne in BLorient510 PRS2377Bakaffa in BLorient488 PRS5616IyasuI in BLorient488 PRS5616IyasuI in BLorient771 PRS2377Bakaffa in BLorient771 PRS4015Fasilada in BLorient754 PRS5617IyasuII in BLorient630 PRS2377Bakaffa in BLorient790 PRS5617IyasuII in BLorient790 PRS9038Susenyos in BLorient644 PRS4015Fasilada in BLorient644 PRS10473Yostos in BLorient624 PRS3430DawitII in BLorient624 PRS3429DawitII in BLorient711 PRS5617IyasuII in BLorient776 PRS8550sardaDe in BLorient778 PRS2377Bakaffa in BLorient799 PRS4015Fasilada in BLorient518 PRS3430DawitII in BLorient633 PRS5616IyasuI in BLorient633 PRS5616IyasuI in BLorient773 PRS4015Fasilada in BLadd16191 PRS4015Fasilada in BLadd16220 PRS9038Susenyos in BLadd16220 PRS9153TaklaHa in FSUor14 PRS6229LebnaDe in BAVet38 PRS7006Menilek in BAVet81 PRS7006Menilek in BAVet87 PRS5617IyasuII in BDLbruce86 PRS5616IyasuI in BDLbruce91 PRS10378Yohanne in BDLaethf15 PRS9038Susenyos in BDLpoc6 PRS5616IyasuI in BLorient681 PRS5618IyasuII in BLorient679 PRS5636IyoasI in BLorient677 PRS5616IyasuI in BLorient680 PRS3430DawitII in BLorient783 PRS5616IyasuI in BLorient784 PRS3692egwalas in BLadd19339|

**Comment by SusanneHummel** [comment]
Thank you! 
I checked the painters mentioned somewhere in the manuscripts record as (as you stae) there are not so many yet. My query was a genaral suggestion.
Thank you for the list!

**Comment by PietroLiuzzo** [comment]
reopening to consider for RDF modeling and views

**Comment by PietroLiuzzo** [comment]
a `persName` with a `@role`, that is an indication of what that person did in that document, like 'owner' in the following example `<persName ref="PRS11905GabraM" role="owner"><roleName type="title">አቡነ፡</roleName> ገብረ፡ ማርያም፡</persName>` will become the following set of triples
````xml

<oa:Annotation rdf:about="https://betamasaheft.eu/DSEthiop1/person/annotation/6">
      <rdf:type rdf:resource="https://betamasaheft.eu/ontology/Owner"/>
      <oa:hasTarget rdf:resource="https://betamasaheft.eu/DSEthiop1"/>
      <oa:hasBody rdf:resource="https://betamasaheft.eu/PRS11905GabraM"/>
      <oa:annotatedAt rdf:datatype="http://www.w3.org/2001/XMLSchema#date">2021-08-13+02:00</oa:annotatedAt>
      <betmas:hasRole>
         <betmas:Role>
            <betmas:roleType rdf:resource="https://betamasaheft.eu/ontology/title"/>
            <betmas:roleName>አቡነ፡</betmas:roleName>
         </betmas:Role>
      </betmas:hasRole>
      <lawd:hasName>ገብረ፡ ማርያም፡</lawd:hasName>
   </oa:Annotation>
````
the annotation (the persName element) has a type 'owner', the roleName is listed as such within.

the occupation is stored as `snap:occupation` and `<snap:occupation>scribe</snap:occupation>`, so is a litteral value associated to a person.

the location of the attestation of the role is preserved by dc:relation (as above) so that I can start from the limitation of the context, look at the identifier of the named entity, and check for annotations which have a type in the Role Class and for the occupation  


```sparql 

PREFIX bm: <https://betamasaheft.eu/>
PREFIX snap: <http://data.snapdrgn.net/ontology/snap#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX snap: <http://data.snapdrgn.net/ontology/snap#>
PREFIX oa: <http://www.w3.org/ns/oa#>

SELECT DISTINCT ?mss ?colophon ?person ?name ?occupation ?role
WHERE {
  ?mss dcterms:hasPart ?colophon .
  ?colophon a bm:colophon ;
  dc:relation ?person .
  OPTIONAL {?person a bm:pers ;
          foaf:name ?name . }
OPTIONAL{  ?person   snap:occupation ?occupation . }
OPTIONAL{  ?annotation oa:hasBody ?person ;
                       oa:hasTarget  ?mss ;
                       a ?role .}
}
}
```
I think that the addition of this part of model is all we need at the moment. The query can be of course limited with a specific person, set of manuscripts, etc. 

What we do not have is a generic artist/painter etc. role reference [in `persName/@role` we can have Illustrator](https://betamasaheft.eu/Guidelines/?id=persName),  in occupation we have 'artist', 'art.', ' art.', 'art. ', ' art ', 'Patron of art', 'Scribe and Artist' searching for 'art' inside occupation and I am not sure if that abbreviates 'artist' or for example 'artisan' which is also among the results of the previous search. This could be used to filter the query above with

```sparql
  FILTER(CONTAINS(STR(?occupation),'art') || ?role=bm:Illustrator)
```

generalizing a bit the query above to get any part, not only colophons (and return the type of context) 
````sparql
PREFIX bm: <https://betamasaheft.eu/>
PREFIX snap: <http://data.snapdrgn.net/ontology/snap#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX snap: <http://data.snapdrgn.net/ontology/snap#>
PREFIX oa: <http://www.w3.org/ns/oa#>

SELECT DISTINCT ?mss ?part ?type ?person ?occupation ?role
WHERE {
  ?mss dcterms:hasPart ?part .
  ?part a ?type ;
  dc:relation ?person .
  ?person a bm:pers  . 
OPTIONAL{  ?person   snap:occupation ?occupation . }
OPTIONAL{  ?annotation oa:hasBody ?person ;
                       oa:hasTarget  ?mss ;
                       a ?role .}
  FILTER(CONTAINS(STR(?occupation),'art') || ?role= <https://betamasaheft.eu/ontology/Illustrator>)
}
````
I get among the results both PRS11849Luqas which is in the colophon, but is not listed there as illustrator (instead as scribe), fetching its occupation. I also get PRS12668GabraI which is both listed as Illustrator, and as  'art', although into a decoration.

manuscript part | part | type | person | occupation | role
 bm:BLorient733/msitem/ms_i1 | bm:BLorient733/colophon/coloph1 | bm:colophon | bm:PRS11849Luqas | Scribe and artist |  
 -- | -- | -- | -- | -- | --
 bm:IVEf83 | bm:IVEf83/decoration/d1 | bm:decoration | bm:PRS12668GabraI |   | bm:ontology/Illustrator

I think this light model adjustment servers the desired purpose.
