### ISSUE TITLE
New work record for BLorient792 = Wright CCCLXXVII

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1544]
BLorient792 is a text for which I don't know any analogy. It seems to be explanation of Biblical passages in Amharic, however it doesn't seem to be a proper andemta. I think it requires at least a work record for the entire work, creating work records for individual parts would seem superfluous to me. But what the title should be like?

https://archive.org/details/catalogueofethio00brituoft/page/286/mode/2up

**Comment by DenisNosnitsin1970** [comment]
Marcin, did you already found a solution? It is difficult to say if it is one work or a collection of individual works. It is not andemta, it is just narrative commentary. Now, looking quickly, I see that at least no. 5 circulated as independent work, if I am not wrong (published by Appleyard?).  You can have a look into R. Cowley, "Ethiopian Biblical Interpretation" (do you have it?), he must have known this manuscript and probably gave some description of the content.

**Comment by MarcinKrawczuk** [comment]
No, I'm still thinking. You're certainly right about no. 5, it even already has a work record: LIT5628CommCreed. I do have Cowley's book and will definitely have a look inside.

**Comment by Ralph-Lee-UK** [comment]
We did create a general 'Amharic commentary on...' for several works, understanding that we are not yet in a position to describe the differences between versions yet but they were for specific texts, and this one is quite different.

**Comment by MarcinKrawczuk** [comment]
OK, so browsing Cowley hasn't brought me closer to any solution so I wanted to put forward two solutions for discussion:
1) To create a general work record for the entire content reproducing the structure of the ms. as type="textpart"
2) To create work records for parts 1-4, possibly 6 WITHOUT a general record for the whole collection
Any thoughts @DenisNosnitsin1970 @Ralph-Lee-UK @DariaElagina @thea-m ?

**Comment by Ralph-Lee-UK** [comment]
My only thought is that the records are such that any association with other commentary would not be missed.

**Comment by MarcinKrawczuk** [comment]
So thanks to the formidable effort of @thea-m  we now know that BLorient792 is available online: http://www.bl.uk/manuscripts/FullDisplay.aspx?index=1&ref=Or_792, this is in case @DenisNosnitsin1970 or @Ralph-Lee-UK would be willing to continue the discussion.

**Comment by DariaElagina** [comment]
I would probably go for one record for the whole "collection" with textparts and corresps for those textparts which already have individual records. If we would come across comparable manuscripts the coding might be improved in future.

**Comment by DenisNosnitsin1970** [comment]
Daria has proposed the optimal way.

**Comment by Ralph-Lee-UK** [comment]
I agree with Daria and Denis
