### ISSUE TITLE
EMIP00045

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1548]
https://betamasaheft.eu/manuscripts/EMIP00045

This record gives error messages with image links: 

![image](https://user-images.githubusercontent.com/39619238/98537927-e9965080-2281-11eb-8a18-3af7afa08d2b.png)

Although there is no list of contents in the side bar

![image](https://user-images.githubusercontent.com/39619238/98538057-1a768580-2282-11eb-9454-b1d5cea12f0f.png)

The @facs statements are coded - see file at https://github.com/BetaMasaheft/Manuscripts/blob/master/EMIP/1-1000/EMIP00045.xml

I can't identify the problem, can you help?

**Comment by Ralph-Lee-UK** [comment]
There appears to be a similar problem with several other files, EMIP 42-50

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo just in case you lost the notification for this one. There is no hurry at all on this one, but I have noticed the same problem also with EMIP 1983.

**Comment by PietroLiuzzo** [comment]
the issue here is only that the latest version is not the one you are seeing online. I am updating those records manually, as it seems too many where passed with the webhook.
