### ISSUE TITLE
LIT4975Dersan vs. LIT1661Homily

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1549]
I have a suspicion that LIT4975Dersan and LIT1661Homily are doublettes. Would anyone care to take a look?

**Comment by DariaElagina** [comment]
LIT1661Homily has by now no attestation in the db. I can reasseure that those three mss linked to LIT4975Dersan have the same text:
[](https://betamasaheft.eu/manuscripts/BLorient771/main)
[](https://betamasaheft.eu/manuscripts/BLorient773/main)  (here there is an incipit)
[](https://betamasaheft.eu/manuscripts/BNFabb31/main)

I am however not sure about [](https://betamasaheft.eu/manuscripts/ESum050/main) 
I can not check the pictures of the manuscript, @DenisNosnitsin1970 could you help and compare the text of the incipit?

**Comment by eu-genia** [comment]
If this is the same then it seems that it was an error to create LIT4975Dersan when we already had LIT1661Homily, @DariaElagina can you please merge the records? (delete + add the formerlyListedAs relation)

**Comment by DariaElagina** [comment]
The LIT1661Homily has yet no attestation, I just wonder if the text in https://betamasaheft.eu/manuscripts/ESum050/main might be not  LIT4975Dersan, but LIT1661Homily

**Comment by DariaElagina** [comment]
If this not the case, I will merge the records of course, I just want to be sure

**Comment by eu-genia** [comment]
I have asked @PietroLiuzzo to add the images of UM-050 to the server in case (I have added the facs but the images are not yet there to see)

**Comment by DariaElagina** [comment]
Thank you! I will take care of it as soon as I can view the images.
