### ISSUE TITLE
general, generic or abstract?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1550]
We have many records, called interchangeably and inconsistently general, generic or abstract, which refer to the "abstract" version of a work of which several recensions exist (they are used in cases where the exact recension is not known, for example when encoding a catalogue). 
Which would be the best term to use? @abausi

**Comment by abausi** [comment]
I would stay with "general", which is less categoric than "generic" 
(appears derogatory and has further possible connotations); "abstract" 
is ambiguous, although the sense is clear.

Il 10.11.2020 18:28, thea-m ha scritto:

**Comment by thea-m** [comment]
Thank you!  I will update the records and leave this issue open until then.
