### ISSUE TITLE
work relation graphs don't load

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1551]
It seems that the relation graphs in the analytic view of work records don't load - I have tried several, and all are in an eternal loading loop. For example https://betamasaheft.eu/works/LIT3702Miracle/analytic or https://betamasaheft.eu/works/LIT5956CommAnCyril/analytic. Maybe it just takes very long, but I think I waited patiently.
It is not urgent.

**Comment by PietroLiuzzo** [comment]
this issue is only with the vis.js viewer. We need to replace that with a better library, like d3.js

**Comment by PietroLiuzzo** [comment]
this was introduced with release 8 of vis.js. I have reverted the version we use to the latest 7 release
