### ISSUE TITLE
visualization of bibliography within text view broken

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1554]
Dear Daria,

The encoding of the refenences in the work record 

https://betamasaheft.eu/works/LIT5069Prayer/text

seem not correct. It is visualized as 

```
The following incipit is taken from     50   .  
The following explicit is taken from     52   .
```

**Comment by PietroLiuzzo** [comment]
this is an issue in the visualization, I will have a look at it next week
