### ISSUE TITLE
Three work records for one prayer?

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1557]
For the BM-Team:
My quick survey of a short prayer indicates that there exist three work records for one and the same prayer:

LIT2993RepCh274 (only 1 attestation, InEtn40552)
LIT3940Prayer (for example: RNBoldpq210 an five other mss)
LIT4962Basema (originally assigned for MNC-010, I am currently working on the description of this Ms, I will change it to LIT2993RepCh274)

For clarity I added the text of this short prayer into the work record LIT2993RepCh274.

በስመ፡ እግዚአብሔር፡ ቀዳማዊ። ዘእንበለ፡ ትማልም፡ ወማዕከላዊ፡ ዘእንበለ፡ ዮም፡ ወደኃራዊ፡ ዘእንበለ፡ ጌሠም፡ ብሉየ፡ መዋዕል፡ ዘእንበለ፡ ዓም። ገባሬ፡ ኵሉ፡ ዘእንበለ፡ ድካም፡ ባሕረ፡ ምሕረት፡ ዘእንበለ፡ ዓቅም፡ ብሁተ፡ ህሊና፡ እስከ፡ ለዓለመ፡ ዓለም። አሜን።

The same I did for other short prayers (LIT2988RepCh269 & LIT3002RepCh282) contained in the same Ms MNC-010, see the following PR.

**Comment by thea-m** [comment]
Thank you, I agree. I suggest to keep LIT2993RepCh274. I will make two PRs with the deletions and changes in the work records and the update of attestations in the manuscript records.

**Comment by SusanneHummel** [comment]
Perfect! 
I changed it already for MNC-010, the PR for this MS follows soon.
