### ISSUE TITLE
New work records for a hymn to God and for a supplication to God

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1558]
1. The Ms MNC-010 contains several hymns to God. One has not been registered yet. Its full text is as follows:

በስመ፡ እግዚአብሔር፡ ወልድ፡ ዘይሤለስ፡ በአካላት፡ ወይትወሐድ፡ በመለኮት። አምላከ፡ አማልክት፡ ወእግዚአ፡ አጋዕዝት፡ ወንጉሠ፡ ነገሥት፡ ዘይሴባሕ፡ በአፈ፡ ኵሉ፡ ፍጥረት፡ በምድር፡ ወበሰማያት፡ በባሕር፡ ወበቀላያት፡ ለዓለመ፡ ዓለም።

2. The Ms closes with a supplication to God. I would also create a new work record for this supplication providing the full text:

እገኒ፡ ለከ፡ እገኒ፡ ለከ። ወእፄውዕ፡ ስምከ። ናዛዜ፡ ኅዙናን፡ ክርስቶስ፡ ለቅቡጸ፡ ተስፋ፡ ገብርከ። መሐረኒ፡ በሂሩትከ፡ በእንተ፡ ማርያም፡ እምከ። አምላኪየ፡ አምላኪየ፡ ኢይጽናዕ፡ ልብከ። ኦእግዚእየ፡ ወአምላኪየ፡ ኢየሱስ፡ ክርስቶስ፡ ተስፋየ፡ ወፀወንየ፡ ወላዕሌከ፡ ትውክልትየ። ወብከ፡ ፀናዕኩ፡ እምከርሠ፡ እምየ። ስረይ፡ ኃጢአታ። ወዕቀባ፡ እመከራ፡ ሥጋ፡ ወነፍስ፡ ዘይመጽእ። ለኃጥእት። ወለድክምት። ዓመትከ፡

**Comment by thea-m** [comment]
I also think there are no IDs for them yet. 
However, I wonder slightly whether these can be considered "works"? There probably are good reasons for this decision in the manuscript (layout or so)?
The first hymn is composed of 3-4 parts which are typical for the beginnings and endings of texts. But if the presentation in the manuscript makes you sure that this is one hymn (not an introductory part to another text), create the work!
For the supplication - I cannot guess now whether this is a "work" or a freestyle, elaborate supplication spontaneously composed by the scribe? It is a difficult question.

**Comment by SusanneHummel** [comment]
The Ms contains several hymns to God of similar short lenght, most of them are listed in Chaine with the exception of tje one mentioend above.For the supplication, I just followed @thea-m 
Since the app seems to be down, I will provide the similiar work record later

**Comment by SusanneHummel** [comment]
Here comes the example od another work record for a supplication to God: https://betamasaheft.eu/works/LIT4113Supplication/main

I am absolotely fine with not creating a work record for this. I just tried to follow the existing examples. .

**Comment by thea-m** [comment]
According to the manuscript description, LIT4113Supplication is a text of four folia, which is significantly more substantial than the supplication we have here. Did you see another example of such a supplication as a work record? (it's absolutely possible, I just cannot remember spontaneously)

**Comment by SusanneHummel** [comment]
No, I don't remember either.
So, I will create only a work record of the new Hymn to God - correct?

**Comment by thea-m** [comment]
That would be my suggestion.

**Comment by SusanneHummel** [comment]
Perfect. Thank you!
