### ISSUE TITLE
Search of a specific work within in a collection

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1559]
How can I search e.g. for all Psalters of the Ethio-Spare collection? I wa snot able to restrict the search to certain signatures.

https://betamasaheft.eu/facet.html?query=Psalter&type-facet=manuscript

**Comment by PietroLiuzzo** [comment]
you can filter by Collection

https://betamasaheft.eu/facet.html?query=Psalter&collection-facet=Ethio-SPaRe
