### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1560]
If I click in the work record

https://betamasaheft.eu/works/LIT2000Mazmur/main

on Ethiopic Psalter, I receive the error message

https://betamasaheft.eu/works/LIT2701Dawit/main

Pietro, shall I continue to report on those error messages, or is this always the same issue?

**Comment by PietroLiuzzo** [comment]
the issue is always that we cannot and do not want to constrain the schema too much. thus encoding goes creative and unsupported.

**Comment by PietroLiuzzo** [comment]
I do not see any issue in the first link, I am looking at the second

**Comment by SusanneHummel** [comment]
Yes, it is only in the second one, the first one is just to show you the work flow.
Please let me know if I shall rather stop writing those error messages.

**Comment by PietroLiuzzo** [comment]
no, you all have to keep reporting. every time I fix something is one less event of allowed creativity getting handled...
