### ISSUE TITLE
Encoding tabot information in records of various types

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1561]
We have a way for encoding tabots in the records of place/institution type (https://betamasaheft.eu/Guidelines/?q=tabot&id=places)
we have (1) the `@type` tabot that can be added to `@ref` to a PRS and (2) `<ab type="tabot">` for a list of dedications, where you can also list inanimate dedications (such as Cross) with `<ref type="authFile">`
yet we have no way to mark up a tabot-dedication to an inanimate entity in records of other types (as in this example https://github.com/BetaMasaheft/Manuscripts/pull/857)
I wonder if we can introduce adding (especially in such cases, where we have no record for the institution, but want to be able to find it when we search for all altars dedicated to the Cross or similar things) a `@subtype` "tabot" to the `<ref type="authFile">`

**Comment by PietroLiuzzo** [comment]
Well, my first instinct would be to ask why we do not have an institution or a place, and what disallows us from creating it and encoding the information there as appropriate. But the description in [Paris, Bibliothèque nationale de France, BnF Éthiopien d'Abbadie 205](https://betamasaheft.eu/manuscripts/BNFabb205/main) reads

> The manuscript was copied before Antoine d'Abbadie  left Ethiopia in 1848. It is not clear if   ጽላ፡  መስቀል፡ in Addition 1 (a1) refers to a person who owned the book or to a church or monastery with a tābot (here, ṣəlla ) dedicated to the True Cross, Masqal .

Which makes me think I probably do not want to find this as a result in a "search for all altars dedicated to the Cross or similar things".

If the "similar things" to which this dedication occurs are marked with `ref[@type='authFile']` as in the example and in place/institution files and the value of `@corresp` in there is already under the category of "Objects of Veneration" I think we have enough information encoded to better specify the "similar things". Thus I do understand where is an issue in the data or encoding practice. We may still use this example to specify the above in the guidelines, that is certainly useful.
 
On the other side, I do not think we have a way to search for "all altars dedicated to the cross" and certainly none that includes entities where a `ref[@type='authFile']` has a `corresp` to a keyword under the category of "Objects of Veneration", thus specified.

- The [keywords index will list all occurrences of  Masqal ](https://betamasaheft.eu/authority-files/list?keyword=TrueCross) this allows a generic search, which matches also the manuscript, and allows a wider look, without claiming there is an altar, and I think it is fairly so.

- The repository/place list view will only offer an optional filter for persName[@type='tabot'] and ref[@type='authFile'][parent::ab[@type='tabot']] and currently does not work

- The [advanced search will give only the institutions](https://betamasaheft.eu/as.html?query=&homophones=true&AttestedInType=1&xmlid=&tabot=TrueCross) and I think this is what would answer the query for "all tabots to x" more appropriately

- The [facet search may be more generous but will have to be filtered when asked a specific object of veneration](https://betamasaheft.eu/facet.html?query=Masqal) and may be filtered when [simply searching tabot](https://betamasaheft.eu/facet.html?query=+t%C4%81bot&type-facet=manuscript) but there is no filter for this feature, and we could easily add it on the model of the filter for art themes which looks only at `t:decoNote//t:ref[@type='authFile']/@corresp` and the keyword filter which looks at any `term[@key]`

beside 
- [ ] fixing the list view


I would suggest to 
- [ ]  add this example in the GL
- [ ]  add a facet filter for "Objects of Veneration" in the facet search
- [ ]  add these search examples in the help page

what do you think?

**Comment by eu-genia** [comment]
Well I think the reason why @DenisNosnitsin1970 wanted to mark up the tabot in the first place is exactly because we do want to find this mention when looking for all churches with altars dedicated to Cross, even when we have no place record in place (impossible in such case - and there are many cases like that - but of course when I have a similar description saying "the manuscript belonged to a church dedicated to Takla Haymanot" I don't have the problem, I assign the `@type="tabot"` and then the search for tabots will give me the result)

**Comment by eu-genia** [comment]
So I was wondering why Cross, or Covenant of Mercy, should be treated so differently, in the sense of dedication of altars, as persons, who are just lucky to have a type assigned

**Comment by PietroLiuzzo** [comment]
they are not persons, so they are treated differently, simply so. but we have enough information to do all what you are asking, just much more precisely. please check my proposals above.

**Comment by PietroLiuzzo** [comment]
@eu-genia would you like to draft the PR for the guidelines page?

**Comment by eu-genia** [comment]
I am not quite sure what the changes to make are, as you opted against an additional mark up for inanimate tabots mentioned outside of institution records, for which I originally created the issue. The example               `<ref type="authFile" corresp="Masqal">Cross</ref>` (Example 11) is already present in the GL.

**Comment by eu-genia** [comment]
(my question was exactly whether we can, if we want, have a filter to search for all tabots dedicated to an inanimate object of veneration, mentioned anywhere on the app, the answer was no, so actually the issue can be closed afaik)
