### ISSUE TITLE
Work records for EMML 1840

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1562]
I would like to create some work records for the ms. EMML 1840, as it contains some texts of personal interest. Following the numbering in the catalogue, the work records are required for:

(1) Combat of Paul, the first hermit
(2) History of St. Longinus, the abbot of Dabra Māhǝw
(3) History of the hermit ʾAbǝlo
(5) Homily by bishop Matthew, the martyr, on the carrying and presentation of Our Lord by Simeon
(8) Combat of Paphnutius, the Egyptian hermit by ʾabbā Bǝlo
(9) Martyrdom of Anthony the Qurayshite
(10) Four homilies by Ephrem the Syrian on judgement and repentance

Also, any idea who "bishop Matthew, the martyr" might be?

Thank you for you input.

[1840.pdf](https://github.com/BetaMasaheft/Documentation/files/5545604/1840.pdf)

**Comment by DariaElagina** [comment]
Thank you! If I understand correctly the catalogue description, this is rather a collection of texts, so the first-level IDs for each text are nor required from my point of view.

**Comment by eu-genia** [comment]
@antobrita has been working extensively on the Acts of Martyrs, it would be good if she contributes in producing a reliable authority list for all the Gadlat attested in Gadla samāʿtāt. This could then serve the basis for developing the metadata for the record **LIT1493Gadlas** and eventually, if necessary, creating individual records.

We had a long discussion as to whether texts which do not circulate independently in Ethiopia but only in this case as part of the Gadla samāʿtāt should have individual records at all. According to the current definition of a work, only a text with an independent circulation should get an ID. (Those texts from GS which may appear in different contexts do earn their own IDs. I am sure @antobrita can eventually help.)
 
1) different from LIT1888Martyr?
2) = LIT4940Longin

**Comment by eu-genia** [comment]
@MarcinKrawczuk - each issue should preferably have only 1 assignee - that is the person who is responsible for the final resolving of the issue, such as creating records - the persons who you address the question to should simply be tagged in your query, using the "@" prefix to the name, then we shall get the query without being assigned

**Comment by eu-genia** [comment]
UPDATE on checking
https://github.com/BetaMasaheft/Works/wiki/Notes-on-Works-encoding

Independent entries are to be created for: the single Passiones within the Gadla Samāʿǝtāt

So yes we do need independent entries

And it would be good if we depart from a reliable Authority list to avoid any overlappings and confusions.

**Comment by MarcinKrawczuk** [comment]
> @eu-genia  
>     1. different from LIT1888Martyr? LIT1888Martyr seems to be about the apostle while mine is the one about Paul the Egyptian hermit, published by Pereira if my memory serves me well
> 
>     2. = LIT4940Longin - LIT4940Longin seems to be about the soldier who pierced the Christ's side, while mine is a historical figure i. e. PRS6343Longinus

**Comment by eu-genia** [comment]
OK, thank you.
Since according to guidelines each martyrdom in GS should have a record, as long as there are none, they should be created.
Thank you.

**Comment by eu-genia** [comment]
I have now received from @abausi a file with all texts of GS listed that I can use as the basis for gradually creating work IDs
As far as I have seen, however, the list does not include (5) Homily by bishop Matthew, the martyr, on the carrying and presentation of Our Lord by Simeon,  so cannot provide more details on that one.

**Comment by MarcinKrawczuk** [comment]
@eu-genia this sounds very helpful! I actually at some point had doubts whether to encode this ms under LIT1493Gadlas, since @abausi himself classifies this ms. separately from GS proper in bm:Bausi2002ActaPhileae p. 7. I am open for discussion, but for the time being I've left LIT1493Gadlas.

**Comment by abausi** [comment]
The file from @abausi represents a large survey on all main catalogues collections and on a few EMML not yet catalogued MSS (basis for some publications, several unpublished studies on GS, and starting point for the work in the SFB 950); it is particularly rich for the bibliographic information and for being the result of an extensive check on the surrogates from all catalogued collections available to me (more have become available in the meanwhile). Of course, it focuses on the most clear GS MSS; data on isolated texts circulating in other collections are considered to a very limited extent.

It is crucial to have clearly identifiable (by incipit, which is always given) for IDs, that shall be created by Zhenia and gradually implemented.

@antobrita has many more data, on many more MSS, and descriptions with a much finer degree of detail. These data will be entered as soon as her monograph is accomplsihed. Essential for the moment is to have a reliable working list of IDs for the texts, to match BHO entries (entered by @MassimoVilla) and all which is already available in BM. The case of the Homily by bishop Matthew is one among many which occur, which are not represented in this file.

The distinction between GS and GQ (Gadla Qǝddusān) has some basis, and works to some extent. There is obviously an overlapping with homiliaries as well. There is margin for discussion on several points. Here it can be useful the category of "thematic codices", for which see the important (freely available online at De Gruyter) essay by Patrick Andrist, ‘Concepts and Vocabulary for the Analysis of Thematic Codices: The Example of Greek Adversus Iudaeos Books’, in Alessandro Bausi, Michael Friedrich, and Marilena Maniaci, eds, The Emergence of Multiple-Text Manuscripts, Studies in Manuscript Cultures, 17 (Berlin–Boston: De Gruyter, 2019), 305–346.

**Comment by MassimoVilla** [comment]
As I have just looked over this issue after being mentioned by @abausi, let me briefly comment and share with you (in particular with @MarcinKrawczuk) some information I collected upon the first text of EMML 1840: 
(1) Combat of Paul, the first hermit.
This is _not_ the same (Greek-based?) version uniquely contained in ms BnF Abb. 60 (= CR 172), ff. 1-16, printed and translated by Pereira and corresponding to **LIT1803Lifeof**.
On the contrary, the text attested in EMML 1840 is a different (clearly Arabic-based) version, so far missing in the BM database. It is also preserved in mss EMML 1844 (very similar to EMML 1840, probably genetically related or even a copy of that), EMML 7505 (available online), ms EMIP UNESCO 02, National Library 67 (apparently not in the BM database) and, as far as it seems to me from the incipit, in ms Dayr Suryān Ethiop. 11 (= DSEthiop11#ms_i11), where the text is possibly incorrectly given the other ID, i.e. LIT1803Lifeof (sorry @thea-m for not telling you this before: it is a recent discovery, I hope we can talk about this separately).
I am a bit familiar with this tradition since it is my intention to present a paper on this new version of the Combat of Paul in a forthcoming workshop, which will be organized next spring in Marseille by the Projet ERC COG HornEast.
In the meanwhile, I believe this is a good occasion to update the BM database with fresh data.

**Comment by abausi** [comment]
Thank you @MassimoVilla for this. This raises again the issue that this MS (EMML 1840, as well as EMML 1844) is actually _not_ a GS MS; it is rather _collectio monastica_ or the like, to some extent not even a _GQ._ There is much to be done here, and there is need of a systematic contribution towards a census of the texts in their manuscript arrangement.

**Comment by MarcinKrawczuk** [comment]
Thank you @abausi and @MassimoVilla for the illuminating remarks. If I may return somewhat to the beginnings of the discussion, should I abandon my cataloging work on EMML 1840 until some decisions are made? @eu-genia

**Comment by abausi** [comment]
I would suggest that since this has been started, it should be 
concluded, at least with the creation of all necessary IDs taking into 
account these exchanges, corrections and remarks.

Il 18.11.2020 15:56, MarcinKrawczuk ha scritto:

**Comment by DenisNosnitsin1970** [comment]
Massimo, 
thank you for a valuable addition. 
Regards - DN

**Comment by DenisNosnitsin1970** [comment]
Massimo, just a small update: I compared the text in DS Ethiop. 11 to others, it is indeed dissimilar to that in BnF Abb. 60 (= CR 172) = LIT1803Lifeof, but also to EMML 1840; however, personally I find the similarity to EMML 7505 (= ms EMIP UNESCO 02, National Library 67) a little illusive  judging at least from the incipits (do you mean that EMML 1840 and 7505 contain the same version?).  I would create a a separate ID for the text in DS Ethiop. 11. This recent manuscript was produced in Egypt, it is on the whole special, containing some texts that look similar to those already known, but still different.

**Comment by MassimoVilla** [comment]
Thank you Denis for your remarks. I believe that EMML 1840 and 7505 contain the same text, even though the introductory lines look quite different. The textual similarity can be appreciated, despite several variant readings, from (EMML 1840, f. 3r) ኮነ፡ በውእቱ፡ አዝማን፡ እምቅድመ፡ ያስተርኢ፡ ብዝኃተ፡ አምልኮ፡ ዲበ፡ ምድር፡ ወአድባራት፡ ወገዳማት፡ ዕሩቃን፡ እምኔሆሙ። etc. (EMML 7505, f. 82rb reads here ወኮነ፡ በውእቱ፡ መዋዕል፡ እምቅድመ፡ ያስተርእዩ፡ ብዝኃን፡ መስታጋድላን፡ (!) ዲበ፡ | ምድር፡ ወአድባራት፡ ወገዳማት፡ ዕሩቃት፡ እምኔሆሙ፡, etc.). In their turn, they seem to slavishly continue the Arabic كان في ذلك الزمان من قبل ان تظهر (كثرة) العبادة على الارض والجبال والبرارى خالية منهم. Then follows the narration of the death of St Paul's and his brother Peter's rich father.
Unfortunately I have no access to images from DS Ethiop. 11, so I cannot compare the two texts. It would be interesting to see whether it also has the above passage. In contrary case, it might be a different recension or even a new translation of the work.
