### ISSUE TITLE
Image Viewer Broken For URLs Without HTTPS

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1563]
It seems that a number of manuscripts have their iiif manifest URLs given using http instead of https. This causes issues when users access Beta Masaheft over https (as they should!), since browsers, as a security precaution, block requests to http URLs from pages loaded over https. Is there a way to batch-change the URLs in manuscript records? I would have suggested another solution would be to simply have the app change the URLs before passing them to the viewer, but this causes problems for API users.

<img width="566" alt="Screen Shot 2020-11-16 at 13 18 01" src="https://user-images.githubusercontent.com/6315671/99251745-27f5b780-280e-11eb-8b01-07e78ecb31a1.png">

Also, perhaps it is worth including a note about this in the guidelines, that it is always preferable to use https URLs (except in the case where sites do not support this, which is now incredibly rare but still happens with old institution sites).

@PietroLiuzzo, @thea-m

**Comment by smaugustine** [comment]
As an update, specifically about Gallica URLs, is there a reason why the `@facs` isn't the manifest URL? It looks like [the app actually changes the URL](https://github.com/BetaMasaheft/BetMas/blob/b5999c790fa2908af062426d4129e4b51ba726da/BetMas/xslt/post.xsl#L286), wouldn't it be better to have the proper manifest URL stored in the record? This is the case for other institutions.

**Comment by PietroLiuzzo** [comment]
It may simply depend on _when_ those urls where added... I think if you see a wrong url you are free to propose a change for that...
the code you are pointing to only changes instances of facs in the enriched TEI we provide. There are several other places where such replacements are carried out to produce our manifest or to call specific urls in different viewers.

**Comment by smaugustine** [comment]
On the mixed content issue, note that [this line](https://github.com/BetaMasaheft/BetMas/blob/b5999c790fa2908af062426d4129e4b51ba726da/BetMas/xslt/post.xsl#L282), too, will have this problem. The Beta Masaheft server is HTTPS by default, sites served over HTTPS cannot load content from HTTP servers.

**Comment by PietroLiuzzo** [comment]
thanks, taking notes...

**Comment by smaugustine** [comment]
@PietroLiuzzo Is there an xquery to find records with `@facs` URLs that are HTTP instead of HTTPS?

**Comment by PietroLiuzzo** [comment]
unfortunately I cannot look at this right now. if you can wait, I will do asap.

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aidno%5Bstarts-with%28%40facs%2C%27http%3A%27%29%5D 
I will make a replacement tomorrow morning for these 51 instances, which should fix the data and remove the need of changing the code
