### ISSUE TITLE
Searching via clavis number

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1565]
Is there any to search for a particular clavis number such as CPG? I see it can be done through "Find in project" function in Atom, but when the number corresponds e. g. to a popular miracle of Mary the result is discouraging. Thank you for your time.
@eu-genia @thea-m @PietroLiuzzo

**Comment by thea-m** [comment]
Yes! https://betamasaheft.eu/works/list "Other clavis ID" in the left filter

**Comment by MarcinKrawczuk** [comment]
Thanks, how useful!
