### ISSUE TITLE
New work records for UM-039

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1568]
Pending decision of @abausi , in order to catalogue UM-039, I may have to create IDs for
- The epistle (letter) of Constantine to the people of Alexandria
- The letter of Constantine on Arius
- Canons of the council of Chalcedon
- Canons of the council of Constantinople
- Canons of the council of Ephesus
- Canonical responses (sylloge) of Timothy (and under these: On the treatises of Gregory of Nazianzus, On the twelve chapters of Cyril of Alexandria, we already have separate IDs for other parts of this collection, LIT1785Letter The epistle to the Alexandrinians, LIT1786Letter The epistle to the Constantinopolitans, LIT2220RefutaThe refutation of the council of Chalcedon)
(not yet created in the course of Senodos work as seem to only be present in this collection for now)

@DenisNosnitsin1970 @thea-m

**Comment by thea-m** [comment]
Thank you, yes, I found IDs for none of these, except maybe LIT2372Syllog - is this the same sylloge of Timothy?

**Comment by eu-genia** [comment]
Yes, thank you. I think I can take that, it has not been used.
