### ISSUE TITLE
New attribute for the element “del” + double useage of the attibute "rend"

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1571]
According to Pietro, encoding requires creativity: I would like to propose “cause” as an attribute for the element “del”

I. 
I find it reasonable, to differentiate between, for example: 
A) something was deleted because it was incorrect: for example erroneously written twice (dittography) or superfluous characters
B) for other reasons like former names of former owners of the manuscript.

I attach here a Ms picture to provide an example for the first group A:

I encoded:
`<hi rend="rubric">ነዓ፡ ኀቤየ፡ ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ ወልደ፡ እግዚአ</hi><del rend="expunctuated" cause="dittography">እግዚአ</del>ብሔር፡ ሕያው። ወወልደ፡ <hi rend="rubric">ማርያም፡</hi> ሥግው። መ<del rend="effaced" cause="superfluous">ለ</del>ብረቀ፡ <hi rend="rubric">መለኮት፡</hi> መደንግፅ። ፍሕ`

The system likes it, does the BM-team as well?

II.
For the first deletion (effaced and surrounded by dots) in the example, it would be reasonable to provide two attributes "rend":

`<del rend="expunctuated" rend="effaced">እግዚአ</del>`

The system does not allow it.
![MNC-010 - 0039](https://user-images.githubusercontent.com/28757489/99821013-c6a54f80-2b51-11eb-8d24-ee0f5e6bdd83.jpg)

**Comment by thea-m** [comment]
I have nothing against the proposed addition. We have used the attribute `@reason` with the element gap to provide similar information (in my mind, there must be conceptual differences between reason and cause...). (@PietroLiuzzo I don't understand why `@reason` is not listed in the guidelines in the attributes list.)
For the second case, it would probably become `del rend="expunctuated effaced"` .

**Comment by PietroLiuzzo** [comment]
@thea-m is right about the multiple, space-separated values for `@rend`.

our Guidelines do not have a lot on `<del>` unfortunately, please refer to the [TEI guideilnes](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-del.html). We can of course add examples, and this one, including the image is indeed a nice one, which highlights the scribal interventions.

 `@cause` does for `<del>` much the same as `@reason` does on `<gap>`. I do not know about the semantic nuances which may have brought to the decision to name these two attributes differently, but they do belong to two classes of attributes which are distinguished, so `@cause` is part of [att.transcriptional](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.transcriptional.html) and refers to authorial or scribal interventions, where `@reason` instead is used on gap  secl  supplied  surplus  unclear and in my understanding is intended for editorial annotation.

We do not need to add this attribute, it is already there, we need to agree and document its usage, so this would need to make its way into the Guidelines. I will make a PR for you to approve.

**Comment by PietroLiuzzo** [comment]
the reason `@reason` is not in the list, is that is is never marked in `<att>` in the GL. I will remedy that lack of encoding as well.

**Comment by PietroLiuzzo** [comment]
@SusanneHummel could you please tell me if this image is available in BM and give me the location, so I can include the image as well?

**Comment by SusanneHummel** [comment]
It is from MNC-010, not yet available. If it makes sense, you could use it anyway in the GL.

**Comment by PietroLiuzzo** [comment]
I cannot use it if it is not available, sorry.

**Comment by SusanneHummel** [comment]
If I encode: ```
<del
                           rend="expunctuated effaced" cause="dittography">እግዚአ</del>
```
I receive the follwoing errro message: value of attribute "rend" is invalid; must be equal to "effaced", "erasure", "expunctuated" or "strikethrough"

**Comment by PietroLiuzzo** [comment]
I thought it had been tested... I have updated the schema, allow it a bit of time and refresh the validation
