### ISSUE TITLE
New work record for Prayer to St George

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1572]
A prayer to St George is attested in MNC-008 (it contains malkǝʾ-hymns and prayers). The same prayer ist attested in the Saʿātāt (bm:Tasfa1955Saatat, pp. 98-103 ). Since the prayer exists independently from the Saʿātāt, a new work record should be created.

Incipit:
ትባርክ፡ ነፍስየ፡ ለእግዚአብሕር፡ ፀሐይ፡ ዘልዳ፡ ኮከብ፡ ዘልዳ፡ ንጉሥ፡ ነአ፡ ጊዮርጊስ። ነዓ፡ ጊዮርጊስ። ሰማዕተ፡ ኢየሱስ፡ ክርሰቶሰ፡ ወነዓ፡ ፍቁርየ፡ ዘልዳ ፡ ንጉሥ፡ ፫ ጊዜ፡ በል፡ ዘሐረጸከ፡ዱድያኖሰ። ወወገረከ፡ ደብረ፡ ዒድራስ። ዘዘረወከ፡ በነፋስ፡ ሰላም፡ ለከ፡ ጊዮርጊስ።

Explicit:
ስብሐት፡ ለአብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ዘአንበሩ፡ ብየ፡ አክሊለ፡ ሞገሠ፡ መዘምረ፡ እኩን፡ ለጊዮርጊስ፡ ኀያል፡ መስትጋድል፡ ኀያል፡ ኮከበ፡ ክብር፡ ኀያል፡ ገባሬ፡ ተአምር ፡ ጊዮርጊስ፡ ቅዱሰ፡ ለእግዚአብሔር፡ በእንተ ፡ ጊዮርጊስ ፡ ሰማዕትከ ፡ ምህላነ ፡ ስማዕ፡ በዕዝንከ፡ ፫ ጊዜ፡ በል፡ ኦአምላከ፡ ጊዮርጊስ፡ ዕቀበነ፡ ዕመከራ፡ ሥጋ፡ ወነፍስ፡ ኦአብ፡ በእንተ፡ ኢየሱስ፡ ርድአነ፡ ክርስቶስ፡ ለአቡኩ፡ ኄር፡ ተማኀፀነ፡ መንፈሰ፡ አብ፡ ወወልድ፡ ናዝዘነ።

**Comment by DenisNosnitsin1970** [comment]
Isn't it "Sebhata fequr" of St. George, with a couple of the first lines dropped
[Mäshafä Sä'atat-1.pdf](https://github.com/BetaMasaheft/Documentation/files/5582277/Mashafa.Sa.atat-1.pdf)
?  Then it may be identical to LIT4957SebhataF. I am sending you a Se'atat edition with this prayer starting on p. 98, but here without the title. Do you have Mogäs Equba Giyorgis' edition? If the case, could you send me one or two page with the work?

**Comment by SusanneHummel** [comment]
Exactly, as I wrote above: The prayer is included in the edition of the Saʿātāt, beginning on p. 98. I use the same edition as you.
I could not and still cannot check whether it is identical to LIT4957SebhataF since this entry does not provide any text, and the links to the Mss from Dayr as-Suryān do not work. 
The binning seems to be completely different. I searched for some phrases of the prayer as attested in MNC-008 and did not get any result in the App. Therefore I assumed that LIT4957SebhataF is a different work. If you could cross check it with the Egyption mss, that would be of great help. The prayer in MNC-008 is very close to the printed edtion of the Saʿātāt (98-103).

**Comment by SusanneHummel** [comment]
I just saw that  LIT4957SebhataF  seems to be attested in another MNC-Manuscript. So, I can compare it by myself. Thanky you anyway!

**Comment by SusanneHummel** [comment]
I compared the prayer mentioned above with a prayer contained in MNC-011. It beginns as follows

ስብሐት፡ ፍቁር፡ ዘቅዱስ፡ ጊዮርጊስ፡ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ነዓ፡ ነዓ፡ ጊዮርጊስ፡ እንዘ፡ ትሰርር፡ በፈረስ፡ (Ms: በፈፈስ) ወነዓ፡ ፍቁርየ፡ ዘልዳ፡ ንጉሥ፡ ሰአል፡ ለነ፡ ናቄርብ፡ ለከ፡ ስብሐት፡ ወወጋዳ፡sic ለጊዮርጊስ፡ ኮከበ፡ ልዳ፡ ለጥ(ባበ?)፡ ህንፃ፡ ማኅፈደ፡ ሃሌ፡ ጊዮርጊስ፡ ዘርብ፡ 

This prayer (probably LIT4957SebhataF) is completely different than the one given in this issue (taken from MNC-008) and the same one contained in the printed edition of the Saʿātāt (bm:Tasfa1955Saatat, pp. 98-103). Both prayers show similarities only at the very beginning but after a few lines develop to a substantially different text. The text in the printed Saʿātāt-edition and the text transmitted in MNC-008 are very close in wording with only minor variations. Therefore, I would consider this prayer as one and the same and the LIT4957SebhataF as a different work.

**Comment by SusanneHummel** [comment]
Consequently, I would not link LIT4957SebhataF as attested in MNC-008 to the prayer in the Saʿātāt.

**Comment by SusanneHummel** [comment]
Could we please arrive at a common decision so that I can continue working? That would be great.

**Comment by DenisNosnitsin1970** [comment]
I have nothing more to say.

**Comment by MassimoVilla** [comment]
If the text in MNC-008 corresponds (with minor variants) to that embedded in the Saʿātāt but not to the LIT4957SebhataF attested in MNC-011, I think you should create a new work record for the prayer contained in MNC-008 and add, among the edition information, that it is printed in the Saʿātāt (bm:Tasfa1955Saatat, pp. 98-103 ), and, among the relations, that it might be part of the Saʿātāt work record ("ecrm:CLP46i_may_form_part_of") and that is different than LIT4957SebhataF ("saws:isDifferentTo")

**Comment by SusanneHummel** [comment]
Thank you Massimo! I will do so.
