### ISSUE TITLE
corresp / anchors view

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1574]
I guess I am being confused, I believed if in the work records there are text parts with a `@corresp`, when I list derived IDs in a MS description I should see the actual works, not the derived IDs, but here
https://betamasaheft.eu/manuscripts/ESum039/main
I am not seeing that.
Is there an error in my encoding of either ESum039 or LIT1047Aksumi? Thanks, @PietroLiuzzo

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/100#issuecomment-732183889_

**Comment by PietroLiuzzo** [comment]
@thea-m @DenisNosnitsin1970 @DariaElagina

**Comment by DariaElagina** [comment]
I think that this is correct to print the second level IDs, and not the IDs for independent works. Text as part of a collection and text in independent circulation are (potentially) two different streams of textual transmission. The manuscript does not contain those texts as independent units, so the second level IDs are correct, IMHO.

**Comment by eu-genia** [comment]
We had a long discussion in this respect (cannot find the issue) but the outcome at that point was the contrary. At least both must be printed. I need to see the CAe identifiers for the works themselves.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/811
https://github.com/BetaMasaheft/Documentation/issues/1467

**Comment by eu-genia** [comment]
Is there anything that speaks against printing both? Second level = First level if there is a first level?

**Comment by PietroLiuzzo** [comment]
I am struggling to understand what is the reason, in this case, for encoding

```xml
<title type="incomplete" ref="LIT6238AksColl#EcclCan">The Ecclesiastical canons</title>
```
note that in https://betamasaheft.eu/works/LIT6238AksColl.xml there is NO xml:id to anchor `EcclCan`, so the pointer looks wrong to me. May be it is in an unmerged branch, I did not check that. You could use `LIT1047Aksumi#EcclCan` . Similarly LIT6238AksColl#HEpA does not exist in the db and the XML is correctly consistent with the GitHub version, so there is no syncing issue. What is surprising here is that a title is actually obtained, but this is the result of a previous requirement about the printing of titles of parts. 
- [ ] this needs to be fixed so that a non-exising anchor will return an error. 

In `LIT1047Aksumi` you have 
```xml
<div type="textpart" n="1" xml:id="EcclCan" corresp="LIT6239EcclCanQ">
<label>Ecclesiastical canons</label>
</div>
```
But I am really not sure why use in the `ESum039` above the anchor instead of, IMHO, more simply, having 

```xml
<title type="incomplete" ref="LIT6239EcclCanQ">The Ecclesiastical canons</title>
```

or even just

```xml
<title type="incomplete" ref="LIT6239EcclCanQ"/>
```

since in `LIT6239EcclCanQ` you have already

```xml
<relation name="saws:formsPartOf" active="LIT6239EcclCanQ" passive="LIT1047Aksumi"/>
```
which is not LIT6238AksColl, which has however a statement like

```xml
<relation name="saws:formsPartOf" active="LIT6238AksColl" passive="LIT1047Aksumi"/>
```
so, I am not sure: is `LIT6238AksColl` a part of `LIT1047Aksumi` in the same way as `LIT6239EcclCanQ` _or_ is `LIT6239EcclCanQ` part of `LIT6238AksColl` and `LIT6238AksColl` part of `LIT1047Aksumi` ?

Given there is a reason for this, I am not sure which view or part of the visualization is concerned here, since the link to the manuscript is given. 
- You have no text for the manuscript, so it cannot be the text view of the manuscript. 
- perhaps we can forget about `LIT6238AksColl`
- `LIT1047Aksumi` has no text. In its text view (https://betamasaheft.eu/works/LIT1047Aksumi/text) you would like to see the text of, e.g. https://betamasaheft.eu/works/LIT5064HEpA/text because there is a `@corresp` to that in it, which I copy below.

```xml
<div type="textpart" n="2" xml:id="HEpA" corresp="LIT5064HEpA">
<label>History of the Episcopate of Alexandria</label>
</div>
```
We had this functionality indeed, which has probably been removed in the migration to the DTS implementation this summer. 
I have reintroduced it, but only at the navigation level of the actual unit, not to conflict with the navigation of the current unit, which I think would be wrong and confusing. Additionally, this is done only at the deepest level, of if there are no further divisions in the selected <div>. This means the transclusion will occur only at the deepest and most relevant navigation level and not conflict with the navigation of the current unit. The imported text is also now introduced by a warning that the text is actually transcluded from elsewhere. See https://betamasaheft.eu/works/LIT1047Aksumi/text?ref=2 or https://betamasaheft.eu/LIT1047Aksumi.2 which will redirect there (since you have `@n` on the div)

**Comment by eu-genia** [comment]
> But I am really not sure why use in the `ESum039` above the anchor instead of, IMHO, more simply, having
> 
> ```
> <title type="incomplete" ref="LIT6239EcclCanQ">The Ecclesiastical canons</title>
> ```
> 
> or even just
> 
> ```
> <title type="incomplete" ref="LIT6239EcclCanQ"/>
> ```

because I was told (here and elsewhere https://github.com/BetaMasaheft/Documentation/issues/1574#issuecomment-732202955) that, when a text is transmitted as a part of collection, we should use second-level IDs, not first-level IDs

was also the advise given here https://github.com/BetaMasaheft/Documentation/issues/1467#issuecomment-674062338

(you are right there was a confusion with the first level ID in the process, fixing now)
