### ISSUE TITLE
Zena Ayhud

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1575]
Dear @thea-m ,

as I am encoding the manuscripts with Zena Ayhud, I have found out that the short descriptions of chapters of LIT2598Yosipp does not correspond at least to the majority of cases. As far as I understand, the descriptions were taken from the catalogue description of Lost. Rüpp. II, 2 by Goldschmidt. These descriptions, basically the place of the Romance of Alexander, do not correspond to other manuscripts and to the edition by Kamil. As Kamil also used Lost. Rüpp. II, 2 and says nothing on any strking pecularities of the manuscript. So, I suppose that there is just a small confusion in the catalogue description by Goldschmidt. This can be explained by a big number of Alexanders in the text :)
As I have now Kamil's edition at my disposal I would like to enhance the text structure and add incipits according to the edition, that would mean also partially to rework the description provided by you on the basis on the catalogue description. Do you have any objections or are you ok with that?

**Comment by thea-m** [comment]
Of course not, improve everything you can!
