### ISSUE TITLE
New work record for a protective prayer

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1576]
I would like to create new record for a protective prayer against criminals contained in BDLaethg37, as per @SusanneHummel's suggestion. Here are the incipit and explicit 
Incipit: ጸሎተ፡ ሰራቂ፡ ወቀማኛ፡ ሀያዲ፡ ወተጸጋኪ፡ አመኃልኩክሙ፡ ወአውገዝኩክሙ፡በእግዚአብሔር፡ ክፍልምያኖስ፡ በኵርኵያኖስ፡ በጢኖ፡ ጠቅያኖስ፡ በብርሃናኤል፡ በብርሃናውል፡ በአማኑኑኤል፡ በዝንቱ፡ አስማቲከ፡ ቃለ፡ አዕይንቲክሙ፡ ይትአርሩ፡

Explicit: ዋታ፡ ድፈር፡ ኤልያስ፡ መቃብር፡ ፈውስ፡ መሐሽ፡ በርንዢ፡ በሀገር፡ እገሌ፡ ባስጋራ፡ ከዞርህ፡ ከተዘወር[]ነ፡ ከፋትነ፡ በረት፡ እለ፡ ተሐ[]በሊት፡ አምሳለ፡ አራዊት፡ []ልኩክሙ፡ ከመ፡ ኢትባኡ፡ ውስተ፡ ቤቱ፡ለገብርከ።

@SusanneHummel @MassimoVilla @DariaElagina

**Comment by SusanneHummel** [comment]
Is it really በአማኑኑኤል፡ (doubleኑ?)
ቤቱ፡ለገብርከ። (space inbetween)

I think it would be very useful. There are so many protective texts, we should start to systematically ondex them.
