### ISSUE TITLE
Work record needed [?] for BLorient549

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1578]
In BLorient549 there is no. 12 entitled "Rules regarding the regulation and constitution of the Christian Church" beginning thus: አንቀጽ፡ ቀዳማዊ፡ በእንተ፡ ቤተ፡ ክርስቲያን፡ ወዘኵሉ፡ ሥርዓታ። I would assume it falls within the wide and diverse ሥርዓተ፡ ቤተ፡ ክርስቲያን፡ category, however I cannot determine, whether I should create a new record or use one of existing records. I will appreciate any suggestion.

https://archive.org/details/catalogueofethio00brituoft/page/94/mode/2up

https://betamasaheft.eu/works/LIT2332serata/main
https://betamasaheft.eu/works/LIT2331serata/main
https://betamasaheft.eu/works/LIT2330serata/main

@thea-m @DariaElagina @DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Marcin, 
is it possible to know what is the content? LIT2332serata (other two records remain unused, I do not know why) is for the text of a special type, Amharic symbolic interpretation for the parts of a church building, contrary to what one think as the first of "ser'at". Your title reminds more of the canon law, is it possible that this text is a part of Senodos or similar texts?

**Comment by MarcinKrawczuk** [comment]
@DenisNosnitsin1970 Unfortunately all the information I have is what Wright gives in his catalogue and all he gives is an incipit and the title. I've not been able to locate this manuscript online.

**Comment by eu-genia** [comment]
Well there is a confusion now. 

Actually BL 549 has a (part of) the main SBK, which should have the ID LIT2332serata, but it seems that it was partially misused for something else, while at the same time there is als LIT4020RegulaeHierarchia for the same, main SBK.

To explain: the IDs in the BM were created from the index of the EAe, so to disambiguate the existing IDs we have to see the index and the EAe. Ideally, the meaning of the IDs should have been:

2332 = Śǝrʿatä betä krǝstiyan, rel. I:340b; III:626b, 765b; IV:273b, 631a–32b, 806b, 960b

We read in EAe IV, 631 that this is the text defined by Dillmann as

Regulae de Hierarchia ecclesiastica [Ordines Ecclesiae, ejusque gradus, a Patribus sanctis constituti.] ‘Orders of the Church and its Grades Established by the Holy Fathers’. BL Add. 16,205

Following Dillmann, Conti Rossini (1900:630f.) refers to ten manuscripts containing a work under this title (but BN d’Abbadie 65, 78 should probably be excluded from his list). This S. (Regulae …) seems to be a writing in Geez which frequently
appears in collections of canonical-liturgical works, as one of the three texts which typically accompany the Mäshafä fäws mänfäsawi (which Dillmann considered parts of the latter, but s. Kleiner 2000, vol. 1, 36–40). Apart from the Regulae …, the other two, in Dillmann’s (DillmLond 39) rendering, are: – Ceremoniale sacerdotum [Regulae de ministerio sacerdotali, quae ad preces et
liturgias rite administrandas pertinent], ‘What is Due from the Order of the Service, Duty of the Clergy, What is Required in Prayers and Liturgies’; – Quaestiones de rebus ecclesiasticis subtiliores, cum solutionibus: [Quaestiones et interrogationes Patrum, earumque solutio], ‘Inquiries and Questions to the Fathers, and Their Responses’.
From the catalogue descriptions it is not quite clear if these three texts are parts or sub-chapters
of one work, or not (cp. mss. **London, BritLib Orient. 549**, fols. 65r–98v; Orient. 799, fols. 70v–80v); they are not always three (cp. ms. VatLib
Cerulli Etiop. 81), and not always identifi ed by
the full titles (cp. Tanasee 169, fols. 50ra–81vb).
In some cases the title **SBK wamaergiha** can probably appear as heading for all of
them (cp. Orient 550, fols. 84r–98r; Orient. 788,
fols. 102–25r). Of specific interest is ms. EMML
no. 1941 (probably the oldest witness, dated
to 1664) fols. 26r–43r, where the title**SBK wamaergiha**  is applied to a text of
somewhat different content, but the Regulae …
are contained on fols. 26r–27v (cp. also EMML
no. 1952, fols. 9b–11b, both from ÷Däbrä Hayq
Éstifanos).


By this definition it is a doublet for LIT4020RegulaeHierarchia ( @thea-m ?)

But it seems that @DenisNosnitsin1970 was using the 2332 for something else

2330 = Śǝrʿatä betä krǝstiyan amä qǝddaseha, rel. IV:631b = EMML nos. 2537, 2588, 3111
2331 = Śǝrʿatä betä krǝstiyan läʾǝgziʾabǝḥer, rel. IV:632b = Cerulli Etiop. 81
_____________

So we have now two IDs (2332 and 4020) for the main Ge'ez SBK
@DenisNosnitsin1970 was using 2332 for the Amharic SBK (Yet, it seems to me from reading the article, that the Amharic SBK is also not one but many...), so, to avoid creating too many new IDs, it may make sense to replace 2332 in those MSS which have the Geez Regulae for 4020, leave 2332 for (one of the) Amharic SBK


BLor549 has then 4020

**Comment by eu-genia** [comment]
(I see now that you already replaced 2332 through 4020 in BL799 which is exactly what I was suggesting, great)

**Comment by DenisNosnitsin1970** [comment]
I will elaborate LIT2332 a little, to show what it is for.

**Comment by eu-genia** [comment]
I already responded above (https://github.com/BetaMasaheft/Documentation/issues/1578#issuecomment-732885205) the ID for the Regulae is LIT4020RegulaeHierarchia

**Comment by MarcinKrawczuk** [comment]
@eu-genia I am confused. My understanding was that in [BLorient549](https://betamasaheft.eu/manuscripts/BLorient549/main) LIT4020RegulaeHierarchia should be used for ms_i5 (which I did) but we haven't reached any conclusion regarding ms_i13. Or am I missing something?

**Comment by eu-genia** [comment]
Sorry you are right I was looking up at a wrong place.
As for no. 13, Wright himself says that this is the same text as in BLadd16205 on f. 25 (ms_i2), that is LIT4022RegulaeFidei

**Comment by eu-genia** [comment]
I have updated the work records to disambiguate https://github.com/BetaMasaheft/Works/pull/477
