### ISSUE TITLE
Delete LIT1998Mazgab

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1579]
@karljonaskarlsson suggests the deletion of LIT1998Mazgab, which is identical with LIT3178Deggwa, where its title can be included (it has been used nowhere). Any objections?
@DariaElagina @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
If you sure that is the same... (I am not 100% sure).

**Comment by karljonaskarlsson** [comment]
I think that there are numerous (or maybe innumerous) different versions of antiphon collections that are called "Dǝggʷā" (and additionally, many which are called "Mazmur"). But I have not noticed a dichotomy between books calling themselves "Dǝggʷā" bzw. "Mazgaba Dǝggʷā".

**Comment by eu-genia** [comment]
according to the EAe, Mazgaba  Dǝggʷā  (lit. ‘the treasury of the Dǝggʷā’), i.e. Dǝggʷā and Soma dǝggʷā together

**Comment by eu-genia** [comment]
So if we have manuscripts with the Dǝggʷā +Soma dǝggʷā LIT1998Mazgab should be the grouping ID

**Comment by karljonaskarlsson** [comment]
Based on the information I have gathered, I have not found support that the definition of "Dǝggʷā" versus "Mazgaba Dǝggʷā" suggested by the EAE is based on manuscript evidence. I wonder if it would be good to have a record for the Dǝggʷā (= calendrical antiphon collection containing all the expected types of antiphons) regardless of recension etc. and regardless of the presence/absence of the section for the Great Fast.

**Comment by thea-m** [comment]
@karljonaskarlsson suggests to wait a bit to carry out this work, which due to the complexity of the Deggwa cannot be decided quickly. Once his work will provide a basis for the improvement of the concerned work records in BM, we'll come back to it.
Thanks everyone!
