### ISSUE TITLE
left array for lookup member?*

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1582]
If I click in the follwong work record on "text"

https://betamasaheft.eu/works/LIT2948RepCh229/main

I receive the follwing error message:
https://betamasaheft.eu/works/LIT2948RepCh229/text

As @PietroLiuzzo recommanded, I keep on reporting those cases.

**Comment by PietroLiuzzo** [comment]
the fix breaks other instances. https://betamasaheft.eu/works/LIT3122Galaw/text

**Comment by PietroLiuzzo** [comment]
The error complains that the expression to the left of a lookup operator needs to be a sequence of maps or arrays [at line 122, column 18, source: /db/apps/BetMas/modules/dtsclient.xqm] 
`for $members in $DTSnav?member?*`
to loop into 
`member : [{"dts:ref":"1"},{"dts:ref":"2"}]` an array of maps
so, I think this is correct, just like https://exist-db.org/exist/apps/wiki/blogs/eXist/XQuery31
I will enquire about this issue.

**Comment by PietroLiuzzo** [comment]
https://exist-db.slack.com/archives/CG2MRUZ35/p1606511137428800
