### ISSUE TITLE
EMIP Images Unavailable (502 error)

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1584]
The images for EMIP manuscripts are returning 502 errors, preventing them from being viewed in the viewer.

![Screen Shot 2020-11-30 at 14 16 42](https://user-images.githubusercontent.com/6315671/100614611-ad04c480-3316-11eb-994e-9b086f804643.png)

(The manifests work fine though)

**Comment by PietroLiuzzo** [comment]
thanks, IIPImage Server was down, it has been now restarted.
