### ISSUE TITLE
Miracles of Mary Help requested

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1587]
EMIP 154 has 49 miracles of Mary, for which I correlated text descriptions with work files for almost all, with the following text descriptions remaining. If anyone can establish which work file these are, I'd be very grateful. 

The first is:

'How a certain God-fearing man took his two elder daughters and went to church, leaving in his house Mary, his youngest daughter, in spite of her protests and wish to go in order to receive the Sacrament; and how the Virgin Mary appeared from out of her picture to the child, and told her that she would take her to herself in Paradise after three days; and how a godly man saw the child three days later, clad in purple and following the Virgin up into heaven'

The second: 
'How the Virgin delivered from devils the soul of a scribe who was engaged in writing a copy of the Book of her Miracles. This scribe had a brother who had sinned, but not knowing him they seized the innocent man and tried to carry him off to hell'

The third:
'How a certain woman whose husband had left her for another woman begged the Virgin Mary to kill the other woman; and how the Virgin Mary brought the other woman, who was devoted in worship of the Virgin, to repentance'

**Comment by thea-m** [comment]
Hello! The first two are LIT3593Miracle and LIT3604Miracle. The third one is probably a version of LIT6031MMWifeGen - that's the general record if no more information is known, it exists in a version with names of the protagonists, LIT5003MiracleJonahWife, and one without their names, LIT3868Miracle.

**Comment by elambrinaki** [comment]
Hello! Could you please advice me how can I follow updates in the records of miracles of Mary on Beta Masaheft? Is there any way I can search for such updates in the app? Thank you!

**Comment by Ralph-Lee-UK** [comment]
@thea-m. as ever, .many thanks.
