### ISSUE TITLE
Pencil writing in ms BDLaethf34

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1588]
Ms BDLaethf34 has some writings in pencil on fol. 1r, written by Juel-Jensen himself (at least in part).
You can see the picture here:
(https://onedrive.live.com/?cid=97A11C83AFE07775&id=97A11C83AFE07775%21127566&parId=97A11C83AFE07775%21127799&o=OneUp)

The second and third writings pose no problem ("Ms Aethiop. 39" and "Belonged to the picturesque Captain Speedy who was in Napier's campaign"). The first is a bit unclear to me:
"Begun (?) with ... of the negus"
Can you read that?
Thank you!!

**Comment by SusanneHummel** [comment]
I read: "Begins with Hymn of the Negus"

**Comment by MassimoVilla** [comment]
> I read: "Begins with Hymn of the Negus"

Great! Sounds reasonable. I couldn't decipher that "hymn", now I can't stop seeing it.
I close the issue. Thank you
