### ISSUE TITLE
values for @subtype in div

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1590]
The schema currently contains an open list of values for `@subtype` in `<div>`: https://betamasaheft.eu/Guidelines/?id=div. 
While @antobrita has been working on the encoding of work records for the gospels, she found it useful to work with until now unused values as "coretext" or "subunit" and many others for the precise subdivision of the texual units included in one work record. I wonder whether it might be useful to include these, with definitions, in the schema. They would probably be relevant also to other texts, and it might be good for the values in particular work records not to become too idiosyncratic. 
@antobrita could you provide a list, ideally with definitions, as a basis for discussion?
@antobrita @DariaElagina @eu-genia @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
it is an open list, and can be easily edited. please, remember to provide short definitions of the new values.

**Comment by antobrita** [comment]
> @antobrita could you provide a list, ideally with definitions, as a basis for discussion?

Sure! The list the following one:

**heading**:  opening lines of a text that precede the incipit. The **heading** can contain the title (or a summary of the content) and it is clearly distinct from the incipit.

Ex: the opening lines of the Gospels:

![image](https://user-images.githubusercontent.com/19854597/101198137-44de1780-3663-11eb-88ce-b901990cf0a0.png)


**coretext**: the main content of a text.

Ex: the text of the Gospels (without heading and colophon).


**colophon**:  colophon of a work (not of a manuscript) that is sistematically transmitted (copied) with the text.

Ex: the colophon of the Gospels.

![image](https://user-images.githubusercontent.com/19854597/101199668-8374d180-3665-11eb-8292-a3242c5153c4.png)


**textsubunit**: general way to indicate a specific section of a text that need to be encoded but does not correspond to the textparts mentioned above.

Ex: the statement about the Eusebian sections in the Gospels.

![image](https://user-images.githubusercontent.com/19854597/101200471-a05dd480-3666-11eb-82b8-17cb074b040f.png)

**list**: a number of connected items or names written consecutively, either one after the other or one below the other.

Ex: tituli of the individual gospels.

![image](https://user-images.githubusercontent.com/19854597/101200972-50334200-3667-11eb-8c37-a580640fe692.png)

and 

![image](https://user-images.githubusercontent.com/19854597/101201120-85d82b00-3667-11eb-9da1-6f9bd687ac3d.png)

**Comment by antobrita** [comment]
I think this might be helpful to refine the search in BM. 

What do you think?

**Comment by thea-m** [comment]
Thank you! I have nothing against adding these values, but we will need some more opinions.
I wonder now about the benefit of adding subtype="textsubunit", instead of adding no subtype in these cases.
And I have one question on the definition of heading: How is it differenciated from a title? (Title is defined now as "contains the title as well as tafaṣṣama/malʾa or similar expression.") Is it a difference of layout, or also of content?

**Comment by antobrita** [comment]
> I wonder now about the benefit of adding subtype="textsubunit", instead of adding no subtype in these cases.

I thought it would help to better specify that "textsubunit" is still a specific portion of a given work. I have noticed, for instance, an inconsistency in the use of the value "chapter" in some work records. For instance, in the work LIT1812GospelLuke:

the value "chapter" is used with reference to the whole Gospel:

<div type="textpart" subtype="**chapter**" xml:lang="gez" corresp="LIT2713Luke">


but also with reference to the individual chapters of the Gospel:


<div type="textpart" subtype="**chapter**" xml:id="ch1">
                  <label>Chapter 1</label>
               </div>
              <div type="textpart" subtype="**chapter**" xml:id="ch2">
                  <label>Chapter 2</label>
               </div>
              <div type="textpart" subtype="**chapter**" xml:id="ch3">
                  <label>Chapter 3</label>

creating some confusion in the structure of the text (is the value "chapter" referred to a larger portion of text or to its subsections?)

In this case, one could keep "chapter" for the larger portion of text (textual unit) and use "textsubunit" for its individual  subsections.

I think it makes more sense. But, again, I do not know if you want that for BM.

**Comment by antobrita** [comment]
> I wonder now about the benefit of adding subtype="textsubunit", instead of adding no subtype in these cases.

I thought it would help to better specify that "textsubunit" is still a specific portion of a given work. I have noticed, for instance, an inconsistency in the use of the value "chapter" in some work records. For instance, in the work LIT1812GospelLuke:

the value "chapter" is used with reference to the whole Gospel:

![image](https://user-images.githubusercontent.com/19854597/101463930-5747a200-393e-11eb-9228-65e6fecbaf92.png)

but also with reference to the individual chapters of the Gospel:

![image](https://user-images.githubusercontent.com/19854597/101464079-7cd4ab80-393e-11eb-8b27-2bef2bf40b09.png)

creating some confusion in the structure of the text (is the value "chapter" referred to a larger portion of text or to its sub-sections?)

In this case, one could keep "chapter" for the larger portion of text (textual unit) and use "textsubunit" for its individual subsections.

I think it makes more sense. But, again, I do not know if you want that for BM.

**Comment by antobrita** [comment]
> And I have one question on the definition of heading: How is it differenciated from a title? (Title is defined now as "contains the title as well as tafaṣṣama/malʾa or similar expression.") Is it a difference of layout, or also of content?

The "heading" can contain the title or the summary of the content and is expected at the beginning of a text, unlike "subscriptions" that can contain a title preceded by  tafaṣṣama/malʾa and that are always found at the end of a text. It is matter of layout, or if we want of _locus_ in the manuscript.

And again, I ignore if this can be of some help for BM.

**Comment by antobrita** [comment]
> but we will need some more opinions.

Yes, sure. I will wait for the others' opinion before committing the changes I have made in the Gospel Works and open a Pull Request.

**Comment by eu-genia** [comment]
It seems to me in part to return to the discussion we already had, partially visible in this issue https://github.com/BetaMasaheft/Documentation/issues/946
where we specified that textparts containing titles may have multiple subtypes 
`<div type="textpart" subtype="title expanded subscriptio explicit">`
where I honestly would say that heading is the same as "title expanded inscriptio"
I have nothing against new subtypes but would careful as to creating synonymous expressions for things already defined

**Comment by DenisNosnitsin1970** [comment]
I used to apply the term "heading" exactly to the same thing as Antonella indicated, but for the rest the term remained a little vague to me. I see that it is used in catalogue of non-Ethiopian manuscripts, sometimes, but it is not easy to grasp what it is, exactly. In the case of the Gospels, historically, what Antonella calls "heading" seems to have developed from the title. Antonella, are there any other examples of a "heading" for any other Ethiopic work?

**Comment by antobrita** [comment]
> In the case of the Gospels, historically, what Antonella calls "heading" seems to have developed from the title.

It is exacly like that, Denis. And the aim of having clearly identified places in the manuscript where titles in their different forms can be found, would allow in the future to make researches on the historical evolution of phenomena (in this case on titles, for instance) starting from the data encoded in BM (this is the main advantage of this work).


> are there any other examples of a "heading" for any other Ethiopic work?

There are (at least I call them heading), even if with a different layout from the one found in Gospels. I'm writing an article on titles where I'm trying to identify the different typologies (and the variety is really reach).


> but for the rest the term remained a little vague to me.

It is because there are no studies on that, and consequently no clear definition, I think.

**Comment by thea-m** [comment]
Let's try to wrap this up. 
If I understand correctly, there are no objections agains adding: colophon, coretext, textsubunit, list. Is everyone happy with adding these, together with the definitions supplied above?
For "heading", I still struggle to grasp the definition. Maybe this will be easier once @antobrita 's article has been published. In the meanwhile, it might be better to stick to @eu-genia's proposal of the combined existing values.

**Comment by DenisNosnitsin1970** [comment]
Well, I think that one thing to add definitions, another thing to apply them to cataloguing practice in the way 
that the definitions are functional for a substantial group of texts, and do not contradict to other BM principles.  "Subunit" for what Antonella calls "heading" (however, encoded as "Headline", in "JohnGospelHeadline", as I see) or "chapter" is OK (but a part of the text is called me'eraf it exactly corresponds to "chapter"). But what exactly is the profit if I encode, for instance, "Biography of John" not as "LIT1693John#BiographyJohn" as a part of the Gospel of John but as "subunit"? Now, we have some part texts of the Gospels encoded like above, LIT1693John#BiographyJohn, some not (but this practice can be applied to  all works). I think that this method allows a great flexibility and precision in the descriptions. I personally would simply create records of the same type for the missing part-texts rather then introduce smth completely different. What to do with the mss that were already recorded?

**Comment by DenisNosnitsin1970** [comment]
Just to clarify: I am  a little puzzled because I do not see exactly what is going to be considered "textsubunit" and where, and how it matches or affects, for example, the current shapes of LIT2715John (Gospel of John proper) and the general record LIT1693John that is supposed to include four units (tituli, biography, Bǝsrāta Yoḥannǝs, stichometry). Sorry, it is only now that I came to see closer at the discussion, after a few exhausting weeks. I can imagine "colophon" (= stichometry) or "heading" of the Gospels as smth equivalent to "subunits" (but I see the reservation of Zhenja and share it). It will more dificult for "tituti" part that seems to be on par with "biography". For the Prefatory part, it might be even more debatable and it is exactly this part of the Four Gospel books that produces more problems and unclarities.

**Comment by eu-genia** [comment]
Denis, I think you are speaking of something else.
The IDs for msItems when cataloguing content, whether first or second level, remain as they were.
The discussion I see is whether we need to refine the definitions for subtypes in divs for textparts when producing an edition, as "chapter" seems too general, especially when textparts are nested at different levels.
I have nothing against using coretext and subunit in case of nested chapters/subchapters. I have more reservations in introducing new entities for notions which we already can describe with what we have.

**Comment by antobrita** [comment]
> Denis, I think you are speaking of something else.
> The IDs for msItems when cataloguing content, whether first or second level, remain as they were.
> The discussion I see is whether we need to refine the definitions for subtypes in divs for textparts when producing an edition, as "chapter" seems too general, especially when textparts are nested at different levels.
> I have nothing against using coretext and subunit in case of nested chapters/subchapters. I have more reservations in introducing new entities for notions which we already can describe with what we have.

Zhenia got the point. The IDs from msItems remain the same. 

Anyway, if you think it is not necessary to introduce new entities because what we have is already enough, no problem. We do not have to do that, really.

**Comment by DenisNosnitsin1970** [comment]
Thanks, now it is clearer than before.  I am still not sure if we have substituted the existing notions for smth new. However, it is not the case for the cases where it is clear what will specified and how. "Heading" remains somewhat illusive for me, I understand what you mean (though, as I told, I know immediately only one case), but I see that elsewhere "heading" is equated to "incipit", or it is said that "incipit" is the same as heading but called after the words "hic incipit" (an interesting footnote in the book "Rereading Middle English Romance: Manuscript Layout, Decoration, and the ..." that you can find in google books, p. 168, footnote 17, with insight who uses the terms and how, I did not trace these indications), but some other use both, so obviously for them it is not the same (there are also curious combinations: "heading(s)" vs "closing(s)")  Also the definition for "coretext: the main content of a text" I feel that it needs a little more consideration as it appears subjective: the main from whose point of view? What is "content" (phisical, intellectual)? I think we will need a little more time for these.

**Comment by eu-genia** [comment]
Denis, you are overcomplicating things.
We now have the structure, for all texts, with practically only chapter used as a subtype for any textpart
The suggestion was to have
coretext for the entire main text
subunit for nested parts
and chapter only for those parts which are really chapters

defining heading is a very different matter, it is not what we call incipit, but we have a way to describe it, see my posting above

**Comment by DenisNosnitsin1970** [comment]
Ok, thank you Zhenja, now it is quite clear.

**Comment by thea-m** [comment]
Thanks everyone! For sure everything can be discussed in more depth. But it seems to me from this discussion that creating the values coretext, textsubunit, colophon and list with the definitions provided above by Antonella would be fine for everyone and would improve our encoding. If there are no objections until the end of the week, I will go ahead and create them.
