### ISSUE TITLE
iiif server crashing far too often

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1591]
@PietroLiuzzo Hi Pietro! I am sorry, I have the same problem now as https://github.com/BetaMasaheft/Documentation/issues/1583

The images of BML Or. 148 aren't loading https://betamasaheft.eu/manuscripts/BMLor148/viewer

**Comment by PietroLiuzzo** [comment]
I have restarted the image server. there is a deeper issue which I will investigate asap so I am not closing this and you can drop a message here when the issue occurs.

**Comment by PietroLiuzzo** [comment]
note for me: check release and version consistency of IIPimage server on current VM.

**Comment by PietroLiuzzo** [comment]
restarted one more time

**Comment by Ralph-Lee-UK** [comment]
Understood, and thank you!

**Comment by elambrinaki** [comment]
Hi @PietroLiuzzo ,
The viewer isn't working.

**Comment by PietroLiuzzo** [comment]
should be back now, thanks for heads-up

**Comment by elambrinaki** [comment]
It is! Thank you!

**Comment by elambrinaki** [comment]
@PietroLiuzzo Sorry for bothering you, would it be possible to please restart the viewer?

**Comment by PietroLiuzzo** [comment]
Thank for the the notification, I have seen it only now sorry. I am restarting the server and have introduced some changes suggested by the system administrators which should help solve the issue. it will take around half an hour from now for the apps to return to operation

**Comment by elambrinaki** [comment]
Thank you! @PietroLiuzzo

**Comment by elambrinaki** [comment]
Hi @PietroLiuzzo , 
When you have a chance, could you please restart the viewer? https://betamasaheft.eu/manuscripts/ESagm004/viewer isn't loading.
Happy Christmas!

**Comment by PietroLiuzzo** [comment]
this luckily was not the server. which means perhaps the changes did work.
it was an issue in the data, which I fixed in this PR. 
https://github.com/BetaMasaheft/Manuscripts/pull/936
Merry Christmas!

**Comment by elambrinaki** [comment]
Wonderful, thank you!

**Comment by elambrinaki** [comment]
@PietroLiuzzo I have a problem with ESqs014 https://betamasaheft.eu/manuscripts/ESqs014/viewer. Could you please help?

**Comment by PietroLiuzzo** [comment]
I am sorry this is not getting any better, but be reassured we are working on it on several fronts and we will find out what is going wrong. I have restarted once more, now you can see the images.

**Comment by elambrinaki** [comment]
Thank you!

**Comment by elambrinaki** [comment]
@PietroLiuzzo I am experiencing a problem with loading images for https://betamasaheft.eu/manuscripts/ESakm016/viewer. May I please ask for your help?

**Comment by PietroLiuzzo** [comment]
shuuld be fine now, sorry for the inconvenience

**Comment by PietroLiuzzo** [comment]
test [cantaloupe](https://cantaloupe-project.github.io/) as alternative to iipimage server

**Comment by elambrinaki** [comment]
@PietroLiuzzo Thank you!

**Comment by elambrinaki** [comment]
@PietroLiuzzo This is me again. Could you please help with loading https://betamasaheft.eu/manuscripts/ESmr001/viewer?

**Comment by PietroLiuzzo** [comment]
is is restarted now

**Comment by elambrinaki** [comment]
Thank you!

**Comment by elambrinaki** [comment]
ESdd010 doesn't load https://betamasaheft.eu/manuscripts/ESdd010/viewer

**Comment by PietroLiuzzo** [comment]
encouraging bit is, this time it is not an issue with the server, it is simply wrong filenaming, I am fixing that now.

**Comment by elambrinaki** [comment]
Great! Thank you very much.

**Comment by PietroLiuzzo** [comment]
Increase of total memory, limiting RAM assigned to exist and a few new settings in IIIF configuration seem to have at least strongly limited this issue.
