### ISSUE TITLE
provide feed for specific searches (given a query, if there are new results, send update to registered user)

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1592]
Hello! Could you please advice me how can I follow updates in the records of miracles of Mary on Beta Masaheft? Is there any way I can search for such updates in the app? Thank you!

_Originally posted by @elambrinaki in https://github.com/BetaMasaheft/Documentation/issues/1587#issuecomment-736901553_

**Comment by PietroLiuzzo** [comment]
We have a generic "latest" function and could potentially provide feeds, however, what you are asking for is a filtered feed for only specific items or groups of items, which sounds like a nice feature. How would you envisage that to work for you? Do you have any examples of how this is done by others?
would any one else find this functionality useful in any of its possible implementations?

**Comment by Ralph-Lee-UK** [comment]
A feed of the latest updates to work, art and other records would be really helpful, yes. It wouldn't have to be just for a specific item, but perhaps such a feed could be grouped so that records that refer to other records are together - so new records for miracles of Mary would then be together.

**Comment by PietroLiuzzo** [comment]
here is the "latest" list, which lists changes from the last two weeks in the db. 
https://betamasaheft.eu/team.html
any such feed will contain only changes which have been pushed to the db. if you want to keep up to date with the development of the data, than GitHub is where we have to look for... keep requirements coming, so we can figure out what to do. @thea-m @eu-genia @DenisNosnitsin1970 @smaugustine @DariaElagina @MarcinKrawczuk

**Comment by thea-m** [comment]
I remember from conversations in the past that there was a desire for such a feed for updates to the guidelines.
(I cannot personally suggest something concrete, for me looking at the history in GitHub is fine for the guidelines, which are not so frequently updated - was there someone among the readers of this issue who had wished for this?)

**Comment by elambrinaki** [comment]
> A feed of the latest updates to work, art and other records would be really helpful, yes. It wouldn't have to be just for a specific item, but perhaps such a feed could be grouped so that records that refer to other records are together - so new records for miracles of Mary would then be together.

I agree with @Ralph-Lee-UK . This way, one can view the work of the collegues on the subject of interest. There might be an edit in the date of a manuscript, or added IDs for the miracles, or a new miracle record.

**Comment by PietroLiuzzo** [comment]
these are all different things, we have to see how to make them fit together (or not together). how would you envisage this? as a page with a search for latest changes which you can filter by type or more of an atom/rss feed? for example, getting a notification if a manuscript related to a miracle is updated is not the same thing as getting to know if the record about the miracle was updated.

**Comment by elambrinaki** [comment]
Yes, a page with a filtered search for latest changes will be great.

**Comment by elambrinaki** [comment]
@PietroLiuzzo Thank you for the link to the "latest" list https://betamasaheft.eu/team.html!

**Comment by elambrinaki** [comment]
@PietroLiuzzo Ideally, one could not only search for updates in records, but for the new records in the chosen category as well. For example, I am interested in following the changes in existing records and the additions of new records for LIT2384Taamme.

**Comment by PietroLiuzzo** [comment]
I am postponing this, as it definitely needs a better user management (on its way, but not for this release)

**Comment by PietroLiuzzo** [comment]
archiving, may be reopened in the future.
