### ISSUE TITLE
New work record for Conti Rossini Golden Gospel of Ham

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1593]
> In which manuscript is the work you would like to create attested? 

https://betamasaheft.eu/manuscripts/DabraLibanosHamGG1/main
@nafisa-valieva and I are preparing a new detailed encoded version of this.

> Or for which other reason would you like to create this new record?

These are already identified and edited works, which should have an ID.
Bausi also matched them to the manuscript of which we have the images
https://betamasaheft.eu/bibliography?pointer=bm:Bausi1997ManoscrittiEritreaParteIII

The work records will allow us also to store the transcription from the conti rossini edition and the association with the reordering done by Bausi in the work records, separated from the manuscript transcription based on the images.

If there is no objection, I will just carry on.

**Comment by nafisa-valieva** [comment]
Yes, great!
we also have transcribed texts by Roger Schneider, in which he followed Conti Rossini's numbering and collated edited texts with the texts from the images he took. He did some important comments as well. I think it can be considered as 'edition in progress'. Where, according to you,  the images of RS's handwritings can find their place?

**Comment by PietroLiuzzo** [comment]
> we also have transcribed texts by Roger Schneider, in which he followed Conti Rossini's numbering and collated edited texts with the texts from the images he took.  He did some important comments as well. I think it can be considered as 'edition in progress'. 

for this transcriptions and edition in progress, I think they can be added to the work record as such. we have several other similar cases.

> Where, according to you, the images of RS's handwritings can find their place?

this is an interesting, although probably separate, issue. We do not have, as far as I remember, this kind of material, but it would definitely be an interesting case for expanding. out of the box I would inclined to treat the handwritten notes as a manuscript, transcribe them independently of the Work records and connect accordingly.+

I think in this issue we are mainly trying to gain consensus from other team members @thea-m @DenisNosnitsin1970 @eu-genia 
@DariaElagina @smaugustine @Ralph-Lee-UK  on creating one work record for each of the texts identified and edited by Conti Rossini and belonging to the added parts of the manuscript of Dabra Libanos, let us get that done first and then move on to this further piece of work.

**Comment by thea-m** [comment]
I am sure that you have already carefully considered whether these works should be created :) it would be the traditional convention to point here to what there works actually are so that people can have an actual chance of searching for them in BM. As I am quite sure you have done this thoroughly, I will assume it will be a waste of time for me to get into the literature to a point which will allow me to carry out these searches.

**Comment by PietroLiuzzo** [comment]
I think @nafisa-valieva did that check already last year. we will check again, but as far as I know these are documents not found elsewhere and I would not expect that during the year they had been created.

**Comment by eu-genia** [comment]
It would be good to treat this in more or less the same way as the Liber Aksumae (BNFabb152 - encoded by Anais, BDLbruce93)

**Comment by PietroLiuzzo** [comment]
that is an additional layer of encoding which will be done at some point for sure, but for the moment we would like only to be able to organize what knowledge we have. we will report on the double-check searches asap.

**Comment by nafisa-valieva** [comment]
I have checked works 'Rossini' and searched for incipits of documents, my résultats are négatives,  so I think we can be sure the works for L'Evangelo d'oro can be created from zero.

**Comment by thea-m** [comment]
allez-y
