### ISSUE TITLE
facet search by date

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1594]
**Is your feature request related to a problem? Please describe.**
once searched in the facet I want to filter by "dates"

**Describe the solution you'd like**
a filter for birth, death, floruit

@DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
No specific problem yet. Basically, it would be nice to have the results offered according to the chronology (yes - birth, death, floruit time) + get snippets. But I see that the problem is lack of information in the data.

**Comment by PietroLiuzzo** [comment]
the snippets including dates have been added for every person record of any type. I have added fields which will allow to search in any of the attributes of datable elements separately and facets to filter down results obtained according to date. because, as you rightly say the data is not very uniform I have opted as elsewhere for a declarative selector of existing values instead of trying to provide time ranges. here you see the results of a simple text search and the filters provided as well as the snippet with the available information. 
<img width="1076" alt="Bildschirmfoto 2021-09-09 um 11 59 57" src="https://user-images.githubusercontent.com/508012/132665823-4b47d1bb-0815-4fcd-9f88-ea1020107244.png">
<img width="1403" alt="Bildschirmfoto 2021-09-09 um 12 21 46" src="https://user-images.githubusercontent.com/508012/132669191-c9a6825f-d2df-482b-a468-42f3ec9233a1.png">
I think that in a way this is also better than a slider because it tells you directly what we actually have and how many of them, but that is perhaps just my bad taste! let me know if it looks ok, in which case, please close the issue as well.

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @DariaElagina @abausi @thea-m
