### ISSUE TITLE
add summary of information from the record

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1595]
from @SophiaD-M  in demo call 
in the results of the facet search print a short summary of the available informations (as in list view and +)

for persons
- dates, description, names, occupation

for works
- abstract, author, dates

for manuscripts 
- date, general title, number of leaves, number of quires

please add more requirements

**Comment by SophiaD-M** [comment]
Really nice! Thank you. 
That would really help the user to single out search results of relevance to them. 

Would there be also a chance to rank the results? Maybe by statistics, the more often a certain term/result is used the higher up in the result list it features? Or some other way to indicate the rank of an entry?
For example "Amda Seyon" - there was a king by this name, very famous, and a second king, less famous. So I would assume the majority of users would want to find information on the Amda Seyon I. But even when defining the search to "persons", the first few results are to some officers of the king, and "possibly his wife or daughter".

**Comment by PietroLiuzzo** [comment]
The results view now has an added resizable box containing a summary of informations extracted from the file. it merges this request with the information provided in the list view.
Works results will look like this
<img width="1207" alt="Schermata 2021-02-18 alle 12 10 14" src="https://user-images.githubusercontent.com/508012/108348617-4e970600-71e2-11eb-8410-3c712afc58d8.png">
person results will look like this
<img width="920" alt="Schermata 2021-02-18 alle 12 10 50" src="https://user-images.githubusercontent.com/508012/108348687-63739980-71e2-11eb-9f7f-a1b88308f9ae.png">
<img width="909" alt="Schermata 2021-02-18 alle 12 12 40" src="https://user-images.githubusercontent.com/508012/108348898-a2095400-71e2-11eb-8190-e3138a8c6778.png">
Manuscripts something like this
<img width="900" alt="Schermata 2021-02-18 alle 12 20 44" src="https://user-images.githubusercontent.com/508012/108349841-c31e7480-71e3-11eb-8ea1-2c18f3a0b314.png">
Institutions 
<img width="909" alt="Schermata 2021-02-18 alle 12 37 02" src="https://user-images.githubusercontent.com/508012/108351591-07ab0f80-71e6-11eb-9da8-1ec48db8d710.png">
Places the same without the number of mss.
