### ISSUE TITLE
delete operation flow into app faulty (mss in new do not get deleted when moved to proper folder)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1599]
https://betamasaheft.eu/manuscripts/BLorient690/main leads to the error 

> Something has gone wrong and there are more than one item with id BLorient690.
> 
> /db/apps/BetMasData/manuscripts/new/BLorient690.xml
> /db/apps/BetMasData/manuscripts/LondonBritishLibrary/orient/BLorient690.xml

As far as I can see however, this manuscript is not contained in the "new" folder anymore.

**Comment by PietroLiuzzo** [comment]
I am fixing this example, but I am keeping the issue to look at as it occurs often.

**Comment by thea-m** [comment]
Same here:
https://betamasaheft.eu/manuscripts/BLorient555/main
https://betamasaheft.eu/manuscripts/BLorient553/main

**Comment by MarcinKrawczuk** [comment]
And here:
https://betamasaheft.eu/manuscripts/BLorient594/main

**Comment by PietroLiuzzo** [comment]
should be fine now, still I am investigating the cause

**Comment by PietroLiuzzo** [comment]
I have rolled out entirely permission issues. this has to be related to some stage of the commit process I have not taken enough into consideration. it would greatly help me if you could check that everything is fine, next time you create a mss record in the app and then move it to its folder following the instruction. this way I will know what recent merge to check too fix the webhook. thanks a lot!

**Comment by PietroLiuzzo** [comment]
I probably found the error yesterday, fixing the double MA value... please let me know next time if this happens (you create a record, commit it, move it, commit the move and find a double, i.e. the previous location has not been cleared). thanks
