### ISSUE TITLE
A treatise on computus

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1600]
I want to create a new record for a short computus treatise that is contained in some old Psalters like Abbadie 105, BFBS 176, BFBS 176, and outside of the Psalter at least in Vat et 81. Any comments or objections?

**Comment by eu-genia** [comment]
Sure, agreed

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Works/pull/413#pullrequestreview-547390846
