### ISSUE TITLE
problem when storing name on file creation and update (empty entry stored and not updated)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1603]
https://betamasaheft.eu/persons/PRS13289Akaweh/main

The name is not displayed, though the XML seems fine 
```
<persName xml:lang="gez" xml:id="n1">አካውሕ፡</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">ʾAkāwǝh</persName>
<persName xml:lang="ar" corresp="#n1">كاؤو</persName>
<persName xml:lang="cop" corresp="#n1">ⲕⲱⲟⲩ</persName>

@MarcinKrawczuk 
```

**Comment by thea-m** [comment]
This seems to persist with records created by @MarcinKrawczuk, recently PRS13277Abbelo and PRS13277Abbelo
(I did not carry out exhaustive checks to see whether this affects other person records and Marcin is just the only one currently noticing....but other person records seem fine)

**Comment by PietroLiuzzo** [comment]
thanks for reporting

**Comment by PietroLiuzzo** [comment]
names are stored in a list and it looks like one possible cause of many empty stored names is that the first update instruction fails to build a name, and stores an empty element which is not updated the following time a request is made 

one possible cause of the failing request for a title to store at the beginning is the presence of empty elements not taken into account by the script
```
<persName xml:lang="gez" xml:id="n1">Gabra ʾAmlāk</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1"/>
```

**Comment by thea-m** [comment]
https://betamasaheft.eu/persons/PRS13297Zamalakot/main

**Comment by PietroLiuzzo** [comment]
the issue was indeed related to the empty persName generated by the app. this line has been removed from the template. the 100+ stored person names affected have been cleared and will be refreshed once the first request for them is made. this should avoid the problem in the future.
