### ISSUE TITLE
two "MA" in the schema

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1605]
There is `<valItem ident="MA" >` for Martina and Mersha. It has been used twice in change elements, in LOC1285Agwaza clearly by Martina, in LIT3951ChronSusenyos probably by Mersha. I would suggest to change Martina's initials to MAm and update the change element. Let me know if I should do that.

**Comment by PietroLiuzzo** [comment]
yes, that is a good idea, thanks. I can update the schema.

**Comment by thea-m** [comment]
Thank you!

**Comment by thea-m** [comment]
so tired I pushed the LOC1285Agwaza  correction directly to master
