### ISSUE TITLE
adde description to search pages

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1608]
**Is your feature request related to a problem? Please describe.**
The searches are not described on each page

**Describe the solution you'd like**
Introduce in the search pages the definitions currently hidden under general Help (https://betamasaheft.eu/help.html) - i.e.
Reproduce the definitions on the specific search pages, e.g. the page https://betamasaheft.eu/xpath should have on top at least the text as present now
XPath search
All searches are XPath searches in an XML database like the one behind this website, but what you can ask in a XPath query is much more than any of the provided search interfaces can offer. So, if you know how to write your XPath, and know the source TEI (available for each file, by appending .xml to the identifier of the record) you will then be able to see your results listed.
Here you can avail yourself also of the structure of the file, the relative position of elements, and the nested elements, querying across the axes.
Examples:
person record which have at least some attribute for birth and death (can be when, notBefore, notAfter) elements and occupation type ruler'.
Manuscripts with an addition element typed Ownership Note followed by another one with type Supplication.

from https://github.com/BetaMasaheft/Documentation/issues/1597

**Comment by eu-genia** [comment]
If I may add here: besides adding the definitions, one could, on top of each type of search page, add links to other search types.

**Comment by PietroLiuzzo** [comment]
how would this be different from the links in the navigation bar? where and how would you like this additional links to be displayed?

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1641

**Comment by PietroLiuzzo** [comment]
please have a look at this short screencast displaying the functionality developed for this requirement
https://www.awesomescreenshot.com/video/5160662?key=eb98ff7b7a9a44ec2eb1f8514a923626
the search page is now one for all, with a selector option at the top. changing the value the description of the search is also updated, with a style similar to the one of the menus: on hover you get the information. Here the type of search description sticks at the top, while the information about the options is removed when mouse goes out. Features of each search which are specific appear below the main search box only when that search is selected.
let me know what you thing @eu-genia @thea-m @DenisNosnitsin1970 @abausi @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
Looks good, one needs to get accustomed and learn how it operates. :)

**Comment by PietroLiuzzo** [comment]
cool, thanks!

**Comment by DariaElagina** [comment]
Very nice, thank you, @PietroLiuzzo !

**Comment by eu-genia** [comment]
looks very promising :)

**Comment by abausi** [comment]
I also agree

Il 09.09.2021 11:54, Eugenia ha scritto:
