### ISSUE TITLE
indexing titles headings colophons etc.

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1616]
following up on #1590 and #946 I checked the index search at
https://betamasaheft.eu/titles
and see that
(1) sometimes subscription/inscription have still been used instead of subscriptio/inscriptio - I can correct that of course but this was already fixed after #1186 so I was wondering whether there are new reasons behind this
(2) I was not aware of supplicationBeginning/ supplicationEnd subtypes (used in LIT1499GadlaS), I thought the agreement was that we do not use long strings but combine a series of strings instead, in order to be able to filter better, Or am I missing something here? @thea-m @antobrita 
(3) question to @PietroLiuzzo - we once decided on this granularity with a series of strings exactly to be able to filter better. Yet in the filter I see that each combination is indexed separately (e.g. div of the subtype "explicit subscriptio" and div of the subtype "subscriptio explicit" - which is OK, the lack of standardization is our error, but neither of them reappears in the list for "subscriptio" or that for "explicit" - and IMHO they should)
![image](https://user-images.githubusercontent.com/17987728/101618605-83345780-3a12-11eb-94ae-8302ed71a9b9.png)
![image](https://user-images.githubusercontent.com/17987728/101618632-892a3880-3a12-11eb-960b-344edd2210f5.png)
(the list for subscriptio has MS records with explicit with type subscriptio, and Work records with div type subscriptio, which is nice, that both categories are combined, but only if the div has subscriptio as the only word in the string)
![image](https://user-images.githubusercontent.com/17987728/101618741-abbc5180-3a12-11eb-8bc7-d887509bf35c.png)
(same of course for title: the index for title does not include occurences for "title inscriptio" etc.)

(4) question to @PietroLiuzzo - I understand that `@explicit`  under msItem and `@div subtype="explicit"` in work records are indexed separately, but can this be somehow overcome?

**Comment by eu-genia** [comment]
sorry @PietroLiuzzo you closed this issue but removing instances of subscription was only one of the several questions I raised. are the others also solved?

**Comment by eu-genia** [comment]
(especially the indexing/filtering problem)

**Comment by PietroLiuzzo** [comment]
please see the commit above which closed the issue. Yes, they are. Not yet live, because this is part of the release. 
results are grouped by one keyword only. filtering also works for one keyword only. results are included in each of the groups.
