### ISSUE TITLE
Letters of Simeon of Beth Arsham

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1617]
These two look suspiciously similar: https://betamasaheft.eu/works/LIT2357Letter/main   and    https://betamasaheft.eu/works/LIT1775Letter/main but maybe someone with more expertise on Syriac matter could tell more? @thea-m @DenisNosnitsin1970

**Comment by eu-genia** [comment]
LIT2357Letter could be the Second Letter (concerning Najran)

**Comment by eu-genia** [comment]
no the second letter is LIT1776Letter

indeed, 2357 should be deleted, thank you

**Comment by eu-genia** [comment]
sorry, wait a bit, am trying to understand

**Comment by eu-genia** [comment]
I guess it is all correct, there are three letters
(1)	Letter on Bar Sauma and the Heresy of the Nestorians = 1775
(2)	Letter to Simeon of Gabbula (on Najran, published by Guidi) = 1776
(3)	„Second letter“ on the Martyrs of Himyar (ascribed to Simeon by Shahid) = 2357

But I will recheck

**Comment by MarcinKrawczuk** [comment]
Thank you @eu-genia , that's so helpful. I would suggest that since the letters do not exist in the Ethiopic tradition I will not elaborate greatly the work records, just provide the bibliography of editions which will clearly distinguish the versions. Does that sound good?

**Comment by thea-m** [comment]
I think that if the letters don't exist in Ethiopic, the records can be deleted. Information on their editions could eventually be provided in the records of the Ethiopic work for which they provided sources.

**Comment by eu-genia** [comment]
Yes agreed they are not part of the Ethiopic Clavis

**Comment by thea-m** [comment]
@MarcinKrawczuk have you any work open on these records which would need to be transferred or can we delete them?

**Comment by thea-m** [comment]
@MarcinKrawczuk has confirmed that they can be deleted
