### ISSUE TITLE
Help identifying work records for two works

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1621]
In the EMIP catalogues there are two short works that often appear together:

Days when the Heavens are Open to Receive Prayers, ርኅወ፡ ሰማይ፡; and Calendar of the Apostles and Evangelists.

They are short but quite frequent works. Is there a work record for these items? Any help most welcome!

Examples shown below: 

![MarwickCodex26_047](https://user-images.githubusercontent.com/39619238/102109066-92107500-3e2b-11eb-8c1a-0794d43b9f2c.JPG)
![MarwickCodex26_048](https://user-images.githubusercontent.com/39619238/102109135-a3598180-3e2b-11eb-827b-3738f2352e02.JPG)

**Comment by DenisNosnitsin1970** [comment]
Ralph, 
the list of feasts seems to be CAe 6011. It exists in widely diverging versions, but might have originally one source.  The text about open heaven I do not know.

**Comment by Ralph-Lee-UK** [comment]
Shall I create a new work record for ርኅወ፡ ሰማይ፡? In the EMIP collection there are at least 10 examples of this - EMIP 37, 67, 150, 188, 301, 1970, 2044, 3193, 3241. Sometimes added to the Psalter, often with the Prayer of Mary at Golgotha and the Mystagogia.

**Comment by DenisNosnitsin1970** [comment]
Obviously, it would be good.

**Comment by Ralph-Lee-UK** [comment]
Good, I'll do that.

**Comment by DenisNosnitsin1970** [comment]
With the open heaven, perhaps you can have a look to which extent it is a text related to magic, perhaps it is also derived from computus / calendar topic (wasn't smth like this in Enoch book?).

**Comment by Ralph-Lee-UK** [comment]
Good thought - let me have a look around. If I find anything, I'll post here again.
