### ISSUE TITLE
Identification of some malkǝʾa-hymns

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1625]
BLorient573 is a collection of 54 hymns. I have not been able to find five of them in the database. They are:

no. 5
no. 27
no. 31
no. 34
no. 35

@Ralph-Lee-UK @thea-m @DariaElagina @eu-genia 

https://archive.org/details/catalogueofethio00brituoft/page/126/mode/2up
http://www.bl.uk/manuscripts/FullDisplay.aspx?index=1&ref=Or_573

**Comment by thea-m** [comment]
@smaugustine

**Comment by thea-m** [comment]
Judging purely from the incipits given in the catalogue:
no. 5 seems to be LIT3096RepCh376 (with a typo in this record which prevented you from finding it, I'll fix it)
no. 27 seems to be LIT1864Malkea
no. 31 seems to be LIT2921RepCh202
no. 34 seems to be LIT2929RepCh210
no. 35 seems to be LIT2928RepCh209

**Comment by MarcinKrawczuk** [comment]
@thea-m Thank you, how could I have missed that?
