### ISSUE TITLE
default search

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1641]
Currently the main search box from the home page brings to facet search. This search is rich but not easiest to use or understand. I wonder if it might be easier to have the search box on the home page bring to the simple search as in the past.

Since, however, there are various ways one could get to various search pages, I suggest that, apart from the definition (taken from the help page) of each type of search on each dedicated search page, there is also a list of links to the other search types.

I.e. I am a new user, I never explored the site much, from the main search field on the homepage (which I never scrolled down) I start searching.  I am then taken to the simple search page with results. On the top of page I see:

```
Simple Search 
This is a most simple search that we can offer: it searches your text only in a few most common elements, and just as you type it.
Little options, little trouble, very synthetic results, i.e. you really need to know already what you are looking for.
Examples:
Search the word 'simple'.
Operators: ................................................................................
For more options use ->Advanced search, ->Facet search, ->XPath search, ->SPARQL Endpoint, or check the Indexes from the upper menu bar.

```
Same for other search pages.

What do you guys think @thea-m @antobrita @DenisNosnitsin1970 @DariaElagina

**Comment by PietroLiuzzo** [comment]
<img width="1287" alt="Bildschirmfoto 2021-08-16 um 14 22 29" src="https://user-images.githubusercontent.com/508012/129563206-9577c2d3-3e67-4c2c-9b83-812e49436489.png">

**Comment by PietroLiuzzo** [comment]
The commit above should close this issue. in the screenshot you can see what I have now. consider that the 52 results are only the test dataset, which is less then 5% of the total. the current indexes return 23 results from the entire dataset. I believe that the question about which search to default to from the first box on the homepage should remain open for now, since the new search, will have all the features of all others and eventually remove entirely the need to have separate searches of different kinds.

**Comment by eu-genia** [comment]
The main issue was the better visibility of all the possible search options, with explanations on each page. What is lacking I believe is the guidance to the possible operators (?)

**Comment by PietroLiuzzo** [comment]
at the moment the 'operators' are unchanged and remain available where they have always been, in the modal available clicking on the info button.

**Comment by eu-genia** [comment]
Since the users would not know where it is now, or where they have always been, they should be able to find out. Either by a written out instruction or at least by the text like "click on the info button to see how to use the operators and for more options". We wanted to make the app useable by anyone coming across, without having to study each and every button first.
(Honestly I still don't know where the information on the boolean or other operators is hidden but probably it is just me (when I click on the info button I see "Hover on words to see search options. Double-click to see morphological parsing. Click on left pointing hands and arrows to load related items and click once more to view the result in a popup." - or is there another button?)

**Comment by PietroLiuzzo** [comment]
Yes, you are right. Also, the top info button (which you clicked) is not the same as the info button on the search (which I referred to), but I think you are right and I will remove _both_, so we remove also the ambiguity. The search info is not needed in the simple search and is redundant in the new search, where there is a menu for that, as for the operator, with an explanation on mouseover. The remaining instructions will be moved to the help page only. 

https://user-images.githubusercontent.com/508012/129692125-18b973dc-0358-4932-bd65-39076cc5bae7.mov

the above screencast is work in progress but should give you an idea of how the need for those hidden informations is gone, and also show you where the operators are at the moment. On hovering you are told what you can do. no clicking, no extra lengthy text which nobody reads anyway. for those who want to read, there is the help page.

**Comment by eu-genia** [comment]
Sorry just noticed 
Little options --> Few options
