### ISSUE TITLE
Text Search Considers TEI Encoding

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1643]
At least with the faceted search, it is the case that searching for text is negatively impacted by the presence of TEI markup. For example, a search for `እንግዳ፡` (ʾǝngǝdā), the second word of the hymn LIT3096RepCh376, does not return the expected result because of the presence of XML tags:

`ኦክርስቶስ፡ እንግ<choice resp="DR"><sic>ደ</sic><corr>ዳ</corr></choice>፡ ዘኢተወከፉከ፡ ሰብአ፡ ግብጽ።`

Ideally in this case it would be possible to search both for `እንግደ፡` and `እንግዳ፡` (the original and the corrected text).

This seems like a small case, but when we consider the amount of encoded rubrication, corrections, etc. this becomes more significant.

**Comment by PietroLiuzzo** [comment]
This is a "normal" issue when working with mixed content. I will have a look if I find a work around.

**Comment by PietroLiuzzo** [comment]
it looks like there is indeed a way to define this, which I need to test however, defining multiple `<text>` indexes with `<inline>` and `<ignore>`

**Comment by PietroLiuzzo** [comment]
After a night long of testing, I have a combination of indexes which seems to work to allow this.

**Comment by PietroLiuzzo** [comment]
the new release of the application will implement on each expanded file two parallel indexes.
one ignores  corr, add, and ex,  the other  orig, sic and del. The effect is the desired one, that searching either of two variant possibilities in these alternating cases the record with this encoding will be found.
