### ISSUE TITLE
multiple idno with facs to be handled

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1649]
https://betamasaheft.eu/works/LIT2701Dawit/main  @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
this record is now visible, the issue is generated by the presence of more than one `idno[@facs]` so I am renaming it.

**Comment by PietroLiuzzo** [comment]
a module needs to be extracted to build thumbnails and links to the iiif server where this is unified instead of being replicated in several modules.
