### ISSUE TITLE
BM down?

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1652]
It seems so.

**Comment by PietroLiuzzo** [comment]
From what I can see, no. Please, could you be a bit more specific about what issue you are encountering?

**Comment by elambrinaki** [comment]
Sorry for being so unclear. Yesterday when trying to open any Beta Masaheft page (e.g. https://betamasaheft.eu/), we got a 502 error message. There were three people who (independently) reported a problem. But all is working now! Please never mind.

**Comment by PietroLiuzzo** [comment]
thanks! I would be very much intersted to know where the issue was reported by the three affected users, if you could please tell me. thanks a lot
Pietro

**Comment by elambrinaki** [comment]
Three people, two members of our team and me, had a problem with loading the site. They told me about it in Slack, I opened an issue on your Github.

**Comment by elambrinaki** [comment]
@PietroLiuzzo My bad, that was 504 error. Now I'm getting it again (e.g. https://betamasaheft.eu). Could you please advice what I do?
![504](https://user-images.githubusercontent.com/34317046/103494056-ee4f2f00-4e02-11eb-828b-1296cb554126.jpg)
