### ISSUE TITLE
Scan 28 in ESmy005

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1653]
In https://betamasaheft.eu/manuscripts/ESmy005/viewer , the image for scan 28 isn't loading. Would it please be possible to view it? Thank you!

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 this image is not in the server connected to BM, could you perhaps point me to where I can find it so I can upload it? thanks

**Comment by DenisNosnitsin1970** [comment]
Pietro, 
I have sent you the file. Did you receive it?
(there is smth with my internet connection)

**Comment by PietroLiuzzo** [comment]
got it thanks!

**Comment by elambrinaki** [comment]
@DenisNosnitsin1970 @PietroLiuzzo Thank you very much!
