### ISSUE TITLE
black pages in the viewer

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1655]
When I load a manuscript in the viewer, I cannot see the content, just black folios. For example, https://betamasaheft.eu/manuscripts/ESagm004/viewer
![Viewer_AGM-004](https://user-images.githubusercontent.com/34317046/103594870-dee5e980-4ec7-11eb-8cdc-1db37e842e31.jpg)

**Comment by PietroLiuzzo** [comment]
thanks for notification, the images are back

**Comment by elambrinaki** [comment]
Thank you!
