### ISSUE TITLE
visualisation of <gap reason="illegible"/> 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1656]
@SophiaD-M has pointed out that it would be helpful if `<gap reason="illegible"/>` in manuscript transcriptions, which is currently not visualised on the app, would be printed as [...].
(It is currently visualised as ▧ when there is `@unit`, but often this is not the case.)
.

**Comment by PietroLiuzzo** [comment]
I have added this to the XSLT. the transformation looks at `@quantity` and `@extent`, not unit. now it will default on this "[...]" when these attributes are not available.

**Comment by thea-m** [comment]
Thank you!
