### ISSUE TITLE
how to find the text displayed in the result list in the Ms.record

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1659]
I searched for the Geez-word አሩጽ and typed it into the search mask:

https://betamasaheft.eu/facet.html?query=%E1%8A%A0%E1%88%A9%E1%8C%BD

I receive two results and are interested in the second one.

![Screenshot1](https://user-images.githubusercontent.com/28757489/103906041-ae889000-50ff-11eb-9f8b-59d96ad8d685.png)

However, once I am forwarded to ms record

 https://betamasaheft.eu/manuscripts/IVEf108/main

I cannot find the text anymore that is displayed in the result list. What do I do wrong?

**Comment by thea-m** [comment]
You can find the text itself in the transcription view, https://betamasaheft.eu/manuscripts/IVEf108/text. However, I strangely do not see the crucial word አሩጽ there (maybe it is a problem with my eyes?). It is present in the XML view, https://betamasaheft.eu/manuscripts/IVEf108.xml. I usually go to the XML view if I want to find the exact location from a search result, because it usually faster than clicking on all possible titles.

**Comment by SusanneHummel** [comment]
Thank you @thea-m 
I also checked the transcription view but could not find it there ( I searched for it). 
Yes, in XML one finds it. Shouldn't the the text, however, be found on the user friendly main page? Since I am working with xml is fine for me now but it might be difficult for others.

**Comment by PietroLiuzzo** [comment]
this is nasty. some words "disappear" in the view.

**Comment by PietroLiuzzo** [comment]
the link in the results view will in future be more precise and point to the exact portion of the view, this is part of the next release already.

**Comment by PietroLiuzzo** [comment]
<img width="592" alt="Schermata 2021-01-08 alle 16 46 09" src="https://user-images.githubusercontent.com/508012/104034363-15c24500-51d1-11eb-9320-a047ac22bba1.png">

**Comment by PietroLiuzzo** [comment]
clicking the link will go to /manuscripts/IVEf108/text?hi=አሩጽ&ref=tei:div[1] and that word will be highlighted, provided it does not disappear in the process, which I am looking at now.

**Comment by PietroLiuzzo** [comment]
found it... now I need to fix it...

**Comment by PietroLiuzzo** [comment]
I found the offending '\s' ... 
https://betamasaheft.eu/manuscripts/IVEf108/text?hi=%E1%8A%A0%E1%88%A9%E1%8C%BD%E1%8D%A1
