### ISSUE TITLE
Guidelines: definition of ‘expunctuated’

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1660]
The guidelines 

https://betamasaheft.eu/Guidelines/?id=del

define the value ‘expunctuated’ as ‘marked with dots above or below the line’

I would suggest to add also: ‘marked with strokes above and below’, or ‘encircled’. Both other scribal practises occur  quite often as here in the examples (they are not really nice ones but from the Ms I am currently working on):
![MNC-007_035](https://user-images.githubusercontent.com/28757489/103909587-2e185e00-5104-11eb-8be3-1eef4c00fe46.jpg)

![MNC-007_037](https://user-images.githubusercontent.com/28757489/103909633-3cff1080-5104-11eb-9479-a7901a8cfc04.jpg)

**Comment by DenisNosnitsin1970** [comment]
I would say "lines above and below" (unless there is already a term in the small vocabulary for scribal corrections), "stroke" is a little ambiguous. Encircling is ok, but I wonder if the scribe in the second example really meant encircling.  I think he meant the same lines above and below, but "optimized" the pen movement. We there are a lot of encircled elements, but the "frame" does not touch the letters.

**Comment by SusanneHummel** [comment]
Thank you @DenisNosnitsin1970 
Yes, the examples are not perfect (though just common in the imperfection). We, however, find regularly also accurately "encircled" scribal errors in the mansucript. I just wanted to suggest to add those two phenomena. 

"Lines" instead of "strokes" are also absolute fine with me.

**Comment by PietroLiuzzo** [comment]
I think this can be close, as the line in the schema and guidelines has already been added. the PR will include this images in the Guidelines page.
