### ISSUE TITLE
Search for a full list of titles

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1661]
@PietroLiuzzo I would like to have a list of _all the titles_ of all the miracles in LIT2384Taamme. This view https://betamasaheft.eu/api/SPARQL/relations/LIT2384Taamme gives me canonical titles of the miracle stories, but many stories have the second and third titles in addition to the canonical title.
For example, LIT3614Miracle has the canonical title "Miracle of Mary: Miracle of a monk of the Monastery of St Samuel of Kalamon", and it is what I see in the relations view https://betamasaheft.eu/api/SPARQL/relations/LIT2384Taamme. However, the miracle record https://betamasaheft.eu/works/LIT3614Miracle.xml gives two other titles: "The monk of Dabra Qalǝmon who did not fast" and "The Virgin Mary and the monk of the Monastery of Qalamun (Qalmon)".
Could you please advice how I can get a full list?
Thank you!

**Comment by PietroLiuzzo** [comment]
Dear @elambrinaki 

This view provides all the titles and a lot of other information, as once requested by Prof. Belcher. 

https://betamasaheft.eu/litcomp?type=formsPart&worksid=LIT2384Taamme

this assumes you enter a Work which contains in some way some others (see selector). 

you could also obtain this with a SPARQL query directly in the endpoint.

````sparql
SELECT ?id ?title
WHERE {?work 
    saws:formsPartOf bm:LIT2384Taamme ;
    crm:P48_has_preferred_identifier ?id ;
    dc:title ?title .}
``````
you can copy paste the above here https://betamasaheft.eu/sparql

or if you want to use it in another program, the same query can be sent from the URL

https://betamasaheft.eu/api/SPARQL/json?query=SELECT%20?id%20?title%20WHERE%20{?work%20saws:formsPartOf%20bm:LIT2384Taamme%20;%20crm:P48_has_preferred_identifier%20?id%20;%20dc:title%20?title%20.} 


see https://betamasaheft.eu/apidoc.html 

Could we make of this a Question & Answer in the Discussion section?

**Comment by elambrinaki** [comment]
Dear @PietroLiuzzo , thank you very much for the SPARQL query! It gives me exactly what I need.

I think in the https://betamasaheft.eu/litcomp?type=formsPart&worksid=LIT2384Taamme view not all titles are shown. For example, LIT3883Miracle has four titles

![LIT3883Miracle (xml)](https://user-images.githubusercontent.com/34317046/104034533-fe6a6400-519e-11eb-9d77-a3695f2a5fc9.jpg)

but only one is shown in that special view

![LIT3883Miracle (TM view)](https://user-images.githubusercontent.com/34317046/104034667-307bc600-519f-11eb-872f-c90f35db734a.jpg)

**Comment by PietroLiuzzo** [comment]
This is because those titles are not entirely correctly encoded...
https://betamasaheft.eu/Guidelines/?id=work-teiHeader

**Comment by elambrinaki** [comment]
Makes sense!

**Comment by elambrinaki** [comment]
@PietroLiuzzo I posted this in the Discussion section. Please edit how you feel fit! Thank you very much for the answer.
