### ISSUE TITLE
Filter by presence of punctuation encoding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1664]
@karljonaskarlsson would be interested to filter manuscripts to find those in which a description of punctuation is encoded. This is encoded in `ab type="punctuation"` in `<layout>`. I don't think that this is possible currently.
If this is already covered by one of the numerous and lengthy search issues (https://github.com/BetaMasaheft/Documentation/issues/1612?), I apologise, I did try to skim them to identify the possible relevance.

**Comment by PietroLiuzzo** [comment]
[this is a list of all elements with ab[type=punctuation]](https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aab%5B%40type%3D%27punctuation%27%5D)

**Comment by PietroLiuzzo** [comment]
We can add also filters to the facet search. would the presence of the element suffice of should the filter indicate something particular or reflect specific features?

**Comment by thea-m** [comment]
I think the presence of the element would be enough, thank you

**Comment by karljonaskarlsson** [comment]
Thank you for the list, @PietroLiuzzo ! What I wanted to search for was early manuscripts with encoded information about punctuation. I suppose that the presence of the element would be enough, then I could filter secondarily for age. But the list is already a good starting point! Thank you!

**Comment by PietroLiuzzo** [comment]
#1211
