### ISSUE TITLE
New Work possibly for text entitled ባርኮ፡ ወውዳሴ።?

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1666]
The following text comes after an 'Image of the Trinity' starting on the left hand side line 8 of the image below. There does not appear to be a work record for this. Can anyone identify this, or should it have a work file created? Any information welcome

![EMIP02247_Weiner248_081](https://user-images.githubusercontent.com/39619238/104480113-1fc2ba00-55bc-11eb-91a3-de447362b233.jpg)

**Comment by thea-m** [comment]
I think that a work file should be created. Its beginning seems similar to BNFet107, f. 3ra, where it is apparently a part of the Səbḥata fəqur, but the text then diverges.

**Comment by DenisNosnitsin1970** [comment]
I wonder if this should be encoded as a part of the Images of the Trinity, even if with its own ID (it seems that the scribe did not have an intention to separate them very clearly, but to estimate better one would need to look at other text boundaries), and think if this text, Malke'a Sellase + bareko waweddase yedallewo la-sellase, represents a special version of the Images of the Trinity. What do you think?

**Comment by thea-m** [comment]
There seems to be a consensus to create a new ID (even if it is part of the Image of the Trinity, as this can also be attested without this hymn). @Ralph-Lee-UK , could you do it? Maybe you can then also have a look at the other text boundaries in this manuscript (which isn't online, right?) to decide Denis's proposal.

**Comment by Ralph-Lee-UK** [comment]
I will take a look at this. Images will be online before too long!

**Comment by Ralph-Lee-UK** [comment]
I will create this today. I agree that there is some significant overlap with BNFet107, f. 3ra at times, but as @thea-m noted they also diverge. I haven't found any other versions of this so far - but I'll include incipit and explicit and note its close connection with the Image of the Trinity

**Comment by Ralph-Lee-UK** [comment]
See https://github.com/BetaMasaheft/Works/pull/461
