### ISSUE TITLE
Identification of Work in EMIP 2264 መጽሐፈ፡ ቀኖና፡ ዘሠርዕዎ፡ መምሕራነ፡ ቤተ፡ ክርስቲያን፡

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1671]
(Apologies for all the requests - we are starting work on a new set of manuscripts at CUA!!)

The work starting at the bottom of the right hand column is described as መጽሐፈ፡ ቀኖና፡ ዘሠርዕዎ፡ መምሕራነ፡ ቤተ፡ ክርስቲያን፡ - which does not appear to me to correspond to any existing work files. Any suggestions welcome! 

The work in the images below 
![EMIP02264_Weiner265_087](https://user-images.githubusercontent.com/39619238/104574581-18e48780-564e-11eb-8813-ba67546359a3.jpg)
![EMIP02264_Weiner265_088](https://user-images.githubusercontent.com/39619238/104574608-23068600-564e-11eb-9383-abf4d8fbf701.jpg)
![EMIP02264_Weiner265_089](https://user-images.githubusercontent.com/39619238/104574634-2c8fee00-564e-11eb-852a-f02776b93313.jpg)

**Comment by DenisNosnitsin1970** [comment]
Dear Ralph, to understand better what is this text, I would have a deeper insight inot other texts. 
Can I get this manuscript?

**Comment by DenisNosnitsin1970** [comment]
OK, I see that probably the same text is in EMML no. 5/ms. IES 377 (a manuscript from Gunda Gunde), ff. 139-145

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 . The full set of images for this text are here

![EMIP02264_Weiner265_087](https://user-images.githubusercontent.com/39619238/104749511-ce950080-574a-11eb-8e6e-5256b0f85e88.jpg)
![EMIP02264_Weiner265_088](https://user-images.githubusercontent.com/39619238/104749517-d18ff100-574a-11eb-8642-894c73bad230.jpg)
![EMIP02264_Weiner265_089](https://user-images.githubusercontent.com/39619238/104749529-d5237800-574a-11eb-9541-ff9747d4ed2f.jpg)
![EMIP02264_Weiner265_090](https://user-images.githubusercontent.com/39619238/104749553-da80c280-574a-11eb-9b6f-3ba89ca08163.jpg)
![EMIP02264_Weiner265_091](https://user-images.githubusercontent.com/39619238/104749563-dd7bb300-574a-11eb-83e1-4cfad96975b9.jpg)
![EMIP02264_Weiner265_092](https://user-images.githubusercontent.com/39619238/104749569-e076a380-574a-11eb-8be4-a3fcdc0e3751.jpg)
![EMIP02264_Weiner265_093](https://user-images.githubusercontent.com/39619238/104749579-e2d8fd80-574a-11eb-910c-b9de858cfad5.jpg)
![EMIP02264_Weiner265_094](https://user-images.githubusercontent.com/39619238/104749436-ba510380-574a-11eb-8170-0c694ad79de5.jpg)
![EMIP02264_Weiner265_095](https://user-images.githubusercontent.com/39619238/104749491-c89f1f80-574a-11eb-8fbe-2d65da35cff1.jpg)

**Comment by DenisNosnitsin1970** [comment]
Thank you, Ralph; sorry, I have just found out that EMML 5 is online in HMML reading room, you can check up the texts. Probably it is the same.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 I will check this - again I don't think that we have a work file for this in BM do we?

**Comment by DenisNosnitsin1970** [comment]
Very unlikely. Please note that sometimes a work record may be already there, but the work is encoded in such a way that it is very difficult to retrieve it (without any text quote, in many cases following a very economic catalogue description, or described in a very special way). I see that EMML no. 5 is in BM, as EMML5, so you can include it into "relations" of the first text (as the record for EMML5 seems to be a stub).

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 - EMML 5 is not identical, but I believe it is the same basic work. I think that it may be LIT3177Canon "Canon of the Doctors of the Church on those who abjure" this is found in BLadd11293 with the incipit እምቀኖና፡ ዘአንበሩ፡ መምህራነ፡ ቤተ፡ ክርስቲያን፡ በእንተ፡ ዘክህደ፡ ሃይማኖቶ፡ - I will edit that work record to include these two attestations, and perhaps spruce up the description a bit!

**Comment by Ralph-Lee-UK** [comment]
this work is https://betamasaheft.eu/works/LIT3177Canon/main and is attested also in BLadd11293 I will edit the work file to include the witnesses and also a Ge'ez and alternative English title

**Comment by DenisNosnitsin1970** [comment]
Great!
