### ISSUE TITLE
Some texts from Gadla samāʿtāt (again)

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1673]
[So,](url
[BNF d'Abb 179 opis.pdf](https://github.com/BetaMasaheft/Documentation/files/5815992/BNF.d.Abb.179.opis.pdf)
)   [BnF Abb. 179](https://archivesetmanuscrits.bnf.fr/ark:/12148/cc109133j) is a Gadla samāʿtāt. I am not able to find in he database the following gadlāt (I use the numbers from CCR's catalogue and a name of the saint for identification):

2  ፒፋሞን
3 አካውሕ
4 ኦርኒ
6 አቡቂር
11 ቴዎጢቃኖስ
16 ዮሐንስ ወልደ ጸራቢ
20 ዮሐንስ ዘስንሁት
22 አብርሃም ፀራቢ
23 አበስኪሮን
29 ቴዎድር
30 ማሪና
32 አበከረዙን
35 መክብhዩ
36 ሐሩስጥፋሩስ
37 ባሲሊቆስ
38 ክርስጢና
39 እንጣዎስ
40 እንድርያኖስ ወእንጦልያ

Unless there are objections, I may start creating work records, I've already created some person records for the above.
@DenisNosnitsin1970 @thea-m @DariaElagina @antobrita

**Comment by thea-m** [comment]
Yes, I also could not find IDs for these, please go ahead!
I only found this for ʾAbakarazun: LIT1405GadlaA, but you will know if this is the same or not.
Thank you!

**Comment by eu-genia** [comment]
6 = LIT1010Abuqer
32 = LIT1405GadlaA as Dorothea rightly said
I shall be working on the stubs for GS texts from AB's file, but I have not come too far yet :)

**Comment by MarcinKrawczuk** [comment]
6 - thanks, I missed it!
32 - LIT1405GadlaA is a Stephanite monk, so he can't be in the GS I guess...

**Comment by eu-genia** [comment]
Marcin is currently creating the records I believe, the issue will be closed when done

**Comment by MarcinKrawczuk** [comment]
This is correct, I am creating the work records. I am about halfway through.
