### ISSUE TITLE
Coding a witness not in the BM database

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1674]
I am creating a new work file, which has three known witnesses. Two of them are in the BM database. The third witness is  not in the database, but is at https://eap.bl.uk/archive-file/EAP286-1-1-133 

How would I code this as a witness in the work file?

**Comment by eu-genia** [comment]
you could create a stub for the MS record (we did that in several cases already, eg when I needed witnesses for Senodos I created DabraBizanSenodos1 etc.); maybe also with a `<facsimile>` element with the external link

**Comment by PietroLiuzzo** [comment]
The guidelines have a paragraph on this https://betamasaheft.eu/Guidelines/?id=work-teiHeader

> Each <witness>↗ will have to take a @corresp pointing to the manuscript @xml:id. If the manuscript is in already described in Beta maṣāḥǝft, that is enough. If the manuscript is described in an external catalogue, then use <@type='external'>↗ in <listBibl[type='mss']>↗ in the manuscript entity.

Which can certainly be made a bit better, it is not that clear and potentially confusing.

You can do as @eu-genia  suggested or simply as indicated in the GL:

`<witness corresp="https://eap.bl.uk/archive-file/EAP286-1-1-133" type="external">`

a further example is here https://betamasaheft.eu/works/LIT2170Peripl.xml

**Comment by Ralph-Lee-UK** [comment]
I think, following other discussions when the work file was created, that I have used the term 'witness' incorrectly, and that the sort of connection I seek to make is in the @listRelation section.  Following your advice, would the following code in that location be correct?

<relation name="lawd:hasAttestation" active="LIT6347SalamWatchful" passive="https://eap.bl.uk/archive-file/EAP286-1-1-133" type="external"/>

**Comment by PietroLiuzzo** [comment]
for relation you do not need `@type`. you can instead explain in a sentence or two what you intend into a `<desc>` inside the relation element

**Comment by eu-genia** [comment]
The guidelines say
`We use <witness>↗ for those manuscripts which are used for the edition we are going to provide in the <div type='edition'>↗. `
If there is no edition, and simply manuscripts with the work should be referred to, I believed the stub was the only option, the use of `witness ` has been discussed.

**Comment by PietroLiuzzo** [comment]
@eu-genia sorry, I am not able to follow your proposition. what do you mean with "has been discussed"?
@Ralph-Lee-UK now I am not anymore sure what you need to do. 

If you simply want to say that there is a witness of the text in the named manuscript the quickest way to go is the `witness[@type='external']` 
with a bit more effort you can make a stub and link in there to EAP. if you list this text as a content in the ms, you do not need to make any linkage from the Work record. if you still want to say that this is one of the witnesses, you can do so as above pointing to the newly created stub. These are two distinct statement, the witness one has a reference, theoretical at least, to a foreseeable or present edition, the second is simply a statement of presence in a manuscript of an identified text and belongs with the cataloguing. 
you can still use relation as discussed above to make several of these statements or more/less precise ones or entirely different ones. the meaning of each relation `@name` is given here in the GL https://betamasaheft.eu/Guidelines/?id=relation, but I am not sure if eventually your requirement falls into this category.
If this is helping you, I can use this and provide examples accordingly in the GL.

**Comment by eu-genia** [comment]
I mean that as far as I am aware, our guidelines say that we use the `witness `element for manuscripts used in an edition, we do not use it to create a repertory of mss with the work if there is no edition provided.  In order to have a list of manuscripts of a work, we need stubs with an msItem.
https://github.com/BetaMasaheft/Documentation/issues/714

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo and @thea-m I think we're getting there, and this is helping me understand some important nuances. 

I am keen to get this right, and very happy for you to tell me to do things differently! 

I'll wind back a little to help you understand what I need! 

Following a discussion on GitHub it was agreed that the 'Greeting to the Congregation of Watchful Angels' should have a work record created as it is a text that has a circulation of its own, although it is also a part of another longer work. I created the record LIT6347SalamWatchful, and in creating this wanted to establish in that record both its relationship to the longer work, and to note in the record the manuscripts in which this text had been identified. I raised this particular issue because one of the manuscripts that has this text is in the EAP collection at the British Library. 

For this purpose I have included the following  lines of code (this version is not yet merged, as I am trying to get this correct before pushing the edits). 

<listRelation>
                    <relation name="saws:formsPartOf" active="LIT6347SalamWatchful" passive="LIT1325egziab"/>
                    <relation name="lawd:hasAttestation" active="LIT6347SalamWatchful" passive="EMIP00203"/>
                    <relation name="lawd:hasAttestation" active="LIT6347SalamWatchful" passive="EMIP02247"/>
                    <relation name="lawd:hasAttestation" active="LIT6347SalamWatchful" passive="https://eap.bl.uk/archive-file/EAP286-1-1-133"/>
      </listRelation>

So 
1) the first 'relation' is to establish that this text is also part of the larger work  LIT1325egziab
2) The second two are aimed at showing that the text is found in the two EMIP mss listed
3) The third is the one that I raised the issue over, which is the attestation in the EAP collection. 

The confusion arises at least partly because of my imprecise use of terms! You pointed to #714 which helps clarify this very well. From reading this, I think that the attestations in the EMIP collection (item 2 above) are no longer needed, because they are themselves coded with the reference to this work, so they should probably be deleted? 

The attestation in the EAP collection does make sense, perhaps, because that one would not come up but based on the example LIT2170Peripl this might need to be coded in a different way?

**Comment by PietroLiuzzo** [comment]
Dear @Ralph-Lee-UK I think I would do as you say as well, so remove the EMIP relations of point 2 and encode the EAP one as in the example provided from LIT2170. I will then use this as an example in the GL, thanks!

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo I am getting on with this, and am glad that I keep good notes to prepare these things! EAP ms is actually for a Greeting to Lalibela that I have been discussing at the same time! I will make a pull request with this record corrected, and then we can make sure that the other work has the correct code in it for this!

**Comment by PietroLiuzzo** [comment]
@Ralph-Lee-UK please have a look at the updated GL (linked above) and let me know please if that is better now and this issue can be closed. Thanks a lot!

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo sorry for the delay. The Lalibela hymn to which this reference belongs was some time in having the pull request approved, but that is now done. I have added the line of code for this attestation to it now. I have another pull request in works waiting to be approved, and as soon as that is done I will submit this one, and mark you to approve it. The new GL look very clear.
