### ISSUE TITLE
Amharic commentary on Psalter

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1675]
It looks like we need one more ID for a Psalter with Amharic commentary. I came accross it in Abbadie 41, a similar commentary is found in RQG-015
![grafik](https://user-images.githubusercontent.com/18533839/105706374-bde64680-5f11-11eb-87c9-9b611ef82d21.png)
and UNESCO Dabra Sehay 014. ID LIT5986CommPsalter was used in MS BL Orient 535, I cannot confirm that this is the same as in mss mentioned above.

**Comment by DenisNosnitsin1970** [comment]
:(

**Comment by DenisNosnitsin1970** [comment]
Yes, at the first glance Or 535 and Abbadie 41 have the same text. Ok, I will deal with this.

**Comment by DenisNosnitsin1970** [comment]
It is quite interesting, somewhat contrary to what is usually said about the relation of text and commentary in Ethiopia.

**Comment by DenisNosnitsin1970** [comment]
I have slightly modified my view. 1) Orient 535 stands together with RQG-015, both have text + commentary as secondary text (but it may well be the main hand in Orient 535). 2) Abbadie 41 contains principally the same text, but it has Psalter + commentaries copied as continuous text without any difference. I think the Psalter as in Abbadie 41 should receive a new ID. 
LIT5986CommPsalter is already used now for Orient 535 but it probably needs an internal structure: commentary for Psalms (LIT5985CommPsalms is already there, yet not used?), commentary for Songs of Prophets,  commentary for Song of Songs as subparts (?) ( a similar division for the text in Abbadie 41, but here text+commentary). It seems that the Amharic commentary as in Orient 535 and RQG-015 was not bound to any specific version of the Psalter, but could be copied separately as an independent work/paratext. Onthe whole, this commentary is less of andemta nature, it is quite close to a translation; it seems to be completely different from andemta published by Stoffregen-Pedersen,  "Traditional Ethiopian Exegesisi of the Book of Psalms" (but I could check only a small portion from the edition).

**Comment by thea-m** [comment]
That sounds reasonable to me. The existing ID LIT5985CommPsalms had been created at the request of @Ralph-Lee-UK together with many other commentary IDs, it's quite possible it hasn't been used yet.
@DenisNosnitsin1970 , will you create the new ID and carry out the elaboration of the substructure?

**Comment by DenisNosnitsin1970** [comment]
Yes, I will.

**Comment by Ralph-Lee-UK** [comment]
This is all fascinating! Recall that we created the LIT5985CommPsalms work file as a compromise because this broad category of work needs further work to understand the different sets of texts in Amharic and their relation to earlier Gǝʿǝz commentary. What you show above is very interesting, as you have said somewhat different from the Andemta material, in the way it is laid out. I believe that some work has been started on how marginal notes on some OT books relates to the Andemta, although not yet published. Might I suggest that the new ID at least makes a connection with LIT5985CommPsalms as the purpose of this was to mean that a researcher looking at this could find all the relevant material?

**Comment by DenisNosnitsin1970** [comment]
I noticed that when I first saw ms RQG-015. OK, I see now why LIT5985 was created, to bundle all Psalms with commentaries, right? I saw that it has relations to no items and used it for Psalms + commentary as in Orient 535, but I can reverse. By chance, do you have Pedersens book on exegesis? If you do, can you share it? In google online versions, an important passage in it is not accessible.

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970  I do have the book - can you tell me which part you need, and I can scan those pages.

**Comment by DenisNosnitsin1970** [comment]
I need the list of manuscripts that starts on p. 48 and ends on p. 53 or 54. Thanks!

**Comment by Ralph-Lee-UK** [comment]
@DenisNosnitsin1970 here it is - let me know if you need any more

[Pedersen - 29 Jan 2021 - 8-47 am.pdf](https://github.com/BetaMasaheft/Documentation/files/5892719/Pedersen.-.29.Jan.2021.-.8-47.am.pdf)
