### ISSUE TITLE
Marking @locus on Concertina Fold Mss

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1678]
I have a few mss that are described in the EMIP catalogues as 'concertina fold' - see images below (this is not a particularly fine example, but is the one I had to hand). Is there any wisdom on how to mark locations in these mss - should I just use line numbers? 

![EMIP02269_Weiner270_004](https://user-images.githubusercontent.com/39619238/106254105-40238300-6210-11eb-96ff-f3b8948b08b6.jpg)

![EMIP02269_Weiner270_003](https://user-images.githubusercontent.com/39619238/106254094-3bf76580-6210-11eb-8507-b75f0b88201b.jpg)

![EMIP02269_Weiner270_002](https://user-images.githubusercontent.com/39619238/106254086-37cb4800-6210-11eb-9f15-ccf9d6693d72.jpg)

![EMIP02269_Weiner270_001](https://user-images.githubusercontent.com/39619238/106254064-33069400-6210-11eb-92fd-05492462263b.jpg)

![EMIP02269_Weiner270_005](https://user-images.githubusercontent.com/39619238/106254012-26823b80-6210-11eb-8638-fbfec3e4e4a0.jpg)
![EMIP02269_Weiner270_006](https://user-images.githubusercontent.com/39619238/106254039-2d10b300-6210-11eb-8c93-cfc68dd048b2.jpg)

**Comment by PietroLiuzzo** [comment]
https://betamasaheft.eu/Guidelines/?id=referencing-the-manuscript This should help, in principle yes, the line numbers are what you need and any sort of structure you are giving to the description.

**Comment by Ralph-Lee-UK** [comment]
Many thanks!
