### ISSUE TITLE
Possible መልክአ፡ ፬እንስሳ፡ Duplicates

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1680]
Chaîne 216 has three witnesses: BL Or. 582, BL Or. 574, and BnF éth. (Mondon-Vidailhet) 197. While none of these, quite unfortunately, have been photographed (at least to my knowledge), the same መልክእ፡ is found in EMML 1959. The latter manuscript shows that this is not a different መልክእ፡ than Chaîne 153 but rather the same one with a stanza added to the beginning, thereby changing the incipit and causing it to appear as a different text in catalogues.

Furthermore, it is entirely an invention of Chaîne that the text is in honour of "the Cherubim", it is clearly dedicated to the Four Living Creatures (and intended for use on their feast day) and is titled in manuscripts as መልክአ፡ ፬እንስሳ፡.

Would anyone be opposed to merging these and adjusting the title? @thea-m? @DenisNosnitsin1970?

A preemptive postscript: I have identified two additional መልክአ፡ ፬እንስሳ፡ unknown to Chaîne, one in a single መልክአ፡ ጉባኤ፡ manuscript and the other in two recent manuscripts of ድርሳነ፡ ፬እንስሳ፡, but both present markedly different texts ("ሰላም፡ ለዝክረ፡ ስምክሙ፡ ግሩም፡ ለጸውዖ።" and "በስመ፡ ሥሉስ፡ ቅዱስ፡ አጋዕዝተ፡ ጥንት፡ ወፍጻሜ።") and don't affect the record(s) at hand.

**Comment by smaugustine** [comment]
I should also add that Chaîne no. 186 is already a duplicate of Chaîne no. 153.

**Comment by thea-m** [comment]
Thank you! I have no objections. Would you like to edit all concerned files, or should I do it?

**Comment by smaugustine** [comment]
Yes, it's not a problem. I'm also looking at a few other problematic titles, like "Image of the elders of the Book of Revelation" > "Image of the Heavenly Priests" (i.e. መልክአ፡ ካህናተ፡ ሰማይ፡), which I'll add in as well.

**Comment by DenisNosnitsin1970** [comment]
ok, fine.

**Comment by thea-m** [comment]
Thank you!
