### ISSUE TITLE
stubs for Tana

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1682]
Stubs to be created for manuscripts here https://rep.adw-goe.de/handle/11858/00-001S-0000-002D-B59F-6

**Comment by PietroLiuzzo** [comment]
@eu-genia @DariaElagina please could you help me parse these PDFs in terms of the requirements of the issue discussed in the meeting two weeks ago? at the link provided I can download three books. Am I right to think that the one concerned here are only those of Teil 3? Thanks!

**Comment by eu-genia** [comment]
there are 6 volumes available here https://rep.adw-goe.de/handle/11858/00-001S-0000-002D-B59F-6/browse?rpp=20&sort_by=7&type=dateissued&order=DESC, and ideally and eventually all could be on BM (there are already some overlappings, eg Hamburg, but there are also a couple of Tanasee manually created)

yet in order to host the images of Steve we need Teil 1 https://rep.adw-goe.de/handle/11858/00-001S-0000-002D-B675-9 and Teil 2 https://rep.adw-goe.de/handle/11858/00-001S-0000-002D-B676-7 (Tanasee collection by Hammerschmidt)

**Comment by PietroLiuzzo** [comment]
I see, thanks! There is unfortunately little I can do with these PDFs with no structure as far as I can see. they are searcheable, but that is about it. any ideas? Otherwise I would actually suggest that stubs with ID and repository only are created as normal OR I can create them from a tabular format with the following fields, so that the XML stubs are anchored to the publications.

- RepoID 
- MSdesiredID 
- bibliographyBMpointer
- bibliographyCitedRange 
- title (main content) 

These are a of course bare minimum, if the table has e.g. form, material, dimensions, all these I can pass from the table to a group of TEI files with a transformation. If someone can fill a table...

**Comment by PietroLiuzzo** [comment]
table can of course include all 6 volumes, as we are at it...

**Comment by PietroLiuzzo** [comment]
if records exist a column with the existing ID could be given, so that instead of creating a new record I can update with the information in the table the existing record

**Comment by DariaElagina** [comment]
Sorry, I have never done it before, but I can feel in the tables (I guess manually). However, I think for the stubs we could keep just an ID, identifier, alternative identifier and a repository.

**Comment by DariaElagina** [comment]
An this could be feeled in really quickly

**Comment by PietroLiuzzo** [comment]
Thanks! let's do that, than. any type of spreadsheet you like is fine. please, NOT a table in word!
Only ids can be populated automatically even in excel, but I think since we are doing this, we should rather add at least the title and bibliography pointers as listed above, so that when the images are available we have something to make sure we are linking the correct set.

**Comment by eu-genia** [comment]
I agree I already started here was just about to share the link
https://docs.google.com/spreadsheets/d/1GHgMfgTLTVNwEJ7-DogUNgBTD5IntzMGaVT_6SU8rEY/edit?usp=sharing
It could be helpful - I am sure Pietro can do it faster - if the ID column is autofilled with Tanasee1 to Tanasee111 and the IDNO1 column with Ṭānāsee 1 to Ṭānāsee 111

**Comment by PietroLiuzzo** [comment]
Thanks @eu-genia ! it can go even faster if both of you fill in from different volums :)
mmm... pulling down a selection of cells with numeric values does not do the trick in Google?

**Comment by eu-genia** [comment]
additionally Tanasee1 to Tanasee58  should get IDNO2 Kǝbrān 1 to Kǝbrān 58, respectively

**Comment by eu-genia** [comment]
I cannot managed with mixed alphanumeric fields, only with numeric ones... or I have to split the cells and then remerge...

**Comment by PietroLiuzzo** [comment]
done

**Comment by DariaElagina** [comment]
ok, do we want to split the volumes, or should I just take the whole task over :)

**Comment by DariaElagina** [comment]
?

**Comment by eu-genia** [comment]
i think there is only work to do if we want to fill at least the main content part, otherwise all can be done more or less automatically... if you feel like filling the content you can start from 1

**Comment by PietroLiuzzo** [comment]
please volume pointer, main content and citedRange are important minimal disambiguators.

**Comment by DariaElagina** [comment]
ok, I will feel in the main content, cited range and volume

**Comment by PietroLiuzzo** [comment]
each volume will have a zotero target, it only needs that in the bibliographyBMpointer column, not an additional column. thanks!

**Comment by DariaElagina** [comment]
ok, thank you!

**Comment by eu-genia** [comment]
@PietroLiuzzo I once (2017) created INS0358TanaDM for Dabra Maryam but cannot see it in the app. I guess some merge got lost... can it be retrieved or should I recreate it?

**Comment by PietroLiuzzo** [comment]
I cannot see in the commit history. perhaps yes, it is simpler and faster compared to digging the history back from 2017 to just make a fresh one

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Institutions/pull/22 for missing institutions, I think I populated all I could "automatically"

**Comment by PietroLiuzzo** [comment]
thanks! I marked red a part of the column with bibliographic record which strikes me as potentially incorrect

**Comment by eu-genia** [comment]
corrected

**Comment by PietroLiuzzo** [comment]
I cannot see 31 here https://betamasaheft.eu/manuscripts/INS0357Kebran/list 
Tanasee31 is listed under the INS0021IHA (!) repository should that just be considered just a mistake and updated to INS0357Kebran ?

**Comment by eu-genia** [comment]
yes thank you an error in the file

**Comment by PietroLiuzzo** [comment]
I have hand fixed two of the three which were already there, the other was fine. I have made now a branch for the others, where I pushed the files for those marked in green in the table. as soon as the others are ready I will make further commits and then a PR with all.

**Comment by PietroLiuzzo** [comment]
I have added page numbers from VOHD 3 and few titles while testing searches in the new app.

**Comment by DariaElagina** [comment]
the table is done

**Comment by DariaElagina** [comment]
three volumes

**Comment by PietroLiuzzo** [comment]
The [PR](https://github.com/BetaMasaheft/Manuscripts/pull/989) contains all the stubs created from the table. I am closing the issue here.

**Comment by eu-genia** [comment]
On credits to images:
Pietro wrote: "The manuscript was microfilmed by Ernst Hammerschmidt. 
                    The images of the microfilm of the manuscript have been curated and 
                    made available to the project by 
                    Steve Delamarter for the Ethiopic Manuscript Imaging Project (EMIP)."

We might want to be more precise to specify dates and persons.  If we go by free text then something like
"The manuscript was originally microfilmed in situ in 1968 by the team of Ernst Hammerschmidt (photographer: Helmut Stein, researcher: Jürgen Jacobi). In 2020 the microfilm copies stored at the Institute of Ethiopian Studies were digitized by the team of the Ethiopic Manuscript Imaging Project (EMIP) and shared by Steve Delamarter"

If we need to be even more precise we could use the surrogates element as suggested here
https://github.com/BetaMasaheft/Documentation/issues/1349

```
<surrogates>
 <bibl>
  <title type="gmd">microfilm</title>
  <idno>*****.</idno>
  <date when="1968">1968</date>
 </bibl>
 </surrogates>
<surrogates>
 <bibl>
  <title type="gmd">digital image from microfilm</title>
  <idno>*****.</idno>
  <date when="2021">2021</date>
 </bibl>
 </surrogates>
```

@thea-m @DenisNosnitsin1970 @DariaElagina

**Comment by PietroLiuzzo** [comment]
I have changed the phrasing, thanks! I do not think we still have that much of a critical mass of information about this to start using `<surrogates>`. with this paragraph we are saying all there is to say.
