### ISSUE TITLE
various error messages after trying to create new person records 

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#1683]
I am trying  to create new records for persons since the early afternoon. The first three records were successfully created without any problems, using firefox.

But after that, I receive always an varying error message, three copied below. As recommanded, I switched the broswer (Chrome) but it did not help. 

Shall I keep on trying or wait?

firefox:

```
<exception>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>
exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 570, column 19]
</message>
</exception>
```
```
<exception>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>
exerr:ERROR Permission to modify permissions is denied for user 'Susanne' on '/db/apps/BetMasData/persons/new/PRS13344TasfāBǝyy.xml': exerr:ERROR Resource or collection '/db/apps/BetMasData/persons/new/PRS13344TasfāBǝyy.xml' does not exist. [at line 572, column 26]
</message>
</exception>
```

Chrome
```
<exception>
<path>/db/apps/BetMas/edit/save-new-entity.xql</path>
<message>exerr:ERROR Permission to modify permissions is denied for user 'Susanne' on '/db/apps/BetMasData/persons/new/PRS13345TasfāBǝyy.xml': exerr:ERROR Resource or collection '/db/apps/BetMasData/persons/new/PRS13345TasfāBǝyy.xml' does not exist. [at line 572, column 26]</message>
</exception>
```

**Comment by PietroLiuzzo** [comment]
please, note that the use of special characters in file names and ids is not allowed.  PRS13345TasfāBǝyy is not correct, use PRS13345TasfaBeyy for example.

**Comment by PietroLiuzzo** [comment]
see first line of https://betamasaheft.eu/Guidelines/?id=entities-id-structure

**Comment by SusanneHummel** [comment]
I always forget that! I know that ruke of course!
Sorry to have disturbed you for nothing!! 

Now it works perfectly.

**Comment by PietroLiuzzo** [comment]
no worries! it should definitely fail more gently than simply throwing an error...
