### ISSUE TITLE
Vat. Aeth. 66: correction in the list of guarantors and identification of the guarantors

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#1686]
Following a suggestion by Samantha Kelly, the additional note 18, on f. 67ra, has some mistakes, due to the wrong interpretation of the text, the introduction (here corrected) and translation of which (here provided) should be as follows (the linguistic reasons for this I cannot explain here):

"Note concerning a loan of eleven golden coins and one ቢሰጥ፡ (carpet?), which will be returned by 41 pilgrims. The following persons are indicated as guarantors: the priest Yāʿqob, spiritual son of Ewosṭātewos; Bakimos, spiritual son of Takla Hāymānot; and Bǝrnābas, spiritual son of Sāmuʾel.

Translation:
In the presence of the pilgrims, Abba Yaʿqob the priest (is) the guarantor from the house of our father Eyosṭātewos, Bakimos (is) the guarantor from the house of our father Takla Haymānot, Bǝrnābas (is) the guarantor from the house of our father Samuʾel (sic), that we give (or: will give) back to the church, all of us 41 (or 44) pilgrims, the property of the church that we took (or: have taken).

Consequently, the associaton of Yāʿqob, Bakimos, and Bǝrnābas should be checked or updated.

**Comment by DenisNosnitsin1970** [comment]
I can take care of this.

**Comment by abausi** [comment]
I repeat, with a statement to make it more clear: the guarantors, in the explanatory note, are attributed to wrong houses: Abba Yaʿqob the priest (is) from the house of Eyosṭātewos; Bakimos (is) from the house of Takla Haymānot; Bǝrnābas (is) the from the house of our father Samuʾel (sic). This can have important consequences for the attribution of IDs as well.

**Comment by abausi** [comment]
Corrected by Denis
