### ISSUE TITLE
Two salām-hymns on John the Baptist

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1687]
[BLorient657](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_657_fs001r) contains two hymns for John the Baptist.

No. 1 f. 2r incipit: ሰላም፡ እብል፡ አጻብአ፡ አእጋር፡ ፪፡ ወለአጽፋሪሆን፡ አሥር፡ በኍልቈ፡ ቃላት፡

No. 2 f. 220v-221r incipit: ሰላም፡ ለዝክረ፡ ዘበመጽሐፈ፡ ሕግ፡ ተሐተመ፡ ወለሰዕርትከ፡ ሜላት፡ ዘእምፈትለ፡ ሥጋ፡ ተአንመ፡

I do not find neither in the database nor in Chaine's Repertoire. I may create the record if you think it's worth it.
@DariaElagina @thea-m @eu-genia

**Comment by smaugustine** [comment]
The latter one is a መልክእ፡ for King Yoḥannǝs I, Chaîne 151 (misattributed to John the Evangelist).

**Comment by MarcinKrawczuk** [comment]
Great, less work for me! Thank you very much @smaugustine.

**Comment by thea-m** [comment]
Thank you, I'll update the record in question with this information and will correct the text there.
