### ISSUE TITLE
QM001 apparently present twice

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1688]
https://betamasaheft.eu/manuscripts/QM001/main

gets the error 

> Something has gone wrong and there are more than one item with id QM001.
> 
> /db/apps/BetMasData/manuscripts/new/QM001.xml
> /db/apps/BetMasData/manuscripts/QaranyoMadhaneAlam/QM001.xml

As far as I see, the manuscript is now only present in the folder QaranyoMadhaneAlam and not in the "new" folder, but it's quite possible that there was some confusion involved in its creation process or that correct procedures were not followed well by me.

**Comment by PietroLiuzzo** [comment]
Thanks! doublets removed

**Comment by thea-m** [comment]
Thank you!
