### ISSUE TITLE
Treatise on Religious Controversies by Two Monks of Dabra Bizan

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1689]
In EMIP 2259, 20th century, we have found this work (images below) mainly in Amharic on the mysteries: baptism, the eucharist, priesthood, repentance etc. The two monks who have compiled this are አባ፡ ገብረ፡ እግዚአብሔር፡ and አባ፡ ወልደ፡ አብርሃም፡ I have included here only the first few leaves, but the work extends from 33r-80v. I have not seen this in any other mss. Do you think it warrants a new work file?

![EMIP02259_Weiner260_037](https://user-images.githubusercontent.com/39619238/106756177-e7485600-6626-11eb-8aea-dc1afd91e59c.jpg)
![EMIP02259_Weiner260_038](https://user-images.githubusercontent.com/39619238/106756193-eca5a080-6626-11eb-8875-b289550b3935.jpg)
![EMIP02259_Weiner260_039](https://user-images.githubusercontent.com/39619238/106756198-ef07fa80-6626-11eb-8d85-70491481a498.jpg)
![EMIP02259_Weiner260_040](https://user-images.githubusercontent.com/39619238/106756205-f0392780-6626-11eb-862f-65faca9834a8.jpg)
![EMIP02259_Weiner260_041](https://user-images.githubusercontent.com/39619238/106756209-f202eb00-6626-11eb-99cf-f0c37d08416b.jpg)
![EMIP02259_Weiner260_042](https://user-images.githubusercontent.com/39619238/106756216-f4654500-6626-11eb-9a6e-5bb5879c1d9d.jpg)

**Comment by DenisNosnitsin1970** [comment]
Yes, it seems to deserve an ID.
