### ISSUE TITLE
Translator's adition

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1690]
How can we encode an addition to a translation that 
is not in the original text? For instance, while translating from Ethiopic into English, 
“is” (copula) is sometimes needed that is missing in the original, 
that it makes the translation smooth and better understandable.
Elsewhere such additions are marked simply with brackets. 
(The issue was inspired by ms VATet66, addition 18).
A search through the guidelines brought 
me to https://epidoc.stoa.org/gl/latest/supp-translation.html and <supplied reason="subaudible">, 
is it the right device?

**Comment by PietroLiuzzo** [comment]
I personally do not think that this count as additions in many cases, but they can be tagged with `<supplied>`, if they need to be tagged. https://betamasaheft.eu/Guidelines/?id=supplied the values here are inherited from the EpiDoc Guidelines in any case. I would use `subaudible` or plainly `omitted`.
