### ISSUE TITLE
link to xpath search example

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1691]
The link to a search example from the Help page (Searches) 
https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3Aadditions%2F%2Ft%3Aitem%5Bt%3Adesc%5B%40type%3D%27OwnershipNote%27%5D%5D%5Bfollowing-sibling%3A%3At%3Aitem%5Bt%3Adesc%5B%40type%3D%27Supplication%27%5D%5D%5D
does not work (?)
(I know the whole Search presentation is probably being reworked, but just in case...)

**Comment by PietroLiuzzo** [comment]
yes, this will be updated.

**Comment by eu-genia** [comment]
Examples added to newSearch.html

**Comment by thea-m** [comment]
Thank you!
