### ISSUE TITLE
transkription of Miracles of Mary mauscripts for PEMM

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1693]
@PietroLiuzzo  and @Giuliacas are fixing the segmentation of the following manuscripts for PEMM project as requested by @elambrinaki before running transkription, export in TEI and push to BM.

- [x] ESfbm001 loaded
- [x] ESdd010 done exported 
- [x] ESmhg012 loaded
- [x] ESdmb005 done, exported
- [x] ESnsm007 done exported
- [x] ESqqm004 done exported
- [x] ESamq002 done, exported
- [x] ESsdm005 done exported
- [x] ESap028 done, exported
- [x] ESmhg010 loaded 

04.12.2021 update:
@elambrinaki asks for four more:
- [x] ESktm002
- [ ] ESsdgm006
- [ ] ESaqm006
- [ ] ESdd001

**Comment by PietroLiuzzo** [comment]
We have to remember that the docx conversion from traskribus is insufficient. we instead need to convert to docx the TEI document after transformation to BM with the TEI stylesheets. the output preserves in a visible way the page and column breaks.

**Comment by elambrinaki** [comment]
@PietroLiuzzo Thank you for transcribing the Ethio-SPaRe Täˀammərä Maryam manuscripts!

In ESap028, it seems that every other sheet is skipped. For instance, 
p 2r, 2v in the transcription correspond to images 3b, 4a in the viewer
p 3r, 3v in the transcription correspond to images 5b, 6a in the viewer (images 4b, 5a are skipped)
p 4r, 4v in the transcription correspond to images 7b, 8a in the viewer (images 6b, 7a are skipped)
p 5r, 5v in the transcription correspond to images 9b, 10a in the viewer (images 8b, 9a are skipped)
and so on.

The last page with the text in the transcription is 21r, while in the viewer the last image with the text is 41b.

(when referring to the images in the viewer, I use "a" for the left side of an image, and "b" for the right side of an image).

**Comment by PietroLiuzzo** [comment]
I will have a look, it may be simply an issue in the transformation to BM, which I did not check

**Comment by PietroLiuzzo** [comment]
Please, could you tell me if you are talking about the docx or some other file I sent you? or about the website?

**Comment by elambrinaki** [comment]
The last docx file
https://docs.google.com/document/d/1brUCqWzu2ku3f7CpApua71bYxEUnAqAD/edit

**Comment by PietroLiuzzo** [comment]
@angelasalerno The four in the list above are being uploaded in Transkribus. Please do the alignment of those in Transkribus and let me know when you are done, so I can export them and load the into BM. Thanks!

**Comment by angelasalerno** [comment]
I’m sorry Pietro but I don’t understand what list are you mentioning.
Do you want me to do the alignment of the first four documents that I see in the list “documents” in “Server”?
I was working on the ESktm002, should I go on with that?


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Pietro ***@***.***>
Inviato: lunedì 10 maggio 2021 19:58
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [BetaMasaheft/Documentation] transkription of Miracles of Mary mauscripts for PEMM (#1693)


@angelasalerno<https://github.com/angelasalerno> The four in the list above are being uploaded in Transkribus. Please do the alignment of those in Transkribus and let me know when you are done, so I can export them and load the into BM. Thanks!
