### ISSUE TITLE
Image links to covers and boards

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1698]
EMIP 2349 contains niches for mirrors on the inside of the covers. It is clear from the guidelines that such features are encoded with a @decoNote with type="binding" but my image set includes images of these. If I were to use @target what is the correct way to refer to the location 'inside front cover' or 'inside back cover'?

![EMIP02349_Weiner317_001](https://user-images.githubusercontent.com/39619238/108048367-dc39f080-703e-11eb-9e67-f2966d955ad6.jpg)

**Comment by PietroLiuzzo** [comment]
I think I would not use locus. I would only provide a link to the image, as for the specimen discussed here https://betamasaheft.eu/Guidelines/?q=images&id=images
so, for this I would do 
```
<rs type="inline">
                  <graphic xml:id="g1" url="https://betamasaheft.eu/iiif/EMIP/Codices/2349/002.tif/full/full/0/default.jpg"></graphic>
                  </rs>
```
would that be ok?

**Comment by Ralph-Lee-UK** [comment]
This sounds like a good solution. The syntax is a little confusing for me - which part of the url relates to the image number?

**Comment by PietroLiuzzo** [comment]
I see that there is room for improvement in how to encode this :) 
as it is now, after the codex number you have the filename followed by .tif, which must be there, then you can select a region of interest and resolution. the syntax is the one of IIIF image API https://iiif.io/api/image/3.0/#41-region

**Comment by Ralph-Lee-UK** [comment]
Thanks for this, it is now clear. The images form 2349 are not yet on the BM server, but all becomes using an EMIP number for a set that is already there! Now that I understand the syntax there is no problem! Many thanks
