### ISSUE TITLE
Scribal idiosyncrasies 

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1700]
Do we have a way of writing the combination of ግ and ዚ found in this example in EMIP 2198?
![EMIP02198_Weiner244_019 (1)](https://user-images.githubusercontent.com/39619238/108193999-00183780-710e-11eb-9392-5f124826a64e.jpg)

**Comment by thea-m** [comment]
`<hi rend="ligature">ግዚ</hi>` :)

**Comment by Ralph-Lee-UK** [comment]
Perfect!
