### ISSUE TITLE
not possible to find Clavis identifiers containing .

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1703]
@MarcinKrawczuk has kindly drawn my attention to the fact that it is not possible to search for Clavis identifiers containing a dot in the clavis search. This is used in CPG and CANT identifiers, so it would be important to find a solution. 
For example, LIT1651Homily corresponds to CPG 5150.9. Searching for CPG 5150 yields no result, and searching for CPG 5150.9 is not possible:
![image](https://user-images.githubusercontent.com/19650382/108364360-4648c600-71f6-11eb-914e-344cbb01ea8b.png)

**Comment by PietroLiuzzo** [comment]
This is not a bug, but we will get this in the new search.

**Comment by PietroLiuzzo** [comment]
This will be possible in the new search with a simple text search
<img width="1236" alt="Schermata 2021-02-19 alle 15 27 33" src="https://user-images.githubusercontent.com/508012/108516989-246b4400-72c7-11eb-9d81-4497ce76e0ee.png">
alternatively it will be possible to select a search type "other clavis ID" working just like the current one, but entering the number into the general text query field.
<img width="1233" alt="Schermata 2021-02-19 alle 16 44 05" src="https://user-images.githubusercontent.com/508012/108526751-cd1ea100-72d1-11eb-8e1c-7079660e6990.png">
