### ISSUE TITLE
A request for creating two recensions of one work

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1704]
So, we have this [Encomium on Four Living Animals by Ps-Chrysostom](https://betamasaheft.eu/works/LIT1651Homily/main). It seems that this text exists in two recensions, as is explained [here](http://www.nasscal.com/e-clavis-christian-apocrypha/encomium-on-the-four-bodiless-creatures-by-pseudo-john-chrysostom/). I have checked some mss and I'm inclined to agree that there are indeed two recensions.  I'm asking for your opinion on creating two recensions in this case.
@thea-m @DariaElagina @eu-genia @MassimoVilla

**Comment by MassimoVilla** [comment]
Dear Marcin,
if, as Lusini (1988: 488) states, two distinct recensions are indeed extant, then according to the BM policy three records should be created: one for the general record (I think LIT1651Homily might be already suitable for this), and one for each of the two distinct recensions A and B. Textual items which cannot be assigned one of the two text types should be given the ID of the general record.
Lusini (1988: 488) says that ms London, BL Orient. 619 preserves both, one after the other. Were you able to consult it?

**Comment by MarcinKrawczuk** [comment]
Yes, I was and It seems to me that [the text on f. 95r-106r](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_619_fs001r) is something entirely different from either of the recensions mentioned in NASSCAL. But if you compare e. g.:

EMML 1763, f. 48v: ሠናየ፡ መጻእክሙ፡ ዮም፡ ኀቤየ፡ አሕዛብ፡ መፍቅራነ፡ ክርስቶስ፡ ወመምህራነ፡ ሕግ፡ መፍቅራነ፡ ተግሣጽ፡ ለትዝክሩኒ፡ ከመ፡ እንግርክሙ፡ ዕበዮሙ፡ ለእሉንቱ፡ ፬እንስሳ፡ ክቡራን፡ ወአነሂ፡ ኣነከር፡ ወዓዲ፡ እትሐሠይ፡ በመንፈስየ። 

BLorient 691 f. 91v: ይእዜኒ፡ ኦፍቁራንየ፡ በአማን፡ ይደሉ፡ ንሰብሖ፡ ለአብ፡ ለወልድ፡ ወለመንፈስ፡ ቅዱስ፡ ሠናይ፡ ዘመጻእክሙ፡ ኀቤሁ፡ ዮም፡ ኦሕዝበ፡ ክርስቲያን፡ መፍቀርያነ፡ እግዚአብሔር፡ ወኀሠሥክሙ፡ በኀቤየ፡ እንግርክሙ፡ ክ(f.92r)ብሮሙ፡ ለእሉ፡ አርባዕቱ፡ እንስሳ፡ ክቡራን፡ ወአነሂ፡ ተሐሠይኩ፡ ወተፈሣሕኩ፡ ምስለ፡ አቡ፡ ኵሉ፡ ፍጥረት፡ ዘእግዚአብሔር። 

I guess that can be classified as two recensions.
