### ISSUE TITLE
New records for names of the planets

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1705]
MS Casamari MNC-001 accommodates an additional note containing the Arabic-based names of the heavenly bodies: Šamš, i.e. the Sun, Qamar, i.e. the Moon, Zǝhurā, i.e. Venus, Zuhal, i.e. Saturn, Maštari, i.e. Jupiter, ʾAṭarǝd, i.e. Mercury, and Mariḥ, i.e. Mars.
I want to mark up these names for indexing in the printed catalogue, but all of them (both Ethiopic and English names) are missing, except Mercury (which is identified as a person, PRS7025Mercury) and Mars (which is identified as a place LOC4583Mars).
Considered the need of standardization and that these names are not strictly relevant for the Ethiopian studies, what are your suggestions? Are they places, persons? Better to refer to them in some other way?
@PietroLiuzzo @eu-genia @thea-m @SusanneHummel @antobrita @DenisNosnitsin1970 @DariaElagina

**Comment by PietroLiuzzo** [comment]
please simply use `<term>` with no further attribute for such cases. You can add a ref to a wikidata entity for the entity in question for the purpose of authority alignment. This should not cause any issue regarding the validation and it is a perfectly usable encoding for a printed index.

**Comment by PietroLiuzzo** [comment]
e.g.
`<term ref="wd:Q525">Šamš</term>`

**Comment by MassimoVilla** [comment]
Thank you Pietro!
