### ISSUE TITLE
Blank folios (protective leaves vs textblock)

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1708]
Anto, Sanne and I believe that for our ItaCat project it would be good to disambiguate between blank folios in the initial/final protective leaves and blank leaves in the textblock, because they are of slightly different nature. This distinction has so far never been put into discussion in the consolidated tradition in manuscript cataloguing.
Also, we would like to give in the printed output the range of blank (protective or not) leaves, without the total numerical amount.
So, let's assume that we have the following example, taken from MS Casamari MNC-008:
```
<measure unit="leaf">82</measure>
<measure unit="page" type="blank">5</measure>
<locus from="1r" to="2r"/>
<locus target="#14v #30r"/>
```
Here, `<measure unit="page" type="blank">` counts the total amounts of blank leaves, but some of them are protective leaves (ff. 1r-2r), others are inside the textblock (ff. 14v, 30r). We want to disambiguate them. How can we specify this difference in `measure` and `locus`? Can we add a @type value? I saw that `<locus type="blank" from="1r" to="2r"/>` works, so does `<locus type="protective" from="1r" to="2r"/>`, but `<locus type="blank protective" from="1r" to="2r"/>` clearly generates an error.
We think that a clear specification at this point of the encoding would facilitate the transformation into PDF and the correct visualization in print.
@antobrita @SusanneHummel @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
I think I have to warn you here about over encoding. You can achieve the same result with a sentence which would be naturally rendered as you intend. 

````xml
There are <measure unit="page" type="blank">2</measure>
protective leaves (<locus from="1r" to="2r"/>) and 
<measure unit="page" type="blank">3</measure> blank 
leaves in the textblock (<locus target="#14 #30"/>).
````
Also, you do not have to provide `<measure>` at all, if you do not want to.

````xml
There are two protective leaves (<locus from="1r" to="2r"/>) and 
three blank leaves in the textblock (<locus target="#14 #30"/>).
````
is also fine inside `<extent>`. 

You may wish to formalise your wording and thus leave it to the code, so that this sentence is built from the encoded information, in which case nothing prevents you from using normal pointers

````xml
There are <measure unit="page" type="protective" xml:id="blank1">2</measure>
protective leaves (<locus from="1r" to="2r" corresp="blank1"/>) and 
<measure unit="page" type="protective" xml:id="blank2">3</measure> blank 
leaves in the textblock (<locus target="#14 #30" corresp="blank2"/>).
````

**Comment by MassimoVilla** [comment]
Great! thank you Pietro for this set of viable options.
I am leaving this issue open in case the others want to say a word or express some preference on one of the above options. I would personally stick to a more discursive solution, i.e. a sentence.

**Comment by SusanneHummel** [comment]
Sorry for being silent that long. I woud also opt for the discursive solution and notes it down in our notes. Thank you @PietroLiuzzo for your help!
