### ISSUE TITLE
note in layout not visualised 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1710]
In https://betamasaheft.eu/manuscripts/EMML2375/main, the `<note>` in `<layout>` is not visualised on the app (it is in other manuscripts, for example TF002), as @MarcinKrawczuk  helpfully pointed out.

```
<layoutDesc>
<layout columns="2" writtenLines="25" cert="high">
<note>
The homilies from
<ref target="ms_i1.2"/>
to
<ref target="ms_i1.16"/>
are numbered at their beginning from 1 to 17.
</note>
</layout>
</layoutDesc>
```

Can you help us to find the problem?

**Comment by PietroLiuzzo** [comment]
looks like it was just a misplaced call to templates in the XSLT.
