### ISSUE TITLE
New record

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1711]
I want to create a new ID for a prayer starting in this way: ሰውር፡ እምላዕሌነ፡ ክብደ፡ ኀጣውኢነ፡ ኦእግዚኦ፡ ኩን፡ ደምሳሴ፡ ወሰዳዴ፡                                                         ለኵሉ፡ ሕሊና፡ እኩይ፡ ነጽር፡ ላዕሌነ፡ እግዚኦ፡ በአዕይንቲከ፨   (Abbadie 111, fol. 92r)። Is there anything against?

**Comment by eu-genia** [comment]
I don't think we have it so please go ahead

**Comment by thea-m** [comment]
I also only found the apparently recently created https://betamasaheft.eu/works/LIT6384Sawwer/main and no other record. It would be helpful to link issues and Pull Requests in such cases.

**Comment by DenisNosnitsin1970** [comment]
Ok.
