### ISSUE TITLE
New work record for "Office of Sunday"

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1712]
Abbadie 111, fols 95ra-97vb
A work called ወዳሴ፡ በሰንበተ፡ ክርስቲያን, it goes like this: 
እግዚአብሔር፡ አኀዜ፡ ኵሉ፡ ዓለም፡ ንጉሠ፡ ነገሥት፡ ወእግዚእ፡
 አጋእስት፡ ወስልጣናት፡ ዘትቤላ፡ ለማርያም፡ እምከ፨ ንዒ፡ ርግብየ፡ ወንዒ፡ ሠናይትየ፡ እንዘ፡ አመቱ፡ ልዑል፡ እሙ፡ ረሰያ፡ ዘመጽአ፡
  ኀቤኪ፡ በመንክር፡ ግርማ፡ ፍሥሒ፡ ለኪ፡ ምርያም፨
I think we do not have it.

**Comment by thea-m** [comment]
Apart from the record which has already been created for it, https://betamasaheft.eu/works/LIT6385WeddaseSan/main, no, I think we don't have it elsewhere :)
