### ISSUE TITLE
Edited Works in wrong directory

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1713]
I recently edited three works: LIT1990Mawase, LIT3186Meeraf, LIT5656Malheq

After editing them, I mistakenly saved the edited versions to the 'new' directory in 'works' rather than their original locations. The edit was simply to add a new subsection to all of these, and was approved by Denis. 

Can you advise me what to do overwrite the old entries in the correct location and delete these from their incorrect location. I'm sure that this is straightforward, but I just need a pointed especially regarding deleting the files from the incorrect location

**Comment by PietroLiuzzo** [comment]
I think if you fix this in your local copy, making the changes in the proper directory and removing the copies from new and then commit the corrections everything should go fine. make a branch for that and a PR as usual with these changes and I can review it.
