### ISSUE TITLE
Salam to Libanos?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1715]
The Salam to Libanos in MKL-014 seems different to me (?) than LIT6167SalLibanos (the salam in Bausi's edition)

incipit
ሰላም፡ ሰላም፡ ሊባኖስ፡ ብፁዕ፨ መንነከ[sic]፡ ኃላፊ፡
                           ዘበምድር፡ ፍግዕ፨ ለወልደ፡ ድንግል፡ ዴገንኮ፡ ለበግዕ፨ ዘቢጠከ፡ ኰኵሐ፡ አውኃዝኮ፡ ለነቅዕ። በእንተ፡ ጽድቅ፡
                           ወሕይወት፡ ርእሶ፡ አንደየ፨ እምኃውዘ፡ ዓለም፡ ጐየ፨ እምኀበ፡ እግዚኡ፡ ተዓሥየ፡ ሠናየ፨...
explicit
ሰላም፡ ለፀአተ፡ ነፍስከ፡ አመ፡ ሰሉሱ፡ ለጥር፤
                           ጊዜ፡ ፍና፡ ቀትር፤  ብፁዕ፡ ሊባኖስ፡ ጥዑመ፡ ዜና፡ ወዝክር፨ ወረዱ፡ ይትቀበሉከ፡ ግሩማነ፡ ራእይ፡ ማኅበር፡ እንዘ፡
                           ይዜምሩ፡ በሐዋዝ፡ መዝሙር፨

Or is it a variant of the same?

According to the description in DomLib the same hymn is also in
EMML 2096 143v
EMML 2810 74v
BAVet276 120r-122r

Thank you @DenisNosnitsin1970 @thea-m

**Comment by DenisNosnitsin1970** [comment]
This salam from MKL-014 is indeed unique and different from the edited one; 
EMML 2096 143v
EMML 2810 74v
contain the edited salam, not that of MKL-014
(I cannot check BAVet276 120r-122r, which is in VAN LANTSCHOOT,
Inventaire sommaire des Mss Vaticans éthiopiens 251-299 )

**Comment by eu-genia** [comment]
Thank you, am creating a new record then

**Comment by eu-genia** [comment]
created https://github.com/BetaMasaheft/Works/pull/490
