### ISSUE TITLE
Person record creation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1716]
@MarcinKrawczuk cannot create new person records anymore (he tried several browsers):
![image](https://user-images.githubusercontent.com/19650382/110294037-9e057080-7fef-11eb-832b-9607e11875b5.png)

**Comment by PietroLiuzzo** [comment]
The underscore at the end is a mistake. please try again without the underscore (or spaces which get into underscores).

**Comment by MarcinKrawczuk** [comment]
OK, it works. Grazie :)
