### ISSUE TITLE
Work record for a text in EMML 1763, ff. 34v-35v 

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1717]
I am asking permission to create a work record for the text published [here](https://www.jstor.org/stable/43661087?seq=1).  I would suggest a main title: ድርሳን፡ በዕለተ፡ እለ፡ አጽብሓ፡. 
@thea-m @eu-genia @DariaElagina

**Comment by thea-m** [comment]
I apologise for the delay in our response!
I agree that this text doesn't seem to have a record yet, please go ahead.
