### ISSUE TITLE
New record for a Ordination/Consecration rituals

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1718]
Dear all,

I would like to create a record for the Ordination/Consecration rituals attested in at least two manuscripts:
https://betamasaheft.eu/manuscripts/EMIP00146/main (here with incipits)
And CHJN008 
I could not find an existing ID for this text in the db. I would create one single work file with corresponding textparts.
Any objections, @thea-m , @eu-genia , @DenisNosnitsin1970 ?

**Comment by DenisNosnitsin1970** [comment]
Ok
