### ISSUE TITLE
Notes on rubrication

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1719]
In the EMIP catalogue notes are included on words that are rubricated throughout the ms, especially Psalters. 

Occasionally there is a note such as 'God is not rubricated in the first three works' - this is noted because it is usual for እግዚአብሔር to be rubricated in the Psalms, Canticles, and Song of Songs. 

How would you recommend noting this?

**Comment by thea-m** [comment]
I think I would simply add is as text in `<seg type="rubrication">` in handNote, where all information on rubrication (if not marked up directly in the text) can be collected.

**Comment by Ralph-Lee-UK** [comment]
That's what I thought - just wanted to check. Many thanks!
