### ISSUE TITLE
modify new person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1720]
This is not terribly important, but:
Most person records I create end up having    
```
<persName xml:lang="gez" xml:id="n1"></persName>
<persName xml:lang="gez" type="normalized" corresp="#n1"></persName>
```
in the file. It would save me some time if these two lines would be present with empty content (or, as now, a name inserted in the form present in one of them) in the newly created files.
Of course, this would only make sense if everyone feels the same way. What do you think? @DariaElagina @DenisNosnitsin1970 @eu-genia @MarcinKrawczuk

**Comment by DenisNosnitsin1970** [comment]
Sorry, I do not understand well - "would be present with empty content", why? Why empty? Should' the field be filled out?

**Comment by eu-genia** [comment]
Am not sure I understand either... When I create a person record I always get the first tag pre-filled with content = name as provided in the form.

**Comment by thea-m** [comment]
Sorry, clearly I did not explain well. 
Currently, we get `<persName xml:lang="gez" xml:id="n1"></persName>` filled with what was typed in the web form. I just thought it would save time to have 
```
<persName xml:lang="gez" xml:id="n1"></persName>
<persName xml:lang="gez" type="normalized" corresp="#n1"></persName>
```
in the record, removing the need for some copy pasting. But if this is only annoying for me, please close this issue.

**Comment by thea-m** [comment]
I still think that it would save a lot of time for the majority of person records to have
```
<persName xml:lang="gez" xml:id="n1"></persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">Name as written in the form</persName>
```

 @PietroLiuzzo do you think that it would be possible to carry out this change whenever it might make sense in your workflow?

**Comment by DenisNosnitsin1970** [comment]
You mean mth like it will be filled "authomatically"?

**Comment by thea-m** [comment]
I propose to change the current fields created automatically when typing
![image](https://user-images.githubusercontent.com/19650382/142849055-17f8ed6f-8e22-4ef1-906a-bf7a0fd3d794.png)

which are:

```
    <person sex="1">
                    <persName xml:lang="gez" xml:id="n1">Takla Giyorgis</persName>
                    <faith type=""/>
                    <birth/>
                    <death/>
                    <floruit/>
                </person>
```

into
```
    <person sex="1">
                 <persName xml:lang="gez" xml:id="n1"></persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">Takla Giyorgis</persName>
                    <faith type=""/>
                    <birth/>
                    <death/>
                    <floruit/>
                </person>
```

(I assume that people write names in the online form both in transliteration and in fidal, so some copying and moving around might always be necessary, but really, the vast majority of our person records consists of an Ethiopic name and its transliteration, having these two lines present would really save time)

**Comment by DenisNosnitsin1970** [comment]
Ok.

**Comment by thea-m** [comment]
Thanks, Pietro!
