### ISSUE TITLE
syncing problem

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1722]
The changes carried out in https://github.com/BetaMasaheft/Manuscripts/pull/1026/files, https://github.com/BetaMasaheft/Persons/pull/342/files and  https://github.com/BetaMasaheft/Works/pull/497/files have not made it through the app.

**Comment by PietroLiuzzo** [comment]
Dear @thea-m is this now fine?

**Comment by thea-m** [comment]
Yes, sorry!
