### ISSUE TITLE
The Miracles of Jesus and its detailed contents in EMIP 2392

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1725]
In the latest batch of material to be catalogued from EMIP is 2392, which is a Miracles of Jesus which contains 47 miracles of Jesus with incipits. The current record for Miracles of Jesus has introductory textparts : Introduction, John, Adam, and then under Miracles: Nativity, Temple, Theft, Abgar. Some of these correspond to what is in the attached PDF. Given the detail that Jeremy brown has put into the catalogue, would it be good to extend the details for the Miracles of Jesus using these details, and also include the bibliographic details such as the works of Grebaut and van Rompay and Arras? If so, would it be best to add these as text parts, or perhaps preferable to create work files in the same way that his has been done for Miracles of Mary, St George and some others?

[Miracles of Jesus EMIP 2392 Contents.pdf](https://github.com/BetaMasaheft/Documentation/files/6164990/Miracles.of.Jesus.EMIP.2392.Contents.pdf)

**Comment by thea-m** [comment]
Thank you! It would be great to encode the detailed catalogue information. I think that individual work files, in analogy to the other miracles, would be the best way. Some exist already: https://betamasaheft.eu/works/LIT2382Taamme/analytic
Of course, this is a lot of work. As always, anything that is being encoded at all is a great progress.

**Comment by DenisNosnitsin1970** [comment]
This will be a good contribution, please add Ethiopic text. However, there is a question: what should be used for text records as the source of the Ethiopic? It should be an edition for those miracles that are edited, shouldn't it?

**Comment by thea-m** [comment]
That would be preferable if there is an edition, but if not or the most detailed description is present in the catalogue, then that one can be taken as well.

**Comment by Ralph-Lee-UK** [comment]
Thanks for this. I think we had one example before where there was not an edition, but I added a note to say where the text was taken from. I'll obviously run it by both of you for approval. EMIP 2392, the ms that I have, has 47, so I can code these. I will check with the existing records first, but the hard work has already been done in preparing the catalogue text with incipit and biographical information, so this shouldn't take too long. There are several other Miracles of Jesus in the CUA Collection that we are now working on, so I can add more when I get to them, but it will make the work worth doing.

**Comment by thea-m** [comment]
Wonderful, thank you! I look forward to the PR!

**Comment by Ralph-Lee-UK** [comment]
@thea-m I have the Patrologia Orientalis editions (3 volumes) of Grebaut - would you like incipits and explicits copying from that?

**Comment by DenisNosnitsin1970** [comment]
If possible, to have both would be excellent.

**Comment by thea-m** [comment]
@Ralph-Lee-UK I think that having the texts from the edition would be great, but if you have others that you can copy paste more easily, do whatever works best for you.
(if adding both, the texts from the edition should go to the work record and those from the manuscript to the manuscript record...but as always, anything at all is an improvement!)

**Comment by Ralph-Lee-UK** [comment]
@thea-m I can do this, at least for the miracles that I have to encode anyway. 

I see that in the case of LIT6012MJSalome that there is a version of the text which is from BDLaethd20 so I will move these incipits and explicits to the manuscript record at the same time. It will take a while, but I think I have about 5 miracles of Jesus in the CUA collection, so the work is worth doing and will accelerate the coding of the later ones!

**Comment by Ralph-Lee-UK** [comment]
@thea-m apologies for multiple posts. I have run into a problem - BDLaethd20 does not appear as a file record in either my working branch or the master branch. This puzzles me, because there is a record at https://betamasaheft.eu/manuscripts/BDLaethd20/main#p1 - any ideas on how I might access this?

**Comment by thea-m** [comment]
Hi, BDLaethd20 isn't yet available publicly (and already has these texts in the record). Honestly, I personally think that having any text at all is the most important thing and that it's better on focusing to edit more files than spending a lot of time finding the perfect source for the excerpts...
