### ISSUE TITLE
deletion of LIT1076alMagm

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1727]
As pointed out by @karljonaskarlsson , LIT4723TarikaWaldaAmid and LIT1076alMagm apparently refer to the same work. I suggest to delete LIT1076alMagm, which hasn't been used yet.
Any obejctions? @DariaElagina @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
No objections.
