### ISSUE TITLE
New CAe number

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1728]
I wold like to assign a new CAe number for a Homily of Gabriel. 

This is the incipit:
ድርሳን፡ ዘቅዱስ፡ ገብርኤል፡ ሊቀ፡ መላእክት፡ ዘይትነበብ፡ እመ፡ ፲ወ፱፡ ለየካቲት፡ ... ዘተናገረ፡ ኤጲፋንዮስ፡ ክቡር፡ ጳጳስ፡ ዘሀገረ፡ ቆጵሮስ፡ ወውስተ፡ መጽሐፍ፡ ዘይሰመይ፡ አክሲማሮስ፡ በእንተ፡ ኂሩቱ፡ ለገብርኤል፡ ሊቀ፡ ሠራዊተ፡ ሰማያት፡ በከመ፡ ናዘዞ፡ ለአቡነ፡ አዳም።

Titel: 
Dǝrsāna Gabrǝʾel, Homily in Honour of St. Gabriel, for 19th. Yakātit, told by Epiphanius, bishop of Cyprus, in the book that is called Aksimāros

found in these mss:
British Library Endangered Archives, EAP526/1/49, fols. 21vb-30ra; EMIP Weiner 330, fols. 146ra-152rb; Accademia Fonds Conti Rossini 40, fols. 21ra-28rb; EMML Nr. 273, fols. 19ra-25ra; EMML Nr. 645, fols. 17va-23vb 

Author: (well its Pseudo-)
Epiphanius of Salamis, bishop of Cyprus

Do you need to know more? I will probably also identify further mss in the future.

**Comment by thea-m** [comment]
Thank you! I agree that no record seems to exist for this yet. 
If you have an explicit, that would also be great. Is the mention of the ʾAksimāros in the incipit enough to safely identify this particular homily, or would people need more information on the content to distinguish it from others?

**Comment by SophiaD-M** [comment]
The combination "Epiphanius, bishop of Cyprus, in the book that is called Aksimāros" or maybe a shortened version, "Epiphanius, in his book Aksimāros"? 

Explicit: እስመ፡ ውእቱ፡ አምላክነ፡ ወውእቱ፡ ሰብእ፡ ከማነ፡ በከመ፡ ይቤ፡ ጳውሎስ፡ ሐዋርያ፡ ወገብረ፡ ሰላም፡ በደመ፡ መስቀሉ፡ ለእለ፡ ውስተ፡ ሰማይ፡ ወምድር፡ ወሞገሰ፡ መስቀሉ፡ ይኩን፡ ላዕለ፡ ፍቁሩ፡ ለዓለመ፡ ዓለም፡ አሜን።

**Comment by DariaElagina** [comment]
I also agree with the creation of a new ID. Thank you!
