### ISSUE TITLE
A work record for Chrysostom's homily

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1729]
I am asking permission for creating work record for Chrysostom's homily on the prodigal son (CPG 4577). It is preserved in EMML 1763 f. 173b-176b where it is attributed to "Gregory, Priest from Antioch", however I have checked Ethiopic text against the Greek and the identification with CPG 4577 seems to stand. 
@thea-m @MassimoVilla @smaugustine

**Comment by thea-m** [comment]
Please go ahead, and make sure the record states clearly that you're the one who identified it.
