### ISSUE TITLE
DidacticMaterial

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1730]
The keyword DidacticMaterial is not shown in the keywords index view, and its page has this error message:
https://betamasaheft.eu/authority-files/DidacticMaterial/main

> Something has gone wrong and there are more than one item with id DidacticMaterial.
> 
> /db/apps/BetMasData/authority-files/new/DidacticMaterial.xml
> /db/apps/BetMasData/authority-files/Genres/DidacticMaterial.xml

I see this file only in the Genres folder, not in new.

**Comment by PietroLiuzzo** [comment]
I have removed the double from the db, so now you see the entry.

**Comment by PietroLiuzzo** [comment]
it looks like this cannot be in the list, because it has never been added to the taxonomy.xml, I am adding it...

**Comment by PietroLiuzzo** [comment]
under which category should it be? there is no Genre afaik. Subjects?

**Comment by thea-m** [comment]
I added it yesterday, did it not go through? If not, yes, subjects is correct

**Comment by PietroLiuzzo** [comment]
it did, I was on the wrong branch apparently. I am adding it to the canonical taxonomy as well. 
should be fine now
https://betamasaheft.eu/authority-files/list?keyword=DidacticMaterial

**Comment by thea-m** [comment]
yes, thank you!
