### ISSUE TITLE
Relations Between Verse and Prose

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#1735]
I'm wondering about how to indicate that one work is a versified form of another work? Whether `saws:isRelatedTo` or `saws:isVariantOf` or something else?

There are a handful of cases, most notably መልክአ፡ ውዳሴ፡ (ማርያም፡) and መልክአ፡ አንቀጸ፡ ብርሃን፡, which give ውዳሴ፡ ማርያም፡ and አንቀጸ፡ ብርሃን፡ arranged in a malkǝʾ/ʿārke verse form, and similarly the isolated cases of a verse ነገረ፡ ማርያም፡ (BL Or 790) and a verse ራእየ፡ ዮሐንስ፡ (BL Or 574), among others which are in need of further investigation.

**Comment by PietroLiuzzo** [comment]
I would use isVersionOf https://betamasaheft.eu/Guidelines/?q=saws&id=relations 

The fact one is in verse or not is eventually already included in the encoding and does not need IMHO further specification in the relation name. 
We could of course define a subproperty of saws:isVersionOf like betmas:isVerseVersionOf eventually to be defined as symmetrical to another new subproperty betmas:isProseVersionOf

related to https://github.com/BetaMasaheft/Documentation/issues/1721
