### ISSUE TITLE
EMIP 2401 New work record for

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1736]
The miracle on the left hand leaf in the attached does not seem to appear in Macomer's list, and I so far have not identified a work record for this miracle. @elambrinaki can you help here? Should we create a work record for this one?

![EMIP02401_Weiner366_017](https://user-images.githubusercontent.com/39619238/114569560-01c52e00-9c6d-11eb-8f86-41067576c069.jpg)

**Comment by elambrinaki** [comment]
@Ralph-Lee-UK We have also come across this miracle and decided it is not from the Macomber list. For such "new" miracles we use IDs starting from 1000. This record is ID 1063 in the PEMM database. When you create a work record on Beta Masaheft, we will link it with our PEMM ID 1063.
So far, we have found two instances of this miracle.

**Comment by Ralph-Lee-UK** [comment]
@elambrinaki I'll get on with this tomorrow

**Comment by Ralph-Lee-UK** [comment]
@elambrinaki I have been delayed because I am waiting for another pull request to be approved from a 'works' branch. Meanwhile there is a further miracle that does not appear to have a work record on the right of this image

![EMIP02401_Weiner366_030](https://user-images.githubusercontent.com/39619238/115269363-26b91580-a133-11eb-9c1a-4d7e8f4ed774.jpg)
