### ISSUE TITLE
Homilies from BnF Abb. 80, EMML 1194 

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1739]
I don't know whether the procedure allows it, but I would like to create work records for a number of homilies. The reason for creating work records is to have clavis number for them so that I can give it as reference in a text I hope to finish someday. 

The homilies are (please note that the list of manuscript is not complete):

1) For the fourth Sunday of the Lent ድርሳን ዘይትነበብ በ፬ጾም ሰንበት እንተ ይእቲ ደብረ ዘይት ቅድስት።
BnF Abb. 80 f. 33r-35v; EMML 1194, p. 95-99

2) For the fifth Sunday of the Lent on martyrdom and monkhood ምንባብ በ፭ሰንበት ጾም ዘደረሰ ርቱዐ ሃይማኖት ዘበእንተ ስምዕ ወበእንተ ምንኵስና።
BnF Abb. 80 f. 35v-38v;  EMML 1194, p. 99-104

3) For the sixth Sunday of the Lent ድርሳን ዘርቱዐ ሃይማኖት ዘይትነበበ በ፮ሰንበት ጾም።
BnF Abb. 80 f. 39r-50v; EMML 1194 p. 105-109

4) On Peter's denial for Maundy Thursdayድርሳን ዘደረሰ ርቱዐ ሃይማኖት በእንተ ዘከመ ክኅደ ጴጥሮስ። 
BnF Abb. 80 f. 51r-55v; EMML 1194 p. 152-161

5) On how Pilate questioned our Lord for Good Friday ድርሳን ዘርቱዓ ሃይማኖት ዘይትነበብ በዐርብ ስቅለት ጊዜ  ፫ሰዓት ዘከመ ሐተቶ ጲላጦስ ለእግዚእነ።
BnF Abb. 80 f. 56r-61v, EMML 1194 p. 161-172

6) On 24 priests of heaven ዛቲ መጽሐፍ ድርሳን ዘ፳ወ፬ካህናተ ሰማይ ዘወፅአት እምኢየሩሳሌም
EMML 1194 p. 19-29, EMIP 01293 = Marqos Addis 8 f. 9r-13v

7) [Sǝbkät] For a Sunday in Advent (Jesus Christ the son in Trinity) ዘደረሰ ርቱዕ ሃይማኖት በሰላመ እግዚአብሔር አሜን። አጽምዑ ኦሰማዕያን ስብከተ መድኃኒት
EMML 1194 1194 p. 29-36, MIP 01293 = Marqos Addis 8 f. 14r-17r

@thea-m @DariaElagina  @eu-genia @Ralph-Lee-UK @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
If they are not there - no objection!
