### ISSUE TITLE
A separate record for a homily from Dǝrsāna Mikāʾel ?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1740]
This is a contiuation of my preceding post. In the same set of manuscripts there is a homily from Dǝrsāna Mikāʾel for the month of Ṭǝrr. It is here transmitted independently, does it therefore deserve a work record of its own?

This is one attestation, possibly the oldest:
EMML 7638, f. 163r-
https://www.vhmml.org/readingRoom/view/201165

@thea-m @eu-genia @MassimoVilla @smaugustine @DenisNosnitsin1970 

Would it be OK if, rather than create a new work record, I used LIT3959Homily?

Thank you very much in advance for your opinion in both cases.

**Comment by DenisNosnitsin1970** [comment]
In this case we usually create an intependent ID, as far as I understand.

**Comment by DariaElagina** [comment]
LIT3959Homily is an independent ID for this text if I am not mistaken, the fact that it has a relation Dǝrsāna Mikāʾel does not make it into a second-level ID. So, no new ID is needed, in my opinion, you can just use LIT3959Homily.

**Comment by thea-m** [comment]
I agree that LIT3959Homily should be used here, the text in the edition and in EMML 7638 seems to be the same.

**Comment by eu-genia** [comment]
can this issue be closed?

**Comment by MarcinKrawczuk** [comment]
Yes, I'm closing it. LIT3959Homily has been modified accordingly.
