### ISSUE TITLE
EMIP 2389, 2390, 2391 originally one manuscript

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1741]
There are three manuscripts in the CUA collection are actually 3 parts of one original ግብረ፡ ሕማማት፡, which has been separated at some point and bound in three sections - but with no folios or other things added when it was divided. 

Would it be appropriate to code these as one entry with three parts, or just note the connection and continuation of the text when catalogued? Are there any clear guidelines for this situation?

Any help most welcome

**Comment by PietroLiuzzo** [comment]
In previous situations of this kind, if I am not wrong, we have done a record for each current manuscript (= Circulation Unit) and related them accordingly with one another. I think the example is similar to this one https://isawnyu.github.io/isaw-papers-awdl/20-7/#section4.3

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo that's very helpful.

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo would it be correct, therefore, looking at the example that you pointed me to, to code the relations in this way, with this code in the <body></body> section towards the end of the XML file:
I think I understand the the following with this description in words:
An original unit of circulation (UniCirc1) has undergone a transformation (#tr1) 
The original unit of circulation is now in three parts EMIP02389 EMIP02390 EMIP02391
The transformation was a simple division 
The transformation has produced three further units of circulation (UniCirc2, UniCirc3, UniCirc4) 
These units of circulation are identical to the three separate ms EMIP02389 EMIP02390 EMIP02391

As the article comments, this perhaps has some repetition, but it means that whichever way a search is done the right sort of relationship between the texts is defined.

There would be a similar but slightly longer 

                
 <listRelation>
                    <relation active="EMIP02389#UniCirc1" name="sdc:undergoesTransformation" passive="EMIP02389#tr1"/>
                    <relation active="EMIP02389#UniCirc1" name="dcterms:hasPart" passive="EMIP02389 EMIP02390 EMIP02391"/>
                    <relation active="EMIP02389#tr1" name="sdc:hasTransformationModel" passive="sdc:D3"/>
                    <relation active="EMIP02389#tr1" name="sdc:resultsIn" passive="EMIP02389#UniCirc2"/>
                    <relation active="EMIP02389#tr1" name="sdc:resultsIn" passive="EMIP02389#UniCirc3"/>
                    <relation active="EMIP02389#tr1" name="sdc:resultsIn" passive="EMIP02389#UniCirc4"/>
                    <relation active="EMIP02389#UniCirc2" name="skos:exactMatch" passive="EMIP02389"/>
                    <relation active="EMIP02389#UniCirc3" name="skos:exactMatch" passive="EMIP02390"/>
                    <relation active="EMIP02389#UniCirc4" name="skos:exactMatch" passive="EMIP02391"/>
                  </listRelation>


This would be reflected with the following code in the record for EMIP 2390

        <listRelation>
          <relation active="EMIP02390#UniCirc1" name="sdc:undergoesTransformation" passive="EMIP02390#tr1"/>
          <relation active="EMIP02389#UniCirc1" name="skos:exactMatch" passive="EMIP02390#UniCirc1"/>
          <relation active="EMIP02390#tr1" name="skos:exactMatch" passive="EMIP02389#tr1"/>
          <relation active="EMIP02390#tr1" name="sdc:hasTransformationModel" passive="sdc:D3"/>
          <relation active="EMIP02390#UniCirc1" name="dcterms:hasPart" passive="EMIP02389 EMIP02390 EMIP02391"/>
          <relation active="EMIP02390#tr1" name="sdc:resultsIn" passive="EMIP02390#UniCirc2"/>
          <relation active="EMIP02389#tr1" name="sdc:resultsIn" passive="EMIP02390#UniCirc3"/>
          <relation active="EMIP02389#tr1" name="sdc:resultsIn" passive="EMIP02390#UniCirc4"/>
          <relation active="EMIP02390#UniCirc2" name="skos:exactMatch" passive="EMIP02389"/>
          <relation active="EMIP02390#UniCirc3" name="skos:exactMatch" passive="EMIP02390"/>
          <relation active="EMIP02390#UniCirc4" name="skos:exactMatch" passive="EMIP02391"/>
        </listRelation>

**Comment by Ralph-Lee-UK** [comment]
@PietroLiuzzo I have made one correction to the second line of the code for EMIP 2390
<relation active="EMIP02389#UniCirc1" name="skos:exactMatch" passive="EMIP02390#UniCirc1 EMIP02391#UniCirc1"/>

**Comment by PietroLiuzzo** [comment]
looks good to me!

**Comment by Ralph-Lee-UK** [comment]
Perfect - I have included the code in the latest pull request.

**Comment by Ralph-Lee-UK** [comment]
Now the code for this is merged, the next step is the visualisation. I have selected https://betamasaheft.eu/manuscripts/EMIP02390/graph for instance, but nothing is visible. This could be because I'm missing something, or equally be because my code is wrong! Any suggestions?

**Comment by PietroLiuzzo** [comment]
This was due to a failed transfer to the triplestore, thanks for letting me know. I have now uloaded manually the files and you can see the graphs generated.
