### ISSUE TITLE
EMIP 2402

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1743]
EMIP 2402 is another set of Image prayers, and other similar works. There are several that I have not been able to identify work records for.

Prayer to God, “Come, Let us weep.”
ንዑ፡ ንብኪ፡ ኢይሜንነነ፡ ውእቱ፡ አቡነ፡ ወእምነ፡ እስመ፡ ውእቱ፡ ፈጠረነ።
![EMIP02402_Weiner367_019](https://user-images.githubusercontent.com/39619238/117458739-86405f00-af42-11eb-9bde-27fd46fc668d.jpg)

Blessing and Praise to Mary
ባርክ፡ ወውዳሴ፡ ለማርያም፡ ሥርጉተ፡ ሥላሴ፡ ስምኪ፡ ወስመ፡
![EMIP02402_Weiner367_027](https://user-images.githubusercontent.com/39619238/117458882-abcd6880-af42-11eb-8e8a-7c88007e456e.jpg)

Mälkəʾä Gäbrä Mänfäs Qəddus
ገብረ፡ መንፈስ፡ ቅዱስ፡ ዕንቈ፡ ሶም፡ ሰላም፡ ለከ፡ ሰላም።
![EMIP02402_Weiner367_033](https://user-images.githubusercontent.com/39619238/117459105-f0f19a80-af42-11eb-87e3-2436b1ae30d8.jpg)
![EMIP02402_Weiner367_034](https://user-images.githubusercontent.com/39619238/117459125-f5b64e80-af42-11eb-88c1-99f76ea1e75b.jpg)

Hymn to Saint George, “Hallelujah, Come, George, Rushing on the Horse.”
ተንሥእ፡ እግዚአ፡ ርድአነ፡ ነአ፡ ጊዮርጊስ፡ እንዘ፡ ትሰርር፡ በፈረስ፡ ወነአ፡ ፍቁርየ፡ ዘልዳ፡ ንጉሥ።
![EMIP02402_Weiner367_050](https://user-images.githubusercontent.com/39619238/117459262-1d0d1b80-af43-11eb-9c3e-399157618c5c.jpg)

Hymn to the Trinity, “For the Father, Son, and Holy Spirit, the Running Wind is Their Messenger,”
መላእክቲሆሙ፡ ለሥሉስ፡ ሩጸቶሙ፡ ነፋስ።
![EMIP02402_Weiner367_057](https://user-images.githubusercontent.com/39619238/117459403-43cb5200-af43-11eb-8bb4-63c698d7a933.jpg)

Any advice welcome, and presumably new work files may be created for those we cannot identify?

**Comment by DenisNosnitsin1970** [comment]
For ተንሥእ፡ እግዚአ፡ ርድአነ፡ ነአ፡ ጊዮርጊስ፡ እንዘ፡ ትሰርር፡ በፈረስ፡ , cp. LIT4957SebhataF, the rest is not familiar to me.

**Comment by smaugustine** [comment]
I wouldn't identify any of these as being a መልክእ፡. I have seen similar poems with ሃሌ፡ ሉያ፡ and 3-4 rhymed lines, but I am not sure they have a proper name. An example would be BL Or 716, 172r-v, "ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ጊዮርጊስ፡ ዘርብ። ዘሰማይ፡ ኮከብ። ..."

**Comment by Ralph-Lee-UK** [comment]
@smaugustine many thanks, and you're quite right - that was simply the catalogue name given to this as a 'collection'. @DenisNosnitsin1970 I will check with LI4957SebhataF and then create some work files for the others.
