### ISSUE TITLE
syncing issue ESqdq004

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1744]
The changes carried out in https://github.com/BetaMasaheft/Manuscripts/pull/1069 are apparently not synchronised on the app. I had thought that the splitting of the files would prevent this? Was there something I should have done that I missed?
Please let me know if you need more information.
Thank you for your help!

**Comment by PietroLiuzzo** [comment]
I also wished that a tested solution for one issue would prevent / avoid / solve others, but it is unfortunately not the case. I am looking at this presently and hope to identify and solve the new issue soon. Did you actually find out with the latest #1091?

**Comment by thea-m** [comment]
You mean https://github.com/BetaMasaheft/Manuscripts/pull/1091? That didn't change anything, I tried it out before writing the issue :(

**Comment by PietroLiuzzo** [comment]
I have reloaded manually, expanded and stored for indexing both ESqdq004 and EMML4398. No luck in finding out what happened unfortunately, yet.

**Comment by PietroLiuzzo** [comment]
I am sorry, this is not going to work yet. the issues about implementing the use of split texts are still open and not likely to be closed until I can have more then 20 minutes in a row of concentrated work. I am looking at working around this for you now.

**Comment by thea-m** [comment]
Thank you, that's wonderful! I hope that it wasn't too troublesome for you.
I'm afraid I don't understand the comment on xml:base in EMML6952 - this file wasn't split.
(I've checked all zotero tags in these files and could find nothing problematic)
