### ISSUE TITLE
New work record for a prayer for the dead

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1747]
This regards the prayer in BL Or 546, f. 153 rb:
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_546_fs001r
![Przechwytywanie](https://user-images.githubusercontent.com/62760230/118163082-d7a88c80-b421-11eb-9c01-3b913889c5fb.JPG)

As discovered by @DariaElagina the same prayer occurs in at least one other case:
https://betamasaheft.eu/manuscripts/BAVet66/main (here ms_i2).

Would you recommend creating a work record for it?
@thea-m @Ralph-Lee-UK @smaugustine @eu-genia

**Comment by Ralph-Lee-UK** [comment]
Based on what we have been doing recently this seems worth it to me.

**Comment by DariaElagina** [comment]
I guess the issue can be closed.
