### ISSUE TITLE
Tigre language

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1750]
Dear all,

am I right that our scheme does not have Tigre in the list of languages? Please, tell me if I am wrong, otherwise, I would need to add it to the scheme.
@DenisNosnitsin1970  @eu-genia

**Comment by DariaElagina** [comment]
@thea-m 
I just want to be sure that I have not overlooked something, thank you!

**Comment by thea-m** [comment]
No, I don't see it in the list either, please go ahead!
