### ISSUE TITLE
TM miracle work record duplicate

### ISSUE THREAD

**Issue by elambrinaki** [BetaMasaheft/Documentation#1751]
@thea-m 
Dear Dorothea,
We realized LIT5906MMApparition is Macomber ID 32 LIT5114MiracleHusband. It is a story about Satan and gold. Original Macomber title is "The husband who denied Christ when he became poor". We compared the plot of LIT5906MMApparition with LIT5114MiracleHusband in EMML (HMML) 6938 (Macomber took incipit for ID 32 from this manuscript).
LIT5906MMApparition was created when you cataloged BLorient652.

**Comment by thea-m** [comment]
Thank you! Yes, I read the story in both manuscripts now, you are right. The differences are considerable, but probably not enough to warrant a records for two recensions (as long as all witnesses haven't been compared). So I suggest I delete LIT5906MMApparition and change its occurrences to LIT5906MMApparition - unless your work has already allowed you the identification of recensions of this miracle?

**Comment by elambrinaki** [comment]
@thea-m You are right, it is likely that the differences in plot aren't enough to create separate work records according to the Beta Masaheft rules. In our database, we did create recension IDs for these two versions of Macomber ID 32 as the incipits are different. Occurrences of ID 32 that match to Macomber incipit from EMML (HMML) 6938 are called ID 32 EMML (HMML) 6938 (recension ID is the manuscript name). Occurrences that match to the incipit from BLorient652 are called ID 32 BOr (BL) 652. This is our general principle to assign recension IDs to story variations with noticeable differences in incipits; story IDs for which Macomber gave two incipits thus have two recension IDs in our system.

**Comment by thea-m** [comment]
Sorry to come back to this. Do you already have several occurrences of both recensions? Then I could quickly check whether the different incipits and plot differences are consistent, and we could keep both IDs within BM (if there is more variation or incipits and plot differences can't be matched, I'd delete one of them).

**Comment by elambrinaki** [comment]
One recension is in EMML6938	f. 68r. The same version is presumably in
PEM (PUL) 41 https://dpul.princeton.edu/msstreasures/catalog/w9505399b f. 164v
EMDA (HMML) 153 https://w3id.org/vhmml/readingRoom/view/500198 f. 74r
EMML (HMML) 1156 https://w3id.org/vhmml/readingRoom/view/202992 scan 184b
Ethio-SPaRe (UH) QS-014 https://betamasaheft.eu/manuscripts/ESqs014/viewer scan 137b
M-432 EMDA (EAP) 1-04 https://eap.bl.uk/archive-file/EAP432-1-4 scan 75b
VOHD (HMML) 105 f. 97r
UNESCO (HMML) 10.11 scan 134b

Another recension is in BLorient652 f. 120v. The same version is presumably in
EMDA (HMML) 180 https://w3id.org/vhmml/readingRoom/view/500259 f. 136v
EMDA (HMML) 10 https://w3id.org/vhmml/readingRoom/view/138172 f. 60v, 90v
EMML (HMML) 8970 https://w3id.org/vhmml/readingRoom/view/201697 f. 115v
Ethio-SPaRe (UH) GKM-004 https://betamasaheft.eu/manuscripts/ESgkm004/viewer f. 134v
Ethio-SPaRe (UH) MKL-002	 https://betamasaheft.eu/manuscripts/ESmkl002/viewer scan 128a
Ethio-SPaRe (UH) SM-010 https://betamasaheft.eu/manuscripts/ESsm010/viewer scan 84b
IES-286 (EAP) 1-1-0432 https://eap.bl.uk/archive-file/EAP286-1-1-432 scan 122b
EMDA (HMML) 407 https://w3id.org/vhmml/readingRoom/view/534313 scan 160b

**Comment by elambrinaki** [comment]
@thea-m Please let me know whether you find the versions consistent or not. Thank you for working on this!

**Comment by thea-m** [comment]
Thank you for the comprehensive list! I checked most manuscripts, and the recensions seem to be consistent according to the two groups listed here. With the exception however of the text of BLor652, which differs from both. I suggest to keep:
LIT5114MiracleHusband for the recension in EMML6938, 
LIT5906MMApparition for the recension in BLorient652, 
and I will create a new record for the recension contained in the manuscripts you listed together with BLorient652 and a new general record.
