### ISSUE TITLE
New work record for Image of the Archangels Michael and Gabriel in EMIP 2723

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1752]
f. 1r-5r of EMIP 2723 have an Image of the Archangels Michael and Gabriel, መልክአ፡ ሚካኤል፡ ወገብርኤል፡. with no Chaine number. I don't see work file for this, and it seems to deserve one. Any advice?

![EMIP02723_Weiner435_005](https://user-images.githubusercontent.com/39619238/118996156-995e2080-b97f-11eb-84bf-b63849c54813.jpg)
![EMIP02723_Weiner435_006](https://user-images.githubusercontent.com/39619238/118996177-9c591100-b97f-11eb-8244-b01617d33ac2.jpg)
![EMIP02723_Weiner435_007](https://user-images.githubusercontent.com/39619238/118996185-9e22d480-b97f-11eb-890f-090c0c30efc6.jpg)
![EMIP02723_Weiner435_008](https://user-images.githubusercontent.com/39619238/118996210-a2e78880-b97f-11eb-9847-4d6a9e8dc956.jpg)
![EMIP02723_Weiner435_009](https://user-images.githubusercontent.com/39619238/118996232-a5e27900-b97f-11eb-996f-1daa8edb5507.jpg)

**Comment by smaugustine** [comment]
I would guess there's not an existing work file for it and that one should be created.

**Comment by Ralph-Lee-UK** [comment]
Thanks!
