### ISSUE TITLE
 manuscript BL add 19,343

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1753]
Dear all,
I have a question concerning the encoding of the manuscript BL add 19,343. It is an (almost) blank paper notebook (?) at the end of wich several documents (letters, notes) are bound/glued. Here is the link to the very brief description of this object by Wright (CCCIV): https://archive.org/details/catalogueofethio00brituoft/page/324/mode/2up
Here is the link to the digitized manuscript: http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_19343_fs001r
I would tend to encode this as a composite manuscript and to stay somewhere in the description that the notebook is basically used as a folder/container. What do you think? 
@PietroLiuzzo  @eu-genia  @DenisNosnitsin1970  @thea-m

**Comment by PietroLiuzzo** [comment]
interesting, I agree a composite ms description with `msPart` and `msFrag` would be fine. The above text could be added as a brief clarification in a paragraph.

**Comment by thea-m** [comment]
I think I would also go for the proposed composite manuscript solution with an explicit explanation in the record, it should be easily understandable then.

**Comment by DariaElagina** [comment]
Thank you, @PietroLiuzzo  and @thea-m !
