### ISSUE TITLE
New institution record for RIE 198

### ISSUE THREAD

**Issue by angelasalerno** [BetaMasaheft/Documentation#1755]
Dear all, 
I have a question concerning the inscription RIE 198. I was adding the reference about the repository of the inscription and I noticed that it is preserved in the Church of the Four Animals in Aksum. 
"Ce bassin en pierre se trouvait en 1906 dans la cour de l'église des Quatre
Animaux à Axoum. Il est actuellement dans un petit bâtiment dans l'enceinte
de cette église, scellé dans le sol."  
I wasn't able to find the correct reference to the precise place so I was wondering if any of you know where can I find it or if I need to create the record itself
Thanks to you all!

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @DariaElagina @thea-m @smaugustine

**Comment by DenisNosnitsin1970** [comment]
It looks like we do not have it, probably a new record is needed.

**Comment by angelasalerno** [comment]
Thank you, I'll create a new record.
