### ISSUE TITLE
Two work files for አኮኑ፡ ብእሲ፡??

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1756]
Two records for the work entitled "አኮኑ፡ ብእሲ፡" 
LIT3047RepCh327
LIT4274AkkonuB

The file for LIT4274AkkonuB is more complete, with the full text of an edition. 

The only location that I can find LIT3047RepCh327 referenced is 
https://betamasaheft.eu/manuscripts/BLorient651/main#p1
And the link to the image is here
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_651_f003v
This appears to be just the first verse of the more extended work.
Is there another reason why there might be two files, or should the two be connected? 

Any advice most welcome!

**Comment by thea-m** [comment]
oh, thank you! No, it's just an overseen doublet. I'll delete LIT3047RepCh327 and update the reference.
