### ISSUE TITLE
መጽሐፈ፡ ግጻዌ and the መጽሐፈ፡ አስልጢ፡

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1757]
In EMIP 2105 there is a relatively rare መጽሐፈ፡ አስልጢ፡ - in the Encyclopaedia Aethiopica this is discussed under the title መጽሐፈ፡ ግጻዌ፡ but as a more 'modest' version of the lectionary. Does the መጽሐፈ፡ አስልጢ፡ deserve a new work file? 

![EMIP02105_ICOR-Lehnus2_003](https://user-images.githubusercontent.com/39619238/120627084-38444b80-c45b-11eb-8b8c-46fca3bdb68b.jpg)
![EMIP02105_ICOR-Lehnus2_004](https://user-images.githubusercontent.com/39619238/120627087-39757880-c45b-11eb-8010-b759e3f4d7b8.jpg)
![EMIP02105_ICOR-Lehnus2_005](https://user-images.githubusercontent.com/39619238/120627088-39757880-c45b-11eb-94f6-7cff8a3b6e5c.jpg)

**Comment by thea-m** [comment]
I think so, and there is one already: https://betamasaheft.eu/works/LIT1917Mashaf/main
I've added the EAE transliteration to it now: https://github.com/BetaMasaheft/Works/pull/555

**Comment by Ralph-Lee-UK** [comment]
Thanks for clarifying!
