### ISSUE TITLE
Homily on abba Macarius

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1758]
In [BLorient767](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_767_fs001r) on f. 127r there is "A discourse on the life of Macarius by ʾabba Yāʿǝqob". I think there is no work record for it and I would like to create one.
@thea-m @DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I think you are right, there is no record for this work.
