### ISSUE TITLE
A work record for a monastic collection

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1759]
In [BLorient768](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_768_f001r) f. 3r there is a text which was published by Arras as [this](https://www.zotero.org/groups/358366/ethiostudies/search/arras/titleCreatorYear/items/ABTG4BHI/item-list). I'm requesting permission to create a work record for it, I was not able to trace it. I would suggest that the Latin title be retained as the main title. I enclose a fragment of EAe entry for reference. 
![Przechwytywanie](https://user-images.githubusercontent.com/62760230/121079966-1cce9d00-c7db-11eb-9f4a-3e33939878e5.JPG)

@thea-m @DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I could not find it either. It is strange, since we should have stubs for the texts indexed in EAE, but I could not check the Index...

**Comment by thea-m** [comment]
I agree. Clearly the Latin title led to a glitch in the index conversion. Please go ahead, thanks a lot!

**Comment by DenisNosnitsin1970** [comment]
Yes, it is not there, apparently. I would suggest that you include the Ethiopic title as the main one,  መጽሐፈ ዜናቲሆሙ ለአባዊና ቀዱሳን, which is there, please not Latin.
