### ISSUE TITLE
Transkribus for printed documents

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1761]
Dear all,

since I have received several requests concerning Transkribus, I want to clarify. Do we use Transkribus for manuscripts only? Or could we use it for printed texts as well? We have an ABBYY OCR for printed texts, which is however usable in the office only. 

Thanks a lot!

@PietroLiuzzo @thea-m @eu-genia @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
You can use the software to _transkribe_ anything. the model we made is only for ethiopic in general, so it can be used only for regions of images which contain solely or mainly that script. It could be used as basis to train a model able to include other languaes, as I would expect in printed texts. 
Please feel free to redirect any inquiry, I have gained quite some 'intelligence' of the software by now.
We have used it for example to get a text from Conti Rossini l'evangelo d'oro...

**Comment by DariaElagina** [comment]
Dear @PietroLiuzzo ,

thank you for the clarifications!
