### ISSUE TITLE
Doublets for Ibn aṭ-Ṭayyib 

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1763]
Dear All,

our DB, as apparently also the EAE Index, has three entries for the same person:
https://betamasaheft.eu/persons/PRS1345AbulFa/main
https://betamasaheft.eu/persons/PRS1342AbulFa/main
https://betamasaheft.eu/persons/PRS5503Ibnatt/main
I have checked the EAE, and I am pretty sure that this is the same person. But since the authors of the contributions are different, they used different forms of the name. I am working right now on the last one, and since all of them seem not to be referred to anywhere, I propose to delete the doublets in accordance with the GL and to list all the name variants in one entry.
Do you have any objections? @DenisNosnitsin1970  @thea-m  @eu-genia

**Comment by eu-genia** [comment]
You are right, thank you!

**Comment by DenisNosnitsin1970** [comment]
OK.
