### ISSUE TITLE
New work record for the list of heresies

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1764]
Dear all,

I want to create an entry for the list of heresies beginning (with some variations): ናሁ፡ ንጽሕፍ፡ አስማቲሆሙ፡ ለመናፍቃን፡ ሰባልዮስ፡ ይቤ፤ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ገጽ፡ ናሁ፡ ንቤ፡ ፫ቱ፡ ገጽ፡ ፩ራዕይ፡
It is attested in a number of manuscripts:
BL Orient 734, fol. 283r (N. 2): https://archive.org/details/catalogueofethio00brituoft/page/202/mode/2up
https://betamasaheft.eu/manuscripts/EMIP02072/main - ms_i6
https://betamasaheft.eu/manuscripts/EMIP00705/main - ms_i6
https://betamasaheft.eu/manuscripts/EMIP00699/main - ms_i1.2

As an addition in https://betamasaheft.eu/manuscripts/BLorient747/main

Any objections or ideas where I could find additional information on the text? @thea-m  @DenisNosnitsin1970  @eu-genia

**Comment by thea-m** [comment]
I think it corresponds to the enumeration of heresies at the beginning of the Mashafa mestir. Maybe you could double check? I just looked at the beginning in BNFet113. This list seems to be attested quite often independently (also as "unidentified" in ESma001), it would definitely be good to identify it and in any case create an ID.

**Comment by DariaElagina** [comment]
Thank you! You are right, it seems to be the same. I will create an independent record for it.
