### ISSUE TITLE
import XML from Berlin Library

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1766]
I am starting to encode this ms https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN863180108&PHYSID=PHYS_0013

I plan to call it BerOrOct59 is this ok?
All the existing Berlin mss are only called BerOr and are lacking the other specifications such as fol, quart or oct and so on

**Comment by eu-genia** [comment]
Yes, OK. Thank you. And welcome :)
(At some point when the existing stubs are enhanced by the descriptions we can rename them (also renaming the pointers of course).)

**Comment by eu-genia** [comment]
Speaking about this manuscript (and others from Berlin) - I guess their descriptions are in XML; I wonder if they can be in any way used before you start redoing the description from scratch @PietroLiuzzo

**Comment by SophiaD-M** [comment]
@vitagrazia81 for your information

**Comment by PietroLiuzzo** [comment]
the images can be linked with their iiif manifest, e.g. https://content.staatsbibliothek-berlin.de/dc/863180108/manifest
this can be found clincking on the small i under ubersicht.
the XML is mycore, as far as I can see.

**Comment by PietroLiuzzo** [comment]
@eu-genia @SophiaD-M @vitagrazia81 how many manuscripts from this repository? I would like to figure out if the mapping is worth it.

**Comment by SophiaD-M** [comment]
We just started and cannot say for sure. I guess for our project not more than 10 relevant mss.
But overall the Berlin collection is of course a huge one.

**Comment by eu-genia** [comment]
bm:Six1983VOHD4 lists 168 manuscripts (which we could also process for stubs in the same way we did for the Tanasee mss https://github.com/BetaMasaheft/Documentation/issues/1682)

**Comment by PietroLiuzzo** [comment]
then it is definitely worth it, yes. could you perhaps point me to a correct selection or a list from their website?

**Comment by eu-genia** [comment]
I made a search for alphabet="Äthiopisch" to get http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2Bcategory.top%3A%22IslamHS_class_00000064%5C%3ASKRI0021%22&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed

**Comment by eu-genia** [comment]
If I look for catalogue=Dillmann (bm:Dillmann1878Verzeichnis) and Äthiopisch I get http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2B%28mymss_ihs68%3ADillmann+mymss_ihs68shelfmark%3ADillmann%29+%2Bcategory.top%3A%22IslamHS_class_00000064%5C%3ASKRI0021%22&XSL.lastPage.SESSION=%2Fsearch_form_islamhs_advanced.xed&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed

**Comment by eu-genia** [comment]
if I look for catalogue="VOHD 20,4" (bm:Six1983VOHD4) I get http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2B%28mymss_ihs68%3A%28vohd+AND+20%2C4%29+mymss_ihs68shelfmark%3A%28vohd+AND+20%2C4%29%29+%2Bcategory.top%3A%22IslamHS_class_00000064%5C%3ASKRI0021%22&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed

**Comment by eu-genia** [comment]
If I look for catalogue ="VOHD 20,6" (bm:Six1994VOHD6) (plus Äthiopisch) I get http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2B%28mymss_ihs68%3A%28vohd+AND+20%2C6%29+mymss_ihs68shelfmark%3A%28vohd+AND+20%2C6%29%29+%2Bcategory.top%3A%22IslamHS_class_00000064%5C%3ASKRI0021%22&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed

**Comment by PietroLiuzzo** [comment]
so, none of these is a complete disambiguated list? with such a list of the myCore IDs, e.g. SBBMSBook_islamhs_00003197 I can get the process started. would anyone be able to put this together, please?

**Comment by eu-genia** [comment]
If we cannot get it from the search results above then I guess it can only be done by hand, copypasting IDs of over 600 records... Possibly not worth it...

**Comment by PietroLiuzzo** [comment]
Sorry, without knowledge of the holding I cannot be sure what list I am building from the searches, if any. 
The mycore XML is accessible and I can parse that, but I need to know what to parse and the searches do not tell me if the list is complete, if there are overlaps, etc. with a list of identifiers I can then set up a transformation, loop the identifiers get the mycore, transform what can be transformed to TEI and create stub records that way.

**Comment by eu-genia** [comment]
There are no overlaps; with the first search you get all, with the other searches you get selections by catalogue. I am now looking through the Dillmann search and putting it in the second sheet here https://docs.google.com/spreadsheets/d/1GHgMfgTLTVNwEJ7-DogUNgBTD5IntzMGaVT_6SU8rEY/edit?usp=sharing but am not sure that this is sensible.
I also see that they created a separate record for each msPart in case of composite MSS (plus the general record), making it all very confusing (see the list example for Ms. or. fol. 596)

**Comment by PietroLiuzzo** [comment]
the only thing I need is the first column eventually, for a basic parsing of their source XML.

**Comment by eu-genia** [comment]
there are 636 IDs for Ethiopic collection (not all are MSS, many are msParts), it would take quite long to copypaste them all by hand

**Comment by PietroLiuzzo** [comment]
I do not see much of an alternative. unless you are asking me to do HTML site scraping, which would take more or less the same time, just to me and with a different method, with higher rate of error due to ignorance of the contents on my side. 
I was looking for a list of results as XML/HTML non paginated which I was not able to find. I will keep looking all other information in the table which you started is also very valuable, and adding that to the info sourced from the website would make of this a mash up process of enrichment. if anyone is ready to help with this, I think all in all it will be better than starting each record from zero.

**Comment by eu-genia** [comment]
http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2Bcategory.top%3A%22IslamHS_class_00000064%5C%3ASKRI0021%22&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed is a list for all they have for Ethiopic collection; there are no overlaps but many MSS are described in  a set of records (linked by "relation"); I don't know how to get non-paginated results... I am simply going by catalogue as for me it is simpler

**Comment by eu-genia** [comment]
Ok I did what I could.
Many of the records are stubs with no additional information (except for folio number), but I did not differentiate.

**Comment by eu-genia** [comment]
(I marked where we already have a record or a stub on BM; in at least two cases which jumped to my eye the Berlin database gives wrong catalogue numbers, I give the correct one in the spreadsheet)

**Comment by PietroLiuzzo** [comment]
thanks! I will work through this asap, but likely not immediately, as this week is full already.

**Comment by eu-genia** [comment]
I was also wondering - should I try to add Berlin MyCore IDs also to the Tanasee stubs (already created)? makes sense or not? they are only stubs , no images, no descriptions except for the cat. number and folio number (http://orient-digital.staatsbibliothek-berlin.de/servlets/solr/select?q=%2BobjectType%3A%22islamhs%22+%2B%28mymss_ihs01%3Atanasee+mymss_ihs01text%3Atanasee+mymss_ihs01shelfmark%3Atanasee%29&XSL.lastPage.SESSION=%2Fsearch_form_islamhs_advanced.xed&fl=*&sort=mymss_ihsinvent+asc&rows=25&version=4.5&mask=search_form_islamhs_advanced.xed)

**Comment by PietroLiuzzo** [comment]
if we have nothing to gain from that, I am not sure it is worth it. I have the impression that they are also about to switch to another website

**Comment by eu-genia** [comment]
I have now compared the existing MSS and corrected all stubs to make them compliant with the schema; the records have all been committed.
some attention may be requested here: https://github.com/BetaMasaheft/Manuscripts/pull/1431
