### ISSUE TITLE
encoding of stubs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1767]
How can I encode the following quire structure (the six stubs in the middle)?
![image](https://user-images.githubusercontent.com/19650382/123094042-b8434d00-d42c-11eb-8f10-090df9b7c3aa.png)
Thank you :)
(Assigning everyone because the mentioning function currently doesn't work for me, I'm the official assignee)

**Comment by DenisNosnitsin1970** [comment]
Is it a deficient quire from which four (or another number of leaves) were lost?

**Comment by thea-m** [comment]
I don't think so - the text ends on the middle of 44va (but I have difficulty with the text and will probably create a new issue for its identification - but still, it doesn't look like missing material).

**Comment by eu-genia** [comment]
are these then true stubs or quire strengthening elements that should be described differently?

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/123783955-35f8d400-d8d7-11eb-9af7-646bd3d53e07.png)
(sorry for the bad quality)

**Comment by eu-genia** [comment]
is this all a protective quire?

**Comment by eu-genia** [comment]
IMHO our problem is that we treat protective quires as quires and part of collation, which often causes difficulties (according to Gumbert, protective quires are described with the binding, not collated - and also if they contain other texts these are, in Gumbert, not msParts etc.)

**Comment by thea-m** [comment]
I don't think so, there appears to be no discontinuity of text between f. 42 and 43.

**Comment by DenisNosnitsin1970** [comment]
If there is no loss of text and no leaves are missing, you can disregard the stubs and describe them under "condition". They may be just ("triple") guards, i.e. reinforcing elements, not true stubs (as Zhenja indicated above). In very many cases (more than one think) it is difficult or impossible to define if quire was meant as protective or not (I am preparing a small article on that topic).

**Comment by thea-m** [comment]
Thank you!
