### ISSUE TITLE
Prayer of Simeon Stylites - new work record?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1768]
In [BLorient578](http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_578_f001r) there is a text unit for which I cannot find work record.

F. 197 r አስተብቍዖት እንተ ዘስምዖን ዓምዳዊ i. e. prayers of Simeon Stylites.

It seems to be attested also in ESqds012 and ESdd002 but alas no work record there ... 

@DariaElagina @thea-m

**Comment by thea-m** [comment]
Interesting! I also found no existing work record/EAe entry for this and would suggest to create one.

**Comment by MarcinKrawczuk** [comment]
@thea-m Interesting indeed, especially since it seems there is even no record for Simeon himself! Good, I will kill two birds with one stone.
