### ISSUE TITLE
LIT5013Prayer additional mss

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1769]
I probably found an additional ms for this LIT5013Prayer.
I would suggest to offer the incipit of the prayer, and ideally more of a title then "prayer" (if we manage to find out more).
This is the second ms:
https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN863180108&PHYSID=PHYS_0175&DMDID=DMDLOG_0011
the text starts on fol. 82r.

**Comment by DariaElagina** [comment]
Thank you, @SophiaD-M ! I will take care of this!

**Comment by SophiaD-M** [comment]
cool, thank you
