### ISSUE TITLE
How to encode a <Locus>, when the folios are misplaced

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Documentation#1770]
Good morning to all. I am learning how to encode :-), working on the Ms. orient. oct. 1270. My question to you here is, how to encode when the folios of the text are misplaced. In my case the text is on: ff. 2ra-16vb, 19ra-24va.
I did:
````xml
<msItem xml:id="ms_i1">
  <locus from="2ra" to="16vb"/>
  <locus from="19ra" to="24va"/>
  <title ref="LIT1450GadlaG">Gadla Gabra Krǝstos</title>
</msItem>
````
Is that correct? Or how do you do?
Thank you and sorry if I will bother you, from now on, with my questions :-)
Vita

**Comment by PietroLiuzzo** [comment]
I think this is fine, and in line with [example 2 of the page of the guidelines](https://betamasaheft.eu/Guidelines/?id=manuscriptContents). Thanks, looks like a good start!

**Comment by vitagrazia81** [comment]
Thanks Pietro, for the reference of example 2 and encouragement :-)
