### ISSUE TITLE
New work record for Māmās hagiographic cycle and questions

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1773]
I guess we need records for
Gadla Māmās
Taʾammǝra Māmās
Malkǝʾa Māmās
(plus an overarching record for the set)
as in ESaqm002 and ESaqm001

I was also wondering about the commemorative Salam, in the record LIT4035SenkessarDL it is given a sub-id LIT4035SenkessarDL#Mask5Mamas - but the ID (this or for the other readings) is not used e.g. in DW03 or BAVet111 - are they the same?

I assume the Synaxary commemoration on 5 Maskaram (being a salam?) is different from the note for 5 Maskaram in the GS (e.g. ESum018)?

Is the GS vita different from the vita in ESaqm001/002?

@thea-m @DenisNosnitsin1970

**Comment by thea-m** [comment]
I agree that we need the record for the hagiographic dossier (and possibly for the individual gadl, miracle and Malkǝʾa, though they don't seem to be attested independently for now). It seems to be a different Māmās from the one commemorated in the Sənkəssār and the GS.
(There isn't yet a fully described manuscript of the "second recension" Sənkəssār public on BM, but the sub-IDs of LIT4035SenkessarDL are used in unmerged branches. There is a sub-ID for the commemoration, Mask5Mamas, and one for the salām, Mask5SalMamas. DW03 belongs to a different recension, BAVet111 had been encoded before the work record was elaborated. In any case, the Sənkəssār commemoration is different from the Acts of the GS (LIT1898Martyr).)

**Comment by DenisNosnitsin1970** [comment]
I can do Mamas, 
I read his Gald (probably there are two - an Ethiopian one (Tigray, Hagerhese and one ms from War'e Lekhe) and a foreing one).

**Comment by eu-genia** [comment]
Thank you :) Then I shall wait :)

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/578

**Comment by eu-genia** [comment]
Can you also check LIT4775GadlaMa / PRS6625Mammas?

**Comment by eu-genia** [comment]
AMQ001 also has as addition salām-hymn for ʾabbā Māmās

**Comment by DenisNosnitsin1970** [comment]
I do not know PRS6625Mammas, but he is dajjazmach, unrelated to St. Mamas.  AMQ-001 has a very faint writing in pensil that is classified as Sälam for Mammas, but with a great degree of uncertainity. I can  barely read a word, and I do not see the name of Mammas anywhere. Should I create a record anyway?

**Comment by eu-genia** [comment]
Sorry I meant PRS6626Mammas of course

**Comment by eu-genia** [comment]
If salam is unreadable then leave it of course

**Comment by DenisNosnitsin1970** [comment]
Can you please check/comment/merge?

**Comment by eu-genia** [comment]
were the doublets removed/merged?

**Comment by DenisNosnitsin1970** [comment]
I think they were.

**Comment by eu-genia** [comment]
This is the issue, the related PR has been merged I believe, long ago. What should I do?

**Comment by DenisNosnitsin1970** [comment]
OK, nothing. Sorry
