### ISSUE TITLE
retrieve PRS13448Gwaggul 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1774]
Dear @PietroLiuzzo , I wanted to create PRS13448Gwaggul, but my internet was too slow so that I received a time-out error before being able to download the file, which now however exists in the system. Could you kindly retrieve it so that it can be used?
I will try to only create new records on good internet days...

**Comment by PietroLiuzzo** [comment]
Dear @thea-m would this be enough to retrieve the file? https://betamasaheft.eu/PRS13448Gwaggul.xml

**Comment by thea-m** [comment]
Yes, thank you! For the future, is typing in this URL the only thing that needs to be done in such cases or was there some other action from your part?

**Comment by PietroLiuzzo** [comment]
The url formed with .xml will fetch whatever XML is currently in the DB with that identifier, so, in similar cases I think it does solve the issue. not to be confused with the enriched tei which can be obtained clicking the TEI-XML button or with https://betamasaheft.eu/tei/PRS13448Gwaggul.xml

**Comment by thea-m** [comment]
Cool, thank you!
