### ISSUE TITLE
Protective texts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1776]
I would like to create new work records for the prayers contained in RDW005 (according to https://github.com/BetaMasaheft/Documentation/issues/371, we create IDs for such texts - I think that these scrolls here are a good means to collect data and then see whether the encoding should be modified. My feeling still is that the recurring motifs in these texts are what the concept of narrative units is for, but let's come back to this later). 
You can see my description with incipits and explicits in the branch DR_21_06_RDW005 (note that some incipits contain the complete texts, I will move these to edition later).

**Comment by DenisNosnitsin1970** [comment]
Ok
