### ISSUE TITLE
BLorient764 f. 168r-172r - is a new work record necessary?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1778]
In BLorient764 f. 168r-172r there is a short text called ግብረ፡ አበው፡ ዘመነኮሳት፡ which appaers also in BLorient593 f. 126r-128r. Which is better: to create a new work record for it or to use its already existing ref as part of the collection?

Thank you!

@DariaElagina @thea-m @eu-genia

**Comment by DariaElagina** [comment]
In BLorient593 this text is encoded with an independent id (LIT2228Ruleso). Is the text in BLorient764 different from that one?

**Comment by MarcinKrawczuk** [comment]
They seem to be the same text. Thank you for the comment. But now after looking at the text of BLorient593 I am not really sure whether this attribution of ግብረ አበው መነኮሳት as the Rule of Pachomius is correct.

**Comment by DariaElagina** [comment]
The identification was done on the basis of the EAE article,Vol. III, Monastic literature, p. 996a, under Other Manuscripts, BLorinet593 is also listed. It might however be possible that there is some confusion in the article...
