### ISSUE TITLE
መልክእ hymn to Antony

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1779]
In BLorient577, f. 73r (not online) there is a መልክእ hymn to Antony. The incipit reads: በረድኤተ፡ ቅዱስ፡ መንፈስ፡ ኅጡአ፡ ህላዌ፡ እምተረክቦ።  I haven't been able to find it neither in the database nor in the "Répertoire...". Any help will be appreciated!

@thea-m @DariaElagina @smaugustine

**Comment by DariaElagina** [comment]
I could not find it either. If there are no objections from other participants, I would just propose to create a new entry.
