### ISSUE TITLE
Protective texts RDW007

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1783]
I would like to create new records for the two (?) protective texts in RDW007. You can find the complete transcription in the file, branch DR_21_07_RDW007 (folder HLC). I would also be grateful if you could have a look at the division into two prayers and see if you agree.
@DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I agree with your division, and with the creation of records (we might think of the creation of several general records though...). Thank you!

**Comment by thea-m** [comment]
Thank you! I'm also not completely happy with this ID creation frenzy, but this was decided in https://github.com/BetaMasaheft/Documentation/issues/371. I will go on for all the scrolls now, so as to have some data to work with, and then continue to think how this could be done better. I'm also thinking of either narrative units or the creation of keywords.
