### ISSUE TITLE
New work record for səbḥat laka prayer

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1790]
I cannot identify the following text attested in RDW-001 (probably incomplete at the beginning). The text that follows is LIT1191Baenta. I checked the Saʿātāt and other səbḥat laka texts I found in BM, but couldn't find these prayers anywhere.
@DariaElagina @DenisNosnitsin1970 
(sorry for the bad quality)
![image](https://user-images.githubusercontent.com/19650382/128376903-62432026-8cc2-4f26-8466-bbf9337128a1.png)
![image](https://user-images.githubusercontent.com/19650382/128377022-e0c5a81e-5a81-4278-b670-8ca96c50ec29.png)

**Comment by DariaElagina** [comment]
I could not find it either. It is also hard to read, maybe I could make another picture if I will go to the office soon

**Comment by thea-m** [comment]
Thank you! I will leave this open for a bit, maybe @DenisNosnitsin1970 might have an idea about the text.

**Comment by DenisNosnitsin1970** [comment]
Are images of somewhat better quality possible?

**Comment by DenisNosnitsin1970** [comment]
This would be helpful.

**Comment by thea-m** [comment]
The manuscript is in the office, I can take better images in two weeks.

**Comment by thea-m** [comment]
![image](https://user-images.githubusercontent.com/19650382/131521559-b8f9da03-b436-420c-a8ba-0355dec7e6e6.png)
![image](https://user-images.githubusercontent.com/19650382/131521639-ba2c66b4-1259-49b5-b7ae-eedb6772fc37.png)

**Comment by DenisNosnitsin1970** [comment]
Sorry, I do not recognize it. In the Sa'atat (edition), indeed, there is a portion with refrain ሰብሐት፡ ለከ but is dissimilar. If nothing fitting is recorded in Chaine, and nothing similar can be quickly noticed in the context of በእንተ ሥላሴከ (that follows), probably a new record is unavoidable.
