### ISSUE TITLE
New work record for Śərʿāta ʾaqqwāqwām

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1792]
I would like to create a new (general) record for an Amharic work called Śərʿata ʾaqqwāqwām in EMIP02076. Part of it is also attested in RDW-003 (which contains before this text a maṣḥafa Ziq), bad images below. The text in both manuscripts does not seem to be identical, but related. I would propose to create a general record and mention the variation in it. But maybe someone actually knows this text?
@DariaElagina @DenisNosnitsin1970 @karljonaskarlsson 
![image](https://user-images.githubusercontent.com/19650382/128714189-a812c324-ec20-41f4-8f1a-59b5d52ec1a6.png)
![image](https://user-images.githubusercontent.com/19650382/128714312-890c44e8-24ec-4189-88ca-a48f58f9d26d.png)
![image](https://user-images.githubusercontent.com/19650382/128714369-42e59d18-162c-4015-bd5e-fd10b1191b58.png)
![image](https://user-images.githubusercontent.com/19650382/128714434-1aa20de2-b36d-4324-a71a-25162a3ce387.png)

**Comment by karljonaskarlsson** [comment]
I also don't know the text, but Śərʿata ʾaqwāqwām seems to be a good term for the "family of texts".
