### ISSUE TITLE
New work record for mazmur hymn (?)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1793]
RDW-003 contains a text I cannot identify. It starts as a mazmur hymn to Yoḥannəs, identical in the beginning for example to what is called "Mazmur chants" in EMIP00497, but continues differently.
![image](https://user-images.githubusercontent.com/19650382/128715060-16b6ebfa-a2c2-4d5d-bf1e-2805df4ff409.png)
![image](https://user-images.githubusercontent.com/19650382/128715123-6a31d0d3-033b-474c-967c-409852e31313.png)
preceding is the text mentioned in #1792 
Maybe someone of you know more about this than me?
@DariaElagina @DenisNosnitsin1970 @karljonaskarlsson

**Comment by thea-m** [comment]
@karljonaskarlsson  suggests to describe this as "Dəggwa-type antiphons for the commemoration of St John the Baptist", without creating a CAe number (because they would probably need to be created for the single antiphons and we haven't worked on this yet). This proposal is fine for me.

**Comment by eu-genia** [comment]
Has an ID been created? @thea-m @DenisNosnitsin1970 ? Can this be closed?
