### ISSUE TITLE
Two Marian texts without [?] work records

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1795]
In [EMML 8897](https://w3id.org/vhmml/readingRoom/view/201642 ) (which in itself is quite close to [BLorient604](https://betamasaheft.eu/manuscripts/BLorient604/main)) there are two texts for which I do not find work records.

1) Fol. 10v-13r is a short account of Annunciation for which I cannot find any analogy
![EMML 8897 f  160 v](https://user-images.githubusercontent.com/62760230/128751902-8c4bde29-1689-4515-af50-5867822fb7aa.JPG)
![EMML 8897 f  10 v](https://user-images.githubusercontent.com/62760230/128751905-b30f9bc3-76de-41c4-9c55-ab2fa085938b.JPG)

2) Fol. 160v-165v is a homily by a rather mysterious "Yohannes bishop of Ethiopia" which seems to be related to EMML 1763 f. 233v-240v

I will appreciate any comments or suggestions.
@thea-m @DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I could not find them as well. I think that you might create records for them if others have no objections.
