### ISSUE TITLE
add narrative units to "Resource type" filter

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1796]
Would it be possible to also include narrative units among the item types of the resource type filter in the faceted search? I don't see any obvious reason against this, but of course there might be one I'm not aware of.

**Comment by PietroLiuzzo** [comment]
Dear @thea-m , thanks for spotting this error. I baked this deep into the index configuration file. It should be now fixed in the code, alas not yet in the live application.

**Comment by thea-m** [comment]
Thank you!
