### ISSUE TITLE
New work record for so-called School Chants

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1797]
I would like to create a new work record for the so-called school chants, as described as Velat 1966, pp. 218ff. (composed of Mastagābəʾ, ʾArbāʿt, ʾAryām, Śalast, Wəddāse Māryām and ʾAnqaṣa bərhān). They are contained for example in Balk 003, but also in several EMIP records (https://betamasaheft.eu/facet.html?query=%22school+chants%22). The sequence of works composing them does not seem to be completely fixed, but I think that a normal collection record with textparts and relations to the independent records of the concerned works would work well. What do you think? 
@DariaElagina @DenisNosnitsin1970 @karljonaskarlsson

**Comment by karljonaskarlsson** [comment]
I think it's a good idea. And one could add the Amharic title, _ya-qāl tǝmhǝrt_, sometimes quoted as _ya-mātā tǝmhǝrt_. I think that they are normally also a subpart of the Mǝʿrāf — does that influence how they ought to be encoded?

**Comment by DariaElagina** [comment]
Thank you, it is great! I think that a relation to Mǝʿrāf should suffice also.
