### ISSUE TITLE
doublet LIT3186Meeraf

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1798]
https://betamasaheft.eu/works/LIT3186Meeraf/main gets the error message 

> Something has gone wrong and there are more than one item with id LIT3186Meeraf.
> 
> /db/apps/BetMasData/works/3001-4000/LIT3186Meeraf.xml
> /db/apps/BetMasData/works/new/LIT3186Meeraf.xml

It is not present in the new folder anymore, as far as I can see. If this is an issue I could fix myself, please let me know. Thank you!

**Comment by PietroLiuzzo** [comment]
sorry for the inconvenience! no, the file has not been deleted in the db, to which you do not have access, I have to fix this sort of things. Thanks for letting me know!

**Comment by thea-m** [comment]
Thank you!
