### ISSUE TITLE
Encoding indications for reading

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1804]
Sorry to create a new issue before my previous one has been addressed, but this has been bothering me for some time. It is very common in homiliaries or hagiographic collections to find at the beginning of the individual texts indications telling on which day or holiday the text should be read (example below).

So far in my practice I have seen these encoded in at least three ways:
1) To incorporate them into the {title} of the work
2) To use a {note} in the {msItem} 
3) To group them together in {additions}, this I must say I don't like, but that's how it is done e. g. in Hammerschmidt/Six catalogues

Is there any recommended way of dealing with them or is it at the discretion of the cataloguer?
@thea-m @DariaElagina @eu-genia @DenisNosnitsin1970 
![Przechwytywanie](https://user-images.githubusercontent.com/62760230/132130574-fddd1445-e225-4761-a367-e3a37b7130d7.JPG)

**Comment by thea-m** [comment]
It is a very good question, that we never addressed in a quite satisfactory way. My inclination would be to encode them as extras, which gives space for a free description and ensures that they are not confused with additions.
(This should be part of https://github.com/BetaMasaheft/guidelines/issues/42, which I am completely responsible for not having dealt with yet, but haven't forgotten)

**Comment by DenisNosnitsin1970** [comment]
I used to pack them in Extras.

**Comment by eu-genia** [comment]
I believe we encode this as Extras of the type FindingAid
