### ISSUE TITLE
Pointers to Zotero Bibliography failing to find their entry

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1807]
Dear all below is a list of pointers present in the data into `t:ptr/@target` for which no information can be found in EthioStudies Group library. The table is organized by wrong pointer and lists the files where this occurs, the information is the same. The data is the one of today, and I have not seen commits. Some can be grouped out as known issues, but others make me wonder what is going on...

pointers | info file
-- | --
bm:Solomon2015Geography | LOC6136Waj LOC6144Wagara LOC5597Sawa LOC6401Zabid LOC4732Mazaga LOC5486Salawa LOC2488Damot LOC3921Ifat LOC3061Fataga LOC1022Abbay LOC2019Bur LOC2614Debarw LOC2255DabraD LOC2582Dawaro LOC1095Adal LOC1743Bale LOC6872Islands LOC6868mountains LOC6844Arafta LOC6866lowland LOC6870plains LOC6871seas LOC6867highland INS0341DL INS0105DD
bm:Isaac1984Jerusalem | INS0355Jer
bm:Kur1968Samuel | LIT1496GadlaS PRS8485Samuel
bm:Nosnistin2014Yasay | LIT1513GadlaY PRS10253Yasay
bm:vvvv | LIT1470GadlaL
bm:ContiRossini1910TaklaHaymanot | LIT1405GadlaA
bm:Zurmoond2007NagaraM | LIT2052Nagara LIT5872NagaraMGen LIT5873NagaraMBE
bm:Cowley1998Exeget | LIT2314senafe
bm:Getachew2006EstifanosT | LIT1437Gadlae
bm:Samharay1928SanctiMarci | LIT1102Anapho BAVet95
bm:CANT1 | LIT2189Preach LIT4849Martyr LIT4847Actsof LIT4846Actsof LIT4848Actsof LIT3542Martyr LIT1020Actsof
bm:Witakowska2006Ethiopicuniversal | LIT4723TarikaWaldaAmid
bm:Worrell1886Zauberwesen | LIT4561Salot LIT1763Legend
bm:Cerulli1963Maria | LIT3917Miracle LIT6030MMMonkGen
bm:Guidi1899Galawdewos | LIT3122Galaw PRS4428Galawdew
bm:bm:GrebTiss1935Codices | LIT3053RepCh333
bm:CPG | LIT2265salota
bm:bm:Bausi2016Constantine | LIT6258Alexandrinians LIT6259Arius
bm:Getachew1992Mariology | LIT6373CanonAgreement
bm:Tedeschi1994IyasusMoas | LIT1467GadlaI
bm:Hayon2003Baqadami | LIT1198Baqada
bm:bm:2007ScholzMagi | AT1039Magi
bm:Chernestsov2005Eleniyohannes | PRS3708eleni
bm:TekleSadik1984Hailu | PRS2335BaedaM
bm:Fiaccadori2003EllaSaham | PRS3734ellasah
bm:Hussein2001Islam | PRS1585AkalaWa
bm:Rubinkowska2003AsfaWasan | PRS2112AsfaWas
bm:Crummey2005Garad | PRS4507GaradKe
bm:Red2010Ruppell | PRS8249Ruppell FSUor42
bm:Dege2010Tewoflos | PRS9451Tewoflos
bm:Beckingham1961PresterJohn | PRS1778Alvares
bm:Nosnistin2007Lamlam | PRS6160Lamlam
bm:Bertrand2000Halevy | PRS5012Halevy
bm:Yared1957Manan | PRS6642MananAs PRS6563Makwanne
bm:Nosnitsin2007Keflo | PRS5929Keflo
bm:Nosnitsin2010RosNabiyat | PRS8212RosNabi
bm:Fiaccadori2005Wazena | PRS10097Wazena
bm:Nosnistin2014YaebikaEgzi | PRS10190Yaebik
bm:Taddesse1979Abbots | PRS10531Zaiyas
bm:Chernestsov200Faris | PRS11813Faris
bm:Ancel201Yeshaq | PRS10350Yeshaq
bm:Mahoney2005HaylaMary | PRS5215haylaMa
bm:Hailu1981Tigrinya | PRS4253GabraIy
bm:Coppet1930ChrMenelik | PRS7006Menilek
bm:Cerulli1969Alexis | BLadd16198
I-XIII) For comparable texts see  e.g.  Fries 1893  Worrel 1909  1910  1914-15  Dobberahn 1976  Burtea 2001 | KopCodEtiopAdd22
Mäṣḥafä dǝggwa 1987 | KopCodEtiopAdd25
I) The text on fols. 4ra-24va corresponds to MQ  Śǝrˁatä qǝddase  ch. III and ch. IV  §30 followed by the Nicaean Creed (it preceeds Qǝddase śälästu mǝˀǝt in MQ) | KopCodEtiopAdd27
the text on fol. 24ra-va corresponds to Śǝrˁatä qǝddase  ch. IV  §§53-61. For the translation  see the corresponding parts in Daoud 1954 | KopCodEtiopAdd27
II) See the Anaphoras in MQ (t.)  Daoud 1954 (tr.). For a summary of the scholarly editions of Ethiopic Anaphoras  see Habtemichael Kidane 2003. In Text II-1 the passage with the reference to the Mäṣḥafä kidan is missing (its beginning corresponds to MQ  Qǝddase ˀƎgziˀǝnä  §2) | KopCodEtiopAdd27
IV) MQ  Ṣälotä kidan (t.)  Daoud 1954:247-252 (tr.) | KopCodEtiopAdd27
Velat 1966a:1-6 (t.) Velat 1966b:170-174 (tr.) | KopCodEtiopAdd27 KopCodEtiopAdd13
V) Cp. supplications in MQ  pp. 267-295 (t.) | KopCodEtiopAdd27
Velat 1966a:7-29 (t.)  Velat 1966b:175-209 (tr.). | KopCodEtiopAdd27
I) Some sections of the text correspond to the passages in the edition Mäṣḥafä säˁatat 1959 EC. | KopCodEtiopAdd7
I-3) Cleave 1951 | KopCodEtiopAdd1 KopCodEtiopAdd5 KopCodEtiopAdd11 KopCodEtiopAdd4 KopCodEtiopAdd26 KopCodEtiopAdd6
I-4) Fries 1892 (t.)  Velat 1966a:76-91 (t.)  Velat 1966b:284-296 (tr.)  Budge 1933:279-296 (tr.) | KopCodEtiopAdd1 KopCodEtiopAdd11 KopCodEtiopAdd4 KopCodEtiopAdd26 KopCodEtiopAdd6
I-5) Velat 1966a:69-75 (t.)  Velat 1966b:279-283 (tr.)  Lash 1972  1973 (tr.) | KopCodEtiopAdd1 KopCodEtiopAdd11 KopCodEtiopAdd4 KopCodEtiopAdd26 KopCodEtiopAdd6
cp. Grohmann 1919:383-394. | KopCodEtiopAdd1 KopCodEtiopAdd11 KopCodEtiopAdd4 KopCodEtiopAdd26 KopCodEtiopAdd6
I) Wechsler 2005 | KopCodEtiopAdd8 KopCodEtiopAdd24
I) Partly similar to Mäṣḥafä sǝnä fǝṭrät 1957 EC (but dissimilar to the text published in Getatchew Haile – Misrak Amare 1991) | KopCodEtiopAdd10
bm:Edele1995Genesis | BNFabb22 BNFabb148
I-III) For comparable texts  see  e.g.  Worrel 1909  1910  1914-15  Dobberahn 1976  Burtea 2001 | KopCodEtiopAdd20
I-4) Fries 1892 (t.)  Velat 1966a:76-91 (t.)  Velat 1966b:284-296 (tr.)  Budge 1933:279-296 (tr.). | KopCodEtiopAdd5
I) Budge 1906  Gädlä Täklä Haymanot 1973 EC | KopCodEtiopAdd3
II) Cp. Budge 1906. | KopCodEtiopAdd3
J.D. Zunner and N.W. Helwig | KopOS-2015-1Mus
I) Basset 1895:30-47(tr.)  Grébaut 1935  Ṣälotä ˀǝgziˀǝtǝnä 1949 EC. | KopCodEtiopAdd16
bm:Valieva2016GL | BLorient718
I-IV) For comparable texts see  e.g.  Fries 1893  Worrel 1909  1910  1914-15  Dobberahn 1976  Burtea 2001. | KopCodEtiopAdd21
I) Cp. Budge 1929 (tr.)  Euringer 1940  esp. nos. VIIA-XIIIG | KopCodEtiopAdd18
II) Cp. Fusella 1994:363-367 (tr.). | KopCodEtiopAdd18
I) Bachmann 1893 | KopCodEtiopAdd2
II) Mäṣaḥǝftä Sälomon wä-Sirak 1988 EC  3-85 | KopCodEtiopAdd2
III) Mäṣaḥǝftä Sälomon wä-Sirak 1988 EC  87-104 | KopCodEtiopAdd2
IV) Mercer 1931 | KopCodEtiopAdd2
V) Dillmann 1894:118-152 | KopCodEtiopAdd2
VI) Cleave 1951 | KopCodEtiopAdd2
I) Guidi 1895 | KopCodEtiop1
van den Oudenrijn 1939 | KopCodEtiop1
II) Cerulli 1969 | KopCodEtiop1
I) Cp. Budge 1929  Euringer 1940  esp. nos. VIIA-XIIIG | KopCodEtiopAdd17
II) Cp. Fusella 1994  363-367. | KopCodEtiopAdd17
III) MQ  Ṣälotä kidan (t.)  Daoud 1954:247-252 (tr.) | KopCodEtiopAdd13
IV) Cp.Velat 1966a:14-29 | KopCodEtiopAdd13
Velat 1966b:198-209 | KopCodEtiopAdd13
VI) The text starts with the admonition “If there be anyone any one…” (MQ  Śǝrˁatä qǝddase  ch. III  §3) and ends witha portion of ˀAmaknǝyo zä-ḥawaryat  The Creed of the Apostles (fol. 79r-v | KopCodEtiopAdd13
MQ  Śǝrˁatä qǝddase  ch. IV  §§31-40) followed by a portion of the ˀAmaknǝyo zä-śälästu mǝˀǝt  The Nicaean Creed (fol. 80r-v | KopCodEtiopAdd13
MQ  Qǝddase śälästu mǝˀǝt  §§ 4-10). | KopCodEtiopAdd13
bm:bm:Kolmodin1915TraditionsV | BNFabb152
bm:Dillmann1861VetTestHat | BNFabb197
I-X) For comparable texts see  e.g.  Fries 1893  Worrel 1909  1910  1914-15  Dobberahn 1976  Burtea 2001. | KopCodEtiopAdd23
I-IV) For comparable texts  see  e.g.  Fries 1893  Worrel 1909  1910  1914-15  Dobberahn 1976  Burtea 2001 | KopCodEtiopAdd19
III-5) Mälkǝˀa gubaˁe 1959 EC  291-294 | KopCodEtiop2
III-6) Mälkǝˀa gubaˁe 1959 EC  735-748 | KopCodEtiop2
III-8) Printed in Ludolf 1702:174 (Lib. VII  Cap. 3) | KopCodEtiop2
III-9) Printed in Ludolf 1702:170 (Lib. VII  Cap. 2)  171 (Lib. VII  Cap. 2.3.) | KopCodEtiop2
III-10) The second canticle on fol. 85r is printed in Ludolf 1702:169 (Lib. VII  Cap. 1.2) | KopCodEtiop2
I) Mälkǝˀa gubaˀe 1959 EC  757-777  Tedros Abraha 2005 (tr.) | KopCodEtiopAdd15
II) Mälkǝˀa gubaˀe 1959 EC  736-756. | KopCodEtiopAdd15
I) Säyfä śǝllase 1947 | KopCodEtiopAdd12
bm:RIE3A | RIE269 RIE277
bm:2016Galawdewos | BDLbruce88
bm:Leroy1968NAG | AG00002 AG00001
bm:Kur1972MK | MasKa003
bm:Lusini2005EAEDersana | ESbmqm003
bm:Nosnitsin2013Stephanite | RNBdorn612
bm:Gusarova2015ManuscriptsPetersburg | RNBdorn613
bm:Ludolf1684NewHistoire | STU0001Commentarius
bm:Thenevot1672Relations | STU0001Commentarius
bm:Allacci1648Symmikton | STU0001Commentarius
bm:Alvarez | STU0001Commentarius
bm:Brerewood679Scrutinium | STU0001Commentarius
bm:Godinho1615Abissinorum | STU0001Commentarius
bm:Telesius1660Historia | STU0001Commentarius
bm:Brerewoo1679Scrutinium | STU0001Commentarius
bm:Botero1600Relationes3 | STU0001Commentarius
bm:Kircher1636Podromus | STU0001Commentarius
bm:Colomies11688Observationes | STU0001Commentarius
bm:Alvares | STU0001Commentarius
bm:Rossigno2010TaklaHaymanot | PRS12300TaklaHaymanot
bm:MeckelburgundSolomon2017Antislavery | LIT5065Antislaveryprotocol
bm:Wion2016Control | LIT5405GebraHagar

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @thea-m @DariaElagina @FrancescaPanini

**Comment by eu-genia** [comment]
Many are the result of typos/inaccuracies and can be easily fixed (more later)

bm:Nosnistin2014Yasay ---> bm:Nosnitsin2014EnAeYasay
bm:Isaac1984Jerusalem ---> bm:Isaac1984Shelflist
bm:Zurmoond2007NagaraM ---> bm:Zuurmond2007NagaraM
bm:Getachew2006EstifanosT ---> bm:Getatchew2006EstifanosT
bm:Rossigno2010TaklaHaymanot ---> bm:Rossignol2010EAETaklaH
bm:Cowley1998Exeget ---> bm:Cowley1988Exeget
bm:Samharay1928SanctiMarci ---> bm:Semharay1928SanctiMarci
bm:CANT1 ---> bm:CANT
bm:Cerulli1963Maria ---> bm:Cerulli1943Maria
bm:Guidi1899Galawdewos ---> bm:Guidi1902Galawdewos
bm:bm:GrebTiss1935Codices ---> bm:GrebTiss1935Codices

**Comment by DenisNosnitsin1970** [comment]
There are various problems. I noticed double tags, tags wrongly spelled or tags completely different in Zotero, or tags without entries in Zotero, or also tag included another kind of mistakes.

**Comment by DenisNosnitsin1970** [comment]
Tag:bm:Kircher1636Podromus > bm:Kircher1636Podromus (I would do Prodromus)

**Comment by eu-genia** [comment]
Let us leave out for now the tags used in Commentarius. I think there is some data in the air there, I had corrected those tags but maybe there is some branch unmerged.

**Comment by DenisNosnitsin1970** [comment]
ok. what should be done with those above?

**Comment by DenisNosnitsin1970** [comment]
Correct one by one?

**Comment by FrancescaPanini** [comment]
Hi,
I haven't created tags in years (the ones I created are from before you had
established clear rules about them so they might well not reflect them),
not sure what I am suppose to contribute to the discussion.

Regards

**Comment by PietroLiuzzo** [comment]
given a list as the one produced above by @eu-genia I can make the substitutions in the files programmatically so they do not need to be updated one by one. 

if instead the error is in Zotero, you will have to fix it there and consequently correct the records affected in BM. I think perhaps @eu-genia and I can take care of these clean up. There are not many.

**Comment by eu-genia** [comment]
bm:CPG ---> bm:CPG1
bm:Getachew1992Mariology ---> bm:Getatchew1992Mariology
bm:Tedeschi1994IyasusMoas ---> bm:Tedeschi1994IyasusMoa
bm:bm:2007ScholzMagi ---> bm:2007ScholzMagi
bm:Chernestsov2005Eleniyohannes ---> bm:Chernetsov2005Eleni
bm:TekleSadik1984Hailu ---> bm:TekleSadik1984Hailu (_I don't see the problem in the tag; ideally, the tag should be corrected both in Zotero and in the data to bm:TekleSadik1989Hailu since the year is 1989, there was an error in Zotero_)
bm:Fiaccadori2003EllaSaham ---> bm:Fiaccadori2005EllaSaham
bm:Beckingham1961PresterJohn ---> bm:BeckHunt1961PresterJohn
bm:Nosnistin2007Lamlam ---> bm:Nosnitsin2007Lamlam
bm:Bertrand2000Halevy ---> bm:Hirsch2000Halevy
bm:Fiaccadori2005Wazena ---> bm:Fiaccadori2014Wazena
bm:Nosnistin2014YaebikaEgzi ---> bm:Nosnitsin2014YaebikaEgzi
bm:Taddesse1979Abbots ---> bm:Taddesse1970Abbots
bm:Chernestsov200Faris ---> bm:Chernestsov2005Faris
bm:Ancel201Yeshaq ---> bm:Ancel2014Yeshaq
bm:Mahoney2005HaylaMary ---> bm:Mahoney2005HaylaMaryam
bm:Hailu1981Tigrinya
bm:Cerulli1969Alexis ---> bm:Cerulli1969AlexisT
bm:Valieva2016GL ---> bm:Valieva2017GL
bm:bm:Kolmodin1915TraditionsV ---> bm:Kolmodin1915TraditionsV
bm:Dillmann1861VetTestHat ---> bm:Dillmann1861VetTest
bm:RIE3A ---> bm:BernandRIEIIIA
bm:2016Galawdewos ---> bm:Solomon2016Galawdewos
bm:Kur1972MK ---> bm:Kur1972MarhaKrestos
bm:Lusini2005EAEDersana ---> bm:Lusini2005EAEDersanaM
bm:Nosnitsin2013Stephanite ---> bm:Nosnitsin2014Stephanite 
bm:Rossigno2010TaklaHaymanot ---> bm:Rossignol2010EAETaklaH
bm:MeckelburgundSolomon2017Antislavery ---> bm:MeckelburgSolomon2017Antislavery


bm:Hayon2003Baqadami / bm:Hussein2001Islam / bm:Rubinkowska2003AsfaWasan / bm:Crummey2005Garad / bm:Red2010Ruppell  / bm:Dege2010Tewoflos / bm:Yared1957Manan / bm:Nosnitsin2007Keflo / bm:Nosnitsin2010RosNabiyat / bm:Coppet1930ChrMenelik / bm:Leroy1968NAG / bm:Gusarova2015ManuscriptsPetersburg / bm:Wion2016Control - fixed (tag or title was missing in Zotero)


I did not touch STU0001Commentarius 

I did not touch KopCodEtiop MSS as these are very dirty - result of automated conversion, never actually adjusted, I suggest that the bibl tags there are removed and bibliography stays as plain text until we get to fixing the descriptions

**Comment by eu-genia** [comment]
Many of the tags were inserted by Solomon, who invented them but never created a Zotero record. I managed to recover most of the data but I don't know what bm:Solomon2015Geography stands for, @sologebre please check and create a (clean) record if possible, or let me know the reference.
In general tags in the XML records should better never be typed but copy pasted from Zotero; this would help us avoid most of such problems in the future.
Thank you!

**Comment by DenisNosnitsin1970** [comment]
Thanks!

**Comment by sologebre** [comment]
Dear Eugenia,
bm:Solomon2015Geography refers to my article "The Chronicle of Emperor Gälawdewos (1540-1559): a source on Ethiopia's mediaeval historical geography". But the tag in Zotero now is bm:Solomon2015Galawdewos.

**Comment by PietroLiuzzo** [comment]
bm:Edele1995Genesis ?

**Comment by PietroLiuzzo** [comment]
I think I have fixed all instances, including Kop and Studies. The only remaining issue is with [bm:Edele1995Genesis](https://betamasaheft.eu/bibliography?pointer=bm%3AEdele1995Genesis&collection=all) In Zotero I cannot find this, so perhaps it just needs a record there @eu-genia ?

**Comment by eu-genia** [comment]
You are right, have overseen that one, record created.

**Comment by PietroLiuzzo** [comment]
thanks! I think we are done here, then.
