### ISSUE TITLE
iiif.xqm to suppor better reconstructed sequences of image regions (Ham, Dabra Libanos, Golden Gospel)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1815]
@MarcinKrawczuk noticed that the images for DabraLibanosHamGG1 don't appear: https://betamasaheft.eu/manuscripts/DabraLibanosHamGG1/viewer
Thank you!

**Comment by PietroLiuzzo** [comment]
Thanks for pointing this out. It is a known issue of the current application, which has been already solved for the forthcoming release, namely the fact that included parts of an XML part are only considered in postprocess, thus not allowing the included information in `<facsimile>`s elements to be accessible to the scripts, in this case the iiif.xqm module building the manifest. I have patched this pasting the facsimiles in and the manifests are produced correctly. However, a different issue came to the surface, related to the images which I am trying to clarify now. The result at the moment for you is probably the same as before.

**Comment by PietroLiuzzo** [comment]
(at the moment only images 4 and 5 of the 1975 set are visible)

**Comment by thea-m** [comment]
Thank you!

**Comment by PietroLiuzzo** [comment]
now all images are visible, except the reconstructed set, which is only documented in the XML.
