### ISSUE TITLE
delete LIT1656Homily and LIT1796Lifeof

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1818]
From https://github.com/BetaMasaheft/Works/pull/618
@MarcinKrawczuk wrote:

> I would suggest to delete LIT1656Homily and LIT1796Lifeof, quite possible it's the same text and the records are not used, so they just create confusion.

I agree with the deletion of LIT1796Lifeof. LIT1656Homily  is listed in the EAe as part of the Maṣḥafa ḫədār in BnF Abbadie 92 - I'm not sure whether that's the same text as the one included in the Gadla samāʿtāt?

**Comment by MarcinKrawczuk** [comment]
Yes, it's the same text. It has four attestations according to Prof. Bausi's list, namely BLorient686, BNFabb92, EMML1479 and EMML1844
