### ISSUE TITLE
New work records fortexts in Abb 39

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1821]
I want to create an entry for Sewasew in Abbadie 39 (in Gallica), a version which is probably older than others.
I could not find any other ms recorded in BM that would contain the same sewasew. For at least some of the tergwame-commentaries in Geez for OT books in this Ms. I will also need new separate records, most of thems do not seem to exist in the database.  Any objections?

**Comment by DariaElagina** [comment]
I think it should be decided if we want to create different entries for different versions. If I am not mistaken, the texts are very heterogeneous in any case. Are the commentaries part of Sawasew?

**Comment by DenisNosnitsin1970** [comment]
The commentaries are not part of Sewasew.  You are right concerning different versions of Sewasew, I can keep doing with one general record.

**Comment by eu-genia** [comment]
is this solved? @DenisNosnitsin1970 please close if yes
