### ISSUE TITLE
New work record for Amharic theological work

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1825]
BDLaethg34 contains an Amharic theological treatise (ff. 9r-36v), mostly a compilation of biblical and patristic excerpts on the nature and life of Christ. I could not identify this work - if you can't either, I would suggest to create a new record. 
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ እግዚአብሔር፡ እምቅድመ፡ ዓለማት፡ በሐንድነት፡ በሶስትነት፡ እንደነበረ፡ ነአምናለን፡ ለሐንደነቱና፡ ለሶስትነቱ፨ መላእክት፡ ቅዱስ፡ ቅዱስ፡ ቅዱስ፡ እግዚአብሔር፡ ጸባኦት፡ ፍጹም፡ ምሉዕ፡ ሰማያተ፡ ወምድረ፡ ቅድስት፡ ስብሐቲከ፨ ተናገሩ፡ ብሎ፡ ኢሳይስኒ፡ እንዳለ፨ ወንጌልም፡ እንዘ፡ ታጠምቅዎሙ፡ በሉ፡ በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ እንዳለ፨
Explicit:   ኃጥኣንም፡ እንደ፡ ሰይጣናት፡ ጸለምተው፡ እንደ፡ ጽላት፡ ጠቍረው፡ ይነሣሉ፡ ያነግዜ፡ ክርስቶስ፨ ጻድቃንን፨ ንዑ፡ ኀቤየ፡ ቡሩካኑ፡ ለአቡየ፡ ብሎ፡ መንግሥተ፡ ሰማያት፡ ያምርስቸዋል፨ ኃጥአንን፡ ሑሩ፡ እምኔየ፡ ርጉማን፡ ብሎ፡ ከዘለዓለም፡ እስት፡ ያሰናብታቸዋል፨ ከመዝ፡ እምነትነ፡ ወሃይማኖትነ፡ውእቱ፨

@MassimoVilla

**Comment by thea-m** [comment]
@MassimoVilla do you think you might have a chance to look at this?

**Comment by MassimoVilla** [comment]
Dear Thea, sotty for my belated reply. I've given a look at the text and tried to compare it with some Amharic texts transmitted in the Ethio-SPaRe MSS, but my search was unsuccessful. The excerpts are possibly taken from the Hāymānota ʾabaw, like other similar Ethiopic or Amharic treatises, but the text does not correspond to any one I know. So, I think the best option is to create a new record.
