### ISSUE TITLE
Images not showing in 'viewer'

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#1829]
The images for this entry show when clicked on in the 'main' page but there are no images in the 'viewer' page

Can you help?

https://betamasaheft.eu/manuscripts/EMIP02033/viewer

**Comment by PietroLiuzzo** [comment]
now the images are visible. I could isolate the bit causing the issue to line 102 but I have not yet understood why it causes the issue. For the moment I have simply commented it out in the db to avoid the issue reported here while I try to figure out why it is breaking the manifest production script.

**Comment by PietroLiuzzo** [comment]
I have patched the locus module to avoid this issue
