### ISSUE TITLE
Typo in EMIP Weiner Arabic mss?

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1830]
I think there are typos in the EMIP Weiner Arabic mss - "Moon faces" instead of "moon phases", like here: https://betamasaheft.eu/manuscripts/EMIP00567/main

The BM search reveals more entries however. 

I am just asking to make sure its a typo and not lots of drawings of moon faces. 

Sorry to assignees - I am also not sure who is responsible for these entries.

**Comment by PietroLiuzzo** [comment]
Thanks! Everyone can fix these, you too. Simply make a branch, do the
changes and submit a pr. If you do not feel comfortable no worries I will
do it ASAP.

SophiaD-M ***@***.***> schrieb am Fr., 5. Nov. 2021, 14:36:

**Comment by thea-m** [comment]
I'm sure you're right, but since there are no images available we can't actually check. Maybe @Ralph-Lee-UK can help?

**Comment by SophiaD-M** [comment]
@PietroLiuzzo  well I could fix it, I just would really like to hear from someone of the EMIP team that this is indeed a typo. Let us hear what @Ralph-Lee-UK can add. Unfortunately I also do not know who the other EMIP people are.

**Comment by eu-genia** [comment]
I think the watermarks show moon faces not phases

![image](https://user-images.githubusercontent.com/17987728/169528005-57e8e9c0-613b-4dbe-98e7-59f06aa3b7a4.png)
