### ISSUE TITLE
ʾabuna Həryāqos identification

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1834]
The name mentioned in supplications throughout the synaxary BLorient670 is ʾAbuna Həryāqos. I wonder if he might be identified with the eccage of the same name who was active in the second half of the 17th century. Wright dates the manuscript to the first half of the 17th century.  The manuscript is from Maqdala. 
A later note on f. 119v mentions eccage Tasfā (?)
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_670_fs001r
What do you think?
@DenisNosnitsin1970 @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
Possible; on f. 118v starts a malk' for him (added later?), where in the beginning he is called kahena la-dabra libanos. Maybe in the poem there will be more explicit indications. If the text is added later, the eccege name (f. 19rb) might be also different.

**Comment by thea-m** [comment]
I think that the poem refers to the abbot, there are several allusions to Takla Hāymānot, his priesthood and the other abbots of Dabra Libānos. I will cautiously identify ʾAbuna Həryāqos with him (not creating a new record, but marking the uncertainty). Thank you!
