### ISSUE TITLE
BL shelfmark inconsistencies

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1835]
As pointed out by @SophiaD-M , there is some inconsistency in our data regarding the shelfmarks of the Additional and Oriental collection manuscripts at the British Library (which can be well noticed here when scrolling down to the British Library https://betamasaheft.eu/manuscripts/browse). 
I am standardising these in the branch DR_21_11_Shelfmarks, but it might make sense to make sure that we agree on one version. This is quite important, because our priority is that manuscripts can be found easily, and people also expect correct and quotable shelfmarks in the titles of our manuscript pages.
We currently mostly use:

- Add. (with variation Additional): BL Add. 16,185 (also variation in the presence of the comma, with variation BL Add. 16185) - the British library uses "Add MS 16185" on the website; Wright has "Add. 16,185".
- Oriental (with variation Orient.): BL Oriental 627 - the British Library uses "Or 627" on the website; Wright has "Orient. 627".

Shall I go on standardising according to these examples (BL Add. 16,223; BL Oriental 627)? Or is any of the variations preferable? Thank you!

@abausi @DenisNosnitsin1970 @eu-genia

**Comment by abausi** [comment]
We faced already this problem when we worked for the COMSt manual. I 
think that Zhenia can recapitulate the point we arrived at. But IT does 
not like dots and there might be a simplification also for this reason. 
We should ascertain which is the authoritative shelfmark for the 
library. I remember the case of "MS." for the Bodleian. A query to the 
library could also help.

Il 16.11.2021 17:23, thea-m ha scritto:

**Comment by eu-genia** [comment]
In COMSt the discussion was that libraries themselves occasionally change the way they abbreviate the sub-collections (Oriental/Or./Orient./Or - they only recently standardized all to Or themselves) same for BnF Éth/Éth./Éthiopien - they used to have Éth. online, now it is written out) and the best solution from the point of view of sustainability is to not abbreviate (Éthiopien, Oriental). I guess we had not quoted Add. there so there was no separate discussion on that, I wonder if we - if we continue with the same principle - should also resolve all Add./Add to Additional to be consistent.

**Comment by DenisNosnitsin1970** [comment]
Yes, the best solution here is to write out; should this be applied to other cases, or only here? Or. for Oriental, Éth for Éthiopien are easy cases, sometimes shelf-marks are composed of more than one abbreviation, or include smth words like "cod.", "aethiop." and others which are less understandable, maybe writing out may be not practical, cp. in VOHD XX-3:  
![grafik](https://user-images.githubusercontent.com/18533839/142174407-86c5ec08-593f-4067-8765-01ce8faf76da.png)

**Comment by thea-m** [comment]
Thank you all, that's very helpful. I take from this that we will write out abbreviations and not use commas/dots. I will carry out these changes for the British Library and assign Zhenia and Denis as reviewers. I suggest that for any future doubts about other collections, we open a new issue.

**Comment by SophiaD-M** [comment]
Sorry to have this late comment on the question. Following up what Denis stated above, writing out abbreviations might lead to some bulky signatures - for example "Petermann Nachlass". I am sure there are others. 
But we might want to consider this more

**Comment by thea-m** [comment]
@SophiaD-M since there seems to be no acute issue with any such manuscript, I will close this issue again. If a manuscript is encoded where another individual shelfmark solution is necessary, a new issue can be opened. Thank you!
