### ISSUE TITLE
Dabra Golgota Dəbəq Gasha

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1836]
@Getinet309 is describing a manuscript held by Dabra Golgota Dəbəq Gasha (near Qrānyo Madḫāne ʿĀlam). There isn't yet a repository record for this monastery, so I would create one. However, I cannot find any information on this monastery anywhere. Is the correct spelling ድብቅ ጋሻ? 
Thank you!
@Getinet309 @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
I think it might be Dəbbəq Gašša, but I do not know it. He might tell where it is located (zone, wäräda, etc.), church or monatery etc. "Near  Qäranyo..." - which one? It is not very informative.

**Comment by Getinet309** [comment]
yes, the real name is ድብቅ ጋሻ(Dəbbəq Gašša) but on the satellite image, it says መርቆሪዎስ, that is rong. Dəbbəq Gašša is a monastory primarly established as church during reign of Abrha in 333 EC. and it reestablished as monastry in 1984. its location found in Amhara regional state East Gojjam zone Hulet Eju Enesie wereda lowland of Qäranyo.

**Comment by thea-m** [comment]
Thank you! @DenisNosnitsin1970 , what abbreviation shall we use for the shelfmark?

**Comment by DenisNosnitsin1970** [comment]
We can call it Dəbbəq Gašša Marqorewos (If I understand right, Marqorewos is its main dedication, with only that does not work as name), and derive an abbreviation, something like DGAM? (Please note a close shelf-mark DGMM already exists).

**Comment by Getinet309** [comment]
Marqorewos is not the main dedication, this is due to Google Maps error. I have sent a request for the corrections.  can the abbreviation be DGDG?

**Comment by DenisNosnitsin1970** [comment]
What is the main dedication?

**Comment by Getinet309** [comment]
The main dedication Dəbbəq Gašša Dabra Golgota Saint Mary monastery.

**Comment by DenisNosnitsin1970** [comment]
I would tend to DGMA, but DGDG is also good.

**Comment by Getinet309** [comment]
we  can choose one of the two
