### ISSUE TITLE
Viewer broken?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1838]
Is there a problem with the viewer?
It seems to me that all manuscripts whose images are hosted by us are not displayed. For example https://betamasaheft.eu/manuscripts/EMIP00424/viewer or https://betamasaheft.eu/manuscripts/ESmkl024/viewer. 
Here https://betamasaheft.eu/manuscripts/list?per-page=20&start=141&cp=ES&date=0,2000&wL=1,100&folia=1,1000&qcn=1,40&qn=1,100 there is the icon 
![image](https://user-images.githubusercontent.com/19650382/142904152-6e404c19-7919-466c-ab6a-0da7cc7719b6.png)
 where the previews should be. 
BnF images are displayed normally.

**Comment by PietroLiuzzo** [comment]
Thanks for the notification, I have manually spawned the process, now the images are visible again.

**Comment by thea-m** [comment]
Thank you!

**Comment by thea-m** [comment]
The same thing seems to have happened again (or at least, the images are again not available)

**Comment by PietroLiuzzo** [comment]
Thanks for the notification. One of the recently viewed files has a problematic image. unfortunately I have to keep down the system to check the logs and cannot do that at the moment, so I have simply restarted. please check again.

**Comment by thea-m** [comment]
Thank you, works now!

**Comment by thea-m** [comment]
and again broken, sorry

**Comment by PietroLiuzzo** [comment]
restarted

**Comment by thea-m** [comment]
and again :)

**Comment by PietroLiuzzo** [comment]
and should be on again. the issue should go when I do the release, so I have been told...

**Comment by thea-m** [comment]
Thank you. That would be great!
