### ISSUE TITLE
moving new records from "new" to numbered folders

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1839]
Many new records have accumulated in the "new" folders of all repositories, making their use now a bit difficult. I would like to move these to the numbered folders, but this has created syncing problems in the past. Let me know if I can do this or maybe there is a possibility of carrying this out with the next release. Thank you!

**Comment by PietroLiuzzo** [comment]
I will do this with the release, so, with webhooks off. thanks

**Comment by thea-m** [comment]
great, thank you.

**Comment by PietroLiuzzo** [comment]
In the other repositories the situation is a bit different,
