### ISSUE TITLE
New work record for commemoration of ʾIyāsu I

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1842]
I would like to create a new work record for a Sənkəssār commemoration of ʾIyāsu I (Commemoration and salām) attested as a guest text in BLorient660 2r-3r, not part of the standard transmission of the Sənkəssār. Any objections?
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_660_f001r
@DariaElagina @DenisNosnitsin1970

**Comment by thea-m** [comment]
any opinions? :)

**Comment by DariaElagina** [comment]
As far as I understand we do not create work records for texts attested as additions only on a regular basis. But if you think that in this case that would make sense, I personally have no objections.

**Comment by thea-m** [comment]
Actually, I think you're right. The case is special because the text is represented as normal commemoration, including the usual introductory formula and salām at the end, but nevertheless we do not see it reproduced elsewhere (yet - it might be possible and I'm not aware of it). The same argumentation would be true for https://github.com/BetaMasaheft/Documentation/issues/1846. I would reconsider and maybe refrain from creating the ID. 
@DenisNosnitsin1970 what do you think?

**Comment by DenisNosnitsin1970** [comment]
In my opinion, this is a border case. The commemorative text on Iyasu was added later, as far as I understand (the mss is from Fasiladas' time, isn't it?), but the added text can be seen also as the normal extention of the Synaxarion's content; it is like a collection of Miracles of Takla Haymanot, Trinity, Gabra Manfas Qeddus, three to five each, to which later one miracle of Libanos was added. It would not be an addition, rather another "layer of writing"/text added later. Here it is more complex as it was added at the beginning. It could have been written on a separate leaf of parchment and inserted under the respective day (You can check the literature on Iyasu I to see, how far is this commemoration from the Vita of Iyasu). At the end, difficult to say. It can be reproduced elsewhere, as there are a few more mss with Iyasu's Acts, maybe we can assume this. Yes, maybe it deserves a record.

**Comment by thea-m** [comment]
Thank you! We would be able to find justifications for both approaches. For now, I will not create a record, but this can always be re-evaluated.
