### ISSUE TITLE
New work record for commemoration of ʾArwā

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1846]
I would like to create a new work record for the commemoration of ʾArwā on 30 Gənbot attested probably as a guest text in BLorient661, f. 72 and 98, and edited by Colin, but not part of the standard transmission of the Sənkəssār.
@DariaElagina @DenisNosnitsin1970

**Comment by DariaElagina** [comment]
I have no objections! Seems to be an interesting case!
