### ISSUE TITLE
New work record for

### ISSUE THREAD

**Issue by Getinet309** [BetaMasaheft/Documentation#1847]
I would like to create a new work ID for ጸሎተ አቡነ እስትንፋሰ ክርስቶስ(Șälotä ʾAbunä ʾəsətənəfasä Kərəsətosə) (Prayer of Abune Estnfase Kristos) that does not have a record on BM before according to my search. It describes the greeting of the appearance of our Lord Jesus Christ. like greeting for (head, face, mouse, right and left hand, right and left leg,). Regardless of greeting the pray also describes praise and wondering the agony that occurs on these parts of bodies during the crucifixion.

**Comment by thea-m** [comment]
Dear Getinet, thank you! For the completeness of this issue, could you please state the manuscript in which this text is contained and give its incipit and explicit?

**Comment by Getinet309** [comment]
it is contained in the last of prayer of  Sene Golgotha.

**Comment by Getinet309** [comment]
the incipit is"  በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ ወአስተብቁዖት፡ ኀበ፡ እግዚአብሔር፡ ዘትበቁዕ፡ ለነፍስ፡ ወሥጋ፡ ሕያዋን፡
                        ሶበ፡ ይጼልዩ፡ ባቲ፡ ያወጽኡ፡ እምሲኦል፡ አበዊሆሙ፡ ወእማቲሆሙ፡ ወአዝማዲሆሙ፡ ወፍቁራኒሆሙ፡ እስከ፡ ፼ ነፍስ፡ በአሐቲ፡ ጊዜ።"
it ends with the word "አሜን አቡነ ዘበሰማያት በል።"

**Comment by thea-m** [comment]
Thank you! So do you consider this prayer a part of Sane Golgotā? 
It would be helpful, if you have access to the manuscript, if you could provide a longer explicit.

**Comment by Getinet309** [comment]
no, it is not the part of Sane Golgotā. only the codex is the same but the contents are quite different. Sane Golgotā is prayed by Saint Marry on June 21 at Golgotha which is the grave of her son our Lord Jesus Christ. Prayer of Abune Estnfase Kristos is about Jesus Christ prayed by Abune Estnfase Kristos.

**Comment by thea-m** [comment]
Thank you! I also think that no record exists yet for this prayer. I will create it. 
I believe we had some confusion in our conversation because you used "Sane Golgotā" to refer to the manuscript in question. I would read this as referring to the work. In order to avoid such confusion in the future, it is always better to refer to manuscripts by their shelfmarks.
