### ISSUE TITLE
EMIP scrolls encoded as codices?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1848]
In the records EMIP03155 and EMIP03220, these manuscripts are described as scrolls, but they are encoded with `<objectDesc form="Codex"> `. In the description of EMIP03155, folio numbers are used. No images are available to me. Could you check whether these are indeed scrolls or another form of manuscript? Thank you!
@Ralph-Lee-UK @Ashlee-Benson @jonahsandford

**Comment by eu-genia** [comment]
@Ralph-Lee-UK since you are back on track - it would be great if you could address this (and other issues your intervention would be helpful, I will pin you)

**Comment by Ralph-Lee-UK** [comment]
EMIP03155 is a scroll, and I have edited the record accordingly. 
I don't have images for EMIP03220, but will follow this up with Steve Delamarter.

**Comment by thea-m** [comment]
Dear @Ralph-Lee-UK , @DariaElagina and I had worked on this a while ago with Pietro. You could have a look at the records RDW005, RDW006 and RDW007 (folder Hamburg/HLC) in which we tried to implement what is possible for the encoding of scrolls. We have worked extensively with subparts inside of `<div type="edition">` to render the structure of the scrolls as precisely as possible. Note that this would be equally possible without actually transcribing the text. 
The scrolls we worked on happened all to be in one column, but you could use the same system of encoding for two columns, adding either simply `<cb>` elements within a structure as the one in the example records and optionally - if you feel that this would be more adequate - additionally define a textpart like `<div type="textpart" subtype="columnb">`. 
This is all still a bit pioneering, so it is likely that more problems and questions will arise. I'm really glad that you'll be working with this now, so that we can continue to improve the encoding of scrolls together.
Currently, the structure of the records isn't rendered well on the app. I hope that's not a big problem for you - it can be improved in the future, and the important thing is that the records are encoded well.

**Comment by Ralph-Lee-UK** [comment]
Also thanks for the information on coding scrolls - very helpful, and I'll work on following the pattern you have established. It will be a good exercise for the new team members
