### ISSUE TITLE
New record for a lexicon of poetic formulas in Ms Abb. 147

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1850]
In Add. 147, a lexicon of poetic formulas is contained as a guest text, 
I want to create a new record for it (even though I do not have any other witness). It starts like: 
ይህ፡ መጽሐፍ፡ ለደቀ፡ መዝሙር፡ ከመምህር፡ ይሻላቸዋል፡ የሰዋስውም፡ ፋናው፡ ነው፡ አስተዋይ፡ ሰው፡ ቢመለከተው። ናሁ፡ እጽሕፍ፡ አነ፡ ነገረ፡ አገባብ፡
Any objections?

**Comment by eu-genia** [comment]
no objections

**Comment by eu-genia** [comment]
LIT6511Sawasew
