### ISSUE TITLE
Folder new disappered in Persons rep

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#1857]
Dear @PietroLiuzzo , @eu-genia , @thea-m , @DenisNosnitsin1970 ,

yesterday @MarcinKrawczuk observed that the folder "new" has unexpectedly disappeared from the Persons rep. The same happened later to me as well. The folders "new" in other repositories are not affected as far as I can see. Since the app was apparently down yesterday, maybe these two events are connected to each other. I do not know if anyone else is affected, but I would like to know what would be the right way to deal with this problem. Should we just create new folders? Or are others experiencing the same problem? Where should I move the files that have not been merged yet? 

Many thanks,

Daria

**Comment by eu-genia** [comment]
As far as I can see, the files were moved to the numbered directory.

**Comment by DariaElagina** [comment]
ok, then we just have to create a new folder?

**Comment by eu-genia** [comment]
yes, do go ahead

**Comment by DariaElagina** [comment]
Thanks, sorry for the disturbance!
