### ISSUE TITLE
Cataloguing EMML1763

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1859]
I am asking permission to officially start work on the cataloguing of EMML1763 (and the related work records of course). I have a copy of it on my computer, I have already done some identifying, it is somewhat ambitious but I think it would be a worthy contribution.
@thea-m @DenisNosnitsin1970 @DariaElagina @eu-genia

**Comment by eu-genia** [comment]
Dear Marcin, thank you, of course you are welcome to!

**Comment by DariaElagina** [comment]
Thank you, Marcin!

**Comment by DenisNosnitsin1970** [comment]
Thanks!
