### ISSUE TITLE
A work record for a Patristic homiliary

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1863]
There is a Patristric homiliary which is preserved with the predominantly same content in a number of mss.:
[BL orient. 774](https://betamasaheft.eu/manuscripts/BLorient774/main)
[AP-005](https://betamasaheft.eu/manuscripts/ESap005/main)
Gunda Gunde 158
Gunda Gunde 64
Berlin orient. fol. 3075 (Nr. 161 in Hammerschmidt & Six)
Tanasee 131 = Daga Estifanos 20

(that's all I could find)

Do you think it is worth / correct to create a work record for them to distinguish it from other Patristic collections?
@DenisNosnitsin1970 @abausi @thea-m @DariaElagina @eu-genia

**Comment by abausi** [comment]
I think that this would be correct: we must start to make order between 
all these homiletic collections, when there is a substantial portion 
which is shared. This is in fact a case where the collection has also a 
consistent Arabic counterpart. So I would be in favour of creating a 
record for such collection.

Il 27.12.2021 19:24, MarcinKrawczuk ha scritto:

**Comment by MarcinKrawczuk** [comment]
Thank you! I am thinking now about the title. None of the manuscripts I have checked has anything that seems appropriate. [One of the Gunda Gunde mss. ](http://collections.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A102618#page/1/mode/1up)uses ድርሳን፡ ዘሊቃውንት፡ but it is definitely written in an older hand. Butts & Erho call it "Homiliary of Fathers" in [their article](https://www.academia.edu/40433515/Jacob_of_Serugh_in_the_Ambrosian_Homiliary_ms_Ambros_X_198_sup_and_its_membra_disiecta_) footnote 11 but I don't know how they found it.

**Comment by abausi** [comment]
I think that this title - Homiliary of the Fathers - can work very well, 
for the moment at least.

Il 28.12.2021 21:20, MarcinKrawczuk ha scritto:

**Comment by MarcinKrawczuk** [comment]
Thank you, I will proceed then.
