### ISSUE TITLE
One manuscript in two sub-projects

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1864]
EMML 1194, which I have catalogued, is the same manuscript as EMIP2924. So these two: https://betamasaheft.eu/manuscripts/EMML1194/main and https://betamasaheft.eu/manuscripts/EMIP02924/main are in fact one and the same manuscript. Should / can it be somehow made known? @PietroLiuzzo @eu-genia @thea-m

**Comment by thea-m** [comment]
Thank you! This happens occasionally. The best thing would be to delete one of them (EMIP2924 presumably), add its shelfmark to the other manuscript in an `<altIdentifier>` element and add the ID through the betmas:formerlyAlsoListedAs relation (and check whether the ID of the manuscript to be deleted has been used anywhere, and in case it has, update the references with the other ID). Could you do that?

**Comment by MarcinKrawczuk** [comment]
I could, but if one day EMIP team wants to upload the files and link them to the viewer, there will be no record where they could put the data. Isn't that a concern?

**Comment by thea-m** [comment]
One would hope that they would ask about why there is no record/check this on the website where they would be redirected to the EMML record. Otherwise you could keep the EMIP record and copy into it your description as well, but keeping both manuscript records is not according to the guidelines.

**Comment by MarcinKrawczuk** [comment]
Very well, I will try to do as you have instructed after the app is back.
