### ISSUE TITLE
Doublet to clean (Basil's homily)

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1865]
I suggest that https://betamasaheft.eu/works/LIT1632Homily/main and https://betamasaheft.eu/works/LIT4116AboutFaithBasil/main are one and the same and the former should be deleted.
@eu-genia @thea-m

**Comment by eu-genia** [comment]
agreed.  https://github.com/BetaMasaheft/Works/pull/660
