### ISSUE TITLE
file not updated in the app?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1867]
some of the files merged here https://github.com/BetaMasaheft/Persons/pull/481 are not updated in the app (at least PRS1257Aboli PRS9683Urbino). (I will recheck tomorrow, but now it has been an hour and the changes are not visible for some reason (strangely PRS10474Yostos from the same PR appears updated).
thank you for having a look when back to work.

**Comment by PietroLiuzzo** [comment]
There seem to have been a missing push and and a merge from master into the branch which resulted in only three files being changed when the merge was made. I have redelivered the hook and those three which have been merged are up to date, the others may be recovered by replicating the changes registered in the history of the branch.

**Comment by PietroLiuzzo** [comment]
correction: the firewall is correctly preventing requests to be sent to fuseki in its new log4j-secured location, hence blocking update to the application. I suspect no changes are actually making it to the application but this will be fixed when I come back from holidays with the release.

**Comment by PietroLiuzzo** [comment]
I have excluded the RDF update until then, so that the XML at least is updated for the moment

**Comment by eu-genia** [comment]
Thank you. I will recheck after the release then.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Persons/pull/483

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1972
