### ISSUE TITLE
Abraham in BL orient 609

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1868]
in BLorient609 has PRS13486Abreham scribe (by @DariaElagina ), yet previously the record PRS12706Abraham had been created (by @sologebre ) with the relation 
```
<listRelation>
                    <relation name="lawd:hasAttestation" active="PRS12706Abraham" passive="BLorient609"/>
                </listRelation>
```
I assume this is a doublet and PRS12706Abraham can be suppressed, right?

The record PRS12706Abraham is not used otherwise (the ID was erroneously used by EMIP instead of PRS1269Abraham, but this I have fixed in a separate PR)

**Comment by DariaElagina** [comment]
Oh, yes, I have overlooked this relation. I can delete the doublet in January. Thank you!

**Comment by eu-genia** [comment]
don't worry, I will reuse the ID for another Abraham )
