### ISSUE TITLE
Clavis number missing

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1871]
I saw that the Clavis Numbers are not provided anymore, after the update, in the place where they used to be. 
It occured in all the work pages that I used in the past days. The number used to be next to the black "CAe" box on the upper right.

![grafik](https://user-images.githubusercontent.com/29302681/148752667-d396a4fa-6632-45ab-81f0-1c44c9d7a96c.png)

As an example here:
https://betamasaheft.eu/works/LIT1119DossierQMQ/main 

I know that the number is provide in the little line above, but before it was more apparent at first sight.

Thank you

**Comment by PietroLiuzzo** [comment]
thanks! that should be fixed now.

**Comment by SophiaD-M** [comment]
Perfect - lightning speed. Thank you
