### ISSUE TITLE
Suggested Citation of this record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1873]
In the field "Suggested Citation of this record", there seems to be a problem which includes the names of publishers mentioned in the record in the statement, e.g. in ESkae011

> ʻDagʿa Tamben, Kunāle ʾArbāʿtu ʾƎnsǝsā, KAE-011ʼ, in Alessandro Bausi, ed., Die Schriftkultur des christlichen Äthiopiens und Eritreas: Eine multimediale Forschungsumgebung / Beta maṣāḥǝftFirmin-Didot et C<sup>ie</sup>, imprimeurs-éditeurs (Last Modified: 14.9.2020) https://betamasaheft.eu/manuscripts/ESkae011 [Accessed: 2022-01-12+01:00]

or in LIT2384Taamme

> Alessandro Bausi, ʻTaʾammǝra Māryāmʼ, in Alessandro Bausi, ed., Die Schriftkultur des christlichen Äthiopiens und Eritreas: Eine multimediale Forschungsumgebung / Beta maṣāḥǝftHarrassowitz VerlagHarrassowitz VerlagDott. Giovanni BardiMedici SocietyThe Medici Society, Ltd.Les Éditions du Cerf (Last Modified: 10.5.2017) https://betamasaheft.eu/works/LIT2384Taamme [Accessed: 2022-01-12+01:00]

**Comment by PietroLiuzzo** [comment]
thanks, should be solved

**Comment by thea-m** [comment]
Thank you! It's still visible, but maybe now everything is not synchronised

**Comment by PietroLiuzzo** [comment]
Yes, thanks, I needed to reload the module
