### ISSUE TITLE
Doublet Martyrium of Elewtǝros and his mother Ǝntǝya 

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1876]
I am quite sure that LIT1894Martyr and LIT3167Eleutheris are one and the same text, if there are no objections I will merge the records.
@thea-m @DenisNosnitsin1970 @MarcinKrawczuk

**Comment by thea-m** [comment]
I agree, please go ahead

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/672
