### ISSUE TITLE
Hide possible name variants in search results

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1881]
It would be nice to hide the list of all possible spelling variants as in 
![image](https://user-images.githubusercontent.com/17987728/149326933-51b0b01f-f6f4-45aa-8f46-f0b14789e3f9.png)

**Comment by PietroLiuzzo** [comment]
<img width="572" alt="Schermata 2022-01-13 alle 13 29 18" src="https://user-images.githubusercontent.com/508012/149330480-31b3347d-8af5-4585-bf3a-0f116bac4672.png">
switched the two, hope it is ok now
