### ISSUE TITLE
Prayer of Antony doublet ?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1882]
I assume that LIT2269salota and LIT4150Salota are the same.
Other opinions?
@thea-m @DenisNosnitsin1970 @MarcinKrawczuk

**Comment by MarcinKrawczuk** [comment]
Since neither of the two is used, I guess it doesn't really matter and one of them could be deleted.

**Comment by eu-genia** [comment]
BetaMasaheft/Works#676
