### ISSUE TITLE
New work record for hymn to Mary

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1886]
I would like to create a new record for a text contained in Aeth. g. 34, ff. 57r-73v. I could not find in anywhere in our records, also not attested in the Saʿātāt. Do you know this text?

Incipit: 

```ሰላም፡ ለኪ፡ ምልዕተ፡ ጸጋ፡ ምልዕተ፡ ክብር፡ ወብዕል፡ እንበለ፡ <gap reason="lost" unit="chars" quantity="1"/>ትጋ፨ አምላክ፡ ሰማያዊ፡ ዘ<gap reason="lost" unit="chars" quantity="1"/>ለድኪ፡ በሥጋ፨ ሰላም፡ ታቦተ፡ <gap reason="lost" unit="chars" quantity="1"/>ግ፨ አንቀጸ፡ ሥጋኪ፡ በድንግ<gap reason="lost" unit="chars" quantity="1"/>ና፡ ንሡግ፨ ሐሊበኪ፡ ጠበጠ<gap reason="lost" unit="chars" quantity="1"/>በ፡ አእሩግ፨ ዘየዓውድዎ፡ ዘ<gap reason="lost" unit="chars" quantity="1"/>ንጌል፡ አፍላግ```

Explicit:
` ሰ፤ ሰርጉት፡ በቅድስና፤ ሰ፡ ቤዛዊተ፡ ዓለም፡ <gap reason="lost" unit="chars" quantity="1"/>ሰፋኒት፡ በአርያም፤ ሰ፡ አስምዕኒ፡ ቃለ፡ ፍሥሐ፡ ጊዜ፡ አኃዘን፡ ወአስቈቍ፤ ሣህልኪ፡ ይብጻሕ፡ <gap reason="lost" unit="chars" quantity="2"/>ሥራቁ፤ ለእሳተ፡ ኀዘን፡ እንዘ፡ ያቁርር፡ ሞቁ፨ ማርያም፡ ለኃጥእ፡ ጽድቁ`

@MassimoVilla @sologebre

**Comment by MassimoVilla** [comment]
Hi, I personally do not know this text, but I have found a very similar incipit in ms Portland, Ethiopic Manuscript Imaging Project, Weiner Codex 367, that is ms EMIP02402_i10.7 (https://betamasaheft.eu/manuscripts/EMIP02402/main#ms_i10.7).
Are we entitled to fill the lost characters with reasonable conjecture in the Work record?
`ዘ<gap reason="lost" unit="chars" quantity="1"/>ለድኪ፡` is surely ዘወለድኪ፡,
`በድንግ<gap reason="lost" unit="chars" quantity="1"/>ና፡` is surely በድንግልና፡, etc.
