### ISSUE TITLE
Dates are not displayed corrrectly

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1887]
As far as I can see, the dates are not displyed correctly in the new version. There are two arrows directed against each other in place of a date, everywhere.
Under "Origin", 
![grafik](https://user-images.githubusercontent.com/18533839/149368691-d5892be8-e997-417c-9ca0-8331cbaa1297.png)

the date shows strange numbers if you click upon it.

**Comment by PietroLiuzzo** [comment]
thanks, should be fixed now.

**Comment by DenisNosnitsin1970** [comment]
Yes, the dates are displayed now, but in "Origin" and elsewhere the dates are still followed by two mysterious arrows (e.g. ESmy008). In some cases, if you click upon it, you get a string of numbers.

**Comment by PietroLiuzzo** [comment]
The answer can easily be found 
- searching the organization
- browsing from the release notes share with you also per email. 
Let me spare you this work with a summary. 
This is the implementation of https://github.com/BetaMasaheft/Documentation/issues/1271 and the suggested rendering was publicly shared there, complete of the exchange symbol you refer to as "mysterious arrows", 8 September 2021.

**Comment by DenisNosnitsin1970** [comment]
Very good, thanks!
