### ISSUE TITLE
Problem with a ES mss.

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#1892]
No contents displayed :(

https://betamasaheft.eu/manuscripts/ESum037

@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
Dear Marcin, this is most probably because of the collation. Using a  `<note>`  instead of an `<item>` will probably solve the issue.

**Comment by MarcinKrawczuk** [comment]
OK, will deal with it.
