### ISSUE TITLE
New work record for "Daily prayers and litanies" in Ethiopic Missal

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1895]
I wonder if it makes sene to create a collective overarching record for the texts that build up "Daily prayers and litanies" part of Ethiopic Missals. "Daily prayers" might include the "Prayers of the Covenant" and three supplication types (all with IDs), in full or in part. Conceptually it is one of the three major Missal parts, along with the Ordinary of the Mass (does not circulate as independent text) and (14) Anaphoras.

**Comment by DenisNosnitsin1970** [comment]
Please give your judgements :)

**Comment by eu-genia** [comment]
I am not an authority in liturgy, maybe we can also ask what @smaugustine @karljonaskarlsson @MarcinKrawczuk think, they have worked more with relevant texts.

**Comment by karljonaskarlsson** [comment]
@DenisNosnitsin1970, what do you mean with the "three supplication types"? Just so I understand

**Comment by DenisNosnitsin1970** [comment]
Mastabqwe', Liton, Zayenagges.

**Comment by karljonaskarlsson** [comment]
Ok, I don't know Qǝddāse manuscripts well enough to know how they are normally organised. But these (kidān and the other three) also often appear in the Mǝʿrāf, at least sometimes as a group. So it might make sense also from that perspective.

**Comment by thea-m** [comment]
Without being an expert in Qǝddāse  either, I think that this could be useful, and such a record doesn't yet exist.

**Comment by karljonaskarlsson** [comment]
But is "Daily prayers" a good term? Velat writes that they are used by lay people at home, but performed exclusively by the priest during the services. He refers to them as "Prières sacerdotales". When they appear in Qǝddāse MSS, I would suppose that they are there rather because of their liturgical function.

**Comment by karljonaskarlsson** [comment]
(Velat, B. (1966) Études sur le Me'erāf, p. 161)

**Comment by DenisNosnitsin1970** [comment]
Kidan/Covenant is performed more often than the rest (texts for eucharistic liturgy)

**Comment by DenisNosnitsin1970** [comment]
Well, "Prayers and litanies"? I think I picked "Daily prayers" somewhere.

**Comment by karljonaskarlsson** [comment]
Maybe "Kidān, Liṭon, Mastabaqʷǝʾ, and Za-yǝnaggǝś" as a name? It would be very self-explanatory.

**Comment by DenisNosnitsin1970** [comment]
It should be better smth "overarching". The terms for separate types will appear in the sub-items.

**Comment by karljonaskarlsson** [comment]
Maybe one could follow Velat and have "Sacerdotal prayers"? If there is no Ethiopian term that encompasses all of them.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/679
