### ISSUE TITLE
Keyword entities visualization?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1898]
I have the possibly false memory that keyword records were also displayed in the past (?)
Some of the keywords - e.g. objects of veneration, feasts - are essential as they are frequently pointed at (as tabots or works may be dedicated to them), but the links to TrueCross or Masqal do not seem to lead anywhere (?)
https://github.com/BetaMasaheft/Documentation/issues/836
Any ideas/memories @thea-m @DenisNosnitsin1970 @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
Where is the issue? Which link leads no where?
https://betamasaheft.eu/authority-files/TrueCross/main works
https://betamasaheft.eu/authority-files/CovenantMercy/main  works

**Comment by eu-genia** [comment]
from records with relations, for example here
https://betamasaheft.eu/works/LIT6513Nagar/main

**Comment by eu-genia** [comment]
Where the keywords are pointed at in records, the links stay as e.g. https://betamasaheft.eu/TrueCross and these do not resolve to /authority-files/ folder

**Comment by PietroLiuzzo** [comment]
Thanks for the clarification, the reference to the taxonomy has been updated in the controller to fix this error in the redirection of the request. (taxonomy is not expanded in the collection data but in with lists)
