### ISSUE TITLE
"edit" button does not work

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1913]
The edit button on the main page of records does not lead anymore to the edit view in GitHub, but returns "not found", e.g. for LIT5679MagicPrayer https://github.com/BetaMasaheft//db/apps/expanded/works/blob/master/5001-6000/LIT5679MagicPrayer.xml

**Comment by eu-genia** [comment]
because it should redirect to https://github.com/BetaMasaheft/Works/blob/master/5001-6000/LIT5679MagicPrayer.xml ...
