### ISSUE TITLE
Disambiguition of relations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1920]
from https://github.com/BetaMasaheft/Documentation/issues/1307:

- have saws:hasPart and dcterms:hasPart been used in different ways or can we stick to one of the two?
- have syriaca:different-from and saws:isDifferentTo been used in different ways or can we pick one?

**Comment by thea-m** [comment]
- [ ] changed rel:enemyOf to snap:EnmityFor
- [ ] changed dcterms:creator in person/manuscript relations to saws:hasWritten
- [ ] change occurrences of saws:hasPart and dcterms:hasPart to saws:contains when both entities are works
- [ ] change syriaca:different-from to saws:isDifferentTo in work records
- [ ] change  saws:isDifferentTo to syriaca:different-from to in all other records
- [ ] Update guidelines & schema

**Comment by eu-genia** [comment]
going back to person/manuscript relations and `saws:hasWritten` - for the moment the relation is not present in the code  unlike dcterms:creator. 
E.g. if there is a work and a person linked through dcterms:creator this is visualized in the main view (e.g. PRS1376Abusaker). 
![image](https://user-images.githubusercontent.com/17987728/183379104-d2b83761-d451-472c-ac21-6dc70ce61a9e.png)

If there is a manuscript and a person linked through `saws:hasWritten` - the data is of course there but visible only under relations. Should this authorship be added to the main person view?

**Comment by thea-m** [comment]
For me, it would be enough under relations

**Comment by DenisNosnitsin1970** [comment]
I don't mind to have it as it is displayed above, but to have it under relations is also ok.
