### ISSUE TITLE
New record for Maṣḥafa tārik

### ISSUE THREAD

**Issue by sologebre** [BetaMasaheft/Documentation#1926]
I started working on the Amharic manuscript (Bodleian Aeth. f. 28), called Maṣḥafa tārik, which contains multiple texts such as the history of Jesus and the apostasy, the history of the kings (biblical figures), the history of the patriarchs and also a local historical texts in Amharic about Graññ Ahmad, Amharic version of a short text dealing with titles and ranks used in the Christian kingdom of Ethiopia, which indeed its Ge'ez  version is available. Checking the BM works, I did not get an ID for this Maṣḥafa tārik. I would like to create a new record, what do you think?

**Comment by thea-m** [comment]
I agree, I had also looked at this text previously and could not identify it.

**Comment by sologebre** [comment]
Thank you Dorothea!

**Comment by eu-genia** [comment]
Sorry just one question: is Maṣḥafa tarik the title of a specific text (one of the texts listed) or of the collection as present in the MS? If of the collection then I am not sure it should get an ID. The individual texts should.

**Comment by thea-m** [comment]
It is the title of the collection, however, the entire collection is styled as a continuous text

**Comment by thea-m** [comment]
Sorry everyone for the mention, I confused this issue with the PR! As soon as https://github.com/BetaMasaheft/Works/pull/1342 is merged, this issue can be closed
