### ISSUE TITLE
Questions of Gregory

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1928]
I want to create a new record for "Questions of Gregory of Nyssa to his brother Basil" (ስእለታት፡ ዘቅዱስ፡ 
ወብጹዕ፡ ጎርጎርዮስ፡...), attested in Abbadie 96 ff. 96vb-116vb (being decribed now), Abbadie 214, Daga Estifanos 33, BerlinRoLa Petermin II. Nachtr. 50 (Dillmann's catalogue no. 53 - ii). 
I did not detect any record for this. Any objections?

**Comment by thea-m** [comment]
I also didn't find it anywhere

**Comment by DenisNosnitsin1970** [comment]
Yes.

**Comment by eu-genia** [comment]
(Denis "assignee" is the person to solve, those to ask should be addressed in the text of the message through @, preferably - so if you are the one who will be creating the record, you are the assignee, if you want me or Dorothea to do it, sure you can assign any of us. Then we shall act accordingly. Thanks!)

**Comment by eu-genia** [comment]
(In this case, since LIT1556Gorgor for this very work already existed, and no traces of it are left, one could potentially use the old Clavis number, and create by hand a record entitled LIT1556Gorgor - or of course create a new number)

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/684
