### ISSUE TITLE
Texts on chronology and computus - LIT3851Hassab LIT1195Bahrah  etc

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1929]
In Ms Abbadie 96, there is  a treatise on chronology and computus that is somewhat similar to LIT3851Hassab, but is much shorter, maybe its another  recension. It starts በስመ፡ አብ፡ ወወልድ፡  ወመንፈስ፡ ቅዱስ። ፩አምላክ፨ ጸሐፍነ፡ በዘ፡ ንዜከር፡ ሐሳበ፡
 ሕገ፡ እግዚአብሔር፨ እማዳም፡ እስከ፡ ልደተ፡ ኖኅ፡ ፲፻ወ፮፻፶ወ፮፡ Probably we need a new record for this.

**Comment by thea-m** [comment]
I also don't find it immediately, but I'm not an expert on these texts. Maybe it might be worthwile to check the witnesses of https://betamasaheft.eu/works/LIT3851Hassab/main

**Comment by DenisNosnitsin1970** [comment]
As far as I could check, Abbadie 96 is the closest text to Ethiopien 64. Now I see that LIT385Hassab de facto functions as a general record, though it should not be like this according to the description which presents Eth. 64 as the main witness. 
Numerous other witnesses included do not contain the same text but various other texts (though I could not always check on images). I always thought that the general record for chronological treatises is LIT1195Bahrah (the description is not absolutely clear, though; Bahra hassab in the title does not give a sufficient clue). Which one should be used as general record?

**Comment by eu-genia** [comment]
To me from the abstracts it also seems that LIT1195Bahrah  was the generic label and LIT3851Hassab is one of them with a specific text (then the title should be changed to " ጸሐፍነ፡ በዘንዜከር፡ ኀሳበ፡ ከመ፡ ኢንደመር፡ ምስለ፡ ከሓድያን።" or similar, and a relation added). Maybe the work and the mss records should be edited accordingly.

**Comment by DenisNosnitsin1970** [comment]
Yes, what I want to say is that LIT3851Hassab was used for other calendar and chronology related texts, without distinction (which is indeed difficult in this case), such records should be edited and LIT1195Bahrah should be used, if appropriate (maybe other specific treatise can be distinguished, cp. LIT6291HassabaRetu ). I can try to do this.

**Comment by eu-genia** [comment]
Yes, I agree, thank you for fixing this.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/689
