### ISSUE TITLE
Viewer for local images

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1931]
The locally stored manuscript images are not shown, e.g. https://betamasaheft.eu/manuscripts/ESagm006/viewer

A quick check of the bm manifest https://betamasaheft.eu/api/iiif/ESamq006/manifest shows that links to individual images result in error, e.g. https://betamasaheft.eu/iiif/AMQ/006/AMQ-006_009.tif/full/full/0/default.jpg results in `error 502 bad gateway`

****
the same problem emerged but was already resolved once on 9 July 2020, unfortunately I do not know how... now it reappeared
```
_Il giorno 8 lug 2020, alle ore 23:18, Eugenia Sokolinski ha scritto:
PS sì sembra down il server, se prendo un link specifico su un'immagine come https://betamasaheft.eu/iiif/AP/020/AP-020_002.tif/full/full/0/default.jpg mi viene 502 Bad Gateway

Zitat von Eugenia Sokolinski 
Caro Pietro,
a me non risultano visibili gli immagini dei MSS su BM (quelli che prima si vedevano senza problemi, p.e. ESap020, ESmkl002, ESdd006) - ci sono problemi con il server? O quale potrebbe essere il motivo?
Grazie!_
Genia
```

**Comment by eu-genia** [comment]
solved by remounting the image server @DenisNosnitsin1970 should be back to normal

**Comment by thea-m** [comment]
Great, thank you!
