### ISSUE TITLE
Database scripts and xml files errors and questions

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1932]
Many of the scripts use URIs containing `https://www.betamasaheft.uni-hamburg.de/` for names (at least) which surely are not true URIs. I assume `https://www.betamasaheft.uni-hamburg.de` should be replaced with `betamasaheft.eu` (?) or the new server address throughout

For example, newEntry.xqm in BetMas has
```
`module namespace new="https://www.betamasaheft.uni-hamburg.de/BetMas/new";

import module namespace templates="http://exist-db.org/xquery/templates" ;
import module namespace titles="https://www.betamasaheft.uni-hamburg.de/BetMas/titles" at "xmldb:exist:///db/apps/BetMas/modules/titles.xqm";
import module namespace app="https://www.betamasaheft.uni-hamburg.de/BetMas/app" at "xmldb:exist:///db/apps/BetMas/modules/app.xqm";
import module namespace config="https://www.betamasaheft.uni-hamburg.de/BetMas/config" at "xmldb:exist:///db/apps/BetMas/modules/config.xqm";
```

`
same for newEntry.xqm in BetMasWeb 

search.xqm has
```
`module namespace restSearch = "https://www.betamasaheft.uni-hamburg.de/BetMas/restSearch";
import module namespace rest = "http://exquery.org/ns/restxq";
import module namespace apprest = "https://www.betamasaheft.uni-hamburg.de/BetMas/apprest" at "xmldb:exist:///db/apps/BetMas/modules/apprest.xqm";
`
```

**Comment by eu-genia** [comment]
The expath-pkg.xml of the main app reads
```
<package xmlns="http://expath.org/ns/pkg" name="https://www.betamasaheft.uni-hamburg.de/BetMas" abbrev="BetaMasaheft" version="5.0" spec="1.0">
    <title>Beta ma????ft: Manuscripts of Ethiopia and Eritrea</title>
    <dependency package="http://exist-db.org/apps/shared"/>
</package>
```
link is wrong and encoding too

**Comment by eu-genia** [comment]
repo.xml in the backup writes
`<permissions user="Pietro" group="dba" mode="rw-rw-r--"/>
`

**Comment by eu-genia** [comment]
It is not possible to download the BetMasWeb application from exide (to get a XAR package); the server goes in tilt and the connection times out (it works for BetMas, gez-en, guidelines)

**Comment by eu-genia** [comment]
It seems impossible (?) to install everything from backup - only Dillmann, Guidelines and the Exist-native apps run; the BM split application results in error messages in a new localhost installation

**Comment by eu-genia** [comment]
Java error on backup result:
Exception: ------------------------------------
Problems occurred found during restore:
WARN: Skipping 8 resources. Skipping app path C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/system/repo/semver-xq-2.2.1/__contents__.xml. Newer version is already installed.
WARN: Skipping 38 resources. Skipping app path C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/packageservice/__contents__.xml. Newer version is already installed.
WARN: Skipping 29 resources. Skipping app path C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/fundocs/__contents__.xml. Newer version is already installed.
WARN: Skipping 109 resources. Skipping app path C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/monex/__contents__.xml. Newer version is already installed.
WARN: Failed to restore resource 'dependencies.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/dependencies.html'.
Reason: The XML parser reported a problem: fatal error at (1,2045) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'existdb-local-packages.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/existdb-local-packages.html'.
Reason: The XML parser reported a problem: fatal error at (16,28) : Attribute name "verbose" associated with an element type "iron-ajax" must be followed by the ' = ' character.
WARN: Failed to restore resource 'existdb-package-descriptor.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/existdb-package-descriptor.html'.
Reason: The XML parser reported a problem: fatal error at (6,3) : The markup in the document preceding the root element must be well-formed.
WARN: Failed to restore resource 'existdb-launcher.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/existdb-launcher.html'.
Reason: The XML parser reported a problem: fatal error at (52,28) : Attribute name "main-title" associated with an element type "div" must be followed by the ' = ' character.
WARN: Failed to restore resource 'existdb-dashboard.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/existdb-dashboard.html'.
Reason: The XML parser reported a problem: fatal error at (1,1683) : The element type "img" must be terminated by the matching end-tag "</img>".
WARN: Failed to restore resource 'index.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/index.html'.
Reason: The XML parser reported a problem: fatal error at (1,527) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'build.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/build.html'.
Reason: The XML parser reported a problem: fatal error at (1,664) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'iron-dropdown-scroll-manager.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-dropdown/iron-dropdown-scroll-manager.html'.
Reason: The XML parser reported a problem: fatal error at (3,83) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'iron-dropdown.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-dropdown/iron-dropdown.html'.
Reason: The XML parser reported a problem: fatal error at (1,351) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'iron-icons.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-icons/iron-icons.html'.
Reason: The XML parser reported a problem: fatal error at (1,137) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'social-icons.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-icons/social-icons.html'.
Reason: The XML parser reported a problem: fatal error at (1,137) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'image-icons.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-icons/image-icons.html'.
Reason: The XML parser reported a problem: fatal error at (1,137) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'vaadin-upload.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/vaadin-upload/vaadin-upload.html'.
Reason: The XML parser reported a problem: fatal error at (1,438) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'vaadin-upload-file.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/vaadin-upload/vaadin-upload-file.html'.
Reason: The XML parser reported a problem: fatal error at (1,276) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'iron-request.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-ajax/iron-request.html'.
Reason: The XML parser reported a problem: fatal error at (41,9) : The content of elements must consist of well-formed character data or markup.
WARN: Failed to restore resource 'iron-ajax.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-ajax/iron-ajax.html'.
Reason: The XML parser reported a problem: fatal error at (45,8) : Element type "iron-ajax" must be followed by either attribute specifications, ">" or "/>".
WARN: Failed to restore resource 'iron-fit-behavior.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/iron-fit-behavior/iron-fit-behavior.html'.
Reason: The XML parser reported a problem: fatal error at (30,37) : Attribute name "no-overlap" associated with an element type "iron-fit-impl" must be followed by the ' = ' character.
WARN: Failed to restore resource 'packagemanager-app.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/existdb-packagemanager/packagemanager-app.html'.
Reason: The XML parser reported a problem: fatal error at (40,140) : The entity name must immediately follow the '&' in the entity reference.
WARN: Failed to restore resource 'dependencies.html'
from file 'C:\Users\Eugenia\AppData\Local\Temp\exist-db-temp-file-manager-8450121505263903322\exist-db-temp-4798775264868809566.tmp#db/apps/dashboard/bower_components/existdb-packagemanager/dependencies.html'.
Reason: The XML parser reported a problem: fatal error at (1,3592) : The element type "link" must be terminated by the matching end-tag "</link>".
WARN: Failed to restore resource 'existdb-packagemanager.html'

**Comment by PietroLiuzzo** [comment]
I am not sure from where does all this originates, but the namespaces are arbitrary URIs which must be consistent within the app and should not be changed. The restore process always worked properly restoring from backup, exporting the apps and reinstalling and so on. I suspect the issue is with file permissions.

**Comment by eu-genia** [comment]
Thank you, I did a localhost installation and tried to unroll from backup multiple times and all looks good up to the very end, but at the end I get errors and the BetMas apps would not run (while as mentioned no problems with Dillmann). I tried to download the apps separately without the data but cannot generate the xar. (using BetaMasaheftAdmin in all cases)
It would be good to have a local copy... also to be sure unrolling from backup works...

**Comment by eu-genia** [comment]
I followed the guidelines precisely and took the latest exist version (which also does not have the log4 issue). Nevermind.
