### ISSUE TITLE
Another text on the origin nd chronology of the Prophets

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1940]
We need a new record for a text on the origin and  chronology of the prophets from Abbadie 96, fols. 146v-148. It is somewhat similar to LIT6156OriginProphets and starts in a similar way, but is different, much more concise and mostly consists of chronological expositions. Knibb bm:Knibb1985LivesProphets and bm:Knibb1985LivesProphets2 do not take it into account, strangely, possibly it was not properly catalogued.

**Comment by thea-m** [comment]
It seems reasonable. How are these works connected with LIT1811Liveso?

**Comment by DenisNosnitsin1970** [comment]
Oh! At first glance they appear a doublet. Both are linked to Abbadie 195, but only LIT1811Liveso is used extensively and in Abb 195. It was me who created LIT6156OriginProphets, by the reasons I do not know any longer (maybe it was to be deleted, but it was not done), around Add 195. I will check it again and perhaps I can use it for the text in Abb 96 rather than creating a new record, should I?

**Comment by thea-m** [comment]
Yes, if LIT6156OriginProphets has not been used or elaborated at all that could be a good solution.
