### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#1943]
Hello! When doing a simple search for "Senodos" from the start page, I am informed that "An error has occurred". It has been like this at least since yesterday.

<img width="1440" alt="Skärmavbild 2022-02-14 kl  09 35 03" src="https://user-images.githubusercontent.com/34240156/153828839-4b61d757-6f60-4791-85d4-01f874ec3b8c.png">

**Comment by thea-m** [comment]
Thank you for reporting this!

**Comment by eu-genia** [comment]
has there been any changes in any senodos-mentioning file recently?
the error does not seem to be in the app (it works fine if i search for "sinodos") so it must be something in the data

**Comment by thea-m** [comment]
spontaneously I only found these PRs:
https://github.com/BetaMasaheft/Manuscripts/pull/1256
https://github.com/BetaMasaheft/Manuscripts/pull/1389/files

**Comment by eu-genia** [comment]
these are all ok... and they were before the new release, and the search used to work fine... will try to keep looking but possibly this is still a bug and has to wait

**Comment by eu-genia** [comment]
it the error is in data it is in works - if I refine search results to manuscripts
https://betamasaheft.eu/newSearch.html?searchType=text&mode=any&query=senodos&type-facet=manuscript
there is no error produced, only in works

**Comment by eu-genia** [comment]
I have a feeling that this is part of a synchronization problem with BetMasData vs BetMasWeb

**Comment by eu-genia** [comment]
No also https://betamasaheft.eu/newSearch.html?searchType=text&mode=any&query=senodos&type-facet=works gives no error, so the works data is good

**Comment by eu-genia** [comment]
Same error comes also when searching for
questions

**Comment by thea-m** [comment]
and for በዓለ ቀርን, as reported by @SophiaD-M 
https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=%E1%89%A0%E1%8B%93%E1%88%88%20%E1%89%80%E1%88%AD%E1%8A%95%20&defaultoperator=AND&mode=none&homophones=on&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&titleStmt-operator-field=AND&titleStmt-field=&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=&fbclid=IwAR2sWS7ijZDwhO-C5Ri2kMtDlZzMIeR3xyYw4EGvmcYTw8-Yf3bpeaNyqWo

**Comment by eu-genia** [comment]
this is a different error

**Comment by eu-genia** [comment]
```
   line 37                               let $nodeName := item/name() 
   line 38                               let $title := switch($nodeName) 
```
check if relaxing helps
```
   line 37                               let $nodeName := if (count($item/name()) eq 1) then $item/name() else ()
   line 38                               let $title := switch($nodeName) 
```

**Comment by eu-genia** [comment]
The main error is identified and corrected for the future (not the past) here https://github.com/BetaMasaheft/Documentation/issues/2045 by the commit https://github.com/BetaMasaheft/BetMas/commit/0d2bdf88457a540d0e9081c50ec11d4687a83cd7
