### ISSUE TITLE
Indexes pointed to from the main page not loading (time limit?)

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1944]
I noticed that the page for "Index of decorations" is not loading but produces only 504 Gateway time-out error
https://betamasaheft.eu/decorations

**Comment by thea-m** [comment]
Thank you for reporting this!

**Comment by eu-genia** [comment]
Problem with redirection /html resolving to
![image](https://user-images.githubusercontent.com/17987728/153842165-d8e7b4b6-af4a-450d-b21c-909b9906fbc7.png)

**Comment by eu-genia** [comment]
The backend link to http://betamasaheft.eu:8080/exist/apps/BetMasWeb/decorations seems to work all right (even if slow)

**Comment by eu-genia** [comment]
Logically, the same (redirect error?) applies to other Indexes pointed from the main page
![image](https://user-images.githubusercontent.com/17987728/153858750-a1e6aef5-d97b-4d9c-a319-1df3034f4cf9.png)
https://betamasaheft.eu/bindings
https://betamasaheft.eu/additions
(but it works for bibliography, index of places and index of persons)

**Comment by eu-genia** [comment]
possibly the loading times are simply too long...

**Comment by eu-genia** [comment]
https://betamasaheft.eu/decorations?type=band
https://betamasaheft.eu/decorations?type=miniature
https://betamasaheft.eu/decorations?type=drawing
work fine

**Comment by eu-genia** [comment]
The hits are simply too many. I now as a test limited the number of hits per type of decoration to 100 and it works. Will try to paginate or otherwise organize the results to ensure loading.
