### ISSUE TITLE
Homilies doublets check

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1950]
Dear @thea-m 
before I delete can you please confirm that
LIT2695Hom (አኃውየ፡ ፍቁራንየ፡ ተዘከሩ፡ ሞተ፡ ዘአልቦ፡ ገብአት፡ ወኢምንተኒ፡ 
            ድርሳን፡ ዘብጹዕ፡ ዮሐንስ፡ አፈ፡ ወርቅ፡ በረቡዓ፡ ፋሲካ፡ ዘይትነበብ፡ በሰላመ፡ እግዚአብሔር፡ አሜን።)
is the same as
LIT2144OntheT (ድርሳን፡ ዘቅዱስ፡ ዮሐንስ፡ አፈ፡ ወርቅ፡ በእንተ፡ ዐሥሩ፡ ደናግል፡) (used in the description BNFet121)
?
Thank you!

**Comment by thea-m** [comment]
I agree
