### ISSUE TITLE
LIT6508DersanaG visualisation error 500

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1957]
https://betamasaheft.eu/works/LIT6508DersanaG/main
<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/works/LIT6508DersanaG/main: exerr:ERROR expected a single value for order expression $t/child::text() ; found: 2 [at line 4361, column 21] In function: viewItem:work(item()*) [5388:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1293:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]</h2><table style="font-family: &quot;Times New Roman&quot;; letter-spacing: normal; orphans: 2; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tbody><tr>
</body>
</html>

**Comment by eu-genia** [comment]
fixed

**Comment by thea-m** [comment]
thank you!
