### ISSUE TITLE
Śǝna fǝṭrat ID

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#1959]
We do not have yet any ID for "Śǝna fǝṭrat" (if I am right, can it be?) as a "work" with an assigned ID; I need to refer to it in a publication and would like to give a Bm ID for this very common and very varying work; as usual, we have to start from a common, overarching name.

I see also a bit confusing ID:
https://betamasaheft.eu/works/LIT5195Worksofcreation/main
that refers to 1 MS only.

**Comment by thea-m** [comment]
There is this "general" record: https://betamasaheft.eu/works/LIT2314senafe/main
Is that what you are looking for?
