### ISSUE TITLE
Walda/Nabiya Ləʿul

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1960]
In BLorient662, a Sənkəssār for Maskaram-Ṭərr (http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_662_f001r), Nabiya Ləʿul and his daughter Walatta Kidān are mentioned in supplications throughout. The same manuscript contains these ownership notes: 
![image](https://user-images.githubusercontent.com/19650382/155186686-696adcc5-e0af-48d1-885e-1075f2bf0c80.png)
(f. 1r)
![image](https://user-images.githubusercontent.com/19650382/155186817-ed803065-b97b-4658-889b-a81db6f41f59.png)
(f. 2v)
In Blorient663, Sənkəssār for Tāḫśāś-Yakkātit (http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_663_f001r), Nabiya Ləʿul and Walatta Kidān are also mentioned in supplications throughout, however, at the beginning of the manuscript, both the names Walda Ləʿul and Nabiya Ləʿul are mentioned (Walatta Kidān is mentioned only later).
Nabiya Ləʿul and Walatta Kidān are also attested together in supplications in BLorient725.
Do you think that Nabiya Ləʾul and Walda Ləʿul could refer to the same person, the attested brother of Bərhān Mogasā https://betamasaheft.eu/persons/PRS9931WaldaLe/main? Or are they more probably two distinct persons, possibly brothers?
@DenisNosnitsin1970 @sologebre

**Comment by DenisNosnitsin1970** [comment]
Difficult to say. Logically, Nabiya Ləʾul and Walda Ləʿul are two different persons; that their names are in part similar, may be not a coincidence, they may be indeed brothers etc, but we can only speculate lest we have a source proving that. I would keep them separately.

**Comment by thea-m** [comment]
That makes sense. Thank you.
