### ISSUE TITLE
Element <gap> with some attributes produces error

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1961]
The error https://github.com/BetaMasaheft/Documentation/issues/1935 could only be resolved by commenting out `<gap reason="lost" unit="chars" quantity="4"/>` in `msItem `1.2.9. it seems that the element `gap ` has problems in `viewItem.xqm` when of type "lost" or of type "illegible".

**Comment by eu-genia** [comment]
In BDLaethf13 
`<gap reason="illegible" quantity="4"/>` can be parsed
`<gap reason="illegible" extent="unknown"/>` cannot be parsed

In MNC002 
`<gap reason="lost" unit="characters" quantity="4"/>` cannot be parsed
`<gap reason="lost" extent="unknown"/>` can be parsed

so type lost should have no quantity, and type illegible must have some quantity to it as of the current state of the art

Should I try to update the code, or should we update the guidelines, @thea-m ?

**Comment by eu-genia** [comment]
UPD I see in the code that it treats extent for illegible as a numeral; I can easily correct this. is extent always a text string?

**Comment by eu-genia** [comment]
https://betamasaheft.eu/Guidelines/?q=illegible&id=text-encoding
do not mention `extent `at all

**Comment by thea-m** [comment]
To substitute extent="unknown" by not using `@extent` at all is fine for me.
I would not substitute "lost" by "illegible" in existing manuscript descriptions - I have used lost when the text really is materially lost and illegible when the image quality is bad, it is tightly bound or really graphically not legible for me.
If the guidelines don't mention `@extent`, it probably should be changed (I cannot have invented its use, but possibly ignored some changes and perpetuated it) - `@quantity` with `@unit` really makes more sense.
This would leave the necessity to update the code to allow `@quantity` with `lost`

And also, from the schema:
> for `gap`
> `@lost=`used to indicate a material loss or a portion of text that  is to be hypothesized for material reasons ("it was there!"), but which is lost for loss of the material
> `@illegible= `a sign, pointing to the place where the text should be added
> `@omitted`=Words or lines skipped in omitted by the editor in transcription
> `@ellipsis`=Text omitted from the edition by the editor, for whatever reason (brevity, context, language, etc.)

The definitions for omitted and ellipsis seem to be the same. Maybe omitted is not needed? 

But maybe @DariaElagina is using these in her work and might have some thoughts?

**Comment by eu-genia** [comment]
OK so we need an update in the code for a possibility for each value to have a quantity but also for each value to have no quantity, right?

**Comment by eu-genia** [comment]
And what should be printed for `@lost` without/with `quantity`? (now it always prints [- ca. -] but I can try to correct it)
no quantity [-]
given quantity [-1 characters-]
?

**Comment by thea-m** [comment]
> OK so we need an update in the code for a possibility for each value (except for ellipsis) to have a quantity but also for each value to have no quantity, right?

I think that would make sense!

> omitted/ellipsis - I sort of understand from these definitions omitted - reason unclear (error of the editor?), ellipsis - reason clear (?) but maybe I am overinterpreting...

Oh, possible! I never read it that way.

> and if the scribe has omitted something, what do we use? if the editor supplies the content then clearly <supplied reason="omitted"> but is there always something supplied? sorry if this is a stupid question...

I think this is somehow the origin of the two values omitted and ellipsis. I am not sure whether gap is the correct element here, because there is no real material gap in these cases, it is a statement on the textual transmission that maybe theoretically would belong in an edition. But of course we mostly don't have editions. I'm not sure. 

I would prefer 

> or I can also try to print e.g. [c. 9 chars lost] for given quantity and [] for no quantity

But I really don't feel as an authority on these questions :)

**Comment by DariaElagina** [comment]
Thank you for asking, but I have not used those elements so far. 
If I may, I think that omitted/ellipsis really needs some clarification.

**Comment by eu-genia** [comment]
So now all possible combinations should be parsed
I left both `extent="unknown"` and extent numeric for illegible, besides quantity, as for `illegible ``extent `with numbers has been widely used for DS mss and in inscriptions
![image](https://user-images.githubusercontent.com/17987728/157777475-6976b37d-d136-412e-8d6d-e319ceb01f6a.png)
but we can see if we decide to be more restrictive; in that case the schema should be updated to guide the users. for the moment I see this issue as closed, if more is discovered we can open a new one.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/BetMas/commit/f981bbe8724617178dfa5424b11d00bf2d1610f2

**Comment by eu-genia** [comment]
On going up to the TEI guidelines https://epidoc.stoa.org/gl/latest/ref-gap.html
`omitted `= Text erroneously omitted from the surface by the scribe
This was actually defined correctly in the rng but not in xml, fixed now
https://github.com/BetaMasaheft/Schema/commit/14d60642029eae387cfcaf27d72ac9d2dc43c506
should be OK now also here https://betamasaheft.eu/Guidelines/?q=gap&id=gap

**Comment by thea-m** [comment]
Great, thank you!
