### ISSUE TITLE
shelfmarks not printed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1962]
As pointed out by @vitagrazia81 , in some recently created files, the shelfmark is not printed, e.g. https://betamasaheft.eu/manuscripts/MfVK79300820/main or https://betamasaheft.eu/manuscripts/BLorient671/main. The encoding seems fine to me, I also re-committed these two records, but nothing changed.

**Comment by vitagrazia81** [comment]
Thanks Dorothea for creating the issue.

**Comment by eu-genia** [comment]
The BL ms shows OK.
For the others at the moment I seem to not be able to get any payload through to the app, all webhooks time out ( so cannot test

**Comment by thea-m** [comment]
Crazy. Thank you!

**Comment by eu-genia** [comment]
The problem is with the expanded files, not the encoding. I am re-expanding them one by one in Oxygen (no idea how to do in batch!), and it seems to work.

**Comment by thea-m** [comment]
Thank you. I also don't know how to batch such a process
