### ISSUE TITLE
Creation of a person record failed?

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1964]
For some reason, after creating a new person record for Frederick North (1766-1827), who owned MS BDLaethg31, I received the following message "unfortunately the ID PRS13736Frederick already exists". This record was obviously created by me on that occasion, yet something seemingly went wrong during the creation process and I had no chance to download the XML file. The record now exists in the database, as a simple search can confirm (typing "Frederick"), but I cannot adjust/move/delete the XML file because I cannot find it anywhere.
What shall I do in this case?

**Comment by eu-genia** [comment]
The easiest solution is you simply create a new xml file with Oxygen and call it PRS13736Frederick.xml, this will overwrite the file in the app.

**Comment by MassimoVilla** [comment]
Good, thank you!

**Comment by thea-m** [comment]
Maybe this can also be a solution for such cases: https://github.com/BetaMasaheft/Documentation/issues/1774

**Comment by eu-genia** [comment]
The solution offered by Pietro back then does not work (any more?) in many cases, as the xml pointed at, if the expansion took place, is the enriched one, not usable for editing (which you can easily see by going to https://betamasaheft.eu/PRS13448Gwaggul.xml (and the TEI button does not give results as documented here https://github.com/BetaMasaheft/Documentation/issues/1939)

**Comment by MassimoVilla** [comment]
Dear Eugenia, I honestly do not remember if I created that work record through the app or manually. It might be that I created it with Oxygen. I see now that LIT6573SalotaFe is listed with no title in the search results.
Also, I see that PRS13736Frederick is also found in the database but some information is missing, either because the record was also created manually or because my manually-created record has not overwritten the previous one (that I intended to create/download in the app yet something went wrong).
I am a bit perplexed as to how to deal with the two records. Should I delete them and create new records ex novo?

**Comment by eu-genia** [comment]
PRS13736Frederick should be OK now - sometimes webhook does not get through the app if it is busy.

LIT6573SalotaFe is now LIT6581SalotaFe (https://github.com/BetaMasaheft/Works/commit/8b13c9c2e817dfce8050b9750f4bdbdd73cc7e07), please can you update the records where you linked the old ID? 
Thank you!
(simply because we already had a CAe number 6573, this is why works may not be created outside the app)

**Comment by MassimoVilla** [comment]
Great, thank you! I will update the record and refresh everything.
