### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#1971]
Dear all, I have been trying, without going too much into it, to make the search page a bit clearer.
For example, I realized that many did not realize that the "old" faceted search was still there, just hidden behind the "+" and "=" symbols below. 
So I added a bit to the intro text on the simple search, and made the font bigger (I am getting old ;))
Please let me know if you find it better/worse and if you want anything else added in terms of HTML (stable, not dynamic).

https://betamasaheft.eu/newSearch.html

I also added 2 examples to the XPath search page, let me know if you have more nice examples to list, these are always helpful. 

@abausi 

https://github.com/BetaMasaheft/BetMas/commit/724266a4b32c68976220f080851dccfde9066e8d

**Comment by eu-genia** [comment]
@thea-m @DenisNosnitsin1970 @SophiaD-M @vitagrazia81 @karljonaskarlsson @DariaElagina @sologebre

**Comment by DariaElagina** [comment]
Thank you, @eu-genia !

**Comment by DenisNosnitsin1970** [comment]
Looks fine.

**Comment by eu-genia** [comment]
Added instructions on faceted search following a conversation with @DenisNosnitsin1970 https://github.com/BetaMasaheft/BetMas/commit/b3d675c48bd013cf1e158f4a2a00b88b037743e8

**Comment by thea-m** [comment]
Thank you! I think it's an improvement. 
One question for the XPath (very helpful examples which might actually allow me to use it): Is there an error/old version in the descriptive text? The variables given have "collection" as in $config:collection-rootMS, but the examples have "data" in its place. Carrying out the example search on persons in colophons with $config:collection-rootMS does not work. But maybe I misunderstand.

**Comment by eu-genia** [comment]
sorry, will correct now

`collection($config:data-rootMS)//
`
is the same as

`$config:collection-rootMS//
`
so you can have 
`collection($config:data-rootMS)//t:colophon[t:persName]
`or
`$config:collection-rootMS//t:colophon[t:persName]
`
for the same results

am also adding more examples

**Comment by thea-m** [comment]
Great, thank you!

**Comment by vitagrazia81** [comment]
Thank you @eu-genia, it looks fine.

**Comment by sologebre** [comment]
Thank you very much @eu-genia!

**Comment by eu-genia** [comment]
If there are more improvement requirements for the visualization of the search page please mention them here; other wishes are collected here: https://github.com/BetaMasaheft/Documentation/issues/2013
