### ISSUE TITLE
Works in MS BDLaethg31

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#1973]
Ms BDLaethg31 contains three texts: the first is the Prayer of Our Lady Mary on Mount Golgotha. The second and third works are unidentified.

The second text begins as follows: በስመ፡ አብ፡ etc. ... ወዘንተ፡ ነገረ፡ እምድኅረ፡ ፈጸሙ። ወካዕበ፡ ተስእልዎ፡ ፲ወ፩ አርዳኢሁ፡ ለኢየሱስ፡ ክርስቶስ፡ ወይቤልዎ። ወናሁ፡ ወሀብከነ፡ ኵሎ፡ ዘሰአልናከ፡ ወአርአይከነ፡ ብርሃነ፡ ዘኢይጠፍኣ፡ እስከ፡ ለዓለም፤ ወትፍሥሕተ፡ ዘኢየሐልቅ፡ ለትውልደ፡ ትውልድ። ወይእዜኒ፡ አርአየነ፡ አርአያሁ፡ ለደይን፡ ከመ፡ ናእምር፡ ወንለቡ፡ አምሳሊሁ፡
It's an apocryphal work based on a dialogue between Jesus and the disciples, but it is not one of the versions of the ʾArdǝʾǝt published by Basset, Littmann etc. 

The third text is titled ጸሎተ፡ ፍትሐተ፡ ማይ፡ and begins as follows: እግዚእ፡ እግዚኦ፡ እግዚአብሔር፡ አኃዜ፡ ኵሉ፡ አንተ፡ ዘፈጠርከ፡ ኵሎ፡ በጥበብከ፡ እምኀበ፡ ኢሀሎ፡ ዘበአማን፡ አንተ፡ አስተጋባእኮሙ፡ ለማያት፡ ትካት፡ ውስተ፡ ፩ ምግባእ፡ ወወሰንኮሙ፡ እምጥንተ፡ ዓለም፡ በዕበየ፡ ኃይልከ፡ ወአእምሮትከ፡ ዘኢይትረከብ።
It is also found as a4 in EMIP 24 (= Marwick Codex 20) with the title "Prayer to de-consecrate blessed baptismal water" and in EMIP 32 (= Delamarter Codex 1) with the title "Prayer for the de-consecration of the water", but the text in BDLaethg31 is much longer than those in the EMIP mss. It might also be part of at least one version of the Maṣḥafa krǝstǝnnā, although I have not detected this prayer in any witnesses I consulted. Anyway, I think a new record is needed with some information on these still unclear aspects.

**Comment by thea-m** [comment]
Thank you, I agree, I searched for both with the same results as you.
