### ISSUE TITLE
BDLaethf13 HTTP ERROR 500

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1976]
https://betamasaheft.eu/manuscripts/BDLaethf13/main
(I did not carry out any checks yet) 

HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BDLaethf13/main: err:FORG0001 can not convert 'unknown' to xs:integer [at line 3458, column 21] In function: viewItem:gap(element()) [4116:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2886:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4134:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1777:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4180:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2955:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5158:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5202:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5271:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4183:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5158:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5247:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4173:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5102:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5409:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1293:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
Again, the error source is with the gap element inside of incipit, as reported here https://github.com/BetaMasaheft/Documentation/issues/1961
(the encoding is correct but for the moment not supported by the app)
for the moment commented out https://github.com/BetaMasaheft/Manuscripts/pull/1475

**Comment by thea-m** [comment]
Ah, thank you!
