### ISSUE TITLE
User of links to various internet resources 

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1978]
There appeared a question of the use of links to images online in "idno". Can the reference to an internet resource with part-set of images be used here? For instance, there is no full set of images for Abbadie 115 on Gallica, but a part set at: http://mandragore.bnf.fr/ark:/12148/cgfbt4443 (miniatures only), also run by BnF. Can it be inserted into "idno", or better elsewhere?

**Comment by eu-genia** [comment]
As mentioned here https://github.com/BetaMasaheft/Manuscripts/pull/1480#issuecomment-1055915552
you can have links to any single html page through `ref target`, but not in `idno facs`, as this attribute requires iiif manifest

**Comment by eu-genia** [comment]
Note also that the link you mentioned is only for 1 image, on f. 5
check this link for all miniatures. you can insert the target one by one for each
http://visualiseur.bnf.fr/Visualiseur?Destination=Mandragore

**Comment by thea-m** [comment]
I think the question at the core here was to document where in the record such links to partial digitisations should be added. The easiest would probably be to include the link, i.e.  `<ref target="http://mandragore.bnf.fr/jsp/feuilleterNoticesImageArk.jsp?numero=1&id=441&idPere="></ref>`, in the concerned part of the description, in this case the decoNote in question:
```
<decoNote xml:id="...">
<locus target="#3v"/>
<desc>Digitised at <ref target="http://mandragore.bnf.fr/jsp/feuilleterNoticesImageArk.jsp?numero=1&id=441&idPere="></ref></desc>
...
```
I was wondering whether it would make sense to link to these images also under `<facsimile>`, but maybe that would offer no extra information.

**Comment by eu-genia** [comment]
I think in this case we are dealing only with images, so I would be for `ref `in `decoNotes`. I personally would not use `facsimile `for single textless pages.
I would reserve `facsimile `for digitized text when no JSON iiif manifest is present.

**Comment by eu-genia** [comment]
so my take would be
manuscript digitized and iiif ---> `idno facs`
manuscript digitized not iiif ---> `facsimile`
single pages ---> `ref`

**Comment by eu-genia** [comment]
Note also here: https://github.com/BetaMasaheft/Manuscripts/pull/1482 it is important that `idno facs` only contains iiif manifest, not any URI. 
For BNF the `gallica.bnf.fr` URI is sufficient.

**Comment by eu-genia** [comment]
```
<decoNote type="miniature" xml:id="d1">
                              <locus target="#3v"/>
                               <desc><ref type="authFile" corresp="AT1044Prophet"></ref>: <persName ref="PRS7181MosesM">Moses</persName> and
                               <persName ref="PRS4372Gabreel">St Gabriel</persName>.</desc>
                               <note>Digitized at <ref target="http://mandragore.bnf.fr/ark:/12148/cgfbt4443"></ref></note>                               
                           </decoNote>
```

**Comment by thea-m** [comment]
I think that's a good solution, I will add this example to the guidelines.

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/guidelines/pull/135
