### ISSUE TITLE
Wright basic codicological data

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1979]
It might make sense to have at some point a systematic look at the binding descriptions of Wright's catalogue, which are very heterogeneous, and update them with basic information from the images (whether the binding has been redone by the library)

**Comment by thea-m** [comment]
Dear all, 

we are nearly done with the digitisations of all of Wright's descriptions. 
Before completely leaving this catalogue behind, I wonder whether it would be a worthwhile undertaking to go through all records and provide some basic codicological data for all manuscripts for which images are available. 
Such data might include:
- quire structure
- binding (original or by the library)
- ruling pattern, basic data on layout
- "Varia" not described by Wright, such as stamps by the library or scribbles

These have already been provided for some of the manuscripts we worked on recently, but at the beginning of the project many of the images were not available yet, and our focus was elsewhere.

What do you think? This would obviously be still a considerable investment of time. The alternative would be to move on to another catalogue and live with heterogeneity of our descriptions (which will always exist anyway).
@abausi @DenisNosnitsin1970 @eu-genia 
Thank you!

**Comment by eu-genia** [comment]
Just to summarize for the issue what @abausi has suggested: OK to try selectively, especially in cases where considerable more added value is expected.

Just a thought from me: of the items suggested above I would think that the quire structure is the most time-consuming task both in terms of determining and encoding, so I would suggest for the time to skip it or do it for really important manuscripts - especially composite ones, where the quire structure could help in determining the layers. Also layout is particularly interesting when there are caesuras I think.
