### ISSUE TITLE
LIT5777MalkKiros, LIT2851RepCh133 and LIT2860RepCh141

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1984]
I think that LIT5777MalkKiros, LIT2851RepCh133 and LIT2860RepCh141 refer to the same text. LIT5777MalkKiros was probably created erroneously., LIT2851RepCh133 and LIT2860RepCh141 differ according to Chaîne in the omission of the preposition ḫaba, but the only manuscript he gives as a witness for this variant in LIT2860RepCh141 is Nr. 190 in his catalogue of the d'Abbadie collection, which is also given as witness for LIT2851RepCh133 . Chaîne's catalogue only lists one hymn with this incipit for Nr. 190.
I would suggest to merge the records.
Any objections @DenisNosnitsin1970 @eu-genia @smaugustine ?

**Comment by DenisNosnitsin1970** [comment]
Ok
