### ISSUE TITLE
A new record for "Ten Questions", Ms Abbadie 122

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1986]
I could not detect any record for the fourth treatise, ዓሠርቱ፡ ተስእለታት፡ ተስአሎ፡ ቀዳማዊት፡ ዘብዩን፡ ውስቴታ፡ ትርጓሜ፡ ትሥልስት፡ ወተዋሕዶ፨ ይቤ፡ ረድእ፡ ኦመምህር፡ ነገር፡ , published in Cerulli, "Scritti teologici etiopici...", II, and attested in Ms Abbadie 122. If it does not exist, I will create it.

**Comment by thea-m** [comment]
I also don't find it.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/716
