### ISSUE TITLE
Berlin mss automated Bm entries

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#1987]
The automated entries that were created for Berlin Stabi, using the info that the Stabi provided, are missing their shelfmark. The shelfmark is only visible in the link, but not in the entry. 

Some of these mss are used by ITIESE, and we can amend the entires, but the other should also be fixed at some point in time - ideally.

**Comment by eu-genia** [comment]
this is a syncing issue, usually the filename should appear after the second/third use and/or after changes are entered; the shelfmark is there, it is simply sometimes not printed as BIG TITLE
if you are in a hurry just list the mss you lack proper visualization and i will re-expand them manually
