### ISSUE TITLE
Another new record for a text in Abb 122

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#1990]
We apparently need a record for another text in Abb 122, ትምህርተ፡ ሃይማኖት፡ ርትዕት፡ (ወፍኖተ፡ አምላክ፡ ጽይሕት፡ ዘጼሕዋ፡ ሐዋርያት፡). It is different from LIT2443Temher and the Amharic text of the same title; its another witness is EMIP00699 (ms item 1).

**Comment by eu-genia** [comment]
OK for me

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/721
