### ISSUE TITLE
Berlin mss not visualised 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1991]
For many of the Berlin mss, there is the error message 

> BerOrOct1011 is not an available item.
> Ids are case sensitive.
> Try browsing or using simple or advanced search.

e.g. BerOrOct1011, BerHsOr15095, BerHsOr9826, BerOrOct3986

Maybe something during the syncing? @eu-genia 
@SophiaD-M

**Comment by eu-genia** [comment]
some webhooks did not work, will try again

**Comment by eu-genia** [comment]
should be all, if you notice more missing please reopen

**Comment by SophiaD-M** [comment]
Dear Zhenia, I think unfortunately it still does not work for all of them. I checked this by chance - https://betamasaheft.eu/manuscripts/BerOr9843/main
same issue.

Also this: https://betamasaheft.eu/manuscripts/BerOr9834/main 
So it might be affecting all od these automated entries?

**Comment by eu-genia** [comment]
BerOr9834 does not exist. And should not exist.  Did you try BerHsOr9843

**Comment by eu-genia** [comment]
We do not have BerOr
BerHsOr
BerOrFol
BerOrOct
BerOrQuart

**Comment by eu-genia** [comment]
(make sure your local directory is synchronized, fetch and pull regularly)

**Comment by SophiaD-M** [comment]
haha, yes, my bad! 
Thank you
