### ISSUE TITLE
erroneous "no images" link for BnF mss

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1994]
In the box "This unit, or parts of it, is contained in 1 manuscript records 1 time" in work records, all BnF manuscripts with linked images have the message "no images", which works as a functioning link to the viewer. Once understood, it's no big problem, but people might be confused and not try to click to click on the link. 
For example https://betamasaheft.eu/works/LIT2845RepCh128/main

**Comment by eu-genia** [comment]
This probably applies to all mss where images are not local but shared through iiif manifest

**Comment by eu-genia** [comment]
actually there is an exception for iiif manifests in the code...

**Comment by eu-genia** [comment]
Found (and hopefully fixed) the error, will resolve after the next reboot (not today) https://github.com/BetaMasaheft/BetMas/commit/4400dbf116b5310330405fa41bc7e262615c27bf

**Comment by thea-m** [comment]
Thank you!

**Comment by eu-genia** [comment]
Thumbs still don't work but the link is now called "Link to images", hope this is sufficient for now )
