### ISSUE TITLE
monastic genealogy

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1997]
I could use some help in the description of a monastic genealogy in BLorient760, f. 3v. http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_760_f001r
There is possibly a text break in the middle of f. 3vb, with the first part going until Samuel of Halleluya, and the second part mainly on the abbots of Dabra Libānos, ending with a Zaməśrāq.
WE have several related IDs (LIT3972Mashaf, LIT4336Ledata, LIT3143Ledata), but their disambiguation is not clear to me and I don't know these texts well. I wonder whether a narrative unit might be more appropriate? 
@DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
You are right, there is quite a bit of confusion here.
I am quite certain that LIT3972Mashaf is the text which often goes together with the Gadla Takla Haymanot. And LIT3143Ledata  is part of it.
LIT4336Ledata has been used as a generic ID for monastic genealogies transmitted anywhere (including additions, etc)
But this is my impression from the use so far. I think LIT4336Ledata so far has been used to refer to a lot of different texts.
I am sure @DenisNosnitsin1970 can try to make some taxonomy out of it.

**Comment by thea-m** [comment]
Thank you! A possible solution would be:
1. Update LIT4336Ledata with the reference and check whether this is really the work contained in the manuscripts linked to it (I can do this).
2. Update LIT3972Mashaf with information that can make it well recognisable by everyone :) and describe its relation to LIT3143Ledata in both records (I could also do this, but I imagine that the quality would be higher if Denis did it?).
3. Create a "general ID" for a monastic genealogy that cannot be identified (I can do this).

Do you agree?

**Comment by DenisNosnitsin1970** [comment]
OK, I can try.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/752
