### ISSUE TITLE
Song of Songs changing title to Ethiopic version

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2002]
Still concerning the Ethiopic Psalter at a larger point.

Could the description for Song of Songs CAe 2326 https://betamasaheft.eu/works/LIT2362Songof/main be changed so that in its entry the Ethiopic title Maḥālǝya maḥālǝy is given as main title and not the English one?   Simply becuase it would be more consistent with the other parts of the Psalter which are listed by their Ethiopia titles too.

Thank you

**Comment by eu-genia** [comment]
If your concern is the consistency of your manuscript description please provide the titles you want to see them printed in the `<title>` element of your `@msItem`
In general, for "international" texts I think it is quite reasonable to have English as the main title of the record. This is not necessarily related to the manuscript description.

**Comment by SophiaD-M** [comment]
I have no preferences here, I just think it would be nicer if they are all in either one language. Could just as well be all in English. 
I simply would prefer such consistency

**Comment by thea-m** [comment]
Thank you for opening this issue! I remember that there was some discussion around this, and that it was decided to keep the English title for such widely known works.
