### ISSUE TITLE
add fidel title to Ascensio Isaiah

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2004]
The entry Isaiha, Ascnsion of https://betamasaheft.eu/LIT1671Isaiah lists only the English versions of the title. It would be great to offer also the the fidel ዕርገተ፡ ኢሳይያስ፡ ነቢይ፡ 

Because in this entry item ms_i2 only the fidel is used https://betamasaheft.eu/manuscripts/BDLaethd13/main

Thanks

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/commit/e91d635d827eeffaf0740508e7fbdc170c53c247
