### ISSUE TITLE
Records for texts related to Mabaa Seyon PRS6418Mabaas

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2007]
I did not find any record for the MIracles of St Mabaa Seyon/Takla Maryam and for the text related to him known as "Book for the Commemoration of the Saviour of the World" (over 10 mss in Ethi-Spare database, cp. e.g. https://betamasaheft.eu/manuscripts/ESmkl007/main). Should I create them?

**Comment by eu-genia** [comment]
Plus an overarching record for the Dossier/Collection of texts )

**Comment by thea-m** [comment]
oh, sorry, https://betamasaheft.eu/works/LIT1973Mashaf/main actually exists, but according to the EAe is loosely used for the dossier. It will be good if you develop it and create the necessary records.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/737
https://github.com/BetaMasaheft/Works/pull/743
https://github.com/BetaMasaheft/Works/pull/744
https://github.com/BetaMasaheft/Works/pull/747
