### ISSUE TITLE
validation errors in records

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2014]
There are some stubs with validation errors because their titles or relations were never completed.
Please check if these can be completed.
@DenisNosnitsin1970  - can you check LIT5206TreatisePassions ?
@thea-m - can you check LIT3961Homily? LIT5959CommAnThaumaturgus (I inserted a passive "LIT2034Naakkw" but maybe am wrong...)
Thank you!

**Comment by DenisNosnitsin1970** [comment]
ok
