### ISSUE TITLE
Work records for homilies in EMML1763

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2018]
I am currently working on EMML1763, largely because I need the Clavis numbers. I think that about 40 out of 80 homilies currently do not have work records. I may enumerate them all if you wish but they are all very rare, and appear usually only in the "twin manuscripts" BritLib Orient 8192 and EMML 8509. So, I request permission to create them.
@thea-m @eu-genia 

PS I actually created the issue on the subject some time ago but now I cannot find it.

**Comment by eu-genia** [comment]
There were some issues, all with green light so closed
https://github.com/BetaMasaheft/Documentation/issues/1717
https://github.com/BetaMasaheft/Documentation/issues/1795
https://github.com/BetaMasaheft/Documentation/issues/1729
Sure, if these are new texts do go ahead.
