### ISSUE TITLE
Print PDF

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2025]
In the previous release it was possible to print a PDF version of each record (?), the button is not there any more, to check if it can be brought back

**Comment by thea-m** [comment]
I remember that it was an active decision not to have this function anymore, because apparently no one used it. But if you (or others) have an interest in it, then it would logically make sense to bring it back.

**Comment by eu-genia** [comment]
This was a request from @DenisNosnitsin1970 , I personally have not used it, but in fact printing the web page directly does not produce nice results. On the other hand it may be easier to convert to PDF in Oxygen.

**Comment by DenisNosnitsin1970** [comment]
I meant - anything that would convert a manuscript description, at any stage of elaboration, into a normal fluent readable text, with no special layout but devoid of all TEI apparatus and therewore more content-focused and convinient for careful reading. Rarely though, this device this was used, e.g. by Nafisa in her PhD of which I append one page.  
[Gadla  Lalibala p 1.pdf](https://github.com/BetaMasaheft/Documentation/files/8305856/Gadla.Lalibala.p.1.pdf)

**Comment by thea-m** [comment]
It works only in oxygen, but this can be done with the makePDF package.

**Comment by thea-m** [comment]
And - sorry, again only oxygen - there is the author mode in oxygen in which all markup is hidden.

**Comment by DenisNosnitsin1970** [comment]
If I have no oxygen and do not work with oxygen, is there anything else?

**Comment by DenisNosnitsin1970** [comment]
But probably Nafisa printed the description from oxygen, this is true.

**Comment by eu-genia** [comment]
I will check next week if there are old xslt that may be reused

**Comment by DenisNosnitsin1970** [comment]
Ok, I see.

**Comment by eu-genia** [comment]
In any case I think I can restore the button, it was commented out in the code but is still there, if desired
```
<!--<div class="w3-bar-item w3-tooltip">
{apptable:pdf-link($id)}
<span class="w3-text w3-tag itemoptiontooltip">Produces a PDF on the fly from the source TEI-XML using XSL-FO and Apache FOP</span>
</div>
</div>-->
```

**Comment by eu-genia** [comment]
The most important thing: the function is still there, it is only the button which is not visible.
Which means: if you replace` /main` with `.pdf` in the address line of the browser you will get your PDF
