### ISSUE TITLE
Keywords in new entry form to be printed as attribute value

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2030]
When you create a new work record and you select the keyword "Christian literature", when you open the record in Atom the keyword has an extra space. It's not really a problem but since it is the most used keyword perhaps it can be corrected.
@eu-genia

**Comment by eu-genia** [comment]
I am aware of this; this is the way all keywords are printed now in the form (so everywhere where the visualization has a space, a space is rendered); maybe I will get to it eventually but hope this is not a huge problem to take the space out. Thank you!

**Comment by MarcinKrawczuk** [comment]
OK, noted.

**Comment by thea-m** [comment]
(it's not a huge problem and not urgent, but more annoying than the space is for me that for example "HistoryAndHistoriography" becomes "History and Historiography" and one has to correct the capitalisation of and as well. For us it's no problem, but for new users it might be confusing. I don't know how complicated editing the new records creation form is - if it's not, maybe the keyword function could be commented out until this eventually gets solved?)

**Comment by thea-m** [comment]
wonderful, thank you!
