### ISSUE TITLE
ERROR cannot convert xs:boolean('true') to a node set

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2034]
Apparently,  
```
<layoutDesc>
<layout columns="2"/>
</layoutDesc>
```
can lead to a visualisation error. In several records, commenting this out solved the error (BDLpoc8, BDLaethd6, BDLaethd12). For BDLpoc8 I tried commenting out different parts of the record, so I'm relatively sure that this is the reason for the error, not a synchronising problem. However, there are also records with the same encoding where there is no visualisation problem (BDLaethd13)
Any ideas? @eu-genia

**Comment by eu-genia** [comment]
looks like a true bug, probably of existDB, that does not understand a boolean operator (and or not) somewhere in the code... no idea why only in some cases, have to explore more
it seems that the error was introduced by wolfgang in existDB optimization from version 4.5 and was fixed in existDB release 6 (we are working with 5.2), see https://github.com/eXist-db/exist/issues/3289

**Comment by eu-genia** [comment]
<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BDLpoc6/main: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]</h2>

URI: | /exist/apps/BetMasWeb/manuscripts/BDLpoc6/main
-- | --
500
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BDLpoc6/main: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
XQueryURLRewrite
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BDLpoc6/main: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BDLpoc6/main: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
javax.servlet.ServletException: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
org.exquery.restxq.RestXqServiceException: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
org.exist.xquery.XPathException: exerr:ERROR cannot convert xs:boolean('true') to a node set [at line 2016, column 21, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:TEI2HTML(item()*) [2016:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4188:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5265:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5323:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4231:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5210:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5299:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4221:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5154:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5461:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by eu-genia** [comment]
The diagnosis was correct, it has nothing to do with columns but with the string
`                    {viewItem:TEI2HTML($h/node()[not(self::t:seg)][not(self::t:list)])}
`
inside of hand description; resolved as suggested on exist github forum through
`                    {viewItem:TEI2HTML($h/node()[empty(self::t:seg)][empty(self::t:list)])}
`

**Comment by eu-genia** [comment]
(you can post issues immediately without spending too much time commenting out, as one first has to read into the error report ;))

**Comment by eu-genia** [comment]
(I have not commented the layout elements back in)
