### ISSUE TITLE
Egziʾabəḥer nagśa recensions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2038]
We currently have one general record for Egziʾabəḥer nagśa (LIT1325egziab), and four records for the recensions (all according to Getatchew 1983): 
- attributed to Giyorgis of Gāsəcca (LIT4030EgziabeherN)
- attributed to Zarʿa Yāʿqob (LIT4031EgziabeherN)
- za-ʿArke (LIT1326egziab)
- Mazmura fəśśuḥan (LIT2001Mazmur)

za-ʿArke developed to become Mazmura fəśśuḥan. Getatchew lists manuscripts belonging to the state of development za-ʿArke, to the state of development Mazmura fəśśuḥan and several between these two (a lot of these latter among the BL manuscripts). My question is how to encode these. Should I create a new record to be used as general record for manuscripts belonging to the za-ʿArke/Mazmura fəśśuḥan collection, for this in-between state?
@DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
I wonder if it is possible always to identify which "Egzi'abeher negse" belongs to which type. Maybe  just a general record for collections of unidentified type?

**Comment by DenisNosnitsin1970** [comment]
Indeed; if one text can be identified as a transitional stage between two recensions, it would be fine, sure.
