### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2045]
https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=%E1%8B%98%E1%8A%A8%E1%88%98%E1%8D%A1+%E1%8A%A5%E1%8D%8E%E1%8D%A1&defaultoperator=AND&mode=phrase&homophones=on&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&titleStmt-operator-field=AND&titleStmt-field=&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=

An error has occurred
something has gone wrong. Sorry! This error has been generated by the application.

err:XPTY0004 Cardinality error in switch operand  [at line 38, column 49, source: /db/apps/BetMasWeb/modules/tei2string.xqm]
In function:
	string:ref(item()*) [142:20:/db/apps/BetMasWeb/modules/tei2string.xqm]
	string:tei2string(node()*) [151:21:/db/apps/BetMasWeb/modules/tei2string.xqm]
	string:tei2string(node()*) [3341:18:/db/apps/BetMasWeb/modules/tei2string.xqm]
	q:summaryWork(item()*, item()*) [3083:29:/db/apps/BetMasWeb/modules/queries.xqm]
	q:summary(item()*) [2922:37:/db/apps/BetMasWeb/modules/queries.xqm]
	q:resultswithmatch(item()*, item()*) [2712:17:/db/apps/BetMasWeb/modules/queries.xqm]
	q:results(node()*, map(*), xs:integer, xs:integer) [-1:-1:/db/apps/BetMasWeb/modules/queries.xqm]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [237:13:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [428:17:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*) [230:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [133:51:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [90:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:apply(node()+, function(*), map(*)?, map(*)?) [50:5:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]

@eu-genia

**Comment by eu-genia** [comment]
interestingly I don't get the error if I search with homophones off
https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=%E1%8B%98%E1%8A%A8%E1%88%98%E1%8D%A1+%E1%8A%A5%E1%8D%8E%E1%8D%A1&defaultoperator=AND&mode=none&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&titleStmt-operator-field=AND&titleStmt-field=&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=

**Comment by eu-genia** [comment]
otherwise it is the same error as here
https://github.com/BetaMasaheft/Documentation/issues/1943
somewhere in the data something is not parsed

**Comment by eu-genia** [comment]
As far as I see it, the problem is multiple references  (e.g. `ref target="#a1 #a2 #a3"`) somewhere

**Comment by thea-m** [comment]
Should this encoding of multiple values for `ref target` be avoided? It is mentioned in the guidelines, but apart from EMIP mss, there are not too many instances. If it poses problems, we might change this.

**Comment by eu-genia** [comment]
ideally i believe it should be avoided as the links are sometimes not resolved correctly, but i still have to explore more to find out whether i can find a solution
still in most cases there is no huge error, just that the links do not work in visualization
what exactly is causing the error in the search (the app is unable to resolve the `@target`, but why?) i still have to find out...

**Comment by eu-genia** [comment]
OK the problem is not multiple targets, the problem is the file expansion
this is related to the problems with expanding 
enriched files take titles for witnesses in listWit from the list of titles in the list for works, as that is where the titles of manuscripts are printed to.  This results in multiple xml:id=t1 in the record
e.g.
LIT4018Mashafa
```
               <witness corresp="https://betamasaheft.eu/Tanasee52"><idno facs="EMIP/Codices/3547/" n="178">Ṭānāsee 52</idno><title xml:id="t1">Maṣḥafa qedar, other texts</title></witness>
               <witness corresp="https://betamasaheft.eu/BAVcerulli81"/>
               <witness corresp="https://betamasaheft.eu/EMML1941"><idno>MS EMML no. 1941</idno><title xml:id="t1">EMML 1941</title></witness>
               <witness corresp="https://betamasaheft.eu/EMML1952"><idno>MS EMML no. 1952</idno><title xml:id="t1">EMML 1952</title></witness>
               <witness corresp="https://betamasaheft.eu/EMML2358"><idno>MS EMML no. 2358</idno><title xml:id="t1">EMML 2358</title></witness>
               <witness corresp="https://betamasaheft.eu/EMML4754"><idno>MS EMML no. 4754</idno><title xml:id="t1">EMML 4754</title></witness>
```
of course this creates problems

**Comment by eu-genia** [comment]
earlier manuscripts hat the title element as `<title>`, more recently and those produced through the app have `<title xml:id="t1">`, and this is written into the expanded work record with `listWit`, so all records that refer to `#t1` inside of a work record that has a list of witnesses become invalid - we think we only have one `t1 `but it can be many

**Comment by eu-genia** [comment]
I have now corrected the `expand.xqm` code that the titles of the manuscripts are not printed in `witness`. The already expanded work records with witnesses will have to be corrected or re-expanded by hand...

**Comment by eu-genia** [comment]
in this case the problem was in the enriched LIT2186Preach, now re-expanded
in the future if this error (Cardinality error in switch operand [at line 38, column 49, source: /db/apps/BetMasWeb/modules/tei2string.xqm]) occurs the work record with a list of witnesses must be found that has to be reexpanded

**Comment by thea-m** [comment]
Oh, wow, you were patient!

**Comment by eu-genia** [comment]
Once I figured out that the problem was in the data, but not the ours, it was easy )

**Comment by eu-genia** [comment]
(And it was important, as gradually the number of files with the witnesses is growing and the error would have started coming more and more often)
