### ISSUE TITLE
How Haymanotä abäw displays in the app

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2049]
If you have a look at https://betamasaheft.eu/works/LIT1586Hayman/main under keywords there is this:
![Zrzut ekranu 2022-03-24 131728](https://user-images.githubusercontent.com/62760230/159914528-a3acae4a-f169-4988-b071-9947c6e86bed.jpg) . I may correct it but I don't really know where the problem lies. 

@thea-m @eu-genia

**Comment by eu-genia** [comment]
it comes from the code wich attemps to show attributed authors
`viewItem:keywordgroupauth($file//t:relation[@name eq 'dcterms:creator']),`
now should be clean
