### ISSUE TITLE
error 500 BLorient80

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2051]
<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient80/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]</h2>

URI: | /exist/apps/BetMasWeb/manuscripts/BLorient80/main
-- | --
500
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient80/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
XQueryURLRewrite
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient80/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient80/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
javax.servlet.ServletException: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
org.exquery.restxq.RestXqServiceException: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
org.exist.xquery.XPathException: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 2. [at line 3361, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4305:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2855:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:incipit(element()) [4165:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1761:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1760:73:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4211:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2924:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5202:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5246:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4204:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5146:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5453:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

</body>
</html>

**Comment by eu-genia** [comment]
We may not have xml markup inside of the `supplied `tag (or other editorial tags)
https://github.com/BetaMasaheft/Manuscripts/commit/88e79321d496cd64bde1eeb4703f57d859bedd0c
