### ISSUE TITLE
Emip mss missing from list

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2052]
I wanted to add the link to a few EMIP mss I came accross in a search, but some of them are not included on the spreadsheed:
EMIP00917
EMIP02229
EMIP02246
EMIP02278
EMIP03221
They all have facs without n in the records.

**Comment by eu-genia** [comment]
there are no images for them on the server as you can easily check going to ad.uni-hamburg.de\daten\aai-hlz-bm
