### ISSUE TITLE
Habta Giyorgis

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2053]
I think that [PRS12464HabtaG ](https://betamasaheft.eu/persons/PRS12464HabtaG/main)and [PRS4933HabtaGi ](https://betamasaheft.eu/persons/PRS4933HabtaGi/main)refer to the same person. I would suggest to delete PRS12464HabtaG , merge the information and update the IDs in manuscripts. Do you agree?
@DenisNosnitsin1970 @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
This might be, I Habta Giyorgis Dinagde was a hight official in Menelik's time and later, we have probably an EAE article about him, it would be good to complete the record with some info.
