### ISSUE TITLE
A suggestion for displaing works about a person

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2056]
Since recently the person records for authors display automatically the works attributed to them. Would it be possible to have the same for persons which are the subject of works?

So for example, in the personal record for St. George we would immediately see all the work records with a relation ecrm:P129i_is_subject_of. 

Currently in order to have it you need to see under "Show attestations" where there are also manuscripts. 
@thea-m @eu-genia

**Comment by eu-genia** [comment]
done, in the red box
