### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2066]
I think the title here might be a type "Antony", what do you think?
https://betamasaheft.eu/persons/PRS1962Anthony/main

If indeed a typo, might I try and change it as TEI training?

**Comment by eu-genia** [comment]
no this is also the way he is often spelled, always by Coptologists, always by Witold ) all spellings are there anyway and a link to https://www.wikidata.org/wiki/Q170547
