### ISSUE TITLE
"schema error" (?) in MS MR-023

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Documentation#2067]
This issue is just to signal that there is a problem or error in the visualization for MR-023, ms which by chance I have opened today (https://betamasaheft.eu/manuscripts/ESmr023/main). 
This is what you see written (in red) under "Contents".

HIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. THIS BIBLIOGRAPHIC RECORD () has no @corresp or t:ptr/@target. Please check the schema error report to fix it. ....

Thank you, 
Vita

**Comment by vitagrazia81** [comment]
Dear Zhenia, 
thank you for transferring the issue (I am sorry for the wrong place).
I can see this red huge text which signals the error if you click on contents, below the explicit. I simply wanted to signal it.

![screenshot](https://user-images.githubusercontent.com/28385898/162281928-ec483379-75a4-4438-8c8f-18a5308a6f08.png)

**Comment by eu-genia** [comment]
now i see. this comes because 90% of EthioSPaRe mss do not comply with the schema, I have not yet been through them, they all have to be revised, only the institutions that start with A. so there are many schema validation issues. I can comment the problematic bit out , it does not belong here anyway.
https://github.com/BetaMasaheft/Manuscripts/commit/87fbfa69a7717193e9b6f1e425b9fa7ff4bfc569
