### ISSUE TITLE
Apocalypse of Peter and related works

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2068]
A part of the Apocalypse of Peter (LIT1127Apocal, not known as such in the Ethiopic literature) is contained in a text starting as: ዳግም፡ ምጽአቱ፡ ለክርስቶስ፡ ወትንሣኤ፡ ምውታን። ዘነገሮ፡ ለጴጥሮስ፡ እለ፡ ይመውቱ፡ በእንተ፡ ኃጢአቶሙ፡ እስመ፡ ኢዓቀቡ፡... (Abbadie 51 and Tanasee 35), it appears in EAE but I was not able to find a record for it in Bm (but the text that follows it in Abbadie 51 is in Bm, LIT2132OntheJ). Probably we need a new  record for that.

**Comment by eu-genia** [comment]
LIT1254Dagemm

**Comment by eu-genia** [comment]
PS I cheat: for records that I know for sure were indexed in the EAe I still check my old file, https://docs.google.com/spreadsheets/d/1a0LtliOVuXoRcDhgj3p5V1Z2i-M5k5_MkT6YgPgh04s/edit?usp=sharing

**Comment by DenisNosnitsin1970** [comment]
thanks!
