### ISSUE TITLE
rename INS0970LeipzigUB

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2070]
I have now noticed that this institution was created outside of app and without checking the "new" folder, resulting in two institutions having the same number. Please rename as 0972 the entry, the id, and where it is pointed at, to avoid confusions (this is not as important as in works but still we tend to reserve new numbers to new records)

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Institutions/issues/54#issuecomment-1082988148_

**Comment by eu-genia** [comment]
now it should become 0974 or whatever the first free number is, as new institutions have been added in the meanwhile

**Comment by vitagrazia81** [comment]
Thanks Zhenia and Dorothea for your notifications. I will rename it.

**Comment by eu-genia** [comment]
Dear Vita, please do not forget to update the manuscript records pointing to UBL, as far as I can see, these have not been corrected and point to the ID which no longer exists. Thank you!

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/1624/files
