### ISSUE TITLE
visualisation error

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2071]
I think that `<dimensions type="leaf" unit="mm" xml:id="leafdim">` (which is according to the guidelines) leads to a visualisation error. I tested with RDW003 and RDW004. The error is still present in many manuscripts, for example of the Bruce collection, e.g. https://betamasaheft.eu/manuscripts/BDLbruce90/main
@eu-genia

**Comment by thea-m** [comment]
I think the problem is more than one dimensions element. This is also relevant for scrolls, for example RDW-005, -006 and -007. 
I commented out the elements so that the records are visible online for now @LeonardBahr

**Comment by eu-genia** [comment]
This was because I edited in the visualization for outer dimensions https://github.com/BetaMasaheft/Documentation/issues/2061 but forgot the option for leaf dimensions
Should be fixed now

**Comment by eu-genia** [comment]
(for the future: make an issue with the error, do not lose time commenting out! I can usually see the problem from the error report)

**Comment by eu-genia** [comment]
no wait now it works with 1x outer and 1xleaf, I still have to add the possibility of multiple outer and leaf dimensions, so this remains open for now

**Comment by eu-genia** [comment]
ok fixed

**Comment by eu-genia** [comment]
ps i did not go through the records where dimensions were commented out, these have to be restored
