### ISSUE TITLE
Griaule/Mondon-Vidailhet shelfmarks and IDs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2072]
We currently have records for only two manuscripts of each collection, but I noticed a possible issue.
We have the manuscripts in folders named Griaule/Mondon-Vidailhet, their Griaule/Mondon-Vidailhet shelfmarks are the primary ones listed in the records, and are reflected in their IDs. However, they have all received "Éthiopien" shelfmarks which - according to the website - seem to be the ones primarily used by the BnF. We give these in `<altIdentifier>`. As our policy is to follow the libraries' convention as much as possible, I think that we should change the primary shelfmark to the Éthiopien one, and switch the Griaule/Mondon-Vidailhet shelfmarks to `<altIdentifier>`.  In principle, it would probably be better to integrate them into the Éthiopien folder and use et in future IDs - but I realise that using the Griaule/Mondon-Vidailhet abbreviation there is useful for orientation. What do you think?
(For instance, we also refer to BnF Éthiopien 677 by this shelfmark, not its old Trocadéro shelfmark.)
@DenisNosnitsin1970 @eu-genia

**Comment by thea-m** [comment]
@abausi Maybe you have some input on this? Should the primary shelfmark used by us be "Éthiopien" or Griaule/Mondon-Vidailhet?

**Comment by abausi** [comment]
I think we should definitely use the "Éthiopien" as primary shelfmark, 
prevailing on others, wich are secundary from the point of view of the 
library, even if this latter provides an immediate hint at the catalogue.

Il 14.04.2022 10:59, thea-m ha scritto:

**Comment by thea-m** [comment]
Thank you, then I'll go ahead with the change.
