### ISSUE TITLE
Add images to Cambridge mss

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2075]
For the following Cambridge manuscripts already included in our data, images are available. It would make sense to link to them in the records. @eu-genia , what would be the best way? Is it possible to link via IIIF manifest, or should we just add a facsimile element?

CamAdd1569
https://cudl.lib.cam.ac.uk/view/MS-ADD-01569/1

CamAdd1570
https://cudl.lib.cam.ac.uk/view/MS-ADD-01570/1

CamAdd1889
https://cudl.lib.cam.ac.uk/view/MS-ADD-01889/1

CamAdd3682
https://cudl.lib.cam.ac.uk/view/MS-ADD-03682/1

CamAdd18881
https://cudl.lib.cam.ac.uk/view/MS-ADD-01888-00001/1

CamAdd18882
https://cudl.lib.cam.ac.uk/view/MS-ADD-01888-00002/1

CamOr1878
https://cudl.lib.cam.ac.uk/view/MS-OR-01878/1

CamOr1885
https://cudl.lib.cam.ac.uk/view/MS-OR-01885/1

**Comment by eu-genia** [comment]
Yes, IIIF is available, so we can simply link the `idno facs` 
the iiif links are hidden behind the IIIF logo
![image](https://user-images.githubusercontent.com/17987728/163393513-8dd9a7a5-5e5b-438d-8be2-31d3df9258c1.png)

https://cudl.lib.cam.ac.uk//iiif/MS-ADD-01569
etc

**Comment by eu-genia** [comment]
but let me look into it a bit first

**Comment by thea-m** [comment]
Thank you!

**Comment by thea-m** [comment]
And the same question for Princeton, e.g. these and more: 
PRet00071
https://findingaids.princeton.edu/catalog/C0776_c00071

PRet00076
https://findingaids.princeton.edu/catalog/C0776_c00076

**Comment by thea-m** [comment]
And Tübingen, currently added in facsimile.
e.g. 
UBTaeth2
http://idb.ub.uni-tuebingen.de/opendigi/MaIX2

UBTaeth19
http://idb.ub.uni-tuebingen.de/opendigi/MaIX19

(It's really not urgent, I was just going through the images now as I was looking whether the list needed updating, so I note here whatever I notice)

**Comment by eu-genia** [comment]
- [x] Cambridge
- [x] Tuebingen
- [x] Princeton
- [x] Sinai

**Comment by eu-genia** [comment]
- [ ] Cambridge
- [ ] Tuebingen
- [ ] Princeton

**Comment by eu-genia** [comment]
Cambridge and Princeton are OK.
For Tuebingen I have a problem that the app transforms the http:// address to https://, but the manifest is stored on a http:// site, have not yet found a way to get around.

**Comment by eu-genia** [comment]
UPD I found the http:// issue but still the IIIF from Tuebingen is not valid... I am trying to figure out if there is a way around. It does get loaded to mirador at http://iiif.gdmrdigital.com/mirador/ but not to https://universalviewer.io/uv.html?manifest=http://idb.ub.uni-tuebingen.de/opendigi/MaIX2/manifest so there may be something with the manifest itself. Still the central mirador takes it so ours should too...

**Comment by eu-genia** [comment]
![Screenshot_20220415-114845_Chrome](https://user-images.githubusercontent.com/17987728/163556459-3b59ca38-7e50-4c18-9c98-7324767590fa.jpg)

**Comment by eu-genia** [comment]
I can try to contact TUB and ask if they are interested in moving to https, for now nothing we can do.

**Comment by eu-genia** [comment]
I wonder if Princeton records should be all renamed, now the IDs/filenames are not the shelfmarks but the digital ids at Princeton server, not very convenient

**Comment by thea-m** [comment]
Thank you! The current Princeton IDs also have the problem that (presumably because they start with PR), when typing them in the URL directly as https://betamasaheft.eu/PRet00001 (as I always access sites...), there is a redirection to https://betamasaheft.eu/persons/PRet00001/main. 
I also think that it would be good if you included a change element for the work you carried out in them, why let it go unacknowledged :)

**Comment by eu-genia** [comment]
This is because the app thinks all IDs that start with L are works, all IDs that start with PR are persons etc. We can use PUL as prefix

**Comment by eu-genia** [comment]
Sinai at `loc.gov` is also possible now

**Comment by eu-genia** [comment]
Tuebingen has switched to https so images can be linked in `facs `as well

**Comment by eu-genia** [comment]
having several set of canvases calculations is impractical, much better to have a separate function for them
