### ISSUE TITLE
General ID protective prayer

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2076]
Maybe this is a question to which the answer already exists, but I didn't find it.
I think it would be useful to create a general ID for a protective/magic prayer for cases in which no text, content or images are available. We have a general ID for ʾasmāt, but even that would be too specific here. 
Or did we have another solution for such cases that I forgot? 
@DenisNosnitsin1970 @eu-genia @DariaElagina

**Comment by DenisNosnitsin1970** [comment]
Do you mean cases when a catalogue just says only "protective/magical prayer"?

**Comment by thea-m** [comment]
yes, like here:
![image](https://user-images.githubusercontent.com/19650382/164001959-a3f36ccc-fbbb-49f5-a627-88237738b5a7.png)

**Comment by eu-genia** [comment]
I am not sure we have an answer. I see that in BNFet170 (similar case?) e.g. you simply did not use any `ref `for the `title`.  Would you suggest to create a NAR record?

**Comment by thea-m** [comment]
Good, then I didn't miss it. A narrative unit would be another possibility. I felt that in analogy to the asmat record a general record would be easiest to use.

**Comment by DenisNosnitsin1970** [comment]
I would rather stay away from a narrative unit, because there is no information for that eather. No ref for the title would be better, in my opinion.

**Comment by eu-genia** [comment]
OK for a very general record for me
