### ISSUE TITLE
Dersana Madhane Alam

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2077]
I think we miss an Id for the work that is called Dersana Madhane Alam (at least I was not ), 
that includes a number of homilies and the work called "Book of the Commemoration of the Saviour of the World", in turn consisting of the hagiography of St Maba'a Seyon (Acts LIT1475GadlaM and Miracles LIT6576MiraclesMabaSeyon). Dersana Madhane Alam exists in various versions (one of them is widely represented in Ethio-SPare mss, another was published by the EOTC).
There are a few works with similar titles to which Dersana Madhane Alam is sometimes applied (LIT5020Hemamatihu, LIT6193HomiliaryPassions), but they are different.

**Comment by thea-m** [comment]
It sounds reasonable. When you create the new record and possibly disambiguate the existing ones, it would be very helpful to include a descriptive abstract, in which the situation is explained.

**Comment by eu-genia** [comment]
see also https://github.com/BetaMasaheft/Documentation/issues/2007
https://github.com/BetaMasaheft/Works/pull/744
https://github.com/BetaMasaheft/Works/pull/745

what is in the end the ID of the Dersan?
The Book of Commemoration is LIT1973Mashaf, and what is the Dersan?

**Comment by DenisNosnitsin1970** [comment]
LIT6618DersanaMadhane for unspecified version, LIT6193HomiliaryPassions for Dersan.

**Comment by eu-genia** [comment]
I now discovered also LIT1291Dersan, it seems that the abstract there needs to be fixed

**Comment by DenisNosnitsin1970** [comment]
This is a different one.
