### ISSUE TITLE
ID for magic recipes?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2080]
BLorient570 contains a longer list of magic recipes (if I understand it well) on ff. 129ra-131ra.
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_570_f001r

They are introduced by the title Maṣḥaf ṭəbab za-maṣʾa ʾəm-gəbṣ - this makes me wonder whether we should treat this collection as a coherent composition that should receive an ID. What do you think?
@DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
I think it deserves an ID.
