### ISSUE TITLE
new record creation: careful

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2082]
Dear @thea-m @DenisNosnitsin1970 

I notice that for some reason when creating new record through the app multiple records are created and only one of them is downloaded and synchronized.

Thus, we have now on the app, e.g. 
![image](https://user-images.githubusercontent.com/17987728/164455983-8152bcd9-abb1-4d40-a9ba-acc91b49375d.png)

![image](https://user-images.githubusercontent.com/17987728/164455873-aeb20da4-5a0d-435e-8f7f-533c2f231d67.png)
(you only see in github the files which you downloaded and committed/pushed, but in the backend I can see multiple doublets)

Please when creating a new record through the app, only click the "create" button once, then wait till the download window appears and download once.
If for some reason the download window does not appear (it sometimes takes a bit of patience) and you have already clicked the "create new entry" button, do not click it again.  Open an issue and I will get you your file.

**Comment by thea-m** [comment]
Thank you! Strange...I'm relatively sure I did not impatiently click six times for poor Adara Giyorgis 😅

**Comment by eu-genia** [comment]
There is also something strange with Walda Zagabrǝʾel created twice by DR on 16-02 - none of the two versions (PRS13705 and 13706) exists on github, both are empty

**Comment by eu-genia** [comment]
OK I think I found it now as PRS13725WaldaZ

**Comment by eu-genia** [comment]
There are also some stubs from 9-03 that have not been synced I believe
PRS13773Zamesraq (DR)
PRS13772BatraM (DR)
PRS13771ZamanfasQ (DR)
are they in work?

**Comment by thea-m** [comment]
Yes, they're on DR_22_03_BLorient760. I was planning to make the PR at the same time as the manuscript PR (where I still need to do something), but it can be done now if that's inconvenient, the person records are done.

**Comment by eu-genia** [comment]
thats fine ) just wanted to make sure once i was comparing the lists

**Comment by DenisNosnitsin1970** [comment]
Sorry for intervening, just for interest, Walda Zagabre'el, is the name correct? One would expect Walde Zagabre'el or very common Walda Gabre'el

**Comment by thea-m** [comment]
f. 87vc
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_674_f001r
![image](https://user-images.githubusercontent.com/19650382/164676064-b6aa712a-897d-44a7-9b5d-1a76908d24a9.png)
Quite possible that it is something else, what would be your interpretation?

**Comment by DenisNosnitsin1970** [comment]
Indeed this is like you transcribed. Unless a small darker area near the upper right area of ደ is the trace of an erasure. But I hypothesize.

**Comment by eu-genia** [comment]
I have looked at the backend and can see that recently

@CarstenHoffmannMarburg has created
PRS14458Zamaryam 
PRS14459Zamaryam

PRS14562EssetaSǝllase
PRS14563EssetaSellase_ (this latter is also synced to GitHub, in spite of the underscore)

PRS14530WaldaMaryam
PRS14531WaldaMaryam
PRS14533WaldaMaryam (this latter is also synced to GitHub)

LIT7045Colic
LIT7046PrayerColic

@DenisNosnitsin1970 has created
PRS14497HamaraKidan
PRS14498HamaraKidan

LOC7442RegbayMadabay
LOC7445RegbayMadabay (this second is synced)

LOC7443Alaqma
LOC7446Alaqma (this second is synced)

@karljonaskarlsson has created
PRS14511Pistis
PRS14512Pistis

Please check: are all needed? All are currently present in the system (not on GitHub except for those synced)

Whenever you create something in the app it is IMMEDIATELY stored. Please do not click twice. If you have not downloaded a record you created just type betamasaheft.eu/ your new ID .xml to download and sync. Thank you.

**Comment by eu-genia** [comment]
Please let me know if any of these should be removed.

**Comment by eu-genia** [comment]
(Also if you have created a record in error, or assigned a wrong ID as in the case of PRS14562EssetaSǝllase - you either must download and merge and then delete or notify me to clean the app, thank you!)

**Comment by CarstenHoffmannMarburg** [comment]
> PRS14562EssetaSǝllase
> PRS14563EssetaSellase_ (this latter is also synced to GitHub, in spite of the underscore)

ʾƎsseta Śǝllāse is a female owner of BLorient̀2959. I did not know that my first attempt resulted in an ID and for this reason I created a new one. I described the problem in https://github.com/BetaMasaheft/Persons/pull/913. One of the two records can be deleted. If the underscore is a problem, I should probably update PRS14562EssetaSǝllase and delete PRS14563EssetaSellase_ .

**Comment by CarstenHoffmannMarburg** [comment]
> PRS14533WaldaMaryam (this latter is also synced to GitHub)

PRS14533WaldaMaryam is an owner in BLorient5423 and should be kept.
I have not found PRS14530WaldaMaryam or PRS14531WaldaMaryam. They have been surely created by mistake, because there is no other Walda Māryām listed in Strelcyns catalogue and all the three record have the same date (19th century, but 430 and 431 without any content). PRS14530WaldaMaryam or PRS14531WaldaMaryam can therefore be deleted. I apologize for any confusion!

**Comment by CarstenHoffmannMarburg** [comment]
> LIT7045Colic
> LIT7046PrayerColic

Are both correct records for two distinct prayers in BLorient11764 (Cf. https://github.com/BetaMasaheft/Works/pull/1164).

**Comment by CarstenHoffmannMarburg** [comment]
> @CarstenHoffmannMarburg has created
> PRS14458Zamaryam
> PRS14459Zamaryam

The name Zamāryām is attested twice in a colophon to a synaxary in BLorient2082. For this reason, I created to IDs, unless it cannot be excluded, that both refer to the same person. I have outlined the problem in ˇhttps://github.com/BetaMasaheft/Persons/pull/869.

**Comment by eu-genia** [comment]
> > PRS14562EssetaSǝllase
> > PRS14563EssetaSellase_ (this latter is also synced to GitHub, in spite of the underscore)
> 
> ʾƎsseta Śǝllāse is a female owner of BLorient̀2959. I did not know that my first attempt resulted in an ID and for this reason I created a new one. I described the problem in [BetaMasaheft/Persons#913](https://github.com/BetaMasaheft/Persons/pull/913). One of the two records can be deleted. If the underscore is a problem, I should probably update PRS14562EssetaSǝllase and delete PRS14563EssetaSellase_ .

PRS14562EssetaSǝllase is more problematic as it has a non-ASCII symbol ǝ in the name, which for HTML stands for %C7%9D and cannot be rendered. 

But you can rename PRS14563EssetaSellase_ to PRS14563EssetaSellase

**Comment by CarstenHoffmannMarburg** [comment]
> But you can rename PRS14563EssetaSellase_ to PRS14563EssetaSellase

OK. I will open a new branch and change the name of the record. The person is owner of BLorient12959.

**Comment by karljonaskarlsson** [comment]
> I have looked at the backend and can see that recently
> 
> @CarstenHoffmannMarburg has created PRS14458Zamaryam PRS14459Zamaryam
> 
> PRS14562EssetaSǝllase PRS14563EssetaSellase_ (this latter is also synced to GitHub, in spite of the underscore)
> 
> PRS14530WaldaMaryam PRS14531WaldaMaryam PRS14533WaldaMaryam (this latter is also synced to GitHub)
> 
> LIT7045Colic LIT7046PrayerColic
> 
> @DenisNosnitsin1970 has created PRS14497HamaraKidan PRS14498HamaraKidan
> 
> LOC7442RegbayMadabay LOC7445RegbayMadabay (this second is synced)
> 
> LOC7443Alaqma LOC7446Alaqma (this second is synced)
> 
> @karljonaskarlsson has created PRS14511Pistis PRS14512Pistis
> 
> Please check: are all needed? All are currently present in the system (not on GitHub except for those synced)
> 
> Whenever you create something in the app it is IMMEDIATELY stored. Please do not click twice. If you have not downloaded a record you created just type betamasaheft.eu/ your new ID .xml to download and sync. Thank you.

For my case, PRS14511Pistis can be deleted. I was not able to download it and tried again to create a file (for the future, I have taken to heart how such cases should be handled correctly)

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 please let me know on your records
PRS14497HamaraKidan
PRS14498HamaraKidan

LOC7442RegbayMadabay
LOC7445RegbayMadabay (this second is synced)

LOC7443Alaqma
LOC7446Alaqma (this second is synced)
