### ISSUE TITLE
A person record for deletion

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2083]
Can we delete https://betamasaheft.eu/persons/PRS7954Proclus/main? It doesn't serve any purpose, we can use https://betamasaheft.eu/persons/PRS7955Proclus/main.
@thea-m @eu-genia

**Comment by eu-genia** [comment]
sure, this is clearly a doublet, EAEIV945a has "Proclus, patriarch of Constantinople, who died in 446", so the same person
