### ISSUE TITLE
A disappeared file

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2084]
I wanted to use this record https://betamasaheft.eu/works/LIT1764Legend/main but the file doesn't exist in my GitHub folder. What should I do?

(Also, long time I created an issue on the texts concerning the True Cross, I cannot find it now)

@thea-m @eu-genia

**Comment by eu-genia** [comment]
does this answer your question? (this is your issue which was under Works, moved here)
https://github.com/BetaMasaheft/Documentation/issues/1619
you suggested to delete LIT1764Legend  )
please refer to LIT6171HolyCross
