### ISSUE TITLE
Manuscripts from the Windsor Castle

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2087]
I would like to provide in the {listWit} in a work record a reference to the manuscript from the Windsor Castle (see the attached catalogue by Ullendorff). Is it possible to do it?
[41460275.pdf](https://github.com/BetaMasaheft/Documentation/files/8550390/41460275.pdf)

**Comment by eu-genia** [comment]
sure ) go ahead ) (these are of course just stubs, not true descriptions)
