### ISSUE TITLE
cannot create new narrative unit

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2088]
> Thank you very much Dorothea for trying to store a new file!
> 
> Unfortunately NAR0183Qene could not be saved
> 
> This is the first error which occurred Collection /db/apps/expanded/narratives/new not found. Could not locate collection: /db/apps/expanded/narratives/new, feel free to copy it and send it to info@betamasaheft.eu.
> 
> [create another entry](https://betamasaheft.eu/newentry.html?collection=narratives)

any ideas? :) I believe it is the first time I get this error.
(Authority and work creation works)

**Comment by thea-m** [comment]
(In any case, I wanted to create a narrative unit called EtanaMogar, not Qene, so I don't mind if it cannot be retrieved, but I wait with creating it without the app in case it's better to retrieve and rename.)

**Comment by eu-genia** [comment]
for some reason there was no /new folder under narratives so nothing to retrieve. should be ok now (or after the next reboot, but probably already now)

**Comment by thea-m** [comment]
Thank you! Now I get 
Thank you very much Dorothea for trying to store a new file!

Unfortunately NAR0183EtanaMogar could not be saved

This is the first error which occurred Write permission is not granted on the Collection. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection., feel free to copy it and send it to info@betamasaheft.eu.

**Comment by eu-genia** [comment]
"Write permission is not granted" error happens when the app has logged you out.

**Comment by eu-genia** [comment]
you should try to log out and log in
