### ISSUE TITLE
Life and teachings of Maqābis of Hor

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2095]
I believe there is no work record for the life of Maqābis (apparently also called Maqārəs in the text) of Hor, attested in BLorient770 and D'Abbadie 59 (both digitised). I also could find no references at all to this text in the EAe or Kinefe Regb. I would suggest to create a work record, but maybe I'm missing something?
@DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
I have never heard of Maqabis, if not a mistake for Maqares, possibly one of the Egyptian monks.

**Comment by eu-genia** [comment]
I have checked both MSS and both do say መቃቢስ in the incipit title.
http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_770_f001r
https://gallica.bnf.fr/view3if/ga/ark:/12148/btv1b100884152/f5

![image](https://user-images.githubusercontent.com/17987728/165493620-515f6b16-b344-4092-ac63-cd4e0ee437b5.png)

And no, we don't have this name in the EAe at all. (Neither Hor).
To my ear both sound "foreign"...

There is a St Maqares in the EAe from monastic genealogy of Abiya Egzi (PRS6692Maqares.) but I think the one in the genealogy is actually PRS6427Macarius, i.e. the Egyptian Macarius the Great.

So I would say yes, new work new person.

**Comment by eu-genia** [comment]
@MarcinKrawczuk have you encountered such saint in your research?

**Comment by MarcinKrawczuk** [comment]
I will think about over the weekend. As for Hor, I'm attaching two pages from Amélineau, but it's not very illuminating.
[Hour.pdf](https://github.com/BetaMasaheft/Documentation/files/8574173/Hour.pdf)

**Comment by eu-genia** [comment]
PS just a note, the name Maqābis in Ethiopic tradition is also used for "Maccabeus", from the Book of Maccabees
Dillmann: https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%88%98%E1%89%83%E1%89%A2%E1%88%B5&id=L4a5b0611a5fd432b86429c2db09d539f
(see also Horowitz p. 195 https://www.degruyter.com/document/doi/10.1515/zava.1906.19.2.194/html),

**Comment by eu-genia** [comment]
Abba Maqābis is commemorated in the Synaxary (also Budge) on 11 Yakkatit, but there is no Vita (just "And on this day also is celebrated the commemoration of Abraham the bishop, and Kanti, and Abba Makabis (Maccabaeus) the monk. "

So Budge also interprets the name as Maccabaeus. I think the one in Budge is probably the same as in BLorient770 etc

**Comment by eu-genia** [comment]
Sorry I am wrong, this one is commemorated on 7 Hamle:
"And on this day also died the holy father Abba Makabis (Maccabaeus), who fought the
fight in the desert of Hur and pleased God." (Budge)
