### ISSUE TITLE
A problem with LIT6522Petros

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2099]
When I look at LIT6522Petros in my Atom (the branch is master) everything seems OK. But the link is not working:
https://betamasaheft.eu/works/LIT6522Petros and the work record is not "visible" where it should be (here for example https://betamasaheft.eu/persons/PRS7806PeterI). 

@eu-genia @thea-m

**Comment by eu-genia** [comment]
the webhook did not expand, should be ok now
