### ISSUE TITLE
EMIP and Bodleian

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2101]
As in https://github.com/BetaMasaheft/Documentation/issues/2100
EMIP has digitized Bodleian MSS, 

I suggest the `facs `information and the `altIdentifier `should be moved/merged, but I am still not 100% sure what to do with the EMIP records if the EMIP people want to see them where they are...  leave a stub with a link? 

In any case I am against having two records describing the same manuscript in two different places...

EMIP03185 = Bodleian Bruce 87 = BDLbruce87
EMIP03186 = Bodleian Bruce 88 = BDLbruce88
EMIP03187 = Bodleian Bruce 89 = BDLbruce89
EMIP03188 = Bodleian Bruce 90 = BDLbruce90
EMIP03189 = Bodleian Bruce 91 = BDLbruce91
EMIP03190 = Bodleian Bruce 92 = BDLbruce92
EMIP03191 = Bodleian Bruce 93 = BDLbruce93

@thea-m @DenisNosnitsin1970

**Comment by eu-genia** [comment]
PS I do not see any images for these mss on the image server for the moment

**Comment by thea-m** [comment]
I agree that there should not be two parallel descriptions. In similar cases in the past, we have deleted one of the concerned records to avoid the danger of duplicate information. Of course, as you wrote, this may lead to people searching for the record in the expected place and not finding it.
I am still uncomfortable with keeping empty records that contain only a link. I imagine that the relation betmas:formerlyAlsoListedAs could also be used for manuscripts, but that will not help if someone looks for a manuscript in the folders and not on the app. Maybe we could create a page on the app that lists all known cases to raise awareness and encourage people to look there? 
But maybe better to collect more opinions.
For the Bruce manuscripts, I would be in favour of having as only/main record the BDLbruce files.
(As far as I know, the Bodleian Library has a very strict image policy, it's quite possible that we are not allowed to publish the images.)

**Comment by eu-genia** [comment]
When Steve writes with the next image batch I will ask him for more details, I only discovered the Bruce and Chester Beatty "descriptions" by chance. 

I think that the ideal situation would be if IDs preserved as passive in the `betmas:formerlyAlsoListedAs `relation would resolve as links when called, or something like that, but this is a bit difficult, since the IDs actually do not exist any more when records are deleted.

I think I could eventually create a list somewhere on the app (passive, not dynamic, that I would update every now and then... And maybe one day I can also have a dynamic one...) with the list of all the passive elements, and maybe I could edit the error page which now says
```
XXX is not an available item.
Ids are case sensitive.
Try browsing or using simple or advanced search.
```

adding something like
`You believe the ID should exist or has existed in the past? Check this list for IDs that have been changed, moved or renamed
`

For the EMIP Bruce mss should we then add e.g. to `BDLbruce87 `etc

```
                     <altIdentifier>
                        <collection>EMIP</collection>
                        <idno>EMIP 3185</idno>
                     </altIdentifier>
```

and 
`<listRelation><relation name="betmas:formerlyAlsoListedAs" active="BDLbruce87" passive="EMIP03185"></relation></listRelation>`

and delete completely EMIP03185?

**Comment by DenisNosnitsin1970** [comment]
EMIP-shelfmarks can remain as additional idnos, but all these manuscripts are known as Bodleian Bruce (= BDLbruce), 
there is no reason to rename them or have two descriptions. Also, indeed, I wonder to which extent the EMIP shelfmarks may be official, in some cases.

**Comment by eu-genia** [comment]
Email from Steve 4.5.2021 for reference:


> Good morning, Zhenia (if I may),
> 
> I believe you are correct in all of your assumptions.  I will respond to several of them. It is a sign of both the complexity of our field--and of me becoming more cantankerous in my old age--that I cannot answer you briefly!
> 
> Yes, the digitization work of EMIP includes just about every configuration you can think of--and each one has a different set of issues related to it.
> 
> I have shot mss in the hands of individuals.  I have shot mss in institutions.  I have brokered the digitization of mss in institutions.  I have brokered the digitization of mss temporarily passing through the hands of dealers.  I have digitized hundreds of microfilmed manuscripts.  I have gathered not a few digitized microfilms from institutions who produced the image sets themselves (often releasing them in pdf form; often releasing them only in single images, which can be assembled into pdfs).  There are profound issues surrounding each of these categories that differentiate them from one another. My interest has never been to become a provider of images (though that naturally becomes an option after one has them).  In a few cases (Bodeleian, Cambridge, Edinburgh), holding institutions require signed agreements not to disseminate. That certainly has implications for what can be shared, but I have not taken that as the rule regarding whether I digitize them or whether I list them with an emip project number.  On the user side, we simply need what we need to do the work we are trying to do. The needs of holding institutions are different.
> 
> So among the EMIP image sets you will find mss in every category.  You are right in thinking that we cannot just post everything in the emip collection without regard to origins and stance of the holding institutions. But, for the most part, I did not organize the emip collection around the principles of the demands of institutions, i.e., things that can be shared go in the list and things that cannot be shared stay outside the list.  Rather the rule for inclusion or exclusion is simply did I (or one of my agents) shoot them.  
> 
> The one huge exception to granting access to others is around the IES collection (5,749 items).  With very few exceptions I have not passed on any of the images from there.  I have simply referred people either to the EAP or, better yet, to HMML for access and useage. [For some inexplicable reason the EAP folks decided to abandon the shelf list principle of organization in which we had put everything, and created a new numbering list.  This makes it virtually impossible to find mss by their IES shelfmark among the EAP holdings.]  I worked very hard to include HMML as an external (i.e., out of country backup site, with permission to share images on site.  [Regarding the other two catalogues that are still to come out regarding the IES collection, a couple of years ago I entered into an agreement with Jacopo to get those completed, but life has brought several disruptions to that plan.   Eventually it will happen.]
> 
> One might think it a simple matter to eliminate the EMIP designations and just retain the designation of the holding institution (Erho has long tried to do this with things I've deposited at HMML).  There are several reasons why this is a bad idea.
> 
> First, and most fundamentally, in the same way that an image set is different from a manuscript, a microfilm is different from a set of digitized images of microfilm frames.  This is not an esoteric distinction.  When it comes to missed shots, doubled shots, foliation errors, etc. any of those can happen at either level.  If I shoot a microfilm that has multiple missed shots and doubled shots (as is frequently the case) I or one of my workers has to go through a process of cleaning up the image set.  With each step to fix errors and clean up image sets, the distance between the various entities (the original ms or the microfilm of the ms or the digitized images of the microfilm of the ms or the manuscript) becomes greater and greater.  The difference between the entities is not insignificant.  Ownership is one filter to pass things through, but it is not the only one.  It has frequently happened that well-intentioned gate keepers try again and again to collapse these distinctions.  But they do so only to satisfy their own conceptions about what is of first importance.  For me, it is not about keeping the EMIP title in front of everyone.  For me it is about preserving those distinctions so that the user is in fact getting what they think they are getting, and if they are getting more than they expected because a step in the EMIP workflow gives them something different or maybe improved from the manuscript itself or any of the derivative images, then it seems only right to preserve that knowledge.  
> 
> All this very long diatribe to say that yes, it is fine to identify EMIP image sets by the names and shelfmarks of their holding institutions, but necessary to attach the EMIP label to the work in some way that will endure.  But, when people fail to understand the distinctions between entities (mss, microfilms, born digital sets, digitized microfilms, etc.) I find that in practice it is the EMIP label that gets lost.
> 
> I would argue that for most general users, access is a more important filter than some others. Who can consult mss in Northern Ethiopia?  Who can consult UNESCO or EMML microfilms of mss in Northern Ethiopia? Who can consult EMIP digitized images of microfilms of manuscripts in Northern Ethiopia?  The answers to these questions are vastly different.  Traveling to a monastery or church in Ethiopia offers the highest barrier to access.  But institutional barriers have for decades made it almost as impossible to access microfilm images of the manuscripts held in the Tanasee, UNESCO, Davies collections , Windsor palace, and dozens of our most prestigious libraries to mention just a few.  In every case, the barriers to getting the EMIP counterpart have been vastly lower.  
> 
> Some months ago, I wrote up and sent a long list of the various sources of the EMIP collection.  Around 100 owners and institutions.  It would be good if that were posted on Bm somewhere.  Eventually, it will be of even further help to log the various distinctions about the medium of the originals and the derivatives.  Even further, there are important stories about the scenarios in which the work was done.  Each of these details adds another dimension to the story and in some cases, these have implications for legalities and access, etc.  It is all way too complicated.  
> 
> You and I and others will shortly enter into another challenging set of decisions surrounding the EMDL collection of Dr. Meley.  It is fraught with intrigue, claims, ego, institutional territoriality, and obligations to granting agencies, and on and on.  These all have profound implications for people getting access to cultural heritage.
> 
> So to reiterate, IN BRIEF!, 
> 
> Yes, label things by holding institutions. Do not lose the EMIP designation, and more importantly don't forget that there are distinctions behind the labels that matter.
> 
> I and my team are still working to deliver to you hard drives with hundreds of corrected image sets.  We look forward to seeing those corrected image sets entered into the system.
> 
> Warm regards,
> 
> Steve
