### ISSUE TITLE
Malke'-hymn to Naʾakkʷǝto Laʾab

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2102]
I do not find Malke'a Naʾakkʷǝto Laʾab among the records. Does it exist? If no, I would create a record for this.

**Comment by thea-m** [comment]
There is this one, is that it?
https://betamasaheft.eu/works/LIT2834RepCh118/main

(Tricky name to search for.)

**Comment by DenisNosnitsin1970** [comment]
Indeed. Thank you!

**Comment by thea-m** [comment]
(If you are working on it anyway - maybe it would be useful to add the transcription variant with single or double k to all of the most relevant records - person, gadl, malkəʿ - to make future searching easier?)

**Comment by DenisNosnitsin1970** [comment]
In think Naʾakʷǝto is an incorrect form for Naʾakkʷǝto. It is the imperfect of causative basic stem and should be geminated (for jussive vocals would be a bit different), is it correct? I would keep only correct forms.

**Comment by thea-m** [comment]
I agree that it's incorrect, my point was that since it is used by people it could make sense to add this to the records so that they have a chance to find them.

**Comment by DenisNosnitsin1970** [comment]
If you want, we can assume the existence of the form Naʾakkuto, but the record was difficult to retrieve mostly because it was half-empty, with no fidel and no translation. If the record is properly filled, looking for it is not difficult.

**Comment by eu-genia** [comment]
it is filled now...

**Comment by DenisNosnitsin1970** [comment]
Thanks 👍
