### ISSUE TITLE
Deleted IDs list

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2103]
I think that the ideal situation would be if IDs preserved as passive in the `betmas:formerlyAlsoListedAs `relation would resolve as links when called, or something like that, but this is a bit difficult, since the IDs actually do not exist any more when records are deleted.

I think I could eventually create a list somewhere on the app (passive, not dynamic, that I would update every now and then... And maybe one day I can also have a dynamic one...) with the list of all the passive elements, and maybe I could edit the error page which now says
```
XXX is not an available item.
Ids are case sensitive.
Try browsing or using simple or advanced search.
```

adding something like
`You believe the ID should exist or has existed in the past? Check this list for IDs that have been changed, moved or renamed
`

**Comment by eu-genia** [comment]
Actually there is this page
https://betamasaheft.eu/deleted.html
but it does not seem to work as supposed; I can try to see if I can fix it

**Comment by eu-genia** [comment]
Ok now the list contains all the `betmas:formerlyAlsoListedAs` cases.
It used to take values only from the file `deleted.xml` which was supposed to be automatically populated by gitsync on merging but it seels it does not always work.
So I have left two lists at https://betamasaheft.eu/deleted.html, the new one, only reading from relations, and the old one, reading from `deleted.xml`.

(Another related problem is that the search also only looks in `deleted.xml`, this is why the majority of deleted records do not show up in search results.)

**Comment by thea-m** [comment]
Thank you, I think that's really important. Am I correct that the list of deleted items cannot be accessed through any menu? At least I didn't find it.

**Comment by eu-genia** [comment]
No, I don't think there is a menu. Needed? Where? Under Resources?
