### ISSUE TITLE
new record for miracle of St George

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2105]
I would like to create a new work record for a miracle of St George, Nr. 80 in Arras' edition
https://archive.org/details/miraculorumsgeor0000geor/page/108/mode/2up

and attested in BLorient687, ff. 91rc-91vc, about a Jewish woman who comes to the church of St George to be healed, gives birth to a snake and is protected by St George from her relatives. 

@DenisNosnitsin1970  @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Snake?! Ok...
