### ISSUE TITLE
error 500 BLorient633

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2110]
https://betamasaheft.eu/manuscripts/BLorient633/main
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BLorient633/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: concat($atomizable-values as xs:anyAtomicType?, ...) xs:string. Expected cardinality: zero or one, got 8. [at line 3497, column 17, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:supplied(element()) [4444:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [3465:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:del(element()) [4247:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [4483:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2681:9:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:colophon(element()) [4226:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1837:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4350:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [3060:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5497:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5541:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4343:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5438:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5748:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
The problem is here
```
 <supplied reason="undefined" resp="PRS10171Wright">
                           <persName ref="PRS3430DawitII">ዳዊት፡</persName>
                        </supplied> 
```
the code for now does not accept mark up inside of `<supplied>` as the simple string "ዳዊት፡" becomes a complex link, and this does not work with the `concat `function necessary to print the "?"

so either no `persName`, or `persName `around `supplied`
```
<persName ref="PRS3430DawitII"><supplied reason="undefined" resp="PRS10171Wright">
                           ዳዊት፡
                        </supplied></persName>
```
https://github.com/BetaMasaheft/Manuscripts/commit/d61056344a7e81834fe9391436092b9403102b43#diff-dd0ca223c866aaa6c45c004bd89c9b2cf5a9b92814ceccbd32fccc9200e3cbdd
