### ISSUE TITLE
records for salām-hymns

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2115]
BLorient590 (http://www.bl.uk/manuscripts/Viewer.aspx?ref=or_590_f001r) contains, following the Ṭabiba ṭabibān, many salām-hymns. I assume that all or many of them are identical to those transmitted in the Sənkəssār. 
I think that it would make sense to create individual work records for them, as they can be transmitted within different collections (Sənkəssār, Nagś, hagiographic dossiers etc.). This would start to lay a foundation for a better study of these works.
Do you agree? @DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
Of course, all texts appearing in different constellations must have an ID. Thank you!

**Comment by DenisNosnitsin1970** [comment]
Agreed.
