### ISSUE TITLE
BnF Éthiopien 146 not visualized on the App

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#2120]
Dear all,

there is a problem with visualization of [BnF Éthiopien 146](https://betamasaheft.eu/manuscripts/BNFet146/main). It would be nice to solve this issue when possible.

Thanks!
@eu-genia , @DenisNosnitsin1970 , @thea-m

**Comment by eu-genia** [comment]
Looks like the same issue as here https://github.com/BetaMasaheft/Documentation/issues/2110

**Comment by eu-genia** [comment]
OK the reason="explanation" is not foreseen by the app, I have temporarily removed it and will edit the code; the record can be visualized

**Comment by DariaElagina** [comment]
Thank you, @eu-genia !

**Comment by eu-genia** [comment]
Ok it is as I thought initially and as it was in #2110 - if there is a `reason `there may not be mark up inside of `supplied`
Or if mark up is necessary then there may be no `reason`
Maybe we should add to the guidelines that mark up inside of `supplied `(and other editorial tags) should be avoided
