### ISSUE TITLE
Golden Gospel of Ham

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#2123]
Dear @eu-genia, @DenisNosnitsin1970, @thea-m  ,

the Golden Gospel of Ham [(link)](https://betamasaheft.eu/manuscripts/DabraLibanosHamGG1/main) ist not visualized, a couple of weeks ago the description was there, but images were not available.

All best,

Daria

**Comment by eu-genia** [comment]
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/DabraLibanosHamGG1/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: substring-after($source as xs:string?, $search as xs:string?) xs:string. Expected cardinality: zero or one, got 2. [at line 2257, column 34, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:layout(item()*) [1955:17:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:layoutDesc(item()*) [4312:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5499:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5554:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5612:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4355:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5499:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5588:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [5612:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:codicologicalUnit(item()*) [4355:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5499:85:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5588:5:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4345:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5440:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5750:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1360:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
I once corrected the file to comply with the app a while ago
https://github.com/BetaMasaheft/Manuscripts/commit/ae9d35746acf169282ff7cee866633b9c08aed21
etc.
, but @thea-m and @nafisa-valieva wanted the changes to be reverted (https://github.com/BetaMasaheft/Manuscripts/pull/1525).

At that poiint, I manually corrected the expanded file to make it still viewable on the app, but at each expand from the app it gets overwritten.

**Comment by thea-m** [comment]
Yes, because a lot of thought went into this encoding and it should not be hastily edited (though of course it has to be!). @nafisa-valieva will look into this when she has time for this. Thank you!

**Comment by eu-genia** [comment]
On the developer side we also need to solve https://github.com/BetaMasaheft/Documentation/issues/2041 - it is a bit tricky, I have not yet managed

**Comment by eu-genia** [comment]
Now I have, the manuscript can be displayed as it is.
(It takes a while to load, and if the app is overloaded timeout error may potentially come up but it is not connected to any error in the data or the code, I can see the record now)
