### ISSUE TITLE
loci and titles of the third-levels msItems

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2128]
the loci in ms descriptions (in some MSS)
and titles of the third-levels msItems (always) are not active links 
e.g. ESmy009, ESmy005

![image](https://user-images.githubusercontent.com/17987728/169620518-c66e824d-8ebd-4bb3-ba71-6051dcf66e62.png)
The expanded tei has
```
<msItem xml:id="ms_i1.5.1">
<t:locus xmlns:t="http://www.tei-c.org/ns/1.0" from="8rc" to="9ra">Fols 8rc–9ra</t:locus>
<title type="complete" ref="https://betamasaheft.eu/LIT3586Miracle">Miracle of Mary: Miracle of Hildephonsus (Dexius) of Toledo</title>
```

e.g. MNC002
![image](https://user-images.githubusercontent.com/17987728/169638521-7b221044-1ae7-4c7b-95e8-63a8848e8164.png)

**locus and title ref must be active links**

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/1970#issuecomment-1133435486_

**Comment by eu-genia** [comment]
it seems that when the locus is expanded as `t:locus` it is not parsed while it is when the expanded TEI has simply `locus `as in BLorient485
```
<msItem xml:id="ms_i1">
<locus from="1r" to="101v">Fols 1r–101v</locus>
```
![image](https://user-images.githubusercontent.com/17987728/169625386-8e140277-fb1c-4af7-b304-960107da92c2.png)

**Comment by eu-genia** [comment]
ESmy005 viewer

HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/api/iiif/ESmy005/manifest: err:FORG0001 can not convert '100?' to xs:integer [at line 85, column 21, source: /db/apps/BetMasWeb/modules/locus.xqm] In function: xs:integer(item()) [-1:-1:/db/apps/BetMasWeb/modules/locus.xqm] locus:folio(xs:string) [78:48:/db/apps/BetMasWeb/modules/locus.xqm] iiif:locus(node()) [134:15:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:ranges(xs:string, node()) [144:8:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:rangeAndsubrange(xs:string, node(), xs:string, xs:string) [266:4:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:makeRanges(item()*, item()*, item()*, item()*) [547:12:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:rangeexistence(item()*, item()*, item()*, item()*) [291:30:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:Structures(item()*, item()*, item()*) [479:27:/db/apps/BetMasApi/specifications/iiif.xqm] iiif:manifest(xs:string*, xs:string*) [-1:-1:/db/apps/BetMasApi/specifications/iiif.xqm]

**Comment by PietroLiuzzo** [comment]
Instead of trying to reverse-engineer from the html view, looking at the module producing it would have quickly pointed you to a conscious and deliberate decision (hence not a bug) in the code, at line 1628-1635 of the `viewItem.xqm` module. Because many of these issues are probably related to some error in handling the code, introduced after the end of February and because this issue is not supported by any vetting from the team or research in commits and previous issues for the reason of this, I have only uncommented in the live application the lines in questions and made no commit to the source code.

**Comment by eu-genia** [comment]
thank you!
the locus is also deliberate?

**Comment by eu-genia** [comment]
the locus was also deliberate, commented out for consistency
