### ISSUE TITLE
Ǝlmasṭoʾagya

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#2135]
There are two measures to be taken concerning this text in the Clavis:

1) correct ʾƎlmasṭoʾagya > ʾƎlmasṭoʾagyā and in the fidal: እልመስጦኣግያ፡ > እልመስጦአግያ፡ (usial ambiguity due to different transcription system);

2) it should be further specified, because the text appears in two forms:
a) an ancient translation, probably from a Greek model: ትምህርተ፡ ኅቡኣት፡gez ([Tǝmhǝrta ḫǝbuʾāt](https://betamasaheft.eu/) gez,;
b) a much later corresponding text from Arabic Vorlage: እልመስጦኣግያ፡ ([ʾƎlmasṭoʾagya](https://betamasaheft.eu/) gez, [Introduction into the Mysteries](https://betamasaheft.eu/) en, [Mystagogy](https://betamasaheft.eu/) en).

We need (by two further separate Clavis numbers?) to be able to distiguish among them, still keeping a general entry when this is not possible. Note that both texts are already edited separately by Lifchitz.

Bibliography is also missing; at least, bm:Lifchitz1940textes should be given.

**Comment by DenisNosnitsin1970** [comment]
Now there are three relevant work records: for Temherta hebuat, for  Almastoagya and for text in the versions difficult to define. 
There is one problem: the work LIT1586Hayman Haymanota Abaw hat "Teaching of mysteries" as its part, it is expected to be the version Almastoagya, but actually it is not easy to understand quickly (Temherta hebuat cannot be excluded). In  LIT1586Hayman, there is a subpart: LIT1586Hayman#TemhertaHebuat. Should it be exchanged for LIT6688TeachingMysteries in the work record (to be further changed for one or another version in each individual manuscript of Haymanota Abaw), or be left as it is now?

**Comment by abausi** [comment]
Thank you Denis. Difficult question, to be answered on the basis of 
comparable cases, which certainly there are. We have in any case 
evidence of separate circulation of both versions, so that it can make 
sense to exchange LIT1586Hayman#TemhertaHebuat with 
LIT6688TeachingMysteries.

Il 30.05.2022 16:34, DenisNosnitsin1970 ha scritto:

**Comment by eu-genia** [comment]
subpart `LIT1586Hayman#TemhertaHebuat` cannot be _exchanged_; you can add a `corresp `to it, but in manuscripts containing Haymanota Abaw we according to our rules are supposed to refer to `LIT1586Hayman#TemhertaHebuat` even if it is the same as an independently circulating work.

**Comment by eu-genia** [comment]
(of course if the Temherta Hebuat inside of Haymanota Abaw may refer to different things then we need different textparts under `LIT1586Hayman`, each with its own `corresp`)

**Comment by eu-genia** [comment]
cp. https://github.com/BetaMasaheft/Documentation/issues/1467

**Comment by abausi** [comment]
It is fine: just let's follows what has been done in all similar cases.

Il 30.05.2022 19:29, Eugenia ha scritto:

**Comment by DenisNosnitsin1970** [comment]
I have made some corrections and changes to accommodate the information in an economic and practical way,  without creating new IDs for various versions of Haymanota abaw after the version of Temherta hebu'at (that would be the correct way according to the encoding rules, as far as I understand now, but this is a separate and big task). If necessary/possible, those dealing with ms of Haymanota abaw can always may a note and coment upon the version of Temherta hebuat.
