### ISSUE TITLE
visualisation of watermark

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2144]
The content of the element watermark is currently not visualised. Only its presence is visualised, e.g. in DSEthiop10, 
```
 <support>
                           <material key="paper"/>
                           <watermark>
                             Watermarks visible on <locus target="#120 #129"/>.
                           </watermark>
                        </support>
```
becomes 
![image](https://user-images.githubusercontent.com/19650382/170997309-981a37fa-e756-4aca-aacd-4fe7ab45e6db.png)

I think that if `<watermark>` has content, the content could be printed where there is now "yes" (which would then not be needed anymore, see also DSEthiop17, which has `<watermark>No watermarks.</watermark>`). If there is `<watermark/>` without content, the current visualisation can be kept. What do you think?
@eu-genia @DenisNosnitsin1970 
https://github.com/BetaMasaheft/Manuscripts/pull/1720#pullrequestreview-989129716

**Comment by eu-genia** [comment]
[done](https://github.com/BetaMasaheft/BetMas/commit/d41c210abd58c5de2c8f27aa9e742047eaa709e5)

**Comment by thea-m** [comment]
Thank you!
