### ISSUE TITLE
mixed up person records

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2149]
I think there is a mixup in the person records for Queen Eleni.
- this is the right one: https://betamasaheft.eu/persons/PRS3706eleni/main#PRS3706eleni?hi=%CA%BE%C6%8Eleni 
- this is the wrong one: https://betamasaheft.eu/persons/PRS3709eleni/main wrong because a) there is already the other entry PRS3706, b) I am quite sure that it should be Admas and not Adman for alt. name. 
- But the reference to https://betamasaheft.eu/works/LIT1608hoheta/main is correct in the sense that according to tradition Eleni/PRS3706, was the author. So that information should be moved to PRS3706, and in the LIT1608hoheta entry the direction should also be to PRS3706.

I hope my explanations make sense.

**Comment by thea-m** [comment]
Thank you! I will look into it soon

**Comment by eu-genia** [comment]
Thank you! the error is from the EAe index, as a result it has both 3706 and 3709 referring to the same person
We can delete 3709 and correct the references
(Eleni in BLorient686 is a completely different one, from Zamana masafent)
