### ISSUE TITLE
BnF d'Abb 54

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2151]
I am asking permission to create a file and basic description for BnF d'Abb 54, I have recently added this ms to a witness list and now it points to nowhere which kind of misses the point of adding it to the witness list. At a first glance, most work records are already in the database.
@eu-genia @DenisNosnitsin1970 @thea-m

**Comment by DenisNosnitsin1970** [comment]
Sure. Please go ahead.
