### ISSUE TITLE
RespStmt contributors

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2153]
The expand generates an RespStmt which lists contributors EXCLUDING those listed as editors
E.g.
![image](https://user-images.githubusercontent.com/17987728/175374020-48b5eeef-c26d-4279-8221-1fb01788be85.png)
```
 {
                            let $ekeys := $node//t:editor/@key
                            let $cwhos := $node/ancestor-or-self::t:TEI//t:change/@who
                            for $resp in distinct-values($cwhos[not(. = $ekeys)])
                            return
                                <respStmt
                                    xml:id="{$resp}"
                                    corresp="https://betamasaheft.eu/team.html#{$resp}">
                                    <resp>contributor</resp>
                                    <name>{$expand:editorslist//t:item[@xml:id = string($resp)]/text()}</name>
                                </respStmt>
                        }
```
Is there a reason for this exclusion? Why the attribution of content is not to all those who contributed, taken from all change elements, also editors?
Do you know the reasons @thea-m @DenisNosnitsin1970 ?

**Comment by eu-genia** [comment]
(I can correct the code so that in the future the attribution of contents will list all names but maybe I am missing something)

**Comment by thea-m** [comment]
I don't remember any reasons for this - there must have been a discussion that I forgot/don't find now. 
I believe https://github.com/BetaMasaheft/Documentation/issues/1213 and https://github.com/BetaMasaheft/Documentation/issues/1214 dealt with different matters, I think.

**Comment by eu-genia** [comment]
Ethio-SPaRe is a different matter, yes.
I find it quite confusing that the "Attribution of content" does not list the persons who created the entry in the first place...

((There is also an issue related to Ethio-SPaRe: all change elements before 2016 in the display get automatically enhanced by "in Ethio-SPaRe", meaning we cannot add any "historical" change element referring to a pre-2016 event))

**Comment by eu-genia** [comment]
I have now added the editors to the expand code (the changes will only show in the newly expanded records)
![image](https://user-images.githubusercontent.com/17987728/175504086-e3c16992-1e1c-47fd-bc22-e86c055d1d3b.png)
