### ISSUE TITLE
Or. 691: dating

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#2159]
The dating of this MS (BL Or. 691) as given by Wright is probably wrong. The manuscript could in fact date, contrary to Wright's statement, to the thirteenth century. See the independent and convergent conclusions by A. Bausi ‘I colofoni e le sottoscrizioni dei manoscritti etiopici’, in Anna Sirinian, Paola Buzi, and Gaga Shurgaia, eds, Colofoni armeni a confronto. Le sottoscrizioni dei manoscritti in ambito armeno e nelle altre tradizioni scrittorie del mondo mediterraneo. Atti del colloquio internazionale. Bologna, 12–13 ottobre 2012, Orientalia Christiana Analecta, 299 (Roma: Pontificio Istituto Orientale, 2016), 233–260: 245-246 (with reference to A. Bausi, La versione etiopica degli Acta Phileae nel Gadla samāʿtāt, Supplemento agli Annali, 60–61 (2000–2001), 92 (Napoli: Istituto Universitario Orientale, 2002), 8-9, n. 18), publishing and commenting also on this colophon; and lastly by Eyob Derillo, ‘Exhibiting the Maqdala Manuscripts: African Scribes: Manuscript Culture of Ethiopia’, African Research & Documentation, 135 (2019), 102–116: 106. So, this possibility should at least be mentioned and probably given as the most likely one.

**Comment by DenisNosnitsin1970** [comment]
Ok, I will have a look.
