### ISSUE TITLE
Clarifying the use of corresp and ref

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#216]
The use of @corresp and @ref should be standardized ( `<witness>` should be used with @ref as `<title>` etc. )
It could also be useful to have a concise overview of when to use @ref and @corresp, with or without #, in one place, not scattered throughout the guidelines as currently

**Comment by PietroLiuzzo** [comment]
For the second part, could you perhaps collect and reorganize the guidelines accordingly? I agree that some. In my understanding, @ref for titles is given because we provide the connection to the work that title designates, while the witness is actually a mss of which we provide a @corresp. # is used to reference an id, we could restrict its use to links internal to the current file. it would be useful also here to see where the inconsistencies are in guidelines and fix them.

**Comment by thea-m** [comment]
@ref as an attribute is used with the following elements:
`<placeName>`:   
 ```xml
 Historical note on the monastic community of <placeName ref="INS0302SanStefano"/>.
```

`<origPlace >`:   
 ```xml
<origPlace ref="INS0327DHE"/>
```
 
`<title>`:  
 ```xml
<title type="complete" ref="LIT3309Qerellos"/>
```

`<persName>`:   
```xml 
Collected by <persName ref="PRS5592Isenberg">Carl Wilhelm Isenberg</persName>
```

`<repository>`:            
```xml 
<repository ref="INS0333SBB"/> 
```

`<country>`,` <settlement>`, `<region>`:
   ```xml 
<country ref="gn:2635167"/>
               <region ref="gn:6269131"/>
               <settlement type="city" ref="gn:2643743"/>
 ```

`<item>` (in additions):  
```xml
<item xml:id="a2" xml:lang="am" ref="NAR0001gwǝlt"> 
```

**Comment by thea-m** [comment]
`<ref>` as element

- `<ref>` with attribute @target is used to point to any xml:id within the same record, or to external resources by adding the URL:

xml:id within the same record: 
```xml
Introductory expressions of direct speech in <ref target="#ms_i5"/>
```
In this case, # is used before the referred entity, since it points to an xml:id in the same record. 

External resource:
```xml

Another version of this homily is contained in BnF Arabe 148, fol. 1v-19v.
                        <ref target="http://archivesetmanuscrits.bnf.fr/ark:/12148/cc89421j/cd0e79"/>
```

- `<ref>` with attribute @corresp is used to refer to another entity in the project (not a `persName `or `placeName`, for which @ref is used, see previous comment) 
The @type (all values listed in the guidelines) should always be specified:
•	mss
•	title
•	mspart
•	author
•	place
•	item
•	hand
•	quire
•	binding
•	work
•	ins
•	pers
•	group
•	deco

Examples:

```xml
The work, though untitled, displays resemblance with the <ref type="work" corresp="LIT2314senafe"/>
```

```xml
Cp. <ref type="mss" corresp="BLorient722"/>
```
This is also used for pointing to vHMML manuscripts
```xml	
<ref type="mss" corresp="https://w3id.org/vhmml/readingRoom/view/133001">
```
In this case, # is not used, if only the ID of a record is pointed to, but is used when pointing to a specific xml:id within this record:

```xml
There are many differences between the text of this manuscript and <ref type="mss" corresp="BNFet122#ms_i1"/>, which is less correct
```

**Comment by thea-m** [comment]
Concerning the use of `<ref>` with either @target or @type and @corresp as described in the last comment, there seem to be some inconsistencies in our records:

- Here I would expect @corresp pointing to the hand in question, not the addition
```xml
<ref type="hand" corresp="#a1"/>
```


- The following all point to mss/msItems/msParts (the use of the values item, mss, mspart should be standardized - especially I have used mss rather indiscriminately):
```xml
<ref type="item" corresp="BLadd16223#ms_i4"/>
```
```xml
<ref type="mss" corresp="BNFet154#a1"/>
```
```xml
<ref type="mspart" corresp="#p2"/>
```
- here I would expect `<placeName ref="">` (but `<ref type="ins" corresp `seems more concrete for institutions)
```xml
<ref type="place" corresp="LOC4623Masca">Masč̣ā</ref>
```
```xml
<ref type="ins" corresp="INS0322BH">Bibliotheca Harleiana</ref> 
```

- hands are pointed to differently:
in the same ms:
```xml
<ref type="hand" corresp="#h1"/>
```
```xml
<ref target="#h2"/>
```

pointing to another manuscript:
```xml
 <ref type="hand" corresp="BAVet2#h2">
```

**Comment by thea-m** [comment]
@corresp is also used (with #, referring to xml:ids within the same record) 

- in Person and Work records to relate the transliterations/translations of the persName/title to its fidal version:
 
```xml
    <persName  xml:lang="gez" xml:id="n1">ወለተ፡ ማርያም፡</persName>
               <persName  xml:lang="gez" type="normalized" corresp="#n1">Walatta Māryām</persName>
```

```xml
<title xml:lang="gez" xml:id="t1">አንከሪቶስ</title>
            <title xml:lang="gez" type="normalized" corresp="#t1">ʾAnkariṭos</title>
```

- in `<bibl>`:
```xml
    <listBibl type="editions">
               <bibl corresp="#t1"><ptr target="bm:Budge1923BaralamText"/></bibl>
               <bibl corresp="#t6greek"><ptr target="bm:Boissonade1832Anecdota"/></bibl>
            </listBibl>
```
```xml
<bibl corresp="#blorient821"><ptr target="bm:Perruchon1889Amda"/>
```

- in `item `(additions):
```xml
 <item xml:id="e1" corresp="#ms_i1.5">
```
```xml
        <item xml:id="e1" rend="marginal" corresp="#h1">
```

- in `<layout>`:
```xml
 <layoutDesc>
                <layout corresp="#a1" columns="2" writtenLines="22">
                 <locus from="1r" to="3v"/> 
                </layout>
```
- in` <handNote>`:
```xml
 <handNote script="Ethiopic" xml:id="h1" corresp="#p1">
```
- in `<person>`:
```xml
<persName ref="PRS11423KenfaMikael" role="owner" corresp="#ms_i1"/>
```

- in `<textpart>`, to point to the fidal version:
```xml
<div type="textpart" subtype="incipit" xml:lang="gez" corresp="#Incipit">
```
@corresp is also used (without #, referring to other records) 
```xml
 <item xml:id="a15" corresp="LIT2665SD">
```
```xml
<div type="textpart" subtype="chapter" xml:lang="gez" corresp="LIT2709Matthew">
```
```xml
<witness corresp="BLadd16223#ms_i.1"/>
```

**Comment by PietroLiuzzo** [comment]
witness does not take @ref, and since @corresp can be used I do not think this change is needed.

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/wiki/guidelines#summary-on-the-use-of-ref-and-corresp
