### ISSUE TITLE
Using transkribus2BM.xsl

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#2160]
I am trying to add a Trankribus TEI output to a record, having transformed it using transkribus2BM.xsl

I use the Atom editor, and have added the package that allows the use of XSL files. 

The file runs, but it is not clear to me how to enter the parameters needed for the code to run - are they entered in the XSL sheet before running? 

I attach a screenshot of the XML file in Atom needing transformation, 

![Screenshot 2022-07-01 095233](https://user-images.githubusercontent.com/39619238/176861019-2046fda7-220d-489e-9a10-4c7639b8b2ad.jpg)

and then how things look after running the XSL code - 'untitled' is generated by the code but then the transformation stops with no further output

![Screenshot 2022-07-01 095504](https://user-images.githubusercontent.com/39619238/176861526-d60cdb4f-6c9c-4d9e-bef2-31e2571c5ab9.jpg)

**Comment by eu-genia** [comment]
@thea-m maybe you can have a look? I have not yet tried the transformation. and i am not at my desk as of next week... thank you!

**Comment by eu-genia** [comment]
Just to be sure - when you export from Transkribus do you select the options as suggested?
(client export, zones per region, zones per line, bounding box coordinates, lb)
![image](https://user-images.githubusercontent.com/17987728/176885470-1bb7dc27-d6d2-4893-ae78-27768b9a12d8.png)
(just to check, my exports look different)

**Comment by eu-genia** [comment]
I have also noticed that if you took the link to xsl from the Guidelines page you may have downloaded the wrong file; I have now updated the link please check that you file looks like this
https://raw.githubusercontent.com/BetaMasaheft/Documentation/master/utility/transkribus2BM.xsl
Once you have saved this file it is there that you must insert the parameters, or it won't run

**Comment by eu-genia** [comment]
Just saw the pic - your xsl is the right file but the parameters are missing
![image](https://user-images.githubusercontent.com/17987728/176890750-548ab199-144d-47fa-84ae-e1e81e525e01.png)

Just checked it works if the export and the parameters are set correctly (I use Oxygen, have not checked in Atom, but I hope that with the correct settings it should be OK).
Note that Atom shall be discontinued soon https://github.blog/2022-06-08-sunsetting-atom/

**Comment by Ralph-Lee-UK** [comment]
@eu-genia @thea-m thanks for these responses. I have downloaded Oxygen to try it there. I am not entirely sure how to implement the XSL transformation within Oxygen - can you explain the steps to do this?

**Comment by eu-genia** [comment]
![image](https://user-images.githubusercontent.com/17987728/176948014-fd2d55f0-2266-43d5-9b27-15e9d7c121ae.png)

**Comment by eu-genia** [comment]
![image](https://user-images.githubusercontent.com/17987728/176948078-027fd798-58ad-44c9-8677-998f2ca8b2ab.png)
![image](https://user-images.githubusercontent.com/17987728/176948214-91d7daf5-a4e0-4b5f-8387-fc2e9c9a632e.png)
choose the latest saxon version available
![image](https://user-images.githubusercontent.com/17987728/176948401-68c357b6-e06f-4f22-a678-ca8deb276939.png)
save and apply by hitting the red arrow button

**Comment by eu-genia** [comment]
https://www.oxygenxml.com/doc/versions/24.1/ug-editor/topics/xml-transformation-with-xslt.html

**Comment by Ralph-Lee-UK** [comment]
This works in Oxygen, so I think we will go with that version to save time! Can you please point me to any records that have Transkribus transcriptions included so that I can look at the details?

**Comment by thea-m** [comment]
Hi Ralph, you could have a look for example at the manuscripts in the folder BML, which all have a Transkribus transcription included.
If you will be including large quantities of transcribed text, you'll probably need to split your files using xi:include: https://betamasaheft.eu/Guidelines/?id=xiinclude. From my personal experience working with such files, I would recommend using the file name in all sub-files, i.e.:
ESap028:
ESap028.xml
facsimileESap028.xml
transkribusTextESap028.xml
That makes orientation easier when you have parallel files open in your editor. 
Let us know how it goes and if you need any help!

**Comment by Ralph-Lee-UK** [comment]
This is very helpful, and clear. I will now work on a sample text from the scrolls to check all the details for our project.
