### ISSUE TITLE
msParts in Miracles of Mary mss 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2162]
I have a conceptual question about the structure of some Miracles of Mary manuscripts of the British Library (that I came accross while finalising the digitization of Wright).
Several of these manuscripts (e.g. BLorient634, BLorient639, BLorient641) share a peculiar composition: introductory texts and hymns, followed by several pages of miniatures, followed by the Miracles of Mary proper. There is often a discontinuity in layout between the introductory texts (often three columns) and the miracles (on a new quire, sometimes numbered 1, often with two columns and fewer written lines, bigger and more calligraphical script). The difference in size in the script makes it difficult for me to judge whether the hands of the introductory texts and the miracles might be the same, but I think it's possible that they were different. 
Due to the number of discontinuities, we have often identified several msParts (Wright's descriptions are a bit cryptic, but often using terms like "prefixed", showing that he noted the discontinuities). 
However, the regularity of this pattern accross several manuscripts makes me wonder whether this identification is really correct, or whether the "parts" were all produced with the intention of forming one unit of circulation. As far as I'm aware, there are no corresponding manuscripts of which the introductory texts would be an integral part, and which would continue in the same layout. Therefore, it doesn't seem to me that they were "taken" from other manuscripts and then bound together with these miracles.
I hope that I made myself somewhat clear - what do you think of this? It would probably deserve a deeper study, comparing much more manuscripts. But as there are already many people involved in Miracles of Mary :) my aim for now is only to find a coherent and satisfactory solution for our digitization of Wright's entries.

@DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
does this fall into the scope of guesh's research?

**Comment by thea-m** [comment]
As he wrote to me per mail, codicological aspects of the manuscripts will be part of the second stage of his research, so, not yet.

**Comment by DenisNosnitsin1970** [comment]
"Part" - you meant "unit"? I do not think it is always. I opened at random AQM 007, it homogeneous, and GSM-013, an older one, the same. I assume there was a tendency to set up "preliminaries", but a tendency or fashion, not a must, realized variously (in Gondaraine book production articulated stronger? a question for Guesh). In the real manuscript culture everything may be possible.

**Comment by thea-m** [comment]
Thank you for the comments, they were very helpful for me. The question of course remains unanswered, but I did the best I could according to my judgment. I think these are interesting perspectives for @GueshSol in the future!
