### ISSUE TITLE
Text on the four elements

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2163]
BLorient482 and BLadd24991 (neither is digitized) contain as addition a "short extract regarding the properties of the four elements, earth, air, fire, water" beginning ምድር፡ ቈሪር፡ ወይቡስ፡ ፍጻርሮ፡ ነፋስ፡ በኵለንታሁ፡ ዘውእቱ፡ ውዑይ፡ ወርጡብ፡ (quoted by Wright in BLorient482 and referred to in BLadd24991, we cannot be sure that they actually are identical). I could find this nowhere else. Should I create a new work record for this?
@DenisNosnitsin1970  @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Yes, of course.
