### ISSUE TITLE
Change: "Work in progress, please don't use as reference"?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2165]
### Discussed in https://github.com/BetaMasaheft/Documentation/discussions/1855

<div type='discussions-op-text'>

<sup>Originally posted by **gnizla** December 10, 2021</sup>
Dear All,

Just found myself reading a contribution on BM by @thea-m  which contains the usual refrain "_Work in progress, please don't use as reference_". Given that the record is in fact very detailed I could not help myself from wondering whether it might not be better/more fair, to slightly alter the phrasing for citation so "_Work in Progress_" taking away the "_please don't use as reference part_"? 

It is good to emphasize that this is work in progress, but then when will it not be in progress? This is a very good record already. With this wording, the risk is that it discourages people using BM from actually citing it and this goes against the app's and the encoder's interests.

Just a thought,

J</div>

**Comment by thea-m** [comment]
Moved from unused discussions for easier orientation.
Pietro wrote:

> I agreed. It should be already possibile and up to the editor to write "completed" in a change element to make that mark change from work in progress. There is also an under review stage and more can be added.

I agree that the current phrasing is misleading. I am absolutely responsible for never writing "completed" in my records, but I feel justified by the fact that they never will be completed. I feel that the division into stages of revision as envisaged at the beginning of the project has not actually been used consistently by anyone. To me, the wikidata state of completeness of the Beta masaheft ID, "always incomplete", applies to the entire digital research environment. I would be in favour of marking all records as "Work in Progress" without further differentiation.
What do you think?
@eu-genia @DenisNosnitsin1970

**Comment by eu-genia** [comment]
sure
