### ISSUE TITLE
Set up CI for narratives repo

### ISSUE THREAD

**Issue by duncdrum** [BetaMasaheft/Documentation#2166]
for xmllints `RNG internal error trying to compile notAllowed` see:

- https://mail.gnome.org/archives/xml/2008-June/msg00087.html
- https://github.com/TEIC/TEI-Simple/issues/24
- https://github.com/hcayless/brackets/blob/master/experiment_1.md

**Comment by line-o** [comment]
We need to find out what needs to go in the author field of each repo.

**Comment by line-o** [comment]
The target collection and the repository names are misleading.
While the repository is called `Narrative` its contents will later be put in to the collection `/db/apps/BetMasData/narratives` -- one uses the plural and the other the singular form.
