### ISSUE TITLE
Validation Errors in Narrative Repo

### ISSUE THREAD

**Issue by duncdrum** [BetaMasaheft/Documentation#2169]
The data files in BetaMasaheft are not valid, I've also checked the expanded version and continue to get validation errors after expansion. 

You can quickly do batch validation using Oxygen. By right clicking on a folder and selecting `validate > validate`.

It is not clear to me if you expect the unexpanded version to be valid against the provided schema or not. even if you only expect the expanded version to validate I would suggest changing the expansion scripts so that they already take valid input, to generate valid output. We need feedback from the editors, for how to change the TEI files or the custom schema.

**Comment by line-o** [comment]
Validation errors appear in all data repositories where CI was set up.

**Comment by eu-genia** [comment]
We only work with unexpanded xml files, users have no access in Oxygen to the expanded versions, only present in the live app.
Many files were generated from non TEI source with errors and are being gradually adjusted. 
And in some cases there were changes to the schema after files were created. 
Is it indispensable that all are 100% valid?

**Comment by duncdrum** [comment]
Looking through the error logs on the crashed server, I would strongly suggest that yes all files already in their unexpanded version should be valid against either tei_all or a custom schema. 

Since we control the expansion, we can ensure that a valid input will remain valid after expansion, both versions will be checked on GitHubs CI, and the unexpanded files should be validated by editors within oxygen (the possibility already exists).

We should talk about how to get there and how to proceed in our next meeting.

**Comment by eu-genia** [comment]
@thea-m @DenisNosnitsin1970 we will all have to see how to make ALL existing xml files valid

- [x ] Institutions
- [ ] Manuscripts (easier to go folder by folder)
- [x ] Narratives
- [ ] Persons (easier to go folder by folder)
- [ ] Places (easier to go folder by folder)
- [x ] Studies
- [ ] Works (easier to go folder by folder)

I have started now but if someone has time to help any help is welcome )

I see a problem here, among other things, in the cases where we use `xi:include `as the "internal" files are not valid(atable)

**Comment by thea-m** [comment]
I can contribute to this (little by little and not immediately - it can be a good task when concentration is low :) ). 
I'm not aware of a solution for the xi:include problem. 
But only files merged into master need to valid, right? Sometimes I find it practical to for instance mark up person names before I create the records in my branches.

**Comment by eu-genia** [comment]
@thea-m of course as long as you are on your branch and have not done the PR you can do anything you want )

I think we must also relax the schema in regard to `facsimile`, at the moment, even without xi:include the `<p>` elements are seen as invalid (at least in `studies`).

@duncdrum we use xi:include to keep the files smaller when there is facsimile generated from transkribus linking to images and/or lengthy transcription present (see e.g. https://github.com/BetaMasaheft/Studies/tree/main/Ludolf1681/Ludolf_Historia_Aethiopica) - the expand module produces a single xml file on the live app. The "inner" xml files cannot be validated as they are. So they would never pass the test.

@duncdrum does this https://github.com/BetaMasaheft/Studies/actions/runs/2773873276 mean that the push does not go through because of the test? I think this is not the desired behaviour. 

Another problem here is that the `viewItem `conflicts and crashes do not necessarily mean the file is not valid; in some cases the xqm module may not yet contain all the code necessary to display what the schema allows.

**Comment by PietroLiuzzo** [comment]
I think that trying to validate all files is against initial project specification and the nature of the project itself, which is a work in progress by definition. sure, it would be nice, but it is not what the data is like. What the team works on will be valid, but the large number of stubs and imported files cannot validate to the Beta Masaheft Schema (please check the customization and the guidelines) as it is obvious. @eu-genia is right: a lot has been written in the modules which deals with well known non-valid features of the data, exactly for this reason.

**Comment by duncdrum** [comment]
@eu-genia 
> The "inner" xml files cannot be validated as they are. So they would never pass the test.

using xincludes to split up large files certainly makes sense. The validation currently running on CI knows about  xinclude and performs expansion before validating the result. And while the noisy logs are annoying, and most likely due to a bug in that program, they are just noise not the cause of failures. It is still possible to validate just the inner xml files against an appropriate schema to have faster validation results. We should talk about the various options in our next meeting. 

To be very clear, all xml files inner, internal, external, expanded, etc. are validatable. Its just a question of defining the right form of valid for each step, and a question of process when doing many small things separately vs one big thing is actually beneficial. 

> does this [..] mean that the push does not go through because of the test? I think this is not the desired behaviour.

No, we have not changed your current mode of deploying changes. What is in master gets automatically synced to production and is processed there. We are in the first phase of preparing to change that. Once we have completed Phase 3, we'll activate the `release` bit and define if data that doesn't pass the local tests will still get deployed. Looking at the server logs from the last crash, I have a strong feeling that not deploying data the fails the local tests, will be the desired behaviour then. 

> Another problem here is that the viewItem conflicts and crashes do not necessarily mean the file is not valid; in some cases the xqm module may not yet contain all the code necessary to display what the schema allows.

agreed, the `viewItem` code needs updating, nothing to do with validation. However, any xquery or xslt trying to process a non-wellformed xml will produce fatal errors, which can lead to server crashes, and backup corruptions and all kinds of nastiness.

**Comment by line-o** [comment]
Now that Narrative validates I will close this issue. Please reopen if we still need it (probably also change the title)
