### ISSUE TITLE
XML files with Transkribus output and images

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#2171]
@thea-m I have worked through one of the Tweed scrolls on Transkribus, and have successfully used the xsl file to process the TEI output from Transkribus. 

They are all in the branch that I am working on at this link:

https://github.com/BetaMasaheft/Manuscripts/tree/EMIP-Metadata-Tweed-Scrolls-20-June-2022/EMIP/magicscrolls/EMIPms00477

I've taken a look at the examples that you indicated, but I remain a little unclear about how to proceed. There are several questions:

1) the files are now in a directory - which I have created. Are there any further changes needed to accommodate this change?
2) with the four files in that directory how are they to be combined? The transcribed text is quite short, so perhaps there is no need to split the files - but how are they to be combined to produce a record with images and transcription as well as a list of items? 

I wonder whether a short zoom call might make things quicker, if that's possible - but whatever works best for you.

All of the files that we will work on are pretty similar, so once I have worked this out the rest should follow the same patter.

**Comment by Ralph-Lee-UK** [comment]
@thea, I have made some progress in looking at BMLor70 which includes some ms items. I will update the record, and see whether things work when the data freeze is over. 

I remain uncertain about what extra changes may be necessary when the xml file moves from being a single file to a directory with three files in it - if you are able to advise on that it would be very helpful.

**Comment by thea-m** [comment]
Dear Ralph, I now had a look EMIPms00477 and the encoding seems fine to me. You correctly split the file and added the reference to all parts in xi:include. 
Regarding the length of file starting at which splitting is useful, that's a really good question and I don't know the answer. Let's wait for @eu-genia in a week or so.
You don't need to do anything else to "join" the files to produce their online view - that is done automatically. But as I wrote previously, the visualisation of scroll records hasn't yet been worked on, so there might be some patience needed in that regard.

**Comment by eu-genia** [comment]
I am not sure about the size either, in case of multi-page/photo mss transkribus-aligned facsimile output is always big enough to justify the split; in this particular case one could probably do without but it is easier to go with a general rule for files with facsimile.

I am not sure I understand what the file [EMIPMS0477_TweedMagicScroll009_tei.xml] is meant to be for: I guess it should be deleted from the folder, we only need 
EMIPms00477.xml 
facsimileEMIPms0477.xml 
transkribusTextEMIPms0477.xml
