### ISSUE TITLE
Add CI to all data repositories

### ISSUE THREAD

**Issue by line-o** [BetaMasaheft/Documentation#2173]
Parent ticket to track progress on all data repositories

- [x] [Authority-Files](https://github.com/BetaMasaheft/Authority-Files) https://github.com/BetaMasaheft/Authority-Files/pull/19
- [x] [Institutions](https://github.com/BetaMasaheft/Institutions) https://github.com/BetaMasaheft/Institutions/pull/60
- [x] [Manuscripts](https://github.com/BetaMasaheft/Manuscripts) https://github.com/BetaMasaheft/Manuscripts/pull/1785
- [x] [Narrative](https://github.com/BetaMasaheft/Narrative) https://github.com/BetaMasaheft/Narrative/pull/20
- [x] [Persons](https://github.com/BetaMasaheft/Persons) https://github.com/BetaMasaheft/Persons/pull/583
- [x] [Places](https://github.com/BetaMasaheft/Places) https://github.com/BetaMasaheft/Places/pull/76
- [x] [Studies](https://github.com/BetaMasaheft/Studies) https://github.com/BetaMasaheft/Studies/commit/7333a418d4a75ee798c181aaf2238c263a449f0d
- [x] [Works](https://github.com/BetaMasaheft/Works) https://github.com/BetaMasaheft/Works/pull/853

Currently unavailable data

- [x] Chojnacki
- [x] corpora

**Comment by line-o** [comment]
When all tasks are completed the data-freeze can be lifted.

**Comment by line-o** [comment]
the collections in BetMasData on the live server are
- authority-files
- Chojnacki ❓ 
- corpora ❓ 
- institutions
- manuscripts
- narratives
- persons
- places
- studies
- works

**Comment by duncdrum** [comment]
we ve added Ci to all data repositories and expath packages are being build. I suggest closing this ticket, and open new ones for future tweaks and validation settings on CI
