### ISSUE TITLE
Maṣḥafa kobor

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2181]
I would like to create a new record for a short text, not very well understandable to me, attested with variation as 
1. part of LIT5048Hassabat in EMIP02288 (f. 30r-30v) and IVEf13 (16v) 
2. independently as addition in ESmhg008 (ff. 2v-3r), IVEf103 (f. 236r), and BDLaethe32 (f. 2r).

The text is described as "Book of fortune telling, Mäṣḥäfä Kobor, መጽሐፈ፡ ኮቦር" in EMIP02288 (a subpart of LIT5048Hassabat) , as "unidentified apocalypse (?)" in ESmhg008  and as magic formula in IVEf103.
It lists (mostly unhappy) events that will follow if Yoḥannəs (the Baptist? his feast day?) falls on each different weekday. The exact formulation and assignment of event and weekday differs in the witnesses, but the style and general content is very similar. 

Incipit (BDLaethe32): ለእመ፡ ኮነ፡ ኮቦር፡ ዮሐንስ፡ በሰኑይ፡ አልቦ፡ ደዌ፡ ለጸብእ፡ አገሳ፡ የሐልቁ፡ ዝናም፡ የሐፅፅ፡ መዓር፡ ይውኅዝ፡
ሰገም፡ ይሰምር፡ ሰናይ፡ ይሰምር፡ ሕፃናተ፡ ይሙውቱ 
Explicit: ለእመ፡ በእሑድ፡ ሐማም፡ ይበዝኅ፡ እክል፡ ወነግድ፡ ይሠምር፡ ፄው፡ ይሐፅፅ፡ አልባስ፡ ሐርስ፡ እናም፡ የሐፅፅ፡ በጥቅምት፡ ይትሃየል፡ በሕማም፡ ሕፃ<`gap reason="illegible"/>`

Do you have any insights into this, or understand the text better than I do?

@MassimoVilla @karljonaskarlsson

**Comment by karljonaskarlsson** [comment]
Hello! :)

I don't know the text and hadn't seen it before. As I would understand it, it refers to the feast day of John the Baptist, which is of course the beginning of the year (which can certainly be an important day for saying how the coming year will be)... but as I said, I don't know anything. It is remarkable how bad the future seems, almost regardless of the weekday on which Yohannes falls...

**Comment by thea-m** [comment]
Thank you, then I'll go ahead. It is followed in BDLaethe32 by a list of saints commemorated at the beginning of the year, so there seems to be some connection between the two.

**Comment by MassimoVilla** [comment]
Thank you Thea, I have never met that text before. Your analysis seems correct to me and a new work record seems necessary
