### ISSUE TITLE
Chojnacki project images not visualized

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2185]
The viewer for the Chojnacki collection does not show any images/results at https://betamasaheft.eu/chojnacki.html or rather https://betamasaheft.eu/chojnacki/viewer

**Comment by PietroLiuzzo** [comment]
at line 219 of config.xqm in BetMasWeb, $config:add-data-root should be replaced by $config:bmdata-root. The viewer module does not receive any information to fill in the data array

**Comment by eu-genia** [comment]
now that you say it it is quite obvious )
