### ISSUE TITLE
Abennat project records

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2187]
Dear all,

I have been creating records from the spreadsheet https://docs.google.com/spreadsheets/d/1irbqUOimAebmaJn0dSAf4zaszbsM_EmdOcMwVutp2Gs/edit?usp=sharing, converting the image files, and linking to images for the Abennat project and realized, quite unexpectedly, on looking at some of the images, that a considerable number of the items they digitized and described are not manuscripts at all but printed editions.

While I do understand that these are the books they use in church schools, and the Abennat project may be interested in recording which books are in use, this was not what is expected from the Beta masaheft research environment and I do wonder if investing time in "cataloguing" books as if they were manuscripts can be justified.

I suggest that  the Abennat project members should clearly distinguish between books and manuscripts (if there are any), and we create records for manuscripts only; books should be listed in our Zotero database, unless they are already there, with tags for Abennat (also school-specific tags like Zema, Commentary, Liturgy etc.). And I suggest that I delete all records that have been created for Abennat if they are books. (Pity for the time and effort lost, but we must have some consistency... Unfortunately I only realized this today when I started sample checking the images after putting them on the server...).

Or we say that early prints (these are mostly prints from HS time) deserve records but we do not even have a schema for book description, we cannot call an Impressum a Colophon.

I am not sure if the shelfmarks assigned by the project are recorded anywhere in the local institutions. If not, whether the books stay in or not, I would consider also reassigning shelfmarks, to distinguish books from manuscripts from the very beginning.

Any other ideas / suggestions / observations ?

We can only hope that in the future the Abennat team concentrates on recording manuscripts that we can then include in Bm.

I open the floor to discussion, am open to any input!

@abausi @MershaMengistie @thea-m @DenisNosnitsin1970

**Comment by thea-m** [comment]
There was a similar case in the EMIP data (https://github.com/BetaMasaheft/Documentation/issues/1446), where it was decided to keep the records for printed books and mark them as such. 
It is my impression that Bm can host data not strictly "manuscript tradition" (i.e. Choijnacki) in clearly denotated subprojects. If for the Abennat project, there is value in describing the books as material objects, TEI allows this and there are probably many examples for it in other projects. But forcing the printed book description into a manuscript schema seems not ideal, indeed.
But if the point of the records is to provide a bibliographic list of references, Zotero would seem the more suitable place. But this should be decided by someone with more knowledge of the Abennat project aims than me :)

**Comment by eu-genia** [comment]
Ah yes indeed.

Ok we can keep them. 

Would be helpful if @MershaMengistie could specify in the spreadsheet which are books and which are manuscripts and whether we are counting folia or pages, as at the moment this is not possible to get straight from the descriptions.

@MershaMengistie  - also for dated printed books the current dating "20th century" should be replaced with the actual year (AM / CE). Thank you!

**Comment by DenisNosnitsin1970** [comment]
As I indicated under #1446, probably there should be a special describing scheme for prints. They cannot be described along the same lines as mss. Such a description will tend more towards a bibliographic record, but it should be able to incorporate more features of the content (handwritten notes by the users, corrections?) and materiality. Some work may  be spent for elaborating a kind of scheme for prints. Some models should already exist for this.

**Comment by abausi** [comment]
I agree.

Il 04.08.2022 14:15, DenisNosnitsin1970 ha scritto:
