### ISSUE TITLE
Accompanying Material

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2194]
Following Dorothea's hint, I am starting to use the element `Accompanying Material` to describe a folded old newspaper loosely placed between the front boards and the tetblock of d'Abbadie 217 (I do not believe that it is a part of binding). 
As far as I understand from the TEI guidelines for mss description (where it stands under 10.7.3.3), it can be placed right after `Binding`.
The content of the element can  be visualised, for instance, right below the Binding, above Layout.

**Comment by thea-m** [comment]
Thank you! This is the element in question: https://tei-c.org/release/doc/tei-p5-doc/de/html/ref-accMat.html
I think it would make sense, possibly also to use accMat instead of adminInfo for cases as the one described in https://github.com/BetaMasaheft/Documentation/issues/1395

**Comment by eu-genia** [comment]
the element is already there, it can be used after bindingDesc, but of course it would have to be added to the script (viewItem.xqm) to be parsed/visualized

**Comment by eu-genia** [comment]
if there is already a record where it is used drop here the ID so that I can do the testing

**Comment by DenisNosnitsin1970** [comment]
It is in Abbadie 217 which is not ready yet.

**Comment by eu-genia** [comment]
the code is in place, will be shown under Binding

**Comment by thea-m** [comment]
Thank you!

**Comment by eu-genia** [comment]
You can assign xml:id to absolutely ANY xml element if you need it (for referring e.g.)
