### ISSUE TITLE
new work record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2195]
I would like to create a new work record for a text attested in DW003 (=Unesco 12.3, EMIP 3102), a compilation of hagiographic commemorations and Biblical excerpts arranged similarily to the Synaxarion and partly based upon it, but exhibiting many significant differences from all known recensions of the Synaxarion. Any objections?
@DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
OK

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Works/pull/856
