### ISSUE TITLE
New record: Dictionary of Giusto da Urbino

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2196]
I want to create a new record for the handwritten Geez French Amharic dictionary compiled by Giusto da Urbino in Ethiopia, 
in Abbade 217. Any objections?

**Comment by thea-m** [comment]
I think it would fall within our scope, for me it is fine.

**Comment by eu-genia** [comment]
I only wonder if it is to be created under Works or under Studies

**Comment by eu-genia** [comment]
(I am rather for Studies)

**Comment by thea-m** [comment]
That probably makes sense! Do we actually have any documentation on what can be encoded as studies and how?

**Comment by eu-genia** [comment]
The homepage says "We also include records for the important early works in Ethiopian and Eritrean studies." ) There have not been much there, only Ludolf for now, if we use it more we should be more clear, but I think things written by non-Ethiopians about Ethiopians in pre-modern times belong to Studies, does not matter whether printed or handwritten.
Works are works of Ethiopian literature getting a Clavis number, in this case probably out of place.

**Comment by thea-m** [comment]
Yes, I see the repository, but they are not mentioned in the guidelines, right?

**Comment by eu-genia** [comment]
I don't think so.

**Comment by DenisNosnitsin1970** [comment]
To make "studies" out of it is ok, but it is still transmitted in the handwritten form, like a work.
