### ISSUE TITLE
Workflow fail

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2200]
After some time I've finally restarted my work in the BM and the problem has emerged: I have created a manuscript record, worked on it a bit and I keep receiving messages like this, please help!
![Zrzut ekranu 2022-08-12 181240](https://user-images.githubusercontent.com/62760230/184404071-fc329444-eda1-4b84-bc6c-5694f7d09556.jpg)
@eu-genia

**Comment by eu-genia** [comment]
just ignore... there has been some validation testing inserted into our github repositories, and every time you do something, the testing checks the whole repository, and if there is any invalid file anywhere, it complains. it has nothing to do with your input.
i have already asked @duncdrum and @line-o to make sure people do not get these discouraging messages, I hope this will be fixed soon, in the meanwhile do not think about it. We all get them.
