### ISSUE TITLE
A request for taking up a new mss.

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2203]
Is SBP, Ms. orient. Fol. 117 = Dillmann 66 booked by sb or can I work on it a little? @eu-genia @DenisNosnitsin1970 @thea-m (GrebTiss remains a top priority naturally)

**Comment by DenisNosnitsin1970** [comment]
I do not do anything on it.

**Comment by eu-genia** [comment]
we have not been working on Dillmann as the Staatsbibliothek are also planning work on converting catalogue descriptions in German collections (Berlin naturally included) into XML (though not TEI) on their new https://www.qalamos.net/content/index.xed portal. But of course they won't be producing in-depth descriptions, just putting what is in the catalogue. Hopefully with some alignment at least as far as CAe is concerned.
Yet of course if you are interested in the MS for your work nothing speaks against describing it.

**Comment by MarcinKrawczuk** [comment]
This is a strong argument against touching it, then again if I make the description in the BM it won't hurt anybody, so I'll do it.
