### ISSUE TITLE
Work records for Berlin Or. fol. 117

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2208]
After examining [Berlin Or. fol. 117](https://digital.staatsbibliothek-berlin.de/werkansicht/?PPN=PPN796464243) it seems to me that the following texts do not have work records in the database (the numbers are according to the Dillmann's catalogue herein attached)

8) is part of ድርሳነ፡ ገብርኤል፡ but has no independent record, cf. https://www.nasscal.com/e-clavis-christian-apocrypha/homily-on-the-archangel-gabriel-by-pseudo-archelaos-of-neapolis/

9) concerns PRS11248YohannesKam, person record could be modified

11) Jacob of Sarug's Homily for Christmas

13) Jacob of Sarug's Homily on Mary and the Incarnation

14) Anonymous homily on the Magi

16) This is, I assume, the homily descibed in Zanetti, _The Ethiopian short life of John of Scetis (seventh century)_, I don't have the book at hand

18) The story of Annunciation

19, 20, 21) Three homilies by John Chrysostom on the Annunciation, at least one of them could be LIT2107OntheA

22) Jacob of Sarug's homily published by Uhlig (Aethiopica 2/99)
[Berlin Ms. or. 117 opis.pdf](https://github.com/BetaMasaheft/Documentation/files/9428445/Berlin.Ms.or.117.opis.pdf)

I will appreciate any help with the searching, otherwise I will create them.
@eu-genia @DenisNosnitsin1970 @thea-m

**Comment by thea-m** [comment]
Please go ahead, @MarcinKrawczuk ! I don't think I would have more search resources available than you.

**Comment by eu-genia** [comment]
I guess this issue can be closed? or more works coming?

**Comment by MarcinKrawczuk** [comment]
Yes, I'm closing it.
