### ISSUE TITLE
Bodleian on Github

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2211]
BetMasData collection on the server has for Bodleian the following structure

![image](https://user-images.githubusercontent.com/17987728/186908693-abfe4c44-c6b0-428f-a66c-3ad9a4cace59.png)

which is clearly different from what we have on github https://github.com/BetaMasaheft/Manuscripts/tree/master/OxfordBodleian

@thea-m do you have an explanation?

was it meant to be that some descriptions are only in the live version and not on github? this is actually against our new workflow, github and online version must be 1:1. (we cannot properly validate the files that are not on git, and this is not securely backupable)

**Comment by thea-m** [comment]
Yes, the real data is on another branch, it is very important for the project that it is not on the master branch. The placeholder data on the master branch was created to allow us to refer to the IDs of the manuscripts for example in person or work records.

**Comment by thea-m** [comment]
Any solution is fine, as long as our current manuscript descriptions are not merged into master.

**Comment by eu-genia** [comment]
this is up to @duncdrum and @line-o to advise us what to do with such data, but I am afraid this does not go well with the new set up

**Comment by thea-m** [comment]
Then that was the wrong term :) In any case, I'm afraid a solution must found in which the files stay on their branch.

**Comment by eu-genia** [comment]
If the data is meant to be completely offline it is OK to keep it on an unpublished branch - but then why is it in `BetMasData` which serves the web app? At the moment the files are not in the expanded folder and are not visualized, but now with manual uploads of corrected files I was planning to run an automatic expansion of all Bodleian files, which would produce records from the stubs available in `BetMasData`.  And then the stubs will be online like all the others. It is quite impossible to keep in mind which subfolders NOT to expand. Is there an issue documenting the decision process?

**Comment by eu-genia** [comment]
In their case there is no discrepancy between the master branch and the app. I will then be pushing your stubs to GitHub.

**Comment by thea-m** [comment]
Thank you!
