### ISSUE TITLE
Bible Society MSS location

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2213]
Hello!

The folder for the manuscripts of the Bible Society is named "LondonBibleSociety", although the manuscripts – as far as I know – are currently kept at the Cambridge University Library. Would it be possible to make this folder a subfolder of the folder "Cambridge"? I think it would enhance the user-friendliness.

Thank you!

**Comment by thea-m** [comment]
That sounds reasonable. If you are working on the collection anyway and understand its history, you could also decide whether the repository ID INS0306BSL should be kept as repository of the manuscripts in question or whether it should be changed (to INS0692CUL?).

**Comment by karljonaskarlsson** [comment]
Historically, it was most certainly a separate repository, so I think it should be kept.

**Comment by eu-genia** [comment]
what is the current most widely used identifier?
as a rule we should have the current `repository `(so CUL) as the main one, with BS as a collection, and the rest under `provenance`, but then of course we would not have the list under INS0306BSL (or I could try to add to the list the MS that mention a collection under `provenance`, this could be also a possibility)
or put BS in the `altIdentifier` `repository`, but for the moment the code would confusingly print both repositories in the main view (I could correct it if necessary, that is, if we decide on it, but this opens then a long way for all the other ms that get moved around...)

**Comment by thea-m** [comment]
I think that if the manuscript are now integrated into Cambridge University Library (and not kept there in a separate library?), this is the repository that should be referred to as their current repository (as manuscripts that were at one point kept in the Musée du Trocadéro now have the BnF as their repository), and their common origin could be marked up as collection (like a "fondo").

**Comment by karljonaskarlsson** [comment]
I am not entirely sure that I follow what you discuss, but we ordered and looked at them simply in the CUL reading room. I did not get the feeling that they were stored separately from other manuscripts, but who knows what happens behind the scenes. Without knowing the Bm technicalities, I think that CUL should be their current repository and Bible Society in London should be something like a previous repository.

**Comment by eu-genia** [comment]
correct, the `repository `under `msIdentifier `should be CUL, BSL should be entered as `collection `and then mentioned under `provenance `in `history`

```
<msIdentifier>
                     <repository ref="INS0692CUL"/>
                     <idno>BFBS Mss 169 </idno>
                     <altIdentifier>
                        <idno>Cowley I</idno>
                     </altIdentifier>
                  </msIdentifier>
...
<history>
<provenance>
                        The ms. was written in <placeName ref="LOC1310Aksum">Aksum</placeName> 
                        and presented by <persName ref="PRS10803Yeshaq"/> 
                        to the Ethiopian community in <placeName ref="wd:Q1218">Jerusalem</placeName>. 
                        From there it passed to <placeName ref="wd:Q220">Rome</placeName> 
                        together with other mss. and, having been transferred from the hostel of  <placeName ref="INS0302SanStefano">San Stefano dei Mori</placeName> 
                        to the <placeName ref="INS0307MB">Museo Borgiano</placeName>, 
                        it was stolen and brought to  <placeName ref="wd:Q84">London</placeName>.
                        <p>In <date>1817</date> the bookseller <persName ref="PRS10804Smith">J. Smith</persName> 
                           in Drury Lane sold it to Church Missionary Society, which transferred it to the <placeName ref="INS0306BSL"> British and Foreign Bible Society</placeName>, for use in a printed Ethiopic edition. </p>
                           </provenance>
</history>
```

PS the wikidata references in provenance should also eventually be changed to normal Bm references (INS0306BSL )
