### ISSUE TITLE
New work record for the exhortion chants

### ISSUE THREAD

**Issue by GueshSol** [BetaMasaheft/Documentation#2214]
@thea-m @eu-genia @DenisNosnitsin1970

**Comment by GueshSol** [comment]
Sorry I submitted an uncompleted issue and will re-arrange it soon.

**Comment by eu-genia** [comment]
Dear Guesh, 
I am sorry I don't know the term. Do you mean exhortation? 
Have you checked that there is no fitting work record yet?

**Comment by eu-genia** [comment]
For example we have LIT4247Exhortation

**Comment by GueshSol** [comment]
There is a summarizing hymn in the Ethiopian miracles of Mary to be sung after the completion of reading a miarcle/s. The hymn is traditionally known with the initial phrase Barakatātihā Lazātti Qǝddǝst (Blessings of this Saint). The hymn appears in many Taʾāmmǝra Maryām manuscripts for example we can find it in BNFAbb114 from f. 81va-82rb and other manuscripts from Gunda Gunde Monastery. The hymn with Barakatātihā Lazātti contains four short sub-hymns to be sung one following the other. I have made an effort to check whether the issue under discussion is recorded in the BM database or not but it seems it is not recorded yet.

**Comment by eu-genia** [comment]
I leave this up to @thea-m and @DenisNosnitsin1970 to check; for my part I can see that `LIT6024IntroMM `contains as `LIT6024IntroMM#Hymn` a text with the `incipit `ሃሌ፡ ሉያ፡ በረከታቲሃ፡ ለዛቲ፡ እግዝእትነ፡ ቅድስት፡ ማርያም፡ ወላዲተ፡ አምላክ፡ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ የሃሉ፡ ላዕለ፡ ኵልነ፡ ሕዝብከ፨ ለመስቀልከ፡ እግዚኦ፡ ንፌኑ፡ ስብሐተ፨ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ሃሌ፡ ሉያ፡ ሰላም፡ ለከ፡ ዮሐንስ፡ ወልደ፡ ነጐድጓድ፨ 
Is this a different one?

There are also passages with በረከታቲሃ፡ ለዛቲ፡ እግዝእትነ፡ ቅድስት፡ ድንግል፡ ማርያም etc. described so far as part of LIT3584Intro, but without assigning a sub-ID, e.g. ESdd010 or ESamq002 (or even LIT1968Mashaf in ESnsm007)

**Comment by GueshSol** [comment]
Sure! this is the hymn to which I was seeking a work ID. Thank you @eu-genia

**Comment by thea-m** [comment]
There is an ID for the hymn to Yohannes and the apostles, LIT4615Salam (LIT6024IntroMM#Hymn=), which is also attested independently. The accompanying texts in LIT6024IntroMM are a bit different. 
@GueshSol what do you think? Is the record for the hymn itself enough, or do you think it would be better to create a new one with the same introduction and ending as in BNFabb114?

**Comment by GueshSol** [comment]
I think the hymn Barakatātihā Lazātti appears as a single hymn in most manuscripts, but according to some manuscripts and also with the normal liturgical practice in churches the hymn contains consecutive sub-hymns such as Salām Laka Yohannis (peace to you John), Salām lakkǝmu Ṗetros wa-Ṗawǝlos (peace to you Peter and Paul) and Salām Laki Ḫoḫǝta Mǝsraq (lit. peace to you Gate of East). Thus, it does not bring a big difference even if we only call the entire hymn with the leading name Barakatātihā Lazātti already recorded as LIT4615Salam.

**Comment by thea-m** [comment]
Good. Can we close this issue? If your research shows that a new differentiation of records or new records are needed, you can always open new issues.

**Comment by GueshSol** [comment]
Sorry, it was a typo and a technical error. I'm investigating the issue I
requested, but it was wrongly submitted. It is all bout three unrecorded
non-stanzaic Chants in the exhortation to the miracles of Mary. I'll
resubmit my issue soon.

**Comment by eu-genia** [comment]
Dear Guesh, this issue has been already closed, I think you were responding to an email; in case of issues you should not respond to emails from github but follow the links to the issues to check ) Thank you!

**Comment by eu-genia** [comment]
(Maybe this was an old notification which GitHub for some reason recovered now, in which case just ignore)
