### ISSUE TITLE
Two entries for same text?

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2215]
I think there is a confusion for "Zenā nagaromu la-Śǝllāse" LIT2286ZenaSellase with this entry here: "Zena nägäromu läśǝllase" LIT2623Zenana. 
Obivously its a transcription thing EAe vs BM. Since the second entry I listed here has basically no content, it might be possible to "simply" delete it?

**Comment by eu-genia** [comment]
Yes sure LIT2623Zenana can be deleted, will do it
