### ISSUE TITLE
error after logging in

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2218]
This error immediately appeared on the homepage after I logged in: 
![image](https://user-images.githubusercontent.com/19650382/187486928-1c12f999-5eea-44cd-b501-435d31954b01.png)

@eu-genia

**Comment by eu-genia** [comment]
as the error says, something happened with the permissions in db/apps/log, I have reset the permissions, should be OK now

**Comment by thea-m** [comment]
Yes, works now, thank you

**Comment by thea-m** [comment]
Thank you very much Dorothea for trying to store a new file!

Unfortunately PRS13882PhillippsT could not be saved

This is the first error which occurred Write permission is not granted on the Collection. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection., feel free to copy it and send it to info@betamasaheft.eu.

[create another entry](https://betamasaheft.eu/newentry.html?collection=persons)

**Comment by eu-genia** [comment]
again permissions... try again
