### ISSUE TITLE
minor typo in title

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2223]
a missing "space" in the work titel https://betamasaheft.eu/works/LIT1679Chroni/main

**Comment by eu-genia** [comment]
Thank you, fixed (the EAe- inherited entries are all full of errors due to automatic conversion and different transcription system; we do not correct them in a systematic way)

**Comment by thea-m** [comment]
(@SophiaD-M , I think it might be faster to fix such minor and non-XML errors yourself than to write an issue describing them?)

![image](https://user-images.githubusercontent.com/19650382/187882859-0258474c-8f88-497d-baa7-dc0bd60f664c.png)

![image](https://user-images.githubusercontent.com/19650382/187882926-d2579421-f630-46c4-ad6a-952d95df0893.png)

![image](https://user-images.githubusercontent.com/19650382/187883013-54dd5e50-1faa-4c71-9fbb-e3e53aa6254e.png)
