### ISSUE TITLE
New work records BDLaethg32

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2225]
I would like to create new records for the works attested in BDLaethg32, all of a protective character. Each prayer is followed by a directive in Amharic. 

1. ff. 1r-4v ጸሎተ፡ ሀብት፡ ወቅብዓተ፡ መንፈስ፡ ቅዱስ፤ ወመፍቅረ፡ ሕዝብ፤ ዘወሀቦሙ፡ እግዚአብሔር፡ ለአብርሃም፡ ወለዳዊት፡
I contains the texts of Psalms 44 (its beginning) and 151, interspersed with magic words.
Psalm 44, Incipit: ጐሥዓ፡ ልብየ፡ ቃለ፡ ሠናየ፨ አዔዳዖ፤ አዔዳዖ፤ አዔዳዖ፨ ወአነ፡ አየድዕ፡ ግብርየ፡ ለንጉሥ፨ ወሥልጣኖ፨  ወሥልጣኖ፤ ወሥልጣኖ፤ ከመ፡ ዓቀለመ፡ ጸሐፈ፡ ዘጠበጠበ፡ ይጽሕፍ፡ ልሳንየ፨ ወረአንታ፡ ወረአንታ፡ ወረአንታ፨
Explicit: በእንተዝ፡ ቀብአከ፡ እግዚአብሔር፡ አምላክከ፨ ኢናጧኢነከ፤ ኢናጧኢነከ፤ ኢናጧኢነከ፨ ቅብአ፡ ትፍሥሕት፡ እምእለ፡ ከማከ፨ አልከውስር፤ አልከውስር፤ አልከውስር፨ ከርቤ፡ ወቀንአት፡ ወሰሊሖት፡ እምነ፡ አልባሲከ፨ አፈሶሊ፤  አፈሶሊ፤ አፈሶሊ፨
Psalm 151, Incipit: ንዑስ፡ አነ፡ እምአኃውየ፨  ለረቢካ፨ ወወሬዛ፡ በቤተ፡ አቡየ፨ ወንሖር፡ ወእርዒ፡ አባግዓ፡ አቡየ፨ ወኑሖ፨ እደውየ፡ ይገብራ፡ መሰንቆ፨ ሸራኮ፨ ወአፃብአየ፡ ያስተዋድዳ፡ መዝሙረ፨ ወለአብትር፨ መኑ፡ ነገሮ፡ ለእግዚእየ፡ ፍልሞን፨ ውእቱ፡ እግዚአብሔር፡ ወውእቱ፡ ሰምዓኒ፨
Explicit:  በእሉ፡ ቃላት፡ ከመ፡ አንሣእኮሙ፡ ወቀባዕኮሙ፡ ለአብርሃም፡ ወለዳዊት፤ ከማሆሙ፡ ቅብዓኒ፡ ወአንሥአኒ፡ በቅድመ፡ ነገሥት፡ ወመኳንንት፤ ወመሳፍንት፡ በቅድመ፡ ሰብእ፡ ወመላእክት፤ በቅድመ፡ ኵሎሙ፡ ደቂቀ፡ አዳም፡ ወሔዋን፤ ለገብርከ፡ 
Directive:
ድግም፡ በሜሮን፤ ፵፱ ጊዜ፡ በቀለመ፡ ወርቅ፡ ጽፈሕ፡ ከከርቤ፡ ጋር፡ ታጠን፨ ዓዲ፡  በነጭ፡ ደሮ፡ መረቅ፡ በቀይ፡ ቀለም፡ ጽፈሕ፡ ጨምረህ፤ አስርተህ፡ ብላ፨ መንካውን፡ ወጭቱን፡ ላባውን፡ ፕፍሩን፡ የታጠብክበትን፡ የማይበላውን፡ ሁሉ፡ ከግብ፡ ቅበር፨ ከአምባጨ፡ ተቀጽላ፡ ክታቡን፡ ያዝ፨

2. ff. 4v-6r, Prayer for "burying the hearts of the enemies":
Incipit: አዳታኤል፡ ስምከ፡ ዘያድለቀልቃ፡ ለምድር፡ ሰዱቃኤል፡ ስምከ፡ ዘይስጥቃ፡ ለባሕር፤ ወኤቴኤል፡ ስምከ፡ ዘያቀልጦ፡ ለሰማይ፤ በዝ፡ አስማት፡ ድፍን፡ ልቦሙ፡ ለሰብአ፡ እገሌ፨ ያሙጅጅ፤ ያሙጅብ፤ አልጀባር፡ አልዣባር፤ ገልማላዊ፤ አልሐዲር
Explicit: ወያረስኦሙ፡ ምክሮሙ፡ ለመካእክት፤ ፯ ጊዜ፡ ከማሁ፡ አርስዕ፡ ነገሮሙ፤ ወዘርዝር፡ ምክሮሙ፤ ለሰብአ፡ እገሌ፡ እገሌ፡ እገሌ፨
Directive: በ፯ ጠጠር፡ በ፯ የብረት፡ አር፡ ፵፱ ጊዜ፡ ደግመህ፡  ፬ቱን፡ በ፬ ማዕዘን፡ በትን፤ ፫ቱ፡   ከቤትህ፡ ከ፫ኛው፡ ማገር፡ ስተል፨

3. ff. 6r-7r, Another Prayer for "burying the hearts of the enemies":
Incipit: ጸሎት፡ በእንተ፡ መድፍነ፡ ፀር፤ ገምድድ፤ ፈርድድ፤ `<del rend="expunctuated">ረምድድ</del>`፤  አምድድ፤ ለምድድ፤ አፈርድድ፤ ረምድድ፤ ለምለሚዎን፤ በኃይለ፡ ዝን`<del rend="strikethrough">ዝለ</del>`ቱ፡ አስማቲከ፤ ድፍን፡ ልቦሙ፡ ለፀርየ፡ ወለጸላዕትየ፡ ሊተ፡ ለገብርከ
Explicit: በሐዋን፡ በዘረጅን፤ በጸረጅን፤ ፯ ጊዜ፤ ዚረፊማኖስ፤ ፫ ጊ፤ ቲቲማኖስ፤ ፫ ጊ፡ አሽድ፤ አልሽድ፤ ፈቀጅ፤ ወከመ፡ ጰዶጸጅ፤ በሰማይ፡ መንበርከ፤ ወበታቦራዊ፡ ስምከ፤ ተማኅፀንኩ፡ ከመ፡ ኢይትናገሩኒ፡ ነገረ፡ ቅሡመ፡ ዘእንበለ፡ `<sic>ፍቅፍ፡</sic>` ወሰላም፡ ለገብርከ፡ 
Directive: በ፯ ጠጠር፡ ፵፱ ጊዜ፡ ደግመህ፡ ፬ቱን፡ በምሥራቅ፤  በምዕ፤ በሰ፤ በዳቡ፤ በትን፡ ፫ቱን፤ ፀርከ፤ ከሚጠጣው፡ ውሀ፡ ጣለው፨ ለመፍትሔ፡ ሥራይ፡ በ፵፱ ዘቢብ፡ ፯፯ ጊዜ፡ ደግመህ፡ ፯፯ቱን፡ ብላ፡ እስከ፡ ፯ ቀን። ጸሊ፡ በኅቡዕ።

4. ff. 7r-8r, Protective prayer containing ʾasmāt, and some Arabic words
Incipit: አስቡን፤ አላሁ፤ ወኒአመል፤ ተዉከል፤ ያቅሐር፤ ያልጀባር፤ ያዘልበጥ፤ ሸሸዱድ፤ ወለዚኒ፤  ጁሐጁ፤ ወና፤ ለናህዴ፤ የናሁም፤ ሱብለነ፤ ወኮነ፤ አላሁ፤ ሙሐንን፤ ወወ፤ የሐልፊሁ፤
Directive: ድግም፤ በ፯ ጊዜ፡ በብር፡ ቀለበት፡ ግበር፡ በአጽባቲከ፨ `<del rend="strikethrough">ግግ</del>`፤ ድግም፡ በነግህ፡ በበዕለቱ። እንዘ፡ ኢይሬእየከ፡ ሰብእ።
Supplication: ኦእኁየ፡ ኢትርስአኒ፡ በጸሎትከ፡ በልቡና፡ ወበቃለ፡ ሃይማኖት፡ ለዓለመ፡ ዓለም፡ አሜን። ጸሊ፡ በኅቡዕ፡ በኵሊ፤ ነቢይን፤ ወመስተቃርሬን፤ መሳውርተ፡ ሰሎሞን፤ ፍታሕ፡ ሥራየ፡ ዘተገብረ፡ በላዕለ፡ ገብርከ፤ እገሌ፤ በቀይ፡ ቀለም፡ በ፫ አንቆቅሆ፡ ጽፈሕ፡ ፵፱ ጊዜ፡ ደግመህ፡ ለብላ፨

@MassimoVilla @karljonaskarlsson

**Comment by karljonaskarlsson** [comment]
I cannot find any already existing files for them, so I think it's valid to create new files.
