### ISSUE TITLE
Abbadie 64 new person records 

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2226]
I will nee new records for Galāwdewos, the scribe of Abbadie 64, and the commissioner Sankorās. 
Any objections?

**Comment by thea-m** [comment]
No objection, I assume that you checked the existing records for each name :) It will be easier for you with the context knowledge than for us.

**Comment by eu-genia** [comment]
Sure, we normally do not open issues for new persons.
