### ISSUE TITLE
Hymn to John Kāmā - but which?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2233]
By your judgement, is LIT2990RepCh271a hymn to the Egyptian (PRS11248YohannesKama) or the Ethiopian (PRS10408Yohanne) monk? @thea-m @smaugustine

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 maybe could also be asked but I would assume the Egyptian

**Comment by DenisNosnitsin1970** [comment]
Probably the Egyptian one. The Ethiopian (of Dabra Libanos) was unlikely a martyr, and hardly anything is known about him. Chaine's incipits are very short, though.
