### ISSUE TITLE
"CAe 3532" used twice

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2236]
The CAe number "3532" has been used for two different works: 

https://betamasaheft.eu/works/LIT3532Tergw/main
https://betamasaheft.eu/works/LIT3532Comment/main

I would suggest deleting the second ("Commentary to the Psalms"), as it appears it has not been used. I would also like to create a new work for a Psalter-related connected to Eusebius, attested for example in https://betamasaheft.eu/manuscripts/RNBdorn609/main and https://betamasaheft.eu/manuscripts/BAVet4/main.

**Comment by thea-m** [comment]
That seems reasonable, please go ahead. Good that you spotted it!

**Comment by eu-genia** [comment]
seems that this one had been closed too early, done now
