### ISSUE TITLE
mark ʷ and w as "homophones" in search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2237]
Would it be possible to find results with ʷ when searching for w and vice versa? I believe it used to be the case, but isn't anymore. https://github.com/BetaMasaheft/Documentation/issues/471

For example https://betamasaheft.eu/simpleSearch.html?searchType=text&mode=any&query=deggwa and https://betamasaheft.eu/simpleSearch.html?searchType=text&mode=any&query=d%C7%9Dgg%CA%B7%C4%81

@eu-genia

**Comment by eu-genia** [comment]
I don't think this feature was ever present in the **simple search**.
It is present in the **full search**. (https://betamasaheft.eu/newSearch.html?searchType=text&clavistype=&query=d%C7%9Dgg%CA%B7%C4%81&defaultoperator=OR&mode=none&homophones=on&signature-operator-field=AND&signature-field=&handDesc-operator-field=AND&handDesc-field=&decoDesc-operator-field=AND&decoDesc-field=&binding-operator-field=AND&binding-field=&supportDesc-operator-field=AND&supportDesc-field=&msContent-operator-field=AND&msContent-field=&additions-operator-field=AND&additions-field=&incipit-operator-field=AND&incipit-field=&explicit-operator-field=AND&explicit-field=&colophon-operator-field=AND&colophon-field=&title-operator-field=AND&title-field=&text-operator-field=AND&text-field=&person-operator-field=AND&person-field=&place-operator-field=AND&place-field=)

**Comment by thea-m** [comment]
good, thank you!
