### ISSUE TITLE
Problem creating new files via the app

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2238]
When trying to create a new Work record via the app, the following error notification appears: 

<img width="1048" alt="Skärmavbild 2022-09-20 kl  10 46 09" src="https://user-images.githubusercontent.com/34240156/191214725-0672e30b-57fa-4163-9116-de790e4971b8.png">

**Comment by eu-genia** [comment]
I could not reproduce the error, the word "guest" suggests that the app does not see you as logged in.
I tried to log in under your credentials to check whether there was a problem and could create the stub without any problem
![image](https://user-images.githubusercontent.com/17987728/191216752-bcfcdbbd-c6e5-46ee-a280-965235a1899b.png)

I downloaded and pushed the stub, please sync the master and continue from there, thank you.

**Comment by karljonaskarlsson** [comment]
I tried logging out and in, but the same problem appeared twice.

**Comment by eu-genia** [comment]
note that you **must** log in on the main page (betamasaheft.eu), not on the subpages

**Comment by karljonaskarlsson** [comment]
Not sure if you are interested, but I tried it in Chrome and everything works fine! So it seems to be a Safari issue.
