### ISSUE TITLE
new record for letter

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2239]
I would like to create a new record for a letter attested in BDLaethb3 (96r-96v) and BLorient481 (2r-3r, https://www.bl.uk/manuscripts/Viewer.aspx?ref=or_481_f001r), from Patriarch John XVII to King ʾIyāsu II, dated to 1460 Era of the martyrs (1743), concerning mostly, if I understand it correctly, the construction of Dabra ḍaḥay Qwəsqwām church. 
Quite an interesting document, in both manuscripts (both containing biblical texts) it is incorporated seemingly as part of the main text and accompanied by an Arabic doxology and stamps (in BDLaethb3, Yusāb (II) is mentioned)).
@MassimoVilla @karljonaskarlsson

**Comment by MassimoVilla** [comment]
No objection from me.
Is the letter unedited? If not, it would also deserve a specific study or an edition.

**Comment by karljonaskarlsson** [comment]
I agree, interesting!
