### ISSUE TITLE
More text IDs in Abb 134

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2245]
I think we need more new IDs for smaller texts in Abb 134, which are small-size prayers located on fols. 123-138 [https://gallica.bnf.fr/ark:/12148/btv1b10087881b/f124.item.r=%22Abbadie%20134%22](url). They are: prayer of water, three prayers for chasing and evicting demons, prayer to obtain grace/majesty, prayer against the headache, prayer against demons. I was able to find another sample for only one of them, in BMLor403. They seem to be very old protective prayers, completely without the use of "asmat".

**Comment by DenisNosnitsin1970** [comment]
A small addition as the matter is complicated. Actually most of the  aforementioned texts were published in Lifchitz, "Textes èthiopiens mgico-religieux", under the title "Rempant de la croix". Apart from the question as to what exactly is " Hasura masqal" (EAE 2, p. 1044a "the general title of a group of Geez canonical magic texts, according to ..."), the editor says that the prayers are not exactly "Hasura masqal" but "peuvent ètre rapprochèes du Rempant de la croix, bien qu'elle n'en portent pa le titre" (still the running title is "Rempant de la croix", at the same time, at least one uses the formula "protect us with your Cross..."). The editor dropped the first prayer (Salota may) and printed the rest as one continuous text. I would create IDs for each of them, may be I can indicate relations to LIT5696MagicPrayer (Hasura masqal). I think it is justified if we upgrade LIT5696MagicPrayer to the general record.

**Comment by eu-genia** [comment]
this sounds reasonable. we can use LIT5696MagicPrayer if no further details are available and differentiate the prayers when we can, of course, clear abstracts and relations would be necessary to avoid confusion. thank you!
