### ISSUE TITLE
wrong images for this ms.

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2246]
The wrong manuscript images have been connected to this ms: https://betamasaheft.eu/manuscripts/BNFabb122/main
Images lead to BnF Abb 99 but should be Abb 122 https://archivesetmanuscrits.bnf.fr/ark:/12148/cc109084t

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 can you please correct
