### ISSUE TITLE
Malkǝʾ-hymn to St George BAVet129

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2247]
In BAVet129 there is a hymn to St George which I am not able to find in the database nor in Chaine's clavis. 

Inc.: ሰላም፡ ለዝክረ፡ ስምከ፡ እንተ፡ የዐውዶን፡ መዐዛ። ወለስእርትከ፡ ጽሁድ፡ ዘርእስከ፡ አክሊለ፡ ቤዛ።
Expl.: ከመ፡ እስራኤል፡ ድኅኑ፡ እመልአከ፡ ሞት፡ በደመ፡ ጠሊ፨ አድኅነኒ፡ ወባልሐኒ፡ ጊዜ፡ ተንሥኦ፡ ቀታሊ፨ በደመ፡ ስምዕከ፡ ዘተክዕወ፡
ጊዮርጊስ፡ ከሐሊ፨ ስብሐት፡ ለእግዚአብሔር፡ ለወሀቤ፡ ልቡና፡ ወትረ፡ እስከ፡ ለዓለም።

I will appreciate if you could have a look.
@DenisNosnitsin1970 @smaugustine @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Sorry, I do not know this one.
