### ISSUE TITLE
Visualizing bibl not inside listBibl (in all elements)

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2250]
I have by chance looked at https://betamasaheft.eu/works/LIT4054Gadl/main and see two problems:
1) For some reason the relation saws:isAttributedToAuthor apparently causes, that in the [person record for Ephrem](https://betamasaheft.eu/persons/PRS3827Ephrem) this text is displayed in the red box, which is not true because Ephrem is not the subject
2) The bibliographical reference to bm:Weninger2005EAEEphrem does not display so it looks like sth is missing from the sentence

@eu-genia @thea-m

**Comment by eu-genia** [comment]
The Gadl is shown in the red box because the record `PRS3827Ephrem `has the relationship `ecrm:P129i_is_subject_of` which should be corrected/removed, it has nothing to do with `LIT4054Gadl`
`bibl `element from inside of `relation ``desc `is not printed.  but i do not see much problem with the sentence, or which sentence do you mean?

**Comment by MarcinKrawczuk** [comment]
OK, I will correct PRS3827Ephrem. As for the other problem - I'm sending the screen shot.
![Zrzut ekranu 2022-10-12 101219](https://user-images.githubusercontent.com/62760230/195288204-cbf7cb5f-5e82-46a3-bf86-65c56015c311.jpg) After the word "tradition" there is a full stop instead of reference to Weninger.

**Comment by eu-genia** [comment]
actually the xquery does foresee the possibility of `bibl `being not in `listBibl`, it should then pick a simple citation from `bibliography.xml`. but for some reason it does not...

**Comment by eu-genia** [comment]
![image](https://user-images.githubusercontent.com/17987728/195562369-4777ec85-eb5e-4c6c-93e8-463bed0b099d.png)

**Comment by MarcinKrawczuk** [comment]
Great, the workaround you have described above seems very practical.
