### ISSUE TITLE
A general salam-collection record

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2256]
It looks like we might need a general ID for an unidentified collection of salam-hymns (not Egziabeher nagsa, not individual salams). Should I creat this ID?

**Comment by thea-m** [comment]
I also looked for it and found none, so it makes sense to create a new one (I assume that you have a concrete manuscript in which such a collection is found?).

**Comment by DenisNosnitsin1970** [comment]
this specific case is Abbadie 102, looks a little shapeless, `https://gallica.bnf.fr/ark:/12148/btv1b100914617`, but the ID might be for any further unidentified gathering of salam-hymns.

**Comment by thea-m** [comment]
From my point of view, go ahead :)

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Works/pull/909
