### ISSUE TITLE
New records for the miracles of Gabra Manfas Qǝddus

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2258]
I would like to create new records for the set of miracles of Gabra Manfas Qǝddus which are found in MS BDLaethe39. Seemingly, there are no records on this subject in the BM database, except for the general record LIT3977Taammer.
MS BDLaethe39 contains ten miracles of Gabra Manfas Qǝddus, all of which already published and translated by Paolo Marrassini in his edition for the CSCO («Vita», «Omelia», «Miracoli» del santo Gabra Manfas Qeddus, 2003).
These are the titles of the records I intend to create:
1. How Gabra Manfas Qǝddus saved from hell the sinful monk who had faith in the saint (incipit:  ወነበረ፡ ፩ መነኮስ፡ <sic resp="MV">ኃጥአ፡</sic> ወይገብር፡ ብዙኃ፡ ሥራያተ፡ ወያመልክ፡ አማልክተ። ወዓዲሰ፡ ይገብር፡ ዝሙተ፡ ወ<cb n="b"/><hi rend="rubric">አኮ፡                                        ሰብእ፡ ባሕቲቶ፡ አላ፡ ያወስብ፡ አክልብተ፡);
2. How the saint brought out a demon from a woman who had been possessed for three years (incipit: ወነበረት፡ አሐተ፡ ብእሲት፡ ዘአኃዛ፡ ጋኔን፡ ዘቀትር፡ ወበሣልስት፡ ዕለት፡ ይወግራ፡ ወነበረት፡ እስከ፡ ፫ ዓመት። ወእምድኅረዝ፡ ሖረት፡ ወኀበ፡ ፩ ካህን። ወውእቱሰ፡                                     ካህን፡ መንፈሳዊ።);
3. How the saint sent a lion to save the nun attacked by two brigands (incipit: ወነበረት፡ አሐቲ፡ መበለት፡ እንዘ፡ ትገብር፡ ትዝካሮ፡ ለአቡነ፡ <hi rend="rubric">ገብረ፡ መንፈስ፡ <supplied reason="omitted">ቅዱስ፡</supplied></hi> ፪ ጊዜ፡                                    በ፩ ዓመት፡ በዕለተ፡ ልደቱ፡ ወበዕለተ፡ ሞቱ፡);
4. How the saint freed a sinful woman from the snake she had in her womb (incipit: ወሀለወት፡ አሐቲ፡ ብእሲት፡ መፍቀሪተ፡ ዝሙት፡ ወሰዓሪተ፡ ሰንበት። ወርእየ፡ እግዚአብሔር፡ እከያቲሃ፡ አዘዘ፡ ዓቢይ፡ ከይሲ፡ ከመ፡ ይባዕ፡ በዕፍረታ። ወአሐተ፡                                     ዕለተ፡);
5. How the saint had the foetus of a pregnant nun transferred to a sterile woman (incipit:     ወነበረት፡ አሐቲ፡ መበለት፡ እንዘ፡ ትገብር፡ ብዙኃ፡ ኃጢአተ፡ ከመ፡ ሰብአ፡ ዓለም። ወእምዝ፡ ፀንሰት፡ ወአእመራ፡ ሊቀ፡ አበው፡ <gap reason="illegible" unit="chars" quantity="1"/>                                     <pb n="73r"/><cb n="a"/>መ፡ ፀንሰት፡ ወለከ፡ ኀበ፡ መምህራ።);
6. How the saint killed the hawk who had stolen the māʿtab-cord from the head of a pious man (incipit: ወሀሎ፡ ፩ ወሬዛ፡ እምርኁቅ፡ ብሔር፡ ዘመጽአ፡ በዕለተ፡ ተዝካሩ፡ ለአቡነ፡ ጸዊሮ፡ ማዕተበ፡ ሐዲሰ፡ በርእሱ፡ ወእንዘ፡ ይከይድ፡ በፍኖት፡ ወነሥአ፡ ማዕተቦ፡                                     ዖፈ፡ ጺላት፡ እምርእሱ።);
7. How the saint resurrected seventy children who had died in a landslide (incipit: ነበረት፡ እንዘ፡ ትገብር፡ ተዝካሮ፡ ለአቡነ፡ <hi rend="rubric">ገብረ፡ መንፈስ፡ ቅ<supplied reason="omitted">ዱስ፡</supplied></hi> በከመ፡ ነገራ፡                                    ብእሲ፡ ጻድቅ፡);
8. How the saint resurrected a child whose body was put in a jar (incipit: ዘኮነ፡ በዘመነ፡ መንግሥቱ፡ ለናኦድ፡ ዘገብረ፡ ለአሐቲ፡ ብእሲት፡ እምድኅረ፡ ሞተ፡ ወልዳ፡ ሕፃነ፡ ወፅአት፡ ወወሰደት፡ ኀበ፡ ይሰትዩ፡ ቤተ፡ ማኅበሮሙ፡ ለአቡነ፡                                    <hi rend="rubric">ገብረ፡ መንፈ<supplied reason="omitted">ስ፡ ቅዱስ፡);
9. How Gabra Manfas Qǝddus saved the poor man who had been killed by Satan because he had not denied the saint (incipit: ወነበረ፡ ፩ ብእሲ፡ በ፩ ሀገር፡ ወሰምዓ፡ መጽሐፈ፡ ገድሉ፡ ለአቡነ፡ <hi rend="rubric">ገብረ፡ መንፈስ፡ <supplied reason="omitted">፩ዱስ፡</supplied></hi> አመ፡ ፭ ለመጋቢት፡ ወጠየቀ፡ ከመ፡ ኮነ፡ ተዝካሩ፡ );
10. How the saint ordered a lion and a leopard to guard a cow and a ram for a year (incipit: ወነበረ፡ ፩ ብእሲ፡ ዘአኃዘ፡ ብዙኃ፡ ንዴት፡ እምብዝኃ፡ ንዴት፡ ከሀዶ፡ ለእግዚአብሔር፡ በልቡ፡ ወኃሠሠ፡ መሬተ። ወሶበ፡ የሐውር፡ በፍኖት፡ ረከበ፡ ሰይጣን፡                                     መስሐቲ፡ ወይቤሎ፡ አይቴ፡ ተሐውር፡ መኑ፡ ተኃሥሥ።).

Shall I proceed?

**Comment by MarcinKrawczuk** [comment]
Sorry for cutting in without being invited but I'm working now on BAVet142 so at least some of the work records would be very useful to me.

**Comment by MassimoVilla** [comment]
Thank you Marcin for noticing that. If there are no objections, I will then create those records and assign you too as a reviewer.

**Comment by thea-m** [comment]
Yes, please go ahead @MassimoVilla . @MarcinKrawczuk , there is no intruding! :)

**Comment by karljonaskarlsson** [comment]
Sounds perfect!
