### ISSUE TITLE
Record for "Miracles of Jesus" not displaying

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2259]
Something is wrong here: https://betamasaheft.eu/works/LIT2382Taamme/main

@eu-genia

**Comment by eu-genia** [comment]
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/works/LIT2382Taamme/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: string($arg as item()?) xs:string. Expected cardinality: zero or one, got 2. [at line 1093, column 69, source: /db/apps/BetMasWeb/modules/item.xqm] In function: item2:RestMss(item()*) [1368:84:/db/apps/BetMasWeb/modules/item.xqm] item2:RestSeeAlso(item()*, item()*) [1432:6:/db/apps/BetMasWeb/modules/item.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
Same error now for LIT2384Taamme

**Comment by eu-genia** [comment]
I have temporarily worked around by removing the link to the viewer for all mss in the witness box


```
1092
 else if($item//t:msIdentifier/t:idno/@facs) then 
                 <a class="w3-bar-item w3-circle" target="_blank" href="/manuscripts/{$itemid}/viewer">{
                if($item//t:collection = 'Ethio-SPaRe') 
               then <img src="{$config:appUrl ||'/iiif/' || string($item//t:msIdentifier/t:idno/@facs) || '_001.tif/full/140,/0/default.jpg'}" class="thumb w3-image"/>
(:laurenziana:)
else  if($item//t:repository[@ref = 'INS0339BML']) 
               then <img src="{$config:appUrl ||'/iiif/' || string($item//t:msIdentifier/t:idno/@facs) || '005.tif/full/140,/0/default.jpg'}" class="thumb w3-image"/>
          
(:          
EMIP:)
              else if(($item//t:collection = 'EMIP') and $item//t:msIdentifier/t:idno/@n) 
               then <img src="{$config:appUrl ||'/iiif/' || string(($item//t:msIdentifier)[1]/t:idno[@facs][@n]/@facs) || '001.tif/full/140,/0/default.jpg'}" class="thumb w3-image"/>
              
              (:BNF:)
            else if ($item//t:repository/@ref = 'INS0303BNF') 
            then <img src="{replace($item//t:msIdentifier/t:idno/@facs, 'ark:', 'iiif/ark:') || '/f1/full/140,/0/native.jpg'}" class="thumb w3-image"/>
(:           vatican :)
                else  if ($item//t:repository/@ref = 'INS0003BAV')
                then <img src="{replace(substring-before($item//t:msIdentifier/t:idno/@facs, '/manifest.json'), 'iiif', 'pub/digit') || '/thumb/'
                    ||
                    substring-before(substring-after($item//t:msIdentifier/t:idno/@facs, 'MSS_'), '/manifest.json') || 
                    '_0001.tif.jpg'
                }" class="thumb w3-image"/>
                (:Berlin:)
                  else  if ($item//t:msIdentifier/t:idno[contains(@facs, 'staatsbibliothek-berlin')]) 
                                                then
                                                    (: https://content.staatsbibliothek-berlin.de/dc/1751174670/manifest
                                            https:\/\/content.staatsbibliothek-berlin.de\/dc\/1751174670-0001\/full\/full\/0\/default.jpg:)
                                                    <img
                                                        src="{
                                                                replace($item//t:msIdentifier/t:idno/@facs, '/manifest', '-0001/full/140,/0/default.jpg')
                                                            }"
                                                        class="thumb w3-image"/>
                else 'Link to images' }</a>
```

now 
```
1092
 else if($item//t:msIdentifier/t:idno/@facs) then <span>Check the viewer</span>

```
@thea-m does it hurt? is it important that we have the link to the viewer with the thumbs in the witness box of works? i will try to look for the culprit but have not found it yet...

**Comment by eu-genia** [comment]
OK I found the culprits
![image](https://user-images.githubusercontent.com/17987728/197408166-8ea014b0-5ce3-4fd6-8f3d-5809a9f9c377.png)
and 
![image](https://user-images.githubusercontent.com/17987728/197368800-7aad9b8a-eb2a-4f8f-b1ea-ca5c86cbfb92.png)
should be all ok now, am putting the original code back in place but we must be very careful with doublets, so far I have seen two ways in which these are frequently created: (1) expanding files with xi:included transcription and (2) moving folders or downloading to wrong folders; doublets result in records not visualized but also corrupt all visualizations where these records would be linked to

**Comment by eu-genia** [comment]
The bug caused by wrong data has been solved so the thumbs are back in place but we can still discuss if we really need them or if a link ("Link to images") specifying that the images are available, without a small image, is sufficient - the thumbs are small and load fast but still if there are many they add up to loading time, and make the scrolling longer
I mean now we have
![image](https://user-images.githubusercontent.com/17987728/197773975-60ea49b1-b928-4370-a7ce-792f25b7742c.png)
but I wonder if this is sufficient to have
![image](https://user-images.githubusercontent.com/17987728/197774143-6220b4c4-923f-408b-a868-f4feda0c027a.png)
as we do for externally served images.
(And while we are at it I wonder what, at present state of manuscript texts digitized, the `word count` brings - it does take quite a bit of loading time)
