### ISSUE TITLE
A miniature on Joachim and Anne

### ISSUE THREAD

**Issue by GueshSol** [BetaMasaheft/Documentation#2260]
I'm describing a manuscript from the Art Institute of Chicago that contains illustrations which some of them seem they are not recorded in the art theme of the BM. One of these miniatures is a depiction showing Jochim and Anne grieving for not having a kid and an angel announcing to them that their prayer is received by God.
As it seems to me this art theme is not recorded, can I create an art theme for this miniature?
Thank you for your help,

**Comment by gnizla** [comment]
Hello, does the caption clearly indicate that they are grieving for not having a child? Or does it simply indicate that they are Joachim and Hannah?

**Comment by GueshSol** [comment]
It just indicates that they are grieving for not having a child.

**Comment by gnizla** [comment]
Then I would entitle it "Joachim and Anne grieving for not having a child" as it is not just a portrait of holy men/women but a narrative scene

**Comment by thea-m** [comment]
Thank you, @gnizla !

**Comment by eu-genia** [comment]
Is it now created as AT1146Anne? If yes can the issue be closed?

**Comment by eu-genia** [comment]
Sorry, AT1146JoachimAnnaGrieving

**Comment by gnizla** [comment]
Great!
