### ISSUE TITLE
Structure of SinaiEt002

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2263]
SinaiEt002 is a codex, composed of, according to the catalogue (and the images don't contradict this):
- ff. 1-57: parchment leaves
- ff. 58-59: paper leaves

Ff. 1-3 are presumably a protective quire; the main text begins on f. 4r.
Ff. 1v-3v and 55vb-59r contain, in a secondary hand, LIT2999RepCh279 (completely without textual breaks, as far as I saw).
https://www.loc.gov/resource/amedmonastery.0027938569A-ms/?sp=3

I would say that this corresponds to SdC transformation model A3 (ajout de contenu et de support matériel avec contenu). If we work under the assumption that a msPart corresponds to a unit of production (not to a unit of material), I would suggest to create two msParts:
p1: Ff. 1-57
p2: the entire text added on 1-3 and 55-59 (thus including Ff. 58-59).

What do you think?
@DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
meaning that ff. 55-57 belong to both p1 and p2? this may be correct in SdC but I do wonder about TEI XML... 
also considering that the hymn begins obviously on 55v, as an additio inserted into a blank

NB just to remind: Gumbert would not include 1-3 with msContent but with bindingDesc only (and would not number them continuously either), in that case the second text would be not a p2 but an a1.... and then there are additions on 53r and 54r in a hand similar to h2

Having had a look at the ms I would actually describe it NOT as a composite one. it only has 1 part with 1 main text, and an additio added on the protective leaves and blanks, while the protective flyer at the beginning is parchment, and the protective flyer at the end is paper (obviously added later)

the IDs still can be used in the SdC relations

**Comment by DenisNosnitsin1970** [comment]
I would also avoid considering the manuscript as composite. Two paper leaves at the end may be a part of the binding separate from the text block. The back board is not well visible, but it looks like the last paper leaf is glued upon it (pastedown). In my view, the text on the aforementioned leaves has a character of an addition ("GuestText"), and I would catalogue it as such.

**Comment by thea-m** [comment]
Thank you!
