### ISSUE TITLE
link does not wrok - error 500

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2264]
This link seems to be broken: https://betamasaheft.eu/works/LIT5400AmmestuTig/main

Al lI get is a lengthy error 500 report.

**Comment by eu-genia** [comment]
Next time please post the report (either as copypaste or as a snapshot), as I need the report for trying to understand and solve the bug

HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/works/LIT5400AmmestuTig/main: exerr:ERROR expected a single value for order expression $t/child::text() ; found: 2 [at line 4557, column 21] In function: viewItem:work(item()*) [5751:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1430:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
the error was mark up inside of `title`, which is not accepted
