### ISSUE TITLE
A doubt concerning person record PRS13524Marqos

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2269]
A certain Mārqos (https://betamasaheft.eu/persons/PRS13524Marqos/main) is credited as being an author of the Discourse of Dionysius on the Martyrdom of Sts Peter and Paul (https://betamasaheft.eu/works/LIT4841Discourse/main). It sounds a bit suspicious. Is it correct? If so, maybe one could add a few words explanation?
@DenisNosnitsin1970 @MassimoVilla @eu-genia @thea-m

**Comment by DenisNosnitsin1970** [comment]
Indeed, Marqos is not the author, but he is said to have contributed to the translation of the work. This information is found in the subscription to the Discourse, in the edition of Budge (1899, text p. 66) and a few  manuscripts of GH that I was able to check (starting from a few old ones, e.g. `<ref type="mss" corresp="ESmy004"/>`). I must say that the way it is said is not very straight, (ዘአስተንተነ፡ በንቅለተ፡ ዛቲ፡ መጽሐፍ፡ ... አቡነ፡ ማርቆስ፡ ዘደብረ፡ ሰብራ፡... ለአኃው፡ ... ኢትዮጵያውያን፡), but I would interpret it as above. The information does not appear anywhere, I think it is good to have it explicit. If correct, it should perhaps be included in the record for the work, but one would need to check more mss for that.

**Comment by MarcinKrawczuk** [comment]
Great, thank you!

śr., 2 lis 2022 o 10:20 DenisNosnitsin1970 ***@***.***>
napisał(a):

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Persons/pull/652
