### ISSUE TITLE
Abb 102 composite?

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2270]
Please look at ms Abbadie 102, fol. 52 (I attach a pdf because the Gallica link for this manuscript 
does not work for the moment
[Abb 102 fols 110 - 112.pdf](https://github.com/BetaMasaheft/Documentation/files/9919502/Abb.102.fols.110.-.112.pdf)
). It looks like a peculiar technique was used to construct fol. 52. A rectangular hole was (later?) cut in the original parchment leaf, and another one was attached upon it (glued?), that had a miniature and a text. Thanks to the rectangular opening, the text on the verso side is visible. Should I catalogue this manuscript as composite? I would say, yes, thoug I see such a "collage-technique" for the first time, and cannot see on the images all details well.

**Comment by eu-genia** [comment]
I am not sure that using "maculature" for illuminations (just as for binding) makes the ms a composite, for me a composite ms is the result of a deliberate wish to bring texts together; in this case the text visible on the verso is an "accident". 

Here https://msdesc.github.io/consolidated-tei-schema/msdesc.html I read
`The use of [<msPart>](https://msdesc.github.io/consolidated-tei-schema/msdesc.html#TEI.msPart) is not recommended for describing added text or decoration where this has been added on the original codicological unit as a supplement to existing text`

but I am not sure which is then the suggested way of dealing with this issue, but if my understanding is right, and the text is just a fragment visible by accident, I would avoid using an `msPart `for it. maybe make a clear comment in the `decoNote` and then use, if wished, our SdC stratigraphy relations to describe what has happened.

**Comment by eu-genia** [comment]
if the text is running on, and the main text continues on the verso of the image, then again this is not necessarily an `msPart `I think, but a replacement/correction technique.

**Comment by eu-genia** [comment]
"Replacement leaves" are described as an `msPart `here https://msdesc.github.io/consolidated-tei-schema/msdesc.html#mssReplacementLeaves - could this be a case of a partial replacement leaf?

**Comment by DenisNosnitsin1970** [comment]
In a number of cases it is exactly the problem, to decide what was deliberate, from the point of view of the manuscript maker, and what was not. The leaf is not a replacement. It may be considered occasional attempt to accomodate an spare image . But it might have been also a conscious attempt to add the miniature "Virgin Mary and Child" to the otherwise very long series of miniatures which "misses the main scene" (the style of the miniature is similar to the others, though I cannot judge it very well - but possibly the same artist). The hole cut in the leaf is unusual, the text on the other side, Malke' to St George, is the beginning only with no continuation (there is however one miracle of George in the ms), but it might be not so meaningfull in the context (at a few other occassions I saw that manuscript-makers prefer to keep a text visibe, if there is a chance for that, with no consideration to link it  to the main content). My tentative conclusion would be:  the added miniature could be a deliberate attempt to "complement" the iconographic programm, the tex on the other side is not so important.

**Comment by eu-genia** [comment]
How did we deal with pasted images? This is just the same, only that by chance there is a text on the verso...

**Comment by DenisNosnitsin1970** [comment]
Ok, I will look up.

**Comment by eu-genia** [comment]
checked:_pastedowns can be described as `accMat` https://www.tei-c.org/release/doc/tei-p5-doc/de/html/MS.html#msadac so I would probably use `accMat `here as well

**Comment by eu-genia** [comment]
maybe yes. could not yet find a similar case among tei encoded mss.
palimpsest layers are surely described as `msPart`s, so the same leaf may belong to several `msPart`s simultaneously, in a way this is also a case of material reuse

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/1922
