### ISSUE TITLE
Online MSS in the British Royal Collection

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2271]
Here is a link to some online manuscripts in the British Royal Collection: http://www.rct.uk/collection/search#/retrieve/b5de0f7c9981c78599ab0c8756218284cb844fb1

It seems like they are not listed on our page for Ethiopic MSS available online.

**Comment by thea-m** [comment]
Thank you, Jonas!

**Comment by eu-genia** [comment]
they have some inconsistencies in the manifests they provide (like blanks in URIs), so the only one that would work is for the moment EthWindsor2. i might have to go for graphic url instead...
