### ISSUE TITLE
BML images not loading?

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2272]
Is there a problem with (most of) the BML (Laurenziana) images on BM? Yesterday, some of them loaded but most wouldn't, and today even fewer seem to work properly. See, for example, https://betamasaheft.eu/manuscripts/BMLor70/viewer.

**Comment by karljonaskarlsson** [comment]
It's possible that it's a broader problem. These images also don't work:
https://betamasaheft.eu/manuscripts/EMIP00999/viewer
https://betamasaheft.eu/manuscripts/EMIP00018/viewer
https://betamasaheft.eu/manuscripts/ESum035/viewer
https://betamasaheft.eu/manuscripts/Tanasee29/viewer

**Comment by eu-genia** [comment]
should be all ok, iiif server restarted
