### ISSUE TITLE
protective prayers in BDLaethf27

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2274]
I would like to create new work records for the following protective prayers attested in BDLaethf27 (JJ-24; images only in the raw folder), in case you don't find records for them either. The order in the scroll is column a top-bottom, then column b top-bottom. 
(I know these issues are not terribly fun, but in the same scroll, there are also six prayers for which I found already existing IDs, so I think that record creation for these protective texts is really the right way to proceed.)

1.	Protective prayer against the evil eye, with ʾasmāt
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ሕማመ፡ ዓይነ፡ ባርያ፡ ወሌጌዎን፡ ገሃነ፡ አርያስ፡ ስውር፡ ሰሙር፡ አግናከር፡ አግናጠር፡ አሙተዳናብኆልት፡ ይሰልብ፡ ልበ፡ ሰብእ፡ ወያጸልም፡ አእይንተ፡ ወይመጽእ፡ ከመ፡ ጽላሎት፡ በመአልት፡ ወበሌሊት፡ አመሐልኩክሙ፡ ወአውገዝኩክሙ፡ በ፭ ቅንዋተ፡ መስቀሉ፡ ለእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡
Explicit: ወመሳነን፡ በድንጋፄ፡ ወጽጋም፡ ወተንኰል፡ በመድኀኒት፡ ወንስናሽ፡ ወሾተላይ፡ ወቆቆላይ፡ ወዓይነ፡ ወርቅ፡ ወልጅ፡ ገዳይ፡ በመጋኛ፡ ወቍራኛ፡ በአስማተኛ፡ ወማርተኛ፡ በበደለኛ፡ ወበተንኰለኛ፡ ወቍመኛ፡ በዝ፡ ኵሉ፡ አመሐልኩክሙ፡ ወአውገዝኩክሙ፡ ከመ፡ ኢትቅረቡ፡ ኀበ፡ ነፍሳ፡ ወሥጋሃ፡ ለአመትከ፡
2.	Protective prayer against bāryā and legewon (different from the preceding)
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ባርያ፡ ወሌጌዎን፡ ርኩስ፡ ዘይሰልብ፡ ልበ፡ ሰብእ፡ ወያጸልም፡ አዕይንተ፡ ወይመጽእ፡ ከመ፡ ጽላሎት፡ በመዓልት፡ ወሕልም፡ አምሐለከ፡ ወአውግዝከ፡ በ፭ ቅንዋተ፡ መስቀሉ፡ ለእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ ሳዶር፡ አላዶር፡ ዳናት፡ አዴራ፡ ሮዳስ፡
Explicit: እሰሮሙ፡ ከመ፡ ኢይቀረቡ፡ ወእለሂ፡ ቀርቡ፡ ይፃዑ፡ ዘሀለው፡ እመሂ፡ በሐቍ፡ ወእመሂ፡ በአቍያጽ፡ እመሂ፡ በአእደው፡ ወእመሂ፡ በአእጋር፡ ወበኵሉ፡ አካላት፡ ዘይቈረጥሙ፡ ወየሐምሙ፡ ወያመጽኡ፡ ንዋመ፡ በመዓልት፡ ወበሌሊት፡ ወያንቀጠቀጡ፡ ወኢይቅረቡ፡ ኀበ፡ ነፍሳ፡ ወሥጋሃ፡ ለአመትከ፡ 
3.	Protective prayer for the binding of demons, with ʾasmāt
Complete text: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ማዕሠሮሙ፡ ለአጋንንት፡ አክያ፡ ሽራህያ፡ እልሻዳይ፡ እልመክኑን፡ አልፋ፡ ድልጠ፡ ቤጠ፡ ወየውጠ፡ ፀባዖት፡ ወእ፡ ኢየሱስ፡ ክርስቶስ፡ ወልደ፡ እግዚአብሔር፡ ሕያው፡ ወወልደ፡ ማርያም፡ ሥግው፡ ዘበመስቀልከ፡ አጽራዕከ፡ ግብሮ፡ ለዲያብሎስ፡ ከመሁ፡ አጽርዕ፡ ሕማመ፡ ባርያ፡ ወሌጌዎን፡ ቍራኛ፡ ወተያጅ፡ መጋኛ፡ ወእሥምት፡ ዓይነት፡ ወውግዓት፡ ቍርፀት፡ ወፍልፀት፡ መትዓት፡ ወጽፍዓት፡ ምች፡ ወተላዋሽ፡ ፌራ፡ ወንዳድ፡ ግብጥ፡ ወዛር፡ መዋቂ፡ ወነቀኝቃኝ፡ ሾተላይ፡ ወትግርትያ፡ ወቍርጥማተ፡ እድ፡ ወእግር፡ ሓቌ፡ ወዘባን፡ ወኵሉ፡ አባለ፡ ሥጋ፡ ቡዳ፡ ወነሃብት፡ ሰብእ፡ ግብር፡ ወጠበብት፡ ቸንፍር፡ ወነገርጋር፡ ድድቀ፡ ወጋኔነ፡ ቀትር፡ ይሰድዱ፡ ወይርሐ<ቁ፡ እምላዕለ፡ ነፍሳ፡ ወሥጋሀ፡ ለአመትከ፡ 
4.	Mark 5:1-13
Incipit: ወንጌል፡ ዘማርቆስ፡ ወበጺሆ፡ ማዕዶተ፡ ጊርጌሴኖን፡ ተቀበልዎ፡ ሶቤሃ፡ ለብእሲ፡ እመቃብር፡ ዘጋኔን፡ እኩይ፡ ላዕሌሁ፡ ዘኮነ፡ ማኅደሩ፡ ማዕከለ፡ መቃብራት፡ ወዓዓቅብዎ፡ ደቅ፡ ወአልቦ፡ ዘክህለ፡ ከመ፡ ያጽንዖ፡ በሰናስል፡ ሶበ፡ ተፈትሐ፡
Explicit: ወአብሆሙ፡ እግዚእ፡ ኢየሱስ፡ ወወዲሶሙ፡ ሶቤሃ፡ እሙንቱ፡ አጋንንት፡ ቦኡ፡ ላዕለ፡ አኅርው፡ ወአብዱ፡ መራእየ፡ አኅርው፡ ወመጽኡ፡ ኵሎሙ፡ መራእይ፡ ኀበ፡ ኀይቅ፡ ወጸድፉ፡ ውስተ፡ ባሕር፡ ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ በዝ፡ ቃለ፡ ወንጌልከ፡ ገስጾሙ፡ ወአርኅቆሙ፡ ለመናፍስተ፡ ደዌ፡ ርኩሳን፡ ወአጋንንት፡ ፀዋጋን፡ ወትግርትያ፡ እቡያን፡ ወሠብእ፡ መሠርያን፡ እምባርያ፡ ወሾተላይ፡ አድኅና፡ ለአመትከ፡
5.	Protective prayer against stomachache, with ʾasmāt
Complete text: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርፀት፡ በከ`<gap reason="illegible" unit="chars" quantity="1"/>`ኮዕ፡ ስምከ፡ በርያኖስ፡ ስምከ፡ በጸሔል፡ ስምከ፡ በአማኑኤል፡ ስምከ፡ በክርስቶስ፡ ስምከ፡ በኅቡዕ፡ ስምከ፡ ወበክሱት፡ ስምከ፡ ተማኅፀንኩ፡ እልፍሉል፡ እልፍሉል፡ እልፍሉል፡ እልፍሉል፡ ጸሎተ፡ ሕማመ፡ ቍርፀት፡ ዘተፈነወ፡ እምኀበ፡ አብ፡ ወወልድ፡ መንፈስ፡ ቅዱስ፡ ከመ፡ ያርዳዕ፡ ወይቤዙ፡ ውሉደ፡ ሰብእ፡ ወእንስሳ፡ እንዘ፡ ይጐጸጕጽ፡ ገበዋተ፡ ወይራነቅል፡ 
ቍልፈተ፡ ወይቈርፅ፡ ከማዑተ፡ ሸገር፡ ሸገር፡ ሸገር፡ ደር፡ ደር፡ ደር፡ በኃይለ፡ ዝንቱ፡ አስማቲከ፡ አድኅና፡ እምሕማመ፡ ቍርፀት፡ ለአመትከ፡ 
6.	Protective prayer against the fear of demons (?)
The phrase "ወፍጹም፡ በጽልመት፡ ፈርሃ፡ ወደንገፀ፡ ዲያብሎስ፡ ርእዮ፡ ብሁተ፡ ልደት፡ በሥጋ፡ አምላክ፡ በሲኦል፡" occurs in several scrolls, but I didn't find in exactly this context.
Complete text: ጸሎት፡ በእንተ፡ ድንጋፄ፡ አጋንንት፡ ዘመዓልት፡ ወዘሌሊት፡ ባርከኒ፡ ክርስቶስ፡ አምላኪየ፡ ዕቀበኒ፡ ወአድኅነኒ፡ እምድንጋፄ፡ አጋንንት፡ ወፍጹም፡ በጽልመት፡ ፈርሃ፡ ወደንገፀ፡ ዲያብሎስ፡ ርእዮ፡ ብሁተ፡ ልደት፡ በሥጋ፡ አምላክ፡ በሲኦል፡ እወግዞሙ፡ ለአጋንንት፡ እኩያን፡ በመለኮተ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ዘይወጽእ፡ እምአፉሁ፡ ሰይፈ፡ እሳት፡ በአብ፡ እትዌከል፡ ወበወልድ፡ እትኬስል፡ በዘቦቱ፡ ለሰሐ፡ ሕምዙ፡ ለሞት፡ አድኅና፡ ለአመትከ፡  
7.	Matthew 8:28-32
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ወንጌል፡ ዘማቴዎስ፡ ወበጺሆ፡ ማዕዶተ፡ ጌርጌሴኖን፡ ተቀበልዎ፡ ፪ አጋንንት፡ ወወጺኦሙ፡ እማዕዶተ፡ እምውስተ፡ መቃብራት፡ እኩያን፡ ጥቀ፡ ወጸዋግናን፡ ወኢያበውኁ፡ እስከ፡ ሶበ፡ ኢይክሉ፡ ኃሊፈ፡ መኑሂ፡ እንተ፡ ይእቲ፡ ፍኖት፡ ወሶበ፡ ርእዮ፡ ለእግዚእ፡ ኢየሱስ፡ ፀርሁ፡
Explicit: ወአተው፡ ውስተ፡ ሀገር፡ ወዜነው፡ ኵሎ፡ ዘከመ፡ ርእዩ፡ ወበእንተ፡ እለ፡ አጋንንት፡ ወናሁ፡ ኵሎ፡ ዘውስተ፡ ሀገር፡ ወጽኡ፡ ወተቀበልዎ፡ ለእግዚእ፡ ኢየሱስ፡ ወሶበ፡ ርእይዎ፡ ለእግዚእ፡ ኢየሱስ፡ ወአስተብቍዕዎ፡ ላዕለ፡ አሕርው፡ ወአብዱ፡ መራእየ፡ አሕርው፡ ወመጽኡ፡ ኵሎሙ፡ መራእይ፡ ኀበ፡ ኀይቅ፡ ወጸድፉ፡ ውስተ፡ ባሕር፡ ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ በዝቃለ፡ ወንጌልከ፡ ገስጾሙ፡ ወአርኅቆሙ፡ ለመናፍስተ፡ ደዌ፡ ርኩሳን፡ ወአጋንንት፡ ፀዋጋን፡ ወትግርትያ፡ እቡያን፡ ወሰብእ፡ መሠርያን፡ እምባርያ፡ ወሾተላይ፡ አድኅና፡ ለአመትከ፡ 
8.	Protective prayer against the evil eye
Complete text: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ሕማመ፡ ዓይን፡ ወፍልፀተ፡ ርእሰ፡ ክርስቶስ፡ ብርሃን፡ ወምእመን፡ ዝበምራቅከ፡ ከሠትከ፡ አዕይንተ፡ እውራን፡ ወበቃልከ፡ ይትፌውሱ፡ ድውያን፡ ዛቲ፡ ነፍስ፡ ሕምምት፡ ወጥውቂት፡ ትርክብ፡ ፈውሶ፡ ዘይቀጠቀጥ፡ ርእሰ፡ ወየለ፡ ወይሰቀሰቀ፡ አዕይንተ፡ ወይሐቂ፡ አስናን፡ ወይጐጸጉጽ፡ ገበዋተ፡ ወይፈነቅል፡ ቍልፊተ፡ ወይቈርፅ፡ እማዑተ፡ ወያደቅቅ፡ አእፅምተ፡ በስመ፡ እግዚአብሔር፡ ሕያው፡ ዘጸሐፈ፡ ኤርምያስ፡ ነቢይ፡ ዲበ፡ ኰኵሕ፡ ኀበ፡ ታቦት፡ ማይ፡ እንተ፡ ተከድነት፡ በደመና፡ ሰማይ፡ በይእቲ፡ ስም፡ ይሕልፍ፡ ወይሰስል፡ ዝንቱ፡ ሕማመ፡ ዓይነት፡ እምላዕ አመትከ፡ 
9.	Protective prayer for the drowning of demons, for Sunday
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎተ፡ መሥጥም፡ ዘዕለተ፡ እሁድ፡ ሰንበት፡ ዓቃቢሁኒ፡ ሰቁኤል፡ ወኮክቡኒ፡ ሽመሽ፡ አሁማ፡ ያችናጅ፡ አልመለኪ፡ ወያኑራ፡ ተዋቂራ፡ ሐጅ፡ መረጅ፡ ሐቅወ፡ መግኑን፡ ኆቤ፡ ወመድኑን፡ በሕትሙኪን፡ ሸይጣን፡
Explicit:     ይሠዓር፡ ሥራይክሙ፡ ወይልሣሕ፡ ሕምዝክሙ። ወይድክም፡ ኃይልክሙ፡ ወይስበር፡ ርእሰክሙ፡ ወይትቀጥቀጥ፡ አዕፅምቲክሙ፡ በዝ፡ ጠልሰም፡ ወበዝ፡ አስማት፡ ኩኑ፡ 
 ርኡዳነ፡ ወድንጉፃነ፡ ኢትቀረቡ፡ ኀበ፡ ነፍሳ፡ ወሥጋሃ፡ ለአመትከ፡
10.	Salām-hymn to Rāguʾel
Incipit: ሰላም፡ ለከ፡ ራጉኤል፡ ሊቀ፡ ሊቃናት፡ ፯ቱ፡ በገጸ፡ አምላክ፡ ትቀውም፡ ለለዕለቱ፡ ሰዓል፡ ለለሰዓቱ፡ ሰላም፡ ለከ፡ መልአከ፡ ቅዳሴ፡ ራጉኤል፡ ዘውገ፡ ቅዳስያን፡ እንስሳ፡ ሰዓል፡ ሊተ፡ ሰሬቀ፡ አበሲ፡ ኀበ፡ ወልድ፡ ለምሕረት፡ ዘሰብሳ።
Explicit: ሰላም፡ ለከ፡ ምክንያተ፡ ጽሂን፡ ራጉኤል፡ አምጣነ፡ ተሐሥሥ፡ አንተ፡ ከመ፡ አምላክከ፡ በሥጋ፡ ዘሞተ፡ ተወኪሊከ፡ ማኅሌትየ፡ ዘንተ፡ ጸግወኒ፡ ሠናየ፡ ዕሤተ፡ ሰላም፡ ለከ፡ ዘኃይስተ፡ ሰማይ፡ ልዑል፡ ራጉኤል፡ ሊቅ፡  መልአከ፡ ኃይል፡ እስመ፡ አንተ፡ መልአከ፡ ሣህል፡ ሰላም፡ ለከ፡ እግዚኦ፡ አድኅና፡ አምሕማመ፡ ዓይነ፡  ወርቅ፡ ለአመትከ፡  
ወገፁ፡ ዘፍጹም፡ በጽልመት፡ ፈርሃ፡ ወደንገፀ፡ ዲያብሎስ፡ ርእዮ፡ ብሁተ፡ ልደት፡ በሥጋ፡ አምላክ፡ በሲኦል፡ ወሪዶ፡ ዘበመስቀልከ፡ አጽራዕከ፡ ግብሮ፡ ለዲያብሎስ፡ ከማሁ፡ አጽርዕ፡ ሕማመ፡ ዓይነ፡ ባርያ፡ ወፍልፀተ፡ ርእስ፡ ለአመትከ፡

@MassimoVilla @karljonaskarlsson

**Comment by MassimoVilla** [comment]
Dear Thea,
here the results of my search:
Prayer n. 2 is found in some MSS and I think it is to be identified with LIT4619Prayer.
Prayer n. 3 is also attested in MS EMIPms00511 (Portland, EMIP, Tweed MS 43), but the work has no ID, so a work record is necessary.
Prayer n. 6: as you have already noted, I have only found a partial correspondence with LIT6714PPIllness (which you created) but the full text of this prayer is different.
Prayer n. 9 (ጸሎተ፡ መሥጥም፡) is found in EMIP02089#i13, but with no ID, so a work record is necessary.
For the other prayers/texts, I have found no correspondence, so I would create new work records for them

**Comment by thea-m** [comment]
Thanks a lot, Massimo! I will go ahead with the record creation.
Just a question regarding text 2: The introduction is attested in several manuscripts, but I could not identify another manuscript (or edited excerpt by Worrell) where it is exactly identical. LIT4619Prayer is only attested in manuscripts of which we have no images or more text. Did you find one where the complete text was more or less identical?

**Comment by MassimoVilla** [comment]
Unfortunately not! MSS BL Oriental 535 and BAV Et. 77 are likely to bear the same text but cataloguers only provided the incipits, so we can't be sure. The possibility that it is a different prayer cannot be excluded (I created a different record LIT4693MagicPr for a prayer which has identical incipit but then adds the "Sator-square" formula).

**Comment by MassimoVilla** [comment]
It is difficult to choose without knowing the text currently encoded as LIT4619Prayer. But the problem is with MSS BL Oriental 535 and BAV Et. 77 which are insufficiently documented, not with the text in BDLaethf27.
A good option would be in my view to assign LIT4619Prayer to our text (for which we have more detailed incipit and explicit and therefore a sound basis for later comparisons), and to update MSS records BL Oriental 535 and BAV Et. 77 by stating that the prayers trasmitted therein are assigned the ID LIT4619Prayer with some (medium?) degree of certainty.
Does this go beyond the scope of our project?

**Comment by thea-m** [comment]
I think that's a good solution!
