### ISSUE TITLE
Cambridge mss online

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2275]
Maybe we could add the following link to the list of digitised manuscripts?

https://cudl.lib.cam.ac.uk/collections/ethiopianmanuscripts/1

**Comment by eu-genia** [comment]
i believe we have the facs for Cambridge mss already, so the images are also availlable in our viewer, the intro says

`Please note that via our Mirador viewer we also link to manifests made available by other institutions like the Digital Vatican Library, Windsor Royal Castle, Berlin State Library, the Bibliothèque nationale de France, Princeton University Library, Library of Congress, Chester Beatty Library, Cambridge, and many others.
`
but of course can add to the list as well, thank you
