### ISSUE TITLE
Using transkribus2BM transformation

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#2276]
I have noticed that the transkribus text file produced by transkribus2BM has not done what I expected. There is a significant amount of the transcribed text missing. 

when filling out the parameters I noted 'single sided' and added the number of image files as the number of foliated leaves parameter. 

![image](https://user-images.githubusercontent.com/39619238/202468558-b582d0bf-1107-4798-ace1-6018aef6a2fb.png)

I don't seem to be able to attach xml files to this issue (it generates an error message when I try), so I'll email them to you

**Comment by eu-genia** [comment]
The xsl transformation is not for the moment dealing with scrolls, it is set up for codices. The difference between selecting "`opening`" or "`singleSide`" is for calculating the folio number.
If you select `opening`, then each image/`facs `is counted as if it were numbered 1 (f. 0v-1r), 2 (1v-2r), 3 (2v-3r) etc, if you select singleSide it thinks that the images are separately r and v so image 1 = folio 1r, image 2 = folio 1v, image 3 = folio 2r, image 4 = folio 2v, etc.
There is no parameter for scrolls, the xslt says
```
 <xsl:variable name="folio" 
            select="$imagenumber - $emptyimagesbeginning"/>
          <xsl:message>folio <xsl:value-of select="$folio"/></xsl:message>
          <!--                select the pb relevant for the current folio. if it is an image of an opening takes page breaks with 
                    @n equal to the image number, otherwise multiplies by 2 and removes one to get only the recto-->
          <xsl:variable name="rectoPB" 
            select="if($imagetype = 'opening') 
            then $this//t:pb[@n=$imagenumber] 
            else $this//t:pb[@n=(($imagenumber*2) -1)]"/>
```
Have you tried with `opening`? When I test with `opening `I do get the entire text.

Did you also do singleSide here https://github.com/BetaMasaheft/Documentation/issues/2248 ?

**Comment by eu-genia** [comment]
Please always use `opening`, you will come up with empty `versos`, I will try to tweak the xslt for scrolls in the future, but for now go with opening, then you have the correct number of images and full text

**Comment by Ralph-Lee-UK** [comment]
thank you for this - yes I have tried this, and all is in order.
