### ISSUE TITLE
problem with creation of IDs: persons IDs not saved 

### ISSUE THREAD

**Issue by vitagrazia81** [BetaMasaheft/Documentation#2277]
@eu-genia, 
I have still problems with  the creation of persons Ids.
Here the message I got:

Unfortunately PRS13949NǝwāyaMāryām could not be saved

This is the first error which occurred Permission to modify permissions is denied for user 'Vitagrazia' on '/db/apps/expanded/persons/new/PRS13949NǝwāyaMāryām.xml': exerr:ERROR Resource or collection '/db/apps/expanded/persons/new/PRS13949NǝwāyaMāryām.xml' does not exist., feel free to copy it and send it to info@betamasaheft.eu.

**Comment by eu-genia** [comment]
This is very strange as the record has been created 6 times (you clicked Create new record 6 times)

![image](https://user-images.githubusercontent.com/17987728/202705124-04125a93-33b0-47d7-b706-b52eb9ffd79f.png)

I will now delete all these new records and we will try again together when you are back in

**Comment by vitagrazia81** [comment]
Actually, I have not clicked for a record 6 times, but 6 times, because 6 were my tries (each new).

**Comment by eu-genia** [comment]
and each time you created a new record.
