### ISSUE TITLE
Work record for a salām-hymn to Kiros

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2278]
In BAVet142 there is a salām-hymn to Kiros, with the incipit:

ሰላም፡ ለከ፡ በእንቲአከ፡ ተብህለ፡ እመድሎተ፡ ሰማይ፡ ወምድር፡ ይፈደፍድ፡ ጥቀ፡ ዘእግርከ፡ ጽፍር፡ ኪሮስ፡ ምሉዓ፡ ክብር፡

Apparently it can also be found in ESdmd013. But I don't see a work record for it, so I'm asking for a permission to create one.

@thea-m @DenisNosnitsin1970

**Comment by thea-m** [comment]
I didn't find one either, please go ahead!
