### ISSUE TITLE
New modifications do not display

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2286]
Two of my recent modifications do not display correctly after merging:

https://betamasaheft.eu/works/LIT2130OntheI/main
https://betamasaheft.eu/works/LIT1271Dersan/main

@eu-genia

**Comment by eu-genia** [comment]
please correct the files and push to a new branch, thank you

**Comment by duncdrum** [comment]
@eu-genia hmm looks like an internal azure / GitHub error. I ll have a look
