### ISSUE TITLE
claves abbreviations in the search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2287]
Could we spell out the claves abbreviations in the search? That would make them more accessible. CC, KRZ and H require some insider knowledge :) (H could be given as "Hammerschmidt Anaphoras" or similar)
@eu-genia 
![image](https://user-images.githubusercontent.com/19650382/206425893-b2914488-2913-4042-bed0-f28a46c1153b.png)

**Comment by eu-genia** [comment]
CC is Clavis Coptica

sure, will do

**Comment by eu-genia** [comment]
I am not sure what the last item in the list, H, stands for

**Comment by thea-m** [comment]
Hahaha, obviously this was necessary. I would have sworn that "CC" stands for Corpus Coranicum. Thanks!
