### ISSUE TITLE
A prayer Särawitä mäla'ekt...

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2289]
I propose a new record for the prayer that starts like ኵሎሙ፡ ሰራዊተ፡ መላእክት፡ መንፈሳዊያን፡
ነደ፡ እሳት፡ እሙንቱ፡ ይጸርኁ፡ ወይብሉ፡ ካልእ፡ ለካልኡ፡ ሱራፌን፡ ይብሎ፡ ቅዱስ፡ ወኪሩቤል፡ ይብሉ፡ እሳት፡ etc.  It is found in Sinai 4 (fols 3r-4r ) and in BAVet15 (fols 115va-116ra), possibly related to but dissimilar from LIT4965Kwellomu.

**Comment by eu-genia** [comment]
ok for me

**Comment by thea-m** [comment]
Yes, please go ahead
