### ISSUE TITLE
EMIP Tweed Project Edits Today 20th December

### ISSUE THREAD

**Issue by Ralph-Lee-UK** [BetaMasaheft/Documentation#2290]
Eugenia - I started work on the wrong branch today, and appear to have made some errors which are now confusing me. You approved some changes this morning and merged to master. These were all correct - but what I have done since then needs correcting. Is there a way that you can reset the records to just after you merged into master with the pull request that I made yesterday?

**Comment by eu-genia** [comment]
Dear @Ralph-Lee-UK if the merge is correct then I would not want to unnecessarily undo it. Can you simply start a new branch from (updated) master and bring your changes there? You can save the XML files you are working on to a temporary folder and then copy them back in once the new branch has been created. Would this work?
