### ISSUE TITLE
A mss record for BNFabb62/63 - one or two?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2293]
I wanted to expand the work record for መጽሐፈ፡ ሚላድ፡ and provide also a list of witnesses. In order to do so I would need to create a stub for BNFabb62/63. According to Wendt, "es handelt sich eigentlich um zwei verschiedene zusammengebundene Manuskripten", the description by CCR is as follows.

![CCR no 140](https://user-images.githubusercontent.com/62760230/210266856-79831710-6b8a-415d-bab2-381708ad2ffa.jpg)

The question is: should I create two separate manuscript records BNFabb62 and BNFabb63? If yes, how do I encode Zusammenbindung - is a note enough or is there a more sophisticated way?

@DenisNosnitsin1970 @thea-m @eu-genia

**Comment by DenisNosnitsin1970** [comment]
I think you can create two records, one for abb62 and a stub for abb63 at least (if it does not the aim that you have now). I assume the explanation can be inserted in the binding description and/or history.

**Comment by MarcinKrawczuk** [comment]
@thea-m - would you like to weigh in?
@eu-genia  - if I follow your suggestion, what should the file name be?

**Comment by thea-m** [comment]
I agree to create the record according to the current units of circulation, i.e. one record with several msParts.

**Comment by eu-genia** [comment]
You can have the file name as BNFabb62and63 or something like that
