### ISSUE TITLE
Work doublet Wǝddāse ʾǝm-qāla nabiyāt? 

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2296]
I wonder if the https://betamasaheft.eu/works/LIT2507Weddas/main?hi=wǝddāse and https://betamasaheft.eu/works/LIT4026Weddas/main might refer to the same work. I suggest that the former of them is deleted, as it has never been used, as far as I can see.

**Comment by eu-genia** [comment]
I think you are right.
