### ISSUE TITLE
titles.html error

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2297]
An error has occurred
something has gone wrong. Sorry! This error has been generated by the application.

exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: range:field($fields as xs:string+, $operators as xs:string+, $keys as xs:anyAtomicType*, ...) node()*. Expected cardinality: one or more, got 0. [at line 1194, column 123, source: /db/apps/BetMasWeb/modules/view.xql]
In function:
	lists:titlesRes(node(), map(*)) [-1:-1:/db/apps/BetMasWeb/modules/resources.xqm]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [237:13:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [428:17:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*) [230:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [133:51:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [90:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:apply(node()+, function(*), map(*)?, map(*)?) [50:5:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]

**Comment by eu-genia** [comment]
The scripts all worked last month and the search results came up, there must have been something inserted in the data that disrupts performance

**Comment by thea-m** [comment]
I didn't find I anything. I checked the recent commit history, the other commits of 9 January went through. The only manuscript recently worked on with corresps in divs is BNFAbb66B, where all msItems referred to do exist.

**Comment by eu-genia** [comment]
By going through each commit and replacing expanded files provisionally with a stub I discovered that the error was indeed somewhere in BNFabb66B, the latest commit with this MS did not fully go through, I have updated the file now and reexpanded it, and all is back in function.

**Comment by thea-m** [comment]
Thank you! But was there a reference to a non-existent msItem in BNFabb66B or was it only the synchronisation issue? I did not find one.

**Comment by eu-genia** [comment]
Honestly I must admit I did not go through the file, I just replaced it. There was something with the `div`s (maybe an extra space, that would have been enough). I was just happy to be able to get all back to work.
