### ISSUE TITLE
BDLaethe34 not visualised

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2298]
As pointed out by @karljonaskarlsson the stub BDLaethe34 is not visualised "BDLaethe34 is not an available item." - xml:id and filename seem fine to me, I couldn't find any other problem either.

**Comment by eu-genia** [comment]
I cannot find a file by such name. I can see BDLaeth34 is it the one you need?

**Comment by eu-genia** [comment]
I see now under JJ. strangely the expanded file with this filename has ID BDLaethb6

**Comment by eu-genia** [comment]
I have corrected manually the expanded file but have to explore further why it expands with the wrong xml:id

**Comment by thea-m** [comment]
Thank you! Now I see the xml:id used to be (erroneously) BDLaethb6 - I had corrected this on 9 January, but apparently it didn't come through

**Comment by eu-genia** [comment]
OK I have reuploaded BDLaethe34 and reexpanded both, now all OK )

**Comment by thea-m** [comment]
Great, thank you!
