### ISSUE TITLE
Sinai MSS title not visualised

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2299]
https://github.com/BetaMasaheft/Documentation/issues/2297
Going through the commit history - the page titles of SinaiEt001-004 are not printed. SinaiEt006 looks normal. I can see no difference in the encoding.

**Comment by eu-genia** [comment]
this sometimes happens at first commit/expand , at the next commit the title would appear, have now expanded

**Comment by thea-m** [comment]
Thank you! @karljonaskarlsson

**Comment by karljonaskarlsson** [comment]
Thank you both! :)
