### ISSUE TITLE
supplicative prayer

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2300]
I could not identify a prayer attested in SinaiEt005, 113ra-115rb (the beginning is missing). It is somewhat similar in style and some expressions to the Mastabqʷǝʿān, but a different text.
Incipit: ክ፡ ትመልአክ፡ ዘበ፡ ቃል፡ ነባበ፡ ወበመንፈስ፡ መንፈስ፡ ዘበወልድ፡ በአምላክ፡ አምላክ፡ ዘበዓለም፡ አሜን፡ ፍሥሓ፡ እስመ፡ ውእቱ፡ ዘኖሐ፡ ኀደፈ፡ ወአብርሃምሃ፡ መርሐ፡
Explicit: ወኵልነ፡ እንከ፡ በአተነ፡ ወፀአተነ፡ ውስተዝ፡ ቤት፡ በሰላም፡ ዕቀብ፡ በአሐቶ፡ ወልደከ፡ ዘቦቱ፡ ለከ፡ ምስሌሆ፡ ወምስለ፡ ቅዱስ፡ መንፈስ፡ ስብሐት፡ ወእኂዝ፡
I would suggest to create a new record, if it cannot be identified.
https://www.loc.gov/resource/amedmonastery.00279385780-ms/?sp=117&st=image

@DenisNosnitsin1970 @CarstenHoffmannMarburg

**Comment by DenisNosnitsin1970** [comment]
I do not know it eather.
