### ISSUE TITLE
record for Miracle of Ewostatewos No. 5 (Turaiev and BMLacq681)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2301]
The miracle of Ewostatewos numbered as 5 in Turaiev's edition has two parts. There are separate CAe IDs for each part:
https://betamasaheft.eu/works/LIT6354MEMiracle/main (5.1)
https://betamasaheft.eu/works/LIT6355MEMiracle/main (5.2)
as they are numbered separately in the EMML catalogue for EMML 1636 (there they appear as miracle 4 and miracle 5, respectively)
What is the best way to refer to them? Would it possibly make sense to create a new CAe entry for both parts together (so that we have Miracle 5 with two parts, for manuscripts which group them under one number? (eg BMLacq681)

@DenisNosnitsin1970 @thea-m

**Comment by DenisNosnitsin1970** [comment]
I think we can do that since both parts already exist and separate IDs and have been applied. It will necessary to interlink all three records.

**Comment by eu-genia** [comment]
I agree (we wrote the issue together ;) )

**Comment by eu-genia** [comment]
Massimo does not respond ) So I think we should simply go ahead and create the record.

I also notice that the record  LIT4315Miracles must be edited, as it assigns sub-IDs to some miracles and not the others while ignoring that separate records have been created.

It has

```
<div type="textpart" subtype="chapter" xml:id="RichMonk">
<label>On the rich monk and the locusts</t:label>
<:div>
<div type="textpart" subtype="chapter" xml:id="Abdabal">
<label>On ʾAbdabal the sinner</t:label>
</div>

etc etc


```

corresp should be added to the individual record

**Comment by eu-genia** [comment]
BTW we could also simply insert a div to have `LIT4315Miracles#Miracle5` to unite 5.1 and 5.2

**Comment by MassimoVilla** [comment]
Please excuse me, I have no regular connection in these days.
Here's my opinion. The two miracles appear as two distinct texts in at least two MSS: EMML 1636 and BGV009. So, I would be in favour of keeping two separate work records, one for each miracle, and creating a third record for those instances in which the two texts are merged, as suggested by Carsten and Eugenia.
We do not know whether the two parts _always_ go together. So, I would not delete LIT6355MEMiracle, which btw has been already used in BGV009.

**Comment by eu-genia** [comment]
I would then for now use LIT4315Miracles#Miracle5 (I have inserted chapters into the LIT4315Miracles record) and then, if we notice that the two parts frequently occur as one miracle we can always add a corresp to a new ID
