### ISSUE TITLE
Texts in MS BDLaethg43 (scroll)

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2302]
Here we have five "magic" texts found in the scroll MS BDLaethg43.
None of them seems to match with those in the BM database. A clear subdivision into textual units is also difficult because the red ink is almost completely faded out and sometimes it is not clear whether the lacuna contained an incipit or not (in these case I have opted for a new textual unit, unless it is very clear from the preceding line that the text should have continued in the following line).
Here we have the incipits:
1. There is no incipit because the upper part of the scroll is missing. The text (with some losses due to material damages at the borders) starts as follows: `<gap reason="lost"/>ተ፡ ጸዋጋን፡ ወሰ<gap reason="lost"/>ርያን፡ ወባርያ፡ <gap reason="lost"/>ማን፡ ወመናፍስት፡ 
                                ርኩሳ<gap reason="lost"/> ደሰክ፡ ወጉዳሊ፡ ዓይነ፡ ባርጨዛ፡ አልጉም፡ ሸርጋታ፡ ወ<gap reason="lost"/>በሽታ፡ ሸውታ፡ 
                                ሽውታ፡ ወትንትን፡ ወቃታ፡ ዘያጸልሙ፡ አ<gap reason="lost"/>ተ፡ ወይቀጠቅጡ፡ አእጽም<gap reason="lost"/>፡ ወይመጽኡ፡` and concludes as follows: `አመሐልኩከ፡ ወውጉዝኩከ፡ በ፭ ቅንዋት፡ መስቀሉ፡ ለእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ ዕቀባ፡ ወአድኅ<gap reason="lost"/> 
                                እምሕማመ፡ መጋኛ፡ ወ<gap reason="lost"/>ኛ፡ ለአመትከ፡ ወለተ፡ ማርያም` (Walatta Māryām is the owner)
2. The first five or six lines of this text were originally rubricated and now are completely illegible due to faded ink. I am not sure that this text is a new one, but since the preceding line concludes with a supplication and the owner's name, I would consider this as a new text. The first readable lines state: `ም፡ ዘየሐዩ፡ በታሕተ፡ ሰማ<gap reason="lost" unit="chars" quantity="1"/>፡ ዘእንበለ፡ ስሙ፡ ለእግዚእ<gap reason="lost" unit="chars" quantity="1"/>
                                ኢየሱስ፡ ክርስቶስ፡ ጋኔን፡ ዘ<gap reason="lost" unit="chars" quantity="1"/>ሬዒ፡ በዓይነ፡ ጠባይዕ፡ እሳታዊ፡ ተዓሠር፡ ይቤላከ፡ ቃለ፡ እግዚአብሔር፡ 
                                ዘአሠሮ፡ ልብርያል፡ በ፭፻፼ ሰናስለ፡ እሳት፡`. The text terminates as follows: `አቃንን፡ አብሮብርዮን፡ አቶታኤል፡ መትርማይ፡ በዝ፡ አስማት፡ አድኅና፡ እምሕማመ፡ ባርያ፡        ወሌጌዎን፡ ዘይጥህል፡ ወያሰለስል፡ ወያመነሞ፡ ወእምኵሎሙ፡ መናፍስት፡ እኩያን፡ ለአመትከ፡ ወለተ፡ ማርያም፡`
3. The incipit of the next text corresponds to LIT4704MagicPr, preserved in MS BAVet101 (ms_i3) but the explicit is different, so I would consider this a new text. Incipit: `በስመ፡ አብ፡ ወወልድ፡ ወምንፈስ፡ ቅዱስ፡ ፩ አምላክ። <gap reason="illegible" unit="chars" quantity="2"/>ቃሕ፡ ማዕሠረ፡ አጋንንት፡
                                አህያ፡ ሸራህያ፡ አልሻዳይ፡ ፀባኦት፡ ቢዛ፡ ባሃ፡ ጻሃ፡ ዱጳሃ፡ ረሃ፡ መልረጹዳንያ፡ ፎያ፡ አክሰሜና፡ ባባፊማርት፡ ወአመበሎ፡ ወማርት፡ አርግዕ፡ ጾማ፡ ለአመትከ፡ ወለተ፡
                                    ማርያም፡`. It concludes as follows: `ወይፃዕ፡ መንፈስ፡ ርኩስ፡ ዘአኃዘ፡ እደ፡ ሰብእ፡ ወተግባረ፡ ሰብእ፡ ይደምሰስ፡ ወዘርአ፡ ጸሎት፡ ከማሁ፡ አርግዕ፡ ውኅዘተ፡ ደማ፡ ወአቁም፡ ፍሬ፡ ማኅፀና፡ ለአመትከ፡ ወለተ፡ ማርያም፡
                                እስመ፡ አልቦ፡ ነገር፡ ዘይሰዓኖ፡ ለእግዚአብሔር።`
4. The next text starts as follows:   `በስመ፡ አብ፡ ወወልድ፡ ወምንፈስ፡ ቅዱስ፡ ፩ አምላክ። ስቅያኤልኤል፡ ስቅያኤልኤል፡ ስቅያኤልኤል፡ 
                                ስቅያኤልኤል፡ ስቅያኤልኤል፡ ስቅያኤልኤል፡ ስቅያኤልኤል፡ በ<gap reason="illegible" unit="chars" quantity="1"/></hi>ይለ፡ ዝንቱ፡ አስማቲከ፡
                                ዘአርዕከ፡ <gap reason="illegible" unit="chars" quantity="1"/>ይለ፡ በረድ፡  ወነፋስ፡ ከማሁ፡ አርግዕ፡ ደም፡ ትክቶሃ፡ ለአመትከ፡ ወለተ፡
                                    ማርያም፡` and terminates as follows:                            `ኦአምላከ፡ ቅዱስ፡ ፋኑኤል፡ ዕቀባ፡ ወአድኅና" እምሕማመ፡ መጋኛ፡ ወቁራኛ፡ <sic>ጻም፡</sic> ወሸተላይ፡ ዓይነ፡ ወርቅ፡ ወዓይነ፡ 
                                ጥላ፡ አይነት፡ ቡዳ፡ ወቁመኛ፡ ለአመትከ፡ ወለተ፡ ማርያም፡`
5. The last text begins as follows: `በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ በእንተ፡ ጽንስ፡ ወስደተ፡ አጋንንት፡ ገቢረከ፡ በእንተ፡ ጽንሰታ፡
                                ለማርያም፡ ዘብሩድስክኤል፡ ኢያርማናኤል፡ በዝንቲ፡ ማኅፀነ፡ ክትረት፡ በስመ፡ ሥሉስ፡ ቅዱስ፡ ሜልዮስ፡ መላልዮስ፡ ሊስ፡ 
                                አፍሊስ፡ በክሜሎስ፡ ዘአርጋዕከ፡ ኃይለ፡ በረድ፡ ወነፋስ፡ ከማሁ፡ አርግዕ፡ ደማ፡ ለእግዚአብሔር፡` and terminates as follows:                            `በዝንቱ፡ አስማት፡ ዘከተሮ፡ ለዲያብሎስ፡ ሳዶር፡ አላዶር፡ ዳናት፡ አዴራ፡ ሮዳስ፡ ሴቃ፡ ሌቃ፡ ጼቃ፡ በእሉ፡ አስማት፡ ዘከተሮ፡ 
                                ለሰይጣን፡ ከማሁ፡ ክትር፡ ደማ፡ ለአመትከ፡ ወለተ፡ ማርያም፡ ሰገዱ፡`

Please take your time, no hurry!

**Comment by thea-m** [comment]
Hi, I also found no work records corresponding to these. I think you can go ahead and create new ones.
