### ISSUE TITLE
Miracle vs passage from the Gadl - separate CAe ID?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2303]
BMLacq681 has, as miracle 15, the story of Ewostatewos and Warasina Egzi, which, according to Marrassini, is the same as translated by Conti Rossini from BAVet46 ff. 54-55 https://betamasaheft.eu/manuscripts/BAVet46/main, 
![image](https://user-images.githubusercontent.com/17987728/215766111-9a4c9915-54ea-4266-b84f-061c94604d80.png)
yet, in BAVet46 it is however not a miracle but a passage from the Vita itself. (In that MS the vita goes from 2 to 119, and only then 6 miracles follow.
![image](https://user-images.githubusercontent.com/17987728/215767188-bd0a317e-9927-4b29-a4a4-3efb65133389.png)

Is this passage also present in other texts of the Vita? Is it a miracle that was inserted in the Vita, or a passage of the Vita that is also used as a miracle?

Should a CAe record be created?

@DenisNosnitsin1970 @MassimoVilla @thea-m @abausi @CarstenHoffmannMarburg

**Comment by DenisNosnitsin1970** [comment]
I think it can get an ID, the passage seems to be a part of the Acts that was taken out and shaped as separate story.
