### ISSUE TITLE
Work record LIT2131OntheI for deletion

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2306]
I would suggest to delete this record, it is not used, it is one of those inherited from the index to EAe and never properly expanded:
https://betamasaheft.eu/works/LIT2131OntheI/main

@eu-genia @thea-m

**Comment by MarcinKrawczuk** [comment]
According to the EAe index it is the first homily in EMML 2375, I would prefer to use https://betamasaheft.eu/works/LIT6799RHintro/main instead. So yes, it is a doublet.

**Comment by eu-genia** [comment]
I will delete LIT2131OntheI.
Ideally of course we should all try to use/expand/correct the records already present (such as LIT2131OntheI) and avoid creating doublets (as far as I can see LIT6799RHintro has been recently created). (I know sometimes things are difficult to find so things can happen, but still the rule should be to try and use what is there). Thank you so much for paying attention!
