### ISSUE TITLE
New Person Maqaryos in additio in BMLacq679

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2310]
There is a person mentioned in a prayer in the manuscript BMLacq679.

ይትባረክ፡ አብ፡ ህገ፡ ዮሐንስ፡ ወይትባረክ፡ ወልድ፡ እንተ፡ ምኒልክ፡ አርስት፡ ተወልደ፡ መድህን፡ ይቀባእ፡ ቅብዐ፡ መንፈስ፡ ቅዱስ፡ ዘይት፤ ወለራብአዊ፡ <persName ref="PRS0000">መቃርዮስ፡</persName> ዘክበበ፡ ገጹ፡ መብረቅወ፡ ስርጋዊሁ፡ ነደ፡ ዕሳት፡ ደምሂ፡ ዘይውህዛ፡ (...)

I did not find a suitable Person in the search and the information on him is very limited. The short text may be written in the 19th or 20th centuries, but whether this date refers to the person in question is not sincere. Do we need a new Person ID?

**Comment by eu-genia** [comment]
@CarstenHoffmannMarburg please only open issues here https://github.com/BetaMasaheft/Documentation/ not under Persons Works or similar
Please also tag persons (like me or @DenisNosnitsin1970 or @thea-m ) if you want your question to be seen and responded to (Dorothea automatically receives notifications of all issues opened anywhere but we others do not, we must be asked, thank you!)

**Comment by thea-m** [comment]
It remains unclear to me. The formulation "ራብአዊ፡..." seems not common to refer to a person, and the text seems more mystical than concrete. There are several saints Macarius/Maqārəs, maybe they are intended here? But in any case, it's possible to create a record, just stating clearly the uncertainties.

**Comment by CarstenHoffmannMarburg** [comment]
It came to my mind, that ራብአዊ may refer to Maqārəs, because he is the fourth person mentioned to receive the blessing. A translation of this addition may be:
"Blessed be the father Həgga Yoḥannəs, and blessed be the son, who is Mənilək, inheritance (=heir?), Tawalda Madḫən, anointed with anointment of the Holy Spirit, and to the fourth Maqārəs, who has as rounded face a lightning of adornment, burnt the fire, the blood, which .."
If you agree, I will encode the four persons as possibly related to each other but neither as saints nor as kings or any other prominent figures.

**Comment by CarstenHoffmannMarburg** [comment]
I created four PRS ID in pull request #768 and updated the record in pull request #2202.
