### ISSUE TITLE
New work ID for biographical note on John Chrysostom as witnessed in BNFabb20

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2311]
BetaMasaheft/Manuscripts#2006 
ms_i3 in BNFabb20 contains a short biographical notice on John Chrysostome whose Epistle on the Hebrews is subject of the previous main work of this manuscript, that ist #LIT3171Commen. It is questionable, whether this short note should be counted as part of LIT3171Commen as suggested by Dorothea. I checked another account in #BLadd16197 and did not see this note. I suggest therefore to create a new work-ID for this small biographical note that is taken from the Tārika Walda ʾAmid, the Sənkəssār, Abušākər and the Chronicle of Yoḥannəs Madabbar, as is told in the incipit.
 
[ParisBNF/abb/BNFabb20.xml](https://github.com/BetaMasaheft/Manuscripts/pull/2006/files/37303957e329093e92733cdf644cc204c610d6d9#diff-f3d30de5802082615846309dadf7ebec26e8372b8301bc1831fa2516ecbcc4a0)

See https://betamasaheft.eu/manuscripts/BNFabb20/viewer on f. 126r to 127v

**Comment by eu-genia** [comment]
Dear @CarstenHoffmannMarburg please always open issues only in the https://github.com/BetaMasaheft/Documentation/issues/, not under Persons, Manuscripts, Works, etc., issues should all be in one place.
And please always tag the persons @eu-genia @thea-m @DenisNosnitsin1970 you want to respond, as otherwise we are not notified of your new issues.

**Comment by eu-genia** [comment]
It seems sensible (just note that it should become ms_i2, as what is now ms_i1 is an additio), 

maybe we can also ask @MershaMengistie to take a short look if he has time, he is a specialist on the Commentaries, maybe he would recognize the text and tell us if it often accompanies the Commentary on the Hebrews.

**Comment by eu-genia** [comment]
(if the biographical note frequently accompanies the Commentary we may need also an ID for the combination of the two texts)

**Comment by eu-genia** [comment]
![image](https://user-images.githubusercontent.com/17987728/219345975-c6b21ca8-86a6-4366-a65b-9d979d06b431.png)

**Comment by thea-m** [comment]
I think that this biographical note corresponds to LIT3171Commen#Vita, which is attested in several other manuscripts, e.g. BLorient737. Taking a maximalist approach, a new record could be created even though the biographical note is as fas as I know not yet known to us in an attestation independent from the commentary. But I don't really see a problem with the current encoding as textpart, which may or may not be present in any particular manuscript.

**Comment by eu-genia** [comment]
Thank you. In this case it should be nested inside of msItem i1 (LIT3171Commen) in BNFabb20, @CarstenHoffmannMarburg please can you edit? thank you.

**Comment by CarstenHoffmannMarburg** [comment]
I did the nesting, but oxygen did not accept a msItem_i1.1 without a title. For that reason I did it this way:
<msItem xml:id="ms_i1">
                            <locus from="3r" to="127v"/>
                        <msItem xml:id="ms_i1.1">
                            <locus from="3r" to="125v"/>
                            <title type="complete" ref="LIT3171Commen"/>
                       </msItem>
                        <msItem xml:id="ms_i1.2">
                            <locus from="126r" to="127v"/>
                            <title type="complete" ref="LIT3171Commen#Vita"/>
                        </msItem>
                        </msItem>
As far as I understand, the ID LIT3171Commen refers to the complete ms_i1 (including the vita). How can I form this properly?
Just for curiosity, I'd like to know how to find the links to the mentioned manuscript. When I looked up LIT3171Commen, I found no more wittnesses than [BnF Éthiopien 66Commentary on the Epistle to the Hebrews](https://betamasaheft.eu/BNFet66#ms_i1)ms_i1
    [BL Additional 16197Commentary on the Epistle to the Hebrews](https://betamasaheft.eu/BLadd16197#ms_i1)ms_i1
    [BnF Arabe 96, , contains an Arabic version of this work.](https://betamasaheft.eu/BnF%20Arabe%2096) (external)
    [BnF Arabe 95, , contains an Arabic version of this work.](https://betamasaheft.eu/BnF%20Arabe%2095) (external)
But no hint to BLorient737!

**Comment by MershaMengistie** [comment]
Dear Zhenia and Carsten: apologies for this late reply. I overlooked it and didn't know that you invited me for a comment. The text is not a commentary but an excerpt from the biography of John Chrysostom written by Giyorgis WA. It is in his book titled after his name.

**Comment by eu-genia** [comment]
Dear @CarstenHoffmannMarburg - 

when you look for witnesses do NOT look at the static list you are quoting, which are the occasional witnesses that were inserted by the editor of the work record itself.
you should look at the dynamic list in the box on the right where you see all occurrences in BM, always uptodate
It says, as of today "This unit, or parts of it, is contained in 12 manuscript records 73 times"

![image](https://user-images.githubusercontent.com/17987728/220303551-70a770c7-1f46-4563-9e02-d3059ce44d31.png)


Of course each msItem needs a title, and the title must be carefully selected

As I wrote in the PR

the structure is (if we follow what Dorothea @thea-m suggests)

msItem 1 LIT3171Commen 
  msItem 1.1 commentary 
  msItem 1.2 biography by Giyorgis Walda Amid LIT3171Commen#Vita


or alternatively, if this biography is a separate text which may appear in different contexts and not only as part of the LIT3171Commen, then

msItem 1 Full dossier containing the commentary and the biography (then we need a new CAe ID here)
 msItem 1.1. Commentary LIT3171Commen 
 msItem 1.2 Biography by Giyorgis (then we need a new CAe ID here too, and edit other records referring to LIT3171Commen#Vita)

but for now we are staying with option 1

**Comment by CarstenHoffmannMarburg** [comment]
I did it in the way Dorothea suggested and Eugenia explained.
