### ISSUE TITLE
Ethiopian manuscriopt in Arquivo Nacional Torre do Tombo

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2313]
We can add link to a digital duplicat of Ethiopian scroll preserved in Arquivo Nacional Torre do Tombo, Portugal (seems to have no signature except "Manuscrito em copta",
https://digitarq.arquivos.pt/viewer?id=4645183.

**Comment by eu-genia** [comment]
I like their dating [15--?]-[17--?]
