### ISSUE TITLE
Do we need a new ID for a prayer to Jesus?

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2317]
@eu-genia @DenisNosnitsin1970 @thea-m 

In the manuscript BMLacq306, there is a short prayer on f. 93r, that I have recorded as p7_i1:

The text of the former is:
ሕዝበከ፡ ወባርከነ፡ ርስተከ፡ ሀበነ፡ ኃይለ፡ ወመዊአ፡ ለአግብርቲከ፡ ለእለ፡ ንጼውዕ፡ ስመከ፡ ስቀበነ፡ ውሉደ፡ 
ሕዝብከ፡ ወሕጽረነ፡ በኃይለ፡ መላእክቲከ፡ ወትረ፡ በኵሉ፡ ጊዜ፡ ወበኵሉ፡ ሰዓት። በኃይለ፡ መስቀልከ፡ ርድአነ፡ በዕፀ፡ ቤዝወነ። ሰረይ፡ ኃጢአተ፡
ሕዝብከ፡ ወመሐር፡ ተግባርከ፡ እግዚኦ፡ ኢታጥፍአነ፡ ሐሰ። በእንተ፡ አብርሃም፡ ፍቁርከ፡ ወበእንተ፡ ይስሐቅ፡ ቍልዔከ፡ ወበእንተ። እስራኤል፡
ቅዱስከ፡ ተዘክር፡ እግዚኦ፡ ኪዳነከ። ፍጡነ፡ ፈኑ፡ ሳህለከ፡ መሐር፡ ኪያነ፡ ኪያነ፡ ዘፈጠርከ። በእንተ፡ ወላዲትከ፡ ወበእንተ፡ ዮሐንስ፡ ዘረፈቀ፡ ውስተ፡ 
ሕፅንከ፡ ወበእንተ፡ ኵሎሙ፡ ቅዱሳኒከ፡ ሕፅረነ፡ ወትረ፡ በኃይለ፡ መስቀልከ፡ ኢታስተኃፍረነ፡ እምተስፋነ። እግዝእትነ፡ ነጽሪ፡ ኀቤነ፡ ጸልዪ፡ ለነ፡
ለደቂቅኪ፡ ወአድኅንነ፡ እምኵሉ፡ ምንዳቤ፡ ወኀዘን።
Marrassini (bm:Marrassini1986Laurenziana, p. 108) has indicated that piece as "prayer to Jesus" although Jesus Christ not mentioned in the text.  I found a similar text in BAVet90 on f. 6r.

I was not able to find and ID for this prayer. Have I overlooked something or do we need a new ID?

**Comment by thea-m** [comment]
It seems to correspond largely to https://betamasaheft.eu/works/LIT6562Prayer/text (ending a bit before the version attested in BDLaethg34)
