### ISSUE TITLE
Two IDs for Maṣḥafa Gənzat

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2321]
@DenisNosnitsin1970 @thea-m @eu-genia 

While working on an manuscript containing a Maṣḥafa Gənzat, I came across two different IDs: LIT1931Mashaf and LIT6155MashafaGenzat. Do these two represent two different versions or recensions of the Maṣḥafa Gənzat and is it justified to have to work IDs?

**Comment by DenisNosnitsin1970** [comment]
Yes, I want to remove it and I assume I did, it is not on my computer any longer, and the notion of 6155 is revomed from MY013. Did smth go wrong? 
![grafik](https://user-images.githubusercontent.com/18533839/223998635-7944dac3-fc53-4849-88ae-f3f3b8fe74b4.png)

**Comment by eu-genia** [comment]
Indeed, the syncing probably did not go through, will remove manually then
