### ISSUE TITLE
Work record for Canonical Responses by Timothy Ailouros (CPG 2520)

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2323]
I cannot seem to find a work record for the Canonical Responses by Timothy Ailouros [published by Bausi](https://brill.com/view/journals/scri/2/1/article-p41_4.xml?language=en). I will create one unless somebody finds it. 
@thea-m @eu-genia @CarstenHoffmannMarburg

**Comment by eu-genia** [comment]
you surely have found them ) LIT2693CanR
