### ISSUE TITLE
Texts in MS f.33 (Maṣḥafa gǝnzat)

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2324]
Dear all,
MS f.33 is a Maṣḥafa gǝnzat which does not contain numerous sections usually transmitted in other copies of the same work, while - on the other hand - it contains several texts not recorded in BM (or transcribed but without ID).
Rather than creating new work records, I am inclined to update LIT1931Mashaf (= Maṣḥafa gǝnzat) with new textparts, because at this stage I cannot tell whether these unrecorded textual units are also found independently.  What do you think?
These are the textparts I would add to LIT1931Mashaf:

```
1. <div type="textpart" xml:id="Exhortation">
<label>Exhortations to be read for all dead before the burial</label>
</div>
(incipit: በስመ፡ አብ፡ [...] ተግሣጽ፡ ዘይትነበብ፡ ላዕለ፡ ኵሎሙ፡ ምዉታን፡ በጊዜ፡ ግንዘት፡ ላዕሌሆሙ፡ ስብሐት፡ ለእግዚአብሔር፡ ፈጣሪ፡ ወመንሥኢ፡ ኃያል፡ መሐሪ፡ ዘውእቱ፡ ዘውስተ፡ እዴሁ፡ ሥልጣነ፡ ሞት፡ ወሕይወት፡  ወትፍሥሕት፡ ወገሀናም። ዘይብል፡ ኀበ፡ ተጋብኡ፡ አው፡ በስምየ፡ እሄሉ፡ አነ፡ ውስተ፡ ማእከሎሙ፡ ወኵሎ፡ ዘሰአልክምዎ፡ በስምየ፡ በእንቲአሁ፡ 
እገብር፡ ለክሙ፡)

2. <div type="textpart" xml:id="Order">
<label>Order to be read for the dead after the burial</label>
</div>
(incipit: ሥርዓት፡ ዘይትነበብ፡ ላዕለ፡ ምዉታን፡ እምድኅረ፡ ህንዘት፡ ስብሐት፡ ለእግዚአብሔር፡ ስፉሐ፡ ሀብት፡ ውዱስ፡ አምላክ፡ በእንተ፡ ጸጋቲሁ፡ ዘአስማቲሁ። ስን፡ ዘአዘዘ፡ ወፈትሐ፡ ወፈጠረ፡ ወአስተዳለወ፡ ወሥሉሠ፡ በህላዌሁ፡ ማኅየዊት፡ ብሑት፡ ርእሱ፡ ባሕራዊት፡ ዘአጸገወ፡ ኵሎ፡ ዓለመ፡ በእንተ፡ አምልኮቱ፡ ወአገበሮሙ፡ በእንተ፡ ስብሐቱ፡ ወረሰዮሙ፡ ታቦተ፡ መንፈሳዊት፡)

3. <div type="textpart" xml:id="Penance3">
<label>Other prayer of penance</label>
</div>
(incipit: በስመ፡ አብ፡ [...] ጸሎተ፡ ንስሐ፡ ካልእ፡ እግዚእ፡ እግዚአብሔር፡ አኃዜ፡ ዓለም፡ ብሑተ፡ ሥልጣን፡ ወስም፡ ቀዳማዊ፡ ዘእንበለ፡ ጥንት፡ ወዳኅራዊ፡ ዘእንበለ፡ ፍጽም፡ ዘትነብር፡ ውስተ፡ አርያም፡ መንበረ፡ ስብሐቲከ፡ ዘኢይተረጐም፡ ዘልብሰትከ፡ አፍሐም፡)

4. <div type="textpart" xml:id="Penance2">
<label>Prayer of penance</label>
</div>
(incipit: ጸሎተ፡ ንስሐ፡ እግዚአ፡ አኃዜ፡ ኵሉ፡ ዓለም፡ አንተ፡ ውእቱ፡ ዘትፌውስ፡ ቍስለ፡ ነፍስነ፡ ወሥጋነ፡ ወመንፈስነ፡ እስመ፡ አንተ፡ ውእቱ፡ ዘትቤ፡ በአፈ፡ ወልድከ፡ ዋሕድ፡ እግዚእነ፡ ወአምላክነ፡ ወመድኃኒነ፡ ኢየሱስ፡ ክርስቶስ፡ ዘይቤሎ፡ ለአቡነ፡ ጴጥሮስ፡ አንተ፡ ኰኵሕ፡ ወዲበ፡ ዛቲ፡ ኵኵሕ፡ አሐንጻ፡ ለቤተ፡ ክርስቲያን፡)
Here I wouls use "Penance2" because "Penance" is an already existing textpart with a different incipit

5. <div type="textpart" xml:id="Commemoration">
<label>Commemoration of the dead with incense and offering</label>
</div>
(incipit: ንግበር፡ ተዝካሮሙ፡ ለሙታን። በዕጣን፡ ወበቍርባን፡ እስመ፡ ይበቍዖሙ፡ ወይከውን፡ ዕረፍተ፡ ለነፍሳቲሆሙ። በከመ፡ ትቤሎ፡ እግዝእትነ፡ ማርያም፡ ለብፁዕ፡ ጴጥሮስ፡ ሊቀ፡ ሐዋርያት፡ ወሶበ፡ ተስእለቶ። እንዘ፡ ይብላ፡ መሥዋዕተ፡ ወቍርባን፡ ዘይትገበር፡ በቤተ፡ ክርስቲያን፡ ምንተ፡ ይበቍዖሙ፡ ለሙታን፡ ወአውሥአት፡ ወትቤሎ፡ እምጼና፡ ገነት።)

6. <div type="textpart" xml:id="PrayerBlessing">
<label>Prayer of blessing 'O holy Trinity, Father, Son and Holy Spirit, one God, bless your people'</label>
</div>
(incipit: ጸሎተ፡ ቡራኬ። ኦሥሉስ፡ ቅዱስ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ። አብርክ፡ ዲበ፡ ሕዝብከ፡ ፍቁራን፡ ክርስቶሳዊያን፡ በበረከት፡ መንፈሳዊት፡ ወፈኑ፡ ላዕሌነ፡ ጸጋ፡ መንፈስ፡ ቅዱስ። ወረሲ፡ ኃዋኅወ፡ ቤተ፡ ክርስቲያንከ፡ ቅድስት፡ ርኅወ፡ ለነ፡ በአሚን፡ ወበምሕረት።)

```
Also, the MS contains two consecutive versions (with some variants) of the first Blessing of ʾAbbā Sāmuʾel (= LIT1931Mashaf#FirstBlessing). Here the two incipits:
f. 58ra-b: በስመ፡ [...] ቡራኬ፡ ዘአቡነ፡ አባ፡ ሳሙኤል፡ ዘአዕረፈ፡ ይምሐሮ፡ እግዚአብሔር፡ አሜን። ይሠሃሎ፡ እግዚአብሔር፡ በብሩህ፡ ገጽ፡ ይትቀበሎ፡ በቃለ፡ ፍሥሐ፡ ወኀሤት፡ ያሰምዖ፡ እግዚአብሔር፡ በጸሎታ፡ ለእግዝእትነ፡ ማርያም፡ ይምሐሮ፡ እግዚአብሔር፡ ማኅፀንትየ። ወምዕቅብናየ፡ ውእቱ፡ ነዳይ፡ ዘዓቀበኒ፡ <sic>ዘንዘ፡</sic>
f. 63rb-va: ቡራኬ፡ ዘአቡነ፡ አባ፡ ሳሙኤል። በስመ፡ አብ፡ ወወልድ፡ ወ</hi>መንፈስ፡ ቅዱስ፡ ፩፡ አምላክ፡ ለዘ፡ አዕረፈ፡ ይምሐሮ፡ እግዚአብሔር፡ አሜን። በብሩህ፡ ገጽ፡ ይትቀበሎ፡ እግዚአብሔር፡ አሜን። ቃለ፡ ፍሥሐ፡ ያሰምዖ፡ እግዚአብሔር፡ አሜን። በጸሎታ፡ ለእግዝእትነ፡ ማርያም፡ ይምሐሮ፡ እግዚአብሔር፡ አሜን። ማኅፀንትየ፡ ወምዕቅብናየ፡ ውእቱ፡ ነዳይ፡ ዘአዕቀበኒ፡ ዘንተ፡ ብሂል፡ ውስተ፡ ሕይወት፡
Do you suggest to add another textpart to the second version, or simply assign the same ID to both parts and explain in a note that they diverge for some textual variants?

**Comment by thea-m** [comment]
I agree regarding the suggestion to encode these textparts in the work record, I think that is a reasonable approach and will contribute to identification in other manuscripts in the future.
Regarding the second question, if you skimmed the entire text and found that the differences throughout are restricted to variants as in the incipit, I would assign the same ID and include a note in the manuscript (or possibly also in the work record).
In 2: እምድኅረ፡ ህንዘት፡ ስብሐት: ግ :)

**Comment by MassimoVilla** [comment]
Great, thank you Thea, and thanks for spotting the typo
