### ISSUE TITLE
New ID for LIT Prayer to the Virgin in BMLacq720

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2330]
@DenisNosnitsin1970 @eu-genia @thea-m 

I could not identify a text, that is entitled "Prayer to the Virgin in manuscript BMLacq720 (msItem 4). It contains a lot of ethnic names, but in this combination it is not familiar to me and can not be found in betamaṣāḥəft (simple) search. Do we need a new ID for it?

                            <title>Prayer of the Virgin</title>

Incipit (f. 44vb):                            <incipit xml:lang="gez">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ለ፩አምላክ፡ ዛቲ፡ ጸሎት፡ ዘእግዝእትነ፤ ቅድስት፡ ድንግል፡ ማርያም፡ ንጽሕት፡ ወላዲተ፡ አምላክ። 
                                ጸሎታ፡ ወበረከታ፡ የሀሉ፡ ምስለ፡ ገብራ። <persName role="owner" ref="PRS13994KidanaMaryam">ኪዳነ፡ ማርያም።</persName> ለዓለመ፡ ዓለም፡ አሜን። ወእመሂ፡ ተንባላታዊሆን። 
                                ወእመሂ፡ ከለዳዊያን፤ አይሁድ። ወዮናናዊያን፡ ወሳምራዊያን። ወግብፃውያን፡ ወኖናፌ፡ ወኵሉ፤ ክርስቲያን። ወለኵሎሙ፡ ሰብእ፡ እኩያን። ዘርዝር፡ ምክሮሙ። </incipit>
                            
Explicit (f. 52vb) <explicit xml:lang="gez">ዝውእቱ፡ ኢየሱስ፡ ክርስቶስ፡ ወኵሎ፡ ሠራዊቶ፡ እሉ፤ እሙንቱ፡ ዘሰመይክዎሙ፡ ከመ፡ ትፈኑ፤ ሊተ፡ ተኢያኮስ፡ ቅድስት፡ ማርያም፡ ድንግል። 
                                ከመ፡ ትዕተብ፡ ወትባርክ፡ ዘንተ፤ ማየ፤ ወዘንተ፡ ዘይተ። በዛቲ፡ ሰዓት። ወቅብዖ፡ ወአጥምቆ፡ ለገብብርከ፡ <persName role="owner" ref="PRS13994KidanaMaryam">ኪዳነ፡ ማርያም።</persName>
                                ወይኩን፡ ሎቱ፡ ፍሥሐ፡ ወሐሤት፡ ወፈውስ፡ መድኃኒት። እምኀበ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ይእዜኒ፤ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም፡ አሜን። ወአሜን፡ ለይኩን፤ ለይኩን፤ 
                                ሊተ፡ ለገብርከ፡ <persName role="owner" ref="PRS13994KidanaMaryam">ኪዳነ፡ ማርያም።</persName>። </explicit>
                        </msItem>

**Comment by DenisNosnitsin1970** [comment]
Not known to me. Is the reading  ለገብብርከ፡ correct?

**Comment by CarstenHoffmannMarburg** [comment]
I remember, that I copied the text, as it was in the manuscript. I want to checked the spelling ለገብብርከ፡ in f. 52v right now, but the scan folios do not open to me. I don't know, whether this is due to my internet connection, that turns out being to weak or due to an error on the website. I will try again later. I think, it is a mistake for ለገብርከ፡, that happened to occur because of the end of the line. I don't know, how to encode obvious mistakes in a proper way and where to find it in the guidelines.

**Comment by DenisNosnitsin1970** [comment]
This might be the site problem, Zhenia will know how to fix it. Possibilities for encoding mistakes are basically here: 
`https://betamasaheft.eu/Guidelines/?q=supplied&id=text-encoding`
I personally avoid correcting mistakes (except one category of omissions), ለገብብርከ፡ I would encode like as <sic resp="DN">ለገብብርከ፡</sic>

**Comment by DenisNosnitsin1970** [comment]
`<sic resp="DN">ለገብብርከ፡</sic>`

**Comment by CarstenHoffmannMarburg** [comment]
Thanks! I also found "<surplus>" for superfluous letters.

**Comment by eu-genia** [comment]
Has record been created? Please link if yes and close the issue.
