### ISSUE TITLE
Duplicate?  CAe 6687 = CAe 6744

### ISSUE THREAD

**Issue by AaronButts** [BetaMasaheft/Documentation#2338]
CAe 6687 and CAe 6744 seem to refer to the same text. The titles are very similar "Homily by Ephrem for Maundy Thursday", and more to the point, the same manuscript, EMML 1763, ff. 184v-187r, is cited in both. 

This is my first "issue", so I may well be missing something obvious. If I am, my apologies in advance!

Many thanks to Dorothea for showing me how to create an "issue". I hope to have a steady stream of them!

**Comment by thea-m** [comment]
Thank you! I skimmed the beginning and end of the homily in BLorient8192 and EMML1763, which are linked in the two records, and it seems indeed to be the same text. If @MarcinKrawczuk, who worked on them, has no objections I will merge the records and delete one of them. Has anyone used any of the two IDs already in a publication or has some other preference for which one to keep?

**Comment by AaronButts** [comment]
Thank you, Dorothea!

I am not aware of anyone having used either ID already in a publication, so I have no preference. 

But, please let me know what is decided because I would like to use the Clavis ID in an upcoming publication.

**Comment by MarcinKrawczuk** [comment]
Sorry about that, there were so many records to create for EMML 1763 / BL Orient 8192... One of them has to go of course, I agree.
