### ISSUE TITLE
PRS-ID for ደማቲዎስ፡ (Timotheus Ailouros?)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2341]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found a person with the name ደማቲዎስ፡, Patriarch from Alexandria in BMLacq776. There are many patriarchs with this name known, but this one may be Timotheus Ailouros, who is venerated here in a Homily to Michael for the month Ḫədār. How can I clarify this assumption? As far, as I can see, there is no PRS-ID for any of the Timotheus, although Timotheus Ailouros is probably already attested in a manuscript (ESum039), two works (LIT1047Aksumi, LIT2372Syllog) and a study (STU0002Historia). 

Is it useful to create an ID for Timotheus Ailouros and add it to the record? 

The witness in BMLacq776 is as follows:
<incipit xml:lang="gez"><hi rend="rubric">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ።</hi> ድርሳን፡ ወነገር፡ ዘቅዱስ፡ አበ፡ 
                                            <persName ref="PRS0000">ደማቲዎስ፡</persName> ሊቀ፡ ጳጳሳት፡ ዘለእስክንድርያ፡ ትነበብ፡ በበዓለ፡ ቅዱሰ፡ <hi rend="rubric">ሚካኤል፡ ሊቀ፡ መላእክት፡</hi> አመ፡ ፲ወ፪ለህዳር፡ 
                                            <hi rend="rubric">ኣ</hi>ርፋ<hi rend="rubric">ታኤል፡</hi> አዘ<hi rend="rubric">ፋታኢ</hi>ል፡ 
                                            <hi rend="rubric">ሕዝት</hi>ናኤ<hi rend="rubric">ል፡ ምርሜ</hi>ል፡ <hi rend="rubric">ስመ፡ አምላክ፡</hi> 
                                            ኢየሱስ፡ ክርስቶስ፡ ቃል፡ ቀዳማዊ፡ ወልደ፡ እ<hi rend="ligature">ግዚ</hi>አብሔር፡ ሕያው፡ ወወልደ፡ <hi rend="rubric">ማርያም፡ ሥግው፡</hi>
                                            ያርኅቅ፡ እምኒነ፡ ኃይለ፡ ሳይግናት፡ ገሙናነ፡ መንፈስ፡ ወያድክም፡ ሀ<pb n="1v"/>ይሎሙ፡ ለመናፍስት፡ ርኩሳን፡ ወያርእየነ፡ 
                                            እ<hi rend="ligature">ግዚ</hi>አብሔር፡ ክብረ፡ ዓቢየ፡ ዘወሀቦ፡ ለቅዱስ፡ <hi rend="rubric">ሚካኤል፡ እምኩሎሙ፡ ቅዱሳን፡</hi> 
                                            መላእክተ፡ በረክተ፡ ረድኤቱ፡ የሀሉ፡ ምስለ፡ ገብሩ፡ <gap reason="omitted"/> ለዓ፡ ዓሜን፡ </incipit>

**Comment by eu-genia** [comment]
Have you tried searching for Timothy and/or Ṭimotewos?
We have PRS9523Timothy for Ailouros and many other Timothies

**Comment by eu-genia** [comment]
Just a minor side note: since the original set of records was created from the index of the Encyclopaedia Aethiopica you can be quite sure that any person/place/work treated in the Encyclopaedia already has a BM ID, at least as a stub.

Note also that LIT1047Aksumi has no author, it is a collection of many many texts. among them indeed there is LIT2372Syllog, which, if you open it, already points to Timothy (with ID) as its author.

**Comment by eu-genia** [comment]
Check also LIT1637Homily

**Comment by CarstenHoffmannMarburg** [comment]
I did look up only for Timotheus. I should watch out for English names better in future.

**Comment by thea-m** [comment]
Searching for Timo* in the simple or advanced search works well and will bring up any timotheus/thy/tewos :)
