### ISSUE TITLE
Does anybody know ንሄድራንስ፡ አድርያስ፡ አብርያስ፡

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2344]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found names in the incipit of a Homily to Mikāʾel for the 12th of Miyāzyā (LIT3962Homily) in BMLacq776. I can estimate from the context and from the form, that these are personal names, but I cannot grasp, whether these are owner, angels or saints from antiquity. The incipit on f. 55ra-b is as follows:

<incipit xml:lang="gez"><hi rend="rubric">በስመአብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱ</hi> ፩አምላክ፡ ድርሳን፡ ዘቅዱስ፡ <hi rend="rubric">ሚካአል፡</hi> 
                                        ሊቀ፡ መላእክት፡ ዘይትነበብ፡ አመ፡ ፲ወ<add place="below">፪</add>ሰንዪ፡ <add place="above">አ</add>ወርኃ፡ ሚዝያ፡ 
                                        ትኅብልናሁ፡ ያሀሉ፡ ምስለ፡ ገብሩ፡ ዘለዓለመ፡ ዓለ፡ <persName ref="PRS0000">ንሄድራንስ፡ አድርያስ፡ አብርያስ፡</persName> መፍትው፡ እንከ፡ አሐውየ፡ 
                                        ከመ፡ ንዘከር፡ እበዩ፡ ዘአብ፡ ወኂሩት፡ ዘወልድ፡ ወክብረ፡ ዘመንፈስ፡ ቅዱስ፡ ኢስመ፡ በህብረተ፡ ሥላሴ፡ ተትበፈ፡ ዓለም፡ ስማይ፡ ወምድር፡ እስመ፡ ይቤ፡ መድኃኒነ፡ በከመ፡ በሰማይ፡ 
                                        ከማ<pb n="55va"/>ሁ፡ በምድር፡ ንቀደም፡ እንከ፡ ጠይቁ፡ ዘበሰማይ፡ ንለቡ፡ እንከ፡ ዘበ፡ ምድር፡ እሰሚ፡ ቀዳሚ፡ ገብረ፡ 
                                        እ<hi rend="ligature">ግዚ</hi>አብሔር፡ ሰማየ፡ ወምድረ፡ ወኩሉ፡ ፍጥረት፡ ዘዚአሁ፡ </incipit>

The folio is a little bit blurred and some letters may be misinterpreted by myself. It would be useful, if you might have a look by yourselves on that page. Unfortunately, I have not found out yet, how to integrate the scan page into a github-Issue. The sequence is in BMLacq776 on f. 55ra. The names may also be distorted and may be different originally (probably Greek: Ανδρώνης, Ανδρέας, ...). 

Shall I treat them as group of people or as one person and give a PRS-ID respectively? 
It appears to me even possible, that ዘለዓለመ፡ ዓለ(ም)፡ is also part of a name, but it would be rather long.

Marrassini described the Homily: "sulle missioni degli angeli e sull'annunciazione alla Vergine", what points rather to an identification with angels associated with Mikāʾel.

**Comment by DenisNosnitsin1970** [comment]
It is difficult to understand what it is. I had a look in the church edition of Dersana Mikael and in a couple of mss, but these names are not there. I assume this passage might be a mistake (text transposition?), hardly they are propose personal names (also they are placed outside the formula). The names look like 'asmat anyway, maybe it is an abortive attempt to insert some; and some of the Dersane Mika'el's mss have several asmat strings included in the readings for some months (see e.g. ESmy012, under "Rubrication").

**Comment by CarstenHoffmannMarburg** [comment]
OK. I will leave it like this in the text without any mark-up.
