### ISSUE TITLE
Eudoxia, wife of Arcadius and Theodosius, father of Arcadius in BMLacq776 (Homily to Mikāʾel)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2346]
@thea-m @DenisNosnitsin1970 @eu-genia 

I found አውዶክስያ, ብእሲቱ፡ አርቃዴዎስ፡ in a Homily to Mikāʾel for the 12th of Gənbot. I identified አርቃዴዎስ፡ to be (byzantine) emperor PRS2016Arcadius and I think, it might be relevant enough to signify his wife and his father and predessessor with own IDs as well. What do you think?

The text is as follows (in BMLacq776, f. 65ra):
ወኮነ፡ በመዋ</hi>ዕሊሁ፡ ለ<persName ref="PRS2016Arcadius">አርቃዲዎስ፡ </persName>ወልደ፡ ለቴዎደስዮስ፡ 
                                        ንጉሥ፡ ርቱዓ፡ ሃይማኖት፡ ዘሀገረ፡ <placeName ref="LOC2196Consta">ቍስጥንጥያ፡ ወዘአጶሊ፡ </placeName>ወበ፡ እብሬቱ፡ ለዮሐንስ፡ ጳጳስ፡ 
                                        ዘውእቱ፡ <persName ref="PRS5720JohnChr">አፈወርቅ፡</persName> ወሃለወት፡ ብእሲቱ፡
                                        ለ<persName ref="PRS2016Arcadius">አርቃዴዎስ፡</persName> ዘስማ፡ አውዶክስያ፡ መፍቀሪተ፡ ንዋይ፡ ወሶበ፡ ርእያ፡ ዮሐንስ፡ ከመ፡ ታፈቅር፡ 
                                        ንዋየ፡ ይምዕዳ፡ ወይጊስፃ፡

**Comment by eu-genia** [comment]
We have PRS3899Eudoxia for the wife and PRS9479Theodosi for the father

**Comment by eu-genia** [comment]
(sure the records can be completed with some data, at least wd:Q232981 for PRS3899Eudoxia wd:Q46696 for PRS9479Theodosi and wd:Q159369 for Arcadius)

**Comment by CarstenHoffmannMarburg** [comment]
Thanks! I took the PRS-IDs for the record of BMLacq776. I will try to add the information to the three PRS-records as you suggested in a minute.

**Comment by CarstenHoffmannMarburg** [comment]
Done. I also added names and relations to the three records.
