### ISSUE TITLE
ʾAstarāniqos and ʾAfomyā

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2347]
@eu-genia @DenisNosnitsin1970 @thea-m 
In a homily for the 12th of Sane in a homiliary to Mikāʾel the names ʾAstarāniqos</persName> and ʾAfomyā of Cilicia. The two are attested in this Homily in several manuscripts:
BMLacq776, f. 68vb
ESmy012
BAVet82
EMIP00016
I did not find PRS-IDs for them yet. May I create IDs for these two?

**Comment by eu-genia** [comment]
don't think we have them (NB I guess a part of the text is translated into English here https://hamernoah.wordpress.com/2020/06/19/where-is-your-rod-that-have-a-sign-of-the-cross/ maybe can be added to the work)
