### ISSUE TITLE
Talāson in various homilies and miracles to Mikāʾel

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2349]
@thea-m @eu-genia @DenisNosnitsin1970 

There is a miracle about a child of a poor man, that was cast into the sea by an evil man. That child was rescued by St. Mikāʾel and raised by a peasant, who named it Talāson. The story appears in little variation in homiliaries to Mikāʾel as in: BMLacq776, BAVet82 in the following parts: 
LIT3959Homily (as far as I know without mentioning the name Talāson but with reference to PRS11321Talafinos)
LIT4155MiraclesMichael (with the name Talāson)
LIT1295Dersan#CommemorativeSane (as far as I know without mentioning the name Talāson)
LIT1295Dersan#HomilyHamle

I want to create an ID for Talāson and encode this name in the record. Do you agree?

**Comment by thea-m** [comment]
If PRS11321Talafinos refers to the same person in the same narration, I would update the existing record with the other name variant. If they are different persons, it's fine to create a new record (depending of course on how much time you want to spend on the records of protagonists). If it is broadly the same narration in all instances, it might make sense to create a narrative unit or general record to connect the work records.

**Comment by CarstenHoffmannMarburg** [comment]
It is not clear to me, whether Talafinos and Talāson are esentially the same. The stories appear to be very similar and Marrassini described the texts to be similar, but not the same:

"e sul bambino TaIafinos ritrovato in mare" 

"Narra di un bambino gettato in mare in un sacco dal ricco malvagio «come Faraone» di cui si fa cenno nell'incipit, poi salvato da S. Michele e trovato da un pastore, che gli mette nome Talāson"

"molto simile a quelle di Talafinos e Talason (cf. nn. 3a, 5a, 9b); qui il bambino è chiamato così dal pastore baʾənta zarakabo wəsta bāḥr"

"Omelia, di Yoḥannes vescovo d'Etiopia in Axum, su TaIason (watalāson behil 'əmmāy zarakabawo, f. 88r), molto simile, anche se non uguale, a quelle dei nn. 3a. 5a, 8b."

**Comment by eu-genia** [comment]
we normally only assign IDs to persons involved in manuscript production when producing manuscript descriptions,
(we do create prs IDs dor the main protagonists of works when we create work records, e.g. saints venerated by a gadl or similar)

**Comment by eu-genia** [comment]
in this case i would collect all name variants in one record

**Comment by DenisNosnitsin1970** [comment]
I know about the saints etc., Talason is not one of them.

**Comment by CarstenHoffmannMarburg** [comment]
I didn't think about the need for a timely closure of an issue. I will try to take on this task in the future!
