### ISSUE TITLE
Doublet LIT1663Homily LIT1183Baenta

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2351]
https://betamasaheft.eu/works/LIT1663Homily/main and https://betamasaheft.eu/works/LIT1183Baenta/main (both created from the EAe index and never used) seem to refer to the same homily attested in Hāymānota ʾabaw (EAe III, 263a).
I suggest to delete one of them. Any preference which ID should be kept?
@AaronButts

**Comment by AaronButts** [comment]
Thanks! Personally I prefer LIT1183: For me at least, 'salvatory passion' does not work in English, at all. I didn't understand what it meant until I read the Ethiopic! So I would keep the Ethiopic one, i.e., LIT1183. 

I just note that there is a complication here: According to my notes, there are actually two excerpts from one Syriac Homily (via Arabic) in question here, but I don't have in my notes how exactly the text(s) appear(s) in the Ethiopic manuscripts, i.e., whether as a single work or as two works. Does that make sense? In other words, I am not 100% certain that we should have one work file or two work files, but perhaps at the moment it is best to keep it as a single work in Ethiopic. What do you think?

**Comment by thea-m** [comment]
Thank you! As far as I understand the situation:
- The records were automatically created from the EAe index.
- Their attestation there refers uniquely to this item in the Jacob of Sarug article: 
![image](https://user-images.githubusercontent.com/19650382/236833871-2ee71903-1146-4e7d-88e2-c56667dafe8a.png)
- From there, I understand that there are two quotations from this homily in the Hāymānota ʾabaw, which (according to the article) constitute the only attestation of this homily in Ethiopian literature.
- As such they already have a "sub-ID" within the Hāymānota ʾabaw record (let me know if you need some explanation on this!): LIT1586Hayman#JacobSarug3 and LIT1586Hayman#JacobSarug4

Originally, we had decided to give CAe numbers only to textual units that circulate independently in the Ethiopian tradition, so as not to reflect a mostly Eurocentric categorisation of textual units. Later, it was decided that this approach needs some tweaking to be practical, because it is often very useful to have a CAe reference to refer to IDs to works that, though they do not circulate independently in Ethiopia, do so in other cultures.
(See also here, with mention of the Hāymānota ʾabaw https://github.com/BetaMasaheft/Documentation/issues/2326 - to confuse matters further, there used to be the ID LIT3447Jacobo to refer collectively to all quotations attributed to Jacob in the Hāymānota ʾabaw, but it has been deleted as these quotations do not circulate independently outside of the Hāymānot ʾabaw)

Concretely, I would say that 
- if we know that such a homily by Jacob really existed, having one single CAe entry is reasonable. This can be linked to in the Hāymānota ʾabaw record. I would go ahead and delete LIT1663Homily. 
- If is known that such a homily did not exist, or it is uncertain, the question is more conceptual and I think the BeInf project could develop a guideline for such cases (which presumably happen more than once?): Do we keep/create CAe entries for hypothetical textual units?

What do you think? Regarding mainly the existence or not of this particular homily, but also the proposed strategy.

**Comment by AaronButts** [comment]
Thanks for this, Dorothea! It is very helpful and interesting. 

I can say with some confidence that this particular homily exists in Ethiopic only in these two quotations in the Hāymānota ʾabaw. Of course new discoveries can be made, but at the moment there are no attestations of this particular homily of Jacob of Serugh in Ethiopic apart from the Hāymānota ʾabaw. 

Nevertheless, we will encounter a different case with the other homily of Jacob of Serugh mentioned in that excerpt from the EAe above, namely Jacob's Homily on the Nativity. Excerpts of it are found in the Hāymānota ʾabaw, and there is also a full translation. It is, I think, crucial to keep these things distinct: The excerpts of this homily in the Hāymānota ʾabaw are *not* taken from the full Ethiopic translation of the homily (as I understand the matter). Rather, the Arabic version of Jacob's homily on the nativity was translated into Ethiopic, and independently the Arabic Confession of the Fathers, in which there are the excerpts from Jacob's homily on the nativity, was translated into Ethiopic. In this way, the Ethiopic version of the entirety of the homily is really a different text  from the excerpts in the Hāymānota ʾabaw. They both ultimately go back to the same Syriac homily by Jacob, but they have completely different histories and attestations in Ethiopic (as well as in Arabic). Does that make sense? 

I am not entirely sure how to "translate" this in the BM framework, but conceptually I think there would be problems with using the same text identifier for the excerpts of Jacob's homily on the nativity in the Hāymānota ʾabaw and the full Ethiopic translation of Jacob's homily on the nativity. What do you think?
