### ISSUE TITLE
Name of the prophets and countries of their origin, Abb 156

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2354]
I want to create an ID for a small work from ms Abbadie 156, on the names of the prophets and countries of their origin, starting: 
ንወጥን፡ በርድኤተ፡ እግዚአብሔር፡ በጸሒፈ፡ አስማተ፡ ነቢያት፡ ወአህጉሪሆሙ፡
ወንስቲተ፡ እምተንቢታቲሆሙ፡ በእንተ፡ እግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ እምኑሶሙ፡ አስከ፡ ዐቢዮሙ፡... ቀዳማይ፡ ነቢይ፡ ኢዮብ፡ ውእቱ፡
ኮነ፡ ወልደ፡ ወልዱ፡ ለዔሳው፡ ወስመ፡ ለአቡሁ፡ ዛራ፡

**Comment by thea-m** [comment]
Is it different from LIT6156OriginProphets, LIT5549TribesApostles or LIT1811Liveso? (I did not check the manuscripts now)

**Comment by DenisNosnitsin1970** [comment]
They all are different, though LIT6156OriginProphets and LIT1811Liveso should get the relation "dissimilar" to this one.

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any correlations in addition. It seems to be close to LIT6156OriginProphets or the like and maybe likely to be a paraphrase of one of the works that Dorothea mentioned. How can this be excluded?
