### ISSUE TITLE
Abbadie 156 further issues

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2356]
I wonder how I should proceed with the content of Abbadie 156. It contains on fols. 3r-19r a collection of commentaries on the OT books: an Introduction and commenatries in Geez from Gen to Deut, and then Hosea, Judges and Ruth. 
The introduction starts:  ስብሐት፡ ለእግዚአብሔር፡ መብርሄ፡ ልቡና፡ ንጽሕፍ፡ ትርጓሜ፡ ኦሪት፨ ኦሪት፡ ብሂል፡ ፍትሕ፡ ወሥርዓት፡ ወሕግሀል። ወቦ፡ እለ፡ እቤሉ፡ አእምሮ፡ ዘይፈልጥ፡ ሠናየ፡ እምእኩይ። ወቦ፡ እለ፡ ይብሉ፡ መጽሔት፡ ዘይሬእዩ፡ ባቲ፡ ግብረ፡ እግዚአብሔር። እስመ፡ በሌሊት፡ እሁድ፡ ፈጠረ፡ እግዚአብሔር፡ ፯ፍጥረታተ፡ በአርምሞ። ተፈጽመ፡ ፯ሥርዋት፡ ዘውእቶሙ፡ መላእክት፡ ሰማይ፡ In parts it comes closer to LIT4117Interpretation, but it seems to be different from LIT6608Commentary. I would create an ID for this collection.

**Comment by CarstenHoffmannMarburg** [comment]
I think it is useful to create a new ID and determine the relation to the existing records in the end or the encoding process of Abbadie 156. It might be either a paraphrase or a collation of different texts.
