### ISSUE TITLE
New art theme record in relation to the mircale on the Calliph of Ātrib (LIT3619Miracle), TM

### ISSUE THREAD

**Issue by GueshSol** [BetaMasaheft/Documentation#2362]
Dear all (@gnizla, @DenisNosnitsin1970, @eu-genia, @thea-m and @CarstenHoffmannMarburg),
While describing the decorative aspects of the canonical 33 (34) miracles of Mary (LIT5673AkkonuColl). I found an art theme of four episodes, corresponding to the miracle of the Caliph of Ātrib who was initiated to destroy of a certain church in Ātrib and later ordered his troops (with the power of the Virgin) not to destroy the Church with his letter sent on a white dove.
May I create a new art theme record concerning this illustration?
(You can see the mentioned art theme for example in MS GG-0044, 76r-76v (https://gundagunde.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A105829#page/74/mode/2up)
Many thanks
@GueshSol

**Comment by CarstenHoffmannMarburg** [comment]
I do not have much expertise in Ethiopian miniature painting and I do not have any overview, if the art theme exists in beta masaheft already.

**Comment by gnizla** [comment]
Sounds good, please include a description of the AT so future users can identify it!

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Authority-Files/pull/30
