### ISSUE TITLE
LOC ID for Armenia

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2363]
@eu-genia @thea-m 

I want to encode Armenia, that happens to occur in an incipit in an Amharic commentary to the bible in BMLacq680 (folio 18va). I did not find a LOC for Armenia. Have I overlooked something?

**Comment by CarstenHoffmannMarburg** [comment]
I found LOC1543Armany. I will try to improve the record, so it can be found more easily in a simple search.

**Comment by thea-m** [comment]
I think that it refers to this church https://betamasaheft.eu/institutions/INS0760HAM/main, please double check whether it's really the country

**Comment by CarstenHoffmannMarburg** [comment]
Sorry! In that case, I will rather search once again and eventually create a new entry.

**Comment by CarstenHoffmannMarburg** [comment]
There are several Wikidata IDs for Armenia. I prefer Q208404 = ancient Kingdom of Armenia rather than the one for the modern day state.

**Comment by CarstenHoffmannMarburg** [comment]
I created LOC7374Armenia. I found it in the search at the Bm website. However, the names in Amharic and Gəʿəz orthography is not displayed, unless in Oxygen it is visible. What was my mistake? Is the record only on my computer?
I cannot find the Pull request on github-website and on github-desktop either. It should have happened in May, but I cannot see it. I am a little confused.

**Comment by eu-genia** [comment]
I am not sure what the problem is, this is what I see, what do you expect?
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/9dc7029b-71f7-4439-95ed-161f57aeabe1)

**Comment by CarstenHoffmannMarburg** [comment]
> I am not sure what the problem is, this is what I see, what do you expect? ![image](https://private-user-images.githubusercontent.com/17987728/286587998-9dc7029b-71f7-4439-95ed-161f57aeabe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzQ2OTIsIm5iZiI6MTcwMTI3NDM5MiwicGF0aCI6Ii8xNzk4NzcyOC8yODY1ODc5OTgtOWRjNzAyOWItNzFmNy00NDM5LTk1ZWQtMTYxZjU3YWVhYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE2MTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMjQ2ZGNmZDg3ZjczNzM5MTA2N2IxOGUwYTJlMGNjNTMwNzUyM2QzYzZmYTYyZTMxMGM5OWY2NmZiYzg3YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t8dkiz6F-WHlVDlLuzNBCU5g0LCqTqidy8lOIBIMKLc)

I see! Thank you! Probably I did not have a look to this place.
