### ISSUE TITLE
Who are ፋሊቡና፡ and ካይና፡?

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2365]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found in a synaxarion in BMLacq680 the names ፋሊቡና፡ and ካይና፡ in connection with John the Baptist. Does anybody have an idea, who these persons may be and if it is enough information to encode them in a record? ፋሊቡና፡ may go back to Philippina and ካይና፡ sounds like Cain, but this appears to me not to be a likely option.

**Comment by DenisNosnitsin1970** [comment]
I do not think we make regular records for protagonists (unless they are saints, as such not far from historical figures).

**Comment by CarstenHoffmannMarburg** [comment]
If there is no identification with a Saint or with a historical figure, I rather skip and do not encode the two names.

**Comment by eu-genia** [comment]
https://books.google.de/books?id=zAJKAAAAcAAJ&pg=PA43&lpg=PA43&dq=%E1%8D%8B%E1%88%8A%E1%89%A1%E1%8A%93&source=bl&ots=TX4-4br5O2&sig=ACfU3U1mwsuhc9evsY8oAk7Lfo0_KT8rkg&hl=en&sa=X&ved=2ahUKEwiAor-W_Zz_AhWvcvEDHQIgBPQQ6AF6BAgHEAM#v=onepage&q=%E1%8D%8B%E1%88%8A%E1%89%A1%E1%8A%93&f=false the catalogue of the Bodleian library translates the commemoration as "Commemoratio Phalibunae et Cainae"

**Comment by CarstenHoffmannMarburg** [comment]
Thanks for finding this witness. I may encode them as a group of persons as I did with PRS14033MaximusManius.
In the catalogue, that you quoted, I can see rather ከይና, but not ኮይና:

**Comment by eu-genia** [comment]
Printed edition has Koyna

**Comment by CarstenHoffmannMarburg** [comment]
I don't understand, what you mean with Printed edition. I thought, the link, you quoted here is a scan copy of a printed book. Is it another edition of Dillmanns catalogue of the Oxford library? It sounds strange to have several printed editions for manuscript catalogues. Anyways, I can encode all the three spellings, but I am not sure, if I can give the alternate variants in a relation. Do I need three relations for three possible spellings?

**Comment by eu-genia** [comment]
I mean Ethiopian one, not catalogue . E.g. https://www.facebook.com/groups/164171270289727/posts/2458544977519000/

**Comment by CarstenHoffmannMarburg** [comment]
OK!

**Comment by CarstenHoffmannMarburg** [comment]
I have created an ID (PRS14034FalibulaKayna). I will push it in a minute.

I have no english names for this couple of saints and no additional information. I can imagine, that the name Fālibulā is coming from Philippa or Kāynā from Cain, as in the Bible. But this mere speculation and I do not want to put any english or greek names into the record, just yet alone the latin translitteration from Dillmanns catalogue and the diverging Gəʿəz names.

**Comment by CarstenHoffmannMarburg** [comment]
I don't know, how to refer to the Bodleian manuscript. There is no number in Dillmanns catalogue except for his own (XXII), but I don't find BDLaeth with the number 22.

**Comment by eu-genia** [comment]
when i search for Dillmann 22 I get BDLbruce82

![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/50fda1cc-7e51-4442-9302-51df3b3f6acc)

![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/ca05cdf0-d6e8-47af-8a6f-f6ee649a594c)

**Comment by CarstenHoffmannMarburg** [comment]
Thanks! I did not use this feature to find references before!

**Comment by thea-m** [comment]
Can this be closed?
