### ISSUE TITLE
PRS IDs for መክሲሞስ, መንፍዮስ,  ፊቅጦር and ፊልጶስ

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2366]
@DenisNosnitsin1970 @eu-genia @thea-m 

I see, the names of martyrs are very many in a Synaxarion. I cannot encode all of them, but in case I come across, I try to figure out, whether an ID already exists or can be easily created, if some information is available and reliable. I hope, this is not bothering you! If I shall change my strategy, tell me!

For the month of Ḫədār I found again many names of Saints and martyrs:

መክሲሞስ፡ -> either Maximus the Confessor" (Μάξιμος Ὁμολογήτες = wd:Q206842) or Maximus of Alexandria (wd:Q1278118)
መንፍዮስ፡ -> Manius of Verona? (but venerated only in the West!)
ፊቅጦር፡ -> Victor of Siena (wd:Q48453396)
ፊልጶስ። -> either Philipp the apostle (wd:Q43675) or Philippus of Herakleia or any other Philipp

Is it reasonable to create IDs for them and point to these PRS in the manuscript record or should I better skip them and not encode their names, because it is not certain or more useful in a work-ID following a more detailed study with disambiguation of Saints and martyrs.

**Comment by CarstenHoffmannMarburg** [comment]
I think it is rather a group of martyrs from Africa. The incipit text says:
አመ፡ <hi rend="rubric">፩ለኅዳር፡ በዛቲ፡ ዕለት፡ ኮኑ፡ ቅዱሳን፡ መስተጋድላን፡</hi> ሰማዕታት፡ 
                                        <persName ref="PRS0000">መክሲሞስ፡</persName> ወ<persName ref="PRS0000">መንፍዮስ፡</persName> 
                                        ወ<persName ref="PRS0000">ፊቅጦር፡</persName> ወ<persName ref="PRS0000">ፊልጶስ።</persName> እሉ፡
                                        መስተጋ<add place="above">ድ</add>ላ<add place="inline">ን</add>፡ ቅዱሳን፡ ኮኑ፡ እምሰብአ፡ ሀገረ፡ አፍራቅያ። 
                                        ወእሙንቱሰ፡ አኃው፡ በመንፈስ፡ ቅዱስ። ወአኮ፡ በሥጋ፡ ወተጋብኡ፡ ኅቡረ፡ በበናቲሆሙ፡ በእንተ፡ <hi rend="rubric">ፍቅሩ፡ ለክርስቶስ፡ ወኮነ፡ 
                                            መዋዕሊሁ፡ ለዳኬዎስ፡</hi> ከሐዲ።

**Comment by CarstenHoffmannMarburg** [comment]
It might be related to the martyrdom of Saint Philipp in Afraqya -> LIT3536Martyr
(አኮነ፡ እንዘ፡ ይበውእ፡ ፊልጶስ፡ ኀበ፡ ሀገረ፡ አፍራቅያ፡ ኀበ፡ ሰብአ፡ ይእቲ፡ ብሔር፡)

**Comment by thea-m** [comment]
Speaking from experience, encoding even only the main commemorated saint takes up a lot of time. I think in general descriptions it's better to focus on the persons related to the manuscript production or make a concrete project with clear aim and publication output out of other kinds of encoding. That said, there is no problem other than time with marking up these saints, and since you already invested some work in it, please go ahead!
If you do create records for saints commemorated in the Senkessar, could you please insert their IDs in the corresponding commemorations in LIT4032SenkessarS, LIT4033Senkessar and LIT4035SenkessarDL?

**Comment by CarstenHoffmannMarburg** [comment]
OK. I would like to encode them as a group from Africa and forget about the other options (Maximus the Confessor, Victor of Siena etc). Does everyone of the four needs an own PRS-ID or should I create one record for all of them? Is there any hint in the Guidelines, that I did not see?

**Comment by thea-m** [comment]
I think it is legitimate to create them as a group https://betamasaheft.eu/Guidelines/?id=groups

**Comment by eu-genia** [comment]
This sounds like you had been logged out. Please refresh/log out and log in

Shortening the file name could also be helpful, but not for Permission reasons, just for user friendliness. Filename does not have to be a summary of content.

**Comment by CarstenHoffmannMarburg** [comment]
Again it was not possible with the long ID, so I tried with a shorter ID and named them PRS14033MaximusManius.

**Comment by thea-m** [comment]
Yes, I agree that it's much better to use shorter IDs for user friendliness!

**Comment by eu-genia** [comment]
We probably should add to the guidelines that IDs should not be longer than 20 digits in total

**Comment by CarstenHoffmannMarburg** [comment]
I agree, I think that the ID PRS14033MaximusManiusFiqtorFilpos was denied, because it had to many characters.
