### ISSUE TITLE
LIT ID for ሰላም፡ ለክሙ፡ ጻድቃን፡ ወሰማዕት

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2367]
@DenisNosnitsin1970 @eu-genia @thea-m 

I found a Salam in the end of the BMLacq680. The Salam may be related to the Sənkəssar, that is the major body of the codex. I decided to encode it individually, because it is done by another hand, the explicit of the previous textpart already has a ownership note and the typical ending of a chapter and there is another text (LIT4630Zaaqrabku) in between, that I want to treat as individual text, as well. I found the same text with striking similarity also in EMIP00330 in a Dərsāna Mikāʾel manuscript. 

BMLacq680, folio 291r: **ሰላም፡ ለክሙ፡ ጻድቃን፡ ወሰማዕት። እለ፡ አዕረፍክሙ፡** በዛቲ፡ ዕለት። **መዋዕያነ፡ ዓለም፡ <cb n="291rb"/>አንትሙ፡ 
                                    በብዙኅ፡ ትዕግሥት። ሰአሉ፡ ቅድመ፡ ፈጣሪ፡ በኵሉ፡** ሰዓት። እንበለ፡ ንስሐ፡ ኪያነ፡ ኢይንሣእ፡ ሞት። <hi rend="rubric">ለዘጸሐሮ፡</hi> በክርታስ። ወለዘአጽሐፎ፡
                                    እንዘ፡ ይደርስ። ለዘአንበቦ፡ ወለዘተርጐሞ፡ በልሳን፡ ሐዲስ። ወለዘሰምዓ፡ ቃሎ፡ በዕዝነ፡ መንፈስ። (...)

EMIP00330 (folio and textpart not known): **ሰላም: ለክሙ: ጻድቃን: ወሰማዕት: ለአዕረፍክሙ:** በርትዕት: ሃይማኖት: **መዋዕያነ: ዓለም: አንትሙ: በብዙኅ: ትእግሥት። ሰዓሉ: ቅድመ: ፈጣሪ: በኵ..**

As far as I see, there is no individual ID for this Salam, yet. Do you agree to create a new ID for it? Do think, this Salam and the previous text (LIT4630Zaaqrabku) should be encoded as individual text as msItem or would you recommend to include it to the Sənkəssār and nest it to ms_i2?

**Comment by thea-m** [comment]
I also didn't find an ID for it, please go ahead!
