### ISSUE TITLE
Museum der Kulturen Basel, scroll

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2368]
It turned out that "Museum der Kulturen" in Basel keeps one Ethiopian magic scroll, previously not known, as it looks at the first glance, and want to create a record for the repository and a stub for the scroll (which is a nice object).

**Comment by thea-m** [comment]
Sure, go ahead :)

**Comment by CarstenHoffmannMarburg** [comment]
Very good!
