### ISSUE TITLE
Iip server down (images not shown)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2369]
The viewer seems to be broken: https://betamasaheft.eu/manuscripts/BMLor148/viewer

**Comment by eu-genia** [comment]
Restarted. Let us keep this issue open and use it every time the problem appears. It will happen again.
@CarstenHoffmannMarburg @DenisNosnitsin1970

**Comment by thea-m** [comment]
Thank you! For this particular manuscript, several images between 130 and 158 do not load:
![image](https://github.com/BetaMasaheft/Documentation/assets/19650382/8a6de2c8-26af-42b9-8e93-f760f3aa171b)

(yesterday and today, so I assume it is not because of my connection...)

**Comment by eu-genia** [comment]
something keeps causing the image server to crash

**Comment by eu-genia** [comment]
Some of the images seem to be problematic; I have reprocessed all but still some are causing the server to crash. I had to remove some pages for now and will try to come back to this problem later.

**Comment by thea-m** [comment]
Thank you!

**Comment by eu-genia** [comment]
ok all images in BML or 148 manually reworked, some still have some issues but seem to not get the server crash

**Comment by CarstenHoffmannMarburg** [comment]
Thank you and well done! Do you think, there is a chance to find two missing folios in BMLacq680 (images for folia 6v-7r and 179v-180r)? Do these images cause similar problems and are they excluded for this reason or is it another problem?

**Comment by eu-genia** [comment]
Do you mean you cannot see images that are there or they are skipped? If they are skipped they probably are skipped when digitizing. Which are the current image numbers?

**Comment by CarstenHoffmannMarburg** [comment]
Yes, both from the foliation in pencil at the bottom, but also from reading the text, it is clear, that two images are missing. It is the image after image no. 8, that is missing, because image 8 shows folio 5v+6r, while the next image 9 shows already 7v+8r, what means that the image for the opening 6v+7r is missing after image 8 and before image 9. The same is for 179v+180r, that is missing after scan image 180 and before image 181.
If it is permanent loss, because the opening was skipped during digitizing, than I should make a note in the record - probably in physDesc -> foliation.  Do you agree?

**Comment by eu-genia** [comment]
yes, can see that. make a note that some folios were not digitized. unless someone (@antobrita ? @abausi ?) has any other set of images (what I have as backup have already been renumbered, I do not have the raw image set)

**Comment by abausi** [comment]
I will try to have a look but all that was done and available was 
shared, so I assume, these images were skipped. There has been a quite 
careful workflow, but errors can always appear. Let me check as soon as 
I can. If there is any problems with Or. 148 I can provide a small size 
PDF that can be transformed in JPEG. I assume this should not cause any 
problem.

Il 02/06/2023 09:51, Eugenia ha scritto:

**Comment by abausi** [comment]
In the BML I have there the same problem, i.e. the opening is missing. I 
shall aks Karsten Helmholz in case he still has a distinct set iof 
images, which I strongly doubt is the case.

Il 02/06/2023 09:51, Eugenia ha scritto:

**Comment by CarstenHoffmannMarburg** [comment]
I have seen, that the images of BMLgadd230 are not available to me at the moment.

**Comment by eu-genia** [comment]
There is an error in the data, the manifest produces an error message

`An error occurred while processing request to /exist/apps/BetMasWeb/api/iiif/BMLgadd230/manifest: err:FORG0001 can not convert '76is' to xs:integer [at line 85, column 21, source: /db/apps/BetMasWeb/modules/locus.xqm]`

**Comment by eu-genia** [comment]
I have changed 76bis to 76b
