### ISSUE TITLE
Identefication of Yohannes

### ISSUE THREAD

**Issue by Addisie** [BetaMasaheft/Documentation#2370]
In the manuscript https://betamasaheft.eu/manuscripts/MDA003/main the name Yohannes is mentioned as a bishop of Tegray on image 168r but I don't get any detail about him. can he identified in his historical background?

@DenisNosnitsin1970 
@sologebre

**Comment by DenisNosnitsin1970** [comment]
I would not know him, he is probably one of the recent figures. Please check the Encyclopaedia aethiopica (since all persons who were indexed in EAE got IDs in the Beta masaheft), and the book of Mersha "Zena pappasat ityopyaweyyan".

**Comment by Addisie** [comment]
Thank you every one. https://github.com/BetaMasaheft/Persons/pull/725
