### ISSUE TITLE
Text identification

### ISSUE THREAD

**Issue by Addisie** [BetaMasaheft/Documentation#2371]
In  https://betamasaheft.eu/manuscripts/MDA003/main in 1st folio I found a guest text that talks about Qebat and Tawahedo relgious conteroversy however, I don't know where the taxet is taken from. can you help to identify the text?
@thea-m 
@CarstenHoffmannMarburg 
@DenisNosnitsin1970 
@MershaMengistie

**Comment by CarstenHoffmannMarburg** [comment]
In the first column of folio 1r, I read the name ቅዱስ፡ ፈለስኪኖስ፡ መንበጋዊ፡ in the sixth to seventh line. This should be Philoxenus of Mabbug with the ID PRS7853Philoxen. The work may be one of the four works, that are related to him in BetaMaṣāḥəft. Possibly it is either LIT6523Feleksinos or LIT6130CommPhilox.

**Comment by thea-m** [comment]
@Giuliacas maybe you have an idea about this text?
It seems to be a compilation of quotations, among them Philoxenos, on the topic

**Comment by DenisNosnitsin1970** [comment]
Sorry, I do not know it.

**Comment by Giuliacas** [comment]
I couldn't identify the text either, it doesn't seem to be an extract from the texts on the controversy I have read so far. But if anything comes to my mind I will let you know.

**Comment by Addisie** [comment]
Thank you every one for your comments.
