### ISSUE TITLE
Short text in ms EU3

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2372]
Dear all,
this is a short text inserted as additional note on the guardleaf of ms EU3 (fol. 1r).
It introduces itself as a homily to the Archangel Raguel and includes several magic names.
The whole text is the following: 
 ድርሳን፡ ዘቅዱስ፡ ራጉኤል፡ ብሃ`<gap reason="illegible" unit="chars" quantity="2"/>`መብሕኤል፡ በዕትናኤል፡ በሃድናኤል፡ `<gap reason="illegible" unit="chars" quantity="1"/>`ጽሐድኤል፡ እሎንተ፡ ቃላት፡ ዘነገሮ፡ እግዚአብሔር፡ ዘቅዱስ፡ ራጉኤል፡ ብሑር፡ ዘቅዱስ።  
Some letters are illegible due to the ink, the handwriting and the state of preservation of the leaf. Still, it seems to me that this text is unrecorded in the BM database.

**Comment by thea-m** [comment]
I also didn't find this text in Bm. I think it would be legitimate both to create a record or forgo the creation - use your best judgment and go ahead! :)

**Comment by karljonaskarlsson** [comment]
I could also not find it, so it seems legitimate to create a new work
