### ISSUE TITLE
mss to be added to list

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2373]
Could you add this link to the list of digitized manuscripts: 
Digitized microfilms of Ethiopic manuscripts of the Ethiopian Patriarchate and Ethiopian Church in Jerusalem (I opened the page of the institute, loaded it entirely and did ctrl+f for "EOC", which got more results than filtering by language)
https://archive.org/search?query=creator%3A%22Center+for+the+Preservation+of+Ancient+Religious+Texts%2C+BYU%22
Thank you!

**Comment by eu-genia** [comment]
is this list https://archive.org/search?query=creator%3A%22Center+for+the+Preservation+of+Ancient+Religious+Texts%2C+BYU%22+EOC complete?

**Comment by eu-genia** [comment]
seems the same as applying Geez + EOC as filters

https://archive.org/search?query=creator%3A%22Center+for+the+Preservation+of+Ancient+Religious+Texts%2C+BYU%22&and%5B%5D=subject%3A%22Ethiopian+Orthodox+Church%22&and%5B%5D=subject%3A%22Ge%27ez%22

**Comment by thea-m** [comment]
Great, thank you!
