### ISSUE TITLE
Work record for Gadla Lǝbdǝyos

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2379]
There seems to be a doublette:
https://betamasaheft.eu/works/LIT4768GadlaLe
https://betamasaheft.eu/works/LIT1472GadlaL

I suggest we keep the more developed one (CAe 4768) and correct the reference in https://betamasaheft.eu/persons/PRS6225Lebdeyos. 

@thea-m

**Comment by thea-m** [comment]
Thank you, Marcin!
