### ISSUE TITLE
LIT ID for Zəmmāre za-Hosāʿnā and Zəmmāre za-Dabra Zayt

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2380]
@DenisNosnitsin1970 @thea-m @eu-genia 

I did find two Zəmmāre songs in the first written folio (1r) in BMLor148. Marrassini categorized them as one, but I think, they are distinct - even though they are related by their content. They nevertheless have different titles and they are written by different hands. I could not find any of them in BM. I looked up for ዝማሬ፡, ሆሳዕና፡, ኪሩ፡ ቤል፡, ደብረ፡ ዘይት፡. I don't know what words or search strategies I can employ in addition. 

In case, they do not have a LIT yet, I would like to create a LIT ID for each of them:

1. Zəmmāre za-Hosāʿnā
<div type="edition" corresp="a1" xml:lang="gez">
            <ab><add place="above">ሀዘ</add>ዝማሬ፡ ዘሆሳዕና፡ ግዕዝ፡ ንዜኑ፡ ክብራ፡ ለዐድግት፡ እስመ፡ ተጻዕነ፡ ለዕሌሃ፡ ነደ፡ እሳት፡ ነበልበለ፡ ኀይል። አትሕትና፡ ዘእንበለ፡ 
               መስፈርት፡ አትሕትና፡ ዘእንበለ፡ ዐቅም። ለርኁባን፡ ኅብስት፡ ለጽሙዐን፡ አነቅዕት። ኦ። ተቀበልዎ፡ ነሲኦሙ፡ አዕጹቀ፡ በቀልት፡ ደቂቅ፡ አዕሩግ፡ ወሕፃናት። ኦ። ተጽኢኖ፡ ዲበ፡ አድግ፡
               ወእዋለ፡ ቡአ፡ እየሩሳሌም፡ በእንተ፡ ሰንበት፡ ወይቤሉ፡ ሆሳዕና፡ በአርያም። ኦ። በከመ፡ ነስአ፡ አብርሃም፡ አዕጽቀ፡ በቀልት፡ ሰብሐ፡ ወዘመረ፡ በ<cb n="1rb"/>በእለተ፡ ሰንበት።
               ኦ።<add place="above">እም</add>ተጽዕነ፡ ዲበ፡ ዕዋል፡ ዘይጼዐን፡ ለዕለ፡ <persName ref="PRS13936Kirubel">ኪሩ፡ ቤል፡ </persName>
               </ab>          
         </div>

:---:
2. Zəmmāre za-Dabra Zayt:
<div type="edition" corresp="a2" xml:lang="gez">
            <ab>ዝማሪ፡ ዘደብረ፡ ዘይት፡ እንዘ፡ ይነብር፡ እግዚእነ፡ ውስተ፡ ደብረ፡ ዘይት፡ ተስእልዎ፡ 
               አርዳኢሁ፡ ወይቤልዎ፡ ማእዜ፡ ይከውን፡ ምጽእትከ፡ ወለሕልቀተ፡ ዓለም፡ ወይ<gap reason="illegible" unit="chars" quantity="2"/>ሙ፡ ለአርዳኢሁ፡ እምበለስ፡
               አእምሩ፡ አዕጹቀሁ፡ ወይትነሥአ፡ አሕዝብ፡ ለዕለ፡ ሕዝብ፡ ወይከውን፡ ብድብደ፡ ወድልቅልቅ፡ በበብሔር፡ ዝኵሉ፡ ለእመ፡ ኮነ፡ አሚሀ፡ ኬ፡ ምጽአቱ፡ ለወልደ፡ እጓለ፡ እምሕያው፡ 
               ምስለ፡ ኵሉ፡ ኀይለ፡ ሰማይት፡ አሜሃ፡ ይውሕዝ፡ <gap reason="illegible" unit="chars" quantity="2"/>ዝ፡ እሳት፡ 
               ወ<gap reason="illegible" unit="chars" quantity="4"/>ብሱ፡ አብሕርተ፡ እሳት፡ ወይትረወጹ፡ መላእክት፡ ለአሣተ፡ ጋብአ፡</ab>
         </div>

**Comment by thea-m** [comment]
I also didn't find IDs for them. I'm not aware of any current cataloguing strategies regarding Zəmmāre , but if these two textual units are attested outside of the collection, it probably makes sense to create new records.

**Comment by CarstenHoffmannMarburg** [comment]
I pushed a pull request with the number #1015. Is it necessary or useful to leave a note like this or is it more appropriate to just close this issue, once a pull request was pushed?

**Comment by CarstenHoffmannMarburg** [comment]
I have just seen the note by Marrassini (p. 91), that this hymn is attested in BN(Gr.) 372, ff. 141v-142r. Does anybody know how to decipher this notation to the current siglum? May it be helpful to have a look to Grébauts (bm:Grebaut1938GriauleI) or Strelcyns (bm:Strelcyn1954Griaule) catalogues? Do you have a list at hand?

**Comment by CarstenHoffmannMarburg** [comment]
If I am correct, we do not have a record for BNFet372 yet. Shall I create a stub based on the information, you wrote in this thread?

**Comment by CarstenHoffmannMarburg** [comment]
I checked the website on Zəmmāre, that you recommended to me. I found a song on Dabra Zayt, but as far as I have noticed, it is not the one, that is witnessed in BMLor148.
http://www.ethiopianorthodox.org/churchmusic/zema%20timehert%20bet/mahlet%20yared/8%20zimare%20zezur%20amba/88%20zimare%20zedebere%20zeit/1.mp3

**Comment by CarstenHoffmannMarburg** [comment]
There is another Zəmmāre on Dabra Zayt on Youtube, that has at least some similarities: 
https://www.youtube.com/watch?v=YHEol821qcg
I put the parallel passages, that I discovered from the given text in bold. I have seen it from the text in the video. From the audio I could hardly understand.
<ab>**ዝማሪ፡ ዘደብረ፡ ዘይት፡ እንዘ፡ ይነብር፡ እግዚእነ፡ ውስተ፡ ደብረ፡ ዘይት፡** ተስእልዎ፡ 
                    **አርዳኢሁ፡ ወይቤልዎ፡** ማእዜ፡ **ይከውን፡ ምጽእትከ፡ ወለሕልቀተ፡ ዓለም፡ ወይ<gap reason="illegible" unit="chars" quantity="2"/>ሙ፡** ለአርዳኢሁ፡ **እምበለስ፡
                    አእምሩ፡ አዕጹቀሁ፡** ወይትነሥአ፡ አሕዝብ፡ ለዕለ፡ ሕዝብ፡ ወይከውን፡ ብድብደ፡ ወድልቅልቅ፡ በበብሔር፡ ዝኵሉ፡ ለእመ፡ ኮነ፡ **አሚሀ፡** ኬ፡ **ምጽአቱ፡ ለወልደ፡ እጓለ፡ እምሕያው፡** 
                    ምስለ፡ **ኵሉ፡ ኀይለ፡ ሰማይት፡ አሜሃ፡** ይውሕዝ፡ <gap reason="illegible" unit="chars" quantity="2"/>ዝ፡ እሳት፡ 
                    ወ<gap reason="illegible" unit="chars" quantity="4"/>ብሱ፡ አብሕርተ፡ እሳት፡ ወይትረወጹ፡ መላእክት፡ ለአሣተ፡ ጋብአ፡</ab>
In case we accept the parallels as dependencies, how can I refer to a youtube video?

**Comment by DenisNosnitsin1970** [comment]
Concerning the levels individual chants, sets of commemoration, and what should be encoded - I assume that individual chants are the units that can be part works or get separate IDs, but what is about "sets of chants" for individual commemorations? There are probably several possible strategies as to how one can deal with that, but we have a number of works built up in the same way, these are other chant works, and also such work as Synaxarion. If you think you will understand that the structure is of the same type. Several minor texts under within one overarching structure (a date - so, you have a set of commemorations for a date, not completely stable). Shoud we look as how these works are encoded?

**Comment by DenisNosnitsin1970** [comment]
Wait, Mawāśəʿt is not Zemmare, and Zemmare is not Mawāśəʿt. Both may have chants for Palm Sunday (this is their relation), and may share some text because they may originally stem from the same sources, but we have to keep them strictly apart. The Zemmare officially printed by the Church should be the basis of the work record, (according to our rules) since a big part of the manuscript tradition (including BNFet372, partly or completely) follows that. It is no wonder that chants in  BMLor148 are not included. They are quite old and with not melekket, isolated, and appear as additional notes. They can be individual local production (written outside of Ethiopia?), or they may be just strongly modified in the later Zemmare.  Are these two chants attested in BNFet372? If they are, you can create IDs for the both, include IDs in BMLor148 and link through relations to  BNFet372 (with or without stub), and link to Zemmare record ("somehow connected"), untill it will be further clarified.

**Comment by CarstenHoffmannMarburg** [comment]
I have consulted the Church book (አምስቱ፡ ጸዋትወ፡ ዜማዎች።, p. ፬፻፷፫ = 463) from the HLCEE-library. There is a ዝማሬ፡ ዘሆሣዕና፡ but with completely different incipit. There are some similarities in the final part, but I don't think, that they are enough to establish a dependancy:
**ዝማሬ፡ ዘሆሳዕና፡** ሑሩ፡ በልዎ፡ ለእገሌ፡ ይቤለከ፡ ሊቅ፡ አይቲአ፡ ጸርሑ፡ ኀበ፡ አግብር፡ ፋሲካ፡ (...) **ንዜኑ፡ ክብራ፡ ለዐድግት፡** ወዲበ፡ ዕዋል፡ **ተፅዕነ፡ ነደ፡ እሳት፡ አትሕትና፡** ዘእንበለ፡ አቅም፡ ወኂሩተ፡ ዚአሁ፡ **ዘእንበለ፡ መስፈርት፡** ጽዋዓ፡ ሕይወት፡ ጽ፡ መድኃኒት፡ ዘወረጸ፡ እምሰማያት። ዝ፡ ጻድቅ፡ ወየዋህ፡ በጽሐ፡ ኀቤኪ፡ ብርሃንኪ፡ ወሰብሐተ፡ እግዚአብሔር፡ ሠረቀ፡ ላዕሌኪ፡ ተፈሥሒ፡ ጽዮን፡ ንጉሥኪ፡ በጽሐ፡

**Comment by CarstenHoffmannMarburg** [comment]
>There is another Zəmmāre on Dabra Zayt on Youtube, that has at least some similarities:
https://www.youtube.com/watch?v=YHEol821qcg
I put the parallel passages, that I discovered from the given text in bold. I have seen it from the text in the video. From the audio I could hardly understand.
ዝማሪ፡ ዘደብረ፡ ዘይት፡ እንዘ፡ ይነብር፡ እግዚእነ፡ ውስተ፡ ደብረ፡ ዘይት፡ ተስእልዎ፡
አርዳኢሁ፡ ወይቤልዎ፡ ማእዜ፡ ይከውን፡ ምጽእትከ፡ ወለሕልቀተ፡ ዓለም፡ ወይሙ፡ ለአርዳኢሁ፡ እምበለስ፡
አእምሩ፡ አዕጹቀሁ፡ ወይትነሥአ፡ አሕዝብ፡ ለዕለ፡ ሕዝብ፡ ወይከውን፡ ብድብደ፡ ወድልቅልቅ፡ በበብሔር፡ ዝኵሉ፡ ለእመ፡ ኮነ፡ አሚሀ፡ ኬ፡ ምጽአቱ፡ ለወልደ፡ እጓለ፡ እምሕያው፡
ምስለ፡ ኵሉ፡ ኀይለ፡ ሰማይት፡ አሜሃ፡ ይውሕዝ፡ ዝ፡ እሳት፡
ወብሱ፡ አብሕርተ፡ እሳት፡ ወይትረወጹ፡ መላእክት፡ ለአሣተ፡ ጋብአ፡
In case we accept the parallels as dependencies, how can I refer to a youtube video?

I found a ዝማሬ፡ ዘደብረ፡ ዘይት። in the Church book on page p. ፬፻፷ = 460. It has some phrases similar to the text in BMLor148, but more in commen with the mentioned youtube video.

**Comment by CarstenHoffmannMarburg** [comment]
>Wait, Mawāśəʿt is not Zemmare, and Zemmare is not Mawāśəʿt. Both may have chants for Palm Sunday (this is their relation), and may share some text because they may originally stem from the same sources, but we have to keep them strictly apart.

Is it possible to find the text of LIT4467PalmSunday somewhere to check a possible relation or similarity in content? Mawāśəʿt za-Hośāʿnā is not in the Church book (አምስቱ፡ ጸዋትወ፡ ዜማዎች።), that I consulted here.

**Comment by DenisNosnitsin1970** [comment]
I do not know, frankly speaking; Mäwase'et is studied less than others.
