### ISSUE TITLE
Mawāśəʾət za-ʾArsimā

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2381]
@DenisNosnitsin1970 @eu-genia @thea-m @karljonaskarlsson 

I found an individual antiphone in BMLor148 on f. 4r-v. It seems to me, that there is just a general record (LIT1990Mawase), but hardly any records for individual antiphones. The one on ʾArsima (PRS8126Rhipsime), I did not find it in EStrm017 (f. 104-164), that was indexed in the work record LIT1990Mawase. I did also not find a suitable text when looking for መዋሥእት or for አርሲማ. What else can I do to look it up? 

May I create a new ID? Is it related to LIT1990Mawase or not?

Incipit:
<incipit xml:lang="gez">መዋሥእት፡ ዘአርሲማ፡ ብፅዕት፡ ዘ፫መልዕልተ፡ ኰኵሕ፡ ዲበ፡ ወርቅ፡ ሐነጸት፡ ቤታ፡ ነፋሳት፡ ዘኢይክሉ፡ አንቀልቅሎታ፡ ብፅዕት፡ አርሲማ፡ በስመ፡ 
                        ኢየሱስ፡ ጸንዐ፡ መሰረታ። ዘ፬፡ ረሰየት፡ ሥጋሃ፡ ከመ፡ ጽኑዕ፡ ሐመር፡ ዘኢይቀርቦ፡ ማዕበል፡ ካልእኒሃ፡ ታስተጻንዕ፡ በገድል፡ እንዘ፡ ትየውሆሙ፡ በቃል። ዘ፲፬፡ በ፡ እቶነ፡ እሳት፡ ወረወት፡ 
                        ርእሳ፡ እማይ፡ ወእመንፈስ፡ እሳተ፡ ለቢሳ፡ በከመ፡ ተጽሕፈ፡ በወንጌል፡ መጠወት፤ ነፍሳ። </incipit>

explicit:
                     <explicit xml:lang="gez">ር፡ ተዝካሬ፡ <gap reason="illegible" unit="chars" quantity="6"/>ጋቢአነ፡ አሐቲ፡ 
                        <gap reason="illegible" unit="chars" quantity="4"/>ን፡ እምኵ<gap reason="illegible" unit="chars" quantity="8"/><pb n="4va"/>ብ፡ 
                        መዝገበ፡ ዘኢይማስን፡ በፃፄ፡ ወናምስጥ፡ እምዕፄ። <hi rend="rubric">ወዓዲ፡</hi> አልቦ፡ ዘይዐቢየ፡ እምኵሎን፡ አንስት፡ ዘእንበለ፡ ማርያም፡ ሙዳየ፡ ትንቢት፡ ዐቢይ፡ ስማ፡ 
                        በመንግሥተ፡ ሰማያት፡ ንግበር፡ ተዝካራ፡ በስብሓት። ። ። ።</explicit> 

Also Marrassini (p. 91) stated, that there are no traceable parallels, but an edition and translation in E. Cerulli, L'Oriente Christiano nell'unita delle sue tradizioni, in: L'Oriente Cristiano nella storia della civilta, Roma: 1964, pp. 34-40 (does not have a BM-ID in zotero yet, but is present in the OPAC of Uni Hamburg. For the place, it is stated to be "Standort/Signatur: 9: M:Cer/26149 Sonderstandort nicht ausleihbar" - Does this mean, it can be accessed in the AAI or in the HLZ or is it inaccessable?) and also in: Storia della letteratura etiopica3, Firenze-Milano 1968, pp. 213-220 (that might be identical to the first edition in bm:Cerulli1956LetteraturaEtiop). Can I add the references to Cerullis editions without consulting them or is it neccessary to access them, before referencing it? Where can I access them?

**Comment by DenisNosnitsin1970** [comment]
I would think (having spoken about the issue with Dorothea) that you can create an ID for Ripsime mewase'et chant, but you would need to include it also into the main Mewase'et record as one of the part works. In order to be consequent, one would need to further elaborate the Mewase'et record, presenting individual chants as part works. It can be done on the basis of the existing editions of Mewase'et (church edition would be also acceptable, it has clear divisions according to the church calendar). Ripsime chant would be one of the work parts (in case it is not in the edition, a note explaining the source would be needed).

**Comment by eu-genia** [comment]
I assume this would also apply to https://github.com/BetaMasaheft/Documentation/issues/2380

**Comment by CarstenHoffmannMarburg** [comment]
OK, in that case, I will create a LIT ID and record for Mawāśəʾət za-ʾArsimā in a minute and later for the other Mawāśəʾət, that I can find in one or two good manuscripts or in the edition by Cerulli.

**Comment by DenisNosnitsin1970** [comment]
For me, it is not obvious, ት rhyme continues also in the second passage, and I do not see any obvious sence discontinuity, just the same praising. Of course, it is not clear either as to why he introduced a dotted divider, but this happens sometimes, the motivation of the scribe remains obscure.

**Comment by DenisNosnitsin1970** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2380 - what is written above would apply also to Zemmare, the only thing is one has to consider the internal structure of the chants for each commemoration, if it should be reflected in work-part or not (I think Mewase'et is less complex than Zemmare in this respect).

**Comment by CarstenHoffmannMarburg** [comment]
I just looked up Cerullis "Storia della letteratura etiopica" in the edition of 1961 in archive.org, but did not find the translation of Mawāśəʿt za-ʾArsimā in the indicated pages and I did not even find it at all. I think the pagination is different in each edition of the "Storia" and the text is hidden somewhere. I think, I will obstain to quote this reference. It might be sufficient to quote Cerullis "L'Oriente Cristiano nella storia della civilta", that I created a Zotero reference just now: "bm:Cerulli1964LOriente".

**Comment by CarstenHoffmannMarburg** [comment]
> I would think (having spoken about the issue with Dorothea) that you can create an ID for Ripsime mewase'et chant, but you would need to include it also into the main Mewase'et record as one of the part works.

May I use a relation with name="dcterms:isPartOf" to point to the general record LIT1990Mawase or another relation?

**Comment by CarstenHoffmannMarburg** [comment]
I have seen a long list of Antiphons encoded as textparts in the record of LIT1990Mawase. That means, I do not have to search for all the Antiphons from the manuscripts or editions by myself, but I can take this list and change it to a list of relations. Is that correct? May I use name="dcterms:hasPart" for these relations?

**Comment by eu-genia** [comment]
do all the separate chants have independent circulation outside of the collection? 
if they are already encoded as textparts and have no independent circulation they do not need CAe IDs, they should be referred by their textpart IDs

**Comment by eu-genia** [comment]
I opened 1990 now, they have IDs already, and there are `corresp `provided? then what is meant by the "list of relations"? `corresp `already establishes the connection

To be fully consistent CAe 1990 should also include IDs for the textparts and then, when chants appear inside of the collection, one would point to them by the derived ID and not the independent one, i.e. now we have

```
<div type="textpart" corresp="LIT4424JohnTheBaptist">
               <label>Antiphon of John the Baptist, 1st Maskaram (<foreign xml:lang="gez">ዘበዓለ፡ ዮሐንስ፡ መጥምቅ፡</foreign>)</label>
            </div>
```
ideally this should become e.g.

```
<div type="textpart" corresp="LIT4424JohnTheBaptist" xml:id="JohnB">
               <label>Antiphon of John the Baptist, 1st Maskaram (<foreign xml:lang="gez">ዘበዓለ፡ ዮሐንስ፡ መጥምቅ፡</foreign>)</label>
            </div>
```
and then if you have a MSS with a Mawāśǝʾǝt collection you point not to `LIT4424JohnTheBaptist `but to `LIT1990Mawase#JohnB` etc

**Comment by karljonaskarlsson** [comment]
What we have in BMLor148 is not _one antiphon_, but a _set_ of individual mawase't antiphons for the commemoration of Arsima. This is only a question of terminology, but I think it's good to distinguish clearly between the individual chants/antiphons and the commemoration/sets of antiphons. The text parts in 1990 also cannot really be called "Antiphon for John the Baptist" etc., but must be something like "Set of antiphons for John the Baptist" or "Commemoration for John the Baptist".

As far as I understood, the set of mawase't chants/antiphons for Arsima is only attested in this manuscript, i.e. only has an individual circulation, but as Denis suggested, checking some editions might be good. If we include it as a text part in 1990, it would mean that 1990 is some kind of theoretical repository of all attested Mawase't antiphons, rather than a work that actuals exists. But maybe that it ok.

**Comment by eu-genia** [comment]
Thank you, very good (though unique attestation is not the same as individual circulation)

**Comment by karljonaskarlsson** [comment]
You are right! In this case, however, I think it might be both :) (at least, the attestation in BMLor148 is not in the context of a larger Mawāśǝʾt collection)

**Comment by CarstenHoffmannMarburg** [comment]
What edition of Mawāśəʾət do you think is useful and available. May Grébaut 1931 as indicated in the record of LIT1990Mawase be a good option? (= Grébaut, S. 1931. ‘Un recueil ancien de Mawâseʿet’, Aethiops, 4/1 (1931), 1–6.) The Aethiops journal is supposed to be available in the AAI-library.

**Comment by karljonaskarlsson** [comment]
Grébaut 1931 is a French translation of the beginning of a small collection of Mawāśəʾt-type antiphons, typical for the earliest preserved stage (as far as I am aware). I think it would be better to look at a church edition from the HLZ library. Probably there will be one on the right hand when you enter the library :)

**Comment by CarstenHoffmannMarburg** [comment]
> Grébaut 1931 is a French translation of the beginning of a small collection of Mawāśəʾt-type antiphons, typical for the earliest preserved stage (as far as I am aware). I think it would be better to look at a church edition from the HLZ library. Probably there will be one on the right hand when you enter the library :)

Thank you! Denis as well gave me a hint via Facebook to look for the big red book in the HLZ library or to consult alternatively the edition of Velat.

**Comment by karljonaskarlsson** [comment]
For Mawase't, I don't believe there is any edition by Velat, but surely you will find one or several in the library.

**Comment by CarstenHoffmannMarburg** [comment]
> and then if you have a MSS with a Mawāśǝʾǝt collection you point not to `LIT4424JohnTheBaptist `but to `LIT1990Mawase#JohnB` etc

I understand, that I am supposed to give short cuts for each of the Antiphons as you did #JohnB for LIT4424JohnTheBaptist. Similarly I may invent #River for LIT4425River and it will turn out to be LIT1990Mawase#River. Is this correct?

I still did not understand, whether this should be done also for LIT6841MawArsima, since this antiphon (or rather antiphons) are not attested in a larger collection, but individually and uniquely attested in BMLor148.
