### ISSUE TITLE
Commentary of ʾOrit

### ISSUE THREAD

**Issue by Addisie** [BetaMasaheft/Documentation#2382]
I am cataloguing Tərgwame ʾOrit (https://betamasaheft.eu/manuscripts/MDA003/main)

which I didn’t find exactly the same work record on Betamasaheft. Because the text reading is not the same as it is possible to compare on the online Images of the manuscript. 
But, such similar records which I found are; (https://betamasaheft.eu/manuscripts/BNFabb156/main?hi=%22%20%E1%89%B5%E1%88%AD%E1%8C%93%E1%88%9C%20%E1%8A%A6%E1%88%AA%E1%89%B5%22 
and https://betamasaheft.eu/manuscripts/BNFabb28/main?hi=%22%20%E1%89%B5%E1%88%AD%E1%8C%93%E1%88%9C%20%E1%8A%A6%E1%88%AA%E1%89%B5%22).
 
Both have the same title, structure and the same commentary from geez to Geez as the same as my ongoing work. 

Thus, could you please share your experience if I should use the available work record ID whether I should create a new work record for this commentary?

**Comment by eu-genia** [comment]
see https://github.com/BetaMasaheft/Documentation/issues/2376

**Comment by Addisie** [comment]
The text is different when I compare my manuscript with others

**Comment by Addisie** [comment]
My manuscript is a compostion of 10 Books 
Maṣḥafa miṭata bǝrhānāta samāy, Maṣḥafa Menhar, Maṣḥafa Maccabi1, Maṣḥafa Maccabi 2,and Daniel including the above  mentioned books by Zhenia

**Comment by eu-genia** [comment]
Sure I listed only 5, Orit are 8 but normally Joshua Judges Ruth?

**Comment by Addisie** [comment]
Thank you very much for the comments and I apolgize for missusing the term Orit.
So, still the question is: is it possible to use the ID LIT4117Interpretation as general ID also in a manuscript that contains a different combination of Old testament biblical books written only in Geez?

**Comment by thea-m** [comment]
@DenisNosnitsin1970 I think you worked a lot with these texts, what do you think?

**Comment by DenisNosnitsin1970** [comment]
OK, i think it is neither  LIT4117Interpretation nor LIT6608Commentary, it seems to be the same text as in EMML 2101, another commentary ascribed to Meherka Dengel. Since that was the only witness, as far as I understand, the record for this commentary collection is missing. But the colophon as transcribed by Getatchew Haile in EMML vol. 4 is missing (should be in text frame 78)
