### ISSUE TITLE
A doublet for deletion

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2383]
I suggest that https://betamasaheft.eu/works/LIT1953Mashaf/main is deleted and LIT1115Antich is kept.
@CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia 

I agree. There are also different CAe connected to these two records? Do they also need to be changed e.g. one of the deleted?

**Comment by eu-genia** [comment]
Of course. each record is always a CAe ID. record and CAe ID are synonyms for us. when deleting a record you delete the CAe ID.
