### ISSUE TITLE
Monastic genealogy in BDLeu6

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#2384]
Dear both,
MS BDL Ullendorff 6 is a Gadla Zamikāʾel ʾAragāwi. The text is followed by another text (fols 68ra-vb) in the main hand, which is a monastic genealogy of Dabra Dāmmo.
Incipit: ዝውእቱ፡ ጥንተ፡ ልደቶሙ፡ ለመነኮሳት፡ እንጦንዮስ፡ ወለዶ፡ ለመቃርዮስ፡ መቃርዮስ፡ ወለዶ፡ ለጳኵሚስ፡ ጳኵሙስ፡ ወለዶ፡ ለዘሚካኤል፡ ዝውእቱ፡ አቡነ፡ አረጋዊ፡ አረጋዊ፡ ወለዶ፡ ለማትያስ፡ ማትያስ፡ ወለዶ፡ ለዮሴፍ፡
Explicit: ወአባ፡ ዓፅፈ፡ ወልድ፡ ወአባ፡ ገብረ፡ ክርስቶስ፡ ወአባ፡ ተወልደ፡ መድኅን፡ ወአባ፡ ዘሥላሴ፡ ጸሎቶሙ፡ ወረድኤተ፡ ትዕግሥቶሙ፡ ይዕቀቦ፡ ለፍቁሮሙ፡ ዘማርያም፡ እንዚራድንል፡ ለዓለመ፡ ዓለም፡ አሜን፡
The text is identical to a monastic genealogy contained in MS BAV Borg. Et. 22 (https://betamasaheft.eu/manuscripts/BAVborget22/main), i2. However, no work record is existing and no MS record for this Vatican manuscript is found in the repository (perhaps it is found in a hidden branch like the JJ-branch or something?).
I suggest to create the work record for this monastic genealogy. Shall I write a short note to Augustine Dickinson (author of the BAVborget22 record) and tell him that the work record is now existing and available?

**Comment by thea-m** [comment]
I am not aware of any ongoing work on the Vatican mss, so I don't expect inactive branches.
The monastic genealogy records were a bit chaotic in the past, so a general record was created: LIT6591MonGenealogy. This could be used if you like, but it would also be possible to create a new one, since the work seems to be clearly distinct.

**Comment by MassimoVilla** [comment]
Thank you, I will then go ahead and create a new record for this particular monastic genealogy which seems to be specifically referred to Dabra Dāmmo

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Works/pull/1006
