### ISSUE TITLE
Doublet for deletion 

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2386]
https://betamasaheft.eu/works/LIT1270Dersan
https://betamasaheft.eu/works/LIT3983Dersan

LIT3983Dersan should probably stay, it is correct and up-to-date.

@CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
It seems very plausible to me. Thank you for finding! However, since I am very new in the project, I do not want to take this decision by myself and also I do not know, how to delete an ID. @eu-genia, @DenisNosnitsin1970 and @thea-m will know better.

**Comment by eu-genia** [comment]
this is of course clearly a doublet; the records should be merged
