### ISSUE TITLE
Clement in Sinodos = Clement I (of Rome?)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2387]
@thea-m 

I found 30 Canons of the Apostles, after the Ascension of our Lord (LIT2673CanonsAscension), that is attributed to some ቀሌምንጦስ፡ in BMLor148 on f. 5r. I guess, this ቀሌምንጦስ፡ is PRS3129Clement = Clement I of Rome, who is (alledgedly) responsible for these Canons, that became part of the Sinodos. May I add relation in the manuscript record of BMLor148#ms.i3.1 as well as in the work record of LIT2673CanonsAscension and in person record of PRS3129Clement?

**Comment by thea-m** [comment]
It is possible! I would maybe avoid the relation in the manuscript record, because it might overload it, and if the work record is elaborated, there is no need to repeat this information.

**Comment by CarstenHoffmannMarburg** [comment]
Ok. How can I make it certain? Maybe @DenisNosnitsin1970 or @eu-genia have any idea? It is not satisfactory to have some ቀሌምንጦስ፡ in the incipit and no knowledge about, what person this is.

**Comment by eu-genia** [comment]
in the work record if you want you can of course add he isAttributedTo relation. please not in the manuscript. 

there is a lot that can be inserted in the work record, herewith what I have from Alessandro on the text


***
I Canoni dopo l’Ascensione - 30 canoni - CA
Manoscritti utilizzati: A(Bibliothèque Nationale (Paris), d’Abbadie 65 71r-76v); B(Staatsbibliothek zu Berlin, Preussischer Kulturbesitz, Orientabteilung (Berlin), Ms. orient. Fol. 398 94v-100v); C(Staatsbibliothek zu Berlin, Preussischer Kulturbesitz, Orientabteilung (Berlin), Ms. orient. Fol. 398 105r-113r); D(EMML 1933 84r-90v); E(EMML 1843 63r-69v); F(EMML 2430 43r-46v); G(British Library (London), Or. 796 63r-68r); H(British Library (London), Or. 481 179v-181r); J(EMML 6522 56v-60r); L(British Library (London), Or. 794  71v-77v); M(British Library (London), Or. 795 51v-54v); N(British Library (London), Or. 793 43r-45v); **O(Biblioteca Medicea Laurenziana (Firenze), Or. 148 5r-14r**); P(Bibliothèque Nationale (Paris), Zotenberg 121 [Éth. 95] 41v-45v); Q(EMML 6955 74v-79r); R(Biblioteca Apostolica Vaticana, Borgiano etiopico 2 56r-62r); S(Ṭānāsee 29, Kebrān 29 49v-53v); Y(EMML 3515 28v-32v); Z(EMML 7030 38v-43r); g(BMW(Or) 796 39r-44r).
Bibliografia: Vs di alcuni canoni in MDLeonessa (1932) dal Borgiano etiopico 2, e precisamente: [1] p. 389, [2] p. 236, [3] p. 215, [4] pp. 215-7, [5] p. 329, [8-11] pp. 219-221, [12] p. 469, [13-8] pp. 405-7, [19] p. 251, [20] pp. 427-9, [21] p. 287, [23-4] pp. 333-5, [25] pp. 309-11, [26] p. 35, [27-8] pp. 453-5, [30] pp. 409-11; Vs dei ca-noni [2] e [10] in Getatchew (1988) 236 e 238 dal ms. R. CA fa esplicita menzione della sezione A2 (detta Baṭelsāt).
Sul testo arabo: Tx inedito; Vs parziale dell’introduzione e di parte dell’epilogo in Riedel (1900) 159-164; Wansleben (1677) 239-241; Riedel (1900) 165; Nau (1905) 1618-1619; GCAL vol. I, 578-580; Darblade (1946) 51-53; Meinardus (1961-62) 233; Nasrallah (1979-88) vol. II, tomo ii, 197-198. Si tratta di canoni di origine si-curamente melchita, probabilmente inseriti successivamente alla più antica raccolta, ma già nel sec. VIII, e figu-rano costantemente nei mss. del sec. XIII, Nasrallah (1979-88) vol. II, tomo ii, 189-190. Il testo è tra le fonti del Fetḥa Nagast dove è introdotto dalla sigla "‘ayn" (FetNagast Vs 10).

**Comment by eu-genia** [comment]
Of course the traditional attribution of most of these texts (just like of the Qalemǝnṭos LIT1957Mashaf) is to Clement of Rome, disciple of Peter but the alleged author is probably more correctly referred to as Pseudo-Clement so I am actually not sure, I would rather
(1) create a Pseudo-Clement
(2) associate Clement I and Pseudo-Clement through a relation
(3) associate the texts to this new Pseudo-Clement

@abausi any suggestions?

**Comment by eu-genia** [comment]
I posted my suggestion above.

It is to create a record for Pseudo-Clement / Qalemǝnṭos disciple of Peter and link to him. There are two independent attributions: the Senodos and the Book of Clement being attributed to Clement Disciple of Peter and another one associating this latter with the Pope. Let us keep the two apart. In this case you do not need uncertainty at all. The work is CERTAINLY attributed to a certain Clement. 
  
Please do not add descriptions of works or bibliography on works to the manuscript record.

The Senodos has been edited by A. Bausi

**Comment by abausi** [comment]
This text is published: please, have a look at my 1995 CSCO edition and to my article ‘Alcune considerazioni sul «Sēnodos» etiopico’, Rassegna di Studi Etiopici, 34 (pub. 1992) (1990), 5–73.
A fitting label is "Pseudo-Apostolic literature"; "Pseudo-Clement"can go, but it is often taken in a narrower meaning, to definte the "Recognitiones", "Homiliae", and related literature.

**Comment by eu-genia** [comment]
I understand that @CarstenHoffmannMarburg wants to encode all he can, so he wanted to mark up the word ቀሌምንጦስ፡ by linking him to `PRS3129Clement`, my objection was to not insert such a link and create another record for this ቀሌምንጦስ፡ if necessary. We can then call him simply Qalemǝnṭos the attributed author, who may have relation to Pseudo-Clement and may have relation to Clement I in some sense.

**Comment by CarstenHoffmannMarburg** [comment]
I understand the reasons not to encode this name or other names of persons and places in manuscript records and I may keep it shorter in the future. The suggestion by Eugenia came in parallel to my latest post and I have seen it later. Not all texts, that are attributed to Clement, may be from the same Pseudo-Clement. If we create a PRS-ID "Pseudo-Clement" it might be neccessary to create a new "Pseudo-Clement" for any new case, when a text is attributed to Clement. Yet alone in the Senodos, the name Clement appears several times. Do we need a new "Pseudo-Clement"-ID for every of these or will we take it to be from the same? It may be better to explain it more explicitely in a note in the work record, that it is doubtful or even impossible, that Clement of Rome authored this work.

**Comment by CarstenHoffmannMarburg** [comment]
I obstained from encoding any Clement to the work record and to the manuscript record, since this seems to be ambivalent and does not seem to be necessary.

**Comment by eu-genia** [comment]
OK for not marking up.

My suggestion would be to treat persons the same way we treat works and in some cases resort to a very general record to a general pseudo-Clement, as, while being different, they all still claim to be the same pope, though at different times and at different contexts, and eventually explain it inside the record. The main thing is to keep the pseudo(s) apart from the real historical person.
