### ISSUE TITLE
A suggestion to delete LIT2631Zenahu

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2392]
So, https://betamasaheft.eu/works/LIT2631Zenahu/main was inherited from the index to EAe, specifically Witakowski's article in vol. 4, p. 948b.

Now, I've checked the mss he quotes and it is clear to me that no such work as autonomous vita of Theophilus ("ዜናሁ፡ ለቴዎፍሎስ") has ever existed in Ethiopia, instead in both mss. mentioned by Witakowski we have this https://betamasaheft.eu/works/LIT2630Zenahu/main (also could be referred to as LIT3309Qerellos#VitaOfCyril).

Therefore, if you agree I would delete LIT2631Zenahu and modify LIT2630Zenahu.

@eu-genia @DenisNosnitsin1970 @CarstenHoffmannMarburg

**Comment by eu-genia** [comment]
wonderful, thank you, would be great
