### ISSUE TITLE
Links given in corresp do not display

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2393]
I vaguely remember we already had this discussion but I cannot find it now...

For example here: https://betamasaheft.eu/works/LIT5856Homiliary/main the links which I encoded like that do not display. 
![Zrzut ekranu 2023-06-24 002019](https://github.com/BetaMasaheft/Documentation/assets/62760230/0a6354e7-1461-4bd4-a7af-f201dfc378e8)

This is the way which is in the guidelines (cf example 7 https://betamasaheft.eu/Guidelines/?q=external&id=work-teiHeader) .

@eu-genia

**Comment by eu-genia** [comment]
there is nothing to display as you provided no text to display
for external links you need some text, the app cannot guess the shelfmark if it is not in our system,
