### ISSUE TITLE
A problem with PRS13651Nathanael

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2394]
This does not work: https://betamasaheft.eu/persons/PRS13651Nathanael/main @eu-genia

**Comment by eu-genia** [comment]
of course it does not, the file exists twice in the app, once in the `new `folder and once in the numbered folder

```
Something has gone wrong and there are more than one item with id PRS13651Nathanael.

/db/apps/expanded/persons/PRS13001-14000/PRS13651Nathanael.xml
/db/apps/expanded/persons/new/PRS13651Nathanael.xml

```
I have deleted the one in the `new `folder

**Comment by eu-genia** [comment]
It seems that this https://github.com/BetaMasaheft/Persons/commit/e709145e1b98a4940911a891997c908147592db5 and https://github.com/BetaMasaheft/Persons/commit/32d216dd8903b6ae44a85b6e51a35823274fb115 did not fully go through - the files were created in the numbered folder but not removed from the new folder, updated manually
