### ISSUE TITLE
Deletion does not go through - any suggestions?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2395]
Recently I've made some deletions but they are still visible in the app (the files are not in my GitHub folder, I've checked).

Am I doing sth wrong?

https://betamasaheft.eu/works/LIT2631Zenahu/main
https://betamasaheft.eu/works/LIT1270Dersan/main
https://betamasaheft.eu/works/LIT1472GadlaL/main

@eu-genia

**Comment by eu-genia** [comment]
some webhooks did not make it through to the app

**Comment by eu-genia** [comment]
deleted manually, please do let me know if you discover more to fix, seems that not all deletions make it (you are doing everything right)
