### ISSUE TITLE
New Mastabqʷǝʿ za-Māryām according to Leonard Bahr

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2398]
@DenisNosnitsin1970 @thea-m @LeonardBahr 

Leonard Bahr wrote on july, 10th on Mastabqwəʿ:

"Gebet 1, was ich in meiner MA Mastabqʷǝʿ za-Māryām (ʾƎgziʾabǝḥer ʾƎgziʾo) nenne und Mastabqʷǝʿ za-Māryām I abkürze Incipit: እግዚአብሔር፡ እግዚኦ፡ Explicit: ስማዕ፡ ጸሎተ፡ ኵሉ፡ ዘሥጋ፡ በእንተ፡ ማርያም፡ ምልእተ፡ ጸጋ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም፡ አሜን።

HSS: AKM-009, 17th century, fols 31ra17–31vb1 BL Or. 545, 17th century, fols 14vb4–15ra13 BnF Éth. d’Abb. 13, 17th century, fols 19rb3–19va17 EMML 1434, 17th century, fols 18rb9–18va14 EMML 4190, 17th century, fols 22rb14–23ra6 Weitere Infos: Dieses Gebet wird Mastabqʷǝʿ za-Māryām in BL Or. 545 genannt. Am Rand findet sich noch die Angabe: ጸሎት፡ ዘእግዝእትነ፡ ማርያም፡ ዘወትር።. Auch in Druckausgaben des Messbuchs wird es Mastabqʷǝʿ za-Māryām genannt."

"Gebet 2, was ich Mastabqʷǝʿ za-Māryām (wa-kāʿba nāstabaqqʷǝʿā la-nǝgǝśta kʷǝllǝna) nenne und Mastabqʷǝʿ za-Māryām II abkürze

Incipit: ወካዕበ፡ ናስተበቍዓ፡ ለንግሥተ፡ ኵልነ፡ Explicit: በምድር፡ ወበሰማያት፡ በባሕር፡ ወበቀላያት፡ ለዓለመ፡ ዓለም፡ አሜን። HSS: AKM-009, 17th century, fols 31vb2–32ra19 BL Oriental 545, 17th century, fols 15ra13–15rc19 BnF Éth. d’Abb. 13, 17th century, fols 19va17–20ra4 EMML 1434, 17th century, fols 18va15–18vb15 EMML 4190, 17th century, fols 23va8–24ra9 Weitere Infos: Es ist möglich, dass das vorliegende Gebet, Mastabqʷǝʿ za-Māryām II, in der Überschrift und Randbemerkung für Mastabqʷǝʿ za-Māryām I in BL Or. 545 mitgemeint ist. In Druckausgaben des Messbuchs folgt es dem vorherigen Gebet und wird ዓዲ፡ ʿādi genannt (im Sinne ዓዲ፡ መስተብቍዕ፡ ዘማርያም፡)."

"Gebet 3, was ich Mastabqʷǝʿ za-Māryām (wa-kāʿba nāstabaqqʷǝʿā la-naqʿa ḥǝywat) nenne und Mastabqʷǝʿ za-Māryām III abkürze Incipit: ወካዕበ፡ ናስተበቍዓ፡ ለነቅዐ፡ ሕይወት፡ Explicit: በምድር፡ ወበሰማያት፡ በባሕር፡ ወበቀላያት፡ ለዓለመ፡ ዓለም፡ አሜን። HSS: EMML 2969, 20th century, fols 14va17–15ra13 Ms. orient. oct. 993, 18th century, fols 49va15–50ra7 EMML 1206, 19th century, fols 140rb1–19 Edition des altäthiopischen Textes und amharische Übersetzung: Getatchew Haile 2004. ደቂቀ እስጢፋኖስ, “በሕግ አምላክ”, (ትርጕም) (Daqiqa ʾƎsṭifānos, “Ba-ḥǝgg ʾamlāk”, (Tǝrgwǝm) ‘The Stephanites, “By the Commandment of God”, (Translation)’) (Collegeville, MN: n.pub., 2004), 36–38.

Weitere Infos: Dieses Gebet wird in EMML 1206 መስተብቍዕ፡ አዋልድ፡ ዘኢተዐውቀ፡ ደራሲሁ። ‘Apocryphal mastabqʷǝʿ, of which the author is unknown.’ genannt."

"Der Grund, warum sie differenziert werden könnten: Meines Wissens (impliziert evtl. mangelne Kompetenz auf BM erfolgreich zu suchen) gibt es eine übergeordnete ID für die Suffragien (= CAe 4711 Mastabqʷǝʿān), aber noch keine IDs für die einzelnen Suffragien mit Ausnahme von CAe 4346 Prayer for those who sleep. Diese drei Gebete (und auch Mastabqʷǝʿ za-Masqal) kommen aber auch einzeln und in kleineren Gruppen in Handschriften vor, also rausgelöst aus der größeren Einheit."

"P.S. (aber erstmal unwichtig): Wir könnten auch Informationen zur bestehenden ID von Mastabqʷǝʿ za-Masqal hinzufügen, vgl.: https://betamasaheft.eu/works/LIT4713Liton/main. Ich finde keine Angabe zu Incipit und Explicit auf dieser Webseite. Incipit: ወካዕበ፡ ናስተበቍዖ፡ ለዕፀ፡ ቅዱስ፡ መስቀል፡ Explicit: ለእሉ፡ ክልኤ፡ ፍጡራን፡ ስብሐተ፡ ፈጣሪ፡ ይደልዎሙ፡ እስመ፡ ተዐረዩ፡ በክብሮሙ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም፡ አሜን። Es gibt drei ältere als die dort angegebenen HSS: AKM-009, 17th century, fols 32rb1–33ra10 AM-007, 18th century, fols 21vb19–22va2 EMML 4190, 17th century, fols 44vb1–46ra9

Ich finde keine Angabe zu Edition. Edition des altäthiopischen Textes und amharische Übersetzung: Getatchew Haile 2004. ደቂቀ እስጢፋኖስ, “በሕግ አምላክ”, (ትርጕም) (Daqiqa ʾƎsṭifānos, “Ba-ḥǝgg ʾamlāk”, (Tǝrgwǝm) ‘The Stephanites, “By the Commandment of God”, (Translation)’) (Collegeville, MN: n.pub., 2004), 38–41. Weitere Infos: In den Druckausgaben des Messbuchs wird es Mastabqʷǝʿ za-Masqal und in einer in Asmara gedruckten Ausgabe Mastabqʷǝʿ za-Madḫane ʿālam genannt. Die Angabe auf BM mit „Liṭon za-masqal“, die zur Folge hat, dass es als Liṭon und nicht als Mastabqʷǝʿ gezählt wird, scheint mir aber auf einer Handschrift zu basieren und muss man fürs Erste wohl so belassen. Die drei älteren Handschriften haben leider keinen Titel. Vielleicht kann man den Text aber neben der übergeordneten Liṭongruppe auch der übergeordneten Mastabqʷǝʿ Gruppe zuweisen?"

**Comment by CarstenHoffmannMarburg** [comment]
I opened the record of LIT4713Liton and I can see indeed an incipit encoded as a div and it should be:
```
<div type="edition">
            <div type="textpart" subtype="incipit" xml:lang="gez" xml:id="Incipit">
                <ab>
                    ወካዕበ፡ ናስተበቍዖ፡ ለዕፀ፡ መስቀል፡ ቅዱስ፡ ጽኑአ፡ ሥልጣን፡ ወኃይል፡
                </ab>
            </div>
        </div>```

I do not understand either, why this is not displayed on the BM-website.

I will add the explicit and the bibliographical information in a minute.

**Comment by CarstenHoffmannMarburg** [comment]
I do not find any indication on manuscripts in the oxygen record of LIT4713Liton. I think, this relation is supposed to be established, when the manuscript in question is recorded more precisely.

**Comment by CarstenHoffmannMarburg** [comment]
> In den Druckausgaben des Messbuchs wird es Mastabqʷǝʿ za-Masqal und in einer in Asmara gedruckten Ausgabe Mastabqʷǝʿ za-Madḫane ʿālam genannt. Die Angabe auf BM mit „Liṭon za-masqal“, die zur Folge hat, dass es als Liṭon und nicht als Mastabqʷǝʿ gezählt wird, scheint mir aber auf einer Handschrift zu basieren und muss man fürs Erste wohl so belassen. Die drei älteren Handschriften haben leider keinen Titel. Vielleicht kann man den Text aber neben der übergeordneten Liṭongruppe auch der übergeordneten Mastabqʷǝʿ Gruppe zuweisen?

I would rather prefer to decide for a consistend terminology either as Mastabqʷǝʿ or Liṭon and to add the parallel titles in the title statement.

**Comment by CarstenHoffmannMarburg** [comment]
>Gibt es einen Standard oder eine Faustregel für die Anzahl der Wörter bei Incipit und Explicit? Falls es Dir nicht ausreicht oder zu lang ist, kann ich Dir gerne in einer anderen Mail die kurzen Texte zum Drüberschauen schicken.

We agreed just very recently to extend incipits and explicits to not more than 20 to 30 words. I think your suggestions perfectly meet this premise.

**Comment by DenisNosnitsin1970** [comment]
I found some cases of the use of LIT4713Liton. I do not know why they do not appear in the database, may be encoding problems. But searching with Oxygen, I found records EMIP03243, BAVet108, LIT3188. Please check. The source of the record may be BAVet108, the cataloguer quoted what was in the catalogue. I remember vaguely that smth like this was edited by Getatchew.

**Comment by LeonardBahr** [comment]
Dear all,

Thank you for your help in opening this issue for me and commenting upon it. First, I would like to repeat the main aim of my request, which is: To add CAe IDs for three Marian prayers that bear the name Mastabqʷǝʿ based on the information I provided above in a mail to Dorothea (My apologies that it is partly written in German).

@CarstenHoffmannMarburg 
- Yes, here are longer incipits:
እግዚአብሔር፡ እግዚኦ፡ ኢየሱስ፡ ክርስቶስ፡ አምላክነ፡ ዘትቤሎ፡ ለፍቁርከ፡ ዮሐንስ፡ እንዘ፡ ሀሎከ፡ ዲበ፡ ዕፀ፡ መስቀል፡ ቅዱስ፡
or, if you want even more
እግዚአብሔር፡ እግዚኦ፡ ኢየሱስ፡ ክርስቶስ፡ አምላክነ፡ ዘትቤሎ፡ ለፍቁርከ፡ ዮሐንስ፡ እንዘ፡ ሀሎከ፡ ዲበ፡ ዕፀ፡ መስቀል፡ ቅዱስ፡ ወትቤላ፡ ለማርያም፡ ነዋ፡ ወልድኪ፡ ወለረድእከኒ፡ ነያ፡ እምከ፡

ወካዕበ፡ ናስተበቍዓ፡ ለንግሥተ፡ ኵልነ፡ ማርያም፡ እምነ፡ ወእሙ፡ ለእግዚእነ፡ ወመድኀኒነ፡ ኢየሱስ፡ ክርስቶስ፡
or, if you want more
ወካዕበ፡ ናስተበቍዓ፡ ለንግሥተ፡ ኵልነ፡ ማርያም፡ እምነ፡ ወእሙ፡ ለእግዚእነ፡ ወመድኀኒነ፡ ኢየሱስ፡ ክርስቶስ፡ ንስእል፡ ወነኀሥሥ፡ ናስተበቍዕ፡ ወንዌድስ፡ ዕበየ፡ ተአምሪሃ፡ ብዙኀ፡ ለእመ፡ ጸባኦት፡ ንጉሥ፡

ወካዕበ፡ ናስተበቍዓ፡ ለነቅዐ፡ ሕይወት፡ ለቅድስት፡ ደብተራ፡ ዘወለደት፡ ወአግመረት፡ ጵርስፎራ፡
or, if you want more
ወካዕበ፡ ናስተበቍዓ፡ ለነቅዐ፡ ሕይወት፡ ለቅድስት፡ ደብተራ፡ ዘወለደት፡ ወአግመረት፡ ጵርስፎራ፡ ይትነከር፡ ዕበየ፡ ክብራ፡ ጊዜ፡ ይትነበብ፡ ተአምራ፡ ጽልሕወ፡ ልብ፡ ብእሲ፡ ሥጋ፡ ቢጹ፡ ዘበልዐ፡

And also for the Supplication of the Cross (CAe 4713)
ወካዕበ፡ ናስተበቍዖ፡ ለዕፀ፡ ቅዱስ፡ መስቀል፡ ጽኑዐ፡ ሥልጣን፡ ወኀይል፡ ወሊሉየ፡ መልክእ፡ ወአካል፡ እመልክአ፡ በትሩ፡ ለአሮን፡ ካህነ፡ ጽላሎት፡ ወአምሳል፡

- I think on LIT4713Liton nothing has been changed yet.
- Yes, those are other hymns, respectively, if I am right, excerpts from መዋሥእት (a liturgical text), ውዳሴ ማርያም for Friday and Tuesday, and ይዌድስዋ መላእክት (the latter of which appears both in Horologia and Psalter MSS).

@DenisNosnitsin1970 

- Yes, the edition and translation by Getatchew Haile is mentioned above.
- Yes, I will check the catalogue(s). (Unfortunately, the images of the MSS are not available.)

**Comment by CarstenHoffmannMarburg** [comment]
For EMIP03243 and BAVet108, I can find no images. I don't know, how to check and what could I check except for the incipit and explicit? 


> I found some cases of the use of LIT4713Liton. I do not know why they do not appear in the database, may be encoding problems. But searching with Oxygen, I found records EMIP03243, BAVet108, LIT3188. Please check. The source of the record may be BAVet108, the cataloguer quoted what was in the catalogue. I remember vaguely that smth like this was edited by Getatchew.

**Comment by LeonardBahr** [comment]
Dear all, dear Carsten,

hopefullly you are fine. 

1) Again, my request: We would need specific CAe IDs for the above three Marian prayers. They should be connected to the general CAe ID of _Mastabqʷǝʿān_: CAe 4711 (cf. https://betamasaheft.eu/works/LIT4711Mastabqwe/main). I see the full text have been entered in the TEI/XML file, but there are no specific IDs subgrouped under CAe 4711. If you would like to, you can check, as a model, the general ID of the Liṭon prayers with the specific IDs of each prayer listed thereunder: https://betamasaheft.eu/works/LIT4860Litanies/main.

2) There is one exception where the full text has not yet been entered in the TEI/XML of CAe 4711, which is _Mastabqʷǝʿ za-Māryām (wa-kāʿba nāstabaqqʷǝʿā la-naqʿa ḥǝywat)_. It would be helpful if the full text could be added to the file. The full text is:
ወካዕበ፡ ናስተበቍዓ፡ ለነቅዐ፡ ሕይወት፡ ለቅድስት፡ ደብተራ፡ ዘወለደት፡ ወአግመረት፡ ጵርስፎራ፡ ይትነከር፡ ዕበየ፡ ክብራ፡ ጊዜ፡ ይትነበብ፡ ተአምራ፡ ጽልሕወ፡ ልብ፡ ብእሲ፡ ሥጋ፡ ቢጹ፡ ዘበልዐ፡ ስመ፡ ማርያም፡ ዘጸውዐ፡ በሕፍነ፡ ማይ፡ ቈሪር፡ መንግሥተ፡ ሰማያት፡ ቦአ፡ ሰሚዐክሙ፡ አንክሩ፡ ዜና፡ ዝክራ፡ አፍቅሩ፡ መንግሥተ፡ ዚአሃ፡ ተዘከሩ፡ ዘኵሎ፡ ታድኅን፡ እግዝእትነ፡ ማርያም። ንዑ፡ ንስግድ፡ ወንግነይ፡ ለንግሣ፡ ዘጾረት፡ ወአግመረት፡ በከርሣ፡ እግዚአ፡ ሰማያት፡ ወምድር፡ መስተስርየ፡ ኀጢአት፡ ወአበሳ። እንዘ፡ ኢትሌሊ፡ ባዕላየ፡ ወኢትሜንን፡ ነዳየ። ማርያምሰ፡ ታፈቅር፡ ዘይገብር፡ ሠናየ። ዛቲ፡ ይእቲ፡ እኅተ፡ መላእክት፡ ትጉሃን። ወለተ፡ ኄራን፡ ነቢያት፡ ብዕሎሙ፡ ለሐዋርያት፡ ሞገሰ፡ ጻድቃን፡ ወሰማዕት፡ ላቲ፡ ይደሉ፡ ክብር፡ ወስብሐት፡ ዘምስለ፡ ወልዳ፡ አምልኮ፡ ወስግደት፡ በምድር፡ ወበሰማያት፡ በባሕር፡ ወበቀላያት፡ ለዓለመ፡ ዓለም፡ አሜን።

3) Finally, we talked about the incipit and explicit and I see they have been added to _Liṭon za-masqal_ (CAe 4713). But these cannot be found in the files of the other Liṭon prayers. In each file of these, the whole prayer has been written out. Thus, I would opt for a consistent solution: Either we use include the whole prayer in each file or merely the incipit and explicit. What do you think? What the usual way of doing that in BM? Of course, we can also add both, but it should be consistent. The texts are rather short, so personally I think we could write down the whole prayer. Just in case you agree, here it is:
ወካዕበ፡ ናስተበቍዖ፡ ለዕፀ፡ ቅዱስ፡ መስቀል፡ ጽኑዐ፡ ሥልጣን፡ ወኃይል፡ ወሊሉየ፡ መልክዕ፡ ወአምሳል፡ እመልክዓ፡ በትሩ፡ ለአሮን፡ ካህነ፡ ጽሎላት፡ ወአምሳል፡ በትረ፡ አሮንሰ፡ ዘሠረፀት፡ ወፈረየት፡ ከርካዐ፡ ዘእንበለ፡ ተክል፡ እንዘ፡ ትቀውም፡ በአፍአ፡ ኢያድኃነት፡ ጻድቀ፡ ወኢቤዘወት፡ ኃጥአ፡ እስመ፡ አልባቲ፡ ክሂል፡ ወኢመዊዐ፡ መስቀለ፡ ክርስቶስሰ፡ ቤዛነ፡ ወኃይልነ፡ አግዓዘ፡ ጻድቃነ፡ ወኃጥአነ፡ እምግብርናተ፡ ሰይጣን፡ ጸላኢነ፡ ነሢኦ፡ ሥልጣነ፡ እምኀበ፡ እግዚአብሔር፡ አምላክነ። ይ፡ ዲ፡ ጸልዩ፡ ቅድመ፡ መስቀል፡ ኵልክሙ፡ መሃይማናን፡ እንዘ፡ ትእኅዝዎ፡ በየማን፡ ወትክሕድዎ፡ ለሰይጣን፡ እስመ፡ ተቀደሰ፡ በደመ፡ ክርስቶስ፡ መድኅን። ይ፡ ሕ፡ ክቡር፡ አንተ፡ ንጉሠ፡ ዕፀዋት፡ መስቀል፡ ወክቡር፡ አንተ፡ ዕፀ፡ መስቀል፡ ወክቡር፡ ዘተቀደስከ፡ በደመ፡ ክርስቶስ፡ ቃል። ይ፡ ካ፡ ለክብረ፡ ዝንቱ፡ መስቀል፡ ክርስቶሳውያን፡ ንሰግድ፡ በፍርሃት፡ ወበረዓድ፡ ኪያሁ፡ ፈጣሪ፡ ህላዌ፡ ወልድ፡ እስመ፡ ቀደሶ፡ በደሙ፡ ወአኮ፡ በደመ፡ በዕድ፡ መልዕልተ፡ ዝንቱ፡ መስቀል፡ አመ፡ ሞተ፡ መለኮት፡ በትስብእቱ፡ ትስብእትሰ፡ እመለኮቱ፡ ኢተፈልጠ፡ ወኢተቶስሐ፡ ቦቱ፡ በበትረ፡ ዝንቱ፡ መስቀል፡ ሐዋርያቲሁ፡ ለዘሞተ፡ እንዘ፡ ይገብሩ፡ መንክራተ፡ ሰደዱ፡ አጋንንተ፡ ወሰበሩ፡ ጣዖታተ፡ በእንተ፡ ዝንቱ፡ አዘዙ፡ መምህራነ፡ ቅዱስ፡ ወንጌል፡ አምሳለ፡ ፈጣሪ፡ ልዑል፡ ንስግድ፡ ለመስቀል፡ ወለማርያም፡ ድንግል፡ ለማርያምሰ፡ ዘንሰግድ፡ ላቲ፡ እስመ፡ ነሥአ፡ ሥጋ፡ እምሥጋሃ፡ እግዚአብሔር፡ ፈጣሪሃ፡ ወረከብነ፡ ንሕነ፡ መድኃኒተ፡ እምኔሃ፡ ለዕፀ፡ መስቀልሂ፡ ከመ፡ ተናገርነ፡ ቅድመ፡ ላዕሌሁ፡ አንጠብጠበ፡ ደመ፡ ቃል፡ ኢሐማሚ፡ በባሕርየ፡ ሥጋ፡ ዘሐመ፡ ለእሉ፡ ፪ቱ፡ ፍጡራን፡ ስብሐተ፡ ፈጣሪ፡ ይደልዎሙ፡ እስመ፡ ተዐረዩ፡ በክብሮሙ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም፡ አሜን።
