### ISSUE TITLE
Encoding a leporello from Luzern

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2401]
@GueshSol @thea-m @DenisNosnitsin1970 

Dörthe Führer from the library in Luzern sent us images from an Ethiopian manuscript with an email by the 12th of july in order to make it available on BM. The manuscript does not have a siglum yet, but this will be delivered soon by Dörthe Führer, when it has been decided. The leporello was a donation from the collection of Silvia and Walter Frei from Luzern. That is everything, what is known about the manuscript.

I am willing to try to encode this manuscript and to update the guidelines concerning leporellos, if neccessary. Alas I can't do it before fall, because I have a number of issues, that I want to settle before.

@eu-genia can you upload the images in the folder and meet the legal requirements if necessary?

**Comment by eu-genia** [comment]
I can surely do that but I do not have the images, the link has expired

**Comment by eu-genia** [comment]
Just to remind you: everything is possible if we have the images - which I do not have

**Comment by CarstenHoffmannMarburg** [comment]
Do you want me to make contact to Dörthe Führer again to receive the images once again?

**Comment by eu-genia** [comment]
I thought maybe you (or someone else) had downloaded them since you were interested and I was not there. If not I can contact her.

**Comment by CarstenHoffmannMarburg** [comment]
I did not download or safe any image.

**Comment by eu-genia** [comment]
I have converted the images and created a stub so that they can be visible and used, feel free to play. Leporello is a form already available in the schema.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you! If it is OK, I will turn to this task after having completed the records on Tanasee1, the Biblioteca Laurenziana (5 records left) and the Mastabqʷǝʿ za-Māryām according to Leonard Bahr (#2398). I guess that this will not be before december.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for creating a stub for the Lucerne leporello! I will try to work on it. There are a number of questions to be answered. The first one is quite obvious. How can we count the pages or openings? In the stub I found the unit of measure "leaf" and the number 12. Do we have other options, such as openings or pages as the basic unit? As far as I can see, there are three small and long leaves, tied together and folded into 27 pages, the first and last of which are attached to a wooden cover and blank. The back was unfortunately not photographed. Most likely the back was left blank as well. We can probably ask for photos of the back, or at least information on whether it is blank or has text or extras on it.

@eu-genia: Do you remember how the number of leaves = 12 came about? I do not understand how this number is calculated. I assume, the number comes from the library as does the information about the outer dimensions? 

I propose to take visible pages as the basic unit - this is 26, because the last one was attached to the wooden board in the end. These page number should be inserted to the images. At the moment, it is very confusing to see the various pictures on different pages.

For the number of leaves, I would explain in a note that three pieces of parchment are bound together with a leather thread or band. I could describe this in a binding desk and calculate 4 sewing stations, but this might be misleading because it is not the same as binding in a codex. For this reason I would prefer to explain it in a note without explicit markup.

<img width="938" alt="Screenshot 2023_Lucerne (1)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/b0da0d7c-31e8-404d-9545-6509f4896f48">
<img width="667" alt="Screenshot 2023_Lucerne (2)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/3c1d316f-a21c-4692-bb9c-68f7744ed358">
<img width="948" alt="Screenshot 2023_Lucerne (3)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/d500db6d-3749-4b7c-9032-0c35f85a5127">
<img width="918" alt="Screenshot 2023_Lucerne (4)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/da14635a-92a8-42ef-a547-97b79fbc957a">

**Comment by CarstenHoffmannMarburg** [comment]
In my opinion, the hand may be much older than 1800. The characters are long and slender. They may imitate the Gwəlḥ script of the Gondar period. I would rather define 1650 to 1900 on the basis of palaeography. I know that prayer books often look much older than they are, but this does not necessarily have to be the case.

**Comment by CarstenHoffmannMarburg** [comment]
For the content, I can affirm, that there are prayers, but I cannot identify any of them. 

The text starts with ቀንዋት፡ ትትአካዕ፡ ማዕከለ፡ ፈያት፡ ፪ቱ፡ አድኅነኒ፡ ክርስቶስ፡ እምፀብዐ፡ ዲያብሎስ፡ ወሠራዊቱ፡ ወእምክረ፡ ልሳን፡ ቀያያፋ፡ However, I suspect, that the initial words are missing. Every following stanza or prayer is introduced with ተማኅፀንኩ:

ተማኅፀንኩ፡ ስመ፡ በአናጋረከ፡ (with ደ expuncuated)
ተማኅፀንኩ፡ በአዕዳዊከ፡
ተማኅፀንኩ፡ ***ዲትከ፡ እሳተ፡ ርኅራኄ፡ ዘአንደዳ፡ ወታኅተ፡ መስቀል፡
ተማኅፀንኩ፡ በአፉከ፡ ምረረ፡ ሕሞት፡ ዘሰረበ፡ ወለልሳንከ፡ 
ተማኅፀንኩ፡ በጽንዓ፡ ሞት፡ **ተ፡ ዕፀ፡ መስቀል፡
ተማኅፀንኩ፡ ለበድነ፡ ሥጋከ፡ ዘአውረድዎ፡ እመስቀል፡
ተማኅፀንኩ፡ ለበመቃብረከ፡ መቃብረ፡ ነግድ፡ ወፈላሲ፡ አምሳለ፡ አባዊከ፡
ተማኅፀንኩ፡ በተንሣኤከ፡ ዘአድለቅለቀ፡ ዓለመ፡ በብርሃኑ፡

I cannot find correlations with existing prayers. What sources can I check, before I create new IDs? Should every prayer starting with ተማኅፀንኩ get its own ID in that case?

**Comment by thea-m** [comment]
@eu-genia I don't think it's our (admittedly not greatly documented) practice to use a general ID for asmat prayers as a rule. The general IDs (LIT6609ProtectPrayer and LIT5888AsmatPrayer) do exist and can be used, but they were created for the specific case that really no other information is available (https://github.com/BetaMasaheft/Documentation/issues/2076, and I believe LIT5888AsmatPrayer has some historical relation to EMIP). See also https://github.com/BetaMasaheft/Documentation/issues/371.
My experience has showed that in most scrolls, there are at least 1-2 prayers which can be identified with existing IDs. So I think that it makes sense, whenever we have a significant amount of text preserved, to create IDs.
