### ISSUE TITLE
Place name ሀንዳቤት (= LOC7316Andabet) in an addition in ms. Ṭānāsee 1.

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2406]
@Addisie @thea-m @DenisNosnitsin1970 @sologebre 

I found the place name ሀንዳቤት in an addition in ms. Ṭānāsee 1. It is supposed to be a name of a region or district, because it is meant to be ምድረ፡ እንተ፡ ስማ፡ ሀንዳቤት፡. I heard from @karljonaskarlsson, that @Addisie is working on a place called አንዳቤት in the Ṭānāsee region, what is a plausible setting for the content of the Additio are provisions for the memorial of King Yəsḥaq (Tazkāra Yəsḥaq). I think it is LOC7316Andabet, that is defined as being located in Bagamdər. In that case the record of LOC7316Andabet can probably receive some additional information.

Can anyone confirm, that the initial ሀ in Gəʿəz versus አ in Amharic is a typical phonetic shift? 

The text of the additio is like the following:

(...) አዕሎኩ፡ ዘንተ፡ መጽሐፈ፡ ውስተ፡ ዛቲ፡ ወንጌለ፡ ጸጋሁ፡ ለእግዚእነ፡ በ፷ወ፯፡ ዓመት፡ ምሕረት፡ ወበ፮፡ አውራኅ፡ እመ፡ ዋዕለ፡ መንግሥትየ፡ ወሀብኩ፡ ምድረ፡ እንተ፡ ስማ፡ ሀንዳቤት፡ እምጽንፋ፡ እስከ፡ ጽንፋ፡ ከመ፡ ትኩን፡ ለተዝካረ፡ ዚአየ፡ ወዐቃቤ፡ ተዝካርስ፡ አባ፡ ኖብ፡ ወልደ፡ ያስይ፡ ዘገሊላ። እንዘ፡ ሀሎ፡ በሕይወቱ፡ ወእምድኅረ፡ አዕረፈ፡ ደቂቀ፡ ወደቂቀ፡ ደቂቁ፡ ይግበሩ፡ ተዝካርየ፡ በይእቲ፡ ምድር፡ እንተ፡ ስማ፡ ሀንዳቤት። ወሀብካዎ፡ ከመ፡ ይኵክኖ፡ ርስተ፡ ሎቱ፡ ወለደቂቁ፡ እስከ፡ አመ፡ ምጽአቱ፡ ለእግዚእነ። ወኢይሠየም፡ እምባዕድ፡ ትውልድ፡ ውስተ፡ ይእቲ፡ ምድር፡ እንተ፡ ስማ፡ ሀንዳቤት፡ ዘእንለ፡ ውሉዱ፡ ለአባ፡ ኖብ። ወአጽሐፍኩ፡ ዘንተ፡ መጽሐፈ፡ አነ፡ ይስሐቅ፡ ወስመ፡ ምንግሥትየ፡ ገብረ፡ መስቀል።  እንዘ፡ ሊቀ፡ ጳጳሳት፡ አባ፡ ገብርኤል፡ ወእንዘ፡ ጳጳስነ፡ አባ፡ በርተሎሜዎስ፡ ወእንዘ፡ ቀሰ፡ ሐፄ፡ ባፀጋ፡ ቂርቆስ። ወእንዘ፡ ሊቀ፡ ዲያቆናት፡ ዮሴፍ፡ ወእንዘ፡ ኢቃቂታት፡ ገብረ፡ ክርስቶስ። ወእንዘ፡ ቀላባስ፡ ዘን፡ ሐሸ፡ ወእንዘ፡ ይቀመጻኔ፡ መዋዒ። ወእንዘ፡ መጌምድር፡ ድልመንገሣ፡ ወአፈ፡ መጌምድር፡ ይትአኰት፡ ስሙ፡ ወእንዘ፡ ሾብሕር፡ ዘናኔ፡ ወእንዝ፡ ስዩመ፡ ህንዳቤት፡ ብላንቱ። (...)

**Comment by CarstenHoffmannMarburg** [comment]
I found a facebook group to ʾAndābet, that may be connected to the town of ʾAndābet near Dabra Tābor in the Gondar region. https://www.facebook.com/groups/simachew/about
Do we have any possibility to locate this place more precisely and more reliable?

**Comment by Addisie** [comment]
Yes,  both of you are correct. I could understand from scholars ' work and traditional scholars ' explanations that the Geez ሀ commonly changed to አ by Amharic speakers or the Amharic አ commonly changed to ሀ by church scholars. 
Sure, it will be much better if LOC7316Andabet receives additional information.

**Comment by DenisNosnitsin1970** [comment]
Yes, ሀንዳቤት may well be Old Amharic for አንዳቤት,
