### ISSUE TITLE
PRS4285GabraKr was permanently deleted (PRS4285GabraKr)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2407]
@thea-m 

I was just looking up, whether there already an ID for Gabra Krəstos (active in 1321/1322). I did not find so far, but I found this phrase in the list of search results: "[PRS4285GabraKr was permanently deleted](https://betamasaheft.eu/persons/PRS4285GabraKr/main?hi=%22%E1%8C%88%E1%89%A5%E1%88%A8%E1%8D%A1%20%E1%8A%AD%E1%88%AD%E1%88%B5%E1%89%B6%E1%88%B5%E1%8D%A1%22) (PRS4285GabraKr)"

It appears to me, that this record has not been deleted enough!

**Comment by eu-genia** [comment]
This is the expected behaviour for deleted doublets merged with other records. If you follow the link to deleted records you will understand why.
