### ISSUE TITLE
New works BDLaethf25

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2409]
Here are some additions in BDLaethf25 that I cannot find in the existing records and that I think would deserve work records:

1. Incipit: <q xml:lang="gez"><seg part="I">በስመ <supplied reason="undefined">፡</supplied> አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ ሕማመ፡ ባርያ፡ ወለ<del rend="effaced">ያ</del>ጌዎን፡ </seg> አ<del rend="effaced">ሁ</del>ላሁ፡ <foreign xml:lang="am">ማቴ፡ አልመላክያው፡ ኑራተዊ፡ <del rend="effaced">ቋ</del>ቁራ፡ ስስምረጅ፡ ወመርመ፡ የፉሕሙ፡ የሽፋቴ፡</foreign>

2. Complete text: <q xml:lang="gez">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ። ፩ አምላክ፡ ያኢበያላሂሂን፡ አህቢሱ፡ ለአመትከ፡ እገሊት። ሃሱ፡ ለሃሱ፡ ለምሃ፡ ሸርሪ፡ ይትባረጹ፡ መባርቅት፡ ወነጐድ፡ ዘወጽአት፡ ትግባእ፡ ወዘርሕቀት፡ ትቅረብ፡ ሰማይኒ፡ የኢያጽልላ፡ አዝዊረከ፡ <del rend="overUnderlined">ነ</del>አዘዋዊረከ፡ አግብአ፡ ለአመትከ።

3. Complete text: <q xml:lang="gez">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡  አልሐጢን፡ አልሐጢን፡ አልሐን፡ በካዝዮን፡ ካፌር፡ ሰለባዊ፡ በዝ፡ አስማቲከ፡ ዘአሰርኮ፡ ለብርያል፡ በ፭፻፡ ፼፡ ሰናስለ፡ እሳት፡ ስብጉጥር፡ እሳት፡ ከማሁ፡ 
እስ፡ ለ፡ ከመ፡ ኢት፡ እም፡ ቤታ<add place="above">በ</add>፡ ሕ<add place="above">ይ</add>ወታ፡ እንዘ፡ ሐለት፡ ዘእንበለ፡ በሞት። ፯፡ ፯፡ ድግምለወሐ፡ ሎማ፡

4. This text has an almost perfect parallel in MS Dabra Dāmmo ʾAbuna ʾAragāwi, DD-045 (fol. 175r), but lacks a work record. Complete text: <q xml:lang="gez">በስመ፡ አብ፡ ወወልድ፡ ወመን፡ ፈስ፡ ቅዱስ፡ ፩ አምላክ፨ አክዮስ፡ አክዮስ፡ አክየ<sic>፡</sic> ሳዊ፡ ዶል፡ መር<del rend="strikethrough">ጌዮን</del>፡<add place="above">ጌዎን፡</add> ለቅሌማድ፡ መልአኩ፡ ለአርዌ፡ ምድር፡ አኀዝኩከ፡ ቀረጽ፡ በቀረጽ፡ አግአዚ፡ አርግዘና፡ ዘምሳና፡ ሙለዱ፡ ለከይሲ፡ ፈውሰ፡ ኩን፡ ለተመን፡ ፈውሰ፡ ኩን፡ ለአፍኦት፡ ፈውሰ፡ ኩን፡ በማቴዎስ፡ ፈውሰ፡ ኩን፡ በ<del rend="strikethrough">ም</del>ማርቆስ፡ ፈውሰ፡ ኩን፡ በሉ<sic>ቂ</sic>ስ፡ ፈውሰ፡ ኩን፡ በዮሐንስ፡ <del rend="strikethrough">ወ</del>በ፬ወ<add place="above">ን</add>ጌላውያን፡ ኅድግ፡ ይቤሉከ፡ አ<sic>ቡ</sic>፡ ወወልድ<supplied reason="undefined">፡</supplied>መንፈስ፡ ቅዱስ፡ ከመ፡ ይፃእ፡ ሕምዙ፡ ለከይሲ፡ በሐ<add place="above">ይ</add>ለ፡ መስቀሉ፡ ለእግዚኢነ፡ ኢየሱስ፡ ክርስቶስ፡ በከመ፡ ኀደጉሐዋርያት። ለእመ፡ ርሁቅ፡ ኣስትዮ፡ ላክደጊመከማይ፡

5. Complete text: <q xml:lang="gez">ጸሎት፡ በእንተ፡ ወሊያ፡ በዘ፡ ቂልያስ፡ ተራትሰ፡ ዘኖምያ፡ ፍታሕ፡ ማሕፀና፡ ለእመትከ፡ እገሊ፡ <del rend="overUnderlined">በማ</del>ይጻእ፡ <foreign xml:lang="am">ልጅ፡ ወእንግህ፡ ልጅ፡ በይማ፡ ድግም፡</foreign>

6. Complete text: <q xml:lang="am">ቀንጠፋ፡ የቁመኛ፡ ነው፡ ምስሪች<hi rend="rubric">፤</hi> ጊንዳ<hi rend="rubric">፤</hi>የቁራ፡ ስር<hi rend="rubric">፤</hi> አንዴል<hi rend="rubric">፨</hi>የምድር፡ ኵሂላ<hi rend="rubric">፨</hi> ሱር፡ በትሪ<hi rend="rubric">፨</hi> ደማይቶ<hi rend="rubric">፨</hi> ጥርጊና<add place="above">ፍን</add><hi rend="rubric">፨</hi> ዕ<del rend="strikethrough">ዕ</del>ፀ፡ ምናሄ<hi rend="rubric">፤</hi> አጋም፡ ስር<hi rend="rubric">፨</hi> አየ፡ ስር<hi rend="rubric">፨</hi>ኀቢጸሊም<hi rend="rubric">፤</hi> ገመሮ<hi rend="rubric">፨</hi> እንሰ፡ ላል<hi rend="rubric">፨</hi> ሰምዛ<hi rend="rubric">፨</hi> ነጭ<hi rend="rubric">፨</hi>ሽንጉርቲ<hi rend="rubric">፨</hi> ኦልቲት<hi rend="rubric">፨</hi> ይህነን<hi rend="rubric">፨</hi> ጨምሮ<hi rend="rubric">፨</hi> <del rend="strikethrough">ይዳ</del>ይዳ፡ በብር<hi rend="rubric">፨</hi>ቀለበት። ይምሶዋል<hi rend="rubric">፨</hi><hi rend="rubric">፨</hi>

7. Complete text: <q xml:lang="gez">ዝሀወት<hi rend="rubric">፨</hi> ዘአበረ፡ አጋዘ<hi rend="rubric">፨</hi> ለአበወሀ<hi rend="rubric">፨</hi> ወ<hi rend="rubric">=</hi>ሰሐበ<hi rend="rubric">፨</hi> ሙሐዘት<hi rend="rubric">፨</hi> አየአላፈ<hi rend="rubric">፨</hi> ወፀበላነ። <add place="above">የመጦሪ<hi rend="rubric">፨</hi><hi rend="rubric">፨</hi></add>

8. Complete text: <q xml:lang="gez"><hi rend="rubric">ሰሐል፡ ሰሐል፡ ሰሐል፡ ጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸጸ<del rend="strikethrough">ጸ</del>እዴየ፡ ሰሐል፡ ወየማንየ፡ አሕመላምል፡ ለጺሒፈ፡ ብርዕ፡ ወቀለም፡ ሊተ፡ ለገብርከ፡ አፍጌት፡ ወርኃ፡ ደቡብ፡ ወወርኃ፡ ደመና፡ <del rend="encircled strikethrough">አክሄል፡ ድሜሄላዊ፡</del> መንጥሔል፡ ድሜሄላዊ፡ በከመ፡ የሐውሩ፡ ፀሐይ፡ ወወርኅ፡ በፍጥረተ፡ ትእዛዝከ፡ ከማሆሙ፡ አሩፅ፡ የማነ፡ እዴየ፡ ለጋ፡ በስመ፡ <del rend="strikethrough">ለለ</del>ሎኤ፡ ኢላኤ፡ ኢላሄ፡ አሩፅ፡ እዴየ፡ ለገቢ<pb n="78r"/>ረ፡ ኵሉ፡ ተግባር፡ በሩፋኤል፡ ብርናዊ፡ በክሳብኤል፡ ዘ<del rend="strikethrough">ፈ</del>ያረውፃ፡ ለፀሐይ፡ ከማሁ፡ አሩፅ፡ እዴየ፡ ከመ፡ ይጠንቅቅ፡ ለአኂዘ፡ ብርዕ፡ ወእጽሐፍ፡ እበያቲከ፡ ዘእንበለ፡ ሐኬት፡ ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ አስተ፡ ፋጥን<supplied reason="undefined">፡</supplied>ወ<add place="above">አ</add>ስተ፡ ቃንዕ፡ ለገብርከ፡ በቀይ፡ ቀለም፡ <del rend="strikethrough">ወ</del>በወረቀት፡ ጸሐፍዕስር<supplied reason="undefined">፡</supplied>

**Comment by thea-m** [comment]
I also could not find records for these texts, please go ahead.
