### ISSUE TITLE
new records for salām-hymns

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2417]
I would like to create new records for the following works attested in BAVet166 (according to the catalogue), for which I could not find any correspondences:
1. Salām-hymn to Fāsiladas , incomplete at the end
incipit:    ሰላም፡ ለከ፡ ፍሡሕ፡ አዕይንት፡ እምወይን፡ ፋሲለደስ፡ ይሁዳ፡ አስናኒከኒ፡ እምኀሊብ፡ ጸዓዳ፡ ወገጽከ፡ ሕንባበ፡ ረዳ፤
explicit: ፋሲለደስ፡ ዜናከ፡ በጽሒፍ፡ እመ፡ ኢያግመሮ፡ ዓለም፡ `<gap reason="ellipsis"/>` ሰላም፨ ፋሲለደስ፡ ሰማዕት፡ ም
It does not seem to correspond to any parts of either LIT3004RepCh284 or LIT6638SalFasilKesadu
2. Salām-hymn to Mary, apparently also attested in the Saʿātāt (as in ESmhg010, do not have access to the edition right now, but will check before creating)
incipit:  ሰላም፡ ለኪ፡ ማርያም፡ ስብሕት፡ በአፈ፡ ኵሉ፡ ውስድት፡  ታቦት፡ አንቲ፡ ሙዳየ፡ ጽላት፡  ዘሕግ፡ ወዘሥርዓት።
3. Salām-hymn to Gabriel, also attested as stanza of LIT2762RepCh46, but apparently transmitted independently.
incipit: ሰላም፡ ለከ፡ ኀበ፡ ድንግል፡ ተፈናዊ፡ ሰላም፡ገብርሌ፡ ብስራታዊ፡ ሰላም፡ ዖፈ፡ እሳት፡ አርያማዊ፡

@CarstenHoffmannMarburg @smaugustine @eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any hints for correspondences in my searches either.
