### ISSUE TITLE
An ID for the collection of the Testaments of the Three Patriarchs

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2418]
Do we need an ID for the collection of testaments?
LIT1412GadlaA
LIT1510GadlaY
LIT1517GadlaY

and then a relation? (I do not think we have such ID at the moment)

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Works/pull/1022#discussion_r1298213548_

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 @thea-m @CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
Yes, the three works can be put together in a general ID "Testaments of the three Patriarchs" (= Testamente der drei Patriarchen). As far as I remember these three are mostly transmitted together and they depend on each other, unless the interdependancy of the three is, according to Heide, not fully solved yet. [Heide on uni-marburg.de](https://www.uni-marburg.de/de/cnms/semitistik/forschung/edition-und-uebersetzung-der-arabischen-und-aethiopischen-versionen-des-testaments-abrahams). I did not find any such overwhelming record in my searches either.

**Comment by MarcinKrawczuk** [comment]
Two examples of the three testaments in one volume:
Gunda Gunde - https://collections.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A12438#page/42/mode/1up
EMML 8812 - https://www.vhmml.org/readingRoom/view/201562

There is something of a joint title: ፍልሰቶሙ፡ ወፀዓቶሙ፡ ለአብርሃም፡ ወለይጽሐቅ፡ ወለያዕቆብ፡
