### ISSUE TITLE
more salām-hymns for BAVet166 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2419]
I would like to create new records for the following works attested in BAVet166 (according to the catalogue), for which I could not find any correspondences:

Salām-hymn to the apostles
incipit:   ሰላም፡ ለክሙ፡ ሐዋርያት፡ ለለ፩፡ ሰላም፡ መራሑተ፡ ጽድቅ፡ ለልዑል፡ ጸማዱ፡ ሰላም፡ አርድእተ፡ ዋሕድ፡
Salām-hymn to Takla Hāymānot, also attested in EMIP00480
incipit: ትርከበነ፡ ሰላምከ፡ እምኀበ፡ ፯ መንፈስ፡ ወሪዳ፡ እምላዕሉ፡ `<gap reason="ellipsis"/>`  ለተክለ፡ ሃይማኖትንብለከ፡ ሰርከ፡ ወነግሃ፡ ሰላመ፡

@CarstenHoffmannMarburg @smaugustine @eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any similar Salām either.
