### ISSUE TITLE
general statement on composite manuscripts in division

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2420]
Where would be an appropriate place in a composite manuscript to make a general statement about the division into codicological units which the description follows? (Something like "This description follows the catalogue..., according to the cataloguer, it is difficult to ascertain whether the different sections of the manuscript originally came from one or several manuscripts").
In history?
(I feel that we already discussed this question once, but couldn't find itnow)
@eu-genia @CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
From time to time, I too am uncertain about the composition of manuscripts. In these cases I have added a note to the entry "According to Marrassini ..." to absolve myself of any responsibility.

**Comment by thea-m** [comment]
Exactly, and this is the most logical approach. The question is where to insert this note in a composite manuscript. (For a non-composite manuscript, I feel that a note inside an msItem works, but with multiple msParts that solution does not seem very elegant). Maybe it could be put in `<history>`
