### ISSUE TITLE
Persons and Toponyms in an addition from emperor Naʿod in Tanasee1

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2421]
@thea-m @DenisNosnitsin1970 @eu-genia @sologebre 

I found many names in an addition in Tanasee1 on f. 4va. The short note states, that Emperor Naʿod (PRS7481NaodA) visited a town called ʾAtronsa ʾƏgziətəna Māryām, that I identified with LOC1602Atrons. 

According to Ernst Hammerschmidt, there are supposed to be "many more places" mentioned in this additio, but I cannot figure out any more place name. Instead, I see a lot of personal names of dignitaries, who joined the king. As far as I understand correct, there is aged Empress Eleni (PRS3706eleni) mentioned and a number of other people. 

I have not identified any of them, except for PRS11437GabraN and PRS11115FereKr in the end, for whom the identifications are quiet precarious. PRS11437GabraN was a Qasis already in Zarʾa Yāʿqobs time. He must have been very old, when he served Emperor Naod as well. Alternatively he could have counted the church utensils earlier together with PRS11115FereKr, if I understand this phrase correctly. PRS11115FereKr is attested in 1508 in Egypt. He may have travelled from Kebran to Egypt. Do you think it is appropriate to encode these identifications or is it too insecure? Should I give new IDs than?

May I make records for the other persons? Alas, I have difficulties to distinguish between names, functions and titles here. Here are my current interpretations:

- a person with the name እናቶ፡ ግራ፡, who carries the honorable title ያጼ (= ዓፄ)
- his wife (= በአልታ) with the name ናኦደ፡ ሞገሣ፡
- a person with the important court office of ዐቃቤ፡ ስዐት (= keeper of the hours / chancellor), and with the name ቴዎጎሎስ፡. It is a little bit curious to me, that ቴዎጎሎስ፡ can be name, but I found in my searches this as a name also in other manuscripts. Otherwise the person, who is the ዐቃቤ፡ ስዐት, is attributed to be a theologian and a ሊቀ፡ ሊቃውንት፡ (head of the priests) and is named ነገደ፡ እግዚኦ፡
- a person, who bears the honorary title ሊቀ፡ ሊቃውንት፡ (head of the priests) and has the name ነገደ፡ እግዚኦ፡. Curiously the name ኢያሱስ፡ is written above. So his true name might have been ነገደ፡ እግዚኦ፡ ኢያሱስ፡
- a person, who bears the title or function ሊቀ፡ ማእምራን፡ (chief of scholars) and has the name ኀብቱ፡ ጸራድ፡ or ኀብቱ፡ ጸራድ፡ ማስሬ፡ or ኀብቱ፡ ጸራድ፡ ማስሬ፡ አቀበስን፡. The meaning of ጸራድ፡, ማስሬ፡ and አቀበስን፡ is not clear to me.
- a person, who is a ቀይስ፡ (= priest) and who bears the title ሐፄ (= "sir", although I knew this title only for the emperors himself) and with the name ተክለ፡ ማርያም፡. Alternatively we speak about the previous emperor PRS9175TaklaMa, whose private priest was the aforementioned ኀብቱ፡ ጸራድ፡. There is also a scribe (PRS13110TaklaM) with this name from the 16th century, but I don't think, that this one is fitting here.
- a persons, whose name is ተከለ፡ ነቢያት and who hold office of being the ሊቀ፡ ደብተራ፡ (the head of the laymen).
- a person with the name ሐብተ፡ ማርያም፡ ግራ፡, who was previously a Bitwadded (ቀኚዕ፡ ብቶደደ)
- a person with the name ናዜ, who was a Bitwadded (military official) at this moment
- another or the same ተክለ፡ ማርያም፡ as mentioned above, who lived while the next person named ጌርሣም፡ had office as ንቡረ፡ ዕድ፡ .
- a person named ጌርሣም፡ had office as ንቡረ፡ ዕድ (leader of the abbots in a certain district)
- again the same or another person with the name ቲዎጎሎስ, who was a ንቡረ፡ ዕድ as well.
- a person with the name ገብረ፡ ናዝራዊ፡, who was a ቂስ፡ ገበዝ፡ (treasurer) and possibly PRS11437GabraN
- a person, whose name was ፍሬ፡ ክርስቶስ፡ or ማስራ፡ ፍሬ፡ ክርስቶስ፡ or ወራቍ፡ ማስራ፡ ፍሬ፡ ክርስቶስ፡, who had the title and function of a ሊቀ፡ ዲየቆን፡, and who is possibly PRS11115FereKr   

In case, you find, the persons are identifiable in a way, I sketched here, I would encode them with person IDs. If you find the interpretation of this passage too doubtful, I would obstain from it.

```
<div type="edition" corresp="#a8" xml:lang="gez">
                <ab>በመዋዕለ፡ ሉቃስ፡ ወንጌላዊ፡ በ<date calendar="qamar" when-custom="159" when="1507">፻፶ወ፱፡ አመተ፡ ምሕረት፡</date> እንዘ፡ 
                    ሀለዉ፡ ንጉሥነ፡ <persName ref="PRS7481NaodA">ናኦድ፡</persName> በ<placeName ref="LOC1602Atrons">አትሮንስ፡ እግዝእትነ፡ 
                    ማርያም፡</placeName> በወርኃ፡ መጋቢት፡ እንዘ፡ ስማዕት፡ 
                    ይእቴ፡ <persName ref="PRS3706eleni">እሌኒ፡</persName> ያጼ፡ <persName ref="PRS0000">እናቶ፡ ግራ፡</persName> በአልታ፡ 
                    <del rend="effaced" unit="chars" quantity="1"/> <persName ref="PRS0000">ናኦደ፡ ሞገሣ፡</persName> ዐቃቤ፡ 
                    <del rend="effaced">አካቅ፡</del> ስዐት፡ <persName ref="PRS0000">ቴዎጎሎስ፡</persName> ሊቀ፡ ሊቃውንት፡ 
                    <persName ref="PRS0000">ነገደ፡ እግዚኦ፡</persName><add place="above">ኢያሱስ፡ </add> ሊቀ፡ ማእምራን፡ 
                    <persName ref="PRS0000">ኀብቱ፡ ጸራድ፡ ማስሬ፡ አቀበስን፡</persName> ቀይስ፡ ሐፄ፡ 
                    <persName ref="PRS0000">ተክለ፡ ማርያም፡</persName> ሊቀ፡ ደብተራ፡ <persName ref="PRS0000">ተከለ፡ ነቢያት፡</persName>
                    ቀኚዕ፡ ብቶደደ፡ <persName ref="PRS0000">ሐብተ፡ ማርያም፡ ግራ፡</persName> ብቶደደ፡ <persName ref="PRS0000">ናዜ፡</persName> 
                    አዛዘ፡ እንዳዘዜ፡ ርእስ፡ ርኡሳን፡ <persName ref="PRS0000">ተከለ፡ ማርያም፡<persName ref="PRS0000"> እንዘ፡ ንቡረ፡ ዕድ፡ 
                    <persName ref="PRS0000">ጌርሣም፡</persName> ወምስለ፡ ንብርዕድ፡ <persName ref="PRS0000">ቲዎጎሎስ፡</persName> 
                    ወቂስ፡ ገበዝ፡ <persName cert="low" ref="PRS11437GabraN">ገብረ፡ ናዝራዊ፡</persName> ወሊቀ፡ ዲየቆን፡ ይፅናዩ፡ 
                     ወራቍ፡ ማስራ፡ <persName cert="low" ref="PRS11115FereKr">ፍሬ፡ ክርስቶስ፡</persName> ዘተመይጠ፡ ንዋይ፡ ለታቦተ፡ 
                    <repository ref="INS0357Kebran">ገብርኤል፡ ዘደብረ፡ ክብራ፡</repository> ፳ወ፫፡ ንዋየ፡ ቤተ፡ ክርስቲያን፡ </ab>
            </div>
```

**Comment by CarstenHoffmannMarburg** [comment]
It came to my mind, that it might be better to create new IDs for ገብረ፡ ናዝራዊ፡ and for ፍሬ፡ ክርስቶስ፡ and note a possible correspondence in the person record.

**Comment by CarstenHoffmannMarburg** [comment]
I have a similar problem with Tanśəʾa Krəstos, whose name appears in addition 9 on the next folio (5ra). By principal it is possible to state a correspondence of names and time either to PRS11538TanseaKr and to PRS11230TanseaK. Shall I neglect this correspondence or shall I add it as a note to the two person records?

**Comment by thea-m** [comment]
I don't know anything more than you ad hoc about these persons - I would say, if the identification with existing person records is only very dubious, create a new record and state the possible identity to the other record in a relations. To me, the identification of person names looks fine.

**Comment by DenisNosnitsin1970** [comment]
Some comments: እናቶ፡ ግራ፡ is unlikely a name; ቴዎጎሎስ may be a name - methatesis for ቴዎሎጎስ; ቀይስ፡ ሐፄ is the title, ራቍ፡ ማስራ፡ is a title. Strange that ናኦደ፡ ሞገሣ፡ is not there.

**Comment by CarstenHoffmannMarburg** [comment]
> Strange that ናኦደ፡ ሞገሣ፡ is not there.

Yes, I checked it again, and I found PRS7482NaodMo.

**Comment by CarstenHoffmannMarburg** [comment]
> I would say, if the identification with existing person records is only very dubious, create a new record and state the possible identity to the other record in a relations. 

Which kind of relation would you recommend? I found syriaca:possibly-identical, but I am not sure, whether we use syriaca-relations.

**Comment by CarstenHoffmannMarburg** [comment]
> We can use all relations, but indeed syriaca:possibly-identical should only be used between two works. Then probably dc:relation is the last resort.

I switched all files to dc:relation, but I think, this is not a perfect solution. Users may think, that two people are relatives or have any other relation to each other. Alas it happens very often, that identical names come to light and we are unable to identify them with certainty.

**Comment by thea-m** [comment]
In such cases (probably always when using the suboptimal dc:relation), it is especially useful to describe the relation verbally inside the element `<desc>` inside the relation
