### ISSUE TITLE
EMML 21 - images not available

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2422]
@eu-genia 
I just wanted to open images from EMML 18 and EMML 21, but they have not been shown to me within several minutes. The images are available, when I follow 'link to images'. But they are not available following 'Images'. It may be like that for all EMML manuscripts.

**Comment by eu-genia** [comment]
It is like that for all EMML manuscripts as you have to log in into the virtual reading room of HMML in order to be able to view the images there, they are not public (the registration is available to everyone though). Has nothing to do with us.

**Comment by eu-genia** [comment]
there was an error in the facs element, fixed now
