### ISSUE TITLE
Dating of BNFabb20 not correct

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2423]
@DenisNosnitsin1970 

I saw, that the origin of BNFabb20 is given with 1501-1600 in our description. But this is not correct. Having a look into the manuscript, the palaeographic style can be estimated much better to the 18th or early 19th centuries. The Dating 1501-1600 may have come through the information on gallica, that may have been taken automatically to the Beta maṣāḥəft website. I think it rests on the information in Abbadie's catalogue (Abbadie, A.: Catalogue raisonné de manuscrits éthiopiens, no. 20, p. 25). But Abbadie refers to the date of the translation of the given work (Tərgwāme Yoḥannəs in 3.) by ʾƏnbāqom but not to the date of the manuscript. I think the date in origin must be altered.
![Abbadie, A _Catalogue raisonné de manuscrits éthiopiens, S  25 (no  20)](https://github.com/BetaMasaheft/Documentation/assets/40291787/c6be3e4d-ebc5-4403-b305-42fc680a399b)

**Comment by DenisNosnitsin1970** [comment]
Yes, this is true, thank you for the information. I did not deal with this ms, but someone else. I will correct it.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you!
