### ISSUE TITLE
Texts from GG-018

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#2424]
Since @thea-m and I will use GG-018 for the summer school cataloguing exercises, it might be a good idea to have CAe entries for the four texts in the MS (which also would need person records).

Each gadl is for a single abbot of Gunda Gunde, conveniently in chronological order, following Mordini (1953):
8. Yəsḥaq (d. 1594)
9. ʾIyosāb (d. 1617)
10. Gabra Masiḥ Dāgəmāwi (d. 1644)
11. Sāmuʾel (d. 1650)

This can be expanded from my own notes:
- Yəsḥaq
  - Died on, and commemorated in the Synaxarium on, 24 Ḫədār
  - From the people of Desʾa, according to an addition on fol. 1r
  - According to the Synaxarium, he was born to the ʾIrob people in a place called Ḥaraze (these statements are not incompatible, since some of the ʾIrob came from Desʾa (cf. EAe))
- ʾIyosāb
  - Died on, and commemorated in the Synaxarium on, 22 Ḥamle (verified in gadl)
  - According to the gadl, he came from the people of Amhara
- Gabra Masiḥ Dāgəmāwi
  - Died on, and commemorated in the Synaxarium on, 10 Maskaram
  - According to the gadl (and the addition on fol. 1r) he was of the people of Wasamā (sp?) but born in the land of the ʾIrob
- Sāmuʾel
  - Died on, and commemorated in the Synaxarium on, 6 Yakkātit (verified in gadl)
  - According to the Synaxarium and the gadl, he came from the people of ʾIrob and was born there

Concerning GG-018 specifically, fol. Ir has a later ownership note of Abuna Gabra Masiḥ, probably the abbot Gabra Masiḥ Śāləsāwi (d. 1844). The petitions on fol. 16v and fol. 40v mention Za-māryām, a name also written in the upper margin on fol. 39r. Meanwhile, fol. 106r and fol. 136v have petitions for Walda Krəstos.

It would be worth investigating more closely whether the first two texts form a single production unit, but I am confident that the last two texts are each an independent unit. It seems as if the first two texts formed a single codicological unit at some point (if not being a single production unit) and the second two texts, produced separately, also formed a single codicological unit at another point and then later these were all combined into a single manuscript. Of course, other combinations could have been possible, it's hard to say for certain.

I also have in my notes that GG-120 is another witness to the same Gadla Yəsḥaq (ie not Yəsḥaq Śārāri or Yəsḥaq Mogasāwi but the 8th abbot), but the GG website is down right now so I can't check. Since that gadl is incomplete in GG-018 it might be worth taking a quick look.

**Comment by thea-m** [comment]
Thanks a lot!
I believe I found existing person and work records for Gabra Masiḥ II and his gadl: PRS4323GabraMa, LIT4779GadlaGM
ʾIyosāb seems to have a person record (PRS10448Yosab - has only been used in the record PRS4323GabraMa, but can be expanded).
I will create records for the other abbots and their gadlāt.

**Comment by thea-m** [comment]
There is also LIT4810GadlaYe for a Yəsḥaq (174 in Kinefe-Regb, there indicated as founder of Gunda Gunde, c. 1475). I think this is not our protagonist, but will refrain from creating a new record until confirmation.

**Comment by smaugustine** [comment]
> There is also LIT4810GadlaYe for a Yəsḥaq (174 in Kinefe-Regb, there indicated as founder of Gunda Gunde, c. 1475). I think this is not our protagonist, but will refrain from creating a new record until confirmation.

You are exactly right, the Yəsḥaq from Kinefe-Regb is Yəsḥaq "Śārāri", who had some foundational role but is not included in the traditional lists of abbots and lived a century before our Yəsḥaq.
