### ISSUE TITLE
ِAmharic transaction note with many names

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2429]
@DenisNosnitsin1970 @thea-m 

I found a note in an additio in Tanasee1 (#a18) on folio 85va-b. It appears to me to be a lot of names with some Amharic words in between. It may concern the transaction of people or land. Can you help me to identify some of the persons or places? I think the script is from the 18th or 19th century, judged from the palaeography. The presumed dating (ዘዮሐንስ፡ ቃል፡ በ፯፻፡በ፲፰፡ = das Wort von John, im Jahr 700, im Jahr 18) is difficult to transfer to a modern dating. The reading might be wrong, because 718 does not fit in any cycle or calendaric system.

ይቤሉ፡ ሰብአ፡ ክቡራን፡ ወወራሚት፡ እንዘ፡ መምሕር፡ ተክለ፡ ሃይማኖት፡ወአፈ፡ መምሕር፡ ደምዬ፡ መምር፡ ኒቆዲሞስ፡ ፈንታ፡ ወልደ፡ ሚካኤል፡ በሊሕ፡ ዳኛ፡ ያፀዲን፡ ምድር፡ ያዘችውን፡ የገዛቸውን፡ ላቤቶ፡ ኃሸ፡ ሽጦናል፡ በ፵፡፩፡ጣን፡ተዶል፡ በከመምር፡ አግኔ፡ የተገዘውን፡ ካባ፡ ገብርኤል፡ የተገዘውን፡ ካይፅ፡ የተገዘውን፡ ይህነን፡ ደብሩም፡ መምሩም፡ ሀገሩም፡ ያለቅዳሴ፡ ከዳ፡ አንዳይገናጅ፡ ታቦር፡ ኪዳን፡ ገበዝ፡ ናትናኤል፡ ሚካኤል፡ አፈ፡ ገበዝ፡ ዝሬም፡ እኒህ፡ ተዳኑ፡ ለሚመጻውም፡ ቦተሾሙ፡ መድን፡ ናቸው፡ ደብር፡ የሰጡች፡ አስጻፊ፡ ደብተራ፤ ኢዮብ፡ ንው፡ ይህ፡ እንዳይፈርስ፡ በቡነ፡ ዘዮሐንስ፡ ቃል፡ በ፯፻፡በ፲፰፡ ቃል፡ ግዝት፡ ነው፡ አባ፡ በኵሬ፡ አባ፡ ሕዝቅያስ። ገዘቶሉ፡

persons involved may be:
1) ተክለ፡ ሃይማኖት -> with the honorific title mamḥər, but not the Saint
2) ደምዬ -> also a mamḥər
3) ኒቆዲሞስ፡ ፈንታ፡ ወልደ፡ ሚካኤል፡ -> also a mamḥər and a determined judge (በሊሕ፡ ዳኛ፡), albeit his title was mutilated to መምር፡ ; His actual name is ኒቆዲሞስ፡ ፈንታ፡, while ወልደ፡ ሚካኤል፡ is supposed to be the name of his father
4) ላቤቶ፡ ኃሸ፡ -> The person that was sold?
5) ጣን፡ተዶል፡ በከመምር፡ አግኔ፡ -> I don't understand, what is the name in here or how many people are involved. Probably again a mamḥər (written as መምር) with the name አግኔ
6) ካባ፡ ገብርኤል፡ or simply ገብርኤል፡ -> a person?
7) ካይፅ፡ -> also a person? I got lost in this sentence!
8) ታቦር፡ -> a reference to the biblical mountain or a place in Ethiopia?
9) ኪዳን፡ ገበዝ፡ -> a name or a title?
10) ናትናኤል፡ ሚካኤል፡ -> a person named ናትናኤል፡, while ሚካኤል፡ is the name of his father infact
11) ደብር፡ -> referring to the community of a monastery mentioned before?
12) ኢዮብ፡ -> name of a dabtarā, who wrote this short note.
13) ቡነ፡ -> name of the place, where the note was added to the codex, potentially a church or a small chapel.
14) ዮሐንስ፡ -> John the Evangelist, used here to date the note.
15) በኵሬ -> a person with the title ʾabbā who supervised the notification of this note.
16) ሕዝቅያስ -> another person with the title ʾabbā who supervised the notification of this note.

**Comment by DenisNosnitsin1970** [comment]
Suggestions: ጋሾ for ኃሸ, ሸጠናል for ሽጦናል፡ (difference between ሽ and ሽ is difficult), ገዝቶሉ for ገዘቶሉ፡.
ካባ፡ ገብርኤል፡ የተገዘውን፡ I assume it means ከ (from) አባ ገብርኤል፡ የተገዛውን፡, i see that the scribe always assimilate in this word za to zo, which is possible.  
በቡነ፡ means በ+አቡነ (ዮሓንስ ቃል)።

After a quick look, the sense excapes from me. I understand the string of names and the formula at the end, but not what exactly was done.  I think a deeper processing of the note may be necessary for a step forward, like division of the note into parts, and a literal word by word translation.

**Comment by CarstenHoffmannMarburg** [comment]
Thanks! I took all suggestions and corrections.
