### ISSUE TITLE
Names in Amharic additio in Tanasee1#a19

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2430]
@DenisNosnitsin1970 @thea-m 

In another additio in Tanasee1#a19 on folio 85vb, there are a number of names listed. I do not understand the purpose of this notification. The persons mentioned are often referred to as Liqa Rad or  Ato and some are judges (ዳኞች), who testifiying some transaction or yet another incident.

በዘመነ፡ ማርቶ፡ በመጋቢት፡ ራስ፡ ቢት፡ ወደድ፡ መንገሻ፡ ታቶ፡ ዋኦ፡ አገኘሁ፡ አርስት፡ ሲገዙ፡ እማኞቹ፡ ሊቀ፡ ረድ፡ ምርንኀህ፡ ሊቀ፡ ረድ፡ ጐሹ፡ ሊቀ፡ ረድ፡ ወንዲ፡ ሊቀ፡ ረድ፡ ሊ ከሩ፡ ምስለኔ፡ ተስፋ፡ ጌታሁን፡ ጔሉ፡ አያሌው፡ ገብረ፡ ማርያም፡ በር፡ ያሁን፡ ዋሴ፡ ናቸው፡ ለውርሱ፡ እማኞች፡ አቶ፡ ታወቀ፡ ብሳቃ፡ ዘለቀ፡ አያሌው፡ ገብረ፡ ማርያም፡ ደስታ፡ ለማ፡ አቶ፡ ገላጋይ፡ እሽቲ፡ ጔሉ፡ ስንደቂ፡ ትኩ፡ አቶ፡ ቀፈራ፡ አቶ፡ ቃፈለ፡ ዠመረ፡ ታውቀ፡ ዳኞቹ፡ ሊቀ፡ ረድ፡ ለማ፡ መጋሊ፡ ውብ፡ እሙ፡ ሉም፡ ወርቅነህ፡ ናቸው። ዳኞች፡ ለሁሉም፡ ናቸው

1) መንገሻ፡ ታቶ፡ ዋኦ፡
2) ምርንኀህ
3) ጐሹ፡
4) ወንዲ
5)  ከሩ
6) ተስፋ፡ ጌታሁን፡
7) አያሌው፡ ገብረ፡ ማርያም፡
8) በር፡ ያሁን፡ ዋሴ፡ 
9) ታወቀ፡ ብሳቃ፡
10) ደስታ፡ ለማ፡ 
11) ገላጋይ፡ እሽቲ፡ 
12) ስንደቂ፡ ትኩ፡ 
13) ቀፈራ፡ 
14) ቃፈለ፡ ዠመረ፡ ታውቀ፡ 
15) ለማ፡ መጋሊ፡ ውብ፡ 
16) ሉም፡ ወርቅነህ፡

Do you agree with my identification of personal names? I guess the title Ato points to a more recent dating, probably in the 19th or early 20th century.

**Comment by thea-m** [comment]
The digital Kane is offline right now, therefore my contribution is very limited. Here a few suggestions for some of the names.

1. It could also be ዋሎ or ዋሶ? is it a name or a function? Maybe belonging together with አገኘሁ?
2. ምርጥነህ, I think
4. Maybe ወንዴ?
8. Is ዋሌ a name or a function?
9. _ʾato_ Tāwaqqa
10. _blātta_ Zallaqa
11. ገላጋይ እሸቴ
13. _ʾato_ Tafarrā
14. Tāfalla...
15. I think that ውብአየሁ is one name
16. sum might be a title?

**Comment by DenisNosnitsin1970** [comment]
Suggestions: ማርቆ፡ in በዘመነ፡ ማርቶ፡, ታቶ፡ means ከ+አቶ, ዋስ for ዋኦ፡ (the scribe omitted word divider after that), ሊ ከሩ፡ should perhaps be understand as ብሩ (the name) because if you zoom you will see that the scribe cancelled ሊ with dashes above and below; ብላታ for ብሳቃ፡;  I would think that the form እሸቴ is meant, not እሽቲ፡, but it is difficult to see.  መጋቢ for መጋሊ፡, and further ወብ አየሁ (name) ሱም (title) ወርቅነ. In some cases I assume it should be -e, not -i, but the quality of the images is not sufficient. As for the previous note, a literal translation may be helpful as a basis for the discussion, to understand, to which extent we can penetrate this text :)

**Comment by CarstenHoffmannMarburg** [comment]
I thank you both for your corrections, each of which I have kept. I did not intend to go so far as to provide a translation for them and for the additions in this manuscript, although I find that a good number of them are very old and very significant. With your help I can try to give a translation as follows:

"In the year of Marqos, in Maggābit Rās, Bit Wadad Mangašā bought lands from ʾAto Wās. The witnesses are Liqa Rad Mərṭənḫah, Liqa Rad Gʷašu, Liqa Rad Wande, Liqa Rad Bərru, and also a person whose name is Tasfā Getāhun, ʾAyālew Gabra Māryām, Barr Yāhun Wāle. The witnesses under warranty are ʾAto Tāwqa, Blātā Zallaqa ʾAyalāw Gabra Maryām, Dastā Lamā, a person whose name is ʾAto Galāgāy ʾƎšte, Səndaqi Təkku, ʾAto Tafarā, ʾAto Tāfala Žammara Tāwqa, and the judges are Liqa Rad Lamā Magābi, Wəb ʾAyyahu, Sum Warqnah, who are the general judges. "

Do you want me to encode such a translation in a div, or did you just ask for it for better understanding in the future?

**Comment by DenisNosnitsin1970** [comment]
I thought the note interests you most. I would not provide translation of such notes on the regular basis, it is an immense work. (I would write all titles small, as they will be difficult to distinguish from the proper names.) A few minor remarks: 
blāttā, Lammā,   ምርጥነህ (?) for ምርንኀህ, Bar for Barr ("door"?), "liqa rad Lamā, Maggābi..."

**Comment by CarstenHoffmannMarburg** [comment]
Yes, the note is interesting to my research. Thank you for the comments!
