### ISSUE TITLE
Eth 616 Griaule 308 

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2432]
It looks like we have two records dedicated to the same manuscript, Ethiopien 616 (Griaule 308), 1) https://betamasaheft.eu/manuscripts/BNFgriaule308/main and 2) https://betamasaheft.eu/manuscripts/BNFet616/main. I corrected the shelfmark (standardized it) and the title in the second one, but when I wanted to remove the first one, I could not detect the file anywhere. Do you have any idea where it is?

**Comment by eu-genia** [comment]
the second record still lacks Strelcyn in the bibliography (and possibly something else, must be checked) and a formerlyListedAs relationship; once we have one record which is complete I can delete the other one from the app

**Comment by eu-genia** [comment]
I have deleted

**Comment by eu-genia** [comment]
I have deleted BNFgriaule308 now.
Note also the other files that are present in the application but are not visible in the GitHub repository - either they are out of sync or they are doublets too, please check, thank you.

![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/642bceff-7174-4bfd-948c-75552b9b203a)

**Comment by DenisNosnitsin1970** [comment]
ok
