### ISSUE TITLE
places ኤገና፡ and ዳፍ in a LandGrant

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2434]
@DenisNosnitsin1970 @thea-m @eu-genia 

I found two place names in an addition in Tanasee1 (f. 236vb). For the first one, that is ኤገና, አገና or ኣገና in the manuscript I can find nothing except for a small town (Agena) in the south between the river Omo and Lake Zway, that is pretty far away from the Tanalake region. The other one is either ዳፍ, ዳን or ዳና. I do not find any place in Ethiopia like this. 
I suppose, both must be small hamlets or little villages close to the southern shore of the Tana Lake, perhaps non existant any more. Is is useful to encode them nevertheless as so far unknown places?

<foreign xml:lang="gez">ዳረጐትነ፡ ወሀብኩ፡ እምድረ፡ <placeName ref="LOC0000">ኤገና፡</placeName> 
                                            ለማኅቶተ፡ ገብርኤል፡ ፲ወ፪፡ ለፈትል፡ ለዕጣን<gap reason="illegible" unit="chars" quantity="1"/>፡ ወሀብኩ፡ ምድረ፡ 
                                            <placeName ref="LOC0000">ዳፍ፡</placeName> ፳፡ ለጥር፡ ወለሀሎየሂ፡ ፀራቢ፡ ገዳፍከዎ፡ ለገብርኤል፡ ዘምስለ፡ ፱ዳስ፡ ዘወይን፡ 
                                            አሪር፡ የሀብክሙ፡ ዝንቱ፡ ኵሉ፡ መብልዕ፡ ዘነበረ፡ ለንቡረ፡ ዕድ። ዘንተ፡ <gap reason="ellipsis" unit="lines" quantity="3"/></foreign>

**Comment by thea-m** [comment]
I don't know them either. Since they relatively certainly seem to refer to place names, I think it would be fine to encode them as such.

**Comment by CarstenHoffmannMarburg** [comment]
I made two records for the two places. Is it reasonable to encode each of the possible spellings
(ኤገና, አገና or ኣገና and ዳፍ, ዳን or ዳና)? The writing is not very clear in the microfilm image.

**Comment by thea-m** [comment]
Yes, I think that would make sense

**Comment by eu-genia** [comment]
Image server up again

**Comment by DenisNosnitsin1970** [comment]
Indeed, it is difficult to discern, if the first is ኤገና or ኣገና (the vowel pattern like ኤገና  is a bit difficult, though probably not impossible). The second is ዳፍ, I am sure.

**Comment by CarstenHoffmannMarburg** [comment]
OK. I will keep ኤገና, ኣገና in the records. Thank you for your comments!
