### ISSUE TITLE
A request to create a new work record

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2435]
I would like to create a work record for a text recently published in:

Forness, Philip Michael. “New Evidence for Severus of Antioch’s Correspondence with the Patricia Caesaria. Ethiopic Fragments Related to the Origin of Evil and the Resurrection of the Dead.” Zeitschrift Für Antikes Christentum / Journal of Ancient Christianity, vol. 26, no. 2, Aug. 2022, pp. 305–45, https://doi.org/10.1515/zac-2022-0023.

As usual it would be nice to have a witness list, for that I would like to ask what should be the proper file name for the manuscript listed here as B.

@eu-genia @CarstenHoffmannMarburg @thea-m 

![For](https://github.com/BetaMasaheft/Documentation/assets/62760230/00513410-4489-4656-a806-e7ec427f294d)

**Comment by eu-genia** [comment]
we already have one DS Genizah ms (DS-XVI) as ADSfragm16 so this one (https://www2.lingfil.uu.se/projects/Dabra_SahelQ/MSS/DSMssSamples/DSMssGeniza/DSXXIII/) should become ADSfragm23.

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 are there more Dabra Sahl images somewhere by the way?
