### ISSUE TITLE
Two images missing in BMLacq680

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2436]
@eu-genia 
In the images of BMLacq680, two openings are missing:
6v-7r,
179v-180r
One can evidently see the gap by looking at the foliation on the bottom left of every recto and by watching at the small damages of the parchment the bottom margin in each case. Also the text does not fit in my opinion.
Is there any option to find the missing images and make them available in the viewer?

**Comment by CarstenHoffmannMarburg** [comment]
Image number 128 is not displayed with a small image at the bottom line.

**Comment by eu-genia** [comment]
the two missing openings seem to have been skipped when photographed; I do not have them in the image set I have here. maybe @abausi has another image set somewhere?

we should collect in this issue all other missing pages (I remember we already had such a case?), then maybe there could be an occasion to rephotograph what had been skipped

**Comment by CarstenHoffmannMarburg** [comment]
I recall that the images of Tanasee1 are of comparatively poor quality because they were made from microfilm images, as discussed in issue #2417. I don't remember any manuscripts with missing images in the BML collection, but I can check the records.

**Comment by CarstenHoffmannMarburg** [comment]
I checked the records of all BML manuscripts, that I have recorded so far. I did not find a hint neither in foliation, nor in condition.

**Comment by eu-genia** [comment]
Last time it came up about the same manuscript https://github.com/BetaMasaheft/Manuscripts/pull/2131 - the pull request was open in May
