### ISSUE TITLE
New Salām in BMLacq680

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2438]
@DenisNosnitsin1970 @eu-genia @thea-m 

I found a salām in BMLacq680 on folio 69vc at the end of a synaxary for maskaram. 

The text, I read as follows:
ሰላም፡ ለአባ፡ ሣሉስ፡ ጥበቦ፡ ዘሠወረ። 
መሲሆ፡ በነግህ፡ እንዘ፡ ይጸውም፡ ድራረ። 
አኅድጎተ፡ ዝንቱ፡ ልማጽ፡ ሶበ፡ አበ፡ ምኔት፡ መከረ። 
ዘቢጦ፡ በቆብዑ፡ ዓረፍተ፡ መቅደሰ፡ ሰቈረ። 
ወእንተ፡ ህየ፡ ወፂኦ፡ እምዓለም። 
ሖረ። 

I could not find the text in the search. May I create a new LIT ID?
[
<img width="516" alt="Screenshot BMLacq680_Salam-la-Ab-salusi-tebabo-za-sawwara" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/ebd7c279-77b8-4077-ad36-efc5b5e3b232">
](url)

**Comment by CarstenHoffmannMarburg** [comment]
There is another salām in f. 109vc at the end of ṭəqəmt, that I cannot identify either. For the text I read:
ሰላም፡ እብል፡ ለሰማዕት፡ ሰቅጥር። ፍቁረ፡ ዳማትርዮስ፡ ማር። ወሰላም፡ ለረድኡ፡ ኢንተ፡ ድኅሬሁ፡ ምቱር። በልብሱ፡ ወኅልቀቱ፡ ጥሙዓነ፡ ደሙ፡ ክቡር። ገባሬ፡ ኃይል፡ ዓቢይ፡ ወእፁብ፡ መንክር። 
<img width="290" alt="Screenshot_salam ebel_BMLacq680" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/da8ac1f8-d2e7-403c-ac5c-d9bce5fca4a0">

**Comment by CarstenHoffmannMarburg** [comment]
The next salām is on folio 150ra. I did not find it either.
ሰላም፡ ለከ፡ ቀሌምንጦስ፡ አቡነ፤ አበ፡ መንፈስነ፤ ከመ፡ ናጽንዕ፡ ዘልፈ፡ በትምህርትከ፡ አሚነ፤ ጽሒፎሙ፡ ሐዋርያት፡ ኃደጉ፡ ለነ፤ ምስለ፡ ቀሌምንጦስ፡ እንዘ፡ ይብሉ፡ መላእክተ። ፈኖነ።
![Uploading Screenshot_Salam laka Qalementos_CH 2023-11-03.png…]()

**Comment by eu-genia** [comment]
Is it a Synaxary? As far as I can see so far we have used derived IDs for Synaxary commemorations as they do not circulate independently (e.g. `LIT4035SenkessarDL#FirstHalf.FirstQuarter.3.Heda29.Heda29SalQalementos`)

check the edition in `LIT4032SenkessarS LIT4033Senkessar LIT4035SenkessarDL`

If we start upgrading commemorations to works then several hundred probably need ot be created

@thea-m would be the best to tell

**Comment by eu-genia** [comment]
See as examples BNFet126 BNFet677 and other catalogued Synaxaries

**Comment by CarstenHoffmannMarburg** [comment]
Yes, there are about more than a hundred in this synaxary. It came also to my mind not to encode each one. If there is no individual circulation for these three, as it appears to me, I will not give them LIT IDs. 
I close this issue here, because I want to push a pull request in a minute, where this discussion can be continued, if neccessary.

**Comment by thea-m** [comment]
My advide would be to use LIT4035SenkessarDL for manuscripts which can clearly be grouped into the second recension, for example by the presence of salāms.
For the first half of the year, the record LIT4035SenkessarDL contains IDs for all commemorations and salāms. Without text edition, there remains a certain risk in assigning its IDs, however, as in the case of the salāms given here, there seems to be only one for the saint in question on these particular days in the example manuscripts, I would say that it is relatively safe to use them (if they should be marked up at all, depending on desired depth of description).
LIT4035SenkessarDL#Mask30SalSalusi
LIT4035SenkessarDL#Teqe29SalSeqtar
LIT4035SenkessarDL#Heda29SalQalementos
