### ISSUE TITLE
ሳራ (PRS12054Sara) in the NT and in the Sənkəssār

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2440]
@thea-m @DenisNosnitsin1970 @eu-genia 

I found ሳራ together with ማርያም፡ መግደላዊት፡ and ሰሎሜ in a Ləfāfa ṣədq in BMLacq384. I think these are the three recognised witnesses of the resurrection of Christ. 

For ማርያም፡ መግደላዊት፡ I found PRS6820MaryMag and I am pretty sure this is the saint in question, whereas for ሰሎሜ I found PRS8417Salome and I am similarly sure.

For ሳራ I found PRS12054Sara. There is no information in the record other than a reference to the sənkəssār. Do you think this is the right ሳራ - the one who witnessed the resurrection? Other personal names listed as Sara do not include any information that would allow identification.

**Comment by eu-genia** [comment]
No. If you open the Senkessar record pointed you will see that it is the Sarah commemorated on 15 Maggabit. If you open the Synaxarion you will read for 15 Maggabit. "On this day died the holy and righteous and ascetic woman, Sara the nun"

As far as I can see we do not have the NT Sarah yet, only the OT Sarah (PRS8533Sarah).

**Comment by CarstenHoffmannMarburg** [comment]
OK, thanks!

**Comment by CarstenHoffmannMarburg** [comment]
I found in Wikidata a biblical figure with the name Sara, who is described as the wife of Tobit (Q2224149). I guess, this is another Sara. The follower of Jesus is not encoded in Wikidata either.

**Comment by eu-genia** [comment]
Sorry, I cannot find a Sarah among the witnesses of the Resurrection (the three Marys). Are you sure there was one? And that it is not the OT Sarah in the text?

**Comment by CarstenHoffmannMarburg** [comment]
Marrassini says, this is: "Racconto della Passione e delle piaghe di Cristo, rivelato a Maria di Magdala, Sara e Salomè. Uno dei testi aggiunti di frequente al Lafāfa ṣədq secondo Euringer, etc." (= Story of the Passion and wounds of Christ, revealing to Mary Magdalene, Sarah and Salome. One of the added texts of frequent at Lafāfa ṣədq according to Euringer etc."). I think, it must be a NT person and saint.

**Comment by eu-genia** [comment]
OK, could be the St Sara then Q238261 who was possibly a servant of one of the Marys but I am not a NT specialist... Or rather the NT does not have her, only later legends.

**Comment by CarstenHoffmannMarburg** [comment]
I made a pull request for Sara and Mary Magdalene (#766). We can continue discussion there.
