### ISSUE TITLE
Work similar to LIT5020Hemamatihu

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2445]
@thea-m @eu-genia @DenisNosnitsin1970 

I found a work in BMLacq384, that seems to be pecular, but similar to LIT5020Hemamatihu, as attested in BLorient631 (f. 2v), BLorient755 and BLorient829fragments. As far as the server of the British Library is down, I cannot check the witnesses at the moment and will postpone the decision, whether a new LIT ID is needed or not.

Incipit of LIT5020Hemamatihu according to the ms-record of BLorient631: ዝንቱ፡ **ሕማማቲሁ፡ ለእግዚእነ፡** ኢየሱስ፡ ክርስቶስ፡ **መድኅነ፡** ዓለም፡ ዘለሊሁ፡ **ከሠተ፡ ሎን፡ ለሥላስ፡ ቅድስት፡ አንስት። እለ፡ ይሰመያ፡** ቅድስት፡ **መግደላዊት፡** ወቅድስት፡ **ሰሎሜ፡** ወቅድስት፡ ኤልሳቤጥ።

Incipit of BMLacq384 on f. 29r: በስመ፡ አብ፡ ... ንጽሕፍ፡ ዜና፡ ሕማማቲሁ፡ ለእግዚእነ፡ ወቅንዋቲሁ፡ ለመድኀኒነ፡ ኢያሱስ፡ ክርስቶስ፡ ዘ**ከሠተ፡ ሎን፡ ለሠላስ፡ ቅድስት፡ አንስት፡ እለ፡ ይሰመይ፡** ማርያም፡ **መግደላዊት፡** ለሳራ፡ ወለ**ሰሎሜ፡**    as it can be seen in the following picture:  

<img width="733" alt="Screenshot 2023_Maqdalawit" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/7b3bf1de-e327-4f12-8c9c-1c059286b340">

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1501
This is still open, because I did not yet create one ID, as described. The proposed solution of that issue is that LIT5020Hemamatihu   can be used as a general record when the precise recension is not known, so that might be a solution here.

**Comment by CarstenHoffmannMarburg** [comment]
OK. I changed the record accordingly.
