### ISSUE TITLE
PRS and LIT for protective prayers in magic scrolls

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2447]
@DenisNosnitsin1970 @eu-genia @thea-m 

In **BMLacq756**, I encoded a number of protective prayers and magical texts. Most of them have correlation to existing LIT, but none of them (but one) can be identified precisely with an existing LIT. I propose therefore to create new LIT and mark the possible relations.

**ms_i1** (First column, line 1 to 34) Prayer against Bāryā, Tǝgrǝtyā and Belsibā - written mostly in Gǝʿǝz and partly in Amharic with invocations of magical names, mostly unintelligible and therefore problematic.
ጸሎት፡ በእንተ፡ ባርያ፡ ወትግርትያ፡ ቤልሲባ፡ ... ለሰይጣና 

<img width="278" alt="Screenshot 2023_Barya, Tegretya, Belsiba" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/32abfc96-0ba9-4685-80f2-b5529e32efc9">
<img width="293" alt="Screenshot 2023_Barya, Tegretya, Belsiba (2)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/5e298da9-89ae-4c5f-9284-a4f3a9ecb047">

**ms_i2** (First column, line 34 to 107) Prayer against Bāryā and Lǝgewon and against various diseases as colic, pleurisy, pleuralgia; with invocation of the names of the nails of the cross (sador, ʾalādar, dānāt, ʾadarā, rodās) and other magical names. They could probably be counted as two, but Marrassini however defined it as one protective prayer:
ጸሎት፡ በእንተ፡ ባርያ፡ ወልጌዎን፡ ርኩስ፡ ዘይሰልብ፡ ልበ፡ ሰብእ፡ ወይጸልም፡ አእይንት፡ ወይመጽእ፡ ከመ፡ ጽለሎት፡ ወሕልም፡
<img width="313" alt="Screenshot 2023_Barya, Legewon (1)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/0e3eface-4948-46a5-9e10-f49de4412933">
<img width="315" alt="Screenshot 2023_Barya, Legewon (2)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/5fd40231-e842-48ff-bd52-9df35af29ea6">
<img width="424" alt="Screenshot 2023_Barya, Legewon (3)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/3694bd4e-5fa7-4226-908a-d022ece3e3cb">
<img width="316" alt="Screenshot 2023_Barya, Legewon (4)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/11aad0f4-86c2-40d3-86d0-7b5280a6cbe1">
<img width="404" alt="Screenshot 2023_Barya, Legewon (5)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/5b591727-7ad8-4cf9-807e-842bb892016e">

**ms_i3** (Left column, lines 107 to 133) Prayer to Jesus Christ - with invocation of the names of the nails of the cross, and other magical names:
በስመ፡ እግዚእነ፡ ኢየሱስ፡ ክር(ስ)ቶስ፡ ዘከተሮ፡ ለሠይጣን፡ በ፭ቅንዋተ፡ ሳዶርቋ፡

This prayer is probably related to LIT6796PPIllnesses, what is not possible to check, because the only referenced witness is in the British library, where images are not available.

<img width="319" alt="Screenshot 2023_Scroll Krestos" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/66431e75-366e-4587-acfb-f5945fb93f0b">
<img width="218" alt="Screenshot 2023_Scroll Krestos (2)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/d6e8f0b2-4ef1-44ae-a7e7-d4703bfacbce">

**ms_i4** (Left column, lines 133 to 155) Prayer against Bāryā and Šatolāy - Prayer for the healing of vaginal bleeding and for the protection of newborn babies through the invocation of magic names similar to LIT6845PPSatolay and the Christ's blood, his sharp sword similar to LIT2295Sayfam and through the six words of the Gospel.

<img width="203" alt="Screenshot 2023_Barya, Satolay (1)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/c4812853-9819-43e2-a7d3-e408182c3fb0">

**ms_i5** (Left column, lines 155 to 183) Mark 5,25-29 - A passage from LIT1882MarkGo about the healing of haemorrhoids, easy to identify in the edition of the Gospel. I suggest to single this portion out to a new own ID as it is the case with LIT6783MarkFive. I think, it is established here, that also Mark 5,25-29 has its own circulation.

<img width="267" alt="Screenshot 2023_Wangel za-Marqos" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/2be86e54-6416-41cb-aeb1-1be9ccd6cd1a">

**ms_i7** (Right column, lines 160 to 189) Prayer against Šatolāy and Šatolāwit - Prayer for healing from vaginal bleeding and for protection of newborn babies through the invocation of magic names and through the binding of demons with the bonds of the Father, Son and Holy Spirit. Once again similar to LIT6845PPSatolay.

<img width="240" alt="Screenshot 2023_Satolay, Satolawit" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/18e8f489-946c-4e16-ac7c-430051aeff25">
<img width="329" alt="Screenshot 2023_Satolay, Satolawit (2)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/92b0a643-1397-450c-a632-66a816cd1c40">

It is necessary to decide, whether these portions of text should be encoded as independent works with their own LIT ID or, if these texts are too fluid, whether they shall be encoded under the existing IDs with their similar texts. 

Furthermore I want to ask, whether it may be useful to encode the names of the demons, that occur in these texts. I did not find them as PRS ID except for Legewon.

**Bāryā** (name probably related to the Bāryā people, but as a demon should get its own ID)
**Tǝgrǝtyā**
**Belsibā**
**Šatolāy**
**Šatolāwit** 
**Lǝgewon** is recorded as PRS6242Legewon, but the record has no indication about the nature as a demon.

**Comment by eu-genia** [comment]
just to be sure - for ms_i2 - you surely checked
LIT4566MagicPr
LIT4575MagicPr
LIT4599Salot
LIT4619Prayer
LIT4702MagicPr
LIT5075MagicPrayer
LIT5076MagicPrayer
LIT5688MagicPrayer
LIT5826MagicPrayer
LIT5827MagicPrayer
LIT5875MagicPrayer
LIT5887MagicPrayer
LIT6484PPAynaTela
LIT6497PPAynat
and they are all different, right?

for ms_i5 - sure, go ahead

for the names of demons -
(1) I am not sure that we should mark up demons as persons; we could use keyword term demon for the moment
(2) I would really concentrate on cataloguing manuscripts and NOT on marking up the texts contained in them, so I would not suggest to lose time on creating records for all persons and places mentioned in the texts; this should be a separate task apart from the primary cataloguing; we only must create records for persons and places relevant for the manuscript production/storage.

**Comment by CarstenHoffmannMarburg** [comment]
> (1) I am not sure that we should mark up demons as persons; we could use keyword term demon for the moment

How will I highlight the name with a keyword in that case?

**Comment by CarstenHoffmannMarburg** [comment]
LIT4566MagicPr -> Just alone the words ጸሎት፡, በእንተ፡ and ባርያ፡ appear in the incipit, what is not enough to state a dependancy. The text in full cannot be checked, because for the only witness BDLaethf5 images are not available.

**Comment by eu-genia** [comment]
> > (1) I am not sure that we should mark up demons as persons; we could use keyword term demon for the moment
> 
> How will I highlight the name with a keyword in that case?

see https://betamasaheft.eu/Guidelines/?id=keywordsIntro example 4

**Comment by eu-genia** [comment]
> LIT4566MagicPr -> Just alone the words ጸሎት፡, በእንተ፡ and ባርያ፡ appear in the incipit, what is not enough to state a dependancy. The text in full cannot be checked, because for the only witness BDLaethf5 images are not available.

I am sure @thea-m has seen the ms

**Comment by CarstenHoffmannMarburg** [comment]
> > > (1) I am not sure that we should mark up demons as persons; we could use keyword term demon for the moment
> > 
> > 
> > How will I highlight the name with a keyword in that case?
> 
> see https://betamasaheft.eu/Guidelines/?id=keywordsIntro example 4

Can I add "demon" to the taxonomy and if yes, how can I do that? If we already have this keyword or when the keyword is established, how will I add it to the record. Is it acceptable to add it to a note as for example: 
`<note>Prayer against <term key="demon">Bāryā</term> and <term key="demon">Lǝgewon</term> and against various diseases as colic, pleurisy, pleuralgia; with invocation of the names of the nails of the cross (sador, ʾalādar, dānāt, ʾadarā, rodās) and other magical names.</note>`
And likewise mark it in the encoded incipit: 
```
<incipit xml:lang="gez"><gap reason="illegible" unit="lines" quantity="3"/> ጸሎት፡ በእንተ፡ 
<term key="demon">ባርያ፡</term> ወ<term key="demon"><supplied reason="lost">ልጌ</supplied>ዎን፡</term> ርኩስ፡ ዘይሰልብ፡ ልበ፡ ሰብእ፡ ወይጸልም፡ አእይንት፡ ወይመጽእ፡ ከመ፡ ጽለሎት፡ ወሕልም፡</incipit>
```

**Comment by eu-genia** [comment]
Yes, this looks correct (we have demon in the taxonomy, very easy to check by typing `https://betamasaheft.eu/demon`), but please also read what I wrote under (2) above.

**Comment by eu-genia** [comment]
(we also have `PRS11330Devil`, and these are all in a certain sense his names/epithets, so could also be used; one could also add names/epithets of Satan to the record `PRS11330Devil `and then refer to specific epithets by sub-IDs as we do for the epithets of Christ)

**Comment by CarstenHoffmannMarburg** [comment]
LIT4575MagicPr has the same demon names (Bāryā and Lǝgewon) as ms_i2. Apart from that, there is no word the same (except for በእንተ), judged from the incipit (ጸሎት፡ በእንተ፡ ሕማመ፡ ባርያ፡ ወጌሌዎን፡ ወበእንተ፡ ማዕሠረ፡ አጋንንት፡) and from the textual witness in BDLaethf11.
<img width="478" alt="Screenshot 2023_BDLaeth_Barya and Legewon" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/272b2c64-a640-4233-962c-808977b7978f">

**Comment by CarstenHoffmannMarburg** [comment]
> Yes, this looks correct (we have demon in the taxonomy, very easy to check by typing `https://betamasaheft.eu/demon`), but please also read what I wrote under (2) above.

I encoded the demon names in that way. It is indeed easier and quicker to do it like that rather than to create PRS IDs for them.

**Comment by CarstenHoffmannMarburg** [comment]
As for the previous, also LIT4619Prayer has correlations in the name of demons judged from the incipit (ጸሎት፡ በእንተ፡ ሕማመ፡ ባርያ፡ ወሌጌዎን፡). All the three witnesses are not available to me. 

NB. When I open Bm website to [LIT4619Prayer](https://betamasaheft.eu/works/LIT4619Prayer/main), I can see the title Ṣalot baʾǝnta ḥǝmāma Bāryā wa-Lagewon (sic), however in the oxygen viewer I see the title correctly transcribed as Ṣalot baʾǝnta ḥǝmāma bāryā wa-legewon. I do not understand, how this can happen, that Bm website and oxygen record do not agree.

**Comment by eu-genia** [comment]
> As for the previous, also LIT4619Prayer has correlations in the name of demons judged from the incipit (ጸሎት፡ በእንተ፡ ሕማመ፡ ባርያ፡ ወሌጌዎን፡). All the three witnesses are not available to me.
> 
> NB. When I open Bm website to [LIT4619Prayer](https://betamasaheft.eu/works/LIT4619Prayer/main), I can see the title Ṣalot baʾǝnta ḥǝmāma Bāryā wa-Lagewon (sic), however in the oxygen viewer I see the title correctly transcribed as Ṣalot baʾǝnta ḥǝmāma bāryā wa-legewon. I do not understand, how this can happen, that Bm website and oxygen record do not agree.

this can easily happen if some pull request did not go through to the server (e.g. the server was not active at the moment the PR was committed to github)

**Comment by eu-genia** [comment]
In this case the title was not updated in the list of titles, should be fixed now

**Comment by thea-m** [comment]
> > LIT4566MagicPr -> Just alone the words ጸሎት፡, በእንተ፡ and ባርያ፡ appear in the incipit, what is not enough to state a dependancy. The text in full cannot be checked, because for the only witness BDLaethf5 images are not available.
> 
> I am sure @thea-m has seen the ms

No :(

**Comment by eu-genia** [comment]
We urgently need someone to apply for funding for a sub-project on magical prayers to do a proper repertory from known manuscripts. This is something we can hardly cover.
