### ISSUE TITLE
Mark up inside of title element in works

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2448]
I wanted to encode Josef in ms_i6, but I did not find an ID for him. It is supposed to be Joseph, the son of Jacob and Rachel, who is registered as Q145746 in Wikiquote. Is his record missing in Bm?

I checked EMIP00227 and LIT6751PPAynat and discovered some similarities to ms_i6 in the manuscript and in the record respectively. However, I saw, that the link [www.betamasaheft.eu/LIT6751PPAynat](https://betamasaheft.eu/works/LIT6751PPAynat/main) is not available at the moment.

_Originally posted by @CarstenHoffmannMarburg in https://github.com/BetaMasaheft/Manuscripts/issues/2224#issuecomment-1854495543_

**Comment by eu-genia** [comment]
The error in LIT6751PPAynat 
`HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/works/LIT6751PPAynat/main: exerr:ERROR expected a single value for order expression $t/child::text() ; found: 2 [at line 4558, column 21] In function: viewItem:work(item()*) [5753:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1430:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [564:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]
`
Is due to the markup inside of the `<title>`

 ```
<title xml:lang="en" xml:id="t1">Protective prayer against the evil eye (<foreign xml:lang="gez">ʿāynat</foreign>),
                    containing <foreign xml:lang="gez">ʾasmāt</foreign></title>
```

or code does not support mark up inside of `title`

**Comment by thea-m** [comment]
Thank you! That was my first suspicion, but for example LIT6506Sebhat is displayed fine....

**Comment by eu-genia** [comment]
`LIT6506Sebhat `has only one element marked up, one is supported, more are not )

**Comment by thea-m** [comment]
One reason for the mark-up was the desire to print these words in italics in the catalogue. Would `<hi rendition="simple:italic">` be possible? This is present experimentally for the same reason in some records, and does not lead to errors (https://betamasaheft.eu/works/LIT3100RepCh380/main).
(It would actually be nice if they were also in italics on the website.)

**Comment by eu-genia** [comment]
I see. I must try to see if I can get the code support more cases of mark up within the `title`

**Comment by thea-m** [comment]
Thank you! If not possible, not the end of the world :)

**Comment by eu-genia** [comment]
I found the error in xql and fixed it, should work now
