### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by AaronButts** [BetaMasaheft/Documentation#2449]
I am not sure that this is the best way to relay this information, but I found an incorrect link in Bm. On the following page:

https://betamasaheft.eu/BMLor148

Under Provenance, there is supposed to be a link to Vaticanus borgianus et. 2, but it simply redirects to the page for BML 148.

Maybe I am missing something obvious...

**Comment by eu-genia** [comment]
thank you, the link was encoded wrongly, @CarstenHoffmannMarburg please make sure that links outside of the record have `corresp `and no` #`, we only use `target ` to refer to pointers inside of the record itself, thank you for paying attention!

**Comment by CarstenHoffmannMarburg** [comment]
I try to keep that rule in the future! Thank you for resolving this problem immediately!
