### ISSUE TITLE
doublet

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2450]
PRS14025Balca is a doublet of PRS2435Balcasa and should probably be deleted

**Comment by CarstenHoffmannMarburg** [comment]
Yes, please. The record of BMLacq680 is supposed to be rendered then.

**Comment by thea-m** [comment]
Can you delete it?

**Comment by CarstenHoffmannMarburg** [comment]
I assume, that this record can only be deleted in a new branch after the previous one (Balco-in-BMLacq680) was approved and merged. I cannot figure out, whether this branch has been merged. I do not find it in the github website PRS pull requests.

**Comment by thea-m** [comment]
Here https://github.com/orgs/BetaMasaheft/repositories?type=all all repositories can be seen, and from each repository, its PRs can be accesssed.
https://github.com/BetaMasaheft/Persons/pulls

**Comment by CarstenHoffmannMarburg** [comment]
Yes, I found 5 open pull requests and 773 closed pr, but the one, I was looking for is not there.

**Comment by thea-m** [comment]
Is it this one? https://github.com/BetaMasaheft/Persons/pull/720

**Comment by CarstenHoffmannMarburg** [comment]
OK. I see the branch was merged and deleted. So I will create a new branch to delete the doublet record.

**Comment by eu-genia** [comment]
As already remarked https://github.com/BetaMasaheft/Persons/pull/720 the id should also be corrected in the ms record.
