### ISSUE TITLE
doublet life of shenute?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2452]
LIT2492VitaSi and LIT1501GadlaS?

**Comment by thea-m** [comment]
Both records go back to the EAe Index/entry of Shenute and were never used.
LIT2492VitaSi refers to the Vita Sinuthii in general, mentioned in Shenute's EAe article on p. 648b, LIT1501GadlaS to its Ethiopic version on p. 649a. I believe it would be according to our principles to delete LIT2492VitaSi. Any objections?
@DenisNosnitsin1970 @CarstenHoffmannMarburg @eu-genia @MarcinKrawczuk

**Comment by MarcinKrawczuk** [comment]
Fine by me, except I think in my not yet approved modification of
LIT1501GadlaS I have made a relation to LIT2492VitaSi, so it should be
deleted.

pon., 29 sty 2024 o 17:07 thea-m ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
I would rather stay with LIT2492VitaSi and delete LIT1501GadlaS as the text is not Ethiopic in origin anyway

**Comment by eu-genia** [comment]
Now that I have seen the new LIT1501 I agree that we keep 1501 and remove 2492

**Comment by MarcinKrawczuk** [comment]
Eugenia, I have added you as a reviewer, I'm not sure how to proceed

pon., 29 sty 2024 o 20:43 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
Replace the relation with formerlyAlsoListedAs and delete 2492, thank you!
