### ISSUE TITLE
Error message: Support and maintenance package Oxygen will expire in 4 days

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2456]
@eu-genia 

I get the following Error message in oxygen. Do I need to follow the instructions or should I dismiss it?

<img width="420" alt="Screenshot 2024_Support-Paket" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/091e94ca-ac58-48f6-b340-55039d9c115d">

**Comment by eu-genia** [comment]
I have ordered an extension (though I do not think it is necessary), you cannot do anything anyway, just ignore
