### ISSUE TITLE
wikidata ID in new record form

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2457]
When adding the wikidata ID in the online new record form, this is rendered in the produced record as sameAs="Q213729", to which wd: then has to be added manually. That is a bit misleading for everyone who has not memorized the guidelines. Would it be possible to update this?
@eu-genia

**Comment by eu-genia** [comment]
Is this OK like it is now with the prompt (then I do not need to touch the code)? please check

**Comment by thea-m** [comment]
Yes, much better, thank you
