### ISSUE TITLE
Order of incensing in EMML1832

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2458]
@DenisNosnitsin1970 @eu-genia @thea-m 

I found an addition in EMML1832 on folio 2r-3r. Getatchew Hayle wrote that this was an "order of incensing". I must confess that I do not fully understand the content and would not have been able to define it in this way by myself. There are a large number of names of which I am not sure what their role is in this context. It is given that there are 24 (or 21?) people or entities responsible for providing (or offering?) the incense. They are listed with the phrase ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ . As far as I understand, the land was given to certain people and each of these people is responsible for providing the incense or the peasants who plough the fields on that person's farmland. However, the number of ምድረ፡ is not 24 or 21, but less. There is also a list of deacons which is described as 12, but there are less than 12 names in this list. Can anyone explain this note and these contradictions? Do you recommend that I encode all the names as personal names, as already indicated, or should I refrain from doing so?

```
<item xml:id="a3">
                           <locus from="2ra" to="3rb"/>
                           <desc type="Record">Order of incensing at the <placeName ref="LOC2260DabraE"/> made by ʿaqqābe saʿat 
                              <persName ref="PRS10374Yohanne"/>.</desc>
                           <q xml:lang="gez">በስመ፡ አግዚአብሔር፡ ግሩም፡ አኃዜ፡ ኵሉ፡ ዓለም፡ ብሑተ፡ ስልጣን፡ ወስም፡ አነ፡ 
                              <persName ref="PRS10374Yohanne">ዮሐንስ፡</persName> ንኡስ፡ ወሕጽጽ፡ እምኵሎሙ፡ ዓቃቤ፡ ሰዓታት፡ እለ፡ ኮኑ፡ 
                              በ<placeName ref="LOC2260DabraE">ሐይቅ፡</placeName> አጽሐፍኩ፡ ከመዝ፡ ይኩን፡ ሥርዓታ፡ 
                              ለቤተ፡ <placeName ref="LOC2260DabraE">እስጢፋኖስ፡</placeName> ሥሩዓ፡ ወልኩዐ። ይኩኑ፡ ካህናት፡ እለ፡ የዐጥኑ፡ ፳ወ፬፡ <cb n="2rb"/>
                              ላዕለ፡ ኍልቈ፡ <gap reason="ellipsis" unit="lines" quantity="19"/>
                              ወድኅሬሁ፡ በዐለ፡ <persName ref="PRS000000000000000">ጠ<pb n="2va"/>ልቃ።</persName> 
                              ወድኅሬሁ፡ በዐለ፡ <persName ref="PRS00000000000000">ሰውሰት።</persName>
                              ወድኅሬሁ፡ ወዘበልዐ፡ ምድረ፡ <persName ref="PRS000000000000">ሎዛ።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS000000000">መርቆርዮስ።</persName> 
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS0000000000">ጊዮርጊስ።</persName> 
                              ወድኅሬሁ፡ ዘበልዓ፡ ምድረ፡ <persName ref="PRS000000000">ቍስቋም።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ ፩፡ እንስሳ። 
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ ካህናተ፡ ሰማይ።
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS0000000000000">ቀሌመን<cb n="2vb"/>ጦስ።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS0000000000000">ማርያም።</persName>
                              ወድኅሬሁ፡ በዐለ፡ ቤተ፡ ቍርዓ።  
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000000">ብእት፡ ኀይሉ።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000000">ብርሃን፡ መስቀል።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000000">ጠልቀይ።</persName> 
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000000">ሐደራ።</persName>
                              ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ <del rend="effaced" unit="chars" quantity="7"/>
                              ወድኅሬሁ፡ <persName ref="PRS00000000000000">ገብረ፡ ክርስ<pb n="3ra"/>ቶስ። </persName>
                              ወድኅሬሁ፡ <persName ref="PRS00000000000000">መቃርስ።</persName> 
                              ወዲያቆናትሂ፡ ይኩን፡ ኍልቆሙ፡ ፲ወ፪፡ ላዕለ፡ ስመ፡ ንጹሓን፡ ሳባኪያን፡ ሩሃን፡ ፲ወ፪፡ ሐዋርያት። ክቡራን። ወአስማቲሆሙ፡ ከመዝ። 
                              <persName ref="PRS00000000000000">ማማስ።</persName>
                              <persName ref="PRS00000000000000">አምላክ፡ ምአ።</persName> 
                              <persName ref="PRS00000000000000">አምላከ፡ ብነ።</persName> 
                              <persName ref="PRS00000000000000">ስምዖን፡ ሴኖዳ።</persName> 
                              <persName ref="PRS00000000000000">ዮሐንስ፡ ከማ።</persName> 
                              <persName ref="PRS00000000000000">ይሄይስ፡ ተአምኖ።</persName> 
                              <persName ref="PRS00000000000000">አንድርያስ።</persName> 
                              <persName ref="PRS00000000000000">ሐደራ።</persName>
                              ዘበልዐ፡ ምድረ፡ <persName ref="PRS000000000000">ልደታ፡ ለማርያም። </persName>
                              ዘበልዐ፡ ምድረ፡ <persName ref="PRS00000000000">መርቆርዮስ።</persName> 
                              <persName ref="PRS00000000000000">ዘርአ፡ ቡሩክ። ።</persName></q>
                        </item>
```

<img width="329" alt="Screenshot 2024_incense 1" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/e366f22c-9c9b-4525-9a29-a60ceac2d4cb">

<img width="562" alt="Screenshot 2024_incense" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/ab8e8b22-b58c-40ad-97e6-f277c7d30b45">

**Comment by thea-m** [comment]
As I understand it, the note gives a hierarchy of 24 priests of the monastery (mirroring the 24 Heavenly Priests) needed within the (office of?) offering of the incense, and then lists the 12 deacons needed for the same purpose. 
I do not know the expression "balʿa mǝdra" and could not quickly find it anywhere. I would very tentatively interpret "za-balʿa mǝdra Qwǝsqwām" etc. as "the one who ??? the land of Qwǝsqwām", designating an office, function or responsability related to lands of the monastery (?), and not as a personal name.  The persons occupying this function must be priests/deacons.
I count 26 offices/person within the hierarchy of those offering incense, including the ʿaqqābe saʿāt, the qays gabaz and the deleted space towards the end. Disregarding the first two former and counting the latter would let us arrive at 24. 
Counting Sǝmʿon and Senodā as two persons lets the list of persons/offices (?) mentioned in the second part of the note arrive at 12.
The entire content is therefore not entirely transparent to me, but I think it's fine to repeat Getatchew's interpretation and possibly state uncertainties.
Regarding whether or not to encode all personal names (according to my interpretation, there are "only" ten personal names in this note in the list of deacons), I think you can decide this freely depending on your time and interest.

**Comment by CarstenHoffmannMarburg** [comment]
To my understanding balʿa has the meaning of any kind of consumption (eating, burning incense). A possible explanation is a condensed phrase meaning "Afterwards, the one who is burning (the incense) (for the benefit of) the land (is) Giyorgis, ....

In any case the 24 person as well as the 12 deacons actually existed. For that reason, it should be reasonable to encode them with IDs.

**Comment by CarstenHoffmannMarburg** [comment]
> Thank you! As I wrote in the issue, I am not convinced that the last four records here are persons. I think they might refer to places or other entities (e.g. māḫbar).

As far as I understand your comment, there are 24 personalities needed. I count them as the follows:

1) ʿaqqābe saʿat (ex officio, unnamed in the list but in this case PRS10374Yohanne, who is mentioned above)
2) qis gabaz (unnamed, ex officio)
3) ማኅበር (PRS14261Mahbar)
4) ዝንጊታ (PRS14262Zengita)
5) ወምበየ (PRS14263Wambaya) 
6) የለዔላ (PRS14264Yalaela)
7) ጠልቃ (PRS14265Talqa forthcoming in the next Pull request) 
8) ሰውሰት (PRS14266Sawsat forthcoming in the next Pull request)
9) ሎዛ (PRS14267Loza forthcoming in the next Pull request)
10) መርቆርዮስ
11) ጊዮርጊስ 
12) ቍስቋም 
13) ድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ ፩፡ እንስሳ። (still a riddle to me)
14) ካህናተ፡ ሰማይ (also a personal name?)
15) ቀሌመንጦስ
16) ማርያም (female?!)
17) ወድኅሬሁ፡ በዐለ፡ ቤተ፡ ቍርዓ።  (unnamed inhabitant from a hamlet a Qwǝrʿā (place related to LOC7423QweraGadal or LOC7425BetaQweraTahtay as under discussion in https://github.com/BetaMasaheft/Places/pull/109)
18) ብእት፡ ኀይሉ
19) ብርሃን፡ መስቀል
20) ጠልቀይ 
21) ሐደራ
22) ወድኅሬሁ፡ ዘበልዐ፡ ምድረ፡ `<del rend="effaced" unit="chars" quantity="7"/>` (one more name that was effaced here)
23) ገብረ፡ ክርስቶስ
24) መቃርስ 

Do you have another suggestion?

**Comment by thea-m** [comment]
I would understand at least the proper names 1–22 as part of a function, inseparable from za-balʿa mǝdra. So, my interpretation (based only on this note without good knowledge of both genre and particular monastic community) would be that there is a person X who is "za-balʿa mǝdra kāhǝnāta samāy" etc.

**Comment by MagdaKrzyz** [comment]
I assume this indeed might be the order of incensing. As far as I known, even today incensing + prayer is done in the church nearly every day, at least once. The "order of incensing" here lists ecclesiastics who should perform the ritual, one after another. Not unexpectedly, the number of them is 24, according to the number of "heavenly priests", and the number of deacons is 12, like Apostles. Most of them "eat" from the lands assigned to the monastery (= get tributes). In a way, incensing is part of their work for the monastery, for which they are given the right to get subsistance.  It is difficult to say how long this order was followed after the text was written.

**Comment by MagdaKrzyz** [comment]
It was DN writing from Magda's laptop.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for your insightful comments! I will continue to encode these names as personal names, except for  ፩፡ እንስሳ።  and ካህናተ፡ ሰማይ, who continue to be mysterious to me.

**Comment by DenisNosnitsin1970** [comment]
"ካህናተ፡ ሰማይ" are 24 heavenly priests, there is a feast for them and a festive homily. It is like three youths in the oven. ፩፡ እንስሳ should be corrected to ፬እንስሳ Four heavenly creatures (the symbols of Evangelists). They also have a feast and a festive homily (even more than one). So both units are equivalent to saints and they have a veneration tradition. Hear are meant parcels of land supplying food etc. for those feasts, as I understand.

**Comment by CarstenHoffmannMarburg** [comment]
I can confirm, that  ፬፡ እንስሳ። is more plausible if compared to the other numbers in the manuscript.

If I understand you correct, all the 24 items do not refer to persons but to places, e.g. "..., afterwards the one, who used to eat from the land of (St) Giyorgis, ... , " This may also explain the presence of ማርያም and of ቍርዓ, that is likely a place name related to LOC7423QweraGadal and LOC7425BetaQweraTahtay mentioned in another addition in this manuscript.

**Comment by CarstenHoffmannMarburg** [comment]
What shall we do with the following entities:
ወድኅሬሁ፡ በዐለ፡ ወምበየ።
ወድኅሬሁ፡ በዐለ፡ የለዔላ።
ወድኅሬሁ፡ በዐለ፡ ጠልቃ። 
ወድኅሬሁ፡ በዐለ፡ ሰውሰት።
As far as I understand baʿal is a title preceding a personal name.

**Comment by DenisNosnitsin1970** [comment]
I assume (I am not 100% sure) that it is the case, this is a special way to refer to plots of lands, though the names of the saints etc for whose feasts the plots are suppose to provide food (of course not the plots themselves, but those who work on them - feudal state!). I remember, vaguely, I read about this somewhere (there is a small body of literature about land documents, and many are published). But in many cases they refer to the proper place names, and in a few cases some other terms may be used, neither saints nor toponyms, but menat for smth else. It is a technical system of referring to land. በዐለ፡ means "lord, ruler, governor". በዐለ፡ ወምበየ possibly means "governor of Wambaya", in my opinion.

**Comment by DenisNosnitsin1970** [comment]
Ba'alta Bihat - "the lady of Bihat"

**Comment by CarstenHoffmannMarburg** [comment]
In that case, it seems to me more appropriate to leave all these names unregistered, because we are not perfectly sure, what they mean. They may either be personal names, place names, names of Saints that refer to the land, that is dedicated to ensure their veneration or something else. Yet alone ወምበየ።, የለዔላ።, ጠልቃ።, ሰውሰት። and ቍርዓ can be encoded as place names according to your recommendation.

**Comment by CarstenHoffmannMarburg** [comment]
> Ba'alta Bihat - "the lady of Bihat"

I do not see any Ba'alta Bihat. Where did you find that term?

**Comment by DenisNosnitsin1970** [comment]
በአልተ፡ ቢሐት, it is the title, occurs in Dabra Libanos Gospels book of Ham, 
`https://betamasaheft.eu/simpleSearch.html?searchType=text&mode=any&query=%E1%89%A2%E1%88%90%E1%89%B5`

**Comment by DenisNosnitsin1970** [comment]
Also በዐልተ፡ ቢሐት፡

**Comment by CarstenHoffmannMarburg** [comment]
> https://betamasaheft.eu/simpleSearch.html?searchType=text&mode=any&query=%E1%89%A2%E1%88%90%E1%89%B5

Do you mean, this is a title of a work, that needs a LIT ID? Where is the similarity to the note, that is discussed here? I cannot access the Bm page on DabraLibanosHamGG1 at the moment.

**Comment by DenisNosnitsin1970** [comment]
This is not a work, but a 14th century title (of one of the queens), which is composed of ba'alt(ä) "lady" (fem. of ba'al) and place name "bihat" (a small place in Eritrea, unlikely in Bm), to illustrate the constructions like በዐለ፡ ወምበየ etc. are built up in the same way. This is how I would understand them. ወምበየ and the like are very old toponyms (if they are), from a purely local context, now for sure not to be found any longer in the same form, if at all.

**Comment by CarstenHoffmannMarburg** [comment]
OK. Now I got it. If I understand you correctly, you recommend to encode ወምበየ።, የለዔላ።, ጠልቃ።, ሰውሰት። as place names and their location should be around lake Hayq.

**Comment by DenisNosnitsin1970** [comment]
Yes, correct.

**Comment by eu-genia** [comment]
As commented under the PR

I would not really encode any of these
The term in phrases preceded by ba'al is surely always a place
But also the phrases balʿa mǝdra XX, even if some of these XX may originally be persons, are referring to my understanding to plots of land
Overannotating sometimes only creates confusion

**Comment by abausi** [comment]
I see all this only one: to my knowledge I full agree with the explanation provided by Denis and/or Magda, concerning the interpretation of "balʿa mǝdra" as "receiving tributes from land (for service)"; there are many other evidences for this and as far as I know, the expression is still understandable in present-day Amharic in this sense. For "baʿal", the same: it is a very common title, used to form common nouns as well as specific titles (some, but not all, also listed in the index of the _EAe_.
