### ISSUE TITLE
Deleting two work records

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2459]
It has been generously pointed out to me by @MassimoVilla that I have created two unnecessary work records. What we need is to:

delete LIT6699SixthSunday and keep LIT6745Dersan
delete LIT6690TewMidp and keep LIT6741Rakb

I will proceed unless there are objections.
@thea-m @CarstenHoffmannMarburg @eu-genia

**Comment by thea-m** [comment]
Thank you, please go ahead (maybe you already deleted LIT6699SixthSunday , in any case, it is not available anymore).

**Comment by MarcinKrawczuk** [comment]
No, it was a typo - the file is still there and the correct name
is LIT6699SixthSaturday.

czw., 11 sty 2024 o 15:53 thea-m ***@***.***> napisał(a):
