### ISSUE TITLE
New petty king Dāwit (1431/1432 AD) documented in EMML1832

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2460]
@eu-genia @thea-m @DenisNosnitsin1970 @karljonaskarlsson 

In a dated addition folio 23v in EMML1832 I found the name of a king called Dāwit. The note is dated to the year 6924 AM and 84 by Ethiopian measurement. According to Taddesse Tamrat and the Augustines calender, this corresponds exactly to the year 1431/1432 AD. Also the mentioned Patriarch PRS5706JohnXI and the Metropolitan PRS2469Bartalom and the Abbot PRS14249Benyam fit this date. 

The only problem is the name of the king, which cannot be Dawit I (PRS3429DawitII), who died in 1413, nor Dawit II (PRS6229LebnaDe), who was born later and reigned from 1508-1540. Looking at the list of kings according to wikipedia, ʿaḍe Takla Māryām (PRS9175TaklaMa) comes into question, but this king is documented as having the regnal name ሕዝበ፡ ናኝ፡. I am not aware of the possibility of a king having two different regnal names.

Taddesse Tamrat (bm:Taddesse1970Abbots, 104-105) concludes that it could be a 'minor king' who claimed sovereignty after the death of King Yǝsḥāq. Following Tamrat, I propose to create a new ID for Dawit as a petty king in 1431/1432. Other possibilities are also possible, but I think that Tamrat's explanation is the most reasonable.

Also, I have discovered PRS9176TaklaMa and I think it is a doublet of PRS9175TaklaMa and should be deleted. 

<img width="319" alt="Screenshot 2024_Dawit" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/6c2a8b1b-2e31-48d3-8cfa-e94a43892eca">
<img width="378" alt="Screenshot 2024_Tamrat_Dawit" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/c42bc2b0-ee8e-4248-b6e2-d7f10b94d9b5">

NB. I thank Jonas for already discussing the matter and therefore include him in this issue.

**Comment by thea-m** [comment]
I think the proposed solution is fine (I don't have the expertise myself to evaluate whether to postulate this new king makes more sense than to accept some dating inconsistency, which is also not so rare). Another possibility would be not to mark up the name, but describe to the uncertainty in a note.

**Comment by karljonaskarlsson** [comment]
To me, it also seems fine. I have no better solution to the problem.

**Comment by eu-genia** [comment]
PRS9175TaklaMa - ase Takla Maryam aka Hezba Nan, 15th century
PRS9176TaklaMa - ase Takla Maryam, 16th century, a puppet emperor installed by Hamalmal, see EAE II, 983a


I would go with the second suggestion of Dorothea, Dawit could be a honoriphic or regnal name of anyone, e.g. also Baeda Maryam was also a Dawit (he is between Dawit I and Dawit II)

**Comment by DenisNosnitsin1970** [comment]
Eugenia is right. The 15th-century king is mostly referred to/known as Takla Maryam or Hezba Nan. If I am not mistaken, more than one "royal name" is noticed for some kings, or some names which are difficult to classify.
