### ISSUE TITLE
Arabic work in Abb 161

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2463]
We need a new work record for the Arabic treatise included in Abbadie 161, “Nuzhat al-asrar", 
a hagiography of sheyh Hussein of Bale (it is printed in the book with the tag IHABook627, 
used in Bm several times). The info from A. Gori. 
The record LIT2078Nuzhat, the one I initially thought would fit, is smth different.

**Comment by eu-genia** [comment]
It is then the same as LIT3527IHA https://betamasaheft.eu/works/LIT3527IHA/main?

Ok

Maybe we can consider having a relation between Bm and IHA 

This makes me aware of an issue with all the IHA work records - they are visualized showing their number as if it were a CAe number which it is not, I must do something about it (suppress the CAe for records from IHA)

**Comment by DenisNosnitsin1970** [comment]
Yes, it is this work.

**Comment by DenisNosnitsin1970** [comment]
So, I am creating a record.

**Comment by DenisNosnitsin1970** [comment]
Sorry, all was in vain, the record LIT2077Nuzhat seems to be "Nuzhat al-ʾasrār wa-ṭahārat al-ʾaqḏār". No idea why it could not be noticed before. The new record was not necessary. I will transfer the contents from the new record to the old one.

**Comment by eu-genia** [comment]
Note that the new PR still must be merged and then the doublet deleted as a separate PR.

**Comment by DenisNosnitsin1970** [comment]
Yes, sure.
