### ISSUE TITLE
Hadiya sultanate vs. Hadiya zone/region

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2469]
@eu-genia @thea-m @DenisNosnitsin1970 

As far as I can see, we have only one ID for Hadiya - LOC3720Hadiyy, that is defined as region.

In Wikidata, there is a distinction between Hadiya zone (Q3125547) and the Hadiya sultanate (Q558596). To me, this distinction makes sense and I wish to create a new ID for the political entity and use it for the description note in EMML1832. Do you agree?

**Comment by eu-genia** [comment]
Yes, of course, it should be split.
