### ISSUE TITLE
Hagiography of Yohannes of Wifat

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2473]
I want to create IDs for hagiographic works about Yohannes of Wifat (PRS10419Yohanne). I think we do not have any.

**Comment by CarstenHoffmannMarburg** [comment]
It would also be nice to add some information to the floruit of the PRS ID.

**Comment by MarcinKrawczuk** [comment]
Sorry for cutting in (again... ) but I've noticed that a certain Yohannes of Wifat is registered in KRZ under no. 182, whereas this number in the BM database point to https://betamasaheft.eu/works/LIT1519GadlaY/main.

**Comment by DenisNosnitsin1970** [comment]
It is fine. Now we know that it is different, it is the Acts of Yohannes "the Oriental". The Acts of Yohannes of Wifat is a different tradition.
