### ISSUE TITLE
Prayer of penitence in BLorient11601

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2474]
@thea-m @DenisNosnitsin1970 @eu-genia 

I found a prayer in BLorient11601. Since the images are not available to me, I can compare the text yet alone according to the incipit given by Strelcyn. In comparison, I find, there is only little correspondence to the existing LIT on prayers for penitence. Do you think, it is appropriate to create a new LIT for this prayer based on the incipit in the Strelcyn-catalogue?

BLorient11601. f. 75v:
**ጸሎተ፡ ንስሓ፡ እግዚአብሔር፡** አምላክነ፡ **አኃዜ፡ ኵሉ፡** ፈዋሴ፡ ነፍሳቲነ፡ ወሥጋነ፡ ወመንፈስነ። እስመ፡ ትቤሎ፡ ለአቡነ፡ **ጴጥሮስ፡** በአፈ፡ ወልድከ፡ ዋህድ፡ እግዚእነ፡ ወአምላክነ፡ **ኢየሱስ፡ ክርስቶስ፡**

LIT2267salota in BNFet74 (p1_i1.2, f. 1v):
**እግዚአብሔር፡ አኃዜ፡ ኵሉ፡** አቡሁ፡ ለእግዚእነ፡ ወአምላክነ፡ ወመድኀኒነ፡ **ኢየሱስ፡ ክርስቶስ፡** አንተ፡ ውእቱ፡ ዘትፌውስ፡

little correspondence to LIT4523Prayer in BAVet55 (ms_i7, f. 59r-63r)
 **ጸሎተ፡ ንስሓ**። ዘወሀቦ፡ **እግዚአብሔር፡** **ለጴጥሮስ**፡ ወይቤሎ፡  ንሳእ፡ ወሀብኩከ፡ ዘንተ፡ መራኁተ፡ መንግሥተ፡ ሰማያት፡ ከመ፡ ትእስር፡ ወትፍታሕ፡ ይቤሎ፡ እግዚኣብሔር፡ አብ፡ ኢየሱስ፡ ክርስቶስ፡ ወልድ፨ ጸጋ፡ መንፈስ፡ ቅዱስ፨ ኤልሳኤልኮስ፨

**Comment by CarstenHoffmannMarburg** [comment]
According to Strelcyn, this prayer is edited in _Ya-beta krǝstiyān ṣalot_, Addis Abeba 1936 E. E. (= 1943/4) on page 27-28. I cannot identify this book and I don't, if it is available.

**Comment by DenisNosnitsin1970** [comment]
We have a couple of similar entries, in particular check LIT4523Prayer; search with ንስሓ. I assume this is one prayer, but possibly present in many variations.
