### ISSUE TITLE
Octateuch in Amharic

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2476]
@eu-genia @DenisNosnitsin1970 @thea-m 

BLorient12125 contains an Octateuch in Amharic. Incipits are given by Strelcyn but no other information on the origin of this translation. I tried to find a record on Amharic bible translations, but I did not find any. In that case, I propose to create 13 new IDs: 8 Books (Genesis, Exodus, Leviticus, Numbers, Deuteronomy, Joshua, Judges, Ruth) + a record for the enumeration of the 8 books + general record for Octateuch in Amharic + general record for the Old testament in Amharic + general record for the New testament in Amharic + general record for Bible translations to Amharic. I would set a relation from each of the Amharic books to its Geez counterpart, unless I do not know, if it is translated from Geez and I do rather even suspect, that it may be derived from a European language.

```
<msContents>
                        <summary/>
                        <msItem xml:id="ms_i1">
                            <locus from="1v" to="286v"/>
                            <title ref="LIT000000000000">Octateuch in Amharic</title>
                        <msItem xml:id="ms_i1.1">
                            <locus target="#1v"/>
                            <title ref="LIT00000000000">Enumeration of the Books of the Old Testament, 39 in number</title>
                            <incipit xml:lang="am">የብሉይ፡ ኪዳን፡ መጻሕፍት፡ እሊህ፡ ናቸው።</incipit>
                        </msItem>
                        <msItem xml:id="ms_i1.2">
                            <locus from="2ra" to="55vb"/>
                            <title ref="LIT00000000000">Genesis</title>
                            <incipit xml:lang="am">ኦሪት፡ ዘፍጥረት፡ በዕብራይስጥም፡ ብርሺት፡ ይባላል።</incipit>
                            <note>The leaves are numbered with some errors from 1 to 50.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.3">
                            <locus from="56r" to="101va"/>
                            <title ref="LIT00000000000">Exodus</title>
                            <incipit xml:lang="am">ኦሪት፡ ዘፀዓት። በዕብራይስጥም፡ ይባላል፡ ወኤሌ፡ ሸሞች፡</incipit>
                            <note>The leaves are numbered with some errors from 1 to 40.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.4">
                            <locus from="102ra" to="136vb"/>
                            <title ref="LIT00000000000">Leviticus</title>
                            <incipit xml:lang="am">ኦሪት፡ ዘሌዋውያን። በዕብራይስጥም፡ ወይቅራ፡ ይባላል።</incipit>
                            <note>The leaves are numbered from 1 to 27.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.5">
                            <locus from="137ra" to="188ra"/>
                            <title ref="LIT00000000000">Numbers</title>
                            <incipit xml:lang="am">ኦሪት፡ ዘኍልቍ። ዘዕብራይስጥም፡ ወይዳብር፡ ይባላል።</incipit>
                            <note>The leaves are numbered from 1 to 36.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.6">
                            <locus from="188va" to="228vb"/>
                            <title ref="LIT00000000000">Deuteronomy</title>
                            <incipit xml:lang="am">ኦሪት፡ ዘዳግም። በዕብራይስጥም፡ ኤሌ፡ ሐደፈሪም፡ ይባላል።</incipit>
                            <note>The leaves are not numbered.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.7">
                            <locus from="229ra" to="256rb"/>
                            <title ref="LIT00000000000">Joshua</title>
                            <incipit xml:lang="am">መጽሐፈ፡ ኢያሱ፡ ወልደ፡ ነዌ። በዕብራይስጥም፡ ይሆሹዓ። ይባላል።</incipit>
                            <note>The leaves are numbered from 1 to 24.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.8">
                            <locus from="256va" to="282ra"/>
                            <title ref="LIT00000000000">Judges</title>
                            <incipit xml:lang="am">መጽሐፈ፡ መሳፍንት። በዕብራይስጥም፡ ሾፍጢም፡ ይባላል፡</incipit>
                            <note>The leaves are numbered from 1 to 21.</note>
                        </msItem>
                        <msItem xml:id="ms_i1.9">
                            <locus from="282va" to="286v"/>
                            <title ref="LIT00000000000">Ruth</title>
                            <incipit xml:lang="am">መጽሐፈ፡ ሩት፡ ምዓባዊት።</incipit>
                            <note>The leaves are numbered from 1 to 4.</note>
                        </msItem>
                        </msItem>
                    </msContents>
```

**Comment by DenisNosnitsin1970** [comment]
It looks like there should be these new records. There is a slight chance that what Strelcyn recorded as Octateuch in Amharic is in fact a commentary in Amharic, but Cowley 1988 "Ethioopian Biblical Interpretation" does not list this ms. There seems to be hardly any notice of this manuscript, anywhere (EAE "Bible: Bible translation into Amharic" does not consider the manuscripts). There are two more manuscripts which contain Amharic OT (along with parallel Geez translation): Addis Abeba, IES 77 (I have it, "Royal Biblie" of HSI I can share it with you, and NALA BBM 362) which perhaps should be considered. Another strange thing about Ms 12125 is that it is of a very moderate size (with 24 lines per page). 
It is pity that it cannot be consulted in any way.

**Comment by CarstenHoffmannMarburg** [comment]
Me too, it makes me suspicious, that every book is introduced with its Hebrew name and the number of folia is often too few to contain the entire book. It might be a commentary in the form of a mere paraphrase that made Strelcyn think it would be the proper text. Shall I proceed anyway and add these concerns in the manuscript record?

**Comment by DenisNosnitsin1970** [comment]
I think so.

**Comment by thea-m** [comment]
Records for the Biblical books in Amharic do not exist. Several manuscripts containing them are described in  Zotenberg's catalogue, but I used the "Geez" work records when encoding them, only encoding the text's language as Amharic (see BNFet24 for example). 
This now seems not ideal to me: if we create unique IDs for different recensions of one work in one language, we should also create them for the work in another language - this would also highlight translations as intellectual and creative projects in their own right. I cannot remember whether we discussed it at the time (possibly related to https://github.com/BetaMasaheft/Documentation/issues/85, but even the principles proposed there were not adhered to in case of the Amharic Biblical books). 
Unless @eu-genia remembers whether there were good reasons to do otherwise, I would now be in favour of creating records for the Amharic Biblical books.

**Comment by eu-genia** [comment]
well, so far we have not produced separate work records even for Greek / Hebrew / Syriac / Coptic / Arabic versions of the same texts, íntroducing for them `t2 ``t3 ``t4 `etc with the relevant language and referring in the title to the relevant subID.
treating each language as a different text would mean thorough revision of data and a fundamental decision of treating texts existing in different languages and assigning clavis numbers.
@abausi should clearly have a say if we should revise the way we have been treating multi-lingual textual traditions so far.
I do understand that local languages for us are somewhat special, but the approach cannot be different.
I personally would be against creating separate records for the same text translated, it seems to go against the principle of a Clavis to me, but there surely may be other opinions.

of course if this is not a translation but a truly different text (e.g. commentary) then it is a different matter.

**Comment by eu-genia** [comment]
see e.g. LIT2290Sargis as an example

if we treat each language as a separate work - what do we then align to other Claves, like CPG or CC?

**Comment by DenisNosnitsin1970** [comment]
Probably Geez versions first, because versions in colloquial languages are normally secondary. Actually, we do not know exactly what it is, and to which extend it is a translation of a Geez version (which one?), and not smth else. For me it is fine if this Amharic version can be clearly individuated, and this is a special case which is not properly studied yet.

**Comment by abausi** [comment]
I would be in favour of having separate new IDs for whatever can be better described in the Ethiopian tradition (i.e. Geez, Amharic etc.). This is essential in order to do what Bm has to do. The issue of alignement is very comlex because not all Claves have the same scope. For exmplae CPG includes also the versions under the same number; others, like CANT, at times uses sub-numbers. In any case, this Amharic Bible or biblical paraphrase seems to be too important not to receive an ID of its own.

**Comment by CarstenHoffmannMarburg** [comment]
I understand the outcome of the discussion that most of you think it is appropriate to create the LIT IDs as I have described above for the Octateuch books (8 books + enumeration + Bible + OT + NT) in Amharic. @eu-genia: Do you agree with this or do you want us to think about it again? 

Do you think it would be useful to create LIT IDs for the other biblical books as well, and rework the existing manuscript records accordingly? At some point it may also be necessary to make a distinction between different translations, whether they are foreign, i.e. Catholic or Protestant translations based on Latin or other European versions, or whether they are based on Geez.

**Comment by eu-genia** [comment]
Sure, let us keep it as a definition for work in clavis - versions in different languages when they are present in Ethiopic mss get an independent ID.  They still may be aligned to the external claves each.

The distinction for the translation should be made in `relation`, there is a `saws `relation.

Yet this discussion raises more questions:

If one starts doing all this properly then one needs to create separate IDs also for the Geez Bible versions, so far we have not distinguished pre/post-revision, so the EAG mss use the same ID as the recent ones.

And: is this exception for the local languages or a general rule for all languages? We might have to go through existing records.

Does this apply to the Tetraglot/Pentaglot mss, at the moment referring to the same biblical ID with the specification of the language?

**Comment by CarstenHoffmannMarburg** [comment]
> I cannot remember whether we discussed it at the time (possibly related to #85, but even the principles proposed there were not adhered to in case of the Amharic Biblical books).

I think the discussion in #85 is not appropriate in this case, because it is primarily concerned with the question of how to refer to a possible source of a given Ethiopic text. I think it is legitimate to refer to the Greek, Arabic, Latin or other possible source texts in the way that has been done so far, because on the one hand they are related to Ethiopic texts, but on the other hand they are beyond the limits of Ethiopian manuscript culture and therefore they should be referred to with clavis IDs and titles encoded, but they should not get their own IDs in Beta masaheft.

Amharic translations of biblical texts, on the other hand, are a different case, because they circulate in the Ethiopian manuscript culture and have their own impact. In principle, it should be possible to create a separate ID for each biblical book and, if necessary, for each recension.

However, in the example of BLorient12125, it is not clear which version of the biblical text is involved, and for others it may be the same. If it is decided to rework or recode the other cases mentioned (IES 77, NALA BBM 362, BNFet24, Tetraglot/Pentaglot), additional records may be needed and can be created. For the moment, I propose to create IDs only for the books mentioned in the Strelcyns catalogue for BLorient12125.
