### ISSUE TITLE
Request to encode EMML 6971

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2479]
I would like to encode EMML 6971 - is that OK?

https://w3id.org/vhmml/readingRoom/view/200596

@DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
of course. 
we have LOC6431Zammad but we need an INS for the repository, can you create it? we do not have it yet I believe
thank you

**Comment by MarcinKrawczuk** [comment]
Sure, I will create the record for repository.

**Comment by MarcinKrawczuk** [comment]
Just a gentle remainder that my question is still open @eu-genia

**Comment by eu-genia** [comment]
there are too many authority lists around ) we align to wikidata wherever possible, and wikidata allows to align to all others
I have created Q124526652 that should be linked via sameAs property (ex. 4 here https://betamasaheft.eu/Guidelines/?id=places)
