### ISSUE TITLE
Tārika Walda ʾAmīd

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2483]
@eu-genia @thea-m @DenisNosnitsin1970 

I want to update LIT4723TarikaWaldaAmid. I have seen the enormous work that Dorothea has done already on the basis of Manfred Kropps edition and Lazarus Goldschmidts catalogue. However, I want to update the titles, abstract and bibliography. In addition, I want to create two records as sub IDs for the two recensions, that I discovered during my work on my dissertation.

**Comment by thea-m** [comment]
That sounds great!

**Comment by DenisNosnitsin1970** [comment]
Thanks!
