### ISSUE TITLE
Abb 154 new ID for text

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2484]
I need a new Id for the text of Amharic commentary by mal'aka sehay Wasan of Gojjam, from Ms Abb 154 (probably unique witness). 
hope there is no objections.

**Comment by eu-genia** [comment]
sure, go ahead.

**Comment by eu-genia** [comment]
has this been done?

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Works/pull/1055
