### ISSUE TITLE
Malkǝʾ of the Trinity

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2485]
@DenisNosnitsin1970 @eu-genia 
There is a text in BLorient8817, f. 88ra-9v, that is described by S. Strelcyn as "Malkǝʾ of the Trinity". There are a number of works encoded as "Hymn to the Holy Trinity" or "Malkǝʾ-hymn to the Holy Trinity". The beginning in BLorient8817 is missing and the incipit starts ex abrupto. Images are not available to me. That makes it difficult to me to find the correct ID.

```
 <msItem xml:id="ms_i2">
                            <locus from="88ra" to="90v"/>
                            <title ref="LIT0000000000000000000" type="incomplete">Malkǝʾ of the Trinity</title>
                            <note>The beginning is missing and the incipit starts ex abrupto.</note>
                            <incipit xml:lang="gez">ድር፡ ወሰማይ። አሠርግው<cb n="88rb"/>ኒ፡ ሥላሴ፡ በቀጠንተ፡ ምግባር፡ ሠናይ። ወረስዩኒ፡ ሐዳሰ፡ እምነ፡ ልማዱ፡ ብሉይ። 
                                ለባዕል፡ ዘተሣለቆ፡ ወዘተጓህለዎ፡ ንዋይ። እንዘ፡ በዴዴሁ፡ ይግዕር፡ እል<supplied reason="omitted" resp="Strelcyn">አ</supplied>ዛር፡ 
                                ድውይ። ሰላም፡ ለእራኃቲክሙ፡ እለ፡ አኃዛ፡ ዓለመ።</incipit>
                        </msItem>
```

I found LIT2933RepCh214, but no correlation with the given text to the one in EMIP00007. 

Other options are ...
LIT3067RepCh347
LIT3051RepCh331
LIT4632Hymn
LIT2981RepCh262
... and possibly many more.

How can I figure out, which one is the possible ID for this text.

**Comment by thea-m** [comment]
Maybe @smaugustine recognizes the text spontaneously. If that is not the case, I would say it is also legitimate to describe it as "unidentified Malkǝʾ-hymn"

**Comment by CarstenHoffmannMarburg** [comment]
I looked up LIT3067RepCh347 in BNFet77. 

I found no correlation either.

**Comment by CarstenHoffmannMarburg** [comment]
I could not check LIT3051RepCh331, because no manuscripts are listed and Chaîne 1913 gives only incipits, that we do not have for BLorient8817.

LIT4632Hymn is available in BAVet91, that has no images.

LIT2981RepCh262 is availabe in two BL-manuscripts that are either not available.

**Comment by eu-genia** [comment]
here is the full text https://debelodatastore.blob.core.windows.net/debelocontainer/Files/SundaySchool/MelkeaSelassie.pdf

**Comment by eu-genia** [comment]
LIT2736RepCh20

**Comment by DenisNosnitsin1970** [comment]
This is the composition which starts: ሰላም ለህላዌክሙ ዘይመውዕ ህላውያተ። ለረኪበ ስሙ ኅቡእ አመ ወጠንኩ ተምኔተ። እምግበርክሙ ሥላሴ ሶበ ረከብኩ አስማተ።
it is number 11 in the edition that I have at hand, Malke'a guba'e 1959 AM,  መልክአ ሥላሴ on pp. 189-210, the quotation of Strelcyn on  page 201.

**Comment by CarstenHoffmannMarburg** [comment]
I can confirm that this is the same text sent by Eugenia in a link in Chaîne as no. 20 (encoded as LIT2736RepCh20) sent by Eugenia in a link, and that is witnessed in BLorient8817. I therefore conclude that the BLorient8817 record can remain as it was recently merged, correct? 
Do you think it would be useful to add the reference to Zotero and to the work record of LIT2736RepCh20? In Zotero, I found bm:1955MalkeaGubae and bm:MalkaGubae1974, but I think these are different editions from the one you sent me via Facebook.

**Comment by eu-genia** [comment]
I have added the entire text to LIT2736RepCh20

**Comment by DenisNosnitsin1970** [comment]
The edition can be added to Zotero, for sure, strange that it is not there yet.

**Comment by CarstenHoffmannMarburg** [comment]
I added the title according to the information from the title page (without author and place): bm:MalkaGubae1959

**Comment by eu-genia** [comment]
I have corrected the title, note that titles in Fidel must be provided in Fidel with transcription and translation
መልክአ፡ ጉባኤ፡ (Malkǝʿa Gubāʾe, ‘Collection of Malkǝʿ-hymns')
And we do not write "printed in Publishing House XX" but simply the name of the publishing house

in Zotero we have also the editions from 1948 AM, 1974 AM, 1996 AM, 2010 AM

**Comment by eu-genia** [comment]
Note also that as the main date we always take the date in GC so instead of 1959 we write 1966/1967, and note the Ethiopian calendar in the Extras

**Comment by eu-genia** [comment]
I assume since it is printed by Tasfā in his private press, then Tasfā Gabra Śǝllāse is the editor
