### ISSUE TITLE
new CAe ID

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#2486]
I would like to ask for a new work ID for the text Gadla Sosǝnnā. Thank you!!

TITLE:
Gadla Sosǝnnā, ገድለ ሶስና, Life of Susanna

GENERAL DESCRIPTION:
A text belonging to the [Beta ʾƎsrāʾel] (https://betamasaheft.eu/persons/ETH1274Betaes/main) (Ethiopian Jewish) literatur. It stands in close relation to the Christian Homily on the Archangel Michael (for Naḥase, CAe 3966).

Text Bibliography:
Stenhouse, Paul. ‘Further Reflections on the Falasha and Samaritan Versions of the Legend of Susanna’. In Between Africa and Zion: Proceedings of the First International Congress of the Society for the Study of Ethiopian Jewry, edited by Steven Kaplan, Tudor Parfitt, and Emanuela Trevisan Semi, 94–102. Jerusalem: Ben-Zvi Institute, 1995.

Wurmbrand, Max. ‘A Falasha Variant of the Story of Susanna’. Biblica 44/1 (1963): 29–45.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for proposing a new LIT ID for Gadla Sosǝnnā! I will create a new work record by the end of this week, if there is no objection by @DenisNosnitsin1970 or @eu-genia.

**Comment by SophiaD-M** [comment]
Dear Carsten,

I am just now back to work and able to check. The entry is quite empty until not. Lacking the details I gave you above.

https://betamasaheft.eu/works/LIT6939GadlaSosenna/main#t1?hi=Sos%C7%9Dnn%C4%81

Would it be possible to include them? 
thank you very much!
Sophia

**Comment by eu-genia** [comment]
Dear Sophia please check the relevant pull request, not the issue, it is linked above and you were tagged https://github.com/BetaMasaheft/Works/pull/1063
