### ISSUE TITLE
Amharic versions of Nagara Māryām and Maṣḥafa nuzaze

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2487]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found two Amharic texts in BLorient13223, that are described by Strelcyn as "Amharic versions of  Nagara Māryām and Maṣḥafa nuzaze" with their incipits. According to our recent discussion in https://github.com/BetaMasaheft/Documentation/issues/2476, I propose to create sub-IDs for the Amharic versions of both texts and link them to the Geez-versions (LIT2051Nagara and LIT1956Mashaf).

**Comment by eu-genia** [comment]
OK for me

**Comment by eu-genia** [comment]
But our discussion was about first level IDs. Please do not confuse - sub-IDs are derived IDs hidden inside of the main record and referrable through e.g. `LIT2051Nagara#t2amh`
