### ISSUE TITLE
Commentary on the Mystery of the Incarnation, in Amharic

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2488]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found an Amharic text in BLorient13223, described as a Guest text on f. 45r-46v by Strelcyn with the following incipit:

የትስብእትና፡ የመለኮት፡ ተዋህዶ፡ እንዴት፡ ነው፡

The same incipit is recorded as well in EMIP00269 in ms_i4 in f. 21r-26v.

I want to create an LIT ID for this text with the title given in EMIP00269 (Commentary on the Mystery of the Incarnation, in Amharic).

**Comment by DenisNosnitsin1970** [comment]
Ok.  Please check if it is not a part of the Five Pillars of Mystery.

**Comment by CarstenHoffmannMarburg** [comment]
I compared it to LIT1097Ammest as it is attested in EMIP00646 (especially f. 44r, where the Trinity is discussed), but I did not find correlations. መለኮት፡ and ተዋህዶ are absent from this text. The presence of እንዴት፡ ነው፡ is coincidental. So I assume, these are different texts.
