### ISSUE TITLE
New Salām to places connected to Jesus

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2489]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found a new Salām in Strelcyns description of **BLorient2198** on f. 27v. I could not find a suitable work ID for it. The incipit given in Strelcyns catalogue is the following: ሰላም፡ ለኪ፡ ኦሃገረ፡ ገሊላ፡ ኀበ፡ አብስራ፡ ገብርኤል፡ ለማርያም፡ ህየ፡ ንሰግድ፡ ኵልነ፡ ኀበ፡ ተሰብአ፡ እግዚእነ። ሰላም፡ ለኪ፡ ኦቤተ፡ ልሔም፡  According to Strelcyn this piece is missing in Chaîne Répertoire.

In examining the manuscript records, I found a similar text in ESap046 on f. 81 that contains a **miracle of the Paraclete** (Taʾammǝra samāʿtāta Ṗarāqliṭos / LIT5878MiraclesParaqlitos). It also contains the phrase ሰላም፡ ለኪ፡ ኦቤተ፡ ልሔም፡, that is attested in Strelcyns incipit, unless the preceding phrase is different. I cannot investigate it further, because I do not have images of BL manuscripts.

```
<lb facs="#facs_81_r1l9" n="9"/>ሰላም፡ ለኪ፡ ሖ
				<lb facs="#facs_81_r1l10" n="10"/>ይመተ፡ አብርሃ
				<lb facs="#facs_81_r1l11" n="11"/>ም፡ ወልደ፡ ታራ፡ 
				<lb facs="#facs_81_r1l12" n="12"/>ወደብተራ፡ ሙ
				<lb facs="#facs_81_r1l13" n="13"/>ሴ፡ ሞተ፡ ሰዊራ፨
				<lb facs="#facs_81_r1l14" n="14"/>**ሰላም፡ ለኪ፡ ቤ** 
			<cb facs="#facs_81_r2" n="b"/>
                  <lb facs="#facs_81_r2l1" n="1"/>**ተ፡ ልሔም፡** መቅ
				<lb facs="#facs_81_r2l2" n="2"/>ደሰ፡ ልደት። ወ
				<lb facs="#facs_81_r2l3" n="3"/>ብዕዳን፡ ለኪ። 
				<lb facs="#facs_81_r2l4" n="4"/>ናዝሬት፡ ዐፀይ፡ 
				<lb facs="#facs_81_r2l5" n="5"/>ግዝረት፨ ሰላም፡ 
				<lb facs="#facs_81_r2l6" n="6"/>ለኪ፡ ቀራንዮ።
				<lb facs="#facs_81_r2l7" n="7"/>መካነ፡ ስቅለት፡ 
				<lb facs="#facs_81_r2l8" n="8"/>ወብዕዓን፡ ለኪ፡
				<lb facs="#facs_81_r2l9" n="9"/>፡ ጎልነታ፡ መቃ
				<lb facs="#facs_81_r2l10" n="10"/>ብረ፡ ንጉሥ፡ ው
				<lb facs="#facs_81_r2l11" n="11"/>ጌቲሴማኒ፡ መቃ
				<lb facs="#facs_81_r2l12" n="12"/>ብረ፡ ንግሥት።
```

I want to create a LIT ID for the salām that is found in **BLorient2198** and point to the possible relation to Taʾammǝra samāʿtāta Ṗarāqliṭos as recorded in ESap046.

**Comment by DenisNosnitsin1970** [comment]
Is the text in BLorient2198 described as salam or malke'?
Probably to indicate a relation would be good (possibly the Miracle quotes the poem, even though I can imagine that 
the image Mary - Betlehem may be of wide use, occuring in multiple works).

**Comment by eu-genia** [comment]
I think the phrase ሰላም፡ ለኪ፡ ኦቤተ፡ ልሔም፡ alone is not enough for identification or even a relation.
There is a standard ziq for Teqemt https://www.ethiopianorthodox.org/churchmusic/zema%20timehert%20bet/mahlet%20yared/11%20aququam%20zewerha%20beal/zewerha%20beal.html (see number 23 here, one can here it sung ))
It could be a widely used topos/epithet from the liturgy.
Do go ahead for a new ID; if Strelcyn says it is not in Chaîne I would assume he checked )

**Comment by CarstenHoffmannMarburg** [comment]
> Is the text in BLorient2198 described as salam or malke'? Probably to indicate a relation would be good (possibly the Miracle quotes the poem, even though I can imagine that the image Mary - Betlehem may be of wide use, occuring in multiple works).

The text in BLorient2198 is described as Salām by Strelcyn. According to his description, it is inscribed on one folio only (27v), that it shares with the end or another text. A folio has 9 to 13 lines in this rather small codex, so it appears to me to be relatively short.

```
<msItem xml:id="ms_i5">
                            <locus target="#27v"/>
                            <title type="incomplete" ref="LIT0000000000000000000000">Salām to places connected with the life of Jesus</title>
                            <note>Only the beginning of the text is preserved. Missing in <bibl><ptr target="bm:Chaine1913Rep"/></bibl>.</note>
                            <incipit xml:lang="gez">ሰላም፡ ለኪ፡ ኦሃገረ፡ ገሊላ፡ ኀበ፡ አብስራ፡ ገብርኤል፡ ለማርያም፡ ህየ፡ ንሰግድ፡ ኵልነ፡ ኀበ፡ ተሰብአ፡ እግዚእነ። 
                                ሰላም፡ ለኪ፡ ኦቤተ፡ ልሔም፡ </incipit>
                        </msItem> 
```
