### ISSUE TITLE
New LIT for "Predications about the birth of Christ made by the Prophets"

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2490]
@eu-genia @DenisNosnitsin1970 @thea-m 

In **BLorient2198,** there is another piece, that is entitled "Predications about the birth of Christ made by the Prophets" by S. Strelcyn:
```
<msItem xml:id="ms_i6">
                            <locus from="28r" to="30r"/>
                            <title type="incomplete">Predications about the birth of Christ made by the Prophets</title>
                            <note>The beginning of the text is missing.</note>
                            <incipit xml:lang="gez">ኀዲስ፡ ሥርዐት፡ ይመጽእ፡ እግዚእ፡ በቀሉ። ሰሎሞን፡ ይቤ፡ ገነት፡ ዕፅው፡ ወአዘቅተ፡ ሕትምት፡ ከማሁ፡ አንቲ፡ ውእቲ፡ ብኵርናተ፡ 
                                ዚአኪ። ይቤ፡ አሞጽ፡ እፀንሖ፡ ለእግዝትንቢት፡ በእንተ፡ ልደት፡ ለክርስቶስ፡</incipit>
                        </msItem>
```

I could not identify it to any LIT in Bm. In the manuscripts, I found some correlating words in a Weddase Maryam in **BMLacq812** (transkribus text). However, I think these are coincidence and should not be regarded as relationship:

				<lb facs="#facs_174_r1l30" n="11"/>ገነት፡ ዕፅው፡ አዘቅት፡ ኅተም፡ልደት፡ ለክርስቶስ፡

I propose to create a new LIT ID for the text reported by Strelcyn for BLorient2198.

**Comment by CarstenHoffmannMarburg** [comment]
Do you think this text needs its own ID or should I leave this text without LIT ID?

**Comment by eu-genia** [comment]
I do not know if this text is a part of some Commentary we already have.
I agree the allusion to the same passages of OT as the Weddase Maryam (the Wisdom of Solomon I guess in this case) does not mean much, there probably are many texts quoting from the same biblical books.
I think a new ID is in place here.
