### ISSUE TITLE
Chrysostoms's homily on the Nativity

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2491]
There is a record for Chrysostoms's homily on the Nativity: https://betamasaheft.eu/works/LIT2135OntheN. Currently six manuscripts refer to this work record.

However, it seems to me that only Berlin Ms. orient. Fol. 117 and BnF Éthiopien 109 contain the homily where the texts corresponds nicely to CPG 4560 beginning with መንክር፡ ምስጢሩ፡ ወልዑል፡ ኦፍቁራንየ፡ etc. 

The other manuscripts contain a homily which is indeed "entitled" as homily on Nativity by Chrysostom but the text seems entirely different and begins with ምንት፡ እንግር፡ ወምንት፡ እነብብ፡ etc. (cf. https://betamasaheft.eu/manuscripts/ESap005/viewer). To be precise, they are not available online, but the content of this homiliary (which is labelled as CAe 5856) does not vary a lot so I guess one could assume that they indeed have it.

Would it make sense to create a work record for the "other" homily on Nativity with the incipit ምንት፡ እንግር፡ ወምንት፡ እነብብ፡?

BTW, I have checked Proverbio's book but it doesn't help much.
@MassimoVilla @eu-genia @DenisNosnitsin1970 @thea-m

**Comment by eu-genia** [comment]
thank you, sounds good to me
MY-002 is now online, unfortunately not much can be done for BL but sure chances are high that they have the same text
