### ISSUE TITLE
Malkəʾ for John the Baptist

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#2492]
I would like to add a malkəʾ for John the Baptist known to me from two manuscripts, EMML 6993 (ff. 64va–67rb) and EMDA 118 (ff. 192ra–194vb). Its 49 stanzas begin:

(1) ሰላም፡ ለፅንሰትከ፡ ውስተ፡ ከርሠ፡ መካን፡ ኤልሳቤጥ፨\
ለመልአከ፡ ዜና፡ ገብርኤል፡ በብስራተ፡ ቃሉ፡ ጽዑጥ፨\
በኵረ፡ ቅድሳት፡ ዮሐንስ፡ እንዘ፡ ሕፃን፡ ቅጥቁጥ፨\
እፎ፡ ተክህልከ፡ አስተብርኮ፡ ለፅንሰ፡ መለኮት፡ ሥሉጥ፨\
ቅድመ፡ ትፍታሕ፡ ማሕፀነ፡ ወትፃእ፡ እምውስጥ፨\
\
(2) ሰላም፡ ለልደትከ፡ ስዱሰ፡ ወርኃ፡ ዘቀደሞ፨\
ለልደትከ፡ አምላክ፡ ሕያው፡ እማርያም፡ ጼና፡ አበሞ፨\
...\
\
(3) ሰላም፡ ለዝክረ፡ ስምከ፡ ዘሳብዕ፡ ውጣኔሁ፨\
ወሳድስ፡ ፍጻሜሁ፨\
...\
\
(49) ሰላም፡ ለበድነ፡ ሥጋከ፡ እንተ፡ እምባሕርይ፡ ትጸሪ፨\
ወኢተዐርቅ፡ ለግሙራ፡ እምጸጋ፡ መለኮት፡ ፈጣሪ፨\
ሥርናየ፡ ማሕሌትየ፡ ዘንተ፡ በሥልጣንከ፡ ገባሪ፨\
ረሲ፡ ሊተ፡ በበ፡ ፷፡ ወበበ፡ ፻፡ ዘይፈሪ፨\
ዮሐንስ፡ አምዳኖ፡ (sic) ዮሐንስ፡ ሰንኮሪ፨

It can be clearly distinguished from the shorter `LIT2999RepCh279`. With respect to that record, I notice that there is a superfluous `LIT6724ImageJB` which I have checked is identical to `LIT2999RepCh279` and so they should be merged.

I could add the record for the new malkəʾ, but perhaps someone else would be better to handle the duplicate records, unless it makes sense to reuse the duplicate for this new malkəʾ? 

There is also a record for a 'መልክአ፡ ዮሐንስ፡' with a relation to John the Evangelist (`LIT1870Malkea`) but there is no text, incipit, or witness nor is it linked in any manuscript entries that I can find.

**Comment by eu-genia** [comment]
Thank you, I was not sure about the hymn in the GS, if it is the same as LIT2999RepCh279 surely it is better to merge the records and use LIT6724ImageJB for the hymn you are describing, as LIT6724ImageJB has not yet been pointed from elsewhere.

EMDA 118 - I could not find it on vHMML, I would create a stub but is there an institution to it?

(for the future - tag those of us who you want to have a look at the issue, we are not automatically notified otherwise)

**Comment by smaugustine** [comment]
My assumption has been that EMDA 118 is from Moṭā Giyorgis based on the adjacent numbers, but I've been meaning to ask Mersha what metadata he has about it (I'm assuming he's the one to ask?).

**Comment by eu-genia** [comment]
He would not have the EMDA metadata, I have been struggling with this https://github.com/BetaMasaheft/Documentation/issues/2360#issuecomment-1978234696 
(we have received from him MG manuscripts with all different shelfmarks, so I am trying to do the mapping, and have been through all EMDA mss from MG, but 118 is not among them)

**Comment by eu-genia** [comment]
but indeed it does fall into the range https://hmml.org/collections/repositories/ethiopia/mo%E1%B9%AD%C4%81-giyorgis-church/ possibly not online yet
