### ISSUE TITLE
Magic prayer against enemies

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2496]
I found a set of magical prayers in BLorient4611, described as: "magical prayers, the first against enemies." by S. Strelcyn. Is it reasonable to create a LIT ID for the first prayer, that is recorded with its incipit:
```
<item xml:id="a2">
                                    <locus from="1v" to="2v"/>
                                    <desc type="GuestText">Several magical prayers, the first against enemies.</desc>
                                    <q xml:id="gez">በስመ፡ <gap reason="ellipsis"/> ካዕበ፡ ቍልዝ፡ አፋዝ፡ <gap reason="ellipsis"/> በኃይለ፡ ዝንቱ፡ አስማቲከ፡ እስር፡ 
                                        አቅዝዝ፡ አዘዝክሙ፡ ሐተምክሙ፡ ለፀርየ፡ ወለጸላእትየ፡ <gap reason="ellipsis"/></q>
                                </item>
```
I did not find any text correlating with this phrase except for combination of እስሮሙ ፡ ለፀርየ ፡ ወለጸላእትየ in LIT1758Lefafa, that is likely to be incidental in my opinion.

@DenisNosnitsin1970 @eu-genia @thea-m

**Comment by thea-m** [comment]
I would say according to our principles regarding protective texts, yes
