### ISSUE TITLE
Magic Prayer against snake venom, measles, smallpox, and manṭaṭa (በስመ፡ አብ፡ በል።)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2497]
In his catalogue S. Strelcyn describes a prayer in BLorient6466 (f. 1r) as "Magic Prayer against snake venom, measles, smallpox, and manṭaṭa". These horrible things all appear in the incipit/title: በስመ፡ አብ፡ በል። ሕብዘ፡ አርዌ፡ ምድር፡ በሊህ፡ እግርኪ፡ ታሕተ፡ ከናፍርኪ፡ ... ኢትሕምም፡ አባለ፡ ሥጋሃ፡ ... እምፈንፃፃ፡ ወኩፍኝ፡ ወእመንጣጣ፡
The prayer starts with በስመ፡ አብ፡ በል just like LIT5086MagicPrayer. Beyond that, I found no relevant coincidence to any LIT record.
Do you agree to create a new LIT record for this prayer?

@eu-genia @DenisNosnitsin1970 @thea-m

**Comment by eu-genia** [comment]
I could not find this specific prayer either, ok to a new record
