### ISSUE TITLE
Prayer to the Virgin Mary - baʾǝnta ḍaʿu-ni lǝmudāna ḍabʿ

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2499]
@eu-genia , @DenisNosnitsin1970 @thea-m 
I found a prayer in a guest text in BLorient8816 on f. 178v. The text is described by Strelcyn by the title "Prayer to the Virgin Mary" and by the incipit በእንተ፡ ፀብዑኒ፡ ልሙዳነ፡ ፀብዕ፡ ወአብቀው፡ አፉሆሙ፡ ላዕሌየ፡ አፈ፡ ኃጥእ፡ Nevertheless, I was not able to identify this text. Can you help me?

**Comment by eu-genia** [comment]
I do not think this prayer has been assigned an ID.
In the past, we did not bother to assign ID to each text appearing as an additio, many of these are hapax legomenon, so there is for the moment no need to necessarily assign IDs to each passage found; it is already helpful if the incipits are provided, in case the prayer is re-encountered somewhere else, at this point an ID must be created.
"ወአብቀው፡ አፉሆሙ፡ ላዕሌየ" seems to be a quote from Psalter (Psalm 21:31)
