### ISSUE TITLE
mastabqʷǝʿ in BLorient5268

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2500]
@eu-genia @DenisNosnitsin1970 @thea-m @LeonardBahr 

S. Strelcyn describes a text in **BLorient5268** as **"deprecatory prayers"** with the title "መስተበቍዕ፡" in the text. He refers to BnF éth. 309 in Grébaut's description (bm:Grebaut1938GriauleI, pp. 24-26). I do not have access to the images because, as far as I know, the British Library server is still down. 

I do not know which ID fits this case. It is difficult for me to understand whether Strelcyn meant that the text in BLorient5268 is _exactly_ the same as that in BNF éth. 309, or whether he means to say that these are deprecatory prayers / mastabqʷǝʿāt _similar_ to those described in Grébauts' catalogue. In the first case, I think it would be reasonable to create a new ID for this work, which apparently exists in these two manuscripts. In the other case, it might be useful to have a generic ID for any kind of mastabqʷǝʿ. I don't think LIT4713Liton or any of the existing IDs fit this function, or have I missed something?

Strelcyn (1978) on BLorient5268 (p. 36):
![Screenshot 2024-03-15 101818](https://github.com/BetaMasaheft/Documentation/assets/40291787/a26526c0-f728-484c-816c-ba7cffe4f612)

Grébaut (1938) on BNF éth. 309:
![Screenshot 2024-03-15 101614](https://github.com/BetaMasaheft/Documentation/assets/40291787/79d12f4c-0fc3-4711-ad7e-297cdeaf69cc)

**Comment by eu-genia** [comment]
LIT4713Liton  is just one of the many supplications we already have in the database.
But in the absence of text and therefore exact identification it is always better to use the generic ID LIT4711Mastabqwe

**Comment by DenisNosnitsin1970** [comment]
You can use LIT4711Mastabqwe.
