### ISSUE TITLE
A prayer to the Lord in BLorient4930 and BAVet97

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2502]
@eu-genia @thea-m @DenisNosnitsin1970 

I found a prayer in one of the flyleaves in BLorient4930. According to Strelcyn, the prayer begins: እግዚአብሔር፡ ዓቢይ፡ ወግሩም። ዘአልቦቱ፡ ጥንት፡ ወኢተፍጻሜት። ወይሄሉ፡ ለዓለመ፡ ዓለም። እስእለከ፡ ወአስተበቍዓከ። ከመ፡ ትርድአኒ፡ ወትባልሐኒ። 

I discovered the same text in BAVet97 as LIT4691Prayer#Monday within a cycle of "prayers for the weekdays". However, in BLorient4930 it exists independently. I suppose it should have its own LIT ID for this reason.

BAVet97
```
<msItem xml:id="ms_i4">
<locus from="71" to="82"/>
<title type="incomplete" ref="LIT4691Prayer">Prayers for the weekdays</title>
     <msItem xml:id="ms_i4.1">
         <locus from="71r"/>
          <title type="complete" ref="LIT4691Prayer#Monday"/>
          <incipit xml:lang="gez"> እግዚአብሔር፡ አምላክ፡ ዓቢይ፡ ወግሩም፡ ዘአልቦ፡ ጥንት፡ ወኢተፍጻሜት፡ ወይሄሉ፡ <supplied reason="lost">እስከ፡ ለዓለ</supplied>ም፡ እስእለ<supplied reason="lost">ከ፡ ወኣስተበቍ</supplied>ዓከ፡ ከመ፡ ትርድአኒ፡ ወትባልሐኒ፡ ወታድኅነኒ፡ እምኵሉ፡ ዘእፈርህ፡ ወእትዓቀብ፨ ወአእትት፡ እምኔየ፡ እከዮ፡ ለሰይጣን፨</incipit>
          <explicit xml:lang="gez">ኦእግዚኦ፡ አድኅነኒ" እመከራ፡ ሥጋ፡ ወነፍስ፡ ለገብርከ፡ ናትናኤል፡ የብ<gap reason="illegible" unit="chars" quantity="2"/>፨</explicit>
<note>The name of <persName ref="PRS11695Natnael">Nātnāʾel</persName> is mentioned in the supplication formula at the end of the text.</note>
</msItem>                       
(...)
</msItem>
```

**Comment by eu-genia** [comment]
I am not sure if copying as an additio means independent circulation as a separate text; I would use `LIT4691Prayer#Monday`

**Comment by DenisNosnitsin1970** [comment]
If it is an excerpt, I would use LIT4691Prayer#Monday.
