### ISSUE TITLE
Prayers, Litany and Genealogy in BLorient8814

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2505]
@DenisNosnitsin1970 @eu-genia @thea-m 

There are a number of text in BLorient8814, that I could not identify and that I want to create LIT IDs for.

a) A text (65ra-75rb) beginning with: በስመ፡ ... ዓለም፡ ልብና፡ እግዚአብሔር፡ ዘክዱን፡ ብከ፡ ዕበይከ፡ ወስውር፡ ብከ፡ ኃይልከ፡ በከመ፡ ሰወርኮ፡ እምዓይነ፡ ሞት፡ ለሄኖክ፡ ነቢይ፡ በተአምኖ፡ ዘአስመረከ፡ ክድነኒ፡ ወሰውረኒ፡ በክንፈ፡ ረድኤትከ፡ እምኀፅ፡ ዘይሰርር፡ በመዓልት፡ ወእምግብር፡ ዘየሐውር፡ በጽልመት፡ 
I did not find any similarity to any recorded text. Referred to as "Prayer" by Strelcyn, but seems to be a very long text to be counted as a simple prayer.

b) Litany to the Virgin Mary (75rb-77ra):
ማርያም፡ ድንግል፡ ሰአሊ፡ ለነ፡
ወላዲተ፡ አምላክ፡ ሰአሊ፡ ለነ፡
ማርያም፡ ቅድስት፡ ሰአሊ፡ ለነ፡
ማርያም፡ ንጽሕት፡ ሰአሊ፡ ለነ፡  
I found various texts with ሰአሊ፡ ለነ፡ followed by  ማርያም፡ ድንግል፡ or an epiteth, but no one with the adressed Virgin in front. I think, this is a new Litany.

c) A "Genealogy of Ethiopian monks" (77ra-78rb) እምደብረ፡ ሊባኖስ፡ was written at the end of this text, in the margin. The name could refer to INS0346DL or to INS0341DL. For the first three representatives, this genealogy is similar to that attested in LIT6341CCR34. After that it is different. I propose to create a new LIT for it an mark the similarity in a relation.
ወእምድኅሬሁ፡ ያንብቡ፡ ዘንተ፡ መጽሐፈ፡ ልደቶሙ፡ ለአበው፡ መ<cb n="77rb"/>ነኮሳት፡ 
                                እንጦ<supplied reason="undefined" resp="PRS8999Strelcyn">ን</supplied>ስ፡ ወልዶ፡ ለመቃርስ፡ መቃርስ፡ ወለዶ፡ ለጳኵሚስ፡ 
                                ጳኵሚስ፡ ወለዶ፡ ለአረጋዊ፡ ዘደሞ፡ አረጋዊ፡ ወለዶ፡ ለመስቀል፡ ሞአ። ወመስቀል፡ ሞአ፡ ወለዶ፡ ለክርስቶስ፡ ቤዛነ። ወክርስቶስ፡ ቤዛነ፡ ወለዶ፡ ለዮሐኒ። ዮሐኒ፡ ወለዶ፡ 
                                ለኢየሱስ፡ ሞአ፡ በቀሚስ፡ ወበቅናት። ኢየሱስ፡ ሞአ፡ ወለዶ፡ ለአቡነ፡ ተክለ፡ ሃይማኖት፡ በቀሚስ፡ ወበቅናት፡ ነሥአ፡ ቆብዓ፡ ወአስኬማ፡ በደብረ፡ ዳሞ፡ በእደ፡ አቡነ፡ ዮሐኒ። 
                                ወእምዝ፡ አቡነ፡ <pb n="77va"/> ተክለ፡ ሃይማኖት፡ ተመይጠ፡ እምድኅረ፡ ነሥአ፡ ቆብዐ፡ ወአስኬማ፡ ኀበ፡ 
                                <placeName ref="LOC3832Hayq">ሐይቅ፡ ባሕር፡</placeName> ወወሀቦ፡ ለአቡሁ፡ ኢየሱስ፡ ሞአ፡ 

d) A "Hymn to the Virgin Mary" (79ra-85vb). To my surprise, I found no parallel to the marked incipit with ʾo-nafs
በስመ፡ ... ኦነፍስ፡ ኦነፍስ፡ ሶበሰ፡ ተአምሪ፡ መካነ፡ ደይን፡ ዘየኀድሩ፡ ውስቴታ፡ ዕቡያን፡ ወውስተ፡ አጽናፊሃ፡ መፍርህ፡ እንዘ፡ ያንኵረኵርዎሙ፡ ለዝኁራን፡ ርእስኪ፡ 

e) A text (f. 96ra-97vb), referred to as "Hymn (salām?) to Jesus Christ" by Strelcyn. The beginning of each stanza is missing, what makes it more difficult to identify. The first stanza was documented by Strelcyn:
... ዘጠጣ። 
እስራኤል፡ ወይሁዳ፡ ኃለፉ፡ በውሥጣ፤
በክቡር፡ ደሙ፡ ለነፍስየ፡ ዘተሣየጣ።
ካዕበኒ፡ በሰበነ፡ ርእሱ፡ ዘሦጣ።
ለማር[ያም]፡ ድንግል፡ አፍአ፡ ወውሥጣ።

I found a similarity to an unidentified prayer in EMIP2368, f. 11v-12r and 34r-34v, that starts with ይትባረክ፡ እግዚአብሔር፡ ለባሕረ፡ ኤርትራ፡ ዘሠጠጣ እስራኤል፡ ወይሁዳ፡. Unfortunatly it is not possible to access images with larger portions of the text.

Do you agree to create new LIT ID for each one or have I missed something?

**Comment by eu-genia** [comment]
looks good

we have all images for EMIP, but many stubs lack the `facs n="?"` information, I have inserted it in 2368, everyone can do it when needed see https://github.com/BetaMasaheft/Documentation/issues/2017 with a link to a spreadsheet with all necessary parameters

**Comment by CarstenHoffmannMarburg** [comment]
> looks good
> 
> we have all images for EMIP, but many stubs lack the `facs n="?"` information, I have inserted it in 2368, everyone can do it when needed see #2017 with a link to a spreadsheet with all necessary parameters

Thank you Eugenia! I can confirm, that this is the same hymn. In EMIP02368 it has 13 stanzas.

**Comment by DenisNosnitsin1970** [comment]
Sorry, this went a little too quick, with the genealogy. Please check, we have LIT6591MonGenealogy general record, LIT3143Ledata for genealogy of Dabra Libanos of Shewa (the dominant one, I do not know any genealogy issued from DL of Ham; I see that you text comes close to it). Perhaps the indication "general record" can be added also to LIT3143Ledata, because genealogies exist in varying versions.

**Comment by CarstenHoffmannMarburg** [comment]
> LIT3143Ledata

I apologise for being too quick with a new LIT! I can confirm that the genealogy in BLorient8814 is essentially the same and therefore to be identified with LIT3143, as it is attested for example in BNFet50. All representatives are the same, while some phrases in between are different deviating text, as I also checked from the pictures:
```
<item xml:id="a25">
  <locus target="#19r" facs="f39"/>
  <desc type="GuestText"><title ref="LIT3143Ledata">Abridged history of the monasteries founded by <persName ref="PRS9162TaklaHa"/> and his disciples</title>, slightly shortened at the end</desc>
   <q xml:lang="gez">ንወጥን፡ ልደተ፡ አበዊነ፡ መነኮሳት። አባ፡ <persName ref="PRS1962Anthony">እንጦንስ</persName>፡ ለብሰ፡ ልብሰ፡ ምንኵስና፡    በሥምረተ፡ እግዚአብሔር፡ በእደ፡ መልአክ። አባ፡ <persName ref="PRS1962Anthony">እንጦንስ</persName>፡ ወለዶ፡ ለአባ፡
   <persName ref="PRS6427Macarius">መቃርስ፡ ዘየዓቢ</persName>፡
   <gap reason="omitted" extent="unknown" resp="PRS10747Zotenbe"/></q>
</item>
```

**Comment by CarstenHoffmannMarburg** [comment]
However, not all the manuscripts recorded as witness of LIT3143Ledata appear to be this text in fact. The list attested in FSUor40 (p. 203-204) according to my observation has no correspondence to LIT3143Ledata apart from the reference to Dabra Libānos:

![Screenshot 2024-03-25 081317](https://github.com/BetaMasaheft/Documentation/assets/40291787/13cca5dd-92a5-4e2c-bcb2-706810f5e2ac)
![Screenshot 2024-03-25 081456](https://github.com/BetaMasaheft/Documentation/assets/40291787/4697f485-749d-4d15-b86f-a9466d461169)

Eventually the FSUor40 record should be corrected and the new ID (LIT6948GenealogyMonks) could be used for the list in FSUor40 instead?

**Comment by DenisNosnitsin1970** [comment]
Carsten, the text from FSUor40 is not a genealogy, it is exactly a list of the abbots of Dabra Libanos of Shawa (no doubt, it is that one, the role of that of Ham was insignificant). Lists of abbot are  much less frequent, they are different from the monastic genealogy (but both to get keywords "historiography", as these are primitive historiographic works).

**Comment by eu-genia** [comment]
For the list of abbots we have LIT4983ListDabra

**Comment by eu-genia** [comment]
So if you have a monastic genealogy (that is Mashafa ledatu, ending and not beginning with Takla Haymanot), you can either use LIT3143Ledata (general record) or create a specific one if it is clearly a specific recension

If you have a list of abbots of Dabra Libanos beginning with Takla Haymanot (and thus clearly only Dabra Libanos of Shoa may be implied) you can use LIT4983ListDabra as a general record

Please check if the content created can go into LIT4983ListDabra

**Comment by CarstenHoffmannMarburg** [comment]
> So if you have a monastic genealogy (that is Mashafa ledatu, ending and not beginning with Takla Haymanot), you can either use LIT3143Ledata (general record) or create a specific one if it is clearly a specific recension
> 
> If you have a list of abbots of Dabra Libanos beginning with Takla Haymanot (and thus clearly only Dabra Libanos of Shoa may be implied) you can use LIT4983ListDabra as a general record
> 
> Please check if the content created can go into LIT4983ListDabra

There is only one witness (IVorlov20), that provides no images for checking the text. However, I think, it is probable, that the list in FSUor40 is related and I should express this probability in a relation.

**Comment by eu-genia** [comment]
I think that there is no need to multiply entities.
If you have a list of abbots then use the CAe ID for the list of abbots, LIT4983ListDabra - any list of abbots of DL, always beginning with Takla Haymanot, then Elsa, etc etc.
Genealogy is a more complex text with several version and from the issue I had thought that you wanted to create a record for a version of the genealogy.

**Comment by CarstenHoffmannMarburg** [comment]
OK. In this case, I will delete LIT6948GenealogyMonks and use LIT4983ListDabra in FSUor40.

**Comment by CarstenHoffmannMarburg** [comment]
If there are no objections, I will start to create LIT IDs for a), b) and d).
