### ISSUE TITLE
Prayer to Jesus commemorating the Passion in BLorient13273 and EMIP02171

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2509]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found a text in BLorient13273 described in Strelcyn as "Prayer to Jesus in 26 stanzas commemorating the Passion". The long incipit is also found in EMIP02171. Unfortunately images are not available in either case.

BLorient13273
```
<msItem xml:id="ms_i8">
                            <locus from="121v" to="127r"/>
                            <title ref="LIT0000000000000000000000000000000">Prayer to Jesus commemorating the Passion</title>
                            <note>In twenty-six stanzas.</note>
                            <incipit xml:lang="gez">ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ መድኅነ፡ ዓለም። ኈልቈ፡ ሕማማቲከ፡ ዘከሠትከ፡ ሎን፡ ለሠላስ፡ ደናግል፡ ቅዱሳት፡ እለ፡ ይሰመያ፡ ቅድስት፡ 
                                ቢርዜዳ። ወቅድስ<supplied reason="undefined" resp="PRS8999Strelcyn">ት</supplied>፡ ሚልቲዳ። ወቅድስት፡ ኤልሳቤጥ፡ እላ፡ እማንቱ፡ 
                                ዘነጸራከ፡ ሥራይ፡ ኃጢአትየ። እስመ፡ አነ፡ ኃጥእ፡ ገብርከ፡ <gap reason="illegible"/></incipit>
                        </msItem>
```

EMIP02171
`<summary>(....) <locus target="#63r"/>-69v: Prayer on the Passion of Jesus Christ, which Jesus revealed to Matilda, Bridget and Elizabeth, ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ መድኅነ፡ ዓለም፡ ኈልቈ፡ ሕማማቲከ።**  (...) </summary>`

I suggest creating a LIT ID for this text attested in these two witnesses.

**Comment by DenisNosnitsin1970** [comment]
It seems there is no ID for that; you will find a couple more items if you look for ሕማማቲከ.

**Comment by CarstenHoffmannMarburg** [comment]
Thanks for the recommendation. I found KopCodEtiopAdd13 and EMIP01909, that have the same similarities judged from the incipit. I will mention them in the LIT record, as far as we decide to create one.

**Comment by eu-genia** [comment]
thank you
images EMIP02171 and EMIP01909 should be are visible now (it is enough to add n="numberOfImages" in `facs`)

**Comment by CarstenHoffmannMarburg** [comment]
I was able to identify the same text in EMIP01909 and BLorient13273. 

In EMIP02171 contrary to the description in the record, contains another text on f. 63r-69v but not the indicated "Prayer on the Passion of Jesus Christ, which Jesus revealed to Matilda, Bridget and Elizabeth" with the seeked incipit ኦእግዚእየ፡ ኢየሱስ፡ ክርስቶስ፡ መድኅነ፡ ዓለም፡ ኈልቈ፡ ሕማማቲከ።. There must be an mistake in the description of EMIP02171.

However, I think, it is fair to create a new LIT for "Prayer on the Passion of Jesus Christ, which Jesus revealed to Matilda, Bridget and Elizabeth" as indicated in EMIP01909, BLorient13273 and KopCodEtiopAdd13.

**Comment by eu-genia** [comment]
thank you
