### ISSUE TITLE
New LIT ID for Hassaba heg

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2510]
@DenisNosnitsin1970 has proposed to create a new LIT record for the work, that is attested in BLorient13269 and in IVorlov34, because the text in these manuscripts judged by the incipits in the catalogues is different to LIT6563HassabHeg (Cf. https://github.com/BetaMasaheft/Manuscripts/pull/2339). Do you agree?

@eu-genia @thea-m

**Comment by eu-genia** [comment]
OK
