### ISSUE TITLE
Prayer over the water and over the oil in BLorient13156 and BerOrOct59

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2513]
@eu-genia @DenisNosnitsin1970 @thea-m 

I found a prayer in BLorient13156, that has a striking parallel in BerOrOct59. It is "to be recited over the water in which a sick person is to bath and over the oil with which he is to be anointed for healing" as Strelcyn puts it.

BLorient13156
```
<msItem xml:id="ms_i4">
                            <locus from="96r" to="111v"/>
                            <title ref="LIT00000000000000000000">Prayer of the Virgin Mary to her Son</title>
                            <note>To be recited over the water in which a sick person is to bath and over the oil with which he is to be anointed for
                                healing.</note>
                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ለከ፡ ንወጥን፡ በረድኤተ፡ እግዚአብሔር፡ አምላክነ፡ ሎቱ፡ ስብሐት፡ በእንተ፡ 
                                ጽሒፈ፡ ጸሎት፡ ዘ፳፩፡ ዘእግዝእትነ፡ ድንግል፡ ማርያም፡ ንግሥተ፡ ኵሎን፡ አንስት፡ ወእሙ፡ ለሕይወተ፡ ኵልነ፡ ኢየሱስ፡ ክርስቶስ፡ እግዚእነ፡ ዘይትነበብ፡ ላዕለ፡ ማይ፡ 
                                ወየሐጽብዎ፡ ለድዉይ፡ ወይጼልዩ፡ ላዕለ፡ ዘይት፡ ወይቀብእዎ፡ ወይትፈወስ፡ </incipit>
                        </msItem>
```

BerOrOct59
```
<msItem  xml:id="p2_i4">
                     <locus from="67r" to="81r"></locus>
                     <title> One of the 21 prayers of Mary, prayed over water, oil and images. </title>
                     <textLang mainLang="gez"> </textLang>
                     <incipit xml:lang="gez"><hi rend="rubric"> በስመ፡ አብ፡ ወወልድ ወመ</hi>ንፈስ፡ ቅዱስ፡ አሐዱ፡ አምላ<hi rend="rubric">
                     ክ። ለከ፡ ንወጥን፡ በረድኤተ፡ </hi> እግዚአብሔር፡ አምላከነ፡ ሎ<hi rend="rubric">ቱ፡ ስብሐት፡ በእንተ፡ ጽሒፈ፡</hi> ጸሎት፡ ዘእም፳ወ፩ለእግዚእትነ፡
                     ድንግል፡ ማርያም፡ <gap reason="ellipsis"/> ዘይትነበብ፡ ላዕለ፡ ማይ፡ <gap reason="ellipsis"/> ወጼልዩ፡ ላዕለ፡ ዘይት፡
                     </incipit>
                     </msItem>
```

I did not find a LIT with this text and therefore I want to create a new ID.

**Comment by eu-genia** [comment]
was LIT6729PrayerWater created for this? I can see it in the app but not in GitHub.

**Comment by eu-genia** [comment]
I think [LIT6729PrayerWater ](https://betamasaheft.eu/LIT6729PrayerWater.xml) can be used for this record, unless it has already been created.

**Comment by CarstenHoffmannMarburg** [comment]
I updated the manuscript records (BLorient13156 and BerOrOct59). I suggest to add these as witnesses as well as an incipit and an abstract to LIT6729PrayerWater. However, I cannot find it in Oxygen, either. I think it needs to be pushed and merged, before it can be updated.

**Comment by eu-genia** [comment]
LIT6729PrayerWater is NOT in github, it was created in the app but never synced, you need to save the xml from the link above to the `new `folder and proceed as usual
