### ISSUE TITLE
church Fārṭā ʿĀdiko Gabrǝʾel?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2517]
BAVet120 and BAVet145 have ownership notes starting with "ዝ፡ መጽሐፍ፡ ዘበጌምድር፡ ፋርጣ፡ ዓዲኮ፡ ገብርኤል፡ ዘወሀቦ፡ ገብረ፡ ሥላሴ፡..."
"Gabrǝʾel" was previously interpreted as the name of a person, but I wonder whether this is the name of a church. Does anyone happen to know it? I only found Fārṭā as a region.
@DenisNosnitsin1970 @Addisie @eu-genia @CarstenHoffmannMarburg

**Comment by DenisNosnitsin1970** [comment]
ፋርጣ፡ ዓዲኮ፡ ገብርኤል፡ this is definitely a church name; even though; I do not know it.

**Comment by Addisie** [comment]
ዓዲኮ፡ ገብርኤል is a church name. It is found near the city of Dabra Tābor and ፋርጣ is one of the districts found in south Gondar.

**Comment by eu-genia** [comment]
Thank you! That is we need also Fārṭā warada, ʿĀdiko tabiya, and then ʿĀdiko Gabrǝʾel church located there

**Comment by DenisNosnitsin1970** [comment]
It looks like today ፋርጣ is warada and ʿĀdiko is what today is called ፀጉር አዲኮ ቀበሌ. Gemination is not known, maybe without.

**Comment by thea-m** [comment]
Thanks everyone
(@Addisie agrees that there is no gemination)
