### ISSUE TITLE
new record for 1 John 1-7

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2518]
I suggest to create an independent ID for the beginning of 1 John (1-7), which is occasionally attested in additions as a guest text (for example, BAVet150, BLadd24992, EMIP00017).
@DenisNosnitsin1970 @eu-genia @CarstenHoffmannMarburg

**Comment by thea-m** [comment]
Nevermind :) LIT5905FidalaHawarya

**Comment by DenisNosnitsin1970** [comment]
Ok, this is different.
