### ISSUE TITLE
Lost PRS records from Tanasee1

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2519]
@eu-genia @thea-m 

I still have a branch "PRS IDs in Tanasee1 (no. 21)" on my github-desktop, but I cannot find this branch among the pull requests on github website. Does this mean, that this branch was already merged and I can delete it on my github desktop?

I wanted to look up several records, but my search for PRS14212BatsagaQirqos and PRS14213Yosef lead to the response 

`Something has gone wrong and there are more than one item with id PRS14213Yosef.`

    /db/apps/expanded/persons/new/PRS14213Yosef.xml
    /db/apps/expanded/persons/PRS14001-15000/PRS14213Yosef.xml"

What was wrong?

**Comment by thea-m** [comment]
It has be merged (https://github.com/BetaMasaheft/Persons/pull/765), I believe @eu-genia is needed to deleted the  doublet in the app

**Comment by eu-genia** [comment]
fixed
