### ISSUE TITLE
Amharic version of the Maṣḥafa śǝrʿat

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2520]
@DenisNosnitsin1970 @eu-genia @thea-m 

I found a text in BLorient13278 which is described as an "Amharic version of the Maṣḥafa śǝrʿat" by Strelcyn. Strelcyn also gave the title "Yaḥǝgǝnnā yaśǝrʿat maṣḥaf", which I do not find explicitly in the incipit.

The Gǝʿǝz should be LIT1968Mashaf.

The Amharic piece in BLorient13278 on the other hand has some similarities to LIT5933CommMuallaqa. However, I compared the text with the only witness in EMIP00031. I do not think that the similarities are strong enough to make an identification of this text with LIT5933CommMuallaqa. I would rather propose a new ID as an Amharic version of the Maṣḥafa śǝrʿat, which in my opinion is a translation rather than a commentary.

BLorient13278 according to Strelcyn:
<img width="804" alt="Screenshot 2024_Mashafa serat (Amharic)" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/6abc825c-8dc4-44d2-a10b-1580efadb6c4">

LIT5933CommMuallaqa in EMIP00031:
![Screenshot 2024-04-18 122844](https://github.com/BetaMasaheft/Documentation/assets/40291787/1120fa1d-8ade-461c-b8fc-8f498e2215aa)
<img width="482" alt="Screenshot 2024_Ms2" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/39fcf11b-6ea1-4c02-b23b-838e07938de7">
<img width="488" alt="Screenshot 2024_Ms3" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/4481e510-e404-418b-aa47-c2661ae6e061">

**Comment by eu-genia** [comment]
ok, the similarities may be mentioned in the `abstract`
