### ISSUE TITLE
Images ESqmb001

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2522]
@eu-genia 

The images of https://betamasaheft.eu/manuscripts/ESqmb001 are not displayed in my firefox.

**Comment by CarstenHoffmannMarburg** [comment]
The same also in google.

**Comment by eu-genia** [comment]
wrong filenames, fixed

**Comment by CarstenHoffmannMarburg** [comment]
Thanks!


________________________________
Von: Eugenia ***@***.***>
Gesendet: Montag, 22. April 2024 10:36
An: BetaMasaheft/Documentation
Cc: Hoffmann, Dr. Carsten; Assign
Betreff: Re: [BetaMasaheft/Documentation] Images ESqmb001 (Issue #2522)


wrong filenames, fixed
