### ISSUE TITLE
new IDs for protective prayers in BAVet128 - 1

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2524]
I would like to create new IDs for the following protective prayers attested in BAVet128 (translations are according to the catalogue)

1. Prayer against amenorrhea: ጸሎት፡ በእንተ፡ ማቈይ፡
     Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/>` ይሚና፤ ለባራ፤ ፋም፡ ላም፡ ታውም፡ ብርትውም፡</incipit>
Explicit ንያም፡ ሌበራ፡ ሰዮንም፡ ያፎንም፡ ዲያንትም፡ ዲያትስ። 

2. Prayer against stomachache
Incipit: ጸሎተ፡ ትቅማጥ፡ ሊሶ፡ አፍሊስ፡ ሜሎስ፡ `<gap reason="ellipsis"/>` በዝንቱ፡ አስማቲከ፡ አንተ፡
                          አውግዘከ፡ `<gap reason="ellipsis"/>` አወግዘከ፡ በሰዶር፡ ወበአላዶር፡ በዳናት፡ ወበአዴራ፡ ሮዳስ፡ ስምከ፡ ወበ፭ ቅንዋቲሁ፡
                        አወገዘከ፡ በልደቱ፡ ወበጥምቀቱ፡ በትንሣኤሁ፡ ወበዕርገቱ፡
Explicit በአብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ አወግዘከ፡ ጥብጥ፡ ሰይጣን፡ ለዓለመ፡ ዓለም፡ አሜን፡ ወተዓትብ፡ ገጸከ፡
                        ፫ ጊዜ፨

3. Prayer for the healing of wounds:
Incipit  በስመ፡ አብ፡  `<gap reason="ellipsis"/>`ጸሎተ፡ ቁስል፡ አመ፡ ረገዝዎ፡ ለእግዚእነ፡ የማናይ፡ ገቦሁ፡ እንተ፡
                       ኢ ጽዔአት፡ ወኢመግለት፡
Explicit ሹቸኙዌ፡ ኡራኤል፡ ፄያሄል፡ ድማሄል፡ በዝንቱ፡ አስማቲከ፡ ፈውስ፡ ቍስለ፡ ገብርከ፡

@CarstenHoffmannMarburg @DenisNosnitsin1970 @eu-genia 

(More will follow, I am splitting them into several issues so that they can be reasonably be dealt with)

**Comment by CarstenHoffmannMarburg** [comment]
I did not find anything relevant.
