### ISSUE TITLE
New IDs for protective prayers in BAVet128 - 3

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2526]
I would like to create new IDs for the following protective prayers attested in BAVet128 (translations are according to the catalogue)

1. Prayer 
Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/>` ወእምቅድመ፡ ፍጥረቶሙ፡ ለመላእክት፡ ወሰማይ፡ ወምድር፡ ወበዘነበርከ፡ 
                        ብዙኅ፡ መዋዕል፡ ዲበ፡ ሠረገላ፡ ኪሩቤል
Explicit: ወተማኅፀንኩክሙ፡ ከመ፡ ኢይቅረቡ፡ ኃይለ፡ ፀላዒ፡ ወፀር፡ ወቄዳር፡ ወመንደፍ፡ ዛር፡ ባርያ፡ ጥቍር፡ ለቀቲል፡ ከመ፡ ኢይቅረቡኒ፡
                        ለገብርከ።

2. Prayer against blacksmiths
Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/> ` ጰራቅዮን፡ ጰራቅዮን፡ ጰራቅዮን፡ በዝንቱ፡ ስምከ፡ ዘሰለርከ፡ መናግሥቲሆሙ፡ ለነሀብት፡ ወትሰብር፡ ሐፂን፡ ወከማሁ፡ ስብር፡ መናግሥቲሆሙ፡ ለነሀብት፡
Explicit: ወከማሁ፡ አጥፍእ፡ እሳቶሙ፡ ለነሀብት፡ ቄዳር፡ ከመ፡ ኢያውዕዩ፡  ብርተ፡ በውስተ፡ እሳት፡ ዘገበርከ፡ እምድር፡ እስከ፡ ፋሌክ፡  ሰማይ፨

3. Another Prayer against blacksmiths
Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/>`  በከመ፡ ተአስረት፡ ኃምስ፡ ሰማይ፡ ወከማሁ፡ እስር፡ <sic>ነሀብት፡</sic> ቄዳር፡ በስመ፡ ዚአከ፡ ብርሃናኤል፡
Explicit: ዘወሀብኮ፡ ኃይለ፡ ወመዊዓ፡ ለሶምሶን፡ ዘነገርኮ፡ ስምከ፡ ለእስጢፋኖስ፡ ዲያቆን፡ ፩ስምከ፡ ሜሎስ፡ ከመ፡ ይማኦ፡ ለሰይጣን፡ ከመ፡ ይማኦሙ፡ ለነሀብት፡ ቄዳር፡ ከማሁ፡ ሀቦ፡ ኃይለ፡  ለገብርከ።

@CarstenHoffmannMarburg @DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
ok
