### ISSUE TITLE
Protective prayers in BAVet128 - 4

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2527]
I would like to create new IDs for the following protective prayers attested in BAVet128 (translations are according to the catalogue)

- Prayer against sorcerers
Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/>` ጸሎት፡ ወስእለት፡ በእንተ፡ እለ፡ ይቀትሉ፡ ሰብአ፡ ወመሠርያን፡ ወዝውእቱ፡ ወዘያስተኃፍሮሙ፡ ላዕለ፡ መሠርያን፡ አስማተ፡ እግዚአብሔር።  ታዶያል፡ ኢያኤል፡ ጼዴያል፡
Explicit: ኮሮስ፡ ሄሎስ፡ ላፍን፡ ራስ፡ ኤሮስ፡ ወእምኵሉ፡ ዘየዓቢ፡ ስምየ፡ አልፋ፡ ፀባዖት፡ በዝንቱ፡ አስማት፡ ተማኅፀንኩ፡ አነ፡ ገብርከ፡  ለዓለመ፡ ዓለም፡

- Prayer against diseases and wounds
Incipit: በስመ፡ አብ፡ `<gap reason="ellipsis"/>` ጸሎት፡ ወስእለት፡ በእንተ፡ ድኅነት፡ እምሕማመ፡ ወበእንተ፡ ኵናት፡ ወንድፈተ፡ ሐፅ፡ ወትደግም፡ ዘንተ፡ አስማተ፡ ወትብል፡ ግራእድ፡ ግራኤል፡ እግዚእ፡ ኢያኤል፡ ኡራኤል፡
Explicit: አአሃኵኤል፡ አኩኤልግሲ፡ ጸባዖት፡ መርዮቶን፡ ወበዝንቱ፡ አስማቲከ፡ አድኅነኒ፡ ወእምኵሉ፡ ዘእፈርህ፡ አነ፡ ገብር፤

Prayer with ʾasmāt 
- Incipit: በስመ፡ ሥሉስ፡ እዌጥን፡ ዘንተ፡ አስማተ፡ ሳጦር፡ እፌጦር፡ እፌጦስ፡ አይአር፡ አሮአይአድ፡
Explicit: በዝንቱ፡ አስማቲከ፡ አድኅነኒ፡ እምዕንባዜ፡ ልብየ፡ እምተግባረ፡ ሰብእ፡ ተማኅፀንኩ፡ በእግዚአብሔር፡ አብ፡ ወበክርስቶስ፡  ወልድ፡ ወበሣልሳይ፡ መንፈስ፡ ቅዱስ፡ ጰራቅሊጦስ፡ ተማኅፀንኩ፡ አነ፡ ገብርከ፡  ለዓለመ፡ ዓለም፡ አሜን።

@CarstenHoffmannMarburg @DenisNosnitsin1970 @eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any relevant similarities to other manuscripts.
