### ISSUE TITLE
Subāʿe ʾErmyās nabiy 330wa3subāʿe ʿǝlatāt

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2533]
There is a text with the incipit ሱባዔ፡ ኤርምያስ፡ ነቢይ፡ ፫፻፴ወ፫ሱባዔ፡ ዕለታት፡ in `BLorient484#ms_i4` and in `BLorient492#a3`, at the moment without ID but cross-referenced one to the other
(`<msItem xml:id="ms_i4" corresp="BLorient492#a3">` in BLorient 484 and `<ref type="mss" corresp="BLorient484#ms_i4">Same text as in ms BL orient 484, item 4</ref>` in BLorient492)
It would probably be cleaner to create an ID and point there from both mss - or is there something that speaks against it?

@thea-m @CarstenHoffmannMarburg @DenisNosnitsin1970

**Comment by thea-m** [comment]
I do not know this text, but it seems reasonable :)
