### ISSUE TITLE
lost works from BLorient686?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2536]
@MarcinKrawczuk can you please check, there are some links from BLorient686 that seem to point to nowhere, possibly some work records were not synced? I cannot find them

1.35 points to LIT6503Gadl - we have the CAe number used for LIT6503GadlaMarqos but it lists a different witness so I am not sure that this is what is meant
1.38 points to LIT6504Mashafa - I could not find it either, also in the old branches

thank you!

**Comment by eu-genia** [comment]
1.35 should be Sebastian
1.38 should be Eusebius

I guess something did not sync properly, new work records should be created, I will do that if there are no objections

**Comment by MarcinKrawczuk** [comment]
I will look into that in the late afternoon/evening, OK?

śr., 8 maj 2024 o 10:00 Eugenia ***@***.***> napisał(a):

**Comment by eu-genia** [comment]
no worries I have fixed (I hope), just let me know if something is not correct, otherwise all good ) thanks!

**Comment by eu-genia** [comment]
also 1.47=LIT6207CyriacusVictor not there, recreating. From the text by Bausi this is a text different from LIT4845Martyr present in BLorient690 (replaced there)

**Comment by MarcinKrawczuk** [comment]
So apparently I did the work records but I never did the PR. So I will delete those branches. Regarding LIT6207CyriacusVictor maybe also the relation could be added: <relation name="saws:isAttributedToAuthor" active="LIT6207CyriacusVictor" passive="PRS3251Cyriacus"/>

**Comment by eu-genia** [comment]
thank you! if anything else comes up shout (or PR)

**Comment by smaugustine** [comment]
@eu-genia, is the relation to Eusebius of Caesarea (`PRS3912Eusebius`) for `LIT6504Mashafa` correct? It seems to be to be another figure, Eusebius of Syria (perhaps `PRS3911Eusebius`)?

I have a malkǝʾ for the martyr on 13 Yakkātit and want to make sure the relation is correct.

**Comment by eu-genia** [comment]
<img width="349" height="112" alt="Image" src="https://github.com/user-attachments/assets/226a88bb-3590-4940-b98d-db8754edadd8" />

**Comment by eu-genia** [comment]
That's what Wright (above) says here (also Bausi in his overview of the Gadla Sama'tat preserves the identification). Since Wright was also the translator of the Syriac martyrology I had assumed he knew what he was talking about. 
The date is confusing of course (as well as "Sorya").

**Comment by eu-genia** [comment]
PRS3911Eusebius is this one https://st-takla.org/books/en/church/synaxarium/06-amsheer/23-amshir-eusebius.html (23 Yakkatit), possibly it is him commemorated in GS?

**Comment by eu-genia** [comment]
The confusing thing is that all three are commemorated in February, maybe some are partially conflated in Ethiopian tradition (?) 
There surely is only one Eusebius frequently appearing in murals alongside Basilides (PRS3911Eusebius) and only one with a text in the Gadla sama'tat. I am not sure if there is anything on the Hermit at all (?)

**Comment by abausi** [comment]
The Eusebius of Or. 686 does not seem to be a Persian martyr, he is rather an ascetic, but I cannot compare the text in order to carry out a certain identification. In any case, there is no reason to identify him with "Eusebius of Caesarea"; in this case, I relied on Wright.

**Comment by MarcinKrawczuk** [comment]
I have consulted "Bibliotheca sanctorum" but with no success.

I would be in favor of creating a new person record for Eusebius venerated
on the 13th of Yakkātit, linking him to LIT6504Mashafa and the work record
for the malkǝʾ, perhaps also providing some info from the entry for the
13th of Yakkātit in the Synaxary.

pon., 26 sty 2026 o 16:42 Alessandro Bausi ***@***.***>
napisał(a):

**Comment by eu-genia** [comment]
Thank you @smaugustine and @MarcinKrawczuk you are of course right, I have created PRS12036Eusebios and updated 6504
