### ISSUE TITLE
Identification of a Hymn to the Paraclete

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2542]
@DenisNosnitsin1970 @thea-m @eu-genia @smaugustine 

I found a text in BLorient9051 on f. 1r to 10v, that is entitled by St. Strelcyn as a "Hymn to the Paraclete". There are still no images available for the BL manuscripts. However, Strelcyn cited a long incipit of the third stanza. Each stanza (out of 30) is reported to begin with እሰግድ. Despite this multitude of hints and information, I was not able to identify this text. Can anybody do better?
```
<msItem xml:id="p1_i1">
                                <locus from="1r" to="10v"/>
                                <title ref="LIT0000000000000000" type="incomplete">Hymn to the Paraclete</title>
                                <note>Composed of thirty strophes of five verses each, beginning generally with 
                                    <foreign xml:lang="gez">እሰግድ።</foreign>. The first two stanzas are partly missing or hardly legible. The beginning of 
                                    the third stanza is legible on <locus target="#2r"/>.</note>
                                <incipit xml:lang="gez"><gap reason="omitted"/><gap reason="illegible"/><pb n="2r"/>
                                   እሰግድ፡ ለርእስከ፡ ርእሰ፡ መላኮት፡ ዝኩ።
                                   ዘነቢያተ፡ ኦሪት፡ ኪያሁ፡ አርድእተ፡ ወንጌል፡ ሰበኩ።
                                    ጵራቅሊጦስ፡ ትቤ፡ ገአረ፡ እስራኤል፡ ሰማዕኩ።
                                    እምቅኔተ፡ ግብጽ፡ አድኅኖሙ፡ ወረደኩ።
                                    ከመ፡ ከማሆሙ፡ ታድኅነኒ፡ ኀቤከ፡ ጸራሕኩ።
                                </incipit>
                            </msItem>
```

**Comment by eu-genia** [comment]
Seems to be different from the other hymns to Paraclete we have

**Comment by smaugustine** [comment]
This is actually the fourth stanza of መልክአ፡ ጰራቅሊጦስ፡, Chaine no. 395. It might normally have been the third except that the text has an extra introductory stanza attested in all copies. The text was printed in Tasfa Gabra Sellase pp. 176–189, among others.

![image](https://github.com/BetaMasaheft/Documentation/assets/6315671/1fd57e3e-b358-466c-99f0-102316999f63)
