### ISSUE TITLE
One more prayer in BLorient13262

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2545]
@eu-genia @thea-m @DenisNosnitsin1970 

There is one prayer in BLorient13262, that I could not find anywhere else. It was given the title: "Prayer against fever and naqaṭqaṭ by the virtue of the magical names written by the Wise Men after the prophecy of the coming of Christ had become known." by Strelcyn.
Incipit: ይመስል፡ ወምስለዝ፡ ኮነ፡ ትንቢት፡ ከመ፡ ይትወለድ፡ ክርስቶስ፡ እግዚእነ፡ ወጸሐፉ፡ ጠቢባን፡ ዘንተ፡ አስማተ፡ አስማተ፡ አእሚሮሙ፡ ከመ፡ ድኅኑ፡ እምንዳድ፡ ወእምነቀጥቃጥ፡ ለእመ፡ ተጠምቁ፡ በማይ፡

**Comment by eu-genia** [comment]
OK for me
