### ISSUE TITLE
Śǝrʾāta krǝstiyān, an Amharic treatise on Christian faith and morals in BLorient11294

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2549]
@eu-genia @DenisNosnitsin1970 

In BLorient11294 I found a text which Strelcyn entitled "Śǝrʾāta krǝstiyān, an Amharic treatise on Christian faith and morals".

**BLorient11294**
```
<msItem xml:id="ms_i2">
                            <locus from="57va" to="59rb"/>
                            <title ref="LIT0000000000000000000000000000000" type="incomplete">Śǝrʾāta krǝstiyān, an Amharic treatise on Christian faith and morals</title>
                            <note><ref target="59r"/> deals mainly with the seven deadly sins. The text ends abruptly on <ref target="59rb"/>.</note>
                            <textLang mainLang="am"/>     
                            <incipit xml:lang="am">ሥርአተ፡ ክርስቲያን፡ ከዚህ፡ አስከትሎ፡ ነው፡ ጌታችን፡ እ<hi rend="ligature">ግዚ</hi>እነ፡ ኢየሱስ፡ ክርስቶስም፡ ወእንዘ፡ 
                                **ታጠምቅዎሙ፡ በሉ፡ በስመ፡ አብ፡ ወወልድ፡** <cb n="57vb"/> **ወመንፈስ፡ ቅዱስ፡** ብሎ፡ ፫ንቱ፡ ለሐዋርያት፡ አስተማረ፡ በኦሪትም፡ ስማዕ፡ እስራኤል፡ ፩አምላክከ፡ 
                                ብሎ፡ አንድነቱን፡ አስተምሮ፡ ነበርና፡ ፲ወ፪ሐዋርያት፡ ሰውን፡ ኍሉ፡ ሲያጠምቁ፡ በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ፡ ብለው፡ ፩ነትና፡ ፫ትነትን፡ ገልጸው፡
                                ለሰው፡ ኍሉ፡ አስተማሩ፡ </incipit>
                        </msItem>
```

The given incipit has some parallels to LIT6549AmhTheol, unless the rest of the recorded incipit and the overall content is described as very different. For this reason, I think it is not reasonable to link these two.
**LIT6549AmhTheol**
"Amharic treatise on the nature and life of Christ" (title by Dorothea)
Incipit (taken from BDLaethg34): በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ እግዚአብሔር፡ እምቅድመ፡ ዓለማት፡ በሐንድነት፡ በሶስትነት፡ እንደነበረ፡ ነአምናለን፡ (!) ለሐንደነቱና፡ ለሶስትነቱ፨ መላእክት፡ ቅዱስ፡ ቅዱስ፡ ቅዱስ፡ እግዚአብሔር፡ ጸባኦት፡ ፍጹም፡ ምሉዕ፡ ሰማያተ፡ ወምድረ፡ ቅድስት፡ ስብሐቲከ፨ ተናገሩ፡ ብሎ፡ ኢሳይስኒ፡ እንዳለ፨ ወንጌልም፡ እንዘ፡ **ታጠምቅዎሙ፡ በሉ፡ በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡** እንዳለ፨

Beyond that, I did not find any text with this title or with similar incipit. I suggest create a new LIT for the small fragment attested in BLorient11294?

**Comment by eu-genia** [comment]
"ወእንዘ ታጠምቅዎሙ በሉ በስመ አብ ወወልድ ወመንፈስ ቅዱስ" is a verse from the Gospel.

**Comment by eu-genia** [comment]
Matthew 28:19 https://books.google.de/books?id=nZIqKMRk6G0C&pg=PA406
