### ISSUE TITLE
A case of an unsuccesful merging ?

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2550]
There is a group of gädlat where some recent changes are visible in Atom but not in the app. I'm letting know just in case:

LIT6482GadlaArs
LIT1895Martyr
LIT1893Martyr
LIT6692MirFasiladas
LIT4040MartyrPhilemon
LIT3162Phileas
LIT4845Martyr

@eu-genia

**Comment by eu-genia** [comment]
done
