### ISSUE TITLE
Connect the specific CAe IDs to a meta CAe ID / Adding the text of a prayer to a TEI/XML file / Aiming at a consistent way to treat incipit/explicit vs. full text

### ISSUE THREAD

**Issue by LeonardBahr** [BetaMasaheft/Documentation#2551]
Dear all,

hopefullly you are fine. It is really amazing to see these three new CAe IDs (referring to https://github.com/BetaMasaheft/Documentation/issues/2398). Thank you for that!

1) Now, that we have specific CAe IDs for the above-mentioned three Marian prayers, it would be helpful to connect them to the general CAe ID of Mastabqʷǝʿān: CAe 4711 (cf. https://betamasaheft.eu/works/LIT4711Mastabqwe/main), because they are, in essence, Mastabqʷǝʿān themselves. If you would like to, you can check, as a model, the general ID of the Liṭon prayers with the specific IDs of each prayer listed thereunder under "General Description": https://betamasaheft.eu/works/LIT4860Litanies/main. In other words: It would make sense to have those three Marian prayers listed on the public page of CAe ID Mastabqʷǝʿān.

2) In the TEI/XML file of CAe 4711, the full text of each prayer has been entered. There is one exception, however, which is Mastabqʷǝʿ za-Māryām (wa-kāʿba nāstabaqqʷǝʿā la-naqʿa ḥǝywat) (CAe 6908). It would be helpful if the full text could be added to the file. The full text is:
ወካዕበ፡ ናስተበቍዓ፡ ለነቅዐ፡ ሕይወት፡ ለቅድስት፡ ደብተራ፡ ዘወለደት፡ ወአግመረት፡ ጵርስፎራ፡ ይትነከር፡ ዕበየ፡ ክብራ፡ ጊዜ፡ ይትነበብ፡ ተአምራ፡ ጽልሕወ፡ ልብ፡ ብእሲ፡ ሥጋ፡ ቢጹ፡ ዘበልዐ፡ ስመ፡ ማርያም፡ ዘጸውዐ፡ በሕፍነ፡ ማይ፡ ቈሪር፡ መንግሥተ፡ ሰማያት፡ ቦአ፡ ሰሚዐክሙ፡ አንክሩ፡ ዜና፡ ዝክራ፡ አፍቅሩ፡ መንግሥተ፡ ዚአሃ፡ ተዘከሩ፡ ዘኵሎ፡ ታድኅን፡ እግዝእትነ፡ ማርያም። ንዑ፡ ንስግድ፡ ወንግነይ፡ ለንግሣ፡ ዘጾረት፡ ወአግመረት፡ በከርሣ፡ እግዚአ፡ ሰማያት፡ ወምድር፡ መስተስርየ፡ ኀጢአት፡ ወአበሳ። እንዘ፡ ኢትሌሊ፡ ባዕላየ፡ ወኢትሜንን፡ ነዳየ። ማርያምሰ፡ ታፈቅር፡ ዘይገብር፡ ሠናየ። ዛቲ፡ ይእቲ፡ እኅተ፡ መላእክት፡ ትጉሃን። ወለተ፡ ኄራን፡ ነቢያት፡ ብዕሎሙ፡ ለሐዋርያት፡ ሞገሰ፡ ጻድቃን፡ ወሰማዕት፡ ላቲ፡ ይደሉ፡ ክብር፡ ወስብሐት፡ ዘምስለ፡ ወልዳ፡ አምልኮ፡ ወስግደት፡ በምድር፡ ወበሰማያት፡ በባሕር፡ ወበቀላያት፡ ለዓለመ፡ ዓለም፡ አሜን።

3) Finally, we talked about the incipit and explicit and I see they have been added to Liṭon za-masqal (CAe 4713) and to the three Marian prayers (CAe 6906, CAe 6907, CAe 6908). On the other side, the incipit and explicit cannot be found in the files of other litanies, namely the Liṭon prayers. In each file of those, the whole prayer has been written out. Thus, I would opt for a consistent solution: Either we include the whole prayer in each file or merely the incipit and explicit. What do you think? What is the usual way of doing that in BM? Of course, we can also add both, but it should be consistent for all three groups of the litanies (Liṭon, Mastabqʷǝʿ, Za-yǝnaggǝś). The texts are rather short, so personally I think we could write down the whole prayer, especially because I already typed down these texts for BM when I was a student assistant. If you agree to this procedure, I can provide these texts here below.

All the best

Leonard

**Comment by CarstenHoffmannMarburg** [comment]
I had the same idea and opened a discussion in https://github.com/BetaMasaheft/Documentation/issues/2552. Let us continue the discussion there and close this issue. For future issues, please keep in mind, that you need to assign yourself or somebody else to the issue and address each person to get their attention. (@.....)
