### ISSUE TITLE
Update LIT4860Litanies according to Leonard Bahr

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2553]
Leonard Bahr made the following remark remark in https://github.com/BetaMasaheft/Documentation/issues/2552:

"And optionally, the two Liṭon prayers for the evening often appear with the other Liṭon prayers. (In the end, the entries for the Liṭon prayers would need to be thoroughly revised, because the current system of attributing to each prayer a weekday is not reflected by the earliest MSS. But this would require a separate issue.)."

I think, there is no reason not to add this information to the abstract. @LeonardBahr: Can you give us examples of early manuscripts, that do not have this order?

@eu-genia @karljonaskarlsson

**Comment by LeonardBahr** [comment]
I mean, I understand the initial desire to attribute weekdays to the prayers, because it reflects the present tradition. 

However, two points I would like to address here: 

1) The information in the TEI/XML of LIT4860 "The following order reflects that of the modern printed editions." is wrong in five of seven cases:

- https://[betamasaheft.eu/works/LIT4266Litonz/LIT4266Litonz.xml](https://betamasaheft.eu/works/LIT4266Litonz/LIT4266Litonz.xml) is attributed to Friday on BM, but the text is used for Wednesday in the present tradition.
- https://[betamasaheft.eu/works/LIT4264Salota/LIT4264Salota.xml](https://betamasaheft.eu/works/LIT4264Salota/LIT4264Salota.xml) is attributed to Saturday on BM, but the text is used for Thursday in the present tradition.
- https://[betamasaheft.eu/works/LIT4268Tazakkar/LIT4268Tazakkar.xml](https://betamasaheft.eu/works/LIT4268Tazakkar/LIT4268Tazakkar.xml) is attributed to Sunday on BM, but the text is used for Friday in the present tradition.
- https://[betamasaheft.eu/works/LIT4265Litonz/LIT4265Litonz.xml](https://betamasaheft.eu/works/LIT4265Litonz/LIT4265Litonz.xml) is attributed to Thursday on BM, but the text is used for Saturday in the present tradition.
- https://[betamasaheft.eu/works/LIT4859Litany/LIT4859Litany.xml](https://betamasaheft.eu/works/LIT4859Litany/LIT4859Litany.xml) is attributed to Wednesday on BM, but the text is used for Sunday in the present tradition.

I do not know how to "prove" this. You could take any printed missal, psalter, book of hours in the Hammerschmidt Library. Alternatively, I could send you the digitised missal from which I typed down all litanies in June 2020 as a student assistant for the HLC.

2) Eight from nine manuscripts I analysed in my MA had a different sequence of the prayers. Only two shared the same sequence, but the sequence is once again different than in today's tradition. There is an overview with the indications of the MSS on p. 111 of my thesis, which you can check here: https://www.academia.edu/107020428/The_Litanies_Intercessory_Prayers_in_Ethiopian_Manuscripts. (The sequence of the present tradition seems to go back to a much later manuscript tradition, the exact period of standardisation I am currently trying to detect by research). Hence, I would opt for a solution that detaches the files from weekdays and focusses on the incipit.

**Comment by CarstenHoffmannMarburg** [comment]
The general description is the following:

> Litanies for the days of the week. The assignment of the litanies to the days of the week varies accross manuscripts. The text of the litanies is available in their individual records: [Liṭon za-sanuy](https://betamasaheft.eu/LIT1807Litonz), [Liṭon za-śalus](https://betamasaheft.eu/LIT4858Litany), [Liṭon za-ʿārb](https://betamasaheft.eu/LIT4266Litonz), [Liṭon za-qadām](https://betamasaheft.eu/LIT4264Salota), [Liṭon za-ʾǝḥud](https://betamasaheft.eu/LIT4268Tazakkar), [Liṭon za-ḫamus](https://betamasaheft.eu/LIT4265Litonz), [Liṭon za-maḫātǝwa fāsikā](https://betamasaheft.eu/LIT3571Litonz), [Liṭon za-rabuʿ](https://betamasaheft.eu/LIT4859Litany).

I think, it would be useful to change the titles of the individual records, e.g.  "Liṭon za-sanuy"  -> ????

Can you provide incipits or propose a manuscript, where I can take them?

**Comment by LeonardBahr** [comment]
[Let me edit this comment later before you act, I am on the road sorry] 

Yes and with great pleasure, once I get home. Shall we take those I used in my thesis on p. 32-33 (see below) or do you prefer longer versions?

- CAe 1807: Liṭon ʾǝnza naʾakkʷǝto ʾǝsma ʿaqabanna
- CAe 4858: Liṭon sǝmǝka ḥǝyāw
- CAe 4266: Liṭon la-tǝruṣ ʾǝgziʾo
- CAe 4264: Liṭon kama tādḫǝnanna
- CAe 4268: Liṭon tazakkar ʾǝgziʾo
- CAe 4265: Liṭon qadāme ṣaggā
- CAe 4859: Liṭon wa-kāʿba nāstabaqqʷǝʿo la-ʾamlāka mǝḥrat 
- CAe 3571: Liṭon soba ʾakko
- Liṭon za-sark (ʾamlākǝna)
- Liṭon za-sark (ʾǝsma 
- rassayanna

**Comment by CarstenHoffmannMarburg** [comment]
I think the shorter titles from your thesis are alright.

**Comment by CarstenHoffmannMarburg** [comment]
I changed the titles in the records mentioned above. However, I did not find a record with the title "Liṭon za-sark ʾamlākǝna" (except for ms. BDLaethe1, f. 7v) or "Liṭon za-sark ʾǝsma rassayanna". Do these records already exist, or it it necessary to create two new records for them?

**Comment by LeonardBahr** [comment]
As the updated comment above indicate, there exists the ID CAe 1808: Liṭon za-sark. It is, however, a humorous deception because there are two Liṭon za-sark, which often circulate independently: Liṭon za-sark (ʾǝsma rassayanna), already present in the Aksumite collection and usually found in Ṣoma dǝggʷā, and Liṭon za-sark (ʾamlākǝna).

**Comment by LeonardBahr** [comment]
"I think the shorter titles from your thesis are alright."

I agree. We could still use longer incipits as proper incipits for the TEI/XML files.

**Comment by LeonardBahr** [comment]
Some more information on these two texts follows. That in square brackets is just for transparency, not for the public page.

**1) Liṭon za-sark (ʾamlākǝna):**

Titles
ሊጦን፡ ዘሰርክ፡ Liṭon za-sark ‘Liṭon of the evening’ [called as such in AKM-009 and in BL Or. 545]
አምላክነ፡ ʾAmlākǝna ‘Our God’ [called as such in BL Or. 545]
ዘሰርክ፡ Za-sark ‘Of the evening’ [called as such in BnF Éth. 74]
ኪዳን፡ ዘሰርክ፡ Kidān za-sark ‘Kidān of the evening’ [called as such in BnF Éth. d’Abb. 72]

Witnesses [all missals from the 17th century]
‐	AKM-009, [fols 28vb18–29ra5]
‐	BL Or. 545, [fol. 12vb9–12vc20]
‐	BnF Éth. 74, [fol. 11ra16–11rb16]
‐	BnF Éth. d’Abb. 13, [fol. 8va5–8vb8]
‐	BnF Éth. d’Abb. 72, [fols 12vb5–13ra14]
‐	MR-025, [fols 22vb13–23ra16]
‐	Ṭānāsee 68, [fol. 18ra10–18rb17]

Edition
Hammerschmidt, Ernst 1959. ‘Das Sündenbekenntnis über dem Weihrauch bei den Äthiopiern’, Oriens Christianus, 43 (1959), 103–109.
Velat, Bernard 1966. Meʿerāf: Commun de l’office divin éthiopien pour toute l’année, Texte éthiopien avec variantes, ed. Bernard Velat, Patrologia Orientalis, 34/1–2 (Paris: Firmin-Didot et Cie, éditeurs, 1966). 7

Secondary Bibliography
Bahr, L. 2023. The Litanies: Intercessory Prayers in Ethiopian Manuscripts, M.A. Thesis, Hamburg: Universität Hamburg (2023).

**2) Liṭon za-sark (ʾǝsma rassayanna):**

Titles
ጸሎተ፡ ሰርክ፡ Ṣalota sark ‘Prayer of the evening’ [This is its title in the Aksumite collection]
ዘሰርክ፡ Za-sark ‘Of the evening’ [This is its title in BnF Éth. d’Abb. 72 ]
ዓዲ፡ ሊጦን፡ ዘሰርክ፡ በጾመ፡ ድጓ፡ ዘይትበሀል፡ ʿĀdi liṭon za-sark ba-ṣoma dǝggʷā za-yǝtbahal ‘Further litany of the evening, which is said in Ṣoma dǝggʷā’ [It is called as such in a printed psalter]

Witnesses [all missals from the 17th century except the first entry]
‐	Aksumite collection, [fols 57vb29–58rb8]
‐	BL Or. 545, [fols 20vb18–21rb4]
‐	BnF Éth. 74, [fol. 15ra7–15rb11]
‐	BnF Éth. d’Abb. 72, [fols 33va16–34ra9]
‐	Ṭānāsee 68, [fol. 26ra9–26rb17]

Edition
Velat, Bernard 1966. Meʿerāf: Commun de l’office divin éthiopien pour toute l’année, Texte éthiopien avec variantes, ed. Bernard Velat, Patrologia Orientalis, 34/1–2 (Paris: Firmin-Didot et Cie, éditeurs, 1966). 7–8

Secondary Bibliography
Bahr, L. 2023. The Litanies: Intercessory Prayers in Ethiopian Manuscripts, M.A. Thesis, Hamburg: Universität Hamburg (2023).

**Comment by CarstenHoffmannMarburg** [comment]
> As the updated comment above indicate, there exists the ID CAe 1808: Liṭon za-sark. It is, however, a humorous deception because there are two Liṭon za-sark, which often circulate independently: Liṭon za-sark (ʾǝsma rassayanna), already present in the Aksumite collection and usually found in Ṣoma dǝggʷā, and Liṭon za-sark (ʾamlākǝna). I guess we could assign to CAe 1808 one of the texts and then create another ID for the other one? Would that corrupt a lot of manuscript descriptions that refer to CAe 1808? Is there a way to see in BM how many such references exist and could we change them, too?

I suggest to create two new IDs for both of them. The CAe 1808 should remain and be transformed explicitly to a general record, what means, that this ID will be used for all cases, where it is not certain, which Liṭon za-sark is needed, what is the case for most of the existing manuscript witnesses.

**Comment by LeonardBahr** [comment]
Good morning, Carsten. Sounds like an optimal solution. But the two new IDs would still be related to CAe 4860, right? I think that would be important, so that we would have all _Liṭon_ prayers unified under one CAe ID.

**Comment by LeonardBahr** [comment]
Selam selam. Some comments and proposals for your provisional translation of the titles:

N.B.: The first word, _Liṭon_, is not part of the text of the prayer itself, although it does occur as a title/heading sometimes. We may leave it out completely. I found it helpful during my MA to add it in order to know exactly that it is a _Liṭon_ prayer every time when one sees it. Some of the translations below only make sense if we look at one or two more of the Ethiopic words. However, it seems unnecessary to add more Ethiopic words to the title merely for the sake of having nice translations. In those cases, I added those words in English in brackets to make the translations meaningful.

_ʾǝnza naʾakkʷǝto ʾǝsma ʿaqabanna_ ‘While we praise him, for he protected us’
_sǝmǝka ḥǝyāw_ ‘Your living name’
_la-tǝruṣ ʾǝgziʾo_ ‘That (your compassion), O Lord, (may run towards us)’
_kama tādḫǝnanna_ ‘That you may save us’
_tazakkar ʾǝgziʾo_ ‘Remember, O Lord’
_qadāme ṣaggā_ ‘ The beginning of grace’
_wa-kāʿba nāstabaqqʷǝʿo la-ʾamlāka mǝḥrat_ ‘And again we beseech the God of compassion’
_soba ʾakko_ ‘If (the Lord) had not been’
_ʾamlākǝn_a ‘Our God’
_ʾǝsma rassayanna_ ‘For you have brought us (enjoyment)’

**Comment by CarstenHoffmannMarburg** [comment]
I will update the titles and keep the older, longer ones as second titles.

**Comment by CarstenHoffmannMarburg** [comment]
> Velat, Bernard 1966. Meʿerāf: Commun de l’office divin éthiopien pour toute l’année, Texte éthiopien avec variantes, ed. Bernard Velat, Patrologia Orientalis, 34/1–2 (Paris: Firmin-Didot et Cie, éditeurs, 1966). 7

Is it correct to read 'page 7' in the end?

`<bibl><ptr target="bm:bm:Velat1966MeerafText"/><citedRange unit="page">7</citedRange></bibl>`

**Comment by CarstenHoffmannMarburg** [comment]
> ‐ BnF Éth. d’Abb. 13, [fol. 8va5–8vb8]

This manuscript does not have an ID yet. @DenisNosnitsin1970: Can I create a stub for BnF Abbadie 13?

**Comment by CarstenHoffmannMarburg** [comment]
> Witnesses [all missals from the 17th century except the first entry]
> ‐ Aksumite collection, [fols 57vb29–58rb8]

The Aksumite is a work (LIT1047Aksumi), but not a manuscript. I will reference it in a relation, but not as a witness in the source desc.

**Comment by LeonardBahr** [comment]
"Is it correct to read 'page 7' in the end?"

> Yes, page 7. The other text pp. 7 to 8.

Are there any texts, incipits or explicits available for Liṭon za-sark (ʾǝsma rassayanna) and Liṭon za-sark (ʾamlākǝna)?

> Yes, give me some minutes and I will post it here below.

**Comment by LeonardBahr** [comment]
Full texts:

Liṭon za-sark (ʾamlākǝna)
ይ፡ ካ፡ አምላክነ፡ ዘዲበ፡ ኪሩቤል፡ ትነብር፡ እምኀበ፡ መላእክት፡ ትትአኰት፡ ወትሴባሕ፡ አንተ፡ ውእቱ፡ ዘከፈልከነ፡ ንባእ፡ ውስተ፡ ጽርሐ፡ ቅዱስ፡ ማኅደርከ፡ ንዘከር፡ ቅድሳተ፡ ስብሐቲከ፡ ወንፍዲ፡ ለከ፡ ዘሰርክ፡ አኰቴተ፡ አንተ፡ ተወከፍ፡ ዘኵልነ፡ ሰክዮተ፡ ወበቍዔተ፡ በተአምኖ፡ ዘውስተ፡ ልብው፡ ዘበሰማያት፡ ምስጢርከ፡ በጼና፡ ሠናይ፡ መዐዛ፡ ዕቀብ፡ ኵለነ፡ ዘእንበለ፡ ጻሕብ፡ ወዘእንበለ፡ ተመውኦ፡ ወዘእንበለ፡ ማዕቅፍ፡ አድኅን፡ አእጋረነ፡ እምዳኅፅ፡ ወአዕይንተ፡ እምአንብዕ፡ ወነፍስተነ፡ እሞተ፡ ኀጢአት፡ ወደምረነ፡ ምስለ፡ እለ፡ ድኅኑ፡ ብከ፡ በጸሎተ፡ ኵሎሙ፡ እለ፡ እምዓለም፡ አሥመሩከ፡ በ፩ዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡ ወምስለ፡ ቅዱስ፡ መንፈስ፡ ስብሐት፡ ወእኂዝ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም። 
ይ፡ ሕ፡ አሜን። 

 Liṭon za-sark (ʾǝsma rassayanna)
ይ፡ ካ፡ ናስተበቍዕ፡ ዘኵሎ፡ ይእኅዝ፡ እግዚአብሔር፡ አብ፡ ለእግዚእ፡ ወመድኀኒነ፡ ኢየሱስ፡ ክርስቶስ፡ እስመ፡ ረሰየነ፡ ተድላ፡ ካዕባ፡ ውስተ፡ ዝንቱ፡ መካን፡ ቅዱስ፡ ንቁም፡ ንሰብሕ፡ ወንዘምር፡ ለዘበኵሉ፡ ቅዱስ፡ ወብፁዕ፡ ስመ፡ ዚአሁ፡ ዘኵሎ፡ ይእኅዝ፡ እግዚአብሔር፡ አምላክነ። 
ይ፡ ዲ፡ ጸልዩ። 
ይ፡ ሕ፡ አቡነ፡ ዘበሰማያት። 
ይ፡ ካ፡ እግዚኦ፡ ዘኵሎ፡ ትእኅዝ፡ ንስእለከ፡ ወናስተበቍዐከ፡ በከመ፡ ዐቀብከነ፡  ኑኀ፡ ዕለት፡ ወአብጻሕከነ፡ ካዕበ፡ ውስተ፡ ብርሃነ፡ ሰርክ፡ ዕቀበነ፡ በኑኀ፡ ሌሊት፡ ሱላሜ፡ ዘእንበለ፡ ኀጢአት፡ ሰርከ፡ ወሌሊተ፡ ጸግወነ፡ ወአድኅነነ፡ እምፍርሀተ፡ ሌሊት፡ ወእምትካዝ፡ ዘይወስድ፡ ውስተ፡ ጽልመት፡ እምሰብእ፡ ዐማፂ፡ ወሐባሊ፡ ባልሐነ፡ ዘአበስነ፡ ወዘተሰወረነ፡ ሕገ፡ ሰብእ፡ አናሕሲ፡ ለነ፡ እስመ፡ ኄር፡ ወመፍቀሬ፡ ሰብእ፡ አንተ፡ እግዚአብሔር፡ አምላክነ፡ በ፩ዱ፡ ወልድከ፡ ዘቦቱ፡ ለከ፡ ምስሌሁ፡ ወምስለ፡ ቅዱስ፡ መንፈስ፡ ስብሐት፡ ወእኂዝ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም። 
ይ፡ ሕ፡ አሜን።

**Comment by CarstenHoffmannMarburg** [comment]
> General question: If the texts are short enough, do we still need incipits and explicits?

Thank you for the full texts! No, I meant: Either full texts or incipits. I will update the records in a minute.

**Comment by CarstenHoffmannMarburg** [comment]
> Full texts:
> 
> Liṭon za-sark (ʾamlākǝna) ይ፡ ካ፡ አምላክነ፡ ዘዲበ፡ ኪሩቤል፡ (...)
> 
> Liṭon za-sark (ʾǝsma rassayanna) ይ፡ ካ፡ ናስተበቍዕ፡ ዘኵሎ፡ ይእኅዝ፡ እግዚአብሔር፡ አብ፡ ለእግዚእ፡ ወመድኀኒነ፡ ኢየሱስ፡ ክርስቶስ፡ እስመ፡ ረሰየነ፡ ተድላ፡ (...)

Are both texts taken from your Master thesis?

**Comment by LeonardBahr** [comment]
No, like the bulk of litanies on BM they are based on:

Anon. 1957. _መጽሐፈ፡ ቅዳሴ፡_ (_Maṣḥafa qǝddāse_, ‘Book of the Missal’) (ʾAśmarā: ba-māḫbara ḥawāryāt fǝre hāymānot ba-kokaba ṣǝbāḥ māttamiyā bet tāttama, 1957).

We could discuss with Dorothea (@thea-m) in the near future if the edition by Velat 1966 - based, however, on late MSS - would not have been a better choice.

**Comment by eu-genia** [comment]
> LIT1047Aksumi

Aksumite collection = [UM-039](https://betamasaheft.eu/ESum039)

**Comment by LeonardBahr** [comment]
Thank you, Eugenia!

**Comment by CarstenHoffmannMarburg** [comment]
> No, like the bulk of litanies on BM they are based on:
> 
> Anon. 1957. _መጽሐፈ፡ ቅዳሴ፡_ (_Maṣḥafa qǝddāse_, ‘Book of the Missal’) (ʾAśmarā: ba-māḫbara ḥawāryāt fǝre hāymānot ba-kokaba ṣǝbāḥ māttamiyā bet tāttama, 1957).
> 
> For the time being it is fine I would say. We could discuss with Dorothea (@thea-m) in the near future if the edition by Velat 1966 - based, however, on late MSS - would not have been a better choice and if it would make sense to update the entries according to his edition.

I assume it is bm:1957Qeddase.

**Comment by LeonardBahr** [comment]
> > Witnesses [all missals from the 17th century except the first entry]
> > ‐ Aksumite collection, [fols 57vb29–58rb8]
> 
> The Aksumite is a work (LIT1047Aksumi), but not a manuscript. I will reference it in a relation, but not as a witness in the source desc.

BM has not only a general CAe ID for the Aksumite collection, but also for the larger textual unit (CAe 6255: https://betamasaheft.eu/works/LIT6255Euchologion/main), the unique collection of prayers/euchologion, in which the above short litany _ʾǝsma rassayanna_ (CAe 7010) is preserved. If you still want to do a relation or sth. besides indicating it as a witness, you could add a reference to it. In this regard, it seems that notes like "This textual unit is included in the following 1 textual units (saws:formsPartOf)" are common on BM?

**Comment by LeonardBahr** [comment]
Perfect. I think everything could go online now. I see https://betamasaheft.eu/works/LIT7009Amlakena/main is still in a primitive state, while https://betamasaheft.eu/works/LIT7010Rassayanna/main does not work at all. But take your time, no need to rush. And again, many thanks for all the help @CarstenHoffmannMarburg!

**Comment by LeonardBahr** [comment]
Thinking of our endeavour, I just realised that there is one more aspect to consider:

It appears that CAe 4860 is the general record for the _Liṭon_ prayers of the morning only (mainly seven prayers, the sequence of which varying from MS to MS). But there is a record of an even more general level: CAe 3188: "General record for a not further identifiable collection of litanies". Thus, I believe every _Liṭon_ prayer should find mention there, while the seven morning prayers should be found under the sub-general record CAe 4860 and the two _Liṭon_ prayers of the evening under sub-general CAe 1808. But the two evening prayers should not be included in in the General Description (abstract) of CAe 4860. To illustrate this "hierarchical" structure in the form of a list:

- CAe 3188 Liṭon (General record for a not further identifiable collection of litanies)
	- CAe 4860 Liṭon za-nagh za-7 ʿǝlatāt za-tanāgaro qǝddus Bāsǝlyos
		- CAe 1807: Liṭon ʾǝnza naʾakkʷǝto ʾǝsma ʿaqabanna
		- CAe 4858: Liṭon sǝmǝka ḥǝyāw
		- CAe 4266: Liṭon la-tǝruṣ ʾǝgziʾo
		- CAe 4264: Liṭon kama tādḫǝnanna
		- CAe 4268: Liṭon tazakkar ʾǝgziʾo
		- CAe 4265: Liṭon qadāme ṣaggā
		- CAe 4859: Liṭon wa-kāʿba nāstabaqqʷǝʿo la-ʾamlāka mǝḥrat
		- CAe 3571: Liṭon soba ʾakko
	- CAe 1808 Liṭon za-sark
		- CAe 7009 Liṭon ʾamlākǝna
		- CAe 7010 Liṭon ʾǝsma rassayanna

**Comment by CarstenHoffmannMarburg** [comment]
Liton-prayers of the morning are already listed in the abstract of LIT3188Liton. However, <ref type="work" corresp="LIT3571Litonz"/>, is not mentioned among the "litanies of the week".

 ```
<abstract>
            <p>General record for a not further identifiable collection of litanies.</p>
            <ab>Specific litanies that can be in the collection are e.g. 
               <ref type="work" corresp="LIT1806Litonz"/>, 
               <ref type="work" corresp="LIT1808Litonz"/>, 
               <ref type="work" corresp="LIT4713Liton"/>, 
               <ref type="work" corresp="LIT3571Litonz"/>, 
               the litanies of the week in <ref type="work" corresp="LIT4860Litanies"/>, including 
               <ref type="work" corresp="LIT1807Litonz"/>, 
               <ref type="work" corresp="LIT4858Litany"/>, 
               <ref type="work" corresp="LIT4266Litonz"/>, 
               <ref type="work" corresp="LIT4264Salota"/>, 
               <ref type="work" corresp="LIT4268Tazakkar"/>, 
               <ref type="work" corresp="LIT4265Litonz"/>,
               <ref type="work" corresp="LIT4859Litany"/>         
            </ab>
```

**Comment by LeonardBahr** [comment]
> Liton-prayers of the morning are already listed in the abstract of LIT3188Liton. However, , is not mentioned among the "litanies of the week".

There is a lacuna between the two commas.

**Comment by LeonardBahr** [comment]
I am still a bit troubled by the entries for the seven week days:

As far as I can see you have added my above titles (based on the incipits) as subtitles ("Titles"), but not as the main titles, i.e. the title type in the XML/TEI file.  In the title type it is still written sth. like "Liṭon za-ʿārb". But this will still lead one to associate a prayer with a specific week day, so the whole GitHub issue remains unsolved. I would propose to do it the other way around. To take the example of CAe 1807: Liṭon ʾǝnza naʾakkʷǝto ʾǝsma ʿaqabanna can be the title type and "Liṭon za-sanuy" should be a subtitle under "Titles".

**Comment by CarstenHoffmannMarburg** [comment]
> I am still a bit troubled by the entries for the seven week days:
> 
> As far as I can see you have added my above titles (based on the incipits) as subtitles ("Titles"), but not as the main titles, i.e. the title type in the XML/TEI file. In the title type it is still written sth. like "Liṭon za-ʿārb". But this will still lead one to associate a prayer with a specific week day, so the whole GitHub issue remains unsolved. I would propose to do it the other way around. To take the example of CAe 1807: ʾƎnza naʾakkʷǝto ʾǝsma ʿaqabanna can be the title type and "Liṭon za-sanuy" should be a subtitle under "Titles".

The titles have been changed to the new incipit based titles, that you proposed:
   
 ```
<title xml:id="t1" xml:lang="gez">እንዘ፡ ነአኵቶ፡ እስመ፡ ዐቀበነ፡</title>
<title corresp="#t1" xml:lang="gez" type="normalized">ʾƎnza naʾakkʷǝto ʾǝsma ʿaqabanna</title>
<title corresp="#t1" xml:lang="en" type="normalized">While we thank him for protecting us</title>
```

**Comment by LeonardBahr** [comment]
Yes, I saw that, but the idea of the whole issue was sth. else:

These are not titles existing in MSS but created titles based on the incipit (created by us) that would enable us to clearly refer to one prayer and distinguishing it from others. They should be the main titles (= title type) in the big grew area on the top of the page. That is also why I initially did not provide translations.

**Comment by CarstenHoffmannMarburg** [comment]
I think, the title in t1 (normalized) will soon appear in the grey area on top.
