### ISSUE TITLE
new type="Sewing" in bindingDesc

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#2554]
@ElianaDalSasso and I would like to create a new value  "Sewing" for `@type` in decoNote in binding. Currently, sewing is described in a decoNote without type (https://betamasaheft.eu/Guidelines/?id=bindingDescription). This would be helpful for us for visualisation, and we think it makes the description in general more consistent (the existing decoNotes without this type would of course stay valid).
Are there any objections?
@DenisNosnitsin1970 @eu-genia @CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
If I understand you correctly, you want to use type="sewing" to note the number of sewing stations. So, for example
`<decoNote xml:id="b2">Two pairs of sewing stations. </decoNote>` 
would become:
`<decoNote xml:id="b2" type="sewing">Two pairs of sewing stations.</decoNote>`.
I have no objection to this.

**Comment by thea-m** [comment]
We want to add an additional type:
```
 <decoNote xml:id="b5" type="SewingStations">4</decoNote>
<decoNote xml:id="b6" type="Sewing">
                                  Chainstitch sewing on four sewing stations (two pairs); periodic fold pattern. Two S-plied threads are used.
                                  The sewing starts from the first quire where, for each pair of sewing stations, there is one length of thread in the centre-fold,
                                  while in the rest of the quires there are two.
                                </decoNote>
```

**Comment by DenisNosnitsin1970** [comment]
ok

**Comment by eu-genia** [comment]
Sure. Will you update the schema? Do you need anything added in visualization?
