### ISSUE TITLE
Publication statement, encoding description view

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2555]
The elements take too much space.
Probably better hide in dropdowns or popups

**Comment by eu-genia** [comment]
Edition statement appears twice

**Comment by eu-genia** [comment]
@thea-m @DenisNosnitsin1970 @CarstenHoffmannMarburg let me know if you think it looks better this way, with the editorial/publication/citation information behind the buttons

**Comment by CarstenHoffmannMarburg** [comment]
I do not know, which problem was adressed here.

**Comment by eu-genia** [comment]
Publication statement, Encoding description, Suggested citation, Attribution of content etc used to be all printed occupying a lot of page space
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/79e4f5a5-3e70-4787-845a-cd6a407dd637)
now there are buttons to open them
