### ISSUE TITLE
PRS and LOC in BLorient2082

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2558]
@eu-genia @DenisNosnitsin1970 

There is a colophon in BLorient2082 at the end of a codicological unit containing a synaxary. It is dated to1641 and it contains a number of names. Many of them sound very odd to me and I cannot identify them with certainty as personal names or place names. Do you recommend to create PRS IDs and LOC IDs nevertheless, or do you rather think it is better not to mark them up?

**LOC**

I) There is no information, where "church of St George" / ጊዮርጊስ፡ ዘማንጽሩ፡ may be situated. If PRS14454EhataKrestos is indeed to be identified with PRS3698ehetaKr, this might be around lake Tana.
II) መረዶ፤ - name of a place or verbal form?
III) ምባጭ፡ አርዋ፤ or ባጭ፡ አርዋ፤?

**PRS**

1) PRS14454EhataKrestos could possibly be the prominent figure, that was venerated as a saint later.
2) PRS14457WaldaHawWS could be two persons. Either, I do not know, whether ምስክር is a title to PRS14457WaldaHawWS or has another meaning.
3) PRS14458Zamaryam and PRS14459Zamaryam are possibly the same person and whether ቦራራ is a title to them.
4) ልብሶ፤
5) በዠር፡ ወንድ፡ አዕጋረ፡ ክርስቶስ፤
6) ተኮ፤
7) እዶ፤
8) ተኽሌ፤
9) መልኮ።

As far as I understand, PRS14454EhataKrestos bought this manuscript from PRS14455AsqaGiyorgis and gave it as a donation to the church Giyorgis za-Mānṣǝru (as Strelcyn noted in his catalogue). The interpretation of the following list is not clear to me. Probably, they are listed as important people, who witnessed the donation to make it valid and honour the donor. 

```
<colophon xml:id="coloph1">
                                    <locus target="#159vb"/>
                                    <note>The note states that this manuscript was bought by 
                                        <persName role="owner" ref="PRS14454EhataKrestos">ʾƎḫǝta Krǝstos</persName> from
                                        <persName role="bequeather" ref="PRS14455AsqaGiyorgis">ʾAṣqa Giyorgis</persName> and offered to the 
                                        <placeName ref="LOC000000000000000000000000000">church of St George</placeName> in the tenth year of the 
                                        reign of <persName ref="PRS4015Fasilada">Fāsiladas</persName>, i.e. <date when="1642">1642 AD</date>.</note>
                                    <q xml:lang="gez">ዛቲ፡ ስንክሳር፡ ዘ<persName role="owner" ref="PRS14454EhataKrestos">እኅተ፡ ክርስቶስ፡</persName> 
                                        ዘተሣየጠት፡ በ፯ወቄት፡ እም<persName role="bequeather" ref="PRS14455AsqaGiyorgis">አጽቀ፡ ጊዮርጊስ፤</persName> 
                                        ወመድኅንሂ፡ <persName ref="PRS14456WalattaDengel"><roleName type="title">ወይዘሮ፡</roleName>ወለተ፡ ድንግል፤</persName> 
                                        ወምስክርሂ፡ <persName ref="PRS14457WaldaHawWS">ወልደ፡ ሐዋርያት፡ ወልደ፡ ሰንቡል፤</persName>
                                        ወ<persName ref="PRS14458Zamaryam">ዘማርያም፡</persName> ዘነበረ፡ ወዓሊሁ፤ 
                                        <persName ref="PRS14459Zamaryam"><roleName type="title">ቦራራ፡</roleName> ዘማርያም፡</persName>
                                        <persName ref="PRS14460Tsaggo"><roleName type="title">አዛዠ፤</roleName> ጸጎ፤</persName>
                                        <persName ref="PRS14461GabraKrestos"><roleName type="title">ቄስ፡ </roleName>ገብረ፡ ክርስቶስ፤</persName>
                                        ወ<persName ref="PRS14462MalkeaKrestos">መልክዓ፡ ክርስቶስ፡</persName> 
                                        ዘ<placeName ref="LOC000000000000000000000000">መረዶ፤ </placeName>
                                        <persName ref="PRS14463BahayloZamaryam">በኃይሎ፡ ዘማርያም፡ </persName>
                                        ዘ<placeName ref="LOC0000000000000000000000">እምባጭ፡ አርዋ፤</placeName>
                                        <persName ref="PRS0000000000000000000"><roleName type="title">ማዮቸ፡</roleName> ብሌኖ፤</persName>
                                        <placeName ref="LOC3549Gojjam">ጕዣሜ፤</placeName>
                                        አዝማች፡ <persName ref="PRS14464WaldaTansae"><roleName type="title">አባ፡ </roleName>ወልደ፡ ተንሣኤ፤</persName>
                                        <persName ref="PRS0000000000000000000">ሩፋኤል፤</persName>
                                        <persName ref="PRS0000000000000000000">ልብሶ፤</persName>
                                        <persName ref="PRS0000000000000000000"><roleName type="title">በዠር፡ ወንድ፡</roleName> አዕጋረ፡ ክርስቶስ፤</persName>
                                        <persName ref="PRS0000000000000000000">ተኮ፤</persName>
                                        <persName ref="PRS14465Elyanos">ኤልያኖስ፤</persName>
                                        <persName ref="PRS0000000000000000000">እዶ፤</persName>
                                        <persName ref="PRS0000000000000000000">ተኽሌ፤</persName>
                                        <persName ref="PRS0000000000000000000">መልኮ። ።</persName>
                                        በ፲፡ ዓመተ፡ መንግሥቱ፡ ለንጉሥነ፡ <persName ref="PRS4015Fasilada">ፋሲለደስ፡</persName> እንዘ፡ ሀሎ፡
                                        በ<placeName ref="LOC3577Gondar">ጕንደር።</placeName>
                                        ዘወሀበት፡ <persName ref="PRS14454EhataKrestos"><roleName type="title">ወይዘሮ፡</roleName> እኅተ፡ ክርስቶስ፡</persName>
                                        ለመቅደስ፡ <placeName ref="LOC00000000000000000000">ጊዮርጊስ፡ ዘማንጽሩ፡ </placeName> ዘሠረቆ፡ ወዘተአገሎ፡ ወዘአውጽኦ፡ 
                                        እምደብር፡ እመሂ፡ ንጉሥ፡ አው፡ መኰንን፡ አው፡ በአለ፡ ሥልጣን፡ ውጉዘ፡ ይኩን፡ በአፈ፡ ጴጥሮስ፡ ወጳውሎስ፡ ወበአፈ፡ እግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ እስከ፡ 
                                        ለዓለም። ። ። </q>
                                </colophon>
```

**Comment by CarstenHoffmannMarburg** [comment]
For the PRS that I have pushed recently (PRS14454EhataKrestos, PRS14455AsqaGiyorgis, PRS14457WaldaHawWS, PRS14456WalattaDengel, PRS14458Zamaryam, PRS14459Zamaryam, PRS14460Tsaggo, PRS14461GabraKrestos, PRS14462MalkeaKrestos, PRS14463BahayloZamaryam), see https://github.com/BetaMasaheft/Persons/pull/869.

**Comment by eu-genia** [comment]
As I commented in the record - the Saint Eheta Krestos was a nun in the community of Walatta Petros, and succeeded as abbess in 1642; I doubt she would buy a manuscript for a church of St George. Besides, wayzaro is a title for a noble woman, not for a nun.

**Comment by CarstenHoffmannMarburg** [comment]
According to Strelcyn, this manuscript was "Presented by Sir Geo Elliot, M.P. 10 Sept 1878". Two British politicians with that name come in question:
1) Sir George Elliot (1814-1893, Q1314450) https://www.wikidata.org/wiki/Q1314450 member of parliament for many years.
2) Admiral Sir George Augustus Elliot  (25 September 1813 – 13 December 1901) https://en.wikipedia.org/wiki/Knight_Commander_of_the_Order_of_the_Bath navy commander and short termed member of parliament
