### ISSUE TITLE
The Life of Yāred (ID and subdivision)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2559]
@eu-genia @DenisNosnitsin1970 

In BLorient12860, I came across a text of "The life of Yāred" (ድርሳን፡ ወገድል፡ ዘያሬድ፡).

I found two IDs, that might fit to this text:

a) LIT1512GadlaY with exactly this title and a reference to Conti Rossini 1904 (as in Strelcyns catalogue) but with no witnesses listed so far.

b) LIT1303Dersan entitled Dǝrsāna Yāred and without any references to manuscripts or secondary literature.

My first question: Is LIT1303Dersan a doublet to LIT1512GadlaY, that can be deleted or is there a reason to keep both of them? E.g. can LIT1303Dersan be used to mark the life of Yāred proper excluding the miracles (what is encoded as ms_i1.1 in the manuscript record below)?

Furthermore, there is a subdivision in Strelcyn description on BLorient12860. After the incipit, there are three miracles indicated, that are said to belong to the life of Yāred. However, there is no such subdivision in LIT1512GadlaY (or LIT1303Dersan) and I did not find either any individual record of a miracle of Yāred. Is it appropriate to create three more LIT IDs for the three miracles and link them as sub-IDs to the main record (LIT1512GadlaY)? Alas the given incipits are relatively small and give little information on the content of these miracles.

```
<msItem xml:id="ms_i1">
                            <locus from="1ra" to="26vb"/> 
                            <title ref="LIT1512GadlaY">The life of Yāred</title>
                            <note>With many variations to <bibl><ptr target="bm:ContiRossini1904YaredPantalewonT"/></bibl>.</note>
                            <msItem xml:id="ms_i1.1">
                                <locus from="1ra"/>
                                <title ref="LIT000000000000000">The life of Yāred</title>
                                <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ድርሳን፡ ዘቅዱስ፡ ያሬድ፡ ቀርነ፡ ቤተ፡ ክርስቲያን፡ ዘይጼውዖሙ፡ ለሃይማናን፡ ከመ፡
                                    ይሴብሕዎ፡ ለእግዚአብሔር፡ በክላህ፡ ወበዐቢይ፡ ቃል፡ ከመ፡ ሱራፌል፤ ድርሳን፡ ዘያሬድ፡ ካህን፡ </incipit>    
                            </msItem>
                            <msItem xml:id="ms_i1.2">
                                <locus from="18vb"/>
                                <title>The three miracles belonging to the Life of Yāred</title>
                                <msItem xml:id="ms_i1.2.1">
                                    <locus from="18vb"/>
                                    <title ref="LIT000000000000000000000000" type="incomplete">Miracle 1</title>
                                    <note>The beginning is missing</note>
                                    <incipit xml:lang="gez">ወእምድኅረ፡ አዕረፈ፡ <persName ref="PRS10245Yared">ያሬድ፡</persName> ካህን፡ ፈጺሞ፡ 
                                        ገድሉ፡ ወመዊዖ፡ ሰይጣነ፡</incipit>
                                </msItem>
                                <msItem xml:id="ms_i1.2.2">
                                    <locus from="22rb"/>
                                    <title ref="LIT0000000000000000000000000">Miracle 2</title>
                                    <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ነገር፡ በእንተ፡ ሰዋሬሁ፡ ለያሬድ፡ ካህን፡ ሠርጐ፡ ቤተ፡ ክርስቲያን፡ </incipit>
                                </msItem>
                                <msItem xml:id="ms_i1.2.3">
                                    <locus from="24vb"/>
                                    <title ref="LIT0000000000000000000000000">Miracle 3</title>
                                    <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ነገር፡ በእንተ፡ ሰዋሬሁ፡ ለያሬድ፡ ካህን፡ ዘተወህቦ፡ ጸጋ፡ </incipit>
                                </msItem>
                            </msItem>
                        </msItem>
```

<img width="896" alt="Screenshot 2024_Yared" src="https://github.com/BetaMasaheft/Documentation/assets/40291787/6dbf9a6b-610c-454c-8670-eaf944309342">

**Comment by CarstenHoffmannMarburg** [comment]
@karljonaskarlsson

**Comment by eu-genia** [comment]
In cases of hagiographic dossiers we use 3 or more CAe ID

- Dossier
- - Gadl proper (with forms part of relation)
- - Miracles (with forms part of relation)
- - any other texts that may be part (salam, malk) (with may form part of relation)

as far as I understand the Homily is a separate text that possibly may also be part of the dossier as 
EMML 208
has the following collection that should be used as the template for the Dossier

CAe XXX (new number needed, not present)

1) Ff. la-25a: Homily on St. Yared [Dersana Yared]. = LIT1303Dersan 

2) Ff. 25a-29a: Combat of St. Yared [Gadla Yared]. = LIT1512GadlaY 

3) F. 29ab: Reward promised to those who commemorate St. Yared. = I am not sure if part of Gadl or a separate ID

4) Ff. 29b-4lb: Miracles of St. Yared [Ta’amra Yared] = new CAe ID needed

5) Ff. 4lb-43a: Exhortation to the commemoration of St. Yared = CAe ID XXXX 

6) Ff. 43a-45a: Notice from the Synaxary [Senkessar] for the commemoration of St. Yared on the 11th of Genbot (= 19 May). = CAe ID XXXX with corresp to Synaxary

7) F. 45b: Greeting to St. Yared [Salamta za-Yared]. = CAe ID XXX
...
9) Ff. 78a-8la: "Image" of St. Yared [Malke-’a Yared]. = CAe ID xxx 

10) Ff. 8lb-84a: Chant [mesbak] for St. Yared.  = CAe ID xxx

**Comment by eu-genia** [comment]
so in your case you need two new IDs
ms_i1 = new ID for dossier
ms_i1.1 = Gadl LIT1512GadlaY
ms_i1.2 = Miracles (new ID)
ms_i1.2.1
ms_i1.2.2
ms_i1.2.3

**Comment by eu-genia** [comment]
On rereading the catalogues it seems that Getatchew uses Dǝrsāna Yāred for the longer text and Combat for just a short one, so probably your text here is both

**Comment by eu-genia** [comment]
Let me correct myself. Dersan is the vita. Getatchew split the bit of the contendings, I am not sure what his reasons are. If what he separated is an intrinsic part of the Dersan we probably do not need the split and we possibly could use LIT1512GadlaY for the generic ID

ms_i1 = LIT1512GadlaY 
ms_i1.1 = Dersan LIT1303Dersan 
ms_i1.2 = Miracles (new ID)
ms_i1.2.1
ms_i1.2.2
ms_i1.2.3

According to Tedros, the version in BLorient12860 is more extensive than in Abbadie 227, used by CCR

Maybe both mss (@DenisNosnitsin1970 ) can be described in parallel

**Comment by CarstenHoffmannMarburg** [comment]
> ms_i1 = LIT1512GadlaY
> ms_i1.1 = Dersan LIT1303Dersan
> ms_i1.2 = Miracles (new ID)
> ms_i1.2.1
> ms_i1.2.2
> ms_i1.2.3

Thank you for your investigations and clarification! If I understand you correctly, you want me to create just one ID for the three miracles as a whole, but not three individual IDs for each of them. Is this correct? In this case, the three miracles could form sub-IDs, right?

**Comment by eu-genia** [comment]
as long as no independent circulation is attested I think that sub-IDs for individual miracles suffice

LIT1512GadlaY should be disambiguated as the Collection of hagiographic texts in honour of Yared

**Comment by CarstenHoffmannMarburg** [comment]
I wanted to create a new LIT ID for the Miracles of Yāred, but unfortunately an error occured:

![Screenshot 2024-07-03 121723](https://github.com/BetaMasaheft/Documentation/assets/40291787/ceefec81-bfc7-436b-aa7d-ef2f9dac52ca)

What was my mistake and how can I proceed?

**Comment by eu-genia** [comment]
Have you tried logging out and in?

**Comment by eu-genia** [comment]
As you can easily see the app sees you as "guest", you are not logged in

**Comment by CarstenHoffmannMarburg** [comment]
I was logged in in another tab. I wonder, how I create an ID named LIT7019MiraclesYared, when I was not logged in.

**Comment by eu-genia** [comment]
You have not yet created it.

**Comment by CarstenHoffmannMarburg** [comment]
If I proceed, I will create a new LIT (e.g. LIT7020MiraclesYared) and the previous is spoiled. As I understand, this cannot be avoided?

**Comment by eu-genia** [comment]
No. You have not yet created anything. Guests cannot save. If you proceed you will create LIT7019MiraclesYared

**Comment by eu-genia** [comment]
The app always generates the number adding +1 to the latest item saved. The last one saved is still 7018.

**Comment by CarstenHoffmannMarburg** [comment]
I made a new try. This time, I was definitely logged in. However, it turned to create an ID without LIT-prefix and without number. I am certainly confused!

![Screenshot 2024-07-03 122944](https://github.com/BetaMasaheft/Documentation/assets/40291787/44f11105-f510-4940-91da-db05c502590b)

**Comment by eu-genia** [comment]
This is very strange and I do not see it in the backend; for me everything works and I have created 7019 for you, you can use it now

**Comment by eu-genia** [comment]
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/4dd13626-6028-4c48-97b1-e2513f30e322)

**Comment by eu-genia** [comment]
I now tried to log in as you and all works fine.

**Comment by eu-genia** [comment]
I found it, you created it as a manuscript
![image](https://github.com/BetaMasaheft/Documentation/assets/17987728/057c8157-23a4-4a3f-bd44-bca6ff5561b4)
You forgot to check "work" in the menu. For manuscripts no prefixes or numbers are added.

**Comment by DenisNosnitsin1970** [comment]
Sorry, I switched a litte later: Indeed two versions of Gadla Yared seem to exist, according to EAE V, 26-27; BritLib 12860 and EMML 1844 represent a text somewhat different from what is in Abb 227.

**Comment by eu-genia** [comment]
`LIT1512GadlaY should be disambiguated as the Collection of hagiographic texts in honour of Yared`
