### ISSUE TITLE
New CAe ID for a new Liṭon prayer

### ISSUE THREAD

**Issue by LeonardBahr** [BetaMasaheft/Documentation#2561]
Hello everyone. 

I plan to do a little project with Jonas, who will show me how to create CAe IDs or edit existing files for texts found in MSS based on new data so that I will be able to contribute myself and to reduce the work of the BM staff in helping me with requests.

As an example, we will take a so far little or unknown _Liṭon_ prayer that I found in the MS Miṭāq Takla Haymānot EMML 2109. The MS dates to the 15th century. The text is written in 2 columns of 23 lines each. It is found on fols 87vb18–88va15 of the manuscript. The text appears here as one of the seven _Liṭon_ prayers for the weekdays. Interestingly, it replaces the prayer _Liṭon tazakkar ʾǝgziʾo_ (CAe 4268) in this role at is in absent. Each single prayer is introduced by the words _Liṭon za-nagh_ ‘Liṭon of the morning’. The text has been recognised as ‘Liṭon, not found in the printed texts, f. 87b’ by Getatchew Haile in the catalogue and I also shortly discussed it in my MA thesis (Bahr 2023: 23).

Step 1 would be to create the CAe ID and step 2 to add the prayer in the abstract (General description) of CAe 4860, which corresponds to the general record of the _Liṭon_ prayers of the morning. I was advised to open an issue here as the starting point before working with the BM webpage and atom or oxygen.

**Comment by CarstenHoffmannMarburg** [comment]
Sounds convincing!

**Comment by eu-genia** [comment]
I assume this can be closed
