### ISSUE TITLE
Salām to Jesus Christ / Hymn to the Crucifixion

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2562]
@DenisNosnitsin1970 @eu-genia 

I found a text in BLorient8819, that is also attested in DimmaUnesco1015. For BLorient8819 (f. 78v-83r) Strelcyn describes it as "Salām to Jesus Christ":

```
<msItem xml:id="ms_i2">
                            <locus from="78v" to="83r"/> 
                            <title ref="LIT0000000">Salām to Jesus Christ</title>
                            <note>Missing in Chaîne, Répertoire.</note>
                            <incipit xml:lang="gez">
                                ሰላም፡ ለሥቃይከ፡ ለለ፩፩፤
                                እምሴተ፡ ሐሙስ፡ ዘኮነ፡ እስከ፡ ምሴተ፡ ዓርብ፡ የዓዱ።
                                ኢየሱስ፡ ክርስቶስ፡ ተስፋ፡ ኤዎስጣቴዎስ፡ ወውሉዱ።
                                ዘበእንቲአሁ፡ ሶበ፡ በውስቴቱ፡ ወረዱ፤
                                ለእሳተ፡ ጤገን፡ ዘብርት፡ አብሰሎሙ፡ ነዱ።
                            </incipit>
                        </msItem>
```

In DimmaUnesco1015, the same text with similar incipit can be found under the title "Hymn on the crucifixion":

```
<msItem xml:id="ms_i9">
                     <title>Hymn on the crucifixion</title>
                     <incipit xml:lang="gez">ሰላም ፡ ለሥቃይከ ፡ ለለ፩፩ ። እምሴተ ፡ ሐሙስ ፡ ዘኮነ ፡ እስከ ፡ ምሴተ ፡ ዓርብ ፡ ያዓቶ ፡ ኢየሱስ ፡ ክርስቶስ ፡</incipit>
                  </msItem>
```

Do you agree to create a new LIT for this text? Which title would you prefer? Do you think የዓዱ is correct in the second line?

**Comment by eu-genia** [comment]
Judging by https://www.facebook.com/DnMelakuYifru/posts/1856422721166773/?paipv=0&eav=AfbQwKz8ucW-k7bayeTN7KcUwX85BqB-BL2rpKqZLFIyqoJH3-SZqDBMmQyouaVeKtI&_rdr this is a text read on the feast commemorating the Crucifixion/Sunday (ስንክሣር ዘወርኃ መስከረም); it also looks that it could be present in the Synaxarion for Maskaram and as such could already have a sub-ID there (`Mask17SalCross`?)

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for this discovery! However, in these two manuscripts, this hymn is attested independent from the synaxary. In that case, it would be necessary to create a new LIT for it nevertheless, correct?

**Comment by eu-genia** [comment]
right, and eventually add a corresp in the relevant div xml:id

**Comment by CarstenHoffmannMarburg** [comment]
Which recension do you think, is the relevant to be picked? How can I verify the existence of this 'hymn to the Crucifixion' inside a synaxary? Should I better look it up in a manuscript or in an edition?

**Comment by DenisNosnitsin1970** [comment]
The PO edition is the standard text.

**Comment by DenisNosnitsin1970** [comment]
It may be under Mesqel feast or around, somewhere in Mekerem.

**Comment by DenisNosnitsin1970** [comment]
In fact, it is present in internet, seems to be under 27 Meskerem in the Synaxary.

**Comment by CarstenHoffmannMarburg** [comment]
The edition by Colin in PO (1986) does not contain Salams I have seen in the HLZ library exemplar and Dorothea confirmed to me. 

The recommended manuscript witnesses for Group A (LIT4032SenkessarS) are not available to me (BNFabb66A, EMML6458) or do not contain the requested month (BNFabb66B) or do contain only fragments with no hint to the desired text (BNFet677).

For the General record (LIT2375Synaxa) no more than fragments or isolated commemorations are attested in witnesses.

For Group B (LIT4033Senkessar) the manuscripts are not available (EMML6952, ESam019, ESqdq004, EMML4398, EStzm001), or they do not have the desired text (EMIP01859, BNFet677, EStzm002).

Possibly @thea-m can help?

**Comment by thea-m** [comment]
The salams are only present in manuscripts of the second recension, you can check the manuscript witnesses of LIT4035SenkessarDL

**Comment by DenisNosnitsin1970** [comment]
Indeed. For sure it may be present in some Synaxarion witnesses.

**Comment by CarstenHoffmannMarburg** [comment]
Indeed, I found this text in ESdd017 on f. 29ra-b. It is one of the witnesses of LIT4035SenkessarDL, as Dorothea recommended. In the record it is possibly already documented with the sub-ID Mask27SalEwostatewos, because Ewosṭātewos is mentioned in it. I think, it is not necessary to create a new sub-ID.

**Comment by eu-genia** [comment]
I think one could either use `LIT4035SenkessarDL#Mask27SalEwostatewos` - or create a new ID to refer in BLorient8819 (independent circulation) and add in `LIT4035SenkessarDL `a `corresp ` to this new ID under `Mask27SalEwostatewos` to state the identity
