### ISSUE TITLE
Amharic commentary-introduction to Kidān za-nagh and Tǝmhǝrta ḫǝbuʾat in BLorient11719

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2565]
@eu-genia @karljonaskarlsson @DenisNosnitsin1970 

I found a number of Amharic commentaries to the Amharic commentary-introduction to the Kidān za-nagh (=LIT1716Kidanz) and to the Tǝmhǝrta ḫǝbuʾat (=LIT2444Temher) in BLorient11719. The texts are only known to me through incipits given by Strelcyn in his catalogue.

I have seen, that similar commentaries exist already for the works in EMIP00634, but I did not find much textual correlation to the LIT that are marked up in that record (e.g. LIT5941CommKidan). Moreover, I found, that LIT5944CommMystatgogia (or any ID with LIT5944) does not exist, yet (I did not find it in the list of renamed or deleted IDs either. I suspect, that it is not yet merged).

I suggest new LIT IDs (one LIT ID and two sub-IDs) for the following texts:

```
<msItem xml:id="p2_i1">
                                <locus from="3ra" to="28rb"/> 
                                <title ref="LIT0000000000000000000000000000000000"/>
                                <note>Amharic commentary-introduction to <ref type="work" corresp="#LIT1716Kidanz">Kidān za-nagh</ref>
                                    and <ref type="work" corresp="#LIT2444Temher">Tǝmhǝrta ḫǝbuʾat</ref>.</note>
                                <msItem xml:id="p2_i1.1">
                                    <locus from="3ra" to="9ra"/>
                                    <title ref="LIT0000000000000000000000000000000000">Beginning of the commentary on the kidān za-nagh.</title>
                                    <incipit xml:lang="am">በስመ፡<gap reason="ellipsis"/> ኪዳን፡ ዘነግሕ፡ ዘነገሮሙ፡ እግዚእነ፡ ለሐዋርያት፡ ጸሎቱ፡ ወበረከቱ፡ ወኃብተ፡ 
                                        ረድኤቱ፡ የሀሎ፡ ምስሌነ፡ ለዓለመ፡ ዓለ<corr resp="PRS8999Strelcyn">ም</corr>፡ አ<corr resp="PRS8999Strelcyn">ሜን</corr>። 
                                        ጌታ፡ በሕይወተ፡ ሥጋ፡ ሳለ፡ ፫ት፡ ዓመት፡ ከ፫ት፡ ወርኅ፡ ያስተማረው፡ ወንጌል፡ ይባላል፡ ሞቶ፡ ተነስቶ፡ ያስተማረው፡ ኪዳን፡ ይባላል፡ ይሀውም፡ ይታወቅ፡ ዘንድ፡
                                        ቅዱስ፡ ጳውሎስ፡ በገላትያ፡ ክታቡ፡</incipit>
                                    <explicit xml:lang="am">ይትእምርተ፡ ኅቡአትና፡ የከዳን፡ መቅድማቸው፡ አንድ፡ ነው። ከእንግዴህ፡ ወዲህ፡ ትእምርተ፡ ኅቡዓት፡ ቢሉ፡ ወይትእምርተ፡
                                        ኅቡዓት፡ ኪዳን፡ ቢሉ፡ ወይኪዳን፡ ይሔድዋል። ትእምርተ፡ ኅቡዓትም፡ ኪዳንም፡ የጌታ፡ ቃል፡ ስለ <pb n="9ra"/>ሆኑ፡ በየፈንታ፡ ይነገራሉ፡ እንጅ፡ እንድ፡
                                        ጊዜ፡ አይነግሩም። ነገር፡ ግን፡ ካህን፡ ትእምርተ፡ ኅቡዓት፡ ሳይተረgwaም፡ መቅደሱን፡ አይከፍተው፡ ካለ፡ ትእምርተ፡ ኅቡዓት፡ ይቅድም።</explicit>
                                    <textLang xml:lang="am"/>
                                </msItem>
                                <msItem xml:id="p2_i1.2">
                                    <locus from="9ra"/> 
                                    <title ref="LIT0000000000000000000000000000000000">Beginning of the commentary on the  tǝmhǝrta ḫǝbuʾat</title>
                                    <note>On <locus from="14v" to="27r"/> the rubrics are missing.</note>
                                    <incipit xml:lang="am">በእንተ፡ ትእምርተ፡ ኅቡአት። ኅቡዓትን፡ የመማር፡ ኅቡዓትን፡ የማስተማር፡ ነገር፡ እንዲህ፡ ነው፡ ብሎ፡ አፍዝዞ፡ ተወው። አንድ፡
                                        የኅቡዓትን፡ ዘይቤ፡ ለማውጻት፡ ስለሽሽግ፡ ትእምርት፡ ስል፡ ነው። በአንተን፡ ነገር፡ ሰል፡ ምን፡ ምስክር፡ አለ፡ ቢሉ። </incipit>
                                    <textLang xml:lang="am"/>
                                </msItem>
                            </msItem>
```

**Comment by eu-genia** [comment]
@Ralph-Lee-UK can you check if LIT5944CommMystatgogia is sitting somewhere on your computer? I do not see it, and it is used in EMIP00634. Thank you!

**Comment by eu-genia** [comment]
I think you can create the IDs, thank you

**Comment by Ralph-Lee-UK** [comment]
@eu-genia sorry for the delay. I don't have this file, but I see that you have dealt with the problem

**Comment by CarstenHoffmannMarburg** [comment]
> I think you can create the IDs, thank you

If I understand you correctly, you want me to create the three new LIT IDs for BLorient11719 (p2_i1, p2_i1.1 and p2_i1.2). 

For text encoded as LIT5944CommMystatgogia in EMIP00634, we still need a decision. Should I remove the link or shall I create a new one to replace the LIT5944CommMystatgogia?

**Comment by eu-genia** [comment]
We need to recreate the file (not through the app but saving directly as 5944, as you do for manuscripts)

**Comment by CarstenHoffmannMarburg** [comment]
> > We need to recreate the file (not through the app but saving directly as 5944, as you do for manuscripts)
> 
> OK. Is it neccessary to repeat the orthographical error in Mystatgogia or can it be LIT5944Mystagogia?

Shall I save it to the new-folder (file:/C:/Users/Hoffmann/Desktop/BetMas/Works/new/LIT5944Mystagogia.xml) or to the folder 5001-6000?

**Comment by eu-genia** [comment]
the easiest is to recreate the same filename but of course if the error is upsetting it can be changed. 5001-6000 better

**Comment by CarstenHoffmannMarburg** [comment]
> the easiest is to recreate the same filename but of course if the error is upsetting it can be changed. 5001-6000 better

OK. For this time, I saved it to the 'New' folder. I hope, that this is OK. I guess, that it is problematic to resave it to another folder, when it is already in processing.

**Comment by eu-genia** [comment]
as long as a PR has not been merged the app has no idea about whatever is on any of the github branches, so you can freely rename and move files as much as you want. it is not in processing.
