### ISSUE TITLE
Refer to websites / online catalogues

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2567]
Hello!

Is there a way to refer to websites / online catalogues as part of the bibliography in a manuscript record? For the Uppsala manuscripts that I am now encoding, the entries on the manuscripts in the online database Alvin sometimes provide more information than the printed catalogues (more measurements, for example) and it would be good to be able to refer to these.

(I'm sorry if there is already a discussion about this somewhere – I could not find anything on this in the Guidelines)

@CarstenHoffmannMarburg @eu-genia @DenisNosnitsin1970

**Comment by eu-genia** [comment]
Of course, you should create a zotero record for the database and assign a bm: tag, as there is e.g. bm:vHMML to refer to HMML digital catalogue or bm:EthioSpare to refer to Ethio-Spare database etc
