### ISSUE TITLE
Unknown letter (ži?)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2569]
@DenisNosnitsin1970 @eu-genia @karljonaskarlsson 

I found a form of a letter in Strelcyns catalogue description on BLorient2263, that I do not have on my keyboard. Can anybody provide an ASCII symbol or something else to insert in this place or should I explain it explicitly in a note?

![Screenshot 2024-07-04 170109](https://github.com/BetaMasaheft/Documentation/assets/40291787/91aeb2f2-365c-428a-bc31-4a0db6725ae3)

It is from an Arabic-Tigrinya glossary and the middle letter (ži?) occurs several times in different words. However, the normal letter ዢ ži happens to appear as well on other places in the same ms_item.

**Comment by eu-genia** [comment]
are there occurrences also for the first order that look differently?

**Comment by DenisNosnitsin1970** [comment]
Could it be an attempt to denote the 6th-order ዥ (Ijlis! for "ተቀመጥ!") in the time when the shapes of those additional graphems were not yet fixed (and they were not in the regular use)?

**Comment by CarstenHoffmannMarburg** [comment]
Thanks for your comments! I will use ዥ to transscribe it. (arab. ʾiǧlis = 'sit down!') Beyond ዥ, there are several ዢ, that has come to my attention so far. I remember a similar case in one of the BML-manuscripts in Florence.

**Comment by CarstenHoffmannMarburg** [comment]
I found some letters in Strelcyns catalogue description for BLorient12996, that I cannot find as ASCII signs in [Wikipedia](https://en.wikipedia.org/wiki/Ge%CA%BDez_script) or [Lexilogos.com](https://www.lexilogos.com/clavier/geez.htm). Do you have other suggestions, that can possibly help? I am interested in the sign for 'moa', 'mha' and ž in the sixth order.

<img width="818" alt="Screenshot 2024_lettersII" src="https://github.com/user-attachments/assets/89ef4c33-eabb-43cf-8c77-02f10edfd053">

The sign for moa can be seen in the desired correct form (ፙ) here in github and on the [Wikipedia-site for Gǝǝz-script](https://en.wikipedia.org/wiki/Ge%CA%BDez_script), but however, when I insert it to the oxygen on my computer it is represented differently with a stroke below and above:

<img width="425" alt="Screenshot 2024_letterIII" src="https://github.com/user-attachments/assets/7a93a3e3-eabc-40e3-9093-36384ee352eb">

I wonder, which form will be found on the website eventually?

**Comment by eu-genia** [comment]
As you can easily see from Wikipedia ፙ stands there as a diacritic for m**y**a, not for mwa/moa (which we would write now as ሟ ). I would assume the lexicon was written at the time when some diacritics were not yet standardized. These idiosyncracies cannot be represented with Unicode, only as drawings. 
So either the signs have to be described in words, or saved as images, uploaded to the server, and pointed at as images.
@abausi other suggestions?

**Comment by CarstenHoffmannMarburg** [comment]
Yes, I already prepared a note with an explicite description just for the case, that these signs can not be represented accordingly. However, it would be nice to know, what come out, when I type ፙ in the oxygen.

```
<note>The author gives the Arabic letters corresponding to the Amharic characters and also indicates the 
                                        pronunciation with reference to German (indicated as <foreign xml:lang="la">Germ.</foreign>), Czech (indicated
                                        as <foreign xml:lang="la">Boem.</foreign>, Italian (indicated as <foreign xml:lang="la">Ital.</foreign>, and 
                                        French <foreign xml:lang="la">Gall.</foreign>. There are also references to Persian. The author notes the letters
                                        <foreign xml:lang="am">ፙ</foreign>, transliterated as 'moa',
                                        a form similar to <foreign xml:lang="am">ፙ</foreign>, but with a haste for the second order on the right side and
                                        transliterated as 'mha' (sic) as well as <foreign xml:lang="am">ኸ</foreign>, transliterated as 'chha', etc.
                                        <foreign xml:lang="am">ጸ</foreign> and <foreign xml:lang="am">ፀ</foreign> are both transliterated as 'za',
                                        <foreign xml:lang="am">ጀ</foreign> is transliterated as 'gia'. The series of ž is noted by
                                        <foreign xml:lang="am">ዠ</foreign>etc. (a character with a haste on the lower left side signifies the sixth order).
                                        The pronunciation of <foreign xml:lang="am">ቸ</foreign> is indicated as 'cia' (but on <locus target="#5r"/>:
                                        <foreign xml:lang="cs">cža</foreign> <foreign xml:lang="la">Boem.</foreign>) and that of
                                        <foreign xml:lang="am">ጨ</foreign> as 'cca' (but  <foreign xml:lang="cs">cža</foreign> (sic!) 
                                        <foreign xml:lang="la">Boemice</foreign>). The author notes the difference between the first and the fourth orders
                                        only as a difference in length but indicates the two functions of the sixth.</note>
```

**Comment by abausi** [comment]
This is a bit unknown land. An as clear as possibile description in words, accompanied by screenshot would be OK.

**Comment by CarstenHoffmannMarburg** [comment]
This is the sign in BLorient12996 according to Strelcyns catalogues typesetting.

<img width="90" alt="Screenshot 2024_zhe (Strelcyn)" src="https://github.com/user-attachments/assets/4c7558e1-9f21-4a04-80da-a314b0632732">

**Comment by eu-genia** [comment]
you could insert the figure in the record as 
```
    <figure>
        <graphic url="BLorient12996/sign1.tif">
        </graphic><desc>...</desc>
    </figure>
```
but at the moment it does not look very good as the viewer is set up for larger images (I have inserted for testing and it fills the whole column), it does not work for small ones; I will try to find a different solution

![image](https://github.com/user-attachments/assets/cfba0aa3-cfca-4249-8b0f-73a504716abb)

**Comment by eu-genia** [comment]
I have added a workaround for small images, see the updated guidelines 
```
<figure>
          <graphic
            url="https://betamasaheft.eu/resources/images/snippets/BLorient12996/sign1.png" height="30px">
            <desc>Symbol used in BL oriental 12996</desc>
          </graphic>
        </figure>
```
![image](https://github.com/user-attachments/assets/d25eeadf-6a38-47a0-833c-6ca2208038f3)

**Comment by CarstenHoffmannMarburg** [comment]
Thank you!

Another symbol is the letter žǝ as used in Strelcyn's catalogue for BLorient2263 (mentioned above).

<img width="73" alt="Screenshot 2024_ž in Strelcyn BLorient2263" src="https://github.com/user-attachments/assets/065f6aa5-dd49-4a42-b446-d6d2def30757">

**Comment by eu-genia** [comment]
you can use the same code, with `sign2.png`

**Comment by CarstenHoffmannMarburg** [comment]
Thank you for creating this graphic! Is it useful to fill the desc inside figure and to integrate it in the text as I did here: 

```
<msItem xml:id="ms_i3.2">
                                <locus from="6ra" to="12vb"/>
                                <title ref="NAR0184ForeignWords">Tigrinya-Arabic Vocabulary</title>
                                <note>Containing several words on <locus target="6ra"/> with a special ancient form of the letter 
                                    <foreign xml:lang="ti">ዥ</foreign> with small strokes in every of the four edges (<figure>
                                        <graphic url="https://betamasaheft.eu/resources/images/snippets/BLorient12996/sign1.png" height="30px">
                                            <desc>Symbol used in BL oriental 2263</desc></graphic></figure>).</note>
                                <incipit xml:lang="ti">ነዓ፡ ብሂል፡ ተአል፤
                                    ተቀመጥ፡ ብ፡ አይዥልስ፤
                                    ተንሥእ፡ ብ፡ ጉም፡ ቁምሂ፤
                                    ኪድ፡ ብ፡ ሩሕ፤
                                    ኬድኩ፡ ብ፡ ሮሕ፡ 
                                    ኬደ፡ ብ፡ ራሕ፡ መሻ፤
                                    ተመልሰ፡ ብ፡ ገለበ፤
                                </incipit>
                                <textLang xml:lang="ti"/>
                            </msItem>
```

Will this be displayed correctly? Will the desc be visible to everyone who opens the manuscript page or is it a clickable add-on?

**Comment by eu-genia** [comment]
the desc would appear as in my example above

note that line breaks in the xml created by hitting enter/return have no meaning and are neither visualized nor computed. if you need to underline that it is a poetry you can use` l` inside of `seg`, if you need to show that the manuscript has line breaks you should use `lb/`

**Comment by CarstenHoffmannMarburg** [comment]
My question was, how this graphic representation will be integrated in the text on the webpage. I think, it might be more useful to delete the desc, because this is already told in the note.

I do not know, whether the manuscripts has line breaks. It is not poetry, but vocabulary. I think, it is not necessary or useful to use `<l>` or `<lb>` here.

**Comment by eu-genia** [comment]
If you do not need the desc you do not insert the desc
