### ISSUE TITLE
Magic prayers in d'Abbadie 207

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2570]
I need a few new records to encompass magic prayers in Abb. 207. 
![grafik](https://github.com/BetaMasaheft/Documentation/assets/18533839/0c00e229-5758-41bf-9a0e-20ff6ac7d7e4)

**Comment by CarstenHoffmannMarburg** [comment]
I have found no relevant parallels in works or manuscripts. However, the more I come into contact with magical prayers, the more I am convinced that it is more important to identify the saints and demons invoked, as well as the diseases and calamities, rather than the texts themselves. This genre of text is too fluid to be well represented in the many LIT records that we already have and that are likely to be created in the future.

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 will you take care of this? or would you like to ask someone to do it?

**Comment by eu-genia** [comment]
if this is closed through a pull request in works - please link that pull request to this issue to make this clear

**Comment by DenisNosnitsin1970** [comment]
Just a remark to the comment above: the demons and saints can be tagged, but still we have to stay with texts, someow. "Fluidity" may be just an explanation for our insufficient knowledge of these texts due to the lack of the manuscript material or loss theirof (in other words, we only stand at the ends of the transmission chains, the witnesses in between are missing).

**Comment by DenisNosnitsin1970** [comment]
https://github.com/BetaMasaheft/Works/pull/1137

**Comment by eu-genia** [comment]
Ok but for the future it is better that from the pull request you link to the issue the pull request is responding to

**Comment by eu-genia** [comment]
inserted now in the first comment there

**Comment by CarstenHoffmannMarburg** [comment]
> Just a remark to the comment above: the demons and saints can be tagged, but still we have to stay with texts, someow. "Fluidity" may be just an explanation for our insufficient knowledge of these texts due to the lack of the manuscript material or loss theirof (in other words, we only stand at the ends of the transmission chains, the witnesses in between are missing).

Yes, I see, that this would be practical. However, Saints can be marked up as PRS, but demons cannot get a PRS as they are supernatural and not personified (enough) as I understand the discussions in https://github.com/BetaMasaheft/Authority-Files/pull/33 and in https://github.com/BetaMasaheft/Documentation/issues/2627. I think this matter needs clarification in a way that we know how to refer to demon (or what we think may be demonic).
