### ISSUE TITLE
PERS in Uppsala O Etiop 3

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2574]
Hello! I wonder if you think it is justified to create a PERS record for the person mentioned in this supplication in Uppsala, O Etiop. 3:

<img width="1041" alt="Skärmavbild 2024-07-11 kl  15 21 53" src="https://github.com/BetaMasaheft/Documentation/assets/34240156/6f8674a6-0518-4152-94b0-48a6b8b36205">

(For the zoomable image, see: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0119&pid=alvin-record:177135)

I think it is quite safe to read: ያ[…]ቅበ[…] አብ፡. The name could be Yāʿqəbanna ʾAb or, possibly, Yāʿqəbakka ʾAb.

@CarstenHoffmannMarburg @DenisNosnitsin1970 @eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
I would suggest the reading ያዕቆብ፡ ዘአብ፡. 

I propose to create a PRS ID and note the alternative readings as n2 and n3 and perhaps describe the insecurity somehow. I would think, that the abstract in a PRS record would be the suitable place for such a note, but I think, we are not using the abstract in PRS records to mark such constraints, do we?

**Comment by eu-genia** [comment]
I would not create a PRS record, just note that the owner's name has been effaced and only a few letters can be guessed. There surely are at least two graphemes between ያ (if it is a ያ) and ቅ. I rather am guessing .. ምቅበ ...

**Comment by karljonaskarlsson** [comment]
Ok, thank you, @CarstenHoffmannMarburg and @eu-genia, for the input!
