### ISSUE TITLE
Creating IDs for Institutions

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2576]
I have came across a problem trying to create IDs for Institutions. I click on "new", routinely, and select "institution", and fill in the formular, but the system creates an ID with the prefix "LOC". I tried several times. Is it a problem, or I did smth wrong?

**Comment by eu-genia** [comment]
you did something wrong. all works ok. you must have selected place. 
I deleted the three places CelaMaryam. If you need an institution, create an institution, I have just tried and it works.

**Comment by eu-genia** [comment]
You must FIRST select institution and THEN click new
