### ISSUE TITLE
"Belleza" close to Asmara

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2579]
The manuscript Uppsala, O Etiop. 7 was donated by August Bergman who, according to a note in the ms, had been a missionary in "Belleza, Asmara". This is probably the "Bäläsa (10 km north of Asmara)" mentioned in EAe IV, p. 1188a, but I'm unsure about which LOC refers to this place. (Note that the "Bäläsa" mentioned in EAe IV appears under "Bäläza" in the index in EAe V.)

There are the following records:

LOC1738Balasa (https://betamasaheft.eu/places/LOC1738Balasa/main), with no attestations
LOC1741Balaza (https://betamasaheft.eu/places/LOC1741Balaza/main), with no attestations
LOC1739Balasa (https://betamasaheft.eu/places/LOC1739Balasa/main), which seems to have connections to Gondar
LOC7209Balasa (https://betamasaheft.eu/places/LOC7209Balasa/main), which seems to be in Tigray

Those of you who know Bm history better than I, can we say which of these records corresponds to the place mentioned in EAe IV? @CarstenHoffmannMarburg @DenisNosnitsin1970

**Comment by DenisNosnitsin1970** [comment]
It might be either 38 or 41 (other two I know). I assume if the IDs have not been used in any way in other records of all repertories, you can take one of them and add itendification.  But I know that Zhenja transformed all places of the index into IDs, maybe she has precise info which EAa articles those to refer to.

**Comment by karljonaskarlsson** [comment]
I would presume then that it is LOC1741Balaza, as the place name appears with "z" in the index.

**Comment by CarstenHoffmannMarburg** [comment]
Yes, please use LOC1741Balaza for it and update this record with some details (even though I could not find it on googlemaps or in the web). 

The others are written with "s" and they are two rivers and a district.
