### ISSUE TITLE
Qǝne poems in Mazgaba dǝrsān and in a collection attributed to Gabra Masiḥ (BLorient9798)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2580]
@karljonaskarlsson @DenisNosnitsin1970 

I found qǝne poems in BLorient9798. 

If I understand the discussion in https://github.com/BetaMasaheft/Documentation/issues/2504, I need to mark up these poems as authFile with the keywords Qene, EtanaMogar, Wazema, Sellase, Mawaddes and Zayeeze. 

In addition, there is one qǝne poem mentioned as ጉባዔ፡ ቃና፡ (= "meeting at Cana"), that I did not come across as a type or mode in qǝne and that is not encoded as a qǝne mode in bm. Is this mode missing in the list?

For the collection entitled "Mazgaba dǝrsān", it is probably necessary to create new ID, as Denis wrote in https://github.com/BetaMasaheft/Documentation/issues/2578.

Another collection is attributed to a person with the name Gabra Masiḥ and I wonder, whether this was PRS4322GabraMa, PRS4323GabraMa or PRS4324GabraMa. All three of them seem to be possible candicates to me.

```
<msItem xml:id="ms_i2">
                            <locus from="39vb" to="49ra"/>
                            <title ref="LIT0000000000000000000">Mazgaba dǝrsān</title>
                            <note>A collection of 90 <ref type="authFile" corresp="#Qene">qǝne songs</ref> of different kinds: 
                                65 <ref type="authFile" corresp="#Sellase"/>, 
                                12 <ref type="authFile" corresp="#Mawaddes"/>, 
                                8 <ref type="authFile" corresp="#Wazema"/>,
                                4 <ref type="authFile" corresp="#EtanaMogar"/> 
                                and 1 <ref type="authFile" corresp="#Zayeeze"/>.</note>
                            <incipit xml:lang="gez">ናሁ፡ እጽሕፍ፡ መዝገበ፡ ድርሳን፡ ዘይረስዎ፡ አዕረስዎ፡ አዕሩግ፡ የዋሃን፡ ወወራዙት፡ ማእምራን፡ ውስተ፡ ቅድስት፡ ቤተ፡ ክርስቲያን፡
                                ባሕቱ፡ ይክሥ<pb n="40ra"/>ት፡ ሊተ፡ እግዚአብሔር፡ ጥበበ፡ ወኪነ፡ አሜን።</incipit>
                            <textLang mainLang="gez"/>
                            <msItem xml:id="ms_i2.1">
                                <title>Qǝne poem of the <ref type="authFile" corresp="#Sellase"/>-type</title>
                                <incipit xml:lang="gez"><persName ref="PRS00000000000000000000000">ኤዎስጣቴዎስ፡</persName> እንዘ፡ 
                                    <title>እልፍ፡ ውሉድ፡ ውስተ፡ ሕፅንከ፡</title> 
                                    <lb n="1"/>እስመ፡ ወርኃ፡ ተድላ፡ ኮኖሙ፡ ለአዕባነ፡ ፍኖት፡ አፈ።
                                    <lb n="2"/>ተሣለቁ፡ እፎ፡ ጸጋከ፡ ትሩፈ።
                                    <lb n="3"/>በፍጻሜ፡ ግፍዕከሰ፡ ከመ፡ ቃለ፡ ሙሴ፡ ጸሐፈ።
                                    <lb n="4"/>ዘመን፡ ለከ፡ እመ፡ ኃለፈ።
                                    <lb n="5"/>አሐዱ፡ ወልድከ፡ ያስተጋብእ፡ ጽንፈ።
                                    <lb n="6"/>ወክልኤቱ፡ ይስድዱ፡ እልፈ።</incipit>
                            </msItem>
                        </msItem>
```

```
<msItem xml:id="ms_i4">
                            <locus from="57v" to="58r"/>
                            <title ref="LIT0000000000000000000">Qǝne poems attributed to Gabra Masiḥ</title>
                            <note>Nine <ref type="authFile" corresp="#Qene">qǝne songs</ref> attributed to Gabra Masiḥ
                                (possibly <persName ref="PRS4322GabraMa">Gabra Masiḥ</persName> or 
                                <persName ref="PRS4323GabraMa">Gabra Masiḥ</persName>): 
                                5 <ref type="authFile" corresp="#EtanaMogar"/>, 
                                1 <ref type="authFile" corresp="#Wazema"/>, 
                                1 <ref type="authFile" corresp="#Sellase"/>, 
                                and 1 in the <foreign xml:lang="gez">ጉባዔ፡ ቃና፡</foreign>-type,
                                written by at least two hands and partly illegible.</note>
                            <textLang mainLang="gez"/>
                        </msItem>
```

**Comment by CarstenHoffmannMarburg** [comment]
I think ኤዎስጣቴዎስ in ms_i2.1 can be identified with PRS3934Ewostate.

**Comment by CarstenHoffmannMarburg** [comment]
My searches for some of the words were not successful. I think, the text, that are encoded as incipits are not attested in bm so far.

**Comment by DenisNosnitsin1970** [comment]
I used to encode qene terms like this: `<foreign xml:lang="gez">śǝllāse</foreign>`, and in Keywords (both for work and ms you can select respective terms - qene and qene types). Guba'e qana is supposed to be among them, if it is not the case, ask ask Zhenija. Persons listed above unlikely fit for the role (or, there is no indication whatsoever for that), it is better to create a new record.

**Comment by CarstenHoffmannMarburg** [comment]
> I used to encode qene terms like this: `<foreign xml:lang="gez">śǝllāse</foreign>`, and in Keywords (both for work and ms you can select respective terms - qene and qene types). Guba'e qana is supposed to be among them, if it is not the case, ask ask Zhenija. Persons listed above unlikely fit for the role (or, there is no indication whatsoever for that), it is better to create a new record.

Can you recommend a best practice example to me? Some records, which I have opened do not provide keywords for qene or for the different modes.

**Comment by DenisNosnitsin1970** [comment]
I have just pushed a PR of four qene poems, this is the scheme we/I use for qenes (I have created a number of IDs in the last months). You should be able to indicate both the genre and all qene types through keywords, if there are some records without, they must have been created before all keywords were introduced.
