### ISSUE TITLE
Doublets? LOC4396Maekal and LOC4444Makal

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2584]
There are two zobas with the same name Māʾkal – LOC4396Maekal and LOC4444Makal – and nothing to set them apart. I wonder if they may be doublets

@DenisNosnitsin1970 @CarstenHoffmannMarburg @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Possibly, but one of them with Ayn, another with Alif. Ultimately, they all originate from the index of EAe. Check if they have been used in the records.

**Comment by karljonaskarlsson** [comment]
LOC4444Makal has only been used by me today. LOC4396Maekal has not been used, as far as I can see.

**Comment by eu-genia** [comment]
Māʿkal (LOC4396Maekal) is correct 
![image](https://github.com/user-attachments/assets/608d9dd8-0b8c-4a09-ad80-c67c451301dd)

Māʾkal is an error/typo for Māʿkal in EAe V:150
![image](https://github.com/user-attachments/assets/9ae72b58-524c-4d98-a61c-1ab0d8f53e1e)

So one of the two should be deleted, the other checked for the correct orthography (ayn is correct)

**Comment by eu-genia** [comment]
Sorry we should harmonize the main title to alif, not ayn

https://ti.wikipedia.org/wiki/%E1%8B%9E%E1%89%A3_%E1%88%9B%E1%8A%A5%E1%8A%A8%E1%88%8D

possibly the spelling with ayn can be added as a variant but also the Amharic spelling without any laryngeal (ማከል)

1 ti ማእከል (Eritrean Ti)
2 ti ማዕከል (Tigray Ti)
3 am ማከል (Amharic)

**Comment by eu-genia** [comment]
@karljonaskarlsson 
can you possibly update LOC4444Makal  with the variants, add relation formerlyAlsoListedAs and delete LOC4396Maekal to close this issue? Thank you!
