### ISSUE TITLE
Nǝʾus zobā

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2587]
As discussed in https://github.com/BetaMasaheft/Places/pull/118, it would be good to have "nǝʾus zobā" as a possible value of "type" within "place" (for smaller administrative units of Eritrea).

Note that it is spelled "nǝʿus zobā" in the EAe article "Administrative division of Eritrea", but this seems to be the less common spelling.

@DenisNosnitsin1970 @eu-genia

**Comment by DenisNosnitsin1970** [comment]
Now I do not know why, but nǝʾus is the correct spelling.
