### ISSUE TITLE
Creating a new record - so-called "Anonymous Homily on the Eucharist"

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2590]
I would like to create a new record for the unique homily preserved in BNFabb66A (starting at f.149v) and then insert it into the manuscript record created by Dorothea. The homily was first published as bm:Beylot1983Sermon and then re-edited as bm:Fritsch2019Order. 

I have not found the record for it in the database. 
@CarstenHoffmannMarburg @eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
Thanks for your initiative! It sounds great to achieve such an improvement! Before you start: Can you provide a text in this issue? Which ms_item do you refer to? I do not have Beylot 1983 and Fritsch 2019 at hand. If you could provide a screenshot, that would be great!
This work is included in a record of the LIT4032SenkessarS. In this case, it should stay like this. But you can add the new LIT ID to the work record (LIT4032SenkessarS), once it is created.

**Comment by MarcinKrawczuk** [comment]
a) The text is quite long so I'm attaching just the beginning.
![2](https://github.com/user-attachments/assets/7eca7dcb-b80d-4730-ba64-4cc265ef38cc)
![1](https://github.com/user-attachments/assets/8c2e8fbd-2836-477c-b925-773ecff34feb)
I suppose we could use ነገር፡ በእንተ፡ ሥርዓተ፡ ምስጢር፡ as the title.

b) In BNFabb66A it is ms_i1.5.28.3

**Comment by CarstenHoffmannMarburg** [comment]
I did not find a work record either. So please go ahead and create a work record for this. The proposed title seems very suitable to me, too. 

I found a similarity in text to in BMLor70, f. 116 (p1_i1.6, LIT3519Epistle): ቃለ፡ ጽድቅ፡ ትምህርተ፡ ሕይወትክሙ፡ ወአመንክሙ፡ is similar to what is found in the second phrase of the text, that you presented above. This might be incidental or the author took up the motif and paraphrased it.

**Comment by MarcinKrawczuk** [comment]
I'm going offline for two weeks now, I'll get back to this after that.

**Comment by thea-m** [comment]
Great, thank you! Could you mention me in the work PR? Then I can insert the ID into the manuscript BNFabb66A, which I am currently editing in an existing branch.
