### ISSUE TITLE
Magical Prayer against disease (ferā) and fever (nədād) in BLorient11763

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2591]
@DenisNosnitsin1970, @karljonaskarlsson 

I found a prayer in BLorient11763, which is entitled by Strelcyn as follows: "Prayer by the Archangel Michael against contagious disease (fera) and malarial fever" (incipit: በስመ፡ (...) ጸሎተ፡ ፌራ፡ ወንዳድ፡ ዘቅዱስ፡ ሚካኤል፡ ሊቀ፡ መላእክት፡ (...) ሌኬ፡ ኤንካ፡ ጌሌ፡

There are some LIT ID to prayers against ferā and nədād, but they seek for protection primarily against various demons and there is no Michael involved (as far as this can be discerned from the incipits and descriptions): LIT5688MagicPrayer, LIT6484PPAynaTela

On the other hand, I found some prayer involving Michael, but none of these are to help against fever or diseases, as I have seen it in the incipits of some of the manuscript witnesses: LIT4519Prayer, LIT4302Prayer, LIT6487PPDam, LIT4346Prayer, LIT5876AsmatPrayer

I think, none of these fit to this prayer in BLorient11763. Do you agree, to create a new LIT ID for it?

**Comment by karljonaskarlsson** [comment]
I also find nothing, so from my perspective, I think you can create a new record

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia
