### ISSUE TITLE
Magical prayer against evil eye (ʿaynat)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2592]
@DenisNosnitsin1970 @karljonaskarlsson 

I found a prayer against ʿaynat in BLorient11763. Incipit given by Strelcyn is the following: በስመ፡ (...) ጸሎት፡ በእንተ፡ ሕማመ፡ ዓይነት፡ ሺምዳን፡ ተክለ፡ ሽርታን፡

I think ሺምዳን and ሽርታን are placeholders for evil words (as they are similar to šayṭān) or some magic names. I found ሺምዳን in EMIPms00498, but I believe it has no relevance for this text.

For the work records related to ʾaynat, there are many: LIT6497PPAynat, LIT4644MagicPr, LIT5875MagicPrayer, LIT4703MagicPr, LIT4626Prayer, LIT5690MagicPrayer, and probably even more. Is there a good reason to favor one of them more than the others and select it for BLorient11763? Otherwise, I suggest to leave it without mark up and without creating a new LIT ID, because information about it is not enough.

**Comment by karljonaskarlsson** [comment]
Regarding ሽርታን, I wonder if there might be a connection to Arabic سرطان = cancer. In any case, it does not change anything about the question about how to encode this text :)

I think your suggestion sounds good. As you were probably also planning, it might be good to give all the text that Strelcyn gives to increase the chance that it might be identified in the future.

**Comment by CarstenHoffmannMarburg** [comment]
What I quoted in the comment above is everything what we have from Strelcyn on this matter:

<img width="326" alt="Screenshot 2024_Shertan" src="https://github.com/user-attachments/assets/0859ed0b-9e0f-43f4-9d66-65761b813b56">

The given incipit will be part of the manuscript record and so it will be searchable in bm.

In case, the images of the manuscripts will be online again, future researchers on the magical prayers can increase the content in the record.

**Comment by CarstenHoffmannMarburg** [comment]
@nafisa-valieva and @sologebre reported, that this prayer might be indicated as "Prayer against ሺምዳን፡". (Cf. https://github.com/BetaMasaheft/Manuscripts/pull/2575#pullrequestreview-2275073056). I found this word also in a prayer in EMIPms00498. Shall I create an ID for these two texts despite the variants? Other attestations of Šumdān I do not have and I do not know this term as a name for a demon.

BLorient11763: ጸሎት፡ በእንተ፡ ሕማመ፡ ዓይነት፡ ሺምዳን፡ ተክለ፡ ሽርታን፡
EMIPms00498: ጸሎት፡ በእንተ፡ ዊርጥማት፡ ሺምደ፡ ሺምዳን፡ ሺምደ፡ ሐውልተ፡ ሰማዕት፡ ዘጊ፡ ዘጊ፡ ዘጊ፡ ዘ..

EMIPms00498 is also available as image:
<img width="188" alt="Screenshot 2024_EMIP_Shumdan" src="https://github.com/user-attachments/assets/2a4917f8-ef0c-4120-881d-f76dd2ef9d5d">


@eu-genia

**Comment by nafisa-valieva** [comment]
@karljonaskarlsson @CarstenHoffmannMarburg 
I do not know what the system is, I am too new. My comment is in the sense that "ʿaynat" must be here a technical word meaning "type". It makes sense that it is a Prayer against cancer (planted by Satan), no? Prayer against "type" is meaningless, unless proven that there is a  disease called  "ʿaynat".

**Comment by CarstenHoffmannMarburg** [comment]
I am not a specialist in Ethiopian magical prayers and the meaning of many terms and words is doubtful to me. The translation of ʿaynat as "type" is new to me, and apparently to Strelcyn in 1978, because he gave it exactly that title, i.e. "meaningless" according to your explanation:

<img width="322" alt="Screenshot 2024_Aynat" src="https://github.com/user-attachments/assets/5a94c758-871a-4b54-a1b8-4e04415b6b2b">

The same "meaningless" title is also in this work ID: LIT4626Prayer

According to my understanding so far, ʿaynat has the meaning "eye" or at least is derived from that meaning. Ṣalot baʾǝnta ḥǝmāma ʿāynat bāryā wa-legewon in this case would mean "prayer against the harm of the eye (of) Bāryā and Legewon" or similarly "ʿāynat Šimdān" can be explained as "eye (of) Šimdān" or "Šimdān-eye" (even if it is not a genitive construction). The idea is that the evil influence of demons is at work when someone is seen by the demon, i.e. by its eye. In this case, it would be useful to have a generic ID for every magical prayer containing "ʿaynat" for which nothing else is known or the information is too little to identify any existing work with it or to create a new one. However, if it means just "type", the opposite is useful.

**Comment by nafisa-valieva** [comment]
I am not a specialist either! Both explanations sounds possible! Thank you!

**Comment by DenisNosnitsin1970** [comment]
'Aynet is in itself means "evel eye". But the type ጸሎት በእንተ ዓይነት is only generic title, which is attached to different prayers only to indicate their function (to act agains "evel eye" of what ever type, which are many). A protectve text that follows is the instrument proper, stuffed with magic or protextive words of whatever type (of which many cataloguers quote only insufficient bits, thinking that ጸሎት በእንተ ዓይነት is enough). The terms mentioned above may be related to Zodiac (at least one, as ሸርጣን is the loan word for cancer, ሽብዳን may be from the same area?). I think it can be styled like: A prayer against the evel eye. Shimdan, the son of Shertan ...  Check: ቁርጥማት (illness). Generic record for these prayers could be useful.

**Comment by CarstenHoffmannMarburg** [comment]
I understand, that a LIT ID for ms_i3 in BLorient11763 is useful. I will create it and I will update the manuscript record in a new branch.

**Comment by eu-genia** [comment]
Yes)

 > the approach to magic texts should be the same as outlined for Qene 

>-We always must use the keyword (Magic) - this will make the already searchable if one wants to find all spells we know of
>-When part of the main text, a CAe ID must be used.
>--When we have no access to the text we can use `LIT6609ProtectPrayer `or, when we know the subtype, a generic ID for the >subtype (LIT5888AsmatPrayer, etc, )


>--When we have the text (so the text is identifiable) we should create a specific CAe ID.
>-When an additio, type `MagicText `with the q wherever possible is sufficient

>In addition, as a desideratum, a taxonomy should be developed and then additional keywords enabling filtered search assigned

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/2603#issuecomment-2324684772_
