### ISSUE TITLE
Visualizing line breaks

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2593]
Could the division of qene texts into lines be visualised? This is the main feature making a poem to qene, a dn the division is encoded in the most cases.

**Comment by CarstenHoffmannMarburg** [comment]
I do not understand the question. I think, the lines are visualized in work records as in case of newly developed LIT7038Qene:

 ```
<ab> 
                        <persName ref="PRS3934Ewostate">ኤዎስጣቴዎስ፡</persName> እንዘ፡ እልፍ፡ ውሉድ፡ ውስተ፡ ሕፅንከ፡ 
                        <l n="1">እስመ፡ ወርኃ፡ ተድላ፡ ኮኖሙ፡ ለአዕባነ፡ ፍኖት፡ አፈ።</l>
                        <l n="2">ተሣለቁ፡ እፎ፡ ጸጋከ፡ ትሩፈ።</l>
                        <l n="3">በፍጻሜ፡ ግፍዕከሰ፡ ከመ፡ ቃለ፡ ሙሴ፡ ጸሐፈ።</l>
                        <l n="4">ዘመን፡ ለከ፡ እመ፡ ኃለፈ።</l>
                        <l n="5">አሐዱ፡ ወልድከ፡ ያስተጋብእ፡ ጽንፈ።</l>
                        <l n="6">ወክልኤቱ፡ ይስድዱ፡ እልፈ።</l>
                    </ab>
```

Do you want us to do it always like this or do wish to have an improved visualization beyond that?

**Comment by DenisNosnitsin1970** [comment]
Qene is a well-formalized poetic text genre, and qenes frequently occur in manuscripts not as coherent regular text, but written verse after verse, clearly showing the rhyme. But if a qene is written as coherent text, the division into verses is clearly marked by a punctuation sign.  When I provide the text in the work record, I prefer to keep the division into verses, to support the definition of qene type. It is less difficult than it looks like (I started to mark in work records, what is the basis, the way I see it or alredy available in the ms). From the catalogue of Strelcyn, it is not clear if the poem already written line by line in the ms, or he preented it like this. But THis is what I also do. In any case, now the division is not visualised in work record (only in the ms), by whatever reason.

**Comment by karljonaskarlsson** [comment]
I think it's good to have the possibility to visualize it in the work record. As you say, Denis, it's good to keep a note on whether this division is our interpretation or actually attested in the manuscripts.

**Comment by eu-genia** [comment]
When line breaks are present in the text you should use `<lb/>`, then they are printed as vertical lines

**Comment by eu-genia** [comment]
@DenisNosnitsin1970 can you show me the example of where line division is properly visualized in ms descriptions? Record/encoding? I am trying to figure out what the expected contexts are, then I could add conditions also for `<l>` elements.

When vertical lines? When line breaks?

**Comment by eu-genia** [comment]
In general, for everyone, if you want to see something visualized you always MUST provide the corresponding encoding and a specific example of what you want to see, not a general wording.
at the moment we have
`<lb/>` (= line break) for printing vertical lines
`<lg>` and `<l>` (= stanza and line number) combination for line breaks (in certain contexts)

**Comment by DenisNosnitsin1970** [comment]
`<l n="1">ተሰብሐ፡ ሰማዕተ፡ ልዳ፡ በልሳነ፡ ሰይፍ፡ ጸላዒሁ፡ እስመ፡ ድኅረ፡ አጽገበ፡ ነደ፡ ፍቁሮ፡ እመብልዓ፡ ነገሥት፡ ሰብአ፡ አቅረበ፡ ሎቱ፡ ፫ተ፡ ጽዋዓ፤</l>  `
`<l n="2">መቃብርሂ፡ ነዳይ፡ ሐመዮ፡ እንዘ፡ ይቀውም፡ በአፍአ፤</l>`
`<l n="3">መዓዛ፡ ሥጋሁ፡ እምጣነ፡ መልዓ፤</l>`
`<l n="4">በአፅናፊሁ፡ አድባር፡ እመኒ፡ ግፉዓ፡</l>`
`<l n="5">ድኅረ፡ ፍት፡ ዓጽሞ፡ ነሥአ።</l>`
This is how I encode the qene 
[(https://betamasaheft.eu/works/LIT7035Tasabha/main)], 
is it correct? 
In the work record it currently appears as a continuous text.

**Comment by eu-genia** [comment]
can you show me the manuscript description where it works? (it should not, with this encoding, but I do not know the context, meaning the ancestor tags)

**Comment by eu-genia** [comment]
in the code the element `<l>` was not properly enabled (it was not shown in works but surely also not in manuscripts, it could not), now it should result in line breaks in all cases

I suggest that we use `<l>` to structure poetry (inside of `<lg>` for stanzas) and `<lb/>` for diplomatic editing to insert vertical lines indicating that a line break is present in the manuscript (whether prose or verse)

What do you think?

@DenisNosnitsin1970 @CarstenHoffmannMarburg @smaugustine @thea-m @karljonaskarlsson

**Comment by DenisNosnitsin1970** [comment]
Now it works, indeed. "I suggest that we use <l> to structure poetry (inside of <lg> for stanzas) and <lb/> for diplomatic editing to insert vertical lines indicating that a line break is present in the manuscript (whether prose or verse)" -  that's fine.
