### ISSUE TITLE
A monastery called Dabra ʾElgǝne?

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2595]
The manuscript Uppsala, O Etiop. 10 contains a donation note to a monastery (?) called Dabra ʾElgǝne (https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0176&pid=alvin-record:480189). It might be in Eritrea, as the manuscript comes from a Swedish missionary who was active there. I have not been able to find this monastery attested anywhere – it doesn't even have any Google hits. Does anyone know it? Can I create an INS record for it?

@DenisNosnitsin1970 @CarstenHoffmannMarburg

**Comment by CarstenHoffmannMarburg** [comment]
I see, that it is reasonable to create an ID, even if the location is not known. I do not know, whether a INS or a LOC is more reasonable.

I am not sure, whether your reading is without alternatives. I read ኤልጣኔ or ኤልጣአ. However, I did not find any of them im Bm or in Googlemaps.

**Comment by karljonaskarlsson** [comment]
The other readings are also possible (and ኤልግአ). Löfgren read ኤልግኔ, so if I have to go with one, that might be the best option. Is it preferable to encode various alternatives?

**Comment by CarstenHoffmannMarburg** [comment]
You can encode as n1, n2, n3, etc. However, it is problematic, if there are several signs doubtful. I do not know, which is preferable for n1.

**Comment by DenisNosnitsin1970** [comment]
ኤልግኔ seems to be more probable because (you have a grafic basis for ኤ in አ, which is a little different; the sign in question ግ has the 6th order marker made of two small half-rings), but the place is unknown to me and the name is odd (remainding of an Arabic name transcribed in Ethiopic). Yes, an ID would be necessary.

**Comment by CarstenHoffmannMarburg** [comment]
Possibly arab. al-ǧanna (= the paradise)? Probably a monastary in an Arabic speaking area?

**Comment by karljonaskarlsson** [comment]
@DenisNosnitsin1970 , in cases like this, do you know if the standard practice is to create a LOC or an INS?

**Comment by DenisNosnitsin1970** [comment]
I think in this case Dabra Elgane is clearly an institution (and potentially a book repository) and may be given an institution record. Nothing else is known about it (it is probably that it is an Ethiopic transcription of an Arabic name), but it does not matter. I am not sure there is a rule for this, such cases are not frequent. But I see now that I encoded ደብረ ስብራ  as LOC in Ms MY-004, whereas from the context it is very clear an monastery (a subscription says that a bishop let a text be translated at Dabra Sabra). I think now it was not correct to encode it as LOC.

**Comment by CarstenHoffmannMarburg** [comment]
There are also cases, where we have both. However, these are cases, for which much more details are known.

**Comment by karljonaskarlsson** [comment]
Thank you! Then it will be an INS for now. And if we learn more about the localisation of this INS, maybe a LOC can be created in the future.
