### ISSUE TITLE
Prayer for catching devils in BLorient11764

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2596]
@karljonaskarlsson @DenisNosnitsin1970 

I found a prayer in BLorient11764, which was entitled "Prayer for catching devils" by S. Strelcyn with the following incipit: 
በስመ፡ <gap reason="ellipsis"/>አላሁማ፡ ወያኑራ፡ ሐሽም፡ <gap reason="ellipsis"/> ዘነበቦሙ፡ ለአጋ<surplus>ጋ</surplus>ንንት፡ ሎፍሐም፡ ከማሁ፡ እስሮሙ፡ ለቡዳ፡ መሰርይ፡ ወሌጌዎን፡ ዕኩይ፡ ለእመ፡ አኀዞ፡ እደ፡ ሰብእ፡

The words አላሁማ፡ ወያኑራ፡ can also be found in LIT4620Prayer. Besides that, there are no more similarities showing up in the record, unless images or the manuscript witness (BAVet77) are not available and it is not possible to check the complete text. The same is true for LIT5126MagicPrayer with the witness IVEf114.

I would propose to create a new ID for this prayer.

**Comment by karljonaskarlsson** [comment]
Ok! I cannot find it either.

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
@nafisa-valieva

**Comment by nafisa-valieva** [comment]
Ok!

**Comment by eu-genia** [comment]
OK for me. In the case of magic prayers in many cases we have a situation similar to that of qene - I assume there is a lot of improvisation there, and many of the prayers may be unique.
Maybe at some point we should develop an additional taxonomy to enable filtered search for spells according to diseases/demons/other keywords... if ever we have someone particularly interested in these aspects)

**Comment by karljonaskarlsson** [comment]
> OK for me. In the case of magic prayers in many cases we have a situation similar to that of qene - I assume there is a lot of improvisation there, and many of the prayers may be unique. Maybe at some point we should develop an additional taxonomy to enable filtered search for spells according to diseases/demons/other keywords... if ever we have someone particularly interested in these aspects)

good idea!
