### ISSUE TITLE
Prayer against bāryā, chest pain (wǝgʿat), diseases, and charms in BLorient11764

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2597]
@karljonaskarlsson @DenisNosnitsin1970 

I found another prayer in BLorient11764. I did not find any correlation to other works or manuscript records: 

```
<msItem xml:id="ms_i5">
                            <title ref="LIT00000000000">Prayer against bāryā, chest pain (wǝgʿat), diseases, and charms</title>
                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ዕልመይከክን፡ ረቢ፡ ታኦስ፡ ባኦስ፡ <gap reason="ellipsis"/> ከማሁ፡ ዓፅርዕ፡ ወአዕትት፡ 
                                ሕማመ፡ ባርያ፡ ወውግዓት፡ ወደዌ፡ ወሥራይ፡ እምላዕለ፡ ነፍሱ፡ ወሥጋሁ፡ ለገብረ፡ እግዚአብሔር፡ </incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

**Comment by karljonaskarlsson** [comment]
I cannot find it either, so I think it's ok to create a new record (which was your suggestion, right?)

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
@nafisa-valieva

**Comment by eu-genia** [comment]
> So the approach to magic texts should be the same as outlined for Qene 

>-We always must use the keyword (Magic) - this will make the already searchable if one wants to find all spells we know of
>-When part of the main text, a CAe ID must be used.
>--When we have no access to the text we can use `LIT6609ProtectPrayer `or, when we know the subtype, a generic ID for the >subtype (LIT5888AsmatPrayer, etc, )


>--When we have the text (so the text is identifiable) we should create a specific CAe ID.
>-When an additio, type `MagicText `with the q wherever possible is sufficient

>In addition, as a desideratum, a taxonomy should be developed and then additional keywords enabling filtered search assigned

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/2603#issuecomment-2324684772_
