### ISSUE TITLE
Prayer against colic (qʷǝrṣat) in BLorient11764

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2598]
@DenisNosnitsin1970 , @karljonaskarlsson 

I found a prayer against colic in BLorient11764. There are four work records for prayers against colic (LIT4604Salot, LIT4622Prayer, LIT4623Prayer, LIT4595Salot; plus LIT6478PPMasaraAganent, which mentions colic along with many other calamities), each of which is very similar and has no further indication beyond a small incipit. Each has ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርጸት፡ at the beginning (unlike BLorient11764, where we only find ጸሎተ፡ ቍረፀት፡). I propose to leave this prayer unmarked, as the information is too sparse.

BLorient11764:
```
<msItem xml:id="ms_i6">
                            <title>Prayer against colic (qʷǝrṣat)</title>
                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ጸሎተ፡ ቍረፀት፡ ኄር፡ ኪሳ፡ ኪሳ፡</incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

**Comment by CarstenHoffmannMarburg** [comment]
There is a similar problem with another text in BLorient 3716b in ms_i6. Two out of the four work records listed above (LIT4622Prayer, LIT4623Prayer) do not have correspondig text apart from the title words ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርፀት፡. For the other two (LIT4604Salot, LIT4595Salot) it is not discernable, because no text was encoded and the manuscripts do not have available images. We probably also need a new LIT ID for this prayer.

```
<msItem xml:id="ms_i6">
                            <title ref="LIT0000000">Prayer against colic</title>
                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርፀት፡ እንዘ፡ ይትዋነይ፡ በውስተ፡ ማኅፀን፡ እንዘ፡ ይበጽብጽ፡ ከርሠ፡
                                ወይፈቅል፡ ቍልፈተ፡ ወይደጕጽ፡ ገበዋተ፡ ዝንቱ፡ ህማመ፡ ቍርፀት፡</incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

**Comment by karljonaskarlsson** [comment]
So you suggest no record for the first one, but a new ID for the second, where more text is provided? It sounds good to me!

**Comment by CarstenHoffmannMarburg** [comment]
> So you suggest no record for the first one, but a new ID for the second, where more text is provided? It sounds good to me!

I suggested not to create record for the first one. For the second one, I was not decided. If you want me to create a new record for ms_i6, I will do that.

**Comment by karljonaskarlsson** [comment]
I could not find it in the existing files, so feel free

**Comment by DenisNosnitsin1970** [comment]
I would suggest to create a new ID, and to interlink it with one or more others. This is the situation which is common in older catalogues. If we cannot  find it, we just create a new ID (in the future, someone else may come who will deal with the issue, or more mss will be accessible online). Another way is to create a general ID to bundle mss that you think may containe the same work, but it requires much more time investment.

**Comment by CarstenHoffmannMarburg** [comment]
> I would suggest to create a new ID, and to interlink it with one or more others. This is the situation which is common in older catalogues. If we cannot find it, we just create a new ID (in the future, someone else may come who will deal with the issue, or more mss will be accessible online). Another way is to create a general ID to bundle mss that you think may containe the same work, but it requires much more time investment.

I understand, that you suggest to create new IDs for both prayers. So I will do that.
