### ISSUE TITLE
ʾAsmāt prayer in BLorient3716b and various manuscripts

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2599]
@karljonaskarlsson @DenisNosnitsin1970 

I found a magical prayer in BLorient3716b and fairly the same incipit in MusKulB26282, TFR002 and EMIPms00520 (transkribus). I propose to create a new LIT record for this text and replace the General LIT ID for ʾAsmāt-prayers in MusKulB26282.

**BLorient3716b** 

```
<msItem xml:id="ms_i2">
                            <title ref="LIT0000000">Prayer against bāryā, Satan, and devils</title>
                            <incipit xml:lang="gez">ድርሱ፡ በስመ፡ አልፋ፡ ፃዕ፡ ፃዕ፡ ፃዕ፡ ወወጺአከ፡ ኢትግባእ፡ ይቤለከ፡ እግዚአብሔር፡ <gap reason="ellipsis"/> አንተ፡ ቡዳ፡ 
                                ወአንተ፡ ባርያ፡ ወአንተ፡ ሰይጣን፡ ወአንተ፡ ጋኔን፡ ዘትትሜሰሉ፡ በብዙኅ፡ ጾታ፡ አህያ፡ ሺራህያ፡ ይመራኤል፡ ሀያል፡</incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

**MusKulB26282**
```
<msItem xml:id="ms_i2">
                            <title type="complete" ref="LIT5888AsmatPrayer">Protective prayer with ʾasmāt</title>
                            <textLang mainLang="gez"/>
                            <incipit xml:lang="gez"><hi rend="rubric">በስመ፡ አልፋ፡ አልፋ፡ አልፋ፡ ፃ</hi>ዕ፡ ፃዕ፡ ወወጺአከ፡ ኢትግባ<gap reason="lost" unit="chars" quantity="1"/>፡ ይቤለከ፡ 
                            እግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ ወዝክረ፡ ስምከ፡ ይደምሰስ፡</incipit>
                        </msItem>
```

**TFR002**
```
                     <msItem xml:id="ms_i1">
                        <title type="complete"/>
                        <textLang mainLang="gez"/>
                        <incipit xml:lang="gez">
                        <hi rend="rubric">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ<supplied reason="omitted" resp="DR">፡</supplied> ቅዱስ<supplied reason="omitted" resp="DR">፡</supplied>
                        ፩አምላክ፡ ጸ</hi>ሎት፡ በእንተ፡ ዓይነ፡ ባርያ፡ በስመ፡ አልፋ፡ ፃእ፡ ፃእ፡ ፃእ፡ ወፂአከ፡ ኢትግባዕ፡ ይቤለከ፡ እ<hi rend="ligature">ግዚ</hi>አብሔር፡ ወዝክረ፡ ስምከ፡ ይደምስስ፡ ለአለመ፡ አለም፡ ዓሜን፡ ያቁ፡ ያቁ፡ ያቁ፡ አንተ፡ ቡዳ፡
                        ወአንተ፡ ሰይጣን፡ አንተ፡ ባርያ፡ ወአንተ፡ ጋኔን</incipit>
                        <explicit xml:lang="gez">ይለክ፡ በግርማ፡ ኦንጉሠ፡ ነገሥት፡ ፌማ፡ ኢይርአዩ<supplied reason="omitted" resp="DR">፡</supplied> ገጹ፡ ወኢይልክፉ፡ ሥጋሁ፡ ለገብረ፡ እ<hi rend="ligature">ግዚ</hi>አብሔር፡
                           <persName ref="PRS12495GabraS" role="owner">
                           <hi rend="rubric">ገብረ፡ ሥላሴ፡</hi>
                        </persName>
                     </explicit>
                     </msItem>
```

**EMIPms00520 (transkribus)**

<lb facs="#facs_3_line_1666694660168_11" n="1" break="no"/>በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱ<lb facs="#facs_3_r1l5" n="2" break="no"/>ስ፡ ፩አምላክ፡ ጸሎት፡ በእንተ፡ ሕማመ፡ 
				<lb facs="#facs_3_r1l6" n="3"/>ባርያ፡ ወሌጌወን፡ ዛር፡ ወዓይነ፡ ጽላ፡ ወጽ<lb facs="#facs_3_r1l7" n="4" break="no"/>ለወጊ፡ ወሸተለይ፡ በሰሙ፡ ለአብ፡ ወስሙ፡
				<lb facs="#facs_3_line_1666694711564_19" n="5"/>ለወልድ፡ በስሙ፡ ለመንፈስ፡ ቅዱስ፡ ታ[ ]<lb facs="#facs_3_line_1666694723142_24" n="6" break="no"/>ዕ፡ ያዝያ፡ ወለምⷋስ፡፡አⷆኅር፡ መ<lb facs="#facs_3_r1l8" n="7" break="no"/>ሙ፡ ለሐራሹን፡ ሐራሹን፡ ሐራሻን፡ ሖሬ፡ ፌ<lb facs="#facs_3_r1l9" n="8" break="no"/>ክር፡ ወጠጅን፡ ዘኃጅን፡ ዋኀ፡ ተ[ ]ዕፍልማ፡ 
				<lb facs="#facs_3_r1l10" n="9"/>ኤል፡ በስመ፡ ሰደር፡ ወአእዳኖዳናት፡ አዴራ፡ 
				<lb facs="#facs_3_r1l11" n="10"/>ሮዳስ፡ አብእቲር፡ ሕፍናና፡ ዋቅ፡ ሕፍርር፡ 
				<lb facs="#facs_3_r1l12" n="11"/>ር ዋኤል፡ በኃይለ፡ ዝንቱ፡ አስማቲከ፡ ሰሁ<lb facs="#facs_3_r1l13" n="12" break="no"/>ል፡ እሳተ፡ መለኮት፡ ምናነ፡ ያልሕቅ፡ መልዐ<lb facs="#facs_3_r1l14" n="13" break="no"/>ኩ፡ አንህሊ፡ ተሲአከ፡ ያአጥ፡ ወያጥን፡ እ<lb facs="#facs_3_r1l15" n="14" break="no"/>ልሐሱስ፡ በኃይለ፡ ዝንቱ፡ አስማተ፡ ቃል፡ ኢ<lb facs="#facs_3_r1l16" n="15" break="no"/>የሱስ፡ ክርስቶስ፡ ወልደ፡ እግዚአብሔር፡ ሕ<lb facs="#facs_3_line_1666694735511_39" n="16" break="no"/>ያው፡ ወልደ፡ ማርያም፡ ሥግው፡ በስይፈ፡
				<lb facs="#facs_3_line_1666694747262_44" n="17"/>ሚካኤል፡ ወገብርኤል፡ ይትወንዝ፡ዊ[ ]<lb facs="#facs_3_r1l21" n="18" break="no"/>ጸዕ፡ መንፈስ፡ ናኩስ፡ ወዘ፡ አኃዘኒ፡ ቡዳ፡ ወባ<lb facs="#facs_3_r1l22" n="19" break="no"/>ርያ፡ ወወሌጌወን፡ ዛር፡ ወቁመት፡ ዓይነ፡ ወርቅ፡ 
				<lb facs="#facs_3_r1l23" n="20"/>ወሸተላይ፡ ዛር፡ ወወሬዛ፡ ይደምሰስ፡ ውጻ<lb facs="#facs_3_r1l24" n="21" break="no"/>ዕ፡ ኃበ፡ አኃዝኩከ፡ በዝንቱ፡ ጸሎት፡ እም<lb facs="#facs_3_r1l25" n="22" break="no"/>እለ፡ ዓመተ፡ እግዚ፡ አብሔር፡ ዘምዘመ፡ 
				<lb facs="#facs_3_r1l26" n="23"/>**አልፋ፡ አልፋ፡ አልፋ፡ ጸዕ ጸዕ፡ ጸዕ፡ ሠጺኑ**<lb facs="#facs_3_r1l27" n="24" break="no"/>**ከ፡ ኢትግባእ፡** ወዝክረ፡ ስምከ፡ ይደም<lb facs="#facs_3_r1l28" n="25" break="no"/>ሰስ፡ ለዓለመ፡ አለም፡ የቂ፡ የቂ፡ የቂ፡ አንተ፡ 
				<lb facs="#facs_3_r1l29" n="26"/>ቡዳ፡ ወአንተ፡ ሰይጣን፡ ወዓንተ፡ ዓይነ፡ 
				<lb facs="#facs_3_r1l30" n="27"/>ጽላ፡ ወአንተ፡ ሸተላይ፡ ዘትትመስል፡ በብዙ<lb facs="#facs_3_r1l31" n="28" break="no"/>ህ፡ ጸታ፡ አህያ፡ ሸራህያ፡ አልሸዳይ፡ ይምራኤ<lb facs="#facs_3_r1l32" n="29" break="no"/>ል፡ አቢይ፡ ኃይለ፡ እግዚአብሔር፡ እደናይ፡ ወ<lb facs="#facs_3_r1l33" n="30" break="no"/>ልደ፡ እብ፡ ዋኅድ፡ በኁፍሐም፡ ልዮሰ፡ ንገር<lb facs="#facs_3_r1l34" n="31" break="no"/>ኩክሙ፡ ኢዩኤል፡ ኢያኦል፡ እግዚእ፡ እግ<lb facs="#facs_3_r1l35" n="32" break="no"/>ዚአብሔር፡ ሩሐል፡ ሕምሳትምኤል፡ ጰልጰ<lb facs="#facs_3_r1l36" n="33" break="no"/>ልሚ፡ ያሸኩች፡ ጋደ፡ እምደ፡ ብርሃን፡ ልብ<lb facs="#facs_3_r1l37" n="34" break="no"/>ሠ፡ ብርሕዊን፡ ዘይበርቅ፡ ቅድመ፡ ገጹእጸ<lb facs="#facs_3_r1l38" n="35" break="no"/>ለኢ፡ ወበኃይለ፡ ጸላኢ። ቡዳ፡ ወዓይነጽ፡
				<lb facs="#facs_3_r1l39" n="36"/>ላ፡ ወጽአ፡ ወጊ፡ ወማእሠረ፡ አጋንንት፡ 
				<lb facs="#facs_3_r1l40" n="37"/>ይደምሰስ፡ ውጻዕ፡ ኀበአኃኩከ፡ በዝን<lb facs="#facs_3_r1l41" n="38" break="no"/>ቱ፡ ጸሎት፡ እምላአለ፡ ዓመተ፡ እግዚ<lb facs="#facs_3_r1l44" n="39" break="no"/>አብሔር፡ ዘምዘመ። 

.

N.B. The folder for the Basel manuscripts in Oxygen is difficult to find. It should be sorted by the name of the city, e.g. BaselMuseumKulturen instead of MuseumKulturenBasel. It is also a mystery to me what the acronym TFR stands for. I understand that it is a private collection, but it is not clear whose collection it is and where it is located.

**Comment by karljonaskarlsson** [comment]
In the xml file INS0904TF, there is some information about TFR.

I'm not sure about the textual identification. Sure, there are some recurring phrases, but are they enough to define there four texts as the same work? Maybe. I don't know the genre of such texts well enough to be able to say how significant the matches are.

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia

**Comment by CarstenHoffmannMarburg** [comment]
@nafisa-valieva

**Comment by nafisa-valieva** [comment]
I am not a specialist either. I am not sure whether some recurring phrases allow us to define these texts as the same work. In hagiography recurring phrases do not mean that it is the same work.

**Comment by eu-genia** [comment]
>             So the approach to magic texts should be the same as outlined for Qene 

>-We always must use the keyword (Magic) - this will make the already searchable if one wants to find all spells we know of
>-When part of the main text, a CAe ID must be used.
>--When we have no access to the text we can use `LIT6609ProtectPrayer `or, when we know the subtype, a generic ID for the >subtype (LIT5888AsmatPrayer, etc, )


>--When we have the text (so the text is identifiable) we should create a specific CAe ID.
>-When an additio, type `MagicText `with the q wherever possible is sufficient

>In addition, as a desideratum, a taxonomy should be developed and then additional keywords enabling filtered search assigned

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Documentation/issues/2603#issuecomment-2324684772_

**Comment by CarstenHoffmannMarburg** [comment]
OK. If you are sceptic about a new ID, I opt for using LIT5888AsmatPrayer to mark up this item.
