### ISSUE TITLE
Doublet for Ḥaṣura masqal-prayers

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2600]
@DenisNosnitsin1970 @karljonaskarlsson 

I found a Magical prayer in BLorient3716b entitled "Prayer by the virtue of the ḥaṣura masqal". I wonder, if I can use **LIT5696MagicPrayer** as this is a generic record for prayers related to the Holy Cross. Beyond the title "Ḥaṣura masqal", I did not find similarities in other records.

```
<msItem xml:id="ms_i3">
                            <title ref="LIT5696MagicPrayer">Prayer by the virtue of the ḥaṣura masqal</title>
                            <incipit xml:lang="gez"><gap reason="ellipsis"/>አአምን፡ በአብ፡ አአምን፡ በወልድ፡ አአምን፡ በመንፈስ፡ ቅዱስ፡ ከልለኒ፡ በወልታ፡ ርድአኒ፡ ወህፅረኒ፡ 
                                በሐፁረ፡ መስቀልከ፡ ኦአምላኪያ፡ ወመድኀንየ፡ መሐረኒ፡ ወተሠሃለኒ፡ ሊተ፡ ለገብረ፡ እግዚአብሔር፡</incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

However, I found a record **LIT1580hasura** with EAe transcription and with no manuscripts related to it. I think this latter one can be deleted as it is doublet of the aforementioned.

**Comment by DenisNosnitsin1970** [comment]
Yes, this is a common situation, though I would say "related to the Holy Cross" is too broad. There is a number of prayers called like this, some are for sure textually interlinked (there may be also different transmission branches in codices and scrolls). Where we cannot be exact about the recension and other witnesse, we use the general record.  The older record may be indeed a doublet.
