### ISSUE TITLE
Branch  Tana6Kebran6Qenes

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2602]
Updates and new records from the branch Tana6Kebran6Qenes did not go
 through after the merge.

**Comment by eu-genia** [comment]
Please link to the pull request in question https://github.com/BetaMasaheft/Manuscripts/pulls?q=is%3Apr+is%3Aclosed

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Manuscripts/pull/2519

**Comment by eu-genia** [comment]
updated
