### ISSUE TITLE
Salām to Fānuʾel in BLorient5426

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2605]
@DenisNosnitsin1970 @karljonaskarlsson 

I found a text, which is entitled "Salām to Phanuel" by S. Strelcyn. I wonder, if this could be LIT6492PPFanuel, which is described to be "A protective prayer consisting of an introduction stating the prayer's purpose, which may vary, and the first stanza of the [Malkǝʾa Fānuʾel](https://betamasaheft.eu/LIT6491MalkeaFanuel)." How can I check, whether this is in fact the first stanza of LIT6491MalkeaFanuel? In that case, it would be appropriate to change the title to "Salām to Fānuʾel".

**Comment by CarstenHoffmannMarburg** [comment]
The title "Salām to Fānuʾel" is also used to indicate a prayer in VBAx231sup8. Unfortunately, there are no IDs and no images.

**Comment by CarstenHoffmannMarburg** [comment]
There is also a prayer in EMIP02075, that is marked up with the (generic) ID LIT5888AsmatPrayer. on f. 21v, there is also a text beginning with Salām laka Fānuʾel. However, this text is very much different from the incipit given by Strelcyn for BLorient5426.

**EMIP02075**
```
                  <msItem xml:id="ms_i4.5">
                     <locus from="21r" to="22v" facs="023"/>
                     <title type="complete" ref="LIT5888AsmatPrayer"> Asmat prayer of the Archangel Fanuel</title>
                     <textLang mainLang="gez">Gǝ‘ǝz</textLang>
                  </msItem>
```
**EMIP02075, f. 21v**

<img width="315" alt="Screenshot 2024_Salam-laka-Fanuel" src="https://github.com/user-attachments/assets/c0a152b9-81eb-4dd1-ad74-964dd8f0518d">

**Comment by CarstenHoffmannMarburg** [comment]
The same text as in BLorient5426 can also be found in ESagm010 in a7:

```
 <item xml:id="a7">
                           <desc type="GuestText" corresp="LIT2765RepCh49">
                             Salutation for <persName ref="PRS7840Phanuel">Phanuel</persName> (salām la-Fānuʾel).<q xml:lang="gez">
                                 ሰላ፡ ለከ፡ ሰዳደ፡ አጋንንት፡ ፋኑኤል፡ ለእግዚአብሔር፡
                                 እምጽርሑ፡ ከመ፡ ኤይስክዩ፡ ሰብአ፡ እለ፡ ይኔሁ፡ ለጌጋይ፡ ዘዘኢአሁ።...</q>
                               Written in black and red ink, in the same <ref target="#h4">hand</ref> as <ref target="#a3">Additio 3</ref>. Cp.
                                 <ref type="work" corresp="LIT2765RepCh49"/>. The abbreviation ሰላ፡
                              for ሰላም፡ is used.</desc>
                        </item>
```

**Comment by CarstenHoffmannMarburg** [comment]
I think, I will use LIT2765RepCh49 for BLorient5426. I think, LIT6492PPFanuel is something different.

**Comment by DenisNosnitsin1970** [comment]
For LIT6491MalkeaFanuel, you can check the incipit in the record (I wonder if it the same hymn as the one printed in Malke'a gubae). LIT2765RepCh49 has been used in BNFabb186, the ms is online (which is different from the one in the edition Malkea gubae).
[Melkea Gubae - Sebatu Kidanat qedase maryam1.PDF](https://github.com/user-attachments/files/16467823/Melkea.Gubae.-.Sebatu.Kidanat.qedase.maryam1.PDF)

**Comment by karljonaskarlsson** [comment]
If you want to find a manuscript with Malkǝʾa Fānuʾel, maybe asking Augustine would be the easiest way, or consulting one of the printed Malkǝʾa gubāʾe in the library
