### ISSUE TITLE
Clavis Numbers Assigned to Multiple Works

### ISSUE THREAD

**Issue by smaugustine** [BetaMasaheft/Documentation#2606]
I have noticed that the following Clavis numbers — which ought to be unique — have been assigned to multiple work records: 

- [x] 4302
- [x] 4303
- [x] 4513
- [x] 4622
- [x] 4661
- [x] 5086
- [x] 5439
- [x] 5631

These should be appropriately reassigned so that the Clavis numbers remain unique.

**Comment by eu-genia** [comment]
Thank you! Fixed except for 5086 - I can only see one 5086 - is the number correct?

**Comment by smaugustine** [comment]
https://betamasaheft.eu/newSearch.html?searchType=clavis&query=5086#results

`LIT5086TUsixLal` and `LIT5086MagicPrayer`

**Comment by eu-genia** [comment]
Thank you, now I see, the name of the file with the ID LIT5086TUsixLal was LIT5085TUsixLal.xml, so could not see it. Renamed.
