### ISSUE TITLE
SS Marinas

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2608]
Currently the record https://betamasaheft.eu/persons/PRS6741Marina/main identifies the St Marina with Marina/Margaret of Antioch, https://en.wikipedia.org/wiki/Margaret_the_Virgin, and lists her as the subject of the martyrdom in GS (https://betamasaheft.eu/LIT6433MartyrMarina) and of the commemoration in Synaxarion (for 23 Hamle).

The record mentions that she should not be confused with another Marina commemorated on 8 Tahsas, this latter with no record of her own. From the text of the Synaxarion for 8 Tahsas it seems that the Marina of 8 Tahsas is "Anba Marina" = https://en.wikipedia.org/wiki/Marina_the_Monk , daughter of Eugenius, who died on that date, but the actual commemoration of Marina the Monk seems to be inserted for 15 Nahase as far as I can see. 

Most importantly, to me it seems that the text edited by Esteves Pereira in BHO 8 (=`LIT6433MartyrMarina`) deals with Marina the Monk (of 15 Nahase).

If no objections arise, I would use `PRS6740Marina `for Marina the Monk and change the link from `LIT6433MartyrMarina `to `PRS6740Marina`.

I am not sure whether `LIT6538Eugenius `is a separate text or if it is actually the same one as `LIT6433MartyrMarina `(Marina the Monk daughter of Eugenius)

@MarcinKrawczuk @thea-m @abausi

**Comment by eu-genia** [comment]
So we would have 
PRS6740Marina = Marina the Monk daughter of Eugenius https://en.wikipedia.org/wiki/Marina_the_Monk = 15 Nahase (edited by Pereira from Synaxary) + 8 Tahsas (death of Eugenius)
PRS6741Marina = Margaret of Antioch daughter of "Decius" https://en.wikipedia.org/wiki/Margaret_the_Virgin = 23 Hamle

I would appreciate help to avoid errors in confirming that the text in GS in `BNFabb179 `(ff. 180ra-187vb, 23 Hamle, suggesting the commemoration for Marina of Antioch) is the same as in `EMML7602 `(ff. 114ra-117vc, 8 Tahsas, suggesting Marina the Monk). I am also not sure about the texts in `EMML6965 `(ff. 160va-165rb, 8 Tāḫśāś) and `Tanasee121 `(ff. 164ra-168rb, 8 Tāḫśāś), currently pointing to a different work record.

Thank you so much!

(@DenisNosnitsin1970 maybe you too could have a look, thank you!)

**Comment by MarcinKrawczuk** [comment]
I think the situations looks like this:

LIT6538Eugenius is about PRS6740Marina
EMML 6965
Tanasee 121
EMML 7602 (mss record needs to be corrected)

LIT6433MartyrMarina is about PRS6741Marina
BnF Abb. 179

Both publications by Pereira contain the entry from the Senkessar (BnF Eth 128) so they do not concern us here.
