### ISSUE TITLE
Creating an Authority file for Gubāʿe Qānā

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2614]
As suggested by Jonas in https://github.com/BetaMasaheft/Manuscripts/pull/2511.

<img width="449" alt="Screenshot 2024_Gubae Qana" src="https://github.com/user-attachments/assets/fe82a0cf-eaa2-4764-b053-229f69a075a5">

@DenisNosnitsin1970 @eu-genia

**Comment by eu-genia** [comment]
Please keep one issue for Qene types https://github.com/BetaMasaheft/Documentation/issues/2504
