### ISSUE TITLE
Abb 184, new text records

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2616]
In Abbadie 184, there are two minor texts which I cannot find in the Bm. One is what Conti Rossini calls መጽሔተ፡ ብርሃን d'Abreham. 
Another one is ጸሎተ፡ ፍቅር፡ እንይርይር፡ ወጸሎተ፡ ፍቅር፡ አቅመጥመጥ፡
I propose to create IDs for these items.

**Comment by eu-genia** [comment]
OK for me.
(do not forget that also @karljonaskarlsson and beginning with Sunday @nafisa-valieva belong to the team and can be tagged in issues and pull requests)

**Comment by CarstenHoffmannMarburg** [comment]
I am OK with that, as well.

https://github.com/BetaMasaheft/Works/pull/1174#event-14080845257
