### ISSUE TITLE
Magic Prayer against the evil eye (ዓይነ፡ ጽላ፡) in BLorient11602

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2617]
@DenisNosnitsin1970 @eu-genia @karljonaskarlsson @nafisa-valieva 

I found a prayer against the evil eye (ዓይነ፡ ጽላ፡) in BLorient11602: በስመ፡ <gap reason="illegible"/> በዝ፡ ጠልሰም፡ ወበዝ፡ ክታብ፡  አድኅ<supplied reason="undefined" resp="PRS8999Strelcyn">ነ</supplied>ኒ፡ እምሕማመ፡ **ዓይነ፡ ጽላ፡** አድኅኖ፡ ለገብረ፡ እግዚአብሔር፡ ኪዳነ፡ ማርያም፡

There are a number of records that contain this term, but in each of those, it is combined with names of demons and phrases different from what is quoted above.

For comparison cf. LIT4568MagicPr ጸሎት፡ በእንተ፡ **ዓይነ፡ ጽላ፡** ወዓይነ፡ ባርያ፡ ወዓይነ፡ አበሾን፡

LIT4565MagicPr ጸሎት፡ በእንተ፡ **ዓይነ፡ ጽላ፡** ወዓይነ፡ ባርያ፡ አጋንንት፡ በስመ፡ እግዚአብሔር፡ ሥሉስ፡ ፈጣሬ፡

LIT4567MagicPr ጸሎት፡ በእንተ፡ **ዓይነ፡ ጽላ፡** ወዓይነ፡ ዛር፡ ወዓይነ፡ አጋንንት፡

LIT4569MagicPr ጸሎት፡ በእንተ፡ **ዓይነ፡ ጽላ፡** ወዓይነ፡ ወርቅ፡ ወተይሸ፡ ወቍራኛ፡ ወዓይነ፡ አጋንንት፡ እኩያን፡

LIT4566MagicPr  ጸሎት፡ በእንተ፡ ዓይነ፡ ባርያ፡ **ወዓይነ፡ ጽላ፡** መርበተ፡ ስሎሞን፡

LIT6829PPAyna ወመንፈስ፡ ቅዱስ፡ ፩ አምላክ፡ ጸሎት፡ በእንተ፡ **ዓይይነ፡ ጽላ፨** ወነገርጋር፨ ወባርያ፡ ወሌጌዎን፨

And also some texts in manuscripts, that do not have a LIT ID, yet.

EMIPms00535	ቡደ፡ ወቁመኛ፡ አልእ፡ ወመጋኛ፡ **ዓይነ፡ ጽላ፡** ወዓይነ፡ ርሶ፡ ወዓይነ፡ ወርቅ፡ እጀ፡

EMIPms00499 ለአመትከ፡ አስላኩ፡ ወለተ፡ ሃና፡ ጸሎተ፡ በእንተ፡ **ዓይነ፡ ጽላ፡** ዘይሰብ፡ ልበ፡ ሰብእ፡ ወያጸም፡ ዓይንተ፡ ወየሐቂ፡ 

EMIPms00488 አስማቲከ፡ አድኅና፡ ወፈውሳ፡ **እምዓይነ፡ ጽላ፡** ፍልት፡ ወጸልመት፡ መዘኛ፡ ወጉሥሞት፡

EMIPms00501 ...

ESssb005 ...

EMIP00616 ...

ESam019 ...

Following the recent discussion about marking up Magic prayer (i.e. https://github.com/BetaMasaheft/Documentation/issues/2592), I will create a new LIT ID for BLorient11602 and mark each of the similar work records in relations.

NB. It may be useful to create a "Magic" label. In this case, someone who is entrusted with a sensitive taxonomy of magic prayers (and images) in the future will be able to collect data more quickly.

**Comment by nafisa-valieva** [comment]
Ok for me!

**Comment by eu-genia** [comment]
As I believe we have agreed, it may be useful to first create a clavis repertory for the magic prayers identified by Strelcyn in his monograph and then continue with occasionally creating records from manuscripts, as he has already conducted the task of comparing and identifying. 
If you go from manuscripts still check what Strelcyn writes in his book as he surely used all those manuscripts in his study.
