### ISSUE TITLE
Magic Prayer by the virtue of the names of God (አስማቲሁ፡ ለእግዚአብሔር፡) in BLorient11602

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2618]
@eu-genia @DenisNosnitsin1970 @nafisa-valieva @karljonaskarlsson 

I found a prayer, that was indicated as "በስመ፡<gap reason="ellipsis"/> ዝውእቱ፡ **አስማቲሁ፡ ለእግዚአብሔር፡** ዘየአምር፡ አልኤና፡ እግዚአብሔር፡ ኵሎ፡ አሚረ፡ 
 ሕልው፡ እግዚአብሔር፡ ዘይጼሉ፡ ሀልዮሙ፡ ወመስተሣህል፡ ልዑል፡ ኀያል፡ ባዕል፡ ኄር፡ ክቡር፡ ወመንክር፡ ማዕምር፡ ወመምህር፡" in BLorient11602.

I did not find any LIT ID, that contains a prayer with the many different names, attributes or epiteths of God, but rather a number of four manuscripts, that have these two words and a similar focus. However, the given incipits are very different in each case:

EMIP00611  በስመ፡ አብ፡ ድርሳን፡ ዘቅዱስ፡ ሚካኤል፡ ሊቀ፡ መላእክት፡ **አስማቲሁ፡ ለእግዚአብሔር፡** እለ፡ ተጽሕፈ፡ በየማናዊ፡ ክንፉ፡ ለቅዱስ፡ ሚካኤል፡ ሊቀ፡

EMIPms00471 ባርያ፡ ወሌጌዎን፡ ልሳነ፡ ሰብእ። ደም፡ ወምጋኛ፡ ዘውእቱ፡ **አስማቲሁ፡ ለእግዚአብሔር።** ኢየሱስ፡ ክርስቶስ፡ ያሸመክቤት፡ ያሸኪታ፡ ደምናሁ፡ 

ESamq019  እሉ፡ ክቡራን፡ **አስማቲሁ፡ ለእግዚአብሔር፡** ዘተረክቡ፡ በእደ፡ ቅዱስ፡ ሚካኤል፡

BMLacq810  ለገብርከ፡ ዘወልደ፡ ማርያያም፡ ተማኅፀንኩ፡ ላዕለ፡ ኵሉ፡ **አስማቲሁ፡ ለእግዚአብሔር፡** ከመ፡ ኢይሙት፡ በኃጢአትየ፡ አን፡ ገብርከ፡ እገለ፡

I want to create a new ID for the text in BLorient11602 leaving the task of merging them with other similar works to potential general IDs or marking them with additional taxonomy to future encoders (as envisaged here: https://github.com/BetaMasaheft/Documentation/issues/2596).

**Comment by karljonaskarlsson** [comment]
The text in BLorient11602 seems very different from the others you mention, so I think it's ok to create a new record for it

**Comment by DenisNosnitsin1970** [comment]
Please note that whenever the string of asmat is somehow associated with Michael, there is a chance that this is a passage extracted from Dersana Mikael. There are some asmat passages included in it (probably  in more recent witnesses). These passages are located in the description of ESmy019, you can have a look. A assume that they may be also in the contemporary church edition of "Dersana Mikael".

**Comment by CarstenHoffmannMarburg** [comment]
> Please note that whenever the string of asmat is somehow associated with Michael, there is a chance that this is a passage extracted from Dersana Mikael. There are some asmat passages included in it (probably in more recent witnesses). These passages are located in the description of ESmy019, you can have a look. A assume that they may be also in the contemporary church edition of "Dersana Mikael".

As far as I can see from the incipit, there is no reference to Michael in the text of BLorient11602. This is the case only in EMIP00611.
