### ISSUE TITLE
Prayer against the evil eye and Manso in BLorient11602

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2619]
@eu-genia @DenisNosnitsin1970 @karljonaskarlsson @nafisa-valieva 

I found a Magic prayer in BLorient11602 that reads as follows: በስመ፡<gap reason="ellipsis"/> ጸሎት፡ በእንተ፡ ሕማመ፡ **ዓይነት፡ ወመንሶ፡** ወማዕሠረ፡ አጋንንት፡ ኢትቅረቡ፡ በሌሊት፡ ዕቀበኒ፡ **መስቀል፡ መድኃኒተ፡ ኵሉ፡ ዓለም።** መስቀል፡ መግረሬ፡ ፀር፡ መስቀል፡ መዋዔ፡ ፀር፡

I found the word መንሶ as ወርቅ፡ መንሶ፡ in the explicit of a magic prayer in LIT6852Prayer: (...) ወቡዳ፡ ተያያዥ፡ ወእጀ፡ ሰብአ፡ ጽላ፡ ወጊ፡ ወፍጌን፡ ወንለ+ሽ፡ ዓይነት፡ ወዓይነ፡ **ወዓይነ፡ ወርቅ፡ መንሶ፡** ወሥራይ፡ ይትሐተሙ፡ በማኅተመ፡ እሌኒ፡ ንግሥት፡ ወበማኅተመ፡ ሰሎሞን፡ ንጉሥ፡ ከመ፡ ኢይቅረቡ፡ ኀበ፡ ነፍሳ፡ ወሥጋሃ፡ ለአመተ፡ እግዚአብሔር፡  
I do not understand the word መንሶ፡ and whether it is connected to mansawa (lead to temptation).

The phrase, that the cross is salvation is also present in EMIPms00532: መድኀኒት፡ መስቀል፡ ኃይልነ፡ መስቀል፡ ፀንዕነ፡ መስቀልቢዘነ፡ **መስቀል፡ መድኃኒተ፡ ነፍስነ፡** አይሁጽ፡ ክሕዱ፡ ወንህነሰ፡ አመነ፡ ወእለ፡

In any case, I would create a new ID for the text in BLorient11602.

**Comment by karljonaskarlsson** [comment]
I agree that a new ID seems to be needed

**Comment by nafisa-valieva** [comment]
Ok for me!

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998

**Comment by CarstenHoffmannMarburg** [comment]
> [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)

I understand your comment as you request to consider Strelcyns work from 1955 ("Prières magiques" in Rocznik orientaliistyczny). I have this volume at hand, but I cannot find any information or parallels in the manuscripts and texts in it. I also checked the index of his catalogue on the Wellcome collection (Strelcyn 1972), where I found the word manšo as it is referred to as a disease. However, I am wondering, whether a proper disease fits well into this passage and whether the missing stroke for the palatal ሾ in መንሶ፡ is a rather untypical deviation. I think, it is appropriate to include this information in an abstract and the reference in the bibliography marking it as possible but not certain.

<img width="659" alt="Screenshot 2024_mansho" src="https://github.com/user-attachments/assets/287c22f1-f9b6-46f9-8296-ccf3993fc3d5">

**Comment by CarstenHoffmannMarburg** [comment]
I wanted to create a LIT ID, but it was not correctly saved to the folder. I got an error note:

![grafik](https://github.com/user-attachments/assets/056d21e8-220a-44d8-a58b-a449b3b31d4f)

I remember, that this or similar cases happened in the past and that it caused troubles with double IDs. How can I solve this? I tried to find the file by typing https://betamasaheft.eu/LIT7083Manso, but I got the answer, that LIT7083Manso is not an available item. What shall I do?

**Comment by CarstenHoffmannMarburg** [comment]
@eu-genia can you help?

**Comment by eu-genia** [comment]
Read the message and you will see: you were not logged in. The file was not saved.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2238
https://github.com/BetaMasaheft/Documentation/issues/2029

**Comment by CarstenHoffmannMarburg** [comment]
I see that the problem was that the application did not see me as logged in when it created the file, whatever the reason may have been. However, I am not sure what to do now. Should I create a new record with the New button in oxygen with the same ID (LIT7083Manso) or is this CAe already used for another work (as it was the case with Marcin recently in https://github.com/BetaMasaheft/Documentation/issues/2029) and should I then create a new ID with a new CAe from the Bm website?

**Comment by CarstenHoffmannMarburg** [comment]
I have seen, that the pull request is still in the app. This is confusing to me, because in this issue, the pull request was marked as being merged. However, I will try to download it from betamasaheft.eu, create a pull request to merge it. Is this correct?
![Screenshot 2024-10-22 164944](https://github.com/user-attachments/assets/3738359d-e9cc-4466-9ba4-9fdb4b146c5b)

**Comment by CarstenHoffmannMarburg** [comment]
OK. I will open a new branch and create a new ID for this prayer through the app.
