### ISSUE TITLE
Magical prayer for binding demons Ṗaṗur Ṗǝwyākāʾel

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2620]
@eu-genia @DenisNosnitsin1970 @nafisa-valieva @karljonaskarlsson 

I found a prayer for binding demons (or devils as Strelcyn says) in BLorient11602. There are two indefinable words following አጋንንት, which may be the names of demons (በስመ፡`<gap reason="ellipsis"/>` ጸሎት፡ በእንተ፡ ማዕሠረ፡ አጋንንት፡ ጰጱር፡ ጵውያካኤል፡).

I want to create a new ID for this prayer.

**Comment by nafisa-valieva** [comment]
Ok for me!

**Comment by karljonaskarlsson** [comment]
For me as well! We use Ṗ for capital ṗ, right? (In the record, I mean – here it doesn't matter, of course)

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998

**Comment by CarstenHoffmannMarburg** [comment]
> For me as well! We use Ṗ for capital ṗ, right?

OK.

**Comment by CarstenHoffmannMarburg** [comment]
> [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)

I found the two odd words in Strelcyn 1955

Ṗaṗur in BLorient11602 is very similar to Ṗaṗar, Ṗaṗurlāmā (also Papurlāmā), Ṗaṗurālābā, attested in Ms. Vat. 128, edited in Strelcyn 1955 (cf. f. 50vb, 56rb, 62ra, 62va) in different prayers in the same codex, is not explained, but it could be regarded as either a kind of Asmāt or Qālāt according to his definition (for he writes these terms in italics like many other magic words). The problematic point is, that in BLorient11602, the word Ṗaṗur appears in a place, that makes me think about the name of a demon rather than a magic word for binding demons contrary to the use in BAVet128.    

Ṗǝwyākāʾel (as in BLorient11602) is also found in a similar form in Strelcyn 1955 in the form of Ṗǝrāʾel (on f. 33va in BAVet128). This name was explained by Strelcyn as possibly deriving from the Hebrew name of an angel, Ṣūrāʾil, which occurs frequently in Aramaic and Jewish texts. The mutilation from Ṗǝrāʾel to Ṗǝwyākāʾel is quite strong and for this reason the derivation of this name may be considered possible but vague. 

I want to create a LIT ID and explain the two terms as outlined here.

**Comment by CarstenHoffmannMarburg** [comment]
> > For me as well! We use Ṗ for capital ṗ, right?
> 
> OK.

Changed.

**Comment by karljonaskarlsson** [comment]
> > [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)
> 
> I found the two odd words in Strelcyn 1955
> 
> Ṗaṗur in BLorient11602 is very similar to Ṗaṗar, Ṗaṗurlāmā (also Papurlāmā), Ṗaṗurālābā, attested in Ms. Vat. 128, edited in Strelcyn 1955 (cf. f. 50vb, 56rb, 62ra, 62va) in different prayers in the same codex, is not explained, but it could be regarded as either a kind of Asmāt or Qālāt according to his definition (for he writes these terms in italics like many other magic words). The problematic point is, that in BLorient11602, the word Ṗaṗur appears in a place, that makes me think about the name of a demon rather than a magic word for binding demons contrary to the use in BAVet128.
> 
> Ṗǝwyākāʾel (as in BLorient11602) is also found in a similar form in Strelcyn 1955 in the form of Ṗǝrāʾel (on f. 33va in BAVet128). This name was explained by Strelcyn as possibly deriving from the Hebrew name of an angel, Ṣūrāʾil, which occurs frequently in Aramaic and Jewish texts. The mutilation from Ṗǝrāʾel to Ṗǝwyākāʾel is quite strong and for this reason the derivation of this name may be considered possible but vague.
> 
> I want to create a LIT ID and explain the two terms as outlined here.

I'm not sure what to make of the same word appearing in different functions. For me, who doesn't know much about the topic of magical texts, it does not seem that farfetched that the same word could have had different meanings in different times and places.

But ጹራኤል > ጵራኤል is not so far, right? I have seen ጸንጠሌዎን for ጰንጠሌዎን :)
