### ISSUE TITLE
Magic prayer to banish black Bāryā

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2621]
@eu-genia @DenisNosnitsin1970 @nafisa-valieva @karljonaskarlsson 

There is a magic prayer in BLorient11602, that speaks about "banishing black Bāryā": በስመ፡(...) **ተሰደድ፡ አንተ፡ ባርያ፡ ጸሊም፡** አጽመ፡ ዘትሰብር፡

There are some other manuscripts with the same set of words but in combination with other demons:

EMIPms00545  	እምእዳ፡ ጻላዒ፡ ወፀር፡ ዳቤ፡ ወደቢት፡ **ተሰደድ፡ አንተ፡ ባርያ፡** ወሌጌዋን፡፡ ዘታባሃንን፡ 

EMIPms00511   ሰንተሞ፡ ቀንታም፡ ስጅር፡ ዱሐም፡ ተአስር፡ ዱሐም፡ **ተሰደድ፡ አንተ፡ ባርያ፡** ሸተላይ፡ ዘታውኅዝ፡ ደመ፡ ወትቀትል

I suggest to create a record for the text in BLorient11602.

**Comment by nafisa-valieva** [comment]
Ok for me!

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998

**Comment by CarstenHoffmannMarburg** [comment]
> [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)

I did not find the verb saddada/tasadda, neither  in the list of magic actions (appendix III) nor in any other place.

**Comment by karljonaskarlsson** [comment]
> > [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)
> 
> I did not find the verb saddada/tasadda, neither in the list of magic actions (appendix III) nor in any other place.

I don't understand (https://betamasaheft.eu/Dillmann/?mode=none&q=ተሰደ&id=L061ce3a10d6c4f28a0c580f628377905)

**Comment by CarstenHoffmannMarburg** [comment]
> > > [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)
> > 
> > 
> > I did not find the verb saddada/tasadda, neither in the list of magic actions (appendix III) nor in any other place.
> 
> I don't understand ([https://betamasaheft.eu/Dillmann/?mode=none&q=ተሰደ&id=L061ce3a10d6c4f28a0c580f628377905](https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%89%B0%E1%88%B0%E1%8B%B0&id=L061ce3a10d6c4f28a0c580f628377905))

I know that saddada/tasadda/tasaddada is listed in both Leslaus' and Dillmanns' dictionaries. However, I looked at Strelcyn's list of magical actions in his 1955 article, where he offers a number of verbs used in magic prayers to attack or protect against demons or magical actions. I did not find this verb in Strelcyn's list. I apologise for my imprecise note.

**Comment by CarstenHoffmannMarburg** [comment]
> > > > [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)
> > > 
> > > 
> > > I did not find the verb saddada/tasadda, neither in the list of magic actions (appendix III) nor in any other place.
> > 
> > 
> > I don't understand ([https://betamasaheft.eu/Dillmann/?mode=none&q=ተሰደ&id=L061ce3a10d6c4f28a0c580f628377905](https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%89%B0%E1%88%B0%E1%8B%B0&id=L061ce3a10d6c4f28a0c580f628377905))
> 
> I know that saddada/tasadda/tasaddada is listed in both Leslaus' and Dillmanns' dictionaries. However, I looked at Strelcyn's list of magical actions in his 1955 article, where he offers a number of verbs used in magic prayers to attack or protect against demons or magical actions. I did not find this verb in Strelcyn's list. I apologise for my imprecise note.

I found this verb also in Strelcyn in his list of protective magic (Magie défensive) on page 366 with the meaning ይሰደዱ፡ "qu'ils soient chassés".

**Comment by karljonaskarlsson** [comment]
> > > > [#2627 (comment)](https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998)
> > > 
> > > 
> > > I did not find the verb saddada/tasadda, neither in the list of magic actions (appendix III) nor in any other place.
> > 
> > 
> > I don't understand ([https://betamasaheft.eu/Dillmann/?mode=none&q=ተሰደ&id=L061ce3a10d6c4f28a0c580f628377905](https://betamasaheft.eu/Dillmann/?mode=none&q=%E1%89%B0%E1%88%B0%E1%8B%B0&id=L061ce3a10d6c4f28a0c580f628377905))
> 
> I know that saddada/tasadda/tasaddada is listed in both Leslaus' and Dillmanns' dictionaries. However, I looked at Strelcyn's list of magical actions in his 1955 article, where he offers a number of verbs used in magic prayers to attack or protect against demons or magical actions. I did not find this verb in Strelcyn's list. I apologise for my imprecise note.

Ok, I understand :)
