### ISSUE TITLE
Magic prayer against devils, bāryā, legewon, migraine, colic, chest pain, rheumatism, budā, falašā, gudale, dabbās, and all diseases in BLorient3663

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2622]
@DenisNosnitsin1970 @eu-genia @nafisa-valieva @karljonaskarlsson 

I found a magic prayer against various demons and diseases in BLorient3663. The text is the following: በስመ፡ <gap reason="ellipsis"/> በስሙ፡ ለአብ፡ በስሙ፡ ለወልድ፡ በስሙ፡ ለመንፈስ፡ ቅዱስ፡ **ታኦስ፡ አዝያስ፡ ሚልክያስ፡** (...) በዝ፡ አስማት፡ ስድዶሙ፡ ለአጋንንት፡ ለባርያ፡ ወለሌጌዎን፡ ለፍልፀት፡ ለቁርፀት፡ ለውግዓት፡ ወልቁርጥማት፡ **ለቡዳ፡** ወፈላሻ፡ ለጉዳሌ፡ ለደባስ፡ እምኵሉ፡ ሕማም፡ እቀቦ፡ ለገብርከ፡ (...)

This text has some parallels with LIT6851Prayer as attested in BDLeu7: ጸሎት፡ በእንተ፡ ሕማመ፡ **ቡዳ፡** ወቁመኛ፡ በስሙ፡ ለእግዚአብሔር፡ አብ፡ በስሙ፡ ለእግዚአብሔር፡ ወልድ፡ በስሙ፡ ለእግዚአብሔር፡ መንፈስ፡ ቅዱስ፡ **ታኦስ፡ አዝዮስ፡ ማሲ፡ ማስያስ፡** አብፌድርስ፡ ሩፋን፡ በጠጄን፡ ዘሐጄን፡ ዋኅ፡ ዋኅ፡ ዋኅ፡  

As well EMIP00616 has some similarities: እግዚአብሔር፡ ወልድ፡ በስሙ፡ ለእግዚአብሔር፡ መንፈስ፡ ቅዱስ፡ **ታኦስ፡ አዝያስ፡ ወለሚልካያስ፡** አክሴፍር፡ አሐፌፌክር፡ ወወጁን፡

I suggest to create a new LIT ID for the text in BLorient3663. The similarities in LIT6851Prayer are probably two meager to mention it in a relation.

**Comment by nafisa-valieva** [comment]
ok for me!
