### ISSUE TITLE
Nicene Creed in Amharic

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2624]
MS Uppsala, UUB, O Etiop. 10 contains the Nicene Creed in Amharic: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0307&pid=alvin-record:480189

I think creating a new work file for this might be good. Do you agree?

@nafisa-valieva @CarstenHoffmannMarburg @eu-genia @DenisNosnitsin1970

**Comment by CarstenHoffmannMarburg** [comment]
I agree.
