### ISSUE TITLE
Marian prayer in UUB O Etiop. 10

### ISSUE THREAD

**Issue by karljonaskarlsson** [BetaMasaheft/Documentation#2625]
There is a prayer on 151va–152ra in Uppsala, UUB, O Etiop. 10 that I cannot find in the existing records: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0306&pid=alvin-record:480189. It begins እሴብሕ፡ ጸጋኪ፡, which appears also in other prayers, but it continues differently from the others that I found. Can I create a new record?

@CarstenHoffmannMarburg @nafisa-valieva @eu-genia @DenisNosnitsin1970

**Comment by CarstenHoffmannMarburg** [comment]
I see strong similarity to LIT3063RepCh343 as it is attested in EMIP00203
Words contained in both are: እሴብሕ፡ ጸጋኪ፡ ኦእግዝእትየ፡ ማርያም። / ታቦር፡ / ልብየ፡ ወታርትዒ፡ ፍኖትየ፡ and others 

**EMIP00203**
<img width="261" alt="Screenshot 2024_Hymn to our lady" src="https://github.com/user-attachments/assets/a7365519-ff09-4ac9-ab56-a95458e998d8">

**OEtiop10**
<img width="161" alt="Screenshot 2024_Hymn to our lady_OEtiop10" src="https://github.com/user-attachments/assets/8cfef170-cf26-4be6-8c24-ff16a3f608fb">

**Comment by CarstenHoffmannMarburg** [comment]
Also LIT3582Prayer seems to be very similar to me: እሴብሕ፡ ጸጋኪ፡ ኦእግዝእትየ፡ ማርያም፡ ወእስእለኪ፡ ታብርሂ፡ ልብየ፡ ወታርትዒ፡ ፍኖትየ፡ ከመ፡ እሖር፡ በንጹሕ፡ ልብ፡ በግኖተ፡ ክርስቶስ፡

If you see important differences, I think it is important to explain the differences explicitly and to disambiguate it from the existing
records and to disambiguate the existing records from one another.

**Comment by karljonaskarlsson** [comment]
Yes, the beginnings are similar, but not the rest, it seems to me. It's a very good idea to add disambiguating statements!

**Comment by eu-genia** [comment]
Very good, please edit all the relevant records to make it clear, thank you!
