### ISSUE TITLE
Magic prayer "The secret names of Solomon" - with discussion on Magic related keywords

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2627]
I found a prayer in BLorient5425, that was entitled "The secret names of Solomon". The incipit and selected parts of the text are the following:
በስመ፡ (...) አስማተ፡ ሰሎሞን፡ ዘንተ፡ አስማተ፡ በእንተ፡ ተግባረ፡ ሰብእ፡ እቤእቤእቤ፡ (...) በዝንቱ፡ አስማት፡ አድኅኖ፡ ገብርከ፡ ገብረ፡ መድኅን፡ አምኵሉ፡ ተግባረ፡ ሰብእ፡ ወእምኵሉ፡ አቃብያነ፡ ሥራይ፡ ወእምኵሉ፡ ወእምኵሉ፡ ግብረ፡ ጸላዒ፡ ሰይጣን፡

There is a LIT ID for "Protective prayers attributed to Solomon" (LIT3991Prayer), that probably was established to serve as a generic ID for all protectiv prayer, that are related to Solomon and therefore suitable for this case. However, the only witness so far is BLadd16214, which as absolutely no parallel to the above mentioned one except for the solitary mention of Solomon:
ጸሎት፡ በእንተ፡ አቁያጻት፡ ወመሣርያን፡ እለ፡ ይቀትሉ፡ ነፍሰ፡ ዘእንበለ፡ ጊዜ፡ እለ፡ ቦሙ፡ ዕፀ፡ መስውር፡ ወይትሜሰሉ፡ በህልመ፡ ሌሊት፡ ወበአርአያ፡ ዘመዓልት፡ እለ፡ የሐውሩ፡ ወእለ፡ ይትሜሰሉ፡ ድበ፡ ወቈናጽለ፡ ነምረ፡ ወኦነረ፡ ቋዓ፡ ወሆባየ፡ ሐሪሰ፡ ወሐርማዘ፡ ወቀታተ፡ ሰገኖ፡ ወጸገኖ፡ ወጽንጽንያ፡ ወመባርተ፡ ወጽንጵላላተ፡ ወእለ፡ ይትሜሰሉ፡ ጽልመተ፡ ወእለሂ፡ ፈረሰ፡ ወበቅለ፡ ዓድገ፡ ወከይሴ፡ ወመንጸቆ፡ እለ፡ ይቄስሙ፡ ሥራየ፡ ኀበ፡ ኵሉ፡ ሰብእ፡ በመብልዕ፡ ወበመስቴ፡ እለ፡ ያደነግፁ፡ ወይበረብሩ፡ ወየአንቁ፡ ክሳደ፡ ወየአጽዉ፡ እንግድዓ፡ ወይሰልቡ፡ ልበ፡ ወይዌልጡ፡ አርአያ፡ ሰብእ፡ ወበዝኵሉ፡ ይትሜሰሉ፡ ኅቡረ፡ እንዘ፡ ሰብእ፡ ከማነ፡ ወዘንተ፡ ብሂሎ፡ ተስእሎ፡ ሰሎሞን፡ ለእግዚአብሔር፡ ወይቤሎ። 

There are a number of prayers in manuscripts that contain the words አስማተ፡ ሰሎሞን፡, but none of them seem to have any similarity to the text in BLorient5425.

Because it is a Asmat-prayer that works with the invocation of secret names, the generic ID LIT5888AsmatPrayer would be useful as well.

I suggest to create a new ID for this prayer in BLorient5425 to avoid the usage of one of the two generic IDs. I will find a way to relate it to LIT5888AsmatPrayer and to LIT3991Prayer.

@eu-genia @DenisNosnitsin1970 @nafisa-valieva @karljonaskarlsson

**Comment by eu-genia** [comment]
OK; it would be good if LIT3991Prayer is edited to include the text to allow for clear disambiguation 

I also wonder if it makes sense to take _Prières magiques éthiopiennes pour délier les charmes_ (maft̳aḥe š̳arāy) by Strelcyn and create a repertory starting from the study rather than redoing Strelcyn's work going occasionally through manuscripts (just like we did for the hymns and Chaîne). Griaule's recettes could also be considered.

@abausi if you agree that it is a sensible task I would ask @CarstenHoffmannMarburg to dedicate some time to it, I believe we need to work more systematically

**Comment by abausi** [comment]
It makes sense, but it will not be easy. We van try
 Rocznik Orientalstycny is fully available online.

Il gio 5 set 2024, 21:25 Eugenia ***@***.***> ha scritto:

**Comment by CarstenHoffmannMarburg** [comment]
I like the idea of systematically encoding the magical prayers from the sources published by Stefan Strelcyn mentioned above. I am aware of the difficulties of comparing these texts with the already existing records, which often enough lack sufficient indications for a clear identification. But even though it is not easy, I think it is necessary. I am prepared to devote myself to this task, unless there is another, possibly more experienced, scholar who wishes to undertake it.

**Comment by eu-genia** [comment]
Thank you @CarstenHoffmannMarburg, very good!  You can also propose while you are at it a meaningful set of keywords.

**Comment by CarstenHoffmannMarburg** [comment]
I found the article recommended by Eugenia in zotero:

Strelcyn, S. 1955 Prières magiques éthiopiennes pour délier les charmes (maftǝḥe šǝrāy), Rocznik orientalistyczny 18. 

However, I did not find this contribution online, but it is indicated to be present in SUB with the signature AR 4302.

Beyond, there are more publications by Strelcyn related to his research on Magic prayers. As far as I can see from the titles, there are the following:

Strelcyn, S. 1949, Sur une prière 'falacha' publiée par c. conti rossini dans les appunti di storia e letteratura falascià, Rassegna di Studi Etiopici 8, 63-82 (online available).

Strelcyn, S. 1951, Note sur le manuscrit éthiopien d'Abbadie 7 de la B. N., Rassegna di Studi Etiopici 10, 52-55 (online available).
 
Strelcyn, S. 1960, La magie éthiopienne, Atti del Convegno Internazionale di Studi Etiopici (Roma 2–4 aprile 1959), 357, Problemi attuali di scienza e di cultura, 48, 147-166.

Strelcyn, S. 1983, Un poème satanique éthiopien, Guirlande pour Abba Jérome: travaux offerts à Abba Jérôme Gabra Musé par ses élèves et ses amis réunis par Joseph Tubiana, Paris, 83–115.

Strelcyn, S. 1951: Un magicien grec en Éthiopie. 

Furthermore, there is also a number of publications concerning plant names and medicine, that may also be related to magic, but which I do not want to consider for the moment. Furthermore, there are a number of catalogues, that may contain valuable information, as well. I want to consider the Indeces of these catalogues, because they contain keywords for Magic prayers, that could serve very well also for keywords in Bm.

**Comment by eu-genia** [comment]
1955 is a monograph, the rest are minor contributions, so I would start with the main study. The earlier articles are clearly superceded by the monograph, and the later ones also depend on it.
If you cannot get borrow the copy from SUB or another library, maybe @MarcinKrawczuk has it (?) or we can ask @JanetFre to scan

**Comment by CarstenHoffmannMarburg** [comment]
From the titles above, I would like to suggest a number of keywords and also list those for which I think we should turn them into keywords. First of all, we should discuss the criteria for what is a good keyword in relation to magic texts or pictures. I think that a keyword should point to a specific and important part of a text (or picture) that makes it different from others. It should be a more or less common feature, more often attested in catalogues, and not solitary. I would also avoid using coded names of patrons or helpers such as Salomon, Moses, Michael, Adam, the three Children, St Andrew, Elyās, the Trinitiy, Mary or the Cross, as these could easily be used for other non-magic texts and lead to confusion. Information about helpers may be better given in summaries or relationships in work records.

In principle, all the keywords listed in Strelcyns' catalogue for distinguishing magical prayers are candidates for keywords in Bm, but I want to limit the number of keywords to dozens, not hundreds. For this reason I would like to suggest the following keywords:

a) Those that are already suggested by Eugenia in https://github.com/BetaMasaheft/Authority-Files/pull/33#issuecomment-2342779558 and for which I agree: Bāryā, BindingDemons (or: Maftahe), Bleeding, Buda, Colic, Dask, DrowningDemons, Colic (or Qwersat), Epilepsy, EvilEye (or Aynat), Falasa (or better Falasha), Fever (or Nedad), Gudale, Legewon, and Malaria (or fera)

b) Those that Eugenia suggested, but which are not very frequent to my perception or which are represented by other keywords, that I want to suggest, but which are nevertheless acceptable to me:
Dabbas, Aqweyasat, ChestPain

 c) Keywords, that I suggest to add to this list according to Indices and titles from Strelcyns catalogue of BL manuscripts in 1978:

Asmat (ʾasmāt or Secret Names)
Blacksmiths
BlackMagic (or SatanicMagic?)
Charms
Disease
Maganna (Magāññā = a demon?)
Neqatqat (nǝqaṭqaṭ or Smashing of Demons?)
Pain
Šotalay (Šotalāy or Šotālāy)
Witch
Witcher (or witch doctors or magicians)
Zar (zār)
(to be continued)

d) Words taken from Strelcyns index, that are useful to distinguish Magic prayers from one another, but which I would suggest not to create a keyword, because the indicated calamity does appear only once or rather rare in manuscripts or which are already sufficiently represented in other keywords are the following:

aphrodisiac
abdominal pain (or stomach pain)
contagion
demon of noon
injustice
mǝč
migraine
pestilence
qʷǝraññā (= wrath)
ṣǝllā wagi (= tablet or beam of the warrior?)
(to be continued)

**Comment by CarstenHoffmannMarburg** [comment]
Continuation keyword-list for magic prayers:
c) suggested keywords 

animals
love/mastafāqǝr
Satan
miscarriage/pregnancy
enmity/enemies/ṣar/magrare ṣar
stones/ʾandarabbi
(to be continued)

d) no keywords recommended

ʾabrǝq/flash
ʾalbugo
ʾardǝʾt
ascaris/soldiers
ʾaṣǝnt (= existence?)
baldness
cataract
cattle
čǝfe/blindness
conjuntivitis
cough
delivery
devils
ears
ʾǝṭi/tumor
eye
fire
gǝrma mogas
ḥaṣura masqal / cross
haemorrhage (represented by bleeding)
horse
house
goods
impotence/potence
leprosy
lance wounds
lǝfāfa ṣǝdq/bandlet of the rightousness
marbabta Salomon
measles
mule
nocturnal terror
rain
revelations
rheumatism
rich
respect
smallpox
snake
sores (= wounds)
suckling infants
tǝmḥǝrta ḫǝbuʾat
thieves
traveller
(to be continued)

**Comment by CarstenHoffmannMarburg** [comment]
Continuation of proposed keywords taken from Strelcyn 1978 (BL as above), Strelcyn 1974 (Rylands) amd Strelcyn 1972:

c) proposed keywords

Dǝdǝq (a demon or an accident or a sudden disease)
Dino/Dini/Dānit/Dinit (evil spirit or demon)
Dobbi/Dobbit (a kind of a sorcerer)
Gargāri/Nagārgār (probably the same demon)
Ǧǝn (ghosts or demons as in Arabic ǧinn)
Qāwzā/Qāwezo/Qāwezā/Maqawze ('king of devils')
Ṣəlā/ʿayna ṣǝlā/Ṣəlā wagi (According to Strelcyn 1973, it is a demon with that name and not ṣəllā = tablet as described above)
Śərāʾel/Śǝrāyal (According to Strelcyn 1972 'beings', but not demons, encountered in rivers, especially at noon, and in desert places when one is walking alone.)
Tǝgridā/Tǝgrǝtyā (a demon)
Wǝllāǧ (literally "the offspring" or "mulatto" = according to Strelcyn a mongrel of a zar and a demon. It can possibly be included to Zār)
Wǝrzǝlyā (a demon)

d) not proposed for keywords

abort
amulet
artisan
asthma
chains/bonds (for demons, there is already BindingDemons, for humans it is negligible)
Christian
coitus
dagāmyāna ʿǝṣ (magicians who make incantations using wood)
diviner/mʷārtaññā/māri
dog
enlightment
fart
fidelity
foetus
food (as beer, bread, fish, etc.)
four elements
fright/fear
Gog and Magog
gʷǝrguho (a demon, related to ʾangʷargʷara = being angry?)
haemorrhoids
hair
headache
hemeralopy (day blindness)
injustice
jaundice
labour
lašǝt (smell?)
madman
madyāt (medicine)
market
mǝč/mǝtāt (violent disease with fever)
mətʿat (rhythm = compulsive movements?)
mǝthat (phantom, illusion; already represented in black magic)
murder/murderer/qatalāy
nails (of the cross)
Nǝdārā (= proper name of the evil eye, probably identical with ʿaynat or ʿayna warq or ʿayna ṣǝlā wagi etc.) 
nǝdǝft (a disease of horses or mules)
nose-bleeding
palpitation (tǝrǝntǝr)
perfume
periostitis/sǝqǝssǝqat 
placenta
premature delivery
pus/magǝl
qamaññā/qʷǝmaññā/qumañña/qamaññā (Sorcerer who makes people ill using philtres and poisons; Could be useful to mention in a file for wizard/sorcerer. However, Trzes explains the word as a disease)
qoqolāy (unidentified)
scabies
scrofula/mǝšǝro
shadow
skin disease (waṭa)
slaves (not to leave the masters house)
sleep
sterile woman/makān
swelling
syphilis/qiṭṭǝñ
talāwāš (listed as 'unidentified' in Strelcyn 1972)
tapeworm
ṭǝfi (slap?)
toothache (la-ḥǝmāma ṭǝrs)
travel
ulcers
urination
tongue/voice/stutter/mute
yamedā wǝdqat (crop failure)
yazār wǝllāǧ (the offspring of the demon Zar?)
Zaradašat ('father of the magicians')
zema

**Comment by CarstenHoffmannMarburg** [comment]
In my opinion, more information to each keyword could be added for using Strelcyns publications and several articles in EAe. This would be very useful as many names or terms are ambiguous and need explanation. This can be done in the summary of the files you have created for the keywords. But it might be more visible and practical if each of them, or at least some of them, also got authority files. I think this is more practical because demons, diseases, etc. can also appear in other texts (e.g. chronologies). It could be easily marked up with ref type="authFile", but also with PRS IDs for demons or wizards.

**Comment by CarstenHoffmannMarburg** [comment]
I have seen that "TrueCross" is already a keyword saved to Authority-Files > ObjectsVeneration. I think, it can be used to mark up Magic Prayers, as well.

**Comment by eu-genia** [comment]
I think I will wait a bit till a meaningful list (should not be too detailed) is compiled

**Comment by eu-genia** [comment]
And keyword files are already authority files, each keyword can be referred to through `ref type="authFile"` (just like we do for TrueCross e.g. when pointing from churches or texts).

**Comment by CarstenHoffmannMarburg** [comment]
Another name of a demon, probably suitable for a keyword/authority file is Bǝryāl (witnessed i.e. in BLorient12859).

**Comment by CarstenHoffmannMarburg** [comment]
I got Strelcyn, S. 1955 Prières magiques éthiopiennes pour délier les charmes (maftǝḥe šǝrāy), Rocznik orientalistyczny 18 from the HLCEE library. The book is very useful for learning more about Ethiopian magical scrolls and texts. For example, in the appendix to this volume one can find information and detailed explanations on various terms that we have discussed as keywords (e.g. for Bāryā Strelcyn also knows the 'Red Bāryā' next to the 'Black Bāryā' and on the Amharic term bāryā yazāw = to have epilepsy). It might be useful to add this information or the bibliographical reference to the existing PRS records if this is not too detailed and cumbersome.

However, I do not think it is very helpful in deciding on keywords - at least if we want to reduce the number of possible keywords but not enlarge them.
I think the next step is to decide how many keywords are acceptable to us in a way that is practical for encoders and helpful for users. In my opinion, the number of keywords related to Magic should not exceed 20. This would mean that the large number of demons (such as Bāryā, Gudāle, Wərzəlyā, Təgridā, ... see in the list above) cannot be part of this list of keywords. Either we refrain from using demons as keywords at all (and instead use PRS records to tag them, which would go against what Eugenia recently explained here as the current practice: [#33)](https://github.com/BetaMasaheft/Authority-Files/pull/33#issuecomment-2363646631) or we need to reduce them to a minimum number of the most prominent.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2245

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2600

**Comment by CarstenHoffmannMarburg** [comment]
It is probably not the right place to narrate the introductory remarks of Strelcyn 1955 in every detail, but rather summarize the categories on magic texts or more specifically of maftāḥe śəḥāy, which are at the focus of his study.

Strelcyn emphasizes some major distinctions, that are useful to describe magic texts. However, not all of them are useful keywords to my point of view:

a) distinction between "general benediction" (Christian texts, used for magic purpose) and "amuletts" (understood both as a type of text and of any written artefact containing such texts i.e. scrolls or books). -> I think, we do not need a new keyword for "general benediction". The existing keyword "Christian content" or "Christian literature" are sufficient for this type of texts, that are indeed very close to liturgical texts. The same is for "amuletts", which is ambivalent in this circumstance and which is well represented in "scroll" or "codex" in physDesc on the one hand and in "Magic" as a keyword to describe text and content on the other hand.

b) Second important distinction is between "actions totale", which are directed against any kind of malady and "actions précises", which are directed against specific calamities. However, I think, this category is better to be defined in an abstract verbally or in a title translation verbatim.

c) The third relevant distinction is between "black magic", which is directed to harm somebody else and defensive "white magic", which is directed to protect against the evil action of others. I advocated for a keyword "black magic" above. However, I think, that the protective magic is by far more numerous by about more than 95%. In this situation, I do not think, that a distinct keyword for "protective Magic" is needed. To my opinion, it is enough to have a keyword for the opposite, i.e. "black magic".

d) A distinction is made also for "qālāt" (which are more or less phantasy words) and "asmāt" (which are supposed to represent certain Christian or otherwise meaningful words or phrases from foreign language and circumstance). However, Strelcyn admits, that qālāt and asmāt tend to merge to one category over time and it is therefore doubtful, that it could be practical to distinguish between these two in Bm records. This is even more problematic, as very many records exist, that contain the word asmat without any possible distinction towards qālāt. 

e) Strelcyn also mentions the existence of magic images (ṭalsam), which, to my opinion, is well represented in deco desc, if supplemented with the keyword "Magic".

f) Strelcyn also mentions magic caracters, for which I do not know, if there is a good way of referencing. It may be useful to have a keyword "Magic caracter".

g) Strelcyn also speak about "medical-magic receipts" as an important component of many magic texts. I think, we have already a keyword for "medicine", what I think is sufficient. A new keyword specifically for medical-magic is not necessary or useful, because the boundaries between these two are to superfloous.

h) Strelcyn reports only very shortly and selectively on various magicians or demonic entities (as there can be identified social or "geographical" groups) in his introduction, but he lists a large number of them in his appendix, which is repeated and enhanced also in his catalogue for the manuscripts of the wellcome institute (1972). I think, it is problematic to create keywords for specific magicians, because they are too many. If it is desirable, sorcerers, witches etc. can be treated as persons and defined with a PRS or ETH ID. 

i) Similarily, it is difficult if not impossible to list all maladies, which appear in Ethiopic magic texts. It would be possible to create a selective list or to combine them to the following categories: "diseases", "animals", "wounds", "poison", "women's disease".

This is my proposal for a small set of keywords after studying Strelcyn 1955.

**Comment by eu-genia** [comment]
It is important to remember that the whole taxonomy (ALL keywords, whether those in the record or not, the whole file) is inserted into each XML record when it is expanded to be displayed, so we should try to keep the taxonomy compact (or find another solution for the future). Every added line increases the size of each and every XML record in the system. While each line is not a lot, when you reproduce it 100 000 times it does take storage space.

I think it is OK to create separate PRS records for "personified" demons (such as Werzelya) etc.

We already have `demon `among the keywords, that can always be used together with the generic `Magic `/ `MagicText `/ `MagicFormula `keywords, and we also have `Asmat` (we can specify there that it also covers _qālāt_).

I think we could add the following to the taxonomy

Magic and spells
- Subtypes (on top of existing MagicText MagicFormula Asmat)
- - --MagicDrawing (for all sorts not covered yet)
- - --MagicSymbols (for magical letters and such)

- Targets of spells 1: Diseases

- - --Disease (any disease)
- - --DiseaseFever (any disease with fever, incl malaria)
- - --DiseasePain (any disease with pain, colic, headache, heartache)
- - --DiseaseMental (any neurological or mental disease, epilepsy/fits, madness)
- - --DiseaseWomen (infertility, menstruation, etc)

- Targets of spells 2: Evil influence, in addition to demon (keyword) Satan (PRS11330Devil) and other personifiable demons

- - --EvilEye
- - --EvilSpirit (generic for all others, if needed, one can create sub-IDs, as we do for text chapters, under `EvilSpirit.xml `and then one could, if necessary, point to EvilSpirit#Barya, EvilSpirit#Buda etc.
