### ISSUE TITLE
Asmat prayer to protect the shinbone (ጸሎት፡ በእንተ፡ አቁያጻት፡) in BLorient5425 and EMIP00616

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2628]
I discovered a prayer to protect the shinbone (ጸሎት፡ በእንተ፡ አቁያጻት፡) in BLorient5425 with the following incipit:
በስመ፡ (...) ጸሎት፡ በእንተ፡ አቁያጻት፡ ወበእንተ፡ ግብረ፡ ሰብእ፡ አቃብያነ፡ ሥራይ፡ እለ፡ ይቀትሉ፡ ነፍሰ፡ ዘእንበለ፡ ጊዜየ፡

A very similar text can be found in EMIP00616, where it is marked up with the generic ID for Asmat-prayers (LIT5888AsmatPrayer) and with the additional title in the manuscript record "Asmat Prayer to protect the shinbone (aqwuyaṣat) and against a witch doctor who killed a person before his time":
:በስመ፡ አብ፡ ወወልድ፡ . . . . . ጸሎት፡ በእንተ፡ አቁያጻት፡ ወዓቃብያነ፡ ሥራይ፡ እለ፡ ይቀትሉ፡ ነፍሰ፡ ዘእንበለ፡ ጊዜሁ፡ እለ፡ ቦሙ፡ ዕፀ፡ ወመሠውር፡ እለ፡ ይትሜሰሉ፡ በሕልመ፡ ሌሊት፡ ወመዓልት፡ በራዕይ ፤ እለ፡ ይትሜሰሉ፡ ዝዕበ፡ ወቍንጽለ፡ ነምረ፡ ወአርዓረ፡ ቋዓ፡ ወሆባየ፡ . . . . .

I suggest to create a new LIT ID for this prayer and to list both manuscripts as witnesses.

@eu-genia @DenisNosnitsin1970 @nafisa-valieva @karljonaskarlsson

**Comment by eu-genia** [comment]
sure

**Comment by nafisa-valieva** [comment]
Ok for me!

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2627#issuecomment-2332477998

**Comment by karljonaskarlsson** [comment]
Good!
