### ISSUE TITLE
Duplet for Central Tigray?

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#2631]
Does anyone knows as to why we have LOC6555CentralTegray and LOC6654CentralTegray? They look like the same, the latter seems to be the main one.

**Comment by eu-genia** [comment]
NB 1 this issue was created under Places, all issues must be created under Documentation, transferred
NB 2 the assignee should be just one person responsible for carrying out the necessary modifications, not persons just being asked

**Comment by DenisNosnitsin1970** [comment]
Should I clean it and insert 6654 everywhere?

**Comment by eu-genia** [comment]
That would be great, 6555->6654. Thank you!
