### ISSUE TITLE
Figure graphic for another new and untypical sign

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2632]
@eu-genia 

I found another new sign in Strelcyns description of BLorient12959, which looks similar to Greek Σ. It Strelcyns catalogue, it looks like that: 

![Screenshot 2024_SpecialSignBLorient12959](https://github.com/user-attachments/assets/692b997f-ed72-4b23-bd62-e02cc1ccaaaa)

Can you create a graphic with that figure, please, as you did in [Issue #2569](https://github.com/BetaMasaheft/Documentation/issues/2569)?

Thank you in advance!

**Comment by eu-genia** [comment]
https://betamasaheft.eu/resources/images/snippets/BLorient12959/sign1.png

**Comment by CarstenHoffmannMarburg** [comment]
The link ends with .png (not .tif). Is this relevant to the link, that I am supposed to add to the record? Is the following code OK?

```
<note>The scribe has filled up the spaces left at the ends of the lines with a special sign (<figure>
                                    <graphic url="BLorient12959/sign1.png"></graphic><desc>Symbol as represented by <bibl>
                                        <ptr target="bm:Strelcyn1978BritishLibrary"/><citedRange unit="page">123</citedRange></bibl>.</desc>
                                </figure>).</note>
```

**Comment by eu-genia** [comment]
Cp. https://github.com/BetaMasaheft/Documentation/issues/2569
