### ISSUE TITLE
Protective prayer against lance wounds በእንተ፡ ኵናት፡ in BLorient12859

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2633]
@eu-genia @nafisa-valieva @karljonaskarlsson 

I found a prayer against lance wounds in a magic scroll (BLorient12859):

```
<msItem xml:id="ms_i3">
    <title ref="LIT000000000000000000000">Prayer against lance wounds</title>
     <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ጸሎት፡ በእንተ፡ ኵናት፡ በስመ፡ ሀለኩ፡ ኸቢር፡ ኑራሂ፡ ሰላም፡ ኢኢዙቢላሂ፡</incipit>
      <textLang mainLang="gez"/>
                        </msItem>
```

Prayers against lance wounds are not uncommon and two of them have been encoded as LIT6982PPDiseases and LIT6989PPFear. In these cases, however, the lance wounds are together with diseases or with fear respectively and are secondary to them. The text as judged from the given incipit is very different.

In BLorient12859, there are some words that I cannot identify as lexically meaningful and I suppose, that they can be seen as ʾAsmāt: ሀለኩ , ኸቢር (perhaps derived from Arabic ḫabr = companion), ኑራሂ (with some similarity to ይኑር = he is tarnished, he is infamous; but without any sense in this construction and context), ኢኢዙቢላሂ

I want to create a new LIT ID and I want to give as keywords Wounds and Asmat (if this is decided after sufficient discussion in https://github.com/BetaMasaheft/Documentation/issues/2627 and https://github.com/BetaMasaheft/Authority-Files/pull/33#event-14193793065).

**Comment by karljonaskarlsson** [comment]
It sounds reasonable to create a new ID

**Comment by nafisa-valieva** [comment]
It sounds reasonable for me too!! Out of my ignorance: I have just learnt that Daria and Dorothea had a relevant presentation. In case you do not have, may be it can be of some relevance for what you are doing.

**Comment by CarstenHoffmannMarburg** [comment]
Thank you, Nafisa! If @DariaElagina or @thea-m would like to share their knowledge with me, I would be happy to receive their presentation on this topic.
