### ISSUE TITLE
A new Salam to George of Lydda used as protective prayer in a magic scroll (BLorient12859)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2634]
@eu-genia @nafisa-valieva @karljonaskarlsson 

I found a text in BLorient12859, which is described as "Prayer for protection. Salām to George of Lydda" by Strelcyn. The incipit is the following:
ሰላም፡ ለከናፍሪከ፡ እለ፡ ተከሥታ፡ ለዘምሮ። ስመ፡ ኢየሱስ፡ ክርስቶስ፡ መምለክያነ፡ ጣዖት፡ ለአስተሐፍሮ። ጊዮርጊስ፡ ልዳዊ፡ ዕጉሥ፡ ለተጽእሮ። ፈረስከ፡ ዘትፄዓኖ፡ እንደ፡ ያስተቃንጽ፡ ዕግሮ። ለረዊደ፡ ጸርየ፡ ይሩጽ፡ ወኢያንትግ፡ በጽሮ።

There is another Salam to George of Lydda encoded as LIT2799RepCh83 and attested in BAVet166, which has no correlation except for the name of George of Lydda:
 ሰላም፡ ለከ፡ ጊዮርጊስ፡ ዘልዳ፡ መስተፅዕነ፡ ፈረስ፡ ፀዓዳ፡ ሰማዕተ፡ ማርያ<ም>፡ ድንግል፡ ወፍቁር፡ ወልዳ፡

I propose to create a new LIT ID for the text in BLorient12859.

**Comment by karljonaskarlsson** [comment]
It looks like a stanza from a malkǝʾ. Maybe @smaugustine  can say if this is correct?

**Comment by nafisa-valieva** [comment]
Yes, @smaugustine was illuminating us that Salām are used too often for no reason. It would be good to have his expertise on this point, I think not too many hymns got their own ids for the moment, there is a hope to have it right / corrected based on fresh research!

**Comment by eu-genia** [comment]
This is surely from the Malkǝʾa Giyorgis, stanza 10

**Comment by eu-genia** [comment]
see e.g. ms EMML 1284 f. 111v-112r etc
![image](https://github.com/user-attachments/assets/9b6fde52-11dd-4757-80cd-3f63d23ed959)

**Comment by eu-genia** [comment]
I have added the text (extracted with OCR, not checked) to LIT2866RepCh147, labels to be added

**Comment by karljonaskarlsson** [comment]
Would it not be better to create a new LIT ID for this text and link it to LIT2866RepCh147?

Because the text in the manuscript that Carsten is describing does not seem to be an incomplete copy of LIT2866RepCh147 – to me it seems rather to be an intentional excerption, i.e. an independent circulation of this stanza.

**Comment by eu-genia** [comment]
I am not sure. As long as it is a single case I would think that referring to `LIT2866RepCh147#stanza10` is sufficient - we are not referring to an incomplete LIT2866RepCh147 but to a specific stanza (s? I do not know if the MS in question contains more of them)

**Comment by eu-genia** [comment]
(if we discover more occurences of individual circulation then yes it would be the case to create a new ID and add a `corresp` to `stanza10`)

**Comment by karljonaskarlsson** [comment]
Ok, that sounds fine! Hopefully, if someone discovers another independent attestation of Stanza 10, they will realize that it is already attested in this way
