### ISSUE TITLE
A new prayer for gaining respect

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2635]
@eu-genia @nafisa-valieva @karljonaskarlsson 

I found a prayer in the magic scroll of BLorient12859, which seek to gain respect, using the word አሸብሮሙ (amh. ሽብሩ "terror") and ግርማ "fear". I want to propose a new LIT ID for this text, that I did not find elsewhere.

በስመ፡ (...) ዑን፡ ነቢ፡ ሰላማ፡ (...) ከማሁ፡ አሸብሮሙ፡ ለሰብአ፡ ኵሉ፡ ፍጥረት፡ በግርማ፡ ገጸ፡ ገብርከ፡ (...)
ዑን might probably be an abreviation of እሙን "true, loyal, reliable" and possible translation could be:
"In the name of (...) the true prophet, her peace (...) in the same way I will terrorize the people of all kinds in fear facing your servant (...)"

**Comment by karljonaskarlsson** [comment]
I'm not sure about ʿun = ʾǝmun, but I agree that there seems to be no  LIT ID for this text so far, so I think you can create one

**Comment by eu-genia** [comment]
Sure, OK

**Comment by CarstenHoffmannMarburg** [comment]
I created LIT7116Respect, but it was not saved, because I was logged out. What can I do?

**Comment by CarstenHoffmannMarburg** [comment]
I created LIT7116RingSolomon for another text (cf. https://github.com/BetaMasaheft/Documentation/issues/2636). So, I see that CAe 7116 was still free and LIT7116Respect was not saved in the app. I will proceed in a minute and create a new LIT ID for the work, which is discussed here.

**Comment by CarstenHoffmannMarburg** [comment]
Again I wanted to create a file from the app and could not save the file. This time, it happened despite stable internet connection in the office. 

![grafik](https://github.com/user-attachments/assets/037b4343-4dfc-4310-874f-d12e4c996224)

**Comment by CarstenHoffmannMarburg** [comment]
I made a new attempt and I was more lucky and created LIT7120Respect.
