### ISSUE TITLE
Use of ETH1508Gallai vs. ETH1973Oromo for Gāllā in protective texts

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2637]
I found two IDs for Oromo/Gāllā: ETH1508Gallai and ETH1973Oromo

I assume, that ETH1508Gallai is to be used for a rather stereotyped use for example in magic scrolls (i.e. BLorient12859), where the term Gāllā stands for any kind of evil or enemies. It is marked as "Galla, idiom" in the record. ETH1973Oromo on the other hand is to be used for the historic Oromo people, no matter these mentions ar positive or deragatory. Is this correct?

I think, that the two IDs are not sufficiently described and disambiguated. I want to propose to add abstracts to each of the records, possibly as the following:

**ETH1508Gallai** 
Stereotyped idiom for evil people or enemies in war, frequently used for example in magic scrolls. The idiom is based on the outdated and deregatory idiom <foreign xml:lang="gez-tr">Gāllā</foreign> for the historic <persName ref="ETH1973Oromo">Oromo people</persName>.

**ETH1973Oromo** 
People in central and southern Ethiopia. Formerly called by the outdated and deragatory term <foreign xml:lang="gez-tr">Gāllā</foreign>.

@karljonaskarlsson @eu-genia @nafisa-valieva

**Comment by CarstenHoffmannMarburg** [comment]
I think, a similar distinction could be useful also for ETH2043sanqel. At the moment, only this one ETH ID exists both for the distinct and for the stereotyped meaning.

**Comment by karljonaskarlsson** [comment]
To me, it seems reasonable to add the abstracts that you suggest

**Comment by nafisa-valieva** [comment]
May be you can also add untill when it was commonly used by western scholars for the historic Oromo people (I do not know when exactly discussion has begun). I think it is not clear in the description you suggest, but it feels missing:  ETH1508Gallai
Stereotyped idiom for evil people or enemies in war, frequently used for example in magic scrolls. The idiom is based on the outdated and deregatory idiom Gāllā for the historic Oromo people.

**Comment by CarstenHoffmannMarburg** [comment]
From what I see, the term Gāllā was used predominantly until the second half of the 20th century as can be seen from publications of this time, i.e.

Edwin C. Foot: A Galla-English, English-Galla dictionary. Gregg, Farnborough 1968
Franz Praetorius: Zur Grammatik der Gallasprache. G. Olms, Hildesheim, New York 1973,

but:

Gene B. Gragg (Hrsg.): Oromo Dictionary. African Studies Center, Michigan State University, East Lansing, Michigan 1982.

I do not know, whether Gene Gragg was the first one to use the name Oromo in academia.

**Comment by eu-genia** [comment]
Let us not to reopen long opened discussions. It fully suffices for Galla to refer to EAE II 660-661, Oromo is for the actual people.
The use in academia is relatively irrelevant, relevant is the local use.

In general, I highly recommend checking EAe for all questions concerning Ethiopian history and ethnology.
The same applies to Falasha/Beta Esrael, Barya, Shanqella, and many many others.

![image](https://github.com/user-attachments/assets/a59cc84a-46a8-491c-8fb2-9527763727b9)
![image](https://github.com/user-attachments/assets/874728a4-e777-481f-9938-9494a6e2f980)
![image](https://github.com/user-attachments/assets/d62e3caf-e543-45e0-9c10-6a4a0baa71b5)
![image](https://github.com/user-attachments/assets/6279d4ee-0e72-41b6-ae2e-137bdde363b5)

**Comment by CarstenHoffmannMarburg** [comment]
As far as I can see, there is a record for Beta ʾƎsrāʾel, but not for the outdated idiom Fālāšā. Shall I create one similar to ETH1508Gallai/ETH1973Oromo?

**Comment by eu-genia** [comment]
I think for the moment the keyword is enough.
