### ISSUE TITLE
Malkǝʾa Māryām

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#2638]
For Malkǝʾa Māryām we have `LIT1858Malkea `(from the original index, used only once in an EMIP ms) and `LIT2891RepCh172 `(used in 73 records)

I guess `LIT1858Malkea  `must be deleted/merged to `LIT2891RepCh172 `

@karljonaskarlsson @DenisNosnitsin1970 @CarstenHoffmannMarburg @nafisa-valieva

**Comment by CarstenHoffmannMarburg** [comment]
I can confirm, that EMIP00037 (only witness of LIT1858Malkea) and EMIP00028 (one of the many witnesses of LIT2891RepCh172) contain the same text (at least in that folio, that I have checked). From my perspective, LIT1858Malkea can be deleted.
