### ISSUE TITLE
https://betamasaheft.eu/Guidelines/?id=colophon links to manuscripts (besides  ESakm010 and  DSEthiop7) do not work

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Documentation#2639]
I have tried to see examples for colophon descriptions, but most of the links appear not working. Would it be easy to fix?

@eu-genia

**Comment by eu-genia** [comment]
fixed, thank you

note: all issues should be created under the main issues page (Documentation). if you use https://betamasaheft.eu/help.html then just click from there, and you will be pointed to the right place

note: assignee of an issue is the person who has to do the work, not the one who creates the issue. 

note: use Labels to categorize the issues
