### ISSUE TITLE
A request to encode BnF d'Abb. 94

### ISSUE THREAD

**Issue by MarcinKrawczuk** [BetaMasaheft/Documentation#2642]
Is it OK if I do a basic encoding of BnF d'Abb. 94 because a) in the database there are links pointing to it b) it is relevant to my interests.

@eu-genia @CarstenHoffmannMarburg

**Comment by eu-genia** [comment]
I guess yes, currently @nafisa-valieva has taken over processing of the d'Abbadie collection from @DenisNosnitsin1970  so she would be the one to ask/confirm that she is not working on it.

**Comment by nafisa-valieva** [comment]
@MarcinKrawczuk Hallo! No problems with me! As you wish, either create yourself or I can create it for you.

**Comment by MarcinKrawczuk** [comment]
Thanks! I'll create it myself, don't bother.
