### ISSUE TITLE
Prayer against enemies (ወሶበ፡ ይሬእዩ፡ ኵሎሙ፡ ገበርተ፡ ዓመፃ፡) in BLorient12859

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2644]
I found a prayer in **BLorient12859**. At the moment, I do not know, what to do with it.
```

<msItem xml:id="ms_i15">
                            <title ref="LIT0000000000000000000000000000">Prayer against enemies</title>
                            <note>The text is written in the first or second column under the eleventh picture.</note>
                            <incipit xml:lang="gez">ወሶበ፡ ይሬእዩ፡ ኵሎሙ፡ ገበርተ፡ ዓመፃ፡ ይባዕ፡ ውስተ፡ ልቦሙ፡ ፍርሀት፡ ወረዓድ፡ ዘአንስት፡ <gap reason="ellipsis"/>
                                ከማሁ፡ አጽልሞሙ፡ ወአእዑር፡ አዕይንቲሆሙ፡ ወአብህም፡ አፉሆሙ፡ ለአረሚ፡ ወለኵሎሙ፡ ገበርተ፡ ዓመፃ፡ እለ፡ ይመጽኡ፡ ኀቤየ፡ ለቀቲለ፡ ሰብእናየ፡ ሊተ፡ ለገብርከ፡
                                </incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```

The beginning is possibly an allusion to [Psalm 92:7](https://www.ethiopicbible.com/books/%E1%88%98%E1%8B%9D%E1%88%99%E1%88%A8-%E1%8B%B3%E1%8B%8A%E1%89%B5-92): ሶበ ይበቍሉ ኃጥኣን ከመ ሣዕር ወይሠርጹ ኵሎሙ ገበርተ ዐመፃ፤ "When the wicked spring as the grass, and when all the workers of iniquity do flourish" 

There is a number of LIT IDs that contain prayers against enemies, but they do not have enough information or access to images. So I cannot link any of them. A recent server outage is preventing me from continuing my search.

Is it reasonable to create another LIT ID for this prayer?

@eu-genia @nafisa-valieva @karljonaskarlsson

**Comment by nafisa-valieva** [comment]
I agree with a new LIT ID! Thank you!

**Comment by eu-genia** [comment]
ok
