### ISSUE TITLE
Prayer against enemies (ይትኃፈሩ፡ ወይኅሰሩ፡ ኵሎሙ፡ ጸላእትየ፡) in BLorient12859 and BMLor403

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2646]
@eu-genia @nafisa-valieva @karljonaskarlsson 

I found a prayer against enemies in BLorient12859, that I did not find in the existing LIT records. I want to create a new LIT ID.

```
<msItem xml:id="ms_i18">
                            <title ref="LIT0000000000000000000000000000">Prayer against enemies</title>
                            <note>The text is written in the fourth column under the eleventh picture.</note>
                            <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ይትኃፈሩ፡ ወይኅሰሩ፡ ኵሎሙ፡ ጸላእትየ፡ እለ፡ ይመክሩ፡ እኵየ፡ ላዕሌየ፡</incipit>
                            <textLang mainLang="gez"/>
                        </msItem>
```
I found a strong correlation in BMLor403 in ms_i2 on f. 77r:

<img width="159" alt="Screenshot 2024_BMLor403" src="https://github.com/user-attachments/assets/18a635b4-f137-4332-8043-0d98301fded8">

It is in fact part of a larger collection of prayers described by Marrassini 1987 (p. 69) as 'Preghiera per rifugiarsi nei nomi divini' (= Prayer for Refuge in the Divine Names), coded as LIT4310Prayer in BMLor403. Both Marrassini and the Bm cataloguer (which was me) did not discover that this long passage consists of 24 different prayers on different subjects, each beginning with ʾO-ʾƎgziʾo (incipit different in BLorient12859).

```
<msItem xml:id="ms_i2">
                                <locus from="49r" to="78v"/>
                                <title ref="LIT4310Prayer"/>
                                <incipit xml:lang="gez">በስመ፡ አብ፡ ወወልድ። ወመንፈስ፡ ቅዱስ፡ አሐዱ፡ አምላክ። ስብሐት፡ ወጸሎተ፡ ወወድሶ፡ ወመለኮት፡ ወተማኅፀኖ፡ በአስማተ፡
                                    ለስርየተ፡ ኃጢአት። ኦእግዚኦ፡ እግዚአ፡ አነኒ፡ ተማኅፀንኩ፡ በዝንቱ፡ ዘዚአከ፡ በአስማት። አሌፍ። ካፍ። ከዋፍ። ኤፍ።</incipit>
                                <explicit xml:lang="gez">አንተ፡ ውእቱ፡ ክረምት፡ ወሐጋየ፡ ለከ፡ ስብሐት፡ ወአኰቴት፡ በምድር፡ ወበሰማይ፡ ለእግዚእየ፡ ወአምላኪየ፡ ኢየሱስ፡ ክርስቶስ።
                                    ኵሎ፡ ጊዜ፡ ይእዜኒ፡ ወዘልፈኒ፡ ወለዓለመ፡ ዓለም፡ አሜን። ወአሜን። ለይኩን፡ ለይኩን።</explicit>
                            </msItem>
```

I propose to create a new LIT ID for the text in BLorient12859 and update the record of BMLor403. 

There is another coincidence or similarity in the explicit of a chapter of Wǝddāse Māryām, which is attested in BAVet83 (ይትኃፈሩ፡ ወይኅሰሩ፡ ኵሎሙ፡ ጸላእትየ፨). I think, that this coincidence is accidental and not strong enough to establish a dependency.

```
                        <msItem xml:id="ms_i1.5.1">
                           <locus from="58vb" to="64rb"/>
                           <title type="complete" ref="LIT2505Weddas#FridayShenute"/>
                           ...
                           <explicit xml:lang="gez">
                              ወተወክፈ፡ እግዚአብሔር፡ ጸሎትየ፨ ይትኃፈሩ፡ ወይኅሰሩ፡ ኵሎሙ፡ ጸላእትየ፨ ሊተ፡ ለገብርከ፡ ኤርምያስ፡ ወይግብኡ፡ ድኅሬሆሙ፡ ወይኅሠሩ፡ ፈድፋደ፡ ፍጡነ፨
                           </explicit>
                           ...
                        </msItem>
```

**Comment by karljonaskarlsson** [comment]
It sounds all good to me! Will you create separate sub-IDs for all 24 parts of LIT4310Prayer and encode a relation to the prayer in BLorient12859?

**Comment by CarstenHoffmannMarburg** [comment]
I want to create one new ID for the collection and sub-IDs for the 24 prayers, except for the last one, which is attested as well in BLorient12859 and for which I want to create a new sub-ID (as part of the collection) and a new ID on its own.

I do not find any relation to LIT4310Prayer. The incipit in the record is meager and not fitting to the text I found in Strelcyns description. The editions of Grébaut (1935) and Turaev (1909) are not available to me. The translations by Budge 1929 and Basset 1895 are either not at hand to me and possibly not sufficient to verify a dependancy.

**Comment by CarstenHoffmannMarburg** [comment]
I wanted to create a sub-IDs for each of the 24 prayers (except for the one, which is also attested in BLorient12859 and for which I wanted to create both a sub-ID as part of the collection and a new ID of its own).


Incipit from LIT4310Prayer:
ስብሓት፡ ወጸሎት፡ ወወድሶ፡ መለኮት፨ ወተማኅፅኖ፡ በአስማት፡ ለስርየተ፡ ኀጢአት። ኦእግዚኦ፡ አነኒ፡ ገብርከ፡ ተማኅፀንኩ፡ በዝንቱ፡ ዘዚአከ፡ አስማት፡ አሌፍ፨ ኤፍ፨ ካፍ፨

**Comment by eu-genia** [comment]
Sounds good
