### ISSUE TITLE
Collection of prayers of the prophets of the Old Testament (ወሶበ፡ ጸርሐ፡ ስመከ፡ ...) in BLorient12859 and Strelcyn 1949

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [BetaMasaheft/Documentation#2647]
@eu-genia @nafisa-valieva @karljonaskarlsson 

I found a collection of prayers from OT prophets in BLorient12859. Each one begins with ወሶበ፡ ጸርሐ፡ or ወሶበ፡ ጸርሐ፡ ስመከ፡ ... Similar prayers can be found in BnF d'Abb. 270, BnF d'Abb. 107 and BnF éth. 320 (for none of these manuscripts have records been made yet) as reported and edited by S. Strelcyn in 1949 (bm:Strelcyn1949PriereFalacha).

```
<msItem xml:id="ms_i19">
                            <title ref="LIT0000000000000000000000000000">Collection of prayers of the prophets of the Old Testament</title>
                            <note>The text is written under the twelfth and thirteenth pictures. Each prayer begins with 
                                <foreign xml:lang="gez">ወሶበ፡ ጸርሐ፡</foreign> (engl. "When he cried") or 
                                <foreign xml:lang="gez">ወሶበ፡ ጸርሑ፡</foreign> (engl. "When they cried") and is often continued with 
                                <foreign xml:lang="gez">ስመከ፡</foreign> (engl. "your name").</note>
                            <msItem xml:id="ms_i19.1">
                                <title ref="LIT000000000000000000000000">Prayer of Moses</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ሙሴ፡ ገበርከ፡ እንዘ፡ ይብል፡ ጋዲን፡ ፈሊዖ፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.2">
                                <title ref="LIT000000000000000000000000">Prayer of Joshua</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ኢያሱ፡ ወልደ፡ ነዌ፡ ውስተ፡ ሀገረ፡ ገባዖን፡ እንዘ፡ ይብል፡ ደርታን፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.3">
                                <title ref="LIT000000000000000000000000">Prayer of Elijah</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ኤልያስ፡ ስመከ፡ እንዘ፡ ይብል፡ አቅርያኖስ፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.4">
                                <title ref="LIT000000000000000000000000">Prayer of Daniel</title>
                                <incipit xml:lang="gez">ወሶበ፡ <supplied reason="omitted" resp="PRS8999Strelcyn">ጸርሐ፡ </supplied>ዳንኤል፡ ስመከ፡ እንዘ፡
                                    ይብል፡ ዝራኤል፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.5">
                                <title ref="LIT000000000000000000000000">Prayer of Manasseh</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ምናሴ፡ ስመከ፡ እንዘ፡ ይብል፡ ቀለኤል፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.6">
                                <title ref="LIT000000000000000000000000">Prayer of the Three Children</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሑ፡ አናንያ፡ ወአዛርያ፡ ወሚሳኤል፡ እንዘ፡ ይብሉ፡ ዳፋኤል፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.7">
                                <title ref="LIT000000000000000000000000">Prayer of David</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ስመከ፡ ዳዊት፡ እንዘ፡ ይብል፡ በለማዊፒሲል፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.8">
                                <title ref="LIT000000000000000000000000">Prayer of Ezekiel</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ሕዝቅያስ፡ ስመከ፡ እንዘ፡ ይብል፡ ወገላውዮስ፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.9">
                                <title ref="LIT000000000000000000000000">Prayer of Jonah</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ስመከ፡ <sic>ዳዊት፡</sic> ዮናስ፡ እንዘ፡ ይብል፡ ዳላዊ፡</incipit>
                                <textLang mainLang="gez"/>
                            </msItem>
                            <msItem xml:id="ms_i19.10">
                                <title ref="LIT000000000000000000000000">Prayer of Jeremiah</title>
                                <incipit xml:lang="gez">ወሶበ፡ ጸርሐ፡ ኤርምያስ፡ ስመከ፡ እንዘ፡ ይብል፡ <gap reason="ellipsis"/> ገደላፊል፡</incipit>
                                <note>Cf. S. Strelcyn, Sur une prière falacha publiée par C. Conti Rossini, RSE 8 (1949), pp. 63 sqq.</note>
                                <textLang mainLang="gez"/>
                            </msItem>
                        </msItem>
```

I would like to create a LIT ID for the collection with sub-IDs for the prayers attested in BLorient12859 and in BnF d'Abb. 270, BnF d'Abb. 107 and BnF éth. 320 as edited in Strelcyn 1949. As far as I can see, there is not record for these prayers, yet.

**Comment by eu-genia** [comment]
if this is a BE collection maybe it can be left for @SophiaD-M if she thinks this is among the mss of her interest; 

my guess is that this is extracted (?) from the `[LIT1828Mahale](https://betamasaheft.eu/works/LIT1828Mahale/main)`, and then we already have CAe IDs for all these Old Testament prayers

**Comment by CarstenHoffmannMarburg** [comment]
If I understood Strelcyn correctly, this is a genuinely Christian text, that was redacted for Beta ʾƎsraʾel in some manuscripts.

**Comment by eu-genia** [comment]
Such is the situation of nearly all Beta Esrael texts. The most widely copied BE text is the Psalter. So are the prayers of the prophets of the Old Testament.

**Comment by karljonaskarlsson** [comment]
I'm not sure it is extracted from LIT1828Mahale – if I remember correctly, there is no Canticle based on Joshua or Elijah. To me, it seems like this collection deserves a LIT ID, but whether it is better left for @SophiaD-M I cannot say

**Comment by eu-genia** [comment]
You are right, some prayers at least have been added. 
Then indeed it makes sense to create a new CAe ID for the collection, possibly with an indication that these may be connected to LIT1828Mahale and at least some of its parts to the single canticles (LIT2277salotu, LIT2265salota, LIT2250salota etc)

**Comment by SophiaD-M** [comment]
ear all,
it would cost me too time and energy at the moment to look into these texts and how they are connected. That is research that needs to be done, and I hope to do that in the future, but right now I have no time for that. 
Would it be possible simply to postpone this matter -- and others like it involving BE material -- until I can hopefully get to it in the course of my own project?

**Comment by SophiaD-M** [comment]
Dear all,
Thank you for the discussion.
It would cost me too time and energy at the moment to look into these texts and how they are connected. That is research that needs to be done, and I hope to do that in the future, but right now I have no time for that.
Would it be possible simply to postpone this matter -- and others like it involving BE material -- until I can get to it hopefully in the course of my own project?

**Comment by eu-genia** [comment]
I suggest that @CarstenHoffmannMarburg , if not already done, creates the CAe ID(s), and we can get back to this when we have more research
