### ISSUE TITLE
locus with facs

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#324]
locus with facs handles only full numbers, no r and v distinctions.
needs to do a better calculation taking those into account

**Comment by PietroLiuzzo** [comment]
```xml
<locus from="205v" to="206r" facs="f424"/>
```

**Comment by thea-m** [comment]
are you sure this is the same case as #386? All loci there have r and v distinctions, but the links do work for some

**Comment by PietroLiuzzo** [comment]
yes, is a different issue, but it might have been related, so I linked it.

**Comment by PietroLiuzzo** [comment]
for vatican library now the accounting is done correctly

**Comment by PietroLiuzzo** [comment]
for bnf now the counting is correct

**Comment by PietroLiuzzo** [comment]
also for our mss it should be correct, but there is no annotation to test.

**Comment by PietroLiuzzo** [comment]
digivatlib not loading tiles in openseadragon modal

**Comment by PietroLiuzzo** [comment]
yep, digivatlib just moved to https. I have added the s and now all works
