### ISSUE TITLE
Synthax View of Manuscript with relative date

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#327]
Do we have a way of indicating the relative dates of msParts, other than in notes stating "msPart2 was sewn later into the manuscript"? I could not find examples in the guidelines.
See for example BDLaethe8, were no msPart has an internal date and the dating is uncertain, but msPart 1 and 2 were added later to the manuscript. 
This would also be theoretically a nice information for the timeline, but as the information is encoded now (and there are no exact dates anyway), it cannot of course be visualized
(or is the date indicated by the numbering of the msParts? I just followed the order in which they are listed in the catalogue)

**Comment by eu-genia** [comment]
each msPart has its own physical description, with all dates specified there

**Comment by eu-genia** [comment]
check e.g. ESaqg006 or BLorient490

**Comment by eu-genia** [comment]
the composite ms has the following structure inside `<msDesc>`

`<msContent>` for the entire thing with the <summary/> tag (otherwise you will only have summaries of parts)
`</msContent>`
`<physDesc>` for the entire thing, only for things that are valid for the whole thing
`</physDesc>`
`<history>` for the entire thing, with origDate if valid for the entire thing, and provenance
`</history>`
`<additional> `for bibl etc
`</additional>`

then `<msPart1>` begins, with `<msIdentifier>`, `<msContents>` (full this time), `<physDesc>` for what applies to msPart1, `<history>` for what applies to msPart1, etc.

same repeats for `<msPart2>`

each msPart is treated as complete separate manuscript descriptions inserted in a general manuscript description

**Comment by eu-genia** [comment]
but of course if no date can be anyhow estimated I see the point, there is no way to formalize the information to visualize the relative manuscript history. maybe we need some @type things for "primary stratum" "secondary stratum" - as the sequence of msParts is not really chronological, we normally rather arrange them in the order of leaves but then the second Part inserted later may have actually been produced earlier

**Comment by eu-genia** [comment]
on thinking it over we do need 2 distinct relative dating possibilities: for writing and for inserting. (distinguishing between "newer" msParts with "newer" texts and "newer" msParts with "older" texts). 
so maybe a @type to msPart but also some sort of relative creation date when no years/centuries can be provided.

and - we also need to mark the "additiones" somehow as some are more or less contemporary with the text, or even by the same hand i.e. part of the original project (like glosses etc), some added later, some even later - when we can we link them to the respective hands (as pointed out by Dorothea in another issue) but this is not the same as specifying the chronology of the layers. (see also the article by Andrist in the latest COMSt Bulletin issue). maybe also in this case we can use the "strata" references. 

maybe there is a way to create IDs also for the stages/layers in the life of the manuscript (maybe under `<history>` of the general `<msDesc>`) and then point to these IDs from msParts and from additions?

**Comment by PietroLiuzzo** [comment]
we had an issue, which has been moved to a requirement (these unknown...) 
https://github.com/SChAth/ScAthiop/issues/161
about implementing this and we certainly still need a nice example to work with: can this be the one? then we need for this a bit of thinking before we make the many changes required to the schema. is the english version of the synthax du codex out?

**Comment by thea-m** [comment]
In this case, p1 and p2 were added later to p3, but that's the only information I can get from the catalogue, so it is not clear whether they were added at the same time or not - not sure whether it would be a good example?
(The English translation isn't out yet, as far as I can see)

**Comment by PietroLiuzzo** [comment]
it is a good minimal example. we need to sit down with the book in hands and study this case plus do some testin. next week?

**Comment by PietroLiuzzo** [comment]
- [ ] confirm encoding of relative date
- [ ] map Synthax to TEI
- [ ] produce visualization as in book

**Comment by PietroLiuzzo** [comment]
Instead of encoding the relative date, the approach here will be to use la synthax du codex as ontology and define according to its terminology what happened. this case seams to me a Model A1 of transformation.

**Comment by PietroLiuzzo** [comment]
(requirement NAV3)[NAV3]

**Comment by PietroLiuzzo** [comment]
this is solved by the SdC ontology encoding and RDF visualizations in 3.0

**Comment by eu-genia** [comment]
this was the example i meant for relative dates

**Comment by PietroLiuzzo** [comment]
@eu-genia I am giving you [here](https://github.com/BetaMasaheft/Documentation/wiki/NAV3#example-1-bdlaethe8)  a more precise link than the one above, where you can find an example of how this could be treated.

**Comment by PietroLiuzzo** [comment]
As discussed yesterday properties like "is earlier than" can be added. e.g. crm:P120_occurs_before
