### ISSUE TITLE
manuscript file names without a numeric part

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#340]
because of the way the url rewriter works now please use ids for your manuscripts which include a numeric part. 

EndaEndreyasSenodos is not ok, EndaEndreyasSenodos1 yes.

If it is not urgent to see this files in the preview app, you can wait that I update the controller which should not take long.

**Comment by eu-genia** [comment]
i can wait :)

**Comment by PietroLiuzzo** [comment]
this is not anymore an issue
