### ISSUE TITLE
scroll descriptions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#372]
from discussions with @DenisNosnitsin1970 
It would be desirable to be able to include the following aspects in the description of scrolls:
1. as no folio numbers exist, the location of items could be indicated by line number (if the information is provided - not the case until now in our manuscripts)
1. one should differenciate between (smaller) scrolls made for personal use and (larger) scrolls made for hanging up in houses. The difference lies in the size and number of parchment strips sewn together, but could the kind of scroll also be indicated explicitely somewhere? 
1. If the information is available (not until now either...) the length of the single parchment strips and the location of the seam where they are sewn together could be indicated (if transcribing the scroll this would also needed to be indicated in the text transcription)

**Comment by PietroLiuzzo** [comment]
1. yes, if there are such lines and they have an id. the current reference with existing msItem or msPart ids is fine. if more precise indication are needed they can be added in writing and than later (once text is added) better referenced, rather than omitting them for lack of pointers. 
2. the 17 scrolls http://betamasaheft.aai.uni-hamburg.de/manuscripts?support=Scroll I would suggest using a simple paragraph inside support desc, unless a formal typology is what you are asking here. 
3. yes, the indication of the seam in the text transcription would be ok IMHO. length can be already given in extent/dimension 

We would indeed need an encoded example and I would submit this to the TEI list to see if there are suggestions.

**Comment by thea-m** [comment]
for point 2:
Would a description like this be fine, @DenisNosnitsin1970 (and is the assumption actually correct?) ? From BDLaethf6

```xml
         <extent>
                           <dimensions type="outer" unit="in">
                              <height>52.5</height>
                              <width>4.63</width>
                           </dimensions>
                           <note>Consists of two strips stitched together and was probably produced for personal use.</note>
                        </extent>
```

**Comment by thea-m** [comment]
Could you check and close the issue if it is fine, @DenisNosnitsin1970 ?

**Comment by DenisNosnitsin1970** [comment]
Is there a technical possibilty to formalize the information on the number of strips? It is important.

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970, you could use `<measure>` with  `@unit="strips"` around the word two or make that into a numeric value instead of a string

> consist of `<measure unit="strips">two</measure> ` strips stitched

or 

> consist of `<measure unit="strips">2</measure> ` strips stitched

I am not sure if there might be something relevant in the work @ElianaDalSasso has done in the last months

**Comment by ElianaDalSasso** [comment]
I must admit that I don't know very much about scrolls. Are the strips always stitched or can be also glued together?Can it be relevant differentiate this feature?

**Comment by DenisNosnitsin1970** [comment]
No, they are not glued together. They are stitched together by means of narrow strips of parchment/leather  led through slits.

**Comment by ElianaDalSasso** [comment]
Thank you for the information!

**Comment by thea-m** [comment]
@DenisNosnitsin1970 , are you fine with the solution proposed by @PietroLiuzzo  ?
To close this issue, it would be good to work with an example. Is there any scroll whose images are available to us that would be appropriate for such a purpose?

**Comment by thea-m** [comment]
I don't think we have examples yet, but I will work on a scroll sometime in the next weeks, maybe we can use that one then as an example

**Comment by PietroLiuzzo** [comment]
sounds like a good plan. thanks

**Comment by Gnisci** [comment]
> one should differenciate between (smaller) scrolls made for personal use and (larger) scrolls made for hanging up in houses. The difference lies in the size and number of parchment strips sewn together, but could the kind of scroll also be indicated explicitely somewhere?

I think this is a bit arbitrary. Recording the size, on the other hand, is objective.

@thea-m I could send you the images of the scrolls in the Bodleian?

**Comment by thea-m** [comment]
It seems like we have agreed in this issue to use  `<measure unit="strips">` to indicate the number of strips of a scroll, which has been already documented in the guidelines. Since I am working on an example now, I will close this issue, which groups several different questions, and will open individual issues with concrete examples when the need arises.
