### ISSUE TITLE
summary display BNFet112

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#382]
in the "extracted summary of contents" list of BNFet112, the labels of the textparts of LIT1586Hayman referenced in the titles of ms_i1.18 to ms_i1.21 are not displayed, instead their xml:ids are displayed.
I can't find a difference between them and the other textparts whose labels are displayed correctly

**Comment by PietroLiuzzo** [comment]
inside label you can put what you want in terms of title ref and persName. You can see this displayed in the text of any work with divs. However it is not currently possible to display this in the summary of manuscripts as there it produces out of sync calls to the api: it calls the title of that part of work, which contains a call to another work for example and this is not triggered. I do not have at the moment an idea to fix this.

**Comment by PietroLiuzzo** [comment]
this issue does not exist anymore
