### ISSUE TITLE
dates in zotero style

### ISSUE THREAD

**Issue by FrancescaPanini** [BetaMasaheft/Documentation#398]
- [x] https://www.zotero.org/paninif/items/itemKey/NHE2A4H4
Lepage, C. and J. Mercier 2011. ‘Un tétraévangile illustré éthiopien à cycle long du XVe siècle. Codicologie et iconographie’, Cahiers Archéologiques, 54 (2011), 99–174.

Come dovrebbe venire:
Lepage, C. and J. Mercier 2011–2012. ‘Un tétraévangile illustré éthiopien à cycle long du XVe siècle. Codicologie et iconographie’, Cahiers Archéologiques, 54 (2011–2012), 99–174.

Citazione:
Lepage, Mercier 2011–2012

***
- [x] https://www.zotero.org/paninif/items/itemKey/93NA4M8Q
Märsǝʿe Ḫazän Wäldä Qirqos 2007. የሐያኛዉ ክፍለ ዘመን መባቻ (Yäḥäyaňawu Kǝflä Zämän Mäbača) (Addis Ababa: Addis Ababa University Press, 2007).

Come dovrebbe venire:
Märsǝʿe Ḫazän Wäldä Qirqos 2006/2007. የሐያኛዉ ክፍለ ዘመን መባቻ (Yäḥäyaňawu Kǝflä Zämän Mäbača) (Addis Ababa: Addis Ababa University Press, 1999 EC = 2006/2007 CE).

Citazione:
Märsǝʿe Ḫazän Wäldä Qirqos 2006/2007

***
- [x] https://www.zotero.org/paninif/items/itemKey/I582VUHN
Chojnacki, S. 1976. ‘The Four Living Creatures of the Apocalypse and the Imagery of the Ascension in Ethiopia’, Bulletin de la Société d’archéologie Copte, 23 (1976), 159–181.

Come dovrebbe venire:
Chojnacki, S. 1976–1978. ‘The Four Living Creatures of the Apocalypse and the Imagery of the Ascension in Ethiopia’, Bulletin de la Société d’archéologie Copte, 23 (1976–1978, pub.1981), 159–181.

Citazione:
Chojnacki 1976–1978

**Comment by eu-genia** [comment]
non c'è verso, l'unica soluzione è mettere 1976_1978 e poi correggere a mano

**Comment by PietroLiuzzo** [comment]
let me look at it once more, there is always hope, I can do much more than I was able to do last year when this question was first asked.

**Comment by PietroLiuzzo** [comment]
The way I am tackling this is simply to offer a javascript based brute force conversion which will produce a formatted bibliography note and citation based on a unique tag pointing to a record in the EthioStudies group library.

**Comment by PietroLiuzzo** [comment]
Ethiopian Calendar date should be entered in extra as "EC 1999"

**Comment by PietroLiuzzo** [comment]
also pub. date should be entered in extras as "pub. 1981"

**Comment by PietroLiuzzo** [comment]
a stand alone jquery brute force transformation can be tested at 

http://betamasaheft.aai.uni-hamburg.de/betterzotero.html

it is very probable that it does not work much further than these three records. have a go if you want and let me know what you would need.
the workflow improvement here would be only that identified records requiring editing can be produced here and copied in the bibliography where the HLCES does not satisfy 100%. I do not know if this is more practical than simply editing the output of the style. Test and let me know.
