### ISSUE TITLE
msFrag encoding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#399]
I have changed the records mentioned in #368  and #369  to contain `<msFrag>`. As we have not previously used this, it would be kind if you could have a look at them, so that I can add the encoding of `msFrag` to the guidelines. I had several issues while encoding:

-  Identifier: The shelfmarks are the identifiers of the respective msFrags, but what should be the identifier of the record as a whole? I have added the msFrags to BNFet45 and BDLaethf11 and left those identifiers for now as they are, but this is of course not precise.
- should, in the case of BDLaethf11 and BDLaethf12, the individual records remain as they are and a new record be created for the msFrag? or should only one (msFrag) record exist and the others be deleted?
- as for composite manuscripts I added all contents of `<physDesc>`, including `<handDesc>`, and `<history>` that apply to all fragments at the top of the records and only added those applying only to one fragment in the description of the `<msFrag>` in question (namely, `<decoDesc>`)
- I gave the fragments xml:ids (f1, f2) and used these IDs in the description of the msItems

Thanks for your help!

**Comment by eu-genia** [comment]
for the BNFet mss -BNFet45 has the identifier as is, and the missing fragment must have something like BNF et 165 part 4 as identifier 
the BDLaeth scrolls are a bit different - there the first question is whether bdlaeth 11 and 12 get individual descriptions at all or only described as msfrags
In any case there should be one "invented" virtually reconstructed ms with an idn BDL aeth 11+12 which consists of the two fragments
Fragments are not identical with msParts as these are truly independently existing manuscripts which we only virtually put together. So if 11 and 12 do NOT get individual descriptions but are only msFrag then they should have complete descriptions each, unlike composite mss, as they are independently circulating units even now

**Comment by PietroLiuzzo** [comment]
#368 #402

**Comment by PietroLiuzzo** [comment]
this situation is described in La Synthax du codex as MA1. it will be encoded relationally with properties and classes from the ontology.
ideally we will have in BNFet45
````xml
<listRelation>
            <relation active="BNFet45#UniCirc1" name="dcterms:hasPart" passive="BNFet45#p1 BNFet45#f2"/>
            <relation active="BNFet45#UniCirc1" name="SdC:undergoesTransformation" passive="BNFet45#tr1"/>
            <relation active="BNFet45#tr1" name="SdC:hasTransformationModel" passive="SdC:D2"/>
            <relation active="BNFet45#tr1" name="SdC:produces" passive="BNFet45#UniCirc2"/>
            <relation active="BNFet45#tr1" name="SdC:produces" passive="BNFet45#UniProd1"/>
            <relation active="BNFet45#tr1" name="SdC:isPartOfTransformation" passive="BNFet45#tr3"/>
            <relation active="BNFet45#UniCirc2" name="dcterms:hasPart" passive="BNFet45#p1"/>
            <relation active="BNFet45#UniCirc2" name="skos:exactMatch" passive="BNFet45"/>
            <relation active="BNFet45#UniProd1" name="dcterms:hasPart" passive="BNFet45#f2"/>
            <relation active="BNFet45#UniProd1" name="SdC:undergoesTransformation" passive="BNFet45#tr2"/>
            <relation active="BNFet45#tr2" name="SdC:hasTransformationModel" passive="SdC:A4"/>
            <relation active="BNFet45#tr2" name="skos:exactMatch" passive="BNFet165#tr1"/>
            <relation active="BNFet45#tr2" name="SdC:isPartOfTransformation" passive="BNFet45#tr3"/>
            <relation active="BNFet45#tr3" name="SdC:hasTransformationModel" passive="SdC:MA1"/>
         </listRelation>
`````
and in BNF et 165

````xml
<listRelation>
           <relation active="BNFet165#UniCirc1" name="dcterms:hasPart" passive="BNFet165#p1 BNFet165#p2 BNFet165#p3 BNFet165#p5 BNFet165#p6"/>
           <relation active="BNFet165#UniCirc1" name="SdC:undergoesTransformation" passive="BNFet165#tr1"/>
           <relation active="BNFet165#tr1" name="SdC:hasTransformationModel" passive="SdC:A4"/>
           <relation active="BNFet165#tr1" name="SdC:isPartOfTransformation" passive="BNFet45#tr3"/>
           <relation active="BNFet165#tr1" name="skos:exactMatch" passive="BNFet45#tr2"/>
           <relation active="BNFet165#tr1" name="SdC:produces" passive="BNFet165#UniCirc2"/>
           <relation active="BNFet165#UniCirc2" name="dcterms:hasPart" passive="BNFet165#p1 BNFet165#p2 BNFet165#p3 BNFet165#p4 BNFet165#p5 BNFet165#p6"/>
           <relation active="BNFet165#UniCirc2" name="skos:exactMatch" passive="BNFet165"/>           
           <relation active="BNFet165#p4" name="skos:exactMatch" passive="BNFet45#f2"/>
        </listRelation> 
````

**Comment by PietroLiuzzo** [comment]
the case of BDLaethf11 and BDLaethf12 is also one where we should use this kind of relational encoding.
also, both of them should be encoded with msPart, as they are not reconstructed manuscript at any stage, they represent the current Circulation Units with a transformation model D3.

**Comment by PietroLiuzzo** [comment]
see nav3
