### ISSUE TITLE
authority files to contain all values in schema

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#405]

**Comment by PietroLiuzzo** [comment]
@thea-m @MassimoVilla @sologebre @eu-genia anyone up for a check of some values in the schema agains the guidelines and authority files?

what is in the schema should be in the guidelines as well and where it is in fact a keyword should have an authority file record as well and a position in the taxonomy.

**Comment by thea-m** [comment]
added the values for `<del @rend>` and `<add @place>` to the text encoding table in the guidelines:
https://github.com/SChAth/ScAthiop/wiki/guidelines#text-encoding

**Comment by thea-m** [comment]
The keywords seem all fine

**Comment by PietroLiuzzo** [comment]
@thea-m @MassimoVilla @sologebre  @DenisNosnitsin1970
can one of you please self assign this issue, confirm it is done and close it? thanks
