### ISSUE TITLE
Estimated dating of the MS

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#415]
When referring to the dating of the manuscript, we generally adopt that of the cataloguer(s), but other proposals might have been done by other scholars. In these cases, when we have two competing opinions, we need to specify the source of the estimation.
The following example is taken from BAVet43. Here we have a broader dating made by Grébaut and Tisserant (16-17th cent.) and a "narrow" proposal made by Conti Rossini (second half of the 16th century).

`   <origDate notBefore="1540"   notAfter="1699">
                        <note>
                           Date according to <bibl><ptr target="bm:GrebTiss1935Codices"/>
                           <citedRange unit="page">187-190</citedRange></bibl>. 
                           </note>
                     </origDate>
                     <origDate notBefore="1550"   notAfter="1599">
                        <note>Date according to <bibl><ptr target="bm:ContiRossini1927Inediti"/>
                           <citedRange unit="page">516</citedRange></bibl>.</note>
                     </origDate>`

Here I encoded the bibliographic reference within `<note/>` but other solutions are possible.
Is it worth repeating the bibliographic reference to the catalogue, which also appears by default in the `<source/>` section down in the file?
Alternatively, we might only add the person ID: ` <origDate notBefore="1540"
                              notAfter="1699"
                              resp="PRS4805Grebaut PRS9530Tisseran"/>`.
The same question also affects the paleographical description. 
Both Dorothea and I think that a standardized way to deal with such cases is required.

**Comment by eu-genia** [comment]
Agree we need a standardized way. 
Cp. also #320  
As discussed at that point with @thea-m  `resp="PRS..."` does not always work very neatly as the same person may have provided varying dates/opinions in different publications/years, so the reference preferably should be to the source of information not to a person

**Comment by PietroLiuzzo** [comment]
any of these methods is fine. I would consider having both bibliographical reference AND resp in `origDate` as these are two distinct informations

**Comment by thea-m** [comment]
Shall we agree on encoding this as in the first example provided by @MassimoVilla 
(`<note>` containing the bibliographical reference)? For the sake of clarity, I would be in favour of repeating the bibliographical reference of the catalogue if an alternative date is also given, not of course if its date is the only one proposed

**Comment by thea-m** [comment]
Added to the guidelines:

It is possible to add more than one `<origDate>` if alternative datings for the manuscript are provided in the catalogue or literature. In these case the source for each date should be specified in a `<note>` inside the respective `<origDate>`. The person responsible for the dating can be indicated with @resp inside `<origDate>`:

```xml
<origDate notBefore="1540" notAfter="1699" resp="PRS4805Grebaut PRS9530Tisseran"> 
<note> Date according to <bibl><ptr target="bm:GrebTiss1935Codices"/> <citedRange unit="page">187-190</citedRange></bibl>. </note> 
</origDate> 
<origDate notBefore="1550" notAfter="1599" resp="PRS3182ContiRo"> 
<note>Date according to <bibl><ptr target="bm:ContiRossini1927Inediti"/> <citedRange unit="page">516</citedRange></bibl>.</note> 
</origDate>
```

Please re-open and edit if you disagree
