### ISSUE TITLE
Search for parts of IDs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#420]
Is it possible to search for a part of an ID? 
I wanted to quickly find the ID of Répertoire Chaine 185 (LIT2904RepCh185) but didn't manage to - this is something that is very easy with the spreadsheet.

**Comment by PietroLiuzzo** [comment]
I have started a not yet working stab to this in the advanced search. you would like this in the same search or in a separate input?

**Comment by thea-m** [comment]
In the same search I think. 
Until now, this really would be useful (for me at least) only for the répertoire Chaine records - so I don't know if it's worth spending much time on it, as I can just use the spreadsheet to find them

**Comment by PietroLiuzzo** [comment]
you cannot know if somebody has deleted those or changed those in the spreadsheet. as you know I have to advise you against it. it is a usefull function to have, so no waste of time!

**Comment by PietroLiuzzo** [comment]
#565 this could be done with the util:indexkeys. not sure. the current

**Comment by PietroLiuzzo** [comment]
The new lookup for ID in the as.html will allow to enter any part of an ID and add that parameter to the search. it can also be used alone.
