### ISSUE TITLE
settling of the review process

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#428]
What happens when a file is ready for review? and final publication? currently these are the guidelines
https://github.com/SChAth/ScAthiop/wiki/workflow
this can be much improved with a backend for review of the contents and a system to notify for review, etc. github branches and pull requests with review could be fruitfully used.

**Comment by abausi** [comment]
We will have to discuss this during the meeting.

Many thanks,

Alessandro

Il 08.05.2017 06:55, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
Here I have a done a test using the GitHub Flow https://github.com/SChAth/Institutions/pull/1

It isn't as straight forward as simple commit and sync, but allows for revision by reviewers and highlight of the changes only. 

It requires a bit of attention about what one is actually editing as well.

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/Institutions/pull/2 is a test of reviewed and non accepted change. this can be also sent with changes incorporated, so is definitely very very practical.

**Comment by PietroLiuzzo** [comment]
it was decided not to use pull requests, but it remains good practice. we will continue with the current informal process for the moment
