### ISSUE TITLE
Golden Gospel

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#460]
Do we have/need a standardized way to mark Golden Gospels?

**Comment by PietroLiuzzo** [comment]
no idea what these are. if they are manuscripts made of gold, please use <material/> in any of the places where our guidelines allow it according to the need, e.g. in binding.

**Comment by eu-genia** [comment]
no - this is a particular type of a manuscript - usually a main copy of the Four Gospels of a church - where documents (land charters, foundation charters, etc) concerning the place are collected.
maybe a keyword to add? or simply put it in the title? or a particular relationship between the MS and the institution? e.g. BL orient 518 e.g. is a Golden Gospel of Madhane 'Alam.

**Comment by abausi** [comment]
We could limit this use: (1) to the cases when the definition of "Golden Gospel" is explicitly mentioned somewhere in the Gospel (there are such cases); (2) when there is enough evidence that the Gospel is the main material repository of documentary texts related to a certain institution; this secon case remains to some extent arbitrary.

**Comment by PietroLiuzzo** [comment]
the manuscript has already a relation to the institution, the keyword would suffice. 

- [ ] create a new authority file
- [ ] update the taxonomy file with the reference organized correctly
- [ ] provide a definition and the value in the schema

**Comment by eu-genia** [comment]
i think the best would be a separate relation, so that also under the Institution we could have a visible box for the GG (s) of this institution (it can also happen that the GG manuscript is not (any more) in the institution of which it is the archive)
possibly a relation of the type "isGoldenGospelof" (with the definition that it can eventually also be applied to manuscripts that may contain other main text than the Gospel, if the second criterion (repository of documentary texts) is fully fulfilled)

**Comment by abausi** [comment]
i am afraid that there is a problem of feasibility: one should discuss to what extent the documents contained refer to what; it is quite common that documents are also mixed; we should then distinguish between (1) GG as containing documents and hosted in a certain place, when the MS is certainly considered nonetheless "the GG of X place", from (2) GG preserved in a different place from that to which its documents refer. A solution would be that of having: (a) GG as a generic attribute, to be tagged in any case; (b) GG of X (aside from the place where it is preserved), as a specific attribute that considers the institution to which the docs refer

**Comment by eu-genia** [comment]
agreed. a neutral keyword + a relation when a definitive relationship is clear.

**Comment by thea-m** [comment]
I have added the relation bm:isGoldenGospelof with the definition "The relation between a Golden Gospel and its original institution (even if the manuscript is now kept in a different place), to be used in cases where the definition of "Golden Gospel" is explicitly mentioned somewhere in the Gospel or when there is enough evidence that the Gospel is the main material repository of documentary texts related to a certain institution." to the schema. Please edit it if you disagree.
Not sure what to do to validate it, @PietroLiuzzo ?

**Comment by thea-m** [comment]
where should this relation be added to manuscript records? `<filiation>` doesn't seem to be the right place. In BLorient508, I added it to `<additions>`, which is where what characterizes the manuscript as a Golden Gospel has been encoded. Can I add this to the guidelines or is there a better place?

**Comment by PietroLiuzzo** [comment]
the guidelines already state that listRelation is allowed everywhere. I think this is enough, I would not overspecify something which can remain free. Or have you encountered limitations?

**Comment by thea-m** [comment]
no, it's ok

**Comment by PietroLiuzzo** [comment]
False, the guidelines did not state this, I stated it probably only in the issue. I have updated the guidelines. Thanks!
