### ISSUE TITLE
map drop down menu 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#463]
I just accidentally discovered the drop down menu on the top right corner of the map which allows to select the types of places shown - this is a very nice feature, could be it somehow be displayed in a clearer or more prominent way? 
Or maybe it is obvious to everyone but me

**Comment by PietroLiuzzo** [comment]
#561

**Comment by PietroLiuzzo** [comment]
useful links for layers and replotting
http://georeferencing.org/tools.html
https://openlayers.org/
https://www.davidrumsey.com/view/georeferencer
https://gis.stackexchange.com/questions/59571/how-to-add-text-only-labels-on-leaflet-map-with-no-icon

**Comment by PietroLiuzzo** [comment]
http://www.qgistutorials.com/it/docs/making_a_map.html

**Comment by thea-m** [comment]
is this still relevant, @PietroLiuzzo ?
