### ISSUE TITLE
why on earth is there a  class="content" in the newly created mss records???

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#464]

**Comment by PietroLiuzzo** [comment]
for some reasons I do not know, but thanks a lot to @thea-m who spotted that, there was in the template an attribute `@class` for `<msItem>` which should have not been there. I have removed it, but few instances should be fixed to remove this

https://betamasaheft.eu/xpath?xpath=%24config%3Acollection-rootMS%2F%2Ft%3AmsItem%5B%40class%3D%27content%27%5D

**Comment by PietroLiuzzo** [comment]
@DariaElagina  @smaugustine your records are affected by this issue, I can fix them for you at the next freeze, this is not a very urgent or concerning issue, and its cause has been fixed already, so, no worries.

**Comment by DariaElagina** [comment]
Dear @PietroLiuzzo , just let me know if it would be faster/ better for you if I fix the records myself

**Comment by PietroLiuzzo** [comment]
It takes probably longer to estimate the difference than to do the actual change! So, please, if you do not mind, just do that. The reason why I am not doing it straight away is that I am not sure if you are working on those files in a branch and I do not want to cause scary conflicts.
