### ISSUE TITLE
keyword box in record creation form

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#465]
It would make the use slightly easier if the keyword selection box were larger and showed more keywords at the same time

**Comment by PietroLiuzzo** [comment]
is this still an issue? the multiselect box as I see it is full width on the page

**Comment by PietroLiuzzo** [comment]
I have made this into a list of checkboxes.

![schermata 2017-11-15 alle 11 02 03](https://user-images.githubusercontent.com/508012/32830169-a83dbc10-c9f4-11e7-8b02-5a9665ca3c9f.png)

**Comment by thea-m** [comment]
thank you!
