### ISSUE TITLE
allow listRelation where needed and deprecate the use of listBibl[@type="relations"]

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#498]
the schema is already heavily tailored and this modification would actually make our files much cleaner, given the heavy usage of the relation element

**Comment by PietroLiuzzo** [comment]
- [ ] schema updated
- [ ] guidelines updated
- [ ] xslt and xquery in the app updated
- [ ] all data upgraded

**Comment by PietroLiuzzo** [comment]
@thea-m @eu-genia @MassimoVilla @sologebre @DenisNosnitsin1970 @abausi 
Dear all, this is a formal change which makes our XML tidier and it has implications for you. The use of listBibl[@type='relations'] is deprecated and you can instead use anywhere in the TEI file listRelation

**Comment by thea-m** [comment]
thank you!
