### ISSUE TITLE
missing link/reference to the works he wrote

### ISSUE THREAD

**Issue by SophiaD-M** [BetaMasaheft/Documentation#524]
PRS8746Semon

The box "This person is subject of the following works" is empty, please connect it if possible to the works this person was the author of.

**Comment by PietroLiuzzo** [comment]
I can add the function we spoke about to display a list of authored works. under see also you can already see what this record contains about this
http://betamasaheft.aai.uni-hamburg.de/analytic/PRS8746Semon

**Comment by PietroLiuzzo** [comment]
If information is present a box will show with this information.
