### ISSUE TITLE
persons

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#529]
there are several cases like 
http://betamasaheft.eu/persons/PRS11574Ekinedu.xml
where the normalized name is in the gez persName and the normalized is empty.
I think this is due to the way the app was creating new records. I would advise to go through those and fix them so that we do not have things like this
http://betamasaheft.eu/persons/list?per-page=63&start=11719&keyword=&date-range=&language=

there aren't that many.

some have also other strange things, please see for example:

http://betamasaheft.eu/persons/PRS11585Sawaryana.xml

a list of files affected is here, but do try other patterns as well:

http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fpersons%27%29%2F%2Ft%3ATEI%5Bdescendant%3A%3At%3ApersName%5B%40type%3D%27normalized%27%5D%5Bnot%28text%28%29%29%5D%5D%5Bdescendant%3A%3At%3ApersName%5B%40xml%3Alang%3D%27gez%27%5D%5D

**Comment by thea-m** [comment]
There are still many newly created records with this problem (for example PRS11765LaakaMaryam, PRS11731WaldaTensae and many more).
This can currently only be prevented by opening each newly created record and edit it manually (which is needed anyway if one wants to enter both fidal and transliteration or more information). 
Another solution would be to adapt the new person creation form so that both the name in fidal and transcription could be entered there.
@sologebre @DenisNosnitsin1970

**Comment by thea-m** [comment]
I corrected the records in question, but there are still records created recently which have this problem. Please remember to open all records created through the app and to edit them if necessary. If this workflow doesn't work for you or you would prefer the record creation form to be modified, please open a new issue. @sologebre @DenisNosnitsin1970 @eu-genia 

@PietroLiuzzo The records shown now by the search
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fpersons%27%29%2F%2Ft%3ATEI%5Bdescendant%3A%3At%3ApersName%5B%40type%3D%27normalized%27%5D%5Bnot%28text%28%29%29%5D%5D%5Bdescendant%3A%3At%3ApersName%5B%40xml%3Alang%3D%27gez%27%5D%5D
all don't exist anymore in oxygen. Is it somehow a problem that the search brings them up, or can this be ignored?

**Comment by PietroLiuzzo** [comment]
on my part of the assignment: those were erroneously non removed. I do not know when, but at a point when the github hook was not responsive which did happen. I took the occasion to test it again and it does work as expected. 
on the create record form: the app should be doing it ok now, isn't it?

**Comment by thea-m** [comment]
The app was always doing it ok...there is only one field for adding a title, whose content is then transferred to the record as content of `<title>` (where we agreed to have the transcribed version of n1) and of `<persName xml:lang="gez" xml:id="n1">` (where obviously we need fidal). So if one has added the transcribed name (which is what I usually do, I don't know about the others), one has to move it to `<persName xml:lang="gez" corresp="#n1" type="normalized">` and add the fidal to n1, and vice versa if one added the name in fidal in the app. For me this is no problem, as I prefer to open and edit the records immediately anyway, but I don't know if this works for everyone.

**Comment by thea-m** [comment]
I corrected the records

**Comment by thea-m** [comment]
There are again several newly created person which have   `<persName xml:lang="gez" type="normalized" corresp="#n1"/>`. Many of them also have names that are clearly not Geez, yet marked up as being so, for example PRS12701Marr or PRS12651Pishoy. 
Please, always either 1) Open all person (and other...) records that you are creating and check them before committing or 2) open an issue if it seems to you that the person creation form should be adapted to accomodate more common ways of entering data. 
Thank you!
