### ISSUE TITLE
overlapping 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#532]
a line from the contents section of BDLbruce77 (the title of ms_i1.1) is overlapping into "Extent"

**Comment by PietroLiuzzo** [comment]
I have chopped titles longer than 50 chars in the item buttons.

**Comment by thea-m** [comment]
the problem still persists, for example here:
http://betamasaheft.eu/manuscripts/FSUor13/main

**Comment by PietroLiuzzo** [comment]
this is now fixed by css, wrapping content of long titles called from the api inside the button.
