### ISSUE TITLE
alphabetic order of manuscript view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#536]
The view in http://betamasaheft.aai.uni-hamburg.de/manuscripts/list
lists mss alphabetically according to their location, with placenames starting with characters with diacritica at the end of the list. Would it be possible to list these placenames at the position of the alphabet where they would be if they had no diacritica? I.e. ʾAddis ʾAbabā under A, Ṣanʿāʾ under S etc.

**Comment by thea-m** [comment]
It would also be helpful if the list of repositories would be ordered alphabetically

**Comment by PietroLiuzzo** [comment]
Please note the latest [release 2.2 note](https://github.com/BetaMasaheft/BetMas/commit/55eb31f56acebc25cecad6e7e99bf59d783ccc5b). Alphabetical ordering has been given up as the main cause of the slowness in loading the lists.
