### ISSUE TITLE
select input menu too small

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#552]
In the advanced search, 
1. the select input menu for specific manuscripts is too small, which makes it impossible to see the complete shelfmarks and select a specific manuscript
1. The select input menus for various filters (i.e. specific work, scribe etc.) also sometimes pop up very late or twice (if one was impatient while waiting and selected the same filter again...)

**Comment by PietroLiuzzo** [comment]
1. if we change the requirement to search only one manuscript, and not multiple as it is now possible to search, this is an easy fix. please let me know.
2. This is true, especially with frequently changing data, but there is little I can do at the moment. I would instead suggest to specify in #561 that some selections might need users to wait a bit. I am adding a text to the selector now

**Comment by thea-m** [comment]
1. I think that searching for only one manuscript is enough, if one wants to search for several mss it would be possible to repeat the same search
2. This seems a good solution. However I am waiting since 8 minutes for the "specific manuscript" menu to open - is there something broken? the other filters did pop up

**Comment by PietroLiuzzo** [comment]
the function app:target-mss is not responding for some unidentifier reason.
if searching one manuscript is enough, then this function is not at all relevant and could be removed, because the id can be added in the id look up to the same effect of searching only in that item

**Comment by thea-m** [comment]
As the id look up can only be used by people who know how our ids are constituted, I still think that there would be a use for this function (though I personally would probably open the manuscript and then search for the information in the record).

**Comment by PietroLiuzzo** [comment]
indeed the user will have to go to a manuscript, copy the id and enter it in the search. is this so painful?

**Comment by PietroLiuzzo** [comment]
I have removed the checkbox. what will happen now is that once the repository checkbox is checked the list of repos will appear. selecting one will prompt a call to the api which will produce in filter.js a new from group after that of the repositories with the titles of the manuscripts from this repository. one or more manuscripts from this list can be choose. selectors are also bigger
