### ISSUE TITLE
add link

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#554]
Has the way to add a link been changed? In the guidelines, we have once:

> You can also use @target to point to external resources. In this case, please enter the full url, including http.

and once:

> `<ref type="mss" corresp="https://w3id.org/vhmml/readingRoom/view/133001">`

However, both methods don't lead to displayed links on the app (tried out in LIT1234Catena and d8 in BLorient718)

**Comment by PietroLiuzzo** [comment]
in BLorient718 the links are there as expected, but since there is no text, they are not visible.

**Comment by PietroLiuzzo** [comment]
updated guidelines

**Comment by PietroLiuzzo** [comment]
an empty `ref[@target]` will now display as default text [link]
