### ISSUE TITLE
Inconsistencies between HLZ style and Zotero extraction of bibliographic records

### ISSUE THREAD

**Issue by FrancescaPanini** [BetaMasaheft/Documentation#559]
Hello,
working with Zotero I noticed some discrepancies between what should be the HLZ style for bibliographic records (https://journals.sub.uni-hamburg.de/aethiopica/about/submissions#authorGuidelines) and the way in which Zotero extracts data.

# Editions and translations:
- [x] Eds (no dot) per editors
- [x] Tr. (not trans.) per translator
- [x] Position of tr. and ed.

## HLZ correct style:
Arras, V. 1963. Collectio monastica. Textus, ed., tr. V. Arras, Corpus Scriptorium Christianorum Orientalium, 238, Scriptores Aethiopici, 45 (Louvain: Secrétariat du Corpus SCO, 1963)

## Current extraction from Zotero:
Arras, V., ed., 1963. Collectio monastica. Textus, trans. V. Arras, Corpus Scriptorium Christianorum Orientalium, 238, Scriptores Aethiopici, 45 (Louvain: Secrétariat du Corpus SCO, 1963)

Other example:
## HLZ correct style:
Bernabò, M. 2008. Il Tetravangelo di Rabbula. Firenze, Biblioteca Med. Laur., cod. Plut. 1.56: L’illustrazione del Nuovo Testamento nella Siria del VI secolo, ed. M. Bernabò (Rome: Edizioni di Storia e Letteratura, 2008).

## Current extraction from Zotero:
Bernabò, M., ed., 2008. Il Tetravangelo di Rabbula. Firenze, Biblioteca Med. Laur., cod. Plut. 1.56: L’illustrazione del Nuovo Testamento nella Siria del VI secolo (Rome: Edizioni di Storia e Letteratura, 2008).

# Authors's Names:
- [x] When an author has more than one name, the initials should be spaced while currently Zotero writes them without space:
Pietro Maria Liuzzo should be extracted as P. M. Liuzzo, NOT as P.M. Liuzzo

# Conference Papers:
- [x] When exctracting conference papers, 'in' is missing and 
- [x] the volume number is written as an Arabic ordinal number:

## HLZ style:
— 1975. ‘Christ’s Entry into Jerusalem in Ethiopia’, in H. G. Marcus and J. T. Hinnant, eds, Proceedings of the First United States Conference on Ethiopian Studies, Michigan State University, 2-5 May 1973, III, Occasional Papers Series, Committee on Ethiopian Studies (East Lansing, MI: African Studies Center, Michigan State University, 1975), 43–60.

## Current extraction:
— 1975. ‘Christ’s Entry into Jerusalem in Ethiopia’, H.G. Marcus and J.T. Hinnant, eds, Proceedings of the First United States Conference on Ethiopian Studies, Michigan State University, 2-5 May 1973, 3rd, Occasional Papers Series, Committee on Ethiopian Studies (East Lansing, MI: African Studies Center, Michigan State University, 1975), 43–60.
 
# Thesis and Dissertations:
 - [x] All thesis are extracted as 'Diss.' even when they are not dissertations but, for example, PhD Thesis. Also the style used is generally different from how it should be:

## HLZ Style:
Heldman, M. E. 1972. Miniatures of the Gospels of Princess Zir Gānēlā, an Ethiopic Manuscript Dated A.D. 1400/01, PhD Thesis, Washington University.

## Current extraction:
Heldman, M. E. 1972. Miniatures of the Gospels of Princess Zir Gānēlā, an Ethiopic Manuscript Dated A.D. 1400/01 (Diss., Washington DC: Washington University, 1972).

# Short citation of work by Anonimous:
- [ ] When the work is by an anonimous author and Anon. is used in the author's field, the short citation should be  work title date NOT author date
E.g.
al-Mawsūʿa 1983 
Anon. 1983 

- [x] However in the full bibliography the Anon. should appear and the item arranged in alphabetical order based on this.

# Subsequent editions:
 - [x] When the field “edition” is used, Zotero SOMETIMES (I think depends on the work type chosen) adds a dot: (2nd edition.)

Thanks and regards,
Francesca

**Comment by PietroLiuzzo** [comment]
added instruction in style for paper-conference type (http://docs.citationstyles.org/en/stable/specification.html)
to add "in"
modified bibliography not to use ordinal numbers for volume in case of type=paper-conference
initialize-with for macro author changed from "." to ". " 
instead of text Diss added variable="genre" which takes what in Zotero is in Type.

**Comment by PietroLiuzzo** [comment]
added <term name="translator" form="short">tr.</term>

**Comment by PietroLiuzzo** [comment]
removed suffix="." from macro edition in else statement

**Comment by PietroLiuzzo** [comment]
Bernabò, M. 2008. Il Tetravangelo di Rabbula. Firenze, Biblioteca Med. Laur., cod. Plut. 1.56: L’illustrazione del Nuovo Testamento nella Siria del VI secolo, ed. M. Bernabò (Rome: Edizioni di Storia e Letteratura, 2008).
 is already correct. it needs an author in the Zotero data!

**Comment by PietroLiuzzo** [comment]
Arras, V. 1963. Collectio monastica. Textus, ed., tr. V. Arras, Corpus Scriptorum Christianorum Orientalium, 238, Scriptores Aethiopici, 45 (Louvain: Secrétariat du Corpus SCO, 1963).
is also correct now in the new style. it needs AUTHOR, CURATOR and TRANSLATOR with the repeated name! see  also Zotero Forums for this

**Comment by PietroLiuzzo** [comment]
type thesis is now without brackets
