### ISSUE TITLE
prepare clear version of search guidelines for users

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#561]
Apparently, the fuzzy search is not obvious to users. Clicking on the info button seems not so intuitive. Maybe it could be displayed more prominently? 
For example, we could possibly add to the info text which is there already:

> You can use AND, OR, and * in your search, for example. The search will add a wildcard in front of your search string.

something like "How to search for Ethiopic words in transliteration" with a pop up containing a detailed description of the fuzzy search and what a wildcard is. 

I think that this is an important issue since searching for certain persons, works, mss and places probably is the first thing new users will do. It might also be valuable to have feedback  on this issue of more users not very familiar with the app

**Comment by PietroLiuzzo** [comment]
I do not think I am the appropriate team member to put together a better version of the available guidance for the users. I will be glad to check a new version and put it online in a defined way.

**Comment by PietroLiuzzo** [comment]
@thea-m I am not sure whom to assign this, but I will change the title to reflect the task to be performed

**Comment by PietroLiuzzo** [comment]
one good thing to add would be example searches. with a table like search this, you will get this, with queries from simple to complex

**Comment by PietroLiuzzo** [comment]
good sample complex queries can be taken from the summer school presentation of @eu-genia

**Comment by PietroLiuzzo** [comment]
I have added two examples from #676 and the list of substitutions as in the dillmann about page also in the search help box

**Comment by PietroLiuzzo** [comment]
we will provide this with https://introjs.com/ and with a section in the guidelines

**Comment by PietroLiuzzo** [comment]
There is now a intro.js package loaded and a introText.js text which shows some of the main features of the homepage and from an item view. more can be added. also hints are available if they will be needed.
