### ISSUE TITLE
Susenyos

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#563]
I believe that some confusion happened while developing the records from the spreadsheet concerning persons called Susenyos.
PRS9038Susenyos referring to ʾaṣe Susənyos seems fine, while PRS9039Susenyos refers on the spreadsheet and in the title of the xml record to Susənyos II. However, the content of the xml record of PRS9039Susenyos is about St Susənyos. The spreadsheet record PRS8886Sisinios referring to St Susənyos is not developed. 
Could you correct this, @sologebre ? I'm sure it's no problem if the information concerning St Susənyos stays with PRS9039Susenyos, as long as all references are checked and "Susənyos II" in the title is corrected. In this case, a new record would have to be created for Susənyos II and PRS8886Sisinios could be deleted. Or the information for St Susənyos could be transferred to PRS8886Sisinios .
Please correct me if I misunderstood

**Comment by sologebre** [comment]
Thank you for your substantive comment. We will keep both records, but as you have suggested, I will transfer the content of PRS9039Susenyos to PRS8886Sisinios, and then I will fill in with new information the record of PRS9039Susenyos.

**Comment by PietroLiuzzo** [comment]
Please remember not to take ANY information in the spreadsheet as trustworthy for bm. Too many changes have occured. If there are missing records or missing info it should be possible to judge internally and correct internally. If a record is not there and you think it should create it. The ids in the Google table are not valid.

**Comment by thea-m** [comment]
I know, I was merely explaining the genesis of the records in question :)

**Comment by PietroLiuzzo** [comment]
yep, I understood, but I cannot help a note of caution when I hear about the table because I ask my self: why did you end up there in the first place?

**Comment by thea-m** [comment]
Because in PRS9039Susenyos St Susənyos is/was referred to as Susənyos II, which seemed strange to me, so I checked the xml file and found Susənyos II also in the title. Then I was just curious and checked the spreadsheet to see what had happened
