### ISSUE TITLE
empty lines

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#570]
`<space extent="2" unit="lines"/>`
Is this the correct way of encoding what the catalogue describes as "two empty lines" within a text?

**Comment by PietroLiuzzo** [comment]
it depends what two empty lines those are. sometimes without checking it might not be possible to decide 

http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-space.html

http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-gap.html

**Comment by thea-m** [comment]
I supposed they are a space, as they follow the (intact and complete) end of a work. However, the genealogical note following them seems to begin with a gap, or to start in the middle of a word. As the ms is lost, we will have to decide based on the catalogue
