### ISSUE TITLE
Marking up quotations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#572]
How can we mark up a quotation (especially biblical) in a text? @DenisNosnitsin1970 had a case where the quotation was clearly indicated in the catalogue. Is it possible to mark the text up and indicate the exact chapter and verse, instead of giving the reference in a note? There must be a possibility to do this in TEI, no? I can't find an example.

**Comment by PietroLiuzzo** [comment]
I dont understand the example. is ref with cref and locus this not ok?

copied from guidelines

For citations, like Matthew 14, 3 use ref with a @cRef containing the urn which you can get from Perseus catalogue searching for the passage.
````xml
 <ref cRef="urn:cts:greekLit:tlg0031.tlg001.perseus-grc1:14.3">Matthew 14, 3</ref> 
````

**Comment by PietroLiuzzo** [comment]
what you say about reference in a note worries me... could I have an example of this practice?

**Comment by PietroLiuzzo** [comment]
with cref if you do not want to point to the greek, you can use in @cRef Matth. and in @loc 14,3

**Comment by thea-m** [comment]
The example is in IVefiopsk10, #a3:
@DenisNosnitsin1970 has now added the reference Numbers 21:8 to the addition's translation (so that the information is mentioned at all, not to stay like this permanently).
Could the quotation introduced by "And it said to Moses" be marked up with `<quote>` (in the Ethiopic text)?
I'm not sure if I understood your comment correctly, `<ref>` takes no @loc apparently

**Comment by PietroLiuzzo** [comment]
ref is the element to be used here, in text or translation. with @cRef we give a canonical reference. urns are supported for perseus and thus the canonical greek text, not for the ethiopic text as we dont have it in most cases. I will now provide support for the ethiopic text and provide documentation on how to handle this as suggested in my previous comment and already done by Dillmann.

**Comment by PietroLiuzzo** [comment]
please use this to refer to the passage in the canonical text edited in BM `<ref cRef="urn:dts:betmas:LIT2075Number:21.8">Numbers 21:8</ref>`

**Comment by thea-m** [comment]
Thank you, wonderful! And in the text itself, would it be marked up like this?
`  ለሙሴ᎓ <ref cRef="urn:dts:betmas:LIT2075Number:21.8">ግበር᎓ ለከ᎓ አርዌ᎓ ምድር᎓ ዘብረት᎓ ኵሉ᎓ ዘነሰኮ᎓ ይርአይ᎓ ኪያሁ᎓ ወይሕየው</ref>᎓ ኪዮስ᎓`
If this is correct, it would maybe be helpful if the link to the verse could be in some way highlighted - as all words in the addition already are links to Dillmann, it can now only be found when someone intentionally clicks on one of the words in `<ref>`. Maybe as for links to work records an arrow icon could  be added after the quotation? Or the quotation could be in italics?

**Comment by PietroLiuzzo** [comment]
a passage in the text which is a litteral quotation of another text does not seam to me the same as a canonical citation. `ref[@cRef]` as above is for canonical citations like the ones discussed. Numbers 21:8, Mattew 14, 3.

you might use cit, which seams here more appropriate.

````xml
<cit>
    <quote xml:lang="gez">
         ለሙሴ᎓ ግበር᎓ ለከ᎓ አርዌ᎓ ምድር᎓ ዘብረት᎓ ኵሉ᎓ ዘነሰኮ᎓ ይርአይ᎓ ኪያሁ᎓ ወይሕየው᎓ ኪዮስ᎓
    </quote>
    <ref cRef="urn:dts:betmas:LIT2075Number:21.8">Numbers 21:8</ref>
</cit>
`````

I have updated the guidelines and I am going to update the visualization accordingly, replacing `cit` with "
