### ISSUE TITLE
references in work record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#573]
The edition of LIT2505Weddas, relations between single textparts and their authors are described, including references to manuscripts, but these references aren't displayed correctly on the app: 

> placed at the end of the work in Vatican, Biblioteca Apostolica Vaticana, Aeth. 83, no data for id LIT2505Weddas#Monday2 (in ms_i1.8) 

I don't see any mistakes in the references or the manuscripts

**Comment by PietroLiuzzo** [comment]
![schermata 2017-09-22 alle 12 27 20 2](https://user-images.githubusercontent.com/508012/30740488-6c67842e-9f91-11e7-80db-94d22a0e18e8.png)
is this not correct?

**Comment by PietroLiuzzo** [comment]
@thea-m could you close if ok?

**Comment by thea-m** [comment]
The view I had meant was this, where this particular issue does indeed look fine now, thank you!
![image](https://user-images.githubusercontent.com/19650382/31440862-a9677abe-ae91-11e7-9ba4-8e1fe0f9ca0a.png)

I noticed though that the manuscript IDs are now printed instead of the shelfmark (BAVet83 instead of Vatican, Biblioteca Apostolica Vaticana, Aeth. 83) - for me, this makes no difference, but from experience this can be very confusing for users

**Comment by PietroLiuzzo** [comment]
![schermata 2017-10-11 alle 14 55 03](https://user-images.githubusercontent.com/508012/31441683-3c3bba60-ae94-11e7-9c71-6078b9015201.png)
please have a look at this in the new release version

**Comment by PietroLiuzzo** [comment]
addendum to... `<ref target="#Monday"/>` not shown

**Comment by PietroLiuzzo** [comment]
Addendum to Monday, equally attributed to Bāsǝlyos  and placed at the end of the work in Vatican City, Biblioteca Apostolica Vaticana, Aeth. 83, Wǝddāse ʾAmlāk, chapter: Monday2 (in ms_i1.8)  (mss)
