### ISSUE TITLE
add images for Frankfurt mss

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#576]
Nearly all Frankfurt mss are digitalized, how can we add the link to the images?
For example FSUor10:
http://sammlungen.ub.uni-frankfurt.de/msorient/content/pageview/5247790

**Comment by PietroLiuzzo** [comment]
the only thing we can do here is adding a generic link to these images with a `ref`. These images are not served through IIIF standards and thus we cannot reuse them as easily as with vatican and bnf for example.

**Comment by thea-m** [comment]
Ah, I understand. Where would I add this link? (and how exactly, see #554) Not in the `<idno facs="">`?
Can I make a suggestion? Maybe it would be good if the links to digitized manuscripts, whether we reused their images or not, could be displayed relatively prominently on the ms page? Maybe under the title? Nothing on the page of, for example of BNFet102, tells a user who doesn't click on the folio numbers that this manuscript is digitized.

**Comment by PietroLiuzzo** [comment]
well, if there are images you get the viewer menu, which you don't get if there are no images...

**Comment by PietroLiuzzo** [comment]
now you get a link to external images in place of images tab
