### ISSUE TITLE
wikidata in institutions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#577]
Do we use wikidata instead of geonames also for institutions? There are still many examples with geonames in the places guidelines, so it's not entirely clear.
I had added some wikidata references in INS0317Frank in the following format:
```xml
    <place type="library" subtype="institution">
                    <placeName xml:id="n1" xml:lang="de">Universitätsbibliothek Johann Christian Senckenberg</placeName>
                    <placeName type="alt" xml:id="n2" xml:lang="de"
                        >Stadt- und Universitätsbibliothek Frankfurt am Main</placeName>
                    <placeName type="alt" xml:id="n3" xml:lang="de"
                        >Senckenbergische Bibliothek</placeName>
 <country sameAs="Q183"/>
                        <settlement sameAs="Q1794"/>
  <location><geo>50.120294 8.653069</geo></location>
                    <listBibl type="catalogue">
                        <bibl>
                            <ptr target="bm:Goldschmidt1897catalogue"/>
                        </bibl>
                    </listBibl>
                </place>
```
But all mss of this institution were then displayed with "No location" in the title. After I changed the references to geonames IDs, the titles correctly have "Frankfurt".

**Comment by PietroLiuzzo** [comment]
please see guidelines. 
https://github.com/SChAth/ScAthiop/wiki/guidelinesPlace#alignment
sameAs is used ONLY for the element place. country, settlement, region, placeName, all take `@ref` . e.g.:
`<settlement ref="Q1794"/>`
this is through for any record. @sameAs is only used to associate an existing record via an id to an authority file in WD or GN. we provide these references to such authority  always as ref.

**Comment by thea-m** [comment]
I tried to update the record accordingly, but apparently I misunderstood something. @ref with wikidata also isn't displayed:
```xml
   <place type="library" subtype="institution">
                    <placeName xml:id="n1" xml:lang="de">Universitätsbibliothek Johann Christian Senckenberg</placeName>
                    <placeName type="alt" xml:id="n2" xml:lang="de"
                        >Stadt- und Universitätsbibliothek Frankfurt am Main</placeName>
                    <placeName type="alt" xml:id="n3" xml:lang="de"
                        >Senckenbergische Bibliothek</placeName>
                    <country ref="Q183"/>
                    <settlement ref="Q1794"/>
```
 http://betamasaheft.eu/manuscripts/INS0317Frank/list

I this particular case, there is actually a wikidata item for the institution is question. Would it make sense to add it:
` <place type="library" subtype="institution" sameAs="Q875587">`
and then not include the rest of the geographical information, as it is contained in the wikidata entry?

**Comment by PietroLiuzzo** [comment]
We will create anyway a record for the institution. the addition of the @sameAs does not harm
