### ISSUE TITLE
problem with indexes

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#580]
http://betamasaheft.aai.uni-hamburg.de/keywords/

> HTTP ERROR 404
> 
> Problem accessing /exist/apps/BetMas/keywords/. Reason:
> 
>     Document /db/apps/BetMas/keywords not found

http://betamasaheft.aai.uni-hamburg.de/additions

> 504 Gateway Time-out

**Comment by PietroLiuzzo** [comment]
how did you get to the first url? there must be a wrong link somewhere, the final slash should not be there.
http://betamasaheft.eu/keywords is correct

**Comment by PietroLiuzzo** [comment]
for the additions list the problem is the size of the page I am trying to load.

**Comment by PietroLiuzzo** [comment]
I now load in additions simply the text of q if any. the user will have to click the link to get to the edited text.

**Comment by PietroLiuzzo** [comment]
incientally: now also the decorations lists does not have any more the grouping problem it used to have.

**Comment by thea-m** [comment]
thank you! I don't remember where I got the link from, but now it seems to work correctly from everywhere. Maybe it was my mistake.
Additions and decorations are very clearly visualized now. However, there is still a small problem with the keywords index: when clicking on any keyword the keyword repeated as many times as there are items containing it appears. For "ApocryphaPseudoepigrapha" the first impression is quite shocking

**Comment by thea-m** [comment]
and a suggestion from @MassimoVilla : in the "additions" index, maybe instead of the IDs, the shelfmarks of the manuscripts could be given?

**Comment by PietroLiuzzo** [comment]
there are way too many titles to be retrived multiple times in that view. I would instead argue that perhaps the keywords list is now redundant, given that we have the authority-files/list view, which returns id, title and type.
http://bet.mas/authority-files/list?keyword=ApocryphaPseudoepigrapha
I will substitute the link with the one to the authority files list which is currently in the home dropdown.

**Comment by PietroLiuzzo** [comment]
done
