### ISSUE TITLE
mss not displayed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#581]
There are many mss described in Ullendorff's catalogue which are not listed in the catalogue view:
http://betamasaheft.eu/catalogues/bm:Ullendorff1951Catalogue/list?start=1&keyword=&language=&date-range=&per-page=50
When entering the ID of the mss in the URL, the following message appears: 

> BDLaethc3 is not an available item.
> Ids are case sensitive.
> Try browsing or using simple or advanced search.

In two of the concerned mss (BDLaethc1 and BDLaethe15), I tried finding out what the problem was by commenting out sections. It turned out that, as soon as I comment anything in the ms out, it is displayed correctly (even after reverting the comment and changing nothing at all in the xml record.) I think that this is what happened with BDLbruce93 as well. 
I don't understand what's going on here - is there any way to return these mss to the app faster  than manually commenting out a section in each of them?

**Comment by thea-m** [comment]
apparently committing any change at all in these records makes them reappear on the app

**Comment by thea-m** [comment]
same for RIE195II...

**Comment by PietroLiuzzo** [comment]
yes, I suspect this is something going wrong in the initial store operation of the file in the database. 
there is nothing I can actively do about it, but the issue seams not to be there in the new release, thus I am closing this issue.
