### ISSUE TITLE
@n in locus

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#583]
How can I refer to the exact locus of an item including lines? I have written once:
`<locus from="1v" to="2ra" n="1-6"/>` , but we have it nowhere in the guidelines and I probably improvised. What I meant is of course that the text begins on 1v in line 1 and ends on 2ra in line 6.
Maybe like this ?
```xml
   <locus from="1v" n="1"/>
 <locus to="2ra" n="6"/>
```

**Comment by PietroLiuzzo** [comment]
Please, don't do that. Use simply

`<locus from="1v" to="2ra">the text begins on 1v in line 1 and ends on 2ra in line 6</locus>`

**Comment by PietroLiuzzo** [comment]
The guidelines did point you in the wrong direction by saying you might use @n. I have not corrected the guidelines.

**Comment by thea-m** [comment]
Thank you! However, this is currently visualized as (a2 in BDLaethe15):

> The text begins on f. 1v in line 1 and ends on f. 2ra in line 6.The text begins on f. 1v in line 1 and ends on f. 2ra in line 6.

with the first sentence being the link to 1v. In this case there are no images available anyway, but if there were, would there be a possibility to keep the links to both 1v and 2r? Would it maybe be easier to add the detailed information in a note?

**Comment by PietroLiuzzo** [comment]
this was simply the transformation, no need to go creative with the markup :)

**Comment by thea-m** [comment]
This encoding has also been used in BAV records, @MassimoVilla (in ES records as well)

**Comment by PietroLiuzzo** [comment]
which encoding? the one with the two loci?

**Comment by thea-m** [comment]
yes, for example BAVet36
ES has some instances of  `<locus from="3r" to="5r" n="5/3"/>` (ESmr004)
Can @n still be used in one locus, such as for example `<locus target="#17r" n="3"/>` (ESmr004)?

**Comment by MassimoVilla** [comment]
I have quite often used @n in BAV records, following the guidelines, to indicate the exact line wherever the catalogue provided it.
The problem usually arose, as illustrated, with two @n since an encoding like this `<locus from="134rb" n="11" to="135ra" n="28"/>` is not allowed. In these cases, in order not to lose information from the catalogue, I split the encoding as follows `<locus from="134rb" n="11"/> <locus to="135ra" n="28"/>`, which is the solution not recommended by Pietro.
Can we  fix the use of @n so I can go through all the BAV records where it has not been properly used?
So far, the suggested solution is:
- line indicated by means of @n in case of an exact locus: `<locus target="#1v" n="1"/>`;
- lines indicated as a content in case of a range: `<locus from="1v" to="2ra">the text begins on 1v in line 1 and ends on 2ra in line 6</locus>`.

Can we add this to the guidelines?

**Comment by thea-m** [comment]
> - line indicated by means of @n in case of an exact locus: `<locus target="#1v" n="1"/>`;
> - lines indicated as a content in case of a range: `<locus from="1v" to="2ra">the text begins on 1v in line 1 and ends on 2ra in line 6</locus>`.

Can we add this to the guidelines, @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
I think **one**  `@n` attribute is supported. I would take the example in massimo comment with the splitting as well. n="3/5" is most certainly wrong.

**Comment by PietroLiuzzo** [comment]
@thea-m rightly points me to my inconsistency.
so, what really should not happen is `@n="3/5" ``@n="3-5"` neither use twice `@n`.
the encoding Massimo used in BAV is fine and is supported as well as the other suggested.

**Comment by PietroLiuzzo** [comment]
@thea-m @MassimoVilla can we close this issue?

**Comment by thea-m** [comment]
So I can add to the guidelines:
> - line indicated by means of @n in case of an exact locus: `<locus target="#1v" n="1"/>`;
> - lines indicated as a content in case of a range: `<locus from="1v" to="2ra">the text begins on 1v in line 1 and ends on 2ra in line 6</locus>` OR `<locus from="134rb" n="11"/> <locus to="135ra" n="28"/>`

?

**Comment by PietroLiuzzo** [comment]
I have slightly edited to give a better idea of the point. yes, I think this is fine and supported

**Comment by thea-m** [comment]
Thank you! Though I think that the point of @MassimoVilla 's encoding with `<locus from="134rb" n="11"/> <locus to="135ra" n="28"/>` was to avoid having to write text (which we only rarely do when indicating the locus of a msItem), so could I still add it to the guidelines like this?

**Comment by PietroLiuzzo** [comment]
yes, we can add a codetemplate, or indeed you can add your own in oxygen, if the text is bothering

**Comment by thea-m** [comment]
thank you!
