### ISSUE TITLE
advanced search button

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#584]
I know that this has been discussed often and I was the one who wanted the "+" to indicate the advanced search. However, several people not very familiar with the app have failed to notice and use it so it seems like this wasn't a good idea. 
I like the way the advanced search is indicated on syriaca with the gear wheel and "search tools":
http://syriaca.org/authors/index.html
Would it be possible to have this also in our menu bar, or is the space there too limited?

**Comment by PietroLiuzzo** [comment]
I have made into cog Search plus, to keep everyone happy
