### ISSUE TITLE
search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#587]
Why do I get "0 results" when searching for "እግዚእብሔር፡ ዓቢይ፡ ውእቱ፡ ለዓለም" and selecting "incipit"?
I would wand to find the incipit of ms_i14.3 in BNFet67

**Comment by PietroLiuzzo** [comment]
I do find exactly that...
http://betamasaheft.eu/as.html?query="እግዚእብሔር፡ ዓቢይ፡ ውእቱ፡ ለዓለም"&element=incipit&references=&work-types=mss
