### ISSUE TITLE
double visualization in binding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#589]
In most St Petersburg manuscripts, binding is encoded in the following way:
```xml
   <binding contemporary="false" xml:id="binding">
                <decoNote xml:id="b1" type="Other">Russian binding made of leather, with tooled Orthodox (Suppedaneum) cross, gilded ornament 
                  and inscription in <foreign xml:lang="la"> Psalterium aethiopicum A. Porphyrii</foreign></decoNote>
                <decoNote xml:id="b2" type="bindingMaterial">
                                 <material key="leather"/>
                </decoNote>
              </binding>
```
All content of  `<decoNote xml:id="b1" type="Other">` is visualized twice on the app, for example: http://betamasaheft.eu/manuscripts/IVefiopsk13/main

@DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
this was a documentation problem.
I have now updated the guidelines https://github.com/BetaMasaheft/Documentation/wiki/guidelines#binding-description
in this case it will be enough to remove `@type='Other'` from the `decoNote[@xml:id='b1']`

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @thea-m please close issue if answer is satisfactory

**Comment by thea-m** [comment]
Thank you, works well!  In which cases should  `@type="Other" `now be used?

**Comment by PietroLiuzzo** [comment]
it can be used, but not on b1, as the guidelines say

> The first decoNote, with @xml:id='b1' should be a general note and remain untyped.
