### ISSUE TITLE
"lettering" in date

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#591]
As pointed out by Susanne, the current visualization of
```xml
   <origin>
   <origDate notBefore="1600" notAfter="1699" evidence="lettering"/>
   </origin>
```

as

> Origin
> 1600 - 1699 (lettering)

is maybe not ideal as its meaning is not immediately clear to users. Maybe we could have instead 1600 - 1699 (dating on paleographic grounds)?

**Comment by PietroLiuzzo** [comment]
( dating on paleographic grounds )

remove trailing spaces
