### ISSUE TITLE
"Printedbook" in search filter

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#593]
When selecting "manuscripts" as a filter in the advanced search, and then filtering for "support", among the list of available object types there is "ms i1.9" - when selecting it RIE195II was given as the only result at first, but since I commited a comment in the record, no result is given: 
http://betamasaheft.eu/as.html?query=&references=&work-types=mss&support=ms+i1.9
There must be a mistake somewhere in our data, but I couldn't find it

**Comment by thea-m** [comment]
and in the same list in the filter, could "Printedbook" be spelled "Printed Book"?

**Comment by thea-m** [comment]
"ms i1.9" has now disappeared

**Comment by PietroLiuzzo** [comment]
it is now printed book
