### ISSUE TITLE
encoding of musical notation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#594]
Until now, we have only described the presence of musical notation in a manuscript using `<notatedMusic>`:
```xml
<notatedMusic>
 <desc>Extensive musical notation.</desc>
</notatedMusic>
```
But what about directly encoding musical notations within a text? For example in FSUor15, incipit of ms_i1.1. The musical notes are added above the lines: http://sammlungen.ub.uni-frankfurt.de/kataloge/content/pageview/1551892
http://dfg-viewer.de/show/?tx_dlf%5Bpage%5D=5&tx_dlf%5Bid%5D=http%3A%2F%2Fsammlungen.ub.uni-frankfurt.de%2Foai%2F%3Fverb%3DGetRecord%26metadataPrefix%3Dmets%26identifier%3D5412370&tx_dlf%5Bdouble%5D=0&cHash=fb30b3e8068e1a55b0f1cc27bd5e55fd
Since the transcribed incipit is present in the catalogue, I would like to include it in the xml record as well.
It would be possible to include the musical signs with `<add place="above">`, but without further specification this would make them seem as later additions. Maybe we could add a @type="notatedMusic" to `<add>`. Or could we use `<notatedMusic place="above">` directly in the text? How exactly would we then add the musical signs?

**Comment by PietroLiuzzo** [comment]
there is MEI for this. however I would discourage at this stage the encoding of this aspect. I would rather keep only using `notatedMusic` with as much information as possible in it to describe the ms  but leave the music transcription to a future dedicated project.

**Comment by thea-m** [comment]
that's what I thought - so to clarify, if I have for example "ቅዱስ፡", where the musical notes are a ጉ above the ዱ and a ስ above the ስ, how would I encode this?
```xml
ቅዱ<notatedMusic place="above"><desc>ጉ</desc></notatedMusic>ስ<notatedMusic place="above"><desc>ስ</desc></notatedMusic>፡
```
It seems a bit strange to have the musical signs in `<desc>`?
