### ISSUE TITLE
problem with comparison feature

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#596]
The comparison doesn't function for some works:
http://betamasaheft.eu/compare?workid=LIT1960Mashaf
http://betamasaheft.eu/compare?workid=LIT2509Weddas
For others, it works normally:
http://betamasaheft.eu/compare?workid=LIT1146Argano

**Comment by PietroLiuzzo** [comment]
should be solved for opening, it still does not display titles correctly

**Comment by PietroLiuzzo** [comment]
should be better now, although still the references in titles cannot be rendered as titles

**Comment by PietroLiuzzo** [comment]
Maḥālǝya nabiyāt,  Third Song of Moses (ጸሎተ፡ ሙሴ፡ ዘሣልስ፡). Excerpt from LIT2637Deuteronomy (work) 32:22-43

should be 

Maḥālǝya nabiyāt,  Third Song of Moses (ጸሎተ፡ ሙሴ፡ ዘሣልስ፡). Excerpt from Deuteronomy 32:22-43
