### ISSUE TITLE
define bio data display in person records

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#597]
#590 
the general look of the person record needs to be briefly discussed to meet better user wishes. A draw up or an example from another website would be helpful.

**Comment by PietroLiuzzo** [comment]
I have moved names on the right and changed slightly the display of birth, death, floruit

**Comment by Gnisci** [comment]
We're talking about adding a brief bio note to each Person right? If that the case I'd be happy to start doing that for Biblical figures, because it would fit into what I am already doing

**Comment by Gnisci** [comment]
Would it be worth having a brief note for the most commonly mentioned Persons? In most cases Biblical figures and saints I would imagine
