### ISSUE TITLE
Images from digi.vatlib

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#598]
A test on ms. BAVet25 f. 3r (here the images: http://digi.vatlib.it/view/MSS_Vat.et.25, f. 3r has here URL number 0006) has been unsuccessful.
The output on the app is: Unable to open [object Object]: HTTP 0 attempting to load TileSource.

**Comment by PietroLiuzzo** [comment]
please note info in guidelines

> Links to the images of the Vatican Library MSS are now supported, by adding in the idno/@FACS the manifest.json url which can be found in the digivatlib on the left info page http://digi.vatlib.it/view/MSS_Vat.et.1, e.g. **http://digi.vatlib.it/iiif/MSS_Vat.et.1/manifest.json** to add link to loci, add @FACS attributes. Please do not forget that the folio number (in the following example 3r) does not necessarily corresponds to the URL number (here 0006).

I temporarily corrected BAVet1 so that you can see.
