### ISSUE TITLE
open seadragon modal not closing

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#599]
when clicking on a leaf with which no image is associated, the expected information is given: "No image available. There is no image available at the moment for (given folio)". Once opened, I can not close the window, which overlaps the text.

**Comment by PietroLiuzzo** [comment]
@MassimoVilla browser?

**Comment by MassimoVilla** [comment]
chrome

**Comment by PietroLiuzzo** [comment]
I think you mean the popup which says that. just click again on the number
