### ISSUE TITLE
Ethio-SPaRe mss to be selected for visualization

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#600]
As planned in the previous meeting yesterday, part of the Ethio-SPaRe mss should be selected for visualization. A rough estimation made yesterday was of one hundred items out of 2,000. The corresponding descriptions should be then conformed to our encoding standard and validated. This needs time of course, but a very small set of instances might be displayed on the occasion of the forthcoming Summer School.
Please, @DenisNosnitsin1970  can we decide which ES MSS we want to present, so that I can go through the MSS records and work on them?

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 wrote me already yesterday
Here are the images which can be used in the sense we have discussed today.
The signatures are: 
MR 1 to 30
AMM 1 to 13
QMB 1 to 7
DMB 1 to 9
MHG 10 to 20
AKM 1 to 10
DDM 1 to 10 
AP 10 to 15 and 20 to 32
MMA 1 to 13.

All in all it is 109 mss
(all catalogued in Ethio-Spare database).

**Comment by PietroLiuzzo** [comment]
the images are not yet available please wait until I have processed them

**Comment by MassimoVilla** [comment]
thank you.

**Comment by PietroLiuzzo** [comment]
https://www.rrz.uni-hamburg.de/services/datenhaltung/uhhdisk/cifs.html

**Comment by PietroLiuzzo** [comment]
There is now a process in place to mount the UHH disks on the server

**Comment by PietroLiuzzo** [comment]
will require fixing the nginx setting for iiif rewrite not to be bound to /media/add/images and will consequently need a longer path in idno/@facs to specify which server as well as the full current path to the images in the ES Disks

**Comment by PietroLiuzzo** [comment]
MR 001 done...

**Comment by PietroLiuzzo** [comment]
I have made a request for an external disk to be mounted on the server, instead  of mounting the 6 ES disks. I will then move there the TIFF which are temporarily on HLZ3. 
- this will allow to keep separate the project work (e.g. I do not have to mess around with ES data)
- the folders will anyway have to be made and named in a conciser way, doing this in ES would just add confusion
- there will be only one disk mounted instead of 6, facilitating maintaince
- there will be no user access to the disk with the images in TIFF

**Comment by PietroLiuzzo** [comment]
once the new disk is there I wil need to
- mount all the ES disks with user folders
- mount the new disk
- make the folders in the new disk
- copy correctly the JPG images from the ES disks to the BM UHH disk
- transform the images to TIFF with the script in /add/media/images/jpg2tiff.sh
- remove all JPG files
- change the nginx configuration to redirect iiif calls to the new BM UHH disk
- reduce the path requirement for the data entry in the idno/@facs

**Comment by PietroLiuzzo** [comment]
folders prepared on HLZ3

**Comment by PietroLiuzzo** [comment]
no images for MR-002, MR-017, MR-028, MR-030.

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/wiki/SER3

**Comment by PietroLiuzzo** [comment]
no images for AP-024 AP-025

**Comment by PietroLiuzzo** [comment]
MHG-017 MHG-018 no images

**Comment by PietroLiuzzo** [comment]
all named files moved, now transforming them to tiff

**Comment by PietroLiuzzo** [comment]
selected MR, AKM, AMM done

**Comment by PietroLiuzzo** [comment]
AP done

**Comment by PietroLiuzzo** [comment]
All the selected images are on the server as TIFFS.
We are waiting for a UHH Disk space increase to solidify the directories and definitively update the guidelines.

**Comment by PietroLiuzzo** [comment]
We have been assigned more space. HLZ 3 and HLZ 5 have now 8Ti. we are moving all *-user directories from HLZ3 and HLZ6 to HLZ 5, HLZ 3 will only host the TIFFs for BM

**Comment by PietroLiuzzo** [comment]
these all need now in "idno/@facs" the reference to the images on the server e.g. MR/001/MR (see guidelines)

**Comment by PietroLiuzzo** [comment]
looks like @LeonardBahr has completed this and I have checked and fixed his changes to the entries.
