### ISSUE TITLE
weird results for query

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#601]
When searching for ለጻሕል and selecting incipit, I would expect to get BAVet108 (ms_i1.6), but there are no results at all
http://betamasaheft.eu/as.html?query=%E1%88%88%E1%8C%BB%E1%88%95%E1%88%8D&element=incipt&references=&work-types=mss

**Comment by PietroLiuzzo** [comment]
yep, fixed incipt to incipit
