### ISSUE TITLE
printing entries from the app

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#607]
There has been a user requirement to print entries from the app (the main view of ms records). When printing this now, all gəʿəz words are visualized with their link to the search in Dillmann, which of course makes the text overcharged and uncomfortable to read

**Comment by PietroLiuzzo** [comment]
https://github.com/BetaMasaheft/Documentation/wiki/APP7
https://github.com/BetaMasaheft/Documentation/wiki/APP8

These requirement had a priority 5, so, the lowest.
In fact, without a definition of how the output should look it is not possible to do anything good. 
You can see in Dillmann app, that the pdf produces a rather defined page, similar to the dillmann layout which was taken as example. 
given an example and a proper specification the pdf can be produced rather easily

**Comment by PietroLiuzzo** [comment]
pdf styling will follow Aethiopica styles and use fonts used there, not noto

**Comment by PietroLiuzzo** [comment]
now tei2fo.xql produces an initial draft print out with TOC of the msItems, full bibliography in all citations, citation, revision. no further development will be done until proper specification is provided.

**Comment by PietroLiuzzo** [comment]
also texts are now rendered (without apparatus and most of the editorial interventions, till better specification) and also places and persons can be printed in a EAe like pdf. closing for the release, and waiting for specification
