### ISSUE TITLE
<biblScope> instead of <citedRange>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#613]
in many person and place records, `<biblScope>` has been used instead `<citedRange>` (see guidelines) to indicate the range of bibliographic references. Could you correct it, @sologebre ? (should go relatively quickly with find/replace)

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%27%29%2F%2Ft%3AbiblScope
