### ISSUE TITLE
Suspicious Title in LIT1753Lament

### ISSUE THREAD

**Issue by MargaretheJenner** [BetaMasaheft/Documentation#614]
In LIT1753Lament: 
Is "Lam" really the title or should it be a short title, or is the wrong TEI? 
It seemed to short for a title so for the moment I was asked to comment it out.

**Comment by thea-m** [comment]
I believe it was meant as a short title. Can we only have one short title for a record (the one used by Dillmann) or is it possible/reasonable to add several? Lam. is also commonly used as an abbreviation for this book.
@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
As it has to be canonical, yes, it definitely needs to be only one: otherways we are ourselves un-canonical. The abbreviation already in use by Dillmann is the most authoritative so, the one added by @MargaretheJenner is the correct one. I would also update the guidelines about it if they are not clear.
