### ISSUE TITLE
scholar view on the homepage

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#618]
Currently all persons marked up with `<occupation type="academic">` are shown on the homepage, which includes modern political figures such as PRS11686Hailemariam - since the study of their activities (I can see no relation to manuscripts for now) is not within our scope, I don't think that their records should be so prominently displayed.
Could we maybe restrict the scholars shown on the homepage to those described as  `<occupation type="academic">scholar</occupation>`, or to those active before the 20th century?
What do you think?

**Comment by PietroLiuzzo** [comment]
I agree and I would thus use the occupation[@type='academic'] sparingly
