### ISSUE TITLE
<locus/> not allowed within <item xml:id="e1"/>

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#623]
`<locus/>` within the description of one of the Varia phenomena is no longer allowed.
However, there cases like the following (from BAVet10):
` <item xml:id="e3">     
                           <locus from="1" to="49"/>
                           <desc>Invocations are inserted in the main hand in the upper margin of many leaves: 
                              e.g., <q xml:lang="gez">በመዕትከ፡ ኢትቅስፈኒ፡</q> (<locus target="#3r" facs="0005"/>), <q xml:lang="gez">አድኅነኒ፡ እግዚኦ። ነጽረኒ፡ ወስምዐኒ፡</q> 
                              (<locus target="#7r" facs="0009"/>), <q xml:lang="gez">ለትኩን፡ ምሕረትከ፡ ላዕሌነ፡</q> (<locus target="#22r" facs="0024"/>).
                           </desc>
                        </item>`
The phenomenon (the invocations in the upper margin) is attested thorughout the whole Ms, so it has bee treated as one single item e1. Alongside the general indication <locus from="1" to="49"/>, a specific <locus/> is also provided within <desc/> to indicate the exact examples, but this is not tolerated. Can't we relax the schema with respect to this point?

**Comment by PietroLiuzzo** [comment]
It is possible but I think not desirable. You will need to make as many items as you know about. the ones we do not know about from the catalogue record we cannot add but somebody will perhaps in the future. In this way we make our data more precise and consistent than that in the catalogue.
