### ISSUE TITLE
<dimensions unit="mm"> in ES mss

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#624]
The descriptions of the ES manuscript usually give the outer dimensions nested inside `<extent/>` in cm (`<dimensions type="outer" unit="cm"/>` or ` <height unit="cm"/> <width unit="cm"/>                   <depth unit="cm"/>`), whereas the inner dimensions inside `<layout/>` have been already automatically converted into mm (this is what I suppose, since they are given in cm in the Ethio-SPaRe database files).
I believe that one unit of measurement would be preferable, and this should be millimetres.
Can we extend the automatic conversion from cm to mm to the outer dimensions as well?

**Comment by PietroLiuzzo** [comment]
yes, is a metter of doing *10 ... 
although back in may 2016 when this work was done, there was a reason not to convert both, which I do not remember. 
could you confirm this is only in ES mss where //layout/dimensions[@unit='cm'] ?

**Comment by MassimoVilla** [comment]
The situation is inconsistent, some MSS already have mm. I was only wondering whether it was possible to convert every time the measurement is explicitly given in cm in that position (//layout/dimensions[@Unit='cm']) into mm.

**Comment by MassimoVilla** [comment]
So far I'm doing it manually.

**Comment by PietroLiuzzo** [comment]
don't do it by hand, I can do it with a transformation.
