### ISSUE TITLE
Rubrication in ES mss

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#625]
Portions of texts written in red ink are currently indicated in ES files as nested inside `<decoDesc>`, precisely as `<decoNote type="rubrication" xml:id="d0"/>`. 
According to the guidelines it should be encoded as `<seg type="rubrication"/>` inside `handNote`, since it concerns a scribal phenomenon.
Can we automatically move the portion of information from `decoDesc` to `handNote` for all ES mss?

**Comment by PietroLiuzzo** [comment]
I distinctly remember doing this or being asked to do something similar previously and then being stopped. Please could you search the closed issue and further document this fenomenon and how to safely perform such transformation? it can of course be done.

**Comment by thea-m** [comment]
#273 
There had been three different ways of encoding rubrications, and in the end we had agreed, as stated now in the guidelines, on `<seg type="rubrication"/>` inside `handNote`
@PietroLiuzzo had written:

> action items
> 
> - [x] deprecate use of minified records and remove references from guidelines
> - [x] correct files where ab[@type="rubrication"] is used
> 
> ES files are to be conformed, probably will require previous hand testing to set rules stright

**Comment by PietroLiuzzo** [comment]
Please note that here we still have two different things, the decoNote and seg. are these actually different?

**Comment by MassimoVilla** [comment]
So far I have only used seg. Rubrication inside `decoNote` might be redundant. In our guidelines it is not even mentioned among the available valued of @type for decoration.

**Comment by thea-m** [comment]
@PietroLiuzzo, the only instances in which rubrication is still encoded within decoNote are the ES and Kopenhagen manuscripts (there were also two BNF records which had slipped through the first round of  corrections and which I updated now). If I understand #273 correctly, its agreed outcome was to transform the descriptions in these records from decoNote to `<seg type="rubrication"> `
