### ISSUE TITLE
Spelling in ES files

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#626]
Some single words inconsistently spelled in the ES files (at least according to our system of transliteration) might be automatically replaced with the correct forms in all ES records.
Here follows a small list of instances I found today:
ʾArganonä >ʾArgānona;
St. > St
ʾabunä > ʾabuna
tämälläs > tamallas (obviously also with capital T)
ʿAmdä > ʿAmda
Kidanä > Kidāna

**Comment by PietroLiuzzo** [comment]
please use the find and replace in all files function in oxygen for all such cases. https://github.com/BetaMasaheft/Documentation/issues/627#issuecomment-334127489

**Comment by PietroLiuzzo** [comment]
carefully of course :)

**Comment by MassimoVilla** [comment]
Do we need for some purpose to keep the backup files with extension .bak after converting them with the find-and-replace function?

**Comment by PietroLiuzzo** [comment]
NO! Please, do not commit those files! 

in the find and replace dialogue make sure you untick the option that creates those files

**Comment by PietroLiuzzo** [comment]
![schermata 2017-10-05 alle 10 55 42](https://user-images.githubusercontent.com/508012/31218821-c2981262-a9bb-11e7-8def-03df61baa75a.png)

**Comment by PietroLiuzzo** [comment]
I have updated the guidelines with a section on editing more then one file in the project
https://github.com/BetaMasaheft/Documentation/wiki/workflow#batch-editing-files
