### ISSUE TITLE
<foreign xml:lang="gez"/> in ES files (ʾabuna and tamallas)

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#627]
Once properly corrected according to our spelling system (cp. #626 ), some words which are not translated yet only transliterated should be - according to our guidelines - always nested inside `<foreign xml:lang="gez"/>`. For instance in some ES records surveyed today: ʾabuna and tamallas. 
Can this be done automatically for all occurrences throughout the ES files (and actually not only the ES files)?

**Comment by PietroLiuzzo** [comment]
in Oxygen you can use the find and replace function across all files which you think need to be updated. this can be done both to fix the transliterartion and to add the tag in this case. when you hit replace all, you will be asked if you want to preview. this is wise to do and you can still not perform the action. even if you did and then find out that there where mis matches, then you can revert the changes from git. I remain at your disposal for further guidance about this

**Comment by thea-m** [comment]
ʾabuna has actually also not been marked up in textual information in persons records (but has been marked up in `<persName>`: `<persName><roleName type="title">ʾabuna</roleName></persName>`, see for example PRS10344Yeshaq). Would it be better to mark this up simply with  `<foreign xml:lang="gez">` or with `<roleName type="title" xml:lang="gez">ʾabuna</roleName>?`
