### ISSUE TITLE
Wikidata in INS0306BSL

### ISSUE THREAD

**Issue by MargaretheJenner** [BetaMasaheft/Documentation#628]
Whilst changing geodata into wikidate I found this code in INS0306BSL:

        <country ref="Q145"/>
                    <region ref="Q21"/>
                    <settlement ref="**LOC2104Cambri**"/>

Is Loc2104Cambri supposed to stay that way or should I change it into wikidata?

**Comment by thea-m** [comment]
It can also be changed to wikidata, thank you!

**Comment by MargaretheJenner** [comment]
Ok. Thank you!
