### ISSUE TITLE
BCE dates

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#640]
how are BCE dates marked up? I don't think there are many in our records, but I found this:
  `<death when="0931" cert="medium"></death>`
in PRS8925Solomon, which seems to me exactly like a CE date

**Comment by PietroLiuzzo** [comment]
-0931
see guidelines. 
please, correct these where needed

**Comment by sologebre** [comment]
Thanks, it is corrected now.

**Comment by thea-m** [comment]
I added this to the guidelines, so that we have the information stated explicitely:

> BCE dates are therefore expressed with -: `<death when="-0931"/>`
