### ISSUE TITLE
encoding of ʾabbā and ʾabuna

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#643]
ʾabbā and ʾabuna are encoded inconsistently both within the records of the concerned persons and when referring to them:

- In the person records:

PRS11351TawaldaM:
`<occupation type="ecclesiastic"><roleName type="title">ʾabbā</roleName></occupation>`

PRS1008Abakaraz:
```
<persName xml:lang="gez" xml:id="n3" type="birth">እስጢፋኖስ፡</persName>
<persName xml:lang="gez" corresp="#n3" type="normalized">ʾƎsṭifānos</persName>
<persName><roleName type="title">ʾabbā </roleName></persName>
```

- when these persons are referred to in other records, their title is sometimes encoded with `<roleName>`, sometimes with `<foreign xml:lang="gez">` and sometimes not marked up at all:

BLadd16197:
` It lists the books belonging to <foreign xml:lang="gez">ʾabbā</foreign> <persName ref="PRS10796Tasfo"/>`

BNFet141:
` <roleName type="title">ʾabbā</roleName> <persName ref="PRS4709Giyorgis"/>`

BAVet29:
`Malkǝʾ-hymn to <persName ref="PRS1246AbibBu">ʾabbā ʾAbib</persName>`

BNFet147:
`ʾabuna <persName role="owner" ref="PRS11300KidanaI"/>`

I think that it would make sense to agree to one way and to document it in the guidelines. I would propose to mark up these titles with  `<roleName type="title">` in the person records in the same way as ʾaṣe is marked up, see #642 
Or are there better arguments for having the title in `<occupation>`?

When referring to these persons, I think it makes more sense to use `<roleName>` instead of `<foreign>`. 

Is it better to mark up the title inside `<persName>` or separate from it?

**Comment by MassimoVilla** [comment]
As far as MSS records are concerned, I also think the best solution is to encode ʾabbā and ʾabuna (as well as other titles such as, e.g., qasis, mamhǝr, nagāśi, qes gabaz, rās, makʷannǝn, wayzāro, daǧǧāzmāč, etc.) within `<roleName type="title"/>`, separated from `<persName>`.

**Comment by thea-m** [comment]
I added to the guidelines:

> The title of a person, such as ʾabbā, wayzaro, makʷannǝn etc., should be encoded separately from the `<persName>` with `<roleName>`:
> 
> `It lists the books belonging to <roleName>ʾabbā</roleName> <persName ref="PRS10796Tasfo"/>`

Please change if needed

**Comment by thea-m** [comment]
Can I modified the guidelines according to the newly agreed on use of `<roleName>`:
https://github.com/BetaMasaheft/Documentation/wiki/guidelines#named-entities-and-authority-lists

**Comment by sologebre** [comment]
Yes, you can modify it.
