### ISSUE TITLE
searching with occupation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#646]
The occupation filters in the advanced search don't work as I would expect them to: When searching for "Yohannes", filtering by "Persons" and choosing occupation "ruler" I would expect to see in the result list all persons called Yohannes whose records contain occupation @type="ruler" (PRS10375Yohanne for instance), however, the results show all persons called Yohannes:
http://betamasaheft.eu/as.html?query=yohannes&references=&xmlid=&work-types=pers&persType=ruler
gets the same results as
http://betamasaheft.eu/as.html?query=yohannes&references=&xmlid=&work-types=pers

**Comment by PietroLiuzzo** [comment]
this was a bug. I had written personType instead of persType in the function. this is now fixed

**Comment by thea-m** [comment]
thank you!
