### ISSUE TITLE
overlapping in ms item navigation menu

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#648]
In manuscript records, the sentence "no major relationship with any other item yet" seems to be printed behind the item navigation menu:
![image](https://user-images.githubusercontent.com/19650382/31990051-46ba7130-b974-11e7-9ee9-6da54d12119e.png)

**Comment by PietroLiuzzo** [comment]
the relation boxes will be hidden (as well as that message) when the id navigation is expanded.
