### ISSUE TITLE
no space between ff. and number in pdf

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#649]
e.g. (ff.12r-20r)
http://betamasaheft.aai.uni-hamburg.de/manuscripts/BNFet141/main

**Comment by PietroLiuzzo** [comment]
@SusanneHummel please use the new url betamasaheft.eu.
I cannot see this happening, the spaces are all correctly there.

**Comment by PietroLiuzzo** [comment]
I see, you mean in the PDF export!

**Comment by PietroLiuzzo** [comment]
this is now corrected and will be in the new release

**Comment by PietroLiuzzo** [comment]
thanks!
