### ISSUE TITLE
Umlaute and other special characters in IDs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#653]
many of the Ids created from the EAe index contain Umlaute and other special signs
(for example: http://betamasaheft.eu/as.html?references=&query=&xmlid=%C3%BC&start=1)
Would it make sense to correct them all at once? (Most of them haven't been used yet and many probably never will, but if someone would click on one of these records they would only get an error message)

**Comment by PietroLiuzzo** [comment]
would be good to fix this carefully to avoid missing references. the filenames would have to be changed by hand anyway.

**Comment by thea-m** [comment]
obviously :)

**Comment by thea-m** [comment]
I believe I updated all concerned records, but the old IDs are still found by the search, for example http://betamasaheft.eu/as.html?query=&references=&xmlid=%C3%BC 
Will this be updated with the next release?

**Comment by PietroLiuzzo** [comment]
yes, I will have to reload all the data from git where it should have gone through well, as I see the changes
