### ISSUE TITLE
spaces in the data

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#654]
There are too many wrong spaces in our data, which gives a bad first impression for new users of the app. It would therefore be worthwile to:
- [x]  search our data for the most common instances in which these occur:
before and after `<persName>`, `<placeName>`, `<title>`, `<date>` and `<ref>`
- [x] adapt the schema to mark as wrong `<persName>`, `<placeName>`, `<title>`, `<date>` and `<ref> `without space before and after the element (except punctuation marks after the elements)

**Comment by Gnisci** [comment]
I was thinking about getting round to manually editing those, but if the schema can do it it would be great!

**Comment by PietroLiuzzo** [comment]
Please @Gnisci and @thea-m provide at least one example for each case

**Comment by thea-m** [comment]
- space before and after `persName`:
PRS1291Abreham: `King<persName ref="PRS9038Susenyos">Susǝnyos</persName>`
PRS10350Yeshaq: `He arrived during the reign of King <persName ref="PRS3874eskender">ʾƎskǝndǝr</persName>in <date>1481</date>` (The spaces before date are now already added in the app)

- space before and after `placeName`
PRS10746Zoskale: `to<placeName ref="LOC2804Egypt"/>`
PRS1881Ammehas: `<placeName ref="LOC2246DabraB">Dabra Bǝrhan</placeName>serving`

**Comment by PietroLiuzzo** [comment]
thanks, it will be enough.

**Comment by thea-m** [comment]
(not quite sure why I had added `<title>` to the list, there are not many instances with missing spaces and in all cases it should really be `<ref type="work">`)

**Comment by PietroLiuzzo** [comment]
yep, I am setting the rules, it will be fine anyway

**Comment by thea-m** [comment]
seems to work well :)

**Comment by PietroLiuzzo** [comment]
@thea-m @sologebre @MassimoVilla @Gnisci @eu-genia @DenisNosnitsin1970 @ElianaDalSasso **PLEASE** make sure you pull all changes and avoid pushing unresolved conflicts which github will point out to you, do solve them before if they show up in the desktop application
