### ISSUE TITLE
invalid @type for title

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#658]
`<title type="feast">` and `<title type="placetype">` (in the authority files) are invalid (though not marked as such in the records, which I also validated before committing). Should these two values be added to the schema?
 (I am a bit uncertain since they refer to the nature of the record, not the title itself...but some of the other values we already have for title @type also don't refer to the title itself)

**Comment by thea-m** [comment]
The records in oxygen are valid, but after committing them I receive the oh no e-mail with "invalid.

Error at line 5: value of attribute "type" is invalid; must be equal to "complete", "incomplete", "main", "normalized", "short", "supplied" or "uniform""

**Comment by PietroLiuzzo** [comment]
This is because the authority files in question have no processing instruction at the top to bind them to the BM schema, they will be validate to the latest TEI by oxygen.

**Comment by PietroLiuzzo** [comment]
The information was superfluous since we use the taxonomy for the organization of the terms. I have removed it.
