### ISSUE TITLE
visualization Digitalizavit <ref target="http://www.tau.ac.il/~hacohen/">Ran HaCohen</ref>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#659]
> `Digitalizavit <ref target="http://www.tau.ac.il/~hacohen/">Ran HaCohen</ref>` 

in the Octateuch records is rendered as 

> Digitalizavit Ran HaCohenhttp://www.tau.ac.il/~hacohen/

Was the name supposed to be the link? Or could a space be added between the name and the link?

**Comment by PietroLiuzzo** [comment]
thanks. it was just a template problem, NOT a "white space" issue. It took more time to find where the issue occurred than to fix it. please always remember to provide an example if possible. the one you are seeing when you write the issue is ok.
