### ISSUE TITLE
title not displayed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#660]
in LIT1893Martyr, the title t1 is not displayed normally on the app (it is printed at the top of the page, but not in the entry, where it should precede "Author"). I can find no mistake in the record

**Comment by PietroLiuzzo** [comment]
I see no error at all... could you give an example of what you would expect with another file?

**Comment by thea-m** [comment]
there is no error at all, I was just slightly confused by the fact that the title isn't printed above "author", as in records with several titles. But I see now that this is the normal visualization for all works which contain only one title element. I personally would prefer to have the title repeated for the sake of the uniformity of all records, but this would be of course redundant
