### ISSUE TITLE
print pdf from PRS4428Galawdew

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#661]
An error occurs when one clicks on the pdf icon in PRS4428Galawdew:
The link which opens is http://betamasaheft.eu/persons/PRS4428Galawdew/PRS4428Galawdew.pdf
(once corrected manually, the pdf is printed normally)

**Comment by PietroLiuzzo** [comment]
this was a wrong declaration (not expecting titles with no string type)
