### ISSUE TITLE
spaces

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#662]
@evidence="internal" in `<death>` (in person records) is printed on the app in the following way:

> Death: 1294 ( internal )

Could the spaces between the brackets be deleted?

**Comment by PietroLiuzzo** [comment]
should be fixed, let me know if it appears again, possibly with an example. thanks

**Comment by thea-m** [comment]
I'm sorry, it has been fixed, but now the space between the date and the bracket has also been deleted - I had only meant the two spaces within the brackets, maybe I was unclear. 
For example in these records:
PRS10303Yekunno: `<death when="1285" evidence="internal"/> is visualized as 1285(internal)`
PRS10233Yamana: `<death when="1636" evidence="internal"/>  is visualized as 1636(internal)`

**Comment by PietroLiuzzo** [comment]
you have to wait the release to evaluate if something has been fixed.

**Comment by PietroLiuzzo** [comment]
<img width="178" alt="schermata 2017-11-13 alle 20 36 01" src="https://user-images.githubusercontent.com/508012/32745211-54662584-c8b2-11e7-9074-4f7764b9804e.png">
