### ISSUE TITLE
dates in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#663]
In person records, dates given as values in `<birth>`, `<floruit>` or `<death>` are not visualized on the app if these elements contain text. If the date is not repeated in the text, this information is therefore lost for the user, for example in PRS10191Yaeqob:

```xml
<death when="1557" evidence="internal">He died two years before the death of his brother 
<roleName type="title">ʾaṣe</roleName> 
<persName ref="PRS4428Galawdew">Galāwdewos</persName>, who died in <date>1559</date>. </death>
```
is visualized as:

> Death: He died two years before the death of his brother ʾaṣe Galāwdewos who died in 1559.

I would suggest to either take care to include the date within the textual information or change the visualization rules.

**Comment by sologebre** [comment]
I think it is better to repeat the given dates as values in the text information. I will also correct the case of PRS10191Yaeqob, accordingly.

**Comment by PietroLiuzzo** [comment]
@thea-m an information not visualized is not lost, search criteria will display the result. it was a decision often repeated that any element which contains text (titles, ref, dates, etc) would display its content rather than the values in the attributes if any text node was present in such elements. 
@sologebre it is always good to explicitly repeat the information if it is in a sentence like in the example above, even if you have given the implicit information explicitly in the attribute.

**Comment by thea-m** [comment]
Thank you! I still believe that the information would be somewhat lost to anyone searching for this person without knowing their date of death, but it seems a good solution to state this also explicitly in the content. 
@sologebre , maybe if would be useful to add such decisions to the person guidelines as well, for anyone else who is going to work with person records and didn't follow this discussion?

**Comment by thea-m** [comment]
I have updated the person guidelines, which had only "It is not necessary to give the dating in the content of the element.":

> When the date is given as a value and no further information is provided, it is not necessary to repeat the dating in the content of the element:
> 
> `<death when="1636" evidence="internal"/>`
> is sufficient. However, if the element contains text, the value will not be visualized. The date should therefore be included explicitly in the content:
> 
> ```xml
> <floruit when="1605" evidence="internal">He  refused to side with his brother <roleName type="title">ʾaṣe</roleName> 
> <persName ref="PRS9038Susenyos">Susǝnyos</persName>
> in a struggle against the young <roleName type="title">ʾaṣe</roleName> 
> <persName ref="PRS10198Yaeqob">Yāʿǝqob</persName> in <date>1605</date>.
> </floruit>
> ```

Please close the issue if you agree, or modify the guidelines, @sologebre 
Thank you!

**Comment by sologebre** [comment]
Thank you.
