### ISSUE TITLE
http://betamasaheft.eu/bibliography/ error

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#664]
HTTP ERROR 404

Problem accessing /exist/apps/BetMas/bibliography/. Reason:

    Document /db/apps/BetMas/bibliography not found

**Comment by PietroLiuzzo** [comment]
in resources.xqm a new function to list bibliography has been added which works on the new ptr and ptr/@target indexes added to the collection.xconf. the results can be filters by bibliography type and by collection or a bm id can be added to query for one specific bibliographic work. the result display the record from Zotero, the occurrences and the total number of citations
