### ISSUE TITLE
clavis

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#668]
@MassimoVilla I do not understand why there are cases like LIT4812 where the guidelines here have been followed https://github.com/BetaMasaheft/Documentation/wiki/guidelinesWork#other-clavis-ids and cases instead where a title element has been added ` <title xml:lang="gez" corresp="#t1">KRZ 187</title>`. Is there a discrepancy in the guidelines?

**Comment by MassimoVilla** [comment]
It is simply work in progress, I have not completed the last 10-12 records. The clavis ID has also been inserted in the title following the example of LIT1914Mashaf (cp. #385)
Are the clavis IDs in the title to be removed?

**Comment by PietroLiuzzo** [comment]
no, no need to remove them, thanks for clarification
