### ISSUE TITLE
preyer of manasseh

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#670]
are these two different?

http://betamasaheft.eu/as.html?query=Manass*&references=&xmlid=&work-types=work

**Comment by PietroLiuzzo** [comment]
and can I delete http://betamasaheft.eu/works/LIT1687Legend/main since there is already http://betamasaheft.eu/works/LIT1762Legend/main ?

**Comment by MassimoVilla** [comment]
As to the first question, they are different texts: the former is the well-known Song of Manasseh usually included as part of the Canticles of the Prophets (= LIT1828Mahale) in the Psalter; the latter is a protective prayer including magical names revealed by God to Manasseh, and only found (so far) in ms BAVet53.

**Comment by MassimoVilla** [comment]
As to the second question, LIT1687 deleted (actually in the spreadsheet the latter had alreaby been crossed out but the record survived)

**Comment by PietroLiuzzo** [comment]
thanks for 2! for 1, is this information you have written here in the records? I think it would be very useful in the abstract or as relations. thanks!

**Comment by PietroLiuzzo** [comment]
I hope I have successfully cut out access to the spreadsheet for everyone. this document should not be used for any purpose.
