### ISSUE TITLE
use of persName

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#671]
In PRS10233Yamana, information on variants of a name is given in this way:
`<persName xml:lang="gez" corresp="#n1" type="birth">the Jesuit sources call him “Emana” or “Imano”</persName>`
Is it fine for the element not to contain the name itself, but an explanation? There is no example for this in the person guidelines, maybe it could be added?

**Comment by PietroLiuzzo** [comment]
no, this is wrongly encoded and needs to be corrected according to the guidelines. the sentence can be left in a note, with references to the persName elements which should contain Emana and Imano only.

**Comment by sologebre** [comment]
It is corrected.
