### ISSUE TITLE
links in "Administrative position"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#673]
In the "Administrative position" box in place records, all references to place names are followed by the What Points Here arrow, but the place names themselves don't link to their record. I think that it would be useful if they did, would it be possible to add this?
For example in http://betamasaheft.eu/places/LOC1002Aari/main, the box contains "settlement: Dabub Omo" followed by the What Points here arrow. I think it would be useful if Dabub Omo would link to http://betamasaheft.eu/places/LOC6543SouthOmo/main

**Comment by PietroLiuzzo** [comment]
![schermata 2017-11-15 alle 11 13 36](https://user-images.githubusercontent.com/508012/32830621-11857e3c-c9f6-11e7-8899-76e68df35fc6.png)

**Comment by thea-m** [comment]
thank you!
