### ISSUE TITLE
keywords in advanced search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#674]
The keyword menu in the advanced search might be confusing to users not aware of its genesis:
There are many unused keywords (mainly for feasts), and the distinction between some keywords is unclear (for example Christian, Christianity and Christian Literature). 

Would it be possible for the definition which appears on hovering above the single keywords to be different depending on the keyword? I.e. "Type of faith" for the various confessions, "Literary genre", "Type of addition" (It is currently "types of places", which should be changed).
Or could definitions for the single keywords be displayed? Maybe it would be enough to simply provide the link to http://betamasaheft.eu/authority-files/list on the right of the boxes, below "Select more general filters"

I'm also not sure about the use of the keywords for feasts. Are these for all texts and images dealing with these feasts? They have never been used as far as I'm aware

**Comment by PietroLiuzzo** [comment]
For most keywords there is no definition. what would we be displaying? a link in a selector for a search filter would be very confusing.

**Comment by PietroLiuzzo** [comment]
IMHO, inconsistencies in assigning keywords should be fixed in the data, not worked around in the visualization. on the other side perfect clarity is a dream, users will have to be guided anyway

**Comment by thea-m** [comment]
There are actually no inconsistencies in assigning keywords in this case, but the "Keywords" menu displays different "keywords" which we use in different contexts. ChristianLiterature is used for works, Christianity for persons and Christian for feasts (this one is not used); one Aksumite is a confession and the other the period keyword, etc.
How could we fix this in the data? Could we change their titles for disambiguation, for example to AksumitePeriod, AksumiteConfession?

**Comment by PietroLiuzzo** [comment]
If the problem here is then just the organisation of values for options in the keywords selector, and  you want them grouped as they are in the taxonomy, this is what should happen now.
