### ISSUE TITLE
Alef in text search

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#676]
Typing in text search in the app has been relaxed to facilitate the search (e.g. laryngeals, sibilants, emphatics, long vowel ā), but Alef is still required.
So, for instance typing "Ewostatewos" and "Entones" (which are the inputs a user is most likely to type, rather than ʾEwosṭātewos and ʾƎnṭonǝs) gives no output. This could give an external user the wrong idea that no work/person/etc. records are extant for those individuals.
It would be good if forms like Entones, 'Entones (so simple ' instead of ʾ) would all point in the search to ʾƎnṭonǝs. 
I also believe that to equate ' to ʾ (and also to ayn ʿ) is much helpful. E.g., the most likely way an external user would look for _Taʾammǝra_ (the cycle of miracles) is in my opinion by typing the form Ta'ammera, and so far forms like Ta'ammera, Te'zaz, Ya'qob give no results (or in the last case only partial results due to other reasons).

**Comment by PietroLiuzzo** [comment]
this has been requested before several times. I cannot add something which has not been entered, so the initial aleph or ayn. but as it should be in the guidelines, you can use a tick ` for that position. it is also a keyboard available character but has the advantage of not being a reserved character like '  . try Ta`ammera instead of Ta'ammera or `Ewostatewos. Moreover there is a keyboard which allows to enter any of these values.

**Comment by PietroLiuzzo** [comment]
you are right that this is not specified in the help box, I will add this information

**Comment by PietroLiuzzo** [comment]
I would also be interested to know what "gives no output" means. I get several results with any of the searches you proposed.

**Comment by MassimoVilla** [comment]
No pertinent results. I limited my search to work records, and Entones or 'Entones give no results. One result is given for person records, but it is wrongly spelled (Ǝnṭonǝs instead of ʾƎnṭonǝs). Ewostatewos gives plenty of results in many repositories, because they are forms written with no initial Alef (yet they should), but no one pointing at any of the four records of the Life of ʾEwosṭātewos.
As for Yaqob, two results are given: one is that of Yaqob Beyene, a scholar; the latter is the 15th-cent. king Zarʾa Yāʿǝqob, but only because in some documents his name is spelled Yāqob.

**Comment by PietroLiuzzo** [comment]
this is all correct, the search works as expected and cannot do more, as infering that a user typing Yaqob actually means Yāʿǝqob. The second can be found entering Ya`eqob, where the machine applying the given substitutions is actually searching for

> Ya`eqob Yä`eqob Ya`ǝqob Ya`əqob Ya`ēqob Yä`ǝqob Yä`əqob Yä`ēqob Yaʾeqob Yaeqob Yaʿeqob Yäʾeqob Yäeqob Yäʿeqob Yaʾǝqob Yaǝqob Yaʿǝqob Yaʾəqob Yaəqob Yaʿəqob Yaʾēqob Yaēqob Yaʿēqob Yäʾǝqob Yäǝqob Yäʿǝqob Yäʾəqob Yäəqob Yäʿəqob Yäʾēqob Yäēqob Yäʿēqob

I cannot consistenlty know what people have in mind when they type something.

you could even try the fuzzy search, entering for example Yaqob~0.5 as in the guidelines
below some sample searches

- http://betamasaheft.eu/as.html?query=Yaqob~0.5&references=&xmlid= 
- http://betamasaheft.eu/as.html?query=%60Entones&references=&xmlid=&work-types=work
- http://betamasaheft.eu/as.html?query=%CA%BEEwos%E1%B9%AD%C4%81tewos&references=&xmlid=&work-types=work
- http://betamasaheft.eu/as.html?query=%60Ewostatewos&references=&xmlid=&work-types=work
- http://betamasaheft.eu/as.html?query=Ya%60eqob&references=&xmlid=&work-types=work

**Comment by PietroLiuzzo** [comment]
#561

**Comment by PietroLiuzzo** [comment]
@MassimoVilla please close the issue if the answer and the proposed action to take under #561 is answering your request.
