### ISSUE TITLE
Standardize spelling

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#677]
The spelling of some Gǝʿǝz words should be consistently given, since there exist competing forms, especially due to the presence of a shwa after ʾ or ʿ. I have myself sometimes altered an existing spelling form, but not regularly.
In the small list below, the former is etymologically better, because it relies on the Semitic pattern, whereas the latter has been used by EAe and relies on pronunciation.
Yāʿqob or Yāʿǝqob
Tǝʾzāz or Tǝʾǝzāz
ʾAʾlāf or ʾAʾǝlāf
tǝsbǝʾt or tǝsbǝʾǝt,
etc.

One more instance:
Taʾammǝra (as used in the Encyclopaedia Aethiopica) or Taʾamra (as used in Ethio-SPaRe)

**Comment by PietroLiuzzo** [comment]
If this are variants in titles transcriptions, both should be given in the data, instead of replacing them.

**Comment by thea-m** [comment]
It would probably make sense for us to adopt the same solution as Traces in these cases? I believe that they generally follow Leslau, which would give us:
tǝʾǝzāz
ʾaʾǝlāf
tǝsbǝʾt
taʾammǝr

We also had inconsistencies with ba-ʾənta/baʾənta

**Comment by MassimoVilla** [comment]
It seems, according to Traces (I only had an informal conversation with Susanne), that ba-ʾənta/baʾənta is considered as one single lexeme. So, contrary to other prepositions like ʾəm-wəsta and so on, it should not be hyphenated.

**Comment by PietroLiuzzo** [comment]
@MassimoVilla will update guidelines after checking the traces decisions with @SusanneHummel guidelines will include examples as are in the current traces documentation for use in BM, in the lexicon/parser and in dillmann app

**Comment by thea-m** [comment]
I think that this can be closed. Here are the relevant guideline pages for reference:
http://betamasaheft.eu/Guidelines/?id=transliteration-principles
http://betamasaheft.eu/Guidelines/?id=dubious-spelling
As always, new issues should be open for any particular new uncertain cases
