### ISSUE TITLE
error in search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#678]
there is an error when searching for "serʿata mangest" in work records:
http://betamasaheft.eu/as.html?query=%22ser%CA%BFata+mangest%22&references=&xmlid=&work-types=work

**Comment by PietroLiuzzo** [comment]
was this working before?

**Comment by thea-m** [comment]
before the release? I don't know, I can't remember whether I already performed this exact search

**Comment by PietroLiuzzo** [comment]
ok, so is no regression.

**Comment by PietroLiuzzo** [comment]
- http://betamasaheft.eu/search.html?query=%22S%C7%9Dr`ata+mangest%22

**Comment by thea-m** [comment]
I get the error when searching with a lower case first letter:
http://betamasaheft.eu/as.html?query=%22ser%CA%BEata+mangest%22&references=&xmlid=&work-types=work
http://betamasaheft.eu/as.html?query=%22ser%60ata+mangest%22&references=&xmlid=&work-types=work

(only in this case, for instance http://betamasaheft.eu/as.html?query=%22ser%60ata+geber%22&references=&xmlid=&work-types=work works as expected)

**Comment by PietroLiuzzo** [comment]
The search is correct, but the 1280 options generated build too long a string for the query search. 
#561 should anyway stress that a fuzzy search is a short cut for any substitution and is indeed always preferable. A fix will be put in place to limit the length of the query.

**Comment by PietroLiuzzo** [comment]
I have added a function to limit the number of options based on the string lenght and added the substitutions for upper case transcription letters

**Comment by PietroLiuzzo** [comment]
@thea-m please test now http://betamasaheft.eu/search.html?query=%22ser%CA%BFata%20mangest%22

**Comment by thea-m** [comment]
perfect, thank you!
