### ISSUE TITLE
INS0341DL not found in search

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#681]
INS0341DL isn't among the results when searching 
http://betamasaheft.eu/as.html?query=%22dabra+libanos%22&references=&xmlid=&work-types=ins
maybe because @subtype="institution" was missing?

**Comment by PietroLiuzzo** [comment]
that should not be the case, it is more likely that the file was not stored correctly. now this issue does not appear to be any more there.

**Comment by thea-m** [comment]
I still don't find it with the same search:
![image](https://user-images.githubusercontent.com/19650382/33429191-13b122c4-d5cc-11e7-99d3-b901ee0bdf20.png)

**Comment by PietroLiuzzo** [comment]
the record was created probably by hand and the type was wrongly assigned (place instead of ins)
