### ISSUE TITLE
Arabic transliteration

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#682]
Which transliteration system do we use for Arabic in Beta maṣāḥəft and Zotero? It has never been stated anywhere explicitly, as far as I'm aware (we don't have a lot of transcribed Arabic in our records currently, but I think it nevertheless makes sense to clarify this in the guidelines now).

I have in general used the same transliteration as the EAe, without ʾiʿrāb (but contrary to the EAe with initial ʾ for hamzat qaṭʿ). For example:

- _Šarḥ sabab intiqāl mamlakat Sulaymān malik ʾIsrāʾīl ʾilā bilād an-naǧāšīya allatī hiya al-ḥabaša_ 
- _Kitāb al-bustān wa-qāʿidat al-ḥukamāʾ wa-šams al-ʾādāb_  

(Only in BM as I haven't yet added Arabic works to Zotero)

However, there have been many Arabic titles added recently to Zotero which do not transcribe hamzat qaṭʿ (For example bm:IHABook833, Aḫbār Makka wa-mā ǧā’a fīhā min al-āṯār), which also corresponds to the Arabic example in the Zotero HLCES bibliography workflow.

**Comment by abausi** [comment]
Out of economic reasons, I would suggest to follow the Zotero HLCES bibliography style. But if there is any reason against, we can discuss this in our meeting.

**Comment by PietroLiuzzo** [comment]
please note that the almost 1000 new records in the EthioStudies group which are inside the ihabiblio collection **SHOULD NOT BE EDITED OR MOVED**.The colleagues of the IslHornAfr project are checking these records for correctness and there is a likelihood that I will remove the entire lot and add it anew in a corrected form.

beside this they do have plenty of titles in arabic and it would make sense for the matter of transliteration to follow with the standard they are using

**Comment by thea-m** [comment]
I understand, nevertheless I find it illogical to transcribe initial ʾ in Gəʿəz and not in Arabic (especially within the beta masaḥəft records)

**Comment by PietroLiuzzo** [comment]
@thea-m will update the guidelines and close the issue
