### ISSUE TITLE
@xml:lang in incipit and explicit

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#683]
Text given in `<incipit>` and `<explicit>` without `@xml:lang="gez"` is (logically) not recognized as Gəʿəz and not linked to Dillmann. However this encoding is conforming to our guidelines, which have:

> incipit and explicit will contain a locus and the original text directly within the element. their language will be assumed to be the one given in textLang if not otherwise specified. 

We have actually all mostly indicated the language even if identical to textLang, there are only a few  instances of `<incipit>` without the attribute, for example BAVet36#ms_i7 or BNFet107#p2_i2. 
I would propose to change the guidelines to include @xml:lang in `<incipit>` and `<explicit>`, or was there a specific reason I ignore to do otherwise?

**Comment by MassimoVilla** [comment]
I agree with Dorothea's proposal to change the guidelines and make it clear the indication of the language.
As for BAVet36#ms_i7, @xml:lang has not been added because the text is actually a Creed in a sort of "Latin" (more or less Latin: Kreyo ʾundapateʾer ʾani pitete...), written in Ethiopic script.

**Comment by thea-m** [comment]
I've changed the guidelines to:

> `incipit` and `explicit` will contain a `locus` and the original text directly within the element. Their language should always be specified, even if identical to the one given in `textLang`.

Thanks for the clarification, @MassimoVilla, the example was wrongly chosen!
