### ISSUE TITLE
Keywords not appearing in DecoNote

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#685]
Even keywords that have been inserted in the schema for DecoNote under the elementSpec[@Ident='term']. (l.344) are giving me some issues.

For example, if I type 
`<term key="censer"/>` I get nothing and if I type `<term key="censer">censer</term>` I get the term but it does not lead me to the keyword.

 To illustrate the point this:
![image](https://user-images.githubusercontent.com/31648831/33183236-51e8400e-d077-11e7-9387-685d074b4851.png)

Gets you this:
![image](https://user-images.githubusercontent.com/31648831/33183241-5854a1b2-d077-11e7-857e-620556b0afba.png)

**Comment by PietroLiuzzo** [comment]
let me try to translate. you would like the `term` elements inside desc in `deconote` to be displaied in the app as links to the main view of that term or to the list of occurrences or to a particular query in the decoration search functionality. as for the content of the term you would like it to be replaced in the visualization by its canonical name if no content is given for the element `term`. 
the modification of the schema provides you only with the validation of those keywords and with the contextual menu in oxygen when you input the space or the first letter of the attribute value.

**Comment by Gnisci** [comment]
Dear Pietro, thanks for getting back to me. Yes, you are spot on!
The first function is really not vital, if it is complicated to set up, you will see the keywords in the keyword section anyway. 
The second is more important, if the keyword is provided in the form  `<term key="FirstSolomonicStyle"/>` I think it should be visualized with its canonical name? The advantages are: 1) it's much quicker to encode and takes up less space making the file more readable; 2) you ensure that the terms will be use consistently across the project.

**Comment by Gnisci** [comment]
Thank you for solving this!
