### ISSUE TITLE
No space after DecoNote ending without <q> element

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#686]
Currently, you get a space after `DecoNote` that ends with a `<q/>` but you don't get a space if the `DecoNote` does not end with a  `<q/>`

See no space between 2 and 3, but space between 3 and 4
![image](https://user-images.githubusercontent.com/31648831/33227239-4aa51f64-d19f-11e7-8b76-3551342674df.png)

**Comment by PietroLiuzzo** [comment]
a reference to the resource in question would have helped me a lot
