### ISSUE TITLE
occupation filter

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#687]
the occupation filter for persons in the advanced search doesn't load

**Comment by PietroLiuzzo** [comment]
I cannot reproduce this issue, it loads with no problems.

**Comment by thea-m** [comment]
still doesn't load for me, neither on the laptop...all other filters work fine

**Comment by PietroLiuzzo** [comment]
you will need to give me more details about what you are trying. I am opening the advanced search, selecting persons and then occupation and the menu loads immediately

**Comment by thea-m** [comment]
works now
