### ISSUE TITLE
Marking-up of the Legends

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [BetaMasaheft/Documentation#690]
An issue for tomorrow regarding the miniatures: I think it would be useful to mark up legends using special mark-up options, so that we could be able, for instance, search for all legends in the database, independently from the miniatures (or all miniatures with the legends). For the moment, a legend is to be recorded as `<q ></q>` only.

**Comment by Gnisci** [comment]
From my many conversations with @PietroLiuzzo my understanding is that, if `<q>` is used inside `decoNote` it will be possible to search for `<q>s`  that are found only in` decoNotes`.

**Comment by PietroLiuzzo** [comment]
@Gnisci is right. this is already possible. try searching ወንጌላት which is in the 3 miniature description in BNFet32 selecting in the advance search "Description" and limiting to manuscripts.

http://betamasaheft.eu/as.html?query=ወንጌላት&element=desc&references=&xmlid=&work-types=mss

if you want I could edit the list there to have something which says "Legends" and searches only q elements in decoNotes.

**Comment by PietroLiuzzo** [comment]
you can also use the xpath search to go precisely to one item with a certain pattern

**Comment by DenisNosnitsin1970** [comment]
To have "Legends" in the list would be helpful, but also "Captions", if possible? (as it appears that these have different functions in the miniatures)

**Comment by PietroLiuzzo** [comment]
what is the semantic distinction? how would the markup differ between these two cases?

**Comment by Gnisci** [comment]
Just had a conversation with @DenisNosnitsin1970  about this. Given that a number of approaches to the problem are possible I would distinguish between:

1. Legends = A sentence which provides information on the main thematic content of the image
2. Caption = A word or sentence which provides information on secondary elements present in the image

In the guidelines, I suggest to use `<q>` for the former and `<foreign>` next to the relevant secondary element for the latter, but of course this is open to debate

**Comment by PietroLiuzzo** [comment]
what are the cases in which you would actually profit from a search that makes this distinction? It sounds to me a bit of an overcomplication. we are already encoding this descriptions very deeply, if there is not a direct interest in this and a real use which would make it indispensable compared to the already available ways to get to this information, I would avoid this distinction and stick with legends only, adding a filter to search only on these.

**Comment by Gnisci** [comment]
Just to clarify, above I was simply reporting a discussion I had with Denis. My personal opinion:

1.   **Conceptually** it is _possible_ to make such a distinction, but it is open to debate whether it is necessary or profitable to do so.

2.  In **searching terms** I don't see a necessity to make this distinction. The search function could easily highlight all the elements marked as `<q>` and `<foreign>` together, without any distinction.

3. In **terms of readability and fruition** I do see it an advantage in providing the Legend, as the main title of the subject at the bottom of the `decoNote`, and the captions in relation to the detail to which they refer, as illustrated in the example below.

![image](https://user-images.githubusercontent.com/31648831/33343850-1be06e00-d487-11e7-9ab0-020b803b2f4d.png)

4. In **Encoding Terms** I think it is not at all complicated to do this, and it leaves the door open for different sorts of queries in the future if one where to change his mind on the matter. Obviously, I trust your judgment more than mine on such issues, so if you think it creates an unnecessary complication, I don't see this as a fundamental issue to uphold.

These are my two cents on the matter! 

w, but if this creates complications we can easily drop the matter.

**Comment by PietroLiuzzo** [comment]
this is now encoded like this 

`````xml
<decoNote type="miniature" xml:id="d5">
<locus target="#8r"/>
<desc>
A miniaure of the
<ref type="authFile" corresp="AT1017WomenAtTomb"/>
, featuring
<persName ref="PRS6820MaryMag">Mary Magdalene</persName>
and Marta, respectively identified by the captions
<foreign xml:lang="gez">ሥዕለ፡ ማርያ፡ መግደላዊት</foreign>
and
<foreign xml:lang="gez">ሥዕለ፡ ማርታ</foreign>
. The two Holy Women hold a
<term key="censer">censer</term>
in one hand and raise their other hand to their chest. They advance towards an
<term key="angel">Angel</term>
who announces the Resurrection and is placed under an
<term key="arch">arch</term>
. Two guards, each with a
<term key="sword">sword</term>
<term key="shield">shield</term>
<term key="vestment">pointed hat</term>
, are sprawled beneath them. The scene is placed under a large
<term key="architecture">dome</term>
surmounted by
<term key="cross">three crosses</term>
.
<q xml:lang="gez">መልአክ፡ ኀበ፡ ተናገሮን፡ ለአንሰት፡</q>
</desc>
</decoNote>
`````

I am not sure I understand what you mean by 

> `<foreign>`  next to the relevant secondary element

let me try to reformulate this. here we could make this distinction in the search (tell me if it coincides with what you said) by searching inside `foreign[@xml:lang='gez']` only aiming at getting gez text which is not the legend, which will often contain also the text of the captions from what I understand. the search in the legend is instead limited to the `<q>` contained in the `decoNote`.

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @Gnisci you can now find here two text search boxes
http://betamasaheft.eu/decorations

One searches inside `q` (legends) the other inside `foreign[xml:lang='gez']`. you can also use both and of course you can use them with the other filters as well.

you will also notice that I have added thumbnails where we have links to available images and a proper @facs inside locus in the decoration

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 what you initially asked is possible in this list. please close issue if satisfactory.
