### ISSUE TITLE
Zotero Bibliography Guidelines: Works written in two Languages

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#698]
I believe we could add an entry for the guidelines for works written in two languages? Something along the lines of:

1) For works written in two languages, provide the title in each language in order of appearance separated by a space and a slash (or n-dash?) e.g. "Santi Guerrieri a Cavallo: Tele Etiopiche di Qes Adamu Tesfaw / Warrior Saints on Horseback: Ethiopian Paintings by Qes Adamu Tesfaw"

**Comment by PietroLiuzzo** [comment]
@FrancescaPanini what do we have to do for these cases?

**Comment by PietroLiuzzo** [comment]
@Gnisci order of appearance in the book?

**Comment by Gnisci** [comment]
@PietroLiuzzo , just stating the obvious, but best to do so: if the English title appears after the Italian title it will be inserted after it, not before just because it is in English

**Comment by PietroLiuzzo** [comment]
we have since then worked quite a lot on the style and guidelines documentation with @FrancescaPanini who uses them daily. Eugenia did start this work although, so no problem!

**Comment by Gnisci** [comment]
I have not heard back from anyone on this, so I am going to suggest a set of guidlines and upload them to the WIKI, if someone thinks there is an issue with these, please note it down here.

31. For works written in more than one language please provide the complete title in each of the given languages following the order of appearance in the publication. Separate each title with a space followed by a / symbol.  So for instance

>  I molti volti dell'arte etiopica: Atti del IV Convegno Internazionale di Storia dell'Arte etiopica / The many Faces of Ethiopian Art: Proceedings of the IV International Conference on the History of Ethiopian Art

**Comment by FrancescaPanini** [comment]
Hi Jacopo,
Before updating the guidelines, let me first look into this, please. I need
to make other changes to the guidelines in any case, but I needed to finish
something else first. I will add this to my to do list and get back to you
as soon as possible.

Regards
Francesca

**Comment by FrancescaPanini** [comment]
Ciao Jacopo,
I have now looked into it.

I think the use of a solidus (/) in this ihnstance is not appropriate: it is not a type of use which OSM envisages for a solidus and is graphically not so nice.

I think a simple full stop is more appropriate in this case. I tried to reconstruct the record you used as an example, although I had to rely on information found online, so it might contain mistakes (please, let me know if it does):
Raineri, O. 1996. _Santi e guerrieri a cavallo: Tele etiopiche, Tele di Qēs Adamu Tesfaw. Warrios Saints on Horseback: Ethiopian Paintings, Paintings by Qēs Adamu Tesfaw_ (Clusone: Ferrari Edizioni, 1996)

I hope this is OK.

Francesca

**Comment by Gnisci** [comment]
Of course, thanks, the important thing is that there is a guideline to achieve consistency!
