### ISSUE TITLE
More than 1 message with ATID

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#699]
Dear Pietro,

In [ESssb008] http://betamasaheft.eu/manuscripts/ESssb008/main  #D4 (91r) I am getting a "more than 1" message before the ATID1035HolyMan

![image](https://user-images.githubusercontent.com/31648831/33556862-acad0a92-d905-11e7-93a0-60e3131b0a74.png)

I did the following: 1) update taxonomy; 2) create new authority file on app; 3) download the authority file in the "new" folder and commit it; 4) move the file from new folder to the ArtThemes Folder and commit again. I checked Git, and it has only one copy of the ATID, which is also not showing in http://betamasaheft.eu/authority-files/list

Incidentally, other art keyword I added in the past days  (same process described above) are also not showing in the Authority Files index.

This commit: 
https://github.com/BetaMasaheft/Authority-Files/commit/03ee291702fffc295fc6eb5bb782892bb655ac8e 

I've been doing exactly the same thing up to this point, so I am wondering if this is really an error on my end?

**Comment by PietroLiuzzo** [comment]
it is not an error on your end, there are several reasons why this might not go through. it just happens. and is easily fixed.

**Comment by PietroLiuzzo** [comment]
incidentally: which other keywords?

**Comment by Gnisci** [comment]
donordepiction
gestureblessing
gesturegrief
gestureorans
gesturewitnessing
saluspopuli
hodegetria
ATID1035HolyMan

**Comment by PietroLiuzzo** [comment]
do you still have problems with these? I cannot see any issue.

**Comment by PietroLiuzzo** [comment]
if not, please close the issue

**Comment by Gnisci** [comment]
The problem is that they don't appear on the authority-files page (the keywords I listed above still do not appear):

![image](https://user-images.githubusercontent.com/31648831/33564482-e37c5bc6-d91a-11e7-8c15-b1fa369d0450.png)

If this is an issue of which you are aware, then please feel free to close it

**Comment by PietroLiuzzo** [comment]
have a look now (there was a missing > which stayed there at some point and prevented further update)
