### ISSUE TITLE
relation used for groups

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#700]
I have just noticed that our guidelines apparently don't state which relation should be used in the records of groups of persons. They have the interesting example 
```xml
<relation 
       name="contains" 
                     active="PRS10775Trinity" 
                     passive="PRS5684JesusCh">
                </relation>
```
which is wrong. Should it be snap:Group, which has been used occasionally in the records? Or is it redundant to list the members in the group record, since their appartenance to the group is indicated in the individual person records by saws:isMemberOf?

**Comment by PietroLiuzzo** [comment]
yep, this is wrong. please go ahead and fix it if you have an opinion about how to encode this right or there are instances which you consider better.

**Comment by PietroLiuzzo** [comment]
it is redundant tu use snap:group, but i see no point to remove that information.
if saws:isMemberOf is use, then lets document that in the GL. 
trinity is also the worst possible example. please, if possible lets pick another more sensible one with a group of monks, for example.

**Comment by PietroLiuzzo** [comment]
thanks @thea-m !
