### ISSUE TITLE
list of ids used 

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#704]
@MassimoVilla asked for a list of the ids used for manuscripts, to be able to use the same id structure for the mss from the same collection and institution in case these are created by different people. this will also have to be linked from the guidelines in the id creation section, 
this will be soon available and will dinamically build 
a list of institutions, a list of collections associated with that institution, a list of the id for each collection in the institution.

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/listIds

**Comment by MassimoVilla** [comment]
weirdly I cannot access, but user name and password are correct, I am sure.

**Comment by PietroLiuzzo** [comment]
should be al set now

**Comment by PietroLiuzzo** [comment]
the issue should remain closed for review during the next release
