### ISSUE TITLE
searching for shelfmark

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#705]
It would be useful to be able to search for manuscripts with their shelfmark or part of their shelfmark, i.e. the content of `<idno>`. This would also allow us to find manuscripts by searching for previous or alternative shelfmarks or other identifiers, so that one could find for example FSUor14 by searching for "14" or "Rüpp. III, 2".
Would it be possible to add such a function to the search, similar maybe to the "Look up by ID" function?

**Comment by PietroLiuzzo** [comment]
In the next release you will find this behaviour in the main search as default. e.g. it will search also `idno` elements contents when running a simple search

**Comment by thea-m** [comment]
Thank you!
