### ISSUE TITLE
Zotero Bibliography Guidelines: Name Suffixes

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#707]
While touching on the matter of editing the guidelines, I think it may be beneficial to be systematic also with the ways in which we deal with suffixes (e.g. Sr. and Jr.) and honorifics (Esq. Lord, etc.) added to names and given in the referenced work?

**Comment by FrancescaPanini** [comment]
Hello,
and thanks.

Oxford Style Manual, page 351: 'Titular prefixes (Sir, Revd, Dr, Captain,
etc.) are not needed unless their removal would mislead'. Example given to
dfine what mislead means: Wood, Mrs Henry...

Hence the author's title should not be given in bibliography. For the same
reason, in bibliography I would also not give "junior" and "senior" as they
do not form part of the name.

Hope this helps,
Francesca

**Comment by PietroLiuzzo** [comment]
please @FrancescaPanini updated the bibliography guidelines in the wiki with this and close issue.

**Comment by Gnisci** [comment]
@FrancescaPanini  I've added that in section 4 of the guidelines, thanks.
