### ISSUE TITLE
app menu (advanced search)

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#708]
I find it a bit confusing that the upper menu on the advanced search page isn't the same as on the rest of the app. It seems to be an older version? (Indexes and Bibliography are listed separately, not under "resources", Hi Dorothea! has no "personal page" and "partners" (but authority files), and manuscripts has no submenu)

**Comment by PietroLiuzzo** [comment]
yes, this has always been like that because the advanced search has to use a different logic from the other app views. I will update that template
