### ISSUE TITLE
more than one <title> in a <msItem>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#709]
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fmanuscripts%27%29%2F%2Ft%3AmsItem%2Ft%3Atitle%5Bposition%28%29%3D2%5D

Split from #548

**Comment by MassimoVilla** [comment]
fixed BLadd16190, BAVet108, and BAVet74.

**Comment by thea-m** [comment]
fixed the BL orient mss
