### ISSUE TITLE
same numeric part assigned to more than one record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#716]
I just created the records LIT4862ChronicleZadengel and LIT4861ChronicleYaqob through the app and then noticed that there were already two records with these numbers, also saved in the "new" folder: LIT4862OntheB and LIT4861Homily (there is also LIT4863Theodore), created in December. I don't know whether these records were created manually or through the app, but in any case, shouldn't my new records from today have started with LIT4864? (I can of course easily rename them, but I was wondering whether there might be some underlying synchronizing problem?)

**Comment by MassimoVilla** [comment]
I created those records manually because I was concurrently working on a number of homilies by John Chrysostom and other Fathers of the Church, and it was easier to do it directly on Oxygen.

**Comment by PietroLiuzzo** [comment]
the issue with the github hook was already there since December, nobody reported it before, hence additional problems. I am working on it.

**Comment by PietroLiuzzo** [comment]
the hook is fixed and should be working as expected, please close or reassign this issue

**Comment by thea-m** [comment]
thank you
