### ISSUE TITLE
"more than 1" keyword

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#717]
In the new record creation form, there is the message "more than 1 Homily/Prayers/Translation" - this must be due to some mistake in our data, but I can't find it. When selected, these keywords are transferred correctly exactly like all the others to the newly created record.
![image](https://user-images.githubusercontent.com/19650382/34674180-3962d90e-f485-11e7-98ea-4202e1786032.png)
(and could you also correct "then" in the error message to "than"? Thanks :))

**Comment by PietroLiuzzo** [comment]
should be ok now

**Comment by thea-m** [comment]
still looks the same

**Comment by PietroLiuzzo** [comment]
please refresh

**Comment by PietroLiuzzo** [comment]
<img width="1059" alt="schermata 2018-01-11 alle 10 42 49" src="https://user-images.githubusercontent.com/508012/34818808-373167de-f6bc-11e7-9620-26a3797706d5.png">
