### ISSUE TITLE
occupation

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#718]
Is there a difference in the use of `<occupation type="political">ruler</occupation>` and `<occupation type="ruler">...</occupation>` (containing the specific type of rulership)? Both have been widely used (for example, PRS7079Mikael, PRS1774Alula, PRS10076WasanS, PRS10441Yonas and many more). Could you maybe document this in the guidelines?

**Comment by thea-m** [comment]
@sologebre ?

**Comment by sologebre** [comment]
Yes, there is a clear difference between <occupation type="ruler"> </occupation> and <occupation type="political">ruler</occupation>. <occupation type="ruler"> </occupation> refers specifically an occupation of a king or a queen or in the contemporary system of political administration can it be a president (head of the state) or prime minister (in the parliamentary form of government). Therefore, in this case <occupation type="ruler"> </occupation> uses for all Ethiopian kings, while <occupation type="political">ruler</occupation> refers largely a person whose occupation belongs to the category of political but he/she can be a ruler (governor of a province), courtier and other political posts. It also entails the various occupations of medieval civil offices of the Christian kingdom of Ethiopia.
