### ISSUE TITLE
document use of bm:wifeOf and other relationships

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#721]
document the use of the relationsship bm:wifeOf and the absence of relationships between kings and their concubines

**Comment by sologebre** [comment]
Very little is known in Ethiopian history about the names of the concubines of kings. It's not well documented. However, it is known that there were kings who had more than one wife, and so I think we can also record the relationship of these women bm:wifeOf. In fact, however, there were royal wives of the kings who received a royal name with the king at the time of coronation. Then, in this case, we also document the royal name as an additional name for these women.
