### ISSUE TITLE
PRS11836ZawaldaM lost

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#727]
"Dear Dorothea, unfortunately PRS11836ZawaldaM already exists! Please, hit the button below and try a different id." appeared before I could download the record

**Comment by PietroLiuzzo** [comment]
as it should... could you please tell me what you were trying to do and what you expected which did not happen?

**Comment by thea-m** [comment]
I was creating a new record for a Zawalda Maryam, filled in the form, clicked on create entry, went to do something else while the page was loading and came back to find "Dear Dorothea, unfortunately PRS11836ZawaldaM already exists! Please, hit the button below and try a different id." How can I retrieve the record PRS11836ZawaldaM  now? It doesn't appear in oxygen

**Comment by PietroLiuzzo** [comment]
ok, so everything is fine, but the time you are waiting is not. the file is there, no worries.
http://betamasaheft.eu/persons/PRS11836ZawaldaM/main
