### ISSUE TITLE
 collation with many added leaves

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#728]
see e.g. GAet7.
quire 24 renders incorrectly, as the second and third leaves appear conjoined with fourth and fifth respectively, whereas it seams these two, four and five are a bifolium, the only in the quire, as far as I understand.

@ElianaDalSasso please could you check the description and confirm the quire structure?

the app has a problem in rendering this situation which needs to be investigated

**Comment by ElianaDalSasso** [comment]
Yes I confirm the structure. q24 has 6 leaves where 1, 2, 3, 6 are single leaves; 4 and 5 are a bifolium
6, stub before 1,
1 added,
2 added,
3 added.
