### ISSUE TITLE
names of troops and regiments

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#731]
Recently the question has come up how to mark up names of regiments in texts. There have apparently already been `<personGrp>` records created for troops or regiments, which seems to work fine, but I believe that this use has not been documented in the guidelines. It would be very helpful if those who have worked with this could add a short description of the use in the guidelines (or an example might be enough).

**Comment by PietroLiuzzo** [comment]
ok, I have seen that in the versioning. doesn't this need a bit of discussion before being documented and accepted?

**Comment by thea-m** [comment]
@eu-genia and @sologebre had worked with this...
Regiments and other military unities (about which I know nothing...) in fact probably are not "abstract" groups of persons. What would be other possibilies of marking them up? As a kind of "institution" (not in the sense of repository...)? There seems to be a need for it, since two persons already did it.
