### ISSUE TITLE
output of field short title in Word Zotero plugin for bibliography

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#734]
When inserting a bibliography (not the single reference, but the bibliography as list of all references, usually at the end of the contribution) through Zotero in Word, if the record contains a "Short title" in the relevant field, the short tile is printed before the name of the author: this should not be and there should be no printed short title. I verified this condition for the "HLCES (long names)" style

**Comment by PietroLiuzzo** [comment]
can you please provide reference (link to zotero or simply title and author) to the example record you are using which is giving the wrong result in the bibliography?

**Comment by abausi** [comment]
take for example the entry Debié, 2015, "L’Écriture de l’histoire en Syriaque", in EthioStudies; for my use I had to delete the Short Title filed, that now I re-entered for the puropose of testing

**Comment by PietroLiuzzo** [comment]
Yours seams to me at the moment the cleanest solution anyway. or is that short title needed somewhere else?

**Comment by PietroLiuzzo** [comment]
moved to https://github.com/BetaMasaheft/bibliography/issues/3
