### ISSUE TITLE
output of encyclopaedia entry in Word Zotero plugin for reference zotero 

### ISSUE THREAD

**Issue by abausi** [BetaMasaheft/Documentation#735]
the present output in Word is as follows:

‘Däbrä Ṣǝyon’, EAe, (2005), 43b–44a (Getatchew Haile)

but it shoul.d be like this, i.e. with indication fo the volume >

‘Däbrä Ṣǝyon’, EAe, II (2005), 43b–44a (Getatchew Haile)

**Comment by PietroLiuzzo** [comment]
I cannot find this record in EthioStudies, but the result is correct testing with other similar records.
please make sure that "II" is in the Volume field for your local entry.
see e.g. Däbrä Kol which is in EthioStudies 
https://www.zotero.org/groups/358366/ethiostudies/items/collectionKey/DT54NJC9/itemKey/DMWU7DSH/tag/bm%3ALusini2005Kol
output in word: 'Däbrä Kol', _EAe_, II (2005), 25b (G. Lusini)
(with the round quotes)
