### ISSUE TITLE
capitalisation of transliterated titles

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#736]
We have never stated any rules for the capitalisation of transliterated Gəʿəz titles (in work and manuscript records), so there are some inconsistencies in our records, for example we have both Wəddāse ʾamlāk (as title of mss containing this work) and Wəddāse ʾAmlāk (as title in the work record). A proposition from @SusanneHummel , which seams very reasonable to me, is to capitalise the first word of the title and all proper names (which we would argue would include here ʾAmlāk). Can we add this to the Transliteration guidelines? 
(which can now be found here https://github.com/BetaMasaheft/Documentation/wiki/Transliteration)

**Comment by abausi** [comment]
I agree with Susanne's proposal

**Comment by thea-m** [comment]
thank you, I'll add it.
As usual, individual issues should be opened for any particular cases that need discussing
