### ISSUE TITLE
"attested in" field in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#738]
IDs entered in the "attested in" field in person creation form are not transferred to the records (I believe I refreshed everything correctly...)
(I personally have no particular need for this field, since I use other relations much more often for person records, but since it exists...)

**Comment by PietroLiuzzo** [comment]
the issue could actually be reproduced when using that without selecting relations. i.e. I had a and instead of a or in a if statement. all should be good now.

**Comment by thea-m** [comment]
still doesn't work for me....(I had also selected another relation, which got transferred, and entered an ID into the is attested in field, which did not - can it only be used without selecting a relation at the same time?)

**Comment by PietroLiuzzo** [comment]
@thea-m, as discussed you enter text (either part of the id or of a title) to SEARCH the id you want to insert then you have to pick it from the list below as it appears. This works just fine as far as I can test.
