### ISSUE TITLE
visualization of relations in institution records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#741]
Are relations added in institution records visualized anywhere in the institution's page on the app? For example, `<listRelation>` in INS0329DE contains a lot of useful information, but I cannot see it anywhere on the app. I think it would be useful if these relations could be displayed on the institution's page.
(The relations of this institution are all shown on the "Relations" page of related LOC records, so the encoding seems fine)

**Comment by PietroLiuzzo** [comment]
no, they were not. they will be after release, the view has been updated
