### ISSUE TITLE
AND search option

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#744]
@cvertan @SusanneHummel and @vitagrazia81 asked to have an option to use the AND operator in the search. this collides with the homophones search, but can be added as an option for the API and for the application which will have a checkbox to say "no homophones"

**Comment by PietroLiuzzo** [comment]
some further specification about this issue

http://betamasaheft.eu/api/search?element=persName&collection=persons&q= "ʾiyasus%20AND%20krǝstos"
the system answers "No result".

Looking for Jesus you have to search for "ʾIyasus Krǝstos" or "ኢየሱስ፡ ክርስቶስ፡" and to a phrase search.

http://betamasaheft.eu/api/search?element=persName&collection=persons&q="ʾIyasus Krǝstos"

This however highlights two problems of the homophones substitutions

The query string, once fed to the homophones substitutions script
- [ ] does not ignore case any more finds ʾIyasus Krǝstos not ʾiyasus krǝstos
- [ ] ingests the AND operator as well in the substitutions engine which is then part of the searched string and is ignored by Lucene. 

This is the case also in the Dillmann App, where there are the modes options and the homophones search EXCLUDES them. (no change needed there)

I have added now in the API (not to the search in the website) a further parameter which will turn off the homophones substitutions and thus allow you to use AND and the case insensitive search, but will not perform homophones substitutions.

/api/search?homophones=false&element=persName&collection=persons&q=ʾIyasus AND Krǝstos
 
where you specify the parameter homophones to false (default is true)
this is also live in the app already but the solution to these issues is not urgent because the wanted result can be obtained already in two ways.

**Comment by cvertan** [comment]
Thank you. 
It is good that we have now both options. I can imagine that  homophones are also important but this may be solved on GeTa side. In TraCES the Transliteration does not use capital letters. do you have any convention in BM ? i.e do all names of places, persons, works usw begin with a capital ? If yes I could do this replacement on GeTa Side before I submit the ques

**Comment by PietroLiuzzo** [comment]
if you omit homophones there is no need to, the search will not be case sensitive

**Comment by cvertan** [comment]
This I understood but I am not sure that ommitting the homophones is the right way. If I understood correctly especially in old Texts the writting was not standardized so we may have cases were we meet a homophone which has to be linked to the NE

**Comment by PietroLiuzzo** [comment]
I agree that it will be good to have the substitutions work as well as the normal query syntax but I cannot do it now. since you are searching in the persName elements of the person collection, there is very little likelyhood of any deviation of that kind there, as it is all data entered here. Especially if you can input directly the correct characters, i.e. they will not be typing iyasus krestos which would not be found at all without the substitutions

**Comment by cvertan** [comment]
Users of Geta are not typing anything. They just select the cells with the mouse and Geta takes the string and perform the search. So misstyping is impossible.

**Comment by PietroLiuzzo** [comment]
great, than turning off homophones on the query should serve you well enough. but I will fix the two points above as soon as I can
