### ISSUE TITLE
vatican manuscripts list

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#745]
add manifest link to Vatican manuscripts [from here](http://digi.vatlib.it/search?k_f=0&k_v=Etiopic&f[]=f%3Amss) where missing

**Comment by PietroLiuzzo** [comment]
@MassimoVilla questo task è fatto, posso chiedere a qualche studente di continuarlo?

**Comment by MassimoVilla** [comment]
Finora ho aggiunto i link da qui (https://digi.vatlib.it/mss/Vat.et), coprendo i mss da BAVet1 a BAVet71. Poiché il prossimo manoscritto è il BAVet114 (ma io sono arrivato al BAVet112 nella catalogazione), non ci sono per ora nuovi manoscritti cui aggiungere manifest link. Se vuoi delegarlo in futuro a qualche studente posso aprire una issue per i singoli mss e taggare chi di competenza.
La lista dall'indirizzo da te inserito è molto utile per aggiungere riferimenti bibliografici ai mss già catalogati, cosa che finora ho fatto parzialmente.

**Comment by PietroLiuzzo** [comment]
se li stai comunque aggiungendo mano a mano va bene così, possiamo chiudere questa issue e rimuoverla dai task
