### ISSUE TITLE
catalogues in zotero

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#747]
make sure all catalogues (see massimo presentation handout and above Menestrel) have a zotero record [list of catalogues](https://github.com/BetaMasaheft/Manuscripts/wiki/List-of-manuscripts) and Massimo handout

**Comment by PietroLiuzzo** [comment]
@MassimoVilla @thea-m @eu-genia could you check if this is still something requiring attention? in the linked list actually all the entries have a tag in the EthioStudies group...

**Comment by thea-m** [comment]
I added the missing catalogues from Menestrel to Zotero (and used the opportunity to also update the list of available images). Our own catalogue list actually has remained very incomplete (I see no need in reproducing Menestrel) and is meant more as a priority list for our workflow than as a comprehensive overview of all catalogues.
