### ISSUE TITLE
print pdf from mss list doesn't work

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#758]
I cannot print pdfs from the manuscript lists of institutions, for example http://betamasaheft.eu/manuscripts/INS00001BL/list. When I select a manuscript and click on "print pdf of all selected items" I get the error 

> HTTP ERROR 403
> Problem accessing /exist/apps/BetMas/modules/printSelected.xql. Reason:
> 
>     Subject 'Dorothea' does not have '--------x' access to resource '/db/apps/BetMas/modules/printSelected.xql'.

(printing a pdf from the same manuscript's page works)
(the feature itself is very nice!)

**Comment by PietroLiuzzo** [comment]
Thanks for the notification! it should be fixed now

**Comment by PietroLiuzzo** [comment]
btw: please let me know how you would like to have that pdf! it is quite a mix of styles and quite random right now!
