### ISSUE TITLE
binding descriptions and dedicated search

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#759]
as discussed with @ElianaDalSasso we will make a few modification to the schema and guidelines to fit more of the information about bindings
- [x] Eliana will update the taxonomy with some values (Guards, types of wood, etc.)
- [x] Eliana will create an authority file with bibliography for each of these entries
- [x] Pietro will update the schema with
      - pastedown (see #35 ) 
      - `@color` for decoNote
      - further values for `decoNote/@type` : fastening, spineTreatment, slipCase, sawingStations
     - `decoNote[@type='sawingStations']` should only take an integer as value 
- [x] Pietro will create a search page like the one for decorations where it will be possible for example to
     - search all mss with two sawing stations
     - search all mss with a leather binding (this should already be possible, but the search for this is currently broken)
     - search for all mss with Headbands / endbands
     - search by model of Headbands
     - fields for this search will be types of decoNote in BindingDesc, material in BindingDesc, terms from those added in the taxonomy, grouped accordingly, presence or not of end leaves, presence or not of pastedown, color, fastening (holes or pegs) 
- [ ] Eliana will produce some sample description using these values to test the search capabilities

**Comment by PietroLiuzzo** [comment]
@ElianaDalSasso the attribute @color can be added , but it is not TEI, so, I would like to restrict it to the minimum possible number of use cases. 

there are at the moment the following values for decoNote[@type]
- Headband
- Tailband
- Fastening
- SpineTreatment
- SlipCase
- SawingStations

to which ones might `@color` be added?

**Comment by PietroLiuzzo** [comment]
same question for pastedown

**Comment by PietroLiuzzo** [comment]
actually, I have updated the schema to include more types, like those in #35. and I have decided for Spine instead of SpineTreatment.
I have allowed pastedown only on decoNote[@type='EndLeaves'] 
I have disallowed color on decoNote with type SawingStations, Spine, Other, Fastening.
I have also introduced an attribute repaired which takes Y or N.

**Comment by PietroLiuzzo** [comment]
the values in the schema need a definition and the guidelines need to be updated

**Comment by PietroLiuzzo** [comment]
The new version of the app will have this search as described, it is already working.
I removed from the values allowed for pastedown the Y/N as this is implicit from the presence of the attribute

**Comment by thea-m** [comment]
by SawingStations, do you mean SewingStations?

**Comment by PietroLiuzzo** [comment]
no, I real mean sawing!
![pnf_sawing](https://user-images.githubusercontent.com/508012/36148004-b58d62b4-10ba-11e8-95a0-b1f9fa408586.gif)
(of course not)

**Comment by ElianaDalSasso** [comment]
It's sufficient to attribute @color to tailband and headband.

Il 13 feb 2018 09:55, "Pietro Liuzzo" <notifications@github.com> ha scritto:

@ElianaDalSasso <https://github.com/elianadalsasso> the attribute @color
<https://github.com/color> can be added , but it is not TEI, so, I would
like to restrict it to the minimum possible number of use cases.

there are at the moment the following values for decoNote[@type
<https://github.com/type>]

   - Headband
   - Tailband
   - Fastening
   - SpineTreatment
   - SlipCase
   - SawingStations

to which ones might @color be added?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/BetaMasaheft/Documentation/issues/759#issuecomment-365192087>,
or mute the thread

**Comment by larkvi** [comment]
What is a sawing station, specifically in the context of an Ethiopian manuscript?

**Comment by ElianaDalSasso** [comment]
The term has been corrected with sewing stations.
According to the definition given by Ligatus in the *Language of Bindings*
project "sewing stations are created by passing a thread through a spine
fold when sewing a book. [...] Sewing stations include change-over stations
or chain-stitch stations in an unsupported structure."
Ethiopian manuscripts are unsupported structures with chain-stitch sewing
on paired sewing stations (see Szirmai, p. 46). Thus, in Ethiopian binding
the number of linked chains on the spine corresponds to the number of
sewing stations. For example, 4 linked chains on the spine correspond to 4
sewing stations (and to 2 paired sewing stations).


2018-02-14 13:55 GMT+01:00 Sean Winslow <notifications@github.com>:

**Comment by PietroLiuzzo** [comment]
received data from Eliana to be added
