### ISSUE TITLE
visualization of physDesc

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#768]
Would it be possible to print "Palaeography" only on the app if `physDesc` actually contains a `handDesc`?
(For example, in BDLbruce88, the first `physDesc `preceding p1, which refers to the entire manuscript, contains no `handDesc`, because the hands are described in each msPart, but "Palaeography" is still printed on the app below "Layout")

**Comment by thea-m** [comment]
Similarly, could

> Intercolumn |  
> -- | --
> Margins | Top:
>   | Bottom:
>   | Right:
>   | Left:
> 

only be printed if these values are specified in `<dimensions>`? I think that there is already so much content on any manuscript page that removing any visual clutter that contains no information would improve the viewing experience.

**Comment by PietroLiuzzo** [comment]
all under if now.

**Comment by thea-m** [comment]
thank you, wonderful!
