### ISSUE TITLE
references to msParts

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#769]
I think that it might be helpful for users if empty references to msParts, which are currently logically visualized as p1, p2 etc would be visualized as "Codicological Unit xy" in keeping with the terminology used throughout the app. 
For example, in BDLbruce88, 
```xml
 <provenance>
                     <ref target="#p2"/>  was copied for <persName ref="PRS2916Bruce" role="patron"/>, but the rest
                        of the manuscript was produced between <date notBefore="1592" notAfter="1605"/>.</provenance>
```
currently visualized "p2 was copied for James Bruce etc." could become "Codicological Unit 2 was copied for James Bruce etc". 

What do you think?

(of course it would also be possible for us to write this into the element if changing the visualization would be too complicated)

**Comment by PietroLiuzzo** [comment]
![schermata 2018-02-09 alle 13 06 52](https://user-images.githubusercontent.com/508012/36027112-21cd92d8-0d9a-11e8-9454-46b6b323c87a.png)
for ref pointing in a target to ids of other types I have also added 
Title with id 1
Hand with id 2
Quire with id 3
Content unit with id p1.1_i2.3.4
Addition with id 4
Extra with id 5

**Comment by PietroLiuzzo** [comment]
![schermata 2018-02-09 alle 13 09 30](https://user-images.githubusercontent.com/508012/36027188-7ccd0cfe-0d9a-11e8-8a69-a758cb7996ce.png)
