### ISSUE TITLE
duplicate institutions (?)

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#770]
In the dropdown menu when creating a new ms record a number of institutions seem to appear several times, sometimes with a slightly different spelling, possibly there is multiple data beyond (?) 
E.g. Bibliothèque nationale de France three times, Biblioteca Medicea Laurenziana twice, Uppsala twice. There is Austrian National Library and Österreichische Nationalbibliothek. And then there are several that appear with the prefix "More then 1".

**Comment by PietroLiuzzo** [comment]
Please @MargaretheJenner check that you have not created double entries in the institutions. if so, please merge the two/three records into one with the best data from both.

**Comment by PietroLiuzzo** [comment]
@eu-genia this is not a duplicate issue (i.e. there isn't another issue which is the same as this)

**Comment by eu-genia** [comment]
still an issue... uppsala 2x, biblioteca medica 2x, bavarian state library / bayerische nationalbibliothek, bnf x 3...

**Comment by thea-m** [comment]
@MargaretheJenner will solve this when she is back. Also note than some of the doublets are due to the fact that there are records for the same institution in beta masaheft and IHA, for example for the BnF INS0303BNF and INS0020IHA. If my understanding is correct, nothing should be done in these cases for now

**Comment by PietroLiuzzo** [comment]
@MargaretheJenner could you update us on this issue and close it if you are finished? thanks

**Comment by MargaretheJenner** [comment]
@eu-genia are http://betamasaheft.eu/manuscripts/INS0341DL/list and this http://betamasaheft.eu/manuscripts/INS0346DL/list the same? can the two records be merged and references to the id which will be deleted be updated?

**Comment by PietroLiuzzo** [comment]
given that the double BNF is due to the IslHornAfr data still waiting to be updated there seem to be no more duplicates in the list. @eu-genia please check and close if satisfactory.

**Comment by eu-genia** [comment]
http://betamasaheft.eu/manuscripts/INS0341DL/list and http://betamasaheft.eu/manuscripts/INS0346DL/list are clearly not the same, the first is in Ethiopia, the second in Eritrea

**Comment by PietroLiuzzo** [comment]
good! then we have one less double!

**Comment by eu-genia** [comment]
Biblioteca Accademia Nazionale dei Lincei 
Biblioteca dell'Accademia Nazionale dei Lincei 
is double

Addis Ababa University Institute of Ethiopian Studies
Addis Ababa University Ya'itopya tenatena...
IES - Institute of Ethiopian Studies
are triple (probably the last one from IHA? still too many)

can the value "test" be removed?

**Comment by PietroLiuzzo** [comment]
@MargaretheJenner

**Comment by thea-m** [comment]
one of the Accademia dei Lincei records (INS0009IHA) is from IHA, so is one of the IES records (INS0002IHA). There is nothing @MargaretheJenner could do about those

**Comment by PietroLiuzzo** [comment]
Yes, we know about those, until the new export comes there is nothing to be done (i.e. any change would be vane) the third IES is then the only one to fix?
