### ISSUE TITLE
clavis sorting

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#772]
Currently the Clavis list (worklist) seem to be sorted automatically according to whichever number appears in the ID, irrespective of the corpus, so now first come all the IslHornAfr works, later mixed with the CAe ones. Maybe there is a better way of sorting? Or by title, or at least first all the CAe works?

**Comment by PietroLiuzzo** [comment]
first the CAe ones is doable

**Comment by abausi** [comment]
then, let's do so

Il 12.02.2018 10:56, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
![schermata 2018-02-12 alle 11 03 35](https://user-images.githubusercontent.com/508012/36091557-6575b2da-0fe4-11e8-86f8-a4b1279deb65.png)
