### ISSUE TITLE
search through a single record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#774]
Is there, or could there be, a function which would allow users to search through an entire record? For example, I searched for "መዝገበ፡ ሥላሴ፡" and found BAVet74. I then opened the page, but in order to find the occurence of መዝገበ፡ ሥላሴ፡ I would have to manually open each msItem to finally find it in the subscription of ms_i1.10.
(I can of course search through oxygen, or anyone could open the xml of the record and search there, but I doubt that many would do this.)
It would be nice to have a field where one could enter a search term and then search through the entire record, including text and relations...

**Comment by PietroLiuzzo** [comment]
this issue should be already closed in the next release

**Comment by thea-m** [comment]
it is again not possible (should a new issue be opened?)
especially in the case of very lengthy records, it would be helpful if the link from the search, or wherever one is (calendar view for example) would go to the exact place in the page, but I don't know if that's possible

**Comment by PietroLiuzzo** [comment]
this conflicts with the wish of having the msItems collapsed. If they are collapesed, pointing to the id of the element where they are contained will not help. I will investigate options, but perhaps it would be enough to know where to look when clicking on the result? like "in msItem 1.10" ?
