### ISSUE TITLE
type="main" in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#775]
is the use of @type="main" in person records still up to date? It was discussed in #518 and has been used widely, though apparently never been added to the person guidelines (I thought it was there, but cannot find it now and do not remember any recent discussion regarding this...) 
Records using this, like PRS2481Bartholo, which has:
```xml
<persName xml:id="n1" xml:lang="gez">በርተሎሜዎስ፡</persName>
<persName corresp="n1" xml:lang="gez" type="normalized">Bartalomewos</persName>
<persName corresp="n1" xml:lang="en" type="main">Bartholomew</persName>
```
are now very strangely visualized (በርተሎሜዎስ in the title and the transciption stated nowhere on the page)

**Comment by PietroLiuzzo** [comment]
corresp="#n1"

**Comment by thea-m** [comment]
aah, thank you!
