### ISSUE TITLE
RDF and new views

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#778]
Dear all, since release 2.5 of the BM app, we now have also a RDF dataset with most of the relational information available in our TEI (not all).
This opens up the possibility to provide various computed visualizations, using the output we can now generate and the [d3sparql javascript library](http://biohackathon.org/d3sparql/)

Please have a look at the above link at the kind of visualizations we can get with the new data and let me know what you would like to see and where. In principle I only need to know the question you would like to ask and have displayed as standard in one or the other view of the app and the type of graph or output you would like to see with that data. I will then prepare a series of ready made queries and visualizations.

As an example you can try and enter here http://betamasaheft.eu/sparql
the following query which will return a table and a force graph of the works with 'homily' in the title by and an author whose name contains 'john'

````sparql

SELECT ?worktitle ?authorname
WHERE {
?author a 'pers';
     crm:P48_has_preferred_identifier ?authorid ;
     dc:title ?authorname .
?work a 'work'; 
     crm:P48_has_preferred_identifier  ?workid ;
     dc:title ?worktitle ;
     saws:isAttributedToAuthor ?author .
FILTER regex(?worktitle, 'homily', 'i') 
FILTER regex(?authorname, 'john', 'i')
}

````

**Comment by PietroLiuzzo** [comment]
https://developers.google.com/chart/interactive/docs/gallery/geochart
This is an easy way to get geocharts sending  simply an array to google, and could be added easily on the basis of clear visualization requirements

**Comment by PietroLiuzzo** [comment]
There are now 10 more graphs produces from the selections in every list view of manuscripts.
<img width="986" alt="schermata 2018-05-18 alle 23 11 52" src="https://user-images.githubusercontent.com/508012/40258143-e394e6c0-5af0-11e8-9829-2d691fe27a8c.png">
there is one more graph in the graph view of manuscripts
there is distribution of attested values in persons and places records, with a table of passages and roles for each person
there is an improved list view of relations in the analytic view.
more graphs can be added. all in the charts.xqm module

**Comment by eu-genia** [comment]
sorry for nitpicking but is it possible to change sawing to sewing?

**Comment by PietroLiuzzo** [comment]
no, it is my favourite mistake, I will never fix it! ;)
