### ISSUE TITLE
box with manuscripts containing a work record which contains the work subject of the view

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#780]
an (additional ? ) witness box is needed for works that can be contained in other works and are listed as textparts with `@corresp` (and possibly also isPartof or isVersionof relations).

e.g. LIT4090Haylu contains as textpart 
```
<div type="textpart"
                 subtype="chapter"
                 xml:id="AmdaSeyon"
                 corresp="LIT4275ChronAmdS">
```
the work LIT4275ChronAmdS should thus show mss containing LIT4090Haylu (such as e.g. BNFet143, which correctly lists "LIT4090Haylu#AmdaSeyon" and not LIT4275ChronAmdS)

**Comment by PietroLiuzzo** [comment]
the mark up is not not very explicit in this direction perhaps. it would be easier to have also a relation like

LIT4090Haylu#AmdaSeyon saws:isVersionOf LIT4275ChronAmdS

I will try to infer that.

**Comment by PietroLiuzzo** [comment]
isPartOf and isVersionOf relations are already displayed on the boxes on the right

http://betamasaheft.eu/works/LIT1889Martyr/main
http://betamasaheft.eu/works/LIT1401Fisalg/text
http://betamasaheft.eu/works/LIT1401Fisalg/main

**Comment by PietroLiuzzo** [comment]
<img width="439" alt="schermata 2018-02-15 alle 17 57 32" src="https://user-images.githubusercontent.com/508012/36269576-bd5dfc72-1279-11e8-87c9-67eae622fa25.png">
this is how it will look for the manuscripts containing works which have divs with a @corresp pointing to the current work

**Comment by PietroLiuzzo** [comment]
<img width="343" alt="schermata 2018-02-15 alle 18 12 22" src="https://user-images.githubusercontent.com/508012/36270360-cc9d2666-127b-11e8-84e8-1cbdcfd1ed14.png">
this should be correct now. Please have a look

**Comment by PietroLiuzzo** [comment]
I see now you also want to see **witnesses** of works of which the one currently viewed is part of or is version of...

**Comment by eu-genia** [comment]
on rethinking - isPartof is not necessary as there the main work ID is  
always present
but is version of would be helpful, as it may again be a different thing

Quoting Pietro Liuzzo <notifications@github.com>:

> I see now you also want to see **witnesses** of works of which the  
> one currently viewed is part of or is version of...
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BetaMasaheft/Documentation/issues/780#issuecomment-365998682


-- 
Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian Studies
Asien Afrika Institut
Universität Hamburg
Alsterterrasse 1
20354 Hamburg

eugenia.sokolinski@uni-hamburg.de

https://www.aai.uni-hamburg.de/en/ethiostudies.html

**Comment by PietroLiuzzo** [comment]
Well, isVersionOf is already there and the witnesses of each of the related versions (main text or version) would be just one click away...

**Comment by PietroLiuzzo** [comment]
the only really missing where the corresp once which are now there
