### ISSUE TITLE
values of dimensions/@type

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#781]
@thea-m reports the use of the following values
 size_of_folium 
 text_area
This are used exclusively in MNC002 and MNC004 by @MassimoVilla .
for the second the guidelines state ["The first dimensions contains the information about the text area."](https://github.com/BetaMasaheft/Documentation/wiki/guidelines#layout-description) so I do not find a reason to add this type. for the first, I assume this is a different measurement from what should go in extent/dimensions[@type='outer'], I would in any case add it to the physDesc, not in the layout section of the ms description and I would be inclined to call it "leaf" instead of size_of_folium, for consistency with the language used in the schema.

**Comment by MassimoVilla** [comment]
As to text_area, I have now given that information first, according to the guidelines.
As to size_of_folium, it has been moved into physDesc with [@type='leaf'], after ` <dimensions type="outer" unit="mm"/>`.
I have updated the guidelines.

**Comment by MassimoVilla** [comment]
One question: since the size of the leaf is usually taken from one specific leaf (usually in the centre fold of the quire, which enables to take better measurements), wouldn'it it be good to keep this information and relax the schema having `<note>Data for <locus target="#6r"/>.</note>` within ` <dimensions type="leaf" unit="mm"/>`?
This is currently not allowed.

**Comment by thea-m** [comment]
It would also be helpful to be able to add the sample folio from which the text area measurement has been taken...could `<locus>` maybe be allowed in `<dimensions>`? (or `<note>` as proposed by Massimo?)

**Comment by PietroLiuzzo** [comment]
no, allowing a note inside dimensions is not advisable, neither a locus. What about simply adding such note in `<extent>`?
````xml
<extent>
                           <measure unit="leaf">113</measure>
                           <measure unit="leaf" type="blank">1</measure>
                           <locus target="#1r"/>
                           <measure unit="quire">12 (A + 11)</measure>
                           <dimensions type="outer" unit="mm">
                              <height>226</height>
                              <width>151</width>
                              <depth>48</depth>
                           </dimensions>
                           <dimensions type="leaf" unit="mm" xml:id="leafdim">
                              <height>215</height>
                              <width>139</width>
                           </dimensions>  
                              <note corresp="#leafdim">
                                 Data on leaves dimensions 
                                 taken from <locus target="#6r"/>.
                              </note>
                        </extent>                       

````
![schermata 2018-03-05 alle 12 43 52](https://user-images.githubusercontent.com/508012/36973345-e3defdae-2072-11e8-8bbb-e17e063f6383.png)

**Comment by thea-m** [comment]
And could this be then included in layout for the text area and margin measurements?

```xml
  <layout columns="2" writtenLines="26">
                           <locus from="119ra" to="132ra"/>
                              <note corresp="#textarea #margin">Data on text area and margin dimensions taken from <locus
                                 target="#119r"/>.</note>
                           <dimensions unit="mm" xml:id="textarea">
                              <height>145</height>
                              <width>100</width>
                           </dimensions>
                           <dimensions type="margin" unit="mm" xml:id="margin">
                              <dim type="top">15</dim>
                              <dim type="bottom">30</dim>
                              <dim type="right">20</dim>
                              <dim type="left">5</dim>
                              <dim type="intercolumn">10</dim>
                           </dimensions>
                        </layout>
```

**Comment by PietroLiuzzo** [comment]
why, can't you already do so?

**Comment by PietroLiuzzo** [comment]
I would not enforce this as a compulsory way of encoding, the ids, corresp and the note should be added only when needed

**Comment by thea-m** [comment]
I can, but no one ever did, so I wanted to be sure :) I'll add it to the guidelines then

**Comment by PietroLiuzzo** [comment]
Massimo file already has that :)

**Comment by PietroLiuzzo** [comment]
you are not alone

**Comment by PietroLiuzzo** [comment]
@MassimoVilla and @thea-m, you are welcome to document all these things in the guidelines and close this issue ;)
