### ISSUE TITLE
Link to Dillmann in text in ms records

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#784]
Contrary to the text edition encoded in the work records, text encoded in BNFabb247 (http://betamasaheft.eu/manuscripts/BNFabb247/text) is not linkable to the Dillmann lexicon.
It would be fine to make the linking possible also for text editions encoded in ms records.

**Comment by PietroLiuzzo** [comment]
your `<div type="edition">` needs a `@xml:lang='gez'` otherwise the links will not be displayed

**Comment by MassimoVilla** [comment]
perfect, thank you!
