### ISSUE TITLE
Problems with the visualization of collation diagrams 

### ISSUE THREAD

**Issue by ElianaDalSasso** [BetaMasaheft/Documentation#791]
The visualization of collation diagrams for quires with added leaves is not always correct.

GAet7.xml
https://github.com/BetaMasaheft/Manuscripts/blob/master/Grottaferrata/GAet7.xml
http://betamasaheft.eu/manuscripts/GAet7/main

1) Diagrams are introduced by the formula Quire Y (X), where Y is the quire number and X is the number of leaves of the quire (I suppose).
In quires with added leaves, the X number doesn't correspond to the actual number of leaves.
It happens for:
Wrong --> right
quire 1(8) --> quire 1(7)
quire 2(14) --> quire 2(10)
quire 3(8) --> quire 3(7)
quire 4(10) --> quire 4(8)
quire 5(12) --> quire 5(9)
quire 7(12) --> quire 7(10)
quire 8(10) --> quire 8(9)
quire 24(10) -->  quire 24(6)

2) Wrong visualization of collation diagrams for:
- quire 2: the diagram shows 1 and 10 as an added bifolium whereas they are single added leaves.

                              <item xml:id="q2">
                                    <dim unit="leaf">10</dim>
                                    <locus from="8" to="17"/>
                                    1 added,
                                    2 added,
                                    9 added,
                                    10 added.
                                    c.8 was originally conjoint to c.1 and c.17 was originally conjoint to c.24. 
                                    Today c.8  and c.17 are single leaves linked to the quire by means of stitching.
                               </item>

- quire 5: the diagram shows 1 and 9 as an added bifolium whereas they are single added leaves; 
                             2 as a single leaf whereas it is conjoint to 7 (bifolium);
                             8 conjoint with 3 whereas it is a single leaf.

                               <item xml:id="q5">
                                    <dim unit="leaf">9</dim>
                                    <locus from="33" to="41"/>
                                    1 added,
                                    8 added,
                                    9 added.
                                    c.41 was originally conjoint to c.47. 
                                    Today it is stitched to a stripe of parchment and linked to c.33.
                                </item>
                             
- quire 7: the diagram shows 1 and 10 as an added bifolium whereas they are single added leaves.

                                <item xml:id="q7">
                                    <dim unit="leaf">10</dim>
                                    <locus from="48" to="57"/>
                                    1 added,
                                    10 added.
                                    Originally c.48 was conjoint to c.41 and c.57 to c.66. 
                                    Today c.48 and c.57 are single leaves linked to the quire by means of stitching.
                                 </item>

- quire 24: the diagram shows 1 conjoint with 6, 2 conjoint with 5, 3 as a single leaf, 4 as a single leaf. The right diagram should show 1, 2, 3 as added leaves, 4 and 5 conjoint as a bifolium, 6 as a single leaf with a stub before 1.

                             <item xml:id="q24">
                                    <dim unit="leaf">6</dim>
                                    <locus from="217" to="222"/>
                                    6, stub before 1,
                                    1 added,
                                    2 added,
                                    3 added.
                                    Probably c.217, c,218 and c.219 had a stub after c.221 but now they are linked to the quire by stitching.
                                  </item>

**Comment by PietroLiuzzo** [comment]
1. the number in brackets is the number of positions in the quire. it can be changed if all agree to contain a different information
2. you have eventually made me notice that the hyphenation was badly set and looked like something else. now the added leaves should be hyphenated, but the existing space at the attachment of the two different added bifolia is perhaps not that much. I do not know how to increase it however at the moment.

**Comment by PietroLiuzzo** [comment]
all points should be fixed now. it was quite a puzzle... please close issue if now it is ok.

**Comment by ElianaDalSasso** [comment]
Yes, it's perfect. Thank you!

**Comment by PietroLiuzzo** [comment]
@eu-genia pointed out issues in ESagm004 and ESagm008 which should be now correct (I have made this change also in the live website)

**Comment by ElianaDalSasso** [comment]
Hi!The collation of the following manuscripts (Hamburg>Stabi) has many added leaves and results in an error 500 when displayed in the app. I put the collation between  to be sure that it was actually the problem.

http://betamasaheft.eu/manuscripts/SHOr405/main

http://betamasaheft.eu/manuscripts/SHOr413/main

http://betamasaheft.eu/manuscripts/SHOr402/main

http://betamasaheft.eu/manuscripts/SHOr409/main
