### ISSUE TITLE
encircled text

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#793]
How can we mark up encircled words in a text, often highlighting words meant to be erased? 
Maybe hi rend="encircled"? Or using `<del>` (with the same attribute) if we are sure the encircling points to an intended erasure?

**Comment by PietroLiuzzo** [comment]
Do we really need to mark that up? if the schema allows it as a value of @rend for hi or del, you can do it

**Comment by PietroLiuzzo** [comment]
can we close this?

**Comment by thea-m** [comment]
I see no reason not to mark it up when we have the information, since it gives evidence of scribal practice.  hi rend="encircled" is of course allowed by the schema, but not visualized, so that `እምሰሜን፡ <hi rend="encircled">ወእምዕራብ፡</hi>  ምደቡብ፡` in DSEthiop2, a12 is currently printed as  እምሰሜን፡ ምደቡብ፡
What would be a good visualization, @DenisNosnitsin1970 ?

**Comment by PietroLiuzzo** [comment]
the visualization should now take care of this and will encircle the text
