### ISSUE TITLE
splitting vs non-splitting named entities in fidel

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#795]
ለነጉሥ፡ ተክለ፡ ሃይማኖት፡
```
ለ<persname ref="0000"><rolename type="title">ነጉሥ፡</rolename> ተክለ፡ ሃይማኖት፡</persname>

or

<persname ref="0000"><rolename type="title">ለነጉሥ፡</rolename> ተክለ፡ ሃይማኖት፡</persname>

```

splitting is possible with prepositions (and even that not always) but not e.g. with suffixes, so consequent splitting shall not be possible in fidel annotations.

most TEI-annotated text corpora do not split, even where splittable, treating graphical units as a whole.

i would suggest to go along with this practice and not split graphical units in editions.

**Comment by PietroLiuzzo** [comment]
documenting "most" would be useful, this decision has no development implications, unless you want some further rule in the schema.

**Comment by eu-genia** [comment]
no no rule in the schema, it was for us to take an editorial decision.
most corpora online are in English and there you find both options, but English words do not decline; all Arabic annotated corpora only annotate graphic units.
an example for English
http://dsg.neu.edu/wiki/index.php?title=Women_Writers_in_Context_publication_system&amp;oldid=277

> All significant persons mentioned in the text of an exhibit should have an `@ref` attribute on `<persName>` which points to the ID of the `<person>` as listed in persons.xml, prefixed with "ep:". For example: `<persName ref="ep:mcavendis.neu">Margaret Cavendish’s</persName>`....

**Comment by thea-m** [comment]
I have always marked up only the actual name, splitting it from prepositions and conjunctions (I cannot remember other cases now, but I probably would have splitted enclitic particles as well), since this seemed more logical to me. It is easier to do this in the editor with fidal than Arabic, though that should not motivate our decisions.

**Comment by eu-genia** [comment]
it might be easier with persnames but with rolenames you will often be confronted with cases where you cannot split the suffix (e.g. -ihu, -e) in fidal

**Comment by thea-m** [comment]
I understand...could we have as a general rule to mark up the smallest possible entity? This would allow for some flexibility.
I agree it would be sensible to agree on a common practice (but there's probably no need to go back and correct the old files)

**Comment by abausi** [comment]
I agree with Dorothea.

A.B.

Il 03.04.2018 10:50, thea-m ha scritto:

**Comment by PietroLiuzzo** [comment]
can we close this?
