### ISSUE TITLE
PDFs with data from BM now openly-accessible on google

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#796]
Dear Colleagues,

Not sure if this point was raise by someone esle, as I have been absent for some months (in which case I apologize, but  I did check closed issues related to the pdfs before posting).

I noticed that with the new version the pdf versions of the catalogue entries for BM are now searchable and openly-accesible on google:

![immagine](https://user-images.githubusercontent.com/31648831/37913227-afbcd584-3114-11e8-9c80-87d5872e30e8.png)
![immagine](https://user-images.githubusercontent.com/31648831/37913787-02e36e34-3116-11e8-803f-315b4fa11cc0.png)

Regardless of whether this is or is not supposed to happen, should these PDFs not contain a warning, like we have on the app, that the content is in a draft form and should thus not be used as a reference?

**Comment by PietroLiuzzo** [comment]
Dear Jacopo,

everything is now openly accessible, but PLEASE do NOT SPREAD THIS INFORMATION. Also for Dillmann we acted this way as a test before public release.

thank you

**Comment by Gnisci** [comment]
Dear Pietro, thank you for getting back to me. My question was not about open access. It was about whether the pdf should not rather not be marked as a draft?

**Comment by PietroLiuzzo** [comment]
please open an issue about the content of the pdf
