### ISSUE TITLE
Openly-accessible PDFs to be marked as drafts?

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#797]
Dear Colleagues,

Not sure if this point was raise by someone esle, as I have been absent for some months (in which case I apologize, but I did check closed issues related to the pdfs before posting).

I noticed that with the new version the pdf versions of the catalogue entries for BM are now searchable and openly-accesible on google:

![immagine](https://user-images.githubusercontent.com/31648831/37915635-441cc32e-311a-11e8-8dcb-734bb656ea73.png)

Now that these PDFs can be found with a simple google search, should they not contain a warning, like we have on the app, that the content is in a draft form and should thus not be used as a reference?

**Comment by PietroLiuzzo** [comment]
There is now a draft notification on each page in red

**Comment by Gnisci** [comment]
I was raising the issue rather than asking/suggesting, but, nevertheless, thank you very much @PietroLiuzzo  for looking into this so quickly.
