### ISSUE TITLE
Guidelines Improvement – User Needs

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#798]
Dear all, 

as you might have noticed, our guidelines (https://github.com/BetaMasaheft/Documentation/wiki/guidelines ;) ), which thanks to you all have been developed constantly since the beginning of the project, have become a bit crowded and confusing. It is difficult for new users to find what they are looking for, and large parts of the examples reflect various stages of the project and cannot be used as a reference anymore.
We think that it makes therefore sense at this point to take a step back and think about how we could develop the guidelines to be more helpful to all users.

To do this well, it would be very helpful to know what you are actually looking for in the guidelines and how you use them/would like to use them.

I expect that new users mainly look to the guidelines to get a general idea about encoding, to understand the general structure of xml records and to find examples for the encoding of common features, while more experienced users might search for descriptions of specific features and check whether a feature they encounter for the first time has already been encoded by someone else.

If you use the guidelines – what would you like to find there? Have you often searched for something you didn’t find at all?

Thank you for helping us!
(And please feel free to remove your assignment if you think that this issue doesn’t concern you)

**Comment by PietroLiuzzo** [comment]
Thanks @thea-m ! you are right and I think here we are to be assigned, without any doubt.

**Comment by PietroLiuzzo** [comment]
#799

**Comment by Gnisci** [comment]
The thing I found (and still find) most useful in the guidelines are practical examples, I would keep these in (and make sure they are up-to-date).

I will try to make the English more synthetic, if nobody objects. This could be a starting point?

**Comment by thea-m** [comment]
Thank you @Gnisci ! I also always used mainly the examples as reference and we will definitively keep and develop them. It would be wonderful if you could help with our English! But I think that it would be best not to do this immediately, since we are going to modify the guidelines a lot in the next days. I'll get back to you when we're ready :)

**Comment by PietroLiuzzo** [comment]
I think we should integrate in the same guidelines also the schema documentation which is currently only partially available, as well as the ontology, which is only documented as graph, not very usefully. this calls for a xml project with a proper app powering it (edited and updated as any other file)

**Comment by PietroLiuzzo** [comment]
the inclusion of the schema would especially remove the need to update both the schema and the guidelines with values for a given attribute and would document all rules in the schema as such

**Comment by PietroLiuzzo** [comment]
the inclusion of the ontology will primarily serve purely documentation purposes but also justify some of the choices in the xml encoding (relation elements, and structure of the ids). in this way the guidelines could also be used for the user guide in many respects

**Comment by PietroLiuzzo** [comment]
further issues about the guidelines to be opened here
https://github.com/BetaMasaheft/guidelines/issues
