### ISSUE TITLE
two records for ʾAḥmad Grāñ?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#801]
It seems to me that PRS1522Ahmadb and PRS1500Ahmad refer to the same person? If this is the case, could you please merge the records and correct the ID in the records referring to this person? Thank you!

**Comment by eu-genia** [comment]
PRS1500Ahmad is Ahmad imam of Zayla as is visible from the Spreadsheet (https://docs.google.com/spreadsheets/d/1a0LtliOVuXoRcDhgj3p5V1Z2i-M5k5_MkT6YgPgh04s/edit?usp=sharing), I don't know why the qualifiers disappeared from the xml record

**Comment by sologebre** [comment]
No, they are not the same persons. PRS1500 is another Ahmad (not ʾAḥmad Grāñ) for whom we will complete the record. So we keep both records.

**Comment by eu-genia** [comment]
yet care is needed in creating new records for persons

e.g. we had originally
PRS7827Petros for Petros the metropolitan of Aksum 
PRS7828Petros for metr. Petros II
PRS7829Petros for metr. Petros III

yet the record PRS7827Petros was filled with data referring to Petros II
record PRS7828Petros was ignored (remained a stub) 
and for Petros I a new record PRS11305Petros was created

I have now removed PRS7828Petros and updated all links (e.g. PRS10384Yohanne was pointing to PRS7828Petros and not to PRS7827Petros)

i would suggest sometimes checking the Spreadsheet in case of doubts

**Comment by thea-m** [comment]
Thank you! But since we don't use the spreadsheet anymore, they should be clearly identifiable by the information in the xml records. It still seems to me that there is some confusion going on in the relations (both are the father of PRS7506Nasraddi?)

**Comment by eu-genia** [comment]
I dont see any relations in PRS1500Ahmad...
But I do not see the information from the Spreadsheet which should have been retained for identification either

**Comment by thea-m** [comment]
http://betamasaheft.eu/persons/PRS1500Ahmad/analytic
The wrong ID was used in the relations for PRS1522Ahmadb, which has probably happened to us all and is not the end of the world, but this is why it is useful to check the app regularly

**Comment by sologebre** [comment]
Ok, thank you!
