### ISSUE TITLE
Ethio-SPaRe transformation

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#802]
In Ethio-SPaRe mss the info now represented in listPerson under persName role="owner" as
e.g. ESakm002
```
<listPerson>
               <person>
                  <persName role="owner" ref="PRS0000">According to crude recent notes pencil, in <locus target="2rv">2rv</locus> (s. Varia), the Ms. was one time owned by Dabra Libānos ʾAnbäsät (the old church of ʾAmbäsät).</persName>
                  <!--ACHTUNG! This is actually paragraphic information identifying the donor. 
                                        Person/persName should only contain the person name, not all the paragraph.-->
               </person>
               <person>
                  <persName ref="PRS00000"/>
                  <!--other-->
               </person>
            </listPerson>
```

should go under history / provenance as
```
<provenance>
                     According to crude recent notes pencil, in <locus target="2rv">2rv</locus> (s. Varia), the Ms. was one time owned by Dabra Libānos ʾAnbäsät (the old church of ʾAmbäsät).
                  </provenance>
```

**Comment by PietroLiuzzo** [comment]
This is not always true. actually a search for the contents of these persName[role="owner"] (which come from the owner element in the domlib XML) is persuasive enough for me that the information often does belong there or does not belong to provenance anyway.

e.g. ATH-007: 
                    
>  The priests of the church of Mikāʾel
>                      ʿAraʿro (located below ʾAraʿro Takla Hāymānot), namely Tomas, ʿAmda  Mikāʾel,
>                      Tasfā ʾIyasus, ʿAṣfä Krǝstos, Gabra Krǝstos, Rǝʾǝsä Hāymānot, Takla Hāymānot,
>                      are mentioned in Additio 2 as those who purchased the Ms.

this information could be better encoded there (certainly, as the comment already says, not in one persName) and in the addition, but none of it belongs to provenance.

This is then an update process which will need editorial work, it is no systematic error to be fixed by a transformation.

**Comment by PietroLiuzzo** [comment]
the point is anyway that it might be sometimes to be moved, but it is not always. therefore is not something to be safely done automatically.

**Comment by eu-genia** [comment]
well we show the subtitle "provenance" and this is what provenance studies do https://www.nottingham.ac.uk/manuscriptsandspecialcollections/researchguidance/medievaldocuments/ownershipandprovenance.aspx

**Comment by eu-genia** [comment]
putting a descriptive text under provenance is safer in preserving and presenting the information online than keeping it where it is now

**Comment by PietroLiuzzo** [comment]
see comment above. not always. thus, if you feel like this is better, you can do it selectively but I am not doing this systematically. as for what provenance studies do, thanks for the link, but also the equation provenance = provenance studies is not documented for our system, neither in TEI nor in our guidelines. if you want to make a point that we should encode under provenance information as it is studied in provenance studies this is a different issue and has to do with the guidelines. If we decide to do so and update the guidelines, there might still be no ground to run this transformation automatically given it is not always that kind of information. in the example I have given above for example those names where rightly added to the owner field in EthioSpare and are rightly there where we encode owners. there should be a persName for each, and I would expect the information about addition 2 to be in addition 2, but certainly not in provenance. another encoding option would be to have this encoded directly in the text of the trasncribed addition with persName[@role='owner'] marked up in the running text
