### ISSUE TITLE
Ethio-SPaRe transformation - decoration data lost

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#806]
in a E-S ms - here ESakm001 - the original file has the following information

> Miniatures
> --
> - Miniature: 1 | Fol. 11v: Christ crowned with thorns, donor.
> - Details | Frontispiece miniature; recent; the name of the donor missing.
> - Miniature: 2 | Fol. 12r: ˀAbunä Libanos and ˀabunä ˀArägawi
> - Details | Frontispiece miniature; recent.
> - Miniature: 3 | Fol. 12v: St. Matthew the Evangelist.
> - Details | Frontispiece miniature;recent.
> - Miniature: 4 | Fol. 13r: The Holy Trinity, two donors.
> - Details | Frontispiece miniature; recent.
> - Miniature: 5 | Fol. 66v: St. Mark the Evangelist.
> - Details | Frontispiece miniature; recent.
> - Miniature: 6 | Fol. 67r: The Virgin Mary with her Child.
> - Details | Frontispiece miniature; recent.
> - Miniature: 7 | Fol. 101v: St. Luke the Evangelist.
> - Details | Frontispiece miniature; recent.
> - Miniature: 8 | Fol. 102r: The Annunciation.
> - Details | Frontispiece miniature; recent.
> - Miniature: 9 | Fol. 158v: St. John the Evangelist.
> - Details | Frontispiece miniature; recent.
> - Miniature: 10 | Fol. 159r: Baptism of Jesus.
> - Details | Frontispiece miniature; recent.
>  
> Initiales : |  
> Drawings
> - Drawing: 1 | Fol. 160v: Crude drawing of a cross.
> - Details |  
> - Drawing: 2 | Fol. 161v: Crude drawing of a cross.
> - Details |  
> - Drawing: 3 | Fol. 180v: Crude drawing.
> - Details |  
> - Drawing: 4 | Fol. 185v: Drawing of a human eye.
> - Details |  

Yet the xml file in BM only has

```
<decoDesc>
                     <decoNote type="miniature" xml:id="d1">
                        <locus target="#160v">f. 160v: </locus>
                        <desc>Crude drawing of a cross.</desc>
                     </decoNote>
                     <decoNote type="miniature" xml:id="d2">
                        <locus target="#161v">f. 161v: </locus>
                        <desc>Crude drawing of a cross.</desc>
                     </decoNote>
                     <decoNote type="miniature" xml:id="d3">
                        <locus target="#180v">f. 180v: </locus>
                        <desc>Crude drawing.</desc>
                     </decoNote>
                     <decoNote type="miniature" xml:id="d4">
                        <locus target="#185v">f. 185v: </locus>
                        <desc>Drawing of a human eye.</desc>
                     </decoNote>
                  </decoDesc>

```

meaning for some reason parts of decoration descriptions got lost (?)

**Comment by PietroLiuzzo** [comment]
This is quite possible, as you know not everything could be parsed and encoded in the new files. I will look into this and see if this information can be restored.

**Comment by eu-genia** [comment]
i have now retyped it in this particular file but would be good if the others are checked... whoever then does the adjustments could otherwise lose the info

**Comment by PietroLiuzzo** [comment]
ok, please do not retype it for other cases so that the extent of the issue can be evaluated and the eventual updated done systematically. thanks!

**Comment by eu-genia** [comment]
another thing: i remember that the transcription in ES mss was once batch updated/corrected, but now again I encounter  ˤ instead of ʿ - maybe it was left behind (?) - can the files be reupdated?

**Comment by PietroLiuzzo** [comment]
another thing another issue :) #807

**Comment by eu-genia** [comment]
(I have not retyped those)

**Comment by PietroLiuzzo** [comment]
the miniatures element is sometimes used as boolean. this will result in a empty miniature decoNote. 
please check the committed files, I have already looked at 30 of them and it looks to me that the requested improvement was achieved.

**Comment by eu-genia** [comment]
it seems to me that again a lot of information has got lost

ESagm004

> Miniatures
> Miniature: 1 | Fol. 66r: Virgin Mary and the Child with the archangels Michel and Gabriel.
> - Details | Legend: ቅዱስ፡ ሚካኤል፡ "Saint Michael". [ማርያም፡] ምስለ፡ ፍቁር፡ ወልዳ ፡ "[Mary] with her beloved Son". ቅዱስ፡ወገብርኤል፡ "and Gabriel". The miniature might have been produced for this Ms., but was added later (legends are written by the scribe Wäldä Muse?).

ESagm004

```
<decoNote type="miniature" xml:id="d3">
<locus target="#66r">Fol. 66r:</locus>
<desc>
Virgin Mary and the Child with the archangels Michel and Gabriel.
</desc>
</decoNote>
```

**Comment by eu-genia** [comment]
ESagm010

> Miniatures
> Miniature: 1 | Fol. 107r: Cross.
> - Details | An elaborate talismanic picture of the cross is drawn over the entire fol. in black, red and yellow.
> 

 
No DecoNote in BM

**Comment by PietroLiuzzo** [comment]
@eu-genia please close issue if this is now ok
