### ISSUE TITLE
finding mss in beta masaheft

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#808]
It would be helpful for users looking for specific manuscripts if the alternative ids given in  `<altIdentifier>` would also be displayed in the manuscript view http://betamasaheft.eu/manuscripts/list. I'm not sure whether that is possible and/or would make the table view too crowded. Maybe Hands or Manuscript Parts could be deleted? (Though surely others might look for just that...)
I think that finding manuscript is a very basic user need which should be a priority for us.

**Comment by PietroLiuzzo** [comment]
![schermata 2018-04-18 alle 07 01 38](https://user-images.githubusercontent.com/508012/38912582-61e4c730-42d6-11e8-8644-4fc04e12d084.png)
how about this?

**Comment by thea-m** [comment]
Wonderful! Would a space be possible between each identifier?

**Comment by PietroLiuzzo** [comment]
added.
