### ISSUE TITLE
text parts in Art Themes?

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#810]
In AT1022MiraclesOfMary, a textpart has  been added for a specific miracle. I think that this practice is not documented in the guidelines? It is also not visualized. 
Depending on the general practice in Art Themes encoding, it might be more precise to create AT records for each specific miracle, and then add relations so that all single miracles would still be connected to  AT1022MiraclesOfMary? Or only AT1022MiraclesOfMary could be used and the particular miracle described in the ms description?

**Comment by eu-genia** [comment]
this was a test run (my doing, to create a sub-id for a specific miracle) but on discussion with Pietro this shall now be removed: we should only keep the general authfile applicable to all miracles (without textparts), and for specific miracles a link should point to the actual work - will clean the art theme file now

**Comment by Gnisci** [comment]
Thanks for input Genia

**Comment by thea-m** [comment]
Thank you! Could you then add this to the guidelines, @eu-genia ? Others might come across similar cases
