### ISSUE TITLE
marking up ligatures

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#813]
I think it could be useful to mark up ligatures when transcribing text. In Ethiospare, the presence of ligatures has been encoded in the description of the hands, and we can of course do the same, but it would be nice to mark this up in the actual words as well. Could we use  `<hi rend="ligature">`?
(I don't know if there is any possibility of actually having a character for the most common ligatures (ግዚ for example), please correct me if that exists!)

**Comment by PietroLiuzzo** [comment]
you can certainly do that, encoding with <hi rend="ligature">. if there is a unicode character for the gliph representing the ligature we can easily use that for the visualization of the ligature, just give me a list and I will tell the transformation to use those when rendering the content of the element

**Comment by thea-m** [comment]
as far as I know there are none

**Comment by PietroLiuzzo** [comment]
I vaguely remember @abausi perhaps has something which he uses in CTE ?

**Comment by abausi** [comment]
no, as far as I know there are none

**Comment by PietroLiuzzo** [comment]
should I then visualize this markup in any particular way? underlined? with a line above the letters involved?

**Comment by abausi** [comment]
that could be a way, provided that underline isnot already used for anything else

**Comment by thea-m** [comment]
underline is already used for hi rend="underline"
 (hi rend="overline" has also been used occasionally, probably all instances represent the catalogues' indications for rubrication, but could not be checked in the manuscripts)

**Comment by abausi** [comment]
one could perhaps a new mark, such as "mon", i.e. monogram

**Comment by PietroLiuzzo** [comment]
<hi rend='ligature'> is semantically correct, and will contain the sequence of character composing the ligature. what remains to be decided is how to display these, but given that there are no symbols, I will use a line above. Could you please provide an example file where this has been encoded?

**Comment by PietroLiuzzo** [comment]
I have added a render for this as a line above the ligatured letters.

monograms (which I thing are different from ligatures) can be encoded as abbreviations, so that the encoder is also able to avail himself of abbreviation marks and similar as in standard TEI.

however we do not render these yet.

**Comment by PietroLiuzzo** [comment]
we now support abbreviations in standard TEI in the output and I have updated the previous PR to the guidelines with information about how to encode. I have also added a standard rendering with ()

**Comment by PietroLiuzzo** [comment]
IMHO this issue can be closed...

**Comment by thea-m** [comment]
Thank you!
