### ISSUE TITLE
visualisation of empty elements in institutions

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#818]
Could `<ab type="history"/>`, `<ab type="tabot">` and `<desc type="foundation">` in institution records only be visualized if they have content? See for example INS0325CR

**Comment by PietroLiuzzo** [comment]
@thea-m @MargaretheJenner @eu-genia yes, I am doing this, BUT: please keep in mind that an empty element is making an empty statement, so, please try to avoid leaving empty elements around.

**Comment by PietroLiuzzo** [comment]
i.e. please fix the institutions where those empty elements appear.

**Comment by thea-m** [comment]
I deleted the empty elements in institutions
