### ISSUE TITLE
tabot

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#819]
do we write tabot or tābot? Both are used in our records. I would be in favour of tābot, since it is not yet a common English word. In any case, we should agree on one transcription.

**Comment by eu-genia** [comment]
it should be tābot of course, i think the other spelling was inherited from E-S or EAe which both have a different transcription convention.
the type (persName) can possibly remain though, main thing is that what is printed is correct

**Comment by thea-m** [comment]
Thank you!
@PietroLiuzzo could you update the visualisation of `<ab type="tabot">` to "Tābots"?
