### ISSUE TITLE
Link to text in general entry

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#821]
In my experience, many people miss the "text" link in the general entries of manuscripts on the app. Would it be possible to have a link to the transcription automatically added to the general description whenever the ms record contains a @corresp to the xml:id of a msItem in `<div type="edition">`? 
For example in http://betamasaheft.eu/manuscripts/BNFet113/main, when clicking on ms_i1.7, there would be a link to http://betamasaheft.eu/manuscripts/BNFet113/text, because the ms record contains 
```xml
<div type="textpart"
                 subtype="chapter"
                 corresp="ms_i1.7"
                 xml:lang="gez"
                 xml:id="ExtractChapter5">
```

**Comment by PietroLiuzzo** [comment]
![schermata 2018-04-18 alle 10 25 07](https://user-images.githubusercontent.com/508012/38920105-c9fe84d4-42f2-11e8-9008-25faca52fb7a.png)
a button called transcription will take you to the correct div if the div has a @n attribute.

**Comment by thea-m** [comment]
I do not see this button yet:
![image](https://user-images.githubusercontent.com/19650382/39465690-fe910cf8-4d24-11e8-8544-165ea0c8efba.png)

**Comment by thea-m** [comment]
Sorry, I apparently see an older version of the app

**Comment by PietroLiuzzo** [comment]
jetzt ist es da

**Comment by thea-m** [comment]
perfect, thank you!
