### ISSUE TITLE
<term> not appearing again in DecoNote

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#822]
@PietroLiuzzo for some reason `<term/>` has stopped appearing again in the Deconotes (you had fixed this I recall).

So one has to type: 

`<term key="angel">angel</term>`

instead of

`<term key="angel"/>`

to visualize content on the app

**Comment by PietroLiuzzo** [comment]
@Gnisci please do not encode to get a visualization. encode correctly and consistently and ask if you have visualization issues.

**Comment by PietroLiuzzo** [comment]
can you provide an example case, please?

**Comment by Gnisci** [comment]
http://betamasaheft.eu/manuscripts/BLorient481/main

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/manuscripts/BNFet32/main#d5 
here the issue does not occur

**Comment by Gnisci** [comment]
![immagine](https://user-images.githubusercontent.com/31648831/38736197-94f0dd70-3f2b-11e8-828e-12a1a65e3112.png)
```

 <decoNote type="miniature" xml:id="d12">
 <locus target="#99r"/>
 <desc> A miniature of the <ref type="authFile" corresp="AT1054AnnunciationZaccharia"/>. 
<persName ref="PRS10509Zachary"/>, to the right, 
holds a  <term key="censer"/> and a <term key="cross"/>.
<persName ref="PRS4377Gabriel"/>, to the left, holds a <term key="cross"/> and performs a 
<term key="gesturewitnessing"/> rather than one of speech.  The scene takes place in front of a 
<ref  type="authFile" corresp="AT1034Tempietto"/> which functions as an explicit to the Eusebian Apparatus, and features  a lamp and a <term key="curtain"/>.  At the top of this picture, on the right
 and left,  are several <term key="bird">birds</term>, namely two ሰጉና፡ or ostrich, as is typical 
 in miniature of the Tempietto, and two ጢራ።. The miniature is the result of a mixing of models
</desc>  
</decoNote>
```

**Comment by PietroLiuzzo** [comment]
BLorient481 works well, I am afraid you just did not wait for the page to finish loading (see spinning well on top left)
![schermata 2018-04-13 alle 15 05 41](https://user-images.githubusercontent.com/508012/38736401-351e9cb0-3f2c-11e8-8b93-decca641937c.png)

**Comment by Gnisci** [comment]
Goofy me! So sorry!

**Comment by PietroLiuzzo** [comment]
it is just a sign the website is too slow!
