### ISSUE TITLE
Showing titles of works on the text page

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#830]
It would be helpful if, on the text page of manuscript records, the titles of the edited work(s)/excerpts could be automatically printed. People can (for example by following a link in Dillmann) come directly to this page without having seen the main entry previously (which they might also be unable to find...), and it would be much clearer for them if they would immediately know what texts they are looking at.
For example, on http://betamasaheft.eu/manuscripts/BLorient718/text there could be printed somewhere in the vicinity of "folio 1" "Life of Lālibalā = CAe 4922". I am not sure if this would be possible if only a @corresp to the msItem is provided in the edition (which is not always done anyway), or if we would need to add a note repeating the title of the work there.

**Comment by PietroLiuzzo** [comment]
the user case description is a bit elliptic for me. Why would they be mislead if they see that they are on a manuscript page? how can we help them out of this?
The change should be no problem, let's see if it helps.
You do not need to reproduce titles anywhere. if there is a corresp, all good, otherways there should be a label. if neither, the placement should help

**Comment by PietroLiuzzo** [comment]
actually this is already the behaviour in the app. fiui! see FSUrueppII2
if the corresp points directly to a work record it will take that, otherways it will look at the local id e.g. #ms_i1 and check if there is a title with a ref or some content in there.
In this case for BLorient718 the transcription has no corresp of any sort and no label, thus only the folio and column breaks are shown. I have changed the name of the tab from text to transcription for manuscripts. I am closing this issue but there is

**Comment by thea-m** [comment]
Thank you for the clarification and checking the manuscripts. We were all obviously not consistent with the use of @corresp, @MassimoVilla @nafisa-valieva .
The users are not mislead, they open for example the  ቀንአት፡ entry in dillmann and see that the word is attested in BLorient718. When they follow the link they arrive at http://betamasaheft.eu/manuscripts/BLorient718/text?hi=%E1%89%80%E1%8A%95%E1%8A%A0%E1%89%B5&start=1, which is perfectly fine. The problem is that they don't get the idea to click on "Entry" and thus have no possibility of reading the manuscript's catalogue description (the same is also true vice versa, apparently no one comes up on their own with clicking on "Text" in the main entry.) This seems to be an issue with the design, but I have no better proposition either.

**Comment by PietroLiuzzo** [comment]
I propose a blinking arrow and a popup with some advertisement of the content. like "Hey, there is more to read, click here!"... every time you open a page you get that and it disappears after like 5 seconds...

**Comment by PietroLiuzzo** [comment]
Which kind of inconsistency do you notice @thea-m ?

**Comment by thea-m** [comment]
using/not using/using @corresp without #...
The other record I had checked before writing the issue was BNFabb247 where there is no corresp either

**Comment by PietroLiuzzo** [comment]
I think it is no inconsistency if there is or not @corresp. not always you can give that information, so we cannot make it a must do. the usage of @corresp pointing to an internal id without starting with the id sign (#) is just a mistake, is not an inconsistency :) see https://github.com/BetaMasaheft/Documentation/wiki/guidelines#references
i.e.
`corresp="ms_i1"` is wrong (but i fiexed this instances this morning)
`corresp="LIT1234Catena#subid"` is fine
`corresp="LIT1234Catena"` is fine

**Comment by PietroLiuzzo** [comment]
can this issue be closed?
