### ISSUE TITLE
Notebook as object form

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#833]
I suggest adding "Notebook" or a similar value to the schema as form in `<objectDesc>` (in `<physDesc>`, instead of Codex etc.). I have now a manuscript (ESakm010) which uses a (lined) notebook as carrier - there may be many more, esp. copied in the colonial period. Any objections? @MassimoVilla @DenisNosnitsin1970 @thea-m

**Comment by MassimoVilla** [comment]
I personally agree with this new value, which in my view we definitely need. Let's think of all the Conti Rossini paper manuscripts now in Rome

**Comment by DenisNosnitsin1970** [comment]
Perhaps a better definition would be necessary - is the industrially produced paperblock one of the main characteristics?

**Comment by thea-m** [comment]
I've added the value to the schema ("An object consisting of an industrially produced paperblock in the form of a notebook") so that we have it for now, feel free to modify the definition

**Comment by eu-genia** [comment]
I would say that ANLcr27 is also a Notebook, it surely is NOT a codex, as most colonial mss. @DariaElagina
