### ISSUE TITLE
Persons in manuscripts

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#834]
The guidelines say on the person list:

> Here it is enough to enumerate the scribe, owner, donor and patron, not everyone mentioned in the manuscript. If this information has already been stated elswhere in the description - **which is preferable** - it doesn't need to be repeated.
> 
```xml
 <particDesc>
  <listPerson>
    <person><persName ref="PRS2232AubertR" role="donor"/></person>
    <person><persName ref="PRS2233Audon" role="scribe"/></person>
    <person><persName ref="PRS2233Audon" role="other"/></person>
  </listPerson>
 </particDesc>
```

which is correct but when the information is not stated elsewhere in the description we only see the info if clicking on relations.

may be confusing especially for an external user.

see e. g. BLadd11620

it does have
```
<particDesc>
<person>
<persName ref="PRS11107Bartol" role="owner">Bartholomaeus</persName>
<persName ref="PRS11108Yaeqob" role="scribe">Jacobus</persName>
</person>
</particDesc>
```
but since the information is not provided anywhere else the persons are only visualized under relations, and without the Latin names given by the cataloguer.

So I suggest to either impose that the information is given somewhere within the manuscript description (best for the scribe would be inside the `handNote`), or that the persons from the `particDesc` are nonetheless printed in the main view as Scribe and Owner and Donor.

(cp. e.g. ESakm010 which has the Scribe in the Codicological description - how should one guess that we also know the scribe for BLadd11620)?

**Comment by PietroLiuzzo** [comment]
The second non-imposing solution is easy to do. 

I do not understand the last question in brackets.

**Comment by eu-genia** [comment]
(it is not a question just an illustration of a "visible" vs an "invisible" scribe) if the names can be printed in the main view that's perfect

**Comment by eu-genia** [comment]
the left column with the navigation is the emptiest ones - can we have a small box at the bottom, can be maybe in smaller font?

still we should somehow make up for the encoding difference - that sometimes names are tagged as `role="scribe"` or` role="owner"` etc inside the description (`handNote `or `colophon `or `additions`) and sometimes only listed in `particDesc`... would be good to have a box listing all names assigned manuscript-related roles, whether in `particDesc` or elsewhere

**Comment by PietroLiuzzo** [comment]
It does not really matter where they appear. they are persName elements with a role attribute. the difference is mainly originated by the need of importing the data from a flat db structure, but it does not harm in any way to have these in different places.

**Comment by PietroLiuzzo** [comment]
the navigation bar is relatively empty. it can be very full in some records, I will make a box in smaller font at the end of the codicological information

**Comment by eu-genia** [comment]
it does if one quickly scrolls through mss records and wants immediately to see the scribe/donor/owner information - they should be in the same place. if the box appears that only reflects the `particDesc `content then those mentioned elsewhere can become "invisible" in their turn as one does not know where to look for them (the descriptions are sometimes very long)

**Comment by PietroLiuzzo** [comment]
i.e. you want this box, as the one in the relations view, not to pick from partiDesc as you asked at the beginning but to take any persName with a role attribute. ok, no problem.

**Comment by eu-genia** [comment]
it should also print the names as provided in the description, if different from the person record (e.g. in the example above BLadd11620 has `<persName ref="PRS11107Bartol" role="owner">Bartholomaeus</persName>` but under relations it is printed "Bartalomewos"

**Comment by eu-genia** [comment]
in mss with several msParts the box should better appear only at the end of the first (main/general) codicological information (for the entire ms) - it now appears there, but then also repeats for each msPart, even where not relevant (see e.g. ESakm011)
(it could also appear for each msPart but then specific for that msPart)

**Comment by eu-genia** [comment]
if the same person is scribe and donor and has two `persName `elements in the description to show that only one role appears in the box

**Comment by PietroLiuzzo** [comment]
the first comment is resolved. the second needs to be specified better and with an example, beacuse I do not understand.

**Comment by eu-genia** [comment]
sorry too few punctuation signs
the box should show all roles mentioned, not just one (as it is already done in analytical view, but not in main view)
e.g. ESakm011 Gabra Giyorgis scribe donor (now only scribe is shown)

**Comment by PietroLiuzzo** [comment]
please check now

**Comment by eu-genia** [comment]
thanks ok now
