### ISSUE TITLE
objects of veneration 

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#836]
we might need an additional category of records for objects of veneration who are not persons

e.g. we can have tābot dedicated to Mary (currently encoded under `<ab type=tabot>` as <`persName ref="PRS6819Mary" type="tabot">Mary</persName>` but also to the Holy Cross, which is not a person so cannot have a PRS type of `id `(we have Masqal under authority files for the moment but so far used mainly for the Feast - if we want to have a record summing up all that we would also do for a saint, such as the dates related, history, texts dedicated etc. this is not enough), or to Kidāna Meḥrat (similary, there is a Covenant of Mercy under ArtThemes, but it is not really the same)

what do you think, @DenisNosnitsin1970 ?

for the moment I shall be using the existing `id`s within the `<ab type=tabot>`  with a `<ref>` (will be updating the guidelines accordingly)

@PietroLiuzzo shall then adjust the search mask that will look for all pointers within the  `<ab type=tabot>`, not only `persNames`

**Comment by DenisNosnitsin1970** [comment]
why don't we treat Cross as Person? there is little difference between it and a person as it is personified.
otherwise yes we need a separate type of records but these would be really very few, i can only think of
Cross
Covenant of Mercy
Four Animals
is it worth it creating such a limited category? can we not treat them as persons for the time being and later see?
more ideas? @MassimoVilla @thea-m

**Comment by thea-m** [comment]
Having keyword records would not work for these entities?

**Comment by abausi** [comment]
I would support the idea of having a category of its onw, as "objects of veneration"

**Comment by eu-genia** [comment]
@thea-m - a keyword record does not allow you to have/visualize in one place all the information such as 
- possible names
- texts dedicated to
- churches dedicated to
- feasts etc. (what we can do for saintly persons)

we can, as @abausi suggested, treat the Four Animals as an epithet/symbol for the Four Evangelists and create a person group for them, but the others are rather inanimate

**Comment by abausi** [comment]
In my opinion we need a technical, sustainable, compatible solution; in general, we should try to create as few new categories as possible, all the more if these apply to unique or very limited cases; in light of these general guidelines and last comments, I would be in favour of the keywords solution

**Comment by eu-genia** [comment]
created keywords, updated relevant records
