### ISSUE TITLE
specific labels for texts

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#838]
when a text in a manuscript appears under a specific label (recorded under the LIT record with an own ID and pointed to with a specific sub-id "`#`") this label should be the one printed.

e.g. 
ESakm010 has
`<title type="complete" ref="LIT2051Nagara#t3"/>`
should print "Zenāhā  la-ʾǝgzǝʾtǝna Māryām"
from

```
<titleStmt>
            <title xml:id="t1" xml:lang="gez">ነገረ፡ ማርያም፡</title>
            <title corresp="#t1" xml:lang="gez" type="normalized">Nagara Māryām</title>
            <title corresp="#t1" xml:lang="en">Story of <persName ref="PRS6819Mary">Mary</persName>
            </title>
            
            <title xml:id="t2" xml:lang="gez">ገድለ፡ ማርያም፡</title>
            <title corresp="#t2" xml:lang="gez" type="normalized">Gadla Māryām</title>
            <title corresp="#t2" xml:lang="en">Life of <persName ref="PRS6819Mary">Mary</persName>
            </title>
            
            <title xml:lang="gez" xml:id="t3">ዜናሃ፡ ለእግዝእትነ፡ ማርያም፡ </title>
            <title xml:lang="gez" corresp="#t3" type="normalized">Zenāhā  la-ʾǝgzǝʾtǝna Māryām</title>
            <title xml:lang="en" corresp="#t3">The Story of Our Lady Mary</title>
            

         </titleStmt>
```

**Comment by PietroLiuzzo** [comment]
the explanation and the example collide. from your example you do not want the id you are pointing to, but the corresponding normalized text, so you want rules to be applied to the subset of titles with that id.

**Comment by eu-genia** [comment]
the print rules should also apply for relation graphs

**Comment by PietroLiuzzo** [comment]
title printing rules apply everywhere, there is a module for that used pretty much everywhere. so, please, tell me which relation graph is not giving you what you expect.

**Comment by eu-genia** [comment]
looks ok, dont know why did not show previously

**Comment by PietroLiuzzo** [comment]
check now
http://betamasaheft.eu/manuscripts/ESakm010/analytic

**Comment by eu-genia** [comment]
now appears correct

**Comment by PietroLiuzzo** [comment]
There is now an issue with the function which handled this. titles:printTitleID($id)

**Comment by PietroLiuzzo** [comment]
it is possible that there is regression also here.
