### ISSUE TITLE
images glued to mss

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#843]
There are several instances in our records of manuscripts which contain devotional images glued to a leaf. Maybe we should document in the guidelines how we encode these images. In BAVet111, `<decoNote type="illustration">` has been used, but this could maybe be misleading? Or is it fine as long as the image is described in `<desc>`? Would it be better to have a dedicated value for @type in decorations? 
I could also imagine that such an image could be in fact a later addition to the manuscript, but this might not always be clear.

**Comment by eu-genia** [comment]
even if i am not assigned: i agree we need a solution to this; a pasted image is actually equivalent to an msPart in most cases as it is a separate unit of production, and often also an originally separate unit of circulation - but i was wondering if our ontology with a set of appropriate relations can help to formalize this

**Comment by PietroLiuzzo** [comment]
I do not think a glued image is necessarily a production unit, and If it is, I wonder how often a relevant one. also I am not sure I would generalise the identification of circulation units. in my understanding of La Syntaxe du Codex, which introduces these concepts, both these are units which are not to simply be observed and notated, but are defined for each manuscript and an outcome of the methodological process. I think @type='illustration' might help, with a good definition for this value in the schema to describe the phenomenon, without having to explain with text every time.

**Comment by PietroLiuzzo** [comment]
IF the pasted image is actually a UniProd or a UniCirc, you can use relations to say so.

````xml
<relation active="BAVet111#d1234" name="SdC:constituteUnit" passive="BAVet111#UniProd1"/>
<relation active="BAVet111#d1234" name="SdC:constituteUnit" passive="BAVet111#UniCirc1"/>
```
`

**Comment by PietroLiuzzo** [comment]
this part on relations is not yet documented and will not be until the end of the conference next week. no need to make an issue or keep this one open.

**Comment by Gnisci** [comment]
The image may also be glued to the board of the manuscript, this happens for instance in BnF, eth. d'Abbadie 82: http://gallica.bnf.fr/ark:/12148/btv1b8538810r/f4.item.r=Ethiopien

**Comment by PietroLiuzzo** [comment]
I think, rereading the first post that it is indeed fine with a type and a desc. It would feel a bit over documented to specify how the image was added to the mss at this point. In the description, glued could be made into a keyword and added following the usual workflow to a relevant list in the taxonomy

**Comment by thea-m** [comment]
@DenisNosnitsin1970 also agrees to encode these images as type "printedImage" in decorations. The type printedImage (A printed image, usually of devotional character, glued to a manuscript) will be added to the schema
