### ISSUE TITLE
ʾƎgziʾabǝḥer za-bǝrhānāt 

### ISSUE THREAD

**Issue by MassimoVilla** [BetaMasaheft/Documentation#844]
There seem to exist two records pointing to the same work: LIT1327egziab (inherited from the EAe index) and LIT3083RepCh363 (from Chaine's repertoire). Both indicate the text ʾƎgziʾabǝḥer za-bǝrhānāt ʾǝgziʾabǝḥer za-śǝlṭānāt.
I am inclined to delete the former and leave the latter, and merge all the occurrences in the MS records.
Is there something I am disregarding?

**Comment by thea-m** [comment]
I agree with you, merging the records seems the best solution

**Comment by eu-genia** [comment]
sure, should become one
