### ISSUE TITLE
visualization of label

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#845]
In LIT4915PhysA, the content of `<label>` of each chapter is not visualized (as it is for example in LIT1401Physio). Is this intended?

**Comment by MassimoVilla** [comment]
Only chapters identified by means of a narrative unit are visualized, and so far only two narrative units have been created: for chapter 3, i.e. the caladrius (NAR0014caladrius), and chapter 4, i.e. the pelican (NAR0013pelican). The other chapters are still identified by means of a simple `<label>` , so their titles are not displayed in the app.

**Comment by thea-m** [comment]
But in LIT1401Physio, the content of <label> of all chapters is printed, not only for chapters 3 and 4:
http://betamasaheft.eu/works/LIT1401Physio/text?per-page=49
