### ISSUE TITLE
visualization of dates in <placeName>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#847]
Placenames in the Chronicle of Galawdewos encoded like this:
```xml
 እም<placeName ref="LOC6845Ajam" notBefore="1540" notAfter="1559">በር፡
                     አጀም፡ </placeName>እስከ፡ 
```
(in paragraph 3)
are visualized as:

>  እምበር፡ አጀም፡  After: 1540 Before: 1559እስከ፡ 

This seems unusual to me, is it intended? Maybe the date range could be given instead in a pop up window when hovering over the name?

**Comment by PietroLiuzzo** [comment]
I agree that the information is superfluous in the text edition view. I have removed it. the encoding of this data appears anyway on the map in the main view.
