### ISSUE TITLE
placenames with pleiades ID in the chronicle of Galawdewos

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#848]
Placenames encoded with a pleiades ID in the chronicle (for example `<placeName ref="pleiades:678369">ሰማርያ።</placeName>` in paragraph 8) are visualized as links on the app, however, when I click on them nothing at all happens. @SophiaD-M however gets a new tab with an error message.

**Comment by PietroLiuzzo** [comment]
now the geez word will be treated as a word and link to a search in the dillmann and you will get a arrow on the right with the correct link. for links to local files you will instead get the normal behaviour (link on word and hand pointing for references)
