### ISSUE TITLE
double visualization of clavis

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#849]
The content of `<bibl type="CAVT">` seems always to be visualized twice on the app when it is the only clavis reference given in a record, see for example LIT1340EnochE. Other clavis IDs and records in which CAVT is not the only one given seem to be fine.

**Comment by PietroLiuzzo** [comment]
this is because I have put the listBibl inside a p instead of making another sourceDesc. I am going to
- [ ] fix the records with this issue
- [ ] document this practice (more sourceDesc elements for different informations)
