### ISSUE TITLE
use of <editor> in work records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#850]
We have always used `<editor>` less frequently in the work records than in records of the other entities, maybe because of the different associations the word raises here. Renderings on the app as 

> Maṣḥafa Henok
> Edited by Ran HaCohen, Dorothea Reule

are a bit misleading.
The guidelines state, after a somewhat cryptical sentence, "If there is a digital edition, a editor will be added.", but do have editors in works without a digital edition.
Another point to consider that in work records especially often many people add different information at different times, making it thus harder to identify one main editor for the record than in the case of manuscript or person records.
So currently we have many edited work records without editor, some with a more or less random editor, and the newly created records with as editor the one who created them. If this situation should be changed, I think it would either be possible not to use `<editor>` in works which do not contain a text edition (but this would be inconsistend with all other records) or to change the visualization to something like "Record edited by..." (in which case it would maybe be good to find a solution for all those edited records which currently have no main editor). What do you think?

**Comment by PietroLiuzzo** [comment]
the guidelines should certainly be updated to say that here the editor is intended as editor of the digital edition in the TEI file. So it is correct that also only work on the metadata is part of this editorial process. the wording can be changed in the visualization and I would encourage always to have an editor or more in the TEI.

**Comment by PietroLiuzzo** [comment]
if you only add a comma, then perhaps don't add yourself as editor, but indeed for anything a bit more meaningful add a change in the revisionStmt
