### ISSUE TITLE
<ref target="#ed1"/> in physiologus

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#851]
In LIT4915PhysA,
```xml
  <editionStmt>
                <p>Digital text of <ref target="#ed1"/> based on <bibl><ptr target="bm:Hommel1877Physiologus"/></bibl>.</p>
            </editionStmt>
```
is visualized as 

> Digital text of Extra with id based on Hommel 1877.

Maybe it would be better to write something in `<ref>`? The edition? And wouldn't it make more sense for the link to go to http://betamasaheft.eu/works/LIT4915PhysA/text?

**Comment by PietroLiuzzo** [comment]
The rendering to string of `<ref>` has been updated to give more precise names for the entities referred to even in the event that no type is given. 

> Digital text of edition ed1 based on Hommel... ,

if the target had pointed to the #ed2 which has @resp="MV" it would have returned

> Digital text of edition by Massimo Villa

you can still write something in` ref`, if you want indeed!

**Comment by PietroLiuzzo** [comment]
this is not anymore there. why remains a mystery

**Comment by PietroLiuzzo** [comment]
this is actually right in the attribution of contents box at the bottom, but is not in the box with the bibliography

Attributions of the contents
Digital text of edition ed1 based on Hommel, F. 1877. Die aethiopische Uebersetzung des Physiologus nach je einer Londoner, Pariser und Wiener Handschrift (Leipzig: J. C. Hinrichs’sche Buchhandlung, 1877)..
This file is licensed under the Creative Commons Attribution-ShareAlike 4.0.
