### ISSUE TITLE
naʿā Giyorgis

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#854]
LIT4957SebhataF and LIT4964NaaGiyorgis possibly point to the same work, whose text does not seem to be transmitted uniformly and which is to my knowledge not well researched.
See also the bibliographic reference to the printed edition in ESum024, which I had not yet added to LIT4957SebhataF.

**Comment by MassimoVilla** [comment]
You are right. It's exactly the Sǝbḥāta fǝqur za-Giyorgis. I have merged the two records in favour of the earlier one.
Thank you!

**Comment by thea-m** [comment]
I have also deleted LIT4325Hymn, which seems to be the same text as well
