### ISSUE TITLE
custodialHist

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#858]
does `<custEvent type="restoration" subtype="ancient"/>` in BAVet1 and IVvostochn610 refer to an ancient restoration of the manuscripts or has it been copied from an example ms record (the restoration is mentioned nowhere else in these two records)?

**Comment by MassimoVilla** [comment]
As for BAVet1, it has been inaccurately inherited from the example ms record. I have removed it.
Thank you!

**Comment by PietroLiuzzo** [comment]
#859
