### ISSUE TITLE
custEvent type="restorations"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#859]
`<custEvent type="restorations">`  is visualized nowhere on the app and cannot be searched for.  This element has only been used in ES records, maybe its use was already discussed somewhere else?
Would a visualization be necessary or is the information anyway encoded in other places of the records (condition)? Is this something that people would be interested in searching for?

**Comment by PietroLiuzzo** [comment]
just let me know where you want it and how.
also for the search, let me know what you want to search for and I will add that filter for manuscripts

**Comment by eu-genia** [comment]
since this is something only given in some - but not all - mss, it probably was considered relevant by ES project. @DenisNosnitsin1970 should know more

**Comment by PietroLiuzzo** [comment]
btw. it CAN be searched for in the xpath search if you know it is there...

**Comment by PietroLiuzzo** [comment]
a new filter has been added in the list view with a warning. this information is now displayed at the bottom of the entry.

**Comment by thea-m** [comment]
thank you!

**Comment by PietroLiuzzo** [comment]
this search does not work. this is almost certainly related to the tabot thing. saved changes seam not to survive rebooting.
