### ISSUE TITLE
doublets in places?

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#860]
It seems to me that a few doublets have been created (can you please check @sologebre ?), they possibly have to be deleted and IDs readjusted.

E.g.
LOC6876Nile - we already have LOC4996Nile
LOC6927DabraWarq - check if not the same as LOC2393DabraW
LOC6913GanataGiyorgis - we have LOC3290Gannat 
LOC6945Ambassal - we already have LOC1413Ambass

For those areas which are not administrative units but descriptive regions inhabited by people (like the land of Gurage, the land of Arsi etc.) the reference should be to the Ethnic entity, e.g. Arsi ETH1154Arsi

**Comment by PietroLiuzzo** [comment]
this "should" is not documented as far as I know, i.e. I have not seen revising the guidelines any place where this is stated. Please formalise this statement checking it against the actual data and propose an update to the guidelines about it.

**Comment by sologebre** [comment]
Only the first one with the Nile, the rest are correct. Dabra Warq is the name of the monastery and also the name of the region in Goǧǧām. Similarly, ʾAmbāssal is the name of the region and also the name of the mountain in the ʾAmbāssal region. So we should keep both files. Ganata Giyorgis is the name of the monastery as it is documented in the chronicle of King Susǝnyos, so I have created a file for it. Yes, Ganta Giyorgis is also the name of the church in Gǝšše, so we both have to keep it. 
On the other hand, descriptive regions inhabited by people (such as the land of Gurage, the land of Arsi, etc.) should not always necessarily be related to ethnic unity. This can only become clear in the context of a  given text.

**Comment by eu-genia** [comment]
Gannata Giyorgis should have the geminated n (already corrected).

This ethnic/geo issue has been discussed in several meetings, and that was the decision suggested by @abausi - followed by me also in AS annotation. For pre-modern sources this is the only way. 
It has also been said that the records for the ethnic groups should provide the possibility to describe the geography if the term is also used in such meaning, this has not been further discussed though.

**Comment by PietroLiuzzo** [comment]
please define what needs to be decided, because the name of the issue does not reflect the contents of the discussion. Once decided what to do for the selected item under discussion, please document the decision in the guidelines. if it is already somewhere, provide a link for discussion here, if it has been discussed and did not make it to the guidelines we have to fix this before we can argue on correctness of one or the other behaviour for any of the topics here.

if the doublets have been solved, here remains as far as I understand a different approach on which ids to give while annotating named entities in texts. Is the difference just that Solomon used for the Chronicle places ids and Eugenia for Amda Seyon Ethnics?

I do agree with Solomon that only the context can decide if the text is actually referring to an ethnic entity or to a place. once that is decided than your principle applies without any problem. or do we have a problem in the definition of what the difference is between ETH and LOC ? 

some examples would also probably help to define the problem and decide what to document and if any change in the encoding is needed

**Comment by eu-genia** [comment]
we cannot define the difference as the terms in question are primarily ethnonyms. the texts have "the land of XX", the "troops coming from XX" or similar, where XX is sort of both, but primarily the people (as one often has in all ancient, also Greek texts, and @PietroLiuzzo mentioned in the oral discussion that they would indeed be tagged as ethnonyms). 
unfortunately the discussions were oral during the meetings, I guess we did not fix it in writing at that point.

**Comment by eu-genia** [comment]
the problem arises when doublets are created. there are already ETH ids for all such entities.

**Comment by sologebre** [comment]
I think it would be no problem to have two ids for each entity. In encoding the text, names that refer both to the name of an ethnic group and to the place where they live may require two ids, depending on the context. In a Gǝʿǝz text of the chronicle of Galāwdewos and even in the chronicle of Susǝnyos Hadiyyā is the name of an ethnic group (ETH1628Hadiyy) and it is also the name of a region where the people of Hadiyyā live in (we already have place id for it, LOC3720Hadiyy). Gambo is the name of an ethnic group (ETH1509Gambo) and the land where these people live in is also called Gambo (we have already place id, LOC3237Gambo). The people of Gurāge (ETH1613Gurage) and their country is called Gurāge land (most often called Gumar LOC6849Gumar). In this regard, we created a file for both an ethnic group and its administrative unit. That is exactly what we have done so far. 
Then we can encode these entities according to the context. If the name Gambo referred in Gǝʿǝz text for example as ወጠነ፡ ሰብአ፡ ገምቦ፡ here it certainly refers ገምቦ as the tribe name, then we tag with the ethnic id (ETH1509Gambo) while if the text reads, for example, ወሖረ፡ ለፀቢአ፡ አሕዛብ፡ ከሓድያን፡ እለ፡ ሀለዉ፡ ውስተ፡ ምድረ፡ <placeName ref="LOC3237Gambo" when="1551">ገምቦ።</ here we should tag the name Gambo with its place id (LOC3237Gambo). Indeed, for your information, land of Gambo is suggested to be the present day of north-eastern Wallagā as proposed by Kleiner (see Kleiner 2006). In the same way, we need two ids for Arsi, one as the name of a tribe of the subgroup of the Oromo (this has already been done, ETH1154Arsi) and as an administrative unit (LOC6874Arsi). I know Arsi tribe and its province very well.  It was the smallest province during the military government, it was the southern part of the region historically resisted the territorial expansion of Mǝnilǝk II. Thus, the name Arsi refers to both as an administrative unit and as one of the tribes’ names of Oromo nation.

**Comment by eu-genia** [comment]
We should be careful as we already once discussed to not project later developments onto the past. There was no Arsi administrative unit during the time of Galawdewos. 
It is OK to create an ID for the administrative unit - but it would apply to the Arsi province from the 20th century onwards. Same for Gambo, Gurage, etc.

**Comment by abausi** [comment]
I do not have time now

**Comment by eu-genia** [comment]
This is what I mentioned above: it had been previously decided to encode the geographical information under the existing ethnic entities, and this is the most practical and logical way of dealing with them. 
The schema for ETH-entries has to allow geographical information. Maybe a sub-type should be added (as we did for Institutions).
It has to be formalized in the guidelines though.
