### ISSUE TITLE
listBibl[@type='catalogue']

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#862]
the use of listBibl[@type = 'catalogue'] is documented in the schema (http://betamasaheft.eu/Guidelines/?id=listBibl)
quite synthetically. with @thea-m we have noted some possible inconsistencies in the use of this element.

What do you really use it for? 

In my understanding of the definition in the schema that is only to group bibliographical references to the catalogues describing the current manuscript. I would not expect to find it in a work record.
Should I add a rule to avoid this, which will mean a lot of new errors for you to fix?

We have also found listBibl[@type='catalogue'] used in manuscript records but containing references to catalogue entries description of other manuscripts containing the same work (please note the difference!)

This becomes quite evident when you get to a list of the manuscripts in a catalogue, which looks for listBibl[@type='catalogue'] and groups the manuscripts according to the bibl it contains, and you find there things which have nothing to do with the manuscripts in that catalogue.

**Comment by thea-m** [comment]
The situation is unchanged from the time that this issue has been written, does it make more sense to accept it or should the use be limited and the respective rules be added to the schema?

**Comment by DenisNosnitsin1970** [comment]
I think we should not add more rules. Sometimes there is indeed a need to refer to the catalogue of a manuscript exactly in the record for this manuscript (there are some descriptions spread over many pages, where the cataloguer makes specific statements etc.). Hopefully everyone understands that this way of referring should not be overused.

**Comment by PietroLiuzzo** [comment]
yes, but in that case it would not be a `listBibl[@type="catalogue"]`, it should be `listBibl[@type="secondary"]` anyway. in the semantic of the TEI this is just incorrect.

I will 
- [ ] add a rule to the schema preventing the use of catalogue in works and of edition in manuscript records
- [ ] analyse the files where this happens and fix them where this is possible.

**Comment by PietroLiuzzo** [comment]
There is no case of `listBibl[@type='edition'] `in manuscripts. 
There are in total 39 cases of `listBibl[@type='catalogue'] ` in works.
can anyone look at them to fix this? 
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fworks%27%29%2F%2Ft%3AlistBibl%5B%40type%3D%27catalogue%27%5D

**Comment by thea-m** [comment]
I can look at the catalogues in work records and fix them.
There are, however, 289 `listBibl[@type='editions']` in manuscripts :) I have used this when an edition uses the respective manuscript. Is this also wrong?
And why do you want to prevent `listBibl[@type="secondary"]` in manuscript records?

**Comment by PietroLiuzzo** [comment]
We have fixed the edition/editionS problem http://betamasaheft.eu/Guidelines/?id=listBibl

**Comment by PietroLiuzzo** [comment]
also secondary was a mistake in my previous comment

**Comment by PietroLiuzzo** [comment]
the 289 are an issue, but not a urgent one I would say. the information you are giving belongs to the `<listWit>` of the work record.

**Comment by thea-m** [comment]
The editions should be anyway present in the work records, but we do not use <listWit> much anymore, because the manuscripts containing the work are shown on the app anyway.

**Comment by PietroLiuzzo** [comment]
the list of manuscripts containing a work and the list of witnesses used for an edition are two different things. The first picks up whatever information is available, it might be less or more then we actually know at the moment. the listWit contains instead a statement, which can be nested about the manuscripts used for an edition and might contain also manuscripts which we do not yet have.
let's check that http://betamasaheft.eu/Guidelines/?id=work-teiHeader does actually make this cristal clear
