### ISSUE TITLE
content of <sourceDesc> in work records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#864]
probably not very crucial, but I noticed that the work records created from the google spreadsheet have
```xml
 <sourceDesc>
            <p>A Work part of Ethiopian Literature</p>
            <p>A TEI file converted from the ETHIO-authority google spreadsheet</p>
         </sourceDesc>
```
(which has often been deleted when a `<listWit>` or other paragraphical information has been added here), while in the newly created records, `<sourceDesc>` contains only `<p/>`.
Just for the sake of homogeneity, would it be better if "A Work part of Ethiopian Literature" would be added to all records (or deleted everywhere)?

**Comment by PietroLiuzzo** [comment]
I don't think it does any harm. those which have been converted from the table have that note until somebody edits them. I agree that the first sentence should be in all files, I will add it.
