### ISSUE TITLE
Role names and regiment

### ISSUE THREAD

**Issue by MagdaKrzyz** [BetaMasaheft/Documentation#866]
It would be good if someone explains what the differences between each of the subcategories are: office, function, rank and title. 
As for the name "regiment" not all military units that we come across in the edited texts can be called like that (see EAE "military units"). I suggest a broader class of "military units".

**Comment by abausi** [comment]
Denis was in favour of "regiment", if I remember well, that has the advantage of an established usage. But in fact it appears to be a convention

**Comment by eu-genia** [comment]
The categories are fuzzy, they were inherited from the EAe (there is an article on titles ranks and functions). For example, some clear divisions are: metropolitan (or king, or governor) is an office, abuna is a title, colonel is a rank. If impossible to decide, choose what seems the best fitting.

**Comment by DenisNosnitsin1970** [comment]
Yes, I was in favor of regiments, but one need to apply this term really to the groups which can be (conventionally) called "regiments". Some of them are well known. Not all groups mentioned summarily as "regiments" in EAE V, "military units" are the true regiments (like säwaryanä asayef, or jawe, or aqet zär), one has to define them in a different way.

**Comment by PietroLiuzzo** [comment]
@MagdaKrzyz where does the question originate?

**Comment by sologebre** [comment]
It appears that the names of the offices in Ethiopia's traditional civil administration and the titles given to these office holders are overlapping. This means that the title holders most often maintain the name of the offices. This is the case; therefore, great care must be taken to mark role names as a title or offices. Most of the time, when the role name is linked to a person, it is certain that we must mark the role names as a title. This is what happened most often in the text. For instance, ወእምቅድመ፡ ይብጻሕ፡ <persName ref="PRS2102Asbo"><roleName type="title">ደጅ፡ አዝማች፡</roleName>ዓስቦ፡</persName> ዓደወ፡ <persName ref="PRS11898Waldakrestos"><roleName type="title">ራስ፡</roleName> ወልደ፡ ክርስቶስ፡</persName> ምስለ፡ <persName ref="PRS11899Cawa">ጨዋ፡</persName> ዘ<placeName ref="LOC1713Bagemd">በጌምድር።</placeName>. 
However, there are also cases a role name does not appear directly linked to a person but we know from the context to which person that role name refers, in such case we markup also that role name as a title. We can identify a person to whom the title is referred through the context of the text and rarely referring to other relevant sources. For instance, ወእምድኅረ፡ ተቀበልዎ፡ በከመ፡ ተአዘዙ፡ ተራከቡ፡ <persName ref="PRS9038Susenyos"><roleName type="title">ንጉሥ፡ </roleName> </persName> ወ<persName ref="PRS1291Abreham"><roleName type="title">አበ፡ ምኔት፡ </roleName> </persName> ወተአምኁ፡ በበይናቲሆሙ፡ በአምኃ፡ ልብ፡ መንፈሳዊ። Here it is clear from the passage that the title ንጉሥ፡ is referred to Susǝnyos while the title አበ፡ ምኔት፡ is referred to ʾabbā ʾAbrǝham, the abbot of Dabra Libānos.
 	However, there are a few cases where role names appear in the text as office names (which are not linked to a particular person) that we will discuss how to mark them. In encoding of the chronicle of Susǝnyos, I have not yet found that the role names appear as offices. But I realized these cases when we had a discussion with Eugenia who notified that they appear in Chronicle of ʿAmda Ṣǝyon and other texts, for which we need to develop a system how to mark the role names when they represent offices that are not necessarily linked to a particular person.

**Comment by PietroLiuzzo** [comment]
the schema has indeed no definitions. 
http://betamasaheft.eu/Guidelines/?q=roleName&id=roleName
please add them

**Comment by thea-m** [comment]
I would propose as a starting point for definitions: 

function: not clear to me
title: title used when adressing a person, particularly of an office holder (e.g. ʾabbā, wayzaro, daǧǧāzmačč), to be used only within a persName, since names of offices and office holders can overlap
office: name of an office within an institution (e.g. Metropolitan, daǧǧāzmāčč, ), to be used only when not accompanied by persName, since names of offices and office holders can overlap 
rank: a position in a hierarchy, particularly military [I would probably not be able to distinguish these in an Ethiopian context from offices and titles]
other: 

I would be very happy for better definitions. I am also not sure whether this list was developed for the Ethiopian tradition or has been imported from elsewhere, maybe it should be adapted. @DenisNosnitsin1970 and @sologebre seem to me the most qualified for solving this.
