### ISSUE TITLE
Amharic transliteration

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#867]
It would be helpful if some indications on transliterating Amharic could be added to the guidelines: 
http://betamasaheft.eu/Guidelines/?id=transliteration-principles
There is for example "Kawalwal ǝska Mayč̣aw" for ከወልወል፡ እስከ፡ ማይጨው፡ in LIT4558Kawalwal: should this be Kä(-?)w(W?)älwäl or Māyč̣aw? Has this ever been discussed?

**Comment by thea-m** [comment]
@MagdaKrzyz do you maybe have Amharic transliteration guidelines already written down somewhere which you would propose us to follow?

**Comment by thea-m** [comment]
@MagdaKrzyz suggested to follow Traces, transliterating the orthography according to the same system as Gəʿəz - is this the approach to be adopted?

**Comment by abausi** [comment]
It should be "Kawalwal ʾǝska Māyč̣aw": it has to be rendered as it is written

**Comment by thea-m** [comment]
So contrary to our Gəʿəz transliteration no hyphenation of prepositions?
