### ISSUE TITLE
type="main" in persName

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#868]
use of @type="main" in persName to be documented

**Comment by PietroLiuzzo** [comment]
please see http://betamasaheft.eu/Guidelines/?id=persons if it is ok.

**Comment by thea-m** [comment]
thank you!
However, in the example of PRS3247Cyprian, the suggested encoding (which makes a lot of sense to me) leads to the visualization "Qoṗrǝyānos" - in line with the title selector priorities stated in #792 
It would be possible to encode it, as has already often been done, as 
```xml
   <persName xml:lang="gez" xml:id="n1">ቆጵርያኖስ፡</persName>
               <persName xml:lang="gez" corresp="#n1" type="normalized">Qoṗrǝyānos</persName>
               <persName xml:lang="en" corresp="#n1" type="main">Cyprian of Antioch</persName>
```
which I don't like this because to me it suggests that "Cyprian of Antioch" is an english version of the original name ቆጵርያኖስ፡ but please correct me if I am wrong.
Could the title selector instead pick first any title having @type="main" regardless of its ID? If we don't want to modify this process, 
```xml
  <persName xml:lang="en" xml:id="n1">Cyprian of Antioch</persName>
 <persName xml:lang="gez" xml:id="n2">ቆጵርያኖስ፡</persName>
               <persName xml:lang="gez" corresp="#n2" type="normalized">Qoṗrǝyānos</persName>
               
```
seems fine to me as well

**Comment by PietroLiuzzo** [comment]
I have done this modification to the script.

**Comment by PietroLiuzzo** [comment]
perhaps the rules for the titles should also be documented in the guidelines

**Comment by thea-m** [comment]
yes, is it now:
1. persName[@type = 'main']
2. persName[@corresp = '#n1'][@xml:lang = 'gez']
3. persName[@corresp = '#n1'][@xml:lang = 'en'][@type = 'normalized']
4. persName[@corresp = '#n1'][@xml:lang[not(. = 'en')][not(. = 'gez')]]
5. persName[1]

?

**Comment by PietroLiuzzo** [comment]
yes.
perhaps also for works and manuscript this should be documented so that it is clear to people what they will see printed and they do not play around with IDs. are you going to do this edit?

**Comment by thea-m** [comment]
yes! :)

**Comment by thea-m** [comment]
are the rules for work titles the same as for persons? I don't think that there is actually any confusion regarding manuscripts

**Comment by PietroLiuzzo** [comment]
In this case we are speaking of the title elements in titleStmt
- title[@type = 'main'][@corresp = '#t1']
- title[@corresp = '#t1'][@xml:lang = 'am']
- title[@corresp = '#t1'][@xml:lang = 'gez']
- title[@corresp = '#t1'][@xml:lang = 'en']
- title[@corresp = '#t1']
- title[1]

**Comment by PietroLiuzzo** [comment]
manuscripts should not be affected at all by this type of encoding, as the label/title of the manuscript is built looking at the repository and other information in msIdentifier

**Comment by thea-m** [comment]
thank you
