### ISSUE TITLE
faith of historical personalities

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#870]
The assignment of "faith" (especially biblical personalities, early saints and church fathers) is a bit inconsistent and can be problematic.
For example, St George is "Christian Orthodox", Aphrahat "Syriac". Why is Dillmann Christian but Ludolf Protestant? and Some Ethiopian personalities are "Orthodox" (PRS8746Semon for example), while the majority is "EOTC" - do we understand EOTC as Ethiopian Orthodox and simply assign it to Christian Ethiopians? Is it historically accurate, when the person in question could be for example an adherent of Qəbāt?
Apparently "faith" has also been interpreted as "faith in which this person in venerated", as in the case of Adam, who belongs to Christianity and Judaism according to our record (why not Islam though?)
(Another question is whether it is really necessary to add an faith to every person record? What is the point of stating that  John the Baptist belongs to "Judaism"?)
We could maybe formulate criteria for when and how to add a faith to person records.

**Comment by eu-genia** [comment]
I would tend to interpret faith as the professed one; Adam should better have none ?
Christian Protestant / Christian Orthodox is what I would expect for filtering purposes, so two values for Dillmann/Ludolf etc.
EOTC could then possibly be replaced with EOC to avoid problems?

**Comment by DenisNosnitsin1970** [comment]
I also interpret faith as the officially professed one. Sometimes it is not clear what a person exactly professed. Priests and monks are definitely Ethiopian Orthodox, and most of the Ethiopians until the mid-16th century too. But already in the 17th century there is a group of Ethiopians who lived many years as Orthodox Christians, but later became Catholics. Do they belong in the database to both confessions? Like King Susenyos. Alaqa Zannab was initially Orthodox, but then, as the BM entry states, he "converted without oficially leaving the EOC"; in the database, he is assigned only to EOC. Also there are cases where we do not know exactly if the person was Orthodox, Catholic or Protestant or which confession was more important for him. There were a lot of people who converted from Islam to EOC. Like ras Mikael father of Lijj Iyasu. Probably it is not quite correct to assign him only to EOC.

**Comment by thea-m** [comment]
I would also interpret the faith as the professed one.
- Two values are probably not needed, because "Catholicism", "Protestantism" and "Orthodox" are already visualized as "Christian Catholic" etc. 
- Note that the requirement to filter for faith has never been stated (and apparently not been needed until now) and therefore is currently not available in the advanced search.
- As for persons who have changed their faith, adding all faiths they ever professed makes the most sense to me. This is what I did with Wansleben.
- In the case of uncertainty, it is always possible to assign "Christianity" or no faith at all. This seems better to me than to overassign for instance EOC. I think that this is a point where a lot of "wrong" or inconsistent information does more harm than no information.
- I would propose to assign "Christianity" in the case of personalities of the history of the Church before its schisms rather than the modern confessions who claim these persons. We could however add "Ethiopian", "Coptic" or "Syriac". What do you think? From which point on would it then be useful to assign "Orthodox" (for us the differentiation between chalcedonian and non chalcedonian churches might be more relevant than "Orthodox" or not) or "EO(T)C"?

**Comment by thea-m** [comment]
Please note the modifications to the taxonomy and descriptions in the schema which I just added for the faith types. I have not added generic Christian "Coptic", "Syriac" or "Ethiopian" values as proposed in my last comment. Would you suggest doing this?
For Christianity, there is now:
- Christianity
contains:
    - Anglican
    - Catholicism
    - Protestantism
    - Orthodox
- Orthodox contains:
    - EOTC
    - Greek
    - Russian
    - Armenian
    - Coptic
    - Syriac

This leaves out Catholic Oriental churches, which could be added under Catholic when needed, the East Syrian Churches and Melkite Churches.
If you agree to my propositions, Athanasius for example would now simply be "Christian", since he lived before the council of Chalcedon.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 @eu-genia @DariaElagina @sologebre

**Comment by PietroLiuzzo** [comment]
can we close this ?

**Comment by thea-m** [comment]
my commit from  14 May 2018 had been reverted a few days later by @Gnisci (I assume accidentally), I no changed the taxonomy back. Since no one in the last year has expressed an opinion on this, I'm closing this issue. A new one can always be opened.
