### ISSUE TITLE
doublets in persons

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#874]
PRS12083Matako is a doublet for PRS6872Matakko (k should be geminated) - see EAe III:372b–73a - PRS12084KeflaMaryam is respectively a doublet for PRS5910KeflaMa. The records should be merged, in whichever direction. To check PRS12040Keflo vs PRS5928KefloK.
To check also the other persons, as most mentioned in the chronicles appear in the EAe meaning they are in the index meaning they already have IDs.

**Comment by eu-genia** [comment]
also PRS12087MalkaSediq is already there as PRS6607Malkase (see EAe IV 853a)

**Comment by sologebre** [comment]
It is checked and corrected.
