### ISSUE TITLE
visualization of two faiths

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#876]
Could you add a space or line break between the values for persons who have more than one faith?
For example in PRS10036Wansleb
```xml
 <faith type="Protestantism"/>
               <faith type="Catholicism"/>
```
is currently visualized as "Christian ProtestantChristian Catholic"

**Comment by thea-m** [comment]
`<faith type="EOTC Catholicism"/>` in PRS4767Gorgoryo is visualized as "Faith Unknown" - is the encoding wrong or could the visualization be changed?

**Comment by PietroLiuzzo** [comment]
The first point should be sorted, also in the live app. 
the second, I would say is strange more than wrong. as discussed over skype, I would assume that one professes a faith or another, and the encoding here suggests he has a foot in two shoes...

**Comment by thea-m** [comment]
thank you! yes, for the second case I will update the guidelines when #870 is closed
