### ISSUE TITLE
Visualization of Binding description

### ISSUE THREAD

**Issue by ElianaDalSasso** [BetaMasaheft/Documentation#878]
In the GAet.7 (http://betamasaheft.eu/manuscripts/GAet7/main) the decoNote attributes: 
- boards 
- cover
- endbands
- sewingStations
- Fastening
- Spine

are not showed on the web page. Only "bindingMaterial" and "Other" are visible.

The same happen in the binding description of GAet.1 (http://betamasaheft.eu/manuscripts/GAet1/main) for boards, sewingStations and Spine.

**Comment by ElianaDalSasso** [comment]
Thank you,
Would be possible to add a space between two words in the visualization of the section "SewingStations"?

**Comment by PietroLiuzzo** [comment]
done
