### ISSUE TITLE
keywords in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#883]
could it make sense to move some of the information contained currently in `<occupation>` (or not at all) to keywords? For instance, we have "Saint", "biblical" or "prophet" (often inherited from the spreadsheet but also used in new records) - maybe due to my conventional understanding they seem a bit out of place in occupation. We already use  `<term key="angel"/>` in person records, could it be useful to add more, for example a "saint" keyword, or would it be better to keep this information with occupation?

**Comment by PietroLiuzzo** [comment]
I would not take non reworked entities in the data, which come from the initial conversion as exemplar. if according to guidelines this is not useful, feel free to update those you come across in the best way you can. using keyworkds is fine. I have to say that I do not entirely understand your "(or not at all)". If there is here a call for a systematic change, e.g. move always content of occupation to keywords, then I can analyse the data to tell you if it is possible in any consistent way without causing trouble

**Comment by thea-m** [comment]
This does not only concern non reworked inherited entities, but as I wrote also newly created records and edited inherited records.  "or not at all" meant that the information is sometimes contained in occupation and sometimes not contained in the record at all. The guidelines allow here for flexibility: "Try to limit the use of `<occupation>` to actual occupations. " 
The question was a general one whether the information would be better encoded in a keyword than in occupation, which I believe would be the case for saint for instance. This concerns many of us and many records and I would not decide it hastily.

**Comment by PietroLiuzzo** [comment]
good, than this has no technical implications, I need not to be assigned.

**Comment by DenisNosnitsin1970** [comment]
I think there should be an possibility to indicate that the person is a "saint" (i.e. possesses some features of a saint  and enjoys veneration in one way or another). I do not percept the records too literally anyway, so occupation -  "saint" or "prophet" is ok for me.

**Comment by thea-m** [comment]
I agree regarding the ridiculousness (by now we have become too used to it), and person types and using them as keywords sounds good to me. (I find 126 times "saint" in occupation though...but these could then presumabely be converted). I don't think it's urgent either.
Any suggestions for other occupations that should be changed to a person type?

**Comment by thea-m** [comment]
We should maybe keep in mind that external users will always take the records literally at a first glance and might not return if our terminology seems too exotic

**Comment by PietroLiuzzo** [comment]
storing that information in keyword instead of occupation is semantically more correct and preferable. 
@thea-m would you like to update the taxonomy? when it is there I can work on the data, and will check again the numbers.

**Comment by PietroLiuzzo** [comment]
If users are not happy with the data, they should edit it. I will add a link to the GitHub repository from each item so that it is clear on each page that people can (and should) contribute.

**Comment by thea-m** [comment]
I'll do it

**Comment by PietroLiuzzo** [comment]
Thank you very much, I would start with the three above only.

**Comment by PietroLiuzzo** [comment]
![schermata 2018-11-27 alle 13 38 29](https://user-images.githubusercontent.com/508012/49082310-bf405980-f249-11e8-952d-cad11d534618.png)

**Comment by thea-m** [comment]
@PietroLiuzzo sorry this seems to have slipped from my attention. I wanted to add the saint keyword now to the taxonomy, but am not sure where. Should I start a new person types category?

**Comment by thea-m** [comment]
@PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
yes, you can do that, I do not recall the entire conversation above but it does look like this was the way to go

**Comment by thea-m** [comment]
I updated the taxonomy, could you check it @PietroLiuzzo ? I did not create a new record for angel, since there is already one. Can the same keyword be listed in more than one place in the taxonomy? 
If it is fine, could you update the schema?

**Comment by PietroLiuzzo** [comment]
I am not sure what you want me to check, but the files did not go through and I have updated them in the app. prophet does not seem to be there yet. no need for more than one angel.

**Comment by thea-m** [comment]
Thank you! They are not yet proposed by the menu and the records don't yet validate with them.

**Comment by PietroLiuzzo** [comment]
The tei server is still down, so I could not update the RelaxNG schema. I have hacked a change yesterday night and updated it. Please create the missing record for prophet.

**Comment by thea-m** [comment]
thank you!
