### ISSUE TITLE
choosing manuscripts in comparison view

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#884]
It could be useful to be able to chose which manuscripts to compare in the comparison view

**Comment by PietroLiuzzo** [comment]
you can now select manuscripts to compare from the list view
![schermata 2018-05-16 alle 12 58 22](https://user-images.githubusercontent.com/508012/40113215-fe5cd1f0-5908-11e8-8721-65dedc7311c8.png)
and click on compare selected manuscripts to be brought to a comparison view of those
![schermata 2018-05-16 alle 12 58 43](https://user-images.githubusercontent.com/508012/40113234-0bea71a6-5909-11e8-8831-7fceba697b10.png)

**Comment by thea-m** [comment]
thank you!
