### ISSUE TITLE
source in placeName 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#890]
The guidelines:
http://betamasaheft.eu/Guidelines/?id=named-entities-and-authority-lists
say on the encoding of placeNames in literary works:

> you can also add a @resp with the ID of one of our person records or editors and a @source with a list of bm:tags from the Zotero Ethiostudies group library 

I tried to find an example of this but found only in LOC3826Hawzen (so, not a literary work...):
` <placeName xml:id="n1" xml:lang="gez" source="#Lusini">ሐውዜን፡</placeName>`
Lusini being the xml:id of a bibliographic entry. Is this what is meant by the guidelines? I would have expected a zotero tag instead of an xml:id in the source.

**Comment by PietroLiuzzo** [comment]
the use of @source is documented here http://betamasaheft.eu/Guidelines/?q=source&start=6&id=sourceAtt
the use of your example from LOC3826 is documented here 
http://betamasaheft.eu/Guidelines/?id=places
it is indeed wrong that we should use there bm: things, I will update the guidelines.
