### ISSUE TITLE
nesting lists

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#891]
The guidelines http://betamasaheft.eu/Guidelines/?id=objectDescription
have in the collation section:

> Give a @xml:id to each item in the list to be able to refer to this unit, using "q" and a consecutive number. You can also nest lists, following the same ID pattern used for msPart for example.

I don't understand the nesting part and cannot find an example. Is there one anywhere? Thank you!

**Comment by PietroLiuzzo** [comment]
There is no example, it must be a residual of something very old. I have removed the sentence.
