### ISSUE TITLE
more than one @role for a person

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#893]
Can a persName have more than one role?
For example, in DSEthiop7 it seems that PRS11959Pawlos, mentioned in the colophon, was both scribe and owner of the manuscript

```xml
ዘ<persName ref="PRS11959Pawlos" role="scribe owner"><roleName type="title">አቡነ፡</roleName> ጰውሎስ፡</persName>
```
is not allowed

**Comment by PietroLiuzzo** [comment]
There is no other example as far as I can see and I would avoid it if possible, please. The secondary role can be added for example in particDesc/listPerson. This is a good example to add to the guidelines, I would put it here http://betamasaheft.eu/Guidelines/?q=scribe&id=particDescPersons

**Comment by thea-m** [comment]
Thank you!
that there is no example just means that it was never encoded in this way, which is to be expected, since it leads to an error. It is possible that there are similar cases were the information is given in a paragraphical description.
Anyway, I added the example to the guidelines
