### ISSUE TITLE
New record and last commits not displayed

### ISSUE THREAD

**Issue by ElianaDalSasso** [BetaMasaheft/Documentation#896]
The app doesn't display the commits I made yesterday: some modifications on GAet2 and GAet1 and the new record GAet3.

**Comment by PietroLiuzzo** [comment]
I had to turn off the hook to load the 13.000 mss I added yesterday without receiving 26.000 emails. I then forgot to turn it on again, I will now manually update in the app the 8 mss modified since, including yours. thanks for the notification
