### ISSUE TITLE
use of period keywords in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#897]
Particulary in the case of Zamana Masāfənt, but possibly also for other periods, the terms might not be familiar to users from other fields, but they have been used often descriptions in the persons records. Instead of explaining the term each time, could it make sense to use period keyword to mark up the periods ? For example, to have something as 
```xml
He was the last puppet King of the <term key="ZaMa">Zamana
                  Masāfǝnt</term>
```
(PRS10377Yohanne, keyword added by me)
If the keyword would link to http://betamasaheft.eu/authority-files/ZaMa/main or https://test.perio.do/#/p/Canonical/periodCollections/p03tcss/?show_period=p03tcssvtwm, no explanation would be necessary. What do you think?

**Comment by sologebre** [comment]
I think it's a wonderful suggestion. If necessary, we can also specify a specific year of events within the period of Zamana Masāfǝnt.

**Comment by thea-m** [comment]
oh, thank you!
