### ISSUE TITLE
visualization of rend="marginal"

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#898]
`@rend="marginal"` in additions is currently not visualized. Maybe the information could be rendered after the `<locus>`, for example in FSUor10
```xml
 <item xml:id="a1" corresp="#ms_i6.1" rend="marginal">
                                    <locus target="#48a"/>
```
as 
1. p.48a, marginal
?

**Comment by PietroLiuzzo** [comment]
I can visualize that, but I do not like the proposal, as it is very prone to inconsistencies, as it might be that there is no locus, or a wrong one or more then one, plus the attribute is attached to the entire addition, not just to its placement.

**Comment by thea-m** [comment]
I am fine with any visualisation, what would you propose?

**Comment by PietroLiuzzo** [comment]
![schermata 2018-05-30 alle 12 43 37](https://user-images.githubusercontent.com/508012/40715802-18822d6a-6407-11e8-92c5-6705d9d577ba.png)

**Comment by thea-m** [comment]
thank you!
