### ISSUE TITLE
definition of values for @type in listBibl

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#900]
It would be good if we could add definitions to all values specified in the schema, and specify the existing definitions, especially as to the entity types to which they refer:
http://betamasaheft.eu/Guidelines/?id=listBibl
- mss: seems to be used only in Ethio-Spare records to list other witnesses of a certain work. This suggests that we do not need this type in newly encoded records.
- text: I still do not know what  is meant by this, has only been used in a handful of (mostly old) work  records, but in quite a lot person records to list the works in which the person is mentioned or which they authored (while in many other person records, "edition" has apparently been used to encode the same, if the work happens to be an edition)
- otherLanguages: used in one work record for references to bibliography on this work in another language

As to the other types, they seem to have been used to encode any items that fit the category, i.e. all editions are encoded as "edition" regardless of the type of entity (persons, manuscripts, works). The current definitions are admittedly vague. See also #862

**Comment by PietroLiuzzo** [comment]
Sorry for the long time it took. Please have a look at the above commit, and tell me if it is satisfactory. This will not yet appear in oxygen, as I cannot yet transform the ODD to RNG.
