### ISSUE TITLE
administrative position box

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#908]
For the administrative box it would be good if the word "settlement" is replaced with the `@type` when provided (but in proper spelling of course)

E.g. in INS0042MR

it should say 

Country: Ethiopia
Region: Bǝḥerāwi Kǝllǝlāwi Mangǝśti Tǝgrāy
Waradā: Dabra Gannat
Ṭābiyā: Mārtā
Qušat: Gulo Maḵadā

In addition to the map, the coordinates themselves should also be printed.

**Comment by PietroLiuzzo** [comment]
@eu-genia 2 problems = 2 issues.

**Comment by PietroLiuzzo** [comment]
the order of this informations has always been in these boxes from small to big political entity, why are we changing it now?
it will look like this and once somebody creates RegionalState, then there will be also a proper title there.
<img width="333" alt="schermata 2018-06-01 alle 22 28 16" src="https://user-images.githubusercontent.com/508012/40861932-295f4fec-65eb-11e8-9cf2-1aae35adef5b.png">

**Comment by eu-genia** [comment]
if small to big, then it should be 
Qušat
Ṭābiyā
Waradā
Regional state
Country

but why not reproduce the order in XML?


RegionalState has been created

**Comment by PietroLiuzzo** [comment]
please simply decide and let me know. it makes no difference to me, I was just wondering because we go back and forth on this small things continuously. the settlements ARE already in the order in which they are in the file.

```xml
<settlement ref="LOC3640GuloMa" type="warada" from="2010-05-11" to="2010-05-13"/>
<settlement from="2010-05-11" to="2010-05-13" ref="LOC6970Marta" type="tabiya"/>
<settlement from="2010-05-11" to="2010-05-13" ref="LOC6971DabraGannat" type="qushat"/>
```

**Comment by eu-genia** [comment]
yes but not country - region. in the XML they go from big (country) to small (qushat), in the box the order is mixed

**Comment by PietroLiuzzo** [comment]
no, but you do want country after region, isn't it? and that is already like that as in the screenshot above. if the settlements are in the wrong order, they simply need to be fixed.

if instead you do not want to fix that in the data but want to revert the order I will invert and have it in order you suggested in the previous post i.e.
country
region
settlments (in the order they appear in the xml)

**Comment by PietroLiuzzo** [comment]
the RegionalState file is there, but the update of the taxonomy is not complete
http://betamasaheft.eu/Guidelines/?id=taxonomy

**Comment by PietroLiuzzo** [comment]
![schermata 2018-06-05 alle 11 50 41](https://user-images.githubusercontent.com/508012/40968837-c43ac956-68b6-11e8-84b3-92ee09d9660f.png)
for the capitals, please correct the authority files accordingly

**Comment by eu-genia** [comment]
Looks good.
