### ISSUE TITLE
illegible button

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#910]
The "Go to..." button which shows up in the compare view if there are no manuscripts containing the work is hardly legible (black script in dark grey beackground) unless one clicks on it, when the writing turns white. 
![image](https://user-images.githubusercontent.com/19650382/40966478-e3d280f2-68b0-11e8-89fc-2b52baa3b756.png)
Could the writing be white from the beginning, or the background colour changed?

**Comment by thea-m** [comment]
same for the "see full text" button in the text view of work records

**Comment by PietroLiuzzo** [comment]
nicht mehr

**Comment by thea-m** [comment]
danke!
