### ISSUE TITLE
Image of Mary's assumption

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#911]
@jonahsandford has asked me the following question:

_Speaking of EMIP00003, I am having a hard time locating the standard title for the Image of Mary's Assumption (ms_i1.3)_

I have tried this search

http://betamasaheft.eu/as.html?query=%22Image+of+Mary%22&element=title&AttestedInType=1&xmlid=&work-types=work

but I am not sure any of those is the one he is looking for.

Could anyone help?

**Comment by eu-genia** [comment]
LIT4971MalkeaErgata

**Comment by PietroLiuzzo** [comment]
thanks! 
I tested with another search: out of curiosity, LIT2110OntheA has nothing to do with this, right?

**Comment by thea-m** [comment]
there is also LIT2932RepCh213

**Comment by PietroLiuzzo** [comment]
what is the relation between these three records (not to count more that could come out in searches) ?

**Comment by eu-genia** [comment]
LIT2932RepCh213 is the Image of Mary's Dormition (Dormition is not the same as Assumption)

**Comment by PietroLiuzzo** [comment]
+ this is not stated anywhere in the data... we need to disambiguate at least

**Comment by eu-genia** [comment]
LIT2932RepCh213 is most probably the Malkǝʾa fǝlsatā attributed to Zar'a Ya'qob (according to Getatchew Haile)
Should be checked on the incipit which one is the one in EMIP00003

**Comment by thea-m** [comment]
I see that LIT2932RepCh213 has been used in EMIP00003 - it is now unclear to me to which work LIT4971MalkeaErgata refers. Is there in fact a reference anywhere to this concrete work, or does it now serve as a "general record" not yet used for any Malkǝʾa ʿƎrgatā different from LIT2932RepCh213 (in which case it could probably be deleted)?

**Comment by eu-genia** [comment]
I think I should re-delete it if it was LIT2932RepCh213 after all. Thank you.

**Comment by thea-m** [comment]
Thank you! Now the situation seems clearer. 
@jonahsandford , please reopen the issue if any questions or uncertainties remain, and thanks for bringing this up
