### ISSUE TITLE
Lectionary keyword

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#912]
I note that EMIP00003 has the Gospel arranged for the days of the week, this is therefore not a usual Gospel manuscript but a Lectionary. It is probably indeed not an extra Work type but we might need a way to mark/filter scripture mss of such type. Should I add a keyword?

**Comment by eu-genia** [comment]
To the record I mean, or shall the person working on the record (Jonah) be asked to do so? So far there are no keywords at all I believe.

**Comment by DenisNosnitsin1970** [comment]
I what sense is it arranged for the days of the week? It can be a Gospel irrespective of the arrangement (which can be only linear; the motes in the upper margins of the pages referring to lessons do not matter), or a Lectionary irrespective of its arramngement (days of the weeks, feasts. Sabbaths etc.)

**Comment by eu-genia** [comment]
http://betamasaheft.eu/manuscripts/EMIP00003/main

**Comment by DenisNosnitsin1970** [comment]
I see. Description should be organized in a different way. This is a classical Gospel of John written in the usual way; the lessons are indicated through the notes in the upper margin of some folios referring to the days of the week. The notes should be probably recorded in "extras"; some are in the main hand, some in a secondary hand. It is not that the main text is somehow divided into seven parts and arranged in a special way like "Lectionary". it remains coherent; but the manuscript was customized by the user(s) in the usual way. I would date the book to the 19th century.

**Comment by PietroLiuzzo** [comment]
@jonahsandford

**Comment by eu-genia** [comment]
@jonahsandford maybe can consider Denis' remark above
