### ISSUE TITLE
Locus in paginated MSS (Accademia dei Lincei 27)

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#913]
dear all,
the manuscript of Accademia dei Lincei 27 is paginated. How should I proceed then with encoding of locus?

**Comment by eu-genia** [comment]
I think if in `<extent>` you specify `<measure unit="page">` the `@locus` should refer to page number (unless already programmed in the app, @PietroLiuzzo can surely add the necessary definitions)

**Comment by DariaElagina** [comment]
ok, thank you

**Comment by PietroLiuzzo** [comment]
No, locus is only for locus, not for pages and the values there should be like 1r 1v or 1ra 1rb for example. locus is a core element on which a lot of computing is made, it cannot carry values which are relative to other information. Did anyone have such cases before?

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.eu/Guidelines/?id=referencing-the-manuscript

**Comment by PietroLiuzzo** [comment]
@eu-genia where did you find the piece of information about the connection of extent/measure and the values of attributes in locus? Thanks

**Comment by thea-m** [comment]
yes, many, and we have discussed it previously, though I don't find where now quickly
for example FSUor10
I remember that it was once visualiuzed as p. , but it is not anymore

**Comment by PietroLiuzzo** [comment]
thanks @thea-m . 
here a list of those with measure[@unit='page']
http://bet.mas/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fmanuscripts%27%29%2F%2Ft%3Aextent%2F%2Ft%3Ameasure%5B%40unit%3D%27page%27%5D

@eu-genia you are right, pp. is added instead of ff. if extent has unit page

e.g. in FSUor39

however, if you look at these example the inconsistency will become clear.

it says pp. but then the values are (correctly) given in folia (1r and 1v, not 1 and 2 as I would expect for pages)

**Comment by PietroLiuzzo** [comment]
There is no documentation for this, so one item here is certainly that we need to 
- [ ] update guidelines for paginated (not foliated) manuscripts

are in FSUor the values correctly given in folia converting from the catalogue pages or something else is happening?

I would be in favour of doing for example

`<locus from="1r" to="2v">1-4</locus>`, which will produce pp. 1-4 but will not break the computation on the values of locus attributes

**Comment by thea-m** [comment]
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fmanuscripts%27%29%2F%2Ft%3Aextent%2F%2Ft%3Ameasure%5B%40unit%3D%27page%27%5D
Most of the manuscripts were edited by me, I will check them in a few days :)

**Comment by eu-genia** [comment]
our converting from page to folio numbering could produce additional errors though

**Comment by thea-m** [comment]
In the FSU catalogue, the catalogue gives all indications with page numbers, but the manuscripts are in fact all digitized and foliated. I will have to go through the records one by one to make sure that they are consistent.

**Comment by PietroLiuzzo** [comment]
it is legitimate (but again, none of this is documented) also NOT to had the locus attributes

<locus>1-4</locus>

**Comment by PietroLiuzzo** [comment]
why @thea-m ? in the FSU from where do the folia notation in the loci come from?

**Comment by PietroLiuzzo** [comment]
then you don't need to check them again, isn't it? perhaps only to add back the pages to avoid the inconsistence of having for `<locus from="1ra" to="6vb"/>` something like _pp._1ra-6vb .
if we have `<locus from="1ra" to="6vb">1-12</locus>` we will have the correct computations for locus and the view will print pp. 1-12

**Comment by eu-genia** [comment]
In FSUor39 the description says extent: 201 pages (and the collation ends at 201) but the text goes to ff. 119v, does not seem plausible

**Comment by thea-m** [comment]
As I have said already, I have to check these manuscripts again. It is possible that I made mistakes or was not consistent in the use of foliation or pagination. I will do it next week.

**Comment by PietroLiuzzo** [comment]
please @DariaElagina encode AL27 as now documented in the guidelines, we will then test that everything is fine and use an example from there for the guidelines (so you can try editing that as well)

**Comment by eu-genia** [comment]
Could a small transformation script/tool be put up somewhere to quickly calculate the fol. from page?
e.g. 
(p+1)/2=f+r if the number is whole and f+v if there is a fraction on top, resulting in, e.g. for p. 99 or p. 100
(99+1)/2=50--->50r
(100+1)/2=50.5--->50v
I know it is a simple operation but maybe some automation could help avoid mistakes if there are a lot of page pointers in a paginated manuscript?

**Comment by eu-genia** [comment]
@Addisie please check this issue and the Guidelines for paginated manuscripts.
I have only now properly looked at your `MEAG002 `description and believe that it must be corrected.
You must specify unit="page" in the physical description and recalculate all values in attributes as if these were folia (see example 9 at https://betamasaheft.eu/Guidelines/?q=paginated&id=referencing-the-manuscript).

Note this must be applied to all manuscripts with pagination instead of foliation. Please check. Thank you!

**Comment by eu-genia** [comment]
In MEAG002 it should be
`<locus from="1r" to="9v">1–18</locus>` etc etc ("pp." will be printed automatically by the app since you provide `<measure unit="page">208</measure>`
