### ISSUE TITLE
use of mistara

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#916]
Where should the information that a misṭāra was used for ruling be encoded? In the guidelines, we mention the encoding of ruling patterns in `<ab type="ruling">` in `<layout>`. I have now added in DSEthiop12:
```xml
<layout>
<ab type="ruling">Misṭāra was used for ruling.</ab>
</layout>
```
(the manuscript contains several `<layout>`s and the ruling information is valid for the entire manuscript - should it be added to each layout? That seems a bit redundant but maybe would be clearer to readers.)

**Comment by PietroLiuzzo** [comment]
just one is enough, no locus specification already says that the information pertains to the entirety of the ms.
