### ISSUE TITLE
Guidelines on file names

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#918]
The issue #917 made me wonder - is it specified somewhere how files should be named? The IDs for places persons and works are generated in the app, but not for manuscripts, so our rule (LIBRARYcollectionNumber) may not be obvious to new users. Or am I missing something?

**Comment by thea-m** [comment]
http://betamasaheft.eu/Guidelines/?q=ID&start=6&id=entities-id-structure

**Comment by eu-genia** [comment]
thanks, sorry, missed it
but so did @DariaElagina

**Comment by PietroLiuzzo** [comment]
no,  @DariaElagina  did not, I misled her because I wanted to show her how to create a new entry! I will add this link to the form
