### ISSUE TITLE
Quire diagrams

### ISSUE THREAD

**Issue by jonahsandford** [BetaMasaheft/Documentation#919]
I am wondering if there is a way I can alter the labeling in my quire diagrams so as to distinguish protection quires from quires proper. To use EMIP 6 as an example (http://betamasaheft.eu/manuscripts/EMIP00006/main), Protection Sheet is appearing as "Quire 1" in the collation diagrams but should ideally appear as "Protection Quire" or "Quire 0" or something to that effect.

**Comment by PietroLiuzzo** [comment]
see this ES example updated by @eu-genia 
http://betamasaheft.eu/manuscripts/ESagm004/main
If I am not wrong the quire named A are the protection sheets and are distinguished from the others only by that name.

please let me know if you agree to have a different way of viewing that information.

**Comment by eu-genia** [comment]
it would be good, yes

**Comment by eu-genia** [comment]
If names of quires can be kept as they were assigned (e.g. in the Ethio-SPaRe) that could be the best, as I believe they sometimes also have quire B for the end protective quire and things like that.

**Comment by eu-genia** [comment]
Quire 0 is not a solution as there can be more.
See e.g. http://betamasaheft.eu/manuscripts/ESagm001/main - Quires A and B are protective leaves

**Comment by PietroLiuzzo** [comment]
So you just want to change the label.

```
<item xml:id="q1">
<dim unit="leaf">3</dim>
<locus from="1r" to="3v"/>
A(3; s.l.: 2, stub after 1/fols. 1r-3v)
</item>
```
where should I take the information? especially if A is not there and needs to be entered as in the EMIP case above? What about adding a `@type='protectionSheets'` to `<item>`? you would need to change this IN ALL existing collations.

**Comment by eu-genia** [comment]
i remember we talked about it at the very beginning two years ago when I noted the problem arising with the E-S descriptions that refer to quire numbers that do not correspond to the automatically assigned numbers in the collation diagram. so solving it whichever way is very good.

assigning a `@type` sounds makeable to me, maybe just `@type='protective'` or `@type='protective'`
I could batch search for all quires labeled A and B.

as a matter of fact, these leaves are usually referred to as "protective leaves" and are normally not part of collation, and neither foliated/paginated, as they are part of the binding, codicologically speaking (see Gumbert). 

but since we have inherited the bulk of E-S mss where they were always treated as quires, with folio numbering assigned, i guess they should be kept in the visualization.

**Comment by PietroLiuzzo** [comment]
@eu-genia what did you have in mind to safely batch search the quires "labelled" A or B ? I feel any text search would be either returning too many results or too many incorrect ones potentially. Perhaps it is better if I do that and then you can spot check if I have missed some cases. I will add the type where the quire description have A and B, after checking if this has been followed also in other descriptions. In this way it will not be the script deciding but the encoding will be somehow more explicit. I will then update the schema, update the guidelines and the visualization, which you will see with the next release.

**Comment by PietroLiuzzo** [comment]
is there an isse about the initial conversation? would be interesting to pick it up from where it was left

**Comment by eu-genia** [comment]
i did not mean automatic batch correcting, i meant rather manual work through E-S mss after a search in all the E-S files: while looking for A quires works quite easily (>A), the B is usually preceded by a space in the transformed XML (> B), but I can go through them all and assign the type, if that is the final decision.

i do not think the question made it to an issue back then

**Comment by PietroLiuzzo** [comment]
don't worry @eu-genia I will do this as commented above. You will possibly then get a list to check. There are also Non ES manuscript which have this.

**Comment by PietroLiuzzo** [comment]
I had another idea. What about printing under the quire diagram title the description as provided? that would surface the description also there exactly as it is given.
<img width="386" alt="schermata 2018-06-18 alle 07 39 07" src="https://user-images.githubusercontent.com/508012/41519836-cf397e88-72ca-11e8-8931-804b5b93cdfe.png">
<img width="188" alt="schermata 2018-06-18 alle 07 41 04" src="https://user-images.githubusercontent.com/508012/41519867-f514984a-72ca-11e8-9d1d-7d14fb97b800.png">
I have added a hint to the navigation info, explaining what those numbers in Quire 1 (2)   are.
In this way you need not change anything at all.

**Comment by PietroLiuzzo** [comment]
discussed during meeting:
the quire diagram title is the source of the confusion, it has been removed and is replaced by whatever content the item description has.
i.e. please @jonahsandford simply use text for protection sheets (not <note>) and that is what you will see in the quire diagrams
