### ISSUE TITLE
types for colophons in ES MSS

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#921]
types for colophons (which are not yet specified in the guidelines) have already been used for some Ethio-Spare manuscripts (ESsmm003, ESakm006, ESakm012), when #895 has been solved and we have met to discuss some examples, they should be updated if necessary

**Comment by PietroLiuzzo** [comment]
see email with document

**Comment by PietroLiuzzo** [comment]
#946

**Comment by PietroLiuzzo** [comment]
moved to 946, closing.
