### ISSUE TITLE
Texts written in two hands

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#927]
Dear all,
I have a question: how do we want to treat texts written in two different hands?  In IVorlov20, I have two cases, where according to Turaev's description, some text was presumably added later in another hand. The first one is the list of abbots of Dabra Libanos. Four last names are added in another hand. The second case is the "chronology in cycles" (Turaev) from Adam till Iyasu I. "The end of the text, starting from Yekuno Amlak" (Turaev) is written in another hand.  I have no idea, how these "additions" are layouted, but as next texts in both cases start on next folia, there is a possibility that these "additions" are written at the bottom. And there is no hint whether they were written in one hand or in two different hands. 
In my opinion, these added portions should be regarded as additions, because they are written in another hand, presumably later. And these texts might also be reagarded as complete without these added information, so it was not about the completion of the text, rather adding new information. But from another point of view, they are just extensions.

**Comment by PietroLiuzzo** [comment]
there is a recent issue which is related to this #887 
please also see the guidelines, which should have enough for the task of associating any portion of your encoding to the correct hand.
http://betamasaheft.eu/Guidelines/?q=hand&id=handDescription
http://betamasaheft.eu/Guidelines/?id=additionsVaria

**Comment by eu-genia** [comment]
the question here is not exactly the `<handNote>` question (which is clear) but rather - if according to the cataloguer there is a single `<msItem>` with a continuous text (as the new hand continues the text begun by someone else) - how do we show that it is a new layer (addition) while still preserving both the information that the resulting new extended text is also one whole (and may have also appear in this extended form in other manuscripts) and the interpretation of the cataloguer (who did not classify these extensions as additions)

**Comment by DariaElagina** [comment]
Yes, thank you, @eu-genia. Well, Turaev actually states that these portions were added. But he does not list them as additions, as zou rightly pointed to. So, it is also the question of interpretation of the information he gives.

**Comment by thea-m** [comment]
If the text were available, it would be possible to mark up the different hands in the transcription. In these cases, however, this is not possible. I would add a note to the msItem explaining the situation and possible an "extra" referring to the msItem as well. If upon assessing the manuscript, you discover that they are indeed additions, the record can be updated.
These texts do not fit the criteria for a quarternary stratum (independent content, not indepedent material, autonomous writing project), as their content is not independent from that of the main text.

**Comment by eu-genia** [comment]
Rediscussing with Pietro: the text remains as per Turaiev a single `<msItem>` where hand shift should be commented upon, with a `@corresp` to a relevant hand ID. The added names are not an independent text and modify the existing one and thus do not qualify as addition.
If we want to properly then describe the history of the MS and produce a graph in the Syntax du codex sense, a set of relations can be added explaining that as a result of an event a new UniCont was produced ([https://github.com/BetaMasaheft/Documentation/wiki/NAV3#example-1-bdlaethe8])

**Comment by PietroLiuzzo** [comment]
Since this part is not yet documented, as I am waiting for some more feedback from TEI community, I volunteer to encode this second part in the mss in question after the encoding of the description has been done.

**Comment by DariaElagina** [comment]
The description is ready http://betamasaheft.eu/manuscripts/IVorlov20/main
Secondary hands appear in p1_i11 and p1_i14. The whole information is given in note by now.
