### ISSUE TITLE
double entries with bm tags in zotero

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#928]
How are we to deal with cases of doublets in zotero, when both entries contain a bm tag? I don't know how to check which tags have been used in Dillmann, so I wouldn't want to delete one of them, but keeping both could also lead to confusion.
The only case I encountered is  bm:Cerulli1960ScrittiII and bm:Cerulli1960Scritti, as well as bm:Cerulli1958Opuscoli and bm:Cerulli1958Scritti.
I saw that there are some zotero entries with two bm tags, is that the solution?
Thank you!

**Comment by PietroLiuzzo** [comment]
There is a solution: fixing it! 
both double records and records with double tags are erroneous and do not follow guidelines. They need to be fixed.

**Comment by PietroLiuzzo** [comment]
you can use the bibliography search of BM to find out which one is used http://betamasaheft.eu/bibliography?pointer=bm%3ACerulli1960ScrittiII&collection=all
I have killed the record bm:Cerulli1958Scritti not used in BM and double of the above. I have done the other check for the other couple and binned bm:Cerulli1958Scritti 
using two tags is possible, but is a fruit of data entry phantasy which we ought to clean up on first sight.

**Comment by FrancescaPanini** [comment]
But please be careful about something: sometimes two records seem the same
but they are not as for instance the publisher is different. In that case
they are not double records and should not be removed.

**Comment by thea-m** [comment]
Thank you! I would love to fix and delete them ;) But currently deleting tags is also against the guidelines, so I wanted to be sure.
Does the bibliography search in BM also show the tags used in Dillmann? That was my main concern, searching and replacing in BM I can do easily.

**Comment by PietroLiuzzo** [comment]
It is now possible to run this search also on Dillmann

**Comment by PietroLiuzzo** [comment]
I have also updated the guidelines

**Comment by thea-m** [comment]
thank you!
