### ISSUE TITLE
relation + visualization for succession

### ISSUE THREAD

**Issue by eu-genia** [BetaMasaheft/Documentation#931]
We never used anything to mark the succession for kings / rulers / abbots etc.

It might be helpful though, also for the visualization to be able to move to the one before/after, similar to the Wikipedia style (e.g. for https://en.wikipedia.org/wiki/Amda_Seyon_I you see immediately the Predecessor and Successor and you can go left-right under the record): the succession is also by far not always father-son, so the family relations do not immediately help.

What do you think, @thea-m, @DenisNosnitsin1970, @sologebre, @DariaElagina ?
Is it feasible, @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
it is feaseble if you add that information.
in wikipedia those are not automatically somehow generated, they are added by the user to the bio template 

| predecessor        = [[Wedem Arad]]
| successor          = [[Newaya Krestos]]

**Comment by thea-m** [comment]
I had actually also already thought about this (too much time spent on wikipedia...), and I think that it could be useful (though, if care is taken to always mention the predecessor and successor in the text, not absolutely necessary). 
Would this translate into new relations for us to add to the records?

**Comment by PietroLiuzzo** [comment]
yes. it would be extra info to be added.

**Comment by eu-genia** [comment]
I understand that it has to be added, I just wanted to hear if everyone thinks it would be nice to have it - we then need two new relation types, unless there are fitting ones somewhere.
Especially for abbots and local rulers it would be an important added value (royal succession is present on wiki, but others are quite obscure, and we do find someone information, even in colophons and such)

**Comment by DariaElagina** [comment]
It would be definitely a useful upgrade.

**Comment by PietroLiuzzo** [comment]
There is nothing for me to develop here, so I do not see the need to assign me. please carefully check the SNAP ontology for proper relations and document the choices made.

**Comment by thea-m** [comment]
I could add bm:isSuccessorOf and bm:isPredecessorOf to our relations, except if such a relation already exists in an ontology you would propose we use @PietroLiuzzo ? (I did not find anything in snap)

**Comment by thea-m** [comment]
ah sorry, I didn't see your previous comment

**Comment by PietroLiuzzo** [comment]
have you searched LOV? http://lov.okfn.org/dataset/lov

**Comment by eu-genia** [comment]
there are many but most do not refer to persons but to works or geopolitical bodies or similar

dbpedia-owl:successor and dbpedia-owl:predecessor may fit, we have not used dbpedia-prefixed entities yet

**Comment by PietroLiuzzo** [comment]
ok, lets go ahead with the bm specific ones.

**Comment by thea-m** [comment]
I've added them

**Comment by eu-genia** [comment]
I have now added the relations to the record PRS1854Amdase for testing. Would be helpful to see them on the main page. Can we, @PietroLiuzzo ?

**Comment by PietroLiuzzo** [comment]
yes, with the next release
