### ISSUE TITLE
<affiliation> in person records

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#932]
There are several newish person records containing the element `<affiliation>`, which I believe has never been discussed and is logically not visualized (for example PRS12103Pakomis).
If the use of this element here is fine (I see no reason why not), could it be visualized?

**Comment by PietroLiuzzo** [comment]
please do not use it before the practice has been discussed and documented. We already do a lot of encoding of things in idiosyncratic ways only in a handful of records which does not help, just get things more confused IMHO. 
You can add the same information in a sentence inside the description, and link with a `<ref/>` or a `<placeName/>` or if it is too hard to write a sentence, you can use a `<relation/>`. So it is not that you do not have another way to do this.
I know this is not a specific way to encode exactly that information, but you all know we cannot just encode everything, and TEI does support plenty more than we use, but it does not mean we have to use it all, especially if we did not agree to do so. 
If this is a thing you plan to encode with any level of consistency we can decide if we want to use <affiliation/> and visualise that as well, but we cannot use it without having documented it. And we cannot document it if there is no aim for that to be encoded and there is no plan to encode that information with some consistency. 
I suggest to fix the records which have this encoding asap.
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%27%29%2F%2Ft%3Aaffiliation

**Comment by thea-m** [comment]
As these records were created by @eu-genia, it probably makes most sense if you do this, since you know the context best

**Comment by eu-genia** [comment]
I am sorry, it seemed to me a most logical place to put the information for monks belonging to a certain monastic community (or to that end, academics belonging to a university or similar context). Have taken all occurrences out now.

**Comment by thea-m** [comment]
thank you!

**Comment by PietroLiuzzo** [comment]
how have you decided to encode this?
is it now in the guidelines?

**Comment by eu-genia** [comment]
I have replaced the tag with descriptive text inside the `<floruit>` element which has been used for biographies.

**Comment by eu-genia** [comment]
(Yet if we do not want to ever use the element maybe it should not be valid in the schema?)

**Comment by PietroLiuzzo** [comment]
well, that is true of so many elements... but also explicit exclusion should be discussed, which was the point here, not the correctness of the encoding. there is still one affiliation, see link above.

**Comment by eu-genia** [comment]
now should be clean
