### ISSUE TITLE
New person function broken

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#941]
I cannot create new persons anymore

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <exception>
> <script/>
> <path>/db/apps/BetMas/edit/save-new-entity.xql</path>
> <message>
> exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Write permission is not granted on the Collection. [at line 583, column 19]
> </message>
> </exception>

(I might have tried to create a Batra Giyorgis twice just now)

**Comment by PietroLiuzzo** [comment]
please refresh your browser, clear your cache and login again. you might alternatively try to use another browser temporarily.
#940

**Comment by thea-m** [comment]
thank you, worked in firefox (where the login window even stays in its place and doesn't disappear all the time! it's wonderful!)
