### ISSUE TITLE
display in institution manuscripts having it as place of origin

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#944]
I think that it could be useful to display in the record of insitutions the list of manuscripts which have this institution as a place of origin, even if they are no longer kept there (this might be very relevant for instance for INS0101MadhaneAlam). 
I assume that these manuscripts will be picked up by the show attestations function (which currently doesn't work for me) anyway, but it could still be helpful to display them grouped together at a more prominent place? If it is not too complicated

**Comment by PietroLiuzzo** [comment]
isn't the filter by place of origin already giving exactly this functionality?

http://betamasaheft.eu/manuscripts/list?origPlace=INS0101MadhaneAlam

 (whereas the attestations is an entirely different thing)

**Comment by thea-m** [comment]
yes, thank you! 
But I don't manage to do it :) (I clicked on place of origin in INS0101MadhaneAlam and then on the filter icon and didn't get results)
http://betamasaheft.eu/manuscripts/INS0101MadhaneAlam/list?mainname=&date-range=0%2C2000&cp=&numberOfParts=&height=&width=&columnsNum=&tmargin=&bmargin=&rmargin=&lmargin=&intercolumn=&folia=1%2C1000&qn=1%2C100&qcn=1%2C40&wL=1%2C100&restorations=

**Comment by PietroLiuzzo** [comment]
if you click place of origin, the usual behaviour for additional filters occurs, i.e. a filter will be loaded, and you will see a spinning wheel. after that is loaded you can pick one of the place of origins of the manuscripts you are seeing and then hit the filter button. looking at your url, where the parameter is not set, you have not selected anything in the origPlace filter. I believe you expected to tick that and that the system would assume "look for what in this list of manucripts in INS1234 comes from INS1234" but that is not IMHO a very good behaviour given the manuscripts at one given insititutions might have very many different provenances. the loaded filter moreover already gives you for a given institituion an idea of the places from which the collections in the institutions originated.

**Comment by thea-m** [comment]
I was clicking on the filter in the page of the institution (hoping for "look for what NOT in this list of manucripts in INS1234 comes from INS1234", which probably cannot work like this), not the manuscript view, so nothing loaded. Anyway, now I understood how to find the information :)
