### ISSUE TITLE
Critical Issues in the encoding of Miniatures

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#947]
Dear @Ralph-Lee-UK ,

I see you've been doing a lot of work on the ATs, which is great, but I think that some of the encoding you did requires discussion and, at least in some cases, amending. 

So far, we've distinguished between iconic and historical depictions. Historical depictions (e.g. The Betrayal of Jesus, or the Crossing of the Red Sea) have a specific AT Id assigned to them. So, for instance, you've created an AT for the Last Supper, and that's just fine.

On the other hand, to date,  iconic portraits of Holy Men, Apostles, and Evangelists etc.. are simply labelled as such, and then further information has been provided with PersName.

I see that you have created some ATs that specify the identify of the figure that has been portrayed, more specifically: 

St George (wrongly encoded ID)
AT1068AngelwithSword
AT1073ArchPhanuel
AT1074TaklaHa
AT1077ArchangelMichael
AT1080AaronRod
AT1081GabraManfasQeddus
AT1082Angel
AT1083FourLivingCreatures
AT1084JesusChrist
AT1114Gabriel

This can be discussed, but I don't think this system works. It would entail creating an endless amount of ATs for each of the nearly infinite possible combination of two or more figures. I would be interested in hearing @eu-genia and @thea-m views on the matter. In any case, before implementing an encoding system that diverges from the one in use, please discuss this with the other team members, because it requires reshaping the whole approach.

 Even if we do proceed with encoding portraits of two or more individuals as ATs these should certainly not include their attributes. So for instance AT1080AaronRod is wrongly encoded in that it does not follow the guidelines. The "rod" should be included as an object in authority files. This also applies to e.g. AT1083FourLivingCreatures, which typically appear in miniature of the ascension or Maiestas and have hitherto been encoded as elements rather than themes. You could encode them as an AT if they featured in a miniature by themselves. I have never seen such an image, but if it exists then it can be an AT.

Additionally, I see you have created duplicates of already existing ATs:

AT1075PresentationJesus already exists as AT1027PresentationJesus
AT1076FlighttoEgypt already exists as AT1016Flight
AT1091TriumphalEntry already exists as AT1011Entry
AT1115JudasBetraysJesus already exists

Needless to say, you should check if an AT already exists before creating a new ID. This certainly requires fixing.

**Comment by Gnisci** [comment]
For much the same reasons I outlined with regard to the encoding of portraits I would be strongly against encoding undefined information as an AT. Such as

AT1078TwoBeardedMen 
AT1113TwoMen

This has no practical purpose and leads to an infinite amount of possible ATs. I think we need to clarify what is intended as an Art Theme = AT. An AT is a clearly identifiable subject that has a long-standing tradition of being represented in art. So, for example, Schiller's _Christian Iconography_ or Louis Réau's _Iconographie de l'art chrétien_, provide lists of subjects that are considered themes in art. A generic depiction of two non-identified men does not qualify as a theme.

**Comment by eu-genia** [comment]
I agree with Jacopo - the AT to be assigned for persons such as saints/prophets should be the generic one, and the saint is then identified with a persID so that everything becomes easily searchable.
E.g. any of the four evangelists gets (if alone) AT1013EvaPortrait, if there is a group (2 or more, no matter who) it is AT1014Evangelists etc.
Same should be done for the saints such as Takla Haymanot, historical persons, etc.

I am afraid there are more duplicates e.g.
AT1112JesusBurial for AT1010Entombment

Cross as a pattern is usually encoded via the keyword 
e.g.

                     ```
<decoNote type="drawing" xml:id="d21">
                        <locus target="#ir"/>
                        <desc><term key="cross"/></desc>
                     </decoNote>
```

Besides, I am not sure about "geometric patterns": these are usually encoded as ornamentation, or drawing, not miniature

**Comment by eu-genia** [comment]
AT1084JesusChrist not by any chance the same as either AT1055ManofSorrows or AT1040Ancient or any of the other standard representations?

Is AT1089ManOnHorse not the same as AT1012Equestrian?

**Comment by thea-m** [comment]
Thank you, @Gnisci for your comments, and also to @Ralph-Lee-UK for all your contributions, which are very enriching for us. 
Maybe some of the doublets pointed out can also be explained in light of the fact that the website (including guidelines) was offline in the last days (works now!!), which has made searching and checking a bit more cumbersome.
Not being an art historian, I do not feel qualified to develop guidelines for the encoding of miniatures. However, the system developed by @Gnisci and documented in the guidelines seems to me very consistent and we have all been able to apply it in our descriptions. In any case, we should all keep in mind that it is always better for variations from the guidelines to be discussed in an issue, to make sure that we're all more or less on the same page regarding encoding.

**Comment by eu-genia** [comment]
Dear @Ralph-Lee-UK ,
you have just created yet another AT, for Saint Luke, yet as I believe, according to the system suggested by @Gnisci the general AT for the Evangelist should be assigned here, and Luke specified by the persName element only.
Would it be possible for you to go through the Art themes and the manuscript descriptions and check?
Thank you so much.

**Comment by Ralph-Lee-UK** [comment]
Apologies, that was my mistake. 

 

I will go through these – there have been some problems with accessing the BM site, which have made this difficult.

 

Regards

 

Ralph 

 

Ralph Lee

Cambridge, UK

* +44 7906149088 
*  <mailto:ralphlee1965@gmail.com> ralphlee1965@gmail.com

 

 <https://www.facebook.com/ralph.lee.7505>   <skype:ralph_and_sarah?add>

**Comment by Ralph-Lee-UK** [comment]
I now see the earlier conversation that you started. I am trying to create a list of AT files so that it is easy to check what has been done. I am also trying to create more generic art themes, rather than be too specific. Perhaps we could have a Skype conversation about this, so that we are working to the same principles?

 

Regards

 

Ralph 

 

Ralph Lee

Cambridge, UK

* +44 7906149088 
*  <mailto:ralphlee1965@gmail.com> ralphlee1965@gmail.com

 

 <https://www.facebook.com/ralph.lee.7505>   <skype:ralph_and_sarah?add>

**Comment by Gnisci** [comment]
Dear @Ralph-Lee-UK ,

Thanks for reply. 

I would be happy to organize Skype meeting to talk this through, you can reach me at: j.gnisci@live.com

Speak soon

**Comment by Ralph-Lee-UK** [comment]
I'm going to give some time to correcting this just now. When I've done what I can, perhaps then we could have a conversation about it?

**Comment by Gnisci** [comment]
Surely. We can also talk about it before you start correcting things, it may be best in fact.

**Comment by PietroLiuzzo** [comment]
art themes and art keywords are listed here
http://betamasaheft.eu/authority-files/list

**Comment by Ralph-Lee-UK** [comment]
Are you available just now? I have just been working on deleting the duplicates
