### ISSUE TITLE
PDF Werkdatei

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#949]
In der PDF werden die Zeugnisse doppelt gedruckt. Wäre es möglich, Aufzählungszeichen oder ähnliches hinzuzufügen, um die Zeugnisse besser lesen zu können?
Außerdem ist die Schriftart auf Seiten 1 und 2 (der Teil zwischen Titel und Footer) zimelich groß.

**Comment by PietroLiuzzo** [comment]
bitte, mindestens einen Beispiel geben. dazu es wäre net einen Beispiel zu haben, wie es ist hier und wie erwartest du es auszusehen. danke

**Comment by SusanneHummel** [comment]
Sorry, ich hatte vergessen, den Link hineinzukopieren: http://betamasaheft.eu/works/LIT1709Kebran/main

**Comment by PietroLiuzzo** [comment]
bitte probier nochmal, ich hab Zeugnisse und Bibliographie aktualisiert (#950 )
