### ISSUE TITLE
PDf Werkdatei 2

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#950]
Die Literatur ist nicht wie in xml untergliedert nach "Secondary Bibliography". "Translation Bibliography" etc. Außerdem fehlen hier angaben zu den Zeugissen (z.B. bei "Editions Bibliography" > "Bezold" stehen die in der Edition verwendeten Textzeugnisse. Es wäre schön, wenn es auch in der PDF zu lesen wäre.

**Comment by PietroLiuzzo** [comment]
bitte, mindestens einen Beispiel geben. dazu es wäre net einen Beispiel zu haben, wie es ist hier und wie erwartest du es auszusehen. danke

**Comment by SusanneHummel** [comment]
Sorry, ich hatte vergessen, den Link hineinzukopieren: http://betamasaheft.eu/works/LIT1709Kebran/main

Es wäre schön, wenn die Bibliografie genau wie auf der webseite gedruckt werden würde. 

Bitte erst NACH deinem Urlaub (werde sonst nie wieder eine issue während deines Urlaubs schreiben...)

**Comment by SusanneHummel** [comment]
Perfekt!!! Sogar die Literatur so schön geordnet. Danke!!
