### ISSUE TITLE
unzutreffende Ergebnisse im Lexicon

### ISSUE THREAD

**Issue by SusanneHummel** [BetaMasaheft/Documentation#951]
Ich habe in http://betamasaheft.eu/works/LIT3122Galaw/text auf das Wort ቤተ geklickt. Dann wird dieses Ergebis im Lexicon angezeigt: http://betamasaheft.eu/Dillmann/?mode=fuzzy&q=%E1%89%A4%E1%89%B0&id=Lc4c9f51b3cb445c4b5047142f77a1a3f

Aber die Ergbnisse sind nicht alle richtig, z.B. im dritten Ergebnis unter "ቤዛ"stimmt nur der erste Buchstabe, und weiter unten, z.B. "ሮተ" nur der zweite Buchstabe.

**Comment by PietroLiuzzo** [comment]
das ist genau was die fuzzy search machen sollte. es gibt kein direktes link an einen lemma, deswegen die fuzzy search function sucht in Dillmann nach ähnliche Worte.
