### ISSUE TITLE
Differenciate new catalogisations and catalogue digitalizations on the app

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#952]
I think that it could be helpful for users (and good for us...) if it would be clearly visible on the app whether a manuscript record is the result of a new catalogisation or of the encoding of an existing catalogue (this is probably what should be highlighted in fact). All records have of course a "Catalogue Bibliography", but I don't think that users not familiar with the project will deduce from this that the catalogue was encoded and the manuscript in many cases not (yet) examined anew.
Maybe a short generic statement could be printed in the app under the editor line (reflecting if possible that the catalogue description has been updated in the record, which nevertheless does not yet constitute an exhaustive new catalogisation)? At least something like:

Oxford, Bodleian Library, Bodleian Laud or. 204
Edited by Dorothea Reule
This manuscript description is based on Dillmann, C. F. A. 1848. Catalogus codicum manuscriptorum Bibliothecae Bodleianae Oxoniensis, Pars VII: Codices Aethiopici (Oxonii: E Typographeo Academico, 1848) , page 35a–35b. 

Any ideas?

**Comment by PietroLiuzzo** [comment]
I fail to see the problem. there is complete evidence of the sources and no copy of any catalogue. I think your presentation for the begehung made it also quite clear that there is no such thing as a digitized old catalogue in BM, but all manuscript descriptions are new catalogue records, based on the explicitly declared sources. The status of this new (citable, fully attributed and version controlled) descriptions is given right at the top with the indication of its status as stub, work in progress, under review, etc. the information you ask for is already quite evident according to me and if you feel this need you can give it again in the editionStmt to declare which one of the catalogues was the main source of your description. I see no possible mistake by any user. it would require on their part a good deal of voluntary misjudgment to overlook DOI, references, citations, contents, bibliography, status, etc. and take those pages as digital copies of any given old catalogue.

**Comment by thea-m** [comment]
I understand your points, but I still think that experience (including the Paris workshop) has shown that most people do not grasp this intuitively and also do not set out to in depth studies of our records in order to understand their genesis.

**Comment by PietroLiuzzo** [comment]
that is probably what I do not get. why would one care about different types of "genesis" of information offered in bm? I would care about references and attribution. If more information is needed on this process there is encodingDesc, e.g.

**Comment by DenisNosnitsin1970** [comment]
I think that indicating the "genesis" in the beginning may be helpful, in the sense of distinguishing between "catalogued" - "previously uncatalogued" manuscripts. Dorothea, what if the manuscript had been catalogued online?

**Comment by PietroLiuzzo** [comment]
where a `<listBibl>` in `//additional//source` is present I can print a link to that in the header, beside editor, prefixed by "This manuscript description is based on". Where there is no `listBibl[@type='catalogue']` inside source I will print something like "Newly catalogued", how is that?
Please note that you can also
- make better use of the text provided in `<change>` 
- add a role description to the `<editor>`
- use freely `<encodingDesc>`
as all these will help clarity for the reader.

**Comment by PietroLiuzzo** [comment]
eventually the cases are many more. I differentiated the cases here so that
- the above is true
- EMIP will also print EMIP
- EMML manuscripts will print content of editionStmt
- IslHornAfr manuscripts will print a link to IslHornAfr website
