### ISSUE TITLE
Encoding miniatures of the Miracles of Jesus and Miracles of Mary

### ISSUE THREAD

**Issue by Gnisci** [BetaMasaheft/Documentation#954]
Dear All,

I was deleting a couple of duplicates and noticed that the miracles of Mary rising the artist who falls from his scaffolding has been encoded as AT1099StMary in EMIP00073 [link](http://cdm.csbsju.edu/digital/collection/SGD/id/8212). There is certainly merit in creating a separate AT for each of the Miracles of Mary and Jesus, as, especially in the 18th century, they form an important bulk of the decoration of manuscripts, but this would be a lengthily task. If it is agreed that these will be encoded separately, then they will certainly need a more specific ID than the one assigned to AT1099StMary.

Thoughts?

**Comment by thea-m** [comment]
If you think that it would be beneficial to do this, I would volunteer to start creating the records (with basic name and reference to the miracle in question, without deeper description of the art) for the miracles I encounter in manuscripts, since I am working on BL Oriental 645 now anyway.

**Comment by Gnisci** [comment]
I think this can be closed right @thea-m ?

**Comment by thea-m** [comment]
I have not done it yet, so I would prefer to leave it open (for myself)

**Comment by thea-m** [comment]
I now created two Art Themes for specific miracles, AT1108MMDaqseyos and AT1109MMWorker. I assigned a title, added a description in the abstract and gave keywords (the same as for most Miracles of Mary, with ChristianContent instead of ChristianLiterature). I also included a relation with the value ecrm:P129_is_about between the Art Theme and the miracle. Does this make sense from the encoding @PietroLiuzzo ?
@Gnisci I'm not sure which part of the description should be contained in the art theme records and which in the description of the manuscripts. Could you have a look at these two records and tell me what you think? That would be kind! (I did this description from BL Orient 641 and 645, I'm aware of the still missing bibliography...)
Thank you!

**Comment by Gnisci** [comment]
This is amazing @thea-m and it is a work of great value, thank you for putting it together.

It's ideal to present an overview of theme, as you did, in the general description. This saves repeating information in the actual description of the manuscript, when you come across new examples of the theme. Space should be reserved just for those details (art keywords) that we deem are worthy of being encoded (like objects or accessory elements) or variants.

In the case of your specific description, I would not refer to the three scenes as "miniatures" because they are typically found on a single page. So something along the lines: "A miniature illustrating the miracle of Miracle of Hildephonsus (Dexius) of Toledo generally depicted as a sequence of three episodes/events, showing: first, Hildephonsus of Toledo handing over to Mary the finished book of the Taʾāmmǝra Māryām, which she blesses and returns to him;  second, Mary presenting to Hildephonsus of Toledo a throne and garment; and third, Hildephonsus of Toledo 's successor falling and being smitten by an angel for having touched Mary's gifts to Hildephonsus without permission." 

I would leave out the part that the episodes are accompanied by captions (these ideally get encoded). In my experience (though I am not a specialist of the Miracles of Mary from the Gondarine period) the scene is depicted with remarkable consistency throughout the tradition. However, you may come across some variants in the traditions. To be significant we are not talking about small changes to the detail (such as Mary performing a slightly different gesture) but to overhauls that do not fit within the very broad description given above (for instance because the scene is treated in two rather than three episodes) these different recension (which are typically called "types" in art history) are worth spelling out in the general description given here (as I did for the Crucifixion). 

As far as I recall the theme takes up one page. But if you find occurences in which it takes up two pages, don't consider this as a different typology (simply broaden the descriptive field by saying that the theme is "typically found on one or two pages".

I am not sure if it is right to encode the information that he is handing a copy of the Miracles of Mary as <ref type="work" corresp="LIT2384Taamme"/> (but I have left it in the description for now), because we are not dealing with the work, but with a representation of it.

Finally, I have removed the third instance in which you mention PRS5555Ildefons, because you are talking about his unnamed successor, not him (he is absent in this episode) so he should not be encoded in it in my view. Don't you think?

I think your idea to preface each miracles with "Miracle of Mary" is excellent and facilitates the accessibility of the content. It ensures two paths for a user to identify material of interest.

Finally, I think that once one gets round to encoding the Miracles of Mary, as you are doing, it will probably be beneficial to delete the generic category: https://betamasaheft.eu/authority-files/list?keyword=AT1022MiraclesOfMary, which was initially created as a (admittedly somehwat innacurate) workaround to not have to encode every miracle. The category could perhaps be replaced with something generic such as "Miracle of Mary: unidentified", to ensure that also those instances where there is clearly a miracle but it cannot be identified get noted down?

Bibliography: always good to include at least a reference when time permits. I've added a reference to a study by Annequin. This is a guy who managed to publish a book with half of the images of the manuscripts flipped, so I don't trust his work, but it's still good to have a starting point.

Sorry for long reply, I thought it best to flesh out some points before you undertake this exceptional work.

**Comment by PietroLiuzzo** [comment]
is_about is fine, yes

**Comment by PietroLiuzzo** [comment]
I would avoid removing AT1022, and instead change its description only to say that it is a non better identified miracle or mary

**Comment by thea-m** [comment]
thank you @Gnisci , that is extremely helpful! I would suggest that I continue with the encoding (it is actually very interesting for me to learn something new I would not otherwise be in contact with) and you look over the files. If we notice that you have to rewrite everything or that this gets too complicated for any reasons, we'll find another solution. What do you think?

**Comment by Gnisci** [comment]
> 
> 
> I would avoid removing AT1022, and instead change its description only to say that it is a non better identified miracle or mary

Yes @PietroLiuzzo Pietro, that is what I was suggesting!

@thea-m that's fine, happy to help if and wherever needed.

**Comment by thea-m** [comment]
There are now descriptions of the miniatures of the ʾAkko-nu bəʾsi collection, which can be used as reference for future encoding of other miracles. A new issue can always be opened for further questions.
