### ISSUE TITLE
Unknown number of hands

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#957]
Dear all,
would it be a good idea to develop a solution for a situation when the precise number of hands in a certain manuscript can not be defined? I just have a statement in the catalogue, that 'diverse hands', so there are presumably more than one. In this case, one could later verify Turaev's description. But still sometimes it might not be possible to define the precise number of hands.
Is there probably a ready solution for such cases?

**Comment by PietroLiuzzo** [comment]
yes, there is
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-handDesc.html
simply adding a paragraph inside handNote and write what you want should do it!

**Comment by DariaElagina** [comment]
Thank you, Pietro. Should I probably add this to our Guidelines?

**Comment by PietroLiuzzo** [comment]
it is already in the TEI guidelines, and we do not behave in any special way here, so no need to replicate in our guidelines what is already in the TEI guidelines we refer to. Our guidelines are only a further specification. If you would like to add an example of this in the dedicated page of the GL, is up to you, it will do no harm and perhaps will help the next one with this question. thanks
