### ISSUE TITLE
creation of new person record

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#958]
I cannot create new person records through the app:

Mit dieser XML-Datei sind anscheinend keine Style-Informationen verknüpft. Nachfolgend wird die Baum-Ansicht des Dokuments angezeigt.
      <exception><path>/db/apps/BetMas/edit/save-new-entity.xql</path><message>exerr:ERROR XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: Database is read-only [at line 583, column 19]</message></exception>

I already emptied the cache and tried it in chrome and firefox

**Comment by PietroLiuzzo** [comment]
Please check now, I have cleaned up some space and restarted the server which was out of disk space

**Comment by thea-m** [comment]
works now, thank you!
