### ISSUE TITLE
Encoding of letters

### ISSUE THREAD

**Issue by DariaElagina** [BetaMasaheft/Documentation#960]
Dear all, right now I am working on encoding of a collection of private letters to Russian doctors in Amharic from Turaev's catalogue. I have a point to discuss with you. Would it be a good idea to create a new keyword? I do not find neither of the existed really fitting. Amharic literature does not fit because these letters are of course no literature. They are rather private letters, not legal documents, so the key word legal documant does not really fit. I think we should think of another key word, which would allow to search for such written documents easily. I think that all in all there are at least around 70 such documents in the collections of St. Petersburg alone. What do you think? Private letter?

**Comment by PietroLiuzzo** [comment]
I would go ahead with hesitation. Guidelines tell you how to properly create the keyword

**Comment by DariaElagina** [comment]
What would be then the best key word? Letter? Private letter is probably too narrow.

**Comment by thea-m** [comment]
Letter seems fine to me (we already have it as an addition type as well). Though I would argue that some letters could be viewed as being literary works, but that can be decided case by case.

**Comment by PietroLiuzzo** [comment]
If Letter is already there, then cannot we use that?

**Comment by DariaElagina** [comment]
We have as an addition type, but not as a keyword for manuscript, work, or narration unit

**Comment by PietroLiuzzo** [comment]
you can certainly use the same. as long as there is an authority file for it, it does not need to be specified for a purpose.

**Comment by PietroLiuzzo** [comment]
this seems to be closed already
