### ISSUE TITLE
Missing Emperors of Ethiopia

### ISSUE THREAD

**Issue by MargaretheJenner** [BetaMasaheft/Documentation#966]
I cannot find: 
Andreyas (https://en.wikipedia.org/wiki/Andreyas)

**Comment by thea-m** [comment]
here he is: PRS3790endreyas

**Comment by MargaretheJenner** [comment]
We have 4 differents versions of Eskender (https://en.wikipedia.org/wiki/Eskender).
Only PRS3874eskender contains useful information. 

Unless they are suposed to be different Eskenders, I suggest to only keep PRS3874eskender

**Comment by thea-m** [comment]
the seemingly empty records refer to other Eskenders, some do have minimal information in `<person>`. If you are curious, you can also click on "attestations" and see where in the project they have been used. We often create quite minimal person records, containing only a name and maybe a relation, particularly for persons mentioned in manuscripts about whom we simply know nothing else. Other records are inherited from the index of the Encyclopaedia Aethiopica and haven't yet been elaborated. So, in this particular case, the records should be kept, but please do again write issues if it seems to you that there are double records or something seems strange

**Comment by sologebre** [comment]
Definitely, please do!

**Comment by MargaretheJenner** [comment]
I cannot identify 
Yeshaq Iyasu (https://en.wikipedia.org/wiki/Yeshaq_Iyasu)

**Comment by thea-m** [comment]
I don't find him either. @sologebre ?

**Comment by MargaretheJenner** [comment]
I cannot identify : 
ʿAmdä Ṣǝyon (https://en.wikipedia.org/wiki/Amda_Seyon_(usurper))

**Comment by sologebre** [comment]
Yeshaq Iyasu (https://en.wikipedia.org/wiki/Yeshaq_Iyasu) was a rebel who declared himself king during the reign of ʾIyāsu I (1658-1706). So, he was not officially recognized an Emperor of Ethiopia. So, we have to crosscheck the wikidata information with conventional Ethiopian histriography.

**Comment by MargaretheJenner** [comment]
I cannot identify: 
Atse Iyasu
https://en.wikipedia.org/wiki/Atse_Iyasu

**Comment by sologebre** [comment]
Here is the id for ʾIyāsu III- PRS5618IyasuII, but the information provided in https://en.wikipedia.org/wiki/Atse_Iyasu is wrong.

**Comment by MargaretheJenner** [comment]
Is http://betamasaheft.eu/persons/PRS5637IyoasI/main 
https://en.wikipedia.org/wiki/Iyoas_II ?

**Comment by MargaretheJenner** [comment]
I cannot find Egwale Anbesa (https://en.wikipedia.org/wiki/Egwale_Anbesa)

**Comment by thea-m** [comment]
Thank you!
Yes, PRS5637IyoasI is https://en.wikipedia.org/wiki/Iyoas_II
https://en.wikipedia.org/wiki/Egwale_Anbesa is PRS3691egwalaA
We apparently have no record for Takla Haymanot of Gondar

**Comment by thea-m** [comment]
@MargaretheJenner maybe this can be closed and new issues be opened for new cases
