### ISSUE TITLE
visualization of extent

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#967]
would it be possible to have a line break on the app after each `<measure>` given in `<extent>`?
For example, in MNC001, there is:
```xml
    <measure unit="leaf">156</measure>
                           <measure unit="leaf" type="blank">2</measure>
                           <locus target="#1r #156v"/>
                           <measure unit="quire">19 (A + 18)</measure>
```
which is visualized as 

> 156 (leaf), 2 (leaf, blank): ff. 1r 156v 19 (A + 18) (quire).

It would also help already if a comma could be added after the locus values.

**Comment by PietroLiuzzo** [comment]
This is a mixed content element, so adding programmatically punctuation is at the risk of having then too much where this is not needed. I believe the easiest thing to do here is to add that comma.

take for example a ES manuscript as ESap017
```xml
<extent>Made of <measure unit="leaf">40.0</measure> folios, of which
                                                  <measure unit="leaf" type="blank"/> blank
                                                  1rv, 2rv, 40v, in
                                                  <measure unit="quire">6.0</measure> quires (A+5). 
                                                <dimensions type="outer">
                              <height unit="mm">195</height>
                              <width unit="mm">165</width>
                              <depth unit="mm">45</depth>
                           </dimensions>
                        </extent>
```
adding commas here would return a rather messy thing.

**Comment by thea-m** [comment]
Ah, I see. Thank you!
