### ISSUE TITLE
Syntaxe du codex relations

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#976]
I could find no record that has used Syntaxe du codex relations to express the history of the manuscript where the graph is shown on the app (for example IVorlov20 or BDLaethf11). Are they all wrongly encoded or are there other problems with the app as well?

**Comment by PietroLiuzzo** [comment]
it is broken.

**Comment by PietroLiuzzo** [comment]
it is now working again.
the sankey code from google charts needed to be updated in charts.xql
I also removed some dead dependencies from the javascript loaded in the head from apprest.xql
there was also still trace of the old sdc namespace, which I hope I have fixed, both in config.xql and in SdCtable.js and d3sparqlsettingsManuscripts.js
