### ISSUE TITLE
new rules for div[edition] and div[bibliography]

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#984]
Dear all,

yesterday Dorothea found out several records which contained bibl directly as child of div[@type='edition'] in some works.

today I am finding (but I am rather sure it is not the first time I see this, so apologies if I am repeating something) that locus is used inside div[@type=edition] 

While the first issue presented 16 cases, the second is more widespread.
http://betamasaheft.eu/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fmanuscripts%27%29%2F%2Ft%3Adiv%5B%40type%3D%27edition%27%5D%2F%2Ft%3Alocus

I think both these behaviours ought to be discouraged and avoided, the first because it has no point, the second because it confuses things: inside the transcription of a manuscripts there should be pb and cb elements, not a locus which points at them. But I might be missing the reason why locus has been used there.

I would be inclined to simply add a rule in the schema, so that you get a nice error message before you do any of these. but let me know if I am missing something.

**Comment by thea-m** [comment]
As far as I see it, you can add these rules. I have used locus in transcription out of habit without thinking much, I'll correct it. Just one question: If the text I transcribed doesn't start at the beginning of the page (often they are small excerpts given by the catalogues), how would I encode this? 
`<pb n="1r"><gap reason="ellipsis"/> my text starts here` ?
What about cases where we don't know whether it starts at the beginning of a page or not?

**Comment by PietroLiuzzo** [comment]
rules added to the schema (not live yet!)
The example is here a bit too vague for me, sorry. In general I would avoid trying to be specific about something I do not know, so, I would not use gap, I would just give the div, pb and cb which are certain and then copy the text where it belongs. The true statement is that it occurs after that page break.

**Comment by thea-m** [comment]
Thank you!

**Comment by thea-m** [comment]
Sorry for overenthusiastic closing... Here there is an example:
in BNFet117, how would I encode the excerpt given in the catalogue as being on 15v-16v (https://archive.org/details/manuscritsorient00bibl/page/138)? (LanguagesNoah in the record) A part from the fact that I don't whether the text begins directly after the page break on 15v, I have the information that it ends on 16v, but would not know where to insert the preceding pagebreaks. 
Should I instead develop the structure of the manuscript, add more nested msItems, include the locus there and then refer in the `<div>` to the corresponding msItem?

**Comment by PietroLiuzzo** [comment]
the wonders of imprecision... 
perhaps avoid the nesting of msItems which are not actually Textual Units, and refer to the excerpt with a locus from the actual msItem it is part of. yes, you can point to the id of a div and avoid al together to try and reproduce the pb, cb or div by folia description in the div[@type='edition']

**Comment by thea-m** [comment]
That's why I didn't create those msItems in the first place...the locus from the one it is part of is `from="1r"`, which is even more imprecise than the current locus indication in the div. Would I then write  a note in this msItem referring the excerpt's xml:id and with the more precise locus?

**Comment by PietroLiuzzo** [comment]
I am not sure if this can be closed @thea-m
