### ISSUE TITLE
list institutions in shelfmark list alphabetically

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#986]
hoping for a small possibility that this is not related to #536... would it be possible to list the institutions in this list
http://betamasaheft.eu/manuscripts/browse
alphabetically? It would really improve the user friendliness

**Comment by PietroLiuzzo** [comment]
good to know that that list at least is used... I will see if I can add tiny sort - table sort or similar to it. 
Please note that for the list to load I am printing the titles after load, i.e. you might be able to sort, but after that has finished loading.

**Comment by PietroLiuzzo** [comment]
since Institutions should not grow so steadily now that menestrel has been added, perhaps a static list of names for these lists would be preferable. run once, stored and used in the scripts instead of recalculating the name each time.

**Comment by PietroLiuzzo** [comment]
<img width="847" alt="schermata 2018-11-21 alle 09 37 19" src="https://user-images.githubusercontent.com/508012/48828846-19847a80-ed71-11e8-89f4-b90a8b8cf9ca.png">

**Comment by thea-m** [comment]
looks good, thank you!

**Comment by PietroLiuzzo** [comment]
Thanks for closing this, I am not yet done with all the consequences this has on the rest of the code.
