### ISSUE TITLE
bibliographic references for translations into different languages

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#999]
In the cases where translations of one work into several languages are available, this is sometimes encoded in a single `listBibl type="translation"`, simply listing each translation in one `<bibl>`, and sometimes in separate `listBibl type="translation"`, as in LIT3928Miracle:

```xml
    <listBibl type="translation" xml:lang="en">
               <bibl>
                  <ptr target="bm:Budge1933Miracles"/>
                  <citedRange unit="item">57a</citedRange>
                  <citedRange unit="page">210-212</citedRange>
               </bibl>
            </listBibl>
```

 ```xml
  <listBibl type="translation" xml:lang="de">
               <bibl>
                  <ptr target="bm:Hofmann1922Schlaferspiel"/>
               </bibl>
            </listBibl>
```

Are both ways fine or should we stick to one? The language indication in the latter is not visualized on the app (not sure if it would be really useful if it were).

**Comment by PietroLiuzzo** [comment]
that @xml:lang is neither about the language of the bibliographic entry or more in general the language of the list of bibliographic entries, if it is meant to mean the language of the translation I would be inclined to think it is simply wrong. especially so since I cannot find this in the guidelines anywhere.

**Comment by thea-m** [comment]
Neither can I. I assumed it indicated the language of the translation, but I don't really think that is very necessary information

**Comment by PietroLiuzzo** [comment]
there are more then 250 of these listBibl with a @xml:lang. rather painful. perhaps somebody could cime in to tell everyone what they intended doing?

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @DariaElagina @MassimoVilla

**Comment by PietroLiuzzo** [comment]
it does no harm, is only wrong, no need to fix, if we want to fix I will fix all in one go. but if it was done, there must have been a reason, and if there was a reason perhaps there is a purpose...

**Comment by PietroLiuzzo** [comment]
and these 250 with xml:lang are many more than the 84 without it. 
I have stubbed a miniparagraph about the fact that this is not necessary
https://github.com/BetaMasaheft/guidelines/pull/9
and I have changed the example in the guidelines

**Comment by thea-m** [comment]
Thank you! Most of those with xml:lang are anyway Miracles of Mary, which were probably copy pasted
Sorry, just to clear my confusion, where is it in the schema and guidelines? (I see your new paragraph, but nothing else and no changed example)

**Comment by PietroLiuzzo** [comment]
The example I changed is here, where the one with the xml:lang was substituted. is an example in the schema.
http://betamasaheft.eu/Guidelines/?id=listBibl

**Comment by thea-m** [comment]
thank you!
